### ISSUE TITLE
Broken positioning for one-tap links

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#1000]
## Bug Description

When adding a 1-tap link (aka element within `amp-story-cta-layer`), the absolute positioning is somehow broken and not based on the bottom 20% of the page.

This used to work (after it was once broken), but seems like it regressed again.

Only change that seems relevant is #916.

## Expected Behaviour

1-tap links should be positioned correctly on the page.

## Steps to Reproduce

Add text element with link in the bottom of the (second) page and check the frontend output.

The element is nowhere to be seen.

## Screenshots

Editor:

<img width="661" alt="Screenshot 2020-04-03 at 10 40 55" src="https://user-images.githubusercontent.com/841956/78341280-b37c4a00-7597-11ea-8028-9b6c8bef4ab8.png">

Frontend:

<img width="1333" alt="Screenshot 2020-04-03 at 10 41 12" src="https://user-images.githubusercontent.com/841956/78341382-e6bed900-7597-11ea-8286-1bff9b28581a.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
FI: In my testing, the background (fill) showed up as expected, however, the text not.
See the editor:
<img width="359" alt="Screenshot 2020-04-03 at 16 58 33" src="https://user-images.githubusercontent.com/3294597/78374921-5f3f8d00-75cc-11ea-96e5-4d868736e3aa.png">

FE:
<img width="303" alt="Screenshot 2020-04-03 at 16 58 53" src="https://user-images.githubusercontent.com/3294597/78374958-6a92b880-75cc-11ea-8437-ff7ee5397406.png">

**Comment by barklund** [comment]
@wassgha are you actively working on this one?

(also congrats to @swissspidy for creating #1000   🎉🎉)

**Comment by wassgha** [comment]
Yes! Will have a PR for it today
