### ISSUE TITLE
Video poster images disappearing

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#1001]
## Bug Description

The video poster image doesn't seem to persist.

## Expected Behaviour

Once set, the poster image should stay

## Steps to Reproduce

1. Upload video by dragging it onto the page, maybe make it a background
2. After upload is finished, see poster image appearing in the design panel
3. After a short time, the poster image disappears again

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Perhaps this was fixed by #894?

**Comment by jauyong** [comment]
Marking as p0 for tracking purposes since this was already worked on by Jonny and Marcin
