### ISSUE TITLE
Media showing image that isn't shown in WP Library

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#1005]
## Bug Description

After deleting all the images from the Library, one image still shows up in the Editor Media Library.

## Expected Behaviour

WP library and Editor library should be in sync.

## Steps to Reproduce

Not sure how easily it is reproducible, however, I removed all the images from Media Library, went to the editor and saw one still showing up.

## Screenshots

<img width="887" alt="Screenshot 2020-04-03 at 12 04 12" src="https://user-images.githubusercontent.com/3294597/78349126-643c1680-75a3-11ea-94b2-d470c2c5b7ba.png">
<img width="361" alt="Screenshot 2020-04-03 at 12 05 34" src="https://user-images.githubusercontent.com/3294597/78349151-71590580-75a3-11ea-9efc-1d033056bdda.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@spacedmonkey Any thoughts on why this might be happening? Are there any images we're hiding from the library that might show up in the editor? 

cc @swissspidy

**Comment by swissspidy** [comment]
> Are there any images we're hiding from the library that might show up in the editor?

We hide the video poster images. But they should be hidden everywhere.

**Comment by swissspidy** [comment]
Can't reproduce this still. Feel free to reopen if this changes.
