### ISSUE TITLE
Bold not displayed right away while in edit mode

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#1007]
## Bug Description

Toggling bold while the Text is in edit mode doesn't have an instant effect while the italic and underline have. 

After exiting the edit mode, bold is shown.

## Expected Behaviour

Bold should take effect right away in edit mode, the same way as italic and underline do, otherwise, it feels broken.

## Steps to Reproduce

1. Add Text
2. Go to edit mode
3. Toggle Bold.

## Screenshots
![bold](https://user-images.githubusercontent.com/3294597/78363431-036d0800-75bc-11ea-8f25-4401120e86f3.gif)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Fixed by #992? Se #922.

**Comment by miina** [comment]
992 seems to be related to output, this issue is just the bold effect not showing right away when toggling in the editor. Will try to create a gif.

Edit: Added under screenshots!

**Comment by spacedmonkey** [comment]
I noticed that if you make some bold, it can remain bolded and I cant unbold it.

**Comment by obetomuniz** [comment]
Indeed, it's not related to #922 . It's not working because we only set the `bold` boolean state in the [initial state](https://github.com/google/web-stories-wp/blob/master/assets/src/edit-story/elements/text/edit.js#L147-L152) without any further tracker of changes.

**Comment by barklund** [comment]
This will be fixed by major rewrite to be done in #413.

**Comment by miina** [comment]
Will assign this to @barklund and move to "In Progress" as it'll get fixed by #1323 (for clarity on the board)
