### ISSUE TITLE
Text: Font family change doesn't (always) recalculate the text size

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#1008]
## Bug Description

Selecting a new font family, the text size doesn't always adjust.

## Expected Behaviour

The text element size should adjust after changing the font.

## Steps to Reproduce

1. Add a Text element
2. Enter edit mode
3. Change font family so that the text would increase enough to create a new row
4. See the text element not resizing.

## Screenshots

![font-change](https://user-images.githubusercontent.com/3294597/78357077-10d0c500-75b1-11ea-98ff-1fd8575202ab.gif)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by dvoytenko** [comment]
This is most likely a race condition on font loading. If font is not ready, the operation would have to be repeated. See https://jsbin.com/lidirog/7/edit?html,js,output.

To make this easier, the best option would be to delay setting the new font family util it has been loaded with document.fonts.load() as in the example above. Most of browsers already support this API, but if some browser does not, we'd just have to keep the racy behavior there.

And one more critical detail: we need to set `fontDisplay: 'block'` in [this style map](https://github.com/google/web-stories-wp/blob/60a7d8c9431ea3feaa9a851b53b13f5b0362d6dc/assets/src/edit-story/utils/textMeasurements.js#L28).

**Comment by dvoytenko** [comment]
To make this easier, the best option would be to delay setting the new font family util it has been loaded with `document.fonts.load()` as in [the example](https://jsbin.com/lidirog/7/edit?html,js,output). Most of browsers already support this API, but if some browser does not, we'd just have to keep the racy behavior there.

**Comment by swissspidy** [comment]
Related: #831
