### ISSUE TITLE
Image inserted rotated and stretched

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#1009]
## Bug Description

Sometimes (at least once ;) ) images are inserted to the page incorrectly.

## Expected Behaviour
An image should be inserted to the page with correct ratio and correct direction.

## Steps to Reproduce

1. Take a photo with phone in portrait mode.
2. Upload that photo to Stories
3. Add the image to a Story.
4. See the reverted image.

## Screenshots

Compare the original and the inserted image -- inserted rotated + stretched.

![bug-stretched](https://user-images.githubusercontent.com/3294597/78357248-6016f580-75b1-11ea-9f72-8f375661c27e.gif)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Note:
By now, this has happened with more than one image.

**Comment by miina** [comment]
More notes:
- The same images that get inserted reversed, these images don't seem to get displayed on the FE either and seem to "disappear" from the editor upon refresh -- just the shape frame is visible

**Comment by o-fernandez** [comment]
@barklund @diegovar is this a Media or Workspace pod issue?

**Comment by barklund** [comment]
I think media, as I think it's an EXIF issue with the image itself.

**Comment by o-fernandez** [comment]
@diegovar mind taking a look?

**Comment by diegovar** [comment]
I can't reproduce this. I took a photo with my phone in portrait mode, uploaded it and added it to the story. It appeared in the right direction at all times. Was it fixed at some point?

**Comment by miina** [comment]
Closing as unable to reproduce.
