### ISSUE TITLE
The user should be able to rotate (change the direction) of a Fill or Background image

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#1010]
## Feature Description

If the image in the Media Library is on the side / incorrect direction, it's not possible to change that for a background/Fill image.

Note: Undo-Redo arrows were the ones that caught the eye when automatically started looking for a place to rotate the image.

<img width="387" alt="how_to-rotate" src="https://user-images.githubusercontent.com/3294597/78357498-dfa4c480-75b1-11ea-877a-858cc51a49ce.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Even though WordPress should really fix the image orientation handling, adding an option to rotate an image by 90deg makes sense to me.

**Comment by dvoytenko** [comment]
I think any rotation angle could be made to work here. But we initially erred on the side that it's not what a background image would want to do. So, I think this should go to @pbakaus and @samitron7 to approve and prioritize.

**Comment by pbakaus** [comment]
I'll let @samitron7 chime in too, but this thread convinced me that we should get rotation for background in. I think we can separate it into two tickets:

1. Allow rotation of masked object in edit mode in design panel (P0)
2. Allow rotation of masked object using direct manipulation in canvas (P1)

Important, I think if we solve this for bg, it should ideally  be solved for all masked elements. So for 1), if you enter edit mode, the rotation field in the design panel (and honestly probably position, scale etc. as well) should show the values for the masked element, and not the outer element. If you click into them to modify, the canvas needs to stay in edit mode, etc.

All of that to show that there's definitely some work here, with some refactor/generalization requirements.

@samitron7 I'm actually wondering if in edit mode we generally only show stuff in the design panel related to the masked element, which makes it *super obvious* to the user to understand what they're modifying.

**Comment by samitron7** [comment]
This really depends on how much "editing" of photos we would like users to do on the phone. There has been some studies to suggest that most people have created their assets elsewhere but for those that take landscape photo and get what Mina is illustrating, I would prefer to keep things simple and handle it with what Pascal is suggesting "fix the image orientation handling" ie - if we can auto rotate this for the user and just give an option to do landscape/portrait. Full rotation adds a lot of other headaches for us at this point and we can revisit later.

**Comment by pbakaus** [comment]
I'll close this for now, due to Sam's comment and as there's now an easy workaround (foreground rotated video or image), due to the new way we handle the safe zone / bleed.
