### ISSUE TITLE
Image resizing not working when the origin point is in the top-left corner

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#1011]
## Bug Description

When the origin of the resizing is top-left corner AND the image is rotated 90 degrees, resizing fails and the image "disappears".

Similar issues occur with text boxes and many different rotations (when rotated more than 90 degrees from 0 in either direction)

## Expected Behaviour
Resizing should work despite of the rotation / start position

## Steps to Reproduce

1. Add an image
2. Assign rotation 90 degrees
3. Position it to the top-left corner
4. Resize from the bottom-right corner as it is visible currently without considering rotation
5. See the odd stuff happening.

## Screenshots
![image-lost](https://user-images.githubusercontent.com/3294597/78357929-9d2fb780-75b2-11ea-8230-0f9dd0d2ff89.gif)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## QA Instructions
1. Add an image
2. Set rotation to 90 degrees
3. Now drag the image to the upper left corner
4. Resize it from the corners
5. Verify the resizing works as expected and that the image doesn't "jump around".

**Comment by miina** [comment]
After spending some time debugging and making clear under which conditions the resizing fails, recreated the situation in CodeSandbox and added an issue to Moveable repo instead: https://github.com/daybrush/moveable/issues/251

For information, the bug happens when `keepRatio` is `true` and snapping is enabled -- also happens only when the element is in one of the snapping points, e.g. in the left edge of the Page (doesn't have to be a corner).

Will wait for information from Moveable and then see how to proceed.

**Comment by miina** [comment]
@barklund FI: I'm resizing this to 1 since once it's fixed in Moveable, all we need to do is update the module.

Let me know if you have any objections.

**Comment by csossi** [comment]
Verified in QA (Master)

**Comment by samitron7** [comment]
UAT - looks good. Closing ticket
