### ISSUE TITLE
Background Video difference between the editor and FE

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#1014]
## Bug Description

The video that looks OK in the editor seems to be scaled in FE.

## Expected Behaviour

Video should look similar in the editor and FE

## Steps to Reproduce

1. Add a video
2. Set it as background
3. Save
4. See the difference between FE and editor.

## Screenshots
Editor:
![editor](https://user-images.githubusercontent.com/3294597/78361734-2944dd80-75b9-11ea-9f31-aa4e92111ab9.gif)

FE:
![FE](https://user-images.githubusercontent.com/3294597/78361744-2e099180-75b9-11ea-968e-4ad5eeb6ff87.gif)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Could you add steps to reproduce? Is it a background video? Or fill?

**Comment by miina** [comment]
@swissspidy Sorry for the lack of information :)

Added more information and steps now. Didn't add the steps before since I wasn't certain if this happens with every video and if not, which ones.

**Comment by miina** [comment]
Additional information: this happens when the video is taken with a mobile (perhaps related somehow: https://github.com/google/web-stories-wp/pull/1102)

**Comment by o-fernandez** [comment]
@barklund @diegovar this one as well - media or workspace issue? labeled as media i/o at the moment.

**Comment by miina** [comment]
Tested with the same video and with some other videos and am not able to reproduce it anymore. Closing as fixed.
