### ISSUE TITLE
Delete poster images when deleting videos

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#1020]
## Feature Description

When uploading a video, the poster image is generated (with `web_stories_is_poster` meta key so it's hidden) and set as the video's featured image.

When a user now deletes a video in the media library, we need to ensure the poster (the video's featured image) is deleted as well. Otherwise there is orphaned data in the database that can't really be deleted by the user (because posters are hidden).

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by diegovar** [comment]
Is this work that happens entirely on the PHP side? @swissspidy

**Comment by swissspidy** [comment]
@diegovar yes. See #1783
