### ISSUE TITLE
Selecting an element from Layers Panel and clicking Delete not working

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#1021]
## Bug Description

When selecting an element via Layers Panel and then clicking the Delete button, nothing happens.

## Expected Behaviour
The element should be deleted after being selected via the Layers Panel.

## Steps to Reproduce
1. Add an element
2. Unselect it
3. Select it via the Layers Panel, see the element getting the selection frame active.
4. Hit "Delete"
5. Nothing happens

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by dvoytenko** [comment]
Related to #738. But I'd not say it's a dupe since the implementation can reasonably well decide to just use the same shortcuts here directly.
