### ISSUE TITLE
Use Mousetrap for useKeyboardHandlers

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#1022]
## Feature Description

We should address this todo in `useKeyboardHandlers`:

https://github.com/google/web-stories-wp/blob/e402de46aa0783efd0626ee1264ea169a6ce3c04/assets/src/edit-story/components/panels/panel/useKeyboardHandlers.js#L26-L41

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment]
@pbakaus @swissspidy I'm not entirely sure what this does, can you please elaborate or help prioritize this?

I do see it's an enhancement so maybe p2?

**Comment by swissspidy** [comment]
@jauyong Just some code refactoring, addressing an open `todo` comment in the code base. Nothing urgent, so P2 is fine.
