### ISSUE TITLE
Video Play icon shown when dragging

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#1026]
## Bug Description

It looks odd when the playback icon is shown while dragging a video around. Especially when dragging off canvas

## Expected Behaviour

Play icon should be hidden while dragging

## Steps to Reproduce

Upload video and drag it around

## Screenshots

<img width="456" alt="Screenshot 2020-04-03 at 15 00 36" src="https://user-images.githubusercontent.com/841956/78370612-294bda00-75c7-11ea-9b43-6c32c5498c6a.png">

<img width="568" alt="Screenshot 2020-04-03 at 15 00 44" src="https://user-images.githubusercontent.com/841956/78370621-2cdf6100-75c7-11ea-9680-6e0364bb8efc.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by dvoytenko** [comment]
/cc @pbakaus @merapi @wassgha 

Moving icon to display layer will help with this as well. Although I'm not sure if we should consider dragging to be hover for the purposes of the icon display.

**Comment by pbakaus** [comment]
The icon should not show during drag.

**Comment by merapi** [comment]
Possibly related #792

**Comment by diegovar** [comment]
Should playback stop when the element starts to be dragged?

**Comment by swissspidy** [comment]
Hmm probably, but perhaps we could split that up into its own tickt?

**Comment by merapi** [comment]
Agreed with Wassim that #1948 will cover it.

**Comment by csossi** [comment]
Verified in QA

**Comment by swissspidy** [comment]
Verified that this has been fixed 👍
