### ISSUE TITLE
Add Context to Failure to Save Error Message

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1033]
## Feature Description

This is a followup to [this comment.](https://github.com/google/web-stories-wp/pull/888#issuecomment-607056978) on #888 

As a user I'd like to know why my story failed to save.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. When a story fails to save, the user should be given sufficient info why (UX needed)

**Comment by samitron7** [comment]
@o-fernandez Do we have a list of reasons why a story would fail to save so I can understand how to make the message helpful.

**Comment by o-fernandez** [comment]
@barklund do you know if such a list exists (see @samitron7 's question)

**Comment by swissspidy** [comment]
Pretty much this: https://github.com/google/web-stories-wp/issues/4790#issuecomment-714530710

**Comment by samitron7** [comment]
Can we close this ticket since it's already being addressed in [4790](https://github.com/google/web-stories-wp/issues/4790#issuecomment-714530710) (ticket Pascal pointed to).

**Comment by swissspidy** [comment]
Hmm not sure, it's not exactly the same.

#4790 is about detecting potential issues before the user starts interacting with the editor/dashboard. It's possible that there are no detected issues at that point.

This ticket is about improving the error messages once interacting with the editor and saving stories etc. It's possible that there are issues with saving, even though no potential issues were detected before.

**Comment by hugelillian** [comment]
@swissspidy Hello! What action should the user take when there's a failure to save?

**Comment by swissspidy** [comment]
> What action should the user take when there's a failure to save?

Good question!

It really depends on the failure context (which this ticket tries to address). Failure happens either because of a client-side issue (e.g. user is offline) or a server-side issue (e.g. error on server, some security mechanism blocking saving.

If the user is offline they should obviously check their internet connection.

For a server-side issue they could try saving again. But if it's a persistent issue that doesn't help either and they would need to contact support to get some assistance.

---

Related: to avoid content loss in both cases, we should try to save their content locally in the browser, see #3842

**Comment by hugelillian** [comment]
Hi @swissspidy -- thank you! This is great.  

Here's an option that could potentially cover both scenarios. What do you think?:

Universal error message option: Story failed to save. Check your internet connecting or try saving again. For more assistance, visit the [support page](https://wordpress.org/support/plugin/web-stories/).


If we want to explain more about why the Story failed to save, we can have two different error messages for each of the scenarios you outlined. If the universal option is possible, I think we should go for that one for simplicity's sake. But if it isn't, will write some more message options here! LMK what you think. Thank you!

**Comment by hugelillian** [comment]
hi @swissspidy -- just following up :) lmk what you think.

**Comment by swissspidy** [comment]
I like the universal option, I think it could work well. It's probably just a tad long for a snackbar message.

**Comment by hugelillian** [comment]
Hi @swissspidy -- thank you; great. 

Shortened revision: Story failed to save. Check your connection or save again. For more help, visit the support page.
