### ISSUE TITLE
Users should confirm when try to delete a story page not saved

### ISSUE THREAD

**Issue by obetomuniz** [GoogleForCreators/web-stories-wp#1038]
## Feature Description

Users should confirm before delete a story page not saved to avoid delete a page under creation. 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Can't users just hit undo if they accidentally delete a single page?

**Comment by jauyong** [comment]
Yes, users are able to undo an accidental page delete.
@samitron7 do you think a confirmation is warranted for deleting a page?

**Comment by o-fernandez** [comment]
Given that the users can easily undo, I will close this issue.
