### ISSUE TITLE
Can't delete via keyboard recently added text

### ISSUE THREAD

**Issue by obetomuniz** [GoogleForCreators/web-stories-wp#1039]
## Bug Description

Texts are not allowing delete once you add them on the canvas, only after removing its focus and focusing again.

## Expected Behaviour

Any element should allow being deleted when it is focused.

## Steps to Reproduce

- Add a Text in the Workspace
- Press <kbd>delete</kbd> key on the keyboard

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Likely related: #1021

**Comment by dvoytenko** [comment]
Duplicated of #738.
