### ISSUE TITLE
Rotated image configured as background doesn't stay rotated

### ISSUE THREAD

**Issue by obetomuniz** [GoogleForCreators/web-stories-wp#1040]
## Bug Description

Setting a rotated image as the background doesn't stay rotated

## Expected Behaviour

Rotated elements should stay rotated when configured as background

## Steps to Reproduce

- Select an Image from media in the Workspace
- Rotate the image
- Select the option "Set as background"
---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Duplicate of #1010

**Comment by obetomuniz** [comment]
100%. Thanks @miina
