### ISSUE TITLE
Color Eyedropper is not working on Color Picker

### ISSUE THREAD

**Issue by obetomuniz** [GoogleForCreators/web-stories-wp#1041]
## Bug Description

Color Eyedropper is not working on Color Picker. It seems obsolete.

## Expected Behaviour

If Color Eyedropper is obsolete, it should be removed. If Color Eyedropper has bugs, it should be fixed to work as expected.

## Steps to Reproduce

- Add a Text element in the story
- Select Text color input
- Try to use Color Eyedropper icon

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Not implemented yet and thus disabled, see #262

**Comment by jauyong** [comment]
@pbakaus do you think it's worth the effort to remove the eyedropper for Alpha?

**Comment by pbakaus** [comment]
nope. Disabled is fine.

**Comment by jauyong** [comment]
marking as p2 to track adding the eyedropper functionality.

**Comment by swissspidy** [comment]
@jauyong not a duplicate?

**Comment by jauyong** [comment]
Yes #262 thank you.
