### ISSUE TITLE
Text color input value is being applied to Textbox color input sometimes

### ISSUE THREAD

**Issue by obetomuniz** [GoogleForCreators/web-stories-wp#1042]
## Bug Description

If you change the Text color input value and click immediately in the Textbox color input, it replaces the color in the Textbox color input by the color used in the Text color input

## Expected Behaviour

When you select input color, it should not be affected by external values, it should display the current color.

## Steps to Reproduce

- Add a Text Element
- Change its Text color
- Click in the Textbox input color

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Noticed that too! Would be great to fix.

**Comment by jauyong** [comment]
Related to #1054 which is regarding the highlight colour

**Comment by obetomuniz** [comment]
Fixed by #1187
