### ISSUE TITLE
export 'createInterpolateElement' was not found in '@wordpress/element'

### ISSUE THREAD

**Issue by wassgha** [GoogleForCreators/web-stories-wp#1048]
## Bug Description

Seeing `export 'createInterpolateElement' was not found in '@wordpress/element` in the console

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Was this after a fresh npm install?

Asking because of #998

**Comment by wassgha** [comment]
False alarm
