### ISSUE TITLE
Text Colour Inheriting from Highlight Colour

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1054]
## Bug Description

Switching between highlight color to text color makes the text color take the highlight color

## Expected Behaviour

When clicking on a colour picker, it shouldn't auto grab another colour

## Steps to Reproduce

1. Add a text box
2. Add a highlight colour
3. While still on or reopen the highlight colour picker and click on the text colour
4. notice the text now auto switches to the highlight colour

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Possible duplicate of #1042

**Comment by obetomuniz** [comment]
Fixed by #1187
