### ISSUE TITLE
Unable to Deselect

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1057]
## Bug Description

Can’t remove from selection using shift + click (although can add with shift + click)

## Expected Behaviour

shift + click on an already selected element, should unselect it

## Steps to Reproduce

1. Add a few elements to the page
2. Select them all with 
3. Try to deselect one with Shift + click

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Closing as this is working now.
