### ISSUE TITLE
Safe Zone is Cropping Shapes

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1058]
## Bug Description

Shapes get cropped by safe zone.

## Expected Behaviour

The shapes should not get cropped in the safe zone

## Steps to Reproduce

1. Add a shape that overlaps the safe zone

## Screenshots

![image](https://user-images.githubusercontent.com/5874851/78502235-13a4f480-772e-11ea-8a0e-102c2929ecd9.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by pbakaus** [comment]
This is not something that can be easily addressed, it's WAI. But I do have a plan that will work to mitigate some of this. Stay tuned.

**Comment by pbakaus** [comment]
OK, I wrote a design doc, [check it out](https://docs.google.com/document/d/1ZF31jSP8BhhLU5Z4Amjfo45UkFUWMEBOTVziY4vursA/edit#). /cc @dvoytenko @samitron7 @swissspidy

**Comment by jauyong** [comment]
no longer required, fixed.
