### ISSUE TITLE
Media gets unselected after clicking "Remove as background"

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#1063]
## Bug Description

When clicking "Remove as background", the media element gets unselected.

## Expected Behaviour

The media element should stay selected.

## Steps to Reproduce

1. Add image
2. Set as background
3. Remove as background
4. See the element being unselected.

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment]
@miina @samitron7 it seems like the image is in focus / selected after removing as bg.
![1063](https://user-images.githubusercontent.com/5874851/82394577-6d7c2800-9a17-11ea-8cb0-dcc6f015fb02.gif)

**Comment by miina** [comment]
@jauyong Looks like this got fixed within #1798. Closing as fixed.
