### ISSUE TITLE
Keyboard shortcuts do not work when multiple elements selected

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#1070]
## Feature Description
When multiple elements are selected, keyboard shortcut do not work. So arrow keys to move and delete, should move or remove all elements elements.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
This works as expected when testing. Perhaps the real issue here is these shortcuts not working globally? E.g. if the focus gets out of the Page. Related: https://github.com/google/web-stories-wp/issues/1781

**Comment by carloskelly13** [comment]
I think I have determined that the bug is if you start the multi selection outside the canvas on a fresh page load it will not correctly capture the keyboard events. If you start the selection inside the canvas it will and all subsequent selections will work.
