### ISSUE TITLE
No media displaying if PDF in WP media library

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#1071]
## Bug Description

No media displaying if PDF in WP media library

## Expected Behaviour

Media is displayed

## Steps to Reproduce

- Go to media in left hard sidebar
- Upload a PDF.
- Create new story.

## Screenshots
![Screenshot from 2020-04-06 16-10-52](https://user-images.githubusercontent.com/237508/78574123-788d4700-7821-11ea-93e7-cdff989c133d.png)

**Comment by merapi** [comment]
Good catch!
