### ISSUE TITLE
Story Preview should save story first

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#1072]
## Feature Description

If a create a new story with a lot of elements and click on "Preview", I want to see my new story on the frontend right away, without having to first save the story.

Right now, if you preview a new story without saving it first, you'll get a 404 on the frontend.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment]
@swissspidy @pbakaus should we just add this to the #221 when we work on auto-save in the future? Technically there is a workaround by manually pressing save so not a p0 and we can handle this later? So I'll make this a p1 but should I merge with 221 or keep this separate?

**Comment by swissspidy** [comment]
P1 makes sense.

I'd keep this separate from #221 as it might not be a small task to implement this (from experience with Gutenberg). #221 is big enough as it is already.

**Comment by pbakaus** [comment]
yep agree with @swissspidy

**Comment by pbakaus** [comment]
Actually, I've changed my mind. This has come up too many times in the fish food for it to be a P1. We need to nip this in the bud ASAP. I've asked @dvoytenko to take a look, but let me know if there's a better person to look at this @swissspidy.

**Comment by swissspidy** [comment]
WFM 👍 

@dvoytenko If it helps, this is how Gutenberg does it: https://github.com/WordPress/gutenberg/blob/61cbfa5f6f857e83e41781eb6db2c47e5ff4a4d1/packages/editor/src/components/post-preview-button/index.js

And some context behind the technical decision: https://github.com/WordPress/gutenberg/issues/3087#issuecomment-338213565
