### ISSUE TITLE
Modals and popups should always be on top of all other layers

### ISSUE THREAD

**Issue by merapi** [GoogleForCreators/web-stories-wp#1082]
## Bug Description

Link overlay is stacked on top of Modal.

Note that this also applies to the (external non-React) media selector that opens when pressing "upload" in media library.

## Expected Behaviour

Link overlay shouldn't display on top of Modal.

## Steps to Reproduce

1. Click on the element with Link
2. Trigger any action that will display Modal (e.g. (i) icon for Link)

## Screenshots

![image](https://user-images.githubusercontent.com/21036224/78677492-18ada380-78e8-11ea-9b64-381dfde42445.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## QA Instructions
1. Add a link to any element and select it (link popup should be visible).
2. Click Upload to open "Upload to Story" (WP Uploader).
3. Verify that link popup is under the Upload dialog (is not obstructing the view).

**Comment by jauyong** [comment]
@merapi I don't quite understand what the issue is here. Can you please add some details or msg me on slack.

**Comment by swissspidy** [comment]
@jauyong Do you see the "Wirtualna Polska" tooltip in the second screenshot? This comes from the element on the page and should definitely not overlay the "How to apply a link" dialog.

**Comment by merapi** [comment]
@jauyong screenshots updated.

**Comment by dvoytenko** [comment]
I think the resolution here is that the dialogs should always layer on top of everything else (except for popup menus maybe).

**Comment by jauyong** [comment]
@swissspidy @merapi 
Isn't this issue dependent on how the author lays out the elements on the page? What if there are elements surrounding the element with a link? In that case the link toolip will have to overlay on top of what's around it, no?

![image](https://user-images.githubusercontent.com/5874851/78815191-e65e7d80-799d-11ea-8b98-d7196fa0f54b.png)

![image](https://user-images.githubusercontent.com/5874851/78815215-ef4f4f00-799d-11ea-9ef4-3bf42d98121a.png)


Tagging @samitron7.

**Comment by swissspidy** [comment]
> What if there are elements surrounding the element with a link? In that case the link toolip will have to overlay on top of what's around it, no?

Yes, but I don't think that's an issue here..? 🤔

The report is explicitly about the tooltip interfering with the help dialog - not about other elements interfering the tooltip.

@merapi correct me if I'm wrong

**Comment by merapi** [comment]
Right, it was too generic, just changed the title, the only element that I found is the Modal. @jauyong @swissspidy

**Comment by swissspidy** [comment]
There's also the media modal interfering here. See #1969

**Comment by barklund** [comment]
@wassgha, if you're actively working on this, please move to "in progress" (and give an estimate on remaining effort), thanks!

**Comment by swissspidy** [comment]
This needs QA

**Comment by csossi** [comment]
Verified in QA

**Comment by samitron7** [comment]
Just noting that the modal for the link is no longer valid since we removed the 1 tap links. I tested the media modal and that seems to work fine but that's not this ticket so unsure what I'm suppose to verify here? @barklund can you let me know before I move to done.

**Comment by barklund** [comment]
@merapi, can you assist here?

**Comment by swissspidy** [comment]
Reading through the issue and #2045, this seems to affect things like:

* Edit Media dialog
* Delete Media dialog
* Calendar popup in document panel
* Color picker popup in document panel

When opening the WordPress media modal, those should all be behind that.

**Comment by wassgha** [comment]
@csossi can we please verify QA fo these use cases?

**Comment by merapi** [comment]
@samitron7 Since "Link indicator" PR is not yet merged - we have them on Staging, I think we want to verify here that the issue in question was fixed (it might fix other places than link indicator popup that will be soon removed).

**Comment by samitron7** [comment]
Does @csossi need to verify for those use cases ?

**Comment by o-fernandez** [comment]
I don't actually know how to do UAT on this issue. Can someone help me understand what was fixed? The thread isn't clear, and the original ticket doesn't have AC/QA Guidelines.

**Comment by swissspidy** [comment]
@merapi @wassgha could one of you provide up-to-date screenshots & testing instructions for UAT?

**Comment by merapi** [comment]
@csossi We don't have a lot of popups right now, but one of the ways you can test it is:

1. Add a link to any element and select it (link popup should be visible).
2. Click Upload to open "Upload to Story" (WP Uploader).
3. Verify that link popup is under the Upload dialog (is not obstructing the view).

**Comment by swissspidy** [comment]
Wait, I thought this already went through QA?

**Comment by merapi** [comment]
Oh, right. 
So since @samitron7 already "tested the media modal and that seems to work fine" - we should move it forward, right?

**Comment by swissspidy** [comment]
Iff that's the only real case affected by this nowadays, yes.
