### ISSUE TITLE
CMD + Click to Select

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1084]
## Bug Description

CMD+Click does not create a multi-selection

## Expected Behaviour

CMD+Click should work as CMD+Shift does now

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by dvoytenko** [comment]
Hmm. IMHO cmd+click for multiselection is atypical and likely dangerous. We have all these functions for cmd and drag which could conflict.

**Comment by pbakaus** [comment]
I'll push back here - every file or list manager universally uses CRTL/CMD+click to say "add this element to the selection", whereas shift stands for "add everything to the selection between the current selected element and the one you clicked".

We can educate people to use shift of course, but I want to monitor users for a while here..I immediately tried to use CMD and was frustrated and didn't do anything.

**Comment by dvoytenko** [comment]
@pbakaus that's true for the file managers. But what about other wyswyg editors? The concept of "select from here to there" is a bit inapplicable to layered elements.

**Comment by pbakaus** [comment]
@dvoytenko fair enough. I think you convinced me. I also just checked Figma, and they're doing only shift+click for multi-selection. Closing this for now!
