### ISSUE TITLE
Auto advancement not working when there are images

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1085]
## Bug Description

Auto advancement is not working

## Expected Behaviour

Page should auto advance per story / page settings

## Steps to Reproduce

Preview a story with multiple pages

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Pretty certain this was fixed by #1025.

**Comment by barklund** [comment]
[This story](https://stories-new-wordpress-amp.pantheonsite.io/wp-admin/post.php?post=1283&action=edit) is set to 4s auto-advancement, but [the rendered story](https://stories-new-wordpress-amp.pantheonsite.io/stories/corgi-puppies/?preview=true) doesn't auto-advance.
