### ISSUE TITLE
Rotate Background

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1086]
## Feature Description

As an editor I'd like to be able to rotate background media

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. I am able to rotate background media

**Comment by swissspidy** [comment]
@jauyong Duplicate of #1010?

**Comment by jauyong** [comment]
Pascal is correct. Closing this.
