### ISSUE TITLE
Element Blocking Next/Previous Buttons 

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1088]
## Bug Description

When an element is so large that it overlaps with the next or previous page buttons in the editor, you are not able to use those buttons.

When there’s an oversized element on top of the page controls, they become impossible to click as well.

## Expected Behaviour

I should be able to navigate pages even if an element expands over this buttons since it is off the page.

I should be able to click on those button even if an element is covering them.

## Steps to Reproduce

1. Add an element to the page
2. stretch it so it is over the next or previous (or both) buttons
3. try to navigate through pages with the buttons

1. Add an element to the page
2. increase the size so that it expands over the page controls
3. try to use the create new page button

## Screenshots

![image](https://user-images.githubusercontent.com/5874851/78717128-1fd7b000-78ee-11ea-900f-79e5fa899f20.png)

![image](https://user-images.githubusercontent.com/5874851/78502034-ef94e380-772c-11ea-9f4e-28b6ef5419b5.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by dvoytenko** [comment]
The same is probably the case with page menu on the bottom. It means that the nav layer should be brought up. But one question here we need resolve is how that layer will play with lasso selection.

**Comment by swissspidy** [comment]
Yep, the same is the case there: #1055.

**Comment by swissspidy** [comment]
Let‘s dedupe this with #1119
