### ISSUE TITLE
Missing Undo Actions

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1089]
## Bug Description

1. Cannot Undo Adding a page
2. Cannot undo masking with an image

## Expected Behaviour

page add should be undone. 

## Steps to Reproduce

1. Add a page
2. press undo
3. nothing happens. 

1. place a shape on the page
2. Mask an image on it.
3. press undo

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
Part 1 should have been solved by #1191.

Part 2 doesn't appear to be an issue anymore, but not sure what might have fixed it.

Please confirm if still an issue, @jauyong.

**Comment by jauyong** [comment]
confirmed, both of these have been fixed.
