### ISSUE TITLE
Instant upload preview not working

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#1100]
## Bug Description

Neither the drop into media library or the drop into canvas seem to show a preview in my testing. This was working and has since broken. 

## Expected Behaviour

When an video file is dropped into the editor, a preview of it should be shown in an element. 
When an video file is dropped into the media library a progress bar should be shown. 

## Steps to Reproduce

See videos

## Screenshots

https://youtu.be/RfQxvsqSWok
https://youtu.be/yNSzCDhjr2k

**Comment by jauyong** [comment]
Not able to replicate on staging. Possibly because my test file was much smaller or your local is much slower?

**Comment by merapi** [comment]
@spacedmonkey Can you provide OS/browser info?

**Comment by spacedmonkey** [comment]
Can no replicate.
