### ISSUE TITLE
Empty lines in text fields cause extra line breaks

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1108]
## Bug Description

Empty lines in text fields receive extra line breaks in both the editor and in the rendered story.

Technical details: We already use `white-space: pre-wrap`, but if there are empty lines in the output, both line breaks (`\n`) and HTML breaks (`<br />`) are inserted into the text content. Removing the `<br />` results in proper layout.

## Expected Behaviour

Manually entered line breaks should not cause extra line breaks beyond those entered.

## Steps to Reproduce

1. Create a text field
1. Click to edit it
1. Enter something on line 1, make two newlines and enter something on line 3 (leaving line 2 empty)
1. See the resulting text field having at least 1 extra line break added between lines 1 and 3.

## Screenshots

![multilines](https://user-images.githubusercontent.com/5874851/78827661-74902f00-79b1-11ea-925e-9e58393fecf2.gif)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
@jauyong, could we re-phrase this ticket to be specifically about manual line breaks in the text becoming too large in the canvas display component? That's the main problem here - there should only be one line of height difference between line 1 and 2 in your example, yet when you exit edit mode the height is suddenly increased between those lines. There are other problems with text fields not correctly showing all lines, but we also have existing bugs for some of that. I don't think we have a bug about manual line breaks though.

**Comment by jauyong** [comment]
@barklund please go ahead and rephrase to what you think makes sense.

**Comment by barklund** [comment]
@jauyong I have updated it with some technical details. Also I removed the gif about highlight text not sizing correctly, as it's covered by #835 and probably several others.

**Comment by pbakaus** [comment]
This is a clear P0. Text needs to be perfect.
