### ISSUE TITLE
Preload image before inserting element

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#1109]
## Feature Description

Before inserting into the images ( and maybe videos ) into a the canvas, prefetch them so they are ready in the browser. 

This should should be triggered before the element is created, maybe on first user interactions, like focus or hover on the element in media library. 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
Preload image helper was added [here](https://github.com/google/web-stories-wp/pull/1102/files#diff-3fdddffd64c7169d4e60054e7ece3030).

**Comment by pbakaus** [comment]
+1!

**Comment by spacedmonkey** [comment]
What is the priority on this?

**Comment by pbakaus** [comment]
P1.

**Comment by diegovar** [comment]
@pbakaus , I'd like to understand the rationale behind this being a P1. It seems like an optimization for the very specific case that an image is clicked and not dragged and dropped. Even so, with the proposed approach of preloading on hover, it would only maybe shave a few milliseconds and also incur unnecessary data transfer. Can this not be bumped to the stable release?

**Comment by o-fernandez** [comment]
@diegovar updated prioritization considering all open bugs. Agree that it's a good optimization for stable release.

**Comment by merapi** [comment]
Related: https://github.com/google/web-stories-wp/issues/2615
(simple hover might preload many images unnecessarily)

**Comment by diegovar** [comment]
Can this be closed in favor of #2615? @o-fernandez. I feel that's a better solution to the underlying problem.

**Comment by o-fernandez** [comment]
Sounds good. let's do that.
