### ISSUE TITLE
Drop Target not Following Flip

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1111]
## Bug Description

When you flip an element, the drop target does not follow. 

**Note:** when #1878 is merged, there's an additional problem on droptarget hover, as hovering a non-flipped element now resets the flip of the drop target which results in displaying both a flipped and a non-flipped drop target (only visible with non-regular blobs).

## Expected Behaviour

Drop target should follow modifications to the element. 

## Steps to Reproduce

1. Flip a shape
2. Attempt to mask the shape with an image and see drop target

## Screenshots

![flipped drop target](https://user-images.githubusercontent.com/5874851/78830637-495c0e80-79b6-11ea-8db4-596bfbc6e48d.gif)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
#1156 seemed close. Maybe it can be resurrected

**Comment by bmattb** [comment]
during bl grooming it was agreed that once an image has been applied with a mask they should be considered grouped and should be considered a single element, therefore flipping the shape with the image already in place will apply the flip to both the mask and the image.

Alternatively flipping the shape first, then moving the image in will result in a flipped mask, with the image presenting right side up

**Comment by miina** [comment]
@barklund @bmattb FYI Pulling this into the sprint.

**Comment by csossi** [comment]
Verified in QA
