### ISSUE TITLE
Border-radius as squircles

### ISSUE THREAD

**Issue by pbakaus** [GoogleForCreators/web-stories-wp#1115]
## Feature Description

I think this would be really cool :) Instead of doing a boring old border radius, we'll one up it and produce pixel perfect squircles using clip-path.

Further reference:
- https://medium.com/@zubryjs/squircles-bringing-ios-7s-solution-to-rounded-rectangles-to-css-9fc35779aa65
- https://jsbin.com/cobuyatimo/edit?html,css,output
- https://codepen.io/AmeliaBR/details/KaJaWK/
- http://iamvdo.me/en/blog/smooth-corners-with-css-houdini

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Note on border-radius:
the Moveable library we're currently using allows setting border-radius to an element this way:
![border-radius](https://user-images.githubusercontent.com/3294597/94465716-9cbe5500-01c0-11eb-949e-ed775ca713b8.gif)

Not sure how it's planned but just FI that we have that option available.

**Comment by pbakaus** [comment]
Yes please. I want it now!

**Comment by o-fernandez** [comment]
@samitron7 do you have designs for applying border radius? Wondering if this needs a product brief at all, just let me know. 

I like Miina's comment above for an easy-to-apply border radius option, worth considering.

**Comment by barklund** [comment]
Note that this ticket is for "border-radius as squircles". I'll be making a new ticket for basic border-radius.

**Comment by samitron7** [comment]
Confirmed corner radius design in issue [1051](https://github.com/google/web-stories-wp/issues/1051).

I do have designs for manipulating borders on the element itself but seeing how the one Miina showed comes for free, I think it's also good enough. One modification is if we can show the control for radius at all times. See Figma flow [here](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=1302%3A234739)

![borderRadius](https://user-images.githubusercontent.com/10889431/95633146-e833f700-0a3b-11eb-8901-7307a176473f.gif)
