### ISSUE TITLE
Stories need to have valid OpenGraph & Schema.org metadata

### ISSUE THREAD

**Issue by pbakaus** [GoogleForCreators/web-stories-wp#1117]
## Bug Description

Stories need to look great when shared on both Facebook and Twitter, and pass the requirements to appear in Google Discover and Search.

## Expected Behaviour

To test this, Stories should pass Google's Schema.org validator, and look great when shared on Facebook and Twitter (have thumbnail, title etc.).

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## QA Instructions

1. Create a new story, making sure it has a featured image
1. Pass story through Google's [structured data testing tool](https://search.google.com/structured-data/testing-tool/u/0/)
1. Pass story through Twitter's [Card Validator](https://cards-dev.twitter.com/validator)
1. Pass story through Facebook's [Sharing Debugger](https://developers.facebook.com/tools/debug/)
1. Try sharing on Facebook and Twitter (no need for actually posting; the previews should work fine)

**Comment by spacedmonkey** [comment]
I think this links to #113

**Comment by swissspidy** [comment]
Some docs:

https://developers.google.com/search/docs/guides/enable-web-stories
https://blog.amp.dev/2020/02/12/seo-for-amp-stories/

**Comment by swissspidy** [comment]
Some schmema.org metadata is added in `\Google\Web_Stories\Story_Post_Type::get_schemaorg_metadata`

**Comment by swissspidy** [comment]
> Stories need to look great when shared on both Facebook and Twitter

@pbakaus should we implement things like [Twitter Cards](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/abouts-cards) or Open Graph tags ourselves to meet the  minimum requirements for this? Or rely solely on third-party plugins like Yoast SEO (see #113)?

> and pass the requirements to appear in Google Discover and Search

I believe we cover the [technical basics](https://developers.google.com/search/docs/guides/enable-web-stories#implement) already (valid AMP, schema.org data). Although it's difficult to deduce the correct content type for structured data.

**Comment by pbakaus** [comment]
> @pbakaus should we implement things like [Twitter Cards](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/abouts-cards) or Open Graph tags ourselves to meet the minimum requirements for this? Or rely solely on third-party plugins like Yoast SEO (see #113)?

Yes, we should definitely add these ourselves. We can allow Yoast and other plugins to override/complete them though. Sharing our stories should render nice previews out of the box on Twitter & FB. /cc @o-fernandez

**Comment by csossi** [comment]
Seeing this error in the Google Structure Tool:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/9d971405-3903-4124-a5b9-069d364989f6)

And on Twitter:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/dca17ec8-6d0a-4c03-a4d7-41ebaea840b6)

And getting this on FB:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/90bcbe6e-4cda-40cf-aad3-a5ab186a6f05)

I'll leave the url I used for testing -  https://stories-qa-wordpress-amp.pantheonsite.io/stories/whiz-bang/ -untouched so that it can be replicated

**Comment by swissspidy** [comment]
Ah well, our staging site is noindex 🤦  So yeah the card validator doesn't work there.

Tried it on my own public site and it works as expected:

<img width="1024" alt="Screenshot 2020-06-10 at 09 19 23" src="https://user-images.githubusercontent.com/841956/84238553-81d5b100-aafb-11ea-89b7-580eb0db05e6.png">

Structured Data Testing Tool:

Seems like the logo needs to be annotated as a proper `ImageObject`:

<img width="759" alt="Screenshot 2020-06-10 at 09 23 46" src="https://user-images.githubusercontent.com/841956/84238975-1f30e500-aafc-11ea-8507-cd5a9e4ab941.png">

Facebook Sharing Debugger:

- `og:description`: looks like we need to bring back excerpts... Will open a new issue for this.
- `fb:app_id`: Nothing we can provide. That's specific to the website, so can be ignored.

**Comment by swissspidy** [comment]
Using `ImageObject` seems to work:

<img width="813" alt="Screenshot 2020-06-10 at 09 49 13" src="https://user-images.githubusercontent.com/841956/84241386-b0558b00-aaff-11ea-8db1-9e9b5805aa91.png">

**Comment by swissspidy** [comment]
@csossi for QA you want to **temporarily** disable the ` Discourage search engines from indexing this site` option under Settings -> Reading. Then Twitter should work.

**Comment by csossi** [comment]
Verified in QA

**Comment by swissspidy** [comment]
For completeness, output of Facebook's sharing debugger:

<img width="551" alt="Screenshot 2020-06-16 at 14 50 21" src="https://user-images.githubusercontent.com/841956/84776587-c7551b00-afe0-11ea-9743-3688a66580cb.png">

And Twitter card validator:

<img width="572" alt="Screenshot 2020-06-16 at 14 49 58" src="https://user-images.githubusercontent.com/841956/84776602-ccb26580-afe0-11ea-8f69-968246036150.png">

See newly added description.

No errors in both tools.
