### ISSUE TITLE
Custom poster image not covering full video size

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#1123]
## Bug Description
If there's a custom poster image of different size that the video, the custom poster image does not fill in the whole room of the video frame, it does in FE and on Thumbnails though (stretched).

## Expected Behaviour
Custom poster image should behave the same way on the Page, on Thumbnails and in Frontend.

## Steps to Reproduce
1. Add a video
2. Assign a custom poster image that has a different ratio than the video.

## Screenshots
<img width="348" alt="Screenshot 2020-04-09 at 09 55 40" src="https://user-images.githubusercontent.com/3294597/78871658-4dd10780-7a48-11ea-8a3e-c5c8158c8e60.png">

<img width="388" alt="Screenshot 2020-04-09 at 09 59 42" src="https://user-images.githubusercontent.com/3294597/78872039-ea93a500-7a48-11ea-8613-bc7c83d20b51.png">
<img width="552" alt="Screenshot 2020-04-09 at 10 00 03" src="https://user-images.githubusercontent.com/3294597/78872042-ec5d6880-7a48-11ea-8693-2c19e8314252.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
There is a similar issue with the preview of the poster in the sidebar. 
What is currently looks like. 
![Screenshot from 2020-04-09 10-01-45](https://user-images.githubusercontent.com/237508/78877749-3f372000-7a49-11ea-87bb-6d57e224657e.png)
Compared what it should may look like.
![Screenshot from 2020-04-09 10-02-13](https://user-images.githubusercontent.com/237508/78877758-42321080-7a49-11ea-8658-48230c65b362.png)

**Comment by dvoytenko** [comment]
This is a tricky item.  I believe video forces `object-fit: contain` on the poster image. And I don't think it can be changed. So the current behavior is more inline with what reality might be.

Assigning this to @pbakaus to consider.

**Comment by pbakaus** [comment]
If amp video does indeed force object-fit contain, I'm OK keeping it contained. But if not, then not.

**Comment by miina** [comment]
For non-background videos, the poster image seems to be look in sync with the editor indeed, there are still some differences to resolve though.
For comparison:
- FE:
<img width="375" alt="Screenshot 2020-04-10 at 09 52 53" src="https://user-images.githubusercontent.com/3294597/78973904-1a0de480-7b11-11ea-9ecf-4c8ce9bf4c23.png">

- Editor page previews (stretched):
<img width="207" alt="Screenshot 2020-04-10 at 09 52 20" src="https://user-images.githubusercontent.com/3294597/78974029-5b05f900-7b11-11ea-9533-fe5876a4c261.png">

- Editor on the page (matches with FE):
<img width="357" alt="Screenshot 2020-04-10 at 09 53 53" src="https://user-images.githubusercontent.com/3294597/78973965-3578ef80-7b11-11ea-8a52-9ea742de5bf7.png">


More differences with background!
For comparison:
- Background video's poster in the front-end:
<img width="391" alt="Screenshot 2020-04-10 at 09 47 17" src="https://user-images.githubusercontent.com/3294597/78973548-73c1df00-7b10-11ea-957a-aa610ce22c88.png">

- Background video's poster in the editor page previews:
<img width="741" alt="Screenshot 2020-04-10 at 09 48 06" src="https://user-images.githubusercontent.com/3294597/78973565-7b818380-7b10-11ea-976e-5d021041fdb2.png">

- Background video's poster in the editor Page:
<img width="497" alt="Screenshot 2020-04-10 at 09 49 27" src="https://user-images.githubusercontent.com/3294597/78973700-b84d7a80-7b10-11ea-9cd2-4f1b43932900.png">

**Comment by pbakaus** [comment]
This is a great analysis and an especially great test video! :)

Yes, I think these should all be normalized. I've unassigned myself from this ticket as it seems clear what there is to do next.

**Comment by miina** [comment]
@barklund @bmattb FYI pulling into Sprint.

**Comment by csossi** [comment]
Verified in QA
