### ISSUE TITLE
Poster image not displayed / jumps in. 

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#1126]
## Bug Description

After video preview completes update, the poster image disappears and is replaced after a couple of seconds with a real poster image from WP. 

## Expected Behaviour

This should not be soo jumpy and the poster image replacement should happen seamlessly. 

## Screenshots

https://youtu.be/nEWXcRzzdbo

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
CC @obetomuniz

**Comment by csossi** [comment]
Verified in QA
