### ISSUE TITLE
Page Menu Bar is Cut Off

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#1127]
## Bug Description

Page Menu Bar is cutting off elements on small screens.

## Expected Behaviour

Page Menu should be synced with Figma designs to support correctly small screens.

## Steps to Reproduce
1. Make the screen small so that the Page Menu width decreases enough for some elements to get hidden.

## Screenshots

![image](https://user-images.githubusercontent.com/5874851/80489675-2fb34480-892e-11ea-8c2b-3d5601adbbd3.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by obetomuniz** [comment]
@miina  @jauyong @samitron7 what is the expected behavior here? Considering that the problem is related to the whole Page Menu itself, not only with the Redo button, should we reduce the size of the elements inside of Page Menu on small screens to use the available area?

**Comment by swissspidy** [comment]
I thought according to Figma the `Page 1` part is hidden on smaller screens. Let's stick to the design.

**Comment by obetomuniz** [comment]
Cool. Updating the Issue description 👍
