### ISSUE TITLE
Yoast SEO Integration for Metadata

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#113]
Original discovery ampproject/amp-wp#3179 

- [x] Contribute [upstream pull request](https://github.com/Yoast/wordpress-seo/pull/15532) to Yoast SEO.
- [ ] Test integration with Yoast 
- [ ] Add Yoast SEO to testing environment

**Comment by swissspidy** [comment]
@spacedmonkey perhaps time to update that upstream PR?

**Comment by swissspidy** [comment]
Took a stab at Yoast SEO integration yesterday: https://github.com/Yoast/wordpress-seo/pull/15532

**Comment by swissspidy** [comment]
https://github.com/Yoast/wordpress-seo/pull/15532 has been merged!

Follow-up tickets will be created to improve the integration.
