### ISSUE TITLE
Edits sometimes applied to a different page when switching pages 

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#1131]
## Bug Description

When I switch pages (from **old** page to **new** page which is a duplicate of **old** page) in a story while editing a text element, the edits to the text element get applied to the **new** page I switch to, rather than the **old** page where I was making the edits. 

## Expected Behaviour

Edits should have been applied to the text element in the **old** page.

## Steps to Reproduce

1. Add a text element to Page 1 of a story, write anything in it. 
2. Duplicate Page 1 and edit the text field on Page 2 to say something else.
3. Start editing the text element of Page 2 and, while still in editing mode on Page 2 switch the page to Page 1 by clicking on Page 1 in the page selector (below the editor canvas)
4. You may see the text you were editing in Page 2 now applied to the text element in Page 1. If you click back to Page 2, should notice that Page 2 text element didn't get any edits applied to it, it kept its original value. This is unexpected.

## Screenshots

https://drive.google.com/a/google.com/file/d/1i9Te_yq1VrC1dKx4U8sPqzSEDwLOAHzB/view?usp=sharing

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
~I am unable to reproduce this. The only bug I see is that the edit is not saved when switching page while in edit mode (because the component is unmounted before it could run the update logic, I suppose), but I can't recreate that the change should appear on a different page.~

**Update**: I can reproduce now that it's been clarified, that it has to be a duplicated page with a (duplicated) text element.

**Comment by barklund** [comment]
So, there are two bugs here:

1. A duplicated page duplicate all elements including their element ID's. Element id's should be unique throughout the story - a duplicated page should generate new ID's for the page and all elements.
2. The carousel should not be interactive when in edit mode. @dvoytenko is looking into that.

**Comment by dvoytenko** [comment]
> 2. The carousel should not be interactive when in edit mode. @dvoytenko is looking into that.

The https://github.com/google/web-stories-wp/pull/1139 in review for this.
