### ISSUE TITLE
New story create history updates without user direct changes

### ISSUE THREAD

**Issue by obetomuniz** [GoogleForCreators/web-stories-wp#1137]
## Bug Description

As soon as the user tries to create a new story, the process created by [this hook](https://github.com/google/web-stories-wp/blob/master/assets/src/edit-story/app/story/effects/usePageBackgrounds.js) is creating an unnecessary update in the history state. 

It is creating side effects on the Editor Workspace, because you can "undo" something that never was changed.

Also, it is enabling prevent window unload, since it is updating the history version number for a new number since the last save.

## Expected Behaviour

Stories can't update history state without user direct actions for this. Maybe will be fixed by #1129 

## Steps to Reproduce

1 - Create a new story
2.1 - Try to reload (You will receive an undesired Window Prevent Unload prompt even without change/create a proper story)
2.2 - Try to "undo" (The action is working/activated without any change from the user)

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@obetomuniz Confirmed that this will be fixed by #1129

**Comment by miina** [comment]
Closed with #1129
