### ISSUE TITLE
Editor: Replace deep clone dependency with native structured clone

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#11505]
## Feature Description

[`structuredClone`](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone) is now available in all browsers. We currently use [`clone-deep`](https://github.com/GoogleForCreators/web-stories-wp/blob/8786821f787193c0b4127654f42269fbec8e9afd/packages/story-editor/package.json#L67) for this purpose, but [only in a single place](https://github.com/GoogleForCreators/web-stories-wp/blob/8786821f787193c0b4127654f42269fbec8e9afd/packages/story-editor/src/app/story/effects/useHistoryEntry.js#L56) as far as I can tell.

We should remove this dependency and use the browser native alternative.

**Comment by swissspidy** [comment]
Yes! Good idea. Support is still rather new in Safari, so with our browserslist config (last 2 Safari versions), this will probably include the `structuredClone` polyfill from core-js in our bundle, but that's fine.
