### ISSUE TITLE
Snapping: Letting go (mouseup) after snapping sometimes "jumps"

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#1150]
## Bug Description

Sometimes when snapping, the element jumps a little bit.

## Expected Behaviour
When snapping, the element should stay in the final position as it was.

## Steps to Reproduce

1. Add an image
2. Move it near the bottom center of the Page
3. Try snapping to the center and letting the element go (see the video below)
4. See the element jumping after letting go.

## Screenshots
![snapping](https://user-images.githubusercontent.com/3294597/78970391-7bca5080-7b09-11ea-9ac1-5d2988aa440b.gif)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment]
@wassgha to confirm if this is still occurring.

**Comment by wassgha** [comment]
Does not look like this is happening anymore, possibly fixed by `react-moveable`. Closing for now, @miina feel free to reopen if it's still occurring on your end.
