### ISSUE TITLE
Unable to Create New Story as Author or Contributor

### ISSUE THREAD

**Issue by sblinde** [GoogleForCreators/web-stories-wp#11504]
## Bug Description

When logging in as an author or contributor role, an error occurs blocking one from being able to continue.

## Expected Behaviour

You should be able to log in and create a story as an author or contributor without having any trouble.

## Steps to Reproduce

1. Log in as an author or contributor
2. Go to create a story
3. Get an error message

## Screenshots
![Screen Shot 2022-05-17 at 1 30 27 PM](https://user-images.githubusercontent.com/7110244/168874781-261f0be7-0ce3-421c-baf6-39c090419c23.png)
![Screen Shot 2022-05-17 at 1 30 51 PM](https://user-images.githubusercontent.com/7110244/168874835-202bca39-4bed-4821-9a0f-60543c944189.png)

## Additional Context

- Plugin Version: `main` branch
- WordPress Version: 5.9.3
- Operating System: macOS
- Browser: Seen in both Chrome and Firefox

**Comment by swissspidy** [comment]
I cannot reproduce this.

Using the editor with these user roles works fine for me locally, on stories-qa, and on stories-new. Not to mention that our e2e tests (which also test these roles) are passing fine.

Do you perhaps more information on how to reproduce this?

**Comment by sblinde** [comment]
> 

That's as much as I was able to garner, a few of us saw it during the bug bash yesterday on the `main` branch. I couldn't replicate it on stories-qa or stories-new, but my role is different there so harder to reproduce.

**Comment by swissspidy** [comment]
I was now able to reproduce this on another environment! PR imminent.

**Comment by felipebochehin87** [comment]
1. Uploaded a new media as an Admin
2. Logged in as an Author/Contributor and created a new story, adding the media that was uploaded on step 1 - no crash
