### ISSUE TITLE
Easy sharing story data for debugging purposes

### ISSUE THREAD

**Issue by merapi** [GoogleForCreators/web-stories-wp#1155]
## Feature Description

For scenarios like this one:
https://xwp.slack.com/archives/CCCAUAH6F/p1586471507080500?thread_ts=1586457879.061800&cid=CCCAUAH6F

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
1. Document what currently works on a wiki page in our github repo or a markdown file in one of the readmes. 
2. Provide details required for the follow up ticket which will be to make this look better

**Comment by merapi** [comment]
Something like this (sharing JSON will not work on Slack thus Base64)?
```js
window.restoreStory = (b64story) =>
  restore(JSON.parse(window.atob(b64story)));
  
window.dumpStory = () => {
  const b64story = window.btoa(
    JSON.stringify({ pages, current, selection, story, capabilities })
  );
  // Copy to clipboard
  window.copy(b64story);
  return b64story;
};
```
in StoryProvider or dedicated place.

**Comment by dvoytenko** [comment]
I think it'd be easiest to make a hidden shortcut and pop a dialog with a big textarea that'd have the current story's JSON and the new JSON can be pasted on top of it. Ideally we'd also be clever enough and replace media resources with something comparable from our own library. At easiest image -> image, video -> video.
