### ISSUE TITLE
Links on text selection

### ISSUE THREAD

**Issue by wassgha** [GoogleForCreators/web-stories-wp#1158]
## Feature Description

Part of #253 , should be able to add a link to a part (selection) of a text in addition to the currently implemented links on the entire text component. 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by wassgha** [comment]
@pbakaus I remember you said we should prioritize this but there's no basis for applying properties to selections of text as opposed to the entire text element, can we prioritize that? (e.g. start with the ability to apply bold/italic to a text selection).

**Comment by pbakaus** [comment]
@wassgha yes! /cc @barklund and @dvoytenko

**Comment by jauyong** [comment]
@o-fernandez to confirm UI

**Comment by o-fernandez** [comment]
This is not in scope for the short term, so let's icebox
