### ISSUE TITLE
Dashboard: context menu resize/overlap on smaller viewports 

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#1160]
## Bug Description
In the new dashboard we have a 'context menu' that opens with the three vertical dots on hover of a story on my stories view. If you are looking at the screen in a smaller size (< 600px) the menu, when open, could have better positioning. Some of the menu cuts off and there's a couple viewport sizes where the left wordpress menu takes priority and overlaps the menu. (see video) 

## Expected Behaviour
Menu should be visible when open and have space between its left edge and the end of the screen. Ideally, that same gutter as the rest of the dashboard. 

## Steps to Reproduce
Resize browser window with first story to the left's context menu expanded and see. 

## Screenshots
Screencast: 
https://drive.google.com/file/d/1EvBLoj9QvxA3EZ0VIfrPHf2i8pramFbs/view?usp=sharing
---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by carloskelly13** [comment]
I believe we can close this since we are not optimizing dashboard for phone-sized screens.

**Comment by BrittanyIRL** [comment]
This bug has been fixed with updates to the layout to prevent this sort of thing, see gif below. 

![overlpa context menu gone](https://user-images.githubusercontent.com/10720454/81201674-631f5000-8f7a-11ea-9e65-501879f7d10c.gif)
