### ISSUE TITLE
Implement page preview that 'plays' a page in the editor

### ISSUE THREAD

**Issue by pbakaus** [GoogleForCreators/web-stories-wp#1163]
## Feature Description

Implement the in-page preview that plays back a page in the editor. Has a spec but no UX yet.

**[Product Brief](https://docs.google.com/document/d/11xtdVNrSa16qg9tmg_ACw6vTD8z8wymhkRSgOqkVCa8/edit#heading=h.c2t7z24byi3x)**

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. Author is able to preview a single page
2. When previewing a page, it is a Workplace-level action to preview and play back the page the author is currently editing (especially important to test animations and videos)
3. When previewing a page, it hides a potential current selection on the Workspace
4. When previewing a page, it exits edit mode (masking mode)
5. When previewing a page, it plays back all animations and videos
6. When previewing a page, it automatically reverts (to normal Workspace mode) after all animations and videos have finished playing.

**Comment by jauyong** [comment]
Note from Grooming on Apr 15:

> related to animations, UX needed, p1, probably for next sprint (or future)

**Comment by jauyong** [comment]
@jauyong to create animations epic and add this to it. 
This will be needed for the Dashboard as well

**Comment by jauyong** [comment]
Moved out of Beta during grooming on Apr 29

**Comment by BrittanyIRL** [comment]
I'm picturing this like the left half of the template details view: https://stories-new-wordpress-amp.pantheonsite.io/wp-admin/edit.php?post_type=web-story&page=stories-dashboard#/templates-gallery/template-detail?id=5&isLocal=false 

If this is the case, we can go ahead and build this and then make UX tweaks to it just so the functionality is there. 

Thoughts, @o-fernandez @samitron7 ?

**Comment by o-fernandez** [comment]
> I'm picturing this like the left half of the template details view: https://stories-new-wordpress-amp.pantheonsite.io/wp-admin/edit.php?post_type=web-story&page=stories-dashboard#/templates-gallery/template-detail?id=5&isLocal=false
> 
> If this is the case, we can go ahead and build this and then make UX tweaks to it just so the functionality is there.
> 
> Thoughts, @o-fernandez @samitron7 ?

Yeah, I think it should be pretty similar. Within the workspace the user would be on a page they are editing and they can click a button that just "previews" that page, similar to how it'd work in template details, instead of previewing the whole story on a new page.

**Comment by BrittanyIRL** [comment]
> on a page they are editing 

Just to confirm, there will be no actual editing of the story (outside of the title getting updated) in the dashboard.  It would just be the left hand side of the detail template view only instead of template pages, it would be story pages. 

Otherwise I think I'm on the same page as you - care if I pull this into the next sprint to get up and running?

**Comment by samitron7** [comment]
@BrittanyIRL Most likely, I'm going to add a play button down to the page action menu at the bottom of the page that allows you to click and play the individual page. Is ticket is in icebox so can I ask why we can't wait for UX here?

**Comment by BrittanyIRL** [comment]
@samitron7 no worries! i was mostly checking in on this because it's been hanging out for a while (because it's not critical!) to see if it was similar to the template detail view because I have capacity the next day. Happy to wait.

**Comment by o-fernandez** [comment]
We should do this as part of #2910, which will be important for 1.0 Stable.

**Comment by o-fernandez** [comment]
Being done as part of #3484, this ticket is now a dupe.
