### ISSUE TITLE
Text element change is sometimes not persisted

### ISSUE THREAD

**Issue by merapi** [GoogleForCreators/web-stories-wp#1164]
## Bug Description

The text element sometimes returns to its old value, e.g. when clicking on the workspace (works when clicking in elements/inspector panel).

## Screenshots

![2020-04-11_04-23-05 (2)](https://user-images.githubusercontent.com/21036224/79043975-e612ec00-7c02-11ea-847d-d49057ed11c7.gif)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by merapi** [comment]
The bug was introduced here: https://github.com/google/web-stories-wp/commit/21551aedf751a39f17337c665ddd966fedec5dc8.

Looks like the underlying issue is [here](https://github.com/google/web-stories-wp/blob/8a8fc33591540c7cb660c5cecc20bc2a1fba4ee2/assets/src/edit-story/utils/useFocusOut.js#L31).
Sometimes `relatedTarget` will be null (it's normal), more details:
https://developer.mozilla.org/en-US/docs/Web/API/FocusEvent/relatedTarget

Removing `evt.relatedTarget && ` should do the trick @barklund can you see any potential issues with that?

**Comment by merapi** [comment]
I looked at it more thoroughly, here is what I found:

The bug was introduced here: https://github.com/google/web-stories-wp/commit/21551aedf751a39f17337c665ddd966fedec5dc8.

^Could work with `useFocusOut onFocusOut` but because `relatedTarget` can sometimes be null (and it's normal, more on that [here](https://developer.mozilla.org/en-US/docs/Web/API/FocusEvent/relatedTarget)) [this line](https://github.com/google/web-stories-wp/blob/8a8fc33591540c7cb660c5cecc20bc2a1fba4ee2/assets/src/edit-story/utils/useFocusOut.js#L31) will not work and the callback will not be called (which saves the text).

You might ask why `useFocusOut onDocumentClick` will not work? - the textBox is unmounted (and listeners removed) when you click outside so that part is never executed (not like in case of e.g. Dropdown).

**Comment by dvoytenko** [comment]
I'm wondering if we should revert onFocusOut (or bring back the onMount along with onFoucsOut). And we can go straight to a more stable solution. Which, I expect, would be a callback in the `useEditingElement` when the editing element ID changes (to a new element, or via `clearEditing`). Something similar is done in the design panel and it's pretty stable.

**Comment by merapi** [comment]
I was thinking about how `useFocusOut` should work, right now we detect focusout and outside click, the missing piece is: what to do when the element is removed. 

In Chrome when you remove the element that was focused, blur/focusout will be fired (not working in FF [bug here](https://bugzilla.mozilla.org/show_bug.cgi?id=559561)). With React we can achieve something like this by utilizing the "unmount event".

Would adding `callback()` in `useFocusOut` clean-up function cause any issues?
I can see it fixes this bug and works with dropdown/datepicker.

**Comment by barklund** [comment]
> Would adding `callback()` in `useFocusOut` clean-up function cause any issues?
> I can see it fixes this bug and works with dropdown/datepicker.

I think that's a safe fix here, yes. It seems reasonable, that _unmount_ is comparable to focus out and should always do the same thing (for text fields: save the content).

For the other situations, we use it to remove the element on focus out, which means that unmount already did what we wanted anyway, so no harm done.

@merapi, 👍 from me.
