### ISSUE TITLE
Removing As Background Setting to Square Aspect Ratio

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1172]
## Bug Description

Clicking “Remove as background” resets the element to a square aspect ratio (should reset to proper aspect ratio instead). This is only happening when setting as a background via dragging onto the mask zone.

## Expected Behaviour

The aspect ratio should not be altered after removing as a background.

## Steps to Reproduce

1. Drag a video onto the masking portion of a page to set it as the background
2. Remove it as a background

## Screenshots

![square aspect ratio](https://user-images.githubusercontent.com/5874851/79146798-eb9e3c80-7d90-11ea-97ac-0b8a09228768.gif)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
This got addressed with #1798, closing as fixed.
