### ISSUE TITLE
Restart not Working in Preview When Only 1 Page

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1175]
## Bug Description

When previewing a story with only 1 page, the restart button does not work. 

## Expected Behaviour

Pressing the restart button should restart the 1 page story. 

## Steps to Reproduce

1. Add a video to the page so you can tell if it "restarts"
2. save and preview the story
3. Press restart when the auto advance is done

## Screenshots

Restart button on the far right.
![image](https://user-images.githubusercontent.com/5874851/79153550-0629e300-7d9c-11ea-9871-de951fd6b8ba.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Seems like an issue in the AMP story viewer, not something that we could control.

@wassgha perhaps you could confirm?

**Comment by wassgha** [comment]
That's correct, I'll report it on the amphtml side. Here's the codepen https://codepen.io/gharbiw/pen/rNOOWzG

**Comment by wassgha** [comment]
Filed https://github.com/ampproject/amphtml/issues/27742

**Comment by swissspidy** [comment]
Closing since it's an upstream issue
