### ISSUE TITLE
Show correct panels for background media selection

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1177]
## Bug Description

When the Page Selected the design panel is not showing the correct options. 

## Expected Behaviour

If there is no background media:
- Show style section
- Do not show any other sections **(currently some are shown)**

If there is background media:
- Show style section **(currently not shown)**
- Show overlay option(s)
- Show background display options

See [Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=2671%3A55920) for default states

## Steps to Reproduce

Select a page with either no background media (and see too many panels) or select page with background media (and see too few panels).

## Screenshots

![image](https://user-images.githubusercontent.com/5874851/79156016-19d74880-7da0-11ea-9e26-7dad4686f14d.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment]
@samitron7 currently only style and overlay are displaying and are applicable to an empty page. Can you confirm the default state of the design panel.

**Comment by csossi** [comment]
Reviewing in QA environment #2158

The design panel re: Image doesn't match figma (colour/% in Overlay section)
Editor:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/0dc37e47-2641-4611-a643-744c9de490a2)

Figma:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/1c4ddba6-fcfb-4bc0-9c47-3eacb1bb0032)

**Comment by swissspidy** [comment]
That part is still **work in progress** in a separate PR. See #1925.

**Comment by samitron7** [comment]
UAT - looks good!
