### ISSUE TITLE
Page Carousel not Centred 

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1178]
## Bug Description

Page Carousel not Centred 

## Expected Behaviour

The carousel should be centered. See Figma for many examples

## Screenshots

![image](https://user-images.githubusercontent.com/5874851/79156334-ae41ab00-7da0-11ea-9bbf-1d50758e0a09.png)
![image](https://user-images.githubusercontent.com/5874851/79156336-b0a40500-7da0-11ea-8e73-a45ac2f7d800.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by wassgha** [comment]
I think this was there before, iirc it's because of the buttons for keyboard shortcuts / grid view that push it to the left
