### ISSUE TITLE
Page Carousel - Remove Blue Indicator When Only One Page    

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1179]
## Bug Description

When there is only one page there shouldn't be a blue indicator on the page thumbnails in the carousel 

## Expected Behaviour

The blue line shouldn't be there.
See [figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=2683%3A260) for examples

## Steps to Reproduce

1. View a single page story

## Screenshots

![image](https://user-images.githubusercontent.com/5874851/79156996-d251bc00-7da1-11ea-84de-d7b08b01ad14.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
@samitron7 Should the blue line still show on hover?
