### ISSUE TITLE
Add Animation on Page Carousel when Navigating Pages

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1180]
## Bug Description

There is a missing animation when navigating between pages on the page thumbnail carousel with the blue indicator at the top.

@samitron7 to add animation demo

## Expected Behaviour

There should be an animation that looks like a slider effect. 

## Steps to Reproduce

1. Go to a story with multiple pages
2. Change the page

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by samitron7** [comment]
Closing ticket since the focus state has changed in new design language.
