### ISSUE TITLE
Page Navigation Hover Styling is Sticking

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1181]
## Bug Description

Sometimes the page navigation arrows are white or grey. It depends on what you last used an hover state. 

## Expected Behaviour

@samitron7 should the default state be grey and the hover state is white? I couldn't find info in figma

## Screenshots

![arrows](https://user-images.githubusercontent.com/5874851/79158036-9f102c80-7da3-11ea-9e92-174e253c3c99.gif)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
It's clearly the focus/active state appearing similar to the hover state. If we don't we mouse-based focus, we should just remove focus styling here.

**Comment by samitron7** [comment]
Yes, the default state is gray and the hover state is white. We like for the arrows to be muted and not the main focus as you are working. Only white when you explicitly need them. Removing UX needed label.

**Comment by csossi** [comment]
Verified in QA

**Comment by samitron7** [comment]
Verified in UAT
