### ISSUE TITLE
Keyboard Page Carousel Navigation 

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1182]
## Bug Description

There is no way to navigate pages via keyboard shortcut. 

## Expected Behaviour

I should be able to navigate pages via left and right arrows.
@samitron7 @pbakaus  to confirm keyboard shortcuts. See this [convo for details](https://xwp.slack.com/archives/CCCAUAH6F/p1586458181066500). 

https://docs.google.com/spreadsheets/d/1VNv8O5SnlqZfgYXo5ua2mCc-MWTN9ow6OtYWxml5Ka0/edit#gid=0

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by samitron7** [comment]
Is feature is already working on the editor. Closing ticket.

**Comment by swissspidy** [comment]
While we can navigate between pages in the carousel using arrows once you've focused on a page, there is no global keyboard shortcut to do so (e.g. CMD+LeftArrow / CMD+RightArrow to go to previous/next page). Such a shortcut is also not listed at https://docs.google.com/spreadsheets/d/1VNv8O5SnlqZfgYXo5ua2mCc-MWTN9ow6OtYWxml5Ka0/edit#gid=0, but maybe we want one?

cc @o-fernandez
