### ISSUE TITLE
Media Uploaded to Page is Disappearing from Library Panel

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1183]
## Bug Description

Media Uploaded to Page is Disappearing from Library Panel.
See screenshot for invalid JSON message.
Note that the image is still there but you have to refresh.

## Expected Behaviour

1. The placeholder in the media panel should persist

## Screenshots

[See gif on Slack](https://xwp.slack.com/archives/CCCAUAH6F/p1586810720133300)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by merapi** [comment]
Discussed it with @swissspidy, it looks like it's our staging env thing and just this one file. I tried to clear the EXIF data and so on - nothing helps, this 900KB file is returning 502, while 28MB GIFs are fine. We are not sure if it's worth putting more effort into this right now, if we encounter more of this - we will investigate further.
