### ISSUE TITLE
Remove Link Option on Full Bleed Media

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1184]
## Bug Description

Images that are the background / fill / full bleed should not have the option to set a link

## Expected Behaviour

The Link section in the design panel should not show up at all for images that are:
1. set as background
2. Uses the "Fill" functionality 
3. Is stretched manually to be full bleed

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
The link section is already hidden for background images.
For fill images the input field is disabled, but no explanation is given. Hiding it as well makes sense to me.
