### ISSUE TITLE
Keyboard handling

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#119]
## Feature description

We need either to have:

1. Global-only keyboard handling, where elements can listen for desired keyboard presses (if focused)
2. Global keyboard handling for global-only interactions (copy, cut, paste, undo, redo, select all) and local keyboard handlers in individual focusable elements (delete, enter, exit, type).

Weigh pros and cons between the two solutions, get consensus and implement.

This is not about creating the actual [keyboard shortcuts](https://github.com/ampproject/amp-wp/issues/3785), but about creating the framework for adding them later.

Ping me @barklund, if you need more details on this.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Select between global-only keyboard handling or global+local keyboard handling
* Implement the selection

## Implementation brief

* 

## QA testing instructions

* 

-----

_Moved over from https://github.com/ampproject/amp-wp/issues/3826_

**Comment by barklund** [comment]
This can be closed now, no? @dvoytenko @swissspidy

**Comment by dvoytenko** [comment]
Yes!
