### ISSUE TITLE
Media Edit Mode: display different cursor where panning is allowed

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#1192]
## Feature Description
When in Media edit mode and panning, currently, the cursor displays the same everywhere, however, panning is not possible from the faded image which might be confusing.

It would be good to differentiate the area where panning is possible and where not.

Example:
![panning](https://user-images.githubusercontent.com/3294597/79203031-bd753700-7e3a-11ea-9c36-7a81ae810def.gif)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
1. It should be clearly understandable where panning is possible and where not.

**Comment by o-fernandez** [comment]
@samitron7 should the image be "draggable" from anywhere in the rectangular box or only within the mask/shape applied? I do find the current state a bit confusing.

**Comment by samitron7** [comment]
Just realized that my wording was not super clear in Figma, but when I said "Drag the image to reposition the image", I meant that the **entire image** should be draggable and not just the portion inside the mask. I updated the wording a bit in [Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=8284%3A1071) to make this super clear and even added the triangle [use case](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=8546%3A3332). Sorry about that.

Removing UX needed label so please let me know if anything else isn't clear.

**Comment by swissspidy** [comment]
QA: verify change of cursor to a "grab" cursor

**Comment by miina** [comment]
@swissspidy @wassgha Based on [Sam's comment](https://github.com/google/web-stories-wp/issues/1192#issuecomment-631926009), the whole image should be draggable though -- the original issue was a bug report and a suggestion but it looks like Sam clarified something else -- the issue description wasn't updated though.

Can you confirm please that this issue is indeed ready for QA despite of that?

**Comment by wassgha** [comment]
I believe the cursor change is still needed so let's keep this issue for the cursor change and spin off the draggable area change into another issue.

**Comment by swissspidy** [comment]
Hmm not sure why I did move it without the PR being approved 🤔

**Comment by wassgha** [comment]
@swissspidy it's approved, this is the PR https://github.com/google/web-stories-wp/pull/2754

**Comment by miina** [comment]
> I believe the cursor change is still needed so let's keep this issue for the cursor change and spin off the draggable area change into another issue.

Ok, sounds good, the other issue should follow up ASAP then probably since as far as I understand then the prioritization and labels etc. is actually for the issue based on Sam's comment.

**Comment by wassgha** [comment]
Created https://github.com/google/web-stories-wp/issues/2765

**Comment by csossi** [comment]
Tested PR#2754

Verified in QA
