### ISSUE TITLE
Dashboard: Custom sort options added to stories API

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#1195]
## Feature Description

Based off of this PR: https://github.com/google/web-stories-wp/pull/1162 to add sorting options to the new dashboard. There are ~two~ one requested sorts that are not available straight from WP's api that we need to add on the server side. 

1. **created by** to first put the current user's stories/templates and THEN everyone else's. 
~2. **last opened** needs to a) be defined by UX and b) be implemented on server side~

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
Adds ability for stories (and templates) to be sorted in the additional ways: 
1) Created by 
~2) Last Opened~

**Comment by pbakaus** [comment]
Actually Sam and I killed "last opened". That should make it easier ;)

**Comment by swissspidy** [comment]
> created by to first put the current user's stories/templates and THEN everyone else's.

@miina @spacedmonkey any thoughts on how we can best implement this?

My initial thought was filtering the resulting SQL query to do something like 

```sql
ORDER BY CASE WHEN post_author = '%s' THEN ... ELSE ...
```

where `%s` is `get_current_user_id()`

**Comment by miina** [comment]
Filtering the query makes sense to me. Not sure what other options there are considering the pagination possibility!

Could also just be something like `... ORDER BY post_author='%s' DESC, ID`

**Comment by BrittanyIRL** [comment]
Hey @swissspidy and @miina any idea when ya'll will get to this? I know it's probably not the _highest_ thing on your list but I didn't want to lose sight of it.

**Comment by miina** [comment]
Oh, since it had the Dashboard label, my brain automatically filtered it out when choosing an issue to work on. Could probably get to it by the end of this week (unless someone beats me to it).

**Comment by BrittanyIRL** [comment]
> Oh, since it had the Dashboard label, my brain automatically filtered it out when choosing an issue to work on. Could probably get to it by the end of this week (unless someone beats me to it).

that would be awesome! yeah if there's a better label for these cross over task just let me know, definitely still getting the feel for how the workflow is organized.

**Comment by miina** [comment]
@BrittanyIRL Q: What should be the ordering logic for the remaining stories? First the current user, and the rest order by ... ?

EDIT: Got information meanwhile that the rest just by author.
