### ISSUE TITLE
Display/Frame text components should not use font fallback

### ISSUE THREAD

**Issue by dvoytenko** [GoogleForCreators/web-stories-wp#1197]
We don't need font fallback for display/frame, b/c validity of the out beats the expediency in that case. Otherwise currently in most of cases switching a font has multiple jumps in the display canvas.

/cc @barklund 

**QA Instructions**

1. Add a Text element
2. Change its font family.
3. Verify there is no "jumpiness" or changing the font multiple times in the text element -- it should change the font family just once per each change,

**Comment by dvoytenko** [comment]
As a further potential improvement, we can also look into [font-display](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display) for the fonts. Though I don't think we use at-font-face there.

**Comment by dvoytenko** [comment]
Notice, this is related but not exactly the same as #1008. But they can share some infrastructure.

**Comment by barklund** [comment]
@dvoytenko, is the intent to force gfonts to use `font-display: block` while in-editor (but use fallback in client-side AMP story) and remove fallback fonts here, or?

**Comment by dvoytenko** [comment]
Yes. The editor itself should prefer `font-display: block`. The output should prefer `swap` or `fallback`. And other features - somewhere in between. E.g. font picker menu should probably use `swap`. In addition this affects `font-family: "my font", ...fallback...`.

The reasoning is this: if you change the font family in the editor in the side panel, it's pretty much always shows fallback first right now and after awhile it jumps to the right font. Thus from editing point of view, fallback is not helpful.

In terms of work being done here: some of this problem is getting resolved in @obetomuniz's #1275. I think that approach will resolve most of editing problems, but I think the display problems will still remain, and can only be solved by correct font-face and fallback CSS.

**Comment by miina** [comment]
Started looking into this, however, it doesn't look like the font fallback is used anymore for display/edit, also, there is no font jumping when switching between the fonts anymore.

Looks like we might be able to close this issue.

Thoughts, @barklund ?

**Comment by csossi** [comment]
Verified in QA

**Comment by swissspidy** [comment]
@miina can this be moved to done & closed?
