### ISSUE TITLE
Search UI / UX

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1200]
## Bug Description

The library panel does not match the [designs in Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=4631%3A5)

## Expected Behaviour
1. Clear query button missing after hitting enter to search
2. Remove upload and filter options after hitting enter to search
3. Update design for empty states

To be taken care of in #26
1. Hover state is missing

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by diegovar** [comment]
@samitron7 Should we hold off on this work if the UI will change to the new designs?

**Comment by samitron7** [comment]
@diegovar Yes hold off on this - getting to it soon. @o-fernandez Do we know what sprint this issue will be slotted into?

**Comment by o-fernandez** [comment]
This seems all in the Media I/O's team control, if that so? If so, I'd let @diegovar and Fontaine decide how to handle. 

If the question is around dependency with the new UI designs, I think that we need @dvoytenko and the TLs to discuss the rollout plans for the new UI.

**Comment by o-fernandez** [comment]
Will close this out in favor of addressing with the visual redesign, #3088
