### ISSUE TITLE
Library Scroll Bar UI/UX

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1202]
## Bug Description

The scroll bar UI/UX does not match [figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=0%3A1)

## Expected Behaviour

1. There padding fo the gutter is off (should be 9px off the border) @samitron7 to confirm
2. There should not be an extra gutter design. It should just be the scroll bar and background colour of the panel. Currently there are 3 sections.

to be taken care of in #26:
1. The scroll bar should only be shown on hover

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by samitron7** [comment]
@jauyong already another ticket covering scrollbar + new visual pass will cover this.

**Comment by diegovar** [comment]
1 and 2 are fixed, 3 (scrollbar on hover) is taken care of in #1698. So closing this issue.

**Comment by swissspidy** [comment]
Closing in favor of #3088 and #1698.
