### ISSUE TITLE
Add Text Via Shortcut

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1204]
## Bug Description

The UX of adding text via shortcut does not match [Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=3462%3A2868)

## Expected Behaviour

1. Default placement of text:
     1.  text box width should be 360 wide (40 px gutter setting on each side) and dropped in centre. Text should centre aligned. This is same for all text presets. 
2. ~Staggering behaviour is incorrect~
3. Default text when using shortcut is incorrect. (i.e. User’s system font (ie Roboto) Style: Regular, 16 px, 24px line height, color #000, left aligned ) [NOTE: Addressed by #1546 ]

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Staggering is handled by #1206.

Detecting the user's system font doesn't really work, as viewers would be unlikely to have the same font. We need to use a font from our current set, so defaulting to Roboto makes sense.

> Default placement of text:
text box width should be 360 wide (40 px gutter setting on each side) and dropped in centre. Text should centre aligned. This is same for all text presets.

Figma currently mentions this:

> The text element is added 40px to the left edge of the page and is in focus.

Note that this somewhat conflicts with staggering.

**Comment by ezxyz** [comment]
Just to clarify, is the "add new text" and the "T+" shortcut button supposed to add the same style as pressing "Body Text" in the presets?

**Comment by swissspidy** [comment]
Seems like they should both do the same (not the case at the moment apparently), but I don't think they should use the preset as the base (since presets can be customized by the user in the future).

**Comment by ezxyz** [comment]
There's some mention of an "animation" is that still relevant?

**Comment by swissspidy** [comment]
That's about nicely animating newly inserted elements for improved UX, I believe.
Definitely something we can split out into a new issue once the animations are defined (and once we have a way to implement them)

**Comment by ezxyz** [comment]
Splitting it out sounds good. I'll consider animations outside of the scope of this bug.

**Comment by ezxyz** [comment]
Note as per slack discussion with @swissspidy we should split this part into a new issue:
>Default placement of text:
> text box width should be 360 wide (40 px gutter setting on each side) and dropped in centre. > Text should centre aligned. This is same for all text presets.

**Comment by ezxyz** [comment]
Also a correction to the spec on the text: According to figma it is:
>Regular, 16px, 24px line height, color #000, **left aligned**

**Comment by samitron7** [comment]
@jhtin and @swissspidy Just to clarify

1. It is the T+ button that adds text onto the page. That newly added text should be defaulted to **body text** (Roboto, Reg, 16px, 24 pb line height) 40px from left edge and center vertically.
2. In the future we'll allow the users to customize the text preset section and possibly also the  default text from the T+ button. I just don't know yet.
3. There is no prototype for this flow, just the Figma files and those are complete so I'm removing the ux label.

@swissspidy Why would this be a problem "Note that this somewhat conflicts with staggering."

**Comment by swissspidy** [comment]
> Why would this be a problem "Note that this somewhat conflicts with staggering."

@samitron7 Given this:

> It is the T+ button that adds text onto the page. That newly added text should be defaulted to body text (Roboto, Reg, 16px, 24 pb line height) 40px from left edge and center vertically.

What happens if I click this button five times? I assume the `40px from left edge and center vertically` only applies for the first time, and after that, staggering should occur? That's what I meant with "somewhat conflicts"

**Comment by jhtin** [comment]
Note: Can I remove myself from this since this work probably doesn't belong to the media pod?

**Comment by samitron7** [comment]
We should use the same staggering rules we set for images and videos [Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=7507%3A304080)

**Comment by csossi** [comment]
tested in PR#2379

According to Figma:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/342b5da3-3c85-41ba-8288-e67039674933)

Looks like site's off re: height and font size:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/a16ca7da-be83-4df1-aa9b-199ca5aba546)

(Note: padding from left edge and vertical centering are fine)

**Comment by miina** [comment]
@csossi Note that this issue was about vertical centering and padding only (point 1.) Point 3. was done in a separate issue and if there are issues with that, a new issue should be created.

(The testing instructions are in #2379).

Will merge this as the vertical centering and padding were OK.

**Comment by samitron7** [comment]
Verify in UAT but @jauyong do we need to file a ticket for the issue @csossi mentioned above?

**Comment by swissspidy** [comment]
Created #2665 as a follow-up, just in case.
