### ISSUE TITLE
Rotate Elements via Corners

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1208]
## Feature Description

As an author I'd like to be able to rotate elements via the corners and not just the top

@samitron7 to add details. 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. Buffer zone on corners for rotate state
2. See Canva

**Comment by samitron7** [comment]
[Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=9488%3A2187)
