### ISSUE TITLE
Hide Selection Box on Elements when Dragging

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1209]
## Bug Description

The blue selection box should be hidden when dragging elements. 

## Expected Behaviour
[figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=2625%3A4397)
![image](https://user-images.githubusercontent.com/5874851/79263656-3ab3a280-7e61-11ea-91e1-b16718497803.png)

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
@samitron7 to review this in relation to #1841

**Comment by samitron7** [comment]
To clarify, this issue is for text only [Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=8012%3A392241)

**Comment by swissspidy** [comment]
Testing is simple:

1. Add a Text Element
1. Drag it!
1. Don't see any selection box

**Comment by csossi** [comment]
Verified in QA

**Comment by samitron7** [comment]
Verified in UAT
