### ISSUE TITLE
Move Drop Target Messaging

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1211]
## Bug Description

The message overlaps with the arrow

## Expected Behaviour

@samitron7 to confirm 
1. hide the arrow when that image is there or add bg colour to message

## Screenshots

![image](https://user-images.githubusercontent.com/5874851/79263981-c6c5ca00-7e61-11ea-9145-da75158c1b52.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
Seems like a small fix, just need to define where to put the messaging so it doesn't overlap. 
**[Reference Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=4552%3A2315)**  doesn't specify expectation (hide arrow, or move message)

**Comment by samitron7** [comment]
As part of the FTUE, I would like to show the message only once. This flow will come once we start working on FTUEs holistically. For now, we can just show the message somewhere above the arrow.

**Comment by bmattb** [comment]
as per @samitron7  she will close this out and create a new, related, yet different ticket.
