### ISSUE TITLE
Add Colour Swatches for Overlay

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1213]
## Expected Behaviour

[See Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=6531%3A49)

## Screenshots

![image](https://user-images.githubusercontent.com/5874851/79264279-4f446a80-7e62-11ea-8a4c-ece59b44845c.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
@jauyong duplicate of #1207?

**Comment by jauyong** [comment]
closing due to duplicate
