### ISSUE TITLE
Do not Apply Existing Overlay After Masking

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1215]
## Expected Behaviour

Overlay should not be applied to newly masked image.

## Steps to Reproduce

1. Add a backgroun to a page
2. Apply linear overlay
3. Add another image as a mask

It should get rid of the linear overlay

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
This directly conflicts with instructions in #1207, that says the opposite - that background overlay should be retained when switching background image.

**Comment by miina** [comment]
Closing as this was confirmed to be correct behaviour.
