### ISSUE TITLE
A new post is by default scheduled in the future if user is ahead of UTC

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#1216]
## Bug Description

When you create a new post, it is by default scheduled in the future (at least if you're in the US).

It seems to be scheduled 4 hours in the future when in EST, which corresponds to UTC.

## Expected Behaviour

The initial timestamp for a new post should be created and/or interpreted in the correct timezone.

## Steps to Reproduce

* Change your timezone on your computer to be ahead of UTC (e.g. EST at UTC-04)
* Create a new post
* See that the "publish" button is actually labelled "schedule".
* Go to the document panel
* See that the publish date is set to 4 hours ahead of now.

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by cvolzke4** [comment]
After creating a new story in wordpress, getStoryById is used to load the unpublished story from wordpress.

getStoryById returns the story in wordpress format, which includes the 'date' field which is in the server timezone without a timezone qualifier, eg "2020-04-21T07:02:43":
https://developer.wordpress.org/rest-api/reference/posts#schema-date

To fix, the 'date_gmt' field that can be used instead:

    const getStoryById = useCallback(
      (storyId) => {
        const path = addQueryArgs(`${stories}/${storyId}`, { context: `edit` });
        return apiFetch({ path }).then((data) => {
          data.date = data.date_gmt + 'Z'; // in getStoryById, or somewhere else that makes sense
          delete data.date_gmt;
          return data;
        });
      },
      [stories]
    );

or where getStoryById is called from:

    getStoryById(storyId).then((post) => {
      const {
        :
        date_gmt,
        :
      } = post;
      const date = `${date_gmt}Z`;
