### ISSUE TITLE
Allow <Tab> to exit editmode

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#1232]
## Feature Description

Pressing <kbd>tab</kbd> should (also) exit edit mode, just as <kbd>esc</kbd> does today.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
This seems to need a decision first as per discussion in #1233. Perhaps this is even a wontfix?
