### ISSUE TITLE
Accessibility: Snackbar is not always noticeable

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#1239]
## Feature Description

Snackbar is currently displayed on top of Media and this leaves its visual accessibility out of our control.

It would be good to reconsider the position/style of the snackbar to improve its visibility.

For example:
<img width="1320" alt="Screenshot 2020-04-15 at 19 04 30" src="https://user-images.githubusercontent.com/3294597/79366168-023cc300-7f4c-11ea-9290-9451701871d3.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by samitron7** [comment]
@o-fernandez Can we icebox this and we'll fix all of this with the new visual design overhaul. Ignore message as it's in icebox - was not able to delete.

**Comment by samitron7** [comment]
Design for this has been completed awhile ago and part of the new visual design pass (FYI @BrittanyIRL)
[Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=1983%3A3)

**Comment by miina** [comment]
Closing as this got fixed as part of redesign.
