### ISSUE TITLE
Paste to Upload Media File is Adding Textbox with filename

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1242]
## Bug Description

1. After pasting, the file name is pasted as a textbox onto the page but I also see the file showing up in the library panel

## Expected Behaviour

1. After pasting, Instantiate a new element with the media asset on the current page.

## Steps to Reproduce

1. On your local copy a media file with cmd + C. e.g. movie.mp4. 
2. In the editor paste with cmd + v
3. Notice a textbox is added instead of the file.

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment]
@pbakaus per your message on #761 I was looking for outstanding feature for paste to upload and found this bug.

**Comment by swissspidy** [comment]
Is this a regression from #1105? cc @miina

**Comment by miina** [comment]
@swissspidy Looks like it!
