### ISSUE TITLE
Fullbleed and safe zones in the editor

### ISSUE THREAD

**Issue by dvoytenko** [GoogleForCreators/web-stories-wp#1244]
For context see [this document](https://docs.google.com/document/d/1ZF31jSP8BhhLU5Z4Amjfo45UkFUWMEBOTVziY4vursA/edit#).

A rough illustration:
![image](https://user-images.githubusercontent.com/726049/79398508-b4b55b80-7f35-11ea-80fd-fe6ed846b7de.png)

The key points:
* The canvas layout will be updated around the "fullbleed area" to be 9:16. We can redefine the breakpoints around 9:16 size.
* The current 2:3 "page area" is centered inside the "fullbleed area".
* The exact UI of fullbleed-vs-safezone is TBD. There will definitely be some clear design to communicate which part is overflowing.
* The "page area" for the most part functions exactly like it used to: the coordinate system, geometry, drop targets  - are all the same.
* The "fullbleed" will also function as a drop target for the background element.
* The background and fill elements will layout differently. They will always auto-size to "cover" the fullbleed area. We can either use the fullbleed area itself to layout these elements or the page area (with negative coordinates and width/height > 100%). The page area might be actually easier with all the edit-mode features, etc.
* There's no longer "Fit to device"/"Do not format" modes for background elements. All background elements are always fullbleed.
* Delete-when-moved-out-of-page feature will trigger when an element is fully outside the fullbleed area.

There will be a separate issue for output of the new mode.

**Comment by wassgha** [comment]
Closed by #1310
