### ISSUE TITLE
Fullbleed and safe zones in the output

### ISSUE THREAD

**Issue by dvoytenko** [GoogleForCreators/web-stories-wp#1245]
For context see: https://github.com/google/web-stories-wp/issues/1244

Prototype is https://jsbin.com/yobiyus/edit?html,css,output

Blocked on https://github.com/ampproject/amphtml/pull/27789

**Comment by dvoytenko** [comment]
[AMP format change](https://github.com/ampproject/amphtml/pull/27789) has been merged.

**Comment by dvoytenko** [comment]
Putting this in the Backlog as a replacement for https://github.com/google/web-stories-wp/issues/1058 which we indicated as critical.

**Comment by barklund** [comment]
@dvoytenko what's the status on this one? Is it just a tracking issue or does it come with actual work? If it needs implementation, can you update the description as to what work is actually required to complete this particular issue, so someone can pick it up?

**Comment by dvoytenko** [comment]
@barklund I need to retest and see if anything is outstanding. I'll try to do it by the eow.
