### ISSUE TITLE
Variable Fonts

### ISSUE THREAD

**Issue by davelab6** [GoogleForCreators/web-stories-wp#1260]
## Feature Description

Support Variable Fonts available from the css2 Google Fonts API, to take advantage of a wider variety of weights and styles. 

[VariableFonts.io](https://VariableFonts.io) and [variablefonts.typenetwork.com](variablefonts.typenetwork.com) explain some use cases and implementation patterns :)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Currently blocked by https://github.com/ampproject/amphtml/issues/27881 I think

**Comment by swissspidy** [comment]
Also useful docs: https://fonts.google.com/knowledge/using_type/loading_variable_fonts_on_the_web

Marking variable fonts as such & loading the right stylesheets should be rather trivial, it's just a question of how to expose variable fonts functionality in the editor.

@davelab6 Does the `webfonts/v1/webfonts` API endpoint declare whether a font is a variable font or not? At first glance it doesn't look like it.

**Comment by swissspidy** [comment]
Looks like we'd have to scrape https://fonts.google.com/variablefonts for now
