### ISSUE TITLE
Optimize template assets

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#1268]
## Feature Description

_(only relevant once we make more progress on templates)_

The [images](https://github.com/google/web-stories-wp/tree/1b755a46a8bea35778d4917a5fe91e8d0c1a47c5/assets/images/templates/travel) for the travel template are quite large, even after compression. **The plugin bundle is currently over 53MB**. And we're only gonna add more templates with more images.

Some things that we can do:

* [x] Do not include in plugin ZIP file as long as templates are not finished / exposed to user -> see #1267
* [ ] ~Use cropped images~
* [x] Host on website / offload to CDN 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment]
@pbakaus should this be part of:
1. 1.0 Beta
2. 1.0 Stable
3. Backlog

**Comment by barklund** [comment]
There's a fourth option here too:

4. Download the images (potentially from CDN) on first usage of template.

And that would definitely be my recommendation, as it's really the best of both world's: no penalty on bundle size, while you still get the files as local (as in local WP installation) assets once you start working with them.

**Comment by pbakaus** [comment]
These should be offloaded to a CDN.  We should not even 'download' them into the media gallery - we fully expect and recommend authors to switch them out anyway.

**Comment by pbakaus** [comment]
@jauyong stable for now.

**Comment by swissspidy** [comment]
We're using GitHub Pages as a CDN for now. But need to find something better soon.

**Comment by swissspidy** [comment]
Current status: trying to find the right place to host this
