### ISSUE TITLE
Fill button does not indicate status (toggle)

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#1292]
## Bug Description

When making an image full-bleed (fill), the button is not toggled

## Expected Behaviour

The button should show the current status

## Steps to Reproduce

1. Insert image
1. Mark as full-bleed
1. Notice that fullbleed button does not change status to indicate that the image is fullbleed.	

## Screenshots

Status quo (see button on the right)

<img width="269" alt="Screenshot 2020-04-21 at 16 51 31" src="https://user-images.githubusercontent.com/841956/79880683-a0b7a100-83f0-11ea-986e-dc7f39e6c768.png">

It should be marked "active" just like the alignment button here:

<img width="278" alt="Screenshot 2020-04-21 at 16 54 12" src="https://user-images.githubusercontent.com/841956/79880834-ce044f00-83f0-11ea-83a9-d4798d805608.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by obetomuniz** [comment]
@swissspidy What about flip controls? Should they also reflect the status when selected? 

![Kapture 2020-05-05 at 12 56 21](https://user-images.githubusercontent.com/1680157/81087283-e59f0580-8ecf-11ea-80c2-258c14da203a.gif)

**Comment by swissspidy** [comment]
@obetomuniz IIRC no. But I'll let @samitron7 confirm.

**Comment by samitron7** [comment]
Pascal is correct. It is not a toggle.
