### ISSUE TITLE
Rebuild media library with virtual list for Masonry Layout

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#1302]
## Feature Description

Using a library like [react-virtualized](https://github.com/bvaughn/react-virtualized) or [react-window](https://github.com/bvaughn/react-window), rebuild the media library to use a virtual list. Virtual list have some key performance improvements over infinite scroll style loading of media. 

Virtual list would still required the masonry layout with variable height images / video in two columns. The media library would also need to remain accessible, with keyboard navigation. 

**[Feature Brief](https://docs.google.com/document/d/1aZH_TI_be2t5Ywyqx4jcPTPdhFGEt7xh-uLzBp2AV4A/edit#heading=h.xqcejitqohdk)**
**[Design](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=2731%3A1757)**

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. Choose a library to use
2. The library should allow files in the media library to utilize a masonry layout
3. Once a library is decided on, we will need to regroup to decide how to proceed. (Meeting setup or document with info shared)

**Comment by spacedmonkey** [comment]
Other libraries I have found in my research. 
https://github.com/clauderic/react-tiny-virtual-list
https://github.com/developerdizzle/react-virtual-list

However, I believe we have to roll out own version of one of these libraries.

**Comment by dvoytenko** [comment]
Reposting from the Slack:

Small prototype: https://codepen.io/dvoytenko-the-flexboxer/pen/bGVBjrZ

Not fully a virtual list, but this idea can be combined with a virtual list if desired.

The structure is:

```
<div group style="height: [calculated]">
  <div column style="margin-top: -[offset]">
    <div cell style="width: W; height: [calculated with ratio]"></div>
  </div>
  <div column style="margin-top: -[offset]">
  </div>
</div>
<div group style="height: [calculated]">...</div>
<div group style="height: [calculated]">...</div>
```

Importantly, the group has a strict height and it also has contain: `layout size`  (but `not paint`). And thus, the contents of a group can be cleared out at any time we want.

Thus, the cost of this demo is `numberOfRecords / groupSize`. Not exactly a virtual list, but for `numberOfRecords` 10K, and a `groupSize` of 100, we need 100 `div`s.

An additional beneficial nuance: only the relative height calculation are done. Thus this approach is semi-responsive. It only needs a single value of the target cellWidth to rerender correctly. No recalculations need to be done since they do not depend on absolute values.

**Comment by diegovar** [comment]
With the performance improvements that Clint is working on, this may not be needed anymore. Additionally, are there use cases where the user would scroll through thousands of images instead of using the search box?

**Comment by merapi** [comment]
Attaching: [this thread](https://xwp.slack.com/archives/CCCAUAH6F/p1588585470214700) is pretty essential. We'll have a whole new layout (not sure if in Beta).

> are there use cases where the user would scroll through thousands of images instead of using the search box?

I think the virtual list solves other problems (other than context performance improvements will), one of them is not to load 100 or 200 images right away (`loading="lazy"` needs more browser support).

**Comment by merapi** [comment]
I'm leaving this issue for Media Pod.
Whoever will continue to work on the virtual list in new layout - feel free to ping me.

I tested all libraries [mentioned on Slack](https://xwp.slack.com/archives/CCCAUAH6F/p1588585470214700) and none of them is using a virtual list, so it looks like we still want to create something of our own (and use something like https://github.com/flickr/justified-layout for calculations).

**Comment by o-fernandez** [comment]
> With the performance improvements that Clint is working on, this may not be needed anymore. Additionally, are there use cases where the user would scroll through thousands of images instead of using the search box?

There's a UX component to this, and the new UI/layout (Masonry) is the approved UI moving forward. So this work still needs to be done. I'd say, not crucial for the Beta, good to have it for Stable.

**Comment by bmattb** [comment]
pulling this out of S32 as this item is in icebox

**Comment by dreamofabear** [comment]
This seems obsolete with the new media picker, closing.
