### ISSUE TITLE
Media Library Hover Menu to Edit Media Metadata

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1304]
## Feature Description

I want to be able to edit media metadata from the media panel
See #405 for metadata in the document panel

**[Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=4898%3A341)**

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. I should be able to edit metadata
2. As I hover over media in the media panel, I should get a dropdown menu with options for Edit and Delete  (See #26)

**Comment by swissspidy** [comment]
@jauyong was this spun out from #26? Should that one be closed?

**Comment by jauyong** [comment]
@swissspidy 
No, I was thinking this was to include the actual editing of metadata which can be triggered from a hover state. 
I will have to go through #26 now and see what is outstanding or if it can be closed.

**Comment by jauyong** [comment]
@swissspidy I just saw your[ comment here](https://github.com/google/web-stories-wp/issues/354#issuecomment-617185969)
if those can only be edited in the side bar is this modal no longer required? 
![image](https://user-images.githubusercontent.com/5874851/80026271-e12a2400-84af-11ea-8121-a643e334a596.png)
https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=4898%3A341

**Comment by swissspidy** [comment]
@jauyong I realized I misunderstood this. All good.

**Comment by jauyong** [comment]
closing this in favour of #354
