### ISSUE TITLE
Multiple select and delete

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#1328]
## Bug Description

Selecting multiple images element and pressing delete, does not remove elements.

## Expected Behaviour

All selected elements should be removed.

## Steps to Reproduce

Create multiple images. 
Select all images
Press delete.

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
This seems to only be happening on Linux. 
See video to show this is happening 
https://youtu.be/le65ceFe7hg

Multiple image do not delete.
Multiple videos do not delete.
Multiple image and videos together do not delete.
Multiple text elements, do delete. 
Multiple text,  image and videos together, do delete.

**Comment by spacedmonkey** [comment]
I am still seeing this issue - https://youtu.be/kqbOGye8cJg

**Comment by bmattb** [comment]
@o-fernandez can you confirm that this Linux issue warrants a P2 priority.

**Comment by o-fernandez** [comment]
> @o-fernandez can you confirm that this Linux issue warrants a P2 priority.

Good catch. No, this should be P3/P4. Let's track as P4 and see if we get more reports. 
Linux usage of our product is extremely low.

**Comment by swissspidy** [comment]
Is this still an issue?
