### ISSUE TITLE
Pasting elements and pasting text not cross-browser compatible

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#1330]
## Bug Description

Paste handler seems to trigger only in Chrome, trying to paste text or elements in other browsers (such as FF and Safari) does not work.

Looks like `useClipboardHandlers` needs adjustments.

Note that cutting and copying seem to work.

## Expected Behaviour
Pasting text and elements should work in all supported browsers.

## Steps to Reproduce
Case 1: Text pasting
1. Copy text from somewhere
2. Open the editor in FF or Safari
3. Click on canvas and Paste
4. See nothing happening

Case 2: Element pasting
1. Open the editor in FF or Safari
2. Create an element, select it and copy.
3. Try pasting.
4. See nothing happening

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
- Text pasting should work in all supported browsers
- Element pasting should work in all supported browsers.

**Comment by spacedmonkey** [comment]
I am seeing this console warning in firefox when I paste text. 
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in SingleSelectionMovable (at selection.js:52) react-dom.development.js:88
    React 5
    SingleSelectionMovable singleSelectionMovable.js:107
    useBatchingCallback useBatchingCallback.js:35
    batchedUpdates$1 React
    useBatchingCallback useBatchingCallback.js:35
    createKeyHandler index.js:222
    _fireCallback mousetrap.js:616
    _handleKey mousetrap.js:677
    handleKey mousetrap.js:1008
    _handleKeyEvent mousetrap.js:737
```

**Comment by spacedmonkey** [comment]
Pasting text in chrome on windows also does not work :(

**Comment by miina** [comment]
I suppose that pasting elements either then? Nor pasting images.

**Comment by spacedmonkey** [comment]
Just confirmed, no pasting is working in Windows Chrome. No pasting elements, no pasting text and no pasting images :(

**Comment by miina** [comment]
Started looking into this but looks like this is already working as expected now, possible due to moving the handlers to global level within #1475 

Closing as fixed. cc @jauyong
