### ISSUE TITLE
Dropping an unsupported file on Media Library crashes the editor

### ISSUE THREAD

**Issue by merapi** [GoogleForCreators/web-stories-wp#1342]
## Bug Description

Dropping an unsupported file on Media Library crashes the editor (Page works fine).

## Expected Behaviour

Should just show the error message (snackbar).

## Steps to Reproduce

Drop e.g. PDF file on **Media Library**

## Screenshots
![image](https://user-images.githubusercontent.com/21036224/80342980-66715800-8865-11ea-879d-8247ceb89671.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
This is a regression where I definitely expect some test(s) together with the bug fix.

**Comment by swissspidy** [comment]
@jauyong I think this should be in this sprint
