### ISSUE TITLE
Poor grammar in media upload failure message

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#1347]
## Feature Description

Currently the wording in the media upload file type error snackbar message reads as the following
```
Please choose only jpg, png, webm, mp4 to upload.
```

But grammatically it should read.

```
Please choose only jpg, png, webm or mp4 to upload.
```
---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by dvoytenko** [comment]
oxford commas!

**Comment by joannag6** [comment]
Maybe we could change the wording to something like:

"Accepted file types: jpg, png, webm, mp4"

so we don't have to worry about how other languages do conjunctions.

**Comment by BrittanyIRL** [comment]
wow this is an old ticket! I think to fix it we go with @joannag6 's idea: `Accepted file types: jpg, png, webm, mp4`
