### ISSUE TITLE
Load fonts using dynamic imports

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#1348]
## Feature Description

In effects to remove WordPress dependencies, use the bundled [fonts.json](https://github.com/google/web-stories-wp/blob/d181a4ea75cff53db730920fb41c41e2624a0c96/includes/data/fonts.json), over using the [Fonts](https://github.com/google/web-stories-wp/blob/d181a4ea75cff53db730920fb41c41e2624a0c96/includes/Fonts.php) REST API in the editor. 

Using a raw JSON file has a number of benefit.
- Less code to maintain. 
- Faster loading files. 
- No WP dependency.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

- Fonts are loaded asynchronously/lazily when the font picker is used for the first time, using dynamic imports (`import()`)
- There's no REST API for fonts anymore

## Implementation Brief

WP & infra pod:

- Remove the PHP for the Fonts API, including tests and the preloading part 
- Move `fonts.json` to `assets/src/fonts/fonts.json` so it can be easily accessed by the editor as well as by the script updating fonts
- Update location in script updating fonts

Prometheus pod:

- Use the `fonts.json` in the editor. 
- `fonts.json` is `import()`ed dynamically
- The dynamic import happens only when needed, e.g. when the font picker is rendered for the first time
- While fonts are loading, the font picker shows a disabled state

**Comment by swissspidy** [comment]
While working on #1273 I touched a lot of the `Fonts` and `Fonts_Controller` code and removed a bunch of things. Less and less work is now done server-side. Right now, in that PR, we basically do two things in PHP:

* Combine Google Fonts with a limited set of system fonts  
  -> could be easily done client-side or as part of the fonts.json file generation (i.e. part of automated tooling / `npm run download-fonts`)
* Normalize list of Google Fonts with weights, styles, variants, and fallbacks.
  -> could be easily automated and moved to tooling as well

If both things are handled by tooling, there's little need for the PHP part, and instead we could just use a dynamic `import()` to load all the available fonts directly from the JSON file.

**Comment by swissspidy** [comment]
I actually have something locally already that gets us halfway there. Will push soon.

**Comment by spacedmonkey** [comment]
Currently the fonts.json is 161kb. It is pretty large considering, that users wil likely only use a very tiny subset of fonts with a story. I am not sure it is the best idea to bundle the whole json file with javascript bundle. 

I like to find a way to lazy load the json file after the editor has loaded. I am going to take a quick look into this.

**Comment by swissspidy** [comment]
@spacedmonkey That's why I mentioned dynamic `import()` above and marked this issue as blocked by #868. With dynamic imports wee would load the JSON file asynchronously at runtime when needed. No need to include it in the bundle for sure.
