### ISSUE TITLE
CORS issues are breaking the Font Picker

### ISSUE THREAD

**Issue by obetomuniz** [GoogleForCreators/web-stories-wp#1382]
## Bug Description

Some fonts when selected are not working (screenshot below).

**Note:** Some fonts are still working (e.g. Risque, Roboto, etc...)

## Expected Behaviour

CORS issues should be fixed.

## Steps to Reproduce

- Add a text element
- Select font "Roboto Condensed"

## Screenshots

![Kapture 2020-04-29 at 15 56 26](https://user-images.githubusercontent.com/1680157/80646106-8316b700-8a42-11ea-8159-58d2bc0feb14.gif)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
I don't exactly see why this is happening now, or why this wouldn't have been happening before.

The HTML that gets added looks like this:

```html
<link
  id="roboto-condensed-css"
  href="https://fonts.googleapis.com/css2?display=swap&amp;family=Roboto+Condensed%3Aital%2Cwght%400%2C300%3B1%2C300%3B0%2C400%3B1%2C400%3B0%2C700%3B1%2C700"
  rel="stylesheet"
  type="text/css"
  media="all"
  crossorigin="anonymous"
>
```

**Comment by dvoytenko** [comment]
That doesn't looks like a CORS error. It's a simply 400 - i.e. something is wrong with the URL. The CORS error is simply because the service is not allowing you to read the error response code - that's rather common.

**Comment by swissspidy** [comment]
Oh, makes sense! Now I know where to look 👀

**Comment by swissspidy** [comment]
See #1385 for a fix!
