### ISSUE TITLE
Custom Calendar Styling

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1391]
## Feature Description

This is a followup to #789 which is a short term solution for the Beta Release. 
Once a calendar is implemented we will need to style it according to the [designs](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=6113%3A618)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
1. The calendar should match the [designs in Figma ](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3408%3A85035)

**Comment by miina** [comment]
Note: It would be good to confirm if we're going to reuse the WordPress calendar style again (as it is in Figma currently), or use something custom -- since we're going to use a custom calendar anyway now and not a copy of WP implementation.

**Comment by swissspidy** [comment]
Pinging @samitron7 to confirm, but I don't think it makes sense to use WordPress styling anywhere in the editor.

**Comment by samitron7** [comment]
Yeah, no WP styling but this is probably a low priority thing. Adding to visual design request.

**Comment by samitron7** [comment]
Figma file is attached in description and [here](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3408%3A85035) as well

**Comment by bmattb** [comment]
@samitron7 after review the eng team requests that the other views to also be included:
1. Year view
2. Month view 
3. Century view

**Comment by barklund** [comment]
Here are the 4 views of the current calendar component, that all need a design. Note that the first is designed at the three latter are very similar:

| | Month | Year | Decade | Century |
|-|-|-|-|-|
| Current design | ![Screen Shot 2020-11-18 at 11 01 20](https://user-images.githubusercontent.com/637548/99555088-eab83380-298d-11eb-88fd-59603a48b917.png) | ![Screen Shot 2020-11-18 at 11 01 01](https://user-images.githubusercontent.com/637548/99555084-ea1f9d00-298d-11eb-9c2a-9c4f0a9ed1ae.png) | ![Screen Shot 2020-11-18 at 11 01 07](https://user-images.githubusercontent.com/637548/99555085-ea1f9d00-298d-11eb-9ece-efb5db5017eb.png) | ![Screen Shot 2020-11-18 at 11 01 13](https://user-images.githubusercontent.com/637548/99555086-eab83380-298d-11eb-955c-c706ec9c2ceb.png) |
| New design | ![Screen Shot 2020-11-18 at 11 04 28](https://user-images.githubusercontent.com/637548/99555090-eb50ca00-298d-11eb-97ac-7cb4c5ac6215.png) | _missing_ | _missing_  | _missing_  |

**Comment by barklund** [comment]
Also, what do the highlights for _today_ and _current selection_ look like? In the current editor, _current selection_ is the blue background, where _today_ is the yellow background. This is present in all views:

Monthly view with current selection as 19th where today is 18th:
![Screen Shot 2020-11-18 at 11 07 47](https://user-images.githubusercontent.com/637548/99555491-62865e00-298e-11eb-950c-ea59dca5e80a.png)

Yearly view with current selection as October where today is November:
![Screen Shot 2020-11-18 at 11 07 56](https://user-images.githubusercontent.com/637548/99555492-631ef480-298e-11eb-8537-3c506d9cf366.png)

The above design only has a single color for highlight - is that supposed to represent _current selection_ only and no highlight for _today_?

**Comment by samitron7** [comment]
OMG...not trying to defend myself here, but I had NO idea to click on the month to get to the other view. Do we know if users actually use the other views? UI is not too friendly plus you can use the inner arrow to navigate month and outer arrow to navigate year. I prefer to hide that functionality and avoid additional work. @o-fernandez thoughts and for context, this is a pure visual restyle of the WP calendar?

I added the current selection state to Figma (also fixed the active color. FYI @BrittanyIRL is implementing the design language so the normal, hover, focus and active state should apply to the calendar. Only button state that is special to the calendar design is the outline circle. This pattern does not exist elsewhere. Please ping her for details on button states.)

**Comment by barklund** [comment]
> OMG...not trying to defend myself here, but I had NO idea to click on the month to get to the other view.

It is a bit secret, yes.

> Do we know if users actually use the other views?

I have no idea. I don't think we log that.

> UI is not too friendly plus you can use the inner arrow to navigate month and outer arrow to navigate year. I prefer to hide that functionality and avoid additional work. @o-fernandez thoughts and for context, this is a pure visual restyle of the WP calendar?

We can [definitely](https://github.com/wojtekmaj/react-calendar#user-content-props:~:text=minDetail) disable the year, the decade, and the century view, if desired. I don't think people often schedule posts for next decade, so we're probably in the clear for this one. As long as we don't use it for birthdates or similar, month-only view is probably fine.

**Comment by o-fernandez** [comment]
I'm totally fine disabling year/decade/etc. Seems like an edge case.

**Comment by samitron7** [comment]
@barklund Let's just start with the view that I provided (ie month). We can disable year, decade and century. If request comes in for year we can react to that later.
