### ISSUE TITLE
Enable autosave for published stories

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#1402]
## Feature Description

Currently, per #221 we disable autosave for published stories. The proposed change here is: 

- When user makes changes after they open the published story, we autosave to a second file (doesn't overwrite published post) every 60 seconds (same interval). 
- User can push changes live by triggering "publish/update" button
- User can trigger "Discard changes/revert to published version" option if they want to ignore any changes made after the last publish

The proposed UX changes are (need finalization before ticket moves to eng queue): 

- Add a "discard changes" or "revert to published" button/option in the UI for published posts with changes
- May want some other way to show in WP (in the editor, stories dashboard, etc.) whether a published story has unpublished changes in draft. 
- We may want to change the buttons nomenclature, we currently closely follow the WP article/page editor and replace "save draft" with "switch to draft" for publish stories, but in this scenario that wouldn't make as much sense since users would still be able to keep a working draft. In that case we think that having the 3 main buttons continue to be "save as draft", "preview" and "Update/publish changes" could be good, and we'd want to move the "unpublish/switch to draft" option and add "discard changes/revert to published" to some "other options" menu (maybe a drop down arrow next to update/publish). 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
A brief summary of how autosaves/revisions work in WordPress:

(I recommend trying it yourself to get a better feeling for it)

1. Create a new post (as `post` post type)
2. The WIP post is periodically saved to both session storage and the database (if online)  
    * If the post is still a draft, this just means updating the currently edited post.
    * If the post is already published, this will create a new autosave (`revision` post type, referencing the `post`)
  Note: See #3842 for details on local autosaving
3. If someone else is taking over editing from you and locks you out of the editor (see #6055 for story locking), the same applies. Your changes will be saved so you don't lose anything.

Let's say you edit a post, save it, and then make some changes again.

If you later open the editor, you might get a message like this (depending on whether the changes were saved to session storage or the database:

![Screenshot 2021-12-07 at 23 08 25](https://user-images.githubusercontent.com/841956/145122489-43355406-1018-424d-a5cc-e7f6cce6a0dc.png)
![Screenshot 2021-12-07 at 22 11 55](https://user-images.githubusercontent.com/841956/145122502-490e59b3-e40c-4cdd-add5-45da117fe5f3.png)

Clicking on the review link will lead you to a WP UI to compare changes in a diff view:

![Screenshot 2021-12-07 at 22 18 43](https://user-images.githubusercontent.com/841956/145122532-bb4ebd9b-69db-4dbb-9f8a-448266d34db9.png)
 
Here's where the implementation in the story editor differs:

1. No offline detection / message
  -> **Needs UX**
2. We don't save to session storage.
  That means you can easily loose content.
  This would be relatively easy to implement, see #9859
3. We don't autosave if the post is already published
  This is easy to fix, just need to remove the status checks here:
  https://github.com/google/web-stories-wp/blob/c249b1ff3ec580a51f6e5bf64a089d93230acfc7/packages/story-editor/src/components/autoSaveHandler/index.js#L47-L70
4. We don't show any message if there is an autosave
  -> **Needs UX**
5. We don't autosave when someone takes over editing

cc @choumx @gajasinski @aaskedall @agingoldseco for thoughts & prioritization

**Comment by swissspidy** [comment]
Ona difference I forgot to mention above:

In Gutenberg, when you create a new post, that post will be periodically _autosaved_ as an autosave, not a "proper" save. 
In our editor, we currently incorrectly always do "proper" saves, which quickly leads to the posts list being polluted:

![Screenshot 2021-12-14 at 22 54 35](https://user-images.githubusercontent.com/841956/146085512-65910106-56bf-40f8-ac1a-2dddd32ce933.png)

To fix this, we simply need to remove the `updateFunc` check here and always use `autoSave`:

https://github.com/google/web-stories-wp/blob/eb22fc727405eadad3b5f25d15dff3d8aa9039f5/packages/story-editor/src/components/header/buttons/preview.js#L112-L127

**Comment by swissspidy** [comment]
@agingoldseco Would love your input here

All we basically need is UX for this kinda message:

![Screenshot 2021-12-07 at 23 08 25](https://user-images.githubusercontent.com/841956/145122489-43355406-1018-424d-a5cc-e7f6cce6a0dc.png)
![Screenshot 2021-12-07 at 22 11 55](https://user-images.githubusercontent.com/841956/145122502-490e59b3-e40c-4cdd-add5-45da117fe5f3.png)

**Comment by barklund** [comment]
My thoughts on the goal of this ticket (which should probably be split into multiple tickets).

## New flow

### Editor changes

#### Working on an unpublished draft of a published story
When you publish a story and keep working, or if you load an already published story and start working on it, the header changes to the following options:
<img width="301" alt="Screen Shot 2022-08-24 at 13 27 02" src="https://user-images.githubusercontent.com/637548/186407140-c8736972-0be7-41d9-ab11-7bb69f887676.png">

- The preview button will preview the current draft of the story.

- The save button saves the current draft as an autosave (and only as that) so the changes are persisted to the database but not published (the published story remains unchanged).

- The update button works as today. If you press the update button the published story is updated to match the current draft (and the current draft is discarded / the revision is deleted).

- The options button at the end will open a small dropdown menu with three extra buttons:
  - Preview published story
  - Revert to published story / discard draft
  - Convert story to draft / unpublish story

All of these extra buttons have some underlying technical consequences, that we can always discuss, but I'm not sure how much we should reveal to the user about what those consequences are.

---

#### Loading a published story with an autosave
When you open a published story in the editor, that has an autosave newer than the published version the story, currently this dialog is displayed:
<img width="537" alt="Screen Shot 2022-08-24 at 13 06 10" src="https://user-images.githubusercontent.com/637548/186403608-3d8bbb44-b932-4dc3-a062-f8aa669400ef.png">

The "View the autosave" button is pretty useless though, as it takes you to a diff view of the underlying JSON changes, which is far too technical to be useful.

I propose we instead display something like this dialog:
<img width="784" alt="Screen Shot 2022-08-24 at 13 05 56" src="https://user-images.githubusercontent.com/637548/186403778-6bc93bc9-57ee-4e79-924c-c6d567c2ec6f.png">

Here you can open previews for the published story and autosave for comparison (it does require that you manually check the differences, but it is a lot more useful that the JSON diff view at least.

We could add additional information to this dialog such as "autosave last modified on July X by Author Y" and maybe even some metadata about said changes: "The autosave includes changes to story metadata, page 3, and page 8".

If you click the last button, "keep working", the autosave is loaded in the editor as in the above scenario where you keep working on an unpublished draft of a published story.

---

### Dashboard changes
We need to highlight that a given published story has an unpublished autosave somehow. Suggestions are welcome, but a simple solution would be something as beautiful as this:
<img width="215" alt="Screen Shot 2022-08-24 at 12 55 17" src="https://user-images.githubusercontent.com/637548/186401914-43e6677f-1832-4c18-aa9e-c09a0bc4463d.png">

If the user wants to see or restore with the autosave, they have to click on the story and go into the editor.

We could however add a new option to the options menu to directly discard the autosave without going through the editor?
<img width="367" alt="Screen Shot 2022-08-24 at 12 56 00" src="https://user-images.githubusercontent.com/637548/186401883-a36e1513-29e4-4c4f-a17c-43322a3b9ad6.png">

---

## New API
To support the above flow, we need to extend the API between WP and the editor a bit.

When a story is loaded in the editor, the config is extended with a new field, `autosave`, which defaults to null is no autosave exists for the current story. However, if an autosave exists, the value will be something like:

```js
{
  ...,
  autosave: {
    revision_id: "<id>",
    last_modified: "<timestamp>",
    author: "<author name>",
    preview_link: "<URL>",
  }
}
```

We then also extend the API with a new endpoint to retrieve a revision as well as delete one: `/web-stories/v1/revision/`.

I don't think we need an API to "restore story from revision" (even though WP has that as a built-in function) as we would handle that manually in the editor by simply overwriting the story data with the data from the autosave. I guess the WP function to restore from revision also deletes the revision, but we could also do that manually when the user chooses to republish.

---

Ping @swissspidy, @timarney, @merapi, @miina for input.

**Comment by barklund** [comment]
@swissspidy, it seems that this ticket is completely useless at this point, no? Do you want to keep it around, re-purpose it, or just close it?
