### ISSUE TITLE
Opacity must be removed/reset when image is set as background

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#1404]
## Bug Description

When the user triggers "Set as Background" in the design panel, the opacity of the element should be reset to 100%. Unfortunately, that's not happening when using the "Set as Background" function. 

Note: It **does** work properly if I drag the the image to the blue-zone border to set as background. Just not when triggering the same function via the Design panel. 

## Expected Behaviour

Expected: image should be set as background without any opacity, opacity is not supported for backgrounds. 

## Steps to Reproduce

Steps to reproduce: 
- Add image to a story
- Change opacity to a <100% value (e.g., 50%)
- Click on "Set as Background" option

## Screenshots

Actual result: seeing background with weird transparency grid going on.

![image](https://user-images.githubusercontent.com/13389997/80710902-7c795580-8abd-11ea-86b8-8ba0906c431f.png)
---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Previously: #739
