### ISSUE TITLE
Undo (CMD-Z) not restoring deleted background image

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#1405]
## Bug Description

Undo should revert my last update. If I delete the background of a page, this is not working. 

## Expected Behaviour

The background should be restored if I trigger an undo right after deleting the background. 

## Steps to Reproduce

1. Delete background image on a page
2. Trigger cmd+z (undo)

## Screenshots

Hard to show, as it's all keyboard stuff. 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
NOTE: CMD+Z also does not "set as background" the image if I press it right after I trigger "remove as background", so it's not limited to just deleting the background.

**Comment by jauyong** [comment]
groomed on may 13. ready to sprint planning

Morten has  PR that may fix this.

**Comment by barklund** [comment]
Duplicate of #1191
