### ISSUE TITLE
Confirm behavior when reordering pages

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#141]
As discussed at https://github.com/ampproject/amp-wp/pull/4048#pullrequestreview-349088343, when reordering pages (in the carousel _or_ grid view), the reordered page is being set as the current  page automatically.

We need to confirm whether this is desired behavior or not.

Relevant code section:

https://github.com/google/web-stories-wp/blob/7b1ed5c25b9bfd9b101217193dbcfe23d5849bb2/assets/src/edit-story/components/canvas/draggablePage.js#L52-L64

**Comment by jauyong** [comment]
pinging @samitron7 for an update on this.

**Comment by swissspidy** [comment]
This was confirmed to be OK like this on Monday's meeting.
