### ISSUE TITLE
No easy way to remove image from shape

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#1410]
## Feature Description

UX consideration:
- It was unclear to me what would happen if I dragged a shape (with a picture in it) onto another shape - unexpectedly the shape I dragged was "swallowed up" by the other shape and its image transferred. 
- After I added an image to a shape I don't seem to have an easy way to "free up" the image from the shape (e.g., changed my mind and want the image to come out of the shape)

**At a minimum, I'd like a way to reset the image to no longer be in the shape (free up the image!).** 

Would consider these as UX areas for possible improvement. Filing for UX consideration. Video attached.
[Drag a shape into another shape.zip](https://github.com/google/web-stories-wp/files/4558935/Drag.a.shape.into.another.shape.zip)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by dvoytenko** [comment]
/to @samitron7, but this is intentional I believe. I think the idea is that Undo can always be used to revert.

**Comment by jauyong** [comment]
For point 2 see #833

**Comment by o-fernandez** [comment]
Closing in favor of #833
