### ISSUE TITLE
Inconsistencies in "set as background" option cropping image

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#1411]
## Bug Description

When I set an image as background by clicking "Set as background" in the Design panel vs. if I drag the image to the edges of the canvas, then "Remove as background" the behavior is different. Sometimes the image shows as cropped others as not. **Setting as background should NOT crop the image regardless of the method.** 

## Expected Behaviour

No matter how I "Set as background" (whether design panel or dragging to canvas edge) the "remove as background" result should be the same. 

## Steps to Reproduce

However, what I observe is the following: 
1. Set as background on Design panel -> remove as background -> image shows again and it is not cropped **(expected, OK)**
2. Drag to canvas edge to set as background -> remove as background -> image shows cropped as a square **(not expected)**

## Screenshots

Video: 
[Set as background crop vs. not.zip](https://github.com/google/web-stories-wp/files/4559002/Set.as.background.crop.vs.not.zip)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## QA Instructions
See #1821.

**Comment by diegovar** [comment]
Apparently this will be fixed by a current refactor that's ongoing, so unassigning.

**Comment by miina** [comment]
@diegovar Could you confirm which ongoing refactor is this part of and who is working on it?

(Want to assign the right person :) Thanks!)

**Comment by miina** [comment]
@barklund Looks like #1798 fixes this indeed (although it's currently broken in the PR but based on code it looks like it will fix this, once the PR gets fixed). Assigning to you for clarity.

**Comment by csossi** [comment]
@miina , when I execute the following:
2. Drag to canvas edge to set as background -> remove as background -> image shows cropped as a square (not expected)

it works fine now (not being cropped), but the placement after doing this often extends beyond page like so:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/2f0f6d82-32d8-4409-beba-e66647115bd8)

reassign back to you, or a new ticket for this?

cc @barklund

**Comment by csossi** [comment]
Verified in QA
