### ISSUE TITLE
Pull in Style Presets from the used Template

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#1416]
## Feature Description

Currently, the Style and Color presets in the Design Panel are only the global presets generated but the user, however, when a template is used, the presets should be pulled in from the templates as well.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

- The presets are set from the templates without having to use a template first (e.g. added once, together with the template initiation)
- The presets are global and pulled in from all the templates
- The presets are pulled in for both colors and also styles, even if the color exists inside a style, too. E.g, a text element in template which has blue background and red text will generate one color preset with red text and one style preset with blue background + red text.

**Comment by swissspidy** [comment]
Closing in favor of #7449
