### ISSUE TITLE
Adding a Text element to a New Story in the Editor, crashes the editor!

### ISSUE THREAD

**Issue by mariano-formidable** [GoogleForCreators/web-stories-wp#1417]
## Bug Description

If you open up the editor to a new (or existing) story, and simply click on the Text tab to add in a text element, the editor immediately crashes to a blank screen.

NOTE:  This happens in the staging editor too (or latest master).

## Expected Behaviour

Clicking to add a text element, should just add the element to the active page... no crashing.

## Steps to Reproduce

1.) Navigate to a "New" story.
2.) Click on the plus next to the "T" to add in a text element.

## Screenshots

Animated gif of the crash happening:
![editor_crash](https://user-images.githubusercontent.com/40646372/80745280-e81aed00-8ad4-11ea-896c-49718c1329c3.gif)

Screen shot of errors in console:
![image](https://user-images.githubusercontent.com/40646372/80745312-f36e1880-8ad4-11ea-86d2-9671040cf384.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
I think this might be fixed by #1413

**Comment by mariano-formidable** [comment]
> I think this might be fixed by #1413

Yup, I just pulled the latest and everything is working again!  Thanks

**Comment by mariano-formidable** [comment]
This was fixed by #1413
