### ISSUE TITLE
Clearing opacity input autofills 100, but autofilled value doesn't get apply if I press enter or click away

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#1419]
## Bug Description

Clearing opacity input autofills 100, but autofilled value doesn't get apply if I press enter or click away

## Expected Behaviour

Expect that if I press enter while seeing 100 populated in the opacity, it will get applied. 

This doesn't happen if I clear the opacity value, wait for the opacity to autopopulate 100, and press enter or clicka way. 

## Steps to Reproduce

1. Open a story
2. Add a shape
3. Set opacity value to non-100 (e.g., 50%) and press enter
4. Now clear the opacity value, wait for 100 to autofill, then press enter OR click away

## Screenshots

[autofilled 100 opacity value doesn't stick.zip](https://github.com/google/web-stories-wp/files/4560890/autofilled.100.opacity.value.doesn.t.stick.zip)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

#### Explicit set to 0
1. Add an element to a page
1. Click to edit element opacity
1. Input "0" using keyboard
1. Blur the input field and observe the element now having opacity 0 (both visually on canvas and numerically in input field)

#### Explicit set to 100+
1. Add an element to a page
1. Click to edit element opacity
1. Input "110" using keyboard
1. Blur the input field and observe the element now having opacity 100 (both visually on canvas and numerically in input field)

#### Clear text field
1. Add an element to a page
1. Click to edit element opacity
1. Input 40
1. Then clear the text contents
1. Blur the input field and observe the element now having opacity 40 (both visually on canvas and numerically in input field)

#### Navigate to 0
1. Add an element to a page
1. Click to edit element opacity
1. Input "10" using keyboard
1. Press down arrow on keyboard until 0 is reached and press a few more times observing, that input does not go below 0
1. Blur the input field and observe the element now having opacity 0 (both visually on canvas and numerically in input field)

#### Navigate to 100
1. Add an element to a page
1. Click to edit element opacity
1. Input "90" using keyboard
1. Press up arrow on keyboard until 0 is reached and press a few more times observing, that input does not go above 100
1. Blur the input field and observe the element now having opacity 100 (both visually on canvas and numerically in input field)

**Comment by csossi** [comment]
Verified in QA
