### ISSUE TITLE
Arrow keys in edit mode move the outer element, not the mask

### ISSUE THREAD

**Issue by pbakaus** [GoogleForCreators/web-stories-wp#1426]
## Bug Description

Arrow keys in edit mode move the outer element, not the mask

## Expected Behaviour

Arrow keys in edit mode should reposition the inner image/video, not the outer element.

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by wassgha** [comment]
Duplicate of #1426 , already has PR #2108
