### ISSUE TITLE
Dropdown positioning 

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#1432]
## Bug Description
If you open a dropdown then close it. The close a the layer panel and reopen the dropdown, the dropdown is in the wrong position. 

## Expected Behaviour

Dropdown should be in the correctly position. 

## Steps to Reproduce

- Open a font weight dropdown.
- Select a weight. 
- Close layer panel.
- Reopen font weight dropdown.

## Screenshots
<img width="300" alt="Screenshot 2020-05-01 at 13 33 02" src="https://user-images.githubusercontent.com/237508/80805820-ec1c3d00-8bb0-11ea-81b8-e633fb9435c3.png">

**Comment by swissspidy** [comment]
Could the work done in #1060 help here?

**Comment by spacedmonkey** [comment]
> Could the work done in #1060 help here?

I think that it would be fixed by #1060. Does anyone know the state of that PR?

**Comment by o-fernandez** [comment]
#1060 seems to have been merged, @csossi can you test this in master/release environment? Given that it was merged prior to the new QA process?

**Comment by csossi** [comment]
@o-fernandez - Unable to test this on Master due to https://github.com/google/web-stories-wp/issues/1990

**Comment by csossi** [comment]
Verified in QA:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/a503d4d1-61c3-4dbc-9015-f7581d4be7f1)

![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/1e34ad85-9e5e-4e18-8dbb-59a37c874b52)

**Comment by samitron7** [comment]
Verified in UAT
