### ISSUE TITLE
Color Picker - Remove Conic Gradient

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1433]
## Feature Description

Per this discussion on[ Slack with Sam](https://xwp.slack.com/archives/CCCAUAH6F/p1588279028158100?thread_ts=1588262974.144900&cid=CCCAUAH6F), we will temporarily remove the Conic Gradient

#1389 will be picked up at a later date

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. The conic gradient is removed from the editor
2. Note if helpful for future work, save the conic gradient code as we may add it back later

**Comment by jauyong** [comment]
FYI @pbakaus @o-fernandez

**Comment by pbakaus** [comment]
Can you paste the discussion inline here? I'd love to understand the reasoning here. /cc @samitron7

**Comment by o-fernandez** [comment]
@pbakaus here was the rationale in the thread: 

> It's hard to get good visual results from it and one of things we are trying to do is prevent misuse of things that can result in subpar visual qualities. same reasons why we decided to not allow for text dropshadow

**Comment by pbakaus** [comment]
OK! I'll say that this was my go-to example to demonstrate a cool gradient, but @samitron7 disagrees, and I don't care too strongly :) Fine by me.
