### ISSUE TITLE
Media gallery weirdly drops lots of items when a video is used as background

### ISSUE THREAD

**Issue by pbakaus** [GoogleForCreators/web-stories-wp#1447]
## Bug Description

Somehow the media gallery wipes out all videos but one when a background video is used.

## Expected Behaviour

Media...should stay in the media gallery..

## Steps to Reproduce

1. Click on "Video" filter in media tab
2. **Drag any video into the background** of the current page
3. Observe how all videos but one in the media tab vanish. (Can vary, depends on your media list).

After you set the video as a background it fetches the media list (reset?) and then because of video filter you just see videos from the first page of all items (not from the first page of videos like initially).

## Screenshots

![image](https://user-images.githubusercontent.com/43004/80845998-cf3b3600-8bbf-11ea-9bcb-a86868894882.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
1. After dragging media to the page, the media library should not change (it is currently getting filtered)

**Comment by miina** [comment]
Note: the additional request seems to happen with images as well, not just the videos.

**Comment by miina** [comment]
One more finding:
It actually seems to happen in case of any drop targeting and not just when setting as a background.
