### ISSUE TITLE
Feature flags

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#1464]
## Feature Description

Have a method to have features merged into master but disable / hidden via a feature flag. 
This would allow developers to merge incomplete work while not showing it to users.

**Comment by diegovar** [comment]
There seems to be several nom packages providing support for feature flags:

https://www.npmjs.com/package/flagged
https://www.npmjs.com/package/react-feature-flags

flagged is particularly interesting as it provides support for HOC and hooks, and seems more powerful in general.

**Comment by swissspidy** [comment]
flagged looks simple enough 👍

Would be trivial to connect this with our build tooling too, i.e. to create ZIP files with certain features enabled for sharing with testers.

**Comment by spacedmonkey** [comment]
I have created a follow up ticket this one to add a UX to feature flags. 
https://github.com/google/web-stories-wp/issues/1738
