### ISSUE TITLE
Safezone makes canvas too big; hides page menu and carousel

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#1467]
## Bug Description

Caused by #1310.
See #1244.
See #1245.

## Expected Behaviour

Due to the safe zone that is being displayed above and below the page, the canvas pushes down the carousel, and makes it practically invisible on a "smaller" screen (tested on 15 inch MBP).

## Steps to Reproduce

1. Open editor
1. Notice partially hidden page menu
1. Notice hidden carousel

## Screenshots

<img width="1679" alt="Screenshot 2020-05-04 at 13 17 24" src="https://user-images.githubusercontent.com/841956/80960844-f9803400-8e09-11ea-9d02-75827c648a7f.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
cc @wassgha

**Comment by wassgha** [comment]
Hmm @dvoytenko  did this happen before on 16:9?

**Comment by dvoytenko** [comment]
/to @wassgha let's address right away while it's fresh.

**Comment by dvoytenko** [comment]
Not that I know of, it did some measurements/calculations to ensure min-height.

**Comment by dvoytenko** [comment]
To correct my statement: there's a min-max calculation in the canvas/layout.js to avoid this issue specifically. My guess, simply, it needs to be adjusted for the new aspect ratio.
