### ISSUE TITLE
Aligning element while editing text crashes the editor

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#1483]
## Bug Description

Clicking on an element alignment trigger while in text edit mode crashes the editor. 

## Expected Behaviour

Element should be properly aligned within the page. Editor should not crash. 

## Steps to Reproduce

1. Add a text element to the page
2. Double click to enter text editing mode, maybe select a word/subset of the text, not sure if it matters. 
3. Click on the element align options (e.g., alight right)

## Screenshots

Video attached
[Align element while in text edit mode crashes editor.zip](https://github.com/google/web-stories-wp/files/4576950/Align.element.while.in.text.edit.mode.crashes.editor.zip)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by ndev1991** [comment]
@o-fernandez What is the expected behavior here? The text should be in edit mode when it aligns? Or exit edit mode?

**Comment by o-fernandez** [comment]
P0 for me is that it aligns the element and the editor doesn't crash. I'm totally fine if it exits edit mode as the user is triggering a function that's unrelated to text editing. 

@samitron7 for your comments in case you have any specific UX concern here. Note that I was in text edit mode and triggered an **element** align change, not text alignment change.
