### ISSUE TITLE
Entire page is getting hidden when editing text box

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#1484]
## Bug Description

When I edit text, the entire page turns white and all else is hidden. 

## Expected Behaviour

Editing text in the text element should not impact the display of anything on the page outside of the text element.

## Steps to Reproduce

1. Set some background to a page (or add other elements)
2. Add a text element
3. Edit the text in the text element

## Screenshots

Video
[Bg turns white when editing text.zip](https://github.com/google/web-stories-wp/files/4576987/Bg.turns.white.when.editing.text.zip)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@o-fernandez Could you confirm if this still happens for you? Tried to reproduce but without luck.

**Comment by o-fernandez** [comment]
Can't reproduce, will close this ticket given that.
