### ISSUE TITLE
Stories logo in left nav

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#1485]
We are currently missing the logo in the Dashboard. 

Requires UX to get image to Dashboard team 
![left nav hover state.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/3ba5fc2e-4575-4072-9474-88115f5ad363)
Acceptance Critera: 
- Story logo in nav

**Comment by jauyong** [comment]
@o-fernandez to check email thread regarding name / logo

**Comment by o-fernandez** [comment]
@samitron7 as discussed this can be a simple text/typefont "logo" that just says Web Stories. Can add a simple icon if that's desirable, but not necessary.

**Comment by samitron7** [comment]
Eng - Let's temporarily add the text WEB STORIES (Roboto) till I can get to this.

**Comment by o-fernandez** [comment]
> Eng - Let's temporarily add the text WEB STORIES (Roboto) till I can get to this.

Given this, let's create a new issue when there's another logo. For now, WEB STORIES in Roboto it is instead of the logo image.

**Comment by BrittanyIRL** [comment]
How's this look?  @samitron7 

<img width="428" alt="Screen Shot 2020-05-20 at 2 44 28 PM" src="https://user-images.githubusercontent.com/10720454/82501233-c5fc0580-9aa9-11ea-83c3-2d7e714c1350.png">

**Comment by csossi** [comment]
Verified in QA
