### ISSUE TITLE
Expect left to right in the gradient component to correspond to top to bottom on the canvas, but it showed the opposite

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#1487]
## Bug Description

When selecting color gradient in the color picker, I expected the color on the left of the gradient to be at the top of the page, and the color set at the right of the picker to correspond to the bottom of the page. (So rotating the picker 90 degrees clockwise would correspond to the canvas color). In reality the opposite happened. 

## Screenshots

![Direction in picker seems reverse from page (expected left to right to correspond to top-bottom)](https://user-images.githubusercontent.com/13389997/81006927-4cfc7d00-8e1e-11ea-9d03-7f99cb8e4076.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
Need UX confirmation that my expectation is correct, and if so, we can add to eng queue. Putting as a P2 for UX review.

**Comment by swissspidy** [comment]
>  When selecting color gradient in the color picker, I expected the color on the left of the gradient to be at the top of the page, and the color set at the right of the picker to correspond to the bottom of the page.

I bet for someone speaking Arabic it would be the opposite 🙂

**Comment by samitron7** [comment]
Expected behavior is for the left color stop to map to the top and the right color stop to map to the bottom.

**Comment by miina** [comment]
@barklund Should this belong together with #6208?

**Comment by miina** [comment]
Closing as this got fixed with redesigning the tool.
