### ISSUE TITLE
Grid View Toggle: See classic WP list view

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#1488]
There's an ability to toggle dashboard view from a grid to a table. While we have this general toggle set up there are a few things we still need to tackle. 

- [ ] When in table view the sort drop downs should disappear and instead should see a link to "See classic WP list view" which, when clicked will send you to the view attached. 
- [ ] When you are on the classic WP list view you should get an arrow CTA at the top of the view to return back to the dashboard

Questions about this: 
- Is this CTA only here when you are getting to this classic view FROM the dashboard or all the time? 

![classic view with CTA.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/79cc1afc-970e-4fb3-baad-02f615d46960)

**Comment by carloskelly13** [comment]
I'll investigate the second requirement but I think modifying the native wordpress list view might be challenging.

**Comment by swissspidy** [comment]
I think there are action hooks available in WordPress that allow us to display something above the table. Then it would be relatively straightforward.

**Comment by carloskelly13** [comment]
Oh perfect. I will look into that! Thanks!

**Comment by swissspidy** [comment]
Happy to cover that part if needed

**Comment by carloskelly13** [comment]
@swissspidy That might be a good idea. I looked into `add_action` but it wasn't clear where to add that since we wanted it on `edit.php`. Or if you can point me in the right place to add the action hook.

**Comment by swissspidy** [comment]
I just spent a few minutes browsing through WordPress source code and have a hard time finding a good place for this.

There's no easy way to remove the title on the page as seen on that screenshot (arguably bad for accessibility anyway) that doesn't involve JavaScript.

However, I've found a reasonable place to put the backlink above the title.

Still needs an answer to this question though:

> Is this CTA only here when you are getting to this classic view FROM the dashboard or all the time?

**Comment by carloskelly13** [comment]
Yeah I think that would complicate things as we'd need to know some kind of referral.

**Comment by swissspidy** [comment]
Mind reviewing #1859?

**Comment by csossi** [comment]
Verified in QA

**Comment by samitron7** [comment]
Is this just to verify that the toggle to classic view is working?

**Comment by swissspidy** [comment]
@samitron7 Yes, and that you can get back to the dashboard from the classic view.

**Comment by samitron7** [comment]
When you click on Return to Web Stories Dashboard, we should return the user to the list view (from where they came from) and not the grid view. Can we make this change please.

**Comment by swissspidy** [comment]
@samitron7 Sure. Opened #2467 for this.
