### ISSUE TITLE
My Stories: Update Story Sort Options

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#1490]
Currently we are displaying some out of date sorting options and the dropdown styles have been updated.  See 'myStories' video at 0:25.

Acceptance Criteria: 
- [x] Update sort options to match new designs 
- [x] Update drop down component styles to have tighter space

Old: 
![bad sort options stories.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/3304e0a7-ba63-49bf-bcc7-be2d90171b15)

New: 
![good sort options stories.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/27863728-feec-4e8c-b6bc-a4297f911e42)

**Comment by BrittanyIRL** [comment]
There is a related CUJ for this: https://docs.google.com/spreadsheets/d/1zE3rdJykQY1YOQUHoczyzPNLa5_bhtv-2wfTE1-NOn0/edit#gid=0

Comments from this spreadsheet related: 
> "Created by" sort confusing in grid view since author metadata not shown
"Last opened" confusing (by me? by anyone?) and doesn't work -- if I select it, it goes to "last modified"

**Comment by BrittanyIRL** [comment]
Created a separate story to track 'last opened' sorting, since that is not available through the API yet and we need it updated on the PHP side of things in order to implement it. Ticket can be found here: https://github.com/google/web-stories-wp/issues/1727

In the meantime, I have set 'last opened' in the dropdown to a disabled state to avoid confusion with it defaulting back to 'last modified'

**Comment by o-fernandez** [comment]
> Created a separate story to track 'last opened' sorting, since that is not available through the API yet and we need it updated on the PHP side of things in order to implement it. Ticket can be found here: #1727
> 
> In the meantime, I have set 'last opened' in the dropdown to a disabled state to avoid confusion with it defaulting back to 'last modified'

@BrittanyIRL I checked with Sam and Paul and we are OK deprioritizing the Last Opened sort option, so you can remove that from the scope for this ticket. Thanks much!
