### ISSUE TITLE
Can't change zoom for background image

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#1491]
## Bug Description

Set image as background and, once in bg, don't have the option to change the zoom for the image. Was only able to do it if remove as background, zoom, and then set as background. Seems like an unnecessary limitation. 

## Screenshots

Video
[Zoom missing for bg image.zip](https://github.com/google/web-stories-wp/files/4577078/Zoom.missing.for.bg.image.zip)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Design from Figma for reference:
<img width="613" alt="Screenshot 2020-05-15 at 12 36 39" src="https://user-images.githubusercontent.com/3294597/82041631-c4e16780-96a8-11ea-88c1-4cd7dee2b2e6.png">

**Comment by csossi** [comment]
Verified in QA
