### ISSUE TITLE
My Stories: Table View - Update Author column to show "Me" when current user is author

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#1496]
While we are  exposing the author of the story in the table view, we are not updating the column to say "Me" when the author is the current user. We need a way to know when the author is the current user and update the text accordingly. 

![table view of stories.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/265d3636-3670-4948-b0a7-7839eb21fe63)

Current view where the 'admin' should all be "Me"
![Screen Shot 2020-05-05 at 8 16 41 AM](https://user-images.githubusercontent.com/10720454/81083202-2172a480-8ea9-11ea-826b-e453d274f769.png)

**Comment by carloskelly13** [comment]
Not needed per Sam
