### ISSUE TITLE
My Stories: Table View - SVGs for sorting

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#1498]
We need to add in the proper SVGs for the sorting on the table view. 
- Normal arrows for date sorts
- Arrows + alpha markers for alpha sorts 

![table view of stories.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/24865e74-9265-4220-9f48-17d8ad00a768)

**Comment by samitron7** [comment]
Here you go. Let me know if zenhub is converting these to images.
![arrowAZ.svg](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/bb0ba157-b08f-4daa-967f-bda72f2a0353)
![arrowZA.svg](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/073fee53-d786-4d12-a5a7-d13922ad4dac)
![arrowFilter.svg](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/18db7b77-67b0-430b-abfa-decec82348ff)
