### ISSUE TITLE
Ability to reset image/video mask (default scale, correct aspect ratio)

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#1507]
## Feature Description

When in media-editing mode, we can zoom and apply mask/cropping. The reset button only resets the zoom to default, but not the cropping/mask. Expand reset to also reset mask/cropping. 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
- Rename "Reset" to "Reset all"
- The reset button should also reset mask/cropping to default.

**Comment by miina** [comment]
Related: #1946

**Comment by miina** [comment]
@o-fernandez Is it OK to use the same button for all the 3? The button currently together with scaling, perhaps it should be adjusted then to reflect being a general reset? Thoughts?

**Comment by o-fernandez** [comment]
> @o-fernandez Is it OK to use the same button for all the 3? The button currently together with scaling, perhaps it should be adjusted then to reflect being a general reset? Thoughts?

I always assumed that "reset" meant everything, crop/mask/zoom, and I think it's fine to just reuse the same button to do that. Unless @samitron7 thinks otherwise, I'd vote to use the same.

**Comment by samitron7** [comment]
Nope, I was in the band camp that reset, resets everything and designed it that way. I think Paul thought reset should only reset scaling since the button was next to the slider. Can you rename it "Reset all". Hopefully this is clears things up.
