### ISSUE TITLE
Creator Can Style Text

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1509]
- [x] Change typeface
- [x] Select weight
- [x] Set font size by entering input value
- [ ] Set font size by using a slider
- [x] Set line height
- [x] Set kerning
- [x] Apply B
- [x] Apply U
- [x] Apply I
- [ ] Apply strikethrough
- [x] Set text color (solid only)
- [x] Set opacity

**Comment by csossi** [comment]
Verified in RC1
