### ISSUE TITLE
Explore Templates: Style Filter

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#1511]
## Description
Add a filter for explore templates dashboard view to filter by style. Style is based on template metadata `tag` content. 

## Acceptance Criteria 
- Ability to filter templates in dashboard by 'style'
- Karma tests added to verify

**Comment by o-fernandez** [comment]
@BrittanyIRL will this be a static filter list, or is this something that can be dynamic as we add more templates? I think it makes sense to style it based on a few sample values, but wondering if you need this to be a static list of values.

**Comment by BrittanyIRL** [comment]
Great question! I like dynamic lists because they are easier to update but it will mean we need an API for it. I propose we do this in two rounds. The first as static, like the rest of our filters currently are so that the front end isn't held up by the backend, and then when we have our template APIs set up, follow them with dynamic data.

**Comment by BrittanyIRL** [comment]
As of this ticket, we have no insight to what this menu is supposed to look like, we've never seen an 'open' version of it. Just for added context.

**Comment by jauyong** [comment]
We are awaiting on specs to be written out, moving this down in priority.

**Comment by o-fernandez** [comment]
We don't have defined a dictionary of what these tags will be, nor do we have an API to make this work dynamically, so it can't be implemented until that's been defined. I'll follow up on priority.
