### ISSUE TITLE
Template Type Prep

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#1512]
## Description 
Layout types are  not currently defined in template metadata. We'll need to align with design and the templates team but can take on the brunt of this work by creating a spreadsheet with each template (by slug), the description, and pulling in a type from that. For instance the `day in the life` template has this description: `This simple and minimalist template will let you create long format video stories that are highly engaging. Create day-in-the-life videos, workout routines, makeup tutorials and much more.` so from that the type would be `minimalist` probably. Once we have this table created it'll be easy to get design/copy approval and move forward. 

- [x] Spreadsheet created and shared 
- [ ] Layout Types verified 
- [ ] Layout Types added to templates 

## Acceptance criteria 
1) spreadsheet with the above that has types ok'd by design and stakeholders
2) a pr to update the template metadata with these types + a test to check that future templates include type as well.

**Comment by o-fernandez** [comment]
Similar to #1511, @BrittanyIRL , wondering if this needs to be a static list or whether we can make it dynamic so it adjusts as new templates are added.

**Comment by jauyong** [comment]
Moving this to the icebox column as we wait on product specs

**Comment by o-fernandez** [comment]
We don't have defined a dictionary of what these tags will be, nor do we have an API to make this work dynamically, so it can't be implemented until that's been defined. I'll follow up on priority.

**Comment by BrittanyIRL** [comment]
Here's a spreadsheet with all of the templates and their descriptions, I've added what I think qualifies as a layout type for _most_ of them, but I shouldn't be the one to decide this. I need help! @choumx can you tackle this? 

We need this info before we can move forward with adding in a layout type filter to the dashboard.

https://docs.google.com/spreadsheets/d/1hdHXDjTIB51mDoaRTqgle2giT1sji8pfW5zScyjqxvc/edit?usp=sharing

**Comment by swissspidy** [comment]
Curious, have we considered _not_ adding a layout type filter in the first place?

**Comment by BrittanyIRL** [comment]
😂  yes, i asked Will this before sinking time on it.

**Comment by BrittanyIRL** [comment]
(that said, happy to abandon this if further conversation agrees to not add it)

**Comment by dreamofabear** [comment]
Oh apologies for the misunderstanding -- by "type" I just meant the category/style/colors dimensions that you mentioned already.

Looking at the spreadsheet, I don't see an obvious win in extracting another dimension. "Category" already covers the theme/vertical bucket.

**Comment by BrittanyIRL** [comment]
oh great, i'll just close then then and we can move on!
