### ISSUE TITLE
Detail Template Pagination Arrow SVGs

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#1514]
We need updated SVGs for the pagination arrows to use on the detail template view, they look like this: ![template detail pagination.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/87c28709-8180-4352-ad81-5af34b385e5a)

**Comment by samitron7** [comment]
![ic-arrowDetailPage.svg](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/e6bdcc22-56ff-442c-b807-dd358df1b1ff)
