### ISSUE TITLE
Support Page

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#1519]
The left nav of the new Dashboard designs tell us that there's a support page, but we do not have designs or specs for this page.

**Comment by o-fernandez** [comment]
The support page is not ready, so we will need to hide the Support link until we get the page up.

**Comment by o-fernandez** [comment]
@BrittanyIRL we now have a support page we can link to. 
The dashboard should just link to: https://wordpress.org/support/plugin/web-stories/

**Comment by BrittanyIRL** [comment]
@o-fernandez - awesome! I'll go ahead and add this link to the dashboard's navigation menu.

**Comment by swissspidy** [comment]
@o-fernandez We probably want to track clicks on this link in telemetry?

**Comment by csossi** [comment]
Currently the link is refreshing page - should it open in a new browser tab?

**Comment by o-fernandez** [comment]
> @o-fernandez We probably want to track clicks on this link in telemetry?

Yes! @BrittanyIRL if that's possible to include? 

> Currently the link is refreshing page - should it open in a new browser tab?

Yes, I should have specified this behavior. Ideally, since it leaves the editor, it'd open in a new tab. @BrittanyIRL is that ok?

**Comment by BrittanyIRL** [comment]
@o-fernandez thanks for the additional specs and confirming behavior. 

I'll make these updates and resubmit for QA.

**Comment by BrittanyIRL** [comment]
@o-fernandez title for tracking event? I currently have: `open_wordpress_support` modeled off clicks to see traditional story list view: `open_classic_list_view`

**Comment by swissspidy** [comment]
open_support_page should work, using trackClick() util

**Comment by csossi** [comment]
Verified in QA
