### ISSUE TITLE
All Grid Items should "play" when hovered over

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#1521]
Regardless of view or if it's a template or a story, when the user hovers over the item it should begin to "play" (animate)

**Comment by carloskelly13** [comment]
This will require collaboration and some technical discussions with the editor team. This will involve building in play functionality with the current PreviewElements components that exists in the editor app codebase.

**Comment by maxyinger** [comment]
taken care of here:
https://github.com/google/web-stories-wp/pull/1861

Hidden behind `enableAnimation` feature flag

**Comment by maxyinger** [comment]
duplicate of #1897

**Comment by csossi** [comment]
@jauyong , should this be closed in favour of [#1897](https://github.com/google/web-stories-wp/issues/1897)?

**Comment by csossi** [comment]
VErified in QA as #1861
