### ISSUE TITLE
Creator Can Style Textbox

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1525]
- [x] Set/modify solid fill
- [x] Remove fill style
- [ ] Set/modify border radius (fill only)
- [x] Set/modify padding  (fill only)
- [ ] Set/modify drop shadow  (fill only)
- [x] Set/modify solid highlight color
- [x] Remove highlight style

**Comment by csossi** [comment]
Verified in RC1
