### ISSUE TITLE
Lasso selection coordinates inaccurate

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#1545]
## Bug Description

Lasso selection coordinates seem to be inaccurate and not following the cursor.

## Expected Behaviour
Lasso selection should be displayed based on the cursor coordinates and movement.

## Steps to Reproduce
1. Try lasso selecting
2. See the outline being created inaccurately

## Screenshots
![lasso](https://user-images.githubusercontent.com/3294597/81067698-54378f80-8edf-11ea-99e5-de44707cf48f.gif)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Potential regression cause: safe-zone implementation in editor: #1310

**Comment by miina** [comment]
@wassgha Note that this issue still happens if the canvas size is adjusted due to resizing meanwhile.

Perhaps that's a lower priority issue to address since probably it's not very likely to happen. Do you prefer me to create a new issue for that case instead of reopening this?

**Comment by dvoytenko** [comment]
Let's reopen

**Comment by miina** [comment]
@wassgha Reopening this since the issue sometimes still occurs when opening the editor and then resizing it (or opening the dev console) so that the canvas size changes.

![lasso](https://user-images.githubusercontent.com/3294597/82188891-d9af3c80-98ee-11ea-90c2-ffc89640569d.gif)

**Comment by wassgha** [comment]
@miina I've been trying to reproduce that with no luck, is there a specific size at which it breaks?

**Comment by miina** [comment]
@wassgha I was also trying to reproduce it locally just now and it actually happens (quite often) only when opening the dev tools positioned to the bottom so that the canvas size changes. However, wasn't able to reproduce it with just resizing anymore currently. Could you try if you're able to reproduce it by opening the page without dev tools and then opening the dev tools positioned to the bottom?

If not, then let's close the issue again. Looks like resizing + inaccuracy isn't happening anymore.

**Comment by barklund** [comment]
@wassgha, what's the status with this one? Are you actively working on this?
