### ISSUE TITLE
Editor crashing when I click on an element

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#1547]
## Bug Description

Editor crashes if I open a story to edit it and click on the background or any on page elements of any of the pages. 

## Expected Behaviour

No crashes. 

## Steps to Reproduce

Open story
Click background

## Screenshots
[All the crashes.zip](https://github.com/google/web-stories-wp/files/4581250/All.the.crashes.zip)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Fixed by #1544
