### ISSUE TITLE
Define min/max values for input fields

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#1549]
## Feature Description

Currently, users can enter huge numbers in editor fields (e.g., font size of 10,000). We should define sensible min/max values for each editor field and enforce them in the UI, including helpful text in case of invalid input. 

[Min/Max Values](https://docs.google.com/spreadsheets/d/1hdru-_p4Yk-VFQ1rEFGYHHI2A7eNZkxLA33-LblG8sE/edit#gid=0)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
For now, from a UX perspective let's just go with preventing users from entering values outside the defined min/max values. If a user enters/tries to enter a smaller/larger value, reset the field to the min or max allowed (e.g., I enter 150% in transparency then the editor auto resets it to 100%)

**Comment by barklund** [comment]
@o-fernandez, added [some more fields to the spreadsheet](https://docs.google.com/spreadsheets/d/1hdru-_p4Yk-VFQ1rEFGYHHI2A7eNZkxLA33-LblG8sE/edit#gid=0), FYI.

**Comment by obetomuniz** [comment]
Thanks @barklund and @o-fernandez for recent updates on the spreadsheet. I'm starting the technical stuff related, as soon as I have some stable proposal, I will sync up again here to check the final thoughts related to the values ranges.

**Comment by obetomuniz** [comment]
@o-fernandez could you please confirm if the current values in the spreadsheet will be the final expected ranges? Also, I did a few changes requests that need to review cuz some of them are not reflecting correctly the current editor UI (e.g. text line height and letter spacing).

**Comment by o-fernandez** [comment]
Updated, let's go with what's in the spreadsheet for now since we don't have any better guidance. @samitron7 @pbakaus @barklund for review if they'd like to make changes before this is wrapped up.

**Comment by pbakaus** [comment]
@o-fernandez mostly seems good, but I would not limit width/height to 10. Otherwise you can't create thin rectangle lines, something we found today is needed as workaround until we have lines / borders.

**Comment by csossi** [comment]
QA Instructions missing

**Comment by swissspidy** [comment]
@merapi Could you please add some thorough testing instructions here? I know you added some at #2255, but that covers only 1 element, and not everything from the linked spreadsheet.
By doing that you can also verify one last time that the implementation in #2255 matches the spreadsheet.

**Comment by merapi** [comment]
@csossi Last connected PR is now fixed, PTAL. Additionally, you can test other fields [as listed here](https://docs.google.com/spreadsheets/d/1hdru-_p4Yk-VFQ1rEFGYHHI2A7eNZkxLA33-LblG8sE/edit#gid=0) if they respect min/max values.

**Comment by swissspidy** [comment]
Note: you can now test this on `master` as I merged the PR prematurely. Didn't realize it had so many connected issues...

**Comment by csossi** [comment]
Tested on Master

- am able to set font size less than 8
- able to set line height less than .5
- able to set letter space greater than 300%
- able to set padding greater than 300

**Comment by merapi** [comment]
@csossi check now, master on QA was stale, I refreshed it (you need to change it back and forth to get the latest version of a given branch).

**Comment by csossi** [comment]
Verified in QA (Tested in Master)

**Comment by o-fernandez** [comment]
1 Issue: I  can still add text and then shrink it in the canvas to be smaller than the min specified. 
Will file a new issue for this - not a Beta blocker
