### ISSUE TITLE
Creator Can Add Image/Video to Page

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1556]
- [x] Upload image/video via upload button in media tab, and then add it from the media tab to canvas. 
- [x] Upload image/video via the original (separate) WordPress media gallery page, then open story editor and add it from the media tab to the canvas.
- [x] Search for media (through entering a keyword or by browsing) already in the media gallery and add it to the canvas
- [x] Filter media by type (image, video, all)
- [x] Drag image/video from desktop to canvas
- [x] Paste image/video to upload (only works on Mac OS)
- [x] Drag media from media library to edge to place as background
- [x] Add image/video on page then click "Set as background" button

**Comment by csossi** [comment]
Verified in RC1
