### ISSUE TITLE
Add eslint-plugin-react-hooks to the JavaScript project

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#1562]
## Feature Description

We have `react-hooks` as part of the eslint config, but `eslint-plugin-react-hooks` is not installed. Doing so adds 45 problems (45 errors, 0 warnings) of missing deps due to the `react-hooks/exhaustive-deps` rule.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

Add the package to the project and review the missing deps.

**Comment by swissspidy** [comment]
Started a PR in #1589. Contributions welcome!
