### ISSUE TITLE
Drag and drop overlay does not cover canvas

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#1564]
## Bug Description
See screenshot.

## Steps to Reproduce

Drag file into window.

## Screenshots

<img width="1792" alt="Screenshot 2020-05-05 at 20 36 11" src="https://user-images.githubusercontent.com/237508/81108781-09367000-8f11-11ea-808f-8f1cbfbe1250.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
According to #1741 this was already fixed in the meantime
