### ISSUE TITLE
Can't change overlay color if there's a background image

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#1569]
## Bug Description

Can't change overlay color if there's a background image

## Expected Behaviour

When adding an overlay, even if over a background image, I should be able to change the color of the overlay and gradient intensity. 

## Steps to Reproduce

Create new page
Add bg image
Add overlay

## Screenshots

![image](https://user-images.githubusercontent.com/13389997/81120809-66bfc200-8efb-11ea-87d1-4ad63dc773e5.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Duplicate of #679?

**Comment by o-fernandez** [comment]
Yeah, let's close as dupe since #1207 covers it and it's still open.
