### ISSUE TITLE
Media "Loading..." indicator seems to be ever present at the bottom of the media panel

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#1572]
## Bug Description

See bug. "Loading..." doesn't go away. Ever. 

## Expected Behaviour

Loading should only show when the user scrolls to the bottom of the loaded media and we are actively fetching more media results. 

## Screenshots

Video 
["Loading..." at bottom of page always there.zip](https://github.com/google/web-stories-wp/files/4584030/Loading.at.bottom.of.page.always.there.zip)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
@csossi this seems to have been Ready for QA for 2 weeks now.

**Comment by merapi** [comment]
As far as I can see that problem was fixed elsewhere and PR closed, just this Issue was forgotten.
