### ISSUE TITLE
Review E2E Testing Strategy

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#158]
While we focus on integration tests, we might want to have E2E tests to cover some aspects of the editor.

It should be easy to port this over from the previous editor when needed.

**Comment by spacedmonkey** [comment]
I think any drag and drop interaction would be good to test with e2e tests. I also think that video poster ( #135 ), would be a good one too.

**Comment by swissspidy** [comment]
Video poster extraction might be a nice candidate indeed, due do it definitely requiring a browser. Although we'd need to use something else than MP4 videos.

Regular drag & drop within the editor should be testable with React Testing Library. Even drag & drop of files might be possible, although there are some caveats (see https://github.com/testing-library/react-testing-library/issues/339#issuecomment-526310225, https://github.com/jsdom/jsdom/issues/1568)

That being said, we should identify the most critical areas to write tests for  and figure out which kind of test is most suitable to cover those. We can start with issues labelled as bugs.

-----

See #337 for current work on bringing back the e2e setup.

**Comment by swissspidy** [comment]
Closing this one for now. Let's add e2e tests on an as-needed basis.
