### ISSUE TITLE
Creator Can Manipulate an Image/Video on Canvas (in both fg and bg mode)

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1585]
- [x] Enter edit mode to change the crop factor of a video/image within its mask, allowing both zoom and repositioning.
- [x] Rest image to its original state
- [x] Set different poster image for the video from the auto-generated one
- [x] Fill in alt tag for accessibility/indexing (image only)
- [x] Fill in title tag for accessibility/indexing (video only)
- [x] Flip an image/video vertically or horizontally
- [x] Set video to looping
- [ ] Trim video (set different start and end point)
- [ ] Add a drop shadow
- [ ] Change border radius
- [ ] Can mute a video
- [ ] Apply a solid, linear or vignette overlay
- [ ] Set overlay color(s) & other gradient properties

**Comment by csossi** [comment]
Verified in RC1
