### ISSUE TITLE
Dashboard: Add Status to Grid View Metadata

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#1595]
## Bug Description

Grid view metadata does not show status. This was not present in the original designs, but we should add it in. Additionally HTML-escaped entities are not properly shown.

Showing "Will&#8217;s Test Story" for title when original title is "Will's Test Story"

## Expected Behaviour

The description under the preview card should list the status.

((title, status [draft, published, modified, etc])

## Steps to Reproduce

Go to the Dashboard grid view.

## Acceptance Criteria

The publish status should be listed under the preview card.

**Comment by BrittanyIRL** [comment]
I think this bug overlaps this story - since this is new metadata to the designs: https://github.com/google/web-stories-wp/issues/1492
