### ISSUE TITLE
Fail Gracefully if there is a JavaScript error

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1604]
Taken from #1369

Acceptance Criteria
1. Fail Gracefully if there is a JavaScript error
2. The editor should not crash when an error occurs
3. This solution should be behind a feature flag so it can be easily disabled for local testing/our dev/qa environments so we can easily catch issues. The solution is only meant to be enabled for end users. 

Note:  Can be done using React error boundaries, see #1219 for prior art.

**Comment by o-fernandez** [comment]
This lacks context, but generally making sure we fail gracefully, and minimize crashes, is crucial for Beta. Let's make sure that at least the most obvious problem areas have been identified and solved.

**Comment by swissspidy** [comment]
At the minimum, we should have catch-all error boundary around the whole editor (and dashboard, too)
