### ISSUE TITLE
Pasting formatted content into text field while editing removes formatting

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#1605]
## Bug Description

The current removal of formatting is intentional, as formatting would not otherwise be correctly converted to our new custom styles - but would rather use DraftJS built-in default styles, which would only cause confusion as those are not fully supported any longer.

Fixing this involves creating a [custom `handlePastedText` callback](https://draftjs.org/docs/api-reference-editor/#handlepastedtext).

This is a known consequence of PR #1323.

## Expected Behaviour

* When pasting formatted content (content with special font weight, color, font style, text decoration or letter spacing), the original styling should be preserved and appear identical in the editor.

## Steps to Reproduce

* Create a new Google Docs document.
* Insert some text here, make some of it bold, some italic, some underline and some green.
* Mark all the text and copy it to the system placeholder.
* In the editor, insert a new text field
* Click the text field to enter edit mode.
* Paste the copied content.
* Observe that the copied content is inserted, but without any formatting.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
