### ISSUE TITLE
Adding a text color or text style preset is broken with inline selection

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#1609]
## Bug Description

When in edit mode inside a text field with multiple colors in the given selection, adding a text color or text style preset does not work. Currently the click to add a preset is completely ignored.

Fixing this requires figuring out exactly what should happen in the different possible cases.

This is a known consequence of #1323.

## Expected Behaviour

* Expected behavior is unknown.

## Steps to Reproduce

1. Add a text field
2. Enter edit mode
3. Make some part of the text field green, another part blue
4. Select everything in the text field
5. Click the "+" icon under presets to add a new preset based off the current selection
6. Observe that nothing happens

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
I documented this and put it as WAI for now. We can revisit this and implement some other changes in the future if necessary, but for now, closing as not a priority.
