### ISSUE TITLE
Use proper semantic HTML for inline text formatting

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#1610]
## Feature Description

Since #1323 all inline text formatting in a text field is done using `<span>` and inline style properties.

This should be changed to proper semantic HMTL elements where applicable - e.g. going from the current:

```html
<span style="font-weight: 800">Hello</span>
<span style="text-decoration: underline">world!</span>
```
To:

```html
<strong style="font-weight: 800">Hello</strong>
<em>world!</em>
```

Thus using semantic elements where possible (for bold font-weights, italic and underline) and keep spans where not (for non-bold font weights, text color and letter spacing).

This however requires moving away from the current `draft-js-export-html` dependency to a custom DraftJS-to-HTML converter (and of course vice-versa).

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
@barklund do you think this is important for Beta? Stable?

**Comment by swissspidy** [comment]
Related: #5326

**Comment by BrittanyIRL** [comment]
@miina  this feels like a prometheus thing?  Not really sure why it got relabeled pea pod (but that was like 14 months ago so....)
