### ISSUE TITLE
Responsive UI and Breakpoints for smooth resizing

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#1621]
## Feature Description

**[Product spec (draft)](https://docs.google.com/document/d/1Jx2Pl5EYRM-SrZYVKbhB7RzPZOIUZkiRbUhydsaUtUE/edit#)**

**Design spec in progress**

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
Moved to 1.0 Post Stable, but please pull back in if you are able to work on it. @barklund @pbakaus @carlos-kelly

**Comment by pbakaus** [comment]
The above PR might be good enough, most other smaller items should likely be addressed in the visual redesign tickets. I'll let @dvoytenko and @barklund make a call though on whether we'll close this ticket after merge, or not.
