### ISSUE TITLE
Creator gets a warning if an element is placed too far in the bleed (not safe zone)

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#1627]
## Feature Description

Part of Safe Zone implementation, creator should be alerted of elements that may be cropped in some devices due to not being in the safe zone. 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by samitron7** [comment]
@o-fernandez Do you think we really need this? This may cause warnings all the time. There are 2 additional features that will help with this:

1. Helper mode - we provide non-intrusive message to alert a user of an issue. This will also work in conjunction with the pre-publish list
2. Preview mode - this is probably the clearest way for users to see what is going on.

If we can move this ticket out of beta to when we get to preview mode.

**Comment by o-fernandez** [comment]
This ticket is not in the beta, we have it in the icebox since a long time ago. But, I'll just go ahead and close it in favor of the features you mention.
