### ISSUE TITLE
API - Saved Templates

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1638]
https://docs.google.com/document/d/1yuQ-qmCpVZS_g-bx902umuR7-3IiJgHgFqdvaKxGvWs/edit#heading=h.rsjf0q34z978

This endpoint should fetch a collection of templates that contain both Bookmarked Templates and My Templates (i.e. it needs to combine two separate input streams into one).

API Url: <TBD>
Method: GET
Supports Paging?: Yes
Expected Response (as JSON): 
- Array of custom user templates and bookmarked external templates
- Either in the response headers or the body of the json, we should also have a total item count.

**Comment by swissspidy** [comment]
Per https://docs.google.com/document/d/1yuQ-qmCpVZS_g-bx902umuR7-3IiJgHgFqdvaKxGvWs/edit?disco=AAAAJl6AbBM, bookmarks are out of scope for stable
