### ISSUE TITLE
API - Bookmarked Templates

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1640]
https://docs.google.com/document/d/1yuQ-qmCpVZS_g-bx902umuR7-3IiJgHgFqdvaKxGvWs/edit#heading=h.m5kftoz0zi5d

This endpoint should fetch a collection of external templates that were “bookmarked” by the current user.

API Url: <TBD>
Method: GET
Supports Paging?: Yes
Expected Response (as JSON):
- Array of bookmarked external templates
- Either in the response headers or the body of the json, we should also have a total item count.

**Comment by swissspidy** [comment]
Not something we need for stable, see https://docs.google.com/document/d/1yuQ-qmCpVZS_g-bx902umuR7-3IiJgHgFqdvaKxGvWs/edit?disco=AAAAJl6AbBM
