### ISSUE TITLE
API - Explore Templates (external Templates)

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1641]
https://docs.google.com/document/d/1yuQ-qmCpVZS_g-bx902umuR7-3IiJgHgFqdvaKxGvWs/edit#

This endpoint should fetch a collection of external templates that are available for the user to use/bookmark.

API Url: <TBD>
Method: GET
Supports Paging?: Yes
Expected Response (as JSON):
- Array of external templates
- Either in the response headers or the body of the json, we should also have a total item count based on any applied search/filters.

**Comment by carloskelly13** [comment]
The attached google doc has an ongoing conversation around the filters required for the Explore Templates API

> The mocks that we received from Sam show that the "Explore Templates" screen can be filtered by: Category, Style, Color, Layout Type.
> 
> Also, these results should be sortable by popularity or create date.
> Pascal Birchler
> Pascal Birchler
> 1:21 PM May 4
> +pbakaus@google.com How is popularity determined? Might influence implementation here.

It appears there are some product decisions required here for the filters.

**Comment by swissspidy** [comment]
Closing for now. Can be reopened once this becomes a priority.
