### ISSUE TITLE
Bookmark Template

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1642]
https://docs.google.com/document/d/1yuQ-qmCpVZS_g-bx902umuR7-3IiJgHgFqdvaKxGvWs/edit#heading=h.ejfki5jfuc3j

This endpoint should bookmark an external template by its ID.

API Url: <TBD>
Method: POST
Supports Paging?: No
Expected Response (as JSON): 
- 200 success response so App knows it worked
Query Params: 
- template_id: The ID of the template to be bookmarked.

**Comment by swissspidy** [comment]
Not something we need for stable, see https://docs.google.com/document/d/1yuQ-qmCpVZS_g-bx902umuR7-3IiJgHgFqdvaKxGvWs/edit?disco=AAAAJl6AbBM
