### ISSUE TITLE
API - Unbookmark Template

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1643]
https://docs.google.com/document/d/1yuQ-qmCpVZS_g-bx902umuR7-3IiJgHgFqdvaKxGvWs/edit#heading=h.76n0u416cimn

This endpoint should remove the bookmark from an external template by its ID.

API Url: <TBD>
Method: DELETE
Supports Paging?: No
Expected Response (as JSON): 
- 200 success response so App knows it worked

Query Params:
- template_id: The ID of the template to be unbookmarked.

**Comment by swissspidy** [comment]
Put in icebox as it's not something we need for stable, see https://docs.google.com/document/d/1yuQ-qmCpVZS_g-bx902umuR7-3IiJgHgFqdvaKxGvWs/edit?disco=AAAAJl6AbBM

**Comment by swissspidy** [comment]
Closing for now. Can be reopened once this becomes a priority.
