### ISSUE TITLE
API - Related Templates 

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1644]
https://docs.google.com/document/d/1yuQ-qmCpVZS_g-bx902umuR7-3IiJgHgFqdvaKxGvWs/edit#heading=h.yw0nds3duxcm

This endpoint should fetch a collection of templates related to a template ID.

API Url: <TBD>
Method: GET
Supports Paging?: Yes
Expected Response (as JSON):
- Array of external templates
- Either in the response headers or the body of the json, we should also have a total item count.

**Comment by swissspidy** [comment]
Closing for now. Can be reopened once this becomes a priority.
