### ISSUE TITLE
Creator can Transform an Element

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1649]
- [x] Move an element
- [x] Snap to place (ie center, etc)
- [x] Align element to page
- [x] Align element to one another
- [x] Rotate element using rotation handle
- [x] Rotate element by entering a value
- [x] Flip element
- [x] Auto-adjust landscape/portrait images/video but allow 90 degree rotation
- [x] Adjust width
- [x] Adjust height

**Comment by csossi** [comment]
Verified in RC1
