### ISSUE TITLE
Improve default radial gradient overlay

### ISSUE THREAD

**Issue by samitron7** [GoogleForCreators/web-stories-wp#1653]
![image.png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/3dff2db5-0682-4f74-906b-5e3678efdc6f)

Can we make the radial gradient look more like this or a vignette filter. 
![Group 4494 (1).png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/e2305c46-a4d1-43da-bb8c-9cce9a9952b0)

Desired CSS for default radial gradient:

```css
background-image: radial-gradient(80% 50% at center, #0000 25%, #000)
```

## QA Instructions
See #1207.

**Comment by swissspidy** [comment]
We also want to allow users to customize the gradient, which we are currently tracking this in #1207.

I assume this is just for improving the default?

**Comment by barklund** [comment]
Updated with specific CSS from [UX Eval doc](https://docs.google.com/presentation/d/1ZiZWrmLiX40rt3n_1LMSGJxYWI-xsWFsS9bkzdbRIV8/edit?ts=5ec35b92#slide=id.g77fdc779d5_0_249).

**Comment by samitron7** [comment]
Yes, this is to increase the quality for the default. The current default is not really usable by design standards.

![Screen Shot 2020-06-01 at 8.56.37 AM.png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/66870566-9d4d-426b-ad0b-39c1dfe06507)

Removing UX label since design is available.

**Comment by csossi** [comment]
Verified in QA

**Comment by samitron7** [comment]
Verified in UAT
