### ISSUE TITLE
Group drag-resize-rotate actions go to history as multiple entries

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#1657]
## Bug Description

Currently, when multiple elements are selected and dragging, resizing, rotation applied, each element will create its own entry to history.

This comes from `updateElementsById` being applied in a loop to each element instead of collecting all the information and then applying it for all the elements together.

https://github.com/google/web-stories-wp/blob/7c22f4c2f1d021fcfc8cd38f76325c22220ad563/assets/src/edit-story/components/canvas/multiSelectionMovable.js#L146-L174

## Expected Behaviour

- One user interaction should go to history as one combined entry, too.

## Steps to Reproduce

1. Add a few elements
2. Select all and drag
3. Click undo
4. See the elements undoing one by one instead of together

## Screenshots
![history](https://user-images.githubusercontent.com/3294597/81379763-f63ac000-9109-11ea-969e-4246a1b1b171.gif)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Related: #1945

**Comment by csossi** [comment]
Verified in QA
