### ISSUE TITLE
Page carousel: scrollbar visible in compact mode

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#1661]
## Bug Description

The scrollbar is visible in smaller screens in compact mode.

## Expected Behaviour

Scrollbar should never be visible, the arrows can be used for navigating in the page carousel.

## Steps to Reproduce

1. Resize your screen small.
2. Add a bunch of pages, enough for the scrollbar to appear
3. See the scrollbar below page carousel

## Screenshots
<img width="674" alt="Screenshot 2020-05-08 at 13 11 23" src="https://user-images.githubusercontent.com/3294597/81400598-c9000900-912d-11ea-8f10-d863ef2c1cbf.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

- Scrollbar should never be visible for page carousel.

**Comment by barklund** [comment]
Irrelevant as the compact carousel indicator doesn't exist anymore.
