### ISSUE TITLE
Creator can View and Move Elements Up/Down the Stack in the Layers Panel

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1667]
**P0**
- [ ] Get preview of metadata of element
- [x] Move element up/down the layers stack
- [x] CMD Up/Down to move element up/down the layer
- [x] CMD+Shift+Up/Down to move element  up/down the layer
- [x] Delete a element from the layers panel
- [x] Expand and collapse the layers panel (clicking on arrow or dragging)

**Comment by csossi** [comment]
Verified in RC1
