### ISSUE TITLE
Creator can View and Modify Document Settings

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1671]
**P0**
- [x] Change default page duration for page advancement speed
- [x] Toogle Auto vs. Manual advancement
- [x] Set/modify publish date
- [x] Set/modify author
- [x] Select logo from dropdown
- [x] Set/modify cover image
- [x] Set/modify permalink
- [x] Set/modify status

**Comment by csossi** [comment]
Verified in RC1
