### ISSUE TITLE
Creator Can View Their Stories in Grid View

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1676]
**P0**
- [x] See all their stories (Drafts plus Published)
- [x] Sort their stories (last modified, last opened, date created, author, title, etc.)
- [x] Filter their stories by All stories, Drafts and Published
- [x] See metadata such as title and status [draft, published, modified, etc]
- [x] Hover over story card to see quick animated preview of story

**Comment by csossi** [comment]
Verified in RC1
