### ISSUE TITLE
Focal point: Front-end & preview implementation

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#17]
## Feature description

Follow-up from ampproject/amp-wp#3964 to reflect the change in the front-end as well.

Currently, it's implemented in the editor but it does not work in the front-end nor in the preview.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

- The chosen focal point and "cropped" image match in the editor and in the front-end.

## Implementation brief

* 

N/A: see ampproject/amp-wp#3964

## QA testing instructions 

* 

## Demo

* 

## Changelog entry

*

**Comment by miina** [comment]
Seems to be blocked by or at least reasonable to work on after refactoring preview/save and making previews responsive.

**Comment by dvoytenko** [comment]
Blocked by #198.

**Comment by miina** [comment]
This seems to be fixed, closing.
