### ISSUE TITLE
Intermittent npm install failures in GitHub Actions workflows

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#1716]
## Bug Description

```
##[error]Process completed with exit code 254.
Run npm ci
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/runner/work/web-stories-wp/web-stories-wp/node_modules/fsevents/node_modules/abbrev/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/runner/work/web-stories-wp/web-stories-wp/node_modules/fsevents/node_modules/abbrev/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-05-11T02_17_25_487Z-debug.log
##[error]Process completed with exit code 254.
```

**Comment by swissspidy** [comment]
Less urgent now that individual jobs can easily be restarted. Closing for now.

**Comment by MkMan** [comment]
Hi @swissspidy , did you end up finding a fix? I am getting the exact same issue but on a generic Node project (not 
web-stories-wp)

**Comment by swissspidy** [comment]
@MkMan This actually never came up again, it has been working fine again ever since. Perhaps after some deps updates.

**Comment by henrycity** [comment]
> Hi @swissspidy , did you end up finding a fix? I am getting the exact same issue but on a generic Node project (not
> web-stories-wp)

Sorry for the late post. Did you manage to fix it? The issue keeps popping up for me and I had to restart the job to make it work.

**Comment by swissspidy** [comment]
The issue seems to have sorted out itself over time I think, we never really encountered this after a while. Perhaps it was due to some dependency update.
