### ISSUE TITLE
Discovery: use Karma for integration tests

### ISSUE THREAD

**Issue by dvoytenko** [GoogleForCreators/web-stories-wp#1721]
Use [Karma](https://karma-runner.github.io/5.0/index.html) for integration (and possibly unit) tests.

TODO:

- [x] Karma setup
- [x] User puppeteer for browser
- [x] Fixture implementation
- [x] Snapshotting and Percy support
- [x] Native events
- [x] Catch and fail unexpected errors
- [x] Fix debug mode
- [x] Integrate into CI, including Percy.

Karma is a popular test framework. It does in-browser testing. By default it's able to test almost against any browser, but some testing features might be available in some environments. Some key components of Karma:
 1. Karma test runner and reporter. Runs a page in a browser. Loads both code and tests in the same context in a friendly iframe.
 2. WebPack. Can reuse our development config.
 3. Jasmine (but many other alternatives, such as Mocha)
 4. Browser launchers: Chrome, Firefox, Safari. But we can also use Puppeteer.

Comparing to Jest:
 * Karma runs in a browser. Can debug at any point and see the actual editor running, inspect in DevTools, add a breakpoint in devtools or use `debugger`etc.
 * Because it's a real browser all the browser APIs are also available. E.g. window selection, IntersectionObserver, etc. But because it's a real browser, flakes happen(tm).
 * Karma uses our WebPack config mostly unmodified, so no need for library mocks: SVGR, Color, DraftJS, etc - all can run as is.
 * However, Jest does a special module loading and can mock the whole modules, default functions, etc. Karma (or rather Jasmine) can do what's possible with the WebPack module loading.
 * Both Jest and Karma would normally use synthetic events, but Karma can also be customized to use native events with Puppeteer. 
 * Some nits, such as `display.only` in Jest vs `fdisplay` in Jasmine for focused tests.
 * [Testing Library](https://testing-library.com/) extends jsdom "expect" matchers, which are convenient, e.g. `toHaveTextContent`. Jasmine doesn't have those by default (but custom matchers are also allowed).
 * Karma tests can and should also use the Testing Library, but the boundary between DOM and jsdom is not always obvious.
 * With Puppeteer screenshots are possible and natural.
 * jsdom runs each test in a clear context. But Karma runs each test suite in a separate iframe (possibly for performance reasons). That means that side-effects and global state are problematic. For instance, `styled-components` by default manage the global state (which styles have been loaded) in the global ES6-module state. It can usually be worked around, but a painful issue at times.

See this [demo](https://drive.google.com/file/d/1swMxiw_aEtnggG0EX2ixYfc_r_0ckuZz/view?usp=sharing). To try out the prototype, use the branch for #1712.

A design proposal doc for commenting can be found here:
http://doc/1kKu8QRPYNtLjhc3botd4sEIwPnUSemLXFyNPIw8Pf50#heading=h.to9an7xfy560

**Comment by cvolzke4** [comment]
A design proposal doc for commenting can be found here:
http://doc/1kKu8QRPYNtLjhc3botd4sEIwPnUSemLXFyNPIw8Pf50#heading=h.to9an7xfy560

**Comment by dvoytenko** [comment]
Some test run data.

Amortized time per unit of test is about **0.3-0.5 seconds**. With a 20 minutes budget this works out to be about **3,000 integration tests**.

The same architecture of tests running on Jest takes up to **1.5 seconds**.
