### ISSUE TITLE
Add Last Opened sort to orderby options for web-stories API

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#1727]
## Feature Description
We need the ability to sort stories by the last time they were opened, thus "last opened". 

@miina added in the ability to sort by author already, this I'm figuring will follow suit but with a little more complexity since we have to track when the last time the story was opened was. 

@o-fernandez @samitron7 can you expand on what "last opened" means so that this gets implemented correctly? 

The API will request will look like this: 
```
wp/v2/web-story?context=edit&order=asc&orderby=last_opened&page=1&per_page=10&status=publish%2Cdraft&_locale=user
```

Design video for reference: 
https://drive.google.com/drive/u/0/folders/1onGbNRFVAalJXtbYYFigSbdG-nHUE7As

Relates to #1490 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
This is not a CUJ for the Beta/Stable, so we can deprioritize for now. It's also unclear what would make most sense, likely a "Last Opened by Me" (not a generic one), so we can spec that out for post Stable release/ post 1.0.

**Comment by jauyong** [comment]
No longer needed. (Grooming May 13)
