### ISSUE TITLE
Add Feature Flags UI

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#1738]
## Feature Description

Add a simple UI ( checkboxes ) to enable / disable feature flagged features. 

Follow up ticket from #1464

## Additional Context

Screenshot of Chrome's experiments screen to give an idea of what this could look like:

<img width="742" alt="Screenshot 2020-05-12 at 15 07 54" src="https://user-images.githubusercontent.com/237508/81701800-6460e900-9462-11ea-8e7f-560f4033e2b2.png">

Gutenberg experiments page:

https://github.com/WordPress/gutenberg/blob/master/lib/experiments-page.php
https://github.com/WordPress/gutenberg/blob/master/packages/e2e-tests/experimental-features.js

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

* Add new `WEBSTORIES_DEV_DEBUG` constant or similar. Defaults to `true`, but is `false` for stable releases.  
  Background: we want this to be only enabled on development builds, not stable releases.
* Enhance build tool to set this constant automatically
* Add new `Experiments` class that defines all feature flags, and — if `WEBSTORIES_DEV_DEBUG` is `true` — adds a new settings screen to the admin menu (using the Settings API).
* The way flags are defined will slightly changed, as they will now need to be grouped by area, and the titles will likely need to be translatable (as they will be displayed in the UI).
* In the `Settings` class, a new experiments/flags setting will be registered, which can be used on the settings screen

**Comment by spacedmonkey** [comment]
The dashboard as a Editor settings section. Should these flags live there?

**Comment by swissspidy** [comment]
My idea in #1464 / #1700 was that this is something more suitable for a separate plugin, or perhaps as part of the Web Stories Tester plugin, and not something that is part of the regular UI. In other words, more intended for developers rather than users.

**Comment by spacedmonkey** [comment]
<img width="684" alt="Screenshot 2020-05-12 at 15 00 30" src="https://user-images.githubusercontent.com/237508/81701150-86a63700-9461-11ea-8d99-a17cd74bd122.png">

So did you have something like how gutenberg works? 

Personally, I don't see an issue with shipping in a part of the core editor. I believe it should live in javascript and not PHP, as we are trying to decouple it from WP. It could have like `chrome://flags/`. Which ships with chrome by default but is hidden. 

<img width="742" alt="Screenshot 2020-05-12 at 15 07 54" src="https://user-images.githubusercontent.com/237508/81701800-6460e900-9462-11ea-8e7f-560f4033e2b2.png">

As long as don't draw attention to the feature, it can be part of the editor. Those enable features in setting screens like should know that these are beta/alpha features and take ownership that they may get breaks etc.

**Comment by jauyong** [comment]
Flagging @o-fernandez for epic categorization and prioritization

**Comment by o-fernandez** [comment]
I'll just drop this under "testing infrastructure" as that seems the most related area, but @swissspidy @spacedmonkey see if you'd rather recategorize.

**Comment by swissspidy** [comment]
@o-fernandez I suppose it depends on whether we'd want end user to be able to access feature flags via some hidden screen (analogous `chrome://flags`), or if this is more for development / QA / testing. It's a super non-urgent thing, as we don't yet have feature flags, and haven't yet specified how exactly we're gonna use them.
