### ISSUE TITLE
Usability re: Uploading Media

### ISSUE THREAD

**Issue by csossi** [GoogleForCreators/web-stories-wp#1752]
## Bug Description

Usability comment: when user is adding an image and successfully uploads, they are in a window with "Upload To Story" at the top left (it's adding to library, not to story) and "Insert Into Page" button at bottom right (which it isn't doing - it's just adding to library). NOTE: When uploading a video, it DOES immediately add to canvas. Also note that cursor isn't changing to "hand" cursor when mouseing over All, Image. and Video.

## Expected Behaviour

From UX directions in [here](https://docs.google.com/presentation/d/1ZiZWrmLiX40rt3n_1LMSGJxYWI-xsWFsS9bkzdbRIV8/edit?ts=5ec3754c#slide=id.g77fdc779d5_0_312)

1. If user clicks "insert into page" the item should be added to the canvas/page
2. Add a secondary "Done" button that just dismisses the dialog without inserting into page. 

## Screenshots

Newly uploaded image (browse PC) automatically checked. Clicked Insert Into Page at lower right:
![image](https://user-images.githubusercontent.com/16945664/82487305-32780400-9aac-11ea-9690-7f57de9baf66.png)

Image is now in Media Library, available for selection, but not inserted into page:
![image](https://user-images.githubusercontent.com/16945664/82487488-67845680-9aac-11ea-9426-ccdc4a4c223e.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
@csossi do you mind adding an image/screenshot to showcase the issue clearly (so others don't have to guess/investigate). 

Also, let's break this into it's own issue (create a separate ticket) since otherwise we risk losing that detail in this ticket

> Also note that cursor isn't changing to "hand" cursor when mouseing over All, Image. and Video.

**Comment by swissspidy** [comment]
> Also, let's break this into it's own issue (create a separate ticket) since otherwise we risk losing that detail in this ticket
> > Also note that cursor isn't changing to "hand" cursor when mouseing over All, Image. and Video.

+100 to this. We have plenty of inconsistencies around this. It's worth tracking `cursor: pointer` changes in a separate ticket to fix it everywhere & document it appropriately.

**Comment by o-fernandez** [comment]
This is actually pretty confusing UX, I have a video where I was struggling with it. 

[What is "Media Library" for in Upload flow.zip](https://github.com/google/web-stories-wp/files/4646476/What.is.Media.Library.for.in.Upload.flow.zip)

@samitron7 this flow would need revision, I think.

**Comment by o-fernandez** [comment]
Added to issue/ticket the findings from Sam and suggestions. Ready for Eng to take a look.

**Comment by diegovar** [comment]
Thanks for the added context for the issue.

I have a question regarding point #2:
"Add a secondary "Done" button that just dismisses the dialog without inserting into page."

Where would this button appear? Tbh if I saw a button called Done I would assume that would add the image into the post. There's a big X at the top right to dismiss the dialog, and you can also click outside of the dialog to dismiss it. Is that not enough?

**Comment by o-fernandez** [comment]
> Thanks for the added context for the issue.
> 
> I have a question regarding point #2:
> "Add a secondary "Done" button that just dismisses the dialog without inserting into page."
> 
> Where would this button appear? Tbh if I saw a button called Done I would assume that would add the image into the post. There's a big X at the top right to dismiss the dialog, and you can also click outside of the dialog to dismiss it. Is that not enough?

I think the "x" should be enough, but @samitron7 could you quickly review and chime in?
