### ISSUE TITLE
Previewing BG Video - Overlap with Play/Preview Icon

### ISSUE THREAD

**Issue by csossi** [GoogleForCreators/web-stories-wp#1753]
## Bug Description

Note that if a video is set as background and there's an image in the middle of the page, user is unable to select "preview" play icon

## Expected Behaviour

Expected that if I selected the BG layer, I'd be able to click the "play" icon

## Screenshots

![image](https://user-images.githubusercontent.com/16945664/81820998-59a86180-94ff-11ea-85b0-202e2872e96d.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
We should get validation from @samitron7 on the correct behavior here and get it fixed.

**Comment by swissspidy** [comment]
Duplicate of #792?

_(General reminder to search for existing issues before creating/triaging)_

**Comment by o-fernandez** [comment]
It does look like a dupe, so will close this one.
