### ISSUE TITLE
Changing Featured Image - Assistive Text

### ISSUE THREAD

**Issue by csossi** [GoogleForCreators/web-stories-wp#1754]
## Bug Description

Able to change poster image, but shouldn't the 2 assistive text fields below it be resetting as well (currently keeps the autopopulated assistive text from the video)? Also, recommending that the field labels not be within the field for assitive text. When it autopopulates, user can't tell what exactly this is

## Expected Behaviour

Expected Assistive Text fields to reset

## Steps to Reproduce

Select FEatured Image
Opt to edit image
Select New Image from Media Library

Note changes to Assistive Text fields

## Screenshots

![image](https://user-images.githubusercontent.com/16945664/81821580-0256c100-9500-11ea-924e-66586cb8539b.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
Marking for UX review

**Comment by o-fernandez** [comment]
Looking at this more closely, I think the current implementation is intended. The user may change as they wish, but it's not tied to the featured image. Let's close and track user feedback.
