### ISSUE TITLE
Adding New Text - Cursor Focus

### ISSUE THREAD

**Issue by csossi** [GoogleForCreators/web-stories-wp#1755]
## Bug Description

Can add text, but expected cursor focus to be in text field

## Expected Behaviour

expected that cursor focus would be within the field (with any assistive text within the field highlighted - expected that user can just go ahead and type without haveing to highlight/remove text

## Steps to Reproduce

Opt to add new text box

## Screenshots

![image](https://user-images.githubusercontent.com/16945664/81822415-118a3e80-9501-11ea-8808-7c75d42552a0.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment]
@csossi I don't quite follow what the issue is. 
is it related to this? #830

**Comment by swissspidy** [comment]
Related: #1608

**Comment by o-fernandez** [comment]
I will close this in favor of #1608
