### ISSUE TITLE
Editor Settings - Blank Page

### ISSUE THREAD

**Issue by csossi** [GoogleForCreators/web-stories-wp#1757]
## Bug Description

Editor Settings page is blank

## Expected Behaviour

Settings options should be appearing

## Steps to Reproduce

- go to Dashboard
- select Editor Settings

## Screenshots

![image](https://user-images.githubusercontent.com/16945664/81824034-00423180-9503-11ea-8253-b5ab1945d779.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
That hasn't been implemented yet. See #570, #1672.

**Comment by jauyong** [comment]
closing per the above note
