### ISSUE TITLE
Clarification re: My Stories

### ISSUE THREAD

**Issue by csossi** [GoogleForCreators/web-stories-wp#1758]
## Bug Description

Card empty/white if no bg media on first page. Also, I see EVERYONE'S stories - should I just see stories authored by myself (or is it because I have "admin" credentials?)

## Expected Behaviour

With a title like My Stories, I expected to see only stories authored by my self.

## Steps to Reproduce

- open Dashboard
- select My Stories

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
Currently, we have left it as My Stories, but agree this can be confusing for users that are creating in a team environment with many other creators. We will revisit this as part of https://github.com/google/web-stories-wp/issues/2750
