### ISSUE TITLE
Dashboard - Sorting in List View

### ISSUE THREAD

**Issue by csossi** [GoogleForCreators/web-stories-wp#1759]
## Bug Description

List view is appearing, but sorting by "Last Modified" isn't working correctly. Clicked the ascending/descending arrow once, and the sort changed (fine). Clicked the arrow again, and there was no change.

## Expected Behaviour

Sort should toggle correctly between ascending order and descending order on clicking arrow

## Steps to Reproduce

- open Dashboard
- go to My Stories
- select List View option at far right
- click arrow for Last Modified to change sort
- Note that sort changes
- select arrow again to change back

Sort doesn't change

## Screenshots

Ascending:
![image](https://user-images.githubusercontent.com/16945664/81829448-e3106180-9508-11ea-94a8-edb87c1fb2fe.png)

same as Descending:
![image](https://user-images.githubusercontent.com/16945664/81829532-fd4a3f80-9508-11ea-8788-f0ce0114b153.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
I cannot reproduce this neither locally nor on https://stories-new-wordpress-amp.pantheonsite.io/.

Close?

**Comment by swissspidy** [comment]
Still can't reproduce.

However, even if, I don't think this is a blocker for beta.

**Comment by BrittanyIRL** [comment]
I can't reproduce this either. Works as expected.

**Comment by swissspidy** [comment]
Thanks for confirming @BrittanyIRL 👍
