### ISSUE TITLE
Add Helper Text to Publisher Logo in Doc Panel Explaining it is Global

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1763]
Since we are dropping the global settings page for Beta, users can only set the publisher logo in the Document panel. We need to let them know this is a global field. 

Acceptance Criteria
1. Add the following helper text to the Publisher Logo fiedl
2. [Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=6113%3A618) flow for temporary message. 
3. Note - we'll need to remove this when the settings page comes back in.

![image.png](https://images.zenhubusercontent.com/5e985a7aea3104e101699670/c1f98cb7-b52c-472e-806f-07fb8bf343f2)

**Comment by samitron7** [comment]
[Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=6113%3A618) flow for temporary message. Note - we'll need to remove this when the settings page comes back in.

**Comment by jauyong** [comment]
@samitron7 @o-fernandez 
Per "Note - we'll need to remove this when the settings page comes back in."
We just opened #2747 for the settings page from the dashboard. Is there a point in putting that temporary message if we are planning to add the settings page soon?

**Comment by o-fernandez** [comment]
> @samitron7 @o-fernandez
> Per "Note - we'll need to remove this when the settings page comes back in."
> We just opened #2747 for the settings page from the dashboard. Is there a point in putting that temporary message if we are planning to add the settings page soon?

Yeah, this should actually have been done for Beta, now that I think about it. Given that I mistakenly moved it to Stable, let's just see how things go and wait until #2747 comes through.
