### ISSUE TITLE
Undo/redo of a group move is done one at a time

### ISSUE THREAD

**Issue by dreamofabear** [GoogleForCreators/web-stories-wp#1773]
## Bug Description

Undoing batch operations are undone individually (by element) instead of as a batch.

## Steps to Reproduce

1. Select multiple elements via shift+click or click+drag.
2. Move the elements on the page by dragging them.
3. Press the "undo" button.

Expected: The group of elements are all moved back to the original position at the same time.
Actual: Only one element is moved back. Subsequent undo's move back the other elements one at a time.

## Screenshots

![out_small](https://user-images.githubusercontent.com/20525523/81893558-ebee4b00-957b-11ea-9718-fa3f822a5bd6.gif)
---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Duplicate of #1657?

**Comment by dreamofabear** [comment]
Ah thanks, tried searching open issues for "undo". Closing as dupe.
