### ISSUE TITLE
Deleting text in element resets its styles

### ISSUE THREAD

**Issue by dreamofabear** [GoogleForCreators/web-stories-wp#1774]
## Bug Description

Deleting all the text in a label resets font color, weight and italic/underline (and perhaps others too).

## Steps to Reproduce

1. Create a text element and set font color, weight or italic/underline.
2. Edit the text and press backspace until all the text is deleted.
3. Type some new text.

Expected: The new text is styled with the same style as the deleted text.
Actual: The new text is not styled.

## Screenshots

![text_bug](https://user-images.githubusercontent.com/20525523/81894149-18ef2d80-957d-11ea-9cdc-e54519c97e1e.gif)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

#### Replace text without clearing
1. Add a text element to a page
1. Apply styling to the text element in the form of font-weight, italics, underline, letter-spacing or color (all styles that can be applied per-character).
1. Then enter edit mode
1. Select all the text
1. Start typing (will clear old content) and observe new characters still being the same style, as the text had before.

#### Clear by selecting all and replacing
1. Add a text element to a page
1. Apply styling to the text element in the form of font-weight, italics, underline, letter-spacing or color (all styles that can be applied per-character).
1. Then enter edit mode
1. Clear the text field by selecting all the text and pressing backspace
1. Start typing and observe new characters still being the same style, as the text had before.

#### Clear by deleting characters one at a time
1. Add a text element to a page
1. Apply styling to the text element in the form of font-weight, italics, underline, letter-spacing or color (all styles that can be applied per-character).
1. Then enter edit mode
1. Clear the text field by placing the cursor at the end and pressing backspace until the input is empty
1. Start typing and observe new characters still being the same style, as the text had before.

**NB**: If you have multiple styles in the text field before clearing (e.g. some text bold, some text not bold), the new text styling should follow that of the first character in the input field (but there might be some variations here depending on where the cursor is before clearing and how you clear it). This part is not essential for this ticket, and any discovered inconsistencies should be noted as a follow-up issue.

**Comment by swissspidy** [comment]
How could I "clear" the formatting in this case without having to reset each setting manually in the design panel? Press backspace again? Might need some UX definition here.

**Comment by dreamofabear** [comment]
Following precedence from text editors, that's usually done with a separate "clear formatting" action. `Command+\` in Docs for example.

Minimally, we should avoid losing the style IMO. Users can always unset styles individually.

**Comment by jauyong** [comment]
Just tagging @samitron7 for awareness on this one.

**Comment by csossi** [comment]
Tested in QA - PR#2584

See QA Testing Instructions above

1st scenario is fine now, but 2nd and 3rd are still having the same prob

**Comment by barklund** [comment]
@csossi, can I get you to re-test this making sure you're on the right branch? I'm seeing all scenarios work as expected here. Scenario 1 probably worked even before this branch, thus you might be on an unrelated to see this result.

**Comment by barklund** [comment]
@csossi it seems there was a temporary problem with Pantheon caching an old version of the branch. But when I re-applied the branch from the dropdown, it worked fine.

You can validate, that you're on the right version of the branch, if you see the safe zone tick marks (rather than the old danger zone marking).

Can you please re-evaluate this issue with that in mind?

**Comment by csossi** [comment]
Verified in QA

**Comment by samitron7** [comment]
All 3 use cases passed but the following one (which is not a part of this QA failed)

1. Add new text field and style
2. Add a new line then select all and type. (Or just add new line and type). All the styles are wiped out.

@barklund Should I move this to done and we get a new ticket filed?

**Comment by swissspidy** [comment]
> Should I move this to done and we get a new ticket filed?

Yes. Every time a ticket does not fully pass UAT, a new issue should be created to address the remaining issues.

**Comment by samitron7** [comment]
Moved to done but filed a new issue.
