### ISSUE TITLE
Dashboard: Toggle left nav A11y tab order

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#1786]
Spawned from https://github.com/google/web-stories-wp/pull/1771 

It would be great if when `tab` is selects the hamburger menu icon the next tab items would be the menu items in the left rail. Right now, because of the DOM layout, they are the last, and you have to tab through everything on the page.

Ideas to solve this includes updating the HTML to have aria roles for the nav vs the main area and ensuring tab focus regardless of outline.

**Comment by csossi** [comment]
Verified in QA
