### ISSUE TITLE
Text element: Resizing/rotating should be possible in edit mode  

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#1801]
## Feature Description

By original design, the Movable features (such as resizing and rotation) were disabled for a Text element in edit mode. The design has now been updated and it should be possible to scale and change the width of a text element in edit mode as well.

[See Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=8011%3A14748).

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
1. It should be possible to scale and change the width of a Text element in editor mode
2. It should be possible to rotate an element in edit mode
3. The font size should be adjusted while resizing, just as in the display mode

**Comment by csossi** [comment]
Tested in PR#2699

When I start typing content immediately after adding the text element and THEN grab a handle, the text entered is automatically selected

Video: https://drive.google.com/file/d/1_pIXpYWt7na7j-7OYnin6nWeG8mn7oW3/view

**Comment by miina** [comment]
Maybe we can merge this and create a separate issue for this specific edge case. I've tried disabling pointer events from the edit mode and it still happens -- not sure why the selection happens but perhaps it's not worthwhile to keep the full PR blocked for that. It also seems to happen on the main branch when dragging the mouse in the upper right corner while in edit mode.

@barklund WDYT?

**Comment by barklund** [comment]
I agree, let's file in separate issue as it's a bit esoteric to re-create.

**Comment by miina** [comment]
Follow-up issue: https://github.com/google/web-stories-wp/issues/3303
