### ISSUE TITLE
Pressing 'Enter' on a text element is not entering in edit mode sometimes

### ISSUE THREAD

**Issue by obetomuniz** [GoogleForCreators/web-stories-wp#1808]
## Bug Description

Pressing <kbd>Enter</kbd> in a selected text element sometimes not put that text element in edit mode.

## Expected Behaviour

Text elements selected in display mode should always go to edit mode when pressing <kbd>Enter</kbd>.

## Steps to Reproduce

Scenario 1:
1. Select a text element (display mode) 
2. Press <kbd>Enter</kbd>
3. Text element will go to Edit mode
4. Click outside the text element to leave the edit mode (without unselecting the text element)
5. Text element will go to Display Mode
6. Press <kbd>Enter</kbd> again

Scenario 2:
1. Add a text element
2. Press <kbd>Enter</kbd>

## Screenshots

![Untitled](https://user-images.githubusercontent.com/1680157/82254243-e05aa580-9928-11ea-93b1-ddffe130559f.gif)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@barklund Is this related to focus-trapping or don't know yet?
