### ISSUE TITLE
Text line height: change to percent values and implement auto value via GRT

### ISSUE THREAD

**Issue by dvoytenko** [GoogleForCreators/web-stories-wp#1820]
Per [spec](https://docs.google.com/document/d/1EQ12sD4a1plmMeBu7YMWOdUSg0FeegB9qi2_OlV3Tp0/edit#): 

> Allows the author to set the line-height to a specific value. Accepts a percentage from -100% to +200%. Set to the value of “Auto” by default. In this case, the line-height adapts to the current font size based on [Golden Ratio Typography](https://grtcalculator.com/) rules.

Thus, two changes need to be done:

1. We currently use fractional value for line height. This should change to `%` values.
2. We need to default line height to `auto` and implement automatic auto rules according [Golden Ratio Typography](https://grtcalculator.com/) rules

These changes need to be for both the editor and the output.

**Comment by dvoytenko** [comment]
/to @pbakaus @o-fernandez to confirm and prioritize.

**Comment by merapi** [comment]
Should cropping leading/trailing whitespace (in both modes % and auto) also belong here? https://docs.google.com/presentation/d/1ZiZWrmLiX40rt3n_1LMSGJxYWI-xsWFsS9bkzdbRIV8/edit?ts=5ec3ef17#slide=id.g7830109f71_0_105

Edit: it is now in the new epic https://github.com/google/web-stories-wp/issues/3532
