### ISSUE TITLE
Background Media behavior inconsistency

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#1821]
## Bug Description

The background behavior seems to be inconsistent/unexpected at times.

For example:
- Setting an overlay to a Page and then adding background media by dragging it directly from Library seems to keep the properties of the previous Overlay.
- Setting an overlay to a Page, then adding background from an existing Media Element by clicking "Set as background" removes the overlay.

Same goes for flipping: flipping seems to be stay when dragging and dropping to a background but not when using "Set as background".

## Expected Behaviour

It feels like Overlay should always remain for different background Media since the Overlay can be set for a Page separately.
It feels like Flipping should never remain for different background Media since flipping can be set per Media, not for a Page.

TBD by UX.

## Steps to Reproduce

1. Add a Page and set overlay
2. Drag and drop an image to be the background
3. See the overlay persisting.
4. Now click "Unset as background", see the overlay being unset
5. Add the Overlay again
6. Click "Set as background"
7. See the overlay being unset again whereas with drop targets it did not.

The same happens with Flipping.

## Screenshots
![May-18-2020 12-43-27](https://user-images.githubusercontent.com/3294597/82204608-80063c80-9905-11ea-9efb-598215c5725e.gif)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

#### Scenario 1
1. Set background image
1. Flip it
1. Drag image from library
1. Hover over background image edge and see new image **temp replacing background** with **no flip**
1. Drop new image over background image edge and see new image **replacing background** with **no flip**

#### Scenario 2
1. Set background image
1. Flip it
1. Click another image in library
1. Start dragging new image placed on canvas
1. Hover over background image edge and see new image **temp replacing background** with **no flip**
1. Drop new image over background image edge and see new image **replacing background** with **no flip**

#### Scenario 3
1. Set background image
1. Flip it
1. Click another image in library
1. Click the "set as background" button for new image and see new image **replacing background** with **no flip**

#### Scenario 4
1. Set background image
1. Assign linear overlay to background
1. Drag image from library
1. Hover over background image edge and see new image **temp replacing background** with **same overlay**
1. Drop new image over background image edge and see new image **replacing background** with **same overlay**

#### Scenario 5
1. Set background image
1. Assign linear overlay to background
1. Click another image in library
1. Start dragging new image placed on canvas
1. Hover over background image edge and see new image **temp replacing background** with **same overlay**
1. Drop new image over background image edge and see new image **replacing background** with **same overlay**

#### Scenario 6
1. Set background image
1. Assign linear overlay to background
1. Click another image in library
1. Click the "set as background" button for new image and see new image **replacing background** with **same overlay**

#### Scenario 7
1. Click an image in library
1. Start dragging new image
1. Drop new image over background image edge and see image **converted to background**
1. Press "unset as background" and see the image **restored to its original size**

#### Scenario 8
1. Click an image in library
1. Press "set as background" and see image **converted to background**
1. Press "unset as background" and see the image **restored to its original size**

**Comment by miina** [comment]
@o-fernandez Assigning you since it looks like this might need a product decision.

**Comment by miina** [comment]
cc @barklund here as well since you're currently generally reworking the background logic in #1798

**Comment by o-fernandez** [comment]
There are two things here: 

1. Inconsistencies in how "set as bg" works if you use the "set as background" button vs. if you use the drop target to drag image as a bg. This should be addressed. I've found related issues (e.g. #1411) and we really should avoid such behavioral deviations. 

2. For the specific issue here, should setting a new bg remove existing overlays? I'll defer to @samitron7  as a UX question. I can see go either way.

**Comment by barklund** [comment]
This will be fixed in #1207 actually.

In that issue it was resolved (by @pbakaus), that overlay should be preserved when overriding the background (not particularly spelled out it should work in all the ways though, but consistency is implied if nothing else), however we didn't address what happens if you remove the background image without replacing it (by "unsetting" as bg or deleting the object).

My current assumption is that the background overlay is reset though in such a case:

Thus summarizing behavior as:
- Background image is replaced by setting another image from library to background: **Overlay persists**.
- Background image is replaced by setting another image from canvas to background: **Overlay persists**.
- Background image is replaced by setting another image as background: **Overlay persists**.
- Background image is removed by unsetting as background: **Overlay resets**.
- Background image is removed by deleting background: **Overlay resets**.

The reason for the difference is, that those three ways of setting a background technically are completely different and the codebases are not shared (nor could they easily be), as they work very differently.

**Comment by miina** [comment]
Thanks for chiming in, @barklund!

It would also be good to clarify about other settings with UX, such as "flipping" -- currently flipping also persists when dragging an image to the background dropzone, meaning that the added image will get flipped right away and will stay flipped when removed as background, too.

Flipping also persists only in case of dropzones but doesn't when setting as background from the button -- another inconsistency.

**Comment by csossi** [comment]
Verified in QA
