### ISSUE TITLE
Allow removing all data when the plugin is installed

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#1822]
## Feature Description

We should delete all data from the database when uninstalling the WordPress plugin. **Ideally only when the user opted in to do so.**

This includes

* Any post of the `web-story` type
* All transients
* All options (style presets, publisher logos, db version, previous db version)
* `web_stories_is_poster` meta key on all attachments
* `web_stories_poster_id` meta key on all attachments
* Any relationship with terms in the `web_story_media_source` taxonomy

First version:

* Opt-in is done via a filter on PHP side.

Future version:

* Opt-in can be done on global settings page (#570)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

* Opt-in data removal on uninstall

**Comment by spacedmonkey** [comment]
Personally not a fan of uninstall hooks, I don't think they are good practice. Not all plugins delete data, so I am not sure that a user would expect all data to deleted. What if are had an issue with the plugin and you deleted and reinstalled the plugin. This happens to me all the time on sites I managed. If everything I uninstall the plugin, I lose my settings, I would get mad. 

Manage we could do something clever, hook into the uninstall process and show a confirmation message if they use also wants to remove data.

**Comment by swissspidy** [comment]
@spacedmonkey That's why this issue proposes an opt-in for data removal. Similar to how all major WordPress plugins do it, this could be done through a checkbox on the settings page (i.e. `[x] Delete all plugin data when uninstalling the plugin`).

**Comment by spacedmonkey** [comment]
> @spacedmonkey That's why this issue proposes an opt-in for data removal. Similar to how all major WordPress plugins do it, this could be done through a checkbox on the settings page (i.e. `[x] Delete all plugin data when uninstalling the plugin`).

Should this be an opt in or out setting?

**Comment by swissspidy** [comment]
An opt-in setting.
