### ISSUE TITLE
Change page preview size

### ISSUE THREAD

**Issue by wassgha** [GoogleForCreators/web-stories-wp#1834]
## Bug Description

The canvas size is changed per UX instructions to be 412:618. 

## QA instructions

This generally has effect on most of the features, but the key features to verify are:

1. Responsive sizing: making window smaller or bigger should resize the canvas and page carousel appropriate, but there's an absolute minimum size that editor cannot be smaller.
2. Lasso selection at the full and a smaller size should work correctly.
3. A previously saved story can be opened at the new editor and it will auto-adjust to the new size.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
Hi @wassgha, have you started working on this?

👍  If you have, please push whatever branch you have (so we can track progress) and move to "in progress".
👎  If not, please un-assign yourself, so someone else can pick this up.

**Comment by csossi** [comment]
verified in QA
