### ISSUE TITLE
Weird thumbnail after using a landscape image as "poster image" for a video

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#1835]
Steps to reproduce: 

- Add video
- Set different poster image for the video, use a landscape picture. 
- See that thumbnail preview looks odd

![weird thumbnail when set poster image for video](https://user-images.githubusercontent.com/13389997/82268463-0be78b00-993d-11ea-8250-82897af9886b.png)

**Comment by swissspidy** [comment]
Looks like a duplicate of #1123.

**Comment by o-fernandez** [comment]
Thanks for catching that, @swissspidy Appreciate the help. :)
