### ISSUE TITLE
Editor crashing when writing in Japanese

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#1836]
## Bug Description

I wrote some text in Japanese, the editor crashed. :'( 

## Expected Behaviour

Don't want it to crash. 

## Steps to Reproduce

See video. 

## Screenshots

[Editor crashing when writing JP text.zip](https://github.com/google/web-stories-wp/files/4647437/Editor.crashing.when.writing.JP.text.zip)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## QA Instructions
1. Add a text field
1. Click to enter edit mode
1. Use the Mac OS X built-in Hiragana keyboard
1. Type the characters "kon" and press <kbd>space</kbd>
1. Observe that Japanese characters are correctly inserted rather than the whole editor crashing.

**Comment by swissspidy** [comment]
Which tool are you using for that? Looks like a Chrome extension or perhaps [Google Input Tools](https://www.google.com/inputtools/).

**Comment by o-fernandez** [comment]
> Which tool are you using for that? Looks like a Chrome extension or perhaps [Google Input Tools](https://www.google.com/inputtools/).

Just my mac's hiragana input
![image](https://user-images.githubusercontent.com/13389997/82329045-b4820300-99ae-11ea-8a94-15ef9bacadb2.png)

**Comment by obetomuniz** [comment]
Trying to reproduce the issue, I was not able to input the same character of the video and crash the editor as described in the issue description. Can you please share with me the input used, @o-fernandez? 

Anyway, typing some Japanese characters from "Hiragana" keyboard, it reported console errors and did not persist the respective Japanese characters typed. It seems a draftjs known issue, which I am looking to workaround.

**Comment by o-fernandez** [comment]
I used the Mac OS X built-in Hiragana keyboard and wrote types in roman
characters "kon" and pressed the space bar, which gets it to コン
I was trying to type konnichi こんにち.
Hope that helps?

**Comment by csossi** [comment]
verified in QA ![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/b2ede516-778f-4b40-ac49-e27a7cc69f21)
