### ISSUE TITLE
Useless color preset option shown when bg image is selected

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#1838]
## Bug Description

If I select the page and it has a bg img/video, I can still see Color presets but clicking them does nothing

## Expected Behaviour

Color presets should only show those that are useful/usable, and be applied if I click them. 

## Screenshots

See video. 
[useless color preset option when bg image is set.zip](https://github.com/google/web-stories-wp/files/4647472/useless.color.preset.option.when.bg.image.is.set.zip)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@o-fernandez Based on Sam's first comment in [this comment thread](https://docs.google.com/document/d/1EQ12sD4a1plmMeBu7YMWOdUSg0FeegB9qi2_OlV3Tp0/edit?disco=AAAAJkni_Qo) it might need confirmation if it should be hidden or not. Perhaps it's still WIP and changing. Thoughts?

**Comment by o-fernandez** [comment]
> @o-fernandez Based on Sam's first comment in [this comment thread](https://docs.google.com/document/d/1EQ12sD4a1plmMeBu7YMWOdUSg0FeegB9qi2_OlV3Tp0/edit?disco=AAAAJkni_Qo) it might need confirmation if it should be hidden or not. Perhaps it's still WIP and changing. Thoughts?

Good catch, let me add this to the queue for UX to review. I think that we'd want to expand this ticket to specify: 
- if the user sets a color, is it a page color that is beneath the bg image/video? 
- if so, when the user removes the bg image/video, should the bg color persist? (I imagine yes)
- ensure user knows when they are applying a bg color vs. an overlay color. 

All good UX questions.

**Comment by samitron7** [comment]
![Group 5215 (2).png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/8fb08452-aa34-4eb3-8b0b-4f1a0470f5c7)

Removing UX Needed label as I think @miina and I are all squared on this.

**Comment by o-fernandez** [comment]
Will close this ticket and create a new one for Color Presets redesign changes.
