### ISSUE TITLE
Styling of text presets section (in design panel) could be improved

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#1839]
## Feature Description

Aesthetically, the design panel text presets doesn't look appealing or fitting for the editor's general UI. Would suggest restyling it. 

![Style presets could use some love.png](https://images.zenhubusercontent.com/5e98486db524b82fc96aeaf6/91bd3a67-061c-45e9-997e-1e18f0464392)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment]
@samitron7 UX Needed, I couldn't find any examples with presets in figma. It's always collapsed:
![image.png](https://images.zenhubusercontent.com/5e985a7aea3104e101699670/c4c6a1b5-583c-40dd-aa3b-bf929f616a98)

**Comment by samitron7** [comment]
FYI - this ticket will be assigned to Victor. Will update the team when work comes

**Comment by samitron7** [comment]
Update: Will review with Paul Thursday

**Comment by o-fernandez** [comment]
Will be covered by #353
