### ISSUE TITLE
Have to deselect the page to be able to undo full bleed image

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1840]
## Bug Description

Add image then click on full bleed icon then CMD + Z to undo. I can only undo if I deselect the page then undo

## Expected Behaviour

I should be able to undo making the image full bleed with CMD + Z and any other undo actions (click button)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment]
Flagging @o-fernandez for awareness and prioritization.

**Comment by o-fernandez** [comment]
Similar to #1852 
Individually, these look like P2, but they seem related so may need to prioritize an overall fix for why these odd states are happening. This can make the experience feel broken for the user.

**Comment by samitron7** [comment]
@o-fernandez @jauyong Can we close this ticket. Omar and I agreed that we're going to remove the feature for full bleed. Confirmed with our storytime partners that this feature has more cons then pros.

**Comment by o-fernandez** [comment]
Created #1932 to capture the ask to remove this feature. Will close this as duplicative/unnecessary given that.
