### ISSUE TITLE
Do not show Selection Handles when Dragging Text Element

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1841]
## Bug Description

When a text element is selected then dragged, do not show the selection handles JUST the outline box. 

## Expected Behaviour

do not show the selection handles JUST the outline box

## Steps to Reproduce

1. select a text element
2. drag it
3. see handles on element shown

## Screenshots

https://drive.google.com/file/d/10MnSiDlrj7yd55-lTPay4vgywfLonVMc/view?usp=sharing

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
From the video, it seems that text element was the only one misbehaving.

**Comment by barklund** [comment]
Note that this issue conflicts with instructions in https://github.com/google/web-stories-wp/issues/1209, which says to (also) remove the blue outline box when dragging. These two issues should be consolidated and merged.

**Comment by o-fernandez** [comment]
@samitron7 can you clarify if just removing the entire blue outline is the right solution? In which case we can close this and just prioritize #1209 as @barklund says.

**Comment by samitron7** [comment]
Yes, remove the blue outline. We do this so the user can just see the text when they drag to position on their lovely layouts.
