### ISSUE TITLE
Uploading UI while scrolled down in Media Library

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1847]
## Feature Description

If I scroll up on the list then drag an image from my local drive to the media library or the page, I should see a UI that lets me know the media is being uploaded. 

[Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=7507%3A303081)

Related: https://github.com/google/web-stories-wp/pull/575

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
1. After scroll in the media library and dragging an image from my local drive to the media library or the page to upload, I should see a UI that lets me know the media is being uploaded.

**Comment by o-fernandez** [comment]
I see this addressed currently in the editor. closing as fixed.
