### ISSUE TITLE
Fix alignment and opacity of "No Media Found" Message

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1849]
## Bug Description

“No media found” should be aligned to the centered and have opacity.

[Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=7497%3A301236)

## Acceptance Criteria
1. opacity: 0.54
2. Message is centred per Figma

See comments for conversation on: If there are no results, do not show the upload button or the media types

## Steps to Reproduce

1. yield no results by using the search in the media library
2. note message for "no media found"

## Screenshots

![image.png](https://images.zenhubusercontent.com/5e985a7aea3104e101699670/e52701a7-b552-4ec9-acaa-214da371892c)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Is there a Figma link for this?

> “No media found” should be aligned to the centered and have opacity.

How much opacity? Things like that need to be specified.

---

> If there are no results, do not show the upload button or the media types

Not showing the media types is odd. What if I am currently filtering by videos and wanna search for videos only? Then when I don't find any videos I might wanna switch to "All".

Related: #1844

Second, not showing the upload button is odd too. Let's say I search for a specific media item, but I don't find it, so I wanna upload a new one. Why hide the button?

**Comment by o-fernandez** [comment]
Agree that hiding the filters and upload option seems odd. Would prioritize styling the message appropriately, but let's reconsider hiding things.

**Comment by jauyong** [comment]
Add some details and Figma link to ticket

**Comment by samitron7** [comment]
@swissspidy 
1. If your results yield a result, the media type is there (so not sure what you're looking at).
2. With the media integration work, we're redoing the entire media panel and moving upload to their section so don't worry about the upload button. Will take your point into consideration
3. The Figma file is in the bug description :) but #FFF at 54%

**Comment by maxyinger** [comment]
Appears to already be completed:

![Screen Shot 2020-10-08 at 12.04.44 PM.png](https://images.zenhubusercontent.com/5ea0a3e2f739259b2b0b092a/5f0b4174-6123-447c-bf73-205617cb3442)
