### ISSUE TITLE
Clicking on add to color presets not working. 

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#1853]
## Bug Description

Clicking on the "Add to color preset" option is not working. 

## Expected Behaviour

Expected new color to be added to the presets section. 

## Steps to Reproduce

Add text element to page
Change text element color to a new color
Click on "Add to color preset" in the color selector, note that nothing is added to presets. 

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Looks like the link has lost its styling as well somehow, picking this up.
