### ISSUE TITLE
Text styles presets misaligned after deleting all color presets

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#1854]
## Bug Description

Text styles presets misaligned after deleting all color presets

## Steps to Reproduce

Add some color presets to the design panel
Add some text style presets to the design panel
Click "edit" and remove all color presets. 

Notice that the styles presets lose the padding between where they start and the left edge of the design panel. 

## Screenshots

![Before deleting color preset.png](https://images.zenhubusercontent.com/5e98486db524b82fc96aeaf6/3f0b073c-2493-4e21-a085-4a77bafd5487)

![After deleting color preset.png](https://images.zenhubusercontent.com/5e98486db524b82fc96aeaf6/123d6fa6-b4e0-43aa-9fec-abc0d6569671)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by dreamofabear** [comment]
Good candidate for a screenshot test.

**Comment by miina** [comment]
Note that this seems to happen only when there's just one type of presets present (e.g. only Styles or only Colors).
