### ISSUE TITLE
Dashboard Story Rename should not dismiss when dragged 

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#1865]
## Bug Description

Click rename in three-dot menu, then drag cursor to select text, and release outside of the input. For some reason box goes away. We dismiss the rename when they click outside as a cancel, but in this case it's unique because they start dragging inside the input but then finish outside.

## Expected Behaviour

It should not close the rename box when the cursor drag starts inside the box but mouses up outside.

## Steps to Reproduce

Click rename in three-dot menu, then drag cursor to select text, and release outside of the input. For some reason box goes away.

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. Enter "title edit" mode by clicking on rename option in 3-dot menu for a story (in dashboard)
2. Click inside the text box and drag mouse to select full text, release click when outside of the text box. 
3. See that text is selected and you are still in text edit mode. Can rename the story. 

NOTE: Clicking outside the text field will cancel/escape the title edit operation and discard changes, similar to pressing esc key.

**Comment by csossi** [comment]
Verified in QA - P:R#2057
