### ISSUE TITLE
Dashboard Author should have a click action and only show when there are more than one user

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#1866]
## Feature Description

1. When the WordPress instance only has one User account, the author should not appear on the grid view on dashboard
2. When the title is clicked it should do ...

[Figma](https://www.figma.com/file/hUTw97921an0e3uU28JoDn/Dashboard?node-id=687%3A1412)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
We can pass a flag via config that indicates whether it's a multi-author site or not. Would be as simple as using `'isMultiAuthor' =>is_multi_author()` in PHP

**Comment by jauyong** [comment]
Putting in icebox per grooming on May 20

**Comment by BrittanyIRL** [comment]
Thought I'd look back into this real quick - see if I could just implement it. 

Tried adding `'isMultiAuthor'   => is_multi_author(),` to the dashboard.php config and referencing it in the dashboard. Set up is fine, but it remains `false` so i'm missing something. Tested with a variety of users and published/draft stories. Looked into the docs a little bit and am unsure where I made my mistake. 

https://developer.wordpress.org/reference/functions/is_multi_author/

This is obviously not time sensitive, but @swissspidy or @spacedmonkey  - if either of you can see where my error is just by looking at this lemme know what it is and then pea pod can take it from there.

**Comment by swissspidy** [comment]
`is_multi_author()` only checks for users who have _published_ at least 1 _post_ (not story).

If we want to check for published _stories_, we'd need to implement our own version of that (very easy)

**Comment by BrittanyIRL** [comment]
🤦  ah yup that makes wayyy more sense to have out of the gate. ok cool well i'll leave this here then since i'm not going to implement that in php 😅  


@o-fernandez is this something you want to prioritize? Should we get this on the roadmap at all?

**Comment by o-fernandez** [comment]
Doesn't seem critical to me, honestly. I'd close or keep in the backlog.
