### ISSUE TITLE
Allow users to filter/search by author in the story dashboard

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#1872]
## Feature Description

Allow users to filter/search by author in the story dashboard. Search may not be possible, but at least filtering. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by maxyinger** [comment]
So we could use the author query arg on the frontend:
https://developer.wordpress.org/rest-api/reference/posts/#arguments

... but we'd have to essentially search for the authors that match on the frontend, then send out a separate query on top of the search term query that queries all stories from those authors.

Essentially every search would populate stories from both these queries:
```
query(`/wp-json/web-stories/v1/web-story/?search=${search_input_value}`);
query(`/wp-json/web-stories/v1/web-story/?author=${getAuthorsThatMatch(search_input_value)}`)
```

Assuming we have all the authors stored on the FE, this would be possible, but feels like maybe something we'd prefer to handle on the BE.

idk. curious to get your input on this @swissspidy & @spacedmonkey ?

**Comment by swissspidy** [comment]
This should just be an author dropdown just like we have in the editor Document panel.

Then simply use the author query arg to filter stories by the author chosen in the dropdown.

No freeform text field to search by authors

**Comment by maxyinger** [comment]
oh nice. lol yea that's much easier. right on

**Comment by csossi** [comment]
Verified in QA
