### ISSUE TITLE
Edit Mode of image hides Zoom Slider outside page

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1873]
## Bug Description

Edit Mode of image has a zoom slider, but this is being cut off by the page edge. This in particular means that any BG image is missing the Zoom Slider completely. I cannot change the zoom of the bg image. 

## Expected Behaviour

In edit mode of a any image, I should be able to change the zoom. 
[Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=8284%3A1424)

## Steps to Reproduce

1. Enter edit mode of a bg image. 
1. Try to change the zoom

## Screenshots

![Screen Shot 2020-05-19 at 1 28 18 PM](https://user-images.githubusercontent.com/637548/82468049-5fb6b900-9a90-11ea-8d85-f21d3f598a8b.png)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
@jauyong The gif doesn't seem to be working. Perhaps too big? You could also upload a ZIP file with a video in it.

**Comment by miina** [comment]
Should be a duplicate of #1491, or at least would make sense to get resolved together.

**Comment by jauyong** [comment]
closing in favour of #1491
