### ISSUE TITLE
Truncate text in input fields with close icon

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1874]
## Bug Description

We need to truncate the text and not let it bleed into the remove icon

This input field is used in  various places. Let's make sure we updated it everywhere.

Also, we need to replace the "close" icon with this one: https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=10350%3A10

## Screenshots

![image.png](https://images.zenhubusercontent.com/5e985a7aea3104e101699670/df12d886-93d9-4228-b057-e099cd884cc3)

![image.png](https://images.zenhubusercontent.com/5e985a7aea3104e101699670/4f7b0b54-c25b-477e-ba3e-e41691a3316e)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Can we combine this with #1875? Looks like it's the same component anyway.

**Comment by swissspidy** [comment]
It's probably more a lack of right-padding that needs to be fixed here, rather than truncating text.

**Comment by jauyong** [comment]
@samitron7 UX Needed. Are were truncating? Adding right-padding?

**Comment by swissspidy** [comment]
I think we mean the same, just with different words :-)

**Comment by samitron7** [comment]
A couple things here:

1. The 'x' icon should only appear if you click inside the input field [[Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=8533%3A1739)].
2. We should truncate the text [[Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=10350%3A10)]

**Comment by csossi** [comment]
Verified in QA
