### ISSUE TITLE
Truncate Alt Text in Design Panel

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1875]
## Bug Description

We need to truncate the text and not let it bleed into the remove icon
Related: #1874

## Steps to Reproduce

enter a long Alt text in the design panel for an image

## Screenshots

![image.png](https://images.zenhubusercontent.com/5e985a7aea3104e101699670/4f7b0b54-c25b-477e-ba3e-e41691a3316e)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Can we combine this with #1874? Looks like it's the same component anyway.

**Comment by swissspidy** [comment]
It's probably more a lack of right-padding that needs to be fixed here, rather than truncating text.

**Comment by jauyong** [comment]
@samitron7 UX Needed. Are were truncating? Adding right-padding?

**Comment by swissspidy** [comment]
I think we mean the same thing :-)

**Comment by swissspidy** [comment]
Let's consolidate these issues...

Duplicate of #1874
