### ISSUE TITLE
Overlay Being Applied to Thumbnails but not Page

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1876]
## Bug Description

The overlay is being applied to the thumbnails but not on the page
See #1207

## Expected Behaviour

Overlays should be applied to the page

## Steps to Reproduce

1. add a bg to a page
2. set an overlay

## Screenshots

 see video here: https://docs.google.com/presentation/d/1ZiZWrmLiX40rt3n_1LMSGJxYWI-xsWFsS9bkzdbRIV8/edit?ts=5ec3ef17#slide=id.g77fdc779d5_0_401

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
This might have been fixed already by #1806. @obetomuniz, can you check?

**Comment by obetomuniz** [comment]
Yeah, it was fixed @barklund
