### ISSUE TITLE
Dragging video to background not registering

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1877]
## Bug Description

I dragged a video to the page to replace the existing bg video. You can see that the thumbnail is updated by the video on the page is not.

## Expected Behaviour

page should show the new video

## Steps to Reproduce

1. add a bg video to a page
2. drag a new video onto the page to replace the original bg video

## Screenshots

https://drive.google.com/file/d/1NeeBON9e6K2L2NSxjoqEw8yiSFAbs3vk/view?usp=sharing

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@jauyong Is this still an issue? Unable to reproduce it. Perhaps it got fixed within #1798

**Comment by jauyong** [comment]
looks fixed to me I'm closing. 
@swissspidy what info were you looking for?
