### ISSUE TITLE
Setting element's width/height to 0 causes oddities

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#1881]
## Bug Description

Follow-up to #993 

- It's currently possible to set the width and height of an element to 0 which causes odd behavior in the editor, such as the element "jumping" to the top left corner of the Page and not being possible to drag it out of there.

- It's currently possible to resize a multi-selection to 0 which causes similar oddities.

## Expected Behaviour

Even if the element width/height can be set to 0, it shouldn't cause buggy behavior.
An alternative would be to set the min width/height to 1px from the design panel.

Also, there should be some kind of limit place for resizing via multi-selection as well.

## Steps to Reproduce
1.
- Add an element
- Set its width and height to 0 from the Design Panel
- Now try interacting with the element

2.
- Add a few elements
- Multi-select a few of these
- Resize to zero
- Now try interacting with the elements after deselecting these.

## Screenshots
After resizing the element to 0, then resizing it larger again and trying to drag it:
![82196667-48de5e00-98fa-11ea-98a2-77969053a58b](https://user-images.githubusercontent.com/3294597/82453031-50dffe80-9ab0-11ea-8ac0-793d5e2fa617.gif)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## QA Instructions

1. Add a media element to a page
1. Resize either dimension to 0 in the design panel
1. Observe that no "weirdness" happens but the value is just set to 10 as the minimum possible size

**Comment by miina** [comment]
@o-fernandez and @samitron7 Tagging you here for thoughts on if we should consider enforcing minimum element size to 1 -- from Design Panel as well.

Also, if we should have a limit for multi-selection resizing -- e.g. not allowing to resize the full selection to 0.

Thoughts?

**Comment by o-fernandez** [comment]
Yes, we should definitely have min/max limits on all elements. I have a [draft spec](https://docs.google.com/spreadsheets/d/1hdru-_p4Yk-VFQ1rEFGYHHI2A7eNZkxLA33-LblG8sE/edit#gid=0) that I need to review with @samitron7 and others to get a sense of what are the good min/max values to pick here, let me share for input.

**Comment by obetomuniz** [comment]
@miina @o-fernandez  I will link this one on #2255. After adding input helpers there for min-max input values, I am not able to replicate the issue. Also, let me know if we will use 10 (as specced currently in the spreadsheet) or 1 (as mentioned above) as the minimum for `width`/`height`.

**Comment by o-fernandez** [comment]
> @miina @o-fernandez I will link this one on #2255. After adding input helpers there for min-max input values, I am not able to replicate the issue. Also, let me know if we will use 10 (as specced currently in the spreadsheet) or 1 (as mentioned above) as the minimum for `width`/`height`.

The spreadsheet is the right source for the value, so 10 in this case.

**Comment by merapi** [comment]
> The spreadsheet is the right source for the value, so 10 in this case.

Update for anyone reading it: it's now 1 for width/height via input (and 20 by handles), so we can create lines.

**Comment by csossi** [comment]
Tested in QA env - PR#2255

Still able to set height/width=0 (with the subsequent jumping around as originally reported above

**Comment by bmattb** [comment]
@merapi  flagging this for you as this is one of the last Sprint 30 outstanding tickets remaining.

**Comment by merapi** [comment]
Fixed 0 in width/height.

**Comment by samitron7** [comment]
Has this been pushed? I'm still able to set 0 W/H

**Comment by merapi** [comment]
@samitron7 it's not yet merged.

**Comment by csossi** [comment]
Verified in QA - PR#2255

W/H input min set to 1
Handles use set to 20
