### ISSUE TITLE
Text element: Edit mode background not extending with new lines

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#1883]
## Bug Description

When adding a new line in editor, the edit mode background does not extend with it and stays transparent.

## Expected Behaviour

The text edit mode background should extend when adding new lines (and also reduce if removing lines)

## Steps to Reproduce

- Add a text element
- Go to edit mode
- Add a new line
- See the edit background area not updating.

## Screenshots
![edit-mode](https://user-images.githubusercontent.com/3294597/82457732-0eb9bb80-9ab6-11ea-89a5-3a8fb67dfd4c.gif)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA - PR#2554

**Comment by samitron7** [comment]
@miina Where we able to remove the text element background? If so, this issue is probably not valid anymore?

**Comment by miina** [comment]
@samitron7 The removal will be done in #2040, this is still currently relevant but soon won't be anymore. Probably we can close this issue though (since it has been merged for quite some time already anyway but it will change again). Thoughts?

**Comment by samitron7** [comment]
Verified in UAT 

@miina Yeah sounds fair to me. I tested it and it seems fine. So moving to done.
