### ISSUE TITLE
Remove category/tags from All Stories view

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#1884]
## Feature Description

Per discussion in #489, category and tags for story organization won't be supported in the version 1.0 of the story editor. As such, we need to remove the category and tags from being shown in: 
1. story dashboard list view
2. All Stories view (classic wp view)

## Additional Context

#489 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
I can handle part 2)

**Comment by spacedmonkey** [comment]
I have created  -  #2073 but it seems to break the dashboard in list view. 

I can leave this with @BrittanyIRL @carlos-kelly to do that work before  ( or as part of ) #2073

**Comment by carloskelly13** [comment]
Perfect. Yeah we use the IDs to iterate the GET of categories and tags and match them up. We can drop that and those columns!

**Comment by carloskelly13** [comment]
@spacedmonkey Would you be fine with us adding the JS-part to your branch in #2073 or we can branch off of that. Either works.

**Comment by spacedmonkey** [comment]
> Would you be fine with us adding the JS-part to your branch in #2073 or we can branch off of that. Either works.

@carlos-kelly Feel free to add to my PR.

**Comment by csossi** [comment]
Verified in QA (merged - reviewed on Master)

**Comment by swissspidy** [comment]
Assigning to you for UAT step & closing
