### ISSUE TITLE
Auto Vs Manual Page Iteration in Story Schema

### ISSUE THREAD

**Issue by maxyinger** [GoogleForCreators/web-stories-wp#1887]
This task is to figure out where auto increment duration should live in the story schema and use it as a metric to increment pages if found for dashboard play on hover. If not found use a default duration.

Sam, Paul & Omar are still fine tuning behavior here. Check in with them to see if they'd like any additional changes to behavior for dashboard auto story page increment on hover when completing this task.

**Comment by swissspidy** [comment]
I thought we already have an autoAdvance value in the schema? Defaults to 7s if there‘s no video found. Or am I missing something?

**Comment by jauyong** [comment]
@samitron7 and @o-fernandez to sync and add details

**Comment by o-fernandez** [comment]
Synced with Sam, for play on hover (in the dashboard) we'd want it to be more of a quick preview, so ~2 seconds per page seems reasonable. The user would click on "preview" if they want to see the real preview.

**Comment by maxyinger** [comment]
> I thought we already have an autoAdvance value in the schema? Defaults to 7s if there‘s no video found. Or am I missing something?

Ah yup. I found it. guess we're don't need this at all here tho if we're just making them all 2s

**Comment by maxyinger** [comment]
Taken care of here:
https://github.com/google/web-stories-wp/pull/1861

**Comment by csossi** [comment]
Verified in QA (#1861)
