### ISSUE TITLE
Animation Editor - Add  type specific controls for animation parts

### ISSUE THREAD

**Issue by maxyinger** [GoogleForCreators/web-stories-wp#1889]
Right now in the animation editor:
http://localhost:8899/wp-admin/admin.php?page=stories-dashboard#/story-anim-tool

We only have Delay & Duration Inputs for an animation type. This task is to create animation type specific inputs for the existing animation types to choose from so you can customize applied animations beyond duration and delay

**Comment by mariano-formidable** [comment]
Fixed by this [PR](https://app.zenhub.com/workspaces/web-stories-5e94d3aced449034e1e9b226/issues/google/web-stories-wp/2060)
