### ISSUE TITLE
Automatically Play Video if it is a background

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1892]
## Bug Description

I drag a video to set as BG. The video should automatically play once it’s set to the BG. 

Figma:
[Set video as bg
](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=7941%3A7809)
[Playback behavior
](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=7507%3A304435)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by merapi** [comment]
The video should auto-play only when dragged from Library, not always (e.g. dragged from canvas to bg), right? @samitron7

**Comment by samitron7** [comment]
Yes, let's simplify and just have the video auto-play in these scenarios:

If you click on video in Library -> insert and auto-play
If you drag it from Library into bg or shape as drop target -> auto-play
If you drag it from Canvas into bg or shape as drop target -> auto-play

**Comment by merapi** [comment]
> Yes, let's simplify and just have the video auto-play when you initially drag onto the page. If the video is already on the page and you drag into any drop target (ie the page, any shape, into another image etc..basically anything that has an available drop target) then it does not need to auto-play.

Just to be clear, it's easier to always auto-play the video on drop (we don't have to detect certain conditions). So if that's what we want - that would simplify things. @samitron7

**Comment by miina** [comment]
@merapi Looks like this is also addressed in #1948, at least the video started auto-playing IIRC, could you confirm?

**Comment by merapi** [comment]
> @merapi Looks like this is also addressed in #1948, at least the video started auto-playing IIRC, could you confirm?

It will be covered there, right now it works for elements inserted from Media Library. I wanted to clarify how this should work for BG elements.

**Comment by samitron7** [comment]
@merapi @o-fernandez chatted offline and agreed to:

If you click on video in Library -> insert and auto-play
If you drag it from Library into bg or shape as drop target -> auto-play
If you drag it from Canvas into bg or shape as drop target -> auto-play

I edited my comment above to reflect this so there is no confusion.

**Comment by csossi** [comment]
Verified in QA
