### ISSUE TITLE
Playback button should be consistently sized

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1894]
## Bug Description

Playback button should be the same size until the video is resized to a min W or min H. When the video is resized below the min H/W, pop the playback control outside of the video element. 

Figma flow

## Steps to Reproduce

1. Resize various videos and note playback button size

## Screenshots

![image.png](https://images.zenhubusercontent.com/5e985a7aea3104e101699670/d5261462-24ad-4498-9f36-a5e923d3003f)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
@merapi is this fixed in #993 or just related?

**Comment by merapi** [comment]
> @merapi is this fixed in #993 or just related?

Just related (new behavior, old was based on [element size](https://github.com/google/web-stories-wp/pull/720#discussion_r398116128)).

**Comment by miina** [comment]
@merapi Assigning this to you since it'll be covered by https://github.com/google/web-stories-wp/pull/1948

**Comment by csossi** [comment]
Verified in QA
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/1bbedef1-bcd8-44d7-a43a-e07e605d3a4a)
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/3624a6cb-64d0-4d7f-8d41-635501fcb140)

**Comment by samitron7** [comment]
Verified in UAT
