### ISSUE TITLE
The bounding box for the blobs should not contain empty spaces.

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1896]
## Bug Description

The bounding box for the blobs should not contain empty spaces.

## Steps to Reproduce

1. Add a blob shape
2. click on it / make it the focus

## Screenshots

![image.png](https://images.zenhubusercontent.com/5e985a7aea3104e101699670/03b48fc2-7d51-4121-b22c-76eddd4abe26)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Not seeing any change here, @barklund

**Comment by swissspidy** [comment]
_This works as expected._

**Before:**

Without this change I see:

* 8 different blob shapes
* Whitespace between actual blob and blue selection box

<img width="1680" alt="Screenshot 2020-06-24 at 14 35 36" src="https://user-images.githubusercontent.com/841956/85557443-0eb65980-b628-11ea-86d8-7acf0786ba3a.png">

**After**

After applying/testing #2574 I see:

* Only 1 blob shape
* No whitespace between blob and selection box
* Blobs have been migrated appropriately

<img width="1680" alt="Screenshot 2020-06-24 at 14 38 29" src="https://user-images.githubusercontent.com/841956/85557812-6d7bd300-b628-11ea-9f58-388b6db021e2.png">

**Comment by samitron7** [comment]
Verified in UAT
