### ISSUE TITLE
Dashboard Hover/Focus to animate story and iterate through pages

### ISSUE THREAD

**Issue by maxyinger** [GoogleForCreators/web-stories-wp#1897]
This is an in progress task to play story animations on hover/focus within the dashboard

**Comment by maxyinger** [comment]
is this a duplicate of:

https://app.zenhub.com/workspaces/web-stories-5e94d3aced449034e1e9b226/issues/google/web-stories-wp/1521

@BrittanyIRL @carlos-kelly ?

**Comment by carloskelly13** [comment]
It is!

**Comment by maxyinger** [comment]
animation is behind a feature flag now, so should only see the stories iterate through pages.

**Comment by csossi** [comment]
Verified in QA (#1861)
