### ISSUE TITLE
Inconsistencies with font display between the editor and FE

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#1900]
## Bug Description

There are some odd inconsistencies happening between the editor and the FE.
Font weight doesn't seem to be added correctly, additionally, for some unknown reasons, only `italic` font is pulled in sometimes for a font even though it's not used. Displays correctly in the editor.

## Expected Behaviour

Fonts should always use consistent font weight and style in the editor and in the FE

## Steps to Reproduce

1. Add 2 Pages
2. Add some text to both pages with Open Sans Condensed.
3. Assign Light on one page as the font weight and bold on the other page, for the same font family
4. Now see the FE -- the fonts are in italic, in the editor not.

The [loaded font src](https://fonts.googleapis.com/css2?display=swap&family=Open+Sans+Condensed%3Aital%2Cwght%401%2C300) in the FE.

## Screenshots
Not italic in the editor:
![Screenshot 2020-05-20 at 17.31.07.png](https://images.zenhubusercontent.com/5e987994ea31047d41699714/97680975-2940-4152-8830-9562ff7fe7cc)

Italic in the editor:
![Screenshot 2020-05-20 at 17.31.18.png](https://images.zenhubusercontent.com/5e987994ea31047d41699714/d8214bdb-cceb-479b-b388-c5d12d2da52b)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Moving to QA since #2324 should fix this, too.

**Comment by samitron7** [comment]
@miina Can you let me know what I should be testing here?

**Comment by miina** [comment]
@samitron7 The testing instructions were in the PR, you might have already tested it.
Copying it over:
1. Add 2 Pages
2. Add some text to both pages with Open Sans Condensed.
3. Assign Light on one page as the font weight and bold on the other page, for the same font family
4. Verify that the text looks the same in the editor and in the front-end.

Basically making sure that the editor looks the same as the front-end / Preview.
