### ISSUE TITLE
Color picker: sliders are not draggable without focusing first

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#1901]
## Bug Description

The color picker sliders are not draggable unless the user focuses on the slider first.

## Expected Behaviour

The color picker sliders should always be draggable.

## Steps to Reproduce

1. Add a shape
2. Open the color picker
3. Try to use the opacity slider.
4. Not happening!

## Screenshots
![sliders](https://user-images.githubusercontent.com/3294597/82467460-fa7bbb80-9ac1-11ea-971f-6cf47045393d.gif)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@barklund @bmattb FYI Pulling this into the Sprint since the Sprint backlog is empty. Not sure I'll finish within the sprint though depending on how much the PR-s waiting for review will need attention.

**Comment by csossi** [comment]
Verified in QA

**Comment by samitron7** [comment]
Verified in UAT. For this particular ticket, the slider does work however, I found an issue and filed it [here](https://github.com/google/web-stories-wp/issues/5401):

When we set opacity to zero within the color picker or enter it inside the input value in the design panel, the opacity input field and hex value disappears. 


<img width="912" alt="Screen Shot 2020-11-23 at 9 27 41 AM" src="https://user-images.githubusercontent.com/10889431/99994874-7951f980-2d6e-11eb-8077-ab59498ba950.png">

**Comment by miina** [comment]
Noted, thanks for finding and filing that.
Since it's unrelated to the underlying issue handled here, closing this one as Done.
