### ISSUE TITLE
Add feature flag to enable/disable Dashboard animations

### ISSUE THREAD

**Issue by mariano-formidable** [GoogleForCreators/web-stories-wp#1902]
We want an easy way to enable/disable _all_ template/story animations in the dashboard (perhaps with a simple feature flag system).  This should effect the following areas:

- Story/Template grid (which can animate on-hover).
- Template detail page.
- Generated `amp-story` (animation tags should _not_ render if animations are disabled).

**Comment by maxyinger** [comment]
think I took care of this here with `enableAnimation` feature flag:
https://github.com/google/web-stories-wp/pull/1861

**Comment by maxyinger** [comment]
covered in https://app.zenhub.com/workspaces/web-stories-5e94d3aced449034e1e9b226/issues/google/web-stories-wp/1897

**Comment by csossi** [comment]
Verified in QA
