### ISSUE TITLE
Add animation support to generated amp-story

### ISSUE THREAD

**Issue by mariano-formidable** [GoogleForCreators/web-stories-wp#1903]
Update the `amp-story` generation logic so page level `animations` are parsed and rendered using our `AMPWrapper` animation system.

**Comment by maxyinger** [comment]
I think this completes this task:
https://github.com/google/web-stories-wp/pull/1846

@mariano-formidable

**Comment by mariano-formidable** [comment]
> I think this completes this task:
> #1846
> 
> @mariano-formidable

Oh no, that other PR just added support for AMP animations using our animation pattern, but I haven't updated the actual `amp-story` generation logic to include animations.  I favored testing in a storybook `amp-story` instead of updating the generation logic because that would affect all stories going forward.  

This issue is specifically about updating the story generation code.

**Comment by maxyinger** [comment]
Ahh I see. right on. cool.

**Comment by swissspidy** [comment]
Just dropping a note there that this would be a great use case for the `toBeValidAMP` assertions we have.

**Comment by csossi** [comment]
Testing instructions required - thanks

**Comment by swissspidy** [comment]
The connected PR #2268 has all the testing instructions. However, since this is behind a feature flag, there's actually no need for QA.

Therefore skipping & merging.

Reminder for the QA process: https://docs.google.com/document/d/1oZXjSJX30JLsIgCqOaER0Uff3Y_Tr-NCiQIfrYUnX9Y/edit?ts=5ebc211a#
