### ISSUE TITLE
Set Min and Max values input values

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1905]
Current spec: [Min/max values](https://docs.google.com/spreadsheets/d/1hdru-_p4Yk-VFQ1rEFGYHHI2A7eNZkxLA33-LblG8sE/edit#gid=0)

These values are rough guesses based on what seems reasonable, but subject to revision as we learn more from users.

**Comment by obetomuniz** [comment]
#1549 Duplicate @jauyong @o-fernandez ?

**Comment by o-fernandez** [comment]
Closed as dupe of #1549
