### ISSUE TITLE
Changing tab to "document" creates a history entry for no reason

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#1907]
## Bug Description

On a saved story, the basic action of changing the inspector tab from "design" to "document" creates a history entry (which can be seen by the "save" button re-enabling).

Simply changing tabs should not edit the story.

## Expected Behaviour

Changing tabs should not edit the story.

## Steps to Reproduce

1. Switch to the design panel if you aren't already
1. Save the story and observe the "save" button being disabled (because the story hasn't changed since last save)
1. Switch tab to "document" and observe the "save" button being re-enabled (because the story somehow changed since last save)

## Screenshots

![document-history-entry.gif](https://images.zenhubusercontent.com/5e9877d5cc796e8868614c8d/1ea2c311-ff14-44c7-bdb0-e8fcca36b604)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
This makes "undo" feel broken if I take an action, click on document tab, and then click undo. Adding it for Stable release.

**Comment by miina** [comment]
@barklund  @bmattb @o-fernandez  FI: I'm adding this to Stable and assigning to myself since #4345 is fixing this as well.

**Comment by csossi** [comment]
Verified in QA
