### ISSUE TITLE
Removing Background sometimes removes Media Asset

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1914]
## Bug Description

Clicking on Remove as bg sometimes removes the media asset instead of detaching it from the bg

## Expected Behaviour

After setting background by dragging it from the library, removing media as background should place it in the foreground on the page

## Steps to Reproduce

1. add a background by dragging it from the media library
2. remove it
3. repeat until you get the issue

## Screenshots

https://docs.google.com/presentation/d/1ZiZWrmLiX40rt3n_1LMSGJxYWI-xsWFsS9bkzdbRIV8/edit?ts=5ec3ef17#slide=id.g77fdc779d5_0_229

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
This should have been fixed by #1191 being merged. Please check if still an issue.

**Comment by miina** [comment]
@jauyong Could you confirm it's still an issue? There have been quite a lot of changes to the background meanwhile, it's very likely this was fixed, too.

**Comment by o-fernandez** [comment]
I can't repro, so for now closing.
