### ISSUE TITLE
Performance: slow navigation

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1916]
## Bug Description

Please check performance on this issue. It’s not consistent for me. Occasionally, I’ll click on a page thumbnail and it hangs for a split sec before displaying the selected page

Edit:
This navigation performance issue should improve with #7987, however, it looks like thumbnails carousel is not the only part that makes it lag. Especially if there are many elements on the current page, the navigation can be quite slow. Let's figure out what else is making it lag and how can we improve it.

## Screenshots

See video: https://docs.google.com/presentation/d/1ZiZWrmLiX40rt3n_1LMSGJxYWI-xsWFsS9bkzdbRIV8/edit?ts=5ec3ef17#slide=id.g780d0a5251_0_103

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
In Backlog Grooming Morten flagged that this is related to overall performance issues and that a solution for those issues would likely address these. This is closely related to #5040 and #5041

**Comment by csossi** [comment]
Verified in QA
