### ISSUE TITLE
Use blue box to indicate page focus in grid view

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1920]
## Feature Description

We should use a selection box instead of the top blue bar to indicate the selected state

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. When a page is selected in the grid view, a blue box should be used to indicate focus

**Comment by barklund** [comment]
@samitron7 is this still relevant? I thought the blue overline was also the current design for the selected page?

**Comment by samitron7** [comment]
We can close this out. This will be part of the new visual design work.
