### ISSUE TITLE
Improve Animation when Changing Zoom in Grid View

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1921]
## Bug Description

Resizing thumbnail animation is super janky (see animation)

## Expected Behaviour

When resizing the gridview, the animation should be smooth
@samitron7 to provide further details

## Steps to Reproduce

1. go to grid view and change zoom

## Screenshots

See video https://docs.google.com/presentation/d/1ZiZWrmLiX40rt3n_1LMSGJxYWI-xsWFsS9bkzdbRIV8/edit?ts=5ec3ef17#slide=id.g780d0a5251_1_0

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by samitron7** [comment]
@jauyong We can close this. New visual design coming in and this will change the grid view a bit.
