### ISSUE TITLE
Set Background Opacity of grid view to 100%

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1922]
## Bug Description

BG opacity of grid view should be set to 100% so that the editor does not bleed through

## Steps to Reproduce

go to the grid view

## Screenshots

https://docs.google.com/presentation/d/1ZiZWrmLiX40rt3n_1LMSGJxYWI-xsWFsS9bkzdbRIV8/edit?ts=5ec3ef17#slide=id.g780d0a5251_1_0

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
reviewed on 7/15 - decided to close - redesign will resolve.
