### ISSUE TITLE
Newly added page should contain title and body text

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1923]
## Feature Description

Newly added page should contain title and body text

[Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=8317%3A361490)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. If you start from a blank canvas, the empty page should contain a header and body text element.
2. You should also get the same header and body text element if you add a new page.

**Comment by bmattb** [comment]
NB - as per @pbakaus please ensure that it uses the primary font in the template in the new page

**Comment by o-fernandez** [comment]
Closing as duplicative of #3402, which has a better solution.
