### ISSUE TITLE
Set Placement of Text Box on Page

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1924]
## Feature Description

Newly added text should always be left aligned to the page.
[Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Stories-Stable?node-id=884%3A2984)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. After clicking on + icon to add new text element. Add element paragraph element 40px from the left edge and center vertically.
2. User can add the following text preset to the page (H1, H2, H3, paragraph, caption, overline)
3. When adding text presets consecutively(ie I click on heading then subheading then body text or heading then body text or body text and heading etc), try to add body text below subheading and subheading below the heading. 

## Testing Instructions

I
1. Add different text presets consecutively.
2. Verify that if presets are added right after each other, the next preset is positioned below the previous.
3. Verify that the preset doesn't go out of the bottom of the page, staggering starts from the default position (vertically centered) if the room ends up in the bottom of the page.
4. Verify that if any change is made between adding the presets, the preset is added to the default position (the consecutiveness counts only if the presets are added right after each other).

**Comment by jauyong** [comment]
Hey @miina is this all covered in #1204? Should I close this one as a dupe?

**Comment by miina** [comment]
@jauyong Nope, this issue is still relevant, thanks for checking!

**Comment by jauyong** [comment]
@samitron7 to review AC and feature description

**Comment by samitron7** [comment]
[Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Sam---Visual-Design-Frames?node-id=884%3A2984)

Let me know if there are any additional questions.

**Comment by miina** [comment]
@samitron7 One additional clarification:
Does "adding text presets consecutively" mean adding the text presets right after each other without making any changes meanwhile? E.g. if the user adds "Heading 1", changes the text of it and then clicks "Heading 2" -- is that not considered consecutive anymore since the user changed the text meanwhile?

Note: The easiest is -- if there have been any changes since adding the previous preset, it's not considered consecutive.

**Comment by csossi** [comment]
Verified in QA

**Comment by samitron7** [comment]
To @miina's comment (6 days ago) - we chatted offline and yes, any changes since adding the previous preset, it's not considered consecutive.
