### ISSUE TITLE
When adding large videos, frame appears empty and layer icon is broken until poster is generated

### ISSUE THREAD

**Issue by diegovar** [GoogleForCreators/web-stories-wp#1926]
## Bug Description

When adding a large video in the Editor that was just uploaded, you can add it pretty much immediately to the story. The frame appears for a bit before the video poster is rendered in the canvas. Also, the layers section on the right shows a broken image until the poster is generated.

## Expected Behaviour

Placeholder should be shown until the video poster is visible.
Placeholder image should be shown in the layers section

## Additional Context

From bug bash.

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
This is very closely related to https://github.com/google/web-stories-wp/issues/2615
