### ISSUE TITLE
Dragging media from library: The clone displays more than media

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#1930]
## Bug Description

When dragging media from media library, the clone being dragged displays some parts of the library as well instead of just the image being dragged. This makes it quite disturbing sometimes when trying to drop to a target precisely.

## Expected Behaviour
Only the image clone should be visible when dragging.

## Steps to Reproduce

1. Drag image from media so that the dragged image is on the first row, just below the filters.

2. See the filters included to the clone.

## Screenshots
<img width="290" alt="Screenshot 2020-05-21 at 14 25 20" src="https://user-images.githubusercontent.com/3294597/82559123-56e8e480-9b6f-11ea-9df4-907347711bcf.png">

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
this is related to #1979

**Comment by bmattb** [comment]
This will be solved once the related issue is addressed as mentioned in #5230

**Comment by miina** [comment]
Assigning 1 SP to this since it should get fixed by #5335 but we should still track it and test it.

**Comment by csossi** [comment]
Verified in QA

**Comment by tmagalhaes-huge** [comment]
Closing this, works well now. @samitron7 @aaecheverria @ivayloklissarov
