### ISSUE TITLE
Popup: proper height/width handling with reasonable defaults

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#1931]
## Feature Description
It would be good to limit popup to some width/height by default and allow overriding these values per use case.

If the popup content exceeds the limits, scrolling will help.

Additionally, the popup should adjust to width/height changes of the content. For example, if the popup is displayed in the bottom edge of the viewport and the content was previously 100px, and then changes to 300px, part of the popup will get hidden "below" the bottom edge of the viewport.[ Video with example](https://github.com/google/web-stories-wp/pull/1743#discussion_r427682509).

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## QA Instructions

See the testing instructions in https://github.com/google/web-stories-wp/pull/2306

**Comment by miina** [comment]
@wassgha Created this issue for Popup enhancements.

Note that this issue currently addresses generally width/height handling for the Popup, however, it might be better to split it up to:
1. Reacting to width/height changes to adjust the popup position
2. Adding max-width and max-height options with defaults.

It might make sense to combine these though in the implementation. Thoughts?

cc @jauyong

**Comment by csossi** [comment]
Verified in QA
