### ISSUE TITLE
Remove "Full Bleed" option

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#1932]
## Feature Description

Per comment in #1840, after UX revisions and review the full bleed option is considered to have more cons and pros. The user can always achieve a similar result by expanding the element manually, the "full bleed" option/shortcut value add is limited. 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/a0b773de-3bc2-4b1c-822b-61d41ef5e9fa)
