### ISSUE TITLE
Media Zooming: Consider the Reset button to use original value, not 100

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#1946]
## Feature Description

Currently, in Media edit mode, the Reset button is resetting the zoom to 100% instead of the previous value for that media.

It might be much more useful to reset the value to the previously existing value to truly reset the zoom to what it was before. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
@samitron7 Sam can you please confirm that the reset button should reset to the previous value, not 100% , and can you consider how #1507 should impact this decision.

**Comment by samitron7** [comment]
The reset button has been a point of confusion for people. Let's remove it and just allow scale and move when you're in image edit mode. The user can always undo to reset image back to the original state.

**Comment by barklund** [comment]
Closed in favor of #1945
