### ISSUE TITLE
Edit Mode of Text Box is Pushing letters to new line

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1951]
## Bug Description

Edit mode and display mode should display the same way -- if the letters are on a new line in display mode, it should also happen for edit mode. If the word is not breaking in display mode, it shouldn't break for edit mode either.

## Steps to Reproduce

1. Size a textbox with text so that the last letter is right up to the edge of the selection box
2. exit edit mode
3. enter edit mode
4. see letters pushed to new line when entering edit mode and text is highlighted

## Screenshots

https://docs.google.com/presentation/d/1ZiZWrmLiX40rt3n_1LMSGJxYWI-xsWFsS9bkzdbRIV8/edit?ts=5ec3ef17#slide=id.g7830109f71_0_48

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

Update the resizing based on [Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=8011%3A14593) -- add wrapping to overflowing text.

**Comment by csossi** [comment]
Verified in QA
