### ISSUE TITLE
Copy Paste Text into Text Box is Creating new Text Box

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1953]
## Bug Description

 If you copy from and paste to the same text element, a new text element is created with the copied text.

Similarly If you copy text from text box 1 and paste it into text box 2, a new text element is created with the copied text.

Related: #1605

## Expected Behaviour

text should be pasted, not text box

## Steps to Reproduce

1. have text in your clipboard
2. paste into a text box while in edit mode

1. have two text boxes
2. copy a word from one text box
3. enter edit mode of the other text box and paste that word
4. see new text box created

## Screenshots

https://docs.google.com/presentation/d/1ZiZWrmLiX40rt3n_1LMSGJxYWI-xsWFsS9bkzdbRIV8/edit?ts=5ec3ef17#slide=id.g7830109f71_0_67

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA

**Comment by miina** [comment]
Hmm, I thought that moving to UAT would reopen the issue automatically, wasn't it so before? Or perhaps it only does this is moving the issue directly to UAT whereas in this case, it happened via the PR.
Will know for the next time, sorry!
