### ISSUE TITLE
Show previously used fonts in the font picker

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#1955]
## Feature Description

At the top of the font picker, the 5 most recently used fonts will be displayed.

The currently selected font should have a checkmark in both the recently used fonts and below in the main list of fonts.

[Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=7992%3A586)

## Additional Context

To be added after #1300 is merged, as it introduces a new structure for font picker.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

- When the user loads the story (new or old), the recently used fonts section is empty
- When the user uses a font, the font is added to the top of the recent fonts
- There should be up to 5 recent fonts displayed and no duplicates

## Implementation Brief
- Update the list of the 5 most recently used fonts every time a font is chosen in the font picker
- There should be no duplicates but the most recent font should always appear on top

## QA Instructions
I
1. Open a Story (existing or new)
2. Add a Text element and open the Font picker
3. Verify that there are no recently used fonts in the beginning of the fonts list
4. Now change the font family of the Text 5 times, every time a different font
5. Verify that each time after choosing the font, the font is added to the top of the fonts list, until there are all the 5 fonts.
6. Now use a new font family again
7. Verify that there are still only 5 fonts in the recently used fonts and the latest is on the top of the list

II
1. Open a Story (existing or new)
2. Add a Text element and open the Font picker
3. Switch the fonts between 2 different fonts a few times
4. Verify that both of these fonts are added to the recently used fonts but are never duplicated.

**Comment by miina** [comment]
@samitron7 One additional UX detail to confirm -- should the recently used fonts always be visible? Or should they just be on top of the list and be scrolled together with the rest of the list? If it should always be visible then in case of 5 recently used fonts, it would take quite a lot of room away from the general list, however, if these are not forced to be visible and just the first items of the list, the user would have to scroll to the top every time to look for those. Thoughts?

**Comment by samitron7** [comment]
You can make the recently font scroll with the list. My take is if they user starts to scroll, they are looking for something beyond the recently used set and if they happen to really want to use a font from the list after scroll, it's really easy to type in the first 2 letters.
