### ISSUE TITLE
Capabilities 

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#196]
WordPress has a series of capabilities that are linked to a users role. Depending on the Users role, they will be not able to do some stuff in a WP context. 

Some key capabilities that related here are the following 
- The ability for a user to upload files.
- The ability for a user  to add tags / categories 
- The ability for a user to publish the story. 
- The ability for a user to add a feature image. 

There are some basic try at implementing this found [here](https://github.com/google/web-stories-wp/blob/0ce0e8854a478773bf15a91d31e0f6f169b2c2a7/assets/src/edit-story/app/story/effects/useLoadStory.js#L96-L99).

We need to expand these capabilities, how they are stored and where they are loaded from.

See original discussion on storing capabilities and moving these out of history [here](https://github.com/ampproject/amp-wp/pull/4122#discussion_r367949420)

Acceptance Criteria
1. Pass an object of capabilities in the config

**Comment by spacedmonkey** [comment]
Thinking over this matter, I believe that might be easiest to create a new REST API to list all capabilties needed for this editor and load them into state or startup of the editor. Thoughts?

**Comment by dvoytenko** [comment]
Yeah. Seems like we will also want capabilities state in the editor and ability to update it from the rest API and refresh the editor state based on that.

**Comment by dvoytenko** [comment]
@spacedmonkey to confirm, post initial load the capabilities are mostly static, right? I.e. they wouldn't normally change no matter what the editor does, it's only the site admin/installation type of stuff?

**Comment by spacedmonkey** [comment]
We should reuse the [canUser](https://github.com/WordPress/gutenberg/blob/4857ad58c1241b3d63d21a6880c989b85746c3dc/packages/core-data/src/resolvers.js#L134-L189) function could in gutenberg.

**Comment by spacedmonkey** [comment]
> @spacedmonkey to confirm, post initial load the capabilities are mostly static, right? I.e. they wouldn't normally change no matter what the editor does, it's only the site admin/installation type of stuff?

No, honestly it depends. In WP core you have a function called [current_user_can](https://developer.wordpress.org/reference/functions/current_user_can/). This allows for a context value to be passed. Meaning it would call something like this `current_user_can( 'edit_post', $post->ID );`. The capability checker than use the post id as context and check can fail depending on this context. But I am not sure if we would need this fine level for what we are trying to do here. Thoughts @swissspidy ?

**Comment by dvoytenko** [comment]
API-wise, we should definitely expose things inline with `current_user_can( 'edit_post', $post->ID );`. But in the context of the editor, there's only a single `post->ID` involved. So it could still be presented as something like:

```
const [canEdit, setCanEdit] = useState(false);
...
<CapabiltiesContext.Provider value={{canEdit}}>
  ...
</CapabiltiesContext.Provider>
```

And later:
```
const {canEdit} = useCapabilities();
```

Are there other capabilities with an open-ended cardinality?

**Comment by spacedmonkey** [comment]
Useful abilities. 
- upload_files
- publish_posts
- edit_others_posts
- edit_published_posts
- assign_categories / edit_categories / delete_categories
- edit_post_tags / delete_post_tags / assign_post_tags

See this [documentation](https://wordpress.org/support/article/roles-and-capabilities). Thinking about passing as config, as it is faster. See https://github.com/google/web-stories-wp/issues/499

**Comment by jauyong** [comment]
@pbakaus to review this and #630 to determine which will go into 1.0 Beta / Sprint 27.
