### ISSUE TITLE
Display Rules for Links

### ISSUE THREAD

**Issue by winterDroid** [GoogleForCreators/web-stories-wp#1968]
Link tooltip should be visible only on hover.

## Expected Behaviour

Link tooltip appears on hover (not when the element is selected).

## Additional Context

From [UX Evaluation](https://docs.google.com/presentation/d/1ZiZWrmLiX40rt3n_1LMSGJxYWI-xsWFsS9bkzdbRIV8/edit?ts=5ec35b92#slide=id.g777bcec6de_0_140)

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. The 2-tap UI (old popup design for now) appears on hover (not when the element is selected [Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=9466%3A5) )

**Comment by jauyong** [comment]
@samitron7 to add details regarding what happens if the element is rotated.
Also need to consider shapes. e.g. a round shape vs corners

**Comment by barklund** [comment]
Issue with blobs with weird sizes and at weird rotations:

![Screen Shot 2020-06-03 at 5 19 01 PM](https://user-images.githubusercontent.com/637548/83690273-6f6cec00-a5be-11ea-97c4-3f33ff3bfa40.png)

**Comment by samitron7** [comment]
Just chatted with Omar and we decided to not show the link icon. I made changes to the UI to reflect removal of the link icon. [Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=9466%3A5)

@jauyong Can we ensure that we change the title and AC to the ticket or close this one and open a new one for the following:
1. When a link is applied to the element, we show the 2-tap UI as confirmation. The confirmation should fade away. [Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=9407%3A16711)
2. The 2-tap ui appears on hover (not when the element is selected [Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=9466%3A5)
3. Lastly, the fields for the metadata (ie description and brand icon) should only appear if the user enters a valid url. Currently, if you enter in garbage in the web address, the metadata fields are available.

Removing UX needed label

**Comment by barklund** [comment]
@merapi, please update the issue description to reflect @samitron7's [comment](https://github.com/google/web-stories-wp/issues/1968#issuecomment-641041843) on what is actually to be implemented here (as both description and title is currently completely misleading).

**Comment by o-fernandez** [comment]
For clarification, since @merapi and @samitron7 discussed offline, it is ok to use the standard from the format for this Beta release and delay additional UI changes to post Beta.

**Comment by samitron7** [comment]
Dropping in a screenshot of the conversation:
<img width="921" alt="Screen Shot 2020-06-12 at 2 07 31 PM" src="https://user-images.githubusercontent.com/10889431/84546366-1421b480-acb6-11ea-95c0-3f52cadbd5ad.png">

@merapi We're good to go but @barklund and @jauyong this would mean we will need to file another ticket. I left another comment above and copying here again so it doesn't get lost:

@jauyong Can we ensure that we change the title and AC to the ticket or close this one and open a new one for the following:

When a link is applied to the element, we show the 2-tap UI as confirmation. The confirmation should fade away. Figma
The 2-tap ui appears on hover (not when the element is selected Figma
Lastly, the fields for the metadata (ie description and brand icon) should only appear if the user enters a valid url. Currently, if you enter in garbage in the web address, the metadata fields are available.

**Comment by jauyong** [comment]
Hey sorry for the delay in getting to this, I see it's already in review but I'll add the AC for Review / QA purposes

**Comment by swissspidy** [comment]
> Lastly, the fields for the metadata (ie description and brand icon) should only appear if the user enters a valid url. Currently, if you enter in garbage in the web address, the metadata fields are available.

I don't think this groups well with the other two ACs, nor dos #2460 cover this. Instead, I'll cover this as part of #2254.

**Comment by csossi** [comment]
Verified in QA - PR#2460

**Comment by samitron7** [comment]
Verified in UAT
