### ISSUE TITLE
Link tooltip visible when selecting media

### ISSUE THREAD

**Issue by winterDroid** [GoogleForCreators/web-stories-wp#1969]
## Bug Description

When selecting an org icon for a link, the tooltip of the link is still visible in the media gallery.

**Comment by swissspidy** [comment]
Could you add some context like a screenshot?

**Comment by winterDroid** [comment]
<img width="1679" alt="Screen Shot 2020-05-26 at 9 46 37 am" src="https://user-images.githubusercontent.com/1552225/82848188-d4c53b00-9f35-11ea-9107-43bb80cd101f.png">

There you can see that the link tooltip is still visible.

**Comment by swissspidy** [comment]
Possible duplicate of #1082.
