### ISSUE TITLE
Discovery: can a poster image be hidden in the media library?

### ISSUE THREAD

**Issue by dvoytenko** [GoogleForCreators/web-stories-wp#197]
Currently, after our editor uploads a video poster, the poster appears in the media library along with the video. After uploading several videos this becomes quickly a bit overwhelming. So the question to start with: is there a way to mark the poster we upload as a "hidden" resource?

**Comment by swissspidy** [comment]
Actually it should already be hidden. If not, that‘s a bug.

**Comment by swissspidy** [comment]
So the good thing is that the poster is hidden in the  WordPress media library

However, it is not hidden in the media tab. So that should be addressed.

Also, in my quick test it seemed to generate and upload a handful of poster images, not just 1. So perhaps there is some race condition as well.

**Comment by spacedmonkey** [comment]
I am not seeing the thumbnails showing up on the media library... I am seeing the preview on the video I just uploaded. See this example. 

<img width="364" alt="Screenshot 2020-02-15 at 11 16 51" src="https://user-images.githubusercontent.com/237508/74586925-b2418e80-4fe4-11ea-8d96-cd1a1fef6499.png">

I am seeing, the poster being generated multiple times for some reason. I will take into a look why that is happening.

**Comment by swissspidy** [comment]
> I am seeing, the poster being generated multiple times for some reason. I will take into a look why that is happening.

-> #331

**Comment by dvoytenko** [comment]
Another related issue: #360.

**Comment by swissspidy** [comment]
This one here shouldn‘t happen anymore. At least I can‘t reproduce it. Feel free to reopen otherwise.
