### ISSUE TITLE
Consider avoiding re-fetch of media after upload

### ISSUE THREAD

**Issue by cvolzke4** [GoogleForCreators/web-stories-wp#1971]
Consider avoiding the media fetch after upload, and instead retrieve the updated resource info from the response of the upload api call.

https://github.com/google/web-stories-wp/blob/master/assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js#L124

This solves two problems:

1. As a part of the larger epic to avoid re-renders, prevent the 'uploadMedia' function reference from being re-created when pagingNum changes.
2. fetch after upload uses the current 'pagingNum', which doesn't update the latest media if the gallery is scrolled down the page.

See also: issue https://github.com/google/web-stories-wp/issues/1971 and PR https://github.com/google/web-stories-wp/pull/1848.

A corner case to consider:
1. User search for cats
2. User filter media library by video.
3. User uploads an image called dog.jpg.

Should the uploaded image be added to the top of the list (and the user scrolled to the top), or should the item disappear? Or should the search be cleared?

**Comment by cvolzke4** [comment]
Answers from Sam

> After uploading an image, should the media gallery scroll to the top?

No, we'll use a snackbar like notification at the bottom of the media library to indicate that media has been uploaded to the top. There is also a persistent go to top bottom that scrolls you back to the top (https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=7507%3A303081)

> If the user has typed a search term, then uploads an image that does not meet that search term, is it reasonable to reset the filter? Or must we re-apply the entire search and refresh the list?

If you're in search mode, the upload button is no longer available (https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=7497%3A301236)

> When uploading a video, should the Video tab be activated, so that the user can see that it's uploading?

1) If type filter is set to All, there is no need to do anything 2) If it's set to something Image, then we'll use the same snackbar message (same one we used in bullet #1). I'll add figma flow for this.

**Comment by dvoytenko** [comment]
> If you're in search mode, the upload button is no longer available

By itself this is not definitive, since the user can always use DND to upload. But I think the use of snackbar clarifies this sufficiently.

**Comment by cvolzke4** [comment]
> > If you're in search mode, the upload button is no longer available
> 
> By itself this is not definitive, since the user can always use DND to upload. But I think the use of snackbar clarifies this sufficiently.

DND is an important case, Sam responded:

"I think for now it would be acceptable [for the item to remain even if it falls outside of the search criteria] if when you do a search then drag to upload. It seems like such an edge case to me so we don’t need to over build"

The key issue is that re-fetching the search results would scroll the user back to the top, which would the user would probably not expect.

Here's a screenshot of the chat in context.
https://share.getcloudapp.com/jkulzWqq

@spacedmonkey Is there anything else to clarify with UX? If so I'll set up a meet with Sam, me and yourself to discuss.

**Comment by dvoytenko** [comment]
This sounds like a good compromise to me.

**Comment by cvolzke4** [comment]
QA notes:
- Mostly no visible changes to the user.
- Fixes the issue of the media being loaded at page 10 (causing weird ordering) when scrolled down to page 10.
- Uploaded media continue to appear at the top of the list.
- Closing the WordPress media picker will still refetch/refresh the list.
- Corner case: When uploaded media doesn't match an active search, it will still be displayed at the top until the search is re-applied, this is WAI.

**Comment by csossi** [comment]
Verified in QA
