### ISSUE TITLE
Resize Text: Text is cropped when resizing width 

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1974]
## Bug Description

Never crop text when a user decreases the width of the text box.

Issue 1: Flickering of text

Issue 2: Incorrect scaling behavior. If you drag to resize text, it should scale like an image (ie, the word “text” in “Fill in some text” should not be placed on a new like.

Set a min width(#917)  when dragging to decrease text box width. Allow the text to overflow outside of the selection box.

When I kern text, the text should be able to overflow outside of the text box but can be cropped by the page boundary.

[Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=8011%3A14593)

## Steps to Reproduce

1. Add a new line to text
2. then resize text box. 

## Screenshots

https://docs.google.com/presentation/d/1ZiZWrmLiX40rt3n_1LMSGJxYWI-xsWFsS9bkzdbRIV8/edit?ts=5ec3ef17#slide=id.g7830109f71_0_14

https://docs.google.com/presentation/d/1ZiZWrmLiX40rt3n_1LMSGJxYWI-xsWFsS9bkzdbRIV8/edit?ts=5ec3ef17#slide=id.g7830109f71_0_84

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment]
UX confirmation needed on min width of 10px as we have 917 already for the min per Morten.

**Comment by jauyong** [comment]
UX needed removed regarding min width as #917 handles that.

**Comment by merapi** [comment]
> UX needed removed regarding min width as #917 handles that.

#917 leaves text element min size up to min font size, so might be worth double checking it.

**Comment by carloskelly13** [comment]
@jauyong @o-fernandez This was opened a while ago and the videos inside the Google Slides doc don't seem to play. Can we retest this on a recent build of the app and see if this is still an issue? (I'm not saying it's not, but a little more context would be great) Thanks!

**Comment by maxyinger** [comment]
I'm currently unable to reproduce any of the issues described in this ticket. Going to send to QA. 

Let me know if there's any context I'm missing or if this ticket is actually for tests that should be added.

**Comment by swissspidy** [comment]
Uploaded the videos from the slides here: https://cloudup.com/ilJ7yLdbqIX

Quite likely that this was fixed in the meantime given the age of this ticket.

**Comment by csossi** [comment]
Verified in QA
