### ISSUE TITLE
Add Keyboard Shortcut on Element for Bold, Underline and Italics

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1977]
## Feature Description

I’m able to CMD B/U/I on the entire element 

[Full Keyboard Shortcut list](https://docs.google.com/spreadsheets/d/17pZLd0faYZc9Xt7mG1KYtaZ0Krn5ppThIisz3TOsv8w/edit#gid=0)

## Acceptance Criteria

1. After selecting a text box element, I am able to CMD + B to bold
2. After selecting a text box element, I am able to CMD + U to underline
3. After selecting a text box element, I am able to CMD + I to italicize

**Comment by csossi** [comment]
Verified in QA (fyi, both WIN and Mac)

![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/704f9734-c370-42ac-bd08-9af3f54fc7af)
