### ISSUE TITLE
Update deprecated Popper.js to v2

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#1978]
## Feature Description

The package we're currently using is deprecated: https://www.npmjs.com/package/popper.js

New version 2 is available at https://www.npmjs.com/package/@popperjs/core.

Migration guide: https://popper.js.org/docs/v2/migration-guide/

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
@swissspidy is this important for a given release (Beta, stable?)

**Comment by swissspidy** [comment]
Nope, not really.
