### ISSUE TITLE
Snap guides not appearing when dragging an element from library

### ISSUE THREAD

**Issue by csossi** [GoogleForCreators/web-stories-wp#1979]
## Bug Description

The blue guide lines aren't appearing on canvas if user chooses to click-and-drag elements from the library panels over to the canvas

## Expected Behaviour

Expected blue lines to appear as user moves teh clicked-and-dragged item over the anvas

## Steps to Reproduce

- open/create story
- click-and-hold media item
- drag over to canvas
- move it around - you'll see that blue lines do not appear

## Additional Context

- Plugin Version:
- Operating System: Win10
- Browser: Opera

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment]
@csossi which blue lines are you referring to? 

This is my dragging an image and it shows the centre lines in blue:
![image](https://user-images.githubusercontent.com/5874851/82908006-5d8fa700-9f35-11ea-9c47-76ef49ad2ffb.png)

**Comment by miina** [comment]
Assigning 1 SP to this since it should get fixed by #5335 but we should still track and test it.

**Comment by miina** [comment]
@bmattb FYI I changed this to 3 points since this came out to be a more complex issue and will be implemented separately for all the elements of the library at the same time instead of only Media first.

Also, this issue is blocked by #5337

**Comment by csossi** [comment]
Verified in QA
