### ISSUE TITLE
Justify right behavior is off

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1980]
## Bug Description

The “e” in the “one” is the only letter flushed to the right. This seems off. 

## Expected Behaviour

all letters and lines should be equally justified to the right

## Screenshots

![image.png](https://images.zenhubusercontent.com/5e985a7aea3104e101699670/bf202d03-3243-4653-92f0-7129ac416d1f)

![image.png](https://images.zenhubusercontent.com/5e985a7aea3104e101699670/efe94c7c-8892-4b16-a672-9fe88709e67b)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by merapi** [comment]
Because we (and DraftJS) use `white-space: pre-wrap` this is normal (also seen in other WYSIWYG editors), [here](https://codepen.io/merapi/pen/jOWvwjN) is an example with other white-space options. 

Since we probably want to leave `pre-wrap` (and use DraftJS) this needs to be solved at a different level (e.g. special case when text is right-aligned - try to shift the text+add space at the end so the last line is aligned - but then display text will be different than edit mode text) or left as is.
Alternatively, we can change the pre-wrap but then DraftJS will behave differently than it is now (no whitespace at the end of a wrapped line).

**Comment by dvoytenko** [comment]
Can we switch to `white-space: pre-line` and solve for double spaces some other way?

**Comment by merapi** [comment]
Testing it on `try/white-space-pre-line`, not yet sure that it is safe to do that (pre-wrap might be important for DraftJS as seen [here](https://github.com/facebook/draft-js/pull/159) / [here](https://github.com/facebook/draft-js/blob/1dc786385c04c2078444be02531ff78b113ecbfb/CHANGELOG.md#added-19) and no option to switch white-space strategy).

**Comment by dvoytenko** [comment]
I'm pretty sure `pre-wrap = pre-line - space-collapse`. So we'd need to do something about space-collapse. It'd mean that we'd have to scan the editor state each time it changes (I think we already do anyway) and replace a sequence of spaces with something that doesn't get collapsed. I think there are only two options for that:

1. Maybe possible to find a unicode character that's defined as non-collapsible. I did a quick search and, unfortunately, didn't see anything. But maybe something exists.
2. A bit more complicated, but we'd wrap each sequence of spaces of length > 1 inside a `<span style="white-space: pre-wrap"></span>`.

Certainly ugly, but at least the second option should work, I believe.

**Comment by bmattb** [comment]
@o-fernandez - @carlos-kelly has flagged that this issue should be removed from S39 and 1.1 as it appears to be a browser issue - https://bugs.chromium.org/p/chromium/issues/detail?id=1006599.

Please confirm that you are okay with this.

**Comment by o-fernandez** [comment]
That makes sense @bmattb @carlos-kelly, let's lower priority and remove from sprint and we can keep track of the browser/chromium bug

**Comment by merapi** [comment]
I just got a notification that this bug is now [fixed](https://bugs.chromium.org/p/chromium/issues/detail?id=1006599#c8) 🎉

**Comment by swissspidy** [comment]
> I just got a notification that this bug is now fixed 🎉

Was just about to report the same 😃 

Given Chrome's [release schedule](https://www.chromestatus.com/features/schedule) I suppose it takes another few months until it actually lands.
