### ISSUE TITLE
Text justify weirdness when resizing

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1981]
## Bug Description

Center, right and flush justify weirdness when resizing width of text box

## Screenshots

https://docs.google.com/presentation/d/1ZiZWrmLiX40rt3n_1LMSGJxYWI-xsWFsS9bkzdbRIV8/edit?ts=5ec3ef17#slide=id.g77fdc779d5_0_167

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
![justify fix](https://user-images.githubusercontent.com/10720454/113628181-5e936980-9619-11eb-8417-6c66e0923347.gif)


this got fixed
