### ISSUE TITLE
Allow user to input text to newly added text element

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1982]
## Feature Description

Newly added text element should be in a highlighted state so that the user can immediately start to type. [Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=8011%3A14748)

Related: #830 #1608

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. After a text element is newly added, it should be in focus so that the creator can start typing

**Comment by swissspidy** [comment]
Duplicate of #1608?

**Comment by jauyong** [comment]
@barklund does #1608 cover this? Should we close this?

**Comment by miina** [comment]
This issue should be resolved, it was done in #1608 as works as expected, closing as such.

cc @barklund @bmattb
