### ISSUE TITLE
Unable To Click-and-Drag Shapes to Canvas

### ISSUE THREAD

**Issue by csossi** [GoogleForCreators/web-stories-wp#1983]
## Bug Description

Users are able to click-and-drag media items from media panel to canvas. Assuming they should be able to do

## Expected Behaviour

Expected to be able to click-and-drag shapes

## Steps to Reproduce

- open/create story
- select Shapes tab
- click-and-hold on desired shape
- drag over to canvas

Unable to. The only way a user can put a shape on canvas is to click

## Additional Context

- Plugin Version:
- Operating System: Win10
- Browser: Opera

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Duplicate of #1579.

This is currently being worked on.

**Comment by jauyong** [comment]
closing in favour of #1579
