### ISSUE TITLE
Define default merge strategy

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#1995]
## Task Description

Let's settle on a consistent strategy for updating PRs - i.e. whether we do generally recommend using `git rebase master && git push --force` or `git merge master && git push`

Bonus: we can also decide whether PRs should be merged with squashed commits ir not, if its relevant for resolving this matter.

**Comment by swissspidy** [comment]
Summarizing the discussion so far:

| Merging | Rebasing |
| ------------- | ------------- |
| - easier, does not lead to conflicts<br>- can be done via GitHub's UI ("Update branch")<br>- Distract from PR changes | - leads to conflicts for anyone who has already checked out the branch locally<br> - conflicts can be fixed via `git fetch origin; git reset --hard origin/<branch_name>`<br>- rewrites history  |


----

Personally, I usually do force pushes as long as the PR is still a draft and WIP (i.e. I am the only one working on it). Once there are other contributors or reviews, I only do merges.

In theory, it shouldn't really matter, as inn the end the PR is probably squash-merged into master anyway.

**Comment by ezxyz** [comment]
I think if we squash merge any issue with commits being confusing will be fixed. I don't think it should matter what we do in our PR, and I think it'll hurt our productivity trying to force a workflow for everyone at a level of commits.

I prefer merging from master, but other people prefer rebasing. When we squash and merge this doesn't change the commit history of the master branch so I think we should let people choose what works for them.
