### ISSUE TITLE
Dashboard: Add integration tests for app structure and navigation

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#1998]
## Task Description

Adding integration tests to spot check each completed view will ensure that future PRs do not break basic functionality of the dashboard. Sometimes a theme or config change can break the app (understandably) and we want to flag those.

**Comment by dvoytenko** [comment]
We are currently trying out Karma in the workspace pod. Please follow it along and we can see if we can setup Karma for the Dashboard as well if that'd be desirable.

**Comment by carloskelly13** [comment]
Yes, I am doing a little spike on it and I think it would be a good idea. The pages do load fine, but I'm sure there will be some setup around how do we standardize the data that is available when puppeteer launches the browser.

**Comment by dmmulroy** [comment]
Initial integration of Karma boilerplate/setup for dashboard is finished in this pr: https://github.com/google/web-stories-wp/pull/2647

Remaining work:
- Properly stub stories data in the APIProviderFixture
- Write navigational/structural tests for the main views in dashboard

**Comment by dmmulroy** [comment]
Comprehensive test suite for My Stories View is in PR review here: https://github.com/google/web-stories-wp/pull/2882

**Comment by o-fernandez** [comment]
@dmmulroy @carlos-kelly anything still pending before moving this to "Closed"?

**Comment by dmmulroy** [comment]
> @dmmulroy @carlos-kelly anything still pending before moving this to "Closed"?

With https://github.com/google/web-stories-wp/pull/3419 merged, this can be moved to 'Closed'
