### ISSUE TITLE
Ensure valid frontend output

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#2]
All necessary AMP extensions should be loaded on the frontend so that a valid AMP story can be viewed.

This is a follow-up to https://github.com/ampproject/amp-wp/issues/3862.

--------

## QA Instructions

1. Verify that publishing a new story and viewing it on the frontend produces valid AMP, with the exception of a missing poster warning
2. Verify that adding a poster image removes that last warning

Can be easily tested with the [AMP validator Chrome extension](https://chrome.google.com/webstore/detail/amp-validator/nmoffdblmcmgeicmolmhobpoocbbmknc?hl=en).

**Comment by kmyram** [comment]
@swissspidy As a matter of house-keeping, should this not count against Sprint 22? Also, there seems to be missing QA-instructions?

**Comment by swissspidy** [comment]
Done, sorry for the delay!
