### ISSUE TITLE
Create a proper method for handling composed characters on Text Element 

### ISSUE THREAD

**Issue by obetomuniz** [GoogleForCreators/web-stories-wp#2002]
## Bug Description

- Leave Edit Mode of the text element is not updating the Display Mode content after use composed characters.
- Block length between edit/display is not synced when using composed characters.
    - While using normal characters = `block.getLength()` and `endOffset` are always synced
    - While using composed characters = `block.getLength()` and `endOffset` are different. `endOffset` is synced with the number of characters on Edit Mode. `block.getLength()` stays synced with the number of characters on Display Mode.

## Expected Behaviour

Users should be able to input composed characters without any problems. After #2003, only if the user hits <kbd>enter</kbd> after insert composed characters it works.

## Steps to Reproduce

- Change your computer to Japanese (Hiragana) [MacOS process]
- On Web Stories Editor, add a new Text Element
- Enter on Edit Mode of the Text Element added previously and type `konnichi` in your QWERTY keyboard, which is expected to render こんにち on the text element editable area.
- Click outside to leave the Edit Mode of the Text Element

## Screenshots

![Untitled](https://user-images.githubusercontent.com/1680157/82936595-3650ce00-9f65-11ea-8f35-e618b8c933aa.gif)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment]
Discussing during grooming,
crashing is no longer happening. moving this out of beta.
