### ISSUE TITLE
Dashboard: Use a template from the explore templates view

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#2007]
## Feature Description

Use a template from the explore templates view. This should launch a copy of the template as a DRAFT story inside the editor.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA PR#2222

Template launched in Editor -example:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/8028f620-cd8a-4564-9ecc-a17acdaeb675)
