### ISSUE TITLE
Layer panel font sizes don't align

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#2014]
## Bug Description

The different types of layers in the layer panel have different font sizes:

![Screen Shot 2020-05-26 at 1 20 31 PM](https://user-images.githubusercontent.com/637548/82951022-6fdd0580-9f74-11ea-862f-15b4c1094ef6.png)

They should have a similar font size as can be seen in Figma:
![Screen Shot 2020-05-26 at 5 18 13 PM](https://user-images.githubusercontent.com/637548/82951324-eda11100-9f74-11ea-94ad-693dcd0ef56f.png)

## Expected Behaviour

Font sizes are expected to be similar according to [Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=2683%3A260).

## Steps to Reproduce

1. Add a text layer and observe a different font size from the background layer.

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/131fecbb-1a40-45fe-bc49-6903eac3112c)
