### ISSUE TITLE
Cannot copy "everything" from one page to another

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#2015]
## Bug Description

There is currently no way to select every element on a page to copy it to another page, as you cannot select both the background element along with any non-background element.

Maybe it is not necessary to be able to do this though, as you can duplicate a page, but if you want to copy a page from one story to another, there's no simple way to achieve it - even with two windows open. You have to do it in two steps.

## Expected Behaviour

Expected behavior is unknown.

## Steps to Reproduce

1. Lasso-select everything on a page with background media
1. Press shortcut to copy
1. Create a new empty page
1. Press shortcut to paste
1. Observe that everything except background was copied.

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Being able to <kbd><kbd>CMD</kbd>+<kbd>A</kbd></kbd> and then copy/paste would be nice too!

**Comment by o-fernandez** [comment]
CMD+A shortcut is something we want to implement, so once that's possible to do select all, plus the option to just duplicate the page which already exists, I think this use case would be pretty well covered. Keeping in icebox for now.
