### ISSUE TITLE
When pasting text in editmode styles are reset

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#2016]
## Bug Description

When editing a text field and having non-standard styling (e.g. bold and pink color), if you paste some text, then (besides the issue described in #1953) the entire text field also changes to default text color.

## Expected Behaviour

Pasted content should follow format of existing content.

## Steps to Reproduce

1. Copy any piece of (formatted) text
1. Edit a text field
1. Make everything pink
1. Paste while still in edit mode
1. Observe that the entire text field is now black

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment]
@barklund is this the same as #760?

**Comment by barklund** [comment]
Duplicate of #1605.
