### ISSUE TITLE
When changing page via carousel, a blue drop bar appears briefly

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#2017]
## Bug Description

When you click to change page via the carousel, a blue drop bar appears briefly next to the clicked page indicating a possible drop location, even though you only briefly click the page, and aren't dragging it at all.

## Expected Behaviour

I expect the blue drop bar to only appear, when the page is being dragged, not just clicked.

## Steps to Reproduce

1. Create multiple pages
1. Navigate to a different page in the carousel by clicking
1. Observe a blue drop bar briefly appearing with each click

## Screenshots

![carousel-drop-bar](https://user-images.githubusercontent.com/637548/82952826-b2541180-9f77-11ea-8d7f-6adc4427e27d.gif)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@barklund @bmattb FYI Pulling into sprint.

**Comment by miina** [comment]
@barklund Can you confirm if that's still an issue? Looks like it's not happening anymore unless really dragging, perhaps you fixed it when reworking the carousel?

**Comment by miina** [comment]
Closing as fixed in another isse/PR (perhaps #5692)
