### ISSUE TITLE
Focused element in DropdownList should change with hover events

### ISSUE THREAD

**Issue by joannag6** [GoogleForCreators/web-stories-wp#2033]
The [DropdownList](https://github.com/google/web-stories-wp/blob/master/assets/src/edit-story/components/form/dropDown/list.js) gets a bit buggy when using both keyboard and mouse to change focus. This ends up with two elements being focussed instead of just the latest one. 

![dropdown.gif](https://images.zenhubusercontent.com/598a66e7f8b79f8376e26cb0/ba96484f-e9ed-49fa-b886-c02131e2cb6d)

We should do something like this instead:
![gif.gif](https://images.zenhubusercontent.com/598a66e7f8b79f8376e26cb0/afc66af6-4a4c-45f2-866f-beae04a81e39)

Could be worth creating a Storybook story for this component as well.

**Comment by zidianlyu** [comment]
It looks like the UI has been updated.

<img width="267" alt="Screen Shot 2020-12-15 at 10 44 39 AM" src="https://user-images.githubusercontent.com/11252886/102258244-9471de00-3ec2-11eb-9cb7-0c656a8ea2d7.png">

@joannag6 do you still have the issue? Otherwise, we might update the status.

**Comment by swissspidy** [comment]
Yup, looks like this has been addressed with the refactoring of the dropdown component. Closing.
