### ISSUE TITLE
Can't access the background edit mode when covered by shape

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#2038]
## Bug Description
When using background media with shape covering the full background area, the background media edit mode is not accessible.

## Expected Behaviour
- Perhaps that's expected but would be good to clarify.

## Steps to Reproduce

1. Add background media
2. Add a shape, e.g. triangle
3. Resize the shape to cover the whole area
4. Try to enter edit mode of background media (e.g. by double-clicking to the area free from the visible part of the shape.
5. See the shape getting selected instead, even though the click is on the area which is not directly on the visible shape.

## Screenshots
![shape](https://user-images.githubusercontent.com/3294597/83033024-e17d8800-a036-11ea-85be-b61c4b1dd367.gif)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@o-fernandez Created this issue since I wanted to zoom/move the background after creating this shape on top, however, apparently, it was not possible. Perhaps it's the expected behavior but I'm not certain, would be great if you could confirm.

**Comment by samitron7** [comment]
@miina This shouldn't be an issue. If you placed another image on top of this, you wouldn't be expected to be able to select the bottom image. Nothing should be done for this use case and I think users will know that they occluded the bottom image.

Can we close this ticket.

**Comment by swissspidy** [comment]
In this case it's a triangle shape on top of the background though, not just an image. Didn't we somewhere define that, when clicking on the space not covered by the shape, we'd select the visible element underneath?

**Comment by samitron7** [comment]
OK - need to think about this a bit actually. If we allow you to select inside the selection box but outside the triangle, this has some cascading effects (lass select de-selection rule, user expectation to click drag anywhere inside the selection box to drag...)

**Comment by samitron7** [comment]
[Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=9569%3A0)

**Comment by miina** [comment]
@barklund @bmattb FYI Pulling this into the Sprint

**Comment by csossi** [comment]
Verified in QA
