### ISSUE TITLE
Subheading is added with font weight as "multiple"

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#2041]
## Bug Description

Adding text preset "Subheading" is added with font-weight showing "multiple".
This might come from subheading being assigned a non-existing font-weight.

See the related larger issue: #1899 

## Expected Behaviour
"Subheading"  preset should use an existing font-weight.

## Steps to Reproduce

1. Add text preset: Subheading
2. See the font-weight.

## Screenshots
![subheading](https://user-images.githubusercontent.com/3294597/83041291-9d8f8080-a040-11ea-9859-8eb4ba6b2a36.gif)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
For QA: Verify  that the "subheading" element shows "Medium" for the font weight instead of "Multiple"

**Comment by csossi** [comment]
Verified in QA - 
PR#2781
