### ISSUE TITLE
Color picker: Changing color type from radial/linear to solid changes the opacity

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#2043]
## Bug Description

When using radial/linear with non-default opacity, the opacity unexpectedly changes when switching to solid.

## Expected Behaviour

- Opacity should stay the same when switching between color types.

## Steps to Reproduce

1. Add a shape.
2. Assign some color to it, leave the opacity to 100%
3. Now change the color to linear and after that, assign opacity 50%
4. Now change the type back to "solid".
5. See the opacity 100% again

## Screenshots
![opacity](https://user-images.githubusercontent.com/3294597/83045877-805db080-a046-11ea-8780-bbf022b3125f.gif)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@barklund FYI that I created an issue for it even though I know this was implemented like this purposefully -- in practice, it still feels like a bug to me.

**Comment by samitron7** [comment]
Thanks @miina. UX verifying that that the expected behavior is for the opacity of solid to change to 50%.
