### ISSUE TITLE
Hide text magic and helper mode behind feature-flag

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#2044]
## Feature Description

Temporarily hide text magic and helper mode behind feature-flag

## Alternatives Considered

* None

## Additional Context

From [UX Evaluation](https://docs.google.com/presentation/d/1ZiZWrmLiX40rt3n_1LMSGJxYWI-xsWFsS9bkzdbRIV8/edit?ts=5ec35b92#slide=id.g780d0a5251_0_1)

## Screenshots

The two last icons:

<img width="401" alt="Screenshot 2020-05-27 at 17 04 04" src="https://user-images.githubusercontent.com/3294597/83046376-375a2c00-a047-11ea-9742-1cc95d368910.png">
---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/4d1be6d8-79cd-48a5-b0ff-1f3fad2df98c)

**Comment by samitron7** [comment]
Verified in UAT
