### ISSUE TITLE
Add a prependMedia/updateMediaElements context actions for useUploadMedia

### ISSUE THREAD

**Issue by cvolzke4** [GoogleForCreators/web-stories-wp#2072]
As it is now, useUploadMedia consumes the 'media' attribute (ie. the array of the media resources) in order to prepend uploaded media resources. This is inefficient, and adds an unnecessary dependency to the 'media' attribute inside of useUploadMedia.

As an alternative, a 'prependMedia' and/or updateMediaElements context actions can be added to add the uploaded media resources instead.

**Comment by swissspidy** [comment]
`prependMedia` was implemented in #6541. See also #2513
