### ISSUE TITLE
Browser back and forward button do not work in the dashboard.

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#2074]
## Bug Description
Found as part of the bug bash, when navigating through views in the dashboard, browser back and forward button do not work at all or as expected. Back and forward button as used by users frequently and are a key part of accessibility.  

## Expected Behaviour

When using back or forward buttons in the dashboard, I should be taken to the last page. 

## Screenshots
https://youtu.be/PVOS9M0dSpU

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by carloskelly13** [comment]
@spacedmonkey I was confused by this since all the navigation links for each page seem to work with back and forward, but I noticed you are expecting the in-page tabs to also get tracked by history. We could add those as query params and add them to the stack. I'm unsure if that is common practice to have in-page elements part of the history stack, but it's certainly doable if we want.

A good example is Twitter where on your profile "Tweets", "Media", and "Links" are tabs within a page but do not get added to the history stack.

**Comment by carloskelly13** [comment]
@o-fernandez For this one do we want the filter tabs to be part of the browser history?

So if I click "Drafts" then Browser Back would take me to "All Stories"?

![Screen Shot 2020-07-06 at 1.27.25 PM.png](https://images.zenhubusercontent.com/5ea09bca6a44046f869bafe0/0101ebfd-666f-4d33-bb48-08a74d766d9b)

**Comment by o-fernandez** [comment]
> @o-fernandez For this one do we want the filter tabs to be part of the browser history?
> 
> So if I click "Drafts" then Browser Back would take me to "All Stories"?
> 
> ![Screen Shot 2020-07-06 at 1.27.25 PM.png](https://camo.githubusercontent.com/03767ba823df255fec3d6fadacb42df35fb8a742/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3565613039626361366134343034366638363962616665302f30313031656266642d363636662d346433332d626234382d303861373464373636643962)

Tabs here in essence function as a page filter and not distinct pages, so I'd say that's not necessary. We can monitor more user feedback and implement a change here if we hear from user that it's important.

**Comment by BrittanyIRL** [comment]
@o-fernandez thought I'd circle back on this if users have had any feedback about browser back and forward, could we possibly close this ticket?

**Comment by o-fernandez** [comment]
@LuckynaSan have you seen any user tickets around this? Would be helpful for us to clean up bugs.

**Comment by LuckynaSan** [comment]
There have not been any reports on this. No issues here in this either [video](https://jmp.sh/VxZW3zl).
