### ISSUE TITLE
Preview / open button doesn't work. 

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#2077]
## Bug Description

When pressing the Preview / open button, nothing happens and weird focus ring around the button is displayed. 

## Expected Behaviour

Button should work. 

## Steps to Reproduce

See video. 

## Screenshots

https://youtu.be/a-dts63THKg

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by carloskelly13** [comment]
We are sorting out what the UX should be for Preview and Open with design and product. It could be a modal like Template detail, or does it show something similar like the Editor when previews.

**Comment by BrittanyIRL** [comment]
> weird focus ring around the button is displayed 

I noticed that too! Common js was overriding our styles, a fix for that is coming through the review/qa pipeline.

**Comment by o-fernandez** [comment]
We fixed the issues (by hiding some options, and other related fixes) so closing this issue.
