### ISSUE TITLE
Unable to trash story. 

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#2078]
## Bug Description

If you have unsaved changes in story, you have confirm losing changes before trashing a story. 

## Expected Behaviour

No confirmation is shown when pressing the trash button. 

## Steps to Reproduce

See video 

## Screenshots

https://youtu.be/2aLU4exA4NQ

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Duplicate of #800?

**Comment by o-fernandez** [comment]
We removed trashing from the doc panel.
