### ISSUE TITLE
Dashboard: Hide views not launching for Beta behind feature flag

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#2081]
## Feature Description

The Settings, Support, and Saved Template views should be hidden behind a feature flag.
---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/9b5b571d-a08a-43ca-919e-82017e3eef36)
