### ISSUE TITLE
Resizing the browser window causes the 'rotate' text box to cut off the number.

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#2083]
## Bug Description

From APAC bugbash: Resizing the browser window causes the 'rotate' text box to cut off the number, working with Shapes. 

I could repro just now. See images. 

**value displayed properly when browser width is normal/wide enough**
![When in normal screen](https://user-images.githubusercontent.com/13389997/83175101-62955780-a0e9-11ea-9648-8531f60c78f7.png)

**rotation value cut off when browser width is shrunk**
![When small width resized](https://user-images.githubusercontent.com/13389997/83175106-64f7b180-a0e9-11ea-96e6-0e57149ca491.png)

## Expected Behaviour

Rotation value should still be displayed even when adjusting browser width. 

## Steps to Reproduce

1. Add shape to page
2. Enter a rotation value with 3 digits (e.g., 150)
3. Resize the browser screen to reduce width. 

## Additional Context

- Plugin Version: Master branch on May 28, 2020
- Operating System: Mac OS X
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Also notice the scrollbars for the alignment options.

Seems like we need to enforce a larger minimum width for the whole design panel.

**Comment by o-fernandez** [comment]
Added to PM backlog to figure out prioritization as part of Responsive UI/Breakpoints.

**Comment by bmattb** [comment]
As per @samitron7  this should be addressed once the new designs have been applied. closing this issue.
