### ISSUE TITLE
Input fields are inconsistently styled when focused

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#2084]
## Bug Description

Some input fields turn alternate color scheme on focus, others do not. This must be synchronized, awaiting UX to clarify in which direction.

[figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=9396%3A400304)

## Expected Behaviour

UX to clarify

## Steps to Reproduce

1. Select a text field
1. Click inside layer opacity input field
1. Then click inside text color opacity input field and observe the difference

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by samitron7** [comment]
Figma [flow](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=9396%3A400304. Removing UX Needed label

All input field behavior should be the same on design and element panel.

**Comment by jauyong** [comment]
removed the needs more info label as we have the figma designs.

**Comment by samitron7** [comment]
Found 2 input fields that are still inconsistent

1. Search field (needs focus border when you click into the input field)
2. Hex value and color opacity (the border are much brighter than the rest which leads me to think we're not using the same color attribute here.

**Comment by barklund** [comment]
@samitron7, I've filed a follow-up issue in #3969 and will look at it asap.
