### ISSUE TITLE
Color swatch input field should select-all on focus

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#2085]
## Feature Description

When focusing the color swatch field for a non-gradient color, the hex can be edited, but only if you select-all to delete the existing content first.

The entire contents should be auto-selected on focus whether by keyboard (already happens) or by pointer device (doesn't happen).

## Alternatives Considered

- None

## Additional Context

- From [UX Evaluation](https://docs.google.com/presentation/d/1ZiZWrmLiX40rt3n_1LMSGJxYWI-xsWFsS9bkzdbRIV8/edit?ts=5ec35b92#slide=id.g77fdc779d5_0_201)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Closing as this got fixed with the redesign.
