### ISSUE TITLE
Make it easier to find layers reordering

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#2086]
## Feature Description

Re-ordering layers is difficult to discover, expected a right-click menu 'Bring to front' or similar.

## Alternatives Considered

None, needs UX consideration. Filing the issue for user feedback tracking for now. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Duplicate of #9139
