### ISSUE TITLE
Right-click on a shape causes a drag to start and continue while the mouse is not down.

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#2087]
## Bug Description

This is pretty weird, found during APAC bugbash: Right-click on a shape causes a drag to start and continue while the mouse is not down.

## Expected Behaviour

Expected the right click to do nothing other than bring up the generic browser right-click menu.

## Steps to Reproduce

Place a shape on the page
Right click on the shape and release the right click
Move mouse around. 

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
I actually cannot recreate this later. There is a similar issue when right-clicking the background around the canvas, where the lasso shows up and moves around while no mouse-button is pressed, but I cannot recreate the bigger bug mentioned in this issue anymore. I have also seen it previously, but not on master now.

@o-fernandez, can you confirm if still an issue?

**Comment by miina** [comment]
I'm able to reproduce this but I'm also able to reproduce this in the Moveable demo site -- will report this issue under Moveable repo directly: https://github.com/daybrush/moveable/issues/252

**Comment by o-fernandez** [comment]
Yeah, I can still repro. To see it I need to: 
* add Shape
* deselect shape
* right click on shape (that was deselected up until then, doesn't work on already selected shape)
* move mouse somewhere else on canva
* left click

After I release the left click elsewhere, the shape moves.

**Comment by jauyong** [comment]
Possibly an upstream issue. Will add points when we hear back and know more

**Comment by csossi** [comment]
Verified in QA (master)

**Comment by samitron7** [comment]
Verified in UAT
