### ISSUE TITLE
Padding should be added to text element size

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#2089]
## Bug Description

When a 100x100 text element is added a 10px padding, it should be changed to a 120x120 text element (and move 10x10 pixel up), so the text will have identical location before and after.

Remember to do this correctly for rotated text fields too.

## Expected Behaviour

* Text field size and location should update as per above.

## Steps to Reproduce

1. Create a new text field
1. Add 20px padding both vertical and horizontal
1. Observe the text field size not increase, but rather shrink the actual text area

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

Things to consider:

* Text fields placed on edge of canvas
* Multi-selection
* Rotated text fields

**Comment by csossi** [comment]
Verified in QA
