### ISSUE TITLE
Replacing background while bg video is playing causes weird interim state

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#2090]
## Bug Description

Replacing background while bg video is playing causes weird interim state, see video for detail. There's a time in which the newly dragged in bg video isn't reflected, even though thumbnail and preview show the new video the canvas shows the old one in landscape (not zoomed as bg)

## Steps to Reproduce

1. add video as bg
2. play bg video
3. while bg video play, drag new video as background (using drop zones)

## Screenshots

[Replace background while playing video causes weirdness.zip](https://github.com/google/web-stories-wp/files/4697501/Replace.background.while.playing.video.causes.weirdness.zip)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
