### ISSUE TITLE
Hide animation tab behind feature-flag

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#2092]
## Feature Description

Temporarily hide animation tab behind feature-flag

## Alternatives Considered

* None

## Additional Context

From [UX Evaluation](https://docs.google.com/presentation/d/1ZiZWrmLiX40rt3n_1LMSGJxYWI-xsWFsS9bkzdbRIV8/edit?ts=5ec35b92#slide=id.g780d0a5251_0_1)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA PR#2214:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/816c06e6-c308-4bb3-b5c0-a3e99b1b2c68)

**Comment by samitron7** [comment]
Verified in UAT
