### ISSUE TITLE
Video: pointer cursor inadvertently shown in accessibility section

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#2093]
## Bug Description

When a video is selected, hovering over the poster image in the accessibility section shows `cursor:pointer` (the little hand withg the finger), but nothing happens when you click

## Expected Behaviour

The cursor should be the normal arrow one while not on the clickable edit icon.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
