### ISSUE TITLE
Hide keyboard shortcut button behind feature-flag

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#2094]
## Feature Description

Temporarily hide keyboard shortcut button behind feature-flag.

That's this button:
![Screen Shot 2020-05-28 at 2 44 15 PM](https://user-images.githubusercontent.com/637548/83180739-e18e8e00-a0f1-11ea-9720-4aadc3524a85.png)

## Alternatives Considered

* None

## Additional Context

From [UX Evaluation](https://docs.google.com/presentation/d/1ZiZWrmLiX40rt3n_1LMSGJxYWI-xsWFsS9bkzdbRIV8/edit?ts=5ec35b92#slide=id.g780d0a5251_0_1)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/142821ba-3f1f-46db-b42e-39fc93884a28)

**Comment by samitron7** [comment]
Verified in UAT
