### ISSUE TITLE
Implement new safe zone toggle and markers

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#2096]
## Feature Description

Implement new tick marks to show safe-zone and remove old design. Also add toggle

### Design

Design in [Figma](https://figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=7637%3A327):

#### Tick marks displayed
![Screen Shot 2020-06-08 at 11 07 21 AM](https://user-images.githubusercontent.com/637548/84046638-5bd3d380-a978-11ea-954f-f93b61e82ee9.png)

#### Toggle

*Disabled:*
![Screen Shot 2020-06-08 at 11 07 55 AM](https://user-images.githubusercontent.com/637548/84046635-5b3b3d00-a978-11ea-9c9b-b668a8480c67.png)

*Enabled:*
![Screen Shot 2020-06-08 at 11 07 50 AM](https://user-images.githubusercontent.com/637548/84046637-5bd3d380-a978-11ea-8335-274471fde6ae.png)

### Issues with current design
See image, the bottom safezone is not visible. 
![0sZ3MJrLrAf](https://user-images.githubusercontent.com/13389997/83181221-9032ce80-a0f2-11ea-81fe-229308567afa.png)

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

- [x] Remove old safe-zone gray-out component
- [x] Create flag for safe-zone toggle somewhere in the stack (probably in Canvas provider?)
- [x] Show tick-marks if safe-zone enabled (default: true). They are 20px by 1px and 40% white. Place at proper layering.
- [x] Add functional toggle button to carousel menu

**Comment by miina** [comment]
@o-fernandez I can actually see the bottom safe-zone on this screenshot, it's just barely noticeable due to the image colors.

Q: What's the expected behavior here, does this perhaps require some UX attention to figure out what to do in case of images which make the safe-zone almost invisible due to the colors?

**Comment by o-fernandez** [comment]
I can't see it at all! But, let's get Sam's input on UX/UI. 

@samitron7 can you take a look at this and provide a recommendation?

**Comment by jauyong** [comment]
@samitron7 to add updated design to ticket.

**Comment by samitron7** [comment]
Apologize for the delay. Figma flow [here](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=7637%3A327) and [here](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=8012%3A395927)

Removing the UX Needed label

**Comment by dvoytenko** [comment]
@o-fernandez @samitron7 Historically playing with fullbleed/safezone has been dangerous. Would you be open to splitting this issue in two: markers and toggle. Markers are definitely safe to do. And toggle could be done post-beta and/or moved under a flag?

**Comment by samitron7** [comment]
OK to split into 2 ticket since we also need FTUE for this concept.

@o-fernandez Yes, this is the latest design. @pbakaus and I chatted and both agreed that it should not intrude with your lovely design on the page. This coupled with the [design space guides](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=8012%3A395927) makes it easy for users to know when they are about to place something that is in one of the safe zone.

**Comment by dmmulroy** [comment]
@samitron7 @dvoytenko for my open PR #2378 should I put the toggle behind a feature flag in that PR?

**Comment by dvoytenko** [comment]
@dmmulroy if you are already that far along and have toggle done, I think it's ok - let's just get more QA on it. If QA has any serious problems returned, we can discuss. If you haven't started the toggle yet, then I'd recommend pushing it to the follow up PR.

**Comment by dmmulroy** [comment]
The toggle is already wired up and should be working in my PR, I'll leave it unless it fails QA at which time I'll put it behind a feature flag 👍

**Comment by swissspidy** [comment]
@csossi Se #2378 for explanation & testing instructions

---

Some things that might need refining:

- The button is set as `display: inline-block`, at least locally on master. That makes the button look like this:  
  <img width="509" alt="Screenshot 2020-06-22 at 15 42 55" src="https://user-images.githubusercontent.com/841956/85294556-126aa480-b49f-11ea-975f-aef428fb716c.png">
- On https://stories-new-wordpress-amp.pantheonsite.io/ it seems to be correctly use `display:block`, but the button seems very small and the icon isn't placed in the middle of the button. Seems like the latter requires an update to the actual `path` within the SVG:  
  <img width="366" alt="Screenshot 2020-06-22 at 15 43 29" src="https://user-images.githubusercontent.com/841956/85294868-71c8b480-b49f-11ea-8af4-dcc38fa25f72.png">
- Tooltips for the safe zone and carousel buttons would help a lot.

**Comment by csossi** [comment]
Verified in QA

**Comment by samitron7** [comment]
Verified in UAT
