### ISSUE TITLE
Hide text sets in text tab behind feature-flag

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#2097]
## Feature Description

Temporarily hide text sets in text tab behind feature-flag

Screenshot:
![Screen Shot 2020-05-28 at 2 50 50 PM](https://user-images.githubusercontent.com/637548/83181302-afc9f700-a0f2-11ea-8e7d-680e5d9e75ef.png)

## Alternatives Considered

* None

## Additional Context

From [UX Evaluation](https://docs.google.com/presentation/d/1ZiZWrmLiX40rt3n_1LMSGJxYWI-xsWFsS9bkzdbRIV8/edit?ts=5ec35b92#slide=id.g7830109f71_0_29)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/e60f4b50-a809-4121-bff6-5cb05043d4ec)

**Comment by samitron7** [comment]
Verified in UAT
