### ISSUE TITLE
Hide search in text and shapes panel behind separate feature-flags

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#2098]
## Feature Description

Temporarily hide search in text and shapes panel behind separate feature-flags

Screenshots:

| In text | In shapes |
|-|-|
| ![Screen Shot 2020-05-28 at 2 54 44 PM](https://user-images.githubusercontent.com/637548/83181687-3b438800-a0f3-11ea-92ea-f99d1852c6c0.png) | ![Screen Shot 2020-05-28 at 2 54 51 PM](https://user-images.githubusercontent.com/637548/83181688-3bdc1e80-a0f3-11ea-9f55-5565a16db9d2.png) |

## Alternatives Considered

* None

## Additional Context

From [UX Evaluation](https://docs.google.com/presentation/d/1ZiZWrmLiX40rt3n_1LMSGJxYWI-xsWFsS9bkzdbRIV8/edit?ts=5ec35b92#slide=id.g7830109f71_0_29)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/1b02a0cc-3aaf-41a8-931a-d3e65f359d3b)
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/5b12e6f2-2035-4f53-9391-fc1f95d0e2a5)

**Comment by samitron7** [comment]
UAT - Verified
