### ISSUE TITLE
Be more consistent with buttons in dialogs

### ISSUE THREAD

**Issue by joannag6** [GoogleForCreators/web-stories-wp#2104]
Questions:

1. Should we use `<Primary>` with `<Plain>`, `<Plain>` with `<Plain>`, or something else?
2. What should the order be? `Confirm` `Cancel` or `Cancel` `Confirm`?
3. Should there be some space in between the buttons?

See related discussions in other PRs:
https://github.com/google/web-stories-wp/pull/1656#discussion_r430941190
https://github.com/google/web-stories-wp/pull/1733#discussion_r430940224
https://github.com/google/web-stories-wp/pull/2080

Material Design guidelines: https://material.io/components/dialogs

### Existing Dialogs

**Preview Error Dialog**

Shown when the story cannot be previewed in a new  tab for some unforeseen reason.

Demo: https://google.github.io/web-stories-wp/?path=/story/stories-editor-components-previewerrordialog--default

Screenshot:

<img width="343" alt="Screenshot 2020-05-29 at 13 33 26" src="https://user-images.githubusercontent.com/841956/83255620-10b80480-a1b1-11ea-9d9c-9bf0eb1ab145.png">

**Edit Media  Dialog**

Shown when editing a media item via the media library.

Demo: https://google.github.io/web-stories-wp/?path=/story/stories-editor-components-media-edit-dialog--default

Screenshot:

![Screen Shot 2020-05-29 at 3 20 15 PM](https://user-images.githubusercontent.com/15134432/83224099-f6395780-a1bf-11ea-9152-4f51de395516.png)

**Delete Media Dialog**

Shown when deleting a media item via the media library.

Demo: https://google.github.io/web-stories-wp/?path=/story/stories-editor-components-media-delete-dialog--default

Screenshot:

<img width="610" alt="Screenshot 2020-05-29 at 13 33 37" src="https://user-images.githubusercontent.com/841956/83255611-0c8be700-a1b1-11ea-940f-c808a16bf15e.png">

**Comment by swissspidy** [comment]
Apparently the dialogs now need to be [dark](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=9631%3A10)? 🤔 

<img width="722" alt="Screenshot 2020-06-12 at 15 17 55" src="https://user-images.githubusercontent.com/841956/84506751-1721a280-acc0-11ea-9b10-3182eb12e8c8.png">

@samitron7 can you verify that?

**Comment by samitron7** [comment]
@swissspidy Let's all use the white one for now. This is all undergoing a visual design overhaul but still there shouldn't be a reason why all the dialog box are coded up differently. They all should look like the material dialog box. And use CANCEL and it should be the action on the left


<img width="274" alt="Screen Shot 2020-06-24 at 2 59 00 PM" src="https://user-images.githubusercontent.com/10889431/85631941-41158600-b62b-11ea-9970-599cb25544a9.png">

Example from [Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=7941%3A18814)

**Comment by swissspidy** [comment]
For QA, please check out the following links and verify that all action buttons/links use the same style:

https://google.github.io/web-stories-wp/storybook/?path=/story/stories-editor-components-dialog-post-publish--default
https://google.github.io/web-stories-wp/storybook/?path=/story/stories-editor-components-dialog-preview-error--default
https://google.github.io/web-stories-wp/storybook/?path=/story/stories-editor-components-dialog-delete-media--default
https://google.github.io/web-stories-wp/storybook/?path=/story/stories-editor-components-dialog-edit-media--default

**Note:** wait until https://github.com/google/web-stories-wp/runs/811930514 passes!

**Comment by csossi** [comment]
Tested in #2755 - Win10/Chrome

"delete" not appearing correctly:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/c7dfd23a-6381-4b74-abed-922f3038c767)

"save" not appearing correctly - and can there be line breaks here?:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/b222dad4-eb18-4163-954b-62b249e691c4)

**Comment by csossi** [comment]
@swissspidy - how can I trigger a "preview" error in order to check that popup?

**Comment by swissspidy** [comment]
@csossi #2755 is the wrong PR. Check `master`. Also, the preview error dialog cannot really be triggered.

That's why I wrote these QA instructions here:

https://github.com/google/web-stories-wp/issues/2104#issuecomment-650284021

**Comment by swissspidy** [comment]
Moving directly to UAT since this is already in master and https://github.com/google/web-stories-wp/issues/2104#issuecomment-650284021 makes this one super easy to verify.
