### ISSUE TITLE
Story list should show story menu on hover

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#2124]
## Feature Description

This is an ask that came up in #1867 : 
> In the list view, not sure if this is spec'd, but it'd be great to also have the 3-dot menu show up on hover and let the user access the actions in there. If not spec'd, we can ignore for now.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/c5202ae8-0842-4460-820e-6fa1ceaadfcd)
