### ISSUE TITLE
"Open In Editor" is squashed on 1110px screens

### ISSUE THREAD

**Issue by mariano-formidable** [GoogleForCreators/web-stories-wp#2151]
## Bug Description

When the browser width is set to approx 1110px (which happens often on my laptop because I normally have my window set to 2/3 the screen width and the chrome dev tools set to 1/3 my screen width), the text for "OPEN IN EDITOR" wraps and appears visually... clunky.  

## Expected Behaviour

The button should have center text and preferable _not_ word wrap at any width.  

## Screenshots

![image](https://user-images.githubusercontent.com/40646372/83310013-9b9ffb80-a1bf-11ea-8681-a8c0b83ec402.png)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
This will probably happen often with translations too
