### ISSUE TITLE
Multi-selection box is not updated/responsive

### ISSUE THREAD

**Issue by merapi** [GoogleForCreators/web-stories-wp#2154]
## Bug Description

The multi-selection box is not updated when switched between small/big canvas.

## Expected Behaviour

The selection box should update after the canvas is resized.

## Steps to Reproduce

- Select 2+ elements while on small/big canvas.
- Resize to big/small canvas.
- The selection box is not updated.

## Screenshots

![responsiveLasso](https://user-images.githubusercontent.com/21036224/83404342-c5009780-a40a-11ea-8e1c-5e1f1f711cf2.gif)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
