### ISSUE TITLE
Templates: Remove Publisher Logos from Templates (Part A)

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#2156]
## Feature Description

We need to remove the publisher logos from the templates, ESPN, Bon Appetit, Vogue and replace them with "outline square box, white. Use black if the bg is white."

This issue tracks the following templates:
- Fashion
- Fitness
- Beauty

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
