### ISSUE TITLE
Templates: Remove Publisher Logos from Templates (Part B)

### ISSUE THREAD

**Issue by mariano-formidable** [GoogleForCreators/web-stories-wp#2159]
## Feature Description

We need to remove the publisher logos from the templates, ESPN, Bon Appetit, Vogue and replace them with "outline square box, white. Use black if the bg is white."

This issue tracks the following templates:
- ~~DIY~~ (no branding)
- Cooking
- ~~Entertainment~~ (no branding)
- Travel
- ~~Wellbeing~~ (no branding)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by littlemilkstudio** [comment]
Mariano pushed his template changes onto this PR which automates the template creation process:
https://github.com/google/web-stories-wp/pull/2164

**Comment by csossi** [comment]
broken image indicator appearing for Entertainment:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/2d8dd156-fc3b-431d-9caa-c912289f79ea)
