### ISSUE TITLE
Element Selection Box In the workspace

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#2162]
## Bug Description

If you place an element (shape, text, video, images) partially in the work space (dark gray area), the element should be clipped but the selection box should be visible so that the user is able to transform (resize, drag on left side etc) so that they are not forced to drag the element back into the page to transform. 
[Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=2832%3A208)

## Steps to Reproduce

1. Place an element (shape, text, video, images) partially in the work space 

## Screenshots

![image.png](https://images.zenhubusercontent.com/5e985a7aea3104e101699670/a30119d7-e9c0-4a63-a246-2bd8ed2703a6)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by samitron7** [comment]
[Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=9517%3A0) flow.

[#2042](https://app.zenhub.com/workspaces/web-stories-5e94d3aced449034e1e9b226/issues/google/web-stories-wp/2042) is a related issue

**Comment by miina** [comment]
This got already fixed in #2285, closing.
