### ISSUE TITLE
Use eslint-plugin-jasmine for Karma tests

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#2173]
See https://github.com/tlvince/eslint-plugin-jasmine

Most of the recommended rulesets would be useful for us I think. `no-focused-tests` was called out in particular though, as this feature should only be used during development and not checked in.

Note that there are also these custom aliases:

https://github.com/google/web-stories-wp/blob/master/assets/src/edit-story/karma/_init.js#L20-L24

Which means we should consider enabling `jest/no-focused-tests` too.

**Comment by dvoytenko** [comment]
@swissspidy custom aliases were aspirational. I don't think I managed to make them work fully, so we can just remove them.
