### ISSUE TITLE
Fix background frame border

### ISSUE THREAD

**Issue by merapi** [GoogleForCreators/web-stories-wp#2185]
## Bug Description

Fix background frame border.

## Expected Behaviour

Either fix the top part or remove it completely. I don't think we need it?

## Steps to Reproduce

- Select BG element
- Deselect BG element
- Border is there

## Screenshots

![image](https://user-images.githubusercontent.com/21036224/83522590-2dba4380-a4e1-11ea-893b-12c6b2f2f02b.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
I can't really reproduce this, may have been fixed by another fix. Will close for now. Reopen if issue is still there.
