### ISSUE TITLE
Hide Text Styles from Beta

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#2186]
## Feature Description

According to @samitron7 the  Color/Style Presets still need work and some UX changes and are not going to beta. See Sam's last comment [in this thread](https://docs.google.com/document/d/1EQ12sD4a1plmMeBu7YMWOdUSg0FeegB9qi2_OlV3Tp0/edit?disco=AAAAJkni_Qo).

We should hide these and add back once the UX has been finalized.

Edit: This will now include Text Styles part only.

## Alternatives Considered
N/A

## Additional Context
N/A

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
N/A

**Comment by csossi** [comment]
Verified in QA

**Comment by samitron7** [comment]
Verified in UAT
