### ISSUE TITLE
Dashboard: Data should refresh with changes when returning back from workspace editor

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#2188]
## Feature Description

When the user is on the dashboard and selects to edit a story and makes changes, when they click back it should update the dashboard to reflect the changes they saved.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

- Visit the Dashboard
- Edit a story and make changes and save/or publish
- Click back on the browser and see that the dashboard preview card for your story is updated with the new changes that were saved

**Comment by csossi** [comment]
Verified in QA

Story (start) in Dashboard:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/edeea7af-e704-4b25-8437-83afe8c37b56)

Linked to Editor and made edits:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/674caf7b-c032-4c73-879d-e139bf1c5549)

Returned to Dashboard:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/823e8f9c-7d5c-43e5-bce0-9fa769b77fa9)
