### ISSUE TITLE
Text: Fill-highlight + padding = incorrect alignment

### ISSUE THREAD

**Issue by dreamofabear** [GoogleForCreators/web-stories-wp#2201]
## Bug Description

Center- and right- text alignment are incorrect with "fill: highlight" and non-zero padding.

## Steps to Reproduce

1. Create a new text element
2. Set "Fill: Highlight" and padding: 20.
3. Set text alignment to "right" or "center".

Expected: The text is aligned to the right or center as expected.
Actual: The text is slightly offset to the left of its expected position.

## Screenshots

<img width="619" alt="Screen Shot 2020-06-02 at 9 37 04 PM" src="https://user-images.githubusercontent.com/20525523/83586549-c02b0900-a51a-11ea-8b3b-29538416b193.png">

## Additional Context

- Plugin Version: 1.0.0-alpha+edfbf49
- Operating System: macOS 10.15.4
- Browser: Chrome 83

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
@barklund to add in dependancies

**Comment by bmattb** [comment]
As per discussion today this ticket is dependant on 3531, 2089, 1980 and should be moved to 1.1 as well

**Comment by csossi** [comment]
Verified in QA
