### ISSUE TITLE
Help user understand how document auto-advance and video loop settings relate

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#2204]
## Feature Description

If a user has the story document set to auto advance, and they add a video to the page in "loop" setting, the story will only play the video for as long as the auto-advance setting. This can lead to the scenario: 
1. User adds video of 30 seconds in "loop"
2. Auto-advance is set to 7 seconds
3. Video only plays for 7 seconds and story advances to the next page. 

The user can switch the video to "play once" so that it plays all the way through and then the story proceeds, but this may not be clear to users. Consider adding helpful hints in-editor to the user. 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Copying idea from #2549:

> We should warn the user about this and let them decide whether to change the video to "play once" instead of looping.

**Comment by swissspidy** [comment]
@o-fernandez This happens also to non-looping videos it seems?

1. User adds video of 30 seconds (not looping)
2. Auto-advance is set to 7 seconds
3. Video only plays for 7 seconds and story advances to the next page.

**Comment by o-fernandez** [comment]
@swissspidy that's good to know! I thought that when a video is set to non-looping/play once, we'd play it all the way through before advancing. If that's not the case, even more the reason to provide education and help users figure out what to do in that case. 

Right now our auto-advance setting is at the document level, depending on how this is affecting story creation with longer videos we may consider moving it to a page-level setting.

**Comment by swissspidy** [comment]
@o-fernandez turns out it's a bug, will investigate...

Edit: #5030
