### ISSUE TITLE
Animations: Add animations to BEAUTY template to match designs

### ISSUE THREAD

**Issue by mariano-formidable** [GoogleForCreators/web-stories-wp#2211]
The animation process for a template is as follows:
- Applying animations in the animation editor `/story-anim-tool`
- Alter its static layout if needed to accommodate the animation
- If template requires a new animation part that doesn't already exist
  - Create ticket for missing animation part
  - Add animation part to code base
  - Go back to template and apply newly created animation part
  - Continue with template animations

Reference the figma designs:
https://www.figma.com/file/RTzSw47oi6pEZXEfP2JoBo/Templates?node-id=1%3A8

And reference the movie clips from this folder:
https://drive.google.com/drive/folders/1E0nLATcplhGNzgteOymx3s2SyA-cc7_M

**Comment by csossi** [comment]
Tested in PR#3058 - Win10/Chrome

The hearts themselves aren't clickable, only the circle around them is. Assuming both should be clickable here

user click on circle area around the heart image (fine):
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/65a69af8-e16b-4348-a8c8-0b426790d208)

user just advances to next panel if they click directly on heart image

**Comment by mariano-formidable** [comment]
@littlemilkstudio QA found a little bug noted above.  It seems even when you preview the template from the editor and try and click on the heart, the link doesn't trigger and it just switches to the next page 😱 
<img src="https://user-images.githubusercontent.com/40646372/87452236-d1554400-c5b5-11ea-9103-eab85ee41df9.gif" height="300">

**Comment by mariano-formidable** [comment]
@csossi Alrighty, clicking on the hearts directly should trigger the links.

**Comment by csossi** [comment]
Verified in QA

**Comment by o-fernandez** [comment]
@mariano-formidable @swissspidy I don't think this is still testable for UAT purposes, is that right?

**Comment by mariano-formidable** [comment]
@o-fernandez The animations are _not_ testable in UAT, but you can confirm that the hearts on page 4 are clickable and link to example.com.  Adding links to the template and the animations were done in the same PR 😱

**Comment by o-fernandez** [comment]
Haha, ok. In that case.... sounds good.
