### ISSUE TITLE
Unclear lasso selection, not sure how to select the elements.

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#2215]
## Bug Description

See video, it's unclear to me why sometimes the top text element is being selected and in others it is not, even if my lasso selection in both cases touches the element. Unclear why it works sometimes and sometimes it doesn't. 

Related: #1782

## Expected Behaviour

It should consistently select the element if in the lasso selection area.

## Screenshots

[Lasso selection not clear.zip](https://github.com/google/web-stories-wp/files/4725108/Lasso.selection.not.clear.zip)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
