### ISSUE TITLE
Text height changing 

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#2218]
## Bug Description

See video. When I have a text for which I inserted a line before and after the text (by pressing the enter key), I get the right effect I wanted. However, when I enter edit mode for that text element the before and after lines are removed. This shouldn't be happening. 

## Expected Behaviour

Lines should not be removed when I re-enter text edit mode for that text element.

## Screenshots

[See video](https://drive.google.com/open?id=1Xyg5LbP35mxcGX88luHWBJ_v_wHdM0SH)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
@barklund / @merapi - we think that this is a good candidate for the Pea pod, but wanted to confirm that @merapi  work on text isn't going to solve. Please confirm.

**Comment by merapi** [comment]
@bmattb This is unrelated to my fixes and looks like https://github.com/google/web-stories-wp/issues/1952 is related and maybe https://github.com/google/web-stories-wp/issues/2788

**Comment by dmmulroy** [comment]
Additional findings:

It appears some sort of `.trim()` functionality is occurring `onClick` of the `Edit` or `TextFrame` text component (or a child of).  If you add two line breaks to start of a text element and two line breaks to the end then click off and then click back on, the two outside line breaks are removed with two still existing.

Edit:

Definitely seems like the `.trim()` like functionality is occurring during mount/early render of `EditLayer`

**Comment by csossi** [comment]
Tested PR 3543 (Win10/Chrome)

The effect is hidden from the user if they resize text with a blank line above and below (note: they can see it if they go into Edit mode)

Start:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/255af3ba-27a6-41c9-a694-2855e96a193e)

Grabbed right side handle and dragged slightly to right and released:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/383dbec6-d01c-4826-b13e-eded59a436fe)

**Comment by swissspidy** [comment]
The testing instructions were:

> 1. Create or open an existing story
> 1. Create a textbox with some dummy text
> 1. Include a linebreak as the first character and as the last
> 1. Click off the canvas to exit Edit Mode
> 1. Double back on the text box to enter Edit Mode
> 1. See that the text height remains the same and the linebreaks are preserved

@csossi Did that work as expected?

If so, it sounds like the issue you noticed with the resizing warrants its own ticket. Because this ticket here is all about the edit mode.

cc @dmmulroy

**Comment by csossi** [comment]
You're correct, @swissspidy  - and it therefore DID work as expected. Passing

**Comment by swissspidy** [comment]
Ah, looks like the resizing issue is covered by #1952
