### ISSUE TITLE
Align story menus to best fit

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#2219]
In the dashboard stories there's a menu that opens per story via the three vertical dots. It would be nice to have the story item menu align to best fit. 
So in the case seen in the screenshot it would be at the bottom.
Storybook will be helpful for testing this out.

![Screen Shot 2020-06-03 at 2.03.51 PM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/d1f20a1d-a760-4c7e-a0ad-cc83ba69eb12)

**Comment by csossi** [comment]
Verified in QA - PR#2711
