### ISSUE TITLE
Text: Wrapping (line breaks) sometimes inconsistent

### ISSUE THREAD

**Issue by dreamofabear** [GoogleForCreators/web-stories-wp#2234]
## Bug Description

Wrapping of text is sometimes inconsistent between desktop vs. mobile or Chrome vs. Safari. This can result in truncated text due to unexpected extra line breaks.

I've encountered at least two distinct causes of this bug. The repro steps below describe one.

This case appears to be fixed by making sure the font stylesheet in the published story includes the all font weights used in the story (in this case, the bold/700 font weight). My guess is Chrome and Safari interpolate unprovided font weight differently.
```html
<!-- Before -->
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet">

<!-- After -->
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500;700&amp;display=swap" rel="stylesheet">
```

Possibly related to #743.

## Expected Behaviour

Text wrapping observed in edit mode should be consistent with text wrapping on the published story (desktop/mobile, and on all supported browsers).

## Steps to Reproduce

Example: View the last page of [this story](https://stories-new-wordpress-amp.pantheonsite.io/stories/wills-test-story/) on Chrome vs. Safari.

1. Create a text element that enough text to wrap once or more.
2. Set the font family to "Roboto" and font weight to bold.
3. Reduce the width of the text box to the smallest width that preserves the current wrapping.
4. Publish the story.
5. View the story on Chrome and Safari (desktop Safari in responsive mode with can emulate iPhone screens).

Expected: The edit mode view, Chrome, and Safari all have the same text wrapping.
Actual: Safari has a different text wrapping.

### Chrome desktop
<img width="390" alt="Screen Shot 2020-06-03 at 9 20 10 PM" src="https://user-images.githubusercontent.com/20525523/83704432-11510080-a5e0-11ea-86de-88927223c17d.png">

### Safari desktop
<img width="467" alt="Screen Shot 2020-06-03 at 9 20 16 PM" src="https://user-images.githubusercontent.com/20525523/83704427-0eeea680-a5e0-11ea-9c69-7de6a9b532f5.png">

## Additional Context

- Plugin Version: 1.0.0-alpha+d606fa7
- Operating System: macOS 10.15.4
- Browser: Chrome 83 and Safari 13.1
---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
> This case appears to be fixed by making sure the font stylesheet in the published story includes the all font weights used in the story 

I originally implemented it this way 🤔

What I find odd here is the existance of the `strong` tags. That probably breaks this.

Related: #1121

**Comment by swissspidy** [comment]
This function is responsible for getting all font variants from Google Fonts:

https://github.com/google/web-stories-wp/blob/21a18f17c3b8fad53f90dc0f480e0ed8d9acdea2/assets/src/edit-story/output/utils/getFontDeclarations.js#L38-L109

It looks like it wasn't updated to accommodate for the inline text formatting we now have, i.e. this is a regression.

Edit: to help clarify, `fontStyle` and `fontWeight` are not a thing anymore. Styles and weights need to be extracted from the text content.

**Comment by dvoytenko** [comment]
@swissspidy WDYT, as a Beta-fix, we were to just request all fonts every time? I actually don't know the extent of the optimization we're getting here anyway: fonts are downloaded lazily in either case.

**Comment by swissspidy** [comment]
I think the difference is quite big for fonts with lots of variants and it adds up when using many different fonts in a story. So IMHO we should definitely optimize this. It worked great before, and doesn't seem hard to fix it again.

As a hotfix, sure we could just request all fonts (like we already do in the editor).

**Comment by dreamofabear** [comment]
The `<strong>` tag in Katharina's story might've been a relic from an old version. In the repro example linked above, the same thing happens with `font-weight: 700`.

**Comment by dvoytenko** [comment]
@swissspidy Certainly, if the optimal path is clear, we should do that. I believe @obetomuniz fixed some similar issues in the editor itself. And /cc @barklund fyi.

**Comment by csossi** [comment]
Verified in QA

Safari:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/f84ad50f-9bb3-48c0-b5c3-c9908b05ee40)

Chrome:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/2a5548f9-4397-4eb6-957a-1d2e4d005e92)

**Comment by samitron7** [comment]
Verified in UAT
