### ISSUE TITLE
Remove 'upload' button while a search is active

### ISSUE THREAD

**Issue by cvolzke4** [GoogleForCreators/web-stories-wp#2235]
## Feature Description

If you're in search mode, the upload button should be hidden:
(figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=7497%3A301236)

This does not prevent an upload from happening as a result of a drag/drop operation into the Media Gallery or Canvas.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by zidianlyu** [comment]
@cvolzke4 may I have an update review to this issue?
I just check the search mode, and here is the current UI:

![Screen Shot 2020-12-16 at 12 58 40 PM](https://user-images.githubusercontent.com/11252886/102405754-78436f00-3f9e-11eb-856e-4480aa008c57.png)

And I cannot find the `upload` button.

**Comment by swissspidy** [comment]
@zidianlyu this refers to the Upload button in the regular media library tab

**Comment by zidianlyu** [comment]
@cvolzke4 

To clarify, do we want something like this?

<img width="252" alt="Screen Shot 2020-12-21 at 11 05 54 AM" src="https://user-images.githubusercontent.com/11252886/102812835-a0efae00-437c-11eb-9ee6-42e1d5c908aa.png">

**Comment by swissspidy** [comment]
Since Clinton is no longer on the project, @samitron7 should be sble to advise.

**Comment by zidianlyu** [comment]
@samitron7, do you have any suggestion on this?

I get the point why we want to hide the upload button during search; however, in this case, as a user, I might have no idea why the upload button get disappeared or how can I get it back. Any suggestions?

**Comment by zidianlyu** [comment]
Update mock link:
https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=7507%3A303736

**Comment by csossi** [comment]
Verified in QA
