### ISSUE TITLE
Refactor folder/hook structure for media fetch/upload actions

### ISSUE THREAD

**Issue by cvolzke4** [GoogleForCreators/web-stories-wp#2236]
## Task Description

Today, the MediaProvider context has too many responsibilities:
- Media pagination
- Loading images and videos from WordPress
- Upload image to WordPress
- Upload video to WordPress
- Upload video poster to WordPress

This causes a few problems:
- Each operation such as uploadMedia handles everything - pagination, API call and transformation, making the logic difficult to follow.
- The logic is closely tied to WordPress media format, which will make it difficult to untangle later.
- Media operations can depend on MediaProvider state, which causes unnecessary re-renders.

Proposed structure:

| Folder     | Hook name    | Operations    | Description
|------------| ------------ | ------------- | -----------
| media      | useMedia (MediaProvider) | Side effects: load media, uploading video posters | Manages all media state, including media lists and pagination. |
| media/load | useLoadMedia | loadMedia()   | Use useWordPressLoadMedia to load pages of media into MediaProvider context state.
| media/upload | useUploadMedia | uploadImage(), uploadVideo(), uploadVideo Poster() | Use useLoadWordPressMedia to upload media, and update MediaProvider context state with progress reports.
| m/wordpress/load | useLoad WordPressMedia | loadMedia() | Use the WordPress APIs from ApiContext to load media from WordPress, and transform the data into Story Editor format.
| m/wordpress/upload | useUpload WordPressMedia | uploadImage(), uploadVideo(), uploadFile() | Use the WordPress APIs from ApiContext to upload media.

**Comment by swissspidy** [comment]
Sounds like a good step towards better decoupling the editor from WordPress 👍 

----

_PS. Updated the issue description to properly spell WordPress with a capital P :-)_
