### ISSUE TITLE
Add support for pending post status. 

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#2239]
## Feature Description

Some user roles in WordPress do not support publishing directly. They do however, support a pending review state. As this stories editor integrated into WordPress, this pending state should be supported too. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Related / perhaps duplicate I suppose: #7762

**Comment by spacedmonkey** [comment]
I think that this is a duplicate. But the other ticket explains it better, I believe.

**Comment by swissspidy** [comment]
In that case, consolidating the tickets
