### ISSUE TITLE
Embed Block: Make embedding local stories easier

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#2240]
## Feature Description

Split out from #1118 and #1249.

Users should be able to more easily embed local stories, either by selecting them from a dropdown, or by typing in an autocomplete field (see https://github.com/google/web-stories-wp/issues/1118#issuecomment-634852376 for an example).

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
@swissspidy Should I pick this up?

I was thinking about reusing the hyperlink popover already found in core. 

![Screenshot 2020-06-18 at 14 30 27](https://user-images.githubusercontent.com/237508/85026638-d074f200-b170-11ea-9c38-30b04d09080d.png)

Or were you thinking about something a little more simple? 

Should this UI be part of the original embed web stories block or should there be two blocks?

**Comment by swissspidy** [comment]
Sure 👍 

Let's do this in the existing block for now.

I haven't looked closely into available options, but if we can re-use logic from that popover, that would make our lives easier for sure 👍 

Obviously without "post" results and without "Open in new tab".

Do you perhaps have a rough estimate? Despite existing components it seems like some effort is required..

**Comment by ckluis** [comment]
I'm new to this project, but if the goal is to also allow people to be able to embed from third parties.  This search box could be extended for internal/external story sources. Example: Search _site:example.com puppy_.

This would provide a rich medium for sharing content.

**Comment by swissspidy** [comment]
Embedding from third party sites is already possible by inserting any story URL in the input field. I don't think we'd want to allow searching third party sites though as the focus is on embedding one's own stories.

**Comment by bmattb** [comment]
@swissspidy  will follow up on this to get additional details from product & UX on the implementation

**Comment by o-fernandez** [comment]
There is already a standard UI that WordPress already uses for **linking** to local posts, can we use the same UI/logic? @swissspidy ? If so, we may not need to block this on PM/UX. 

Also, marking as P2 given beta feedback popularity of this request.

**Comment by swissspidy** [comment]
Probably! There are some twists to that UI as it's used in a different context in Gutenberg (adding links), but we should be able to do some quick testing to verify its usefulness.

**Comment by swissspidy** [comment]
So I spent some time exploring using the existing (and experimental) `LinkControl` Gutenberg (depicted further up in the thread) for our embed block. For reference, that's the component visible when inserting links in paragraphs:

<details>
<summary><strong>View Screenshots</strong></summary>

<img width="620" alt="Screenshot 2020-10-02 at 13 38 11" src="https://user-images.githubusercontent.com/841956/94919364-aabbf080-04b4-11eb-87d7-025cd81a00c8.png">
<img width="693" alt="Screenshot 2020-10-02 at 13 38 19" src="https://user-images.githubusercontent.com/841956/94919369-ac85b400-04b4-11eb-9b74-8783d22bd217.png">

</details>

As you can see from the screenshots above, that component works best wrapped in a `Popover` that is absolutely positioned on the screen after performing some action (like clicking on a button).

It does **not** work well for enhancing an input field like ours:

<img width="653" alt="Screenshot 2020-10-02 at 13 34 29" src="https://user-images.githubusercontent.com/841956/94919587-01c1c580-04b5-11eb-883a-05996efa385c.png">

So what I've come up with is something like this:

<details>
<summary><strong>View Screenshots</strong></summary>

<img width="667" alt="Screenshot 2020-10-02 at 13 34 33" src="https://user-images.githubusercontent.com/841956/94919632-12723b80-04b5-11eb-9207-45a9a4d18f61.png">
<img width="740" alt="Screenshot 2020-10-02 at 13 34 45" src="https://user-images.githubusercontent.com/841956/94919630-11d9a500-04b5-11eb-96df-a5f870640c31.png">
<img width="783" alt="Screenshot 2020-10-02 at 13 34 51" src="https://user-images.githubusercontent.com/841956/94919622-0f774b00-04b5-11eb-9b9d-b2bf87c0cf3f.png">

</details>

I am not super convinced that this is an improvement though.

Unfortunately it's not possible to improve the display or the wording for this experimental component, as its inner components are not exposed publicly.

I've asked in the Gutenberg Slack channel to hear some opinions on this.

---

NB: turns out @westonruter opened a [feature request](https://github.com/WordPress/gutenberg/issues/14393) for this last year because we had the same struggle in the legacy stories editor 😅  Unfortunately there was no traction on that ticket.

**Comment by swissspidy** [comment]
This is being worked on by rtCamp.

**Comment by swissspidy** [comment]
Closing in favor of #4863
