### ISSUE TITLE
Use Web Stories icon everywhere

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#2242]
## Feature Description

Splitting out from #1118: the embed block needs a better icon.

See https://drive.google.com/drive/folders/1hs8w0c9gLpPXRRT8vjpmM9_cnEoYFTAk?usp=sharing for status quo.

We can also use this icon for the WordPress admin menu.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
@samitron7 Any chance of getting on icon for Web stories? If could be used for the sidebar and the gutenberg block.

**Comment by swissspidy** [comment]
Status quo:

<img width="838" alt="Screenshot 2020-06-18 at 15 43 17" src="https://user-images.githubusercontent.com/841956/85027663-72e5a300-b17a-11ea-93ec-adb948635b74.png">


IMO we should use the same icon as Search. See this example in the bottom right corner here:

![web-stories-single-result](https://user-images.githubusercontent.com/841956/85027958-ce179580-b17a-11ea-9ab0-2e3f7ccdc472.png)

amp.dev has a smiliar icon:

<img width="380" alt="Screenshot 2020-06-18 at 15 44 39" src="https://user-images.githubusercontent.com/841956/85027993-d5d73a00-b17a-11ea-82f4-3a8fe9ccfe04.png">

**Comment by samitron7** [comment]
@swissspidy and @spacedmonkey

Icon for embed block:![logo-embedBlock.svg](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/f1114e72-6eb3-4c61-bf8d-076828c3a093)

Icon for editor: ![logo-stories.svg](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/dcfde680-ef44-41c1-a1da-d28337857c5f)

**Comment by spacedmonkey** [comment]
@samitron7 This is what the icon looks like in action. 

### Inactive in sidebar
<img width="170" alt="Screenshot 2020-06-25 at 15 38 41" src="https://user-images.githubusercontent.com/237508/85741111-10e8e880-b6fa-11ea-9bcd-bec9037b7672.png">

### Active in sidebar 
<img width="70" alt="Screenshot 2020-06-25 at 15 38 52" src="https://user-images.githubusercontent.com/237508/85741142-16dec980-b6fa-11ea-92e0-908134f4b627.png">

### Icon in block editor
<img width="714" alt="Screenshot 2020-06-25 at 15 39 12" src="https://user-images.githubusercontent.com/237508/85741161-1a725080-b6fa-11ea-93ea-bbdeaef6f196.png">

**Comment by samitron7** [comment]
You guys can grab it [here](https://material.io/resources/icons/?search=amp&icon=amp_stories&style=baseline)

**Comment by swissspidy** [comment]
Ha, I didn't know it was on the Material Design page. Even better!

Copying it here for reference:

```svg
<svg xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" height="24" viewBox="0 0 24 24" width="24"><g><rect fill="none" height="24" width="24"/></g><g><g/><g><rect height="15" width="10" x="7" y="4"/><rect height="11" width="2" x="3" y="6"/><rect height="11" width="2" x="19" y="6"/></g></g></svg>
```
