### ISSUE TITLE
Embed Block: Provide example content

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#2243]
## Feature Description

Splitting out from #1118: the embed block needs better example content.

See https://drive.google.com/drive/folders/1hs8w0c9gLpPXRRT8vjpmM9_cnEoYFTAk?usp=sharing for status quo.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by samitron7** [comment]
@swissspidy "the embed block needs better example content." Can you give me a screenshot of this so I know what specifically I need to modify?

**Comment by swissspidy** [comment]
@samitron7 We need a good-looking web story that we can use as an example.

Right now we use this example story: https://amp.dev/documentation/examples/introduction/stories_in_amp/preview/

It will be shown to users when they want to embed a story in Gutenberg. It looks like this:

<img width="1184" alt="Screenshot 2020-06-11 at 10 20 07" src="https://user-images.githubusercontent.com/841956/84362239-355aa600-abcd-11ea-8862-e6cc3f60908e.png">

**Comment by swissspidy** [comment]
Of course we can also keep this puppy story for now until we have a nicer story of our own to embed :) We probably shouldn't display a 3P story.

**Comment by spacedmonkey** [comment]
Whatever example content, would have to join to a url that was public and maintained? Are we going to have a website for the public launch of the plugin?

**Comment by swissspidy** [comment]
Correct. And yes, eventually we're gonna have a microsite for the plugin, but that might be _after_ launch. Until then, the current dog story is probably good enough.

**Comment by o-fernandez** [comment]
@swissspidy could we use a template? I imagine that'd be a great representation, and we'd make sure they are good.

**Comment by swissspidy** [comment]
@o-fernandez Good idea! It needs to be a publicly accessible via URL, so we could create a story from a template, and then store it somewhere at https://google.github.io/web-stories-wp/ (or Firebase, eventually) and noindex it. That would be easy enough. But in any case not a stable blocker.

**Comment by swissspidy** [comment]
Obsolete now that the latest stories are used as demo content
