### ISSUE TITLE
Discussion/Discovery: Consider refactoring the element/background structure

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#2253]
Currently, there is always a background element (a shape) even if the user has never added a background element. This results in "dragging along" an empty element and moving it back and forth even though it's not really changing nor having any visual effect.

Currently, based on discussion with @barklund, the background element is kept as a separate element for the following reasons:
1. Drop targeting to background
2. Simpler layer panel -- always having a background element in the layers
3. Simpler reducer rules do to always having a background element.

There are some alternatives we could consider, to name a few:
- Using the Page directly instead of the default background element.
- Keeping the always-existing invisible background element, however, not storing it into `defaultBackgroundElement` when it's replaced since it never changes anyway.
- Keeping only non-background elements in the `elements` array and storing the background element separately

It would be good to discuss if the current implementation is the best option or if there is a better and simpler alternative to move forward with instead.

**Comment by swissspidy** [comment]
> * Keeping the always-existing invisible background element, however, not storing it into `defaultBackgroundElement` when it's replaced since it never changes anyway.

IIRC this came up in #12131 as well.
