### ISSUE TITLE
Alert UI

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#2263]
We've been using the default browser alert to confirm deleting a story. We should switch this out for an actual alert of some sort. We could follow the one in material ui to cut down on UX time. 

This story will be comprised of 
- Alert UI 
- Tests
- Storybook 
- Replacing default browser pop up in use on removing stories 

https://material-ui.com/components/dialogs/#alerts

**Comment by BrittanyIRL** [comment]
(going to move forward mimicking material ui to give users a better experience. We can always circle back with new designs.)

**Comment by swissspidy** [comment]
There's already a Dialog component in the editor app, if we can re-use that.

With that being said, we should be really starting to properly extract commonly used components into their own folder/package

**Comment by BrittanyIRL** [comment]
Thanks, @swissspidy I'll see about copying or mimicking that with the intentions of pulling it out into a shared space.

**Comment by o-fernandez** [comment]
This makes sense - go ahead with your plan to mimic material UI and we can always do a UX exercise if necessary. Don't think we should block the initial effort on UX bandwidth.

**Comment by BrittanyIRL** [comment]
Now delete story confirmation looks like this: 
<img width="432" alt="84210088-12b57980-aa75-11ea-9c8c-d352bc27dedb" src="https://user-images.githubusercontent.com/10720454/84401039-05f16c80-abc0-11ea-885c-0b5325858859.png">

instead of this: 
<img width="489" alt="Screen Shot 2020-06-11 at 8 47 12 AM" src="https://user-images.githubusercontent.com/10720454/84401143-2a4d4900-abc0-11ea-8b70-312d05533b6f.png">

**Comment by o-fernandez** [comment]
That looks good to me as a start, we can make any UX tweaks as necessary in future tickets/revisions.

**Comment by csossi** [comment]
Verified in QA

**Comment by samitron7** [comment]
@swissspidy are story deletion permanent? If so, @BrittanyIRL  if it's easy to change the message to read:

**Delete permanently**
[Story title] will be permanently deleted. This action cannot be undone.

If not, we can close out and I'll file a ticket for update when we get the new visuals in.

**Comment by swissspidy** [comment]
@samitron7 It's up to us. Right now & by default, deleting means putting into the trash. Items can be recovered from trash for around 30 days (depends on website configuration). IMO we should keep it that way.

Trash recovery can currently be done via the classic WP list table.

**Comment by BrittanyIRL** [comment]
text updates like the above are super easy! Just let me know if you want it changed per Pascal's comment above.

**Comment by samitron7** [comment]
Based on @swissspidy's comment, let's just keep it that way.

Verify in UAT
