### ISSUE TITLE
Bug: Default height of layer panel should vary with window size

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#227]
## Feature description

Based off of work done in #51 and #152 in particular, layer panel height is defaulted to 6 layers.

This should vary with overall window size when UX has defined this.

Awaiting UX! Low priority.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by creatorpiyush** [comment]
Can I take this issue if no one is working on it?

**Comment by swissspidy** [comment]
@creatorpiyush Sure thing! We haven't defined the exact breakpoints for this change yet, but you're more than welcome to help setting up the necessary changes for this if you want to. Just leave a comment here if you'd need help setting things up, or if you find areas in the docs that could be improved.

**Comment by creatorpiyush** [comment]
thanks @swissspidy for giving me this opportunity

**Comment by BrittanyIRL** [comment]
This is super out of date with the layer panel updates that have happened in the last 2 years 😅  - closing
