### ISSUE TITLE
Drag and drop (Page)

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#229]
As a user I want to be able to add and upload media files via drag and drop directly to the page

[Feature Brief - Epic: Media Gallery](https://docs.google.com/document/d/1aZH_TI_be2t5Ywyqx4jcPTPdhFGEt7xh-uLzBp2AV4A/edit#)

**Acceptance Criteria**

1. A user is able to drag media from their desktop onto a page and it is uploaded and added to the active page.
2. A user is able to drag media from their desktop onto the workspace and it is uploaded and added to the active page.
3. A user is able to drag multiple media elements (of mixed type) from their desktop onto the workspace / page.
3. After media is dropped, it should show up instantly on the page and media panel
4. After media is added to the page they should be staggered
4. After media is dropped, it will be automatically uploaded
5. After an upload fails, an error message will be shown
6. The first image added to a page will be added as a background image
7. If the media is not uploaded immediately, the uploading UI is shown. #231 
8. If the media is not fully uploaded, hover options should not be shown.
9. A drop target is shown when hovering over the workspace/page with files to drop
9. This should include functionality from #228 

**[Design](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=3642%3A0)**

**Comment by spacedmonkey** [comment]
Assigning to Dima to get across the line.

**Comment by spacedmonkey** [comment]
<img width="1888" alt="Screenshot 2020-03-03 at 11 44 38" src="https://user-images.githubusercontent.com/237508/75772839-9cea9500-5d44-11ea-836f-a020beef6e5f.png">

Using `getBoundingClientRect` in [layout.js](https://github.com/google/web-stories-wp/blob/bd78a337298f08fc64734a1941a47f9d16ee7582/assets/src/edit-story/components/canvas/layout.js#L132) gives some weird results.

**Comment by jauyong** [comment]
Hey @dvoytenko what is your size estimate for the remaining work left for this?

**Comment by dvoytenko** [comment]
I estimate only about 3-4 hours. Just need to get to this and been blocked by a couple of other issues. I should have ample time to do this tomorrow (Tue Mar 10).
