### ISSUE TITLE
Dashboard: Do not use capitalized strings for internationalization

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#2291]
## Bug Description

In the `TemplateNavBar` the string `Use template` is written in all caps:

https://github.com/google/web-stories-wp/blob/c3323311aa68c70944f53d8a651035c61ab9a829/assets/src/dashboard/components/templateNavBar/index.js#L87-L89

This is not ideal for translators, especially since the string `Use template` already exists a few times. So this would duplicate strings.

## Expected Behaviour

`Use template` should be written like so, and capitalized with CSS (`text-transform: uppercase`).

## Steps to Reproduce

Check out a template on the dashboard.

## Screenshots

<img width="208" alt="Screenshot 2020-06-08 at 12 10 41" src="https://user-images.githubusercontent.com/841956/84019157-34cdcf80-a981-11ea-88bb-bd9f4f318292.png">

## Additional Context

- Plugin Version: `master`
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
Fixed w/ other small text bug: https://github.com/google/web-stories-wp/issues/2293
