### ISSUE TITLE
Dashboard: Hide Bookmark feature behind flag

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#2292]
## Feature Description

The bookmark button in the upper right corner should be hidden as long as the feature isn't implemented:

<img width="1509" alt="Screenshot 2020-06-08 at 12 09 53" src="https://user-images.githubusercontent.com/841956/84019311-62b31400-a981-11ea-8968-b67dd28fa930.png">

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by samitron7** [comment]
Verified in UAT
