### ISSUE TITLE
Entering story title is slow / lagging

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#2303]
## Bug Description

Entering a title for a story is currently super slow in the editor, at least in development mode. It seems like changing the title causes re-renders all over the place.  In production mode it appears to be a bit faster though.

## Expected Behaviour

Entering the story title shouldn't cause lags.

## Steps to Reproduce

1. Open editor
1. Display FPS meter in dev tools
1. Set React dev tools to highlight updates
1. Type in a long story title, quickly

## Additional Context

- Plugin Version: `master`
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
@swissspidy can you confirm that this is still an issue? Perhaps it happens under special circumstances? I cannot recreate any lag whatsoever neither locally nor in production.

**Comment by swissspidy** [comment]
Can't reproduce anymore, closing.
