### ISSUE TITLE
Move alignment options above color presets

### ISSUE THREAD

**Issue by samitron7** [GoogleForCreators/web-stories-wp#2305]
Reasoning: I found myself using these options quite a bit for stories with image layouts and having the alignment options shift on me was disorientating.

**Comment by samitron7** [comment]
Let's move the alignment option to the top so that they aren't jumping and moving around on the users

![DesignPanel-Image (7).png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/e782a018-6dd5-483d-9e9d-435bb1e4828e)

**Comment by swissspidy** [comment]
The title of the issue is basically the testing instruction 🙂 
For details & testing, see #2620.

**Comment by csossi** [comment]
Verified in QA
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/a3e13927-8053-4ca6-a348-d77300f8110b)
