### ISSUE TITLE
Selection Box - Image doesn't seem to cover the selection box

### ISSUE THREAD

**Issue by samitron7** [GoogleForCreators/web-stories-wp#2307]
![Screen Shot 2020-06-08 at 8.44.29 AM.png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/0a222dff-bd3d-476d-ab0f-b5c91d6a20b2)

**Comment by merapi** [comment]
Saw that too. That image itself is "broken" (transparent strip on the left side).
![image](https://user-images.githubusercontent.com/21036224/84052549-0667e880-a9b1-11ea-8a30-50dc4d97e225.png)

**Comment by samitron7** [comment]
Ah - I didn't even noticed that! Went back and tried to see if I can duplicate this issue with other images and I was not so closing out this ticket. Thanks for tracking this down Marcin.

**Comment by swissspidy** [comment]
@merapi @samitron7 if this is an image from the template we should probably fix it in the templatte

**Comment by samitron7** [comment]
@swissspidy This image was grabbed from unsplash and it had a white edge on the left and that was what was causing the appearance that the selection box was larger than the image. This issue should be closed as it's a non-issue.
