### ISSUE TITLE
Upload preview and progress bar

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#231]
As a user uploading files, I want to see the upload progress and a preview of the file

[Feature Brief - Epic Media Gallery](https://docs.google.com/document/d/1aZH_TI_be2t5Ywyqx4jcPTPdhFGEt7xh-uLzBp2AV4A/edit#)
**[Design](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=2683%3A0)**

**Acceptance Criteria**
1. After media is dropped or pasted, it should show up instantly on the page and or media panel depending on where it was dropped (see #229 & #228 )
2. When the media is not uploaded immediately, the uploading UI is shown.
3. For every way of uploading except via upload button, media is in a special “local” mode before fully uploaded to the CMS.  In this mode, the user cannot:
- edit metadata
- publish the story (if the ‘local’ element is on a page)
- Use certain functions like auto-text-magic & eyedropper (in the case the resource is tainted / comes from another URL)
4. If paste / drag into page, a local version will be previewed on the canvas and replace when file is uploaded.

**Comment by spacedmonkey** [comment]
Making a progress bar with the [api-fetch](https://developer.wordpress.org/block-editor/packages/packages-api-fetch/) package is going to be hard, as it doesn't have a callback we easily use to tick progress. 

I have had a working idea, of using [api-fetch middleware](https://developer.wordpress.org/block-editor/packages/packages-api-fetch/#middlewares) and [axios](https://github.com/axios/axios) to make a [progress bar.](https://stackoverflow.com/questions/44936028/progress-bar-with-axios). I haven't done a tonne of research on this yet.

**Comment by spacedmonkey** [comment]
Before working on this ticket, we should tackle #435 . I believe this uploading files will need to be stored in state for a bit.

**Comment by spacedmonkey** [comment]
> ⚠️To ensure the media is placed at the top of the list, we will reset sort if necessary.

From this [doc](https://docs.google.com/document/d/1aZH_TI_be2t5Ywyqx4jcPTPdhFGEt7xh-uLzBp2AV4A/edit?usp=sharing).

**Comment by jauyong** [comment]
Please note paste is now handled in #761 . This ticket is for dragging

**Comment by spacedmonkey** [comment]
@pbakaus Product question, what is meant to be happen if an upload is in progress and the user navigates away from the editor? Also see #799

**Comment by pbakaus** [comment]
@spacedmonkey should produce a confirm dialog similar to when something hasn't been saved yet else where, e.g. "Your media is still uploading. Are you sure you want to exit and cancel?" or something along those lines.

**Comment by spacedmonkey** [comment]
I don't think it would be that different from solution in #799 . Whatever solution we make for that ticket, we should implement here for consistency.

**Comment by spacedmonkey** [comment]
Should be merge this as is with this confirm and follow up in another ticket?

**Comment by pbakaus** [comment]
I don't know what "as is" means but generally yes, as I'm a fan of "merge often, file new tickets to make up for it" :)

**Comment by spacedmonkey** [comment]
@pbakaus As is mean, As it currently is or In it's current state. 

This must be a British thing that I didn't know about.

**Comment by pbakaus** [comment]
@spacedmonkey oh I understood the words, just didn't know which PR you referred to and the specific functionality ;) #575? If so, then yes, please do.

**Comment by spacedmonkey** [comment]
See my comment here https://github.com/google/web-stories-wp/pull/575#pullrequestreview-383947425
