### ISSUE TITLE
Upload Error Handling - Snackbars Messages

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#232]
As a user I want to be informed when there are errors uploading my media files

[Feature Brief - Epic: Media Gallery](https://docs.google.com/document/d/1aZH_TI_be2t5Ywyqx4jcPTPdhFGEt7xh-uLzBp2AV4A/edit#)

**[Design - Error Handling](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=2731%3A7346)**

**Acceptance Criteria**
1. We will use the material design snackbars for error messaging: (https://material.io/components/snackbars/#usage)
2. Destructive actions or errors that require user input will require the dialog box: https://material.io/components/dialogs/ */
**[Design](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=2731%3A7346)**
3. Error type 1, Unsupported type. Only the following are supported: jpg, jpeg, svg, gif, png, webp, mp4, webm, or mp3
4. Error type 2, Upload size exceeded. This is dictated by the underlying CMS.
5. Error type 3, Other upload error. Uploads can fail for a myriad of reasons. Forward the message from the underlying CMS to the user and allow the user to retry if possible.
6. Unsupported type and limit size errors are errors that cause the media type to not be displayed on the editor (ie we don’t show the thumbnail in the editor).
7.

**Comment by spacedmonkey** [comment]
As discussed in the meeting, more and more [material UI ](https://material.io/develop/web/) elements are sneaking into this project. 

I have recommended using [material-ui](https://material-ui.com/), which implements the UI for react. Isn't officially supported by Google, but it is extremely popular.

**Comment by dvoytenko** [comment]
We could try it out for the error messaging. I'm not sure what that dependency involves and if it might conflict with our styled-components/themes. Does anyone know?

**Comment by spacedmonkey** [comment]
Upload errors are handled [here](https://github.com/google/web-stories-wp/blob/bd78a337298f08fc64734a1941a47f9d16ee7582/assets/src/edit-story/app/uploader/useUploader.js#L60-L67).

**Comment by spacedmonkey** [comment]
Related: https://github.com/google/web-stories-wp/issues/440 https://github.com/google/web-stories-wp/issues/196

**Comment by spacedmonkey** [comment]
I think we should look at [material-ui](https://material-ui.com/)'s [snackbars](https://material-ui.com/components/snackbars/)

**Comment by ndev1991** [comment]
@spacedmonkey This should build new material-ui snackbar like error handling components not using the material ui. correct?
