### ISSUE TITLE
Images added as different sizes when dragging vs clicking

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#2326]
## Bug Description

When you click to add an image to the page, it is added as one size.
Then if you drag the same image to the page, it is added as a larger size. 

## Expected Behaviour

It should be consistent. 

## Screenshots

https://xwp.slack.com/archives/CCCAUAH6F/p1591724046225200

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
We could scale images (and shapes) up when dragging starts to the same size they would have, if just placed by clicking - and we could potentially use an animation similarly to this:

https://twitter.com/siddharthkp/status/1273868440923713536

CC @samitron7, @pbakaus, @o-fernandez.

**Comment by merapi** [comment]
Drop behavior for images/video is in Figma now (added on Friday): https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=10064%3A0

**Comment by pbakaus** [comment]
yep that behavior sgtm.

**Comment by samitron7** [comment]
@barklund Get outta here, can we do that animation please. Once the thumb hits the page, animate the resizing.

And Marcin and I chatted about all this on slack and I updated Figma for all things related to sizing when added to page on Figma. Let me know if any additional tickets are missing figma links.
