### ISSUE TITLE
Color Presets Page Not working and Need to Gray Out Ones with Opacity

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#2328]
## Bug Description

1. Color preset should appear when you select a shape, text and page and it should be able to update the element's color  (right now, they don't work for the page. ie it doesn't update the page color when you select a color preset)
2. Any color swatches with opacity less than 100% has to be grayed out for the page

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA

**Comment by samitron7** [comment]
Verified in UAT for this issue

But note: @miina I commented on 2308 that when you select a text element, the same color options should show up. Currently that is not the case.
