### ISSUE TITLE
Generate the whole story in the JS

### ISSUE THREAD

**Issue by dvoytenko** [GoogleForCreators/web-stories-wp#233]
Currently we split the story generation between php and js code. Doing this in js only will make it less fragmented and more portable.

**Comment by swissspidy** [comment]
Would this be for just `<amp-story>` and its children, or also custom CSS?

One downside of generating the whole story is that one cannot change things like the publisher logo after the story has been saved, because it is an attribute of `<amp-story>`

**Comment by dvoytenko** [comment]
I was under the impression that this part doesn't change? I.e. we currently generate the whole story just ones when saved, right? To do something like changing a few metadata points, perhaps we should be simply replacing them in the ready HTML?

**Comment by swissspidy** [comment]
Sure, that would be a possibility.

I just had a look at the [list of supported attributes](https://amp.dev/documentation/components/amp-story/#attributes) again.

The publisher name & logo seems like the only field that could change independently of the story. Just replacing that in PHP should be easily doable.

So I'd say let's give it a try 👍
