### ISSUE TITLE
Media pane doesn't load a new page when scrolling to the bottom.

### ISSUE THREAD

**Issue by diegovar** [GoogleForCreators/web-stories-wp#2332]
## Bug Description

Media pane does not load a new page when scrolling to the bottom.

## Expected Behaviour

Media pane should load a second page.

Introduced in #2069

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Tested in PR#2314

Please clarify QA Instructions here. Currently, when I scroll down the media pane, I see the "loading" message and new images load - and it gets to a point where images seem to be repeating:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/c2007e04-0b22-4170-93e5-282cc3e5bb42)

**Comment by diegovar** [comment]
I think that's only because some people uploaded the same image many times
to the media library. So there's lots of duplicates.

**Comment by swissspidy** [comment]
Yes, there are tons of images uploaded multiple times:

<img width="1661" alt="Screenshot 2020-06-17 at 12 33 18" src="https://user-images.githubusercontent.com/841956/84887916-c41c6680-b096-11ea-8ead-117f464a71a0.png">

**Comment by swissspidy** [comment]
Verified this fix myself
