### ISSUE TITLE
Date Formatting: use WordPress settings

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#2334]
## Feature Description

This enhancement is applicable to both the dashboard as well as the editor. In both places we use [Moment.js](https://momentjs.com/) to format dates, or something custom.

Usage in the editor:

<img width="265" alt="Screenshot 2020-06-10 at 10 43 29" src="https://user-images.githubusercontent.com/841956/84246717-493bd480-ab07-11ea-9eb1-531a9d566fc5.png">

Another area is WIP in #2270, I already left a comment there.

Usage in the dashboard:

https://github.com/google/web-stories-wp/blob/dbb8da9fb65864992aab259e972ed177e6b40409/assets/src/dashboard/utils/getFormattedDisplayDate.js#L37-L45

Wherever we display dates we should not hardcode the format where possible. Two reasons:

1. Our apps need to work for users around the globe. `M/D/YYYY` only really works for folks in the US.
1. WordPress already solves this for us and provides us with localized date formats.

How it can be fixed:

```js

moment.format('LT'); // Display time in localized format.
moment.format('LL'); // Display date in localized format.
moment.format('LLL'); // Display date+time in localized format.
```

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Note: Long term we'll probably replace `moment` with a lean package like `date-fns` and `Intl.DateTimeFormat`, but for now it's important to have consistency here across the board and use what's already provided to us for free.

**Comment by carloskelly13** [comment]
@swissspidy This was pretty easy to do but there seems to be an open WordPress regression that prevents the usage of `LL` or `LLL`

https://github.com/WordPress/gutenberg/issues/12626

Like the ticket; we get F, j, then the year.
![Screen Shot 2020-06-19 at 3.14.07 PM.png](https://images.zenhubusercontent.com/5ea09bca6a44046f869bafe0/fb53db2d-78aa-4155-99f1-1590b91d6241)

It does however work correctly for the other settings and we get the correctly formatted date.

![Screen Shot 2020-06-19 at 3.15.54 PM.png](https://images.zenhubusercontent.com/5ea09bca6a44046f869bafe0/e181e2be-e35b-485c-9b30-a798cf595217)

![Screen Shot 2020-06-19 at 3.15.08 PM.png](https://images.zenhubusercontent.com/5ea09bca6a44046f869bafe0/3b6faa5c-bbcb-4ee3-aca7-d072ab08b542)

**Comment by carloskelly13** [comment]
I also noticed the 4th option returns ` 4/55/2020` for June 11. So something is definitely amiss with the locale dates and moment. I will look more into it.

**Comment by swissspidy** [comment]
Looks like WooCommerce worked around this by just falling back to `YYYY-MM-DD`: https://github.com/woocommerce/woocommerce-admin/pull/3516

And apparently I once filed a WordPress core ticket to improve Moment.js  localization: https://core.trac.wordpress.org/ticket/47373

If needed, we could override the localization done bee WP here:

https://github.com/WordPress/wordpress-develop/blob/6408e197bd7917d2c28490fc0815756ad208bed1/src/wp-includes/script-loader.php#L139-L166

Looking at https://momentjs.com/docs/#/customization/, the format expected by Moment.js is just way different than what WP provides.

See sections "Locale aware formats" and "Hour, minute, second, millisecond, and offset tokens"

**Comment by carloskelly13** [comment]
Yeah, I noticed they did YYYY-MM-DD too. Is that the preferred solution or do we want to override the localization by WP? I guess in other words, what is the new acceptance criteria for where we are?

**Comment by carloskelly13** [comment]
So I actually found a solution. The combination of `'dateFormat'   => get_option('date_format')` passing that to config and using the `format` function from `@wordpress/date` lets me correctly format Moment dates in JS using the WP format. Their JS package does the translation. The issue is that Moment uses mm for minutes while WP uses them for months which is why it looked like April 55th. It also handles the F, j too. I will have a PR up in the morning that should fix this.

**Comment by swissspidy** [comment]
Interesting!

Looking forward to the PR. We‘ll need to make sure that package is properly handled in webpack because of the license.

**Comment by carloskelly13** [comment]
Sounds good. I believe `@wordpress/dependency-extraction-webpack-plugin` takes care of that since the package is name spaced `@wordpress/*`.

**Comment by csossi** [comment]
Can QA Instructions be added here?

**Comment by swissspidy** [comment]
@csossi They are on the associated pull request, #2698. Copying here...

1. Visit `wp-admin/options-general.php` and change the date formatting
1. Hit save
1. Refresh the My Stories Dashboard View and see the new date formatting

**Comment by csossi** [comment]
Verified in QA
