### ISSUE TITLE
Broken status & visibility options

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#2337]
## Bug Description

Currently, the selected visibility is not blue, while the unselected ones are blue.

## Expected Behaviour

It should be the other way around.

## Steps to Reproduce

1. Create new story

## Screenshots

Here "Draft" should be selected, not the other two options:

![image (4)](https://user-images.githubusercontent.com/841956/84242025-8bade300-ab00-11ea-8ced-cc90d40fdc5b.png)

## Additional Context

- Plugin Version: `master`
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
This looks pretty confusing and broken, let's prioritize getting this in soon!

**Comment by csossi** [comment]
Verified in QA

![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/b12b748f-682d-43c2-9d28-7f474019503d)
