### ISSUE TITLE
Text: setting background color with multi-selection

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#2338]
## Bug Description

When two texts are selected and one of these has "Fill" as the background mode and the other not, the background color setting is still displayed -- it is also changed for both text elements, however, it is only visible for the element which has "Fill" set.

## Expected Behaviour

Not sure -- should the background color setting be hidden if not all the selected elements support it?

It should at least not change the default background color for the element that doesn't have "Fill" chosen.

## Steps to Reproduce

1. Add two text elements
2. Set "Fill" as background mode for one
3. Select both elements.
4. Now change the background color/opacity
5. See only one element visibly changing
6. Now change the background mode to "Fill" for the other element, too
7. See the default background color had changed meanwhile.

## Screenshots
![bg-issue](https://user-images.githubusercontent.com/3294597/84250311-2cee6680-ab0c-11ea-8f8e-44c70114cf5a.gif)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@o-fernandez Tagging you here since I'm not sure what should be the correct expected behavior from the product's perspective. Thoughts?

**Comment by o-fernandez** [comment]
I think this is OK for Beta. We should wait to get user feedback before prioritizing a fix for this.

**Comment by BrittanyIRL** [comment]
@miina  this feels relevant to the work on text prometheus is doing. I'm going to move it to prometheus but if that is wrong just pass it back.

**Comment by miina** [comment]
@BrittanyIRL Yep, this is for Prometheus, thanks for tagging!
