### ISSUE TITLE
Layer Panel: Dragging background displays indicators even though the bg can't be dragged

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#2339]
## Bug Description
When trying to drag the background element, it still shows visible drag indicators as if it would be possible, it's not though.

## Expected Behaviour
Drag indicators should not be shown for background element.

## Steps to Reproduce
1. Add a few elements
2. Try to drag the background in the layer panel
3. See the indicators visible.

## Screenshots
![dragging](https://user-images.githubusercontent.com/3294597/84251069-21e80600-ab0d-11ea-96bf-5015737cae1e.gif)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@barklund / @bmattb FYI Pulling this into 1.2 and Sprint 41.

**Comment by csossi** [comment]
Verified in QA

**Comment by samitron7** [comment]
Verified in UAT
