### ISSUE TITLE
Story menu out of the screen for a story card on the right edge

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#2340]
## Bug Description
In the “All Stories” view when opening the menu (e.g. to Delete the Story) for a Story that’s on the right edge, the menu gets hidden outside of the screen

## Expected Behaviour
The menu should always be visible.

## Steps to Reproduce
1. Go to All Stories
2. Ensure having enough stories to have one story on the right edge of the screen
3. Try opening the Story menu
4. See the menu hidden out of the screen

## Screenshots
<img width="230" alt="Screenshot 2020-06-09 at 19 06 16" src="https://user-images.githubusercontent.com/3294597/84251448-ac306a00-ab0d-11ea-8d05-251a84da4816.png">

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
This duplicates #2219

**Comment by miina** [comment]
Thanks! Tried to search but didn't see that one.

Closing as duplicate.
