### ISSUE TITLE
Tooltips: tooltip with longer text goes out of the screen

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#2343]
## Bug Description
When longer text is added to the tooltip, it stays on one line causing the tooltip to go out of the screen.

## Expected Behaviour
Tooltip should wrap the text instead to always stay within the borders of the viewport.

## Steps to Reproduce
1. Add a tooltip with longer text to something in the Design Panel
2. See the tooltip partially not visible.

## Screenshots
<img width="256" alt="Screenshot 2020-06-10 at 17 16 20" src="https://user-images.githubusercontent.com/3294597/84285938-57f1ae00-ab3e-11ea-8c17-f634ebd4a1a2.png">

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
cc @wassgha FYI -- in case this will be covered in #1931

**Comment by wassgha** [comment]
That's correct, it will be

**Comment by miina** [comment]
@wassgha I'm still seeing the issue with longer tooltips:
<img width="176" alt="Screenshot 2020-06-17 at 09 55 23" src="https://user-images.githubusercontent.com/3294597/84871393-c2e03f00-b080-11ea-8d97-953ba10579e9.png">

To reproduce:
1. Add shape color presets so that the last in the line would have opacity.
2. Now select the Page
3. Hover over the last preset: it should be grayed out and display the tooltip, however, part of it is outside of the screen.

**Comment by csossi** [comment]
Verified in QA
