### ISSUE TITLE
Disable story action items that are not usable

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#2344]
For beta we should disable story action items on the context men (vertical three dots) that aren't ready to be interacted with. These are create template and preview. Preview on hover of the story should also be hidden for release to avoid confusion.

**Comment by samitron7** [comment]
@BrittanyIRL "Preview on hover of the story should also be hidden for release to avoid confusion."

Is this hovering over the story cards in the dashboard and seeing your story play?

**Comment by BrittanyIRL** [comment]
@samitron7 - just the button that says 'preview' when you hover over a story - since that button doesn't do anything yet. 

so hover looks like this for now: 
https://user-images.githubusercontent.com/10720454/84297015-219a3b80-ab0a-11ea-81f9-e3a8222ed03a.png

**Comment by samitron7** [comment]
@o-fernandez Shouldn't you be able to preview your story using the story runtime preview here? It's just seems weird to not allow that.

**Comment by swissspidy** [comment]
Eventually yes, but it's not implemented yet, hence hidden. Or do you mean something else?

**Comment by o-fernandez** [comment]
Agree with @swissspidy if we have that ready to go then it'd be great, but if that's not something we can have implemented now, I'm ok doing it post Beta and hiding the button for now.

**Comment by swissspidy** [comment]
To be clear, hiding this button is exactly what this issue is about and has already been implemented and is now awaiting UAT.

**Comment by samitron7** [comment]
@swissspidy Ah ok, I thought it was implemented for some reason since we have it inside the editor.

Verified in UAT
