### ISSUE TITLE
Create template from story 

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#2347]
This ticket stems from #223 and is created to track the initial implementation of creating a template from a story only, not the rest of the feature work which is not part of this. Doing this now allows us to ask better questions about further implementation. 

What this does is test out the new API for templates that workspaces created to know that this works ahead of feature work. This includes the following acceptance criteria from #223 

2. When a user triggers “save as template”, we create a copy of the story (the original stays as it is) but as a template 
3. A user can “save as template” from any existing story in their dashboard, either published or draft.

Acceptance criteria 
- Ability to click 'create template' from a story and get a successful API response on your POST (`wp-json/wp/v2/web-story-template?_locale=user`

**Comment by csossi** [comment]
Any QA instructions to add here? Tested in PR#2310 - on clicking Create Template, nothing visible to use seems to happen. What am I checking in order to verify here?

**Comment by swissspidy** [comment]
@BrittanyIRL Everything here is behind a feature flag, no?

Per https://docs.google.com/document/d/1oZXjSJX30JLsIgCqOaER0Uff3Y_Tr-NCiQIfrYUnX9Y/edit, QA can be skipped until we remove the flag.

**Comment by BrittanyIRL** [comment]
yup! it's all hidden for now. think this got lost in the review shuffle. i'll make sure it gets merged here soon.
