### ISSUE TITLE
Dragging video by the controls (play button)

### ISSUE THREAD

**Issue by merapi** [GoogleForCreators/web-stories-wp#2351]
## Feature Description

Dragging from the middle (mouse down on play button) is causing playing - consider solution (and need) for different behavior.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
flagged that this is a challenge to implement, and as it currently exists, is by design. Also the workaround for this is pretty simple: grab the element from a location other than the onhover play button
