### ISSUE TITLE
'DELETE' method from '@wordpress/api-fetch' getting ignored

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#2352]
It appears that when we are using the `DELETE` method with wordPress's 'api-fetch' package it's getting ignored. It should show a request method of `DELETE` where it shows a `POST` (see delete story as an example) 

![84302795-cf7b0980-ab4d-11ea-9de5-42e3896f1393.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/5f0e5f31-4caa-4fb3-8f9e-fbbf5aa6774a)

See this PR for more context: https://github.com/google/web-stories-wp/pull/2330

**Comment by swissspidy** [comment]
That seems actually possible.
There should be a HTTP header telling that it‘s actually a DELETE or something.

Not all servers allow DELETE, hence this „masking“

**Comment by mariano-formidable** [comment]
I think we should make sure our data package is sending `force: true` for `DELETE` calls, but other than that I think our current code is doing it the same way the editor is 🤔

**Comment by swissspidy** [comment]
The header I was looking for is `X-HTTP-Method-Override`.

> I think we should make sure our data package is sending force: true for DELETE calls,

Not really. That is not needed. `force: true` is only needed when deleting media items in WordPress, nothing else.

**Comment by mariano-formidable** [comment]
> Not really. That is not needed. `force: true` is only needed when deleting media items in WordPress, nothing else.

Ha, even better, then it was all good in the first place 🎉
