### ISSUE TITLE
Hide container when no categories available

### ISSUE THREAD

**Issue by winterDroid** [GoogleForCreators/web-stories-wp#2365]

**Comment by diegovar** [comment]
@samitron7 If no categories are available (eg: because the API fails, or while they are loading), should we hide the categories section? Or do we reserve the space?

**Comment by samitron7** [comment]
If no categories are available, we should hide them but if they are loading, can we reserve a space large enough to fit "category loading" until it loads and I'll add this to the new visual design queue.

**Comment by diegovar** [comment]
If we reserve a space just for 'Category loading", this could introduce a jump when the categories finally load. Shouldn't we reserve the same space while the categories are loading and when they are displayed, so this doesn't happen?

Another alternative suggested by Marc is to load categories *and* media at the same time, and wait for both to complete before displaying anything (so if categories OR media are missing, we display a loading spinner or message). WDYT?

**Comment by samitron7** [comment]
sgtm. If categories take a long time to load (which hopefully they dont), we can do adjustments later.

**Comment by ezxyz** [comment]
@samitron7 just confirming that the jump is okay? Diego's comment was actually offering two different suggestions, so I'm not sure which is the one you wanted.

**Comment by ezxyz** [comment]
I've implemented the UI with the loading (and I can remove the loading if needed) Just need UX confirmation about which one we want to use.

**Comment by ezxyz** [comment]
@samitron7 I've added the simplest version of the categories fix in https://github.com/google/web-stories-wp/pull/3459  
![Loading categories - empty](https://user-images.githubusercontent.com/13947816/88497881-f65da400-d004-11ea-9d17-e916be96c429.gif)

Once that PR gets merged, it'll close the issue. Free to reopen this issue if you think there should be improvements.
