### ISSUE TITLE
Embed Block: Fix center alignment

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#2374]
## Bug Description

The block cannot be properly centered. Seems like some CSS is missing for that.

## Expected Behaviour

Center-aligning a block should work

## Steps to Reproduce

1. Insert block
1. Try to align center

## Screenshots

<img width="1105" alt="Screenshot 2020-06-11 at 18 08 32" src="https://user-images.githubusercontent.com/841956/84411398-935bad80-ac0e-11ea-9e18-402817d207ab.png">

## Additional Context

- Plugin Version:  `master`
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
I took a quick look into this, I think it is simple fix. By just adding `margin: auto` when `aligncenter` is present.

**Comment by swissspidy** [comment]
@spacedmonkey sounds promising! wanna take this on?

**Comment by swissspidy** [comment]
See #2465 for testing instructions

**Comment by csossi** [comment]
Verified in QA

Editor:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/96d06c03-e1e4-42fc-b254-01ab84232126)

FE:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/aec6da17-0a03-4fc1-b75c-c014f26ca3d8)
