### ISSUE TITLE
Dashboard: Backgrounds not coming through on preview cards

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#2375]
## Bug Description

The backgrounds are not visible on the preview cards.

## Expected Behaviour

Backgrounds should show up on preview cards.

## Steps to Reproduce

For older stories that haven't been updated in about a week, their backgrounds will not show up.

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
Previews are looking good for me in master, closing.
