### ISSUE TITLE
Embed block: clarify title requirement

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#2376]
## Feature Description

The embed block currently requires a title to be set, and otherwise displays nothing. This is because an `<a>` tag without content doesn't really make sense.

See https://github.com/ampproject/amphtml/blob/master/spec/amp-story-player.md for the spec.

Two big problems:

- The title requirement is not communicated as such in the editor
- On the frontend nothing is rendered if the title is missing

Possible solutions:

- Flag requirement in the editor
- Not making the title required.  
  (That would be bad for accessibility & SEO though.)
- On the frontend, show an error message for logged-in users, saying  "Missing title"
- Use  something like `Web Story` as a fallback  title.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

* Story should be displayed even if there's no title entered in the editor
* If no title is entered in the editor, a fallback title is used on the frontend

## Implementation Brief

* Add "Web Story" fallback title when rendering the block on the frontend

**Comment by csossi** [comment]
@swissspidy - previewed an embedded web story and seeing the following in Source:
			<amp-story-player
				style="width: 360px; height: 600px"
			>
				<a
					href="https://stories-qa-wordpress-amp.pantheonsite.io/stories/auto-draft-8/"
					style="--story-player-poster: url(https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/images/fallback-poster.jpg)"
				>
					Auto Draft				</a>
			</amp-story-player>

And FE looks like:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/1168562e-5589-4719-93ec-5e3fd3606b5f)

Should I be seeing "Web Story" somewhere here? Please advise if I'm misunderstanding the intent here

**Comment by csossi** [comment]
tested in PR #2415, btw

**Comment by swissspidy** [comment]
@csossi you should only see it in the page markup, not visible on the page

**Comment by swissspidy** [comment]
To clarify, you should only see "Web Story" in the markup when no other title has been added in the block sidebar.

Moving forward on the board since I just manually verified at https://stories-qa-wordpress-amp.pantheonsite.io/
