### ISSUE TITLE
Hide in progress template actions

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#2381]
Ahead of beta adding a flag to hide in progress template actions. This includes: sorting, filtering

**Comment by samitron7** [comment]
@BrittanyIRL Can you let me know what I should testing here? Just want to make sure I'm on the right page and testing the right thing.

**Comment by samitron7** [comment]
@BrittanyIRL Friendly poke!

**Comment by BrittanyIRL** [comment]
Sorry this totally got lost in my email! 

YES. So you should now see this: 
![Screen Shot 2020-06-18 at 9 13 59 AM](https://user-images.githubusercontent.com/10720454/85045632-14053700-b144-11ea-83b7-f108107cad21.png)

So the search and the filtering on templates that isn't done yet are hidden from view currrently. 

Do you think we should also hide the sort since that's not wired up?

**Comment by BrittanyIRL** [comment]
Went ahead and put up a quick PR to hide the sort as well, it was missed in the initial pass of this work to hide the in progress template actions. I'll let you know when that's done.

**Comment by BrittanyIRL** [comment]
ok, @samitron7  for UAT this just needs to verify that the explore templates page on dashboard now looks like this: 
![Screen Shot 2020-06-18 at 9 30 50 AM](https://user-images.githubusercontent.com/10720454/85061174-3b1b3300-b15b-11ea-94d1-7d81846f01cb.png)

(So no filters, search or dropdown)
