### ISSUE TITLE
Update state

### ISSUE THREAD

**Issue by joannag6** [GoogleForCreators/web-stories-wp#2393]
Store query string, search results, pagetoken in state
Add method to reducer to update state with new query [triggered on SearchBar onChange]
Add method to reducer to update state with search results

**Comment by cvolzke4** [comment]
There are be 2 parts of the state for search:
1. Local to the SearchBar widget.
2. In the react context state (media.media3p.searchTerm), updated with the setSearchhTerm() reducer action.

Note that as per go/story-editor-media3p-state, a call to setSearchTerm() will automatically trigger the 'fetch side-effect' and perform a re-fetch (search).

setSearchTerm() should be called when the user presses enter in the SearchBar.

Another option is to setSearcTerm on a debounce, but this should be avoided to avoid overwhelming providers until we know how many qps is expected.

**Comment by diegovar** [comment]
Closed as implemented as part of #2391
