### ISSUE TITLE
Dashboard: View Style Toggle shows wrong tooltip

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#2398]
## Bug Description

On the dashboard....

When I am on the grid view:

There's a button with the list-view icon, indicating that when I click on it, I get to the list view. However, hovering over the button says "Grid View"

For the list view it's obviously the other way around.

## Expected Behaviour

Instinctively, I expected the tooltip to tell me which view I'm going to activate, not the view I am on.

Also, I think the `aria-label` is more valuable when it describes the same. Pseudo code:

```js
if (layoutStyle === VIEW_STYLE.GRID) {
  ariaLabel = __('Switch to list view',  'web-stories');
} else {
  ariaLabel = __('Switch to grid view',  'web-stories');
}
```

## Steps to Reproduce

1. Open dashboard
1. Hover over view style toggle

## Screenshots

<img width="200" alt="Screenshot 2020-06-12 at 09 41 25" src="https://user-images.githubusercontent.com/841956/84478187-2c330d00-ac91-11ea-9b97-8fa509728613.png">

## Additional Context

- Plugin Version: `master`
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
I might be wrong, so curious to hear other thoughts on this

**Comment by carloskelly13** [comment]
That is a good point. I wonder if being even more clear like "Switch to Grid View" or "Switch to List View" is even better. Easy to change this to whatever people would like.

**Comment by swissspidy** [comment]
Yeah that makes sense 👍 

----

related: #2467

**Comment by samitron7** [comment]
Verified in UAT
