### ISSUE TITLE
Dark UI for Font Picker

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#2416]
## Feature Description

Restyle the new font picker to match the Dark UI in figma

https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=9388%3A1063

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

- The new font picker when enabled should be styled according to figma

**Comment by BrittanyIRL** [comment]
Hey Workspace team - Carlos is on holiday this week. Curious how you would like to handle this ticket. I am happy to take over the work on it but I have no context for the font updates happening so if one of you has capacity to take on this story please speak up. 

cc @miina @barklund @swissspidy

**Comment by BrittanyIRL** [comment]
Thanks @swissspidy  - that auto move to done gets me sometimes!

**Comment by o-fernandez** [comment]
This is in UAT, but I believe this is only in the new font picker, so testing is dependent on getting the new font picker merged? @BrittanyIRL @swissspidy can you confirm? 

Will add as a dependency for now.

**Comment by swissspidy** [comment]
Right, it‘s behind a flag. So UAT can be done once the flag is removed in a new ticket.
