### ISSUE TITLE
Enable the new Font Picker

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#2418]
## Feature Description

Enable the new Font Picker feature flag so it is visible by default, see Acceptance Criteria for details.

This is a combination of the following issues:

- [x] #2205 
- [x] #30
- [x] #1955
- [x] #2416
- [x] #1989
~- #3304~  

**[Product Brief](https://docs.google.com/document/d/1EQ12sD4a1plmMeBu7YMWOdUSg0FeegB9qi2_OlV3Tp0/edit#bookmark=id.pobjqyu57enf)**

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
- The new Font Picker is enabled, including font preview, search, and recent fonts.
- Karma tests for all these 3 features
- Please write QA Instructions for all the parts of the new Font Picker, too

## QA Instructions
See #3215

**Comment by miina** [comment]
Should this issue also perhaps include adding Karma tests for the new font picker? cc @barklund

**Comment by barklund** [comment]
> Should this issue also perhaps include adding Karma tests for the new font picker? cc @barklund

Yes please! And QA instructions for validating the entire font picker implementation (those QA instructions might serve as integration testing instructions too).

**Comment by BrittanyIRL** [comment]
Will figure out what all is left on this and depending on - dillon or I will take it.

**Comment by BrittanyIRL** [comment]
Update on this ticket: 
1955 is in review, owned by Barklund to be reviewed by Miina 
2415 in review, owned by Carlos/Brittany, to be reviewed by Barklund and Miina 

@barklund or @miina - do one of you want to own adding Karma tests and documentation to the font update since it's in the editor?

**Comment by miina** [comment]
> @barklund or @miina - do one of you want to own adding Karma tests and documentation to the font update since it's in the editor?

Sure, once the relevant issues have been merged 👍

**Comment by csossi** [comment]
"muli" is missing from the list noted at https://github.com/google/web-stories-wp/issues/1989

**Comment by miina** [comment]
Looks like "Muli" font [isn't pulled into the fonts list at all](https://fonts.google.com/specimen/Muli), it is marked in the curated list in the code though. We can probably merge the font-picker and investigate the Muli font issue separately if needed. cc @barklund

**Comment by miina** [comment]
Note: Looks like "Muli" was renamed to "Mulish" -- will replace.

**Comment by carloskelly13** [comment]
Nice catch on that Miina!

**Comment by samitron7** [comment]
IBM Plex Sans is missing from the list. Also this isn't part of the ticker but @wassgha @bmattb @barklund for the beta 2 cut we should make it a point to prioritize and fix the different styling for the dropdown

<img width="246" alt="Screen Shot 2020-08-13 at 9 57 59 PM" src="https://user-images.githubusercontent.com/10889431/90215375-4af87180-ddb0-11ea-8053-a373cc088205.png">

<img width="249" alt="Screen Shot 2020-08-13 at 9 57 52 PM" src="https://user-images.githubusercontent.com/10889431/90215379-4f248f00-ddb0-11ea-8a3f-0744b28ee222.png">

**Comment by swissspidy** [comment]
> IBM Plex Sans is missing from the list

I cannot confirm this. See:

<img width="304" alt="Screenshot 2020-08-14 at 10 37 17" src="https://user-images.githubusercontent.com/841956/90230672-2f29b580-de1a-11ea-9df3-08c3ef5283e2.png">

IBM Plex Sans is not on the  list of curated fonts shared at https://github.com/google/web-stories-wp/issues/1989#issuecomment-662253222

**Comment by swissspidy** [comment]
UAT feedback was added in https://github.com/google/web-stories-wp/pull/3215#issuecomment-673903589.

#4008 and #4009 were opened based on that.
