### ISSUE TITLE
Selection handlers should take precedence over page actions

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#2463]
## Bug Description

_Follow-up issue for #2042_

See comment: https://github.com/google/web-stories-wp/issues/2042#issuecomment-643923137

When an element is rotated outside of the page such that the handles are on top of any of the page actions of the left and right nav buttons, the selection box handles should take precedence. Currently that is not the case:
![image](https://user-images.githubusercontent.com/13389997/84662190-76aec680-aee9-11ea-955c-b6744feffcae.png)

Figma flow [here](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=9488%3A1796)

## Expected Behaviour

The selection box handles should take precedence.

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by dvoytenko** [comment]
@samitron7 Felt very strongly that the selection should NOT take precedence over the page menu. Could we just confirm this one more time quickly before making the change?

**Comment by samitron7** [comment]
Yes, if you're rotating and the element is off the page then want to resize, it's a pain to have to move the element back inside because it's conflicting with the page action. If the element is actively selected, the focus should go to it. We should close out this ticket.

**Comment by swissspidy** [comment]
> If the element is actively selected, the focus should go to it.

That's what this ticket seemingly wants to address, so why close it? 🤔

**Comment by o-fernandez** [comment]
Agree with @swissspidy and we can clarify, the point here is to keep the focus while the element is selected. If the element is not selected, then priority to page actions makes sense.

**Comment by miina** [comment]
@o-fernandez To confirm: should it take precedence over the Page carousel as well? Or just the Page actions?

**Comment by o-fernandez** [comment]
> @o-fernandez To confirm: should it take precedence over the Page carousel as well? Or just the Page actions?

See [Figma Flow here](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=9488%3A0)
The selection box should remain hidden/not be clickable once you get to the page carousel section, as that's technically outside the workspace.

**Comment by csossi** [comment]
Verified in QA - PR#2556

![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/0e954931-266b-4672-b9af-ba3554be4433)

**Comment by samitron7** [comment]
This should also include the page navigation. Currently, if the selection box controls are over the page navigation, I end up navigating the page instead of focused on what i need to do (ie, manipulate my element)

![Screen Shot 2020-06-29 at 11.03.28 AM.png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/169ec10e-aca5-4064-84f9-2947d5177386)

**Comment by miina** [comment]
Thanks for the information, created a new issue and closing this: https://github.com/google/web-stories-wp/issues/2814
