### ISSUE TITLE
Text color reverts to black when text in element is cleared

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#2466]
## Bug Description

I've set the text color to some custom color (e.g., white) but if I clear the text in the text box it all reverts back to black and I have to set the color black to my custom color. 

## Expected Behaviour

Expected the text color to remain the same unless I changed it. 

## Steps to Reproduce

1. Add text element
2. Change text color
3. Delete all text in text element

## Screenshots

![Text element color reverts to black when I delete all text](https://user-images.githubusercontent.com/13389997/84672974-20e11b00-aef7-11ea-8801-f048bf90593b.gif)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Looks like the same issue as #1774, which is also already in this sprint
