### ISSUE TITLE
Dashboard: allow deep-linking to list view

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#2467]
## Feature Description

_Follow-up to #1488_

Switching between the list view and grid view does not currently affect history.

Per https://github.com/google/web-stories-wp/issues/1488#issuecomment-644159292 we want to be able to directly link to the list view.

This enhancement requires two changes:

1. Enabling deep-linking to dashboard list view
1. Change backlink on the WordPress list table so it points to that list view

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
See comments here: https://github.com/google/web-stories-wp/issues/2074

**Comment by BrittanyIRL** [comment]
Per this comment here: 
https://github.com/google/web-stories-wp/issues/2074#issuecomment-654475139 

I'm closing this.
