### ISSUE TITLE
Lazy load image / video in media library

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#247]
As an editor I want to be able to browse all files in the media library

[Feature Brief - Epic: Media Gallery
](https://docs.google.com/document/d/1aZH_TI_be2t5Ywyqx4jcPTPdhFGEt7xh-uLzBp2AV4A/edit#)

**[Design](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=4638%3A1)**

**Acceptance Criteria**
1. The media tab in the Element panel shows all of the user’s videos and images in a virtual list that can be scrolled to the end (no matter how many elements are in the user’s library).
2. By default, the media gallery is sorted by upload date (“Most recent”), so that the most recently uploaded assets appear at the top. This sort order can be reversed with an action.
3. Lazy load should be used to satisfy optimal UX / performance
4. Users can use the arrow keys to navigate through the image elements and trigger elements to be displayed when reaching the bottom

**Comment by spacedmonkey** [comment]
I have used [echo lazy load ](https://github.com/toddmotto/echo) before. But it doesn't seem like is currently that well supported these days. Lazy loading images is easier than loading videos.

**Comment by dvoytenko** [comment]
In our case all lazy loads are images, right? We only load videos on focus/hover, so it's less lazy loading and more of a "action" loading.

**Comment by spacedmonkey** [comment]
As discussed in my meeting with @jauyong , I think this ticket should also include accessibility work, making sure users can use the arrow keys to view navigation through the image elements and trigger a elements to be displayed when reaching the bottom. I also believe we will need to use the [speak](https://github.com/WordPress/gutenberg/blob/4857ad58c1241b3d63d21a6880c989b85746c3dc/packages/a11y/src/index.js#L54-L70) api to announce new items.

**Comment by spacedmonkey** [comment]
I think this ticket can trackelled as part of #23 .

**Comment by dvoytenko** [comment]
The keyboard navigation and lazy loading seem mostly orthogonal to me. Why do we need entangle them here?

**Comment by dvoytenko** [comment]
/cc @merapi 

I reviewed the initial infinite scrolling pull requests. I definitely now think that keyboard navigation is completely separate from lazy loading, though may provide an additional signal for it. All the lazy loading issues are just as present for keyboard as mouse navigation here and are the result of scrolling semantics. Let's track separately. I seem to remember we initially wanted to track keyboard navigation with masonry layout.

**Comment by merapi** [comment]
Agree, keyboard navigation and layout are definitely dependent (and I have a tested solution there), lazy loading - separately.

**Comment by merapi** [comment]
The current infinite scroll with `loading="lazy"` is good for Alpha (we can adjust the pageSize [from 100 to 20-50 range] and rootMargin to load fewer images and sooner in unsupported browsers).

For the next version, we will combine layout https://github.com/google/web-stories-wp/issues/248 + visibility tracking to create a great experience (on top of that keyboard support will be added).

**Comment by spacedmonkey** [comment]
@merapi What is happening with this ticket? Should it be removed from the in progress column?

**Comment by merapi** [comment]
We were discussing it, thus "in review", but I think we can close it and will create another ticket(s) for Beta release with proper layout/keyboard/lazy/thumbnails split.
