### ISSUE TITLE
Templates: Update DIY template to 9:16

### ISSUE THREAD

**Issue by mariano-formidable** [GoogleForCreators/web-stories-wp#2470]
Use this Figma doc to apply 9:16 updates to the existing `DIY` template:
https://www.figma.com/file/RTzSw47oi6pEZXEfP2JoBo/Templates?node-id=766%3A61

**Comment by csossi** [comment]
Broken images appearing on final page:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/5c6056da-4db9-4eee-9260-261d8344dd10)

**Comment by mariano-formidable** [comment]
Re-generated template json, double checked the images, hopefully it's all working now:
![image](https://user-images.githubusercontent.com/40646372/85906551-810f7100-b7c3-11ea-9d71-c14401071c5d.png)

**Comment by csossi** [comment]
Thanks, @mariano-formidable - iamges appearing now

There looks like there are quite a few differences between what I'm seeing in QA and the direction in figma. Figma has:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/55c906bd-0d31-418a-b295-93f37c83f6a1)
For example, 
- opacity differences
- looks like page attachments and social media links should be removed

**Comment by mariano-formidable** [comment]
It looks like you were reviewing the `Fitness` template, but this story is to update the `DIY`.  The cover image for `DIY` is this:
![image](https://user-images.githubusercontent.com/40646372/86058987-b8299080-ba16-11ea-9c8a-eecb2836ff58.png)

**Comment by csossi** [comment]
Ugh - sorry about the DIY confusion, @mariano-formidable 

Verified in QA

**Comment by samitron7** [comment]
Verified in UAT

@o-fernandez  Overall looks decent but some minor improvement on line spacing and text width post beta (ie, the "for" text is really hanging out there"

![Screen Shot 2020-06-30 at 12.42.33 PM.png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/bbad53cc-1916-4240-8422-c31b1ebc7ea4)

**Comment by o-fernandez** [comment]
Filed this follow-up bug for the item Sam mentioned. https://github.com/google/web-stories-wp/issues/2872
