### ISSUE TITLE
Templates: Update Fashion template to 9:16

### ISSUE THREAD

**Issue by mariano-formidable** [GoogleForCreators/web-stories-wp#2471]
Use this Figma doc to apply 9:16 updates to the existing `Fashion` template:
https://www.figma.com/file/RTzSw47oi6pEZXEfP2JoBo/Templates?node-id=766%3A61

**Comment by maxyinger** [comment]
https://github.com/google/web-stories-wp/pull/2577

**Comment by csossi** [comment]
Tested in PR#2577

Social icons still appearing on final page:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/aafdb3ff-9858-4812-a2f1-3aa238d383ed)

**Comment by mariano-formidable** [comment]
The social icons have been removed, and a 4th image added.  However, because QA isn't updated with new images unless they're merged into master first, the 4th image on the final page of the template might appear broken during your test, but it is working and will appear when merged:
![image](https://user-images.githubusercontent.com/40646372/86058716-2c176900-ba16-11ea-8a3c-574adb899354.png)

**Comment by csossi** [comment]
Tested in PR#2577 - Win10/Chrome
