### ISSUE TITLE
Templates: Update Cooking template to 9:16

### ISSUE THREAD

**Issue by mariano-formidable** [GoogleForCreators/web-stories-wp#2472]
Use this Figma doc to apply 9:16 updates to the existing `Cooking` template:
https://www.figma.com/file/RTzSw47oi6pEZXEfP2JoBo/Templates?node-id=766%3A61

**Comment by csossi** [comment]
Image missing:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/aa6a07cb-c4d0-4e8e-a26b-d00cc59aabae)

**Comment by mariano-formidable** [comment]
Okay, I re-generated the template json and double checked that all the images are properly rigged and are part of the repo soooo hopefully they should all show up:
![image](https://user-images.githubusercontent.com/40646372/85905645-c8483280-b7c0-11ea-8efc-ebb33036c279.png)

One thing to note, if you've created a story from a template by clicking on "Use Template", that story will _not_ be updated with updates to the source template.  To view the latest versions of the templates be sure to go to "Explore Templates".

**Comment by swissspidy** [comment]
What just came to mind:

Because of file size, we currently load all template assets from our GitHub pages „CDN“. That only uses what‘s in master though...
So if a PR adds new template images, those can‘t be seen on the QA site because they‘re not on master.
I initially thought of this as a rather rare case, but it seems like I should expedite work on this.
I‘ll tackle this ASAP.

**Comment by mariano-formidable** [comment]
> What just came to mind:
> 
> Because of file size, we currently load all template assets from our GitHub pages „CDN“. That only uses what‘s in master though...
> So if a PR adds new template images, those can‘t be seen on the QA site because they‘re not on master.
> I initially thought of this as a rather rare case, but it seems like I should expedite work on this.
> I‘ll tackle this ASAP.

That totally must be what's happening, nice catch!

**Comment by csossi** [comment]
image not appearing:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/d1cb6cb0-6714-422c-a16c-21660c4e8c6f)

**Comment by swissspidy** [comment]
Probably because of https://github.com/google/web-stories-wp/issues/2472#issuecomment-650440917

If the template is otherwise fine, and works locally, I would suggest marking this as QA-passed.
