### ISSUE TITLE
Templates: Update Fitness template to 9:16

### ISSUE THREAD

**Issue by mariano-formidable** [GoogleForCreators/web-stories-wp#2473]
Use this Figma doc to apply 9:16 updates to the existing `Fitness` template:
https://www.figma.com/file/RTzSw47oi6pEZXEfP2JoBo/Templates?node-id=766%3A61

**Comment by csossi** [comment]
Tested in QA envronment - PR#2628

Some broken images appearing:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/0171d85e-8cc2-426b-b467-b1dbe17c7c4c) ![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/bb982cc6-d600-407f-a532-4d6f47b77d4c)

Invalid character appearing:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/889087ab-7314-4509-9cf7-3d5091f37ef0) ![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/4c5a6dd6-0b49-4de7-b1af-6f8386fe851f) ![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/7f20a3b9-a89a-400a-903b-db08b9afff3d)

Some pages have this notation re: bg:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/9c44dc4f-ab1a-400d-afae-b03adcc1a81c) ![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/b411dcdd-21e3-4d42-851b-b633171436d5) ![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/55fb3ec9-fe81-4a7d-840b-d6984d4626da)

**Comment by mariano-formidable** [comment]
The missing images have been merged into master, so they should start appearing in the QA environment.

**Comment by csossi** [comment]
Thanks, @mariano-formidable - images now appearing fine!

But I'm still seeing that odd character on some pages (as described earlier) - for example:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/21569c36-de65-482e-8efc-c7cd8147f3f9)

**Comment by swissspidy** [comment]
I can confirm that. Was lazy and used https://www.soscisurvey.de/tools/view-chars.php to display hidden characters and saw this:

<img width="440" alt="Screenshot 2020-06-30 at 10 41 12" src="https://user-images.githubusercontent.com/841956/86104374-3ee57880-babe-11ea-98e7-7decd5db29bd.png">
<img width="1053" alt="Screenshot 2020-06-30 at 10 42 34" src="https://user-images.githubusercontent.com/841956/86104511-6ccabd00-babe-11ea-984c-98273700a1aa.png">

`U+2028` is a `line separator` character.

Let's make sure we get rid of it.

**Comment by mariano-formidable** [comment]
Okay, I fixed the hidden character problem across all the pages that they appeared 👍

**Comment by csossi** [comment]
Verified in QA

**Comment by samitron7** [comment]
Failed in UAT

1. We need to swap out the watch image. This one still has the nike and apple logo
![Screen Shot 2020-06-30 at 1.02.12 PM.png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/3d611442-4bf8-48a8-a722-298a448acc77)

2. We need to move text and button over. As is the button is too far inside the story navigation zone
![Screen Shot 2020-06-30 at 1.00.11 PM.png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/eef54dcc-ac14-4b6f-a409-0b0f175150f7)

**Comment by mariano-formidable** [comment]
@samitron7 I've fixed both issues you found.  The template is ready for re-UAT.

**Comment by samitron7** [comment]
Verified in UAT
