### ISSUE TITLE
Templates: Update Beauty template to 9:16

### ISSUE THREAD

**Issue by mariano-formidable** [GoogleForCreators/web-stories-wp#2476]
Use this Figma doc to apply 9:16 updates to the existing `Beauty` template:
https://www.figma.com/file/RTzSw47oi6pEZXEfP2JoBo/Templates?node-id=766%3A61

**Comment by csossi** [comment]
Broken images on page 1:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/3a92c75c-dba8-4cc0-b44c-d480dfb14f95)

**Comment by mariano-formidable** [comment]
Okay, the broken image should be fixed!

**Comment by samitron7** [comment]
Verified in UAT
