### ISSUE TITLE
Templates: Update Wellbeing template to 9:16

### ISSUE THREAD

**Issue by mariano-formidable** [GoogleForCreators/web-stories-wp#2477]
Use this Figma doc to apply 9:16 updates to the existing `Wellness` template:
https://www.figma.com/file/RTzSw47oi6pEZXEfP2JoBo/Templates?node-id=766%3A61

**Comment by csossi** [comment]
See figma - https://www.figma.com/file/RTzSw47oi6pEZXEfP2JoBo/Templates?node-id=766%3A61

The "blob outlines" referenced in figma (across multiple pages) isn't present on the qa site For example, there should be one here:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/b7f8bcdd-273a-47a7-80e2-29be74152ac2)

Also still seeing page attachment here:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/03d847e8-4629-487c-8b61-5e1884f0d12b)![image.png]
And social links should be removed:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/5de03a77-e61b-4347-b957-d4d40925a8df)

**Comment by mariano-formidable** [comment]
Okay the pages should be fixed!

**Comment by csossi** [comment]
Verified in QA - PR#2659
