### ISSUE TITLE
Display plugin version number in editor

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#2501]
## Feature Description

On the dashboard we already display the plugin version in the bottom right corner.

Can we find a similar spot in the editor? This way users could easily see which version they're on & copy it when making support requests.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
![image.png](https://images.zenhubusercontent.com/5e98486db524b82fc96aeaf6/aa3b93c7-420b-4c48-a33d-eae1a95fd292)

Simplistic, but I'd imagine this can just be put in the workspace's empty area, maybe bottom left corner in that area, to the right of the elements panel? 

@samitron7 are you OK with this?

**Comment by samitron7** [comment]
For support request, I'm assuming we don't yet have a way to provide feedback within the editor and therefore automate attachment of the version.

If this is temporary, I think this is fine as long as we can keep the text to a minimal like [this](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Stable-Release?node-id=1%3A83256)

**Comment by swissspidy** [comment]
It's probably not urgent as long as we have the version number in the dashboard

**Comment by csossi** [comment]
Verified in QA
