### ISSUE TITLE
Learn More Dialogue

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#251]
As an editor I want to be able to learn more about the background fill behaviours. 
This is a follow up from #18 

**Acceptance Criteria**
1. After clicking the "Learn More" the dialogue should pop up
2. The user is able to click OK to close the dialogue

**[Design](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=2765%3A8225)**

**Comment by spacedmonkey** [comment]
This dialogue use a [material design](https://material.io/) [dialog](https://material.io/components/dialogs/#). As of https://github.com/google/web-stories-wp/issues/232#issuecomment-583399629. 
>  I have recommended using material-ui, which implements the UI for react. Isn't officially supported by Google, but it is extremely popular.

**Comment by miina** [comment]
@pbakaus To confirm: is this in Sprint 23 even though it's now a P1?

**Comment by spacedmonkey** [comment]
@pbakaus @jauyong I think the same dialog created for this ticket can be used for #354 . Meaning the size is much smaller

**Comment by pbakaus** [comment]
If the size is much smaller, let's get it in. Otherwise let's move to next sprint.

**Comment by jauyong** [comment]
Thanks @spacedmonkey 
Per Paul's message above, if this dialog is reused for #354 do you think we can get both done this sprint? Otherwise I'll add a label to get #354 in Sprint 25.
CC: @kmyram

**Comment by jauyong** [comment]
@pbakaus also want to check in regarding Miina's note that this is a P1 and in this sprint...Should this be moved out of the sprint?

**Comment by pbakaus** [comment]
@jauyong as mentioned before, if the work is very small, we can put it into this sprint. Otherwise moved it out.

**Comment by wassgha** [comment]
Since I made #706 for links, I'll do this as well
