### ISSUE TITLE
Create [PRE]APPEND_MEDIA action to add uploaded media instead of SET_MEDIA

### ISSUE THREAD

**Issue by cvolzke4** [GoogleForCreators/web-stories-wp#2513]
## Task Description

Today, local media uses SET_MEDIA to set the entire media list when uploading media. This is bad practice, as uploading media becomes an n^m operation (n=images uploaded, m=list size), and may be prone to race conditions. A better approach would be have an action that adds the uploaded media to the list.

**Comment by diegovar** [comment]
According to the react developer tools, when a new page is loaded the existing media elements are not rerendered. Is this really necessary then?

**Comment by cvolzke4** [comment]
> According to the react developer tools, when a new page is loaded the existing media elements are not rerendered. Is this really necessary then?

This is actually for locally uploaded media. I've updated the description.

I think this is still worth doing for tech debt reduction. Consider when scrolled past 10,000 media resources, and then uploading 100 more by dragg/drop. This is now an n^2 operation, where 100 * 10,000 media resource entities have to be moved around, because each 100 individual uploads re-assigns the entire media list.

**Comment by swissspidy** [comment]
A `prependMedia` reducer now exists since #6541
