### ISSUE TITLE
Implement proper library tabs

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#252]
Implement proper library tabs by:

- [x] Add correct design and icons
- [x] Add quick-navigation to add a new text element
- [x] Add arrow navigation support when focus is on any tab (any tab will auto-select on focus, so you can't have a focused tab be not selected, which makes ui simpler)
- [x] Add (only currently) selected tab to tab order (technically remove non-selected tabs from tab order)
- [ ] Add global shortcut to quickly focus currently selected tab

**Comment by barklund** [comment]
FYI: I'm going to build this PR off of @dvoytenko's work in #320 expecting it to be merged soon, as I'm going to need the shortcut stuff for this.

**Comment by jauyong** [comment]
I spoke with Sam and she said she'll be adding info for the text shortcuts to the designs later today.
