### ISSUE TITLE
Use wp-env package for Docker environment

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#2521]
Right now we use a customized Docker environment that we already used back in the AMP plugin, and originates from Gutenberg.

By using the [`@wordpress/env`](https://www.npmjs.com/package/@wordpress/env) package for our Docker environment, which is an evolution of it, we can greatly reduce maintenance burden for ourselves.

It should also make it easier to test various combinations of WordPress versions and the like.

**Comment by swissspidy** [comment]
So I did a quick experiment for this: #2589.

Some issues / questions:

* Code coverage for unit tests does not seem to be possible, e.g. using XDebug (https://github.com/WordPress/gutenberg/issues/20636)
* How can I run unit tests against WP trunk?
* How can I run unit tests on PHP 5.6?

**Comment by rheinardkorf** [comment]
Still have those same questions/issues. 😄  Right now it is keeping me to custom environments, but would love to use an official approach.

**Comment by spacedmonkey** [comment]
Related: https://github.com/WordPress/gutenberg/pull/22613

**Comment by swissspidy** [comment]
So apparently 

> So I did a quick experiment for this: #2589.
> 
> Some issues / questions:
> 
> * Code coverage for unit tests does not seem to be possible, e.g. using XDebug ([WordPress/gutenberg#20636](https://github.com/WordPress/gutenberg/issues/20636))
> * How can I run unit tests against WP trunk?
> * How can I run unit tests on PHP 5.6?

So apparently these all seemed to be fixed?

**Comment by swissspidy** [comment]
Closing for now; we can reopen once all the remaining blockers are resolved upstream
