### ISSUE TITLE
Story saved pointing to "blob" URL, causing video to fail loading in story

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#2547]
## Bug Description

For [this story](https://stories-new-wordpress-amp.pantheonsite.io/stories/bokunostory/) the background video in page one was saved using an incorrect blob url. Per @swissspidy 's review this is the markup: 
`<amp-video autoPlay="autoplay" poster="blob:https://stories-new-wordpress-amp.pantheonsite.io/13a6604b-2b51-4a6e-b4e6-7d0eceec4bf4" artwork="blob:https://stories-new-wordpress-amp.pantheonsite.io/13a6604b-2b51-4a6e-b4e6-7d0eceec4bf4" title="Bridge In Place" alt="Bridge In Place" layout="fill" id="el-5aff6cbd-9252-4e9d-a532-969cbde98f1a-media"><source type="video/mp4" src="blob:https://stories-new-wordpress-amp.pantheonsite.io/491491bd-b975-46b1-b337-5561e134bdce"/></amp-video>`

Also from Pascal: "See the blob: thing. That means the video & images were probably still uploading at the  time the story was saved, Of course a blob: URL isn’t really valid, hence the video fails to play"

## Expected Behaviour

Story should be saved with the proper video URL, no blobs.

## Steps to Reproduce

1. Drag a video onto canvas to upload while creating story
2. While video is uploading, save story/autosave? 

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
Here's another story where I can seem to repro (see page two [here](https://stories-new-wordpress-amp.pantheonsite.io/stories/new-story/))

I repro'd by just creating a story and saving/previewing while I was working and dragging video to the canvas to upload and use in the story. Unsure of the specific steps that led to the broken video in page 2, but not in page 1, but I reproduced the issue quickly.

**Comment by swissspidy** [comment]
Since it seems so easy to reproduce, I suppose we can start asking what should ideally happen in this case.

First and foremost, I'd say saving and previewing should never ever result in `blob:` URLs in markup. We need to avoid that. But what should we output instead? Placeholders? Nothing?

Then, we might want to think about some UX changes to prevent this from happening in the first place.

For example, we could just disable all those actions (save/preview/publish) while upload is in progress.

Or, when you click on those buttons, they'll just wait for the upload to finish before doing anything.

**Comment by swissspidy** [comment]
> For example, we could just disable all those actions (save/preview/publish) while upload is in progress.

Seems like this is already in place! But only for the publish button, not the preview button.

**Comment by merapi** [comment]
When clicking Preview we will:
```js
// Save story directly if draft, otherwise, use auto-save.
const updateFunc = isDraft ? saveStory : autoSave;
```
that means the blob url will be persisted in the DB either way.

Should we disable the Preview button while something is uploading? (like Save/Publish buttons)
There are other solutions to this (e.g. save the story with blob url and update it after the upload is done) but require a lot more effort and can create more issues to solve.

**Comment by swissspidy** [comment]
Yeah, as a first measure for beta we should just disable the Preview button during uploads. At least in my opinion.

I like some of the other options above too, but we can follow-up on those post-beta.

**Comment by dvoytenko** [comment]
@swissspidy @miina Disabling Preview (and maybe Save) until upload is done is a good idea. But we also need to disable auto-save, right?

**Comment by swissspidy** [comment]
Yep, good point 👍

**Comment by merapi** [comment]
Right, I will also disable autosave while uploading (other buttons are already disabled).

BTW: Autosave is relying on hasNewChanges which will be true if you just e.g. select any element (doesn't change story_data), this should be based on comparison between last story_data and current story_data, right?

**Comment by swissspidy** [comment]
> BTW: Autosave is relying on hasNewChanges which will be true if you just e.g. select any element (doesn't change story_data), this should be based on comparison between last story_data and current story_data, right?

Yeah, that sounds like a bug then. Mind filing an issue?

**Comment by miina** [comment]
@merapi `hasNewChanges` definitely doesn't seem to (or shouldn't) be `true` when just selecting a new element when I'm testing. Can you file an issue with steps to reproduce?

EDIT: E.g. the "Save draft" button is enabled only if `hasNewChanges`, however, it continues being disabled when just clicking through elements. Does it work differently for you?

**Comment by merapi** [comment]
@miina testing main branch, `hasNewChanges` is `true` after I select something.
https://drive.google.com/file/d/1ZePEpYtQvUGyF0UueZgaYG9izuiyciFM/view?usp=sharing

**Comment by miina** [comment]
> @miina testing main branch, hasNewChanges is true after I select something.

Hmm, okay, this seems to happen only in case of Media -- looks like selecting media is creating a new history entry for some reason (`hasNewChanges` is tracking new history entries compared to the saved version) -- e.g. you can see the Undo becoming active as well. Looks like there's something updating Media when selecting it even though nothing is actually changing, seems like a regression/bug indeed.

Edit: we should create a bug issue for "Selecting Media creates a new history entry" or sth similar.

**Comment by csossi** [comment]
Testing Instructions missing

**Comment by swissspidy** [comment]
@csossi see #2604 for instructions

**Comment by swissspidy** [comment]
Copying them here for visibility:

> Try to save/preview the story (open Preview tab and check if the story is updated there) while something is uploading - you shouldn't be able to do it.

I'd like to add to this:

> Observe the Network tab in dev tools and verify no autosave request is made while something is uploading

So basically:

Upload media -> verify that you cannot manually save the story while upload is in progress (i.e. disabled buttons)

**Comment by csossi** [comment]
Verified in QA

Button disabled when in mid-upload:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/d4272b35-50b0-4e39-ba6c-e2be18996c6f)

**Comment by merapi** [comment]
> Verified in QA
> 
> Button disabled when in mid-upload:
> ![image.png](https://camo.githubusercontent.com/17cbee1915e5891764d42c965ced0f590ad00cae/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3565613038356534373034653732633061393963363939372f64343237326233352d353062302d346533392d626136632d653262653138393936633666)

Not sure why, but the Preview button is enabled on your screenshot (should be disabled because it saves the story when clicked). Maybe just a wrong branch on QA env?

**Comment by swissspidy** [comment]
I verified that it is actually disabled
