### ISSUE TITLE
Update dashboard page preview to 9:16 + fullbleed

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#2557]
We need to update the page ratio on preview components in the dashboard (grids and detail views) to be 9:16 instead of 2:3. We also need to take into consideration the fullbleed/dangerzone area of the stories and show that. Using `edit-story/components/canvas/layout` as a reference for the updates done to the containers that hold the displayElement component that the dashboard references from edit-story to determine necessary updates on the dashboard end. 

Acceptance criteria: 
- Updated aspect ratio on stories to be 9:16 + fullbleed height added to top and bottom.

**Comment by samitron7** [comment]
Verified in UAT
