### ISSUE TITLE
Install PHPStan locally

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#2561]
## Feature Description

Install PHPStan locally and make it part of git hook / lints that run locally. This means that a developer does not have to submit the code to github before seeing this output of this tool. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
We can probably copy how ampproject/amp-wp does it.

**Comment by spacedmonkey** [comment]
> We can probably copy how ampproject/amp-wp does it.

I believe that don't install PHPStan locally as PHPStan-WordPress requires PHP 7.1. I think that is not a issue for us.

**Comment by swissspidy** [comment]
PHPStan-WordPress only requires what PHPStan does, no?

But we'll see it when we get there 👍

**Comment by spacedmonkey** [comment]
You are right, both of them require 7.1. 
https://github.com/phpstan/phpstan/blob/master/composer.json#L6
https://github.com/szepeviktor/phpstan-wordpress/blob/master/composer.json#L14

As WordPress core requires 7.2, I don't think that is a problem.

**Comment by swissspidy** [comment]
WordPress still supports 5.6, 7.2 is just the recommendation. See:

https://github.com/WordPress/wordpress-develop/blob/2cb1a61c69cedb24f4391531e50d67f0be477579/composer.json#L13

And we do so too:

https://github.com/google/web-stories-wp/blob/63ef3c3ff8808c141011d234c66772ceee73420f/composer.json#L8
