### ISSUE TITLE
Make it easier to run PHP unit test locally

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#2562]
## Feature Description

Currently to run PHP unit tests, it requires PHP and MySQL to be setup currently on developers local machine. For many of the developers on this project, these will not be setup. 

WordPress core now run's it unit tests in inside the docker containers. See this [line](https://github.com/WordPress/wordpress-develop/blob/master/package.json#L163). 

Related: https://github.com/google/web-stories-wp/issues/2521

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Should this be blocked by #2521?

**Comment by swissspidy** [comment]
Maybe later
