### ISSUE TITLE
Clarify mouse and keyboard behavior on the compact mode of the page carousel

### ISSUE THREAD

**Issue by dvoytenko** [GoogleForCreators/web-stories-wp#2575]
## Feature Description

We have two modes of the carousel: expanded and compact. Expanded mode shows the page previews, while the compact only shows white lines. The keyboard and mouse behavior are obvious and well-defined for the expanded mode, but with the collapsed mode is less obvious.

For instance, consider the following questions for the compact mode:

1. Should user be able to click into the carousel and use ↔️ keys to navigate between pages.
2. Should user be able to use mod+↔️ to reorder pages.
3. Should user be able to use mouse to drag-reorder pages.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
Irrelevant as the compact carousel indicator doesn't exist anymore.
