### ISSUE TITLE
Color Presets: Text, Shape, Page should all share the same color presets

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#2585]
## Bug Description

Currently, the Text color presets are separated from the shape and page presets.

## Expected Behaviour
- Text, Shape, Page should share the same color presets
- When a preset includes gradient, it's grayed out and with a tooltip explaining that Text color can't have gradient.
- Text presets are for the text only, not for the Text background.

## Steps to Reproduce
1. Add a text element and a shape.
2. Click on the shape, add a preset.
3. Now click on the text -- the preset added via shape is not visible.

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA - tested in PR#2598

**Comment by samitron7** [comment]
@miina I'm able to set a page bg color that contains an opacity.

**Comment by miina** [comment]
@samitron7 Could you please write the steps / add a video to show how?
Steps that I followed:
1. Add a color preset to Text which includes opacity.
2. Now select background instead
3. Try to click the color preset which had an opacity
4. Nothing is happening -- it's not possible.

Also tried the same with a shape background gradient including opacity, doesn't seem to be possible, as expected
![bg-color](https://user-images.githubusercontent.com/3294597/85990326-227c0a00-b9f2-11ea-8e58-cd89bf0d4375.gif)

**Comment by samitron7** [comment]
1. Remove all the color swatches in the saved colors section
2. Add a shape and apply a gradient to it. Add to color preset
3. Select the page bg and click on the new color with opacity. You'll see that you can add that color to the page

![Screen Shot 2020-06-29 at 8.51.26 AM.png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/75001b2c-e909-4fcd-8f28-4dffbd9a11c7)

**Comment by miina** [comment]
Thank you, can reproduce now, will create a new issue for it for beta.

**Comment by samitron7** [comment]
@miina Should I move this ticket to done and comment that it failed and you created a new ticket?

**Comment by miina** [comment]
Yes, I should have done it myself after creating a new ticket.

New ticket: #2811 

Closing to follow up in the new issue.
