### ISSUE TITLE
Color Presets scrollbar shifts everything on the Design Panel

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#2586]
## Feature Description
When there are enough color presets to create a scrollbar, the scrollbar shifts everything on the design panel.

The scrollbar should be adjusted not to shift the items on design panel.

Follow-up to https://github.com/google/web-stories-wp/issues/2308, see https://github.com/google/web-stories-wp/issues/2308#issuecomment-645817738

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment]
@miina this is what I see, what's the issue here? 

![color-presets-scroll](https://user-images.githubusercontent.com/5874851/85054762-8db01b80-b16a-11ea-8d2c-49929364b7dc.gif)

**Comment by swissspidy** [comment]
> what's the issue here?

The second scrollbar.

When you now remove a few presets (or just one?), the second scrollbar disappears and there seems to be a jump/shift happening.

**Comment by swissspidy** [comment]
Maybe this helps:

<img width="279" alt="Screenshot 2020-06-19 at 10 19 51" src="https://user-images.githubusercontent.com/841956/85112762-7169b880-b216-11ea-846f-c9f1bc002ed4.png">

<img width="278" alt="Screenshot 2020-06-19 at 10 19 43" src="https://user-images.githubusercontent.com/841956/85112758-70388b80-b216-11ea-8d00-32d5f53a5eac.png">

See how the circles are closer together on the bottom screenshot

**Comment by miina** [comment]
Was just about to add some screenshots but looks like you already did it, thank you, @swissspidy!

Note: the issue was created based on Sam's note (link is in the description), here is the original note:
> This one is minor but because of the scrollbar, when I select a any element then the page, color swatches (and really everything on the panel) shifts a bit.

The shift can also be seen when resizing the panel:
![shift](https://user-images.githubusercontent.com/3294597/85113470-a1658b80-b217-11ea-93be-a508b8760114.gif)

**Comment by swissspidy** [comment]
From #2620:

<img width="838" alt="Screen Shot 2020-06-19 at 11 13 51 AM" src="https://user-images.githubusercontent.com/841956/85264528-1bdd1800-b471-11ea-9b40-8fd4ec124a4f.png">

2 & 3 need to be done.

**Comment by miina** [comment]
Note: this should get fixed together with #1858, moving to In Progress.

**Comment by barklund** [comment]
@Miina, was this fixed as part of #1858 as mentioned or is it still an issue?

**Comment by miina** [comment]
Still an issue -- #1858 was closed unresolved since the browser design didn't work well in the editor context, it has a replacement issue: #3363
