### ISSUE TITLE
Design Panel - Video

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#259]
This ticket is for video specific features not covered by the panel-focused issues: #279 #280 #282 #283 #284

**Acceptance Criteria**
1. ?
4. The relevant tooltips are shown on hover

[Feature Brief - Epic: Selection & In-place Editing
](https://docs.google.com/document/d/1_3-_v4zH6bW9hOplOO8wYxj8l4C0soMgEbD7XLiXrrg/edit#)

**[Design](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=0%3A1)**

**Comment by spacedmonkey** [comment]
@jauyong Is this related - https://github.com/google/web-stories-wp/issues/45#issuecomment-565604761

**Comment by swissspidy** [comment]
This needs ACs for functionality like the [video poster workflow](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=4263%3A41814), which also includes a field for setting the assistive text for the video / poster (area currently pending UX review).

**Comment by pbakaus** [comment]
Please close or modify so that it's clear what the actual work here is, from the title alone.

**Comment by jauyong** [comment]
I will review what is outstanding and update this ticket.

**Comment by jauyong** [comment]
Closing in favour of #1199 #1200 #248 #1304
