### ISSUE TITLE
Dashboard: changing stories status filter should scroll to top

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#2596]
## Feature Description

As mentioned on #1744:

1. I'm on the 'All Stories'' tab
1. Then scroll down the list
1. Then click on 'Drafts' or 'Published', the list should start at the top. Currently, it's starting at the same scroll position.

## Additional Context

<img width="1678" alt="Screenshot 2020-06-18 at 19 39 03" src="https://user-images.githubusercontent.com/841956/85053824-6160c300-b19b-11ea-8bd3-81ff228a3f97.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by carloskelly13** [comment]
@swissspidy I'd also say it should scroll to top when you toggle Grid/List view.

**Comment by swissspidy** [comment]
That sounds reasonable 👍

**Comment by csossi** [comment]
Verified in QA
