### ISSUE TITLE
Media Library - Hover/Focus States and Actions

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#26]
## Feature description

When user hover / select a media element in sidebar, controls should appear to allow user to insert, set background and edit media data. 

This ticket is blocked by ampproject/amp-wp#3851 ampproject/amp-wp#3859 ampproject/amp-wp#3856 

**[Feature Brief - Epic: Media Gallery](https://docs.google.com/document/d/1aZH_TI_be2t5Ywyqx4jcPTPdhFGEt7xh-uLzBp2AV4A/edit#)**

**[Design](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=4644%3A299408)**

---------------

## Acceptance criteria

Generic Element Panel States ([Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=4644%3A299408)): 
1. While hovering over element nav bar options, hover states are active
2. While hovering over the plus (+) icon next to Text in the element nav bar, it's own unique hover state is active
3. While hovering over anywhere inside the pink area (see design) the scroll bar is shown.
4. While hovering over the search field, the text cursor is shown
5. While focused on the search bar, the text cursor is shown and the input field is white.
9. While hovering over a text link use colour: #4285F4.
10. Blue for the non selected state (#1A73E8) 

Media Library:
1. While hovering over the "All types" filter or clicking the dropdown arrow, the dropdown menu is shown (Dropdown was not done as party of Alpha see #1199)
7. While hovering over a media file the more icon is shown. (See #354)
8. While hovering over a video file, the video is played along with the more icon mentioned above. (video is playing on hover on Version 1.0.0-alpha)
8. After clicking on the more icon a dropdown menu with options Edit and Delete are shown (See #354 for edit functionality)
9. After clicking edit in the dropdown menu, a dialog is opened where the editor can edit the media metadata. THIS WILL BE HANDLED IN #354 
2. After clicking delete in the dropdown menu, the media file is removed from the library and the files below are shifted up

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jauyong** [comment]
Need to confirm if UX / Designs are done prior to Feb 5 grooming...

**Comment by jauyong** [comment]
Awaiting updates in design from @samitron7

**Comment by dvoytenko** [comment]
Do we have a similar issue for media in the canvas?

**Comment by jauyong** [comment]
@dvoytenko we don't but I will create one. 
@samitron7 I quickly reviewed the selection rules and Edit sections and don't see much regarding available actions in the workspace / canvas other than a resize bar appearing when you select media. Do you have additional actions to add there as well?

**Comment by dvoytenko** [comment]
@samitron7, at a minimum we need a video/gif replay inside the canvas.

**Comment by pbakaus** [comment]
What's the status here? I see @samitron7 assigned but AFAIK the designs exist?

**Comment by jauyong** [comment]
Just need to choose a colour for text links @samitron7 
![image](https://user-images.githubusercontent.com/5874851/79876214-c3c65e80-83b8-11ea-80bb-73cf948eee9e.png)

**Comment by jauyong** [comment]
Added details to description regarding text colours...
blue for the non selected state (#1A73E8) and #4285F4 the hover state.

**Comment by ezxyz** [comment]
I was wondering what is the color of the input text in the search bar when it turns white? Currently (with a dark search bar) the text is white itself.

**Comment by jauyong** [comment]
@jhtin Looking at figma it seems to be black #000000

![image](https://user-images.githubusercontent.com/5874851/80024505-30bb2080-84ad-11ea-8ff0-200d1ef38e4c.png)

**Comment by jauyong** [comment]
closing this ticket. per @jhtin the [generic element panel state tasks are all in review or done.](https://xwp.slack.com/archives/CCCAUAH6F/p1587617849452800?thread_ts=1587616908.450300&cid=CCCAUAH6F)

Media library tasks are covered in: #1199 #354 #1319
