### ISSUE TITLE
Design Panel - Shape Types, from Templates and Licensed Icons

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#260]
This ticket is for shape specific features not covered by the panel-focused issues: #279 #280 #282 #283 #284

**Acceptance Criteria**
1. When viewing shapes, they are grouped by "Types of shapes"
   1. Basic
   2. Background
   3. Icon
2. When using a template, shapes are inherited from the template (template shapes are local and not global shapes?)
3. Licensed icons

[Feature Brief - Epic: Selection & In-place Editing
](https://docs.google.com/document/d/1_3-_v4zH6bW9hOplOO8wYxj8l4C0soMgEbD7XLiXrrg/edit#)

**[Design](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=0%3A1)**

**Comment by pbakaus** [comment]
Please close or rename to make clear what the actual work is.

**Comment by jauyong** [comment]
@pbakaus I've updated the description based on the missing features from the Product Spec doc. It seems that doc needs to written out still.
