### ISSUE TITLE
Drop shape relative to dragging point

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#2605]
## Feature Description

When dragging a shape onto the canvas (post-merge of #1856), the element is dropped regardless of where the element was "grabbed".

## Additional Context

See [comment](https://github.com/google/web-stories-wp/pull/1856/files#r437047591).

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Closing as fixed within #5614.
