### ISSUE TITLE
Setup trackable CUJ integration testing

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#2607]
## Task Description

Create a way to track the implementation of all CUJ's through integration testing the different aspects of the required implementation.

## Implementation Brief

Each CUJ has a number of bullet points detailing the actions of the epic. These will be used to track implementation for example for the action _"Delete textbox"_ under the CUJ _[Creator can Add and Write Text](https://github.com/google/web-stories-wp/issues/1494)_:

```js
// File: deleteTextboxShortcut.karma.js
describe('CUJ: Creator can Add and Write Text', () => {
  describe('Action: Delete textbox', () => {
    describe('when a textbox is selected', () => {
      it('should be removed when pressing backspace', () => {
        // Implementation goes here
      });

      it('should be removed when pressing delete', () => {
        // Implementation goes here
      });
    });
  });
});

// File: deleteTextboxDrag.karma.js
describe('CUJ: Creator can Add and Write Text', () => {
  describe('Action: Delete textbox', () => {
    // Disable reason: Not implemented yet
    // eslint-disable-next-line jasmine/no-disabled-tests
    xit('should allow you to delete a text box by dragging it off-stage', () => {});
  });
});
```

This would be tracked as 66.67% (2 tests implemented, 1 test skipped) implementation of this action, and as this is one of 6 bullet points for the CUJ, the CUJ would overall be tracked as 11.11% (1/6 * 2/3) – assuming no other test files implement anything for this CUJ at all.

To track the number of actions for a CUJ, simply look for how many different `Action: Some action` that are listed as direct descendants of a given `CUJ: Title`.

In order to do this, we'd need to create (mostly empty and skipped) karma tests throughout the application of all the relevant actions under all the CUJ's, we want to track.

Then we'd setup some monitoring, that would create these aggregated numbers and collect them in some table - e.g. something like:

| CUJ | Action | Files | Completion |
|-|-|-|-|
| Creator can Add and Write Text  | _[total]_ | | 🚨    **28.28%** |
| Creator can Add and Write Text  | Delete textbox | _[1]_ **[2]** _[3]_ | 🛴     **66.67%** |
| Creator can Add and Write Text  | Write/edit text | **[1] [2]** |🏆     **100.00%** |
| ...  | ... | ... |
| Creator Can Style Text  | _[total]_ | | 🛴    **71.19%** |
| Creator Can Style Text  | Set line height | **[1] [2]** _[3]_ **[4]** |🏔️     **95.79%** |
| ...  | ... | ... |
| _[total]_  | _[total]_ | | 🚨    **42.84%** |

Each row is annotated with links to all the relevant test files for a given action - that makes it much easier to find all the missing implementations. Just for this example, the idea would be that the links in **bold** would be files with 100% implementation, and the links _in italic_ would be the ones still skipping at least one test.

I'm thinking we could do this with a [custom jasmine reporter](https://jasmine.github.io/tutorials/custom_reporter) - it seems simple enough to do.

**Comment by dvoytenko** [comment]
Brilliant!

**Comment by dvoytenko** [comment]
Additional proposal is to instrument the custom Jasmine reporter to also produce a screenshot for each CUJ test to be automatically pushed to Percy. See [this screencast](https://drive.google.com/file/d/1d-WTjckbEyS5j2S9Fn7sMePSt_NLK9vl/view?usp=sharing) for an example flow.
