### ISSUE TITLE
Design Panel - Text

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#261]
This ticket is for text specific features not covered by the panel-focused issues: #279 #280 #282 #283 #284

**Acceptance Criteria**
1. ?

[Feature Brief - Epic: Selection & In-place Editing
](https://docs.google.com/document/d/1_3-_v4zH6bW9hOplOO8wYxj8l4C0soMgEbD7XLiXrrg/edit#)

**[Design](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=0%3A1)**

**Comment by pbakaus** [comment]
Closing this ticket as it is really not actionable.
