### ISSUE TITLE
Snapping is sometimes quite "jumpy"

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#2613]
## Bug Description
In some situations, snapping seems to be quite jumpy.

Maybe this happens when multiple snapping points collide / are close to each other and one snapping causes another snapping to happen which then results in jumpiness.

## Expected Behaviour
- Snapping should feel smooth and not jump more than one snapping distance at a time

Note: not sure how much we can do from our side -- maybe that's something to replicate in codepen and then creating an issue to Moveable repo.

## Steps to Reproduce
1. Add an image to the upper part of the Page, the bottom border close to the middle line but not exactly.
2. Add a heart shape (with that shape it was the most obvious when testing)
3. Rotate the shape and snap its visually uppest corner to the bottom of the image
4. Now try resizing the shape slowly from the visually lowest corner.
5. See jumpiness.

## Screenshots
![snapping-oddity](https://user-images.githubusercontent.com/3294597/85127349-8bfc5b80-b22f-11ea-8cf2-9fb86e31e322.gif)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment]
@o-fernandez I couldn't easily replicate this so putting this in the icebox as a low priority bug.

**Comment by o-fernandez** [comment]
@miina can you double check this and maybe close it out if no longer relevant?

**Comment by miina** [comment]
Wasn't able to reproduce with these steps anymore, closing.
