### ISSUE TITLE
Hide elements tab behind flag

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#2616]
## Feature Description

Let's put this behind a flag until it's implemented.

## Additional Context

<img width="377" alt="Screen Shot 2020-06-19 at 7 43 05 AM" src="https://user-images.githubusercontent.com/841956/85145255-9842e180-b24c-11ea-958e-e9c117e05119.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
This tab **was** definitely hidden:

![Screen Shot 2020-06-19 at 1 01 59 PM](https://user-images.githubusercontent.com/637548/85160927-11324100-b22d-11ea-980d-8912bd4dc252.png)

This is from the branch `fix/blobs` I happened to have checked out from a review of #2574.

I'm not sure why it is now _unhidden_? Maybe a bad merge somewhere?

**Comment by swissspidy** [comment]
Maybe the media3p tab merge from this week?

**Comment by swissspidy** [comment]
Yeah looks like #2553 caused this
