### ISSUE TITLE
Unify Button components

### ISSUE THREAD

**Issue by merapi** [GoogleForCreators/web-stories-wp#2617]
## Feature Description

We have at least 2 Button components (not including Dashboard) so there is a potential to unify them and make them all work with link type button (`a`) and multi-line labels.

https://github.com/google/web-stories-wp/pull/2256#discussion_r442833065

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
Buttons have been unified via design system. closing.
