### ISSUE TITLE
Can't play the video sometimes (no play button)

### ISSUE THREAD

**Issue by merapi** [GoogleForCreators/web-stories-wp#2618]
## Bug Description

From Sam:
If I drag a video and set as bg, the video autoplays. Then I deselect the video (video stops playing) then select it again but there is no play button so I'm not able to ever play the video again.

First thought: Might be connected to isTransforming and dropTargets that don’t set null.

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
@merapi  to take a look and validate that this is still an ongoing issue and confirm the estimate

**Comment by merapi** [comment]
The issue still exists, since it's a bug - I'm not sure about the estimate (can be 2-3).

**Comment by csossi** [comment]
Verified in QA
