### ISSUE TITLE
Editor UI refinements for beta

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#2619]
## Feature Description

Move "Nothing selected" to the center and a bit further down
Design & Document tabs should be aligned to the left

![DesignPanel - Page (8)](https://user-images.githubusercontent.com/841956/85148284-3edcb180-b250-11ea-98b6-9cdf143c07ba.png)

Remove white lines at the bottom:

<img width="369" alt="Screen Shot 2020-06-19 at 7 52 26 AM" src="https://user-images.githubusercontent.com/841956/85148241-33898600-b250-11ea-9e33-6cf65c23eb20.png">

<img width="369" alt="Screen Shot 2020-06-19 at 7 51 52 AM" src="https://user-images.githubusercontent.com/841956/85148245-34221c80-b250-11ea-82ae-426f5d4ad7ac.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Two main things to test inn #2620:

* Verify that there is no whitepace between the presets color swatches and the bottom border  
  <img width="317" alt="Screenshot 2020-06-22 at 13 52 11" src="https://user-images.githubusercontent.com/841956/85284507-9ddc3980-b48f-11ea-8756-a40332186f8f.png">
* Verify that the collapsed presets panel is expanded when entering edit mode

**Comment by csossi** [comment]
Verified in QA - Tested PR#2620
