### ISSUE TITLE
Beta Support and Feedback Form

### ISSUE THREAD

**Issue by ernee** [GoogleForCreators/web-stories-wp#2629]
## Task Description

Per previous discussion, we'll use a form to receive user support requests and feedback during the Beta release period. 

See the following for review:

- [Support and Feedback Form](https://docs.google.com/forms/d/1xo5J7hdvPGDpEENZtlF3G4-mo3Q0E-S7oRvSyOjZ_I4/edit?usp=sharing) 
- [Form flow reference](https://docs.google.com/spreadsheets/d/1DiC8ghS7j2ffNQzImgT7f_x8QDJJRpg0lHvr38YqtpI/edit?usp=sharing)

Some pending questions:

- Should we allow uploads?
- Anything to omit or include?
- Feedback on which responses are required or optional?

cc: @o-fernandez , @amedina , @swissspidy

**Comment by swissspidy** [comment]
Nice work on the form! 👍 

> Should we allow uploads?

Yes, it would be useful if people could upload screenshots 👍 

> Anything to omit or include?

- For the "Report an issue" step, we should add add a "error message / details" field?  
  This would need to support pre-filling. When users click on the "Report Error" button implemented in #2256, the field should be pre-filled with the error message / stack trace.  
  I'm gonna take a stab at this... 
- Should we add the "Provide an email address where we can contact you." field to all cases?
- Should we add the "How would you rate your experience with the Web Stories Editor plugin?" field to all cases?

> Feedback on which responses are required or optional?

- For the "Report an issue" form, should we perhaps consolidate the 3 fields into 1 longer one?  
  Having to fill out 3 required fields there might be too much hassle.


----

Note to self: we need to make the form public once it's finished 🙂

**Comment by swissspidy** [comment]
Looks like prefilling would work like this:

```
https://docs.google.com/forms/d/e/1FAIpQLSfRK9gFWMavvGbEWPFUFz8PDgrDE6XdVuh3B9e1Fu549V8BxQ/viewform?entry.1908864204=Report+an+issue&entry.770137249=This+is+an+error%0A%0Aon+multiple+lines
```

Where `This+is+an+error%0A%0Aon+multiple+lines` needs to be replaced with the actual error message.

Edit: assigning myself to update this in the code once the form is finalized

**Comment by o-fernandez** [comment]
> > Should we allow uploads?
> 
> Yes, it would be useful if people could upload screenshots 👍

+1

**Comment by swissspidy** [comment]
@ernee Could you please update the form as per above's feedback?

**Comment by ernee** [comment]
Hi @swissspidy!  Currently the form (and reference spreadsheet) have been updated per feedback above and separate discussion. 

Special note: 

- we determined it was best not to allow uploads at this time
- an error field is available; pending support for pre-filling from the workspace I think

Feel free to let us know if we should make any further adjustments at this time (**cc:** @o-fernandez)

**Comment by samitron7** [comment]
@ernee What is the reason why we can't do upload at this time? Sometimes you need a screenshot to really explain what's going on.

**Comment by o-fernandez** [comment]
> @ernee What is the reason why we can't do upload at this time? Sometimes you need a screenshot to really explain what's going on.

We decided to do email follow-ups to get screenshots, for a variety of privacy and security considerations.

**Comment by swissspidy** [comment]
@ernee since we're probably gonna do a mailing list, time to close this issue?

**Comment by ernee** [comment]
@swissspidy we are still awaiting final confirmation about change in direction. I'll update the topic when it's complete.
