### ISSUE TITLE
Letter-spacing input update behavior is not consistent with other inputs

### ISSUE THREAD

**Issue by merapi** [GoogleForCreators/web-stories-wp#2636]
## Bug Description

Letter-spacing input is live updated (and cannot be cleared).
All other fields require confirmation (enter, blur) to apply the value.

## Expected Behaviour

Letter-spacing input should work as any other input does.

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment]
@samitron7 @o-fernandez 
Do we prefer live updates when you change field values? or do we prefer that you have to press enter or click out of the field to see the change?

**Comment by samitron7** [comment]
For inputing values, pressing enter is the norm so let's not change that behavior. (Sliders though should be live preview)

**Comment by barklund** [comment]
This has been solved by #4608.
