### ISSUE TITLE
QA Workspace for Beta

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#2648]
End to End testing of the workspace features and functionality for Beta.

QA to use the CUJ's marked for Beta here:
https://docs.google.com/spreadsheets/d/1zE3rdJykQY1YOQUHoczyzPNLa5_bhtv-2wfTE1-NOn0/edit#gid=0

Please review the feedback in the "Testing Comments" column in this document and validate that these are valid issues - https://docs.google.com/spreadsheets/d/10uxX3_sft8PrAgR0Sze0EGQWMdDdpo8npoFr4VODa84/edit?ts=5ef0f834#gid=0

**Comment by o-fernandez** [comment]
Per Claudio, this is complete.
