### ISSUE TITLE
Add Links to Privacy Statement and ToS

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#2650]
## Feature Description

As someone interested in Web Stories, I want to be able to view the Privacy statement and ToS.

Note:
Do something similar to Site Kit

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. On the plugin download page / information page, a link to the Privacy statement is provided https://policies.google.com/privacy
2. On the plugin download page / information page, a link to the ToS is provided: https://policies.google.com/terms

**Comment by swissspidy** [comment]
I suppose we need to figure out where to put these?

Would it suffice to add to the Dashboard alone?
