### ISSUE TITLE
Increase default font size

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#2665]
## Feature Description

This is a follow-up to #1204

Valuable discussion also in https://github.com/google/web-stories-wp/pull/1546/files#r426681693

According to Figma:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/342b5da3-3c85-41ba-8288-e67039674933)

However, we cannot use **16px** as-is, because the font size needs to be responsive. We currently use **1em**, which equals about 14px. **1.2em** would be closer to 16px though, so might be worth changing.

Also, the line height probably needs to be **1.5** instead of **1.3**?

![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/a16ca7da-be83-4df1-aa9b-199ca5aba546)

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by samitron7** [comment]
@swissspidy Can we just go ahead and change it to 1.2em now? 14px is a accessibility issue.

**Comment by swissspidy** [comment]
QA: see #2781 for instructions

**Comment by csossi** [comment]
Verified in QA
