### ISSUE TITLE
Preview button should reload existing window

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#267]
When clicking on the post preview button multiple times, a new window is opened every time.

It might make more sense to just reload an existing window if one has been opened already. This can be achieved by using a different window name than `_blank`.

There are some caveats though, see https://developer.mozilla.org/en-US/docs/Web/API/Window/open#Note_on_use_of_window_open

**Comment by merapi** [comment]
My current workflow is like this:
Click [Save draft] then [Preview], a new tab pops up and when I'm done I just close the tab with a shortcut and I'm back to editor, next time I don't have to locate the tab with preview, it will just pop up (so overall 2 clicks to see the preview).

This addition will not hurt my workflow and can help others. This will help best if you have the preview tab visible all the time (almost like live-reload).

The question is: can/should we do better? one click to save&preview? maybe just for development env?

Question for all: What would you like to see here to make your preview workflow better/faster?

**Comment by swissspidy** [comment]
Didn't realize what I might kick off with this issue 🙂 

A complete workflow overhaul is definitely out of scope for this issue. I simply proposed changing the tab/window name.

We're currently sticking to what's described in the [relevant epic doc](https://docs.google.com/document/d/1GJZljicdXcP7oRdywsF3EGUaCVpCHsDrK2gUMubnrbk/edit?pli=1#). I just asked for clarification there about the preview tab name there.

If you have any suggestions for changes in this area, please read that doc & reach out to @pbakaus

**Comment by merapi** [comment]
Improvements while in development mode are out of scope, here is the on-topic change: https://github.com/google/web-stories-wp/pull/420
