### ISSUE TITLE
Add description copy to templates

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#2687]
Right now the templates all have lorem ipsum. We should add in actual template descriptions. 

**[Template descriptions](https://docs.google.com/document/d/1tewOPzegX0QBcualXs7VMlgcCACwWAXiKRE3QFogNWM/edit#)**

![Screen Shot 2020-06-23 at 4 57 35 PM](https://user-images.githubusercontent.com/10720454/85479247-a8bbca80-b572-11ea-9396-db6d861d43be.png)

**Comment by samitron7** [comment]
@o-fernandez @pbakaus Can one of you help fill these out? I'm admittedly not the best copy writer.

**Comment by o-fernandez** [comment]
⁀⊙﹏☉⁀
Unless @pbakaus or @samitron7 think otherwise, or have some descriptions somewhere already we can use, I'd vote for just removing the descriptions in there and leaving the descriptions blank.

**Comment by samitron7** [comment]
@pbakaus Your call here as I'm a terrible writer. For stable, we do need to get all this squared out so maybe asking Crystal/Lizzi to help here :)

**Comment by pbakaus** [comment]
I'll do it.

**Comment by pbakaus** [comment]
Here's a first pass, lmk if that works: https://docs.google.com/document/d/1tewOPzegX0QBcualXs7VMlgcCACwWAXiKRE3QFogNWM/edit#

**Comment by swissspidy** [comment]
Looks good to me 👍

**Comment by samitron7** [comment]
Thanks for doing that Paul. They all sound good.

**Comment by o-fernandez** [comment]
@BrittanyIRL see descriptions written by @pbakaus here: https://docs.google.com/document/d/1tewOPzegX0QBcualXs7VMlgcCACwWAXiKRE3QFogNWM/edit#

Can you prioritize this ticket to see if we can get it in quickly?

**Comment by BrittanyIRL** [comment]
@o-fernandez @pbakaus two tiny questions (flagged by Mariano) about phrasing. Left comments in the google doc with the copy in it, if you can respond that would be great!

**Comment by o-fernandez** [comment]
@pbakaus seems to have resolved them last night, so good to go!
