### ISSUE TITLE
Responsive design

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#27]
## Feature description

We need responsive design making the editor look good in every size down to iPad (768x1024) and up to WQHD (2560 x 1440) – and of course everything in-between.

How, when and what is as yet undefined.

Product priority first, then UX, then engineering.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by barklund** [comment]
@dvoytenko, if this is partially solved by #136, which is now merged, this issue shouldn't be in "review in progress" column anymore.

**Comment by dvoytenko** [comment]
I filed #234 for page carousel responsiveness. Closing this issue.
