### ISSUE TITLE
Small UI improvements for media  library

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#2732]
## Feature Description

As per @samitron7's feedback:

* Change the color of the circle in the more menu to `#2F3449`. Black is too striking
* Change the color of the circle in the media edit button to `#2F3449`.
* Remove the play button. This isn't needed since we have the time duration.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

* Remove icon
* Change "more" icon so color can be set via CSS and is not hardcoded in the SVG

**Comment by swissspidy** [comment]
**FOR QA**

Testing PR #2733:

* Media library: Verify the three-dots button that appears over images/videos is not black.
* Media library: Verify that no play button is shown when hovering over videos.
* Document panel: Verify that the pencil button for editing the publisher logo or cover image is not black.

**Comment by csossi** [comment]
Verified in QA - PR#2733
