### ISSUE TITLE
Fix link protocol handling

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#2745]
## Bug Description

When adding a link, if I type **https://** it gets changed to **http://https://** which is not valid. 
From @swissspidy : "Even when I type http very slowly, it turns it into http://http"

## Expected Behaviour

- User input shouldn't be updated while the user is still entering a URL.
- Do not prepend http:// to a user if it has another valid protocol such as https://

## Steps to Reproduce

See gif
![http::: getting added after I type https:::](https://user-images.githubusercontent.com/13389997/85746068-2f3bed80-b6d4-11ea-970b-c987697b9f03.gif)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA - Tested in PR#3214
