### ISSUE TITLE
Close Color Picker by Tapping Outside 

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#2749]
## Feature Description

From Dima during bug bash:

> Color pick should close on the first tap outside. Currently it closes/reopens when clicking again on the color preview.

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. When the color picker is open clicking outside of the color picker box should close the color picker. This includes clicking on the color preview box which is used to open the color picker.
2. Clicking outside of the color picker should only close the color picker box. e.g. If the color picker is open and the creator clicks on another button, it should only close. 

![color-picker.gif](https://images.zenhubusercontent.com/5e985a7aea3104e101699670/19253f1c-82c0-4321-8fda-ac7c4f6da098)

**Comment by swissspidy** [comment]
I believe this has since been fixed
