### ISSUE TITLE
Media Edit Mode: Extend draggable area to include shaded area

### ISSUE THREAD

**Issue by wassgha** [GoogleForCreators/web-stories-wp#2765]
## Feature Description

See comment at https://github.com/google/web-stories-wp/issues/1192#issuecomment-631926009

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by wassgha** [comment]
@samitron7 I'd like to confirm that the desired behavior is for the area outside the box (area #3 in the screenshot) to be draggable as well even though clicking that area is already assigned to closing the editor? (It makes sense for me to have area #2 be draggable, but not sure about #3) 
<img width="244" alt="Screen Shot 2020-06-26 at 2 07 28 AM" src="https://user-images.githubusercontent.com/591655/85840866-15d98680-b752-11ea-8e2b-f97f1a20b3cb.png">

**Comment by samitron7** [comment]
Yes, area 3 should also be draggable. Click outside of image and not box to close.
