### ISSUE TITLE
Style presets not expanding when adding first color

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#2783]
## Bug Description

1. Make sure there are no saved colors
1. Create new story
1. Click ➕ icon to add new saved color
1. The panel stays collapsed

## Expected Behaviour

1. Make sure there are no saved colors
1. Create new story
1. Click ➕ icon to add new saved color
1. The panel expands

## Steps to Reproduce

1. Make sure there are no saved colors
1. Create new story
1. Click ➕ icon to add new saved color

## Screenshots

https://xwp.slack.com/files/UNKJGEE2W/F01646E2KBL/savedcolors.mov

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
See #2782 for instructions

**Comment by csossi** [comment]
Tested 2782 - Win10/Chrome

Added a new story. As soon as I clicked canvas, design panel appeared expanded but with black as a saved colors (which I didn't save). Seemed to appear by default:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/9ff6dc9f-34e1-44e2-8cfc-de5e2b98ecc9)

**Comment by swissspidy** [comment]
@csossi Style presets are global, so probably someone else on the QA site added one. Just delete it.

**Comment by csossi** [comment]
Verified in QA
