### ISSUE TITLE
Indicate broken image if image is deleted from library but still on page

### ISSUE THREAD

**Issue by samitron7** [GoogleForCreators/web-stories-wp#2784]
Steps to reproduce:
1. Add image to the page
2. Then delete the image from the library
3. Note that the image is still on the page but when you publish you don't see it

Expected behavior:
We need to remove the image from the page but leave the mask with image broken message (I believe this is done for past stories, but not this use case.

![Screen Shot 2020-06-26 at 7.32.41 AM.png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/b28c3eaf-6a3b-44e2-a753-ff3cac688730)

![Screen Shot 2020-06-26 at 7.32.55 AM.png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/2829d78c-9a3a-4b3c-9e7e-e8ed76dc1ec9)

**Comment by swissspidy** [comment]
Good point. Right now it looks like this when using an image/video in a story that doesn't exist anymore:

<img width="403" alt="Screenshot 2020-06-26 at 16 55 16" src="https://user-images.githubusercontent.com/841956/85870888-f2542180-b7cd-11ea-98de-cbcd7dcc9132.png">

**Comment by swissspidy** [comment]
Closing for now as users are warned before deletion and behavior is as follows:

1. Add image to the page
2. Then delete the image from the library
3. Image is removed from page
