### ISSUE TITLE
Selection frame out of place when  resizing window

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#2785]
## Bug Description

Originally reported by @samitron7 on Slack.

## Expected Behaviour

The selection frame should move with the element.

## Steps to Reproduce

1. Create element
1. Make sure element is selected
1. Resize browser window
1. See how selection frame is not at the same place anymore

## Screenshots

![ezgif-4-e97c17f11cd3](https://user-images.githubusercontent.com/841956/85872399-f719d500-b7cf-11ea-9d82-1dd656012fdb.gif)

## Additional Context

- Plugin Version: `master`
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
as per @samitron7  not stable

**Comment by bmattb** [comment]
seems related to #2154
