### ISSUE TITLE
Adding newline wipes out text element stlyes

### ISSUE THREAD

**Issue by samitron7** [GoogleForCreators/web-stories-wp#2786]
## Bug Description

Found in QA for #1774.

## Expected Behaviour

When adding a newline on a text element and continue typing, it should keep existing styling.

## Steps to Reproduce

1. Add new text field and style (color, font weight etc...)
2. Enter edit mode and add a new line then select all and type. (Or just add new line and type). All the styles are wiped out.

## Additional Context

- Plugin Version: `master`
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Seems to be working but I might be missing something:
![style](https://user-images.githubusercontent.com/3294597/87799853-0085e280-c84e-11ea-95b3-eb66657eefbb.gif)

@samitron7 Could you confirm if you can still see the issue?

**Comment by samitron7** [comment]
Seems to be working for me now.
