### ISSUE TITLE
Percy: false positives caused by media not fully loaded

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#2787]
It looks like there can be false positives when videos or images on the library haven't fully loaded yet. Example:

https://percy.io/google/web-stories-wp/builds/5863854

<img width="1659" alt="Screenshot 2020-06-26 at 14 20 11" src="https://user-images.githubusercontent.com/841956/85856362-2cb2c400-b7b8-11ea-8594-09d93f0e12f4.png">
<img width="1663" alt="Screenshot 2020-06-26 at 14 20 04" src="https://user-images.githubusercontent.com/841956/85856368-30dee180-b7b8-11ea-853d-069c3550f9f3.png">

**Comment by dvoytenko** [comment]
Hmm. Percy should be waiting for the `window.onload`, so I'm wondering if this is more related how the video is sampled when rendered. If this is a very common flake, we can, to start, block videos from loading at all in the snapshots. Not sure what's a better path forward though.

**Comment by swissspidy** [comment]
Closing this for now as it hasn't occurred since.
