### ISSUE TITLE
Karma: consider rerunning failed tests to weed out flakes

### ISSUE THREAD

**Issue by dvoytenko** [GoogleForCreators/web-stories-wp#2792]
## Task Description

With integration nature and on-browser testing flakes will be happening. Even with a tiny probability of having a flake per test, with the growing coverage, the probability of having at least one flake for the whole suite is also growing.

Jasmine doesn't have rerun option. So we instead may need to add a custom reporter that will record all the failed tests and do a second Karma run with only those tests. We can have a threshold, e.g. only under N failed tests are rerun. More failures just fail the job completely.

Note: special attention should be paid to the coverage now. The new supplemental coverage report should be saved in a separate place and uploaded along with the report from the main run.

**Comment by swissspidy** [comment]
Bummer that Jasmine doesn't have this built-in.

I'm sure someone has already implemented something like this already though.

Quick search reveals https://www.npmjs.com/package/jasmine-failed-test-files-reporter and https://www.npmjs.com/package/jasmine-spec-reporter that might help.

**Comment by swissspidy** [comment]
> So we instead may need to add a custom reporter that will record all the failed tests and do a second Karma run with only those tests.

With the current webpack setup for Karma tests we can only run the complete test suite AFAIK. So this doesn't seem possible.

We could just do a "re-run all tests if tests failed" thing if we want to

**Comment by dvoytenko** [comment]
I still think it could be possible. The Jasmine has an option `specFilter` (see https://jasmine.github.io/api/3.5/Configuration.html) and Karma additionally provides `--grep` flag for Jasmine as well (see https://github.com/karma-runner/karma-jasmine). So I'm still holding out some hope for this.
