### ISSUE TITLE
Dashboard: Performance Audit 

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#2793]
The dashboard is a bit slow, let's identify the causes and potential solutions. 
The goal here is that each page takes less than < 500ms (ideally less than < 100ms) to load. 

Things already identified: 
- 200 classes generated for displayElement (previews of stories)
  - See about limiting changes w/ styled components `.attr` or limiting how many previews are rendered (no reason to render those offscreen) 
- dashboard isn't using editor's `use-context-selector`
  - go through code, see where this would be useful to limit unnecessary updates

**Comment by BrittanyIRL** [comment]
@o-fernandez @pbakaus 
Did a brief audit of dashboard - my stories based on time to first interaction and identified 5 possible "quick" wins we could implement. 
Since @pbakaus made note to treat this as part of QA I would like buy in that these are acceptable action items. All of them are things that we can do in the dashboard save for pre loading the APIs which @spacedmonkey volunteered to do (though i might be able to follow the example he set in the editor if strapped for resources!). 

https://docs.google.com/document/d/1ulDbJEWA9Q-5QyNsb2NpTACne8RMw8dpqfshkXlEgRI/edit?usp=sharing

**Comment by o-fernandez** [comment]
Dropped a comment in the doc 

- would be great to get a few folks to review (I'd recommend 1-2 TLs at a minimum, could add a peer as well) and align on the approach. 
- when finalizing approach, a quick summary of expected benefit (performance improvement) and expected cost (time effort) would be great to help prioritize the efforts. can include both quick wins and longer term efforts into the estimates.

**Comment by swissspidy** [comment]
Awesome! I took a quick stab at the document already, but will take a closer look this week.
