### ISSUE TITLE
Design Panel - Element Alignment

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#280]
As an editor I want to be able to set the alignment on elements

**Acceptance Criteria**
1. The user is able to set the alignment on an element
2. The alignment options are updated based on the amount of elements selected

**[Design](https://github.com/google/web-stories-wp/issues/279)**
![Design Panel - Alignment](https://user-images.githubusercontent.com/5874851/74204671-245f4f80-4c42-11ea-8def-fd15187dfa14.png)

**Comment by pbakaus** [comment]
This isn't working correctly. Too many buttons are disabled for single elements (for single elements, they should align against the page). /cc @samitron7

**Comment by ndev1991** [comment]
Created following up PR for single element selection. #1246 and closes this issue.
