### ISSUE TITLE
Color Picker: dark background color when typing

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#2808]
## Bug Description

All input fields in the design panel keep a dark background color when focusing/typing.

The color picker input on the other hand switches to a white background.

## Expected Behaviour

The background should not change to `#ffffff`  when typing in the color picker input. It should have the same look & feel as other input fields in this state.

## Screenshots

<img width="274" alt="Screenshot 2020-06-29 at 15 39 41" src="https://user-images.githubusercontent.com/841956/86012984-f0cd6800-ba1e-11ea-8adf-555fe2149d52.png">

<img width="276" alt="Screenshot 2020-06-29 at 15 39 46" src="https://user-images.githubusercontent.com/841956/86012988-f1fe9500-ba1e-11ea-9a68-a14e75476140.png">

## Additional Context

- Plugin Version: `master` (`1.0.0-alpha.10`)
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
This has been fixed some time ago.
