### ISSUE TITLE
Color Picker: behavior when multiple fields are selected

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#2809]
## Bug Description

Originally reported by Sam:

When 2+ elements are selected, the color picker's input field contains the placeholder `(Multiple)`. When you click on it, the color picker is opened.

## Expected Behaviour

> I expect to be able to type and not open the color picker. The rule is clicking on text should behave like an input field and clicking on the color swatch, opens the color picker

## Steps to Reproduce

1. Select 2 or more text elements with different colors
1. Click on the `(Multiple)` placeholder in the color picker input field.

## Screenshots

<img width="285" alt="Screenshot 2020-06-29 at 15 47 51" src="https://user-images.githubusercontent.com/841956/86013883-efe90600-ba1f-11ea-9503-fee6610018af.png">

<img width="1004" alt="Screenshot 2020-06-29 at 15 48 21" src="https://user-images.githubusercontent.com/841956/86013913-fa0b0480-ba1f-11ea-898f-b3a83b7fb313.png">

## Additional Context

- Plugin Version: `master` / 1.0.0-alpha.10
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
Somewhat related to this is the label displayed for gradients in the same place.

@samitron7, what should happen when you click the label for "radial" or "linear" for a radial or linear gradient? Should clicking _that_ label also switch to an input field or should it open the color picker (as it does now)?

![Screen Shot 2020-10-01 at 16 09 11](https://user-images.githubusercontent.com/637548/94858153-9ae2d480-0400-11eb-8f6d-4b0590a6619b.png)

**Comment by samitron7** [comment]
It should open the color picker. The only time you get the input field is if you have a hex value there.

**Comment by miina** [comment]
@barklund @bmattb FYI I've pulled this into 1.2 since the sprint backlog is empty.

**Comment by csossi** [comment]
Verified in QA

**Comment by samitron7** [comment]
Verified in UAT
