### ISSUE TITLE
Page presets: Linear gradient should be disabled for a Page

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#2811]
## Bug Description

Bug from UAT for #2585 

Currently, it is possible to assign some presets with gradient + opacity to Page background.

## Expected Behaviour
Presets with opacity should not be allowed for Page background.

## Steps to Reproduce
See https://github.com/google/web-stories-wp/issues/2585#issuecomment-651207162

1. Remove all the color swatches in the saved colors section
2. Add a shape and apply a gradient to it. Add to color preset
3. Select the page bg and click on the new color with opacity. You'll see that you can add that color to the page
## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/d739e843-aaeb-4fcc-97cc-aa52133a9fca)
