### ISSUE TITLE
Improve URL validation for links

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#2815]
## Feature Description

This is a follow-up issue to #1966.

The links feature uses the [valid-url](https://www.npmjs.com/package/valid-url) npm package to validate URLs. In #2254, the way URLs are validated was changed a bit, and made a little bit more strict. However, that package still only validates URLs against the spec.

That means typos like `https://google.coms` won't be caught, since the format is technically valid.

In #2254 the server-side validation was relaxed a bit to prevent false positives. However, it seems like we cannot get around circling back at least a little bit.

Related: #2745

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

* Typos like `https://google.commss` should be reported as errors (i.e. non-existent URL)
* Blocked URLs like `https://google.com` should not be reported as errors

## Implementation Brief

* In `Link_Controller`, return errors for failed HTTP requests (i.e. non-existent URLs, error 500 -> check for `WP_Error`)

**Comment by swissspidy** [comment]
## Testing Instructions

1. Add new element
1. Add link to `https://google.commss` -> verify that "Invalid web address" error is displayed
1. Add link to `https://google.com` -> verify that no error is displayed

**Comment by csossi** [comment]
Verified in QA:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/6acefdb9-82d6-40b6-a22a-557672dc178c)

![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/aef539d4-aab9-4293-bb8c-253bc3d5c1af)

**Comment by swissspidy** [comment]
@samitron7 is the current behavior better & does pass UAT?

**Comment by samitron7** [comment]
@swissspidy Even though ticket is closed, this behavior is vastly better. Thank you
