### ISSUE TITLE
Shapes Added As White

### ISSUE THREAD

**Issue by csossi** [GoogleForCreators/web-stories-wp#2819]
## Bug Description

Adding a shape to an image appears in white - unable to see when defaulting to a white background
## Expected Behaviour

Shape should not default as `#FFFFFF`

## Steps to Reproduce

- create new page
- select Shapes tab
- click shape to add to page

note white shape added

## Screenshots

https://drive.google.com/file/d/11gK6xGkQj89n-4u0Hg2OElqVyzfrXPQ0/view

![image](https://user-images.githubusercontent.com/16945664/86071304-ecb83f00-ba4c-11ea-866a-b5f384833c84.png)

## Additional Context

- Plugin Version:
- Operating System: Win10
- Browser: Chrome (latest)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

* Shapes should be added with color `#EEEEEE`

**Comment by swissspidy** [comment]
Great timing :-)

Sam already asked me to change the shape color to `#eeeeee` when adding to the page

**Comment by o-fernandez** [comment]
Per @pbakaus this is a beta blocker - added as such.

**Comment by csossi** [comment]
Tested in PR#2858

Verified in QA
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/60cf3782-fd3d-4141-8e35-fcf6e7d600e9)
