### ISSUE TITLE
Create category list fetch side effect for media3p

### ISSUE THREAD

**Issue by cvolzke4** [GoogleForCreators/web-stories-wp#2825]
## Task Description

Creating and updating state + wiring up with UI.

There's no ‘fetchTrendingCategories’ action function returned from the context value.

To load the initial trending categories list, a useEffect react hook will react to state changes and automatically re-fetch data.

See the existing MediaProvider useEffect hook to see how this works for local media:
https://github.com/google/web-stories-wp/blob/master/assets/src/edit-story/app/media/mediaProvider.js#L118

**Comment by diegovar** [comment]
Obsolete, covered by #2358
