### ISSUE TITLE
Design Panel - Layer (Opacity)

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#283]
As an editor I want to be able to set the style of elements on the page

**Acceptance Criteria**
1. User is able to set Layer opacity for all elements (media, text, shape, background media)

Note: Font Style will be handled in #284 

**[Design](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=2671%3A55920)**

**Comment by miina** [comment]
Changing the description and title of this issue due to the changes in Design to reflect the Layer panel which now includes Opacity for all the elements.
cc @pbakaus
