### ISSUE TITLE
Image in media library needs a max height

### ISSUE THREAD

**Issue by samitron7** [GoogleForCreators/web-stories-wp#2831]
I uploaded a large shape image to the media library and the image took up several pages worth of height space. Note where the cursor are in the images.

![Screen Shot 2020-06-29 at 11.37.09 PM.png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/20550e94-4880-4d39-b2b0-658cc617badb)

![Screen Shot 2020-06-29 at 11.38.47 PM.png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/d2a65a3a-eac0-46ae-8b5f-cf216f185f1d)

**Comment by o-fernandez** [comment]
@diegovar wondering if this is something that media pod could take a look at? 
@samitron7 any recommendation on max height?

**Comment by diegovar** [comment]
We're trying to move into the row-based layout ASAP (even for the upload tab). In that case, what should be the max height of a row @samitron7

**Comment by samitron7** [comment]
Set max height to 108px. FYI, btw visuals coming in for this soon!

**Comment by diegovar** [comment]
Obsolete as we now have a row-based layout.
