### ISSUE TITLE
Design Panel - Font Style 

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#284]
As an editor I want to be able to set the style of text or  text with textbox on a page

**Acceptance Criteria**
1. The editor is able to select a font TO BE DONE IN #309 
2. The editor is able to set font weight
3. The editor is able to set font size
4. The editor is able to select line height (auto sizing?)
5. The editor is able to set text letter spacing
6. The editor is able to set text alignment
7. The editor is able to specify: bold, italic, underline
8. The editor is able to set text box color?
0. The editor is able to set text box spacing?
9. The editor is able to set padding 
9. When editing a text with textbox, the editor is able to set textbox color and opacity
10. All relevant tooltips are shown

**[Design](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=2671%3A55920)**

**Comment by miina** [comment]
To be followed up separately:

Selecting part of Text to set it italic, bold, underline: https://github.com/google/web-stories-wp/issues/413
