### ISSUE TITLE
Snap to dimensions of elements

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#285]
_This is a follow-up to #95 and #170._

As described in the [epic brief for this feature](https://docs.google.com/document/d/1_3-_v4zH6bW9hOplOO8wYxj8l4C0soMgEbD7XLiXrrg/edit#heading=h.7g88vfclpjfp), when dragging or resizing an element or group of elements, the editor offers alignment help with snap areas:

* [x] Snap to the sides of other elements (Drag, Resize)
* [x] Snap to the width/height of elements (Resize)
* [x] Snap to the center of elements (Drag, Resize)
* [x] Snap to vertical/horizontal center of the page

As far as I can tell, only 3 out of these 4 types have been implemented.

This issue covers the last remaining one: snapping to dimensions of siblings when resizing elements. This way the user can easily make elements of equal size.

Now, it seems that the [Movable](https://github.com/daybrush/moveable) library does not support this out of the box, so we might have to do the calculation ourselves (needs confirmation).

------

**[Epic](https://docs.google.com/document/d/1_3-_v4zH6bW9hOplOO8wYxj8l4C0soMgEbD7XLiXrrg/edit#heading=h.7g88vfclpjfp)**

------

**Acceptance Criteria**

* When resizing a single element, it should snap to width and height of other elements on the same page.
* When resizing multiple elements, the movable container should snap to width and height of other elements on the same page.

**Comment by dvoytenko** [comment]
/to @wassgha for triage only. I believe resize snapping is not in Moveable at this time. Let's check and file a bug for them. Once done, please unassign the bug for prioritization. If confirmed, we'll likely need to contribute code to Moveable.

**Comment by samitron7** [comment]
I zipped up a .mov file but also shared this on slack. Let me know if you can't view it.

[snap2closestDistance.mov.zip](https://github.com/google/web-stories-wp/files/4320699/snap2closestDistance.mov.zip)
