### ISSUE TITLE
Fix karma tests memory issues

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#2851]
## Task Description

Karma tests [often](https://github.com/google/web-stories-wp/pull/2718/checks?check_run_id=813311005#step:7:16) [have](https://github.com/google/web-stories-wp/pull/2718/checks?check_run_id=813328011#step:7:24) memory issues and halt execution - even before actually starting running the tests.

This seems inconsistent but increasingly common, as tests grow more and more complex and comprehensive.

Possible fixes include:

* Increasing memory limit
* Fixing underlying memory leak (if any)

See [this thread](https://xwp.slack.com/archives/CCCAUAH6F/p1593228776378200) for discussion.

**Comment by dvoytenko** [comment]
I think I can confirm that it happens in the source map preprocessing. Here's the full debug log for the failure:

```
>> WebPack
✔ Stories Editor
  Compiled successfully in 133.37ms

30 06 2020 09:10:48.198:DEBUG [web-server]: Instantiating middleware
ℹ ｢wdm｣: Compiled successfully.
ℹ ｢wdm｣: Compiling...

✔ Stories Editor
  Compiled successfully in 58.80s

ℹ ｢wdm｣: Compiled with warnings.

>>> Fails between these two logs

30 06 2020 09:12:03.278:DEBUG [preprocessor.sourcemap]: base64-encoded source map for /Users/dvoytenko/DNI/web-stories-wp/assets/src/edit-story/components/canvas/karma/backgroundCopyPaste.karma.js
```

This most likely comes from this Karma configuration:

```
preprocessors: {
  'assets/src/edit-story/**/karma/**/*.js': ['webpack', 'sourcemap'],
},
```

Not clear what are all issues related to sourcemap here.

**Comment by dvoytenko** [comment]
[Here's](https://github.com/karma-runner/karma/issues/2673) something similar and suggested solution is [here](https://github.com/webpack-contrib/karma-webpack#alternative-usage). This promises to speed up our test compilation time on WebPack quite a bit.

**Comment by barklund** [comment]
> The above configuration generates a webpack bundle for each test.

That sounds horrible! Yes, let's go for this alternative approach and pack them all in single bundle for CI.

**Comment by dvoytenko** [comment]
PTAL: https://github.com/google/web-stories-wp/pull/2887
