### ISSUE TITLE
Delete story button styling

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#2861]
## Bug Description

Should align delete story dialog with spec in #2104 
![image](https://user-images.githubusercontent.com/13389997/86166666-25a2f300-bae3-11ea-9874-4b6a293fb755.png)

Originally implemented in #2263

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
Confirming this update should update the buttons to have less round borders, different hover like this? 
![new dialog buttons](https://user-images.githubusercontent.com/10720454/86167557-9c33f680-bacb-11ea-9cb8-296f78b0b4d1.gif)

**Comment by o-fernandez** [comment]
@samitron7 to clarify/confirm Brittany's question above.

**Comment by samitron7** [comment]
@BrittanyIRL I think @swissspidy made a pass at all the dialog box and that change looks similar to what he has. Pascal, can you confirm.  Is there a hover state on the delete button as well in the animation (I can't tell).

**Comment by swissspidy** [comment]
@samitron7 Yes. You can test it yourself here:

* https://google.github.io/web-stories-wp/storybook/?path=/story/stories-editor-components-dialog-post-publish--default
* https://google.github.io/web-stories-wp/storybook/?path=/story/stories-editor-components-dialog-preview-error--default
* https://google.github.io/web-stories-wp/storybook/?path=/story/stories-editor-components-dialog-delete-media--default
* https://google.github.io/web-stories-wp/storybook/?path=/story/stories-editor-components-dialog-delete-media--default

**Comment by BrittanyIRL** [comment]
> @BrittanyIRL I think @swissspidy made a pass at all the dialog box and that change looks similar to what he has. Pascal, can you confirm. Is there a hover state on the delete button as well in the animation (I can't tell).

Great, i just wanted to confirm before updating the styles for dialogs within dashboard

**Comment by BrittanyIRL** [comment]
re testing: please see PR description for more context https://github.com/google/web-stories-wp/pull/2949

**Comment by csossi** [comment]
Verified in QA
