### ISSUE TITLE
Firefox preset circles partially filled

### ISSUE THREAD

**Issue by merapi** [GoogleForCreators/web-stories-wp#2864]
## Bug Description

![image](https://user-images.githubusercontent.com/21036224/86167930-ada2f000-bb17-11ea-86a3-a63cb6533f01.png)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by wassgha** [comment]
Moving to QA

**Comment by csossi** [comment]
Verified in QA
