### ISSUE TITLE
Text Magic

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#2869]
## Feature Description

combo of color, fill style/highlight, line height, frosted glass effect

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
This is now a duplicate of #7718 which prometheus is already working on.

**Comment by swissspidy** [comment]
Hmm I always thought text magic referred to this awesome demo Paul built a while ago: https://codepen.io/pbakaus/pen/gOpZXbW

Which is quite different from #7718 I think

**Comment by BrittanyIRL** [comment]
i guess i saw it as iterations, but i don't know. This is just an old ticket and I wanted to get some stuff cleaned up and more current.
