### ISSUE TITLE
Update Travel template "No. 3" label and square shape location

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#2873]
## Feature Description

Per https://github.com/google/web-stories-wp/issues/2475#issuecomment-652008326
Need to update the location of the "No. 3" label and box in the Travel template

**Move from here**
![image](https://user-images.githubusercontent.com/13389997/86171702-2770b480-baeb-11ea-8038-3c61720e5a6a.png)

**Move to here**
![image](https://user-images.githubusercontent.com/13389997/86171729-322b4980-baeb-11ea-9660-38329f59d767.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/3d229ee3-47cd-4c25-9160-018c531e1ae5)

![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/f64c5c62-199d-4ed8-a651-556b77275760)
