### ISSUE TITLE
Do not allow shrinking text to less than font size 8

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#2878]
## Feature Description

Per comment: https://github.com/google/web-stories-wp/issues/1549#issuecomment-652019457

Currently, I can add text to the canvas and using the selection box edges shrink the box and the text so that text is smaller than 8. Our min limit in the font size box (in design panel) is 8, and that should be the same when resizing using selection box. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
@merapi Can you please provide a story point estimate for this issue?

**Comment by merapi** [comment]
@o-fernandez How should it work for multi-selection? for images/videos/shapes we allow values smaller than 20 (width/height limit) - so there is no limit in multi-selection resize, should it be the same for text?

**Comment by o-fernandez** [comment]
I'd follow the more restrictive logic, in this case, as soon as a text element shrinks so that the text size is 8 then don't allow any more shrinking (across the whole selection). 

Does that make sense?

**Comment by samitron7** [comment]
@merapi Replaying to your comment from Slack "will it be ok to just stop resizing by handles without any information to the user? it applies to any type of multi-selection, e.g. text+image/video/shape "

But this is a little more thought than just simply restricting the size because of the following situation:

1. I created a list that has a title text at 24px, a 1px line then a list with a bunch of text elements at 18px. I select to resize. Would like to keep the relative sizing of the element inside the list.
2. Text presets and grouped sets. also would like to keep relative sizing between elements inside the group.

Let set these rules on figma and atttach. I'll add to my queue if this can wait.

**Comment by merapi** [comment]
@samitron7 relative sizing is already kept right now (1. and 2. will work as described), the question is what should happen if you select 8px text and a bunch of other elements (of any type) and you try to make them smaller? - if we stick to 8px font-size as hard limit then you will not be able to resize the whole selection down (without any hint). 
Other 2 options are:
1. Stop resizing below 8px but just the text (other elements will be sized down)
2. Do not enforce the limit (current behavior)

**Comment by samitron7** [comment]
I personally think we shouldn't enforce the limit for the multiple select scenario. The minute you set a limit on something and not another, it causes a cognitive load on the users plus we need to explain what is happening (ie why is some text resizing while others arent etc..). There could also be a situation where the user want to use it as a stylistic effect. I prefer to allow the users to resize even if some of the text falls below our desired min and catch under guidance in the pre-publish list. Also, I believe 12px is the hard requirement for text you need to read from the format team.

**Comment by merapi** [comment]
> Also, I believe 12px is the hard requirement for text you need to read from the format team.

@o-fernandez can you confirm? should we update [Design Panel Min and Max values](https://docs.google.com/spreadsheets/d/1hdru-_p4Yk-VFQ1rEFGYHHI2A7eNZkxLA33-LblG8sE/edit#gid=0)?

**Comment by o-fernandez** [comment]
I would leave as it currently is, per our last discussion. We will enforce the min time as it already is defined, no need to change the min text size for now in my opinion, just because to Sam's comment we may use small text to create an effect. We could just let users know in the pre-publish checklist that text below 12px is not necessarily readable, but not prevent it.

**Comment by csossi** [comment]
QA Instructions missing, so I want to confirm where we've netted out here

Is the rule that resizing text-only has a min of 8px while resizing a group of assets can go below that?

**Comment by samitron7** [comment]
@csossi This rule should apply to text regardless if they are resized as a single unit or within a selected group. The hard legible limit is 12px and we'll attempt to catch any text below 12px in pre-publish. @merapi I do think we need to not go below 1px otherwise we can not apply a selection box to an element that can not be seen.

**Comment by merapi** [comment]
Currently, there is a limit when resizing single text element by handles (8px, same as via input).
With multi-selection, there is no limit.

> I personally think we shouldn't enforce the limit for the multiple select scenario.

> We will enforce the min time as it already is defined, no need to change the min text size for now in my opinion

@samitron7 @o-fernandez 

12px limit will be checked on the pre-publish list.
Should we change the current behavior in any way (this PR, please check it on QA)?

**Comment by samitron7** [comment]
We have an upcoming design review on text this thursdy so let's pause on this ticket till then. Update will follow after the meeting.

**Comment by o-fernandez** [comment]
> We have an upcoming design review on text this thursdy so let's pause on this ticket till then. Update will follow after the meeting.

Ping - was there a resolution on how this will be handled? @samitron7

**Comment by merapi** [comment]
There will be no font-size limit, just the 1px bounding box limit.
Font sizes smaller than 12px will be caught on the pre-publish checklist.
@samitron7 correct?

We still need to do https://github.com/google/web-stories-wp/issues/3377

**Comment by o-fernandez** [comment]
ok, I'll close this ticket as won't fix since it's not really valid. Will file a separate ticket, if none already, to then align the design panel to have smaller font sizes.
