### ISSUE TITLE
Dashboard results scrolling to top on pagination

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#2884]
Omar noticed this today, when you load another page of results in the dashboard the window is scrolling up! we only want it to scroll up when you swap quick filters or sorts. 
![bad scroll](https://user-images.githubusercontent.com/10720454/86185636-a82fb080-baeb-11ea-8eb7-b2a29fadbb7e.gif)

Acceptance Criteria
- Scroll to top of results should only happen when you change a filter or a sort on my stories 

Testing: 
- Scroll down the list of stories in your dashboard, see that there's no attempt to send you to the top of the page again
- click a different quick filter and see that you are scrolled to the top
- scroll down the view and change the sort and see that you are scrolled to the top

**Comment by pbakaus** [comment]
Confirmed in UAT.
