### ISSUE TITLE
Dashboard Typeahead Should Scroll

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#2885]
## Bug Description
Right now the dsahboard's typeahead on search is showing 5 items, everything outside of that is not rendered and not scrollable. You have to keep typing to get different results. 

## Expected Behaviour
When there's more results than can fit in the visible area of the typeahead options they should be scrollable

## Steps to Reproduce
Search for something common in my stories on the dashboard and see that you cannot scroll 

## Screenshots
(see that the total available results is 242 but you cannot scroll)
![Screen Shot 2020-06-30 at 4 23 51 PM](https://user-images.githubusercontent.com/10720454/86186534-31e07d80-baee-11ea-9ca5-01b210f2048e.png)

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
- search results typeahead should have the ability to scroll through options and select outside of the 5 that render first visible.

## Implementation Brief
- just needs a scrollable div for overflow. Can reference editor too.

**Comment by csossi** [comment]
Verified in QA
