### ISSUE TITLE
Add links to product anchors in all templates

### ISSUE THREAD

**Issue by samitron7** [GoogleForCreators/web-stories-wp#2888]
Please add dummy links back into templates. 

![Screen Shot 2020-06-30 at 10.02.47 PM.png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/97309a1f-3fbe-4ceb-a58e-320c1f456b8f)

**Comment by mariano-formidable** [comment]
@samitron7 Should we link to anything in specific (for each template)?  When we had dummy links before, we were just linking to google.com, is that okay?

**Comment by swissspidy** [comment]
Maybe example.com?

**Comment by samitron7** [comment]
example.com sgtm
