### ISSUE TITLE
Font Template Presets

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#29]
## Feature description

Font presets are made available to the user so they can more easily add consistent and good looking text elements. 

![image](https://user-images.githubusercontent.com/5874851/70653720-03b75100-1c23-11ea-97f3-2601c5e62a13.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by spacedmonkey** [comment]
As discussed in https://github.com/google/web-stories-wp/pull/266 . I have some questions where these presents are stored / defined. It seems likely the these will need to be stored in WP as a custom post type, as these present can be user defined.

**Comment by jauyong** [comment]
Closing this as we have #353
