### ISSUE TITLE
Landing Page: Roboto font not loading

### ISSUE THREAD

**Issue by tomjn** [GoogleForCreators/web-stories-wp#2907]
## Bug Description

Someone forgot to load the Roboto webfont on the github pages site:

<img width="598" alt="Screenshot 2020-07-01 at 15 26 10" src="https://user-images.githubusercontent.com/58855/86255641-42a4f800-bbaf-11ea-99b2-c03562d70b13.png">

Perhaps the developer had Roboto installed on their system and didn't realise? Or 

## Expected Behaviour

I opened the developer console and added `<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet"> `, to get this:

<img width="546" alt="Screenshot 2020-07-01 at 15 28 23" src="https://user-images.githubusercontent.com/58855/86255977-acbd9d00-bbaf-11ea-91d8-6c341b1eadf7.png">

## Steps to Reproduce

Open the site in Chrome or Firefox on MacOS, or any other system that doesn't have Roboto installed at a system level

## Acceptance Criteria

Text that uses the roboto font family should be shown in the roboto font family

## Implementation Brief

Put this in the header:

```html
<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
```

**Comment by swissspidy** [comment]
Thanks Tom!

Pretty sure the font CSS was there when I checked earlier. Let me check again...

**Comment by swissspidy** [comment]
So the font declaration **is** there:

https://github.com/google/web-stories-wp/blob/0a0aaee4b37840c10b5d78fe5d368f09a2ec1d4a/beta/index.html#L715

It's just wrong. Fix imminent.
