### ISSUE TITLE
Color Presets redesign

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#2908]
## Feature Description

**[Product Brief](https://docs.google.com/document/d/1EQ12sD4a1plmMeBu7YMWOdUSg0FeegB9qi2_OlV3Tp0/edit#heading=h.wco7md3p3ukx)**

**[UX Design](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Stories-Stable?node-id=736%3A1175)**

## Reviews
- [x] Product brief reviewed by UX
- [x] Product brief reviewed by eng (TL and/or dev)
- [ ] UX Design reviewed and approved by PM
- [ ] UX Design reviewed and approved by eng
- [ ] Eng design reviewed by TL (if needed)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by samitron7** [comment]
Over of color rules including addition of local and global color to design panel and color picker widget: [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Stories-Stable?node-id=736%3A1175)

**Comment by barklund** [comment]
This ticket is redesign only, not about adding global colors (that work is to be done in #3635).

**Comment by miina** [comment]
There were no more issues in the Sprint backlog so pulling this in. FYI @barklund @bmattb

**Comment by miina** [comment]
@samitron7 Confirming about the split color presets in Figma. Do we want to split the colors only in case of solid colors, or also in case of gradients?

Split colors in case of gradients and solid:
<img width="289" alt="Screenshot 2020-10-06 at 16 53 49" src="https://user-images.githubusercontent.com/3294597/95211177-89c50980-07ec-11eb-9d95-73f41738306d.png">

^ On the last preset here one of the color stops is almost transparent blue, however, making it opaque for the split leaves quite a different impression compared to how it actually looks like, perhaps the splits are meant for solid only?

Split colors in case of solid only and displaying gradients as they are:
<img width="370" alt="Screenshot 2020-10-06 at 16 55 25" src="https://user-images.githubusercontent.com/3294597/95211199-90538100-07ec-11eb-93e4-080bb6e3bbe9.png">

**Comment by samitron7** [comment]
@miina Split are meant for solids only to help indicate the solid color especially if opacity is low. For gradients, you may have multiple colors so we can't do the split.

**Comment by bmattb** [comment]
@o-fernandez In backlog grooming it was flagged that this ticket is dependant on #4104 which won't be completed until Friday / end of sprint, **however** this can be prioritized for week 1 of S40, and still make it into the V1.1 release

**Comment by bmattb** [comment]
tagged with release 1.3 as per roadmap document, moved out of current sprint due to dependancy on #4830

**Comment by csossi** [comment]
Verified in QA
