### ISSUE TITLE
First Time User Experience (FTUE)

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#2909]
## Feature Description

**[Product Brief - focuses on FTUE post plugin activation](https://docs.google.com/document/d/1Q9B6SGID3Rj4KfwwObgz4qmtkUczNHE-4DS-zomY2Pc/edit#heading=h.snvm6t5ev6rj)**

Related effort, but decoupled: Plugin activation #2853

** UX designs in progress?**
 
## Reviews
- [ ] Product brief reviewed by UX
- [ ] Product brief reviewed by eng (TL and/or dev)
- [ ] UX Design reviewed and approved by PM
- [ ] UX Design reviewed and approved by eng
- [ ] Eng design reviewed by TL (if needed)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
Pushing to post stable for actual FTUE, will add a ticket for a FTUE Sample Story. @samitron7 FYI per discussion.

**Comment by samitron7** [comment]
Is this ticket specifically for the sample story or for FTUE within the editor?

Can we create an epic for FTUE and add the following as task. Huge to explore FTUE so this list may grow over time.

**EDUCATION**
1. Drag and drop/masking
2. Media edit mode
3. Add new paragraph text icon
4. Toggle off drop zone
5. Safe Zone
6. Preview mode (specifically how to get back to the editor, sys nav, safe zone)
7. How to get back to dashboard
8. General basics
9. KB Shortcuts

**FIRST TIME EXPERIENCE**
1. Empty cart case for My Stories, Media Upload, Save colors, Save style
2. Templates exploration (zero state in dashboard)
3. Animations

**Comment by bmattb** [comment]
@samitron7 / @o-fernandez - Proposed actions here:

1. as Sam suggests, creation of the FTUE epic. 
2. This ticket gets renamed "A user is presented with FTUE on plugin activation"
3. A new ticket called "FTUE Education" as noted above
4. A new ticket called "FTUE Experience" as noted above

LMK and I'm happy to create the stubs

**Comment by o-fernandez** [comment]
This ticket was originally for actual FTUE, so what Sam is mentioning above, but I'm happy to close this ticket and start the new tickets as we believe the structure should be. 

I like the way @bmattb you outline it. One epic for FTUE Education, one for FTUE Experience, and each of those can later have a bunch of small tickets as Designs are finalized.

**Comment by samitron7** [comment]
Yes to closing this ticket and creating 2 separate epic.

**Comment by o-fernandez** [comment]
@bmattb see above ^^ I'd call those part of 1.3 for now, although some pieces will probably move past release 1.3

**Comment by bmattb** [comment]
FYI - I have created the two epics FTUE Experience (#5494 ) and FTUE Education (#5492 ) - sorry for the delay here.

**Comment by samitron7** [comment]
Thanks @bmattb! FYI: @Cecil921 @angelapgUX
