### ISSUE TITLE
User can apply animations to an element [MVP]

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#2910]
## Feature Description

Applying a single animation to an element
- A user can apply an animation to any one element on the page. 
- After applying an animation, the user can change the duration and delay. 
- A user may set the delay to be based on either: Page Load, Play after an animation on another element completes [NOTE: only elements that already have an animation should be available to select]

**[Product Brief](https://docs.google.com/document/d/11xtdVNrSa16qg9tmg_ACw6vTD8z8wymhkRSgOqkVCa8/edit#heading=h.m0pv6unnoqe)**

**[Designs](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=2%3A47073)**

## Reviews
- [x] Product brief reviewed by UX
- [x] Product brief reviewed by eng (TL and/or dev)
- [x] UX Design reviewed and approved by PM
- [x] UX Design reviewed and approved by eng
- [ ] Eng design reviewed by TL (if needed)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
Assigned ticket to folks for review and feedback on [Product Brief](https://docs.google.com/document/d/11xtdVNrSa16qg9tmg_ACw6vTD8z8wymhkRSgOqkVCa8/edit#heading=h.m0pv6unnoqe)

@barklund @carlos-kelly @dvoytenko @pbakaus @samitron7

**Comment by samitron7** [comment]
Reviewed July 1 and left comments on the brief

**Comment by amgmbs** [comment]
Can't wait to see it implemented!
