### ISSUE TITLE
React Components

### ISSUE THREAD

**Issue by c0b41** [GoogleForCreators/web-stories-wp#2915]
Do you have any plan to publish react component npm, i want to use ui my own cms, but looks like currently platform agnostic.

**Comment by swissspidy** [comment]
Excellent question!

We definitely plan on making this as platform agnostic as possible. The WordPress integration is just the first step.

How exactly these integrations will work and what kind of npm packages we'll publish is still being worked on, so there's nothing concrete to say at the moment.

But once we're finalizing this, we'll definitely provide documentation on how this could be integrated into your CMS of choice.

Hope that helps!

**Comment by swissspidy** [comment]
Closing this one for now.

Once we got to a point where we can publish npm packages etc., we'll have dedicated issues for those efforts.
