### ISSUE TITLE
Recommended design space snapping guidelines in canvas

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#2917]
**[Product Brief](https://docs.google.com/document/d/1HkyGYEp1LmJl91eh4N_OiYVZqK-QDjwLfUKaCpT9zQ4/edit#heading=h.to3r8okkb7z1)**

**[Design](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=8012%3A395927)**

### QA Instructions

1. Add an element to stage
1. Start dragging the element
1. Drag element so that center or edges approach the page edges (for horizontal both safe-zone and danger-zone + vertical) or page center
1. Observe that pink guidelines will be displayed relative to the element (these are full-size guidelines covering the entire workspace)
1. Make sure safe zone is enabled
1. Drag the element edges to the 48px vertical edge margin or safe zone horizontal margin
1. Observe that the pink design space guideline is displayed as the element can snap to it

**Note**: the design space element is also shown when snapping from "the outside" which might be counterproductive, but not a bug for now. Also observe that the design space guideline is also shown when snapping to the top or bottom edge of the safe zone, which partially conflicts with the general horizontal guideline located here. Also not a bug for now.

**Comment by csossi** [comment]
Should changing this copy (colour change) be a part of this ticket (and could instructions be added)?
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/7ba08dde-0e2b-4de4-87b0-bb72e4c06c4e)

**Comment by csossi** [comment]
Verified in QA
