### ISSUE TITLE
Poster images are black square in Firefox

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#2923]
## Bug Description

When a user uploads a video, the generated poster image is a black image. 

## Expected Behaviour

The poster image is not a black image. 

## Steps to Reproduce

- Upload video. 
- Wait for poster to generate. 

## Screenshots

![Screenshot 2020-07-01 at 22 09 27](https://user-images.githubusercontent.com/237508/86333789-4767bb80-bc44-11ea-8a94-776ae60d2154.png)

## Additional Context

- Plugin Version: 1.0.0-beta1
- Operating System: 10.15.5
- Browser: 78.0.1

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Can you share the exact video you've been using?

It may be the case that the first few frames of the video are simply black, and that we need to seek forward a little bit more. Right now we seek forward by 0.5s:

https://github.com/google/web-stories-wp/blob/dbf553c529c0be2feaa279c79f8663fcf35e0c21/assets/src/edit-story/app/media/utils/getFirstFrameOfVideo.js#L30

NB: theoretically we could make this a bit smarter and seek forward as long as the frame's all-black.

**Comment by spacedmonkey** [comment]
I am using the bunny videos from [here](https://riverrock.eu/app/uploads/2018/08/SampleVideo_1280x720_1mb.mp4?_=2). 

It isn't the video, as chrome works. 
<img width="1884" alt="Screenshot 2020-07-02 at 10 06 49" src="https://user-images.githubusercontent.com/237508/86339902-0bd0ef80-bc4c-11ea-9964-3f370b46aa26.png">
and safari
<img width="1904" alt="Screenshot 2020-07-02 at 10 09 48" src="https://user-images.githubusercontent.com/237508/86340013-33c05300-bc4c-11ea-98b7-766ac6bd3c87.png">

**Comment by spacedmonkey** [comment]
Just tested with more 2 different video with same result.

**Comment by swissspidy** [comment]
Ah, I see, it's a Firefox specific. My bad!

I did some quick testing and here's what I found out:

Other than in Chrome, the `canplay` event for the video is fired **twice** in Firefox. However, the first time around, the `seeked` event hasn't been fired yet. So a simple solution is to first wait for `seeked`, and then for `canplay`.

I have a fix ready.

**Comment by spacedmonkey** [comment]
Worth noting that https://github.com/google/web-stories-wp/pull/2914 doesn't fix the issue.

**Comment by merapi** [comment]
> Worth noting that #2914 doesn't fix the issue.

That's Safari only (and other issue, not poster).

**Comment by swissspidy** [comment]
Video that's useful for testing: https://xwp.slack.com/archives/CCCAUAH6F/p1593694867064300

**Comment by csossi** [comment]
Verified in QA
