### ISSUE TITLE
Multisite: Run activation hook on new site creation

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#2929]
## Feature Description

Run activation hook on new site creation on a multisite.

[Example](https://github.com/spacedmonkey/super-simple-events/blob/master/public/class-super-simple-events.php#L332-L349) 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
@spacedmonkey Can you add an estimate here?

**Comment by spacedmonkey** [comment]
Should be very simple. Only making it 2, as we need to write some tests for it.
