### ISSUE TITLE
TypeError: Cannot read property 'elements' of undefined

### ISSUE THREAD

**Issue by prajjawalgupta** [GoogleForCreators/web-stories-wp#2930]
Something went wrong!

The editor has crashed. Please try reloading the page and report the error using the button below.

Apologies for the inconvenience.

Reload
Report Error

its crashing and saying some like this i hope you will able to fix it fast.

**Comment by prajjawalgupta** [comment]
Something went wrong!

The editor has crashed. Please try reloading the page and report the error using the button below.

Apologies for the inconvenience.

Reload
Report Error

**Comment by swissspidy** [comment]
Hi @prajjawalgupta, if you click on "Report Error", it should create a new GitHub issue with the error message and stack trace already pre-filled. Can you please share the whole error message and stack trace with us? You can open your browser's developer tools to get the full error details from the console.

Also, please let us know which browser you are using.

**Comment by swissspidy** [comment]
@prajjawalgupta Would be great to get some more information from you. What did you do when this error appeared? Did you just create a new story? Or perhaps use a template?

**Comment by swissspidy** [comment]
@prajjawalgupta friendly ping! Would be great to get some more information from you. What did you do when this error appeared? Did you just create a new story? Or perhaps use a template?

**Comment by ernee** [comment]
@prajjawalgupta the stable version of the plugin 1.0.0 has been released. I will close your issue now, but please feel free to update and reach out to us in our [WordPress.org support forum](https://wordpress.org/support/plugin/web-stories/) if you should still experience the issue. Happy to help!
