### ISSUE TITLE
Remove .DS_Store when building distribution archive

### ISSUE THREAD

**Issue by hrbrmstr** [GoogleForCreators/web-stories-wp#2931]
Minor nit, but y'all are including `.DS_Store` in the distribution archive (at least in the `v1.0.0-beta.1`)

![image](https://user-images.githubusercontent.com/509878/86360425-58163280-bc40-11ea-9cfb-e47b25df96e3.png)

No sensitive info is in it, but it'd be cleaner install w/o the file.

**Comment by swissspidy** [comment]
Thanks for your report!

You can blame it on me doing last minute testing of the ZIP file 😄
