### ISSUE TITLE
Dashboard: Add integration tests for templates actions

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#2946]
Building off of [#1998 ](https://app.zenhub.com/workspaces/web-stories-5e94d3aced449034e1e9b226/issues/google/web-stories-wp/1998) to establish integration tests for the templates APIs much like the stories suite of tests. This would be best to do after we have established our APIs for explore templates. Work here should include testing explore templates view as well as the detail template view.

**Comment by bmattb** [comment]
After bl review this ticket is confirmed to be a duplicate
