### ISSUE TITLE
Dashboard not listing scheduled stories

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#2951]
## Bug Description

Splitting this out from #2823:

If you save a story to be published in the future, it won't be listed anywhere in the dashboard. You can see it in the "All Stories" view  though.

## Expected Behaviour

The dashboard should list scheduled stories. They have the post status `future`.

## Steps to Reproduce

1. Create new story
1. Set publish date to be in the future
1. Save story
1. Visit Dashboard

## Additional Context

- Plugin Version: `1.0.0-beta.1`
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
Mind if I pick this up?

**Comment by BrittanyIRL** [comment]
I was curious if this was a fix in the dashboard or something in PHP, while looking into it I ended up just fixing it. Maybe took an hour total.

**Comment by BrittanyIRL** [comment]
Moved this back to review because I realized Pascal needs to rereview. Sorry about that!

**Comment by BrittanyIRL** [comment]
@csossi I'm sorry, I merged this after review and am now using this update in another branch to resolve some date stuff. Do you mind testing this on pantheon in staging? You should now see scheduled stories not just published (like this one below). 

<img width="248" alt="Screen Shot 2020-07-17 at 9 39 36 AM" src="https://user-images.githubusercontent.com/10720454/87810282-97807980-c811-11ea-9c47-7776fdac38f1.png">

**Comment by csossi** [comment]
Verified in QA - tested in Main branch:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/e4948c0c-3141-4617-bbde-31a6859ed54a)
