### ISSUE TITLE
Not all fonts are loading

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#2964]
## Bug Description

Currently only 1000 fonts of the 1011 fonts are loading in the REST API request for fonts. 

## Expected Behaviour

All fonts are loaded. 

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Why is that? Is this an issue/limit with the REST API? Something else?

**Comment by spacedmonkey** [comment]
There is a limit of 1000.
