### ISSUE TITLE
Saved Colors: Add button is not working

### ISSUE THREAD

**Issue by ManthanSutariya** [GoogleForCreators/web-stories-wp#2977]
## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Hi there

The issue template is there to be filled out. Can you please share some details about this issue? Screenshots, video, browser version, etc.

**Comment by swissspidy** [comment]
Hi @ManthanSutariya, are you able to provide more information here? A video showing the problem would help immensely!

**Comment by swissspidy** [comment]
@ManthanSutariya Friendly ping! Could you perhaps provide more information here? A video showing the problem would help immensely!

Please note that the "Add" button won't do anything if you've already saved the current color.

Closing this under the assumption that this is the case. Feel free to leave a comment if that's inaccurate.
