### ISSUE TITLE
Templates: allow using only one page from a template

### ISSUE THREAD

**Issue by sarverse** [GoogleForCreators/web-stories-wp#2989]
**Enable selection only one template or page from the template section:**
So whenever I use a template it copies every story in the template. Please allow us to select only one story or page from the said template.

**Alternatives Considered**
A good alternative would be to copy existing story you have already published. This would make it easier to simply make a copy of existing story, edit it, and publish it. Saves time.

**Comment by swissspidy** [comment]
> So when I visit example.com/stories It throw a 404 error. I don't know how Google would auto index the web stories? I have no impressions on web stories right now. What should I be doing to get stories on Google? So I guess a sitemap is required?

Right now we support embedding stories in your regular website/blog using the built-in story embed block. After publishing your story you are directed towards creating a new post to embed the story. This will help both your users and search engines alike to discover your content.
Of course, a sitemap can't hurt, but it's definitely not required.

**Comment by swissspidy** [comment]
> So when I visit example.com/stories It throw a 404 error.

We're tracking implementation of such a page at #3063. Follow that issue for any progress.

> So whenever I use a template it copies every story in the template. Please allow us to select only one story or page from the said template.

@sarangsss29 So what you are saying is that you want to use only one page of a given template, not the whole template? Could you just delete the pages you don't need?

**Comment by LuckynaSan** [comment]
Here is another user's feedback (that is possibly related to this request): https://wordpress.org/support/topic/copy-duplicate-pages-across-templates/. 

The user suggested a way to import a page from multiple templates into one story.

**Comment by BrittanyIRL** [comment]
Hey @LuckynaSan and @swissspidy  -

Now that we have page templates in the editor, do we still want to leave this as a future possible feature or is that a good solution?

**Comment by swissspidy** [comment]
Yeah I think we can close this one 👍
