### ISSUE TITLE
Prevent conflicts with AMP plugin

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#3]
This includes things like changing the post type name, etc.

Slightly related: #2. 

---------------

## QA testing instructions

1. Verify that creating, saving, and viewing stories works with the AMP plugin inactive
1. Verify that creating, saving, and viewing stories works with the AMP plugin active, but the stories experience disabled 
1. When activating the stories experience, both "Stories" options should be visible in the admin menu
1. Verify that creating, saving, and viewing stories works with the AMP plugin active, and the stories experience enabled

**Comment by kmyram** [comment]
@swissspidy Seems to be missing QA-instructions?

**Comment by swissspidy** [comment]
Added some instructions, sorry for the delay.

Please not that this somewhat of a moving target as there is work being done on the AMP plugin at the same time that affects this. See https://github.com/ampproject/amp-wp/pull/4219 and https://github.com/ampproject/amp-wp/pull/4217 for example.

**Comment by csossi** [comment]
Hi @swissspidy - posted a simple story (1 page, background image only), and Chrome's AMP Validator kicked out the following error:
![image](https://user-images.githubusercontent.com/16945664/75565196-88905a80-5a1b-11ea-9e3b-6687de99197c.png)

**Comment by swissspidy** [comment]
The `canonical` tag will only be added once the story is published—not when it's still a draft.

#346 is adding it for drafts too though, so should work fine.
