### ISSUE TITLE
Font Picker: Search fonts

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#30]
## Feature description

This is a follow up to ampproject/amp-wp#3759 

[Fonts Figma spec](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=3138%3A2463)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. User is able to search for fonts
1. After the user enters chars, search results are displayed based on the input
1. If there are no matches for a search, indicate that no matches are found
1. After the user clicks on font picker, the focused is placed on search field

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by ndev1991** [comment]
Do we have any requirements for popular fonts and suggested fonts?

**Comment by swissspidy** [comment]
^ @jauyong @pbakaus @o-fernandez

**Comment by pbakaus** [comment]
^ @samitron7

**Comment by o-fernandez** [comment]
I'd go with what's in [the Figma spec](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=3138%3A2463) for now.

![image](https://user-images.githubusercontent.com/13389997/81008621-3c013b00-8e21-11ea-81e5-f3f98d736f71.png)

**Comment by swissspidy** [comment]
I don‘t think Comic Sans is popular :-)
The design on Figma looks like the old font list from the legacy editor. We need to cone up with a better definition of popular fonts.

**Comment by o-fernandez** [comment]
@samitron7 @pbakaus anything you had in mind when it comes to popular fonts? If not, I'd say we skip this for now. Seems like a plausible enhancement to do later if not readily spec'd. 

Unless there's any opposition, I'd suggest splitting that into its own issue, and keeping the rest of the spec'd items in here. @jauyong

**Comment by ndev1991** [comment]
@pbakaus @o-fernandez @samitron7 Do we have any updates here for popular fonts, suggested fonts?

**Comment by swissspidy** [comment]
Personally I'd say, when opening the fonts dropdown, we should just show the N first fonts from the list. Popular fonts can be looked at later.

**Comment by o-fernandez** [comment]
Agree, per my prior comment I suggest separating the "Popular fonts" into its own ticket. I'll update this ticket to reflect that.

**Comment by pbakaus** [comment]
+1. I'd do popular fonts after launch.

**Comment by miina** [comment]
If this issue addresses search only then it looks like it already has a PR and is in review by https://github.com/google/web-stories-wp/pull/1300 which in addition to preview also implements search. cc @ndev1991 to confirm.

**Comment by ndev1991** [comment]
> If this issue addresses search only then it looks like it already has a PR and is in review by #1300 which in addition to preview also implements search. cc @ndev1991 to confirm.

Yes, that basic features already implemented on #1300 .
1. Input search box focus on open
2. List default fonts lists
3. Search has two separate lists that starts with and includes
4. Recent used fonts feature added (Just temp state for used fonts. Refresh will clean that state)

**Comment by swissspidy** [comment]
I just realized that we could get the most popular fonts from Google Fonts. That would not include system fonts like Arial though, but I don't think that'd be a huge issue.

**Comment by ndev1991** [comment]
> I just realized that we could get the most popular fonts from Google Fonts. That would not include system fonts like Arial though, but I don't think that'd be a huge issue.

That sounds great! Can you post some more details?

**Comment by swissspidy** [comment]
@ndev1991 well, the [Google Fonts API](https://developers.google.com/fonts/docs/developer_api) supports sorting fonts by popularity, so basically we could create something like the existing `fonts.json` file, but just with the top X popular fonts.

<img width="752" alt="Screenshot 2020-05-11 at 15 49 33" src="https://user-images.githubusercontent.com/841956/81569145-2cdd3880-939f-11ea-9cb7-c49b4a289452.png">

Something we can pursue after launch. Unless we want to determine popularity ourselves.

**Comment by pbakaus** [comment]
I think this is great as first step (popularity from Google fonts).

**Comment by ndev1991** [comment]
> @ndev1991 well, the [Google Fonts API](https://developers.google.com/fonts/docs/developer_api) supports sorting fonts by popularity, so basically we could create something like the existing `fonts.json` file, but just with the top X popular fonts.
> 
> <img alt="Screenshot 2020-05-11 at 15 49 33" width="752" src="https://user-images.githubusercontent.com/841956/81569145-2cdd3880-939f-11ea-9cb7-c49b4a289452.png">
> 
> Something we can pursue after launch. Unless we want to determine popularity ourselves.

@swissspidy Do we have any plan to add that fields to current fonts.json file? Maybe fonts.json will be generated by some cron job from php?

**Comment by swissspidy** [comment]
> Do we have any plan to add that fields to current fonts.json file?

No plans yet. We'll get there once we need to implement popularity. Could be either be a field in `fonts.json` or a new `popular-fonts.json` file - we will see.

> Maybe fonts.json will be generated by some cron job from php?

The `fonts.jso`n file is already generated by a cron job _in the repository_. This cannot be done in PHP within the plugin.

**Comment by o-fernandez** [comment]
Agree with @swissspidy - to clarify, no popularity to be implemented as part of this ticket. We can explore this in the future. :)
