### ISSUE TITLE
Templates not loading properly in WP

### ISSUE THREAD

**Issue by Tobe2d** [GoogleForCreators/web-stories-wp#3010]
## When I open create stories from template it show missing assets 

check the screenshot below:

![9HJOI](https://user-images.githubusercontent.com/841956/86583145-13adce00-bf83-11ea-8eab-a17919380332.png)

Hope you can fix or guide on how to fix.

## Additional Context

- Plugin Version: Version 1.0.0-beta.1
- Operating System: Wordpress on cPanel
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
@ammartist Thanks a lot for your report!

Have you tried clearing the cache and hard-refreshing the browser? Does it work in other browsers?

Could you perhaps open your browsers developer tools (press F12 on the keyboard) and check the "Console" tab for any errors? If you go to the "Network" tab, are there any failed requests for images? It should look a bit like this:

<img width="1674" alt="Screenshot 2020-07-06 at 12 26 27" src="https://user-images.githubusercontent.com/841956/86583821-2aa0f000-bf84-11ea-877e-3daede501858.png">

Finally, do you see an image when opening https://google.github.io/web-stories-wp/static/beta/images/templates/beauty/beauty_page1_bg-alt.png directly in your browser?

**Comment by Tobe2d** [comment]
Hi Swissspidy,

I did cleared the cache and I try another browser (edge) on edge it stuck on Please wait...
Back to chrome I did the F12 and below is the screenshot
https://paste.pics/9HKOF

regarding this link https://google.github.io/web-stories-wp/static/beta/images/templates/beauty/beauty_page1_bg-alt.png
yes it open on both browsers chrome and edge

**Comment by swissspidy** [comment]
Thank you, that's already very helpful so far!

In Chrome, after pressing F12, can you do the following too:

1. Go to the "Network" tab
1. select "Img" in the filter below
1. Type "beauty" in the search box on the left
1. Take a screenshot

It should look like this:

<img width="871" alt="Screenshot 2020-07-06 at 13 22 23" src="https://user-images.githubusercontent.com/841956/86588450-ff220380-bf8b-11ea-80bd-e3a808f5df9f.png">

Also, does viewing the templates work in Incognito mode?

**Comment by Tobe2d** [comment]
Here you go:
![9HKV9](https://user-images.githubusercontent.com/841956/86593359-58dafb80-bf95-11ea-93b6-9161fee1b28b.png)

**Comment by swissspidy** [comment]
Thanks a lot @ammartist! It looks like the issue is caused by **Adblock Plus**, which wrongly blocks requests for the images in templates. I recommend disabling the ad blocker on your site so that no images will be blocked.

**Comment by Tobe2d** [comment]
After disabling Adblock Plus the issues remains the same however,  I found out that Malwarebytes' extension was blocking them. 
Now the question will be how to prevent Malwarebytes from blocking them and whitelisting it

**Comment by swissspidy** [comment]
I can confirm that it's indeed the Malwarebytes Chrome extension causing this!

It looks like you can whitelist the domain as follows:

<img width="376" alt="Screenshot 2020-07-06 at 15 39 45" src="https://user-images.githubusercontent.com/841956/86599497-ff77ca00-bf9e-11ea-9dbc-d38e51700821.png">

This did the trick for me.

Note: once we release the stable version of the plugin, the domain will be different from the one in the screenshot, so it might be the case that you'd need to do this again once we release the stable version.

**Comment by Tobe2d** [comment]
Yep, that work's perfectly now ;-)
