### ISSUE TITLE
GSC Error tag amp-story

### ISSUE THREAD

**Issue by mpedrao** [GoogleForCreators/web-stories-wp#3015]
## Bug Description

Google Search Console warns you that you can only have an amp-story derived tag in <body> as shown in the image.
## Expected Behaviour

I sent the amp-story sitemap in Search Console and hours later this warning appeared that the content will not be indexed due to an amp-story tag error in <body>. There should be no such error.

## Screenshots

![github](https://user-images.githubusercontent.com/67908914/86596283-56b27600-bf70-11ea-8139-d986a4d6cbcc.png)

## Additional Context

- Plugin Version: Version 1.0.0-beta.1
- Operating System: linux Ubuntu
- Browser: Brave/Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Hi there

Running your story URL (https://nerdvision.com.br/stories/superman-the-movie-final-cut) through the [AMP validator](https://validator.ampproject.org/) shows that there is 1 issue with AMP validation, which is the one that Search Console is reporting.

The issue is coming from this piece of code:

```html
<noscript><iframe
src="https://www.googletagmanager.com/ns.html?id=GTM-5CKVTZX"
height=0 width=0 style=display:none;visibility:hidden></iframe></noscript>
```

This is not allowed for Web Stories, at least not in this form. For Web Stories, `<amp-analytics>` needs to be used, see https://support.google.com/tagmanager/answer/9205783?hl=en.

Are you using a particular plugin to insert Google Tag Manager on your site? Or did you implement this yourself?

**Comment by mpedrao** [comment]
Hi friend. Thanks for the reply.
I use the wp plugin called Head, Footer and Post Injections. where I put the GTM tag.

**Comment by swissspidy** [comment]
Thanks for your info!

In the plugins settings, please try something like this for now:

```
<?php if ( ! is_singular( 'web-story' ) ) : ?>
<noscript><iframe
src="https://www.googletagmanager.com/ns.html?id=GTM-5CKVTZX"
height=0 width=0 style=display:none;visibility:hidden></iframe></noscript>
<?php endif; ?>
```

Here's a screenshot of the settings page:

<img width="940" alt="Screenshot 2020-07-06 at 15 50 50" src="https://user-images.githubusercontent.com/841956/86600639-95602480-bfa0-11ea-9917-4f141c394091.png">

**This will fix the error.**

However, it means the GTM tag won't be printed for individual Web Stories.

To achieve that, you'd need to follow the instructions at https://support.google.com/tagmanager/answer/9205783?hl=en for creating an AMP container etc.

However, I would recommend you to use a plugin like [Site Kit by Google](https://wordpress.org/plugins/google-site-kit/) to handle this automatically for you. Then it will work automatically and you don't even need the Head, Footer and Post Injections plugin for this.

**Comment by mpedrao** [comment]
![github](https://user-images.githubusercontent.com/67908914/86612791-0a266500-bf87-11ea-9d6e-bc6b93d77e5f.png)
Thank you for your help.
I did exactly as shown in your code, check the image, I deleted the WP cache and tested again on the AMP validator and the error continues.

Did I do something wrong.

ps: I installed the Google Site kit as indicated.

https://validator.ampproject.org/#url=https%3A%2F%2Fnerdvision.com.br%2Fstories%2Fsuperman-the-movie-final-cut

**Comment by swissspidy** [comment]
You need to delete lines 1-4. The only thing you should have in this box is this:

```html
<?php if ( ! is_singular( 'web-story' ) ) : ?>
<noscript><iframe
src="https://www.googletagmanager.com/ns.html?id=GTM-5CKVTZX"
height=0 width=0 style=display:none;visibility:hidden></iframe></noscript>
<?php endif; ?>
```

Nothing else.

---

Have you completed the Site Kit plugin's setup? If so, you should be able to **deactivate** the "Head, Footer and Post Injections" plugin and use GTM via Site Kit.

**Comment by mpedrao** [comment]
friend, thanks for the tips and your time.
I made the changes and now everything is ok!
thank you, you were very helpful.
