### ISSUE TITLE
Settings Data: Publisher Logos

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#3032]
## Feature Description
_See this ticket for more context of page:[https://github.com/google/web-stories-wp/issues/2747]( https://github.com/google/web-stories-wp/issues/2747)_ 
We need to be able to set and remove publisher logos from the dashboard 
<img width="369" alt="Screen Shot 2020-07-06 at 5 32 22 PM" src="https://user-images.githubusercontent.com/10720454/86675617-ab74e180-bfae-11ea-8e02-12ae7959203d.png">

## Additional Context

- Unsure if we should be able to upload multiple files at once 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
- We need the ability to add new logos 
- We need the ability to remove already uploaded logos 
- Response should include image source so we can render it 
- ~On upload should check that image fits specs (Whether the image is a perfect square, Whether it is at least 96 x 96px large) and if not return an error for it.~

## Implementation Brief
- Connection needs to be written and endpoint exposed in includes/Dashboard

**Comment by spacedmonkey** [comment]
See comment here. https://github.com/google/web-stories-wp/issues/3031#issuecomment-656115181

Add CRUD api for publisher settings should very simple.

**Comment by swissspidy** [comment]
This would involve uploading media to `/wp/v2/media` and then sending the resulting image ID to the settings endpoint.
Changing the active publisher logo  as well as removing logos would also mean updating the setting on the settings endpoint.

**Comment by spacedmonkey** [comment]
We could reuse existing endpoints to make this possible. 

`/wp/v2/media` could be used to upload files. 
`/wp/v2/settings` could used to set the publisher logo id. 

This would limit the number of users with `upload_files` and `manage_options` capability in WordPress. This is a limitation, but I am not sure it is a bad one. Not sure that a site admin might want every user to be able to set logos. 

Thoughts @swissspidy

**Comment by bmattb** [comment]
after discussion:

1. use the existing endpoints
2. update the settings api
3. provide example requests for Pea Pod

**Comment by swissspidy** [comment]
Hi @BrittanyIRL,

A quick update on this issue:

We decided to keep things RESTful and DRY and use existing functionality as much as possible.

There's a robust `wp/v2/settings` endpoint for getting the publisher logos information, and [`wp/v2/media`](https://developer.wordpress.org/rest-api/reference/media/) for dealing with media.

Usage for both depends on whether the user is allowed to upload files or manage settings in WordPress. We pass that info via `capabilities.canManageSettings` and `capabilities.canUploadFiles` to the config provider.

There's a maximum upload limit (file size), check `maxUpload` in the config to prevent uploading images that are larger.

The media upload is heavily used in the editor already, so it's easiest to just check that for reference on how upload works.

Examples:

**Change active/default publisher logo:**

```js
await wp.apiFetch({ path: 'wp/v2/settings', method: 'POST', data: {
 web_stories_active_publisher_logo: 123
} });
```

**Update list of all publisher logos:**

```js
await wp.apiFetch({ path: 'wp/v2/settings', method: 'POST', data: {
 web_stories_publisher_logos: [123, 456],
} });
```

**Upload a new image**

* `POST` request to `wp/v2/media`
* `POST` request to `wp/v2/settings` if upload is successful

**Get all publisher logos including their sources:**

1 `GET` request to `wp/v2/settings`, retrieve `web_stories_publisher_logos` from response.
1.`GET` request to `wp/v2/media`, pass array of logo IDs as `include` param to get the image URLs for all publisher logos

**Remove publisher logo**

* `POST` request to `wp/v2/settings` to update both settings
* If image should be permanently deleted, also a request to `wp/v2/media`

**Comment by BrittanyIRL** [comment]
@swissspidy this all is great with me, thanks for the details on implementation!
