### ISSUE TITLE
Failed to save the story

### ISSUE THREAD

**Issue by govindaimladder** [GoogleForCreators/web-stories-wp#3062]
## Bug Description

error: Failed to save the story

Getting issue while trying to publish the story. Even in preview mode its showing 404 page(Not found)

## Expected Behaviour

It should Plublish 
## Screenshots

![image](https://user-images.githubusercontent.com/68001147/86894681-0890a480-c121-11ea-9e67-b862348a8def.png)
![image](https://user-images.githubusercontent.com/68001147/86894914-5d341f80-c121-11ea-82e3-3a1b75fb9298.png)

## Additional Context

- Plugin Version: Latest 
- Operating System: Windows 10/  Wordpress Website : aimladder.in
- Browser: Edge

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
There might be something interfering with the REST API on your WordPress site.

Does this still happen with all other plugins disabled and when disabling any ad blockers?
If you open developer tools in your browser (press <kbd>F12</kbd>) and check the Network tab, do you see any failed requests when clicking on "Save draft"?

**Comment by digitalsetups** [comment]
This happened on one of our test sites. Though we are not sure what's the exact issue, but server down time in the background may cause it. Another time the WP login session expired just after this. Our issue was resolved by just logging into the dashboard again and refreshing the Edit Story screen.

**Comment by swissspidy** [comment]
Glad to hear you were able to resolve the issue. Thanks for the update!

**Comment by govindaimladder** [comment]
@digitalsetups but I tried to login after clearing browser cache and still same issue.

**Comment by swissspidy** [comment]
@govindaimladder Are you saying you are experiencing the same issue? If so, could you perhaps create a new ticket?

There, please answer the following questions:

Does this still happen with all other plugins disabled and when disabling any ad blockers?
If you open developer tools in your browser (press <kbd>F12</kbd>) and check the Network tab, do you see any failed requests when clicking on "Save draft"?

**Comment by govindaimladder** [comment]
Getting this: Please guide.

![image](https://user-images.githubusercontent.com/68001147/86907869-51e9ef80-c133-11ea-8b80-61c3af8181d5.png)


also getting error while going to Story Dashboard
"Unable to Load Stories
Unexpected token < in JSON at position 0"

**Comment by swissspidy** [comment]
@govindaimladder If you click on that `132...` item and then the "Response" tab, what do you see? Can you share a screenshot?

**Comment by govindaimladder** [comment]
I tried it. and this is what codes I am getting.  looks like :view-source of webpage

Thank you for your quick response


![image](https://user-images.githubusercontent.com/68001147/86915851-4b15a980-c140-11ea-9936-51f1d36585af.png)

**Comment by swissspidy** [comment]
That's odd. Have you perhaps somehow disabled the WordPress REST API on your site?

If you check the "Headers" tab and the full request URL, which URL was requested? It should contain something like `/wp-json/...`.

When you  go to Tools -> Site  Health, does it say the REST API is available?

**Comment by govindaimladder** [comment]
Oh. Thank you for your response. Yes you got it. 
![image](https://user-images.githubusercontent.com/68001147/86918355-34715180-c144-11ea-9b5e-a68a813e5969.png)

have issue with REST API. can you please guide how it can be fixed?

**Comment by swissspidy** [comment]
I'm afraid that is a bit beyond our capabilities here for supporting the Web Stories plugin.

I recommend you to check out the Troubleshooting guides at https://wordpress.org/support/ and ask for help there, or contact your hosting provider.

**Comment by govindaimladder** [comment]
Thank you. So much. I checked the issue and will contact hosting provider for further update. Thank so much for your quick response. Will get back if need any help. Hope my this website will pass all site health https://www.aimladder.in/ and story will work after this.
