### ISSUE TITLE
Blocks: Latest Stories

### ISSUE THREAD

**Issue by digitalsetups** [GoogleForCreators/web-stories-wp#3064]
## Feature Description

The existing Web Story block works fine. But there should be a block that displays multiple latest stories.

It could work similarly to the built-in "Latest Posts" block.

**View Modes**

* List View
* Grid View
* Circles
* Carousel

**Display Options**

* Show date
* Show author
* Show "View all stories" link
* Show preview image only (otherwise uses amp-story-player)

**Sorting and Filtering**

* Order by
  * Newest to oldest
  * Oldest to newest
  * A -> Z
  * Z -> A
* Author to filter by
* Number of items (default e.g. 5)
* Filtering by taxonomies supported by the post type (once #489 lands)

## Additional Context

See also #4747

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Hey @digitalsetups, thanks for opening this issue!

We're already looking into the various possibilities for more blocks, and a "Latest Stories" block is certainly planned! It would offer similar functionality like the existing "Latest Posts" block in WordPress, which I think is what you cover in your request (number of items, number of columns, etc.).

The part with supporting a example.com/stories archive page we still have to figure out independently from that. Right now we don't have an archive page.

**Comment by bmattb** [comment]
@o-fernandez / @pbakaus / @amedina - please confirm if this should be added to the stable release scope

**Comment by pbakaus** [comment]
nope, we'll have to do this after 1.0 stable. Great suggestion though!

**Comment by o-fernandez** [comment]
I think this is something that would be great to do and would benefit from a product spec and some UX thinking. Moving to my queue for a product brief.

**Comment by swissspidy** [comment]
Closing as this is being worked on by rtCamp.
