### ISSUE TITLE
Cover Image: Display guidelines / requirements to user

### ISSUE THREAD

**Issue by aditya58singh** [GoogleForCreators/web-stories-wp#3082]
## Feature Description

The Cover Image can't be removed, as we have to replace it. 

Even the size for Cover Page is not recommended it will be hard to make a cover page for a designer.

**Comment by swissspidy** [comment]
> The Cover Image can't be removed, as we have to replace it.

This is a known issue, see #1002.

As for guidelines, that's a good suggestion. We definitely want to add those. In the meantime:

These guidelines apply to the cover image:

* The poster image should be representative of the entire AMP story.
* The poster image should be visible to the user when the AMP story begins. It does not need to look _exactly_ like the first page of the story, but perhaps be an approximation of that.
* If the poster image is derived from a frame in a video, the thumbnail should be representative of the video. For example, the first frame in a video is often not representative.
* Each poster image should meet the recommended minimium size:
  * Portrait: 640px x 853px
  * Landscape: 853px x 640px
  * Square: 640px x 640px

**Comment by aditya58singh** [comment]
Thanks for the cover guidelines 👍

**Comment by o-fernandez** [comment]
Will track this effort as part of #78 which we are currently working on.
