### ISSUE TITLE
Collections of new features / optimization

### ISSUE THREAD

**Issue by Dennis-95** [GoogleForCreators/web-stories-wp#3086]
## Feature Description

1. Add the possibility to add (Via shortcode or selection) in a page the list of all stories made
2. Add Yoast seo integration to manage meta data
3. Add the possibility to show / filter stories by specific categories (Like a blog)
4. Add the possibility to manage structured data

## Alternatives Considered

N/D
## Additional Context

N/D
_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Heya, thanks for your feedback! Those are all very interesting suggestions.

> Add the possibility to add (Via shortcode or selection) in a page the list of all stories made

We are looking into adding a new "Latest Stories" block (#3064) as well as enabling an archive of all stories (#3063). Would those additions help you?

> Add Yoast seo integration to manage meta data

We are working with plugin developers like Yoast SEO to figure out the best way we can enable this.

Curious to hear which kind of features you would be most interested in. Would you want to edit just the title & meta description, or would you expect most/all of the Yoast SEO features to be available to you?

> Add the possibility to show / filter stories by specific categories (Like a blog)

If we would add categories and add categorization to the "Latest Stories" block mentioned above, would that help you?

> Add the possibility to manage structured data

Can you elaborate on that? What kind of structured data would you want to change yourself that is not already handled by plugins like Yoast SEO?

**Comment by Dennis-95** [comment]
Thanks a lot for your time! Here my answers:

> We are looking into adding a new "Latest Stories" block (#3064) as well as enabling an archive of all stories (#3063). Would those additions help you?
 
Yes, that would be nice additions! The reason of my request is that Google suggested to treat stories in the same way as a normal URL, and then linking them too from the websites. The shortcode move, however, will help to add stories where gutenmberg is not enable (Elementor builder, divi builder ecc..)
 
> We are working with plugin developers like Yoast SEO to figure out the best way we can enable this.
>
> Curious to hear which kind of features you would be most interested in. Would you want to edit just the title & meta description, or would you expect most/all of the Yoast SEO features to be available to you?

I think that just title and meta description are useful, and maybe the possibility to edit how the link preview is shown via social. The rest of features are probably useless

> If we would add categories and add categorization to the "Latest Stories" block mentioned above, would that help you?
 
Yes and not! The filter you mentioned is a good feature, but i imagine a filter on"all stories archive page" to make a blog-like result, something like
![Cattura](https://user-images.githubusercontent.com/45852903/87028737-5bc92c80-c1df-11ea-9ada-56b23efc9b62.PNG)
or like 
![Cattura2](https://user-images.githubusercontent.com/45852903/87028819-77343780-c1df-11ea-9d71-b43ed34a16f0.PNG)
 I requested this feature because it will be very useful to have stories structured like a blog page, basically exactly in this way: https://claudia-makeup.com/blog-trucco/ 
 
> Can you elaborate on that? What kind of structured data would you want to change yourself that is not already handled by plugins like Yoast SEO?

Google suggest here 4 structured data that works with web stories, i imagine a section where manage those type of data, or better that data will be autofilled when i add a video (risky in my opinion)
link: https://developers.google.com/search/docs/guides/enable-web-stories#implement

**EDIT:** I forgot to mention the generation of a feed, something like /stories/feed to send stories to 3part software (Google news publish center?)

I take this opportunity to report and ask another 2 things if possible:

1) I tested the plugin on my websites (https://claudia-makeup.com/stories/trucco-anni-2000-stories/) but i saw tons of errors in my search console:

This tag is required "amphtml engine v0.js script" miss or wrong.

You have to add extension JavaScript "amp-story" per il tag "amp-story-page".

Javascript not alloweed: </script> </amp-analytics> </amp-story><script src="https://claudia-makeup.com/wp-content/cache/min/1/6b2231b212646e5bb66ad83c9b9f8934.js" data-minify="1" defer></script></body></html>

Is that a plugin error? Is that just reported?

2) This is more a seo oriented question, but maybe you can help me. If i make a short story of a long and exhaustive article, is this considered duplicated content? Basically the 2 URL will share almost the same text and im not really sure if still worth use it or not

https://claudia-makeup.com/stories/trucco-anni-2000-stories/
https://claudia-makeup.com/idee-make-up/trucco-anni-2000/

I hope all its clear, thanks a lot!

**Comment by swissspidy** [comment]
> The shortcode move, however, will help to add stories where Gutenberg is not enable (Elementor builder, divi builder ecc..)

Our focus is currently on the Gutenberg blocks as these provide by far a better user experience than shortcodes. But we'll keep it in mind 👍 

> I requested this feature because it will be very useful to have stories structured like a blog page

Totally! I think we will get to something like this eventually.

> I forgot to mention the generation of a feed, something like /stories/feed to send stories to 3part software (Google news publish center?)

Good point. Your Stories RSS Feed is available via https://claudia-makeup.com/feed/?post_type=web-story. We'll make sure to make this easier to discover.

Not sure about Google News though, as there are different requirements there. It might be best left to other plugins to implement this.

> Google suggest here 4 structured data that works with web stories, i imagine a section where manage those type of data, or better that data will be autofilled when i add a video (risky in my opinion)

Noted! I'm sure we can find a good solution here. I will create a new ticket for this enhancement.

> I tested the plugin on my websites (claudia-makeup.com/stories/trucco-anni-2000-stories) but i saw tons of errors in my search console:

It appears that you are using the WP Rocket WordPress plugin, which is not currently compatible with Web Stories. If possible, disable it for Web Stories specifically, or disable individual features that optimize JavaScript.

> If i make a short story of a long and exhaustive article, is this considered duplicated content? Basically the 2 URL will share almost the same text and im not really sure if still worth use it or not

Excellent question! From what I've seen, this is a very common approach for a lot of sites, so I think it's fine to do this. In your article, you could then use the "Story Embed" block to link to your story.

**Comment by Dennis-95** [comment]
> The shortcode move, however, will help to add stories where Gutenberg is not enable (Elementor builder, divi builder ecc..)
> Our focus is currently on the Gutenberg blocks as these provide by far a better user experience than shortcodes. But we'll keep 
it in mind 👍

Thanks a lot!

Totally! I think we will get to something like this eventually.

🔝

> Good point. Your Stories RSS Feed is available via https://claudia-makeup.com/feed/?post_type=web-story. We'll make sure to make this easier to discover.

Oh didnt see that, thanks!

> Not sure about Google News though, as there are different requirements there. It might be best left to other plugins to implement this.

DO you have any idea about plugin should i use?

> Noted! I'm sure we can find a good solution here. I will create a new ticket for this enhancement.

Thanks!

> It appears that you are using the WP Rocket WordPress plugin, which is not currently compatible with Web Stories. If possible, disable it for Web Stories specifically, or disable individual features that optimize JavaScript.

Sure, i will do  it!

> Excellent question! From what I've seen, this is a very common approach for a lot of sites, so I think it's fine to do this. In your article, you could then use the "Story Embed" block to link to your story.

Nice! i tried to use it in my post, but it seems the embed infinite loading for some reason: https://claudia-makeup.com/idee-make-up/trucco-anni-2000/#leggi-larticolo-nellinnovativo-formato-web-stories

do you have any suggestion? ot its a bug?

EDIT: Maybe i spotted another but: Desktop version of my stories works fine, mobile version show a weird bug on images
https://claudia-makeup.com/stories/trucco-anni-2000-stories/


![Screenshot_20200710-132350__01](https://user-images.githubusercontent.com/45852903/87149622-e75ebe00-c2b0-11ea-9857-9a32eb6a08ec.jpg)
![Screenshot_20200710-132426](https://user-images.githubusercontent.com/45852903/87149631-e9c11800-c2b0-11ea-9a01-67dc19f04710.jpg)

**Comment by swissspidy** [comment]
> Do you have any idea about plugin should i use?

I've used a Google NEws add-on for Yoast SEO in the past, but I'm sure there are others.

> Nice! i tried to use it in my post, but it seems the embed infinite loading for some reason:

Looks like WP Rocket is causing some issues here as well, and is removing the JavaScript needed here. Try clearing the cache in WP Rocket or temporarily disabling the plugin to see if it works then.

> EDIT: Maybe i spotted another but: Desktop version of my stories works fine, mobile version show a weird bug on images

Seems like issues were not loading correctly. Does this still happen after clearing the cache on your phone? Can't reproduce it right now so it's hard to tell.

**Comment by swissspidy** [comment]
Hi @Dennis-95 

Just a quick information: I've created a few follow-up tickets for some of your ideas / requests. Feel free to follow those for any updates on them, or otherwise keep an eye open for any new plugin releases :-)

Besides the WP Rocket issue with the Story Embed block, I believe the only outstanding issue is the one with the mobile version.

**Comment by Dennis-95** [comment]
> I've used a Google NEws add-on for Yoast SEO in the past, but I'm sure there are others.

Thanks!

> Looks like WP Rocket is causing some issues here as well, and is removing the JavaScript needed here. Try clearing the cache in WP Rocket or temporarily disabling the plugin to see if it works then.

Oh, it can be, after disabling the cache the mobile version of my issues seems fixed, but not the desktop one. Do you have any idea about the .js file that should i exclude from wp rocket optimization?

> Just a quick information: I've created a few follow-up tickets for some of your ideas / requests. Feel free to follow those for any updates on them, or otherwise keep an eye open for any new plugin releases :-)

Sure, thanks a lot!

**Comment by ernee** [comment]
Hi @Dennis-95 !

> Oh, it can be, after disabling the cache the mobile version of my issues seems fixed, but not the desktop one. Do you have any idea about the .js file that should i exclude from wp rocket optimization?

I've experienced similar issues on my test site. Could you temporarily disable the  _Combine JavaScript files_  option in WP Rocket? This may address the Story Embed Block issue/ errors.

**Comment by Dennis-95** [comment]
> Hi @Dennis-95 !
> 
> > Oh, it can be, after disabling the cache the mobile version of my issues seems fixed, but not the desktop one. Do you have any idea about the .js file that should i exclude from wp rocket optimization?
> 
> I've experienced similar issues on my test site. Could you temporarily disable the _Combine JavaScript files_ option in WP Rocket? This may address the Story Embed Block issue/ errors.

I tried to disable the plugin but no way, still stucked in this infinite loading!
![Cattura](https://user-images.githubusercontent.com/45852903/87190536-f0707f00-c2f2-11ea-9de6-4c08bbc4b297.PNG)

**Comment by ernee** [comment]
@Dennis-95 thanks so much for checking and reporting back!

You may be aware, but if you append a query string like _?nocache_  at the end of your URL this allows a preview of WP Rocket's optimizations disabled. Like you correctly reported, the issue with the infinite loading of the embed still persists (however, the errors from Search Console should subside with _Combine JS_ disabled for now). 

In the browser tools, disabling this request from the [Rebar plugin](https://codecanyon.net/item/rebar-reading-progress-bar-for-wordpress-website/23941493) resolves the infinite loading of the embed: 

https://claudia-makeup.com/wp-content/plugins/rebar/js/rebar.min.js?ver=2.0.2

Can you safely disable this plugin to check if this helps?

**Comment by Dennis-95** [comment]
> @Dennis-95 thanks so much for checking and reporting back!
> 
> You may be aware, but if you append a query string like _?nocache_ at the end of your URL this allows a preview of WP Rocket's optimizations disabled. Like you correctly reported, the issue with the infinite loading of the embed still persists (however, the errors from Search Console should subside with _Combine JS_ disabled for now).
> 
> In the browser tools, disabling this request from the [Rebar plugin](https://codecanyon.net/item/rebar-reading-progress-bar-for-wordpress-website/23941493) resolves the infinite loading of the embed:
> 
> https://claudia-makeup.com/wp-content/plugins/rebar/js/rebar.min.js?ver=2.0.2
> 
> Can you safely disable this plugin to check if this helps?

You are awesome, disabling rebar (The top bar that represent the % of text reading) fix the problem with the loading, is this a plugin (wp stories) bug or a rebar problem?

Thanks a lot!

**Comment by ernee** [comment]
@Dennis-95 We'll need to investigate further to see where the problem lies. Your report here has certainly helped! We'll follow up when we have more information. Thank you!

**Comment by ernee** [comment]
@Dennis-95 just a quick follow up that a fix is being worked on for the conflict with the Rebar plugin. You can follow issue #3245 for updates.

**Comment by Dennis-95** [comment]
> @Dennis-95 just a quick follow up that a fix is being worked on for the conflict with the Rebar plugin. You can follow issue #3245 for updates.

Thanks a lot, you are awesome!

**Comment by swissspidy** [comment]
I just left a comment on #3245 about the Rebar plugin conflict, but wanted to mention it here too. Basically, the issue will be fixed by **Tuesday next week**. There is no need to update the plugin or anything.

If you want to test the bugfix already today, head over to https://cdn.ampproject.org/experiments.html and (temporarily) opt-in to the nightly channel. Then, try adding a new embed block with the Rebar plugin active. If that does still not work for you, please leave a comment on #3245.

Closing this issue now since all other issues have been resolved or spun off into their own tickets.

Thanks again for your help!
