### ISSUE TITLE
Jetpack Integration for Metadata

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#3092]
## Task Description

Splitting this out from #113:

Let's make sure Jetpack's SEO features and the like work with the Web Stories plugin. For this, we might need to submit a PR upstream.

Patching https://github.com/Automattic/jetpack/blob/master/functions.opengraph.php to use `web_stories_story_head`

**Comment by spacedmonkey** [comment]
I did a little discovery into this and was hard to test as the SEO tools have become a paid for feature. To test this we need to have the seo tools working locally. 

However, once we work this membership etc, it should be simple enough. 
Consider this [method](https://github.com/Automattic/jetpack/blob/3aa604e282c3ea7694d2a17dc169c0ac7f983a6c/modules/seo-tools/jetpack-seo.php#L11-L46). It should be a matter to hook in a couple of actions.

**Comment by gravityrail** [comment]
It's probably more fruitful to integrate with Jetpack's meta tags (e.g. [functions.opengraph.php](https://github.com/Automattic/jetpack/blob/master/functions.opengraph.php)) than the SEO feature directly, which as you point our are a paid feature and therefore used by fewer people.

**Comment by swissspidy** [comment]
That file, https://github.com/Automattic/jetpack/blob/master/functions.opengraph.php, has `add_action( 'amp_story_head', 'jetpack_og_tags' );`

Let's send them a PR to change this to use the `web_stories_story_head` hook. Then this should just work.

**Comment by spacedmonkey** [comment]
This is the original PR https://github.com/Automattic/jetpack/pull/13416

Should we remove the this code, as amp stories in the AMP plugin are not a thing anymore? 

I think we need to improve `Jetpack_AMP_Support`. Our plugin adds in [is_amp_endpoint](https://github.com/google/web-stories-wp/blob/a8d4ea95e583889fa042fffc5ea1ac81b9f30172/includes/plugin-compat/amp.php#L40
). But what if you have jetpack, amp and web stories installed?

**Comment by swissspidy** [comment]
I don‘t think we need to change anything else beyond the filter name. But a quick test will tell us more.

**Comment by spacedmonkey** [comment]
>I don‘t think we need to change anything else beyond the filter name. But a quick test will tell us more. 

Should we keep existing action or replace it ?

**Comment by swissspidy** [comment]
We can safely replace it

**Comment by spacedmonkey** [comment]
I have patched jetpack to use the new action name. But was unable to test locally. Hopefully we hear back from the jetpack team. 

https://github.com/Automattic/jetpack/pull/17399

**Comment by swissspidy** [comment]
Yay this got merged super quick!

Now just need to test this properly. I'll see if I can get thee plugin running loccally, or alternatively test it on my personal site.

**Comment by o-fernandez** [comment]
What's the right way to test this? @swissspidy ? Is it needed for me to do UAT on this?

**Comment by swissspidy** [comment]
I can take this one @o-fernandez 👍

**Comment by swissspidy** [comment]
So while this works great, it results in duplicate Open Graph tags being printed because Jetpack does not remove existing ones.

Seems like they'd need to do this:

```php
$instance = Google\Web_Stories\get_plugin_instance()->discovery;
\remove_action( 'web_stories_story_head', [ $instance, 'print_open_graph_metadata' ] );
\remove_action( 'web_stories_story_head', [ $instance, 'print_twitter_metadata' ] );
```

Not sure if they're open to do this.

Alternatively we remove those two actions if we detect Jetpack.

@spacedmonkey thoughts?
