### ISSUE TITLE
Dashboard: Update document title when changing routes

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#3097]
## Feature Description

In #2750 we are going to rename the "Dashboard" item in the WordPress admin menu to "My Stories", since that is the default/primary view.

That means when you click on the menu item, you see the "My Stories" view, yet the document title (`<title>`) still says `Dashboard ‹ Web Stories — WordPress`.

I suggest to update the document title according to navigation. So when I click on "My Stories", the document title should be updated to `My Stories ‹ Web Stories — WordPress`, when I visit "Explore Templates" it should say `Explore Templates ‹ Web Stories — WordPress`, etc.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
Do we want this to be translated? `__(
    'My Stories ‹ Web Stories — WordPress',
    'web-stories'
  ),` vs ` 'My Stories ‹ Web Stories — WordPress'`

**Comment by swissspidy** [comment]
Ah, I should have made this more clear.

Yes, the document title should be translatable, but differently.

I'd do it like this:

```js
const adminTitle = __( 'Web Stories', 'web-stories' );
const currentScreenTitleThatChangesDynamically = __( 'My Stories', 'web-stories' );

/* translators: Admin screen title. 1: Admin screen name, 2: Network or site name. */
const adminTitle = sprintf( __( '%1$s &lsaquo; %2$s &#8212; WordPress' ), currentScreenTitleThatChangesDynamically, adminTitle )
```

We could also provide parts of this via PHP to make the coupling less tight:

```js
const adminTitle = useConfig(); // returns '%s &lsaquo; Web Stories &#8212; WordPress'
const currentScreenTitleThatChangesDynamically = __( 'My Stories', 'web-stories' );

/* translators: Admin screen title. %s: Admin screen name. */
const adminTitle = sprintf( adminTitle, currentScreenTitleThatChangesDynamically );
```

**Comment by BrittanyIRL** [comment]
ah ok, noted. i'll update how the translation is getting done.

**Comment by csossi** [comment]
Verified in QA
