### ISSUE TITLE
Google News Support

### ISSUE THREAD

**Issue by digitalsetups** [GoogleForCreators/web-stories-wp#3107]
## Feature Description

We suggest to add 'genres' taxonomy as in Google News Publisher like Opinion, Satire, User Generated, Blog, Ed-Op, and more that can be chosen on Edit Story screen. 

~Also add categories and tags to organize stories within Edit Story screen.~ -> #489

## Additional Context

In reference to  #3086, we can use categories in breadcrumbs markup either SEO Yoast or as a built-in feature. Genres can be used in Article/NewsArticle markup and also in Stories Sitemap (now sitemaps are supported by default in WP) if the Article type is NewsArticle in markup. News sitemap generated by Yoast will be helpful as a reference. 

We can also use genres, categories, and tags on archive pages #3063 and as filters in Latest Stories block #3064 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Just to clarify, you would want to use all three taxonomies: genre, category, and tags?

That seems like quite some work to maintain these for every story you create.

**Comment by swissspidy** [comment]
Tempted to split out Genres support into its own ticket as it's really a Google News specific feature.

**Comment by digitalsetups** [comment]
> Just to clarify, you would want to use all three taxonomies: genre, category, and tags?
> 
> That seems like quite some work to maintain these for every story you create.

Yes, it does but it's normal for us. For Google News we need to manage 'Sections' (Categories in WP) and 'Genres' (Custom Taxonomy or an option by Yoast for News). The rest, tags are used for internal searches, schema markup keywords, and grouping sections for 'common contexts' generally. 



> Tempted to split out Genres support into its own ticket as it's really a Google News specific feature.

That's great. Please add 'Sections' (Categories) as well as news are fetched from website by Google News based on their section added to the Publisher center.

**Comment by swissspidy** [comment]
To summarize the Genres part:

* Genre could be used for the schema markup
* Genre could be used for Google News sitemap (if stories are surfaced in Google News)
* Genre could be used for filtering in the 'Latest Stories' block.

A follow-up question to this:

If you could just use Yoast SEO + Yoast's News SEO extension with stories, would this cover your needs?

> Please add 'Sections' (Categories) as well as news are fetched from website by Google News based on their section added to the Publisher center.

To clarify: would you want a separate 'Sections' taxonomy, or does the WordPress built-in 'Categories' taxonomy work?

-----

NB: Tags and categories are covered by #489, updated the issue description accordingly.

**Comment by swissspidy** [comment]
@digitalsetups friendly ping

**Comment by digitalsetups** [comment]
@swissspidy Sorry for the delay in response. 

The summary for 'Genres' is perfect. 

> If you could just use Yoast SEO + Yoast's News SEO extension with stories, would this cover your needs?

It's true only in the case when Yoast adds support for 'Yoast for News' meta data for Web Story post type. Only then, we shall be able to choose the 'Genre'. And Web story adds support for 'Categories' taxonomy to let that post to be in 'Category Feeds' which is fetched by Google. 

Relying on Yoast News for 'News type stories' is better in most cases. This way, we can have general sitemap for web stories and another sitemap generated for only news type stories by Yoast. 

This requires Yoast News as well other Yoast meta data options to be there in Web Stories and also 'Categories' taxonomy support for Web Story. 

**Another concern:** If we rely for 'Genres' on Yoast meta data, then how would be able to filter posts based on 'genres' in 'Latest Stories' block? What if Yoast News is not installed and we are relying on some other plugin for News like Jetpack news sitemap? From the 'genres' will come for news sitemap and also for 'filtering' in 'Latest Stories' block?

> To clarify: would you want a separate 'Sections' taxonomy, or does the WordPress built-in 'Categories' taxonomy work?
Yes, as metnioned above, adding support for 'built-in Categories taxonomy' would be fine and works best.

**Comment by swissspidy** [comment]
Those are very good points, thanks!

> It's true only in the case when Yoast adds support for 'Yoast for News' meta data for Web Story post type.
> This requires Yoast News as well other Yoast meta data options to be there in Web Stories and also 'Categories' taxonomy support for Web Story.

We are working on making this happen :-) Hence the question.

> Relying on Yoast News for 'News type stories' is better in most cases. This way, we can have general sitemap for web stories and another sitemap generated for only news type stories by Yoast.

I figured as much 👍 Thanks for your input.

> If we rely for 'Genres' on Yoast meta data, then how would be able to filter posts based on 'genres' in 'Latest Stories' block? What if Yoast News is not installed and we are relying on some other plugin for News like Jetpack news sitemap? From the 'genres' will come for news sitemap and also for 'filtering' in 'Latest Stories' block?

We would build the Latest Stories block in such a way that it would allow filtering by any category available, be it 'Categories', 'Genres', or 'My-Super-Awesome-Tags' added by some other plugin.

**Comment by digitalsetups** [comment]
> We would build the Latest Stories block in such a way that it would allow filtering by any category available, be it 'Categories', 'Genres', or 'My-Super-Awesome-Tags' added by some other plugin.

That's perfect. Just to clarify: even if Yoast News is not there, we will still have Genres there? Because, I haven't yet checked if Yoast registers those 'fixed set of Genres' as a custom taxonomy or just fixed-valued meta option. If its not a custom taxonomy then, will the filter for 'genres' still be available in Latest Stories block?

**Comment by swissspidy** [comment]
Ah that's a good point! The genre in Yoast News is indeed just a meta option, not a custom taxonomy. That would not really make it possible to add a filter to the block.

So it seems like we're back on square 1 :-)

**Comment by ernee** [comment]
Just sharing another use case for Google News support: https://github.com/google/web-stories-wp/issues/3401#issuecomment-692919547
Note the following plugin is being used to generate the RSS feed: https://wordpress.org/plugins/gn-publisher/

**Comment by spacedmonkey** [comment]
I have a plugin for [google news sitemap plugin](https://github.com/spacedmonkey/simple-google-news-sitemap). I could work on adding web stories support for it.

**Comment by swissspidy** [comment]
Closing this because there are existing plugins out there to achieve this.
