### ISSUE TITLE
Creating new story from template crashes editor

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#3109]
## Bug Description

_Introduced in #3094._

Creating a new story by using one of the templates completely breaks the editor.

That's because some PHP globals are not properly set, leading to `null` being passed as the `storyId` to the editor instead of the actual story ID.

A hotfix was added in #3110.

#3094 was ultimately reverted and regression tests have been added in #3129.

## Expected Behaviour

Creating a new story from a template should work without issues.

## Steps to Reproduce

1. Go to "Explore Templates" in the Dashboard
1. Click on "Use template" on any template.
1. Notice how story editor is broken.

## Screenshots

<img width="1680" alt="Screenshot 2020-07-09 at 19 48 59" src="https://user-images.githubusercontent.com/841956/87073170-3fe47b80-c21d-11ea-8a7e-920eb8771ac3.png">

## Additional Context

- Plugin Version: `1.0.0-beta.1`
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
It might have been broken by 500cdb7854b6f32bf2c7abcfa6fbb36222a7c47e, #3094.

**Comment by swissspidy** [comment]
Assigning myself to add an E2E test for this.

**Comment by o-fernandez** [comment]
Moved this to "Ready for Sprint" as I hope we can just work on it soon? Thanks @swissspidy for monitoring and filing.

**Comment by swissspidy** [comment]
@o-fernandez Well sort of, I already fixed it :-) Gonna add tests tomorrow to verify the fix and prevent future regressions.
