### ISSUE TITLE
Scale Anchor Misalignment in Bounce & Zoom Animation Parts

### ISSUE THREAD

**Issue by maxyinger** [GoogleForCreators/web-stories-wp#3115]
Some items that are meant to scale together are slightly misaligned when animating in. May be a precision error or transform-origin not being applied properly.

Primarily seen with link dots. Visible in Fashion & Fitness template on link pages.

![87084800-6e9a2c00-c1f4-11ea-88ac-0e527a97dd10.png](https://images.zenhubusercontent.com/5ea0a3e2f739259b2b0b092a/093f3e0f-b2aa-459b-82d5-587dbb679a72)

https://github.com/google/web-stories-wp/pull/3112#issuecomment-656321512

**Comment by bmattb** [comment]
not for stable as per @samitron7
