### ISSUE TITLE
Invalid AMP due to broken style tag

### ISSUE THREAD

**Issue by ghost** [GoogleForCreators/web-stories-wp#3124]
Hello, from the WP you cannot access the code to modify parameters or metadata.
When sending the stories to Google Search Control, it tells me that they are not validated for AMP.
The problem is:
Only "style" tags with "amp-boilerplate" and "amp-custom" are allowed, and can only be placed in the document header.
Thank you very much, greetings

**Comment by swissspidy** [comment]
Hi @MeryEU, please share the URL to the story you've created so we can better assist you. It's likely that another plugin (e.g. a caching or performance plugin) of yours is interfering with Web Stories.

**Comment by ghost** [comment]
Yes, 

https://www.cronicasdelaenfermedad.com/stories/cronicasdelaenfermedad/

I have plugin sg optimizer, asset cleanup

Thanks, this is my first story, there are more what the same problem.

**Comment by swissspidy** [comment]
Hi there

Please update to version 5.5.8 of SG Optimizer if you haven't already. That version fixes an incompatibility with Web Stories.

Looking at your story I don't see any AMP validation errors now, so it seems like you already updated and the issue is resolved!

**Comment by ghost** [comment]
Yes it true, thanks so much, is so cool stories
