### ISSUE TITLE
Leverage useResizeEffect in InspectorProvider

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#313]
There's still a TODO for that:

https://github.com/google/web-stories-wp/blob/4afcdcba7610906c72d9537fbe4472204375be9b/assets/src/edit-story/components/inspector/inspectorProvider.js#L49-L52

`useResizeEffect` has since been implemented.

**Comment by merapi** [comment]
Issue 1 - if you start from a small window and make it big, you will not be able to enlarge the Layers panel.

Issue 2 - if you start from a big window, resizing down the window will hide other panels.

https://drive.google.com/open?id=1girEMi09cD5PF9ukc-dHB4lHvBXf_sc4

`useResizeEffect` will fix Issue 1, it's pretty easy, should we also fix Issue 2? is it an issue? @swissspidy
