### ISSUE TITLE
MonsterInsights Integration

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#3130]
## Feature Description
MonsterInsights's plugin [Google Analytics Dashboard](https://en-gb.wordpress.org/plugins/google-analytics-for-wordpress/) is an extremely popular WordPress, installed over 2 millions times. Web stories should integrate it's existing analytics to work with this plugin. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
Related: https://github.com/google/web-stories-wp/issues/2731

**Comment by swissspidy** [comment]
Briefly chatted with Chris from Awesome Motive; they will look into adding support for Web Stories as part of their addon offering.
