### ISSUE TITLE
Display fallback message if JavaScript is disabled

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#3132]
## Feature Description

Right now, when JavaScript is disabled users are stuck on a `Loading...` message when trying to open the editor or the dashboard.

It would be trivial to add a fallback message like on the block editor that says:

```
The Web Stories editor requires JavaScript. Please enable JavaScript in your browser settings.
```

## Additional Context

What users see when opening Gutenberg and JavaScript is disabled:

<img width="1045" alt="Screenshot 2020-07-21 at 11 40 06" src="https://user-images.githubusercontent.com/841956/88038841-0da11b00-cb47-11ea-8a5e-ad028688bf64.png">

What users see when opening the story editor and JavaScript is disabled:

<img width="1010" alt="Screenshot 2020-07-21 at 11 40 18" src="https://user-images.githubusercontent.com/841956/88038874-1d206400-cb47-11ea-97da-763e652cd398.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

* Can follow what WordPress does:  
    https://github.com/WordPress/wordpress-develop/blob/c2aaa14d57fd84fef1d7fd4c29ad8873014bbe9f/src/wp-admin/edit-form-blocks.php#L434-L467

**Comment by o-fernandez** [comment]
@swissspidy I think your suggestion of the message is perfectly reasonable, and it makes sense to align it with the same UI that WP uses for posts. Could we just go with that and remove the UX dependency? 

Moved to ready for sprint for your evaluation, but feel free to kick it back to UX needed as necessary.

**Comment by swissspidy** [comment]
Sounds good to me!
