### ISSUE TITLE
Letterboxing when viewing story via Instagram in-app browser

### ISSUE THREAD

**Issue by mattyrose** [GoogleForCreators/web-stories-wp#3133]
## Bug Description

I'm attempting to use web stories as my Instagram profile link to house various links. The stories work great in my browser on both desktop and mobile, but when I open with Instagram specifically (I'm not sure what they use as a browser) it creates a margin at the top of the page that cuts off the stories, and I can't seem to replicate anywhere else. It very well may just be something on Instagram's side, but my technical knowledge is very limited and wanted to throw it out there- if this is not a fixable bug, I understand.

## Expected Behaviour

If I open the link on a regular mobile browser, it works perfectly, but it is creating an extra margin when opened on Instagram and cutting off content.

## Steps to Reproduce

Opening a story link through the website URL option in an Instagram profile. (Not currently live on my page but can add it back if needed)

## Screenshots

Instagram viewing:
![C6BF9886-4417-41D7-B5E9-9CC2A3717F2E_1_105_c](https://user-images.githubusercontent.com/68116681/87166188-34369a80-c299-11ea-8c62-09b1455b8b64.jpeg)

Mobile browser viewing:
![7C1A096C-DEAD-4BDD-BA24-EC558FFB8EC6_1_105_c](https://user-images.githubusercontent.com/68116681/87166231-41538980-c299-11ea-9c3d-ab5a03794acd.jpeg)

## Additional Context

- Plugin Version: 1.0 Beta
- Operating System: iOS 13.5.1
- Browser: Instagram (does not happen in Facebook's mobile browser)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Thanks for raising this! Interesting use case :-)

If you change your profile link to a story like https://preview.amp.dev/documentation/examples/introduction/stories_in_amp real quick, does that still happen?

**Comment by mattyrose** [comment]
Oh very interesting- nope, that link works perfectly.

**Comment by swissspidy** [comment]
Thanks for your speedy reply! That's good to know. We'll definitely look into this.

**Comment by mattyrose** [comment]
Thanks for looking into it! Let me know if/how I can help at any point.

**Comment by bmattb** [comment]
assumption from Pascal - reduced space in the browser is causing the letterboxing.  Paul did request from AMP that a blurred background scaled up is used instead as a solution.

**Comment by mattyrose** [comment]
Hey guys- just wanted to circle back and share that I ended up embedding this web story into a page at 100% width, and it fixed the issue. I know it's very low on the priority list of things to explore, but wanted to share that it works flawlessly if embedded into a page or post.

**Comment by bmattb** [comment]
@pbakaus / @o-fernandez please confirm (and add release label) if this is needed for Stable, thx

**Comment by pbakaus** [comment]
Not need for stable.

**Comment by o-fernandez** [comment]
@swissspidy @choumx is this something dev can propose a solution for and add SPs? This issue came up multiple times during the beta period and we'd want to ensure this use case of opening and rendering stories properly when opened from IG works properly.

**Comment by swissspidy** [comment]
I'm not so sure about that. Given that we use the aspect-ratio feature in the AMP story format for this, I think this might be more complex and requires some knowledge of how the player itself works. Perhaps it requires aspect ratio changes (which would have high impact), or perhaps it's even a non-issue.

cc @pbakaus because you worked closely on the aspect ratio parts with Dima if I'm not mistaken. Curious to hear your thoughts on this.

**Comment by pbakaus** [comment]
Weird enough, it looks like there's not significantly reduced space in the screenshot, but I would also have suggested that as reason. The fact is that beyond a visible aspect ratio of 9:16, there will be letter boxing. There are options to avoid that, ranging in complexity and drawbacks:

1. Expand the 'bleed' (unsafe zone) around the safe zone to something like 1:2. Does put the burden on the user to fill even more space that could get wasted.
2. Add 'stretch background option' - would need to be explicit opt-in, as it is unsafe: in this case, the user would say "I want my background to be filling the whole viewport always, even at the expense of it not being perfectly aligned with the foreground elements".
3. Apply tricks that make the background at least look better. Hence why I *really* think we should do https://github.com/ampproject/amphtml/issues/29168, but the Stories team has not put it on the roadmap yet.

/cc @dvoytenko

**Comment by dvoytenko** [comment]
Why shouldn't we do (3) but in the editor itself? We have everything we need for that, I believe. Doing this in editor would also enable us to add some additional properties/editing controls to refine the blurred background if it becomes necessary in the future. Plus overall I think it'd work a lot faster when generated statically, vs added in runtime.

**Comment by pbakaus** [comment]
> Why shouldn't we do (3) but in the editor itself? We have everything we need for that, I believe. Doing this in editor would also enable us to add some additional properties/editing controls to refine the blurred background if it becomes necessary in the future. Plus overall I think it'd work a lot faster when generated statically, vs added in runtime.

Actually yes, you're totally right. Let's do it in editor.

**Comment by dreamofabear** [comment]
What about just having a better background color? We could probably pick a reasonable color automatically for most story pages.

**Comment by dvoytenko** [comment]
A better background color could be a first step in the same direction. But TBH I'm not sure that'd be any easier to do since to make a blurred image, one just needs to duplicate the same bg image, scale it up ~50% and set a blurred filter on it, vs loading the image in the canvas and running the avg color calculations. Also a blurred image would work better when the image has significantly different color areas above and below. E.g. a skyline image or such.

**Comment by dreamofabear** [comment]
An even easier option is to just match IG/Snap and use "black background + rounded corners". Curious why the format team didn't go that route to begin with -- it'd be more consistent and elegant IMO.

**Comment by dvoytenko** [comment]
That's a good question to them. But if we think it's a way to go, we can still do it here?

**Comment by dreamofabear** [comment]
Just realized that the thread starting from Paul's comment is a completely separate issue. 😄 

**Original issue:** Stories viewed in IG's in-app browser has an unexpected top margin which truncates the bottom of the story. I can't reproduce this on staging (1.1.0-alpha) and IG on iPhone XS.

**Secondary issue:** For stories viewed on tall devices, the default background (behind the 9:16 authored content) is ugly.

I'll create a simple PR that changes the default background color to match the editor's background color (a dark gray close to the background color used by IG/Snap).

**Comment by swissspidy** [comment]
@choumx Current background color is on purpose it seems, see #424

**Comment by swissspidy** [comment]
Otherwise needs feedback from Sam first I think. And a ticket.

**Comment by dreamofabear** [comment]
I'm referring to the gray background behind the authored content:

<img width="341" alt="Screen Shot 2020-09-28 at 5 12 08 PM" src="https://user-images.githubusercontent.com/20525523/94490465-5105ae80-01b4-11eb-9ae9-9e1944250cd8.png">

> Otherwise needs feedback from Sam first I think. And a ticket.

Yup, will add Sam to the review. Do you want another issue besides this one?

**Comment by westonruter** [comment]
I just noticed this as well. 

Editor | Pixel 2 XL (and Pixel 4 XL)
------|---------------------------
![image](https://user-images.githubusercontent.com/134745/94640379-5ede3100-0293-11eb-98d3-9afb03098172.png) | ![image](https://user-images.githubusercontent.com/134745/94640332-3a825480-0293-11eb-87a1-c2e832ad6060.png)

I set the image to be the background, so I was expecting it to be full bleed as shown in the editor.
