### ISSUE TITLE
Support Legacy WordPress Meta Boxes

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#3134]
## Feature Description

In https://github.com/Yoast/wordpress-seo/pull/15532 / #113 we made the first step to support plugins like Yoast SEO.

To give users control over things like meta descriptions and Open Graph descriptions, we need to support WordPress' legacy meta box system, so that we can display meta boxes like the one from Yoast SEO.

There's a lot of prior art for this in WordPress and Gutenberg.

## Additional Context

Yoast SEO support was mentioned in support requests like #3086 and #3107.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
@swissspidy to provide estimate

**Comment by swissspidy** [comment]
Experimental support has been added now in #5048. #5519 has been created to stabilize it for 1.3
