### ISSUE TITLE
Export Stories to HTML

### ISSUE THREAD

**Issue by obuylov** [GoogleForCreators/web-stories-wp#3157]
## Feature Description

Add an export button that allows to save Stories for non-WordPress sites.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

See original implementation in the legacy editor: https://github.com/ampproject/amp-wp/pull/2625

**Comment by swissspidy** [comment]
Hi @obuylov 

Thanks for your feature suggestion! Would this be something you would want to use to further edit stories somewhere else, or just to export and then host the static assets somewhere else?

**Comment by rastarr** [comment]
Well, I'd love to use this WP plugin to host the stories it makes elsewhere - I've tried other online editors which are not as friendly to use as this plugin is (despite early dev).

> Hi @obuylov
> 
> Thanks for your feature suggestion! Would this be something you would want to use to further edit stories somewhere else, or just to export and then host the static assets somewhere else?

**Comment by ernee** [comment]
@rastarr thanks for the request! Could you provide us more detail about how and where you'd like to use what you create with the Web Stories plugin?

**Comment by obuylov** [comment]
> Hi @obuylov
> 
> Thanks for your feature suggestion! Would this be something you would want to use to further edit stories somewhere else, or just to export and then host the static assets somewhere else?

Yes! just to export and then host the static assets somewhere else

**Comment by philwonski** [comment]
> Hi @obuylov
> 
> Thanks for your feature suggestion! Would this be something you would want to use to further edit stories somewhere else, or just to export and then host the static assets somewhere else?

2nd this request. I am looking primarily to be able to edit the generated HTML somewhere else. Some way to export would be really useful and also allow hosting the Stories without Wordpress if one needed.

**Comment by philwonski** [comment]
> > Hi @obuylov
> > Thanks for your feature suggestion! Would this be something you would want to use to further edit stories somewhere else, or just to export and then host the static assets somewhere else?
> 
> 2nd this request. I am looking primarily to be able to edit the generated HTML somewhere else. Some way to export would be really useful and also allow hosting the Stories without Wordpress if one needed.

As a follow-up to this, it works if you just open chrome dev tools before loading the Story and right-click  the file after it shows up in the Network tab.  Thank you for this wonderful plugin!
