### ISSUE TITLE
Display Stories in Story Player in archives

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#3166]
## Feature Description

On a WordPress site, stories can appear in search results and eventually archives (#3063).

However, the look & feel will be very dire, as only the excerpt is displayed. This is an opportunity to display the actual story in an `<amp-story-player>`.

## Alternatives Considered

We could just leave as-is, but that might not be desired.

## Additional Context

Status quo:

<img width="1680" alt="Screenshot 2020-07-13 at 15 07 35" src="https://user-images.githubusercontent.com/841956/87308075-f779d600-c51a-11ea-960a-52c227f41639.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

* Filter story content on non-single views to display them in an `<amp-story-player>`

**Comment by spacedmonkey** [comment]
What conditionals should we be targeting here?

`is_search` and `is_post_type_archive`? Is that it?

Stories could be added to author and date based archives maybe...
