### ISSUE TITLE
Story description showing up in the top of the page

### ISSUE THREAD

**Issue by gurtner** [GoogleForCreators/web-stories-wp#3168]
There is some possible code bug that makes the story description be printed at the top of the stories page, as the link shows: https://escribacafe.com/stories/5376/

**Comment by swissspidy** [comment]
Hi @gurtner, thanks for reaching out!

Could you please test whether this still happens with all other plugins disabled?

At first glance it looks like you are using some sort of caching / performance plugins, please make sure that those are disabled too and their caches were cleared.

**Comment by gurtner** [comment]
Got it. The plugin qtmplayer from Qantum Themes is causing that. It is a required plugin for my theme. I will try to figure it out what exactly is causing that and will update this issue in case of any interest. Thank you.

**Comment by swissspidy** [comment]
@gurtner Were you able to find out more in the meantimme?

I am closing this issue for now but please feel free to comment if you find anything useful - we're still receiving notifications.

Thanks!
