### ISSUE TITLE
Investigate flakiness of mediaFetching Karma tests.

### ISSUE THREAD

**Issue by diegovar** [GoogleForCreators/web-stories-wp#3182]
The `assets/src/edit-story/components/library/panes/media/media3p/karma/mediaFetching.karma.js` test seems to be very flakey.
On CI I see tons of messages like this:
`ERROR: 'Warning: You seem to have overlapping act() calls, this is not supported. Be sure to await previous act() calls before making a new one.` as well as `Error: Not ready errors from expectMediaElements`

**Comment by swissspidy** [comment]
It seems that this is still happening, see for example this test run https://github.com/google/web-stories-wp/runs/869637674?check_suite_focus=true ~1hr ago on master

**Comment by diegovar** [comment]
I wonder if it's caused by a timeout by the waitFor? Should we override onTimeout to determine if that's the case?
