### ISSUE TITLE
Media dropdown menu not shown for videos

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#3185]
## Bug Description

We display these three dots when hovering over media items, which allows opening a menu to edit & delete media.

Apparently, this menu is currently missing for videos.

## Expected Behaviour

I should be able to edit and delete video items.

## Steps to Reproduce

1. Hover over video.
1. See no three-dots-button

## Screenshots

Here's what it looks like for images:

<img width="326" alt="Screenshot 2020-07-14 at 11 13 17" src="https://user-images.githubusercontent.com/841956/87407926-1cc21f00-c5c3-11ea-941c-c3bcd497507e.png">

For videos, the button is simply missing.

## Additional Context

- Plugin Version: `1.0.0-beta.1`
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Any chance we could have tests here? Also, why skip QA and UAT?

**Comment by joannag6** [comment]
Oops sorry! Thought I removed the #Fixed line in my PR. Yep working on tests now (got a bit complicated with pointer events), wanted to get the fix in first. Added it to the QA queue.

**Comment by csossi** [comment]
Verified in QA (tested in Master - already merged)

![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/fe03be59-7224-4128-8041-a461e1af59cd)
