### ISSUE TITLE
Wellbeing Template: Use correct font weight for Source Serif Pro

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#3194]
## Feature Description

In #1616 it was noted that the Wellbeing template cannot currently use the lighter 300 font weight of the Source Serif Pro font because it's not yet available on Google Fonts.

According to https://github.com/google/fonts/issues/23#issuecomment-658175392 this has just changed now!

That means we can now adapt the template to use the correct 300 font weight for Source Serif Pro.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

* Source Serif Pro uses font weight 300 where applicable.

**Comment by swissspidy** [comment]
FYI @mariano-formidable @pbakaus

**Comment by pbakaus** [comment]
nice!

**Comment by csossi** [comment]
Verified in QA
