### ISSUE TITLE
Perform a review of the current text solution and advise on next steps

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#3219]
## Feature Description

Please create a document that details the following 

1. Current issues that are impacting text throughout the plugin
2. Look at known features that are upcoming on the roadmap (inline names, font family selection) etc
3. Analysis/ proposal of how to best update and de-risk this area of functionality

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
1. Consider highlight and padding (Marcin looking at Figma) 
2. Re: solution, ensure that the generated story text is not bad for a11y/screen readers/etc.
3. Look at future features in roadmap: inline links, inline font family styling, etc.

**Comment by bmattb** [comment]
Review of this document is booked for Wed July 22

**Comment by bmattb** [comment]
Ask from Dima - how do we quickly find a way to test this solution and get product approval on it (CUJ tests). Provide screenshots from FF & Chrome to Sam/Omar/Paul for approval.

**Comment by bmattb** [comment]
Ask from Omar - Update your document to include in the top summary the alternatives that were reviewed, why they aren't valid, (ie: we would need to recreate the textjs and that would take a lot of time), call out the key findings etc

**Comment by bmattb** [comment]
BMB will put this document in a shared location and communicate this out.

**Comment by bmattb** [comment]
We need to ensure that the remaining issues that are outstanding have been captured and are detailed. Still needed - created script to get font metrics from files - BMB to action

**Comment by bmattb** [comment]
https://github.com/google/web-stories-wp/issues/3486 was created as requested above
