### ISSUE TITLE
Grouping: group layers together for moving and aligning

### ISSUE THREAD

**Issue by quadcom** [GoogleForCreators/web-stories-wp#3222]
## Feature Description

I have a series of shapes lined up horizontally. I would like to be able to group those shapes together so that they can be moved as one block. Also, be aligned page/center without collapsing on top of each other.

## Alternatives Considered

At the moment all we can do is select each object by shift-clicking. Alignment, however, will not work as it collapses the object on top of each other

## Additional Context

![image](https://user-images.githubusercontent.com/7085931/87587480-24abbd00-c6b0-11ea-9df7-723bd5984df1.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Closing in favor of #9244
