### ISSUE TITLE
Improve generated video poster file name

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#3228]
Noticed this while looking into #1218.

In `useUploadVideoFrame` we retrieve the first frame of a video (for the poster image) and then upload it to WordPress via `useUploader` / `uploadFile` and ultimately the API provider's `uploadMedia`.

Whenever we do that, the uploaded poster image gets named by WordPress like so: `image-1`, `image-2`, `image-3`, etc. - regardless of the original video's title or file name.

This is because of this line in `uploadMedia`:

```js
file.name || file.type.replace('/', '.') // turns image/png into image
```

I think we should improve this to allow setting better image names, and the key is the `uploadFile` callback.

Idea:

First, add a second `data` parameter to `uploadFile`. Then do something like `const additionalData = { post: storyId, media_source: 'editor', ...data }` in `uploadFile`. This allows passing additional data when uploading the file.

In `useUploadVideoFrame` we can now pass a second argument to `uploadFile` to set a custom `title` à la "Generated Video Poster" or something.

Finally, `uploadMedia` can take this `title` and derive a file name from there, but still fall back to `file.name` and `file.type`.

**Edit:** Ideally, the poster name would just be the video name + suffix. So if the video in the WordPress media library  is named `awesome-video.mp4`, the poster could be named `awesome-video-poster.png`

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
See #4064 for a bug that could be fixed by this.

**Comment by westonruter** [comment]
I found an easy workaround to this. Just go straight to the Media library screen in WordPress and upload the video there. Open the video from that screen and click Edit more details:

![image](https://user-images.githubusercontent.com/134745/94467456-dae35680-0177-11eb-90c9-0886be951444.png)

Then you can supply your own tailored featured image for the video:

![image](https://user-images.githubusercontent.com/134745/94467557-fd756f80-0177-11eb-89bf-808e90279573.png)

The featured image is used for the `poster`, bypassing the need for the Web Stories editor to generate one.

**Comment by swissspidy** [comment]
Re-assigning pods so we can unblock some backend work with this.
