### ISSUE TITLE
Media: fall back to generated poster if there's no featured image

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#3230]
## Feature Description

Splitting this out from #1218:

In `Media::get_callback_featured_media_src()` (and also `Media::wp_prepare_attachment_for_js`) we provide information about the featured image if one is set.

Now, if there is no featured image set but there is a automatically generated poster image, we should use that as a fallback.

Untested code example for explanation:

```php
public function get_callback_featured_media_src( $prepared ) {
	$id    = $prepared['featured_media'];

	if ( $id ) {
		return $this->get_thumbnail_data( $id );
	}

	$poster_id = (int) get_post_meta( $prepared['id'], self::POSTER_ID_POST_META_KEY, true );

	if ( $poster_id ) {
		return $this->get_thumbnail_data( $poster_id );
	}

	return [];
}
```

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

* If now featured image is set, fall back to `web_stories_poster_id` meta value to fill `featured_media_src`

**Comment by bmattb** [comment]
@swissspidy  will update this ticket to align with #1218

**Comment by spacedmonkey** [comment]
I did a little research into this ticket, it seems like the generated poster id is already in the API response. See 
```
alt_text: ""
amp_validity: {results: [], review_link: null}
author: 1
caption: {raw: "",…}
comment_status: "open"
date: "2020-07-17T17:37:53"
date_gmt: "2020-07-17T17:37:53"
description: {raw: "",…}
featured_media: 1428
featured_media_src: {src: "http://localhost:8899/wp-content/uploads/2020/07/image-46.jpeg", width: 1280, height: 720,…}
generated: true
height: 720
src: "http://localhost:8899/wp-content/uploads/2020/07/image-46.jpeg"
width: 1280
generated_slug: "samplevideo_1280x720_1mb-31"
guid: {rendered: "http://localhost:8899/wp-content/uploads/2020/07/SampleVideo_1280x720_1mb-31.mp4",…}
id: 1427
link: "http://localhost:8899/?attachment_id=1427"
media_details: {filesize: 1055736, mime_type: "video/mp4", length: 5, length_formatted: "0:05", width: 1280,…}
media_source: "editor"
media_type: "file"
meta: {amp_status: "", web_stories_is_poster: false, web_stories_poster_id: 1428}
amp_status: ""
web_stories_is_poster: false
web_stories_poster_id: 1428
mime_type: "video/mp4"
missing_image_sizes: []
modified: "2020-07-17T17:37:54"
modified_gmt: "2020-07-17T17:37:54"
permalink_template: "http://localhost:8899/?attachment_id=1427"
ping_status: "closed"
post: 1426
slug: "samplevideo_1280x720_1mb-31"
source_url: "http://localhost:8899/wp-content/uploads/2020/07/SampleVideo_1280x720_1mb-31.mp4"
status: "inherit"
template: ""
title: {raw: "SampleVideo_1280x720_1mb-31", rendered: "SampleVideo_1280x720_1mb-31"}
type: "attachment"
web_story_media_source: [3]
```

What was more interesting, is that when a poster was updated in user selected, it did not perform an API request to the original attachment to update the feature image. It only update the poster on image on the current element. I am not sure if this is a bug or by design. 

To update to original generated image then, it would be simple adding a function like this. 

```
 const getMediaById = useCallback(
    (mediaId) => {
      const path = addQueryArgs(`${media}/${mediaId}`, { context: `edit` });
      return apiFetch({ path });
    },
    [media]
  );
```

then use the `web_stories_poster_id` field and it's id, to await the api call to get the URL and the value. 

I am not sure if we should create a bug for the media pod to report that feature image is not being setup correctly. Thoughts @swissspidy ?

**Comment by swissspidy** [comment]
The behavior mentioned above was clarified in #3438.

It seems like there is no need for this ticket at all.
