### ISSUE TITLE
Web Stories sitemap inclusion for popular SEO plugins

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#3243]
## Feature Description

We should review our options and provide guidance to users, at the right time and preferably within WP, of how to ensure their Web Stories are included on sitemaps if they use any of the popular sitemap plugins: 

- All in One (AiO) SEO Pack
- XML Sitemap & Google News
- Google XML Sitemaps
- SEOPress

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
@o-fernandez  to review and think about where/how to surface this to the user.

**Comment by bmattb** [comment]
Infra's work on this is minimal as per @swissspidy
