### ISSUE TITLE
Story editor shifts and hides publish buttons when browsing template pages on 13-inch screen

### ISSUE THREAD

**Issue by ernee** [GoogleForCreators/web-stories-wp#3248]
## Bug Description

The Story editor shifts unusually and hides the publish buttons when browsing the  **Beauty** and **Wellbeing** templates:

<img width="642" alt="Editor with collapsed admin menu" src="https://user-images.githubusercontent.com/8108643/87732631-65740680-c782-11ea-8f63-bc1124ed35fc.png">

Note the admin menu is collapsed. 

When the admin menu is expanded, the publish buttons are hidden when browsing **all templates.** Additionally, a bar appears at the bottom of the editor screen:

<img width="642" alt="Editor with expanded admin menu" src="https://user-images.githubusercontent.com/8108643/87732316-7ff9b000-c781-11ea-9800-66718ef053bb.png">

## Expected Behaviour

There is no shifting, hidden publish buttons, or bar at the bottom of the editor when browsing templates on a 13-inch screen. 

## Steps to Reproduce

1) On a 13-inch screen, select the Beauty or Wellbeing template (collapsed admin menu) or any template (expanded admin menu). 
2) Browse through each page, notice either shifting, hidden publish buttons, or a bar at the bottom.

## Screenshots

**Beauty Template**

- [collapsed admin menu video](https://recordit.co/a5kntUBhRh) 
- [expanded admin menu video](https://recordit.co/0ngfQCmMuN)

**Wellbeing Template** 

- [collapsed and expanded admin menu video](https://recordit.co/p12Y5QVPVq)

## Additional Context

- Plugin Version: 1.0.0-beta.1
- Operating System: MacOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
We had a similar issue with such shifts in #2304.

Maybe another thing @wassgha could look at?

**Comment by ernee** [comment]
Similar behavior was also reported by @hansschuijff.  In [this issue](https://github.com/google/web-stories-wp/issues/3455):

> Using the first template I run into two other issues:
> 1. The editor page is scrolled max down, so in my case, since my admin menu is longer, the actual editor isn't actually in the viewport, making me scroll up before I can edit.
> 2. When I scroll up maximum to the top, the buttons and title field are partly behind the admin toolbar and I cannot scroll to a point they are completely visible.
> 
> [Here's my video](https://recordit.co/XJ768RNk3o) so you can see what I saw.

@hansschuijff could you share which device and what size screen you're using in the video? 
 
other info:

- WordPress version: 5.4.2
- PHP version: 7.3.5
- Plugin Version: 1.0.0-beta.1
- Operating System: Windows 10
- Browser: Firefox Developer 79.0b9 (64-bits)

**Comment by hansschuijff** [comment]
@ernee Yes, of course.

My laptop is a Toshiba Satellite L50-B-1HH and has a 15.6 inch screen set to the default 1366x768 pixels. My browser is maximized (Firefox developer). The screen above the recorded part is filled with a bookmarks bar, address bar and the browser tabs and below the recorded part is the Windows 10 start bar. All programs are updated to the latest versions.

**Comment by ernee** [comment]
@hansschuijff much appreciation for these details. We'll be addressing such issues as you noted with responsiveness in  https://github.com/google/web-stories-wp/issues/1621. Feel free to follow its progress for the stable release.

**Comment by o-fernandez** [comment]
As @ernee mentioned, the right issue to follow for the solution to this is #1621. We will close this issue, but note that it is linked and will be used to inform and validate the final solution.
