### ISSUE TITLE
Use srcset for images to prevent loading full assets in editor and AMP stories

### ISSUE THREAD

**Issue by diegovar** [GoogleForCreators/web-stories-wp#3249]
Unsplash has some huge images which users can then zoom into in their canvas, or resize to be small. In the output format (image/output.js) we should be at least using srcset to load the appropriate image sizes.

Testing instructions (copied from Pascal):
Given that the Unsplash integration is still behind a feature flag (and feature flags are not part of QA), focus by just adding some images from the library to the editor, saving & previewing the story, and verifying that you see srcset attributes for the images in the source code.

**Comment by csossi** [comment]
On Selecting an image from the unsplash tab and inserting into post, the image appears properly in Gallery, but not on canvas:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/884d2ee7-18ec-4ca2-9863-bd0e6c462063)

**Comment by diegovar** [comment]
Hi Claudio, the image can take a few seconds to appear while it downloads
from Unsplash. Did it not appear at all?

**Comment by winterDroid** [comment]
> Hi Claudio, the image can take a few seconds to appear while it downloads from Unsplash. Did it not appear at all?

I think this example is for a normal gallery image and not Unsplash. You can also see the broken image indicator on the canvas.

**Comment by diegovar** [comment]
> > Hi Claudio, the image can take a few seconds to appear while it downloads from Unsplash. Did it not appear at all?
> 
> I think this example is for a normal gallery image and not Unsplash. You can also see the broken image indicator on the canvas.

Ah good point Marc, thanks for noticing that. @csossi  Can you test again ensuring you enable the `media3pTab` flag and in the correct tab?

**Comment by swissspidy** [comment]
@diegovar Note that flags can currently only be toggled via code, not UI, which means this cannot be tested on our QA environment (yet).

Also, the general rule is that features behind a flag are not going through QA.

#3526 does not seem to be specific to Unsplash though, so I don't see how the feature flag is relevant in this case.

I think clear QA instructions would help tremendously here.

**Comment by diegovar** [comment]
Hi Claudio, I'm terribly sorry, got confused and the comment I made regarding the media3p tab doesn't apply here. As Pascal correctly pointed out, QA is meant to test only things that are not behind a feature flag. In this case, we want to test that images added from the Upload tab display correctly in the media gallery, in the editor itself (this includes the canvas, the page indicators under the canvas and the layer section at the bottom right) and in the generated stories.

The issue you just found with that image is independent of this fix and occurs because that image was actually added by the [**Unsplash Wordpress plugin**](https://wordpress.org/plugins/unsplash/), which is _different_ from our Unsplash integration in the Media 3p tab. When you use that plugin, the images get "copied" into the user's media library, which is why you see it in the gallery. It seems that if you use our Upload button and select that image from the "Media Library" tab, then it doesn't get added to the canvas correctly (I see that the src is apparently "undefined" in the Network tab). If you click on the image directly in the gallery to add it, it seems to be added correctly (though it takes a bit of time for the image to download from Unsplash). Paging @spacedmonkey about this in case it's a known issue.

I'd recommend you try using actual uploaded images to test this PR, and not ones that were added from the Unsplash plugin (which I realize is hard to tell because there's no visual indicator in the Story Editor gallery or the Wordpress Media Library that this was the case).

**Comment by diegovar** [comment]
> @diegovar Note that flags can currently only be toggled via code, not UI, which means this cannot be tested on our QA environment (yet).
> 
> Also, the general rule is that features behind a flag are not going through QA.
> 
> #3526 does not seem to be specific to Unsplash though, so I don't see how the feature flag is relevant in this case.
> 
> I think clear QA instructions would help tremendously here.

With regards to QA instructions, should they be added to the issue, or the PR in this case?

**Comment by csossi** [comment]
@diegovar - If you could add QA instructions here, that'd be great - cheers

**Comment by swissspidy** [comment]
@csossi The testing instructions are in the PR linked from this issue, #3526. Copying them here for visibility:

> Use the editor (especially by adding images from Unsplash via the `media3pTab` flag) and ensure that images display correctly in the editor and in the generated AMP stories.

Given that the Unsplash integration is still behind a feature flag (and feature flags are not part of QA), focus by just adding some images from the library to the editor, saving & previewing the story, and verifying that you see `srcset` attributes for the images in the source code.

**Comment by csossi** [comment]
Understood - thanks, @swissspidy

**Comment by diegovar** [comment]
Any updates on QA for this?

**Comment by spacedmonkey** [comment]
@diegovar Sorry I missed the ping here. I will install the Unsplash plugin and do some testing.

**Comment by spacedmonkey** [comment]
I installed the unsplash plugin and it worked for me. What is the issue with the two plugins again? 

See video of it working. https://youtu.be/kwPJ_8fpLPs

**Comment by swissspidy** [comment]
This is not about the Unsplash plugin! The whole ticket here is about the custom Unsplash integration in the Web Stories plugin.

**Comment by swissspidy** [comment]
FYI: Wanted to do QA myself, but moving this back to "In Progress" due to a bug I found.

**Comment by diegovar** [comment]
> This is not about the Unsplash plugin! The whole ticket here is about the custom Unsplash integration in the Web Stories plugin.

I think what Jonny was talking about was my comment above (https://github.com/google/web-stories-wp/issues/3249#issuecomment-669083282) where I found that the reason the images were not showing in the Canvas for Claudio in the first comment (https://github.com/google/web-stories-wp/issues/3249#issuecomment-669083282) was because the image had been added through the Unsplash plugin, and was failing to render for some reason. However, I'm unable to reproduce that issue anymore in the QA env with images added through that plugin, so everything good.

> On Selecting an image from the unsplash tab and inserting into post, the image appears properly in Gallery, but not on canvas:
> ![image.png](https://camo.githubusercontent.com/9fcf424599f2fb97f99f327481dd4fc310790384/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3565613038356534373034653732633061393963363939372f38383464326565372d313865632d346361322d393836332d626430653663343632303633)

**Comment by diegovar** [comment]
> FYI: Wanted to do QA myself, but moving this back to "In Progress" due to a bug I found.

I've fixed that issue so this should be ready for QA now.

**Comment by csossi** [comment]
Tested as per Pascal's direction/QA instructions

srcset details appearing:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/dd6d2d14-6923-4362-884b-70aeac8f6a4b)

Verified in QA
