### ISSUE TITLE
AMP: Mark story post type as not supported

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#3257]
## Feature Description

Originally raised in https://github.com/ampproject/amp-wp/issues/5050 and fixed in https://github.com/ampproject/amp-wp/pull/5053.

Let's use the new `amp_supportable_post_types` filter (available in the upcoming 1.6 release) to make sure the `web-story` post type is **not** in that list.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

* Stories post type should not be listed in the AMP plugin settings.

## Implementation Brief

* Use `amp_supportable_post_types` to remove `web-story` post type from that list.

**Comment by bmattb** [comment]
possible follow up is to make a common method to add/remove from arrays
