### ISSUE TITLE
Google photos integration

### ISSUE THREAD

**Issue by ai-Apps-coder** [GoogleForCreators/web-stories-wp#3275]
## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by LuckynaSan** [comment]
Thanks for your valuable feedback! I will relay your suggestion to the team for consideration and follow up with any updates.

**Comment by LuckynaSan** [comment]
Thanks again for your suggestion. Integration into media services such as Google Photos is under consideration by the product team, but there is no ETA at the moment. Please feel free to watch this repository for any future updates.
