### ISSUE TITLE
Allow insert from URL media

### ISSUE THREAD

**Issue by ai-Apps-coder** [GoogleForCreators/web-stories-wp#3276]
## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by LuckynaSan** [comment]
@traforate That given feature is not supported yet, but we are considering the possibility here #471. If you’d like please elaborate on which kind of media you would include (e.g. YouTube, mp3 video, images, etc.).

**Comment by LuckynaSan** [comment]
@traforate I will close this issue out since you are following 471 mentioned above. Thank you!
