### ISSUE TITLE
Option to start Story unmuted

### ISSUE THREAD

**Issue by injainja** [GoogleForCreators/web-stories-wp#3281]
I have build my first story and tested it with my community:
http://www.Schamane.berlin
I would like to share the feedbacks I got as enhancement wishes. 

Please add an option to start the stories unmuted. I know, that it is considered bad practice, but the option should be there anywhere. We had several users who didn't understand that the story is muted and needs to be unmuted. 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by ernee** [comment]
@injainja thanks for the request! We'll review this with the team and provide any updates as we have them.

**Comment by injainja** [comment]
Thank you so much - if you need any more information from my side please ask...  🤗

**Comment by ernee** [comment]
@injainja thanks again for your request! The video's sound playback/ behavior is part of the AMP specification ([reference](https://amp.dev/documentation/examples/components/amp-video/#autoplay)). As you mention, it is considered best practice not to autoplay audio so the format aims to adhere to this. While I'm closing this issue for now, the details provided from the community of users you've tested with is super helpful feedback for consideration as we continue development.

**Comment by injainja** [comment]
Ok, thank you. I understand, that you stick to the best practices... To solve the problem of overlooking the the audio button, you should consider to make either the button bigger or - even better - the small equalizer at the button that is displayed if sound is played. I will open a different topic for that. Thank you once more for your precious work!
