### ISSUE TITLE
Make the mute/unmuted button bigger more prominent

### ISSUE THREAD

**Issue by injainja** [GoogleForCreators/web-stories-wp#3282]
## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by ernee** [comment]
@injainja thanks also for this request regarding the mute/ audio experience. Is this related to the experience/ feedback you mentioned in #3281?

**Comment by injainja** [comment]
@ernee 
Thank you for your kind reply 🙂
This request is related in a way to https://github.com/google/web-stories-wp/issues/3281
but it also is a different topic. 
Like two requests:

1) 3281 is a request to add an option to start the stories with the sound ON by default. (atm the stories start muted)
2) This request is about making the mute/unmute button a little bit bigger or better visible especially on the first page, because many of my test clients overlooked that it is possible to turn on  sound, because they didn't notice the little an unmute button at the top of the page. 

So you can see that the topics are related but address different problems.

**Comment by ernee** [comment]
@injainja as mentioned in #3281, the context for this request is helpful. I've [opened this request](https://github.com/ampproject/amphtml/issues/29476) in the AMP project repository about the discoverability of the mute button. You are welcome to follow it and we'll provide updates on the progress too. Thanks again for your request!

**Comment by swissspidy** [comment]
Closing in favor of https://github.com/ampproject/amphtml/issues/29476 as it would be an upstream change.

In the meantime, workarounds exist. For example, you can put a "Sounds on" text directly on your story.

Example: https://wp.stories.google/stories/creating-a-web-story-in-less-than-5-minutes-storytime/#page=4c93e4af-f01d-4e8c-927a-1670ef7d7543
