### ISSUE TITLE
Option to use "one-click" links

### ISSUE THREAD

**Issue by injainja** [GoogleForCreators/web-stories-wp#3283]
Atm you need to click links to open a pop-up. After cklicking  the Pop-up, the link will work. Please add an option to each link for directly linking without any pop up. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by LuckynaSan** [comment]
@injainja Thank you for your recommendation! I did share this with the team. The current direction we plan to support is that links will be 2-tap links. However, we are working on a [feature](https://github.com/google/web-stories-wp/pull/2848) for a 1-tap option with a page attachment. 

For further context, the handling of links is based on the story format spec in [#links-in-amp-story-grid-layer](https://amp.dev/documentation/components/amp-story/#links-in-amp-story-grid-layer). Whenever a link is tapped a tooltip will be shown - deferring the corresponding action until the user taps again in the tooltip. 

We greatly appreciate your feedback! I will close out this topic for now.

**Comment by injainja** [comment]
Ok, thank you for the information 👍
