### ISSUE TITLE
Pasting copied text

### ISSUE THREAD

**Issue by btechstories** [GoogleForCreators/web-stories-wp#3284]
## Bug Description
When pasting a copied text, it paste same text twice
## Expected Behaviour

It should paste once and within the set boundary of the text area

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by LuckynaSan** [comment]
Thank you for reporting this. We are currently looking into this issue. Please feel free to follow the issue here #1953 for any updates. 
For now we will close this issue as a Duplicate of #1953.
