### ISSUE TITLE
New options for ending the stories

### ISSUE THREAD

**Issue by injainja** [GoogleForCreators/web-stories-wp#3286]
Atm when we click on the last page of a story, there will be a very ugly screen to share the story. This is killing in my opinion the user experience. Please add following options concerning what happens when clicking on the right edge of the last page:
- deactivated, so that the last page doesn't do anything at all when clicking on the right edge
- jump to a website
  a) with confirmation
  b) without confirmation
- leave it like it is atm, but with options to customize it

Thank you so much guys for your awesome work. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by ernee** [comment]
@injainja thanks for your request and kind feedback! Could you share a video of your experience with ending the story? You can use something like the app [recordit](https://recordit.co/) to make a quick gif/video and share the link.

**Comment by injainja** [comment]
@ernee 
Thank you for your kind response and your interest for this topic. I did a screen recording:

https://www.liesenfeld.de/d/story.mp4

The story that I used in this video is this one:
http://www.schamane.berlin
But my request is generic. 😀

Like I said before:
Please add following options concerning what happens when clicking on the right edge of the last page:
1) deactivated, so that the last page doesn't do anything at all when clicking on the right edge
2) jump to a website
  a) with confirmation
  b) without confirmation
3) leave it like it is atm, but with options to customize it

**Comment by ernee** [comment]
@injainja thanks for the video and explanation! What you're seeing in the mobile view is the default bookend experience for stories ([reference here](https://amp.dev/documentation/components/amp-story-bookend/) on amp.dev).

This feature is [eventually being deprecated](https://github.com/ampproject/amphtml/issues/26957). The functionality originally provided by the bookend (sharing, next stories) will now be provided by the story player. The AMP project is open to receiving feedback for this though. The feature won't be fully deprecated until alternatives are finalized.

Given that this is still in progress, the Web Stories plugin currently on mobile will have this default experience (on desktop there [isn't a bookend](https://github.com/google/web-stories-wp/issues/3066#issuecomment-655409873)).

In the meantime, as you have already done, the last page of your story can be modified to direct users accordingly. The pre-made templates under _Stories > Dashboard > Explore Templates_  have some great examples too. 

Thanks again for your feedback/ suggestions!
