### ISSUE TITLE
Test & Update WordPress 5.5 Compatibility

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#3300]
## Task Description

We just had a small bugfix for WP 5.5 compatibility land today, see #3298

Let's make sure there are no other big issues like this, and then bump the `Tested up to` value accordingly here:

https://github.com/google/web-stories-wp/blob/ec3886cff6983e0576b98c88dd4d990826f45c74/readme.txt#L5

**Comment by bmattb** [comment]
RC for 5.5 is July 28th

**Comment by bmattb** [comment]
RC2 came out yesterday

**Comment by spacedmonkey** [comment]
I tested the editor and block in 5.5. Works fine for me. Anything else we should create new issues.
