### ISSUE TITLE
Text Edit Mode: Resizing heading causes text selection if done right after adding

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#3303]
## Bug Description
Under specific conditions, the text is selected when resizing in edit mode.

See the original report: https://github.com/google/web-stories-wp/issues/1801#issuecomment-658975910

## Expected Behaviour
Text should never get selected when resizing in edit mode.

## Steps to Reproduce
1. Add a heading
2. Type something to enter edit mode
3. Now resize from the bottom right corner.
4. See the text getting selected.

## Screenshots
![selected](https://user-images.githubusercontent.com/3294597/87970773-84e19b00-cac4-11ea-86a5-d1599ec50180.gif)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by dreamofabear** [comment]
I can't reproduce this, please reopen if this is still an issue.
