### ISSUE TITLE
New font picker: use virtualized list instead of rendering all (1010) fonts

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#3304]
## Feature Description
Currently, the new font picker is rendering all the fonts at the same time, this, however, causes performance issues, see , see https://github.com/google/web-stories-wp/pull/2530#pullrequestreview-447542380 and https://github.com/google/web-stories-wp/pull/2530#issuecomment-658148495

We should use a virtualized list instead.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
1. The new font picker should not render all the 1010 fonts at the same time.
2. Opening the new font picker should (ideally) happen with 100ms or less.

**Comment by miina** [comment]
@merapi FYI: In case this issue will still need implementing then here is the [WIP PR](https://github.com/google/web-stories-wp/pull/3379) in case that's useful. Please close if the decision is to just go with the curated list (#1989)

**Comment by swissspidy** [comment]
I thought Paul's comment on #1989 was clear 

>  even in the new curated list scenario, a user can still type a font into the box and get to a filter of the whole 1000 fonts. That still needs to be fast.

Did I miss something else in the meantime?

**Comment by o-fernandez** [comment]
We will implement the new font picker without virtualized list and test performance first. If it is pretty responsive ~300ms for worse case scenarios, then we'll skip this effort. 

Rationale: we think this will only be useful in searches that return a lot of fonts, which is only expected for 2 character font searches (e.g., user only types two characters). We don't search when there's only one character in the search, and once you type 3 characters the list of results shrinks quite a lot.

**Comment by miina** [comment]
Closing as irrelevant since we're using the curated list now.
