### ISSUE TITLE
Display pause-button also on mobile view like in desktop

### ISSUE THREAD

**Issue by injainja** [GoogleForCreators/web-stories-wp#3315]
## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by ernee** [comment]
@injainja thanks for your request! I've [opened this request](https://github.com/ampproject/amphtml/issues/29469) with the AMP project for consideration.  Feel free to follow it and we'll also provide an update here on the progress. 

While the play/pause button isn't present on mobile at the moment, users can do a _long press_ on the screen to pause and _release_ to play the story.

**Comment by swissspidy** [comment]
Closing in favor of https://github.com/ampproject/amphtml/issues/29469

If this would get implemented, it would not require a plugin update or anything. In other words: nothing we can do here ourselves.
