### ISSUE TITLE
One page remains mute with Firefox for Android

### ISSUE THREAD

**Issue by injainja** [GoogleForCreators/web-stories-wp#3321]
## Bug Description
http://www.schamane.berlin works fine with any browser, but not with Firefox for Android. Only a Video that is embedded within a circle seems to be affected. 

## Steps to Reproduce
1) Open the domain
http://www.schamane.berlin
with Chrome and unmute:
Every page has sound

2) Open the domain
http://www.schamane.berlin
with Firefox for Android and unmute:
The first page doesn't have sound. 

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by ernee** [comment]
@injainja many thanks for reporting! I can see the issue in the Firefox browser with the video in your first story page.

There may be something specific with the video in the first story page that is preventing the audio from playing in Firefox. 

- Audio is not available when I visit the mp4 media file URL to the video in Firefox directly. When I visit the link in other browsers it plays without issue. 
- Additionally, the second video's media file URL plays audio in Firefox and other browsers without issue. 

Could you check and let me know if you experience the same?

**Comment by injainja** [comment]
Yes - the problem seems to be caused by the video and not by the plugin. So you can close this topic. Thank you so much, I will try to find the cause of the problem and will post it here in case someone else runs into the same problem.

**Comment by injainja** [comment]
JFYI - I found the problem. Mozilla doesn't like videos with 192 / mp3 Audio. Changed it to 128 / AAC and it works now. Thanks to @ernee  for pointing me in the right direction. I really appreciate your work, guys! The plugin is going to be awesome and very, very helpful for a lot of people. Web-Stories are the future of the web imho.

**Comment by swissspidy** [comment]
@injainja Glad you were able to find the issue! Thanks also for your kind feedback!
