### ISSUE TITLE
Validation Error on Standard AMP Mode

### ISSUE THREAD

**Issue by netnaps** [GoogleForCreators/web-stories-wp#3327]
## Bug Description

I am getting an error on the Standard Mode:  AMP on WordPress, I am using " ?amp " in my permalinks.

## Screenshots

![Screenshot 2020-07-21 at 3 38 16 PM](https://user-images.githubusercontent.com/67054369/88041788-84024500-cb68-11ea-9f1c-210658f5d43a.png)

## Additional Context
- Plugin Version: Latest 
- Operating System: WordPress Latest, MacOS 
- Browser: Chrome, Safari

**Comment by swissspidy** [comment]
Hi @netnaps, thanks for your report!

We're aware of this and are tracking this compatibility issue in #3258. Please follow that issue for any updates.

This issue will be resolved with the upcoming 2.0 release of the AMP plugin (due mid-August).

If we release another Web Stories beta before that, we'll likely include a fix for this ourselves.
