### ISSUE TITLE
Make web stories plugin compatible with Block Directory

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#3330]
## Feature Description

Block directory is coming to 5.5, we should do some discovery to see if make this plugin available in it. 

Link: https://make.wordpress.org/meta/2019/05/08/block-plugins-and-the-block-directory/

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Related: #3300

Don't think we'd need to do anything for the block directory though, but curious to learn more.

**Comment by spacedmonkey** [comment]
There is a block plugin checker that we run our code against. https://wordpress.org/plugins/developers/block-plugin-validator/

Here is the output
![wordpress org_plugins_developers_block-plugin-validator_(iPad Pro) (1)](https://user-images.githubusercontent.com/237508/88176084-ace51180-cc1e-11ea-83fc-58984c44eb7b.png)

I am not sure that we would want this to be in the block directory, as this plugin does more than just add a block. 

I will create some some PRs to valid bugs the checker found.

**Comment by swissspidy** [comment]
After seeing that fatal error in your screenshot, and reading https://make.wordpress.org/plugins/2020/07/22/proposed-block-directory-guidelines/ it's pretty clear that this is not applicable to our plugin.

The block directory is for blocks that exist of a block.json file, some JavaScript and some CSS - nothing more. Our plugin does not fall into that category.
