### ISSUE TITLE
Use register_block_type_from_metadata function

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#3331]
## Feature Description
The `register_block_type_from_metadata` function will be added in WordPress 5.5.  The web stories plugin should use the `register_block_type_from_metadata` function and register on attributes in `block.json`.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Related: #3330.

**Comment by bmattb** [comment]
recommendation from @spacedmonkey was to wait until 5.5 is released. pretty low priority. after discussion, moving to the icebox. cc @o-fernandez

**Comment by spacedmonkey** [comment]
We could revisit this once https://github.com/google/web-stories-wp/issues/7598 is complete.
