### ISSUE TITLE
Dashboard: Safari typeahead options overlap

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#3342]
## Bug Description
In safari type ahead options are overlapping and the background color for hover is off center.
![safari typeahead long options](https://user-images.githubusercontent.com/10720454/88085894-57840400-cb3b-11ea-9598-3201b8a76739.gif)

## Expected Behaviour
It should look more like this: 
![Screen Shot 2020-07-21 at 10 17 48 AM](https://user-images.githubusercontent.com/10720454/88085962-75e9ff80-cb3b-11ea-9d3d-9a32a625cfb6.png)

## Steps to Reproduce
In Safari: Use the search typeahead in the header of the dashboard

- Plugin Version: 1.0.0-beta.1
- Operating System: Mac - Catalina 10.15.5 
- Browser: Safari

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

- typeahead options shouldn't overlap and space should be respected, like in chrome and firefox

## Implementation Brief

- add proper fallbacks in typeahead options so that works as expected

**Comment by bmattb** [comment]
added to s33 after start

**Comment by csossi** [comment]
What was the final resolution here? to account for long titles with "...", or line break?

Checked PR3347 and seeing this:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/5f0ffcb5-a4e7-480c-98e2-4df48d226023)

But the "Expected Behaviour" above indicates line breaks

**Comment by BrittanyIRL** [comment]
This is my fault for not clarifying or updating this. The resulting typeahead options should all be 1 line with an ellipsis now.

**Comment by csossi** [comment]
Perfect - Thanks, @BrittanyIRL !

**Comment by csossi** [comment]
Verified in QA
