### ISSUE TITLE
CUJ QA - User can add Image/Video to page

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#3348]
## Bug Description

REF document - https://docs.google.com/spreadsheets/d/1zE3rdJykQY1YOQUHoczyzPNLa5_bhtv-2wfTE1-NOn0/edit#gid=0

Please review the tasks below and test/confirm current state.

This CUJ is to confirm that the user is able to add images and videos to pages in their stories. Please validate the following tasks:

1. Upload image/video via upload button in media tab, and then add it from the media tab to canvas. 
2. Upload asset by dragging image/video from desktop to canvas
3. Upload asset by dragging image/video from desktop to media library
4. Upload image/video by pasting (only works on Mac OS)
5. Search for media (through entering a keyword or by browsing) already in the media gallery and add it to the canvas
6. Filter media by type (image, video, all) - NB: known issue with this https://github.com/google/web-stories-wp/issues/1572 has previously been identified.
7. Drag media from media library to edge to place as background
8. Add image/video on page then click "Set as background" button

 

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
re: item 4

Works fine for images, but video is appearing at a box with filename (tested in Mac/Chrome):
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/141b1eb1-4a3f-4d38-8d9e-a7be9238de6a)

**Comment by bmattb** [comment]
@spacedmonkey - will dig up the matrix that details that this is a known issue - @bmattb will create a new bug to address (if it's not already noted)

**Comment by spacedmonkey** [comment]
I documented here that paste to upload on works in some OS / broswer mixes. 

https://github.com/google/web-stories-wp/issues/761#issuecomment-621181267

I think we need a table that lists all the supported features in different broswers and this to be well documented. Like this

Paste ( Image )
Paste ( Video )
Drag and drop Canva ( Image )
Drag and drop Canva ( Video )
Drag and drop Media library ( Image )
Drag and drop Media library ( Video )

Then OS, windows, Mac OS, ChromeOS
and broswer.

**Comment by bmattb** [comment]
closing this as the work has been completed, and the outstanding issue was logged in a separate bug ticket
