### ISSUE TITLE
Add a ProviderTab for Coverr

### ISSUE THREAD

**Issue by cvolzke4** [GoogleForCreators/web-stories-wp#3350]
## Task Description

- Add a new ProviderTab for the Coverr provider.
- In onProviderTabClick, call setSelectedProvider to update the selected provider.
- Verify keyboard navigation.

Similar to this, though it needs cleaning up:
https://github.com/google/web-stories-wp/pull/3364/files#diff-dd6e2e686434fe0300a8809ad6ad354aR213

**Comment by diegovar** [comment]
Closed in favour of json config
