### ISSUE TITLE
Add video poster, posterId, length, lengthFormatted, src to getResourceFromMedia3p

### ISSUE THREAD

**Issue by cvolzke4** [GoogleForCreators/web-stories-wp#3354]
## Task Description

'poster' - the last image in the images list (sizesFromBiggest[sizesFromBiggest.length - 1]]).
'posterId' - can be left as null (I think).
'length' - the duration of the video in seconds.
'lengthFormatted' - eg. '0:17'.

**Comment by spacedmonkey** [comment]
Should we just change the format of the WordPress media api to fit the media3p api response?
