### ISSUE TITLE
Error: Current WordPress version does not meet minimum requirements for Web Stories.

### ISSUE THREAD

**Issue by Rv10000** [GoogleForCreators/web-stories-wp#3378]
Get the following error when trying to enable. 

Error: Current WordPress version does not meet minimum requirements for Web Stories.

I'm aok on PHP version (5.6.4). Any ideas why I'd be getting that error?

**Comment by swissspidy** [comment]
Hi there

The Web Stories plugin requires at minimum WordPress 5.3 as well as PHP 5.6 or higher.

Note that WordPress recommends PHP 7.2 or higher, so I highly recommend updating your PHP version. PHP 5.4 is not supported anymore.

**Comment by Rv10000** [comment]
Gotcha. Thanks.
