### ISSUE TITLE
Dashboard My Story Preview Overlay

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#3391]
Feature Description

Mirroring the preview overlay in the workspace, when you view a story in My Stories an overlay should appear that plays the complete template.

https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=7669%3A852

Additional Context

Do not alter or remove anything below. The following sections will be managed by moderators only.

Acceptance Criteria

Visit the My Stories section on the dashboard
Click the View button or card
An overlay with a full preview playing the story should show
For now we are not showing the device or OS toggle in the preview.

**Comment by BrittanyIRL** [comment]
Flag to enable for testing: enableStoryPreviews

**Comment by csossi** [comment]
Not seeing the VIEW button - testing in PR#3727:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/6bff218c-aa19-4240-8648-374469d122ed)

**Comment by BrittanyIRL** [comment]
Do you mind testing this again and making sure you enable the storyPreviews flag on the new experiments page in the dashboard and hit save on the flag update and then navigate to the dashboard? The button's hidden behind the flag. 
 
<img width="500" alt="Screen Shot 2020-08-10 at 8 27 35 AM" src="https://user-images.githubusercontent.com/10720454/89800313-7a268e80-dae3-11ea-8e2c-1a66580864cd.png">

**Comment by csossi** [comment]
Verified in QA

Assuming here that "View" is now "preview" by design
