### ISSUE TITLE
A user is presented with a default layout when they create a new page

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#3402]
## Feature Description

1. When I add a new blank page, the page is not blank. We create a cover layout for the user (ie title, subtitle and body text)
2. The next page they add will be an editorial page (section header and body text)

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Closing in favor of #10110
