### ISSUE TITLE
Disallowed attribute or attribute value present in HTML tag in Search Console

### ISSUE THREAD

**Issue by luckyadirake** [GoogleForCreators/web-stories-wp#3403]
## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Hi @luckyadirake, please share the URL to your story so we can assist you.

**Comment by luckyadirake** [comment]
https://carsbycash.com/stories/%E0%B8%A3%E0%B8%B1%E0%B8%9A%E0%B8%8B%E0%B8%B7%E0%B9%89%E0%B8%AD%E0%B8%A3%E0%B8%96%E0%B8%A1%E0%B8%B7%E0%B8%AD%E0%B8%AA%E0%B8%AD%E0%B8%87/


Best Regards,
Adirake Ekphaisansup (Lucky)

**Comment by swissspidy** [comment]
Thanks.

You appear to be using some kind of social media sharing plugin that adds `xmlns:og="http://opengraphprotocol.org/schema/" xmlns:fb="http://www.facebook.com/2008/fbml"` to the `<html>` tag of every site. That causes the "disallowed attribute" error for stories.

Could you share your Site Health information with us? You find Site Health under Tools in WordPress admin. From there you can go to the Info tab and click on "Copy site info to clipboard". Paste that site info here.

Thank  you.

**Comment by luckyadirake** [comment]
`
### wp-core ###

version: 5.4.2
site_language: en-TH
user_language: en-TH
permalink: /%postname%/
https_status: true
user_registration: 0
default_comment_status: closed
multisite: false
user_count: 3
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/carsbyca/public_html
wordpress_size: loading...
uploads_path: /home/carsbyca/public_html/wp-content/uploads
uploads_size: loading...
themes_path: /home/carsbyca/public_html/wp-content/themes
themes_size: loading...
plugins_path: /home/carsbyca/public_html/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-active-theme ###

name: Avada Child (Avada-Child-Theme)
version: undefined
author: Your name here
author_website: (undefined)
parent_theme: Avada (Share On Theme123.Net) (Avada)
theme_features: automatic-feed-links, custom-header, custom-background,
woocommerce, menus, post-formats, post-thumbnails, widgets, fusion_builder
theme_path: /home/carsbyca/public_html/wp-content/themes/Avada-Child-Theme

### wp-parent-theme ###

name: Avada (Share On Theme123.Net) (Avada)
version: 3.7.2
author: ThemeFusion
author_website: http://themeforest.net/user/ThemeFusion
theme_path: /home/carsbyca/public_html/wp-content/themes/Avada

### wp-themes-inactive (7) ###

Twenty Fifteen: version: 1.0, author: the WordPress team (latest version:
2.6)
Twenty Fourteen: version: 1.3, author: the WordPress team (latest version:
2.8)
Twenty Nineteen: version: 1.5, author: the WordPress team (latest version:
1.6)
Twenty Seventeen: version: 1.4, author: the WordPress team (latest version:
2.3)
Twenty Sixteen: version: 1.4, author: the WordPress team (latest version:
2.1)
Twenty Thirteen: version: 1.4, author: the WordPress team (latest version:
3.0)
Twenty Twenty: version: 1.2, author: the WordPress team (latest version:
1.4)

### wp-mu-plugins (1) ###

Health Check Troubleshooting Mode: author: (undefined), version: 1.5.1

### wp-plugins-active (13) ###

BJ Lazy Load: version: 1.0.9, author: Bjørn Johansen, Aron Tornberg,
angrycreative
Elementor: version: 2.9.14, author: Elementor.com
Elementor Pro: version: 2.10.3, author: Elementor.com
Fusion Core: version: 1.6.2, author: ThemeFusion
Health Check & Troubleshooting: version: 1.4.4, author: The WordPress.org
community
Remove Yoast SEO Comments: version: 3.1, author: Mitch
SG Optimizer: version: 5.6.0, author: SiteGround
Smush: version: 3.6.3, author: WPMU DEV
Web Stories: version: 1.0.0-beta.1, author: Google
Wordfence Security: version: 7.4.9, author: Wordfence
Yoast Duplicate Post: version: 3.2.5, author: Enrico Battocchi & Team Yoast
Yoast SEO: version: 14.6.1, author: Team Yoast
Yoast SEO: Local: version: 13.3, author: Team Yoast and Arjan Snaterse

### wp-plugins-inactive (1) ###

Yoast SEO Premium: version: 14.4.1, author: Team Yoast

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 9.26

### wp-server ###

server_architecture: Linux 3.12.18-clouder0 x86_64
httpd_software: Apache
php_version: 7.3.16 64bit
php_sapi: cgi-fcgi
max_input_variables: 3000
time_limit: 120
memory_limit: 768M
max_input_time: 120
upload_max_size: 128M
php_post_max_size: 128M
curl_version: 7.59.0 OpenSSL/1.0.2r
suhosin: false
imagick_availability: false
server-headers:
server: nginx
date: Fri, 24 Jul 2020 14:43:48 GMT
content-type: text/html; charset=UTF-8
content-length: 42348
expires: Wed, 11 Jan 1984 05:00:00 GMT
cache-control: no-cache, must-revalidate, max-age=0
x-cache-enabled: True
link: <https://carsbycash.com/wp-json/>; rel="https://api.w.org/", <
https://carsbycash.com/>; rel=shortlink
set-cookie: wpSGCacheBypass=1; expires=Fri, 24-Jul-2020 16:23:47 GMT;
Max-Age=6000; path=/; HttpOnly; SameSite=Lax
vary: Accept-Encoding
content-encoding: gzip
host-header: b7440e60b07ee7b8044761568fab26e8
x-proxy-cache: BYPASS
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.6.40-84.0-log
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id:
7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/carsbyca/public_html/wp-content
WP_PLUGIN_DIR: /home/carsbyca/public_html/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 768M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

`


Best Regards,
Adirake Ekphaisansup (Lucky)

**Comment by ernee** [comment]
@luckyadirake thanks for the info! I'm curious if this is related to your theme.

1) Does your theme offer Open Graph settings and do you have them enabled? 

2) I see you're using a child theme as well. Are you able to safely check your theme files (header.php perhaps) to see if the following has been added manually in the`<html>` tag: `xmlns:og="http://opengraphprotocol.org/schema/" xmlns:fb="http://www.facebook.com/2008/fbml"`?

**Comment by ernee** [comment]
@luckyadirake just following up to see if you were able to make the above checks?

**Comment by luckyadirake** [comment]
Hi sorry for late reply, i m using yoast plugin for seo purposes

If its the theme , there is nothing that states xml fb

**Comment by swissspidy** [comment]
@luckyadirake Could you try uninstalling the plugin and installing this in-development version to see if the issue persists? Download: [web-stories.zip](https://github.com/google/web-stories-wp/files/5062050/web-stories.zip)

Report back here when you've done it so we can take a look. Thanks!

**Comment by ernee** [comment]
@luckyadirake I'm following up on your reported issue. 

Have you tried the latest Beta 2  available for download [on the website](https://google.github.io/web-stories-wp/beta/)? If you have a chance, could you try it and let us know if this issue persists? thanks so much!

**Comment by luckyadirake** [comment]
I ll try and let u know asap thanks alot

**Comment by ernee** [comment]
@luckyadirake just following up to see if you had a chance to try the most recent version 1.0.0-rc.1? Feel free to let us know if you still experience the issue.

**Comment by ernee** [comment]
@luckyadirake the stable version of the plugin 1.0.0 has been released. Please feel free to update and reach out to us in our [WordPress.org support forum](https://wordpress.org/support/plugin/web-stories/) if you should still experience the issue. Happy to help!
