### ISSUE TITLE
Issue with report in Search Console and Stories pages

### ISSUE THREAD

**Issue by quadcom** [GoogleForCreators/web-stories-wp#3409]
**## Bug Description**

Search Console is reporting "image size smaller than recommended" but it does not tell which image or where in the page collection it's talking about.

**## Expected Behaviour**

First, is the WP plugin not following Google's own recommendations on image sizes or is the Search Console unaware of how to view the content?

**## Steps to Reproduce**

I submitted a sitemap with the stories listed.

**## Screenshots**
![image](https://user-images.githubusercontent.com/7085931/88325848-74fbce00-ccf3-11ea-98de-09eb1664ff7a.png)

**##Site Address**
       https://torontoheadshot.com/m/stories/headshots-toronto/
       https://torontoheadshot.com/m/stories/linkedin-headshots/

## Additional Context

- Plugin Version: 1.0.0-beta.1
- Operating System: Win10
- Browser: Chrome
- WP: 5.4.2

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Hi there,

Thanks for your report!

It looks like a small edge case where we're not passing the correctly sized cover image (poster image).

We'll take a closer look and let you know once we know more.

**Comment by LuckynaSan** [comment]
@quadcom GitHub issue #3434 should have resolved this issue. Can you please try downloading the latest version of the [Web Stories plugin](https://wordpress.org/plugins/web-stories/) and report any other issues you encounter on the [Web Stories Support Forum](https://wordpress.org/support/plugin/web-stories/). Thank you!
