### ISSUE TITLE
Editor crashing

### ISSUE THREAD

**Issue by hoyyosoy** [GoogleForCreators/web-stories-wp#3410]
Could not make a single story, it crashes all the time.

![2020-07-23 16_33_47-Dashboard ‹ — WordPress](https://user-images.githubusercontent.com/54292976/88331402-45ed5880-cd03-11ea-9673-d971af040921.png)
![2020-07-23 16_34_57-Add New Story ‹ — WordPress](https://user-images.githubusercontent.com/54292976/88331405-471e8580-cd03-11ea-8181-7b334b81e8cd.png)

**Comment by swissspidy** [comment]
Hi there

When you see the "Something went wrong" screen, please open your browser's developer tools (press F12) and check the Console tab. Which error message do you see?

Also, does this still happen with all plugins disabled?

**Comment by hoyyosoy** [comment]
Hi, and thanks.
Here is the screenshot:
[image: 2020-07-23 16_53_11-.png]

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by swissspidy** [comment]
@hoyyosoy I'm afraid the screenshot did  not upload. Could you upload it via the GitHub website instead of via email? Thanks!

**Comment by hoyyosoy** [comment]
no problem
![2020-07-23 16_53_11-](https://user-images.githubusercontent.com/54292976/88336263-10e50400-cd0b-11ea-9c17-5660bba53743.png)

**Comment by ernee** [comment]
@hoyyosoy thanks for the screenshot! 

1) Could you also upload an image of what's in the _Console tab_ here: 

![88336263-10e50400-cd0b-11ea-9c17-5660bba53743](https://user-images.githubusercontent.com/8108643/88441033-ad1f1180-cdc4-11ea-8d95-0ee0d1301f29.png)

2) If possible, could you safely deactivate other plugins one by one to see if any are involved? Alternatively, you can use the [Health Check and Troubleshooting](https://wordpress.org/plugins/health-check/) plugin, which will allow you to safely disable plugins (and switch to a default theme) for only the logged in user in _Troubleshooting_ mode. More on [how to use it here](https://make.wordpress.org/support/handbook/appendix/troubleshooting-using-the-health-check/#troubleshooting).

**Comment by hoyyosoy** [comment]
1. yep
2. not today, let you know tomorow
![2020-07-24 21_04_26-Mouse Highlight Overlay](https://user-images.githubusercontent.com/54292976/88444044-862b0480-cdf1-11ea-8d73-6282ac1a42a2.png)
![2020-07-24 21_02_59-Mouse Highlight Overlay](https://user-images.githubusercontent.com/54292976/88444048-875c3180-cdf1-11ea-8c4a-05763c976944.png)

**Comment by ernee** [comment]
@hoyyosoy I hope you're well. I was wondering if you had a chance to check if any of your other plugins could be involved? Thanks again for any feedback at your convenience!

**Comment by hoyyosoy** [comment]
Thanks for your help. I've abandoned the project until they fix the bug, or
google gets help for this issue.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by ernee** [comment]
@hoyyosoy thanks for the update! If you have a chance to provide your [Site Health Information](https://i.imgur.com/Rtkmsba.png) or a list of your active theme and plugins that could be helpful for us to continue troubleshooting the beta version. 

We'll follow up on the issue as we have more information. Many thanks!

**Comment by ernee** [comment]
Hi @hoyyosoy! Have you tried the latest Beta 2 available for download [on the website](https://google.github.io/web-stories-wp/beta/)? If you have a chance, could you try it and let us know if this issue persists? Thank you!

**Comment by hoyyosoy** [comment]
I gave a try once more, for like 2 hours, although I followed all the steps
had no luck when I tried to embed it to a post.
Also see attached screenshot from Search Console. Sorry but couldn't make
it work.
[image: 2020-09-13 16_58_52-Window.png]

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by ernee** [comment]
@hoyyosoy thanks so much for your attempt! We cannot view screenshots attached on the email reply, but feel free to upload it directly here in the Github issue.

Just to confirm: so the editor is now working for you (you can create the story), but you are having problems embedding the story in a post? 

Also, there is a new version of of the plugin 1.0.0-rc.1 available - did you try this version (it's available as an update as well as [on the website](https://wp.stories.google/))?

**Comment by hoyyosoy** [comment]
As I said I gave Stories a try once more, for like 2 hours, although I followed all the steps had no luck when I tried to embed it to a post. Also see attached screenshot from Search Console. Sorry but couldn't make it work. I have the latest version installed.
![2020-09-13 16_58_52-Window](https://user-images.githubusercontent.com/54292976/93115449-3c90c480-f692-11ea-8d2c-7a47a2229987.png)

**Comment by swissspidy** [comment]
@hoyyosoy Please share the URL to your story so we can help. Also, can you clarify what you mean with "had no luck when I tried to embed it to a post". What exactly didn't work?

**Comment by hoyyosoy** [comment]
Hi, and thanks.
I created the story, hit publish and an error shows up, attached.
Hit publish again and it works.
But when I go to see the story there is an empty page, see link: https://soñada.com/la-sonada-mas-que-un-residencial/

![2020-09-14 16_32_45-Window](https://user-images.githubusercontent.com/54292976/93130591-204c5200-f6a9-11ea-8d50-c8f2bebd532d.png)
![2020-09-14 16_34_44-Window](https://user-images.githubusercontent.com/54292976/93130603-25110600-f6a9-11ea-80f9-c1fdf1e47e3c.png)

**Comment by ernee** [comment]
@hoyyosoy thanks for your reply and the screenshots! Thanks for providing [your story URL ](https://xn--soada-pta.com/stories/1523/)which shows the two validation errors in your previous screenshot and might be a factor in the issue. 

Could you temporarily disable the Autoptimize plugin and let us know if the issue/ errors persist?

**Comment by ernee** [comment]
@hoyyosoy the stable version of the plugin 1.0.0 has been released. While I no longer see the validation errors on the story URL,  please feel free to update and open a topic in our [WordPress.org support forum](https://wordpress.org/support/plugin/web-stories/) if there are still issues with embedding the story in your page. Happy to help troubleshoot further there.
