### ISSUE TITLE
Filter to only show media uploaded in Stories Editor

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#342]
As an editor I want to be able to filter media that was uploaded through the story editor

**Acceptance Criteria**

1. Create hidden taxonomy and tag media uploaded via the stories editor
2. Media uploaded through the story editor is identifiable 
3. Media in the gallery can be filtered by media uploaded via the stories editor

**[Feature Brief - Epic: Media Gallery](https://docs.google.com/document/d/1aZH_TI_be2t5Ywyqx4jcPTPdhFGEt7xh-uLzBp2AV4A/edit)**

**Comment by spacedmonkey** [comment]
I think we should add a new term in PHP, so whatever way an image / video is uploaded, at long as the parent id is a story, then term is added.

**Comment by diegovar** [comment]
@swissspidy does this require changes on the Wordpress side?

**Comment by swissspidy** [comment]
Yes it does

**Comment by swissspidy** [comment]
LMK if you wanna tackle this soon so we can prioritize it.

**Comment by kmyram** [comment]
Move to WP&Infra pod

**Comment by swissspidy** [comment]
@o-fernandez Is this still slated for stable? There's no design for this yet, but we could make the necessary backend changes already so that we have the data already once we add the UI.

The spec currently says  this:

> In addition, there’s an affordance to show only photos uploaded through the story editor, as the assets that many will upload through the editor often do not make sense to use in general posts and pages, and vice versa. Therefore, we’ll create a hidden tag/taxonomy when we upload media through the editor, to be able to then filter in the UI.

**Comment by swissspidy** [comment]
@o-fernandez friendly ping

**Comment by o-fernandez** [comment]
I think we'd want this to go through UX design before prioritizing it for the workspace pod, however, I do think we'd want it eventually so it'd make sense to at least appropriately tag things in the backend so when we roll this out in the UI the data is complete. 

So, let's make this a backend-only ticket for now, and I'll file a separate ticket for the workspace effort to be added post Beta. 

Sorry for the delay responding. 

#2190 will track the workspace/media panel work and design effort for it.

**Comment by swissspidy** [comment]
@spacedmonkey could you take that on?

I think we need a hidden taxonomy named like `web-story-media-source` or something, with terms like `editor`, `coverr`, and potentially others.

Depending on how media is uploaded, we'd add the correct term.

**Comment by spacedmonkey** [comment]
In the unsplash plugin I used a hidden taxonomy called `media_source`. The idea is to at some point support third party media library in core and use this taxonomy to denote the source of media. Thoughts on reusing this key?

**Comment by swissspidy** [comment]
Interesting, good to know! Not entirely sure yet, but feel free to use `media_source` for now. We can always rename it during development if we want to.

I wrote `web-story-media-story` as I want to avoid conflicts with other plugins. If there's ever a `media_source` taxonomy in core, we can leverage our DB upgrader to migratte.

**Comment by spacedmonkey** [comment]
So cab you confirm, all places in the editor that user uploads an image, should be tagged with a `web-story-media-source` term with the value `editor`? 
So these include. 
- Drag and drop ( media library )
- Drag and drop ( canvas )
- Paste upload
- Upload via media picker. 

What about generated poster images?

Adding the term should as simple as adding here 

https://github.com/google/web-stories-wp/blob/74490fdd0399fd772417b936d120988ea7a14115/assets/src/edit-story/app/uploader/useUploader.js#L116-L118

and here 

https://github.com/google/web-stories-wp/blob/74490fdd0399fd772417b936d120988ea7a14115/assets/src/edit-story/components/mediaPicker/useMediaPicker.js#L57-L67

**Comment by swissspidy** [comment]
Yep, that sounds about right! 👍 

We can ignore poster images. They are a bit of a special case.
