### ISSUE TITLE
Clarify Video Poster Behavior

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#3438]
## Task Description

Two cases where I am not sure if those are _working as intended_, or if those are _bugs_.

**Scenario 1:**

1. I upload a video to the editor in the media library panel on the left side.
1. The video is automatically added to the WordPress media library.
1. In the background, a poster image is being generated and attached to the video.
1. I add the video to the canvas.
1. I manually change the video's poster image to be something else.

Current behavior: The poster image is changed for the video element on the canvas, but not in the WordPress media library.

Question: should the poster image change be reflected in the WordPress media library.

**Scenario 2**

1. I upload a video to the editor in the media library panel on the left side.
1. The video is automatically added to the WordPress media library.
1. In the background, a poster image is being generated and attached to the video.
1. I add the video to the canvas.
1. I add the video to the canvas _**a second time**_.
1. I manually change the first video's poster image to be something else.

Current behavior: The poster image is changed for the first video element, but not for the second  video element.

Question: should the poster image be changed for both video elements?

## Context

This came up while Jonny was  looking into #3230 and #1218.

**Comment by samitron7** [comment]
1. Should the poster image change be reflected in the WordPress media library.
I say yes. Any change on the stage should be reflected in the library or else it's a bit confusing.

2. Should the poster image be changed for both video elements?
@swissspidy confirmed that you can only have 1 poster image attached to an image in the WordPress media library at a time (even though we store the original generated one if you replace it - it's just not exposed to the users to see)? If this the case, we need to make both poster images on the page the same.

**Comment by o-fernandez** [comment]
Reading through the poster image guidelines, the poster image is meant to be representative of the video. If users are doing this properly, I think both of your proposals are good -- also show in the media library (scenario 1) and keep the poster image for use in future times the video is added to the page (scenario 2).

**Comment by swissspidy** [comment]
Thank you both! Created #3441 and #3442 to address this!
