### ISSUE TITLE
Plugin Activation Message Refinements

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#3439]
## Task Description

Follow-up to #2853:

1. Set font weight for "You're all set. Tell some stories" to regular
2. The button should have 4px rounded corner.
3. the first image (rotated story screenshot) should be brought down a bit so that you don't see the left bottom corner
4. Link to https://google.github.io/web-stories-wp/beta/tips.html
5. Remove double lick logic in favor of dark mode preference detection

**Comment by swissspidy** [comment]
See #3559 for testing instructions

**Comment by csossi** [comment]
Installed Dark Mode plugin and set it in User Profile. Should the background be darker instead of white when in dark mode?:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/52dda754-93a7-40df-90b2-e944fca4f03e)![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/3a73cb46-7977-4a66-8f78-62edc297db6b)

**Comment by swissspidy** [comment]
@csossi I don‘t know about any Darm Mode plugin. This PR refers to the dark mode setting in your operating system.

**Comment by swissspidy** [comment]
If your OS doesn‘t have that, white is expected.

**Comment by swissspidy** [comment]
@csossi This is what I am talking about:

<img width="780" alt="Screenshot 2020-08-07 at 14 45 54" src="https://user-images.githubusercontent.com/841956/89646825-ca6fd780-d8bc-11ea-983a-7e01708c616e.png">

If you don't have that on your OS, can you at least confirm you were able to verify the other things?

**Comment by csossi** [comment]
Understood, @swissspidy - will review

**Comment by csossi** [comment]
Verified in QA

**Comment by swissspidy** [comment]
Thanks @csossi!

**Comment by samitron7** [comment]
Added a side-by-side comparison of the design mock top and the implementation (bottom). Spacing is off on quite a bit of things and missing a scrim (black gradient overlay at the bottom)

<img width="998" alt="Screen Shot 2020-08-13 at 11 21 17 PM" src="https://user-images.githubusercontent.com/10889431/90219968-18547600-ddbc-11ea-98b1-fd29390383f3.png">
<img width="1554" alt="Screen Shot 2020-08-13 at 11 21 08 PM" src="https://user-images.githubusercontent.com/10889431/90219972-1b4f6680-ddbc-11ea-88b2-2fb777e57957.png">

Also, I was not able to see the light mode even after toggling my sys dark/lite mode setting. Can we get a screenc apture of that

**Comment by swissspidy** [comment]
Will add screenshots of both versions in a bit.

But is the scrim a new addition? 🤔 If not, it was missed already last time.

**Comment by swissspidy** [comment]
> Spacing is off on quite a bit of things

With a responsive design, it's very hard to get pixel perfect result on every screen size. There's definitely some room for improvement though, which we can add for sure.

> missing a scrim (black gradient overlay at the bottom)

Ah, now I realize that the dark mode option has a scrim but the other one doesn't. I must have missed that!

> Also, I was not able to see the light mode even after toggling my sys dark/lite mode setting. Can we get a screen capture of that

Currently looks like this:

<img width="1680" alt="Screenshot 2020-08-14 at 11 23 57" src="https://user-images.githubusercontent.com/841956/90238226-deb85500-de25-11ea-9802-4c57baddb151.png">

----

I've opened #3906 for further refinements of the plugin activation message.
