### ISSUE TITLE
Videos: Update Poster in Media Library

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#3441]
## Bug Description

As clarified in #3438, when changing the poster image of a video, the change also needs to be reflected in the database.

## Expected Behaviour

A request to the REST API is made to update the `featured_media` field of the video to what was selected by the user.

## Steps to Reproduce

1. I upload a video to the editor in the media library panel on the left side.
1. The video is automatically added to the WordPress media library.
1. In the background, a poster image is being generated and attached to the video.
1. I add the video to the canvas.
1. I manually change the video's poster image to be something else.
1. The poster image is changed for the video element on the canvas, but not in the WordPress media library.

## Additional Context

Related: #1218, #3442

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

* When changing the poster image of a video, the change is also reflected in the database.

**Comment by bmattb** [comment]
During grooming we discussed that we need to confirm from the perspective of the WP backend that the user could still restore the original poster image

**Comment by swissspidy** [comment]
Seems like this is working as intended. Changing the poster for a video on the canvas should not change it in the database.
