### ISSUE TITLE
Ezoic compatibility: AMP Issue in Search Console

### ISSUE THREAD

**Issue by JenTow** [GoogleForCreators/web-stories-wp#3448]
## AMP Issue In Search Console

After posting my first web story I received an error in search console. The error reads "Tag 'amp-story' is not allowed to have any sibling tags ('body' should only have 1 child)."

## I am not sure how to fix this error

 Here is the url to my web story. https://digitalsheeo.com/stories/11-reasons-to-love-the-tasty-pins-pinterest-plugin/

## Steps to Reproduce

 I found it in search console

## Additional Context

- Plugin Version: Version 1.0.0-beta.1 
- Operating System: Mac Mojave 10.14.6
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Hi there

Please share the URL to your story

**Comment by JenTow** [comment]
https://digitalsheeo.com/stories/11-reasons-to-love-the-tasty-pins-pinterest-plugin/

I had shared it above under steps to reproduce the error. Sorry - I'm new to GitHub. Thanks for your help.

**Comment by ernee** [comment]
@JenTow not a problem and thanks for sharing the URL! 

From what I can see, there is [a validation error](https://jumpshare.com/v/knw0Wqnf0zvrugKTQdWZ) on the story page due to either a plugin or service placing the `amp-analytics` tag in the wrong place in the HTML of the page. (It should be inside the `amp-story` tag, but currently it outside of it as a sibling tag). 

What are you currently using to implement Analytics on your site? I see references to `ez-amp-analytics`.

**Comment by JenTow** [comment]
I added the code myself without using a plugin. Does that help?

**Comment by ernee** [comment]
@JenTow thanks for the info! 

So the specification requires the `amp-analytics` tag to be within the `amp-story` tag. Could you provide more details about where you added the code? 

Currently, the [Site Kit plugin](https://wordpress.org/plugins/google-site-kit/) automatically places the amp-analytics tag properly if using its code snippet.

We're currently working on providing a way to add the [tracking ID from a settings area]( https://github.com/google/web-stories-wp/issues/3482) in the Web Stories plugin Dashboard.

**Comment by JenTow** [comment]
I just deleted the code I had added and installed the site kit plugin. I had installed it in the header.php file before. I never used a plug in for analytics.
The only plug in I have for AMP that I know of is the beta. 
Sorry for the newbie questions - but when you launch this to the public you’ll get tons of people like me :) Good practice!
Thanks again,
Jen

**Comment by JenTow** [comment]
I also received an email this morning saying that my images are not large enough for AMP. When I went to the documentation it is asking for an image that is at least 1200 px wide. Web story images are only 828 px wide. How do I fix this?

**Comment by ernee** [comment]
@JenTow thanks so much for reaching out! It's definitely helpful for us too. 

> I just deleted the code I had added and installed the site kit plugin. I had installed it in the header.php file before. I never used a plug in for analytics.

Interestingly, I'm still seeing the error when I run the story in the [AMP Test tool](https://search.google.com/test/amp?url=https%3A%2F%2Fdigitalsheeo.com%2Fstories%2F11-reasons-to-love-the-tasty-pins-pinterest-plugin%2F) and see the same code in the source code (along with Site Kit's code). 

Could you try clearing the cache in your caching plugin? We can then check the story again.  

> I also received an email this morning saying that my images are not large enough for AMP. When I went to the documentation it is asking for an image that is at least 1200 px wide. 

Could you provide the full error message or perhaps a screenshot of what's reported in your Search Console account?

We are working on addressing [an issue](https://github.com/google/web-stories-wp/issues/3297) with the automatic sizing of the [poster image ](https://amp.dev/documentation/components/amp-story/#poster-guidelines-(for-poster-portrait-src,-poster-landscape-src,-and-poster-square-src))for the story. It would be good to confirm if this is related.

**Comment by JenTow** [comment]
I did clear the cache (a couple of times to be safe). The only thing I can
think of is the beta plugin has a bug? I don’t have any other plugin that
adds analytics.

For the image issue, here’s a screenshot of the message I received.

Thanks so much for your help!

**Comment by ernee** [comment]
@JenTow sure thing and thanks for the details! 

The Web Stories plugin wouldn't add the code from `ez-amp-analytics`.  Note that I'm seeing the invalid block of code for `amp-analytics` from this source twice in the HTML of the page: at the beginning and the end of the `body` tag. 

Are you also using the [Ezoic service](https://www.ezoic.com/) on your site? In one of the code blocks I see this:` clientId(AMP_ECID_EZOIC)`

> For the image issue, here’s a screenshot of the message I received.

It doesn't look like the screenshot came through. You can drag and drop the screenshot to upload it to the comment [as seen here](https://github.blog/2015-09-25-attach-files-to-comments/#:~:text=Just%20drag%20and%20drop%20the,will%20appear%20in%20your%20comment.).

**Comment by swissspidy** [comment]
> I also received an email this morning saying that my images are not large enough for AMP. When I went to the documentation it is asking for an image that is at least 1200 px wide. Web story images are only 828 px wide. How do I fix this?

Note that images are used in various places for stories and we crop the images if needed.

Looking at the  story you shared earlier, I see that the featured image of your story (https://digitalsheeo.com/wp-content/uploads/2020/07/11-Reasons-To-Love-Tasty-Pins.png) is smaller than 1200px wide. So you'd need to make that bigger.

**Comment by ghost** [comment]
@ernee 

> Are you also using the [Ezoic service](https://www.ezoic.com/) on your site? In one of the code blocks I see this:` clientId(AMP_ECID_EZOIC)`

I'm seeing the same errors above with my Ezoic integration.

I did a quick attempt to solve this by setting Ezoic to exclude my site's route to web /stories/ and purge both WordPress and Ezoic caches.  Unfortunately, this didn't help and I'm seeing sibling `<amp-analytics>` blocks added above and below `<amp-story>` (with duplicate `id` attrs...oooo).

I'll open a support ticket with Ezoic to find out if they have an open issues around this.

**Comment by ernee** [comment]
@itsmikechu thanks for reporting! Feel free to provide an update here on what you find out.

**Comment by ghost** [comment]
I've walked Ezoic Support through the details.  They're passing it onto the tech team.

**Comment by mikechu-pennfoster** [comment]
While I wait for tech support to investigate and respond, I excluded the /stories/ route from Ezoic.

![ezoic-exclud-pages-amp-web-stories](https://user-images.githubusercontent.com/66074888/89067904-76bb3680-d370-11ea-8bd0-fd0541b456bb.png)

My AMP [web story]( https://dataoverhaulers.com/stories/safest-social-networks/) validated in Google Search Console. :+1:

**Comment by ghost** [comment]
While I wait for tech support to investigate and respond, I excluded the /stories/ route from Ezoic.

![ezoic-exclud-pages-amp-web-stories](https://user-images.githubusercontent.com/2320216/89068600-dd8d1f80-d371-11ea-8aaa-42d88f9e2550.png)

My AMP [web story]( https://dataoverhaulers.com/stories/safest-social-networks/) validated in Google Search Console. :+1:

**Comment by ernee** [comment]
@itsmikechu great tip for those using the Ezoic service in the meantime! 

@JenTow if you have access to the above settings, this might help in your case.

**Comment by ghost** [comment]
I received notification from Ezoic support that they've pushed an update for their AMP integration.  I'm removing the exclusion rule from earlier and testing...

**Comment by ghost** [comment]
>Hi there,
>The developers have resolved this issue by rendering everything in the /stories folder as static content - removing our own analytics from the affected pages.
>Your Ezoic Team,

**Comment by ernee** [comment]
@itsmikechu really appreciate the updates. Has the validation error resolved on your story? Feel free to share a URL if you like.

**Comment by JenTow** [comment]
It still has not fixed the issue for my story. I retested this morning and
I’m still getting the error message

**Comment by mikechu-pennfoster** [comment]
@ernee, Yes. My validation errors are gone and the DOM looks good on my WP web story https://dataoverhaulers.com/stories/safest-social-networks/

@JenTow, I see that yours still has the invalid `<amp-analytics />` tags.  Have you tried 
1. clearing your WP cache 
![image](https://user-images.githubusercontent.com/66074888/89570463-86ca8e80-d826-11ea-96a6-0607e18b431d.png)
2. clearing your Ezoic cache
![image](https://user-images.githubusercontent.com/66074888/89570586-b4173c80-d826-11ea-8efa-0317bcc07096.png)

**Comment by ghost** [comment]
@ernee, Yes. My validation errors are gone and the DOM looks good on my WP web story https://dataoverhaulers.com/stories/safest-social-networks/

@JenTow, I see that yours still has the invalid <amp-analytics /> tags. Have you tried:
1. clearing your WP cache
![image](https://user-images.githubusercontent.com/2320216/89570818-ff314f80-d826-11ea-8be9-efe589fc134e.png)

2. clearing your Ezoic cache

![image](https://user-images.githubusercontent.com/2320216/89570871-11ab8900-d827-11ea-9a8b-97409750f697.png)

**Comment by JenTow** [comment]
I cleared both and haven’t seen a change. Any other ideas? Thanks so much for your help. I am trying everything you offer.

**Comment by ghost** [comment]
You might reach out to Ezoic support.  They've been responsive and quite helpful.  Point them to this thread for sure.

**Comment by ernee** [comment]
@itsmikechu @JenTow thanks for the update and this additional information. I've also reached out to Ezoic to see how we can resolve this since the changes don't appear to be immediately applied in some cases. I'll update this issue with more info when I know more.

**Comment by ernee** [comment]
@itsmikechu @JenTow  just quick update that the Ezoic team is still looking at applying these changes on their platform. They'll keep us updated on the progress and I'll also update you here. Have a great weekend!

**Comment by ernee** [comment]
Hi @JenTow ! Just following up on this issue. The Ezoic team has informed us of a fix on their platform. I'm currently not experiencing the issue any longer. When checking [your story](https://digitalsheeo.com/stories/11-reasons-to-love-the-tasty-pins-pinterest-plugin/), the service does not look like it is activated- have you made changes? 

It would be great to get your confirmation whether you're still experiencing the issue with Ezoic.

**Comment by ernee** [comment]
@JenTow we just released the stable version of the plugin 1.0.0 and the issue is resolved for me using Ezoic. I'll close your issue now since we're moving support to the [WordPress.org forums](https://wordpress.org/support/plugin/web-stories/), so please don't hesitate to reach out to us there for any further questions or concerns.

**Comment by 0xSatwik** [comment]
Any way to monetize web stories. I am using ezoic ads to my website. Please help me
All the stories link- 
https://liteblogging.com/web-stories/

**Comment by 0xSatwik** [comment]
Please give me a way please. I have ezoic and adsense approval. I am using Google Web stories plugin

**Comment by swissspidy** [comment]
@airdropking1810 We already replied to you [on the WordPress.org support forums](https://wordpress.org/support/topic/adsense-ads-are-not-showing-3/) with all possible information. Let's keep the conversation there; we don't provide support on GitHub.

To recap:

* Your AdSense configuration looks correct
* It can take some time for ads to appear, be patient
* Try creating longer stories with more than 7 pages
* Try [AdSense troubleshooting](https://support.google.com/adsense/workflow/10383839?hl=en)
* If you still have issues with AdSense, reach out to [AdSense support](https://support.google.com/adsense/#topic=3373519)
