### ISSUE TITLE
Elementor, and some way to put it in frontend

### ISSUE THREAD

**Issue by polyinnovator** [GoogleForCreators/web-stories-wp#3450]
What is the capabilities of being able to show it in your site? Especially with things like page builders, such as mine: Elementor?

**Comment by swissspidy** [comment]
Great question!

Right now we support embedding individual web stories using a dedicated Gutenberg block.
We aim to provide more such blocks in the future.

Curious to hear how you would imagine an integration in Elementor - what kind of functionality would you like to see?

**Comment by WebSwiftSEO** [comment]
Hello @swissspidy 

Unrelated to Elementor but related to integration into wordpress in general, It would be good if there was a story slider like how most social network display stories. Possibly a short code and or other such functionalities to integrate story siders into wordpress. I was also thinking about a category style page that lists the stories as I notice that the example.com/**stories**/ is just a 404 page. 

Best Regards

Ylia

**Comment by polyinnovator** [comment]
@WebSwiftSEO @swissspidy It is COMPLETELY related to elementor. It has the power to do what you are saying, if programed to. So if you are on the website there can be a button on the frontend, specifically placed with the page builder, or floating with html or something. So that people on the site can interact with the stories as well.

My page builder doesn't really interact with the gutenburg block, it might work, but I don't it will look right. So either something can be used with builders, or just on top of in the corner?

i,e, https://wordpress.org/plugins/wp-story/

**Comment by WebSwiftSEO** [comment]
Sorry @polyinnovator I meant my comment was unrelated to Elementor.

**Comment by polyinnovator** [comment]
@WebSwiftSEO but it isn't though. That is why I replied what you are saying there is something that I would want with elementor being the powerhouse to cause it to happen. I think it would be too hard to get it to work with gutenburg, but elementor could probably handle what you're saying if it was programmed that way.

I want something like that as an elementor widget, or at least floating like I said in my other comment.

**Comment by WebSwiftSEO** [comment]
@polyinnovator I don't use page builders as I don't see the need with Gutenberg and in the past they compile code in a bloated and un optimized fashion. @swissspidy It would be good if there was a story slider like how most social network display stories. Possibly a short code and or other such functionalities to integrate story siders into wordpress. Also a category style page that lists the stories as I notice that the example.com/**_stories_**/ is a 404 page. 

Example Story Slider Screenshot:  https://prnt.sc/tonevg 

Best Regards 

Ylia

**Comment by polyinnovator** [comment]
I think that the shortcode idea is good. You'd be surprised how optimized
many page builders are now for wordpress. Certainly not like wix or other
non wordpress ones, but webflow for example uses practically base code.

Elementor is also one of the strongest ones out there.

Point is that I have no use case for this plugin if my people on my site
can't see it, I don't want to make another facet of content purely for SEO
purposes. I'm happy to do it for a dual purpose, but not standalone.

Ylia I think we are saying the same thing, we want some sort of frontend
solution to be able to have a way for the user on the site to see the
stories in addition to what google does with them in search. :)

**Comment by wolfmaster8** [comment]
I suggest making a widget [amp-stories] for displaying in the frontend. Don't need to make a particular integration.

**Comment by polyinnovator** [comment]
My site doesn't use widgets really at all, I think with gutenburg they are
straying away from them. I haven't seen any for a long time. Although a
short code would be a great idea.

**Comment by swissspidy** [comment]
Thanks everyone for your inputs!

I'll try to summarize the feedback so far:

* Widget(s) to embed stories - being tracked in #3687
* Shortcode(s) to embed stories - being tracked in #3135
* Elementor Widget to embed stories - being tracked in #3688
* Story "slider" to show most recent stories - note that we're planning a "Latest Stories" block in #3064 
* Archives page (`example.com/stories/`) - note that this one is already planned and being tracked in #3063 

Please let me know if I missed anything

**Comment by polyinnovator** [comment]
No that is perfect thank you for the synopsis! All of you were great for
the ideation.

**Comment by swissspidy** [comment]
Hi all

I've split this ticket up into five separate ones, please follow the ones you are interested in for any updates:

* Widget support: #3687
* Shortcode support: #3135
* Elementor support: #3688
* Latest Stories block: #3064 
* Archives page: #3063
