### ISSUE TITLE
Permalink input field doesn't allow hyphens anywhere, nor spaces at the end

### ISSUE THREAD

**Issue by hansschuijff** [GoogleForCreators/web-stories-wp#3455]
## Bug Description

In the editor when manually changing the permalink, the entry field ignores hyphens that I type and spaces at the end of the entry string. So I can't enter something like "girl-hugs-lion" in the way it is written. I can insert hyphens by first entering "girlhugslion" and then go back and insert a space wherever I want the hyphen, since it translates the space to a hyphen. But what I also cannot do is directly type "girl hugs lion" and having it translate to "girl-hugs-lion", since spaces at the end of the field (and any char is the last char while you're first type the string) are ignored too.

## Expected Behaviour

In all other entry fields in WordPress all allowed permalink characters can also be entered directly in the entry-field and even none-allowed chars. Non allowed chars are filtered out,  and spaces translated to hyphens, only when the field is exited. So I should be able to just start typing in the permalink field using hyphens and spaces in the middle or at the end of the field and the system will translate when needed. When the plugin choses to validate during typing at least the allowed chars should be permitted.

## Steps to Reproduce

* Open the stories editor
* Go to the document option tab in the editor sidebar
* Enter a string containing spaces and/or hyphens in the permalink field.
* Notice that both hyphens and spaces are ignored while entering the string
* Try to insert a hyphen anywhere in the permalink
* Notice that no hyphen is inserted
* Try to insert a space anywhere in the permalink
* Notice that it is translated to a hyphen anywhere but at the end

Additional ways to reproduce issue:

1) Start a new story _without a title_.  One cannot add hyphens/ spaces within text until after the story is saved. [Video](https://recordit.co/dq74419Wtv)) 

2) Start a new story with  _a title_. One can add  hyphens/spaces within the pre-populated text.  ([Video](https://recordit.co/4yoinQqaUw))

In all cases,  adding hyphens/ spaces  _after_ the text is not possible. 

Possibly related detail: 

3) When using keys like space or underscore in the permalink entry field within the permalink value (so not at the end), the keystroke is translated to a hyphen, but the cursor is also moved to the end of the entry field. Expectation is that would remain on its position.

## Additional Context

- WordPress version: 5.4.2
- PHP version: 7.3.5
- Plugin Version:  1.0.0-beta.1
- Operating System: Windows 10
- Browser: Firefox Developer 79.0b9 (64-bits)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

1. Go to document panel
1. Type something with spaces and/or dashes and observe, that it is possible (though both appear as dashes)
1. Make sure to leave a trailing hyphen, then blur the input field and observe, that the trailing hyphen is removed

**Comment by ernee** [comment]
@hansschuijff thanks for reporting! 

1) I am able to recreate the same with a new story _without a title_. After saving the story, I am able to add the hyphens/spaces within the text as expected. ([Video](https://recordit.co/dq74419Wtv)) 

2) When  editing the permalink in a new story _with a title_, I can add hyphens/spaces within the pre-populated text.  ([Video](https://recordit.co/4yoinQqaUw))

However, I cannot add hyphens/ spaces  _after_ the text, even after saving in both cases. 

I'll flag this for us to look into further.

**Comment by o-fernandez** [comment]
@barklund is this something that the Workspace pod could look at? We'd want this prior to 1.0 Stable. 
@bmattb @chris-pgm FYI.

**Comment by hansschuijff** [comment]
Hi @ernee 

Thanks for checking the issue. I have tried again and am able to use hyphens like you within the permalink, only not at the end. So your findings are like mine now. But retrying it, I found some more details:

1. When I use keys like space or underscore in the permalink entry field within the permalink value (so not at the end), the keystroke is translated to a hyphen, but the cursor is also moved to the end of the entry field. I would expect it to remain on it's position.

In your video I saw you starting of with a template, and I hadn't used it like that yet, since from the menu I just chose add new. As a route the dialogue now seems a bit inefficient and it seems strange that template selection isn't part of the add new dialogue. 

Using the first template I run into two other issues:
1. The editor page is scrolled max down, so in my case, since my admin menu is longer, the actual editor isn't actually in the viewport, making me scroll up before I can edit.
2. When I scroll up maximum to the top, the buttons and title field are partly behind the admin toolbar and I cannot scroll to a point they are completely visible.

[Here's my video](https://recordit.co/XJ768RNk3o) so you can see what I saw.

The structure seems a bit strange to me, and I would expect templates to be part of the add new also, since that is the normal route in WordPress, or at least the templates should be part of the stories admin menu too, making it directly visible as an option. Normally with a custom post type I would expect add new to be a starting point for creating stories and the "all stories" to give access to the list. It seems that the dashboard tries to combine that in a more visual interface, but then it probably should replace the others, or add the templates too in the menu. And how am I expected to go from the dashboard to viewing stories on the frontend?

When templates is a way to add new stories based on prefabricated stories, it should in some form be part of the add new story dialogue. Something like: 1. Choose add new. 2. Get to select a template (or a blank canvas) 3. edit the content.

Anyway, except for missing an option to see stories in the frontend, the dashboard seems pretty complete, so probably most of the time the other menu-items will not be needed. On a system with long response times eliminating steps (page loading) would be helpful.

Thanks for looking into it.

Hans

**Comment by ernee** [comment]
@hansschuijff  sure thing and really appreciate your feedback! 

While we'll keep this issue specifically for the issue with the hyphen and spaces to be addressed,  I've moved your findings regarding the shifting workspace to [this similar issue](https://github.com/google/web-stories-wp/issues/3248) and also opened [a new issue ](https://github.com/google/web-stories-wp/issues/3650)for your request about the placement/ access for using templates. 

Please feel free to provide any more details in those respective issues (I've asked a few clarifying questions there too).

**Comment by hansschuijff** [comment]
@ernee Thanks for that, I knew I was going a bit off topic here, but it was connected with my test for this issue, so I just added it for what it's worth.

**Comment by csossi** [comment]
Verified in QA (4154)

**Comment by netnaps** [comment]
Hi, till this gets resolved I just added the "-" with the non-breaking space: **&nbsp;** &nbsp and this worked!
here is a story URL I have published https://netnaps.com/stories/8-activities-kids-at-home/ 

if anyone else could use the same trick for the meantime.

**Comment by o-fernandez** [comment]
Validated the fix, to be released in the next plugin update.
