### ISSUE TITLE
Compatibility with the Hebrew language

### ISSUE THREAD

**Issue by mlifshitz** [GoogleForCreators/web-stories-wp#3456]
Hello,
The plugin is great.
But he has a problem with the compatibility of languages ​​written from right to left (eg Hebrew).
If you can fix it would be great.
Thanks.

**Comment by swissspidy** [comment]
Thanks for your report!

Could you provide some details on what issues you are experiencing specifically?

We know that dragging elements is currently not easily possible in RTL languages.

**Comment by mlifshitz** [comment]
When I increase / decrease this element it escapes to the other side.
The main problem is in the transition between stories, the arrow pointing for the transition between the stories is in the opposite side.

**Comment by swissspidy** [comment]
> The main problem is in the transition between stories, the arrow pointing for the transition between the stories is in the opposite side.

Is this in the editor, or on the frontend? Could you perhaps share a screenshot to clarify? Thank you!

**Comment by LuckynaSan** [comment]
Hello @mlifshitz, have you had a chance to gather the details above?

**Comment by LuckynaSan** [comment]
As we have not received a response on this issue, we will close it out. Please feel free to post a topic on the [Web Stories Support Forum](https://wordpress.org/support/plugin/web-stories/) if you continue to encounter any issues. Thanks!
