### ISSUE TITLE
Update the beta

### ISSUE THREAD

**Issue by injainja** [GoogleForCreators/web-stories-wp#3467]
## Request

please update the beta with a more recent version so that us mortals may test the new features (like animations) and give precious feedbacks 🤗

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Hi there

Please note that we haven‘t implemented animations yet.

Once we have a set of changes we think warrant a new beta release, we‘ll definitely publish one.

**Comment by altlanes** [comment]
When copying and pasting this takes place but easy to delete "StartFragment the future of wordprss content display EndFragment"

Awesome so far tho.

**Comment by swissspidy** [comment]
@altlanes Would you mind opening a new issue about this? Please include some screenshots and details about your system (Browser, WordPress version, etc.)

**Comment by injainja** [comment]
> Hi there
> 
> Please note that we haven‘t implemented animations yet.
> 
> Once we have a set of changes we think warrant a new beta release, we‘ll definitely publish one.

Ah, I see - I thought animations were already there because of the issues posted here. Misinterpreted that  🙏
Than you 👍
