### ISSUE TITLE
Error 500 after clicking Create Story

### ISSUE THREAD

**Issue by wolfmaster8** [GoogleForCreators/web-stories-wp#3481]
## Bug Description

After clicking Create Story button, the page throws an 500 error. Then I refresh the page and the creation page is shown. See video below.

## Expected Behaviour

After clicking Create Story the creation page is shown.

## Steps to Reproduce

1. Click on Create Story.

## Screenshots

[YouTube video](https://youtu.be/pQ2kj_rU8fw)

## Additional Context
- WP version: 5.4.2
- Plugin Version: 1.0.0-beta.1
- Operating System: macOs
- Browser: Edge 2020

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by ernee** [comment]
@wolfmaster8 thanks for the report and video! 

Did you receive an email from WordPress regarding the error? 

If so, could you send us any details provided about the error (it's usually toward the end of the email under _Error Details_)?

**Comment by ernee** [comment]
@wolfmaster8 I'm following up on your reported issue. 

1) Did you receive any additional error messages via email?
2) Could you check if the REST API is showing as working properly under _Tools > Site Health > Status_  from the WordPress Dashboard?

**Comment by wolfmaster8** [comment]
Hello @ernee, sorry for the late response.

1. I haven't received any email regarding this error.
2. REST API is working on the site.

This error might be a memory/compatibility issue with other plugins.

After debugging the 500 error, it was showing memory exhausted error with Divi and Shield plugin.

However, today I could only reproduce this error once.

I'll update everything on my test site and see if I'm getting this error again.

**Comment by wolfmaster8** [comment]
After updating everything and installing the latest version 1.0.0-beta.2, I'm not longer receiving this error.

**Comment by ernee** [comment]
@wolfmaster8 really appreciate your follow up and the insights. Glad to hear it is working now with the recent Beta!
