### ISSUE TITLE
Dashboard Settings: Google Analytics 

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#3482]
## Feature Description
The overarching work for this can be found here for context: https://github.com/google/web-stories-wp/issues/2747

Set up functionality in dashboard settings to read and update google analytics from wordPress settings API 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
(all of this is behind a feature flag) 

- [x] Ability to read google analytics tracking ID from API and show in UI 
- [x] If user is admin and feature flag is true, able to see settings page and update analytics ID
- [x] If user is not admin or feature flag is false, unable to see settings page or update analytics ID
- [x] Connect error handling to toaster
- [x] Unit Tests
- [x] Karma Tests

## Implementation Brief
- UI is already drafted behind feature flag, just need to add in functionality and state changes for permissions

**Comment by swissspidy** [comment]
[Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=6095%3A1) mentions adding a note to the analytics field if Site Kit is active, but it has no UI yet. Perhaps we should create a follow-up issue and assign it to Sam to track this?

**Comment by BrittanyIRL** [comment]
If that is easier to do, absolutely. I think that this (and the publisher logos sister ticket 3483) are both going to serve as MVPs of the settings page since the more nuanced portions have no UI yet. I left the overarching Settings Page ticket in the UX needed column to essentially act as a safe guard to capture the outstanding work beyond MVP? I don't want to bog Sam down with tickets that are repetitive.  

Thoughts?

**Comment by swissspidy** [comment]
Ah, I see, well then it can be tracked in the overarching Settings Page ticket 👍

**Comment by BrittanyIRL** [comment]
Some clarity on this for testing: 
- When the flag is enabled and you are logged in as an admin, you should be able to navigate to settings from the dashboard and update the google analytics id. This Id update should persist when you return to the page. 
- you need to hit 'enter' to save the update. same as renaming a story.

The feature flag you want to flip to enable this is called `enableSettingsView`

**Comment by swissspidy** [comment]
@BrittanyIRL Curious, are we now doing QA for feature-flagged features too? I thought we do the QA part once the flag is removed. Although I like that approach thanks to the new Experiments page, so not sure. Shall we revisit this & make it explicit?

**Comment by BrittanyIRL** [comment]
> @BrittanyIRL Curious, are we now doing QA for feature-flagged features too? I thought we do the QA part once the flag is removed. Although I like that approach thanks to the new Experiments page, so not sure. Shall we revisit this & make it explicit?

@swissspidy - 
Ah that makes sense - just habit to pass it to QA - thanks for calling this out. I think it makes sense to have it go through QA when the feature behind the flag is done as well as when a new flag is introduced to verify that it is showing/hiding properly.  

Happy to revisit or do whatever makes the most sense to the team/pipeline.

**Comment by BrittanyIRL** [comment]
Follow up ticket to address confusion in how to submit updates here: https://github.com/google/web-stories-wp/issues/3843

**Comment by csossi** [comment]
reassigning back - will QA when feature flag removed

**Comment by BrittanyIRL** [comment]
Moving this to done. Feature work is complete and there's a separate ticket to enable feature flag after QA and UAT:  https://github.com/google/web-stories-wp/issues/4132
