### ISSUE TITLE
Update Editor so Animations can be previewed within Editor UI

### ISSUE THREAD

**Issue by mariano-formidable** [GoogleForCreators/web-stories-wp#3484]
We want the ability to preview existing animations, one page at a time, within the Editor UI by simply clicking a "play" button.

During Animation Playback the following should be true:
- The selection outline for any active element should be temporarily hidden (it should re-appear when the animation is complete or stopped and reset).
- Clicking within the active story page in an attempt to select a different element should just be ignored (meaning a the new element is not selected and the animation will continue playback).
- Clicking on any of the panel UI (trying to change text color, click on a different layer, add a new image/text element, etc...) should immediately stop and reset the animation (this might change in the future, but for now, I think for the first iteration of this feature, if you're clicking around while the animation is playing then it just stops playing).

### Feature Flags

The play/stop button and the ability to playback animations should be hidden behind the `enableAnimation` feature flag.

### Screenshots

Play buttons begins animation playback:
![image.png](https://images.zenhubusercontent.com/5b35729a5b51b10bd4dd5fd1/7fbc0a31-0aa0-4beb-9db8-f41918ba02f1)

Play button becomes a stop button during playback.  When the stop button is clicked, the animation is stopped and _reset_ (not just paused).
![image.png](https://images.zenhubusercontent.com/5b35729a5b51b10bd4dd5fd1/944337a4-65dd-47da-9b18-bede5c3fdee6)

Story Page _before_ animation is played:
<img src="https://images.zenhubusercontent.com/5b35729a5b51b10bd4dd5fd1/9fafbdc1-7768-424b-a7e3-3229dad0a606" height="300">

Story page _during_ animation playback (notice that the element selection outline disappears, but it is expected to reappear once playback is complete):
<img src="https://images.zenhubusercontent.com/5b35729a5b51b10bd4dd5fd1/cc297698-1fc4-4cff-a4df-977cdfd3b8f2" height="300">

### Helpful Sources
- [Animation UI Figma Design Docs](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=11038%3A0)
- [Animation product specs](https://docs.google.com/document/d/11xtdVNrSa16qg9tmg_ACw6vTD8z8wymhkRSgOqkVCa8/edit#heading=h.m0pv6unnoqe)

**Comment by maxyinger** [comment]
**QA Check:**
Had to make small changes to the buttons in the dock right beneath the page view in the editor so I could fit the play button in here. I believe these have since been updated again with the latest design pass. The test is just to make sure there's no regressions here with sizing/spacing of these buttons.

![Screen Shot 2020-08-10 at 12.11.19 PM.png](https://images.zenhubusercontent.com/5ea0a3e2f739259b2b0b092a/fbd3b939-4c83-4827-bf65-3bb52ef4e32a)

**Comment by maxyinger** [comment]
reverted page menu button styles to what's on main since this ticket doesn't have any design aspects to it. nice cus we can now bypass QA
