### ISSUE TITLE
Add author attribution for Unsplash when a media element is focused or hovered

### ISSUE THREAD

**Issue by diegovar** [GoogleForCreators/web-stories-wp#3500]
As per Unsplash requirements. See PRD.

**Comment by csossi** [comment]
Looks like this was already merged, so checked in Main Branch

Uploaded a few Unsplash image. Not seeing author on hover.
https://drive.google.com/file/d/1_6kPGENevgZLDlnZA1tki0OxWEMVR04Y/view

The 4 images in the video were selected from Unsplash tab

**Comment by swissspidy** [comment]
Heya, I a don't think that's what's need to be tested here. Actually, I don't think this is for QA at all as the whole Unsplash integration is behind a feature flag.

@winterDroid Please confirm that Unsplash integration is still behind a feature flag. As a reminder, Feature-flagged items are not going through QA until the flag is enabled.

**Comment by winterDroid** [comment]
@swissspidy yes it is still behind a feature flag. This feature is very implicitly behind one as otherwise no attributions will be present. That's why I moved it to QA to ensure that no existing media element logic is broken.

**Comment by swissspidy** [comment]
Testing instructions would have been very helpful in that case
