### ISSUE TITLE
Avoid "Auto Draft" titles and permalinks

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#3508]
## Bug Description

The "Auto Draft" placeholder should be removed when saving stories, otherwise we get "Auto Draft" titles and "auto-draft" permalinks.

## Expected Behaviour

1. Go to `wp-admin/post-new.php?post_type=web-story` to create a new story
1. Publish the story without making any changes
1. The story's title should be **empty** and the slug is just the story's ID

## Steps to Reproduce

1. Go to `wp-admin/post-new.php?post_type=web-story` to create a new story
1. Publish the story without making any changes
1. See that the story's title is "Auto Draft" and the slug is "auto-draft"

## Additional Context

- Plugin Version: `master`
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
FYI @o-fernandez

**Comment by bmattb** [comment]
@o-fernandez  - mirror what WP does with posts without titles.

**Comment by bmattb** [comment]
We expect that the pre-publish checklist will also help prevent this from happening.

**Comment by csossi** [comment]
Verified in QA
