### ISSUE TITLE
Frame moves a bit when you enter text edit mode

### ISSUE THREAD

**Issue by merapi** [GoogleForCreators/web-stories-wp#3520]
## Bug Description

The frame moves when you enter text edit mode, happens on Chrome on full-size and scaled canvas, Firefox on scaled canvas, not in Safari?

## Expected Behaviour

The frame should stay in place when entering the edit mode.

## Steps to Reproduce

Add text, enter edit mode (on Chrome at any canvas size).

## Screenshots

https://drive.google.com/file/d/1xCzbQRmn6ezbMHCU9QSpGoCqAdiBwlgN/view?usp=sharing

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Initial investigation

`layout.js`
```js
    '.         .         .         .         .       ' minmax(16px, 1fr)
```
If you remove `1fr` and replace it with e.g. `20px` the issue will go away. That might lead to a theory that property like `readonly attribute long offsetTop;` is used somewhere (in Moveable?) and it loses the precision since it's an integer.

Also, full-bleed height rounding kinda fixes the issue, the bottom line is little blurry on Firefox and there can be other consequences of that change but it points to the similar root cause:
```js
'--fullbleed-height-px': `${Math.round(pageSize.width / FULLBLEED_RATIO)}px`,
```

**Comment by swissspidy** [comment]
Does this still happen?
