### ISSUE TITLE
Workspace: Add Keyboard Shortcuts for Save and Select All Elements

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#3527]
## Feature Description

Add Meta + S and Meta + A keyboard shortcuts for Save and Select All Elements in the Workspace Editor

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

Command + S (Mac) / Control + S (Windows) should save the story
Command + A (Mac) / Control + A (Windows) should select all elements

**Comment by csossi** [comment]
Verified in QA - Tested in PR#3393

**Comment by samitron7** [comment]
Confirmed in UAT
