### ISSUE TITLE
Cropping Leading & Trailing whitespace

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#3530]
As discussed in our meeting where @merapi  reviewed current text issues

details in this doc - https://docs.google.com/document/d/1wchYL4ZClv6b7kSadOR0mQuOZmFAHu9F3klKiFRkGYs/edit#

**Comment by barklund** [comment]
@merapi, is this not fixed by solution to #1952?

**Comment by merapi** [comment]
@barklund this one is about the line-height whitespace (not really a bug, just a new req) ![Screenshot_20200813-110536_Slides.jpg](https://user-images.githubusercontent.com/21036224/90115925-11dee380-dd55-11ea-8460-18c6aaff7223.jpg)

**Comment by barklund** [comment]
@merapi, ah this is what we need the font metrics for, right? I'll set it as blocker.

**Comment by merapi** [comment]
Yep, this is one of the things that will utilize font metrics.

**Comment by o-fernandez** [comment]
Looks good, couldn't break it!
