### ISSUE TITLE
Padding should increase the line height in highlight mode

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#3531]
This is happening now, but it is not correctly implemented.

more details in this doc:
https://docs.google.com/document/d/1wchYL4ZClv6b7kSadOR0mQuOZmFAHu9F3klKiFRkGYs/edit#

**Comment by bmattb** [comment]
@o-fernandez  to put a priority label.

**Comment by barklund** [comment]
@o-fernandez, should we perhaps do this ticket next sprint too, when we have @merapi around for it - even though it's slated for 1.2?

**Comment by o-fernandez** [comment]
Yup, it is fine to put this into a milestone that's ahead of the slated release, particularly for bugs/fixes. So, delivering the fix earlier = fine. If it will be later/beyond the tagged release then we should discuss/review prioritization.

**Comment by csossi** [comment]
Verified in QA
