### ISSUE TITLE
Edit Media Metadata via Media Library Hover Menu

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#354]
As an author I want to be able to edit media metadata

NOTEs: 
See #26 for hover state to open edit metadata option 
See #405 for metadata in the document panel
See #1319 for delete via dropdown

**[Design](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=4898%3A341)**

**Acceptance Criteria**
1. After clicking edit in the dropdown menu, a dialog is opened where the editor can edit the media metadata.
2. While in the dialog the author is able to edit the Title. AKA `title`
3. While in the dialog the author is able to edit the Content Description. AKA `alt`

**Feature Brief?**

**Comment by jauyong** [comment]
1. Is Alt text the only metadata available for images? What about caption and description? 
2. What metadata is available for videos? WP has: caption and description?
3. What about global alt text vs. post/story specific alt text?

**Comment by pbakaus** [comment]
> 1. Is Alt text the only metadata available for images? What about caption and description?

We don't think caption and description would ever be used in the editor, so can be skipped for now.

> 2. What metadata is available for videos? WP has: caption and description?

Probably..none? @cramforce had some thoughts on this a while back. I swear I remember some alt-like thingy on `<amp-video>` but maybe I've been dreaming it up?

> 3. What about global alt text vs. post/story specific alt text?

Let's make them global for now, I'd say, until somebody complains. /cc @samitron7

**Comment by spacedmonkey** [comment]
I will upload these screenshots again here for reference. Settings screen from video widget. 

![image](https://user-images.githubusercontent.com/237508/75773779-775e8b00-5d46-11ea-988e-125c24e5dd3b.png)

![image](https://user-images.githubusercontent.com/237508/75773752-6ada3280-5d46-11ea-82d1-be530a02e55e.png)

**Comment by cramforce** [comment]
AMP Stories support a `title` and `alt` attribute on `amp-video` elements. We should strongly encourage providing these. It might make sense to actually support both. Maybe label one as description and one as "Text appearing in the video".

Captions are also supported, and it would be great to see support for them in the editor. Given that there are also styling and positioning considerations for them beyond the simple act of providing them, adding caption support should probably be tracked separately. Eventually it would be amazing to see auto-captioning support from a text transcript ala youtube (this is different from auto-captions which youtube also has and which also would be amazing).

**Comment by cramforce** [comment]
AMP Stories support a `title` and `alt` attribute on `amp-video` elements. We should strongly encourage providing these. It might make sense to actually support both. Maybe label one as description and one as "Text appearing in the video".

Captions are also supported, and it would be great to see support for them in the editor. Given that there are also styling and positioning considerations for them beyond the simple act of providing them, adding caption support should probably be tracked separately. Eventually it would be amazing to see auto-captioning support from a text transcript ala youtube (this is different from auto-captions which youtube also has and which also would be amazing).

**Comment by pbakaus** [comment]
Thanks Malte!

@spacedmonkey @jauyong let's make `title` and `alt` P0, and call them "Title" and "Content description" respectively.

Let's also add a ticket to support Captions/subtitles, and make it a P1.

**Comment by jauyong** [comment]
Created #449 and added to the feature map sheet.

**Comment by spacedmonkey** [comment]
@cramforce I dont see `alt` and `title` in this [docs page](https://amp.dev/documentation/components/amp-video/?format=websites). 

Track is supported, which is great. And there seems to be support for ogv / webm alt versions as well.

**Comment by jauyong** [comment]
@samitron7 to add title and alt to the design

**Comment by swissspidy** [comment]
Seems like we can close this one? `alt` (video + image) and `title` (video only) can be edited in the sidebar.

**Comment by joannag6** [comment]
Media Library Hover Menu being implemented on as part of #1319

**Comment by swissspidy** [comment]
@joannag6 Seems like this one can be closed? What's missing here?

**Comment by joannag6** [comment]
Will move to Ready for QA.

**Comment by swissspidy** [comment]
PR to test: #2660

**Comment by csossi** [comment]
Verified in QA

**Comment by samitron7** [comment]
Verified in UAT
