### ISSUE TITLE
Site Kit Analytics tag missing

### ISSUE THREAD

**Issue by quadcom** [GoogleForCreators/web-stories-wp#3546]
## Feature Description

I installed a fresh WP install and added Web Stories and Google Sitekit to provide tracking in Analytics

The Stories plugin seems to strip any scripts added by Sitekit which means I cannot track any interaction with pages generated.

Please provide support for Analytics tracking in entirety, not just Sitekit or Google Analytics alone.

## Alternatives Considered

I have not found any alternatives or solutions

## Additional Context

Nothing to add as nothing is generated like an error message.
---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by LuckynaSan** [comment]
@quadcom Thank you for submitting this issue and hopefully, we can assist. Can you please share the URL to your story?

**Comment by quadcom** [comment]
https://torontoheadshot.com/m/stories/headshots-toronto/

https://torontoheadshot.com/m/stories/linkedin-headshots/

I use the Google Tag Assistant and nothing gets fired.

**Comment by swissspidy** [comment]
Is the Analytics module in Site Kit properly configured & active? Or are you inserting the Analytics snippet on your site using another way? The Site Kit settings will tell you that.

Also, could you perhaps clarify what you mean with "support for Analytics tracking in entirety"?

**Comment by quadcom** [comment]
So the analytics portion is not adding the code but the tag manager section
is.

I have the same config on the parent site (https://torontoheadshot.com) and
it works fine.

**Comment by LuckynaSan** [comment]
> https://torontoheadshot.com/m/stories/headshots-toronto/
>https://torontoheadshot.com/m/stories/linkedin-headshots/
>I use the Google Tag Assistant and nothing gets fired.

Regarding the URL structure of the story URL, it looks like it's serving from a directory "m" based on the URL: https://torontoheadshot.com/m/stories/headshots-toronto/

- Is Site Kit installed on the main website: https://torontoheadshot.com/ 
- Can you confirm the [WordPress settings](https://i.imgur.com/MkFLF0E.png)

**Comment by quadcom** [comment]
SO because my theme on the main site does not play well with Web Stories (Oxygen Theme Builder). I installed a fresh WP install in /m/ and then installed Web Stories in that. Both WP installs have Google Sitekit installed and I have confirmed that it is injecting TagManager code into the page.

![image](https://user-images.githubusercontent.com/7085931/89467920-7b069b80-d744-11ea-8a70-5a735b061e1f.png)

I have a script redirect from the '/m/' page to my main site as I only use this subsite for stories.

**Comment by swissspidy** [comment]
FWIW, it‘s called Web Stories. Not Google Stories.

**Comment by LuckynaSan** [comment]
> SO because my theme on the main site does not play well with Web Stories (Oxygen Theme Builder). I installed a fresh WP install in /m/ and then installed Web Stories in that. 

@quadcom I want to mention that there is a fix out #3714 to improve Oxygen compatibility and perhaps a subsite for stories will not be needed. I will provide you with any updates as I find out more.

**Comment by LuckynaSan** [comment]
@quadcom Could you attempt to uninstall the plugin on your site and upload this ZIP file to install a newer in-development version: [web-stories.zip](https://github.com/google/web-stories-wp/files/5059162/web-stories.zip)

This should help improve the compatibility.

**Comment by quadcom** [comment]
> @quadcom Could you attempt to uninstall the plugin on your site and upload this ZIP file to install a newer in-development version: [web-stories.zip](https://github.com/google/web-stories-wp/files/5059162/web-stories.zip)
> 
> This should help improve the compatibility.

Is this for compatibility with Oxygen or Google tracking? Should I put this in the sub-folder WP install or in the main Oxygen site?

**Comment by LuckynaSan** [comment]
>Is this for compatibility with Oxygen or Google tracking? Should I put this in the sub-folder WP install or in the main Oxygen site?

The compatibility improvement was with Oxygen Page Builder and if that is on your main site then you can install it there. Could you let us know if you are still facing issues with the Web Stories plugin?

**Comment by quadcom** [comment]
So, since all the earlier stuff I've re-homes my mobile approach to m.torontoheadshot.com

Again, clean WP install Divi as the theme.  Site Kit is installed and tags are inserted using Tag Manager.

On the Web Stories pages, none of the Tag Manager scripts are present according to the GTag Assistant.

![image](https://user-images.githubusercontent.com/7085931/93154662-2e629880-f6d2-11ea-8b19-06ada867aa73.png)

I also tried adding a header/footer plugin and adding the Tag Manager scripts manually in the event this is a Site Kit issue. Still no tags present on Web Stories pages.

**Comment by swissspidy** [comment]
Hi there,

Site Kit currently only supports analytics for Web Stories through the **Analytics** module, not the **Tag Manager** module. However, support for it is in the works already, so you can expect this to function soon. Please follow https://github.com/google/site-kit-wp/issues/2070 for any updates on this.

Since it's handled by Site Kit, I am closing this issue.

Thanks a lot for your report and your patience while we were sorting things out! Please do not hesitate to open new ticket if you have any more questions about Web Stories for WordPress.

----

> I also tried adding a header/footer plugin and adding the Tag Manager scripts manually in the event this is a Site Kit issue. Still no tags present on Web Stories pages.

FWIW, these plugins don't work out of the box with Web Stories because they don't have the same header / footer areas.
