### ISSUE TITLE
Update button not disabled despite no changes

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#3548]
## Bug Description

In `assets/src/edit-story/components/header/buttons.js` there is some logic to disable the "Update" button if there are no new changes.

However, that does not seem to be working. The Update button is always visible & enabled, allowing me to update the story despite there being no new changes.

If there are no changes, the button should be disabled.

## Expected Behaviour

1. Publish story
1. Don't make any changes
1. The Update button is disabled

## Steps to Reproduce

1. Publish story
1. The Update button is not disabled
1. Click on Update
1. The Update button is still not disabled

## Screenshots

<img width="320" alt="Screenshot 2020-07-30 at 10 29 30" src="https://user-images.githubusercontent.com/841956/88900583-df5ec200-d24f-11ea-8f95-ec1a0d188d6b.png">

https://github.com/google/web-stories-wp/blob/9f6927743e52c9dd37254e1b7c504a6144f13116/assets/src/edit-story/components/header/buttons.js#L248-L271

## Additional Context

- Plugin Version: `master`
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by amovar18** [comment]
@swissspidy might have found the issue
https://github.com/google/web-stories-wp/blob/3824d2cee3e231ae0795d3b08f6eb15417f49399/packages/story-editor/src/components/header/buttons/update.js#L146-L153
If we change the `disabled` prop to `disabled={!isEnabled}` then we can disable the `Update Button`

**Comment by amovar18** [comment]
@swissspidy might have found the issue
https://github.com/google/web-stories-wp/blob/dff6f6d4c805444709c365d27e39ab2952264bcd/packages/story-editor/src/components/header/buttons/update.js#L146-152
If we change the `disabled` prop to `disabled={!isEnabled}` then we can disable the `Update Button`

**Comment by swissspidy** [comment]
Totally forgot this issue exists.

Yup, that's exactly what we need. Mind opening a PR? A small test in `packages/story-editor/src/components/header/buttons/test/update.js ` would be nice too.
