### ISSUE TITLE
Add Keyboard Shortcuts to Developed Sections

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#355]
This ticket is to go back to all sections that have already been developed and add keyboard shortcuts to them. 
Any new sections being developed will include developing keyboard shortcut functionality.

**Instructions**
1. Validate whether a shortcut [as defined in this list](https://docs.google.com/spreadsheets/d/17pZLd0faYZc9Xt7mG1KYtaZ0Krn5ppThIisz3TOsv8w/edit#gid=0) is implemented correctly, if so, mark it as implemented in column A
2. For any keyboard shortcut not yet implemented, implement. Add to column A "implemented in #355" to refer to this ticket. 
3. Once merged, UAT can update the spreadsheet to reflect that it's on the latest version.

**Acceptance Criteria** 
1. Media Gallery - This section is partially done, but I don't see any shortcuts in the [brief](https://docs.google.com/document/d/1aZH_TI_be2t5Ywyqx4jcPTPdhFGEt7xh-uLzBp2AV4A/edit#heading=h.2d83f6r6hu5x)
2. Design Panel - This section is partially done, not sure which shortcuts exist.
3. Document Panel - This section is partially done, not sure which shortcuts exist.
4. Workspace - This section is partially done, not sure which shortcuts exist. (undo, redo) (Delete is done in #63)

**Comment by o-fernandez** [comment]
I think the latest keyboard shortcuts list is this one: [Story Editor Product Spec: Keyboard Shortcuts](https://docs.google.com/spreadsheets/d/17pZLd0faYZc9Xt7mG1KYtaZ0Krn5ppThIisz3TOsv8w/edit#gid=0)

These all fall under Workspace, so moving to that epic/team.

**Comment by bmattb** [comment]
moving to the Pea-Pod! :)

**Comment by bmattb** [comment]
direction given was for @carlos-kelly to break this ticket into additional tickets, with the unactionable features to be added as backlog items.
