### ISSUE TITLE
Discovery: Global Tab Order

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#356]

**Comment by samitron7** [comment]
@jauyong @barklund can you guys be specific to what the ask is here? Is this if keyboard tabbing through the editor? if so then @dvoytenko Do we have a pattern establish for this already? I like to sync with you to go over whatever pattern we have to that I can bring to accessibility office hours.

**Comment by dvoytenko** [comment]
@samitron7 main principals are outlined here: https://docs.google.com/document/d/1jR6c0eGNfoUXJg04v_isMfPnvRc2SD8zfevCIPqAjF4/edit#heading=h.5wi7gpgou1

The tab navigation in the editor is currently functional, but not entirely ideal or clean.

**Comment by jauyong** [comment]
Discovery was completed. We will create new tickets for actionable items as they come up.
