### ISSUE TITLE
Structured Data issue due to poster image size

### ISSUE THREAD

**Issue by ivo-aml** [GoogleForCreators/web-stories-wp#3560]
## Suggestion Request 
Hi guys I got some issue with the Google stories plugin and I hope you can suggest me via email if I should deactivate the plugin because of this error in my Search console or just to ignore it (_removed_)

## Issue in question

Here is the error message I got from Google search console ( inside search console I got this URL for both errors- https://advancedmarketinglab.com/stories/942/ ): 

![Capture](https://user-images.githubusercontent.com/69001403/88929757-d800de00-d27a-11ea-8062-eda410be6b7b.PNG)

- Plugin Version: 1.0.0. Beta-1
- Operating System: WP
- Browser: Chrome, Firefox

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by LuckynaSan** [comment]
Thanks for sharing those details and for reporting this issue. This [image](https://advancedmarketinglab.com/wp-content/uploads/2020/07/Picture9-300x144.png) size is 300 x 144 pixels. Note the following recommended minimum requirements for Web Stories:

            Each poster image should meet the recommended minimum size:
            Portrait: 640px x 853px
            Landscape: 853px x 640px
            Square: 640px x 640px
I noticed a [CDN URL](https://jmp.sh/RwJZSBS) for [JetPack Site Accelerator](https://jetpack.com/support/site-accelerator/) in your source code for [this image](http://i0.wp.com/advancedmarketinglab.com/wp-content/uploads/2020/07/Picture9-300x144.png), which has an image size of 2167 × 1043 pixels. This could indicate the image size was altered, however, we need to check a few more details.

- Did you upload a [Cover image](https://jmp.sh/XEnOhz8) to the editor for the story?
- Can you check what the image size is from your [media library](https://jmp.sh/XmyRkuS)?

**Comment by LuckynaSan** [comment]
@ivo-aml Just want to note that the issue you described is similar to [this open issue](https://github.com/google/web-stories-wp/issues/3434) where a bug in the plugin causes that 300x144 image, which is too small and causes that Search Console error.

**Comment by swissspidy** [comment]
The second issue - "Error in required structured data element" - seems to indicate that you're story might not have a title. You should enter a title before publishing a story.

The title is used for the `headline` structured data field, and that is currently empty and causes this error:

<img width="764" alt="Screenshot 2020-07-31 at 15 43 04" src="https://user-images.githubusercontent.com/841956/89040917-cb48bc80-d344-11ea-9189-25251b6ce729.png">

**Comment by ivo-aml** [comment]
Hey thanks for the reply man. I actually have the cover image which is
2167/1043. So you saying whenever I do a story I have to use images with
the sizes that you mention in the email?

**Comment by ivo-aml** [comment]
Hey Pascal, thanks man. I did include the title.
Thanks again.
Regards

**Comment by LuckynaSan** [comment]
@ivo-aml 
> Hey thanks for the reply man. I actually have the cover image which is
2167/1043. So you saying whenever I do a story I have to use images with
the sizes that you mention in the email?

Your cover image size meets [structured data recommendations](https://developers.google.com/search/docs/data-types/article#article_types) which states it should be at least 1200px wide. The recommendation is to use at least 828 x 1792 sized fullscreen/ background images as mentioned in this [best practices documentation](https://amp.dev/documentation/guides-and-tutorials/start/create_successful_stories/?format=stories#images).

**Comment by LuckynaSan** [comment]
Hi there! I notice the [AMP test result](https://search.google.com/test/amp?id=z-7EAgVqezzA-RxVXl-y3g) is okay, but [if you preview it](https://jmp.sh/JQQs64j) you can see the poster image isn't ideal. We've made a few recent changes that might solve the issue surrounding small poster portrait images. Could you perhaps try removing the plugin and installing this in-development version? Download: [web-stories.zip](https://github.com/google/web-stories-wp/files/5078028/web-stories.zip)

**Comment by ivo-aml** [comment]
Hey yes, I'll do that. Thanks man.

**Comment by ivo-aml** [comment]
Hey guys, here is what I got after uploaded the new version.
1 - I had my first story still there but from thew editor if I click on
"Preview" I got this error:
*Warning*: DOMDocument::loadHTML() expects parameter 2 to be integer,
string given in
*/home2/aml/public_html/wp-content/plugins/web-stories/includes/Story_Renderer.php*
on line *97*

2 - Also if I paste the link in new private window takes me to the same
error page.
Please, let me know :)

**Comment by ivo-aml** [comment]
Hi guys, another thing. check this quick screen recording. You can see how
every time I click the new slide the page is jumping up:
https://ttprivatenew.s3.amazonaws.com/pulse/advancedmarketinghub-gmail/attachments/14392398/TinyTake15-08-2020-12-37-53.mp4

**Comment by swissspidy** [comment]
> *Warning*: `DOMDocument::loadHTML()` expects parameter 2 to be integer,
string given in */home2/aml/public_html/wp-content/plugins/web-stories/includes/Story_Renderer.php*
on line *97*

Which version of PHP are you using? Also, more specifically, which version of libxml are you using? You can check that by using `phpinfo()` or by doing something like `php -i | grep libxml` in the command line.

> Hi guys, another thing. check this quick screen recording. You can see how
every time I click the new slide the page is jumping up:

Which browser and which browser version are you using?

**Comment by ivo-aml** [comment]
I see the PHP is 7.1.24. Should I upgrade it? About the browser I am using
right now Firefox but with the previous plugin version was doing the same
and this time I was on Opera I think.

**Comment by swissspidy** [comment]
> I see the PHP is 7.1.24. Should I upgrade it?

No, it's fine. The `DOMDocument::loadHTML()` warnings should be fixed with the next release. Although the latest PHP version is 7.4, so it's about time for an upgrade anyway :-)

**Comment by ivo-aml** [comment]
Cool, I will upgrade the PHP in mean time.

**Comment by LuckynaSan** [comment]
Hello @ivo-aml!  Have you updated the PHP version and tried the latest Beta 2 available for download on the [website](https://google.github.io/web-stories-wp/beta/)? Please let us know if your issue persists.

**Comment by ivo-aml** [comment]
Hey,
sorry for my late reply man. Yes I updated the PHP and activated the
version that you gave me in one of the previous emails. Honestly, I haven't
try it yet because I was quite busy these days. But thanks for contacting
me, one of next days I will give you feedback.
Regards

**Comment by swissspidy** [comment]
Note that 1.0.0-rc.1 has been released in the meantime. Make sure to update accordingly.

**Comment by LuckynaSan** [comment]
@ivo-aml We will close this issue out as we have yet to receive a response. Feel free to open a new topic on the [Web Stories Support Forum](https://wordpress.org/support/plugin/web-stories/) if the issue persists. Thank you!

**Comment by ivo-aml** [comment]
Hi, cool, no problem. Sorry for the late replies man, but I had a deadline
to finish revamping a site ( wanderlust-magazine.com) where we are planning
to use the Web stories plugin as well. Yes, if I got issues I will
definitely send you an email.
Thanks again.
Best regards
Ivo
