### ISSUE TITLE
Update Preview and AMP Story generated animation code to support effects like "Fly In"

### ISSUE THREAD

**Issue by mariano-formidable** [GoogleForCreators/web-stories-wp#3562]
In order for animation effects like "Fly In" to be supported by our Dashboard preview animations and in a generated AMP Story, we have to make sure that the page's `elements` are being passed into the appropriate animation providers.

Also, be sure to update the `StoryAnimation.Provider` in the editor to also have `elements` passed in.  So _three_ `StoryAnimation.Provider` implementations should be updated with this ticket.

## To Test

Once things are configured, you can test it by created a demo story and applying the "Fly In" animation effect to an element in the story.  Then see if the effect plays properly in the Dashboard when you hover over the story's preview card, and also check that the animation plays properly when you view its generated AMP Story.

**Comment by maxyinger** [comment]
Isn't this in review with this PR? 
https://github.com/google/web-stories-wp/pull/3545/files

I've been referencing other tickets being blocked by #3421 but I think this might be a more descriptive ticket to reference. going to update now

**Comment by mariano-formidable** [comment]
> Isn't this in review with this PR?
> https://github.com/google/web-stories-wp/pull/3545/files

Oh no, this ticket refers to the fact that the `StoryAnimation.Provider` we use to display the Preview card animations and the generated AMP story animations, does _not_ have `elements` being passed in to it.  I'm only passing in `elements` in the storybook examples but not our actual code.
