### ISSUE TITLE
Error 500 when creating new story

### ISSUE THREAD

**Issue by Jazzman200** [GoogleForCreators/web-stories-wp#3575]
Im unable to start a new web story after the plugin has been installed. 

When i click add new story i get the following error message. 

![image](https://user-images.githubusercontent.com/69023201/88991118-e1438680-d31e-11ea-9e7d-b0aed1e45161.png)

Any ideas on what i need to do to fix this issue?

Thanks

**Comment by LuckynaSan** [comment]
@Jazzman200 We will be happy to troubleshoot this issue with you. Could you please share the following details:
- [Site Health information](https://i.imgur.com/Rtkmsba.png)
- hosting provider and plan 

Thanks!

**Comment by LuckynaSan** [comment]
@Jazzman200 Just a courtesy follow-up about the issue you experienced. Are you able to share any further details?

**Comment by LuckynaSan** [comment]
@Jazzman200 We will close this issue out as we have yet to receive a response. Feel free to post a topic on the [Web Stories Support Forum](https://wordpress.org/support/plugin/web-stories/) if the issue persists. Thank you!
