### ISSUE TITLE
Can't update permalink to include dashes

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#3582]
## Bug Description

User Reported Bug: if you forget to set the title of the story (you should be warned when saving the first time), the permalink can't be updated to include dashes in the link name. 

I (@o-fernandez ) have noticed this in the past. I think that if I paste in a permalink with dashes in it it'd be ok, but in the permalink input box for some reason I couldn't type them in. We should review and make sure this is fixed, if it hasn't been fixed already. 

## Expected Behaviour

User should be able to update the permalink and use dashes. 

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
So this is #3455?

**Comment by o-fernandez** [comment]
Closing in favor of #3455
