### ISSUE TITLE
WPTuts Review Video

### ISSUE THREAD

**Issue by ocbroadband** [GoogleForCreators/web-stories-wp#3585]
## Request

Review Video

## Additional Context

N/A

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

Review video created by a fairly good WP group on the plugin.   Enjoy!

https://www.youtube.com/watch?v=Sn0OAnLiIGI

**Comment by ernee** [comment]
@ocbroadband awesome! Thanks for sharing!

**Comment by swissspidy** [comment]
Thanks, we'll share it with the team.
