### ISSUE TITLE
Display List of Keyboard Shortcuts

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#359]
## Feature Description

We need to display a list of functional shortcuts. It should probably itself have a global shortcut to be opened (which will be displayed in this list).

@samitron7 to define UX.

@pbakaus to prioritize.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by pbakaus** [comment]
This would be great to get in if time allows, but worst case we can produce the list on the website for now. So P1 seems right.

**Comment by samitron7** [comment]
[Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Stable-Release?node-id=361%3A0)

Note there is no FTUE for this iteration. FTUE will possibly come post stable.

**Comment by bmattb** [comment]
@samitron7 to link the Product brief on this

**Comment by samitron7** [comment]
Spreadsheet to kb shortcut [here](https://docs.google.com/spreadsheets/d/1VNv8O5SnlqZfgYXo5ua2mCc-MWTN9ow6OtYWxml5Ka0/edit#gid=0)

**Comment by o-fernandez** [comment]
![image](https://user-images.githubusercontent.com/13389997/92767938-98dba780-f365-11ea-8904-f69edb5b6992.png)

Shortcut needs to be udpated. should just be CMD+Option+1 or 2 or 3. No Shift

**Comment by o-fernandez** [comment]
It's fixed! let's meerge :D
