### ISSUE TITLE
Story Board Page Top 1/4 not displayed.

### ISSUE THREAD

**Issue by SuperNeoGuy** [GoogleForCreators/web-stories-wp#3596]
## Request

While working on each story board page as you move to the next page to edit the story page top 1/4 cuts off.
In the screen shot below the red marks indicate the Wordpress Nav bar which the story board page cuts off and unable to scroll any further up to view all the page. Need to delete content and start again.
Not all pages have this issue. this may be an issue with the shapes content if to enlarge the shape beyond the story board page to produce the effect, but not sure.

## Additional Context
![image](https://user-images.githubusercontent.com/37615890/89086868-8caf1280-d3d5-11ea-948d-f639b7488243.png)

- Plugin Version: 1.0.0-beta.1
- Operating System: Windows
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by ernee** [comment]
@SuperNeoGuy thanks so much for reaching out about this. This sounds similar to a few open issues we have about the Workspace shifting in certain conditions (for example https://github.com/google/web-stories-wp/issues/3248). 

Could you tell us the following:

1) Which device are you using and what size is the screen?
2) Did you start with one of the Templates (which one) or Create New Story?

**Comment by itlabs-eu** [comment]
Hello,

I'm facing the same issue in some pages when using the pre-made templates. I noticed that the problem occurs when one of the elements extends far outside the visible area. In the attached print, the layer "Blob 3" has a large portion outside the visible area, pushing the entire page upwards.

My screen resolution is 1366 x 768, so probably the problem will not manifest itself at higher screen resolutions.

My suggestion would be to add a scroll bar to the central work area.

Thanks
![Captura de tela de 2020-08-05 22-09-29](https://user-images.githubusercontent.com/17102339/89479419-2c1f2d00-d769-11ea-94a7-3f85254fdc50.png)

**Comment by swissspidy** [comment]
Thank you, very useful!

Sounds like a regression of #2304 / #2380 that should get addressed.

**Comment by SuperNeoGuy** [comment]
> @SuperNeoGuy thanks so much for reaching out about this. This sounds similar to a few open issues we have about the Workspace shifting in certain conditions (for example #3248).
> 
> Could you tell us the following:
> 
> 1. Which device are you using and what size is the screen?
> 2. Did you start with one of the Templates (which one) or Create New Story?

Hi,
Sorry for the late reply.
1. My device is Dell laptop XPS 13 9370 & screen res is 1536 x 864.
2. Yes started with a template which was the Sleep template.
thanks

**Comment by ernee** [comment]
@SuperNeoGuy thanks so much for these details! We'll be working on this issue in #3248, so feel free to track progress there. Closing this issue out in favor of that one.
