### ISSUE TITLE
Permalink address Dashes (Work Around)

### ISSUE THREAD

**Issue by SuperNeoGuy** [GoogleForCreators/web-stories-wp#3597]
## Bug Description
Unable to type the title page link in full with dashes. as per screen shots below.
work around!
Need to type the story address title address with no spaces first.
Then go back and add in the dashes.

## Expected Behaviour

![image](https://user-images.githubusercontent.com/37615890/89087342-5b374680-d3d7-11ea-8b0e-9ef5f0ac0b53.png)

![image](https://user-images.githubusercontent.com/37615890/89087621-31caea80-d3d8-11ea-88e9-20999f10fea8.png)

![image](https://user-images.githubusercontent.com/37615890/89087661-4d35f580-d3d8-11ea-9b52-d766d0a0f88c.png)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
Thanks for the report! We have a very similar ticket about this issue #3455, which you can follow to see the latest progress we have made on the issue. 

I will close out this issue as a duplicate, but please add a new comment if you think that issue #3455 doesn't fully address your concern and we can look at this ticket again.
