### ISSUE TITLE
When uploading video poster, also need to update video dimensions

### ISSUE THREAD

**Issue by dvoytenko** [GoogleForCreators/web-stories-wp#360]
When we upload the poster, it's also a great opportunity to update the video's size - we need to know it for use in the editor. An alternative approach would be, when poster is available, to use it's original size as the video's original size.

One important nuance: the size might be available later, once the video is already placed on the page. I think we have no choice but to jump-update it once the original size is available. We'd likely need to show some sort of "loading" indicator when original size is not available at the time of insertion.

Finally, a video with its width/height not available should be displayed as a square in the media panel. Defaulting to 150x80 will be wrong half the time when we don't know the video's orientation. So square is a safe default. Once original width/height are available, we should, of course, use those.

**Comment by spacedmonkey** [comment]
I was going to look into this in #45

**Comment by swissspidy** [comment]
> When we upload the poster, it's also a great opportunity to update the video's size - we need to know it for use in the editor.

Indeed! We need a few things there in the future:

* Video dimensions (on `loadedmetadata`)
* Video duration (on `loadedmetadata`)
* Poster image (on `canplay`)
* File size (on `loadedmetadata`)

**Comment by swissspidy** [comment]
Fixed by #824
