### ISSUE TITLE
JSON Error Message trying to use a TEmplate

### ISSUE THREAD

**Issue by EckCreativeMedia** [GoogleForCreators/web-stories-wp#3604]
## Request

Downloaded and trying to use the Google Stories plugin into my WP website.

-> Got an error message (below) Lower bottom right of the screen when I clicked on "USE TEMPLATE".

**"Unable to Create Story From TemplateThe response is not a valid JSON response."**

I tried with all the templates given, got the same error message.

## Additional Context

- Plugin Version: Version 1.0.0-beta.1
- Operating System: Windows 10
- Browser: Google Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by LuckynaSan** [comment]
@EckCreativeMedia Thank you for reporting this. 
- Could you tell me if you are experiencing this same error when trying to use the template in an [incognito browser](https://i.imgur.com/ALzgiHp.png)
- Provide screenshots of any [browser console errors](https://imgur.com/KyLAzgH)
- check Site Health (go to Tools -> Site Health -> [Status](https://jmp.sh/aYS4Dlx)) does it display any messages about REST API?

**Comment by LuckynaSan** [comment]
@EckCreativeMedia Were you able to check the above details?

**Comment by LuckynaSan** [comment]
@EckCreativeMedia As we have not received a response on this issue, we will close it out. Feel free to post a topic on the [Web Stories Support Forum](https://wordpress.org/support/plugin/web-stories/) if you continue to encounter any issues. Thanks!
