### ISSUE TITLE
not able use template or publish story once created 

### ISSUE THREAD

**Issue by Roboromeo1** [GoogleForCreators/web-stories-wp#3606]
I'm getting this error , 

Unable to Create Story From Template
The response is not a valid JSON response.

**Comment by LuckynaSan** [comment]
@Roboromeo1 Thank you for reporting this error. 

Does this happen with all other plugins disabled and when disabling any ad blockers?

If you open developer tools in your browser (press F12) and check the Network tab, do you see any console errors when clicking on "Save draft"? Could you share a screenshot? You can use services like [Imgur](https://imgur.com/) or [Jumpshare](https://jumpshare.com).

**Comment by LuckynaSan** [comment]
@Roboromeo1 Have you had a chance to review the questions above? Hopefully, we can resolve this issue if you are still experiencing it.

**Comment by swissspidy** [comment]
Closing for now as there's been no response for over a month.
