### ISSUE TITLE
Design issues when Theme is disabled by the Oxygen Page builder

### ISSUE THREAD

**Issue by SEO-Durban** [GoogleForCreators/web-stories-wp#3623]
Web Stories is not working when the theme is disabled by the Page builder Oxygen.

Oxygen is a fast-growing new way to build WordPress websites without all the clutter.

This is how Web stories look like. All images and text are placed on the first page and there is only one page.

Any ideas to solve this issue. Could there be a workaround by adding a template to the Web stories where all the attributes could be setup?

![Annotation 2020-07-31 084810](https://user-images.githubusercontent.com/30296773/89164068-de42d300-d576-11ea-906b-a6861be9ab26.jpg)

[Link to the Stories on SEO-Durban.co.za](https://seo-durban.co.za/stories/auto-draft/?fbclid=IwAR2gMWbE90jiAGOpEclUlJAEZMOE7iHLLsCmEAMw9z328CJ11MGaUvVpKUU)
Best regards
Sten

**Comment by LuckynaSan** [comment]
@SEO-Durban Thank you for reporting this. I will investigate this further with the team, but in the meantime could you share your [Site Health](https://i.imgur.com/Rtkmsba.png) information to check if there are any plugin or theme incompatibilities?

**Comment by SEO-Durban** [comment]
Thank you very much.

Here are the site health for my website seo-durban.co.za  (any
recommendations are always appreciated)

`
### wp-core ###

version: 5.4.2
site_language: en_ZA
user_language: en_ZA
timezone: -02:00
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: true
user_registration: 0
default_comment_status: closed
multisite: false
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/aszktvxu/seo-durban.co.za
wordpress_size: loading...
uploads_path: /home/aszktvxu/seo-durban.co.za/wp-content/uploads
uploads_size: loading...
themes_path: /home/aszktvxu/seo-durban.co.za/wp-content/themes
themes_size: loading...
plugins_path: /home/aszktvxu/seo-durban.co.za/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-dropins (1) ###

advanced-cache.php: true

### wp-active-theme ###

name: Write (write)
version: 2.1.2
author: Themegraphy
author_website: http://themegraphy.com/
parent_theme: none
theme_features: woocommerce, wc-product-gallery-zoom,
wc-product-gallery-lightbox, wc-product-gallery-slider, menus,
post-thumbnails, title-tag
theme_path: fake

### wp-themes-inactive (3) ###

Twenty Nineteen: version: 1.6, author: WordPress Team
Twenty Seventeen: version: 2.3, author: the WordPress team
Twenty Twenty: version: 1.4, author: WordPress Team

### wp-plugins-active (13) ###

404 to 301 - Redirect, Log and Notify 404 Errors: version: 3.0.5, author:
Joel James
CAOS: version: 3.6.0, author: Daan van den Bergh
Cloudflare: version: 3.5.1, author: Cloudflare, Inc.
Fluent Forms: version: 3.6.42, author: WP Fluent Forms
Getwid: version: 1.6.4, author: MotoPress
Google XML Sitemaps: version: 4.1.0, author: Arne Brachhold
NitroPack: version: 1.3.16, author: NitroPack LLC
Oxygen: version: 3.4, author: Soflyy
OxyPowerPack: version: 1.2.46, author: Emmanuel Laborin
Self-Hosted Google Fonts: version: 1.0.1, author: asadkn
Web Stories: version: 1.0.0-beta.1, author: Google
Wordfence Security: version: 7.4.10, author: Wordfence
Yoast SEO: version: 14.7, author: Team Yoast

### wp-plugins-inactive (4) ###

Akismet Anti-Spam: version: 4.1.6, author: Automattic
Load Oxygen Locally: version: 1.0.2, author: THOMAS Michaël aka SUPAMIKE
Modal Block: version: 1.0.0, author: Mark Bird
Swift Performance Lite: version: 2.1.3, author: SWTE

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 9.25

### wp-server ###

server_architecture: Linux 3.10.0-962.3.2.lve1.5.36.el7.x86_64 x86_64
httpd_software: LiteSpeed
php_version: 7.2.32 64bit
php_sapi: litespeed
max_input_variables: 10000
time_limit: 900
memory_limit: 256M
max_input_time: 600
upload_max_size: 512M
php_post_max_size: 256M
curl_version: 7.62.0 OpenSSL/1.0.2k
suhosin: false
imagick_availability: false
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.3.23-MariaDB-cll-lve
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id:
3591daad22de08524295e1bd073aceeff11e6579 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/aszktvxu/seo-durban.co.za/wp-content
WP_PLUGIN_DIR: /home/aszktvxu/seo-durban.co.za/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: not writable
mu-plugins: writable

`

Best Regards

*Sten Wichmann*
*Manager & On-Site **SEO Specialist*

[image: ]   *removed email* <removed email>
[image: ]   *seo-durban.co.za* <https://www.seo-durban.co.za>
[image: ☎]   0027 (0)604520785

*SEO-DURBAN*
*WE OPTIMISE WEBSITES*

We know what works for *Google* and how to rank HIGH [image: ]
*(everyone says that right)*.

 *We **can prove IT!!!*[image: 👍]

Klik here
<https://www.google.com/search?rlz=1C1GGRV_enZA749ZA749&q=seo+company+durban&oq=seo+company+durban&gs_l=psy-ab.3...16213.464817.0.465331.20.14.1.0.0.0.439.2233.2-1j3j2.6.0....0...1.1.64.psy-ab..13.7.2245.6..0j35i39k1j0i22i30k1j0i19k1.JEm9nD5EbkU>
-
Search for SEO company Durban *here we are #1 and in the maps section too.*
Klik here
<https://www.google.com/search?q=search+engine+optimisation+durban&rlz=1C1GGRV_enZA749ZA749&oq=search+engine+optimisation+durban&aqs=chrome..69i57j69i60l2j69i65l3.6867j0j9&sourceid=chrome&ie=UTF-8>
-
Search for Search engine optimisation Durban *We rank #1 here as well*.
Our website was launched in April 2017 and the optimisation needed for
ranking at the top of *Google* is *VERY* difficult because who would hire
an SEO company that can´t rank on Google?


*Read more about SEO on our website SEO-Durban.co.za
<https://www.seo-durban.co.za/>*


This email and any attachments may be confidential and the subject of legal
professional privilege. Any disclosure, use, storage or copying of this
email without the consent of the sender is strictly prohibited. Please
notify the sender immediately if you are not the intended recipient. In
addition, delete this email from your inbox, do not disclose the contents
to another person, and do not use, copy or store the information in any
medium.

**Comment by LuckynaSan** [comment]
@SEO-Durban #3714 has been opened to improve the compatibility with Oxygen Builder. In addition to that, you'll want to [enable these two checkboxes](https://jmp.sh/Ji1qJYG) to hide the "Edit with Oxygen" links in the admin once there is an updated zip file available to use.

**Comment by swissspidy** [comment]
@SEO-Durban As mentioned before, please uninstall the plugin on your site and upload this ZIP file to install a newer in-development version: [web-stories.zip](https://github.com/google/web-stories-wp/files/5049916/web-stories.zip)

This should help improve the compatibility.

**Comment by SEO-Durban** [comment]
Thank you for the feedback. The new version is working fine now.

Best Regards

*Sten Wichmann*
*Manager & On-Site **SEO Specialist*

[image: ]   *Removed email* <Removed email>
[image: ]   *seo-durban.co.za* <https://www.seo-durban.co.za>
[image: ☎]   0027 (0)604520785

*SEO-DURBAN*
*WE OPTIMISE WEBSITES*

We know what works for *Google* and how to rank HIGH [image: ]
*(everyone says that right)*.

 *We **can prove IT!!!*[image: 👍]

Klik here
<https://www.google.com/search?rlz=1C1GGRV_enZA749ZA749&q=seo+company+durban&oq=seo+company+durban&gs_l=psy-ab.3...16213.464817.0.465331.20.14.1.0.0.0.439.2233.2-1j3j2.6.0....0...1.1.64.psy-ab..13.7.2245.6..0j35i39k1j0i22i30k1j0i19k1.JEm9nD5EbkU>
-
Search for SEO company Durban *here we are #1 and in the maps section too.*
Klik here
<https://www.google.com/search?q=search+engine+optimisation+durban&rlz=1C1GGRV_enZA749ZA749&oq=search+engine+optimisation+durban&aqs=chrome..69i57j69i60l2j69i65l3.6867j0j9&sourceid=chrome&ie=UTF-8>
-
Search for Search engine optimisation Durban *We rank #1 here as well*.
Our website was launched in April 2017 and the optimisation needed for
ranking at the top of *Google* is *VERY* difficult because who would hire
an SEO company that can´t rank on Google?


*Read more about SEO on our website SEO-Durban.co.za
<https://www.seo-durban.co.za/>*


This email and any attachments may be confidential and the subject of legal
professional privilege. Any disclosure, use, storage or copying of this
email without the consent of the sender is strictly prohibited. Please
notify the sender immediately if you are not the intended recipient. In
addition, delete this email from your inbox, do not disclose the contents
to another person, and do not use, copy or store the information in any
medium.

**Comment by LuckynaSan** [comment]
@SEO-Durban I'm glad this issue has been resolved! I will close this out. Thanks!
