### ISSUE TITLE
Background element should not be allowed to be moved as part of multi-selection

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#363]
**To reproduce**

1. Select background element
1. Cmd-click on other element to start multi-selection
1. Move elements around

**Actual behavior**

* The background element moves as part of the selection
* As soon as moving stops, it goes back to its background element position, but it keeps the changed coordinates

**Expected behavior**

The background element should not move as part of the multi-selection, and coordinates should be unchanged

**Comment by barklund** [comment]
You shouldn't be able to select multiple elements with the background being one of them at all either by [adding](https://github.com/google/web-stories-wp/blob/master/assets/src/edit-story/app/story/useStoryReducer/reducers/selectElement.js#L33-L38) or [toggling](https://github.com/google/web-stories-wp/blob/master/assets/src/edit-story/app/story/useStoryReducer/reducers/toggleElement.js#L36-L44) an element in selection.

But I do see the bug right there in both of them. If the selection is currently just the background element, nothing stops another element to be added to the selection. So, the fix would be quite simple here.

**Comment by swissspidy** [comment]
Perfect, even better! Thanks @barklund!
