### ISSUE TITLE
Firefox: elements from the library cannot be dropped on canvas drop targets

### ISSUE THREAD

**Issue by merapi** [GoogleForCreators/web-stories-wp#3632]
## Bug Description

Firefox only: elements from the library cannot be dropped on canvas drop targets.

## Screenshots

![firefox-drop-from-library](https://user-images.githubusercontent.com/21036224/89187815-0e519c80-d59e-11ea-884b-61127020653a.gif)

## Additional Context

- Plugin Version:
- Operating System:
- Browser: Firefox

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Closing as this seems to be working now in FF.
