### ISSUE TITLE
Firefox: drop targets visuals are broken

### ISSUE THREAD

**Issue by merapi** [GoogleForCreators/web-stories-wp#3633]
## Bug Description

Drop targets visuals are broken on Firefox, see attached GIF.

## Screenshots

![firefox-drop-targets-visuals](https://user-images.githubusercontent.com/21036224/89189741-b6686500-d5a0-11ea-9a8c-28d1ece23804.gif)

## Additional Context

- Plugin Version:
- Operating System:
- Browser: Firefox only

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Is this still an issue?
