### ISSUE TITLE
Show both "global" and "local" colors in the color picker

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#3634]
## Feature Description

In the color picker, users can access both global (available across all stories) and local (story-specific) preset colors. 

**[Designs](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=1965%3A326019)**

### Limitations

* This ticket is to be implemented after #3635 and assumes the new API and functionality of that ticket to be in place.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
@barklund can you please provide a HL estimate on this

**Comment by barklund** [comment]
This ticket is to be implemented after #3635 and assumes the new API and functionality of that ticket to be in place.

**Comment by barklund** [comment]
This ticket also does not include new design for color picker, as this new design is not final. It only concerns the footer with the display of "current story colors" vs. "all story colors" and the option of adding a color there.

**Comment by bmattb** [comment]
@o-fernandez please indicate if this is required for 1.2

**Comment by bmattb** [comment]
This is dependant on the panel redesign work that is currently targeted for v1.3

**Comment by claudiosossi** [comment]
Verified in QA
