### ISSUE TITLE
Show both "global" and "local" colors in the design panel color presets

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#3635]
## Feature Description

Related to #3634, user should be able to see both local and global colors in the design panel's color presets section (in addition to the color picker, which is covered by #3634). 

In addition, the user should be able to _manage_ color presets and delete any no longer of interest from both global and local color lists. 

**[Figma Designs](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=1972%3A214736)**

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
@barklund estimate please (then remove your assignment and the Estimate Needed label) - thanks!

**Comment by barklund** [comment]
This ticket requires thorough implementation brief before commencing, as this has implications for backend and API too.

**Comment by miina** [comment]
@o-fernandez  Q: Would saving of the global colors work separately from the local story colors? E.g. would the colors be saved globally right away after adding/removing?

**Comment by o-fernandez** [comment]
> @o-fernandez Q: Would saving of the global colors work separately from the local story colors? E.g. would the colors be saved globally right away after adding/removing?

@miina I'm not sure I understand the question...
* Global and local colors are separate, local is just for that story, global is for all stories. 
* Colors should be added/removed near immediately from the respective place when the user adds/remove (e.g., if I add a global color, it should show up as a global color for all users across all stories near instantaneous. I imagine the same with local colors?)

**Comment by miina** [comment]
@o-fernandez Currently, with the color presets as they are now, these only get updated in the database together with saving the story -- once the user clicks "Update" (or "Save Draft" or auto-save happens).

That was the question -- if the global colors should be saved immediately after any change instead of waiting for saving the story (so they would show up for all the other users right away as well).

**Comment by o-fernandez** [comment]
> @o-fernandez Currently, with the color presets as they are now, these only get updated in the database together with saving the story -- once the user clicks "Update" (or "Save Draft" or auto-save happens).
> 
> That was the question -- if the global colors should be saved immediately after any change instead of waiting for saving the story (so they would show up for all the other users right away as well).

I think it's OK to do all updates at story saving time. The behavior can be a bit odd, given that global colors are not tied to the story, but it would also be weird for global colors saving to behave differently from local colors being saved.

**Comment by miina** [comment]
From grooming today:
Potential conflicts should be addressed in case of more than one user modifying the global colors at the same time, e.g. keeping a version of the global presets and detecting the changes compared to the previous version only.

**Comment by spacedmonkey** [comment]
What is needed from the infra pod here?

**Comment by miina** [comment]
@barklund @bmattb FYI I'll pull this into the sprint and start looking into it. Most likely won't get ready within this sprint as it's 8 points.

As of now it looks like there's nothing needed from the infra pod, will let know if new information comes up.

**Comment by csossi** [comment]
Verified in QA
