### ISSUE TITLE
"Page" element can have either color or media applied to it, but not both

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#3638]
## Feature Description

[Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=2%3A91886)

A user will be able to specify the page background color, or add a page background media element that'd be fullbleed. A user may not specify both color and bg media, as in that case the bg color wouldn't display. 

If the user adds an image, the page background color in the story is automatically set by the user (can be set to be the average pixel color in the image).

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

**Note**: We will implement this in the old design, not the new one (not yet at least).

Implementation of dominant color will be done using [`colorthief`](https://lokeshdhakar.com/projects/color-thief/), which is already in the project.

For background videos, we take the primary color of the cover image for the video - regardless of whether that cover image is manually set rather than taken from the video itself.

### TODO

- [ ] Remove color panel for background elements if there's a media element
- [ ] Set background element color based on dominant color of media content

**Comment by csossi** [comment]
Verified in QA
