### ISSUE TITLE
Text presets: expand text presets to include new options

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#3639]
The text presets section has been updated to include: h1, h2, h3, paragraph, caption. 

**[UX Specs in Figma file](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Sam---Visual-Design-Frames?node-id=711%3A530)**

**Comment by barklund** [comment]
Assuming this ticket is only about adding/updating the new text definitions and not about allowing dragging for texts onto page (as that is not currently possible).

**Comment by barklund** [comment]
I think this was completed by #3787 - @o-fernandez to confirm if still an issue

**Comment by o-fernandez** [comment]
I don't think this has been completed **[per the spec](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=837%3A1962)**. This is what it looks like if I do this in the editor today: 

![image](https://user-images.githubusercontent.com/13389997/91231178-cf28ee00-e6fa-11ea-8b5e-7a9e74884f68.png)


Here is the visual spec: 

![image](https://user-images.githubusercontent.com/13389997/91231251-ecf65300-e6fa-11ea-861a-0fe4ea447fb0.png)

I updated manually the values for each of these to follow the spec Sam provided (assuming px translates fairly OK to the editor values) and looks much closer to the design. Although noted that we don't allow for fractional font size (e.g., 21.6 so had to use 22) or negative letter spacing (so couldn't apply the -1% on the heading). @samitron7 FYI

Mistakes/differences I noticed: 

- H2, H3 in the editor today use the normal font weight, rather than bold. 
- They all default to 1.5 font height, while the spec has different font height for headings. 
- Most font sizes are different (and don't follow the same scale Sam used).

Updated view
![image](https://user-images.githubusercontent.com/13389997/91231677-b0772700-e6fb-11ea-86f6-b42771a93444.png)


Also note that the presets preview in the text panel are left aligned in the spec, while center aligned in the editor's text panel. 
![image](https://user-images.githubusercontent.com/13389997/91231985-414e0280-e6fc-11ea-8e90-dbed7ee5e3cc.png)


The spec also has the typographic scale and all the conversions, so hopefully this also helps: 
![image](https://user-images.githubusercontent.com/13389997/91233703-c38bf600-e6ff-11ea-8c92-81d6a9809723.png)

**Comment by csossi** [comment]
Verified in QA

**Comment by o-fernandez** [comment]
Filed #4419 for continuation work - fractional text sizes.
