### ISSUE TITLE
Text Sets (Combos): Filter by current font

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#3640]
A user may filter text sets by using either: 

- category filters (work to be done in #4080) 
- "show matches for font in story"

"Show matches for font in story" would only show text sets that use the fonts already in use in the user's current story. 

**[Designs](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=2%3A31546)**

**Comment by barklund** [comment]
~This ticket is blocked by #491 still in UX Needed thus this will be moved similarly and cannot be estimated until UX for blocker is known~

Edit: Ignore this

**Comment by csossi** [comment]
Verified in QA

**Comment by o-fernandez** [comment]
The "match font in the story" filter is missing in the designs @samitron7 [figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=892%3A0)

**Comment by samitron7** [comment]
It should be [here](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=2%3A31546)

**Comment by o-fernandez** [comment]
Updated the main descriptions, def not up to spec. Will file a ticket to update and put into the UX Quality issues.
