### ISSUE TITLE
Theme update for visual design (visual pass update)

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#3641]
Theme updates to get the dashboard into its new UI design. (**[Figma overview file](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Sam---Visual-Design-Frames?node-id=0%3A1)**)

**Comment by o-fernandez** [comment]
@wassgha working on this in PR #3622

**Comment by swissspidy** [comment]
Should this be correctly added to the sprint?

cc @bmattb

**Comment by bmattb** [comment]
@wassgha As this is in the current sprint, can you please provide an estimate of story points for this?

**Comment by barklund** [comment]
This ticket is now only related to tickets #3622 (already merged) and #3787 (in review). Once completed, this ticket will be closed. Remaining work will be added in new tickets.
