### ISSUE TITLE
Grid View: focused page not distinguishable from selected page

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#3653]
After #2717 implementation, when in page grid mode I can use the tab key to navigate around page grid layout and the arrow keys to change pages when in the page grid itself. However, there are two confusing states as it is not visible to the user what's being selected. 

Here's the tab selection order I see: 
1. Back button
2. Smaller grid sizing button
3. **Grid sizing slider (selection not distinguishable)** 
4. Larger grid sizing button
5. **Pages grid (selection not distinguishable - defaults to currently selected page and there's no visible differentiation between "current page" and "current page selected")** 

We should have some visual differentiation between selected and not selected state.

**Comment by o-fernandez** [comment]
@carlos-kelly @dmmulroy do you think you could come up with something good to do here without requiring UX designs? Let me know if you have something in mind, otherwise we can put this in the UX queue although that may take a bit given how backlogged UX is.

**Comment by carloskelly13** [comment]
@csossi Did this fail QA and what was the reason? Thanks!

**Comment by dmmulroy** [comment]
Closing this as done/duplicate - this is being solved as part of #4240 in PR #4248
