### ISSUE TITLE
Move StoryAnimation components into edit-story codebase & update to useContextSelector pattern

### ISSUE THREAD

**Issue by maxyinger** [GoogleForCreators/web-stories-wp#3670]
Move all story animation code (provider, wrappers & animations) into edit-story code base. edit-story code should be a dependency of dashboard and not the other way around which it currently is.

Update useStoryAnimation hook to follow useContextSelector pattern used in edit-story codebase.

**Comment by swissspidy** [comment]
If it's used by both, maybe worth splitting out into `assets/src/animations` or something?
