### ISSUE TITLE
React Fast Refresh

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#3689]
## Feature Description

[Fast Refresh](https://github.com/pmmmwh/react-refresh-webpack-plugin) (née Hot Reloading) might be a welcome enhancement for engineers working on the project.

## Additional Context

https://github.com/pmmmwh/react-refresh-webpack-plugin

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
@swissspidy - ok if I move this into our next sprint for @samwhale?

**Comment by swissspidy** [comment]
Sure!

I have some WIP code that I can push to a branch tomorrow as a starting point for collaboration.

**Comment by samwhale** [comment]
Wasn't able to make too much headway here. Added my findings to #10779, and hopefully in the future we can make more of a dent!

Going to move onto something different for now.
