### ISSUE TITLE
Cross hair guidelines appear on background image on selection

### ISSUE THREAD

**Issue by pbakaus** [GoogleForCreators/web-stories-wp#369]
## Bug Description

Cross hair guidelines appear on background image on selection.

## Expected Behaviour

The guidelines should only appear on pointer down (drag).

## Steps to Reproduce

Add an image to the background, then click it.

## Screenshots

![image](https://user-images.githubusercontent.com/43004/75103213-6ecebd80-55ac-11ea-8e39-95ec8095c4e5.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
This already has a PR, #364
