### ISSUE TITLE
Use default meta values

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#3690]
## Feature Description

In WordPress 5.5 there new functionality added that allows for default meta values to be registered. See the official [blog post](https://make.wordpress.org/core/2020/08/04/registering-default-values-for-meta-data/). Register meta is used in 2 places, [here](https://github.com/google/web-stories-wp/blob/7cf07181c4a39995df3552a4f50b86036c2b43af/includes/Media.php#L115-L139) and [here](https://github.com/google/web-stories-wp/blob/7cf07181c4a39995df3552a4f50b86036c2b43af/includes/Tracking.php#L64-L76).

Related #3300

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
after discussion agreed that this could be added to s34
