### ISSUE TITLE
Improve console errors / error stack traces

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#3694]
## Task Description

Right now the error message we get from the React error  boundary (`error.componentStack`) is not that usable. Example:

```
TypeError: Cannot read property 'elements' of undefined
in oM
in Unknown
in bs
in Unknown
in xA
in Unknown
in Qc
in Unknown
in $l
in QN
in Se
in te
in NH
in v
```

Let's find out how we could improve this, without making the app significantly larger or slower.

Right now we don't build any source maps for production builds. Enabling that would only help for console errors, but not the React error boundary, as that is just a string that cannot be mapped to a source map. Plus, the source maps are quite large (multiple MB).

We could do something like passing `keep_fnames: /[A-Z].+/,` to terser so the function names are more readable.

An alternative would be `babel-plugin-react-displayname-path` or `babel-plugin-add-react-displayname`.

Or, if none of the above is possible, we could just send the users a custom development build of the plugin for debugging or something like that.

## Additional Context

https://webpack.js.org/configuration/devtool/
https://github.com/facebook/create-react-app/issues/3753
https://github.com/facebook/create-react-app/issues/6667

## Implementation Brief

Amend webpack config like so:

```js
terserOptions: {
	[...]
	// We preserve function names that start with capital letters as
	// they're _likely_ component names, and these are useful to have
	// in tracebacks and error messages.
	keep_fnames: /__|_x|_n|_nx|sprintf|^[A-Z].+$/,
}

**Comment by swissspidy** [comment]
Soooo! Site Kit uses this: https://github.com/google/site-kit-wp/pull/976

And it seems to work well for them. Let's do the same then.

```js
terserOptions: {
	// We preserve function names that start with capital letters as
	// they're _likely_ component names, and these are useful to have
	// in tracebacks and error messages.
	keep_fnames: /__|_x|_n|_nx|sprintf|^[A-Z].+$/,
}
```

**Comment by swissspidy** [comment]
This might get even better with React 17: https://reactjs.org/blog/2020/08/10/react-v17-rc.html#native-component-stacks

**Comment by spacedmonkey** [comment]
What should we do, wait for React 17 or add this one liner. I would say add one liner and remove when we upgrade to react 17

**Comment by swissspidy** [comment]
If I understood the blog post correctly, we would still have to keep this change even with React 17. But we'll see once we upgrade.
