### ISSUE TITLE
Background img does not respect containment boundaries at center position

### ISSUE THREAD

**Issue by pbakaus** [GoogleForCreators/web-stories-wp#371]
## Bug Description

When the background layer is dragged and perfectly centered, it ignores the containment/boundaries of the page.

## Expected Behaviour

Background should always be covering the page.

## Steps to Reproduce

Drag the background img, and position exactly in the center. For more pronounced effect, drag your cursor to the bottom of the page.

## Screenshots

![Screen Shot 2020-02-22 at 7 56 55 PM](https://user-images.githubusercontent.com/43004/75103312-fff26400-55ad-11ea-8d7d-5483a54ddb20.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by pbakaus** [comment]
Additional note: Dropping it in that state seemingly auto heals itself, but not in actuality: The zoom slider is now super broken, as it believes the focal point is somewhere other than the center.

**Comment by barklund** [comment]
Other issues partially cloud this now (the zoom slider is not visible for background images), but otherwise, is this still an issue @pbakaus?

**Comment by pbakaus** [comment]
Can't repro anymore, let's close for now.
