### ISSUE TITLE
Plugin Activation: Warn if WordPress version incompatible

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#3732]
## Feature Description

We've seen cases where users installed the beta on WordPress < 5.3, which is not supported.

Just like we have a warning for incompatible PHP versions, let's add a warning for incompatible WordPress versions.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

* Plugin activation should bail early on WordPress < 5.3

## Implementation Brief

* In `web-stories.php`, define a new `WEBSTORIES_MINIMUM_WP_VERSION` constant
* In the `activate` function in `includes/namespace.php`, compare the current WP version against that constant.

**Comment by spacedmonkey** [comment]
Doesn't WordPress core do this now. In 5.2/5.3 the [validate_plugin_requirements](https://github.com/WordPress/wordpress-develop/blob/f556437ef433cacb67299ec3ee40ce56311077da/src/wp-admin/includes/plugin.php#L1113-L1205) function was added. See the original trac ticket [#43992](https://core.trac.wordpress.org/ticket/43992). I feel like core has this covered and we have already added the header needed to show this message. Is there something I am missing.

**Comment by swissspidy** [comment]
@spacedmonkey That only works on WordPress 5.2+ though. If someone installs the plugin on WordPress 5.0 (which has happened), then  that doesn't exist.

**Comment by spacedmonkey** [comment]
I feel like they change the api to only return results for plugins that would work. So if you search on the plugin repo in cms you would not see it. You would manually have to install it.

**Comment by swissspidy** [comment]
> You would manually have to install it.

Correct, which is what people have to do right now with the beta. We're not in the repo yet.

**Comment by swissspidy** [comment]
We can consider removing it at some point, but since this helps catching some edge cases, we should do this for now.

**Comment by spacedmonkey** [comment]
So it is basically the same as these existing lines? 
https://github.com/google/web-stories-wp/blob/3fb20c46c829a91e5ac9c1acea09c8f42a39aaea/includes/namespace.php#L98-L104

We could tweak this to 

```
	if ( version_compare( get_bloginfo('version'), WEBSTORIES_MINIMUM_WP_VERSION, '<' ) ) {
		wp_die(
		         /* translators: %s: WordPress version number */
			esc_html( sprintf( __( 'Web Stories requires WordPress %s or higher.', 'web-stories' ), WEBSTORIES_MINIMUM_WP_VERSION ) ),
			esc_html__( 'Plugin could not be activated', 'web-stories' )
		);
	}
```

**Comment by swissspidy** [comment]
> So it is basically the same as these existing lines?

Yes.

> We could tweak this to

Do you mean because WordPress 5.3 requires PHP 5.6 anyway?

I like the thought, but I could see us bumping the PHP requirement for the plugin sooner than WordPress does.

So if we ever require WordPress 5.5+ but PHP 7+, then we need both `WEBSTORIES_MINIMUM_WP_VERSION` _and_ `WEBSTORIES_MINIMUM_PHP_VERSION`.

Thus, we should keep both.
