### ISSUE TITLE
Get storybook playground into basic, functional state

### ISSUE THREAD

**Issue by pbakaus** [GoogleForCreators/web-stories-wp#374]
## Feature Description

Would be great if we could get https://google.github.io/web-stories-wp/?path=/story/playground-stories-editor--default into basic, functional state. This means, at minimum:

* A few test images in the media gallery (can be static)
* A few test shapes
* Text works
* Save saves to localStorage
* Preview works

/cc @swissspidy 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

* **Related issues / PRs:** #11, #233, #2918

**Comment by swissspidy** [comment]
This is gonna be a great exercise to further decouple the editor from WordPress. Unfortunately I haven't had the time to look into it more, but mocking the REST API responses to support media usage and storage (although it should probably use sessionStorage) seems feasible.

Previews would be more feasible with #233, but could also be faked by the storybook integration in the meantime

**Comment by spacedmonkey** [comment]
Related https://github.com/google/web-stories-wp/issues/349
