### ISSUE TITLE
Undefined method error

### ISSUE THREAD

**Issue by princeofanimation** [GoogleForCreators/web-stories-wp#3745]
## Request

Fatal error: Call to undefined method WP_Post_Type::get_rest_controller() in /home1/mobiljm5/public_html/wp-content/plugins/web-stories/includes/REST_API/Stories_Autosaves_Controller.php on line 71

- Plugin Version: Version 1.0.0-beta.1
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
@princeofanimation Thanks for your report! Which version of WordPress are you using?

This plugin currently requires WordPress 5.3 or newer. The reported `WP_Post_Type::get_rest_controller()` function is not available before that. Please try updating your WordPress site and let us know if that fixes the issue.

Note that we'll be improving the messaging around this soon, see #3732

**Comment by ernee** [comment]
Hi @princeofanimation! I'm checking if you were able to update your WordPress version?

**Comment by ernee** [comment]
@princeofanimation just making another quick follow up to see if you were able to update your WordPress version as well as try the latest Beta 2  available for download [on the website](https://google.github.io/web-stories-wp/beta/)?

Could you let us know if this issue persists after doing the above? thank you!

**Comment by ernee** [comment]
@princeofanimation just following up on your issue again. Does the error still occur with the most recent version of WordPress and of the plugin version 1.0.0-rc.1?

**Comment by ernee** [comment]
@princeofanimation the stable version 1.0.0 of the plugin has been released, so feel free to update (along with WordPress 5.3 or higher). If you should have any further questions or concerns, please open a topic in our [WordPress.org support forum](https://wordpress.org/support/plugin/web-stories/). We're happy to help!
