### ISSUE TITLE
AMP Invalidation due to WP Rocket

### ISSUE THREAD

**Issue by ArtFl-2** [GoogleForCreators/web-stories-wp#3746]
## Request

My web story produces AMP errors and is not validated by Google's testing tool.
Please view the test results:
https://search.google.com/test/amp?id=Bw5OlqUaO7c2K-WExoccbA

I use WP Rocket caching plugin and AMPforWP plugin.
Could there be a conflict?

## Additional Context

- Plugin Version: 1.0.0-beta.1
- Operating System: Windows 10
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by fellyph** [comment]
Hi @ArtFl-2 

I had the same issue you should remove the stories urls from WP Rocket. 
On Advanced Rules set the plugin to exclude the cache for stories urls ```/stories/(*)```

**Comment by ArtFl-2** [comment]
Hi fellyph,

Yes, it worked.
Thank you so much for your kind assistance!
