### ISSUE TITLE
Error when click share on Chrome MacOS

### ISSUE THREAD

**Issue by fellyph** [GoogleForCreators/web-stories-wp#3754]
## Bug Description

I've created my first web stories when I try to share on Chrome macOS I'm getting an error message

## Expected Behaviour

If the browser doesn't have support shows a fallback instead an error message

## Steps to Reproduce

1. go to the web story
2. click at the share button on the top right corner

## Screenshots

1. at the story click on share
![Screen Shot 2020-08-10 at 09 25 17](https://user-images.githubusercontent.com/330792/89763938-6f6ff780-daeb-11ea-9a78-c0f3aaa6d5b9.png)

Error message
![Screen Shot 2020-08-10 at 09 28 37](https://user-images.githubusercontent.com/330792/89764242-f1602080-daeb-11ea-93af-86c8fea997be.png)

## Additional Context

- Plugin Version: 1.0.0-beta.1
- Operating System: macOS
- Browser: Chrome 84.0.4147.105

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by LuckynaSan** [comment]
Hi @fellyph, When I [share your URL](https://jmp.sh/Ng5tVgF) an error did not occur. Does this error occur when you share the story in a different browser like Firefox or Safari?

**Comment by fellyph** [comment]
@LuckynaSan the error is only on Chrome, Firefox and safari works fine for me too.

**Comment by swissspidy** [comment]
I can also not reproduce this in Chrome 84. Does it work in incognito mode?

**Comment by fellyph** [comment]
@swissspidy Same on incognito mode, I also tested with all extensions off

<img width="1161" alt="Screen Shot 2020-08-15 at 13 21 50" src="https://user-images.githubusercontent.com/330792/90312218-72f3ec00-defa-11ea-918d-8edcf97ad26e.png">

**Comment by swissspidy** [comment]
@fellyph Thanks a lot, very helpful. One more question: does this also happen with any other web story, or just the ones created on your site?

Here are some other web stories:

https://preview.amp.dev/documentation/examples/introduction/stories_in_amp
https://www-usatoday-com.cdn.ampproject.org/c/s/www.usatoday.com/amp-stories/beyonce-rule-the-world/

**Comment by fellyph** [comment]
@swissspidy 

<img width="978" alt="Screen Shot 2020-08-15 at 14 48 57" src="https://user-images.githubusercontent.com/330792/90313714-8efd8a80-df06-11ea-8937-fd21425e7a09.png">

Same error, do you think is it my machine ?

**Comment by LuckynaSan** [comment]
@fellyph Could try [downloading Beta 2](https://google.github.io/web-stories-wp/beta/) version of Web Stories and let us know if the issue persists?

**Comment by fellyph** [comment]
Hi @LuckynaSan 

I've tested the new version and I still getting the issue, I started to analyse my chrome to find what I have different than than Chrome Canary and Incognito mode and I have found. 

My Chrome had a experimental flag enabled I've disabled it and now the share button is working fine:

<img width="1172" alt="Screen Shot 2020-08-27 at 14 22 56" src="https://user-images.githubusercontent.com/330792/91447654-d540db00-e870-11ea-8f5d-cde75b803d82.png">

Now the share button is working:

<img width="1184" alt="Screen Shot 2020-08-27 at 14 23 30" src="https://user-images.githubusercontent.com/330792/91447733-ebe73200-e870-11ea-9d03-210a7cd3355f.png">

**Comment by LuckynaSan** [comment]
Thank you and great findings! Glad it is working now.
