### ISSUE TITLE
Social Sharing: Missing Featured Image

### ISSUE THREAD

**Issue by fellyph** [GoogleForCreators/web-stories-wp#3755]
## Feature Description

I've shared on twitter my web story the shared card doesn't show the feature image. After I have tested the same on facebook.

## Alternatives Considered

If is possible read the feature image as feature image for social sharing on LinkedIn, Twitter and Facebook. 

## Additional Context

Fetch the content on Twitter cards test
<img width="1143" alt="Screen Shot 2020-08-10 at 10 10 41" src="https://user-images.githubusercontent.com/330792/89768347-66832400-daf3-11ea-9069-800332371c20.png">

Fetch the content on facebook debugger
<img width="1360" alt="Screen Shot 2020-08-10 at 09 47 08" src="https://user-images.githubusercontent.com/330792/89768258-481d2880-daf3-11ea-9192-dd7db9c4f0a0.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Hi there,

Thanks for your report!

We do add the code for social sharing by default. However, on your site the necessary logic is handled by Yoast SEO, so you'd have to check the Yoast SEO settings and [consult their documentation](https://yoast.com/help/twitter-sharing-not-working/).

Note that Twitter has some [requirements](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary-card-with-large-image.html) for the image when sharing, so make sure your featured image meets those requirements.

**Comment by fellyph** [comment]
Hi Pascal

I will have a look at the documentation

Thanks,
Fellyph
