### ISSUE TITLE
Add a field to include the Web Story title on Document settings

### ISSUE THREAD

**Issue by fellyph** [GoogleForCreators/web-stories-wp#3756]
## Feature Description

First time that used the Visual editor was't clear were I can change the Web Story title

## Alternatives Considered

Is it possible include a title field on the document settings panel?

## Additional Context

<img width="859" alt="Screen Shot 2020-08-10 at 10 26 34" src="https://user-images.githubusercontent.com/330792/89769003-57e93c80-daf4-11ea-8e9b-745d5b06b9c1.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by ernee** [comment]
@fellyph thanks for your feedback and request!

**Comment by swissspidy** [comment]
I am closing this as a duplicate of #41 as the title input will be reworked to make it more prominent. Also, guidance exists for pointing users to that field as well.
