### ISSUE TITLE
Add a description field at document settings

### ISSUE THREAD

**Issue by fellyph** [GoogleForCreators/web-stories-wp#3757]
## Feature Description

I've shared my web story on twitter and the card descriptions was my Web Story title + parts of the text from my web stories without a non-logical sentence on the description. The sequence of the layers affects the text order and the user wont be aware about it until share the story

## Alternatives Considered

Is it possible to include a description field to add a meta description to write more appealing description for social sharing. 

## Additional Context

<img width="804" alt="Screen Shot 2020-08-10 at 10 34 53" src="https://user-images.githubusercontent.com/330792/89769855-d2ff2280-daf5-11ea-8cb0-ca5177f0f6bd.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by ernee** [comment]
@fellyph thanks again for a great request! We'll look into improving this in the plugin. 

Per [this issue](https://github.com/google/web-stories-wp/issues/3755#issuecomment-671257937), it also seems like you are using Yoast on the site. In case it may be of interest, we'll also be looking into [supporting legacy WordPress metaboxes](https://github.com/google/web-stories-wp/issues/3134) which may help with customizing this description.

**Comment by fellyph** [comment]
Hi @ernee 

I've disabled the YOAST to test it and the code generated for twitter is the same:

```<meta name="twitter:card" content="summary_large_image"><meta name="twitter:creator" content="@fellyph"><meta name="twitter:site" content="@fellyph">```

And the "og" tags also are the same:

```<meta property="og:title" content="Como criar WebStories no WordPress - Blog Fellyph Cintra">```
```<meta property="og:description" content="Como criar WebStories no WordPress Baixe a versão beta  aqui Baixe a versão beta  aqui 1 – Baixe o plugin oficial web stories para WordPress 2 – Instale no painel de plugins 3 – Ative o plugin e crie sua primeira história 4 – Adicione o conteúdo com imagens es vídeos com o editor visual 5 […]">```
```<meta property="og:url" content="https://blog.fellyph.com.br/stories/como-criar-webstories-no-wordpress/">```
```<meta property="og:site_name" content="Blog Fellyph Cintra">```

**Comment by swissspidy** [comment]
Thanks for checking!

The improvements in #3134 and #490 would help improve the meta description for both regular usage and when using Yoast SEO.

**Comment by swissspidy** [comment]
Closing this since the "Story description" field nowadays allows setting the meta description, and custom meta boxes will be soon supported too
