### ISSUE TITLE
Open the document settings by default

### ISSUE THREAD

**Issue by fellyph** [GoogleForCreators/web-stories-wp#3774]
## Feature Description

When the user creates a new web story, start the visual editor with the right side panel with a message "Nothing selected", and some informations are hidden on the document settings tab at the first moment. 

## Alternatives Considered

Would help the user fill important information such as icon and feature image if the document settings tab started selected by default?

## Additional Context

<img width="1392" alt="Screen Shot 2020-08-10 at 10 28 46" src="https://user-images.githubusercontent.com/330792/89787177-f38aa500-db14-11ea-8d99-3947e9afdff6.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by ernee** [comment]
@fellyph this is really helpful feedback!

**Comment by swissspidy** [comment]
@samitron7 This ticket is a low-hanging fruit to get some UX input on to improve the default state.

**Comment by swissspidy** [comment]
@o-fernandez thoughts on this feature request?

**Comment by BrittanyIRL** [comment]
Now that we have combined the panels the default state shows media to insert.
