### ISSUE TITLE
Save style for headers, sub headers and text

### ISSUE THREAD

**Issue by fellyph** [GoogleForCreators/web-stories-wp#3775]
## Feature Description

When I worked creating web stories, I tried to use the same visual identity for header and text across the pages and every new page I needed to set up font family, font size and other properties. That takes some time to make the layout consistent.

## Alternatives Considered

Would be great have an option to save a style for headers, sub-headers and text to reuse between pages. I will helps to speed up the process to create stories and help the layout be consistent.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Thanks for your report! Saving & re-using text styles is something we're planning on adding. You can follow #353 for progress on that feature.

**Comment by fellyph** [comment]
Thanks @swissspidy
