### ISSUE TITLE
broken database

### ISSUE THREAD

**Issue by dgmdonna** [GoogleForCreators/web-stories-wp#3776]
## Request

The problem is that in 2 sites that I have used the plugin, the database has been broken, generating problems with the menu and the content

## Additional Context

- Plugin Version: Version 1.0.0-beta.1
- Operating System: Windows
- Browser: Chrome (last update 08-09-2020)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by ernee** [comment]
@dgmdonna thanks for reporting and I'm sorry to hear about the trouble.

1) Did this occur after activating the plugin or with some action in particular? 

2) Could you share your [Site Health information](https://i.imgur.com/Rtkmsba.png) so we can check for any conflicts?

**Comment by swissspidy** [comment]
A screenshot would be helpful too!

**Comment by dgmdonna** [comment]
Before using the plug in we made a backup of the database, but it still broke the way it shows when you are logged into wordpress.

Site Health: 
### wp-core ###

version: 5.4.2
site_language: en_US
user_language: en_US
timezone: -05:00
permalink: /blog/%postname%/
https_status: true
user_registration: 0
default_comment_status: closed
multisite: false
user_count: 8
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/lttrmastrsite1/public_html
wordpress_size: 20.16 GB (21651076154 bytes)
uploads_path: /home/lttrmastrsite1/public_html/wp-content/uploads
uploads_size: 736.70 MB (772481139 bytes)
themes_path: /home/lttrmastrsite1/public_html/wp-content/themes
themes_size: 9.87 MB (10351126 bytes)
plugins_path: /home/lttrmastrsite1/public_html/wp-content/plugins
plugins_size: 89.54 MB (93885956 bytes)
database_size: 249.69 MB (261815218 bytes)
total_size: 21.22 GB (22789609593 bytes)

### wp-active-theme ###

name: Brandon (brandon)
version: 1.1.0
author: Muffin group
author_website: http://muffingroup.com
parent_theme: none
theme_features: automatic-feed-links, post-thumbnails, menus, widgets
theme_path: /home/lttrmastrsite1/public_html/wp-content/themes/brandon

### wp-themes-inactive (1) ###

Twenty Twenty: version: 1.4, author: the WordPress team

### wp-plugins-active (21) ###

Accelerated Mobile Pages: version: 1.0.61.2, author: Ahmed Kaludi, Mohammed Kaludi
Admin Columns: version: 4.1.6, author: AdminColumns.com
Advanced Custom Fields: version: 5.8.13, author: Elliot Condon
Akismet Anti-Spam: version: 4.1.6, author: Automattic
All In One SEO Pack Pro: version: 3.6.2, author: All in One SEO Team
All In One WP Security: version: 4.4.4, author: Tips and Tricks HQ, Peter Petreski, Ruhul, Ivy
AMP Pro Extension Manager: version: 1.0.9, author: AMPforWP Team
AMP Theme Framework: version: 1.0, author: AMPforWP Team
Brave Payments Verification: version: 1.0.4, author: Brave Software Intl
Classic Editor: version: 1.5, author: WordPress Contributors
EmbedPress: version: 2.6.0, author: WPDeveloper
HREFLANG Tags Lite: version: 1.9.6, author: DCGWS LLC
Imagify: version: 1.9.10, author: WP Media
Ninja Forms: version: 3.4.24.3, author: Saturday Drive
Ninja Forms - File Uploads: version: 3.3.7, author: The WP Ninjas
Ninja Forms for AMP: version: 1.2.4, author: Ahmed Kaludi, Mohammed Kaludi
Simple 301 Redirects: version: 1.07, author: Scott Nellé
Simple Share Buttons Adder: version: 7.7.1, author: Simple Share Buttons
SSL Insecure Content Fixer: version: 2.7.2, author: WebAware
Web Stories: version: 1.0.0-beta.1, author: Google
WordPress Force HTTPS: version: 0.1.4, author: A. Kai Armstrong

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1690
imagemagick_version: ImageMagick 6.9.10-68 Q16 x86_64 2020-04-01 https://imagemagick.org
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 125 GB
	imagick::RESOURCETYPE_DISK: 9.22337203685E+18
	imagick::RESOURCETYPE_FILE: 12288
	imagick::RESOURCETYPE_MAP: 125 GB
	imagick::RESOURCETYPE_MEMORY: 63 GB
	imagick::RESOURCETYPE_THREAD: 12
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 9.25

### wp-server ###

server_architecture: Linux 3.10.0-862.3.3.el7.x86_64 x86_64
httpd_software: Apache
php_version: 7.3.20 64bit
php_sapi: cgi-fcgi
max_input_variables: 1000
time_limit: 360
memory_limit: 1024M
max_input_time: 360
upload_max_size: 8192M
php_post_max_size: 16M
curl_version: 7.71.0 OpenSSL/1.1.1g
suhosin: false
imagick_availability: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.7.31
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: https://www.looktotheright.com
WP_SITEURL: https://www.looktotheright.com
WP_CONTENT_DIR: /home/lttrmastrsite1/public_html/wp-content
WP_PLUGIN_DIR: /home/lttrmastrsite1/public_html/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable



This is an image of how the site is now, even with the database restored.

![image](https://user-images.githubusercontent.com/22637780/89907348-ef1cc580-dbc2-11ea-8de4-c525dfee7052.png)

**Comment by ernee** [comment]
@dgmdonna thanks so much for the details!

Since this is affecting your experience while logged in, I'm curious if this is a theme or plugin conflict. 

Could you install the [Health Check & Troubleshooting plugin](https://wordpress.org/plugins/health-check/), enable [Troubleshooting mode ](https://make.wordpress.org/support/handbook/appendix/troubleshooting-using-the-health-check/#troubleshooting)(which affects your logged in user only) and let us know if the issue persists?

**Comment by dgmdonna** [comment]
Sorry for the delay, now it looks like that because I restored the DB, otherwise part of the content had disappeared and in the AMP version it assigned a post to a page and there was no way to change that unless I was not editing the DB.

We are in the process of migrating to a new design, so I want to avoid this new event, because we find the proposal of the Story very interesting

**Comment by ernee** [comment]
@dgmdonna thank you for these additional details. I see you have several AMP extensions. I'll look into this further to see if they can be involved.

**Comment by ernee** [comment]
@dgmdonna just a follow up that I have not been able to replicate this issue, so it may be something specific in your environment. We've released the stable version 1.0.0 of the plugin, so feel free to try it (on a test site to be safe). Please don't hesitate to open a topic in our [WordPress.org support forum](https://wordpress.org/support/plugin/web-stories/) if the issue should reoccur. It would be great if we can further troubleshoot to find the source.
