### ISSUE TITLE
Improve Karma tests / documentation

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#3788]
## Feature Description
Currently, the Karma tests require the format of `CUJ:[CUJ description]:[Action description]` as the description. If the description is missing the action description, e.g. just `CUJ: description`, [the tests fail](https://github.com/google/web-stories-wp/pull/3215/checks?check_run_id=970626273#step:7:2058).

If the `CUJ:` is missing as the prefix, the bulk of tests won't be included in the report count.

We should make the system more robust and/or update the documentation to reflect what's required; also add at least some kind of information for the dev in case of leaving in the failure of tests with incorrect format -- to understand the reason.

There are currently some Dashboard tests that are not following the required format and are thus excluded from reporting (search for `'Action: ` to see). These should get updated as well to the new format. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
cc @barklund since you made those changes recently. Perhaps you can elaborate on the reasoning there?
