### ISSUE TITLE
Carousel design broken

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#380]
## Bug Description

There's no spacing anymore between pages in the bottom carousel, and the active state also seems broken.

This does not match the [design on Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=2625%3A86587).

Related: #234

## Screenshots

Actual:

<img width="891" alt="Screenshot 2020-02-24 at 17 34 37" src="https://user-images.githubusercontent.com/841956/75173844-cd707480-572f-11ea-90bc-6014e26a3634.png">

Expected:

<img width="964" alt="Screenshot 2020-02-24 at 18 15 01" src="https://user-images.githubusercontent.com/841956/75174851-9ac77b80-5731-11ea-9e4e-34607ae68ad3.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by merapi** [comment]
Carousel navigation (and design, see arrow and grid view icon clash) is also not aligned with the spec, should we include this work here?

![image](https://user-images.githubusercontent.com/21036224/75245812-c51b4680-57ce-11ea-948f-cf8536821805.png)

**Comment by swissspidy** [comment]
@merapi Navigation behavior is handled by #311 . This issue here is for fixing the design of the carousel—that includes the navigation design.

**Comment by merapi** [comment]
### Regarding the active state:
From my research, it's best not to use `outline` for this (as we currently use), by utilizing `border` we can skip all issues listed below.

Current code (`const Page = styled.button`) is not working on Chrome, Firefox/Safari is fine with that.

If we change it to `const Page = styled.div` it's working everywhere, but we lose some a11y.

If we try to bring back some a11y with `const Page = styled.div.attrs({ role: 'button', tabIndex: 0 })` it breaks in Chrome.  

As per Figma, we should also remove `:hover`.

![image](https://user-images.githubusercontent.com/21036224/75271751-0296c880-57fd-11ea-816e-1d9fd25707c6.png)

I also saw https://github.com/google/web-stories-wp/issues/10 and I'm not sure if we have that functionality described somewhere? probably we will need some state indicating the page being moved. If we use `border` to indicate active state then we can utilize `outline` for that.

That's how it works with `border` and native outline:
https://share.getcloudapp.com/WnuNEPO2

**Comment by barklund** [comment]
> Current code (`const Page = styled.button`) is not working on Chrome, Firefox/Safari is fine with that.
> If we try to bring back some a11y with `const Page = styled.div.attrs({ role: 'button', tabIndex: 0 })` it breaks in Chrome.

How does either approach break in Chrome? Can you push a branch with this?

I think a `<li/>` with a `role="option"` (and the parent then an `<ul/>` with `role="listbox"`) or `tab` (and `tabpanel`) seems semantically sound.

**Comment by merapi** [comment]
> How does either approach break in Chrome? Can you push a branch with this?

`.button` (current code on master) and `.div.attrs` will result in such result in Chrome (only):
(issue occurs when you click on Page thumbnail - it doesn't stay selected, the first part with arrows navigation is ok)
https://share.getcloudapp.com/ApurrK8g

Does it work for you otherwise?

**Comment by barklund** [comment]
> > How does either approach break in Chrome? Can you push a branch with this?
> 
> `.button` (current code on master) and `.div.attrs` will result in such result in Chrome (only):
> (issue occurs when you click on Page thumbnail - it doesn't stay selected, the first part with arrows navigation is ok)

Ah, because an unfocused button has `outline: none` in Chrome always somehow, which overrides the CSS for it. Yes, convert to a `border` as suggested - don't sacrifice semantics for styling.

**Comment by dvoytenko** [comment]
Just wanted to point out that, at least visibly, Figma specifies outline for the selected page thumbnails - it's clearly outside the boundary of the thumbnail. Performance-wise, if we set/unset the border, we will also force relayout each time. Alternative to this would be to always set border and only manipulate it's transparency. This is somewhat of a dangerous path. I usually prefer outlines where outlines are called for.

**Comment by barklund** [comment]
@dvoytenko but when this clashes with semantics, I say we go for border. And button's (or button-like elements) clearly can't use outline in Chrome due to conflicting uses.

We can just toggle the border color between the `bg.v1` used by the canvas background and the active color. That will have very limited performance impact. Would that be an acceptable solution?

**Comment by merapi** [comment]
After more digging:

`@moxystudio/js-keyboard-only-outlines` is inserting this buggy `style` when you click (`focusin`):
```html
<style><br>*:focus {<br>    outline: none !important;<br>}<br>*::-moz-focus-inner {<br>    border: none !important;<br>}</style>
```

but `br`s are not the root cause of cross-browser inconsistency.

It turns out that `pointer-events: none;` on some elements (we have a few) will cause `focusin` to not being fired in Firefox/Safari (so in Chrome it's fired but then it's causing active state bug...). 

So using `outline` is hard in that case, `border` will do the job and for the _active state_, in particular, it sounds like a reasonable choice.

**Comment by merapi** [comment]
> We can just toggle the border color between the `bg.v1` used by the canvas background and the active color. That will have very limited performance impact. Would that be an acceptable solution?

Yep, that is the current solution for `outline` anyways (if `transparent` would cause perf. problems, I think that's not the case here and if we use it, we can forget about accidental de-sync of bg<>border colors).
```js
outline: ${PAGE_THUMB_OUTLINE}px solid
    ${({ isActive, theme }) =>
      isActive ? theme.colors.selection : theme.colors.bg.v1};
```

**Comment by dvoytenko** [comment]
@barklund @merapi if we see `border` semantically more appropriate here - then certainly. And, yes, we should proceed with the transparent/selection border color in that case. However, if it's an issue with the `keyboard-only-outlines` - I'd rather we disabled it for now. We do use `pointer-events:none` heavily and it'd probably be only more so. So if there's some inherent incompatibility, we'll run into it again somewhere.

**Comment by swissspidy** [comment]
Sounds like we'd want to keep an eye on `@moxystudio/js-keyboard-only-outlines`. I'll create an issue to track this so it's not forgotten.

For now, let's go with the `border` and `listbox` option.
