### ISSUE TITLE
Prop types errors surrounding masks

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#381]
## Bug Description

The following prop types errors are currently appearing in the editor but shouldn't. Either the prop types were simply not accurate, or they are symptom of an actual issue somewhere.

Those should be investigated and fixed.

![Screenshot 2020-02-24 at 21 28 11](https://user-images.githubusercontent.com/841956/75188720-f2bfab80-574c-11ea-8f46-6a791a753a5d.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Still happens

**Comment by miina** [comment]
@dvoytenko Curious why are the frame wrappers rendered even if `Frame` does not exist?
https://github.com/google/web-stories-wp/blob/f272e875c9e4fff8ea4632cebad5858ae2ca2217/assets/src/edit-story/components/canvas/frameElement.js#L104-L114

**Comment by dvoytenko** [comment]
@miina, `Frame === null` doesn't really mean "Frame doesn't exist". It's more of a "Frame filling is not needed, but frame itself always exists". You can think of it as a border: even if there's no text, the border might still be useful.

**Comment by dvoytenko** [comment]
Basically, it means we were simply overprotective initially when setting mask proptypes. We just need to relax.
