### ISSUE TITLE
Dashboard Settings: Successful Updates UI

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#3810]
## Feature Description
When a user updates a publisher logo or their Google Analytics ID as an admin in the Dashboard on the Settings page we need to show success of that update. Currently there's no success messaging in the Dashboard to piggyback off of. We do have a toaster wired up for error handling, do we want to implement success toasts as well?  

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

- UX for success of updates added to ticket, then front end implementation 

## Implementation Brief

- TBD

**Comment by BrittanyIRL** [comment]
I have success toasts wired up (see '[copy preview url' in the story context menu](https://github.com/google/web-stories-wp/issues/4101))  - so I think just some verbiage here for what a success toast should say for successfully updating your google analytics ID is needed. Something like: 

title: Google Analytics ID updated 
body: Stories will all now use UA-XXXXXX-XX as their GA ID.

**Comment by swissspidy** [comment]
There could be a simple "Settings saved." snackbar message.

**Comment by BrittanyIRL** [comment]
> There could be a simple "Settings saved." snackbar message. 

wow this is from almost year ago. Let's just do that and get this closed before we hit a full year from creation. 🥵

**Comment by BrittanyIRL** [comment]
@csossi  there's QA instructions in the PR ✨

**Comment by csossi** [comment]
Verified in QA
