### ISSUE TITLE
Dashboard Settings: Set Default Publisher Logo

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#3811]
## Feature Description

When an admin is on their Settings page in the dashboard, they should be able to identify and edit which of their publisher logos is the default. 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

- UX on how to display the above criteria 
- Update connection to settings API to designate change in default logo

## Implementation Brief

- TBD based on UX

**Comment by samitron7** [comment]
@BrittanyIRL Rules for publishers logo [here](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Stable-Release?node-id=218%3A118). Let me know if you have an additional questions.

**Comment by bmattb** [comment]
moved to Sprint backlog

**Comment by BrittanyIRL** [comment]
this is between a 3 and 5 point ticket depending on if we want to include testing so i assigned it 5 points to be on the conservative end.

**Comment by csossi** [comment]
Verified in QA

**Comment by o-fernandez** [comment]
Looks great!
