### ISSUE TITLE
User is unable to paste to upload a video into editor on Chrome / MacOS

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#3826]
## Bug Description
As noted by @csossi  in https://github.com/google/web-stories-wp/issues/3348 when the user on Chrome/Mac attempts to paste a video into the editor they are presented with the name of the video file instead of the video.

![68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3565613038356534373034653732633061393963363939372f31343162316562312d346133662d346433382d386439652d613762653932333864653661](https://user-images.githubusercontent.com/58738530/89947939-3c189000-dbf3-11ea-84b2-cade8cb72b79.png)

## Expected Behaviour

The asset should be presented in the editor and added to their media library 

## Additional Context

- Plugin Version:
- Operating System: Mac OSX
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Can't reproduce this right now
