### ISSUE TITLE
Poster fallback image is not the right size

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#3839]
## Bug Description

As noted in https://github.com/google/web-stories-wp/issues/3671 :

> When users don't add a story cover image (poster image), we use the following image as a fallback:
>
>https://github.com/google/web-stories-wp/blob/7fc1c9af6a1e43c0edc2ec57a45f82eccb1d8d08/assets/images/fallback-poster.jpg
>
>This is basically a last resort to ensure the image meets the poster requirements.
>
> However, the image is too small, and doesn't meet the requirements anymore. Search requires at least 1200px wide images, and AMP changed its requirements too, see #3297. So we'd need to update that poster.

## Expected Behaviour

_Current_ image size: 696x928

**Correct** images ize: 640px853px

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
I just looked at the placeholder image and has the text in English 'Image Not Yet Supplied'. This is a weird for a number of reasons. 

- In english not translatable. 
- Capital letters all over the place. 
- Not centered. 

Maybe we could use something more like this from [placeholder.com](https://placeholder.com/) 

<img src="https://via.placeholder.com/150" />

It doesn't contain english text and is pretty generic. 

Or something like this 

![placeholder-test](https://user-images.githubusercontent.com/237508/90246627-ecbda400-de2c-11ea-8bfb-b4307bfb975d.png)

I think we should use this as a chance to improve the placeholder.

**Comment by swissspidy** [comment]
@spacedmonkey Agreed! I like the second example

There's a neat Material icon we could use for that.

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="black" width="48px" height="48px"><path d="M0 0h24v24H0z" fill="none"/><path d="M21 19V5c0-1.1-.9-2-2-2H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2zM8.5 13.5l2.5 3.01L14.5 12l4.5 6H5l3.5-4.5z"/></svg>
```

That in the center of a grey 640x853px image would work well I think.

**Comment by spacedmonkey** [comment]
I am guessing that is the [image](https://material.io/resources/icons/?icon=image&style=baseline) icon.

That looks like this. 

![baseline_image_black_18dp](https://user-images.githubusercontent.com/237508/90247954-9140e580-de2f-11ea-9ec5-e9045083798a.png)

We will have to create it as PNG as it is not recommended to use an SVG. But should be pretty simple to put together.

**Comment by spacedmonkey** [comment]
Should we confirm with @samitron7 before going ahead.

**Comment by swissspidy** [comment]
No need really, this poster is not really user-facing 99% of the time, it's just to pass validation.

And yes, it needs to be a PNG, I added the SVG merely so it can be quickly stretched for editing. The default png on the Material site is too small.

**Comment by spacedmonkey** [comment]
<img width="320" alt="placeholder" src="https://user-images.githubusercontent.com/237508/90251955-8b9ace00-de36-11ea-8670-5dc31fc4ba61.png">

I mocked this up using material design colors. Let me know if you are happy with this @swissspidy I will update the image.

**Comment by swissspidy** [comment]
@spacedmonkey Sweet! Works for me!
