### ISSUE TITLE
Get the Web Stories plugin listed on the "Block enabled" list in the Wordpress.org plugin repository

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#3840]
## Task Description

 In order to support discovery of the Web Stories plugin it is advisable to have our plugin added to the list of block enabled plugins on the plugin homepage - https://wordpress.org/plugins/
As per the https://make.wordpress.org/plugins/2018/12/07/blocks-plugins-and-you/  post :

> If you’ve written a plugin that introduces or improves blocks, or know of a plugin that does, email us at plugins@wordpress.org. Note that these must be plugins with their block-enabled version currently available in the Plugin Directory.
>
> We’re featuring these plugins in a new “Blocks-Enabled Plugins” section in the directory, as well as in a new section on the WordPress Plugins homepage.

**Comment by swissspidy** [comment]
Related: #1270

**Comment by swissspidy** [comment]
email sent
