### ISSUE TITLE
Add message when Autosave exists

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#3841]
## Feature Description

The default editor in WordPress has this mechanism which we want to implement as well.

1. Edit post
1. Make some changes, triggering autosave
1. Close window
1. Edit post again
1. See message like this: "There is an autosave of this post that is more recent than the version below. View autosave."

For the prototype implementation, let's create a simple modal/dialog.

Need to pass autosave information to the editor in `get_editor_settings()`. Prior art:

https://github.com/WordPress/wordpress-develop/blob/9b04bb68f1ec37c38d79372ba93929bf5b96e522/src/wp-admin/edit-form-blocks.php#L216-L225

## Additional Context

Screenshot:

![68747470733a2f2f636c2e6c792f325a335432523273316131702f496d616765253230323031382d30312d30372532306174253230322e31332e3034253230504d2e706e67 (1)](https://user-images.githubusercontent.com/841956/90044178-90903e00-dccd-11ea-9d70-444e9a414dc7.png)

Original Gutenberg implementation: https://github.com/WordPress/gutenberg/pull/4218

**Comment by timarney** [comment]
> For the prototype implementation, let's create a simple modal/dialog.

@swissspidy --- would this be like the font check dialog?  Check for link when the editor loads - pop the modal if it does which links to the autosave.

**Comment by swissspidy** [comment]
Yeah, conceptually pretty much.

Though this can live in `story-editor` package as that's where the autosaving is happening.
