### ISSUE TITLE
Down arrow on categories container should expand container

### ISSUE THREAD

**Issue by cvolzke4** [GoogleForCreators/web-stories-wp#3859]
## Task Description

Arrow based navigation is enabled for the category pill container in https://github.com/google/web-stories-wp/pull/3781. As an improvement, pressing the 'down' arrow should expand the categories instead of scrolling through 1 single line of categories pills.

**Comment by diegovar** [comment]
Also potentially focusing the categories dropdown button and pressing enter should expand it and contract it.

**Comment by cvolzke4** [comment]
Duplicate of #4002
