### ISSUE TITLE
Font picker: UnifakturCook font preview not loading

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#3865]
## Bug Description
Follow-up for #3215 (needs that to be merged before looking into this)
The font preview for UnifakturCook font specifically is not loading.

## Steps to Reproduce
1. Open the new font picker.
2. Type in `Unifaktur`.
3. See the font preview not being loaded.

See console errors, too

## Screenshots
<img width="1098" alt="Screenshot 2020-08-12 at 21 44 47" src="https://user-images.githubusercontent.com/3294597/90055219-4e6ef880-dcdd-11ea-8957-5c890286db77.png">

<img width="298" alt="Screenshot 2020-08-12 at 21 50 32" src="https://user-images.githubusercontent.com/3294597/90055398-94c45780-dcdd-11ea-95bb-cf73be0830d4.png">

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
The [UnifrakturCook](https://fonts.google.com/specimen/UnifrakturCook) font does not have a regular / 400 font weight, but only a 700 one.

So https://fonts.googleapis.com/css?family=UnifrakturCook&subset=menu&display=swap rightfully returns  a 404, but https://fonts.googleapis.com/css?family=UnifrakturCook:bold&subset=menu&display=swap works.

Given that we have all the information about fonts and available font weights, it would be trivial to  just load the bold variant in this case (or just the first available font weight).

At first glance it looks like the `ensureMenuFontsLoaded` effect in `FontProvider` could just call `getFontWeight` for all fonts and then process that.

**Comment by swissspidy** [comment]
Too big of an edge case, better fixed on the Google Fonts side
