### ISSUE TITLE
Use new render class in Admin.php

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#3868]
## Feature Description

Follow up ticket #3733 ( #3325 ). 

Use the new `Embed` class in Admin.php to generate markup for embed block. 

Reapply these changes https://github.com/google/web-stories-wp/commit/a1ccdc7a475b514dc2dcab8ab9af5df8963645b8 and add deprecations. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
So, I wasn't able to get the block deprecation in #3879 working.

At the same time, we also need to move #3581 forward, which will result in  block deprecation as well, and will revert some of the changes here, particularly the `margin:0` part.

Thus I am 

1. Converting #3879 to draft again
1. Closing this in favor of #3581
