### ISSUE TITLE
Add since annotation to all doc blocks

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#3873]
## Feature Description

With stable around the corner, I think it is time to add `@since` notation to all PHP docblocks. 

## Additional Context

There are currently 203 functions / methods in includes
There are currently 227 functions / methods in tests/phpunits

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
This should only cover `includes`, not `tests`

**Comment by spacedmonkey** [comment]
> This should only cover includes, not tests

There is value in adding since on tests, so know when the test was added. A test maybe added later.

**Comment by swissspidy** [comment]
The maintenance burden for adding `@since` to tests is bigger than the value it adds.
