### ISSUE TITLE
TypeError: Object.fromEntries is not a function. (In 'Object.fromEntries(Object.entries(t).map(([e,t])=>[a(e),i(t,n)]))', 'Object.fromEntries' is undefined)

### ISSUE THREAD

**Issue by reimongela** [GoogleForCreators/web-stories-wp#3874]
Hi all,
I'm getting the below error message on Google Web Stories.... any leads on solving this will be greatly appreciated.
Reimongela

```
TypeError: Object.fromEntries is not a function. (In 'Object.fromEntries(Object.entries(t).map(([e,t])=>[a(e),i(t,n)]))', 'Object.fromEntries' is undefined)
    in kH
    in Unknown
    in Dm
    in Unknown
    in OH
    in TH
    in div
    in layout__Area
    in section
    in layout__Editor
    in RH
    in Unknown
    in RN
    in Unknown
    in Ce
    in Unknown
    in RL
    in Unknown
    in sT
    in Unknown
    in oM
    in Unknown
    in bs
    in Unknown
    in xA
    in Unknown
    in Qc
    in Unknown
    in $l
    in QN
    in Se
    in te
    in NH
    in v
```

**Comment by reimongela** [comment]
Hi all,
I'm getting the below error message on Google Web Stories.... any leads on solving this will be greatly appreciated.
Reimongela

TypeError: Object.fromEntries is not a function. (In 'Object.fromEntries(Object.entries(t).map(([e,t])=>[a(e),i(t,n)]))', 'Object.fromEntries' is undefined)
in kH
in Unknown
in Dm
in Unknown
in OH
in TH
in div
in layout__Area
in section
in layout__Editor
in RH
in Unknown
in RN
in Unknown
in Ce
in Unknown
in RL
in Unknown
in sT
in Unknown
in oM
in Unknown
in bs
in Unknown
in xA
in Unknown
in Qc
in Unknown
in $l
in QN
in Se
in te
in NH
in v

**Comment by reimongela** [comment]
Hi all,
I'm getting the below error message on Google Web Stories.... any leads on solving this will be greatly appreciated.
Reimongela

TypeError: Object.fromEntries is not a function. (In 'Object.fromEntries(Object.entries(t).map(([e,t])=>[a(e),i(t,n)]))', 'Object.fromEntries' is undefined)
in kH
in Unknown
in Dm
in Unknown
in OH
in TH
in div
in layout__Area
in section
in layout__Editor
in RH
in Unknown
in RN
in Unknown
in Ce
in Unknown
in RL
in Unknown
in sT
in Unknown
in oM
in Unknown
in bs
in Unknown
in xA
in Unknown
in Qc
in Unknown
in $l
in QN
in Se
in te
in NH
in v

**Comment by reimongela** [comment]
Hi all,
I'm getting the below error message on Google Web Stories.... any leads on solving this will be greatly appreciated.
Reimongela

TypeError: Object.fromEntries is not a function. (In 'Object.fromEntries(Object.entries(t).map(([e,t])=>[a(e),i(t,n)]))', 'Object.fromEntries' is undefined)
in kH
in Unknown
in Dm
in Unknown
in OH
in TH
in div
in layout__Area
in section
in layout__Editor
in RH
in Unknown
in RN
in Unknown
in Ce
in Unknown
in RL
in Unknown
in sT
in Unknown
in oM
in Unknown
in bs
in Unknown
in xA
in Unknown
in Qc
in Unknown
in $l
in QN
in Se
in te
in NH
in v

**Comment by swissspidy** [comment]
Hey @reimongela, which browser are you currently using?

**Comment by reimongela** [comment]
Safari on MacBook

**Comment by swissspidy** [comment]
@reimongela Which Safari version? You can check this by clicking on "Safari" in the menu bar:

<img width="487" alt="Screenshot 2020-08-13 at 17 00 31" src="https://user-images.githubusercontent.com/841956/90151004-88480980-dd86-11ea-9171-7d9dc671e0a6.png">

**Comment by reimongela** [comment]
Safari 11.1.2
Chrome 84.0.4147.125

**Comment by swissspidy** [comment]
Thanks for the additional info!

It appears that the Web Stories editor uses certain features that are not supported by Safari 11.

We currently support and test with the last 2 versions of all major browsers, which for Safari means versions 12 and 13 — so Safari 11 is too old. Is it possible for you to update Safari?

Unfortunately the lack of support for Safari 11 is not really clear from the error message you're seeing, so we are working on improving that in #1369.

Meanwhile we'll see if and how we can improve compatibility with Safari 11 nonetheless, even though we don't officially support it.

**Comment by reimongela** [comment]
Thanks.

What about Chrome 84.0.4147.125?

**Comment by swissspidy** [comment]
The editor should work normally under Chrome 84. If it isn't that might be a bug in the plugin or a conflict with something on your site.

**Comment by reimongela** [comment]
Hi does the plugin have a history of conflicts with which other plugins?

**Comment by ernee** [comment]
Hi @reimongela! Since the plugin is in beta for just over a month now, we're still learning more about how it interacts with other plugins and working on addressing newly found issues (feel free to watch this repository to get the most up to date info). 

Does the plugin work in Chrome 84 for you? If not, feel free to provide your [Site Health Information]( https://i.imgur.com/Rtkmsba.png) so we can review your setup for anything that might be conflicting.

**Comment by ernee** [comment]
@reimongela just following up on your issue. Does the error still occur with the most recent version of Chrome and of the plugin version 1.0.0-rc.1?

**Comment by reimongela** [comment]
Hello there. So far so good, no issues at all, working perfectly fine thank you.Rei
    On Thursday, September 17, 2020, 8:51:47 PM GMT+3, Renee Johnson <notifications@github.com> wrote:  
 
 


@reimongela just following up on your issue. Does the error still occur with the most recent version of Chrome and of the plugin version 1.0.0-rc.1?
