### ISSUE TITLE
Add logic for ensuring the fonts in the curated list actually exist

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#3880]
## Feature Description
The font names can change and the curated list is currently based on the static names. This can cause the changed fonts not to appear in the font picker's curated list.

For example, meanwhile, the font "Muli" has changed to "Mulish" which causes it not to appear in the curated list.

Perhaps there's a way to check if the fonts actually exist and report a failure if not.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
> For example, meanwhile, the font "Muli" has changed to "Mulish" which causes it not to appear in the curated list.

Was the font actually renamed or was it just a typo in the original list? 🤔 

> Perhaps there's a way to check if the fonts actually exist and report a failure if not.

That would be quite simple do to in a JS test I think

**Comment by miina** [comment]
> Was the font actually renamed or was it just a typo in the original list? 🤔

It was [actually renamed](https://github.com/google/fonts/pull/2504).

**Comment by swissspidy** [comment]
Ha, it was actually renamed! https://github.com/google/fonts/issues/2563#issuecomment-662367260

**Comment by swissspidy** [comment]
Jinx! 😅
