### ISSUE TITLE
TypeError: a is not a function

### ISSUE THREAD

**Issue by reimongela** [GoogleForCreators/web-stories-wp#3884]
```
TypeError: a is not a function
    in RL
    in Unknown
    in sT
    in Unknown
    in oM
    in Unknown
    in bs
    in Unknown
    in xA
    in Unknown
    in Qc
    in Unknown
    in $l
    in QN
    in Se
    in te
    in NH
    in v
```

**Comment by reimongela** [comment]
On Google chrome...

**Comment by LuckynaSan** [comment]
@reimongela What version of Chrome are you using?

**Comment by LuckynaSan** [comment]
Hi there, I am closing this out as a duplicate issue of #3874. Please provide a response there. Thank you.

**Comment by reimongela** [comment]
Hi.Please see the attached as this wasn't resolved.Thanks and regards,

    On Thursday, August 20, 2020, 6:55:34 PM GMT+3, LuckynaSan <notifications@github.com> wrote:  
 
 


Hi there, I am closing this out as a duplicate issue of #3874. Please provide a response there. Thank you.

**Comment by swissspidy** [comment]
@reimongela There is no attachment. Try uploading attachments via the GitHub user interface.

We closed this ticket as a duplicate of your other report at #3874. If you do think the two issues are not related, please let us know and provide as many details as possible.

Also, please try the updated beta 2 version to see if the issue has been resolved already.

**Comment by reimongela** [comment]
Thanks for the reply. Kindly send me the link to beta 2 version.Regards

**Comment by swissspidy** [comment]
You can download it from https://google.github.io/web-stories-wp/beta/ or update from right within your WordPress admin
