### ISSUE TITLE
Search won't be disabled on category selection

### ISSUE THREAD

**Issue by winterDroid** [GoogleForCreators/web-stories-wp#3898]
## Bug Description

When selecting a category, search is still enabled. 

## Expected Behaviour

@samitron7 what do you think? At least search should get disabled.

**Comment by samitron7** [comment]
@winterDroid Can you provide a little context. I'm a little confuse with the title of the ticket and the comment for the expected behavior. What is the problem and what are you recommending?

**Comment by winterDroid** [comment]
@samitron7 when we are selecting a category, the search bar is still enabled. So users can enter a search term, but on search, the previously selected category will be deselected since we don't support search in category. It looks even more confusing when the user had a search term entered and selects a category since then search term is present and a category is selected, but just the images from the categories are displayed. So I at least would suggest disabling the search bar when a category is selected.
