### ISSUE TITLE
Make "No media found" match the mocks (style and wording)

### ISSUE THREAD

**Issue by winterDroid** [GoogleForCreators/web-stories-wp#3899]
## Bug Description

There is a big padding above the "No media found" empty result search screen.

## Screenshots

<img width="393" alt="download (1)" src="https://user-images.githubusercontent.com/841956/90230027-369c8f00-de19-11ea-98f8-b3d3c728f4cd.png">

**Comment by swissspidy** [comment]
@winterDroid FYI uploaded the screenshot directly to the issue because your URL was not public :-)

**Comment by bmattb** [comment]
If this bug is to be addressed in this sprint it should be moved to the Sprint backlog column in ZH and estimated. If not, the tag for this sprint should not be added. Thanks!

**Comment by diegovar** [comment]
To fix this I believe we have to hide the media subheading if there's no media displayed yet. We should probably display the media subheading if the search has no results.
