### ISSUE TITLE
Video in Media Library

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#39]
## Feature description

Find elegant way to display video in the media gallery when you need it.

**[Epic: Media upload and management](https://docs.google.com/document/d/1aZH_TI_be2t5Ywyqx4jcPTPdhFGEt7xh-uLzBp2AV4A/edit#heading=h.2d83f6r6hu5x)**
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. Show poster image
2. List Duration
2. Play icon (is just autoplay on hover)
3. Autoplay on hover (muted?) See #26 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jauyong** [comment]
@pbakaus @samitron7 
RE:
> If you hover over a video, play the video and display the button

Should the video be muted when played or not? 
Will the video also autoplay when navigating via keyboard?

**Comment by pbakaus** [comment]
@jauyong very good question. I'll discuss with Sam..I'm leaning towards playing it with sound (as that is the most realistic), but this could get annoying very quickly. We might need to have a global "mute" button for the global editor UI.

**Comment by spacedmonkey** [comment]
As discovered in https://github.com/google/web-stories-wp/issues/434#issuecomment-593891764 , WP does store the duration of videos in post meta. So this can displayed without issue.
