### ISSUE TITLE
Accessibility tab navigation causes Media Pane move

### ISSUE THREAD

**Issue by winterDroid** [GoogleForCreators/web-stories-wp#3900]
## Bug Description

When navigating with tab presses from the media pane to the canvas and back (shift + tab), the media pane will move up.

## Screenshots

<img width="395" alt="db355fa5-90d0-4737-a0f4-fe87fa575b40" src="https://user-images.githubusercontent.com/841956/90230840-7152f700-de1a-11ea-84de-5bb9921ee0ee.png">

**Comment by swissspidy** [comment]
Again, no googleplex URLs please :-)

**Comment by winterDroid** [comment]
I tried multiple times but it seems I can't reproduce this anymore. Will close.
