### ISSUE TITLE
Scroll velocity not reset after more media items are loaded

### ISSUE THREAD

**Issue by winterDroid** [GoogleForCreators/web-stories-wp#3901]
## Bug Description

Once a new page is loaded, the list scrolls a bit further.

## Expected Behaviour

Should stay at the current position.

## Steps to Reproduce

Fast fling to bottom of media list

## Screenshots

![7c17004f-3f68-4cdc-8096-af90481c5d70](https://user-images.githubusercontent.com/841956/90230147-5df35c00-de19-11ea-9a9c-5480e1def229.png)

## Additional Context

Used a touchpad on Mac in Chrome

**Comment by ezxyz** [comment]
Based on discussion: Time box this issue if its too complicated just don't fix it.
