### ISSUE TITLE
Tweak visibility delay of the loading indicator

### ISSUE THREAD

**Issue by winterDroid** [GoogleForCreators/web-stories-wp#3902]
## Feature Description

Currently one does rarely see the loading indicator. So when scrolled fast to the bottom, one does not see new results but also no loading indicator.

**Comment by dreamofabear** [comment]
I only see it in 3G emulation. It's a label that says "Loading..." at the bottom of the media picker.

**Comment by BrittanyIRL** [comment]
![Screen Shot 2021-08-30 at 1 56 41 PM](https://user-images.githubusercontent.com/10720454/131404470-8d61a990-31b3-4039-9d57-e483cb02044d.png)

From Will's comment I'm thinking that the loading section that was referred to here is the media panel (re `media picker`) - this looks fine to me. Tested in fast 3g. The placeholder images make sense as the page is loading and having the loading message overlaid as it is prevents content shift. 

I'm going to close this, if other loading components need tweaking we can create new tickets for them specifying the section.
