### ISSUE TITLE
More appropriate label than "Trending" for search results

### ISSUE THREAD

**Issue by winterDroid** [GoogleForCreators/web-stories-wp#3903]
## Feature Description

Right now we show "Trending" above the media list when not searched at all and when performed a search. For a selected category we show its name. It might be confusing to the user to show "Trending" also for search results.

Also, when a search is made we should show something like `Results for "cat"`

**Comment by BrittanyIRL** [comment]
Anyone have a nice synonym we could pop in here and move this ticket out? 
@o-fernandez ? 

My 2 cents is `Popular`
![Screen Shot 2021-07-06 at 11 17 39 AM](https://user-images.githubusercontent.com/10720454/124648208-d73dd800-de4b-11eb-8048-45d4aafe5721.png)

**Comment by swissspidy** [comment]
If I understand the ticket correctly, this is not about replacing "Trending" with "Popular" or so in general.
It is about not showing "Trending" when doing a search.

So for search we could just show "Search Results" as the label.

Not sure we need a `Results for "cat"` text there.

**Comment by BrittanyIRL** [comment]
ah yeah i totally read that differently. Thanks for expanding on that, Pascal!

**Comment by BrittanyIRL** [comment]
@agingoldseco  are you cool with just a copy change here when there's a search? 
Something like this? 
![Screen Shot 2021-11-03 at 2 05 34 PM](https://user-images.githubusercontent.com/10720454/140192830-e5a686b2-aee0-48d2-b8ea-392d7a3a2e3e.png)

(where the 'search results' copy replaces the 'trending' copy when there's a search present)

**Comment by agingoldseco** [comment]
Yes, definitely okay with this! Think it makes more sense.

**Comment by BrittanyIRL** [comment]
(Re acceptance criteria - let's also make sure a new test is present to verify the update)

**Comment by csossi** [comment]
Verified in QA
