### ISSUE TITLE
Image dragged from computer on canvas does not have sizes

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#3905]
## Bug Description

When I dragged an image from my computer to the canvas, and later saved the story, no `srcset` attribute was added. Seems like we need to call `updateElementsByResourceId()` or similar after upload to ensure the dropped element gets the proper `srcset` attribute?

This is a follow-up to #3249. The issue was first reported at #3526.

## Steps to Reproduce

Note: depends on #3526 being merged.

1. Drag an image from the computer directly onto the canvas
1. Wait until upload has finished (see progress bar in media library)
1. Save story.
1. Preview story on frontend.
1. Look for an `srcset` attribute on the image.

On the contrary, if you then insert the image via the media library, the sizes and `srcset` will be there.

Note: also test with copy/paste

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by diegovar** [comment]
I think what's going on is that the resource doesn't seem to have any `sizes`. No `sizes`, no srcset, because the srcset is simply calculated at rendering time and is not stored in the resource at all.

From looking at getResourceFromLocalFile, it seems like it doesn't set the `sizes` at all. Is that intentional?

**Comment by swissspidy** [comment]
> From looking at `getResourceFromLocalFile`, it seems like it doesn't set the sizes at all. Is that intentional?

A local image is just a blob and simply can't have multiple sizes yet, no? Sizes get generated once the image has successfully uploaded. So my thought was that as soon as the upload is finished, the image / the image resource gets updated with the correct sizes information.
