### ISSUE TITLE
Drag Icon while Dragging the Image

### ISSUE THREAD

**Issue by mechiragjain** [GoogleForCreators/web-stories-wp#3908]
## Bug Description

When we add any image from Media Library or Local System then we get option to drag the image on the story. That drag option is enabled or not, we can't get any idea.

## Expected Behaviour

So to make it clear, the cursor should be changed to "Drag Icon". It will look more enhanced when the cursor changed when we hover over external images.
Drag Icon Cursor Image Example :
![Drag Icon Cursor](https://static.thenounproject.com/png/581820-200.png)

## Screenshots
See this video
[![Watch the video](https://res.cloudinary.com/chiragjain/image/upload/v1597405786/freesnippingtool.com_capture_20200814171926_djiuxz.png)](https://res.cloudinary.com/chiragjain/video/upload/v1597405595/Google_Web_Stories_Cursor_yrtl19.mp4)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by LuckynaSan** [comment]
Hi there, thank you for your suggestion about the drag icon! We will relay this to the team and provide you with any updates.
