### ISSUE TITLE
CUJ Testing for Beta v2 - Creator Can Add Image/Video to Page

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#3923]
## Feature Description

In preparation for our Beta2 release please review and confirm the functionality detailed in https://github.com/google/web-stories-wp/issues/1556 

- [x] Upload image/video via upload button in media tab, and then add it from the media tab to canvas.
- [x]  Upload image/video via the original (separate) WordPress media gallery page, then open story editor and add it from the media tab to the canvas.
- [x]  Search for media (through entering a keyword or by browsing) already in the media gallery and add it to the canvas
- [x]  Filter media by type (image, video, all)
- [x]  Drag image/video from desktop to canvas
- [x]  Paste image/video to upload (only works on Mac OS)
- [x]  Drag media from media library to edge to place as background
- [x]  Add image/video on page then click "Set as background" button

**Comment by csossi** [comment]
Created #4023

**Comment by csossi** [comment]
Created #4024

**Comment by LuckynaSan** [comment]
Created https://github.com/google/web-stories-wp/issues/4064

**Comment by csossi** [comment]
Created https://github.com/google/web-stories-wp/issues/4109
