### ISSUE TITLE
CUJ Testing for Beta v2 - Creator can manipulate an image/video on canvas (in both fg and bg mode)

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#3924]
## Feature Description

In preparation for Beta 2 release we would like to have the functionality described in https://github.com/google/web-stories-wp/issues/1585 confirmed.

- [x] Enter edit mode to change the crop factor of a video/image within its mask, allowing both zoom and repositioning.
- [x]  Rest image to its original state
- [x]  Set different poster image for the video from the auto-generated one
- [x]  Fill in alt tag for accessibility/indexing (image only)
- [x]  Fill in title tag for accessibility/indexing (video only)
- [x]  Flip an image/video vertically or horizontally
- [x]  Set video to looping
- [ ]  Trim video (set different start and end point)
- [ ]  Add a drop shadow
- [ ]  Change border radius
- [ ]  Can mute a video
- [ ]  Apply a solid, linear or vignette overlay
- [ ]  Set overlay color(s) & other gradient properties

**Comment by LuckynaSan** [comment]
Tested on macOS Mojave 13-inch v. 10.14.6 / Safari v. 13.1.2 and found no issues.

**Comment by csossi** [comment]
Verified in QA
