### ISSUE TITLE
CUJ Testing for Beta v2 - Creator can Drag and Drop an Image/Video into an Available Drop Target

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#3926]
## Feature Description

In preparation for the Beta 2 release we would like to have validation and confirmation of the CUJ functionality detailed in 
https://github.com/google/web-stories-wp/issues/1588

Basic shapes are drop targets
 Media elements are drop targets

**Comment by csossi** [comment]
Verified in PR#4012
