### ISSUE TITLE
CUJ Testing for Beta v2 - Creator can Set Page Color

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#3927]
## Feature Description

In preparation for the Beta 2 release we would like to have validation and confirmation of the CUJ functionality detailed in 
https://github.com/google/web-stories-wp/issues/1622

- [x] Open colorpicker in design panel when page is selected

**Comment by LuckynaSan** [comment]
Tested on macOS Mojave 13-inch v. 10.14.6 / Safari v. 13.1.2 and found no issues.

**Comment by csossi** [comment]
Verified in QA
