### ISSUE TITLE
CUJ Testing for Beta v2 - Creator can Add and Delete a Page

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#3928]
## Feature Description

In preparation for the Beta 2 release we would like to have validation and confirmation of the CUJ functionality detailed in 
https://github.com/google/web-stories-wp/issues/1623

- [x] Add new page by clicking on the + button
- [ ]  Add new page by pressing "N" key (when not in text edit mode)
- [x]  Click "duplicate page" button
- [x]  Select the background/page and copy it to clipboard, then paste
- [x]  Click "delete page" button (trashcan icon)

**Comment by LuckynaSan** [comment]
Tested on macOS Mojave 13-inch v. 10.14.6 / Safari v. 13.1.2 and found no issues.

**Comment by csossi** [comment]
Verified in QA
