### ISSUE TITLE
CUJ Testing for Beta v2 - Creator can View Page Thumbnail

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#3929]
## Feature Description
In preparation for the Beta 2 release we would like to have validation and confirmation of the CUJ functionality detailed in 
https://github.com/google/web-stories-wp/issues/1624

- [x] View page thumbnails
- [x]  Understand what current page they are on
- [x]  Switch quickly between pages
- [x]  Reorder pages directly from thumb carousel
- [x]  Delete page
- [x]  View thumbnail in grid view

**Comment by csossi** [comment]
Verified in QA

**Comment by LuckynaSan** [comment]
Tested on macOS Mojave 13-inch v. 10.14.6 / Safari v. 13.1.2 and found no issues.
