### ISSUE TITLE
CUJ Testing for Beta v2 - Creator can Work in Safe Mode

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#3930]
## Feature Description

In preparation for the Beta 2 release we would like to have validation and confirmation of the CUJ functionality detailed in 
https://github.com/google/web-stories-wp/issues/1625

- [x] Toggle safe mode ON/OFF
- [ ]  Get a warning when an element is placed too far into the bleed

**Comment by csossi** [comment]
Verified in QA

("warning" is out-of-scope for Beta 2 release)
