### ISSUE TITLE
CUJ Testing for Beta v2 - Creator can Add a Page Attachment

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#3931]
## Feature Description

In preparation for the Beta 2 release we would like to have validation and confirmation of the CUJ functionality detailed in 
https://github.com/google/web-stories-wp/issues/1626

 

- [ ] Add page attachment
- [ ]  Delete page attachment

**Comment by csossi** [comment]
Not in scope for Beta 2 release
