### ISSUE TITLE
CUJ Testing for Beta v2 - Creator can Add and Write Text 

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#3932]
## Feature Description
In preparation for the Beta 2 release we would like to have validation and confirmation of the CUJ functionality detailed in 
https://github.com/google/web-stories-wp/issues/1494

- [x] Add new text box by click on the + button
- [x]  Add new text box in the preset section
- [x]  Delete textbox (use del or backspace keyboard shortcut)
- [x]  Write/edit text
- [x]  select an individual word to edit
- [x]  Select all text inside a textbox

**Comment by LuckynaSan** [comment]
Tested on macOS Mojave 13-inch v. 10.14.6 / Safari v. 13.1.2 and found no issues.

**Comment by csossi** [comment]
Verified in QA
