### ISSUE TITLE
CUJ Testing for Beta v2 - Creator Can Style Text

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#3933]
## Feature Description

In preparation for the Beta 2 release we would like to have validation and confirmation of the CUJ functionality detailed in 
https://github.com/google/web-stories-wp/issues/1509

- [x] Change typeface
- [x]  Select weight
- [x]  Set font size by entering input value
- [ ]  Set font size by using a slider
- [x]  Set line height
- [x]  Set kerning
- [x]  Apply B
- [x]  Apply U
- [x]  Apply I
- [ ]  Apply strikethrough
- [x]  Set text color (solid only)
- [x]  Set opacity

**Comment by csossi** [comment]
Verified in QA

Slider and strikethrough are out-of-scope for Beta 2
