### ISSUE TITLE
CUJ Testing for Beta v2 - Creator can Apply or Save a Color from/to Their Preset Library

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#3939]
## Feature Description

In preparation for the Beta 2 release we would like to have validation and confirmation of the CUJ functionality detailed in 
https://github.com/google/web-stories-wp/issues/1629

- [x] Click to apply a color to an element
- [x]  Save a color to presets
- [x]  Delete color preset

**Comment by csossi** [comment]
Verified in QA
