### ISSUE TITLE
CUJ Testing for Beta v2 - Creator can Apply or Save Text Style from/to Their Preset Library

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#3940]
## Feature Description

In preparation for the Beta 2 release we would like to have validation and confirmation of the CUJ functionality detailed in 
https://github.com/google/web-stories-wp/issues/1630

- [ ] Click to apply a style to a text element
- [ ]  Save text style to preset
- [ ]  Delete text style

**Comment by csossi** [comment]
Not in scope for Beta 2 release
