### ISSUE TITLE
CUJ Testing for Beta v2 - Creator can Select an Element

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#3941]
## Feature Description

In preparation for the Beta 2 release we would like to have validation and confirmation of the CUJ functionality detailed in 
https://github.com/google/web-stories-wp/issues/1648

- [x] Select a single element
- [x]  Lasso select
- [x]  Shift+click to add element to selection

**Comment by csossi** [comment]
Verified in QA
