### ISSUE TITLE
CUJ Testing for Beta v2 - Creator can Transform an Element

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#3943]
## Feature Description

In preparation for the Beta 2 release we would like to have validation and confirmation of the CUJ functionality detailed in 
https://github.com/google/web-stories-wp/issues/1649

- [x] Move an element
- [x]  Snap to place (ie center, etc)
- [x]  Align element to page
- [x]  Align element to one another
- [x]  Rotate element using rotation handle
- [x]  Rotate element by entering a value
- [x]  Flip element
- [ ]  Auto-adjust landscape/portrait images/video but allow 90 degree rotation
- [x]  Adjust width
- [x]  Adjust height

**Comment by LuckynaSan** [comment]
Tested on macOS Mojave 13-inch v. 10.14.6 / Safari v. 13.1.2 and found no issues.

**Comment by csossi** [comment]
Verified in QA
