### ISSUE TITLE
CUJ Testing for Beta v2 - Creator can Delete an Element(s)

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#3944]
## Feature Description

In preparation for the Beta 2 release we would like to have validation and confirmation of the CUJ functionality detailed in 
https://github.com/google/web-stories-wp/issues/1650

 

- [x] Hit delete key
- [x]  Multiple select/lasso and delete
- [x]  Select all (CMD/CTRL) and delete
- [x]  Element is automatically deleted if dragged off the page

**Comment by csossi** [comment]
Verified in QA
