### ISSUE TITLE
CUJ Testing for Beta v2 - Creator can Undo or Redo any Action They Take

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#3945]
## Feature Description

In preparation for the Beta 2 release we would like to have validation and confirmation of the CUJ functionality detailed in 
https://github.com/google/web-stories-wp/issues/1651

- [x] cmd/ctrl-z should always undo my most recent action
- [x]  cmd/ctrl-shift+z should always redo most recent action
- [x]  alt. use redo/undo buttons

**Comment by csossi** [comment]
Verified in QA
