### ISSUE TITLE
CUJ Testing for Beta v2 - Creator can Browse and Add Shape

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#3946]
## Feature Description

In preparation for the Beta 2 release we would like to have validation and confirmation of the CUJ functionality detailed in 
https://github.com/google/web-stories-wp/issues/1663

**P0**
- [x] Add shape element to page by clicking on the shape from the shapes library
- [x]  Add shape element to page by dragging shape from the shapes library

**P2**

- [ ]  Browse shapes from template library
- [ ]  Browse basic shapes
- [ ]  Browse 3rd party shapes

**Comment by LuckynaSan** [comment]
Tested on macOS Mojave 13-inch v. 10.14.6 / Safari v. 13.1.2 and found no issues.

**Comment by csossi** [comment]
Verified in QA
