### ISSUE TITLE
CUJ Testing for Beta v2 - Creator can Manipulate Shape

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#3947]
## Feature Description

In preparation for the Beta 2 release we would like to have validation and confirmation of the CUJ functionality detailed in 
https://github.com/google/web-stories-wp/issues/1664

- [x] Set a new fill color (solid, linear, radial)
- [x]  Size, rotate, move
- [x]  Set color opacity
- [ ]  Set drop shadow color

**Comment by csossi** [comment]
Verified in QA 

Note: drop shadow out-of-scope for Beta2
