### ISSUE TITLE
CUJ Testing for Beta v2 - Creator can Use Shape for Masking Media Elements

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#3948]
## Feature Description

In preparation for the Beta 2 release we would like to have validation and confirmation of the CUJ functionality detailed in 
https://github.com/google/web-stories-wp/issues/1665

- [x] Drag image into shape to use as shape mask
- [ ]  Remove shape mask from media element

**Comment by csossi** [comment]
Verified in QA
