### ISSUE TITLE
CUJ Testing for Beta v2 - Creator can View and Move Elements Up/Down the Stack in the Layers Panel

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#3949]
## Feature Description

n preparation for the Beta 2 release we would like to have validation and confirmation of the CUJ functionality detailed in 
https://github.com/google/web-stories-wp/issues/1667

- [x] Get preview of metadata of element
- [x]  Move element up/down the layers stack
- [x]  CMD Up/Down to move element up/down the layer
- [x]  CMD+Shift+Up/Down to move element up/down the layer
- [x]  Delete a element from the layers panel
- [x]  Expand and collapse the layers panel (clicking on arrow or dragging)

**Comment by LuckynaSan** [comment]
Tested on macOS Mojave 13-inch v. 10.14.6 / Safari v. 13.1.2 and found no issues.

**Comment by csossi** [comment]
Verified in QA
