### ISSUE TITLE
CUJ Testing for Beta v2 - Creator can name and save their story

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#3953]
## Feature Description

In preparation for the Beta 2 release we would like to have validation and confirmation of the CUJ functionality detailed in 
https://github.com/google/web-stories-wp/issues/1668

- [x] Name story
- [x]  Edit name of story
- [x]  Manually save the story
- [x]  Draft stories autosaved every 60 s. Published stories no autosave.

**Comment by csossi** [comment]
Verified in QA
