### ISSUE TITLE
CUJ Testing for Beta v2 - Creator can View and Modify Document Settings

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#3955]
## Feature Description

In preparation for the Beta 2 release we would like to have validation and confirmation of the CUJ functionality detailed in 
https://github.com/google/web-stories-wp/issues/1671

- [x] Change default page duration for page advancement speed
- [x]  Toogle Auto vs. Manual advancement
- [x]  Set/modify publish date
- [x]  Set/modify author
- [x]  Select logo from dropdown
- [x]  Set/modify cover image
- [x]  Set/modify permalink
- [x]  Set/modify status

**Comment by csossi** [comment]
Verified in QA
