### ISSUE TITLE
CUJ Testing for Beta v2 - Creator Can Go to Their Settings Page

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#3956]
## Feature Description

In preparation for the Beta 2 release we would like to have validation and confirmation of the CUJ functionality detailed in 
https://github.com/google/web-stories-wp/issues/1673

- [ ] Set GA tracking ID
- [ ]  Upload and set a publisher logo globally
- [ ]  Manage their logo

**Comment by csossi** [comment]
Settings section is out-of-scope - currently behind feature flag
