### ISSUE TITLE
CUJ Testing for Beta v2 - Creator Can View Their Stories in Grid View

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#3958]
## Feature Description

In preparation for the Beta 2 release we would like to have validation and confirmation of the CUJ functionality detailed in 
https://github.com/google/web-stories-wp/issues/1676

- [x] See all their stories (Drafts plus Published)
- [x]  Sort their stories (last modified, last opened, date created, author, title, etc.)
- [x]  Filter their stories by All stories, Drafts and Published
- [x]  See metadata such as title and status [draft, published, modified, etc]
- [x]  Hover over story card to see quick animated preview of story

**Comment by csossi** [comment]
Verified in QA
