### ISSUE TITLE
CUJ Testing for Beta v2 - Creator Can View Their Stories in List View

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#3959]
## Feature Description
In preparation for the Beta 2 release we would like to have validation and confirmation of the CUJ functionality detailed in 
https://github.com/google/web-stories-wp/issues/1677

- [x] See stories in list view
- [x]  See expanded list of metadata
- [x]  Go to WP list view to actually do any action

**Comment by csossi** [comment]
Verified in QA
