### ISSUE TITLE
CUJ Testing for Beta v2 - Creator can modify or delete a story (using more/3-dot menu)

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#3960]
## Feature Description

In preparation for the Beta 2 release we would like to have validation and confirmation of the CUJ functionality detailed in 
https://github.com/google/web-stories-wp/issues/1678

- [x] Open in editor
- [ ]  Preview story
- [x]  Rename story
- [x]  Duplicate story
- [x]  Delete story

**Comment by csossi** [comment]
Verified in QA
