### ISSUE TITLE
Creator can Browse Templates in Grid View

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#3962]
## Feature Description
In preparation for the Beta 2 release we would like to have validation and confirmation of the CUJ functionality detailed in 
https://github.com/google/web-stories-wp/issues/1636

- [x] Browse all templates
- [x]  See template details page
- [ ]  Filter templates
- [ ]  Sort template
- [ ]  Bookmark/Unbookmark a template
- [x]  Use template
- [ ]  Preview template

**Comment by LuckynaSan** [comment]
Created [4066](https://github.com/google/web-stories-wp/issues/4066)

**Comment by LuckynaSan** [comment]
Browse templates in grid view passed in Safari/Mac.

**Comment by swissspidy** [comment]
FWIW, filters and the like haven't been implemented yet

**Comment by csossi** [comment]
Verified in QA
