### ISSUE TITLE
CUJ Testing for Beta v2 - Creator Can Search Templates

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#3963]
## Feature Description

n preparation for the Beta 2 release we would like to have validation and confirmation of the CUJ functionality detailed in 
https://github.com/google/web-stories-wp/issues/1683

- [ ] Enter keyword to search template
- [ ]  Select from suggested search terms in search box
- [ ]  Sort search results

**Comment by csossi** [comment]
This section is out of scope for Beta 2 release
