### ISSUE TITLE
CUJ Testing for Beta v2 - Editor Supported on Desktop

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#3964]
## Feature Description

In preparation for the Beta 2 release we would like to have validation and confirmation of the CUJ functionality detailed in 
https://github.com/google/web-stories-wp/issues/1685

**P0**
- [x] Use the editor on desktop

**P1**
- [ ]  Can resize the browser window

**Comment by csossi** [comment]
Verified in QA
