### ISSUE TITLE
Text Sets: Create utility to add a set of elements to a page

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#3966]
## Feature Description

Create a wrapper around the existing `useInsertElement` hook that can `useInsertSet` correctly.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

_Please fill this section before commencing issue resolution_.

**Comment by miina** [comment]
Note: need to ensure that inserting a combo will be one history entry only.
