### ISSUE TITLE
Story web non valide

### ISSUE THREAD

**Issue by 3pgarro** [GoogleForCreators/web-stories-wp#3968]
Hi, 

I created my first web story with WordPress Web Stories but when I test it with https://search.google.com/test/amp?hl=fr, it tells me that the web story is non valid. 

Here is the web story url : https://www.pg-linguistics.fr/stories/pourquoi-engager-agence-seo/

Someone could check it please ? 

With best regards, 
Pierre

**Comment by LuckynaSan** [comment]
I do see the validation issues in the AMP test [results](https://search.google.com/test/amp?id=18idW3DbTr_IlrHci2jnOg). Could you tell me if you have [WP Rocket](https://wp-rocket.me/) plugin installed? If you do, you'll want to ensure that either the [JS combine option is disabled](https://jmp.sh/2Z1ipoF) or [exclude story URLs from optimization](https://jmp.sh/NYGxWJx) in the settings. Please note we are working on a solution from the Web Stories plugin side to improve the compatibility with that plugin.

**Comment by 3pgarro** [comment]
Thanks for your answer ! 
The web story is now valid.

**Comment by LuckynaSan** [comment]
I am glad your issue has been resolved.

**Comment by t1000upgraded** [comment]
Hey @LuckynaSan you response helped me as well. Thanks a million my friend
