### ISSUE TITLE
Width & Height Error on AMP Native Mode for Embeds in Post or Page

### ISSUE THREAD

**Issue by netnaps** [GoogleForCreators/web-stories-wp#3992]
## Bug Description

Width & Height Error on AMP Native Mode for Embeds in Post or Page

## Expected Behaviour

No AMP Validation Errors

## Steps to Reproduce

Opened this on [WordPress Support Forum](https://wordpress.org/support/topic/web-stories-beta-plugin-on-amp-standard-mode-issues-with-embed/#post-13261692) Here

## Screenshots

![Screenshot 2020-08-15 at 12 14 14 AM](https://user-images.githubusercontent.com/67054369/90318921-71094780-df51-11ea-9b7f-49095a380b38.png)

![Screenshot 2020-08-15 at 11 47 30 PM](https://user-images.githubusercontent.com/67054369/90318985-e2e19100-df51-11ea-9084-c66cdc40d620.png)
![Screenshot 2020-08-15 at 11 48 01 PM](https://user-images.githubusercontent.com/67054369/90318988-eb39cc00-df51-11ea-8f5b-ef8c4c9dcd4e.png)

## Additional Context

- Plugin Version: Beta 1
- Operating System: WP Latest, MacOS Catalina 
- Browser: Chrome, Safari

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Marked for stable as it causes AMP invalidation.
