### ISSUE TITLE
Font picker: fix search behaviour

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#4008]
## Bug Description

Follow-up for https://github.com/google/web-stories-wp/issues/2418.

There are two bugs with search:
- Search should only display font matching the characters in the beginning of the font. E.g. "Arimo" should not respond to searching "Mo".
- Recently used fonts should not be displayed when searching.

See also https://github.com/google/web-stories-wp/pull/3215#issuecomment-673903589 reported by Sam.
## Steps to Reproduce
See the original comment: https://github.com/google/web-stories-wp/pull/3215#issuecomment-673903589

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by pbakaus** [comment]
AFAIK candidate to push out. @o-fernandez

**Comment by csossi** [comment]
Verified in QA
