### ISSUE TITLE
Font picker: Adjust the style based on Figma

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#4009]
## Feature Description
The font picker was styled by the previous design but enabled when the new design already existed. This means that the font picker is still styled based on the previous design, it should get updated to the new style.

See originally reported by Sam: https://github.com/google/web-stories-wp/pull/3215#issuecomment-673903589

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

The font picker should match Figma style, see [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Stories-Stable?node-id=937%3A0)

**Comment by maxyinger** [comment]
doing in tandem with:
#4059

**Comment by csossi** [comment]
Verified in QA
