### ISSUE TITLE
Problem with view the Story in public mode

### ISSUE THREAD

**Issue by Spottel** [GoogleForCreators/web-stories-wp#4014]
I wanted to test the webstories and have the following problem.
If my story is in draft status, I can view it in preview mode or via the link. 
If I make the story public. I can no longer view the story over the link.
The error is 
Page can not be found

What can I do?

https://www.frank-schuenemann.de/stories/frankschuenemann/

**Comment by LuckynaSan** [comment]
Hi there! Thanks for reporting this. 

- Can you confirm the [permalink field](https://jmp.sh/Spieetv) matches the URL provided above?
- Can you check the [story is set to public ](https://jmp.sh/J6kBaxl)then update the post again?

**Comment by Spottel** [comment]
Thank you for your message.
Yes my story is on public and the name is test.

Also the draft mode works:
https://www.frank-schuenemann.de/?post_type=web-story&p=2569

In public mode:
https://www.frank-schuenemann.de/stories/test/  => **Not works!**

https://www.frank-schuenemann.de/stories/test/?preview_id=2569&preview_nonce=ac221a517d => Public (Preview Mode) => **Not works!** (This link is from the Preview Button in Public Mode)

https://www.frank-schuenemann.de/stories/test/?preview_id=2569&preview_nonce=ac221a517d&post_type=web-story
 => Public (Preview Mode) with the params post_type => **Works!**

I think it is a problem with the domains and the path/params.
I use a Multi Site Setup. With Multi Domains.

**Comment by Spottel** [comment]
It works now! Dont know why :-) Thank you!

**Comment by LuckynaSan** [comment]
Good to hear it works. Thank you!
