### ISSUE TITLE
Local build sometimes fails when running in watch mode

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#402]
## Bug Description

When running `npm run dev` local build fails spontaneously. However, it does not fail in the terminal, the error is only reported as a failed build when reloading the browser window.

The failed builds occur regardless of the change. Simply change any line anywhere can cause the build to fail - changing a `1` to a `2` in any file back and forth will trigger the error after a few attempts.

Aborting the watching process and restarting it always produces a valid build.

## Expected Behaviour

The build should never fail in the browser only.

## Steps to Reproduce

1. Checkout `master`
1. Run `npm i`
1. Run `npm run dev`
1. Make changes to any file and watch process rebuild
1. Reload browser to see resulting changes
1. The browser renders nothing and throws an error:

```
Uncaught Error: Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: <root>/assets/src/edit-story/components/canvas/gridview/index.js: ENOENT: no such file or directory, open '<root>/node_modules/svgo/lib/svgo/../../.svgo.yml'
```

The actual file containing the error (in the above  `components/canvas/gridview/index.js`) can vary - it can be any file containing a reference to an SVG. And the file is not related to the change performed triggering the rebuild.

7. If no error happened, repeat from step 4 until one does occur. It takes no more than 4 attempts on my setup.

## Screenshots

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Seems to have been a common issue at some point in the past: https://github.com/svg/svgo/issues/622
Also: https://github.com/gregberge/svgr/issues/46

**Comment by swissspidy** [comment]
@barklund Are you still experiencing this?

**Comment by barklund** [comment]
It occurs less frequently now, but happen as late as yesterday - though not today at all. I'll keep monitoring.

**Comment by barklund** [comment]
Just happened, so still occurs, but a lot less frequently.

**Comment by swissspidy** [comment]
Closing this one for now. Please reopen if this still occurs.
