### ISSUE TITLE
Uploaded Image/Video Appears as Broken In Canvas

### ISSUE THREAD

**Issue by csossi** [GoogleForCreators/web-stories-wp#4023]
Activated PR#4012 - Win10/Chrome

- started new story
- selected Upload from Media section
- Browsed to local folder and selected Image
- image loads in Media Gallery tab
- Selected "Insert into page"
- Image appears as broken on canvas

Video: https://drive.google.com/file/d/1fcyqu3uZ5ymOWryZ_UPsN5xKWzsZKh5R/view

**Comment by LuckynaSan** [comment]
Here is a [screenshot of the issue](https://jmp.sh/m5v7WXQ) occurring on macOS Mojave 13-inch v. 10.14.6  / Safari v. 13.1.2.

**Comment by swissspidy** [comment]
@csossi Can you test that again? Would need to switch to PR #4039 on the QA environment. If it works, I'll add it to #4012, too.

**Comment by LuckynaSan** [comment]
I re-tested on safari/mac and the image uploaded to canvas successfully.
