### ISSUE TITLE
Setting BG Video - Play/Pause State Logic

### ISSUE THREAD

**Issue by csossi** [GoogleForCreators/web-stories-wp#4024]
PR4012 - Win10/Chrome

- added a video to canvas
- clicked Set As Background
- Video was set as background, but with "pause" button appearing (meaning video should be playing)
- Video wasn't playing

- Note: If I click the "pause" button and THEN "play", then it will begin to play

Video - https://drive.google.com/file/d/15Xzw7miM1BuvArf3EWFuQyrsSB_Rn5R5/view

**Comment by swissspidy** [comment]
@merapi Is this a known issue? How does it relate to #3643?

**Comment by merapi** [comment]
Something went wrong, definitely need to cover this one with tests.

**Comment by merapi** [comment]
#3643 will fix it.

**Comment by swissspidy** [comment]
Duplicate of #2618
