### ISSUE TITLE
Document Panel - Metadata Functionality

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#405]
## Feature Description

As an editor I want to be able to edit metadata for my story

Note: As of March 4, This ticket is for functionality, designs are coming later.  See #504 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

* **Design**
* **[Epic - Document Workflow](https://docs.google.com/document/d/1GJZljicdXcP7oRdywsF3EGUaCVpCHsDrK2gUMubnrbk/edit?pli=1#heading=h.ymf85pwospli)**

* **Related issues / PRs:**

## Acceptance Criteria
1. Authors can edit document-wide metadata in the “Document” tab of the design panel.
7.  Authors are able to edit the View post setting
11. The poster image is required
12. Authors are able to set the publisher logo
12. The publisher logo is required
13. Date picker for publish date ( with validation )
14. Styled dropdown for authors 
15. Confirmation dialog on move story to trash.
17. Validation on page slug edit.
14. Authors are able to edit the auto-advance settings (TO BE DONE IN #84)
See epic doc for more details

Already done in #87 
1. Authors are able to edit the Password
2. Authors are able to edit the Visibility
3. Authors are able to edit the Publish status
5. Authors are able to edit the Author
6. Authors are able to edit the URL Slug (AKA POST PERMALINK)
13. Authors are able to write an excerpt
11. Authors are able to set the poster image (AKA FEATURED IMAGE?)

**Comment by jauyong** [comment]
Assigning to @samitron7 for UX.

**Comment by spacedmonkey** [comment]
Some other functionality that is missing from the documents sidebar.
- Date picker for publish date ( with validation )
- Styled dropdown for authors ( and maybe search ).
- Confirmation dialog on move story to trash. 
- Rich text formatting excerpt ( Nice to have )
- Validation on page slug edit.

**Comment by miina** [comment]
Should revisions be saved (and available for restoring) for a Story?

**Comment by swissspidy** [comment]
@miina According to the document linked above, yes

**Comment by miina** [comment]
> See epic doc for more details

^ Just saw that now, thought that it was missing from the description but looks like it was intentional. (I guess? cc @jauyong just in case)

**Comment by miina** [comment]
Note that I'm working on parts of this (simplified image fields + status/visibility and other adjustments that are currently already in design) together with #504 (as discussed over the last grooming) and thus assigned it to myself for now.

Note that for some reason this issue is not on the project board (even though in Sprint 25), should it be? cc @pbakaus @jauyong @kmyram

**Comment by jauyong** [comment]
@miina @pbakaus @kmyram 
I have a note from March 9 (Monday Sync Meeting) that this was to be moved out of the sprint.

**Comment by miina** [comment]
Interesting, since it seems that the Sprint label was added on the March 9 :)

Anyway, probably this issue covers too much for one single issue so we can adjust the issue based on what gets done elsewhere (e.g. in #667). Some parts of it will be done in some other issues as well, e.g. the Publisher logo selection likely within #570

**Comment by o-fernandez** [comment]
@jauyong @samitron7 this issue seems to cover a ton of different things in one ticket. Can we have smaller tickets? Some of this is likely done already, so worth closing this issue and opening tickets for what's remaining.

**Comment by spacedmonkey** [comment]
Feel like most of this ticket is done as part of #667 . 

I think we should close this ticket our and create new tickets for any missing functionality.

**Comment by jauyong** [comment]
@spacedmonkey is there any functionality that isn't merged on staging / UAT? Just want to make sure I'm aware of the latest before I close this and create the new tickets...

**Comment by swissspidy** [comment]
I think we're all covered here.

The two missing things I saw:

- Ability to make stories password protected (low priority as per https://github.com/google/web-stories-wp/issues/87#issuecomment-577026598)
- Ability to add excerpt (covered by #490)

Will open a new issue for password protection.

This one can be closed.
