### ISSUE TITLE
srcset complications with cropped/zoomed images

### ISSUE THREAD

**Issue by merapi** [GoogleForCreators/web-stories-wp#4051]
## Bug Description

#3249 introduced responsive images via `srcset` (for editor and output) while it's a good optimization for the output it also introduces complications for cropped/zoomed images (see gif).

## Expected Behaviour

There should be no visual difference between display and edit mode when the image is cropped/zoomed.
Output quality should also match the one in the editor?

## Screenshots

Display: lower res image via srcset
Edit: highest res image (no srcset)

![srcsetzoom](https://user-images.githubusercontent.com/21036224/90514461-7f2db280-e161-11ea-94bf-e5c0f59b371f.gif)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by diegovar** [comment]
I can't seem to reproduce this. Can you attach the image that is causing the issue? Or upload a longer video showing the flow / context?

**Comment by merapi** [comment]
Try with this image on staging: https://drive.google.com/file/d/1C-zSdmELVJ25JAA3LdLQl8Ro-TU7Dqya/view?usp=sharing
