### ISSUE TITLE
Improve E2E Test for inserting media from library

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#4052]
## Task Description

Following #4039, #4023, let's make sure the existing e2e test for this catches said bug.

https://github.com/google/web-stories-wp/blob/757c3845f5c00e8413126070520b51b3fb70e7eb/tests/e2e/specs/editor/media/insertMediaFromLibrary.js#L27-L44

A percy screenshot would have caught this bug, but the screenshots are skipped because of #1206.

Maybe there are other ways to catch this, too. Like checking for the actual `img` attributes

**Comment by swissspidy** [comment]
See also #4377 / #4367. Another opportunity to add tests.

**Comment by spacedmonkey** [comment]
I am marking #1206 as a blocker for now.

**Comment by swissspidy** [comment]
#1206 is not a blocker for this. But since #4535 was merged it's not relevant anymore anyway.
