### ISSUE TITLE
Dashboard: Rename Story Text Box is cut off 

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#4053]
## Bug Description

The right border of the input field is cut off in Firefox when renaming a story on the dashboard.

## Expected Behaviour

It should not be cut off.

## Steps to Reproduce

1. Rename a story in Firefox

## Screenshots

![image.png](https://images.zenhubusercontent.com/5ea09bca6a44046f869bafe0/02d4dd11-d35b-4ab8-883e-c72985be5de3)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Tested #4068

Verifeid in QA
