### ISSUE TITLE
Dashboard: Improve Search Performance 

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#4054]
## Bug Description

Searching (filtering by name) can be slow when there are a huge batch of stories. Investigate where improvements can be made.

## Screenshots

https://recordit.co/eAI3kTKXSA

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

- Launch the Dashboard
- Search for stories on My Stories using a name
- See that performance has increased since last testing or against the video linked above

**Comment by csossi** [comment]
Hi @dmmulroy - testing in PR 4067 and see tht performance has indeed improved, but part of the check for 4067 is that the input field works as expected. What I'm finding is that when a user inputs a search term, suggestions populate below - which is fine but the top selection is always highlighted/active by default. 

In the attached image, I want to search for "cattus". My expectation is that all stories with "cattus" in the name would be returned on pressing keyboard ENTER. Instead, only "Cattus Two" is returned as it was automatically highlighted:

![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/3f23589e-5a5c-4468-a68e-502eea3fdcf5)

Let me know if this requires a new ticket - cheers

**Comment by csossi** [comment]
Verified in QA (new ticket re: above issue)
