### ISSUE TITLE
3P Media: Category background colour is incorrect

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#4058]
## Bug Description

When viewing categories within the 3P integration panel the background is blue

## Expected Behaviour

BG should be same (black)

## Screenshots
![Screen Shot 2020-08-18 at 7.13.02 AM.png](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/edae9e37-f5c3-41c4-aae8-ac29c7323b01)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
@o-fernandez  request from @samitron7  to address this in Beta-2 release 

CC: @diegovar / @carlos-kelly

**Comment by swissspidy** [comment]
This is not a beta 2 item as 3p Media is behind a feature flag

**Comment by bmattb** [comment]
removed from the beta2 release as per comment above, thanks @swissspidy

**Comment by swissspidy** [comment]
Fixed by #3787.

No UAT needed as it's behind a feature flag.
