### ISSUE TITLE
Dropdown styling is incorrect

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#4059]
## Bug Description

@samitron7  to advise on how this is incorrect

## Screenshots
<img width="345" alt="Screen Shot 2020-08-18 at 7 16 49 AM" src="https://user-images.githubusercontent.com/58738530/90533003-e6d60480-e145-11ea-8563-259015177f9d.png">

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
@o-fernandez - request from @samitron7  to include in Beta-2 release, not a showstopper

**Comment by o-fernandez** [comment]
Seems like this is UX Needed? @samitron7 @bmattb ?

**Comment by barklund** [comment]
The media filter dropdown is also used in the design panel (for setting the font-weight) and document panel (for setting the author). The unopened dropdown looks correct, but the opened dropdown is wrong - it's currently in a white design and should be updated to a black design (and not the previous dark blue design).

The design should be the same as for the font picker (to be redesigned in #4009, design can [be seen here](https://github.com/google/web-stories-wp/pull/3215#issuecomment-673903589)).

I've added Prometheus to this one as it has an impact in the editor too. Also, whoever fixes #4009 might easily pick this one up too, as they're somewhat similar.

**Comment by maxyinger** [comment]
Added to font picker style update PR #4009
https://github.com/google/web-stories-wp/pull/4304

**Comment by csossi** [comment]
Verified in QA
