### ISSUE TITLE
Focus state in the layers panel is the incorrect background colour

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#4060]
## Bug Description

The focus state in the layers panel should be gray

## Expected Behaviour

Gray background on focus state

## Screenshots

<img width="143" alt="Screen Shot 2020-08-18 at 7 17 15 AM" src="https://user-images.githubusercontent.com/58738530/90533741-e9852980-e146-11ea-8a87-a31d90ab43a8.png">

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
@o-fernandez - request from @samitron7  to address this prior to Beta-2 release, however not a showstopper CC: @carlos-kelly

**Comment by csossi** [comment]
Verified in QA
