### ISSUE TITLE
Background colour for the Auto/Manual auto-advance toggle is incorrect

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#4061]
## Bug Description

@samitron7 sez that the bg to the toggle for auto vs manual tap to advance should be gray

## Screenshots
<img width="261" alt="Screen Shot 2020-08-18 at 7 17 24 AM" src="https://user-images.githubusercontent.com/58738530/90534226-7b8d3200-e147-11ea-8be2-486db32f27bd.png">

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
@o-fernandez - @samitron7  has asked for this to be fixed prior to Beta-2 release, however it is not a showstopper.

**Comment by swissspidy** [comment]
Fixed by #3787
