### ISSUE TITLE
Stories without titles showing blank title in list view and search dropdown

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#4062]
## Bug Description
Last week a fix was made to show `(no title)` for stories with blank titles. It snuck past us that a similar update is necessary for the list view and search dropdown. 

## Expected Behaviour

When a story title is blank (or just white space) it should show `(no title)` as the title in read format (if you are renaming it, the input value should be an empty string when you click 'rename') 
When you search, empty titles should not be dropdown value options. 

## Steps to Reproduce

Create a new story draft, don't name the story. Go to dashboard, see that the grid view shows `(no title)` for that story. Go to list view, see that it shows blank. 

For the search input, I think it's easiest to create a story from a template and don't name it. Then you have the previous template metadata attached to the default WordPress search and if you type in something to do with that template the new story will be pulled in as a search option. 

## Screenshots

![Screen Shot 2020-08-17 at 3.51.26 PM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/de46d4fe-65d8-4a98-a239-0aaa6d399efa)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

- no more blank story titles for list view in dashboard
- no blank dropdown values in search

## Implementation Brief

- check for story title and story title length before allowing through to typeahead for search
- check for story title before rendering readable title in dashboard list view of stories 
https://github.com/google/web-stories-wp/pull/4027

**Comment by csossi** [comment]
Tested in 4027

Verified in QA
