### ISSUE TITLE
Editor panel section divider color incorrect

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#4063]
## Bug Description

The lines that indicate the section dividers should be gray, instead of blue

## Screenshots
<img width="274" alt="Screen Shot 2020-08-18 at 7 17 54 AM" src="https://user-images.githubusercontent.com/58738530/90535522-fa369f00-e148-11ea-8a26-6e744b930c53.png">

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
@o-fernandez - @samitron7  has asked that this be addressed as part of Beta 2 but not a showstopper, please update with the appropriate labels 

CC: @carlos-kelly / @barklund

**Comment by csossi** [comment]
Verified in QA
