### ISSUE TITLE
Pages  in the carousel jitter

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#4066]
## Bug Description
The pages inside an existing template jitter when you open the editor on an existing template. 

Issue occurs for the following templates: [Doers Get More Done](https://recordit.co/eXkB2AxSgs), [Experience Thailand](https://recordit.co/iSkZPZESbB), [Sleep](https://recordit.co/lSeVos7uUM)

## Expected Behaviour

The pages in an existing template should not jitter up and down when you open the editor.

## Steps to Reproduce
1. Explore template
2. Use Template (Doers Get More Done, Explore Thailand, Sleep)

## Additional Context
Same behavior in an incognito browser.
The other templates did not jitter.

- Plugin Version: 
- Operating System: macOS Mojave 13-inch v. 10.14.6 /
- Browser: Safari v. 13.1.2

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Maybe an issue with the safe zone and the responsiveness of the carousel?

**Comment by o-fernandez** [comment]
I've noticed this in the past, I think it has to do with shape handling when they are very large and go far outside the canvas. The entire canvas moves up/down and it's hard to manage certain pages. The Sleep template is particularly problematic, IIRC. 

It would be good for the prometheus or the pea pods to TAL and see how we may solve this, if not already in the works. 
@barklund @carlos-kelly any thoughts?

**Comment by miina** [comment]
Seems to not happen anymore, probably got resolved related to #5692. Closing this issue, cc @barklund

**Comment by LuckynaSan** [comment]
@miina Hi there, I am reopening this issue as it is occurring in Safari / macOS 13-inch. See video below and please let me know if there are other details I can share.


https://user-images.githubusercontent.com/66372350/107670056-5eea3680-6c60-11eb-8d18-d14934bbb5a4.mov

**Comment by LuckynaSan** [comment]
Closing this issue as it no longer occurs with version 1.4.0.
