### ISSUE TITLE
Verify Coverr AMP video url rewriting / caching end to end

### ISSUE THREAD

**Issue by cvolzke4** [GoogleForCreators/web-stories-wp#4069]
## Task Description

Test that the 'mp4' video links provided by Coverr are embedded and published correctly, and the AMP urls are rewritten.

This is an end-to-end test to verify that the Coverr videos links, which are 302 redirected from storage.coverr.co to mux.com, are rewritten/cached appropriately.

1. Create a story, and insert a Coverr video.
2. Publish the story to the open web.
3. Open the story using the STAMP url of the story.
4. Verify that the link to the video is an AMP cache cdn url.
5. Verify that video playback works as expected.

**Comment by swissspidy** [comment]
Chromium doesn‘t support mp4 videos so not sure how reliable such an e2e test can be :/

**Comment by cvolzke4** [comment]
> Chromium doesn‘t support mp4 videos so not sure how reliable such an e2e test can be :/

This issue describes a manual test.

**Comment by diegovar** [comment]
Verified.
