### ISSUE TITLE
Fix Search state

### ISSUE THREAD

**Issue by joannag6** [GoogleForCreators/web-stories-wp#4071]
Clearing the search in one provider doesn't clear the search in the other provider. This is confusing since the search state is supposed to be preserved. This also prevents the user from being able to search for something else in the other provider

Repro steps:
1. Click on Unsplash tab and Coverr tab so both have the trending images loaded.
2. In the Unsplash tab, type "cat" into search bar and hit enter. (Cat images will appear in Unsplash tab)
3. Click on Coverr tab
4. Videos are still trending videos, not cat videos. Hitting enter again in the search bar doesn't do anything either.

**Comment by diegovar** [comment]
I can't reproduce this, can you provide steps to reproduce?

**Comment by diegovar** [comment]
Hey Clint, I remember in standup you came up with a nifty solution for this, what was it? Was it clearing the media when the search term changes?

**Comment by cvolzke4** [comment]
> Hey Clint, I remember in standup you came up with a nifty solution for this, what was it? Was it clearing the media when the search term changes?

Setting isMediaLoaded=false for each provider will cause useFetchMediaEffect to re-fetch the media when the tab is changed:

https://github.com/google/web-stories-wp/blob/9cd13ee04a8ec6240017e2fdd513fe3b45720e23/assets/src/edit-story/app/media/media3p/useFetchMediaEffect.js#L121
