### ISSUE TITLE
Coverr video urls not loading in gallery and canvas

### ISSUE THREAD

**Issue by joannag6** [GoogleForCreators/web-stories-wp#4072]
Sometimes Mux cancels requests (happens in both gallery and canvas)

**Comment by bmattb** [comment]
@diegovar - is this going to be done in Sprint 36? If so, can we move into sprint backlog, else remove the S36 tag please.

**Comment by o-fernandez** [comment]
@diegovar is this still an issue or are we complete on Coverr?

**Comment by diegovar** [comment]
We're complete.
