### ISSUE TITLE
Media Gallery sometimes rearranges the images weirdly when loading the next page

### ISSUE THREAD

**Issue by joannag6** [GoogleForCreators/web-stories-wp#4073]
Scroll to the bottom of the list, sometimes things get rearranged weirdly

I think this is how the row Gallery "chooses" to place the images, if you keep track of the last image in the list, it sometimes gets rearranged into a different position

Note: This might just be an issue with the gallery we're using and might not be solveable.

**Comment by diegovar** [comment]
Can you add more details?

**Comment by dreamofabear** [comment]
Needs more info, closing.
