### ISSUE TITLE
Text Sets (Combos): Add all text sets to data structure

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#4078]
## Feature Description

Create all 125(?) text sets in the data structure defined in #3965 and make sure they display correctly with #4077.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
Text Sets are added for:

- [x] Cover
- [x] Editorial
- [x] Section header
- [x] Steps
- [x] List
- [x] Table
- [x] Quote
- [x] Contact
- [x] Funky Sets

## Implementation Brief

_Please fill this section before commencing issue resolution_.

**Comment by maxyinger** [comment]
I'm just gonna start hacking these out. If we wanna do these in parallel at all just contact me and we can devise a plan to break em up a bit

**Comment by maxyinger** [comment]
Cover Texts Sets: https://github.com/google/web-stories-wp/pull/4522

**Comment by maxyinger** [comment]
Section Header: https://github.com/google/web-stories-wp/pull/4537

**Comment by maxyinger** [comment]
Step: https://github.com/google/web-stories-wp/pull/4547

**Comment by maxyinger** [comment]
Editorial: https://github.com/google/web-stories-wp/pull/4552

**Comment by maxyinger** [comment]
List 1: https://github.com/google/web-stories-wp/pull/4563

**Comment by dmmulroy** [comment]
Quote: #4696 (approved and merged, just found this ticket)

**Comment by dmmulroy** [comment]
Contact: #4750

**Comment by bmattb** [comment]
I just want to confirm that there has not been any QA by @csossi on this... is that correct?
