### ISSUE TITLE
Bigger-than-viewport elements mess up the workspace layout

### ISSUE THREAD

**Issue by pbakaus** [GoogleForCreators/web-stories-wp#408]
## Bug Description

Very big elements cause the workspace to be misaligned.

## Expected Behaviour

Workspace position should never be affected by size of elements.

## Steps to Reproduce

Resize text element to be very large. Drag around a little.

## Screenshots

![image](https://user-images.githubusercontent.com/43004/75301933-23f1b780-57f1-11ea-90a7-f8725a89f955.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Not an issue anymore
