### ISSUE TITLE
Put eyedropper functionality behind feature flag

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#4081]
## Task Description

Work on the eyedropper feature is tracked in #262, and a prototype has been explored in #3007 — but it's still not implemented.

For this reason it's probably best to put the eyedropper behind a feature flag to prevent user confusion. Right now it's just a disabled button in the color picker.

<img width="223" alt="Screenshot 2020-08-18 at 20 09 44" src="https://user-images.githubusercontent.com/841956/90601933-375a6a00-e1f9-11ea-9333-d5c32ff94c82.png">

**Comment by sks** [comment]
Hi @swissspidy,

I would like to give this a shot.

**Comment by westonruter** [comment]
Yes, I was confused by this. I kept trying to click the eyedropper but I couldn't get it to ever do anything.

**Comment by csossi** [comment]
Verified in QA
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/ff2bac7d-1189-45d8-83c2-f4e4a464da06)
