### ISSUE TITLE
History: Opening an existing story indicates new changes right away

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#4094]
## Bug Description
When adding a new clean story without any changes, or opening an existing story, the Save Draft button is active, the Undo button is active, and trying to close the Story warns about unsaved changes. 

## Expected Behaviour
Opening a story without making changes should not indicate having changes.

## Steps to Reproduce
1. Create a new story
2. See the Save Draft and Undo button active.
3. Try to close the tab.
4. See the warning.

## Screenshots
![new](https://user-images.githubusercontent.com/3294597/90634447-fcbbf600-e227-11ea-8142-33a1439d9354.gif)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Perhaps related to animation work?

Also perhaps related: #3548. That one could be caused by this bug; not sure.

---

In any case, I'd say tests are mandatory for this ticket :-)

**Comment by miina** [comment]
Note: Saving and auto-saving also seem to modify history currently. E.g. clicking "Save draft" and then "Undo" does nothing but the save button gets active again -- indicating as if the save itself caused a new entry in the history somehow. Perhaps related.

**Comment by swissspidy** [comment]
This is continues to be annoying.

It  also means that I can create a story (`auto-draft` at this point), autosave will kick in, and then it will turn it into  an actual draft.

**Comment by miina** [comment]
Also seems to be causing some flakiness with tests (#4218 )

**Comment by miina** [comment]
Looks like this is the first commit where the issue appears: 2974e4d72ad8aec0dcc54017eba9d6aa80d1f698
PR: https://github.com/google/web-stories-wp/pull/3813

cc @barklund FYI

**Comment by miina** [comment]
@barklund @o-fernandez Should we perhaps pull this into the stable? To ensure the history is stable in the stable? 😛 
(I could most likely look at it tomorrow/on Monday if yes)

**Comment by o-fernandez** [comment]
Sure, but lower priority than the rest of the Stable items, IMO. @bmattb FYI :)
