### ISSUE TITLE
Dashboard: Created/last modified relative strings are sometimes broken

### ISSUE THREAD

**Issue by merapi** [GoogleForCreators/web-stories-wp#4095]
## Bug Description

The first story was modified a few minutes ago.

## Expected Behaviour

It should print the correct relative time.

## Steps to Reproduce

The screenshot is from staging (I'm in UTC+2).

## Screenshots

![image](https://user-images.githubusercontent.com/21036224/90636388-d21f6c80-e22a-11ea-916f-4bdc29f71dc0.png)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Can confirm.

Looks like #4082 fixes this. Can you try that branch?

**Comment by merapi** [comment]
> Looks like #4082 fixes this. Can you try that branch?

I've created a new story on that branch, still looks broken.

![image](https://user-images.githubusercontent.com/21036224/90641088-19a8f700-e231-11ea-809d-fe24079b135c.png)

**Comment by swissspidy** [comment]
Weird. It's working fine for me on that branch. Just created some new stories:

<img width="708" alt="Screenshot 2020-08-19 at 15 56 04" src="https://user-images.githubusercontent.com/841956/90643988-8376d000-e234-11ea-857c-b9a3f4e29784.png">

What's your timezone setting in WP?

**Comment by merapi** [comment]
UTC+2, you can also check on QA env (UTC+0)

![image](https://user-images.githubusercontent.com/21036224/90645120-ddc46080-e235-11ea-828c-607ec85d0b21.png)

**Comment by swissspidy** [comment]
Hmm it seems to work when I set a specific timezone, e.g. Zurich, but not a when I specify a specific a UTC offset, etc. UTC+2

**Comment by merapi** [comment]
Please check now on QA https://github.com/google/web-stories-wp/pull/4082/commits/dea73130179d52172bb819a250e2b7247043f6b8

**Comment by swissspidy** [comment]
I can see clearly now the ~rain~ bug is gone!
