### ISSUE TITLE
Dashboard: Set action functions as refs to reduce re-renders

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#4097]
## Feature Description

Assign the action functions in the Dashboard as refs to reduce the re-renders.

https://docs.google.com/document/d/18m9HamHkOvvTrv-mSOJawha0K4KTdn49HrnfXShULDI/edit#heading=h.khdu6hi94lhl

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by dmmulroy** [comment]
I spent the past few days going through the ~170 instances of our use of useCallback in the Dashboard and I marked 6 as potential candidates for this stateRef pattern.  Most instances would not benefit from this pattern do to the component which uses/create the callback receiving and using the state as props/from context and would rerender itself and it's children anyways.  In addition, most of the time, our callbacks using state are not passed/prop drilled very far and commonly are directly provided to a button (or some other actual dom component) making for inexpensive rerenders.   

After circling back around and testing these 6 instances, 2 actually broke the app due downstream useEffect's depending on them (i.e. the effect firing when the reference to callback changes), and the others either would rerender/update their ref at the same time as state updates, or made no difference on performance.

I am going to close this as this pattern doesn't provide much in the way of performance improvements for the Dashboard.
