### ISSUE TITLE
Flickering Background Video on Canvas

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#4099]
## Bug Description

When moving elements around on the canvas, the background video constantly flickers, making for a very jarring experience.

## Expected Behaviour

No flickering

## Steps to Reproduce

1. Set video as background.
1. Add text element and move it around.

## Screenshots

Video: https://cloudup.com/cP-f2-W0ovY

## Additional Context

- Plugin Version: current `main`
- Operating System: macOS
- Browser: Chrome 84

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by merapi** [comment]
Is there something wrong with our Staging/QA setup?

A simple request for https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/uploads/2020/08/image-3.jpeg (this is the video poster) looks like this:

![image](https://user-images.githubusercontent.com/21036224/90690581-3d406180-e272-11ea-81e3-8860071be3f2.png)

**Comment by swissspidy** [comment]
IDK, but my video is from my local install if that helps

**Comment by merapi** [comment]
Alright, in that case, I can only reproduce a similar effect when I disable caching in DevTools.

![image](https://user-images.githubusercontent.com/21036224/90954808-1d7a8a80-e478-11ea-9f1a-49e5006be67c.png)

**Comment by swissspidy** [comment]
Some dev 
<img width="1279" alt="Screenshot 2020-08-22 at 13 16 36" src="https://user-images.githubusercontent.com/841956/90954993-e2795680-e479-11ea-844c-c2ca85560abc.png">tools 
screenshots from my local testing:

<img width="924" alt="Screenshot 2020-08-22 at 13 17 30" src="https://user-images.githubusercontent.com/841956/90954990-df7e6600-e479-11ea-9665-9ca744d4d405.png">

I don't get why the background video's poster image is loaded dozens of times, even when I am not interacting with the video at all. I am moving a text element.

Caching or not, this sounds like a bug to me.

**Comment by swissspidy** [comment]
Can't reproduce, closing for now.
