### ISSUE TITLE
Finalize title input (make wider, center on large screens)

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#41]
## Feature description

Story Title displayed above everything else. Ability to rename story, which will modify the slug.

[Figma Save Story Title Flow](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=9045%3A4)

From[ Fishfood doc:](https://docs.google.com/document/d/1KHeF6yBRLqa29OUZ3Lu-h4evlVI1TmqJOprly-wWOto/edit#)

> The ‘title’ input is too small and not centered on large resolutions

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. Make larger
2. Center

Per Figma, the Title field should be centered on a bigger surface. Only smaller surfaces (~iPad) the title should be left-aligned.

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jauyong** [comment]
@spacedmonkey I think slug was done in #87 and it exists on staging without the updated design (see screenshot). 
Can this be closed?


![image](https://user-images.githubusercontent.com/5874851/75792983-b556b180-5d3c-11ea-833a-981219598b1d.png)

**Comment by spacedmonkey** [comment]
@jauyong  I put this field in the sidebar, as I was waiting for a design for the title. The title is not complete.

**Comment by pbakaus** [comment]
What's the UX still required to finish this?

**Comment by swissspidy** [comment]
@jauyong @samitron7 What does the arrow next to the title do?

<img width="377" alt="Screenshot 2020-04-23 at 10 24 59" src="https://user-images.githubusercontent.com/841956/80076722-dec9d780-854c-11ea-9c27-9b8782bbf050.png">

<img width="524" alt="Screenshot 2020-04-23 at 10 24 54" src="https://user-images.githubusercontent.com/841956/80076713-dc677d80-854c-11ea-8abd-0d8679423640.png">

**Comment by jauyong** [comment]
I'm not sure. I'll have to defer to @samitron7

**Comment by spacedmonkey** [comment]
I think that #889 should also be handled by this ticket as it deals with title as well.

**Comment by jauyong** [comment]
RE: the arrow , this is not part of beta. It is a dropdown with publish options

**Comment by jauyong** [comment]
@samitron7 to add details for breakpoints and max width.

**Comment by ndev1991** [comment]
@samitron7 Can you add details for input title? Max width and other information? And it's hard to realize where is the input starts and ends. There is no border or focus state on figma?
Maybe full width from the start next to the buttons?

**Comment by samitron7** [comment]
The page width dictates the width of the title and I thought I added this to figma but will double check and update here. Sorry for the delay.

**Comment by samitron7** [comment]
Figma flow [here]([url](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=9045%3A4)). Added max width and breakpoints. Removing the UX Needed label. Let me know if anything else is missing.

**Comment by barklund** [comment]
@samitron7, thanks for the design and details here.

1. Is there a design for the functionality behind the arrow/dropdown?
1. Should we implement just the input field without the arrow at first, or do we add the dropdown along with the new input field here?
1. If we implement the new input field, but not add the dropdown, should we still follow the design and leave the space for the arrow empty for now?

**Comment by samitron7** [comment]
@barklund The dropdown depends on what @o-fernandez says about adding cta inside the editor for actions like
1. Save as template
2. Make a copy
3. Rename (which just places the focus on the title field - some people may need this extra help)
4. Any other actions that is needed.

I have initially spec'ed these actions during the wireframe days :)

**Comment by o-fernandez** [comment]
Since we don't have specific actions to add to the dropdown for now, I'd favor implementing the new title design without the arrow at all. 

We can add the arrow later as needed, but for now, I think it's OK not to have it.

**Comment by samitron7** [comment]
@o-fernandez The location for Save as template is inside the dropdown to the title. It's a pretty common patten for design tools to have that action copied to renaming the title etc (as a dropdown).

**Comment by o-fernandez** [comment]
> @o-fernandez The location for Save as template is inside the dropdown to the title. It's a pretty common patten for design tools to have that action copied to renaming the title etc (as a dropdown).

Can we implement the drop down then as part of #223 ?  
Not sure we need it as part of this particular ticket, so trying to decouple if not necessary to do it now.

**Comment by swissspidy** [comment]
The middle ground here would be putting it behind a feature flag. That means we implement the dropdown already, but hide it until "Save as template" is a thing.

**Comment by samitron7** [comment]
@swissspidy sgtm

**Comment by barklund** [comment]
Current local implementation has these widths at different screen sizes (there are three buttons in the "real" editor vs two in Figma, thus they take up extra space):

| Height | Width | Regular | Hover | Focus
|-|-|-|-|-|
| Short | Wide | ![wide_regular](https://user-images.githubusercontent.com/637548/90296154-c3b30880-de58-11ea-8c25-17f2433c4710.png) | ![wide_hover](https://user-images.githubusercontent.com/637548/90296153-c31a7200-de58-11ea-8a17-9669c895bc52.png) |  ![wide_focus](https://user-images.githubusercontent.com/637548/90296152-c31a7200-de58-11ea-87de-5fed9517c54c.png) |
| Short | Medium | ![medium_regular](https://user-images.githubusercontent.com/637548/90296158-c44b9f00-de58-11ea-80e4-faa6f944d94b.png) | ![medium_hover](https://user-images.githubusercontent.com/637548/90296157-c3b30880-de58-11ea-9ce6-2687dc4077bc.png) | ![medium_focus](https://user-images.githubusercontent.com/637548/90296155-c3b30880-de58-11ea-9bed-421c73a11d8d.png) |
| Short | Narrow | ![narrow_regular](https://user-images.githubusercontent.com/637548/90296162-c4e43580-de58-11ea-98a4-77919f990d8d.png) | ![narrow_hover](https://user-images.githubusercontent.com/637548/90296160-c4e43580-de58-11ea-8442-d683ef81bdf8.png) | ![narrow_focus](https://user-images.githubusercontent.com/637548/90296159-c44b9f00-de58-11ea-9020-02c9ee56f764.png) |
| Tall | Wide | ![tall_wide_regular](https://user-images.githubusercontent.com/637548/90297104-72584880-de5b-11ea-9578-e11544678d95.png) | ![tall_wide_hover](https://user-images.githubusercontent.com/637548/90297102-72584880-de5b-11ea-8140-64dc322f80ee.png) | ![tall_wide_focus](https://user-images.githubusercontent.com/637548/90297101-71bfb200-de5b-11ea-96ef-a37d6f43c187.png)
| Tall | Medium | ![tall_medium_regular](https://user-images.githubusercontent.com/637548/90297108-73897580-de5b-11ea-94fb-096ab1306064.png) | ![tall_medium_hover](https://user-images.githubusercontent.com/637548/90297106-73897580-de5b-11ea-805b-9fde723e834e.png) | ![tall_medium_focus](https://user-images.githubusercontent.com/637548/90297105-72f0df00-de5b-11ea-9a45-90648d62aad9.png) |
| Tall | Narrow | ![tall_narrow_regular](https://user-images.githubusercontent.com/637548/90297100-71271b80-de5b-11ea-97ff-16e0ce862a7e.png) | ![tall_narrow_hover](https://user-images.githubusercontent.com/637548/90297112-74baa280-de5b-11ea-8fe5-7d794c5efdfc.png) | ![tall_narrow_focus](https://user-images.githubusercontent.com/637548/90297111-74220c00-de5b-11ea-8e4d-cc7c67b5e03f.png) |

@samitron7, can you confirm this implementation? The input field is pretty narrow in the medium view above, where there's quite a lot of space in general, but not enough for the full width version. Is that per design?

**Comment by samitron7** [comment]
@barklund Sorry for the late reply but I was trying to delay for a good reason. The new design system addresses a lot of these concerns (and this is probably the last thing you want to hear after all your hard work here!) but still not quite ready. If you want to put on a pause on this work, I'll make it a thing to finish the work for this with the design agency.

**Comment by barklund** [comment]
@bmattb @o-fernandez, pushing this one back to UX Needed for now.
