### ISSUE TITLE
Textbox Opacity field allows invalid values

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#4100]
## Bug Description

While the opacity field allows only values between 0 and 100, the opacity field for the textbox (background) has no such validation.

## Expected Behaviour

Both field should sanitize input the same way

## Steps to Reproduce

1. Insert text element
1. Choose "highlight" fill mode
1. Change colors and opacity for both text and text background

## Screenshots

<img width="259" alt="Screenshot 2020-08-19 at 17 20 44" src="https://user-images.githubusercontent.com/841956/90654235-73fd8400-e240-11ea-8cd7-7d386fb2bf72.png">

## Additional Context

- Plugin Version: current `main`
- Operating System: macOS
- Browser: Chrome 84

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #11391.

1. Added elements to the canvas (text, images, shapes, etc...)
2. Changed opacity for each element (especially text box) - values greater than 100 are set to 100, negative values are set to 0
