### ISSUE TITLE
Dashboard: Add copy story URL and open story URL in new tab options to story context menu

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#4101]
## Feature Description

Add two new context menu items to a story menu

1. Copy the story URL to the clipboard "Copy Story URL"
2. Open the story URL in a new tab "Open in new tab"

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

The ability to do the following via the context (three-dots) menu My Stories in Dashboard:

1. Copy the story URL to the clipboard 
2. Open the story URL in a new tab

**Comment by BrittanyIRL** [comment]
@csossi please see the PR description for more nuanced testing/acceptance: https://github.com/google/web-stories-wp/pull/4144

**Comment by csossi** [comment]
Verified in QA
