### ISSUE TITLE
Preview Story Templates on Hover

### ISSUE THREAD

**Issue by mechiragjain** [GoogleForCreators/web-stories-wp#4103]
## Feature Description

Preview the story by showing slides one by one when a user hovers over the template. This will make a user work simpler as he/she can view all the slides of the template on the Explore Template section only without going one level deep to specific template page.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Thanks for your feedback!

We're already working on implementing this, including previewing animations of the individual template pages. Just like you suggest, you'll be able to hover over the template and see all the pages one by one.

I recommend keeping an eye out for our future releases where this will be included.

Thanks again.
