### ISSUE TITLE
Animation: Group animations

### ISSUE THREAD

**Issue by mariano-formidable** [GoogleForCreators/web-stories-wp#4105]
**NOTE:** This story needs to be broken down into smaller stories before work begins.

---

We need to add the ability to apply/update/remove animations to groups of selected elements.  This will involve **Animation Panel** and **Animation Timeline** work (and possible touch other parts of the editor).

<img src="https://images.zenhubusercontent.com/5b35729a5b51b10bd4dd5fd1/e784f266-ce96-471a-8c24-7e9f8a26c540" width="400">

Refer to the [figma designs](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=2%3A47073) for more information.

---

**NOTE:** This story needs to be broken down into smaller stories before work begins.

**Comment by bmattb** [comment]
@o-fernandez  candidate for an Epic, no?

**Comment by o-fernandez** [comment]
> @o-fernandez candidate for an Epic, no?

Agree! @mariano-formidable I turned this into an Epic. We can file all the sub-tickets as part of this epic and then move the point estimates out of the Epic into the issues. LMK if you need help with this.

**Comment by o-fernandez** [comment]
This particular item, grouping animations, is not part of the MVP requirements for shipping animatinos. Will remove from 1.2
