### ISSUE TITLE
Hovering over videos in the gallery causes them to load immediately, which is HUGELY wasteful

### ISSUE THREAD

**Issue by diegovar** [GoogleForCreators/web-stories-wp#4110]
Today, hovering over videos in the gallery causes them to load the preview immediately, which is very wasteful. We should introduce a delay so that hovering around the gallery doesn't suddenly trigger the download of so many videos at the same time.

**Comment by swissspidy** [comment]
Did this go through UX or UAT in any form? There might be a need to tweak the delay here.

**Comment by diegovar** [comment]
> Did this go through UX or UAT in any form? There might be a need to tweak the delay here.

We're having a UX review next Thursday with Sam where I'm planning to fine tune this and the loading pill delay, among other things.
