### ISSUE TITLE
Snackbar message is unreadable

### ISSUE THREAD

**Issue by merapi** [GoogleForCreators/web-stories-wp#4114]
## Screenshots

![image](https://user-images.githubusercontent.com/21036224/90759151-554eca00-e2e0-11ea-9516-458765619259.png)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
This needs a Percy test for sure

**Comment by merapi** [comment]
> This needs a Percy test for sure

Looking for a good place for it.

It makes more sense to use https://docs.percy.io/docs/storybook (snapshot the isolated component) than `percy/puppeteer` (render the whole page and somehow trigger one of the snackbars).

WDYT @swissspidy ?

**Comment by swissspidy** [comment]
That's a good point. Something we should look into, and a ticket for that makes sense. Ot shouldn't block work on this issue though.

Adding a storybook story for snackbar notifications would be a good first step.

NB: The dashboard already has all of that. Bit of duplication here 🤔

**Comment by swissspidy** [comment]
This didn't go through UAT.

On `main` I currently get this:

<img width="521" alt="Screenshot 2020-08-31 at 17 12 04" src="https://user-images.githubusercontent.com/841956/91735817-21f81f00-ebad-11ea-8d61-e6d856e0d8c8.png">

@merapi Can you confirm this? If so, this needs a new follow-up ticket.

cc @bmattb

**Comment by merapi** [comment]
@swissspidy I can confirm (not sure what happened), fixing the message for the current bright background [here](https://github.com/google/web-stories-wp/pull/4295).

**Comment by csossi** [comment]
Verified in QA
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/5fbb9c70-f6a8-471b-a65f-72aad3ef353a)
