### ISSUE TITLE
Design the header image for the WordPress.org plugin page

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#4118]
As part of the release of the plugin to the WordPress.org plugin repository we will need to provide a number of assets to ensure that the plugin landing page is attractive & captivating.

example of such pages are:
https://wordpress.org/plugins/google-site-kit/
https://wordpress.org/plugins/amp/

Please provide a header image that will be displayed to users on the plugin page.

from https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/#plugin-headers:

> Plugin Headers #Plugin Headers
> Plugin headers are those images you see at the top of a plugin page:
> 
> Hello Dolly Header
> When designing your header image, keep in mind the use of international plugin directories. Some of these, like Hebrew and Arabic, use Right-To-Left (RTL) languages. In these cases, the title will be overlaid on the right hand side of the image, not on the left side. Design your banner such that the title can be in either position. As this may not work with all designs, you should create a different image for RTL pages with -rtl in the name.
> 
> Filenames #Filenames
> Normal Banner: banner-772x250.(jpg|png)
> Normal Banner (RTL): banner-772x250-rtl.(jpg|png)
> High-DPI (Retina): banner-1544x500.(jpg|png)
> High-DPI (Retina RTL): banner-1544x500-rtl.(jpg|png)
> If RTL images are available, then they will be displayed on plugin pages in languages that use RTL. For example of an RTL image, look at Custom WP Login in English and then in Arabic.
> 
> For an example of Retina images, check out Hello Dolly or Pluginception. You cannot use the retina image alone, it only works as an “add-on” to the 772×250 image. The larger ‘retina’ image is only used on displays that can show the higher detail.

**Comment by swissspidy** [comment]
@samitron7 To summarize:

- Use **1544x500** (**PNG** or **JPEG**) for the banner on WordPress.org (but if we have a bigger original image that would be great)
- Create a “flipped” version for **right-to-left** languages of that same 1544x500 banner

**Comment by samitron7** [comment]
Banners! Let me know if anything is missing.
![banner-772x250-rtl](https://user-images.githubusercontent.com/10889431/92560594-89eedb00-f227-11ea-9f4d-8304a041f0e2.png)
![banner-772x250](https://user-images.githubusercontent.com/10889431/92560611-8f4c2580-f227-11ea-9611-f0e0867e7b60.png)
![banner-1544x500-rtl](https://user-images.githubusercontent.com/10889431/92560622-93784300-f227-11ea-9dd6-0f9a566d6598.png)
![banner-1544x500](https://user-images.githubusercontent.com/10889431/92560637-98d58d80-f227-11ea-87ee-a46ca0e30991.png)

**Comment by swissspidy** [comment]
@samitron7 The larger images don't have a period after "ever". Is that on purpose? Note that I'll need to use these hi-res versions

**Comment by swissspidy** [comment]
@samitron7 Minor nit: the editor in a RTL context would be flipped too. Example:

<img width="1680" alt="Screenshot 2020-09-09 at 10 13 11" src="https://user-images.githubusercontent.com/841956/92572723-17ace380-f285-11ea-9814-0479214e8171.png">

Is that easy to do for this banner? If not, we can leave it for now.

**Comment by samitron7** [comment]
@swissspidy The period are all removed (we don't need them) and I swapped the panels for RTL. Let me know if you see anything else.

![banner-1544x500-rtl](https://user-images.githubusercontent.com/10889431/92659111-9a956480-f2ac-11ea-8687-bc4d25d148ba.png)
![banner-1544x500](https://user-images.githubusercontent.com/10889431/92659115-9bc69180-f2ac-11ea-9e7c-38b33d319a5b.png)


![banner-772x250](https://user-images.githubusercontent.com/10889431/92659107-99fcce00-f2ac-11ea-8e9f-ada6241a04db.png)

![banner-772x250-rtl](https://user-images.githubusercontent.com/10889431/92659100-979a7400-f2ac-11ea-9e6b-6e5afd5540be.png)

**Comment by swissspidy** [comment]
Excellent, thanks!
