### ISSUE TITLE
Design the plugin icon image for the WordPress.org plugin page

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#4119]
As part of the release of the plugin to the WordPress.org plugin repository we will need to provide a number of assets to ensure that the plugin landing page is attractive & captivating.

example of such pages are:
https://wordpress.org/plugins/google-site-kit/
https://wordpress.org/plugins/amp/

Please provide the plugin icon image for the plugin

from: https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/#plugin-icons
> Plugin Icons #Plugin Icons
> Plugin icons are square images that show on the side of the plugin in searches on WordPress.org but also on the back-end of WordPress.org.
> 
> Akismet with it's Plugin Icon
> In addition to JPG and PNG formats, you can also use SVG. Vectors are perfect for icons, as they can be scaled to any size and the file itself is small. If you chose to use SVGs, you must also use a PNG icon as a fallback, otherwise your plugin icon will not display properly in older browsers or on Facebook.
> 
> If you do not use an icon, an auto-generated one will be made for you. Some examples are the circled icons below:
> 
> Example of auto-generated icons
> Top ↑
> 
> Filenames #Filenames
> Normal: icon-128x128.(png|jpg)
> High-DPI (Retina): icon-256x256.(png|jpg)
> SVG: icon.svg
> There are no plans to change these sizes.

**Comment by swissspidy** [comment]
@samitron7 To summarize: we need a square SVG icon for this

**Comment by samitron7** [comment]
![icon-128x128](https://user-images.githubusercontent.com/10889431/91912319-ba52da00-ec67-11ea-9a76-08783d40d6e9.png)
![icon-256x256](https://user-images.githubusercontent.com/10889431/91912320-baeb7080-ec67-11ea-973f-1942a24f47a6.png)
[Link](https://drive.google.com/file/d/1XwvB42n-bMRHGmeU1EP-cQU1GhDACCo5/view?usp=sharing) to SVG since it's not a supported file

**Comment by swissspidy** [comment]
@samitron7 Sweet, thanks! I suppose we could use that for the WordPress admin menu icon as well (without the background color of course)?

**Comment by bmattb** [comment]
moved to Sprint Backlog

**Comment by samitron7** [comment]
@swissspidy For the WordPress admin menu icon, I need to generate the negative icon for you all. @bmattb @swissspidy you guys know if a SVG will do?

**Comment by swissspidy** [comment]
@samitron7 yes, svg please
