### ISSUE TITLE
Provide the Intro post for the support forum on the WordPress.org plugin page

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#4122]
The plugin’s support forums will be available at https://wordpress.org/support/plugin/web-stories/.

Please provide an Introductory post for the support forum (A read this first post) that would seed the forum . Here is an example https://wordpress.org/support/topic/read-first-welcome-to-the-site-kit-support-forums/

![Screen Shot 2020-08-20 at 11.36.44 AM.png](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/319e407e-8a59-483d-853c-fc556d2bfead)

**Comment by bmattb** [comment]
Can i get confirmation that @ernee is owning this task?

**Comment by LuckynaSan** [comment]
Hey Matt, I will be owning this task.

**Comment by bmattb** [comment]
Thanks!
