### ISSUE TITLE
Text element: Allow selecting part of text and set bold/underline/italic

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#413]
## Feature Description

Allow setting a selected part of the text to be bold, italic, or underline.

Note that the functionality for selecting part of the text is already functional via keyboard, by selecting part of the text and using Cmd+b/u/i.

This also needs to be available via sidebar and be reflected in the front-end, too.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

- User can select part of the text in the Text element and set it to bold, italic or/and underline (both via keyboard -- already functional -- and via sidebar)
- The same selection can have one/multiple rules assigned.
- Front-end displays the selected rules as expected.

**Comment by samitron7** [comment]
The behavior whether you're using keyboard shortcut or the side bar (design panel) should be identical. That is if i select a single word from the text element and hit CMD + B or hit the bold button in the design panel, the result should be the same (ie  only bold the text that was selecte)d

**Comment by miina** [comment]
@pbakaus This was split out from https://github.com/google/web-stories-wp/issues/284 as discussed in Slack, didn't add any labels to it by default, however, should it move to the current Sprint (as the "parent" issue) and get the P0 label?

Let me know or just feel free to assign.

**Comment by pbakaus** [comment]
yes please.
