### ISSUE TITLE
Enable Dashboard Settings

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#4132]
## Feature Description

Work for the settings page in the dashboard has been being done behind a feature flag. This includes the ability to:
- navigate to the settings view _when_ the user has the role of admin (otherwise settings does not show up at all in the dashboard navigation or as an available route) 
- Assuming user has the role of 'admin', the ability to read and update their google analytics id for stories 
- Assuming user has the role of 'admin', the ability to add and remove publisher logos 

Further work necessary that's already known: 
- https://github.com/google/web-stories-wp/issues/3809
- https://github.com/google/web-stories-wp/issues/3810
- https://github.com/google/web-stories-wp/issues/3811
- https://github.com/google/web-stories-wp/issues/4150
- https://github.com/google/web-stories-wp/issues/4149
- https://github.com/google/web-stories-wp/issues/4148
- https://github.com/google/web-stories-wp/issues/4147

What I want to call out as UAT is done: 
- I added a loading screen to the publisher logos upload container that doesn't have designs or anything like it that I could rely on, it just says 'loading...' 
- We have no way of telling when an action is successful other than the data being there, which is tricky with the google analytics id update since you hit 'enter' to submit the data. 

## Alternatives Considered

N/A

## Additional Context
Work here is very light for implementation but I suspect it will take QA and UAT both a bit of time, for what it's worth with estimating. 

This ticket is a check in that this page is turning out correctly since it has yet to have QA or UAT done on it as it's behind a feature flag but it's quite robust and should be given some time. 

I deviated from the original designs a bit to keep continuity with the dashboard structure - using shared layouts for things like header and main body gutters with the idea that with the new design system these will be updated. 
https://docs.google.com/document/d/1Xs4uOZ3KCNlTMdjDT6q7cvTUpA1xk-kzrnVLQALltQk/edit#

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
- User can navigate to settings as an admin 
- User can read their google analytics id
- User can update their google analytics id (click enter in input, tbd on a better way to get this across) 
- User can read their existing publisher logos 
- User can remove an existing publisher logo
- User can add a new publisher logo 

## Implementation Brief

- Implement the `enableSettingsView` flag

**Comment by csossi** [comment]
Testing in 4152

Verified in QA

Note: Doesn't appear for non-admin (as expected):
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/ca25508d-bbfb-474d-9945-9f9c834707cb)

**Comment by BrittanyIRL** [comment]
Summary from quick meeting 8/26/2020 w/ @o-fernandez , @samitron7 , @bmattb , @BrittanyIRL 

From my list above, these are the tickets to complete before making settings visible: 
- #4149 
- #3810 - we still need a way to indicate how to submit, but I forgot to mention that we can add a success toast on successful update. Sam will get me updated input specs. 
- Sam will get me the designs for #3811 and then it should also be implemented. 

Everything else will come in future releases.
