### ISSUE TITLE
FTUE sample story in editor

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#4137]
Instead of #2909, for Stable we will ship with a Sample Story that serves as FTUE which is in the editor when installed.

**Comment by swissspidy** [comment]
Previously explored this in #2845, which kinda works, but doesn't solve important aspects:

* Just like the templates, the sample story needs to be **versioned** & automatically updated/migrated so it always works correctly
* The sample story needs to be **translatable**

Also, it requires product brief for how viewing that story should work. Can users edit it? Publish it?

**Comment by samitron7** [comment]
@o-fernandez @pbakaus This is more if a product question here. Given the short amount of time we have left, are we still considering doing everything @swissspidy is asking? Moving to product brief column.

**Comment by o-fernandez** [comment]
@pbakaus can chime in, but I think the idea is that this would just be a story pre-loaded that we'd ship with for now. Users can do anything they want with it, similar to any other story. No need to treat it specially like a template. 

In the future, we will probably build real FTUE into the product and not use the story.

**Comment by pbakaus** [comment]
The reality is that @swissspidy is outlining the MVP. We can't bundle a story that loads in the editor and *not* do the things above. The editor will break. Thus, AFAIK the easiest would be to make this a hidden user story. For that to work, the following is required:

1. Add hidden attribute to story JSON structure, which, if present, doesn't show it in the template gallery, sitemap, or anywhere else WP is concerned
2. Build the story, and bundle its JSON with the plugin, so right when the db structure is generated, it is put in
3. In editor code, check whether the `hidden` attribute is set, then disable the save button/functionality

If this makes it hard to make the story translatable, maybe we have to do a hidden template instead.

**Comment by swissspidy** [comment]
> Thus, AFAIK the easiest would be to make this a hidden user story.

This approach would only really help with the versioning part, as that is done by the editor when loading the story.

But our migration tool is quite simple to use and works well for stories, templates, and text sets. It wouldn't take much effort to add migration/versioning to the FTUE story.

> If this makes it hard to make the story translatable, maybe we have to do a hidden template instead.

It **does** make it hard to translate indeed. We'd need to translate it before displaying to the user, as multiple users can use different languages that aren't the same as the language at the time of insertion into the db.

Note that templates are currently not translatable either, so making it a hidden template would not really make a difference.

----

To cover translation and migration, I see one viable path that would work and not take too much effort.

1. We maintain 1 JSON file for the FTUE story. The text elements in it would contain placeholder texts.
1. This JSON file can be automatically versioned & migrated using our migration tool. It will always be up-to-date. Just like our templates.
1. In PHP, we parse the JSON file, and replace the placeholder texts with the actual translatable/translated texts.
1. This JSON file is passed as the story to the editor.
1. A "readonly"/"hidden" flag is added to the JSON file. If present, the save button in the story (and perhaps other functionality) would be disabled

**Comment by pbakaus** [comment]
> > Thus, AFAIK the easiest would be to make this a hidden user story.
> 
> This approach would only really help with the versioning part, as that is done by the editor when loading the story.
> 
> But our migration tool is quite simple to use and works well for stories, templates, and text sets. It wouldn't take much effort to add migration/versioning to the FTUE story.
> 
> > If this makes it hard to make the story translatable, maybe we have to do a hidden template instead.
> 
> It **does** make it hard to translate indeed. We'd need to translate it before displaying to the user, as multiple users can use different languages that aren't the same as the language at the time of insertion into the db.
> 
> Note that templates are currently not translatable either, so making it a hidden template would not really make a difference.
> 
> To cover translation and migration, I see one viable path that would work and not take too much effort.
> 
> 1. We maintain 1 JSON file for the FTUE story. The text elements in it would contain placeholder texts.
> 2. This JSON file can be automatically versioned & migrated using our migration tool. It will always be up-to-date. Just like our templates.
> 3. In PHP, we parse the JSON file, and replace the placeholder texts with the actual translatable/translated texts.
> 4. This JSON file is passed as the story to the editor.
> 5. A "readonly"/"hidden" flag is added to the JSON file. If present, the save button in the story (and perhaps other functionality) would be disabled

SGTM, but I will also say, you could just as well do this for all templates, and make this one a special template or something :) We need the templates to be translatable in the future.

**Comment by swissspidy** [comment]
> SGTM, but I will also say, you could just as well do this for all templates, and make this one a special template or something :) We need the templates to be translatable in the future.

Very true, but wouldn't we in the future load templates from an API instead of bundling them? Then the solution would likely look different.

**Comment by pbakaus** [comment]
> > SGTM, but I will also say, you could just as well do this for all templates, and make this one a special template or something :) We need the templates to be translatable in the future.
> 
> Very true, but wouldn't we in the future load templates from an API instead of bundling them? Then the solution would likely look different.

Oh yes, good point. Nevermind!

**Comment by bmattb** [comment]
@swissspidy - Can you confirm if you can take this on and reassign ?

**Comment by swissspidy** [comment]
@bmattb I don't really have the capacity to start working on this until Monday or so, so I doubt I would have time to do this for 1.0. I can certainly help with the WordPress & migrations parts of this, but aspects like the readonly-treatment can be easily worked on by other pods.

**Comment by samitron7** [comment]
@swissspidy Can you list out the details of what needs to be done here so we can reassign. On UX side, I will created the story and provide the link to the published story.

**Comment by swissspidy** [comment]
As discussed with @barklund on Slack, and in https://github.com/google/web-stories-wp/issues/4137#issuecomment-683630334, this works very similar to how we store the templates. 

And I think we can probably use #2845 as a starting point to make things easier.

**Versioning / Migration**
This seems to be as easy as updating `bin/commander.js` to call `updateTemplates('includes/data');`

**Translations**

In PHP, after loading the JSON file, we do a search/replace on the story to replace all texts with translated texts.

**Assets**

The assets URLs in the JSON file will be fixed using search/replace as well.

The assets need to be part of the ZIP file, which could make it quite big.

**Making the story readonly**

I think this step _could_ be optional, but let's try to do it nonetheless.

We can add a "readonly" flag to the JSON blob (just like it has `version`.

If present, we disables saving, previewing, autosaving, publishing, uploading, changing authors.

-> @barklund If you could take a stab at this, that would be good.

**Alternatives Considered**

We don't do the loading, translation, and assets stuff in PHP, but instead load the story JSON blob using basically `assets/src/dashboard/templates/getTemplates.js`

Bug I don't think this should be a concern of the editor.

**Comment by swissspidy** [comment]
@samitron7 is this demo story already finished or in progress? would be good to have something to work with.

@pbakaus Does the demo story have to be readonly? If I compare it with Gutenberg for example, users can save & publish the demo post just like any regular post. Removing this requirement would simplify this a lot.

**Comment by pbakaus** [comment]
> @samitron7 is this demo story already finished or in progress? would be good to have something to work with.
> 
> @pbakaus Does the demo story have to be readonly? If I compare it with Gutenberg for example, users can save & publish the demo post just like any regular post. Removing this requirement would simplify this a lot.

I'm completely OK not making it readonly if that makes things simpler.

**Comment by samitron7** [comment]
@swissspidy  I just got done laying down the scaffold and animation but need to make visual tweaks. 
published version [here](https://stories-new-wordpress-amp.pantheonsite.io/stories/tips-to-make-the-most-of-web-stories/)

**Comment by swissspidy** [comment]
@samitron7 Thank you! Could you provide some ETA for when you think that work will be done? We need to prepare all the content for translation and make it work in the plugin. We can't do that until the content is finished.

**Comment by samitron7** [comment]
@swissspidy I'll have it done by EOD tomorrow and will ping you.

**Comment by samitron7** [comment]
Completed. Here's the [link](https://stories-new-wordpress-amp.pantheonsite.io/stories/tips-to-make-the-most-of-web-stories/)

**Comment by swissspidy** [comment]
@csossi See #2845 for testing instructions

**Comment by o-fernandez** [comment]
When I deactivate the plugin and activate it, and click on the FTUE story link I get this
https://google.github.io/web-stories-wp/beta/tips.html
![image](https://user-images.githubusercontent.com/13389997/93806206-d0283f00-fc16-11ea-8d86-dcf346acadd2.png)
@swissspidy Know why this may be?

**Comment by swissspidy** [comment]
@o-fernandez Looks like the deployment here didn't work... Let me deploy manually real quick.

**Comment by swissspidy** [comment]
@o-fernandez Please try again

**Comment by o-fernandez** [comment]
Now that works. Thanks!
