### ISSUE TITLE
Add relevant data to Site Health screen

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#4139]
## Feature Description

To be able to better support our users, we need some data points in Site Health related to stories.

Filter `debug_information` to add:

* libxml version (see https://github.com/ampproject/amp-wp/blob/be84e8a2fb8def6b1831656d2067b268e70c959c/src/Admin/SiteHealth.php#L524-L528)
* `WEBSTORIES_DEV_MODE` value 
* `WEBSTORIES_CDN_URL` value
* List of active experiments

Filter `site_status_test_php_modules` to include `mbstring` (see https://github.com/ampproject/amp-wp/blob/be84e8a2fb8def6b1831656d2067b268e70c959c/src/Admin/SiteHealth.php#L661-L664)

Filter `site_status_test_result` to mark the `https_status` test status as critical if its current status is recommended (see https://github.com/ampproject/amp-wp/blob/be84e8a2fb8def6b1831656d2067b268e70c959c/src/Admin/SiteHealth.php#L535-L555)

## Additional Context

Here's how the AMP plugin does it:

https://github.com/ampproject/amp-wp/blob/dce58640f7c36befda67b145d00ec4f40c2278eb/src/Admin/SiteHealth.php#L447-L450

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

* Create a new `Site_Health` class in the `Admin` namespace

**Comment by spacedmonkey** [comment]
Could we also add a REST API call to the status check api as a site health check.

**Comment by spacedmonkey** [comment]
I would also add themes that have theme supports for web stories in the info.

**Comment by swissspidy** [comment]
> Could we also add a REST API call to the status check api as a site health check.

Hmm good suggestion. Could this perhaps be added to the existing REST API check?

> I would also add themes that have theme supports for web stories in the info.

Not sure. The current theme name is already available and might be enough. But can't hurt to add a simple `current_theme_supports` check.

**Comment by csossi** [comment]
Verified in QA
