### ISSUE TITLE
Dashboard Settings: Publisher Logo Dimension Check

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#4147]
## Feature Description
When a new publisher logo is added we should check that it is the proper dimensions. If it is not at least 96px x 96px a warning should show. 

## Additional Context
#2747
https://docs.google.com/document/d/1Xs4uOZ3KCNlTMdjDT6q7cvTUpA1xk-kzrnVLQALltQk/edit#heading=h.g8j12riqi2ft

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
Only images that are 96px x 96px or larger should be accepted as publisher logos on the settings view 

## Implementation Brief
- We can either check this locally or in the settings API when a new logo is added.

**Comment by BrittanyIRL** [comment]
@o-fernandez - just confirming that this is something we want for 1.0 - stable since it's something we want to do on the backend and will require workspace time. This dimension check is not currently something that's in place in the editor either when you set publisher logos there.

**Comment by o-fernandez** [comment]
> @o-fernandez - just confirming that this is something we want for 1.0 - stable since it's something we want to do on the backend and will require workspace time. This dimension check is not currently something that's in place in the editor either when you set publisher logos there.

We could delay the check, but should at least **tell** users that we recommend 96x96px publisher logos.

**Comment by BrittanyIRL** [comment]
<img width="1032" alt="Screen Shot 2020-08-26 at 1 04 26 PM" src="https://user-images.githubusercontent.com/10720454/91351208-c4269a00-e79c-11ea-815d-29990eb3fc7c.png">


Does this suffice for now?

**Comment by csossi** [comment]
Verified in QA
