### ISSUE TITLE
Dashboard Settings: Ability to crop publisher logos

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#4148]
## Feature Description

When a user uploads a logo ensure it is cropped to be a perfect square, a user may crop the image during upload.

## Additional Context

- https://docs.google.com/document/d/1Xs4uOZ3KCNlTMdjDT6q7cvTUpA1xk-kzrnVLQALltQk/edit#

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
- User has ability to crop an image to perfect square during upload

## Implementation Brief
Right now, the settings view in dashboard doesn't use the media uploader that wordpress has natively that's harnessed in the editor. I'm not super sure how we want to go about this.

**Comment by swissspidy** [comment]
Related: #8067 

We could leverage the same for the Dashboard too. Publisher logo selection/upload would open the WordPress media modal for selection & cropping.

**Comment by BrittanyIRL** [comment]
Since this is cropping media, @swissspidy should it be considered media related or dashboard related for pod assignment since you guys officially took over media recently?

**Comment by swissspidy** [comment]
Good question! I'll assign to WP pod for now.

**Comment by swissspidy** [comment]
Totally forgot that logos can be uploaded via drag & drop.

If we want to use the WordPress media modal, perhaps we should remove the drag & drop feature? Else, how would the cropping be done after dropping? (unless we build a super custom solution for the cropping)

cc @spacedmonkey

**Comment by BrittanyIRL** [comment]
oh good catch!! 
I think removing the drag and drop for consistency in upload would make sense. As WordPress users, it's the customary pattern to uploading media. Just my 2 cents.

**Comment by spacedmonkey** [comment]
Now the there is the ability to crop images built into the WordPress media library, https://github.com/google/web-stories-wp/issues/7337 becomes more useful
