### ISSUE TITLE
Dashboard Settings: Warn user when deleting a logo

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#4149]
## Feature Description
Warning if deleting a logo - User trying to “delete” an existing publisher logo should be warned that this will remove the logo from any existing stories using that logo. 

## Additional Context

https://docs.google.com/document/d/1Xs4uOZ3KCNlTMdjDT6q7cvTUpA1xk-kzrnVLQALltQk/edit#

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

- User is warned that removing logo will remove it from any existing stories using that logo

## Implementation Brief

- Do we want this to be a dialog that must be confirmed to process delete? Text that's readable on the page if there's logos set?

**Comment by BrittanyIRL** [comment]
Prep work is done here, just needs updated language to use for dialog: https://github.com/google/web-stories-wp/tree/feature/4149-warn-before-remove-logo

**Comment by BrittanyIRL** [comment]
<img width="568" alt="Screen Shot 2020-08-28 at 9 42 22 AM" src="https://user-images.githubusercontent.com/10720454/91592063-cca0e100-e912-11ea-9e9d-f716206a0f64.png">

@o-fernandez if you can help with what copy should look like for this dialog I can get this task wrapped up today!

**Comment by o-fernandez** [comment]
> <img alt="Screen Shot 2020-08-28 at 9 42 22 AM" width="568" src="https://user-images.githubusercontent.com/10720454/91592063-cca0e100-e912-11ea-9e9d-f716206a0f64.png">
> 
> @o-fernandez if you can help with what copy should look like for this dialog I can get this task wrapped up today!

I'm not the best at copy, so I think what you have is fine. I'd suggest adding a bit more text on the impact: 
"Are you sure you want to remove this logo? This will affect any stories that currently use it as their publisher logo."

**Comment by csossi** [comment]
Verified in QA
