### ISSUE TITLE
Encoding of special characters broken on frontend

### ISSUE THREAD

**Issue by Dennis-95** [GoogleForCreators/web-stories-wp#4166]
## Bug Description

Special characters like àòù'ì doesnt works after beta2 update

## Expected Behaviour

Show fonts special characters
## Steps to Reproduce

Open 1 webstory like https://claudia-makeup.com/stories/recensione-snap-shadow-cadet-webstory/

## Screenshots

![Cattura](https://user-images.githubusercontent.com/45852903/90932219-760d4180-e3fe-11ea-95ae-66c592c82349.PNG)

## Additional Context

Tested on windows10 chrome, windoes10 firefox, one plus 5t android 10 with chrome, and firefox

- Plugin Version: beta2

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by ernee** [comment]
@Dennis-95 thanks for reporting! 

I see validation errors on the story, which looks like you are experiencing [this issue](https://github.com/google/web-stories-wp/issues/4140). It occurs on certain server configurations. 

Could you download this in-development version of the plugin which fixes the validation errors: 

[web-stories.zip](https://github.com/google/web-stories-wp/files/5111575/web-stories.zip)

Let us know if  the special characters issue persists with this version.

**Comment by Dennis-95** [comment]
> @Dennis-95 thanks for reporting!
> 
> I see validation errors on the story, which looks like you are experiencing [this issue](https://github.com/google/web-stories-wp/issues/4140). It occurs on certain server configurations.
> 
> Could you download this in-development version of the plugin which fixes the validation errors:
> 
> [web-stories.zip](https://github.com/google/web-stories-wp/files/5111575/web-stories.zip)
> 
> Let us know if the special characters issue persists with this version.

Thanks a lot! I tried to install this version but the problem seems persist

**Comment by ernee** [comment]
@Dennis-95 thanks for your reply!

So the validation errors are now gone, but I also still see the issue with the special characters. 

Did you create this story with one of the provided templates? If so, which one?

**Comment by Dennis-95** [comment]
> @Dennis-95 thanks for your reply!
> 
> So the validation errors are now gone, but I also still see the issue with the special characters.
> 
> Did you create this story with one of the provided templates? If so, which one?

I used fresh and bright template, but also on stories made from 0 like https://claudia-makeup.com/stories/come-truccare-occhi-verdi-webstory/ seems not working

Thanks a lot!

**Comment by Dennis-95** [comment]
is there a way to fix the problem? Do you suggest to revert the beta1?

**Comment by swissspidy** [comment]
@Dennis-95 No, we do not recommend downgrading. While we are working on addressing this rare issue for affected users, please try this in-development version and let us know if you see any changes. Download: [web-stories.zip](https://github.com/google/web-stories-wp/files/5112377/web-stories.zip)

**Comment by swissspidy** [comment]
At the same time I suggest talking to your hosting provider to upgrade your version of PHP and specifically the libxml version used by PHP.

**Comment by Dennis-95** [comment]
> At the same time I suggest talking to your hosting provider to upgrade your version of PHP and specifically the libxml version used by PHP.

I downloaded your plugin version and updated the php, now the problem seems fixed, thanks!
