### ISSUE TITLE
Image stretching

### ISSUE THREAD

**Issue by andrewtsymbal** [GoogleForCreators/web-stories-wp#4172]
## Bug Description

I have created a web story, but after a short period of time, I noticed that my images stretched and cropped.
Since it looks not good, I have tried to update it. But when I'm trying to use the same image from the media library it placed already cropped and stretched.

## Screenshots

https://i.imgur.com/WQt8B8F.png

## Additional Context

- Plugin Version: 1.0.0-beta.2
- Operating System: Windows
- Browser: Chrome, Opera, Firefox

---

**Comment by andrewtsymbal** [comment]
When I double click on the [image it looks good](https://i.imgur.com/GyBCODL.png), as it should.
But then I back to the editor it's [cropped and stretched](https://i.imgur.com/WrNjxFz.png)
Have no idea how to adjust it.

**Comment by LuckynaSan** [comment]
Hi there, thank you for reporting this issue. Could you share your stories URL and we can look into this further?

**Comment by andrewtsymbal** [comment]
Sure, here is a [Story URL](https://3dfplans.com/blog/stories/camper-van-design/). The story was created with beta 1 version and this stretching and cropping happened after plugin update to beta 2 version.

**Comment by LuckynaSan** [comment]
@andrewtsymbal Thanks for the details! 

- Could you also share the image file you uploaded into the media library?

As an aside I noticed your Web Story URL has an [AMP validation error](https://jmp.sh/RVwoweW) (e.g. custom Javascript error) occurring that's associated with the WP Rocket caching plugin. Could you [exclude the "/stories/" URL in your settings](https://jmp.sh/UeiMrTT) from optimization on those posts under Advanced Rules > Never Cache URL(s).

**Comment by andrewtsymbal** [comment]
@LuckynaSan 
I have [excluded "/stories/"](https://i.imgur.com/Bmx3jJx.png) from the caching.
Here are links to the original images:
[image 1](https://3dfplans.com/wp-content/uploads/2020/08/Ford-transit-web-story-01.jpg)
[image 2](https://3dfplans.com/wp-content/uploads/2020/08/Ford-transit-web-story-02.jpg)
[image 3](https://3dfplans.com/wp-content/uploads/2020/08/Ford-transit-web-story-03.jpg)

Also, when I check the [story URL ](https://3dfplans.com/blog/stories/camper-van-design/) the [Validation Status is PASS](https://i.imgur.com/N4zWePP.png)

But when I check ["/stories/"](https://3dfplans.com/blog/stories/) directory and the [blog post URL](https://3dfplans.com/blog/ford-transit-custom-motorhome-3d-design/) both of them have FAIL status.

Should I do something with it or google see only the story itself, [this one](https://3dfplans.com/blog/stories/camper-van-design/)?

**Comment by kyuumeitai** [comment]
Yep, it happens on stories made with previous beta.1 plugin. It adds height to images stretching it in Y axis (height), it seems that is related to safe zone calculations.

**Comment by andrewtsymbal** [comment]
Any update on this?

**Comment by swissspidy** [comment]
Heya, thanks for the nag. We're still looking into this! Unfortunately I can't give you any specific update or anything.

Perhaps you could help me with one thing while we're at it:

If you create a new story from scratch with the same images, does this still happen? Or does it only affect stories created with the previous version?

**Comment by andrewtsymbal** [comment]
I will do the test and let you know.

**Comment by ernee** [comment]
@andrewtsymbal we just released version 1.0.0-rc.1 which should be available as an update. There is a fix that may resolve the issue you experienced. Could you update and let us know if it helps?

**Comment by andrewtsymbal** [comment]
After update to 1.0.0-rc.1 [images in the editor](https://i.imgur.com/xIKhpSr.png) looks good. 
When I click [Preview in the Editor](https://i.imgur.com/yovyUHQ.png) they also look good.

But the published version still has [stretched images](https://i.imgur.com/CXfC6YT.png) 
I have cleared the website cache and tested it in the different browsers.
Also, the mobile version doesn't work - [images are not appearing](https://i.imgur.com/tL7JmoY.png)

You can test the [Story](https://3dfplans.com/blog/stories/camper-van-design/) link yourself

**Comment by andrewtsymbal** [comment]
An **update for mobile**
on iOS [images are not appearing](https://i.imgur.com/tL7JmoY.png)
on Android [images also stretched ](https://i.imgur.com/OdoFrp5.png)

**Comment by swissspidy** [comment]
@andrewtsymbal have you tried re-saving the published story? The markup won‘t be updated otherwise

**Comment by andrewtsymbal** [comment]
@swissspidy under re-save do you mean [press update](https://i.imgur.com/NTdojts.png)

**Comment by andrewtsymbal** [comment]
Yes, now it looks good on mobile and web!

**Comment by swissspidy** [comment]
Yes, that's what I meant.

Great to hear everything is working now!
