### ISSUE TITLE
Beta 2 update no change, no animations

### ISSUE THREAD

**Issue by wecommaix** [GoogleForCreators/web-stories-wp#4174]
## Request

Hi, I saw that plugin got updated to Version 1.0.0-beta.2.
I read the changelog and I can see you implemented animations and many new features.

However, after updating, the interface of plugin is exactly the same as before and I can't see the new features.

I tried two things : I updated the plugin on my website AND to install it on a fresh wordpress, same problem.

Maybe I am wrong. Are the functionalities wrote in changelog took effect ?

Thanks for your help !

## Additional Context

- Plugin Version: Version 1.0.0-beta.2
- Operating System: PC, Windows
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Hi there

Animations are not finished yet, so you won‘t see them in the editor just yet.

This beta includes lots of small UX improvements abd bug fixes though.

**Comment by wecommaix** [comment]
Hi Pascal,

Thanks for your quick feedback !
I am impatient to see those news.

**Comment by Tobe2d** [comment]
@swissspidy thanks for the clarification... it was driving me crazy... what was I missing! Until I found the answer here...

I can't wait to see the Animations inside web story's editor... Hope the wait is not long ;-)
