### ISSUE TITLE
Beta 2 - Broken images, weird text editing behaviour (line duplication, mirage text)

### ISSUE THREAD

**Issue by quadcom** [GoogleForCreators/web-stories-wp#4176]
## Bug Description

So I was informed by a client that the page I directed them to was not working. Upon checking the pages in the editor, images that were in the gallery were showing as missing (broken image). Also, while changing text, a line lower on the page was duplicated higher up on the page but in reality, that text wasn't really there. It was covering up some other text underneath it. Deleting that text was deleting the actual text on that line. (Sorry best I could describe what I saw happening. It was truly f'd up hence the 'mirage' text description)

## Expected Behaviour

Just reporting odd issues. Images shouldn't be showing as missing if they are in the gallery.

## Steps to Reproduce

Unsure

## Screenshots

I missed the opportunity to grab shots. I will for next time.

## Additional Context

- Plugin Version: 1.00Beta2
- Operating System: Win10
- Browser: Chrome (latest)
- WP5.5 w/WPMigrate installed
- PHP php74rc

Downgraded to 1.00Beta1 and those problems resolved.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by ernee** [comment]
@quadcom thanks for reporting!

1) If possible could you send us a URL of the story and perhaps a recording of what you experience? You can use something like [Recordit](https://recordit.co/) to capture a screencast of the issues. 

2) When you create a new story does the issue persist?

**Comment by dmitry-christie** [comment]
@quadcom is your client using Cloudflare or LiteSpeed cache?

**Comment by quadcom** [comment]
No, I'm the client. It's my own site.

One thing I have to add is I moved the site from torontoheadshot.com/m to m.torontoheadshot.com. That move caused Google Site Kit to completely implode which was causing major issues just loading stories in the editor. I keep getting fatal errors pop up. 

I had to completely remove Site Kit and reinstall it and then go and reconnect all the services. Once that was done Stories started working ok again. Not sure where the connection is between Site Kit and Stories.

While I was able to get the story opened in the editor. I had to replace the broken images in the pages and I haven't seen the issue pop up since so I can't say 100% what the cause of the problem was. I wish I could.

I will add {off topic} that while I do like the main stories gallery layout. I often find myself going to list view and then WordPress list view so that I can get to both the view link and to adjust SEO focus keyword settings provided by Rankmath. There's also no place to provide or adjust and SEO details for the story.

**Comment by ernee** [comment]
@quadcom thanks for these details! It looks like we were also troubleshooting your site in [this issue](https://github.com/google/web-stories-wp/issues/3546) previously. For Site Kit, it relies on your [WordPress site settings](https://i.imgur.com/MkFLF0E.png) to determine where your site is located and where to place code snippets. 

There is automatic compatibility with Site Kit and Web Stories, so when both are activated and configured the Analytics tracking for Web Stories will be applied to Web Story URLs given that the location of the site is defined in the WordPress settings (in your previous case it appears you may have had a redirect on the URL where your stories were located which could affect the way Site Kit works). 

> There's also no place to provide or adjust and SEO details for the story.

This is on our radar and implementation can be tracked in the following issues: 

https://github.com/google/web-stories-wp/issues/490
https://github.com/google/web-stories-wp/issues/3134

Note that Web Story URLs provide default metadata (SEO and Social), so are valid out of the box and soon to be customizable.
