### ISSUE TITLE
Category container is really big when no media is shown.

### ISSUE THREAD

**Issue by ezxyz** [GoogleForCreators/web-stories-wp#4177]
![Screen Shot 2020-08-21 at 12.56.52 PM.png](https://images.zenhubusercontent.com/598a6729f8b79f8376e26cbc/fc73bed6-a01f-463a-9369-92ead6d06fac)

**Comment by diegovar** [comment]
This was most likely introduced in https://github.com/google/web-stories-wp/pull/4115. When we fix this, we should double check in Safari as flexbox apparently behaves quite differently there (this issue might not even be happening there!)
