### ISSUE TITLE
Dashboard: Borders on Template Detail Preview Cards are being cut off on the bottom

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#4183]
## Bug Description

Borders on the template detail preview cards are being cut off on the bottom.

## Steps to Reproduce

1. Visit the Explore Templates Page on Dashboard
2. Click the "View" button to see the Template Detail Page

## Screenshots

![screenshot_2020-08-22_at_12.16.14.png](https://images.zenhubusercontent.com/5ea09bca6a44046f869bafe0/e41e3c45-ddbd-489a-82bd-9d67ab20b82d)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA

**Comment by o-fernandez** [comment]
Looks so much better!
