### ISSUE TITLE
Prompt user to add a story title when publishing, if not set already

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#4184]
## Feature Description

If a user clicks on Publish, and have not set a story title, bring up a dialog box asking them to add a story title. 
Users should be strongly encouraged to set a good story title that's under 40 characters long per [quality guidelines](https://drive.google.com/corp/drive/folders/1dqPtjNTYN7OxTngWAYhy8zn8X3EuRTGJ)

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
