### ISSUE TITLE
Enforce adding canonical tag at all times

### ISSUE THREAD

**Issue by ernee** [GoogleForCreators/web-stories-wp#4193]
## Bug Description

Currently, when a site has [discouraged search engines from indexing](https://jmp.sh/A2nwere ) and has the [Yoast plugin](https://wordpress.org/plugins/wordpress-seo/) activated, the `<link rel="canonical" href="https://example.com" >` tag is removed from the Web Stories post when the `<meta name="robots" content="noindex">` tag is present. This can lead to a [validation error](https://jmp.sh/Bx8w9wP) on the post URL.

## Expected Behaviour

The canonical tag remains when the noindex tag is present and Yoast plugin is activated. 

## Steps to Reproduce

1) Discourage search engines from indexing the site 
2) Activate Yoast plugin
3) Visit story URL and see the canonical tag is not present with a validation error. 

## Additional Context

Removal of canonical tag when there is a noindex tag is [default Yoast plugin functionality](https://yoast.com/help/canonical-urls-in-wordpress-seo/#troubleshooting).

- Plugin Version: 1.0.0-beta.2
- Operating System: MacOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by igecorner** [comment]
Hi,

I am getting, "amp-story canonical error" in google webmaster tools, please advice

**Comment by swissspidy** [comment]
@igecorner please open a new support request and share as much information as possible. Include the URL to your story.
