### ISSUE TITLE
Snapshot components in isolation

### ISSUE THREAD

**Issue by merapi** [GoogleForCreators/web-stories-wp#4195]
## Feature Description

After the stable release, we should continue our effort for snapshotting components in isolation. https://github.com/google/web-stories-wp/pull/4145

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
This is a good time to reflect on our usage of Percy to see how beneficial it is for us.
