### ISSUE TITLE
Dashboard A11y: Story Menus - prevent focus on separators 

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#4197]
## Bug Description
Right now, using a keyboard in a story context menu on the dashboard, you can focus on the separator "lines" that break apart menus. These should not be focusable. 

## Expected Behaviour

Separator lines should not be focusable in story context menus. 

## Steps to Reproduce

Open a story's context men (the menu that pops open if you click on the three dots below a story in the grid or list view) and use the keyboard to go through menu items, see that separator lines are focusable.

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
Ready for review pending #4101 which has updated spacing that will help here. 
https://github.com/google/web-stories-wp/tree/a11y/context-menu-borders

**Comment by csossi** [comment]
Verified in QA (menu separator lines removed)
