### ISSUE TITLE
Dashboard A11y: List View - can't sort using keyboard

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#4199]
## Bug Description
Sorting My Stories in list view only works with a mouse. It should also work with a keyboard. 

## Expected Behaviour
Be able to sort list view of stories using keyboard.

## Steps to Reproduce

Navigate to Dashboard -> My stories -> list view, use keyboard to focus on table header and try to sort by a row using keyboard. 

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA

**Comment by o-fernandez** [comment]
This now works, but for some reason when I was tabbing through the table header was not showing so it was really confusing to see where the focus was. I think we should fix this in one of two ways: 
(1) always show the header tab and/or 
(2) when the focus is on a table row make sure that is in the display area / scroll to it. 

I think 2 is a bit tricky, but probably the right thing to do regardless. Having the focus be in a hidden part of the screen is confusing. 

Filed #4420 for this.
