### ISSUE TITLE
Story-only plugin build

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#42]
## Feature description

Dedicated plugin page on wp.org to get just "Stories" portion of plugin

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
Follow-up issues: #2, #3, #4.
