### ISSUE TITLE
Dashboard A11y: List View - Can't focus rows

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#4200]
## Bug Description

Right now the story list view in dashboard can't be focused/tabbed through with a keyboard. 

## Expected Behaviour

Be able to tab through rows of list view of stories. 

## Steps to Reproduce

Go to the Dashboard -> My Stories -> List View, tab through page, see that you can't get into the table. 

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

- fix should include updating karma tests

**Comment by csossi** [comment]
Verified in QA
