### ISSUE TITLE
Dashboard A11y: Story/Template Preview - can't pass focus to iframe

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#4204]
## Bug Description
If you preview a story/template IN the dashboard it's with an iFrame and focus isn't passed to the iFrame so you can't control the preview at all.

## Expected Behaviour

Pass keyboard focus to iframe. 

## Steps to Reproduce

Go to dashboard, preview a story or template (currently needs a feature flag enabled) and use keyboard to tab through, see that you can't focus in the iFrame. 

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
