### ISSUE TITLE
Telemetry: Add banner for user opt-in

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#4226]
## Feature Description

#3165 follow-up: implement banner asking new users to opt in to product usage data tracking

**[Banner design](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Stable-Release?node-id=180%3A216606)**

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
@samitron7 this is for the "banner"  portion of the telemetry opt-in. #3165 is for the settings field in the dashboard.

**Comment by o-fernandez** [comment]
Banner is here: https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Stable-Release?node-id=180%3A216606

**Comment by csossi** [comment]
Testing PR 4374 (Win10/Chrome)

Not seeing the banner in the QA environment. I deactivated the Web Stories plugin and reactivated. Are there different steps I should be taking?

**Comment by dmmulroy** [comment]
@csossi Do you have the Data Sharing Opt In checked on the Editor Settings page already?

**Comment by o-fernandez** [comment]
Saw the banner. Can't see settings, but I think that's because it's another PR, we should make sure both go together.

**Comment by dmmulroy** [comment]
> Saw the banner. Can't see settings, but I think that's because it's another PR, we should make sure both go together.

@o-fernandez  Is this considered QA Approved then?  I believe you're talking about #4152

**Comment by BrittanyIRL** [comment]
#4152 can be merged as soon as this is in, there's changes in here that we want before enabling settings.

**Comment by swissspidy** [comment]
The banner worked fine in my testing today, so I'd consider it QA approved
