### ISSUE TITLE
Fix focused state color for library navigation tabs

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#423]
## Bug Description

Currently library navigation tabs just use `action` color for showing focus. Once UX has decided, replace with proper color.

Current design without focus:
![Screen Shot 2020-02-27 at 2 29 16 PM](https://user-images.githubusercontent.com/637548/75479565-c171f600-596d-11ea-93e3-a42276cfb607.png)

Current design with focus:
![Screen Shot 2020-02-27 at 2 29 27 PM](https://user-images.githubusercontent.com/637548/75479566-c20a8c80-596d-11ea-858e-f18b7751959b.png)

Desired design with focus:
**TBD**

## Expected Behaviour

**TBD**

## Steps to Reproduce

1. Click a library tab
1. Press <kbd>tab</kbd> and then <kbd>shift</kbd> + <kbd>tab</kbd> to see tab with and without focus.

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by wassgha** [comment]
Closed by #544
