### ISSUE TITLE
Unable to Create Story From Template 

### ISSUE THREAD

**Issue by mediabooth** [GoogleForCreators/web-stories-wp#4231]
When trying to click "use template" blue button the action does not work and the follow error in a red box pops out from bottom right corner "Unable to Create Story From Template The response is not a valid JSON response."

<img width="1575" alt="Screen Shot 2020-08-26 at 4 17 29 pm" src="https://user-images.githubusercontent.com/70255572/91267899-a61a6300-e7b7-11ea-8ccd-fcbfd2b9b6b3.png">

**Comment by mediabooth** [comment]
A similar bug appears when trying to retrieve "My stories" Unable to Load Stories
The response is not a valid JSON response.

**Comment by LuckynaSan** [comment]
@mediabooth Thank you for reporting this. Could you check the Site Health (go to Tools -> Site Health -> Status) to see if it displays any messages about REST API?

Could you share the WordPress version/ PHP version that you can also find in the Site Health tab under Info? 

If you open developer tools in your browser (press F12) and check the Network tab, do you see any console errors when clicking on "Save draft"? Could you share a screenshot? You can use services like [Imgur](https://imgur.com/) or [Jumpshare](https://jumpshare.com/).

**Comment by Shamnadt** [comment]
I got similar issue and my Dashboard load nothing. I found a conflict with the plugin '**Asset CleanUp: Page Speed Booster**'. After deactivating that plugin, the Dashboard shows all Stories but the images not loading. 

My REST API is fine. I've Wordpress 5.5 and PHP 7.3.20.

The Chrome Console has this error: Unchecked runtime.lastError: The message port closed before a response was received.
Source: /wp-admin/edit.php?post_type=web-story&page=stories-dashboard:1

![My Stories ‹ Web Stories − WordPress - Google Chrome 30_08_2020 01_48_01 (2)](https://user-images.githubusercontent.com/3878477/91645504-17ca0980-ea63-11ea-97b3-ed764852795c.png)

**Comment by mediabooth** [comment]
@LuckynaSan Thanks for your replying. I've just checked Site Health and I see no error about RestAPI and the PHP version is 7.3.20. The problem didn't show up today, and I have no console error as well.

**Comment by LuckynaSan** [comment]
@Shamnadt @mediabooth Could you both try updating to Web Stories version 1.0.0-rc.1 that is now available. Please let us know if the issue persists.

**Comment by mediabooth** [comment]
Hi @Shamnadt, I've just updated and everything looks good. Actually, I didn't see more errors since our last interaction. I was thinking if the problems weren't on WordPress 5.5 instead on Stories.

**Comment by LuckynaSan** [comment]
Great to hear! I will close this issue. Thanks!
