### ISSUE TITLE
Page carousel compact mode showing drag indicators

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#4232]
## Bug Description
Drag indicators are shown in compact mode even though reordering is not enabled.

## Expected Behaviour
Drag indicators should not show in compact mode

## Steps to Reproduce
1. Add a few pages.
2. Resize the window so that compact mode would be shown for the page carousel
3. Try dragging the indicators around
4. See the drag indicators.

## Screenshots
![indicators](https://user-images.githubusercontent.com/3294597/91284215-e368fb80-e78b-11ea-9361-08707bf3466c.gif)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
Irrelevant as the compact carousel indicator doesn't exist anymore.
