### ISSUE TITLE
Make default background color for page background white

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#424]
## Bug Description

Generated stories currently have a gray default background color even though the editor works with a default white background color. IF explicitly set to white in the editor, only then will the generated story have a white background.

This behaviour has to be settled by UX.

## Expected Behaviour

**TBD**

## Steps to Reproduce

1. Create a new story and see a default white background on the canvas
1. Press preview and see a non-white background

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Didn't we settle for white default background here?

**Comment by pbakaus** [comment]
Let's not block on @samitron7 please, and make it white for now. She's swamped, if she disagrees then we can reopen.

**Comment by swissspidy** [comment]
I think it‘s white everywhere, so this could be closed

**Comment by miina** [comment]
Closing this as fixed (the default is white)
