### ISSUE TITLE
Add meta tags for creation tool name and version

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#4242]
## Feature Description

Meta tags to add: 
`amp-story-generator-name`: The name of the tool
`amp-story-generator-version`: The version of the tool

@swissspidy could you TAL when you're back? 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

Replace https://github.com/google/web-stories-wp/blob/f8c63ece3c67ed30061a1c5f47a3d82daf2979fa/includes/Story_Renderer/HTML.php#L161 with:

```html
<meta name="amp-story-generator-name" content="Web Stories for WordPress" />
<meta name="amp-story-generator-version" content="<?php echo esc_attr( WEBSTORIES_VERSION ); ?>" />
```

**Note:** Not translatable on purpose.

**Comment by swissspidy** [comment]
@o-fernandez We need to make sure any dashboards are updated accordingly now that this change has been implemented

**Comment by o-fernandez** [comment]
SG.
