### ISSUE TITLE
Dashboard: Template Detail View does not reload on hard refresh

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#4246]
## Bug Description

When you are on the template detail view and hard refresh the page it does not reload. This seems to be a regression. Unfortunately a Karma test would not work since refreshing the page disconnects the test runner.

## Expected Behaviour

The Template Detail View should reload on refresh.

## Steps to Reproduce

1. Visit Explore Templates on Dashboard
2. Click "View" on any Template
3. Refresh the browser

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
> Unfortunately a Karma test would not work since refreshing the page disconnects the test runner.

Could an E2E test work?

**Comment by csossi** [comment]
Verified in QA
