### ISSUE TITLE
Errors inside Search Console

### ISSUE THREAD

**Issue by durmonski** [GoogleForCreators/web-stories-wp#4253]
Hello guys,

I’ve installed the Google Web Stories Beta plugin and I submitted a story to test it.

Here's the story:
https://durmonski.com/stories/the-selfish-gene/

Sadly, I’m getting the following errors inside Google Search console:

1.
Tag ‘amp-story’ is not allowed to have any sibling tags (‘body’ should only have 1 child).
2.
A mandatory AMP HTML tag is missing from this document.
3.
Tag found outside the document head which is only allowed as a direct child of the document head.
4.
Only amp-boilerplate and amp-custom ‘style’ tags are allowed, and only in the document head.

I don’t have the AMP plugin installed. Should I? If yes, shouldn’t the Google stories run without the AMP plugin?

I posted this issue inside WordPress AMP forum, here:
https://wordpress.org/support/topic/errors-inside-search-console/#post-13318315

Your colleagues there said the following:

> Also, it appears there may be a compatibility problem with WP Rocket. You may want to mention this in your GitHub issue.

Can you please check?

Thanks!

Ivaylo Durmonski

**Comment by LuckynaSan** [comment]
@durmonski Thank you for submitting this issue! The reason why these errors occur is because the Web Story post is an AMP document. AMP is a framework built with its own optimizations. AMP documents must also adhere to [certain specifications](https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml/) in the code to be valid AMP. Search Console will flag the URL when valid code is being altered or invalid code is added.

> Also, it appears there may be a compatibility problem with WP Rocket. You may want to mention this in your GitHub issue.

Could you [exclude the "/stories/" URL](https://jmp.sh/UeiMrTT) in WP Rocket settings to prevent optimization on those posts under Advanced Rules > Never Cache URL(s).

**Comment by durmonski** [comment]
OK, thanks. I've excluded the stories.

So, I should add the AMP plugin if I want to use the stories? 

This part I didn't get.

**Comment by LuckynaSan** [comment]
You don't need to add the AMP plugin if you want to use Web Stories. 

I did notice your story URL showed some validation errors on the [AMP test results](https://search.google.com/test/amp?utm_source=gws&utm_medium=onebox&utm_campaign=suit&id=y9UxwmuNkl7-rrG7gxGiiw) that are like error messages occurring on [another issue ](https://github.com/google/web-stories-wp/issues/4166). Could you please try this in-development version and let us know if you see any changes. Download: 
[web-stories.zip](https://github.com/google/web-stories-wp/files/5138560/web-stories.zip)

**Comment by ernee** [comment]
Hi @durmonski ! Just following up that the most recent version 1.0.0-rc.1 contains a fix for the issue you experienced. Please let us know if updating the plugin resolves the validation errors you received in Search Console.

**Comment by ernee** [comment]
@durmonski the stable version of the plugin 1.0.0 has been released. I will close your issue now, but please feel free to update and reach out to us in our [WordPress.org support forum](https://wordpress.org/support/plugin/web-stories/) if you should still experience the issue. Happy to help!
