### ISSUE TITLE
Provide FAQ content for inclusion in plugin submission

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#4256]
## Task Description

An important section of any plugin readme file on wordpress.org is the FAQ section which is used to anticipate support questions for new plugin users before they happen. As such it would be good to have such a section within the stories plugin readme file

some tips on FAQ from [Smashing Magazine](https://www.smashingmagazine.com/2011/11/improve-wordpress-plugins-readme-txt/)

> Anticipate issues and answer them in advance.
> Deal with any known conflicts with old WordPress versions or other plugins.
> If a problem recurs in the support forums, add it to your FAQ.
> Use Markdown to highlight each question and follow it with an answer.
> Include any code snippets or shortcodes that the user might need.
> The FAQ is a tool to help you. Use it properly, and save some money on Aspirin.

More detail on the custom sections of the plugin readme files can be found at https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/#custom-sections

**Comment by bmattb** [comment]
@o-fernandez / @ernee is this something that @ernee can own?

**Comment by swissspidy** [comment]
Note that the FAQ section can cover product-related questions and not just support related things, so I don't think the support team should fully own this.

Also, we can just refer to the website if possible.

Some inspiration: https://wordpress.org/plugins/google-site-kit/

**Comment by ernee** [comment]
We have a working list of possible FAQs in our support sheet that can be cherry-picked for the most helpful tips as well.

**Comment by o-fernandez** [comment]
**[Draft doc for review within Microsite plan](https://docs.google.com/document/d/1JQ5i9V6jvR9iw0hLxQ87VxgXL1WYF8-vvV-58-SqUyg/edit?ts=5f616303#heading=h.5f3cmn7a9q85)**
