### ISSUE TITLE
Missing images (404)  + white screen in the stories dashboard on update to beta 2

### ISSUE THREAD

**Issue by dmitry-christie** [GoogleForCreators/web-stories-wp#4268]
## Bug Description
A couple of days ago I've updated the plugin to v1.0.0-beta2 from beta1. One of the editors reported that the stories dashboard was turning white a few seconds after the load. + the images were also missing within the editor. 

I'm posting this as one issue because I suspect that it is somehow linked to caching and compatibility with LiteSpeed server (one of our other websites has W3 cache and seems to be working fine). We're also using Cloudflare but caching is disabled within wp-admin section.

## Expected Behaviour

For the stories dashboard to load fully and the images not to be missing.

## Steps to Reproduce

Update the plugin and try to load the dashboard or edit one of the stories.

## Screenshots

[story editor](https://yadi.sk/i/RD4epndGulHTAQ)
[stories dashboard](https://yadi.sk/i/gI534ARdnSNj7Q)
[developer console](https://yadi.sk/i/GBZX5o8encIjpQ)
## Additional Context

- Plugin Version: beta 2

User 1:
- Operating System: Windows
- Browser: Chrome
User 2:
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by LuckynaSan** [comment]
@dmitry-christie Thanks for opening this issue. Do these errors occur after performing a hard refresh on Chrome (hold down Ctrl and click the Reload button / hold down Ctrl + Shift and click R)? 

Could you provide your [Site Health](https://i.imgur.com/Rtkmsba.png) Information so we can review your setup for anything that might be conflicting?

**Comment by jesusdlg** [comment]
I've the same issue.

![1](https://user-images.githubusercontent.com/26446642/91924521-922f9f00-ec98-11ea-87ad-3169b5bf2efc.jpg)
![2](https://user-images.githubusercontent.com/26446642/91924525-9360cc00-ec98-11ea-9db2-0fdb0a2ec103.jpg)

**Comment by dmitry-christie** [comment]
> @dmitry-christie Thanks for opening this issue. Do these errors occur after performing a hard refresh on Chrome (hold down Ctrl and click the Reload button / hold down Ctrl + Shift and click R)?
> 
> Could you provide your [Site Health](https://i.imgur.com/Rtkmsba.png) Information so we can review your setup for anything that might be conflicting?
Sure. Yes, hard refresh doesn't help.

```
### wp-core ###

version: 5.5.1
site_language: en
user_language: en
timezone: +00:00
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 20
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /var/www/html
wordpress_size: loading...
uploads_path: /var/www/html/wp-content/uploads
uploads_size: loading...
themes_path: /var/www/html/wp-content/themes
themes_size: loading...
plugins_path: /var/www/html/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-dropins (2) ###

advanced-cache.php: true
object-cache.php: true

### wp-active-theme ###

name: gcs (gcs)
version: 1.0.7
author: Underscores.me
author_website: http://underscores.me/
parent_theme: none
theme_features: core-block-patterns, automatic-feed-links, title-tag, post-thumbnails, menus, html5, custom-background, customize-selective-refresh-widgets, custom-logo, custom-header, widgets, editor-style
theme_path: /var/www/html/wp-content/themes/gcs
auto_update: Disabled

### wp-themes-inactive (1) ###

Twenty Nineteen: version: 1.7, author: the WordPress team,Auto-updates disabled

### wp-mu-plugins (1) ###

Local by Flywheel Live Link Helper: version: 1.1, author: Flywheel

### wp-plugins-active (45) ###

Accelerated Mobile Pages: version: 1.0.61.2, author: Ahmed Kaludi, Mohammed Kaludi (latest version: 1.0.62.2), Auto-updates disabled
ACF Content Analysis for Yoast SEO: version: 2.6, author: Thomas Kräftner, ViktorFroberg, marol87, pekz0r, angrycreative, Team Yoast (latest version: 2.7), Auto-updates disabled
ActiveCampaign: version: 7.1.3, author: ActiveCampaign (latest version: 8.0.1), Auto-updates disabled
Advanced Custom Fields PRO: version: 5.8.14, author: Elliot Condon (latest version: 5.9.0), Auto-updates disabled
Ajax Load More: version: 5.3.7, author: Darren Cooney, Auto-updates disabled
AMP Opt-in Forms: version: 1.9.20, author: AMPforWP Team, Auto-updates disabled
AMP Theme Framework: version: 1.0, author: AMPforWP Team, Auto-updates disabled
Better Search Replace: version: 1.3.3, author: Delicious Brains, Auto-updates disabled
Bloom: version: 1.3.10, author: Elegant Themes, Auto-updates disabled
Buttonizer - Smart Floating Action Button (Premium): version: 2.1.9, author: Buttonizer, Auto-updates disabled
Classic Editor: version: 1.6, author: WordPress Contributors, Auto-updates disabled
Code Embed: version: 2.3.3, author: David Artiss, Auto-updates disabled
Download Plugins and Themes from Dashboard: version: 1.7.0, author: Algoritmika Ltd, Auto-updates disabled
Easy Table of Contents: version: 2.0.11, author: Steven A. Zahm, Auto-updates disabled
Embed Plus for YouTube - Gallery, Channel, Playlist, Live Stream: version: 13.4, author: Embed Plus for YouTube Team (latest version: 13.4.1.1), Auto-updates disabled
EWWW Image Optimizer: version: 5.6.2, author: Exactly WWW (latest version: 5.7.0), Auto-updates disabled
Gravity Forms: version: 2.3.2.11, author: rocketgenius, Auto-updates disabled
Gravity Forms ActiveCampaign Add-On: version: 1.4.5, author: rocketgenius, Auto-updates disabled
HubSpot All-In-One Marketing - Forms, Popups, Live Chat: version: 7.39.5, author: HubSpot (latest version: 7.41.0), Auto-updates disabled
LeadDyno WordPress Plugin: version: 1.10.3, author: LeadDyno, Auto-updates disabled
LiteSpeed Cache: version: 3.4, author: LiteSpeed Technologies, Auto-updates enabled
Menu Image: version: 2.9.6, author: Rui Guerreiro (latest version: 2.9.7), Auto-updates disabled
Popup Maker: version: 1.11.1, author: Popup Maker (latest version: 1.11.2), Auto-updates disabled
Post Duplicator: version: 2.21, author: Metaphor Creations, Auto-updates disabled
Really Simple SSL: version: 3.3.4, author: Really Simple Plugins (latest version: 3.3.5), Auto-updates disabled
Recent Posts Widget With Thumbnails: version: 6.7.1, author: Martin Stehle, Auto-updates disabled
Responsive Menu: version: 3.1.30, author: ExpressTech, Auto-updates disabled
Shortcoder: version: 5.3.2, author: Aakash Chakravarthy, Auto-updates disabled
Simple 301 Redirects: version: 1.07, author: Scott Nellé, Auto-updates disabled
Simple 301 Redirects - Addon - Bulk CSV Uploader: version: 1.2.5, author: Webcraftic <wordpress.webraftic@gmail.com>, Ash Durham <plugins@kingpro.me>, Auto-updates disabled
Stripe Payments: version: 2.0.34, author: Tips and Tricks HQ, wptipsntricks (latest version: 2.0.35), Auto-updates disabled
Structured Content: version: 1.4.4, author: Gordon Böhme, Antonio Leutsch, Auto-updates disabled
TinyMCE Advanced: version: 5.5.0, author: Andrew Ozz, Auto-updates disabled
Webcraftic Disable Admin Notices Individually: version: 1.2.2, author: Webcraftic <wordpress.webraftic@gmail.com> (latest version: 1.2.3), Auto-updates disabled
Web Stories: version: 1.0.0-beta.1, author: Google, Auto-updates disabled
WP All Export: version: 1.2.7, author: Soflyy, Auto-updates disabled
WP File Manager: version: 6.5, author: mndpsingh287 (latest version: 6.9), Auto-updates disabled
WPML For AMP: version: 1.7.6, author: Ahmed Kaludi, Mohammed Kaludi, Auto-updates disabled
WPML Media: version: 2.5.5, author: OnTheGoSystems (latest version: 2.6.0), Auto-updates disabled
WPML Multilingual CMS: version: 4.3.16, author: OnTheGoSystems (latest version: 4.4.0), Auto-updates disabled
WPML String Translation: version: 3.0.12, author: OnTheGoSystems (latest version: 3.1.0), Auto-updates disabled
WPML Translation Management: version: 2.9.9, author: OnTheGoSystems (latest version: 2.10.0), Auto-updates disabled
WP Offload SES Lite: version: 1.4.3, author: Delicious Brains, Auto-updates disabled
WP Pusher: version: 3.0.5, author: WP Pusher, Auto-updates disabled
Yoast SEO: version: 14.7, author: Team Yoast (latest version: 14.9), Auto-updates disabled

### wp-plugins-inactive (1) ###

Smart Notification WordPress Plugin: version: 9.2.6, author: Smart IO Labs, Auto-updates disabled

### wp-media ###

image_editor: EWWWIO_Imagick_Editor
imagick_module_version: 1690
imagemagick_version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
file_uploads: File uploads is turned off
post_max_size: 16M
upload_max_filesize: 16M
max_effective_size: 16 MB
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 9.50

### wp-server ###

server_architecture: Linux 5.4.0-31-generic x86_64
httpd_software: LiteSpeed
php_version: 7.3.17-1+focal 64bit
php_sapi: litespeed
max_input_variables: 1000
time_limit: 0
memory_limit: 128M
admin_memory_limit: 256M
max_input_time: 60
upload_max_filesize: 16M
php_post_max_size: 16M
curl_version: 7.68.0 OpenSSL/1.1.1f
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.4.13-MariaDB-1:10.4.13+maria~focal-log
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /var/www/html/wp-content
WP_PLUGIN_DIR: /var/www/html/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

```

**Comment by jesusdlg** [comment]
### wp-core ###

version: 5.5.1
site_language: es_MX
user_language: es_MX
timezone: America/Monterrey
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/internetcreativo/public_html
wordpress_size: 832.23 MB (872653068 bytes)
uploads_path: /home/internetcreativo/public_html/wp-content/uploads
uploads_size: 164.38 MB (172366237 bytes)
themes_path: /home/internetcreativo/public_html/wp-content/themes
themes_size: 28.03 MB (29394450 bytes)
plugins_path: /home/internetcreativo/public_html/wp-content/plugins
plugins_size: 219.78 MB (230455928 bytes)
database_size: 44.37 MB (46524444 bytes)
total_size: 1.26 GB (1351394127 bytes)

### wp-dropins (1) ###

advanced-cache.php: true

### wp-active-theme ###

name: Avada Child (Avada-Child-Theme)
version: 1.0.0
author: ThemeFusion
author_website: https://theme-fusion.com
parent_theme: Avada (Avada)
theme_features: core-block-patterns, fusion-builder-options, title-tag, automatic-feed-links, custom-header, custom-background, woocommerce, wc-product-gallery-slider, wc-product-gallery-lightbox, post-formats, post-thumbnails, fusion-builder-demos, menus, align-wide, wp-block-styles, editor-styles, editor-font-sizes, widgets
theme_path: /home/internetcreativo/public_html/wp-content/themes/Avada-Child-Theme
auto_update: Desactivado

### wp-parent-theme ###

name: Avada (Avada)
version: 7.0.2
author: ThemeFusion
author_website: https://themeforest.net/user/ThemeFusion
theme_path: /home/internetcreativo/public_html/wp-content/themes/Avada
auto_update: Desactivado

### wp-themes-inactive (3) ###

Twenty Nineteen: version: 1.7, author: el equipo WordPress,Actualizaciones automáticas desactivadas
Twenty Seventeen: version: 2.4, author: el equipo WordPress,Actualizaciones automáticas desactivadas
Twenty Twenty: version: 1.5, author: el equipo WordPress,Actualizaciones automáticas desactivadas

### wp-plugins-active (27) ###

Accelerated Mobile Pages: version: 1.0.62.2, author: Ahmed Kaludi, Mohammed Kaludi, Actualizaciones automáticas desactivadas
Advanced Custom Fields PRO: version: 5.9.0, author: Elliot Condon, Actualizaciones automáticas desactivadas
Autoptimize: version: 2.7.7, author: Frank Goossens (futtta), Actualizaciones automáticas desactivadas
Avada Builder: version: 3.0.2, author: ThemeFusion, Actualizaciones automáticas desactivadas
Avada Core: version: 5.0.2, author: ThemeFusion, Actualizaciones automáticas desactivadas
Avada Custom Branding: version: 1.2, author: ThemeFusion, Actualizaciones automáticas desactivadas
Cloudflare: version: 3.5.1, author: Cloudflare, Inc., Actualizaciones automáticas desactivadas
Defender Pro: version: 2.3.1, author: WPMU DEV, Actualizaciones automáticas desactivadas
Duplicate Page: version: 4.3, author: mndpsingh287, Actualizaciones automáticas desactivadas
Duplicator Pro: version: 3.8.8.1, author: Snap Creek, Actualizaciones automáticas desactivadas
Hello Dolly: version: 1.7.2, author: Matt Mullenweg, Actualizaciones automáticas desactivadas
Loco Translate: version: 2.4.3, author: Tim Whitlock, Actualizaciones automáticas desactivadas
PWA: version: 0.5.0, author: PWA Plugin Contributors, Actualizaciones automáticas desactivadas
Quform: version: 2.12.0, author: ThemeCatcher, Actualizaciones automáticas desactivadas
Really Simple SSL: version: 3.3.5, author: Really Simple Plugins, Actualizaciones automáticas desactivadas
Schema Pro: version: 2.1.2, author: Brainstorm Force, Actualizaciones automáticas desactivadas
SEMrush SEO Writing Assistant: version: 1.1.1, author: SEMrush, Actualizaciones automáticas desactivadas
Slider Revolution: version: 6.2.22, author: ThemePunch, Actualizaciones automáticas desactivadas
Smush Pro: version: 3.6.3, author: WPMU DEV, Actualizaciones automáticas desactivadas
Snapshot Pro: version: 3.3.0, author: WPMU DEV, Actualizaciones automáticas desactivadas
Tawk.to Live Chat: version: 0.4.2, author: Tawkto, Actualizaciones automáticas desactivadas
WebP Express: version: 0.17.5, author: Bjørn Rosell, Actualizaciones automáticas desactivadas
Web Stories: version: 1.0.0-beta.2, author: Google, Actualizaciones automáticas desactivadas
WP-Optimize - Clean, Compress, Cache: version: 3.1.2, author: David Anderson, Ruhani Rabin, Team Updraft, Actualizaciones automáticas desactivadas
WPMU DEV Dashboard: version: 4.10.1, author: WPMU DEV, Actualizaciones automáticas desactivadas
WP Super Cache: version: 1.7.1, author: Automattic, Actualizaciones automáticas desactivadas
Yoast SEO Premium: version: 14.8, author: Team Yoast, Actualizaciones automáticas desactivadas

### wp-plugins-inactive (2) ###

Contact Form 7: version: 5.2.2, author: Takayuki Miyoshi, Actualizaciones automáticas desactivadas
LayerSlider WP: version: 6.11.1, author: Kreatura Media, Actualizaciones automáticas desactivadas

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1690
imagemagick_version: ImageMagick 6.9.10-68 Q16 x86_64 2020-04-01 https://imagemagick.org
file_uploads: File uploads is turned off
post_max_size: 16M
upload_max_filesize: 20M
max_effective_size: 16 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 62 GB
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 786432
	imagick::RESOURCETYPE_MAP: 62 GB
	imagick::RESOURCETYPE_MEMORY: 31 GB
	imagick::RESOURCETYPE_THREAD: 8
gd_version: bundled (2.1.0 compatible)
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 4.19-ovh-xxxx-std-ipv6-64 x86_64
httpd_software: Apache
php_version: 7.4.9 64bit
php_sapi: fpm-fcgi
max_input_variables: 1640
time_limit: 180
memory_limit: 256M
max_input_time: 60
upload_max_filesize: 20M
php_post_max_size: 16M
curl_version: 7.72.0 OpenSSL/1.1.1g
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.3.24-MariaDB
client_version: mysqlnd 7.4.9

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/internetcreativo/public_html/wp-content
WP_PLUGIN_DIR: /home/internetcreativo/public_html/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

**Comment by LuckynaSan** [comment]
@dmitry-christie Thank you for providing the Site Health info. It looks like Web Stories beta.1 is installed. Did the issue occur on beta.2 or did you downgrade to beta.1? 

> Web Stories: version: 1.0.0-beta.1, author: Google, Auto-updates disabled

The Site Health info provided appears to indicate all the plugins disabled. Do you have the [Health & Troubleshooting ](https://wordpress.org/plugins/health-check/)plugin enabled? Could you please try to only enable Web Stories beta.2 then activating plugins one by one to find the one causing the issue?

**Comment by dmitry-christie** [comment]
@LuckynaSan Thank you for your response. Yes, just to confirm that's what has happened. I had to downgrade since it's a live website and we're actually using the stories.
Ok, I've installed H&T plugin and will try to do that on a staging instance later this week.

**Comment by ernee** [comment]
@dmitry-christie many thanks for any information you can provide. We've also just released version 1.0.0-rc.1 which should now be available as an update. Feel free to try that as well to see if it resolves the issues mentioned. 

@jesusdlg it would be great to get your feedback if the update helps in your case too.

**Comment by dmitry-christie** [comment]
@ernee Done. It seems to be working now for me so far. Let's wait for @jesusdlg, just to be sure :)

**Comment by jesusdlg** [comment]
Hi,

FYI, I just installed the RC version and now it works fine for me.

Thank you!!

**Comment by ernee** [comment]
Really appreciate the follow up @dmitry-christie and @jesusdlg !
