### ISSUE TITLE
No files uploaded if only one file in group is invalid

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#4294]
## Bug Description

If I try to upload two PNG files and one MOV file, I get an error message saying that MOV files are not supported. No file is uploaded.

## Expected Behaviour

I expect the PNG files to be uploaded successfully, despite the MOV file being rejected.

## Steps to Reproduce

1. Try to upload a PNG file **and** an MOV file together, e.g. by drag & drop.
1. See error message
1. See that no files have been uploaded at all, not even the PNG file

## Additional Context

- Plugin Version: beta 2 / current `main`
- Operating System: macOS
- Browser: Chrome 84

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
I think this is fixed! 

@csossi can you just double check this in staging that if 1 file upload fails but you're uploading multiple at once and the others are fine that the ones that are valid do upload?

**Comment by csossi** [comment]
Verified in QA
