### ISSUE TITLE
Dashboard - My Stories

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#43]
## Feature description

Displays all user created stories, with support for pagination, ability to click into stories to preview and edit

**[Feature Brief - Epic: Dashboard](https://docs.google.com/document/d/1Xs4uOZ3KCNlTMdjDT6q7cvTUpA1xk-kzrnVLQALltQk/edit#heading=h.snvm6t5ev6rj)**

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pbakaus** [comment]
Another ticket so large that it is not actionable or useful. Closing for now. Let's file smaller, doable tickets.
