### ISSUE TITLE
TypeError: Cannot read property 'elements' of undefined (Editor Crashed)

### ISSUE THREAD

**Issue by Arjungoyal21** [GoogleForCreators/web-stories-wp#4307]
TypeError: Cannot read property 'elements' of undefined
    in StoryProvider
    in Unknown
    in SnackbarProvider
    in Unknown
    in HistoryProvider
    in Unknown
    in Media3pApiProvider
    in Unknown
    in APIProvider
    in Unknown
    in ConfigProvider
    in LL
    in ThemeProvider
    in StyleSheetManager
    in App
    in FlagsProvider

**Comment by LuckynaSan** [comment]
Hello @Arjungoyal21! Thanks for reporting this issue. What browser and browser version are you currently using, and on which operating system (Windows/Mac)?

**Comment by Arjungoyal21** [comment]
Google chrome browser / window 10

Something went wrong!

The editor has crashed. Please try reloading the page and report the error
using the button below.
Apologies for the inconvenience.

[image: image.png]

**Comment by LuckynaSan** [comment]
@Arjungoyal21 What version of chrome are you using? Chrome version can be located like the screenshot below:

![image](https://user-images.githubusercontent.com/66372350/92256962-71d33080-eea2-11ea-877d-a0e4e5575630.png)

**Comment by Arjungoyal21** [comment]
[image: chrome.png]

**Comment by swissspidy** [comment]
@Arjungoyal21 Images sent via email unfortunately don't work here on GitHub. Please upload images using the GitHub website, or write your version as text.

**Comment by LuckynaSan** [comment]
@Arjungoyal21 Plugin version 1.0.0-rc.1 is now available as an update. Could you please try to update to see if it resolves the issues?

**Comment by Arjungoyal21** [comment]
I updated the plugin but still it's causing same issue. When I ever I try
to do anything the editor crashes.

**Comment by swissspidy** [comment]
@Arjungoyal21 Does this still happen when disabling all other plugins and using one of the WordPress default themes like Twenty Twenty?

In addition to that, please share your Site Health info with us. You can copy the data from Tools -> Site Health -> Info -> "Copy site info to clipboard"

**Comment by LuckynaSan** [comment]
As we have not received a response on this issue, we will close it out. Please feel free to post a topic on the [Web Stories Support Forum](https://wordpress.org/support/plugin/web-stories/) if you continue to encounter any issues. Thanks!
