### ISSUE TITLE
Consider the right UX for updating the media3p search term

### ISSUE THREAD

**Issue by cvolzke4** [GoogleForCreators/web-stories-wp#4308]
Consider the right UX is for updating the search term, and then changing tabs with an updated search term. There are two behaviours:

1. Update search term and press enter, see new results in current tab.
2. With a new search term applied, change tabs to apply the search term in the new tab.

For each of #1 and #2, there are two options (both 1 and 2 are represented in each video):

a) Leave existing search results displayed, then slightly later refresh with new results:
https://share.getcloudapp.com/YEuoDXEZ

b) First remove search results, showing a blank space instead (or a loading pill near the top, or a spinner or something else):
https://share.getcloudapp.com/7KuLjpr9

**Comment by o-fernandez** [comment]
Given that we've shipped, let's keep it as it is and only change if necessary given user feedback. Will close this for now.
