### ISSUE TITLE
Stories Never Publish or Update with Text

### ISSUE THREAD

**Issue by letsbeus** [GoogleForCreators/web-stories-wp#4315]
When I go to create stories they never publish or save. I have experimented and found they do publish and update when only pictures are imported. Once I create a heading or any text box the plugin never saves or publishes.

**Comment by LuckynaSan** [comment]
@letsbeus Thank you for reporting this issue! 

- Can you please tell me what browser/browser version you are using along with the operating system (Mac/Windows)? 

- If you could share your [Site Health](https://i.imgur.com/Rtkmsba.png) information we can check if there are any issues on the plugin side. 

- If possible could you send us a recording of what you experience? You can use something like [Recordit](https://recordit.co/) to capture a screencast of the issues.

**Comment by LuckynaSan** [comment]
@letsbeus Plugin version 1.0.0-rc.1 is now available as an update. Could you please update the Web Stories plugin and let us know if the issue persists?

**Comment by LuckynaSan** [comment]
As we have not received a response on this issue, we will close it out. Please feel free to post a topic on the [Web Stories Support Forum](https://wordpress.org/support/plugin/web-stories/) if you continue to encounter any issues. Thanks!
