### ISSUE TITLE
Elements with links not working

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#4318]
## Bug Description

I added a link to an element but it gets removed when previewing the story.

I _think_ the issue is here:

https://github.com/google/web-stories-wp/blob/76cdad28a6897e1049f6a342e2a08d5edb3cb26f/assets/src/edit-story/output/page.js#L52-L62

This should probably be `! hasPageAttachment || !isElementBelowLimit(element)`

IMO this is a blocker for stable and definitely needs some unit tests.

## Expected Behaviour

Link should not disappear when previewing the final AMP output.

## Steps to Reproduce

1. Add a link to an element
1. Preview story
1. Notice that there's no link

## Additional Context

- Plugin Version: `main`
- Operating System: macOS
- Browser: Chrome 84

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Testing

I
1. Add a link
2. Verify that it shows up in the front-end (is clickable)

II
1. Add a link
2. Add a Page attachment
3. Ensure the link is outside of the Page Attachment area
4. Save and verify that the link shows up in the front-end as well

III
1. Add a link to the bottom of the page (needs to be in the Page Attachment area)
2. Add a Page attachment
3. Save and verify that the link is not clickable in the front-end

**Comment by csossi** [comment]
Verified in QA
