### ISSUE TITLE
Dragging an image from library to off-canvas shouldn't do anything

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#4319]
## Bug Description

If you drag an image already on the canvas fully out of the canvas, it'll be removed. But if you drag an image from the image library **on to** the workspace, but place it **fully outside** the canvas, it'll actually be placed there. It should just be ignored.

The same goes for shapes – and (in the near future) texts.

If you try to manipulate these elements, re-selecting them actually deletes them, as it's registered as a drag off-canvas.

Make sure to test this in both unit tests and integration tests.

## Expected Behaviour

* Don't add new elements if dragged in but remain fully outside the canvas
* Any such element drop should simply be ignored as if it never happened

## Steps to Reproduce

1. Start dragging an image from the image library
1. Drop it fully outside the canvas
1. Observe that an element is actually added

## Screenshots

![dragoff.gif](https://images.zenhubusercontent.com/5e9877d5cc796e8868614c8d/598b912d-5d48-4efd-9d45-2f7abc4c4b7d)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
The issue got fixed within #5512, however, will just add a test for it. Pulling into Sprint 46. FYI @bmattb @barklund
