### ISSUE TITLE
Apply form changes `onChange` instead of `onBlur`

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#432]
## Feature Description

As mentioned [on Slack](https://xwp.slack.com/archives/CCCAUAH6F/p1582912550180900), form changes in the design panel should apply immediately, and not just on `blur`.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

* Form changes in the design panel should apply `onChange`, and not just on `blur`, without losing any changes.

**Comment by dvoytenko** [comment]
I'm very much not in favor of this. Please block this item until we have an agreement. I'll close this issue. @swissspidy please reopen when you're back and we'll discuss.
