### ISSUE TITLE
Code quality: consider adding a linter warning if a file has more than X lines

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#4344]
## Feature Description
Files can get quite bloated which makes these hard to manage and hard to read and hard to review. Sometimes files need just small changes and it seems ok but various small changes happening all the time can get a file to be 500 lines without even noticing.

Perhaps we could agree on a `max-lines` limit to avoid this happening.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
cc @barklund @swissspidy WDYT?

**Comment by swissspidy** [comment]
I know Morten had some thoughts on file size in the past as styled components declarations are often the reason for long files.

Perhaps we could use `max-lines-per-function` instead of `max-lines`?

**Comment by swissspidy** [comment]
Handy command to sort files by line length:

```bash
find packages -name '*.js' -exec wc -l {} + | sort -rn
```

Closing though since it's not a priority
