### ISSUE TITLE
Test breaks in multisite

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#4353]
## Bug Description

When working on #4301 , I found that if I created a new site and switched to it in a test, many of the test would break for no reason. This breakable was unrelated to the change in hand. An example of these breakables could be found [here](https://github.com/google/web-stories-wp/runs/1072450694#step:12:43). 

## Expected Behaviour

New site can be created in unit tests and it just works.

## Steps to Reproduce

```
        /**
	 * @group ms-required
	 */
	public function test_init_sets_missing_options_multisite() {
		$blog_id = (int) self::factory()->blog->create();
		switch_to_blog( $blog_id );
		$this->assertSame( WEBSTORIES_DB_VERSION, get_option( \Google\Web_Stories\Database_Upgrader::OPTION ) );
		$this->assertSame( '0.0.0', get_option( \Google\Web_Stories\Database_Upgrader::PREVIOUS_OPTION ) );
		restore_current_blog();
	}
```

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Hmm this multisite test seems to work just fine:

https://github.com/google/web-stories-wp/blob/623f6e3b5ae40891a4599593840cd34cb33b08a8/tests/phpunit/tests/Story_Post_Type.php#L328-L349

**Comment by spacedmonkey** [comment]
Yeah, I saw that, it is weird. But for a start that test is wrong. 

This line, 
```
$blog_id = $this->factory->blog->create();
```
should be
```
$blog_id = self::factory->blog->create();
```

**Comment by swissspidy** [comment]
`$blog_id = $this->factory->blog->create();` still works thanks to a  magic getter in `WP_UnitTestCase_Base`. So that can't be it. Maybe something to do with the order of tests?

**Comment by spacedmonkey** [comment]
I think it might have something to do with permalink structure and on primary site the blog posts have a `/blog` base, not I am not sure that is it. 

It is a weird one for sure and I could not crack it. I think we would need https://github.com/google/web-stories-wp/issues/2562 for me to be able to really debug it.

**Comment by spacedmonkey** [comment]
After doing a little testing locally, if I re-enable this test, I get 5 fails and 20 errors. See https://github.com/google/web-stories-wp/runs/1199374258?check_suite_focus=true

I believe the issue is related to capabilities. By enabling this test, it somehow means that the web stories capabilities are  not added to the main site. Maybe because the site is reset or something. This makes sense of all the test fails here. It means are tests may not be valid and we should workout what does this and fix them, ASAP.

**Comment by swissspidy** [comment]
Seems like an issue with how the `activate` function runs on `wp_initialize_site`. If you can take a look next week  that'd be great. Just need to timebox it
