### ISSUE TITLE
TypeError: Cannot read property 'r' of undefined

### ISSUE THREAD

**Issue by manuel103** [GoogleForCreators/web-stories-wp#4354]
TypeError: Cannot read property 'r' of undefined
    in StylePresetPanel
    in Unknown
    in form
    in designPanel__Form
    in DesignPanel
    in DesignPanels
    in div
    in designInspector__TopPanels
    in div
    in designInspector__Wrapper
    in DesignInspector
    in div
    in inspectorContent__InspectorPane
    in section
    in inspectorContent__InspectorPanes
    in Inspector
    in div
    in inspectorLayout__InspectorContainer
    in section
    in inspectorLayout__Layout
    in InspectorLayout
    in div
    in dropTarget__Content
    in Unknown
    in div
    in dropTarget__DropTargetComponent
    in UploadDropTarget
    in Unknown
    in InspectorProvider
    in iU
    in LL
    in div
    in layout__InspectorArea
    in div
    in layout__WorkspaceLayout
    in Unknown
    in RichTextProvider
    in Unknown
    in UnitsProvider
    in Unknown
    in CanvasProvider
    in Workspace
    in div
    in layout__Area
    in section
    in layout__Editor
    in wU
    in Unknown
    in DropTargetsProvider
    in Unknown
    in TransformProvider
    in Unknown
    in MediaProvider
    in Unknown
    in FontProvider
    in Unknown
    in StoryProvider
    in Unknown
    in SnackbarProvider
    in Unknown
    in HistoryProvider
    in Unknown
    in Media3pApiProvider
    in Unknown
    in APIProvider
    in Unknown
    in ConfigProvider
    in LL
    in ThemeProvider
    in StyleSheetManager
    in App
    in FlagsProvider

**Comment by ernee** [comment]
@manuel103 thanks for reporting this error! 

1) Do you recall the last action you took before the error occurred? A screencast/video using a tool like [Recordit](https://recordit.co/) would be great.

2) Could you tell us which browser and the version you are using?

**Comment by manuel103** [comment]
Hello,
The error occurs when you try to select multiple layers from the layer navigator.
This happens from Google Chrome 64 bit version 85.0.4183.83.

**Comment by LuckynaSan** [comment]
Hello @manuel103 Can you confirm if this issue occurred when you used an existing template, or when you created a new story?

**Comment by ernee** [comment]
@manuel103 I experienced something similar using one of the templates (seen in #3544). Along with the question above do you recall approximately how many layers you were trying to select at a time? Thanks!

**Comment by manuel103** [comment]
The issue occurred while using an existing template (Fresh & Bright template) and I was trying to select 2 layers when the plugin crushed and threw the above error

**Comment by ernee** [comment]
@manuel103 thanks for the details!

**Comment by ernee** [comment]
Hi @manuel103! the stable version of the plugin 1.0.0 as been released, but it appears this issue still persists. This open issue will be used to address it: https://github.com/google/web-stories-wp/issues/3544 

 Please feel free to [subscribe to the issue](https://jmp.sh/rOFTITp) to keep up to date on its progress. I'll close your issue here, since we are providing support for the plugin in the [WordPress.org forums](https://wordpress.org/support/plugin/web-stories/) now. Please don't hesitate to reach out to us with any future questions or concerns there.
