### ISSUE TITLE
There is an invalid attribute or attribute value in the HTML tag

### ISSUE THREAD

**Issue by Dennis-95** [GoogleForCreators/web-stories-wp#4359]
## Bug Description

I've actually 24 stories on my websites, almost all builded in the same way.
2 of them, exactly https://claudia-makeup.com/stories/trucco-mascherina-webstory/ and https://claudia-makeup.com/stories/come-truccare-labbra-webstory/ i see the search console issue: "There is an invalid attribute or attribute value in the HTML tag"

## Expected Behaviour

No errors in GSC like other stories

## Steps to Reproduce

Test wesbtories on GSC

## Screenshots

![1](https://user-images.githubusercontent.com/45852903/92325159-9ff27500-f048-11ea-9b0e-d8aea44b3c1a.PNG)
![2](https://user-images.githubusercontent.com/45852903/92325160-a123a200-f048-11ea-8ff5-c5ff4349cd2c.PNG)

## Additional Context

N/D
- Plugin Version: 1 beta 2
- Operating System: windows 10
- Browser: chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Thanks for your report, @Dennis-95!

That markup definitely is incorrect. We'll take a look!

I see those are webp images. The webp image format is currently not natively supported by WordPress. Are you using a specific plugin to allow webp images? Perhaps you could share your Site Health info with us?

**Comment by swissspidy** [comment]
@Dennis-95 Could you try this development version to see if it fixes the issue for you? Download: https://github.com/google/web-stories-wp/suites/1153718827/artifacts/16652005

**Comment by Dennis-95** [comment]
> Thanks for your report, @Dennis-95!
> 
> That markup definitely is incorrect. We'll take a look!
> 
> I see those are webp images. The webp image format is currently not natively supported by WordPress. Are you using a specific plugin to allow webp images? Perhaps you could share your Site Health info with us?

Yes! I convert images into webp with https://shortpixel.com/
About health check, is there a way to share it privately?

> @Dennis-95 Could you try this development version to see if it fixes the issue for you? Download: https://github.com/google/web-stories-wp/suites/1153718827/artifacts/16652005

I will try!

**Comment by Dennis-95** [comment]
> @Dennis-95 Could you try this development version to see if it fixes the issue for you? Download: https://github.com/google/web-stories-wp/suites/1153718827/artifacts/16652005

I can't, i forgot to mention that i've a modified version of the plugin https://github.com/google/web-stories-wp/issues/4166
If i try to install yours the bug come back!

**Comment by swissspidy** [comment]
@Dennis-95 Please try this version then: https://github.com/google/web-stories-wp/suites/1161480146/artifacts/16836418

It contains this fix **and** #4166

**Comment by Dennis-95** [comment]
> @Dennis-95 Please try this version then: https://github.com/google/web-stories-wp/suites/1161480146/artifacts/16836418
> 
> It contains this fix **and** #4166

I tried to install it but #4166 bug persist!

**Comment by swissspidy** [comment]
@Dennis-95 My bad! Let's try it one more time with this version: https://github.com/google/web-stories-wp/suites/1161900271/artifacts/16848400

**Comment by Dennis-95** [comment]
> @Dennis-95 My bad! Let's try it one more time with this version: https://github.com/google/web-stories-wp/suites/1161900271/artifacts/16848400

Installed, #4166 bug seems fixed but GSC keep report this error: "Attribute "srcset" in the tag "amp-img" it's set  with "undefined undefinedw" not valid."

![Cattura](https://user-images.githubusercontent.com/45852903/92524960-485c3100-f223-11ea-946f-f0c25176a848.PNG)

Thanks a lot as always

**Comment by swissspidy** [comment]
@Dennis-95 try editing the story and saving it again.

**Comment by Dennis-95** [comment]
> @Dennis-95 try editing the story and saving it again.

It worked perfectly, thanks a lot!

**Comment by Dennis-95** [comment]
@swissspidy Hello, just a quick question, the new update v1.0.0-rc.1 (2020-09-10) includes this bug fix and #4166 bug fix?
can i safely update? Thanks a lot!

**Comment by swissspidy** [comment]
Yes

**Comment by Dennis-95** [comment]
After the last update i'm re-experiencing 3 errors on all my web stories:
1) Tag script AMP missing
2) HTML AMP missing
3) Javascript not allowed

I used for my screenshoots: https://claudia-makeup.com/stories/recensione-snap-shadow-cadet-webstory/
Do you know how can i fix this?
Thanks a lot!

![2](https://user-images.githubusercontent.com/45852903/94747100-7219fb00-037e-11eb-9496-4a6c7fa0b8a9.PNG)
![3](https://user-images.githubusercontent.com/45852903/94747101-734b2800-037e-11eb-94af-96c145e419be.PNG)
![1](https://user-images.githubusercontent.com/45852903/94747097-70e8ce00-037e-11eb-9e7d-c7f5f09ae0c9.PNG)

@swissspidy

**Comment by swissspidy** [comment]
Are you using WP Rocket or a similar plugin? You need to disable it or at least some of its modukes for stories URLs.

**Comment by Dennis-95** [comment]
Due to the url change from stories to web-stories wp rocket made the problem, now it's fixed thanks!

**Comment by Dennis-95** [comment]
> Are you using WP Rocket or a similar plugin? You need to disable it or at least some of its modukes for stories URLs.

Hello @swissspidy !
I tried to exclude all files from wp rocket optimization, in the first it worked but now the search console re.report the same problem in all my webstories
Can you please check if still wp rocket the problem?

Thanks a lot

**Comment by swissspidy** [comment]
Looking at the source code of https://claudia-makeup.com/web-stories/recensione-snap-shadow-cadet-webstory/ I still see WP Rocket being active there and minifying all JS, so yes, it's still WP Rocket causing this.

**Comment by Dennis-95** [comment]
I'm speaking with wp-rocket support to find a fix about this, i tried to avoid the minify on:

/wp-content/plugins/spreaker-shortcode(.*).js
/stories/(.*)
/web-stories/(.*)
/wp-content/plugins/web-stories/(.*).js
cdn.ampproject.org/amp-story-player-v0.js
/wp-content/plugins/attesa-pro/js/jquery.attesa-pro.min.js
/wp-content/plugins/web-stories/assets/js/(.*).js

/wp-content/plugins/web-stories/(.*).css
/web-stories/(.*)
/stories/(.*)
/wp-content/plugins/web-stories/assets/css/(.*).css

Bu it seems not working! I will update this with the solution provided from wp rocket! (i hope! )

**Comment by LuckynaSan** [comment]
Hi there @Dennis-95, thank you for the update! Could you try excluding stories URL from caching/ optimization in the Advance Settings like this [screenshot](https://jumpshare.com/v/XCh5zaSk91Dkf4bSBG6K)?

**Comment by Dennis-95** [comment]
> Hi there @Dennis-95, thank you for the update! Could you try excluding stories URL from caching/ optimization in the Advance Settings like this [screenshot](https://jumpshare.com/v/XCh5zaSk91Dkf4bSBG6K)?

It was exactly that option! Thanks a lot

**Comment by swissspidy** [comment]
Glad to hear that worked!

I'm closing this issue once again.

If you encounter any more issues, we recommend opening a thread in the [WordPress.org support forums](https://wordpress.org/support/plugin/web-stories/) as we're concentrating our support efforts on that platform.

PS. It would be amazing if you could [write a review](https://wordpress.org/support/plugin/web-stories/reviews/) for the plugin on WordPress.org :-)
