### ISSUE TITLE
Karma tests fail with "System limit for number of file watchers reached"

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#4364]
## Bug Description
Karma tests seem to fail with "System limit for number of file watchers reached" error which prevents the tests from running, for example:
<img width="1042" alt="Screenshot 2020-09-07 at 14 10 25" src="https://user-images.githubusercontent.com/3294597/92381631-85350480-f10b-11ea-84b0-649309f04e35.png">

See a [failing job](https://github.com/google/web-stories-wp/pull/4345/checks?check_run_id=1080743156).

## Expected Behaviour
Karma tests should fail only when an actual test fails.

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
This doesn't actually cause failures, as there seem to be successful runs despite the error message.

See https://github.com/google/web-stories-wp/runs/1084952934 for example

**Comment by miina** [comment]
Indeed. So it seems to be the disconnecting that causes failure.

**Comment by swissspidy** [comment]
Haven't encountered this in quite some time; closing for now
