### ISSUE TITLE
Web Stories as the new PowerPoint

### ISSUE THREAD

**Issue by agoza** [GoogleForCreators/web-stories-wp#4366]
## Feature Description

I am building an educational website and its main content will consist of PowerPoint-like slides that users can interact with to learn about a topic. Since Web Stories has quite similar properties with how presentation slides are, I'm wondering if it is possible, or if it is already supported for me to easily do the following:
- design a Stories page with multiple image layers per page
- animate transparent images' movement as separate layers that enter a page one by one to complete a bigger image (like building a steam engine train Lego)
- add a .gif layer for extra interactivity (e.g. smoke gif coming out from the train)
- from users side, every layer on that one page will appear with each mouse click/mouse scroll or tap/swipe on mobile
- downloadable Stories (like a whole PowerPoint presentation .ppt file, the page with animations will be downloaded along with other pages with words as a file of its own so users can study the material on their own phone/computer without having internet)

Please advise how can I perform the above in a WYSIWYG way or otherwise point me to the right pages so that I know how and what code to implement.

## Alternatives Considered

Hire a friend developer to design and animate all of the above whenever there is a new lesson to be posted. Or I can upload Microsoft PowerPoint slides instead. Users will visit the page only to download the files, and they will do so without ever interacting with the website. 

## Additional Context

PowerPoint is from Microsoft, Web Stories is from Google. PowerPoint files often require a paid product (Microsoft Office) or knowledge on its best alternatives. If this idea has its debut, the files should be readable in a reasonable format and accessible to everybody. It could well be the next textbook.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by ernee** [comment]
@agoza thanks for sharing your request and use case! There are a few things you can currently or will be able to do with Web Stories and others I'll forward over to the team for consideration:

> design a Stories page with multiple image layers per page

The editor supports adding multiple layers of various types (image/ video, text, shapes, etc) to a story page. You can reorder these layers via the _Design panel_. [Here's an example](https://jmp.sh/KmVeuaW) from a page from one of the available premade templates.

> animate transparent images' movement as separate layers that enter a page one by one to complete a bigger image (like building a steam engine train Lego)

Animation support is on the roadmap. [ Here's a reference](https://docs.google.com/document/d/11xtdVNrSa16qg9tmg_ACw6vTD8z8wymhkRSgOqkVCa8/edit#heading=h.m0pv6unnoqe) for what to expect in future updates.  

> add a .gif layer for extra interactivity (e.g. smoke gif coming out from the train)

The editor also supports the .gif media type as a layer. [Here's a reference](https://docs.google.com/document/d/1aZH_TI_be2t5Ywyqx4jcPTPdhFGEt7xh-uLzBp2AV4A/edit#) for how the media gallery works.

> from users side, every layer on that one page will appear with each mouse click/mouse scroll or tap/swipe on mobile

> downloadable Stories (like a whole PowerPoint presentation .ppt file, the page with animations will be downloaded along with other pages with words as a file of its own so users can study the material on their own phone/computer without having internet)

I'll share these with the team - great ideas!
