### ISSUE TITLE
Multi-selection causes error when at least one element is rotated

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#4368]
## Steps to Reproduce
1. Add two text elements
2. Rotate one of those
3. Select both
4. See the error

## Screenshots
<img width="404" alt="Screenshot 2020-09-07 at 17 21 23" src="https://user-images.githubusercontent.com/3294597/92397225-bff86600-f126-11ea-8d7c-4919a95be631.png">
<img width="540" alt="Screenshot 2020-09-07 at 17 21 14" src="https://user-images.githubusercontent.com/3294597/92397228-c25ac000-f126-11ea-99f4-c91fadec4e34.png">

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Testing Instructions
1. Add two elements
2. Rotate one of those
3. Verify that the design panel is not broken
4. Add a value to the X/Y field, e.g. 50. Now try to use arrow keys to change the value.
5. Verify that it's possible to change both X and Y values with arrow keys.

**Comment by miina** [comment]
Looks like the issue comes from trying to find min-max values for the X and Y panel, however, the calculation of the min-max value is assuming that only one element is selected, this causes `NaN` values.

I suppose the ideal case would be:
In case of multi-selection, for min value, taking reference from the element with the smallest real X/Y value, for the max-value, the largest

Started the implementation, will continue tomorrow.

**Comment by csossi** [comment]
Verified in QA
