### ISSUE TITLE
Leverage React Strict Mode

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#4370]
## Feature Description

I was wondering whether we should wrap all our React apps in `<StrictMode>` to help spot potential issues.

We can try wrapping of an individual app, or just parts of the tree. Depends on how many issues there are, and how we want to go about fixing them.

## Additional Context

Docs: https://reactjs.org/docs/strict-mode.html

Helpful blog post: https://kentcdodds.com/blog/react-strict-mode/

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
@barklund @carlos-kelly curious to hear your thoughts on this. Any experience with strict mode?

**Comment by spacedmonkey** [comment]
@swissspidy I would say that #4497 means this ticket is in progress. In my limited tests of the PR, it seem to work in my testing. 

From this [article](https://kentcdodds.com/blog/react-strict-mode), it seems as simple as the PR you introduced. It may have side effect.

We will also need add tickets for any issues this raises.
