### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'r.elements')

### ISSUE THREAD

**Issue by jimdhope** [GoogleForCreators/web-stories-wp#4373]
TypeError: undefined is not an object (evaluating 'r.elements')
    in StoryProvider
    in Unknown
    in SnackbarProvider
    in Unknown
    in HistoryProvider
    in Unknown
    in Media3pApiProvider
    in Unknown
    in APIProvider
    in Unknown
    in ConfigProvider
    in LL
    in ThemeProvider
    in StyleSheetManager
    in App
    in FlagsProvider

**Comment by jimdhope** [comment]
Just trying to upload a photo to the story editor from my media library. Happens every time I try and add an image

**Comment by LuckynaSan** [comment]
Thanks @jimdhope  for reporting your issue. Feel free to provide your [Site Health](https://i.imgur.com/Rtkmsba.png) Information so we can review your setup for anything that might be conflicting.

A screenshot or video can be helpful as well. You can use software like [Jumpshare](https://jumpshare.com/) to make a screenshot or https://recordit.co/ to make a video and share the link.

**Comment by LuckynaSan** [comment]
@jimdhope Plugin version 1.0.0-rc.1 is now available as an update. Could you please try to update to see if it resolves the issue?

**Comment by LuckynaSan** [comment]
As we have not received a response on this issue, we will close it out. Please feel free to post a topic on the [Web Stories Support Forum](https://wordpress.org/support/plugin/web-stories/) if you continue to encounter any issues. Thanks!
