### ISSUE TITLE
Media Library - Loading Bar

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#439]
## Feature Description

As an editor I want to know that media files are loading in the library (on initial load)

[Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=4644%3A299408)
![image](https://user-images.githubusercontent.com/5874851/79161311-43e13880-7da9-11ea-9bd8-a21b582889e8.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. When media files are loading in the library, a skeleton layout is shown

**Comment by jauyong** [comment]
@spacedmonkey is the skeleton layout insufficient in your opinion? Perhaps a video of the slow loading would better portray the issue?

**Comment by jauyong** [comment]
@samitron7 to update skeleton designs

**Comment by jauyong** [comment]
This is the current state which was reported as a bug. Since we have this ticket I am using it instead of filing a bug. 


![image](https://user-images.githubusercontent.com/5874851/79161514-9d496780-7da9-11ea-872c-6c1da8b0c31a.png)

**Comment by spacedmonkey** [comment]
Closed via #1430
