### ISSUE TITLE
Flaky Karma test: should apply formatting correctly for multi-style text field

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#4396]
The test for `CUJ: Creator Can Style Text: Apply B, Apply U, Apply I, Set text color, Set kerning` and `should apply formatting correctly for multi-style text field` is sometimes failing with the following error message:
<img width="1003" alt="Screenshot 2020-09-08 at 19 50 29" src="https://user-images.githubusercontent.com/3294597/92507993-273a1700-f208-11ea-939f-03ac8f09fc1f.png">

**Comment by swissspidy** [comment]
cc @barklund

**Comment by barklund** [comment]
@swissspidy, why was this moved to review? Mouseslip?

**Comment by swissspidy** [comment]
@barklund yep, mouseslip!

**Comment by bmattb** [comment]
duplicate of #3465 closing.
