### ISSUE TITLE
UX when uploading without upload permissions

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#440]
## Feature Description

As an editor with no upload rights, I want to be informed that I am not able to upload

In WP, not all users have the rights to upload media. 

**[Feature Brief - Epic: Media Gallery](https://docs.google.com/document/d/1aZH_TI_be2t5Ywyqx4jcPTPdhFGEt7xh-uLzBp2AV4A/edit#)**

Note: This requires #196 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
1. When logged in without upload rights, the upload button is grayed out (disabled)
2. When logged in without upload rights and the user tries to paste a file via keyboard, the upload is silently disabled (doesn't do anything)
3. When logged in without upload rights and the user trues to drag and drop a file, the upload is silently disabled (doesn't do anything)
4. When logged in without upload rights, the upload poster image button is grayed out (disabled)

**Comment by jauyong** [comment]
@spacedmonkey FYI the feature brief specifies a silent disable (doesn't do anything) for keyboard paste and drag and drop. During our call we discussed using the error messages (snackbar)

**Comment by spacedmonkey** [comment]
This ticket would like require https://github.com/google/web-stories-wp/issues/196 as this handles doing capability checks.
