### ISSUE TITLE
Consider decoupling feature releases from plugin releases

### ISSUE THREAD

**Issue by cvolzke4** [GoogleForCreators/web-stories-wp#4403]
## Feature Description

Consider decoupling feature releases (Unsplash, Coverr, Tenor) from plugin releases with the goal of:
1. Pragmatically in the short term, allow us to release with stable if there are non-ui blockers on our side before the Monday release cutoff.
2. Allow us to disable a provider if there is a prolonged outage or other issue.

There isn't a javascript API / HTTP endpoint available for backend feature discovery, so other teams have been creating their own API endpoints.

## Approaches considered

1. As a start, a feature endpoint can be added media.proto with a list of enabled features ('unsplashTab', 'tenorTab', 'coverrTab').
2. Later, we can add integrate the backend feature tooling to return enabled features (avoid hard coding).
3. Alternatively (or later), a new API can be added to provide a feature flag / experiments endpoint for Story Editor generally.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Better handling for cases where the API is not available makes sense, but I am wary of adding any feature flag API endpoints. That's a huge change and is ultimately a product decision. Also, and perhaps most importantly, we first need to ensure that this does not violate [WordPress.org guidelines](https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/).

**Comment by cvolzke4** [comment]
> Better handling for cases where the API is not available makes sense, but I am wary of adding any feature flag API endpoints. That's a huge change and is ultimately a product decision. Also, and perhaps most importantly, we first need to ensure that this does not violate [WordPress.org guidelines](https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/).

I mentioned this idea in standup as a pragmatic way to release sooner if we're still waiting for non-functional parts before Monday, and to provide a turn-down option later once the release is in an environment that we don't have control over.

It's probably too late for the Monday cutoff, but an implementation for media3p tabs wouldn't need to be baked in forever (so this wouldn't have to be a one-way door solution). If the WordPress guidelines allow it, a general-purpose way of toggling feature flags would be a good practice for feature development in Story Editor going forwards.

I had a read over the WordPress.org guidelines, which part do you see is relevant to feature hiding?

**Comment by swissspidy** [comment]
> I had a read over the WordPress.org guidelines, which part do you see is relevant to feature hiding?

I was specifically referring to this proposed item:

> Alternatively (or later), a new API can be added to provide a feature flag / experiments endpoint for Story Editor generally.

I'm wary about doing that. The guidelines are sometimes a bit vague, so I don't wanna make assumptions. We'd need to reach out to the plugins team first before doing anything in this regard.

Some sections that caught my eyes:

> Trialware is not permitted
> Plugins may not contain functionality that is restricted or locked, only to be made available by payment or upgrade. Functionality may not be disabled after a trial period or quota is met
> 
> Plugins may not send executable code via third-party systems.
> Executing outside code within a plugin when not acting as a service is not allowed
> Serving updates or otherwise installing plugins, themes, or add-ons from servers other than WordPress.org’s

Again, I don't wanna make assumptions. We just need to clarify these things before investing time in something like this.


----

Anyhow, we've now shipped, so I don't consider this a priority for now. Let's close it and consider it a "maybelater"

**Comment by swissspidy** [comment]
I got confirmation from the plugins team that this would be OK, but only on an opt-in basis by the user. And of course with all the code being already in the plugin (delivering executable code to the plugin from an external service would be a no-no)
