### ISSUE TITLE
TypeError: Cannot read property 'elements' of undefined

### ISSUE THREAD

**Issue by OpenCopyMike** [GoogleForCreators/web-stories-wp#4406]
TypeError: Cannot read property 'elements' of undefined
    in StoryProvider
    in Unknown
    in SnackbarProvider
    in Unknown
    in HistoryProvider
    in Unknown
    in Media3pApiProvider
    in Unknown
    in APIProvider
    in Unknown
    in ConfigProvider
    in LL
    in ThemeProvider
    in StyleSheetManager
    in App
    in FlagsProvider

Using theme: Divi 

Console:
Uncaught (in promise) TypeError: Cannot read property 'length' of null
    at PostObjectsCache.get_taxonomy_slug

Failed to initialize plugin: et_quicktags ReferenceError: et_quicktags_strings is not defined

**Comment by swissspidy** [comment]
Hi there,

Does this still happen with all other plugins disabled and when using another theme like e.g. Twenty Nineteen?

The error message indicates that the REST API is not working correctly on your site. Would you mind sharing your Site Health info with us?

**Comment by OpenCopyMike** [comment]
> Hi there,
> 
> Does this still happen with all other plugins disabled and when using another theme like e.g. Twenty Nineteen?
> 
> The error message indicates that the REST API is not working correctly on your site. Would you mind sharing your Site Health info with us?

Deactivating all other plugins seems to fix the issue (Still using Divi Theme)

After reactivating one at a time I have found these two conflicting plugins:

- **Advanced Custom Fields Pro (ACF Pro)** - This causes the et_quicktags_strings error but the story editor is still usable (though the notification is quite annoying)

- **SmartCrawl Pro** - seems to break the media library in the story editor and causes it to crash.

Updating SmartCrawl pro has fixed the media library issue, so it's just the error caused by ACF Pro now

Site Health Info:

`
### wp-core ###

version: 5.5.1
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 3
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/firstree/public_html
wordpress_size: loading...
uploads_path: /home/firstree/public_html/wp-content/uploads
uploads_size: loading...
themes_path: /home/firstree/public_html/wp-content/themes
themes_size: loading...
plugins_path: /home/firstree/public_html/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-active-theme ###

name: First Reef (FirstReef)
version: 1.0.0
author: First Reef Studio
author_website: https://www.firstreef.com.au
parent_theme: Divi (Divi)
theme_features: core-block-patterns, custom-background, automatic-feed-links, post-thumbnails, menus, title-tag, post-formats, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, customize-selective-refresh-widgets, editor-style, widgets
theme_path: /home/firstree/public_html/wp-content/themes/FirstReef
auto_update: Disabled

### wp-parent-theme ###

name: Divi (Divi)
version: 4.6.1
author: Elegant Themes
author_website: http://www.elegantthemes.com
theme_path: /home/firstree/public_html/wp-content/themes/Divi
auto_update: Disabled

### wp-plugins-active (17) ###

Beehive Pro: version: 3.2.8, author: WPMU DEV, Auto-updates disabled
Branda Pro: version: 3.4.0, author: WPMU DEV, Auto-updates disabled
Change Password Protected Message: version: 1.2.5, author: pipdig, Auto-updates disabled
ConvertKit: version: 1.9.2, author: ConvertKit, Auto-updates disabled
Defender Pro: version: 2.3.1, author: WPMU DEV, Auto-updates disabled
Forminator Pro: version: 1.13.5, author: WPMU DEV, Auto-updates disabled
Hummingbird Pro: version: 2.6.1, author: WPMU DEV, Auto-updates disabled
Jetpack CRM: version: 4.0.2, author: Automattic, Auto-updates disabled
Knowledge Base for Documents and FAQs: version: 6.8.0, author: Echo Plugins, Auto-updates disabled
SmartCrawl Pro: version: 2.8.0, author: WPMU DEV, Auto-updates disabled
Smush Pro: version: 3.7.0, author: WPMU DEV, Auto-updates disabled
Snapshot Pro: version: 4.0.3, author: WPMU DEV, Auto-updates disabled
TinyMCE Advanced: version: 5.5.0, author: Andrew Ozz, Auto-updates disabled
Web Stories: version: 1.0.0-beta.2, author: Google, Auto-updates disabled
WordPress Importer: version: 0.7, author: wordpressdotorg, Auto-updates disabled
WP and Divi Icons Pro: version: 1.2.0, author: Aspen Grove Studios, Auto-updates disabled
WPMU DEV Dashboard: version: 4.10.2, author: WPMU DEV, Auto-updates disabled

### wp-plugins-inactive (1) ###

Advanced Custom Fields PRO: version: 5.9.1, author: Elliot Condon, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
file_uploads: File uploads is turned off
post_max_size: 64M
upload_max_filesize: 64M
max_effective_size: 64 MB
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 9.25

### wp-server ###

server_architecture: Linux 3.10.0-962.3.2.lve1.5.35.el7.x86_64 x86_64
httpd_software: LiteSpeed
php_version: 7.3.21 64bit
php_sapi: litespeed
max_input_variables: 3000
time_limit: 300
memory_limit: 128M
admin_memory_limit: 256M
max_input_time: 120
upload_max_filesize: 64M
php_post_max_size: 64M
curl_version: 7.62.0 OpenSSL/1.0.2k
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.3.24-MariaDB
client_version: 10.3.23-MariaDB

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/firstree/public_html/wp-content
WP_PLUGIN_DIR: /home/firstree/public_html/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

`

**Comment by ernee** [comment]
@OpenCopyMike thanks so much for following up with this information. I was able to replicate some of the issues you reported with Divi + ACF, and SmartCrawl, so we'll look into this further. Just to confirm: you mentioned the issue with SmartCrawl Pro was resolved with an update- was it the 2.8.0 version as seen in your Site Health Info?

**Comment by ernee** [comment]
@OpenCopyMike just circling back that we'll be tracking the issues with [Divi + ACF here](https://github.com/google/web-stories-wp/issues/4492) and [SmartCrawl here](https://github.com/google/web-stories-wp/issues/4491) (in my testing I do not see it in the recent pro version as well). Thanks for reporting!

**Comment by ernee** [comment]
@OpenCopyMike the stable version of the plugin 1.0.0 as been released, but it appears the issues persist.

Please feel free to [subscribe to the issues](https://jmp.sh/rOFTITp) to keep up to date on their progress. I'll close your issue here, since we are providing support for the plugin in the [WordPress.org forums](https://wordpress.org/support/plugin/web-stories/) now. Please don't hesitate to reach out to us with any future questions or concerns there.
