### ISSUE TITLE
Update Web Stories Logo

### ISSUE THREAD

**Issue by samitron7** [GoogleForCreators/web-stories-wp#4408]
Logo: ![Logo - Horizontal LockUp.svg](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/cf10976b-4e11-4e7e-a510-1749d7de85ff)

Nav icon (it's white so kinda of an easter egg looking for it - but it's definitely attached ->): ![Web Stories WP Menu Icon.svg](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/c0a0f798-e8ca-4acf-ab52-2dd1209b3d40)

**Comment by swissspidy** [comment]
Thanks! I'll handle the admin menu icon in #4410. Will leave the dashboard part to the dashboard folks :-)

**Comment by swissspidy** [comment]
@samitron7 I've also updated our Gutenberg block accordingly at #4410. OK like this?

**Comment by csossi** [comment]
Verified in QA
