### ISSUE TITLE
Video - Options

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#441]
## Feature Description

As an editor utilizing videos, I want to see what options are available for my videos

**Waiting for Feature Brief**

**https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=2671%3A55920**

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

1. The editor is presented with a looping option
2. The editor is able to mute a video (the video will have no sound when played) (Note: Videos are muted in AMP)

**Comment by spacedmonkey** [comment]
![image](https://user-images.githubusercontent.com/237508/75769606-63169000-5d3e-11ea-9bc0-68caeb36c9d1.png)

![image](https://user-images.githubusercontent.com/237508/75769583-57c36480-5d3e-11ea-9afd-c3064134e8c4.png)

WordPress it's supports added subtitle tracks and alternative version of file ( ogv, webm ).  Should we also support these @swissspidy @pbakaus @jauyong ?

**Comment by spacedmonkey** [comment]
Worth noting that gutenberg itself does not support subtitles ( https://github.com/WordPress/gutenberg/issues/7673 )  or alternate sources ( https://github.com/WordPress/gutenberg/issues/9457 ), at time of writing.

**Comment by swissspidy** [comment]
Alternative versions: AMP Stories only support MP4, WEBM, HLS ([docs](https://amp.dev/documentation/guides-and-tutorials/develop/amp_story_best_practices/#video-formats)), so this is a bit less relevant. I'd say we should just focus on MP4 for now. Other formats should be handled automatically by the editor in the future (WebAssembly, CDN, etc.)

Subtitles: Perhaps at some point in the future, but not a P0 in my eyes. Even then we should ideally just automate it and hide it from users.

Deferring to @pbakaus for making the decision though.

**Comment by pbakaus** [comment]
> Alternative versions: AMP Stories only support MP4, WEBM, HLS ([docs](https://amp.dev/documentation/guides-and-tutorials/develop/amp_story_best_practices/#video-formats)), so this is a bit less relevant. I'd say we should just focus on MP4 for now. Other formats should be handled automatically by the editor in the future (WebAssembly, CDN, etc.)
> 
> Subtitles: Perhaps at some point in the future, but not a P0 in my eyes. Even then we should ideally just automate it and hide it from users.
> 
> Deferring to @pbakaus for making the decision though.

I would say let's do MP4 and WEBM for now. Want to find out whether, and how we can support HLS in the future. /cc @newmuis

**Comment by newmuis** [comment]
We're in the midst of reevaluating what the best options are for video, but I don't think HLS makes the cut as a recommendation at this moment.  We'll update the docs once this is finalized, but doing only WEBM/MP4 makes sense for now

**Comment by jauyong** [comment]
Hey @samitron7 is there a design for where the looping option shows? Or is it the same as Jonny's screenshot above?
I looked at the media panel section and the design panel - video section in Figma.

**Comment by jauyong** [comment]
@pbakaus the brief for Media-specific controls is also missing as denoted by the red text in the [Product Spec doc. ](https://docs.google.com/document/d/16XRdN7nDDQahSXeZjV3w9WT7aemtUwGQPOvzLDSwsIk/edit#)

**Comment by pbakaus** [comment]
@jauyong all related spec should be written. Note that there's a red "Panel:Video" in the spec, but we only really need that when we ship subsequent features not in v1.

**Comment by jauyong** [comment]
I couldn't find where looping was covered in the docs but since this is in code review I'd assume Jonny found it

**Comment by pbakaus** [comment]
arrgh you're so right. The loop option was missing. Will add now.

**Comment by pbakaus** [comment]
Alright, it can be found here: https://docs.google.com/document/d/1EQ12sD4a1plmMeBu7YMWOdUSg0FeegB9qi2_OlV3Tp0/edit#heading=h.h3uoy4bqqh92

**Comment by swissspidy** [comment]
Just realized that muting is deprecated in favor of using `autoplay` (which we already do), so we don't need to implement that.
