### ISSUE TITLE
Fix element staggering to make Percy snapshots reliable again

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#4413]
## Bug Description

Elements are inserted in random positions, which makes Percy snapshots super unreliable because there are diffs for every. single. change.

This is bad because it makes the team trust these snapshots less, and blindly approve any changes.

## Screenshots

<img width="860" alt="Screenshot 2020-09-09 at 12 21 14" src="https://user-images.githubusercontent.com/841956/92586739-f81eb680-f296-11ea-9486-3e981061f481.png">
<img width="1675" alt="Screenshot 2020-09-09 at 12 21 29" src="https://user-images.githubusercontent.com/841956/92586762-ffde5b00-f296-11ea-9659-f73b25f168f1.png">

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
Staggering is not yet implemented as per #1206, recco was to place all images in a consistent position always.

**Comment by csossi** [comment]
Verified in QA

**Comment by swissspidy** [comment]
Thank you!
