### ISSUE TITLE
Media (category) dropdown arrow floating in space

### ISSUE THREAD

**Issue by samitron7** [GoogleForCreators/web-stories-wp#4416]
## Bug Description

There is a second dropdown arrow that appears to be floating in space.

## Expected Behaviour

There should only be one dropdown arrow.

## Steps to Reproduce

1. Make sure to enable all third-party media related feature flags (also gifs and videos)
1. Go to the Third-party Media tab and observe that images will be default category
1. Click on the category dropdown button to expand the category list
1. Change the third-party media category to gifs or videos
1. Observe that the category collapse button from the images list persists (potentially behind new media elements, but it's lurking back there)

![Screen Shot 2020-09-09 at 7.40.36 AM.png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/6b498031-c1b2-4fe0-bc8f-851193932604)

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
I am unable to reproduce this (locally from `main` branch), but someone else should feel free to look more into this.

**Comment by swissspidy** [comment]
I can't reproduce this either

**Comment by swissspidy** [comment]
Additional info provided on Slack:

> Try this:
> 1. Click on the dropdown arrow to open the category dropdown
> 2. Then click on the video tab or the gif tab


Now I can reproduce.

**Comment by barklund** [comment]
> > 2. Then click on the video tab or the gif tab
> 
> Now I can reproduce.

Ah, I didn't have those tabs enabled. Have amended the above instructions.

**Comment by o-fernandez** [comment]
Tested 4439 and was able to repro the issue without it, and see the fix with it. Passed.
