### ISSUE TITLE
Text size doesn't accept fractional sizes

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#4419]
## Bug Description

Testing #3639 noticed that our editor doesn't accept fractional text sizes in the text size input box. We should fix this to allow fractional text input. Once that's done, we should also revisit the spec for text presets and ensure fractional sizes are properly set (e.g., H3 should be 21.6, Caption should be 13.5)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Wasn't this by design?

**Comment by swissspidy** [comment]
Also, this will probably cause rounding issues with different browsers

**Comment by bmattb** [comment]
estimated as 1, but flagged that this may have unintended consequences with movable.
