### ISSUE TITLE
Video - Add features from Images

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#442]
## Feature Description

This ticket is to add features built for images so they are also available for videos.

See image ticket: #35 
---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
1. The author is able to crop videos
2. Refactor video element to sync with Image (re-use code)

**Comment by jauyong** [comment]
@spacedmonkey I'm not sure what else is missing here.

**Comment by spacedmonkey** [comment]
@miina Might be a good person to add detail to this ticket, as she has worked on the image element.

**Comment by miina** [comment]
@jauyong / @spacedmonkey AFAIK then cropping should be the only issue to implement.
Basically the cropping movable should be brought over to the Video element as well, panning has already been implemented.

I could do the cropping, too, once the issue gets prioritized to the Sprint.

**Comment by miina** [comment]
Note: This is also a good issue to look into sharing (reusing) more general media logic between the image and video elements.

**Comment by spacedmonkey** [comment]
> Note: This is also a good issue to look into sharing (reusing) more general media logic between the image and video elements.

I agree. Maybe make a type of element called media with shared logic. Hopefully then, changes that effect both elements can be made in one place.
