### ISSUE TITLE
Show media thumbnail when adjusting crop/mask/zoom if the full image hasn't loaded

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#4422]
## Bug Description

Show media thumbnail when adjusting crop/mask/zoom if the full image hasn't loaded. Continuation of #2615, which fixed using the thumbnail in the canvas, but not when you double-click to adjust mask/zoom while image hasn't loaded. . 

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Related: #4051, #4178
