### ISSUE TITLE
Using Arrow keys when the Page is selected creates a new history entry

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#4425]
## Bug Description
It looks like using arrow keys applies the position change to the page (or the shape used as the background element) as well, even though the background element is not really moving.

## Expected Behaviour
Arrow keys should not have an effect when focused on the Page

## Steps to Reproduce
1. Click on the empty Page
2. Use arrow keys
3. See the Undo button/Save draft changing to active

## Screenshots
![nav](https://user-images.githubusercontent.com/3294597/92644898-51610700-f2e4-11ea-9756-aa8847708b5e.gif)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Just ran across this again and it's still an issue. Any chance we can fix this?

**Comment by miina** [comment]
I'll take a look when I have time left from the Sprint issues.

**Comment by csossi** [comment]
Verified in QA
