### ISSUE TITLE
How get embed code of a story?

### ISSUE THREAD

**Issue by uditrathod09** [GoogleForCreators/web-stories-wp#4436]
Hi, i am using WordPress as CMS and Elementor as a page builder, Is there any way I can embed web story through my elemente page builder.

**Comment by ernee** [comment]
@uditrathod09 thanks for your request! 

We have a few open issues to explore [Elementor support](https://github.com/google/web-stories-wp/issues/3688) as well as [shortcode support](https://github.com/google/web-stories-wp/issues/3135) which may address your use case at a future point. 
 
With that said, we have seen an example of Web Stories being embedded via  Elementor Pro's post widget ([video](https://youtu.be/Sn0OAnLiIGI?t=886)) which may be an option in the meantime.  

Please feel free to follow the issues linked for updates!

**Comment by uditrathod09** [comment]
Thank you for your help.
