### ISSUE TITLE
Supporting qualifying outbound links (`rel` attribute)

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#4440]
## Feature Description

_Originally reported at https://github.com/ampproject/amphtml/issues/30140_

For certain links users might want to tell search engines their relationship with the linked page using [the `rel` attribute](https://support.google.com/webmasters/answer/96569?hl=en). Examples include:

* `rel="sponsored"` - Mark links that are advertisements or paid placements
* `rel="ugc"` - Mark links as user-generated content (UGC) such as comments and forum posts
* `rel="nofoloow"` - For when you'd rather Google not associate your site with, or crawl the linked page from, your site

These can also be combined.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
https://developers.google.com/search/blog/2021/07/link-tagging-and-link-spam-update
https://developers.google.com/search/docs/advanced/guidelines/link-schemes

@o-fernandez @shishirm Is this something that has come up often when working with creators?

**Comment by o-fernandez** [comment]
I haven't seen requests from this, from either creators or other users, but I'd also guess that the creators we have in the funded program are not necessarily savvy or would ask for this proactively.

**Comment by mxbclang** [comment]
We've had a few requests for this in the forums, including one today:

- https://wordpress.org/support/topic/links-with-more-rel-options-nofollow-etc/
- https://wordpress.org/support/topic/affiliate-links-22/

**Comment by swissspidy** [comment]
@agingoldseco We might want to add some checkboxes to the "Link" panel to mark links as sponsored or nofollow. Could you perhaps mock up something simple?

**Comment by agingoldseco** [comment]
@swissspidy Yeah, will work on this later today—will we need to explain to users what those options mean somehow though? And no checkbox for UGC?

**Comment by swissspidy** [comment]
We can add a link to the documentation at https://developers.google.com/search/docs/advanced/guidelines/qualify-outbound-links?hl=en which explains these options.

And correct, no checkbox for UGC. UGC is only relevant when users of your website are able to create content or links on it; e.g., in the comment section on your site. So not relevant for stories.

**Comment by agingoldseco** [comment]
@swissspidy How's something like these? The checkboxes could show up only when you put a link in.

<img width="826" alt="Screen Shot 2021-10-29 at 3 39 32 PM" src="https://user-images.githubusercontent.com/90645922/139492720-854ca83e-cc97-489e-adbb-cac305753975.png">

**Comment by swissspidy** [comment]
The left one would work better when text length changes because of translations 👍

**Comment by agingoldseco** [comment]
Let's do it then :)

**Comment by agingoldseco** [comment]
Here's a link to the panel update in Figma: https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor-Sprint-Feature-Level-Designs_?node-id=10604%3A449277

**Comment by swissspidy** [comment]
Great, thanks!

Any objections to changing "What are these?" to something more like "Learn more about qualifying outbound links"?

**Comment by agingoldseco** [comment]
Not at all, but I also don't think people would be more likely to click a longer link than just a short "quick info" button-like one if they don't know what those checkboxes are for.

**Comment by swissspidy** [comment]
Could also change the title to "Qualify outbound links" and change the link to "Learn more"

My concern wasn't the length but the tone of "What are these?" not matching the rest of the app IMO

**Comment by emilyfabulous** [comment]
Hello, can you please remove me from this thread, I don't think I need to
be on it.

Thanks!

**Comment by agingoldseco** [comment]
That absolutely works too, let's go with it.

**Comment by swissspidy** [comment]
Just realized we'll need this for page attachments too. We can just re-use the same appearance there.

**Comment by csossi** [comment]
Verified in QA
