### ISSUE TITLE
Embed Block: Update name

### ISSUE THREAD

**Issue by samitron7** [GoogleForCreators/web-stories-wp#4446]
Can we use the negative logo for this instead so we're adhering to the same patterns as the other logo for the block menu. Also, does it make sense to change the name to "Web Stories"?

![WebStories-icon.svg](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/ce47274f-83e2-4596-aa9c-d0fdfd3cf3f8)

![Screen Shot 2020-09-10 at 10.15.28 AM.png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/0248b95d-460d-4678-a802-8c68893fc6a0)

**Comment by swissspidy** [comment]
After syncing with Sam we'll keep the icon but change the block name.
