### ISSUE TITLE
Telemetry Banner causes stories to get cut off/shrink

### ISSUE THREAD

**Issue by dmmulroy** [GoogleForCreators/web-stories-wp#4449]
## Bug Description

When the Telemetry Banner is visible and there are stories the stories get cut off/shrink

## Expected Behaviour

Stories should not get cut off/shrink

## Steps to Reproduce

- Opt out of Telemetry tracking and clear localStorage via `localStorage.clear()` in the console and reload the My Stories page.  The banner should display and cut off/shrink the below stories.
### How they currently look:
![image.png](https://images.zenhubusercontent.com/5ed1482c796b702933b1c4b9/b029f2ee-9dd3-4d3a-a172-d255ab2901b8)

### How they should look:
![image.png](https://images.zenhubusercontent.com/5ed1482c796b702933b1c4b9/f56013cb-fdbf-456b-a546-1304ebb8a837)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA

Before:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/a60edd20-9131-41d2-b687-8a510036ebcc)
After:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/075ed6d8-b1a5-437d-b75c-b98cd19630cf)

New ticket created re: positioning when using keyboard nav
