### ISSUE TITLE
Remove (delete) element when dragging it completely out of a Page

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#445]
## Feature Description

Based on Figma, an element should be removed when it's dragged completely out of the Page.

[See Design](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=2832%3A208)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
- When user drags an element fully out of the Page, it should be removed.

**Comment by miina** [comment]
@o-fernandez The original issue states that the elements should be deleted if dragged outside of the canvas, however, elements can also end up being outside of the canvas after resizing or rotating (especially during multi-selection actions). 

When an element is outside of canvas, it's not really accessible anymore, so Undo would be the only way how to get it back to the Canvas anyway. Based on this it seems that it would make sense to remove any element that is left outside of Canvas as a result of dragging/resizing/rotation (and not just dragging).

Thoughts?

**Comment by o-fernandez** [comment]
> @o-fernandez The original issue states that the elements should be deleted if dragged outside of the canvas, however, elements can also end up being outside of the canvas after resizing or rotating (especially during multi-selection actions).
> 
> When an element is outside of canvas, it's not really accessible anymore, so Undo would be the only way how to get it back to the Canvas anyway. Based on this it seems that it would make sense to remove any element that is left outside of Canvas as a result of dragging/resizing/rotation (and not just dragging).
> 
> Thoughts?

Good catch! I'd say yes, it makes sense to remove an element that ends up fully outside of the canvas even in multi-select rotation cases. 
@samitron7 FYI and in case you believe otherwise.

**Comment by csossi** [comment]
Verified in QA

**Comment by samitron7** [comment]
UAT - Verified!
