### ISSUE TITLE
Enable the Keyboard Shortcut Menu

### ISSUE THREAD

**Issue by mariano-formidable** [GoogleForCreators/web-stories-wp#4455]
Set the "showKeyboardShortcutsButton" flag to default to `true`.

**Comment by swissspidy** [comment]
@mariano-formidable So this already did go through QA?

**Comment by mariano-formidable** [comment]
> @mariano-formidable So this already did go through QA?

@swissspidy Nope, I mistakenly hit merge instead of moving to QA.  So I put it in UAT so it can get checked on that end.  I didn't think it was worth reverting since it's a flag flip and Omar _did_ QA the entire menu in my other ticket (the QA environment must have had the flag enabled already because he tested and approved it).
