### ISSUE TITLE
FTUE  Story: Update imagery to include new logo everywhere

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#4456]
## Bug Description

Update the FTUE page to show the new Web Stories logo when showing the Gutenberg block. 
Right now, it has the old web stories logo. Need to switch to the new one. 

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Have you cleared the cache? We‘ve updated this to the new colored logo already.

**Comment by swissspidy** [comment]
Screenshot of 1.0.0-rc.1:

<img width="707" alt="Screenshot 2020-09-10 at 23 35 44" src="https://user-images.githubusercontent.com/841956/92811038-60b48300-f3be-11ea-8c9e-948066412e73.png">

**Comment by o-fernandez** [comment]
Sorry, this is for @samitron7 in the FTUE story. Just filed a quick bug during the review meeting. I'll update to specify.

**Comment by swissspidy** [comment]
@o-fernandez Looking at https://stories-new-wordpress-amp.pantheonsite.io/stories/tips-to-make-the-most-of-web-stories/ I don't see the old logo anywhere. Was this resolved? This is kinda blocking work on the FTUE story integration into the plugin, so would be good to know.

**Comment by o-fernandez** [comment]
Looks fixed! There was one item (gutenberg block screencast) that was not yet resolved, but it looks fixed now. :) We can close this out.
