### ISSUE TITLE
Gap and white box at the bottom of media pane

### ISSUE THREAD

**Issue by ezxyz** [GoogleForCreators/web-stories-wp#4457]
## Bug Description

![Screen Shot 2020-09-11 at 10 29 50 AM](https://user-images.githubusercontent.com/13947816/92832086-8cfded00-f41a-11ea-8fd3-400f19d8f66c.png)
Notice the gap at the bottom of the scroll list and the white box.

![Screen Shot 2020-09-11 at 10 29 50 AM](https://user-images.githubusercontent.com/13947816/92832441-009ffa00-f41b-11ea-967f-548f1735f402.png)
Red circle for emphasis.

## Expected Behaviour

The gap shouldn't be there.

## Steps to Reproduce

Load enough media in a media tab (both local and 3p) that it creates an overflow. Then the gap and white box is there.
## Additional Context

- Plugin Version:
- Operating System: Mac OS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

No longer have the gap.

**Comment by bmattb** [comment]
@o-fernandez / @swissspidy - is this considered a blocker for 1.0? cc: @diegovar

**Comment by swissspidy** [comment]
It looks like a trivial thing to fix and is kinda embarrassing if we don't fix it for stable. So I'd vote yes.

@barklund Perhaps you could take a quick look to see if it's as trivial as it seems?

**Comment by csossi** [comment]
Verified in QA
