### ISSUE TITLE
Make post type permalink base customizable

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#4459]
## Feature Description

Sometimes users are already using `/stories/` for a page or through some other post type. To avoid conflicts with existing content, we can make our permalink base customizable.

For example, [WooCommerce](https://docs.woocommerce.com/document/permalinks/) does that too. Screenshots:

![2016-06-13-at-11-23](https://user-images.githubusercontent.com/841956/92895645-f5010300-f41b-11ea-8a5f-f6658bcb91a3.png)
![product-permalinks-settings](https://user-images.githubusercontent.com/841956/92895650-f5999980-f41b-11ea-8e77-45035cc29c27.png)

## Additional Context

Making this customizable means we need to flush rewrite rules every time this is changed, and make sure we never hardcode the permalink base anywhere.

This is done automatically if we also add this to the "Permalinks" settings screen in WordPress, like WooCommerce does.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by westonruter** [comment]
Perhaps `/web-stories/` would be a safer default base?

**Comment by swissspidy** [comment]
With #4501 this becomes less urgent I think

**Comment by swissspidy** [comment]
Closing for now as it doesn't seem needed.
