### ISSUE TITLE
Lazily generate video thumbnails for all uploaded videos. 

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#446]
## Feature Description

Posters are generated on-the-fly when new videos are uploaded, but that doesn’t really help existing videos. The first time a author opens the story editor, the editor needs to lazily start requesting poster generation for all existing videos (it’s expected, and OK that images would slowly trickle in, since poster generation takes time).

---

**Comment by jauyong** [comment]
closing and merging with #470
