### ISSUE TITLE
Default analytics configuration not working

### ISSUE THREAD

**Issue by Bernietorras** [GoogleForCreators/web-stories-wp#4460]
## Bug Description

When you add the Analytics code in the Editor Settings field, the `"send_to"` is missing: `["UA-XXXXXXX-X"] } },"` at the end of each trigger.

Also in the event `storyProgress`, if we insert the label (`"eventLabel"`) with the variable `{storyPageId}` gives you a code that is not useful for analysis. It is much more interesting to know what the story number is. So it's much more interesting to add the variable `{storyPageIndex}` instead of `{storyPageId}`.

The names of the variables are incorrect in some cases.

The code that the plugin launches is like this:

```
<script type="application/json">
    {
        "vars": { "gtag_id": "UA-XXXXXXXXX-X", "config": { "UA-XXXXXXXXX-X": { "groups": "default" } } },
        "triggers": {
            "storyProgress": { "on": "story-page-visible", "request": "event", "vars": { "eventAction": "story_progress", "eventCategory": "${title}", "eventLabel": "${storyPageId}", "eventValue": "${storyProgress}" } },
            "storyEnd": { "on": "story-last-page-visible", "request": "event", "vars": { "eventAction": "story_complete", "eventCategory": "${title}" } },
            "trackFocusState": { "on": "story-focus", "tagName": "a", "request": "click " },
            "trackClickThrough": { "on": "story-click-through", "tagName": "a", "request": "click " },
            "storyOpen": { "on": "story-open", "request": "event", "vars": { "eventAction": "story_open", "eventCategory": "${title}" } },
            "storyClose": { "on": "story-close", "request": "event", "vars": { "eventAction": "story_close", "eventCategory": "${title}" } },
            "audioMuted": { "on": "story-audio-muted", "request": "event", "vars": { "eventAction": "story_audio_muted", "eventCategory": "${title}" } },
            "audioUnmuted": { "on": "story-audio-unmuted", "request": "event", "vars": { "eventAction": "story_audio_unmuted", "eventCategory": "${title}" } },
            "pageAttachmentEnter": { "on": "story-page-attachment-enter", "request": "event", "vars": { "eventAction": "story_page_attachment_enter", "eventCategory": "${title}" } },
            "pageAttachmentExit": { "on": "story-page-attachment-exit", "request": "event", "vars": { "eventAction": "story_page_attachment_exit", "eventCategory": "${title}" } }
        }
    }
</script>
```

## Expected Behaviour

You should launch the events in each story

## Steps to Reproduce

See the source code of the stories for the names of the events

## Potential solutions

1.- `"send_to"` is missing: `["UA-XXXXXXX-X"] } },"` at the end of each trigger. Before closing the trigger.
2.- Change variable in `"event_label"` of `"storyProgress"` -> `"${storyPageId}"` for `"${storyPageIndex}"`
3.- Add `"event_label"`: `"${storyPageCount}"` in storyEnd trigger.
4.- Add `"event_name"`: `"custom"` at the beginning of the variables of each trigger
5.- Change variable  `"eventAction"` for `"event_action"`
6.- Change variable `"eventCategory"` for `"event_category"`

Example:

```
<script type="application/json">
    {
        "vars": { "gtag_id": "UA-XXXXXXXXX-X", "config": { "UA-XXXXXXXXX-X": { "groups": "default" } } },
        "triggers": {
            "storyProgress": { "on": "story-page-visible", "vars": { "event_name": "custom", "event_action": "story_progress", "event_category": "${title}", "event_label": "${storyPageIndex}", "eventValue": "${storyProgress}", "send_to": ["UA-XXXXXXXXX-X"] } },
            "storyEnd": { "on": "story-last-page-visible", "vars": { "event_name": "custom", "event_action": "story_complete", "event_category": "${title}", "event_label": "${storyPageCount}", "send_to": ["UA-XXXXXXXXX-X"] } },
            "trackFocusState": { "on": "story-focus", "tagName": "a", "request": "click ", "send_to": ["UA-XXXXXXXXX-X"] },
            "trackClickThrough": { "on": "story-click-through", "tagName": "a", "request": "click ", "send_to": ["UA-XXXXXXXXX-X"] },
            "storyOpen": { "on": "story-open", "vars": { "event_name": "custom", "event_action": "story_open", "event_category": "${title}", "send_to": ["UA-XXXXXXXXX-X"] } },
            "storyClose": { "on": "story-close", "vars": { "event_name": "custom", "event_action": "story_close", "event_category": "${title}", "send_to": ["UA-XXXXXXXXX-X"] } },
            "audioMuted": { "on": "story-audio-muted", "vars": { "event_name": "custom", "event_action": "story_audio_muted", "event_category": "${title}", "send_to": ["UA-XXXXXXXXX-X"] } },
            "audioUnmuted": { "on": "story-audio-unmuted", "vars": { "event_name": "custom", "event_action": "story_audio_unmuted", "event_category": "${title}", "send_to": ["UA-XXXXXXXXX-X"] } },
            "pageAttachmentEnter": { "on": "story-page-attachment-enter", "vars": { "event_name": "custom", "event_action": "story_page_attachment_enter", "event_category": "${title}", "send_to": ["UA-XXXXXXXXX-X"] } },
            "pageAttachmentExit": { "on": "story-page-attachment-exit", "vars": { "event_name": "custom", "event_action": "story_page_attachment_exit", "event_category": "${title}", "send_to": ["UA-XXXXXXXXX-X"] } }
        }
    }
</script>
```

Example 1: https://mesasescritorio.com/stories/la-mesa-de-joan-boluda/
Example 2: https://mesasescritorio.com/stories/review-couchmaster-cycon/

## Additional Context

- Plugin Version: 1.0.0-rc.1
- Operating System: Win 10
- Browser: Chrome 8.5

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Hi @Bernietorras 

Thanks a lot for your feedback! This is great timing as I was just looking into the analytics part as well.

Changing `storyPageId` to `storyPageIndex` sounds reasonable.

About the other things I am not so sure 🤔  I think I'll have to asks some folks about it first.

> 1.- `"send_to"` is missing: `["UA-XXXXXXX-X"] } },"` at the end of each trigger. Before closing the trigger.

This should only be needed when using multiple providers I think...? I'll have to check though, but the [examples](https://developers.google.com/analytics/devguides/collection/amp-analytics) in the docs don't do this.

> Change variable in `"event_label"` of `"storyProgress"` -> `"${storyPageId}"` for `"${storyPageIndex}"`

 👍 

> Add `"event_label"`: `"${storyPageCount}"` in storyEnd trigger.

👍 

> Add `"event_name"`: `"custom"` at the beginning of the variables of each trigger

👍  

> Change variable  `"eventAction"` for `"event_action"`
> Change variable `"eventCategory"` for `"event_category"`

After checking the docs this seems reasonable.

**Comment by Bernietorras** [comment]
Hi Pascal,

Thank you for considering these bugs. I used this documentation on AMP
stories analytics:

https://www.google.com/amp/s/blog.amp.dev/2019/08/28/analytics-for-your-amp-stories/

Best regards,

Bernie

**Comment by swissspidy** [comment]
This will be in the 1.0.0 release. Thanks again for your report!
