### ISSUE TITLE
E2E Tests: Test Site Kit integration

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#4461]
## Task Description

It would be good to verify the Site Kit analytics integration using some E2E tests, in case there are any changes.

This might be doable by filtering the `googlesitekit_active_modules` and `googlesitekit_analytics_settings` options.

See also https://github.com/google/site-kit-wp/tree/develop/tests/e2e/plugins and https://github.com/google/site-kit-wp/blob/develop/tests/e2e/specs/modules/analytics/dashboard-date-range.test.js

Two cases:

1. Site Kit installed and active, analytics code should be printed
1. Site Kit integration on Settings screen

**Comment by spacedmonkey** [comment]
Just to confirm on this ticket. We would to make an e2e plugin to mock sitekit plugin and not install the real plugin?

**Comment by swissspidy** [comment]
Not exactly. We would install Site Kit, but also an _additional_ plugin that tricks Site Kit into thinking it's already fully setup.

The above links are pointers for how to do that. I've previously inquired about this on the Site Kit Slack channel (https://10up.slack.com/archives/CFFRMC5DE/p1599755975048500). @adamsilverstein might be able to help out with more concrete examples if needed.

**Comment by spacedmonkey** [comment]
Doing some discovery. I think need to copy a lot of the code from sitekit. 
For a start all of these plugins
https://github.com/google/site-kit-wp/blob/d720e79196474496b9f2164f86bd4bc4ba0d2201/tests/e2e/specs/modules/analytics/setup-with-account-no-tag.test.js#L82-L93

There are no simple filters to enable this functionality. The site verification, auth apis and setup analytics need to mocked. This is at least 3/4 e2e mock plugins. 

I have two questions, 
1. Should this even be a e2e test? Could we use another kind of less expensive test. 
2. Should this test live in our plugin or in site kits plugin? If the test lives in site plugin, it means we dont have to copy over all the mock plugins. 

Any change the sitekit plugin would massively effect our end to end test. This doesn't feel like the best way to test.

**Comment by bmattb** [comment]
During backlog grooming we discussed the approach on this: 

1. Jonny will provide recco's 
2. Pascal will think about this test specifically
3. A strat for e2e testing of officially approved plugins should be developed
4. apply these understandings to the related AMP ticket #5114

**Comment by spacedmonkey** [comment]
I have decided to give my recommendations in the form of a pros / cons list. 

1. We install the site kit in the e2e tests. We copy and paste the e2e plugin from site kit plugin in web stories. When the test run, activate the plugins, run through the full sitekit activation process. Run through analytics configuration process.  Run tests. 

#### Pros
- Like real world example. 
- Will reflect changes in sitekit plugin. 

#### Cons
- Any change to the sitekit may break our e2e tests. 
- Activation process is slow to run and likely to break. 
- Slow to run

2. Add web stories e2e to site kit plugin. Use existing e2e plugins and helper utils to run activation and analytics config. 
#### Pros

- Like real world example. 
- Will reflect changes in sitekit plugin. 
- Any change to the sitekit will be reflected in their tests. 

#### Cons

- Tests will not be in control of the web stories team and sitekit team will have to manage and feedback if things break. 
- Slow to run

3. Create a new e2e plugin that mocks output from sitekit plugin. Basically copying this [method](https://github.com/google/site-kit-wp/blob/27d4df7bbfbf6c7e59310ee9338e2a6155870268/includes/Modules/Analytics.php#L464-L515) into our own e2e plugin. 

**Pros**
- e2e is full in web stories team control 
- Easy to maintain and control.
- Fast to run

**Cons**
- Changes to sitekit will not be reflected. Any changes will need to updated manually. 

Personally I recommend option 3, it gives us the most control and is fast to put together. However, it is worth talking to the sitekit team about option 2, see if they are interested. 

It also worth noting that the amp plugin is a little different. Option 1 with amp plugin may work much better, as much of the mocking is not needed.

**Comment by swissspidy** [comment]
Yesterday I mentioned another, simplified option:

Install Site Kit in e2e tests but don't do any of the mocking, just activating it & verifying that the stories dashboard displays the Site Kit specific messaging.

For testing analytics frontend output option 3 sounds like a good start.

**Comment by spacedmonkey** [comment]
Again, the options listed above were to test the two test cases listed.  

> Site Kit installed and active, analytics code should be printed
Site Kit integration on Settings screen

I think we should have to two tests. 

1. Activate the real site kit plugin to see if message shows in dashboard. 
2. Mock analytics in our own e2e plugin.

**Comment by swissspidy** [comment]
Let's do it then!
