### ISSUE TITLE
Add support for webp file format in WP Core 

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#447]
## Feature Description
WordPress core does not support the upload of webp file format. 

Related Trac tickets. [35725](https://core.trac.wordpress.org/ticket/35725), [35726](https://core.trac.wordpress.org/ticket/35726), [24718](https://core.trac.wordpress.org/ticket/24718) and [42920](https://core.trac.wordpress.org/ticket/42920).

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
Safari with version 14.0 is adding support for webp natively, meaning we can support it in our editor and WordPress core can support it. 

See the dev notes for more [details](https://developer.apple.com/documentation/safari-release-notes/safari-14-beta-release-notes).

**Comment by swissspidy** [comment]
As discussed, would be nice to get this into WP 5.7

**Comment by swissspidy** [comment]
Looks like it's on some core people's wishlist already. No need to track this here too

**Comment by spacedmonkey** [comment]
Progressing being made here - https://core.trac.wordpress.org/ticket/35725
