### ISSUE TITLE
Dashboard: Stories position shift upon focus

### ISSUE THREAD

**Issue by csossi** [GoogleForCreators/web-stories-wp#4470]
Chose to ignore top banner and keyboard nav to first story. The display repositions in such a way that story is no longer in full view:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/0ecd83da-3522-480f-942b-1c5689eb7d2a)

- load Dashboard with opt-in banner at the top (clearing cache through devtool storage beforehand - see https://app.zenhub.com/workspaces/web-stories-5e94d3aced449034e1e9b226/issues/google/web-stories-wp/4449
- keyboard nav to first story
- note that screen now repositions as image above

**Comment by dmmulroy** [comment]
I'm seeing this occur without the banner being open as well

**Comment by BrittanyIRL** [comment]
To echo dillon, I think this is a grid issue not a banner issue. Great catch though! I will take a look at this next week.

**Comment by csossi** [comment]
Verified in QA
