### ISSUE TITLE
Support the upload of SVG files

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#448]
## Feature Description

WordPress by default does not support the upload of SVG files.  This can be added with a simple filter. 

```
function cc_mime_types($mimes) {
 $mimes['svg'] = 'image/svg+xml';
 return $mimes;
}
add_filter('upload_mimes', 'cc_mime_types');
```
Original filter from [CSS-tricks](https://css-tricks.com/snippets/wordpress/allow-svg-through-wordpress-media-uploader/).

However, there an a number of [security issues](https://wordpress.tv/2019/01/22/daryll-doyle-securing-svg-uploads-in-wordpress/) with SVG, which is why WP core does not support them out of the box. See the original [ticket](https://core.trac.wordpress.org/ticket/24251) for details.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Would it make sense to only support uploading SVG from within the stories editor, but not generally for the whole WordPress site?

**Comment by spacedmonkey** [comment]
I am not sure how we would do that, once you enable the REST API to receive the SVG, then the cat is out of the bag. 

The security issues, are pretty big, including script injection.

**Comment by dvoytenko** [comment]
@spacedmonkey I don't think I've seen any security issues in SVGs for a very long time, as long as they are used as external resource (e.g. `<img>` tag). When inlined - of course, all bets are off. But even then, AMP validator will disallow any script injections there. So, I think we shouldn't have any security issues, and definitely not if we start with external-resource uses.
