### ISSUE TITLE
Unable to delete saved styles

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#4481]
## Bug Description

Under some circumstances it's impossible to edit/delete saved styles.

## Expected Behaviour

I should be able to delete saved styles at all times.

## Steps to Reproduce

**Note:** the issue only appears when there are **no saved _colors_**.

1. Ensure there are no saved colors
1. Save style
1. Try to edit saved styles
1. Nothing happens

## Screenshots

![image (8)](https://user-images.githubusercontent.com/841956/93118085-0833fd00-f6c0-11ea-834a-85c549165541.png)

## Additional Context

- Plugin Version: 1.0.0-rc.1
- Operating System: macOS
- Browser: Browser

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Taking a look now!

**Comment by pbakaus** [comment]
glad you could repro @swissspidy! thanks!

**Comment by swissspidy** [comment]
@miina missed QA on this :) OK with me since you added solid tests, but let‘s not forget UAT

**Comment by miina** [comment]
Oops, indeed! WIll ping Claudio to do post-merge QA for this.

**Comment by csossi** [comment]
Verified in QA
