### ISSUE TITLE
Can the plugin be used in a network install?

### ISSUE THREAD

**Issue by henrywright** [GoogleForCreators/web-stories-wp#4487]
## Feature Description

Multisite is a native feature of WordPress. Will it be supported?

**Comment by ernee** [comment]
@henrywright thanks for your inquiry! We are still [exploring Multisite support](https://github.com/google/web-stories-wp/issues/2670), so currently the plugin would need to be used at the sub-site level. Feel free to follow the issue linked for this feature's progress.

**Comment by henrywright** [comment]
Thanks @ernee
