### ISSUE TITLE
NextGen Gallery Compatibility: validation errors in combination with other plugins

### ISSUE THREAD

**Issue by ernee** [GoogleForCreators/web-stories-wp#4489]
## Bug Description

As discovered [in this issue](https://github.com/google/web-stories-wp/issues/3744#issuecomment-673161619), the [NextGen gallery plugin](https://wordpress.org/plugins/nextgen-gallery/) may surface invalid markup on the web story URL causing validation errors, particularly in combination with other plugins. 

For example, with NextGen + Web Stories the following validation errors surface:
<img width="849" alt="NextGen validation errors with Web Stories" src="https://user-images.githubusercontent.com/8108643/93160173-a88c2080-f6c4-11ea-914c-233d1daae8ab.png">

Similar to the report in the initial issue, the following is flagged with NextGen + Web Stories + Jetpack (related posts module) + Atomic Blocks:

<img width="874" alt="Screen Shot 2020-09-14 at 8 13 32 PM" src="https://user-images.githubusercontent.com/8108643/93161159-cfe3ed00-f6c6-11ea-82ca-d30a1e3df60b.png">

- The issue occurs upon activation and appears only reversible by deactivating the plugin. 
- Invalid markup consistently references custom JS added to by NextGen, and often invalid CSS from other sources.

## Expected Behaviour

No validation errors on the story URL with NextGen gallery plugin. 

## Steps to Reproduce

1) Install and activate NextGen + WebStories (or any other plugin referenced above)
2) Check the story URL and see the validation errors flagged

## Additional Context

- Plugin Version: 1.0.0-rc.1
- Operating System: MacOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by westonruter** [comment]
This has come up in the past with the AMP plugin: https://wordpress.org/support/topic/amp-custom-is-missing-in-the-class-amp-gallery-embed-php/

This is the workaround that I put together: https://gist.github.com/westonruter/99b1ca0d593f44888401a396d991e3a6

This won't work with Web Stories as-is. It changed be changed to check the `REQUEST_URI` for `/web-stories/` however.

**Comment by westonruter** [comment]
The issue is NextGEN Gallery's “resource manager”.

**Comment by spacedmonkey** [comment]
Seems like @swissspidy is working on this #5198
