### ISSUE TITLE
WP Rocket Compatibility: validation errors with JS file optimization

### ISSUE THREAD

**Issue by ernee** [GoogleForCreators/web-stories-wp#4490]
## Bug Description

A few JavaScript file optimization options in the [WP Rocket plugin](https://wp-rocket.me/) can surface validation errors on the story URL. Currently, it looks like the _Minify_ and _Combine JavaScript files_  options on the **File Optimization tab** :

<img width="554" alt="Screen Shot 2020-09-10 at 9 42 20 PM" src="https://user-images.githubusercontent.com/8108643/93163056-fd329a00-f6ca-11ea-83c5-fe2652986371.png">

Reports:

https://github.com/google/web-stories-wp/issues/3744#issuecomment-671481039
https://github.com/google/web-stories-wp/issues/3746
https://github.com/google/web-stories-wp/issues/3968

Current workarounds: 

- Disabling the option(s)
- Excluding the _/web-stories/_ url on the [Advanced Rules tab](https://jmp.sh/b2mELvw) 
- Using the [official AMP plugin](https://wordpress.org/plugins/amp/) with [supported template options off](https://jmp.sh/hIVr6Qz) in the settings if site is not using AMP already. This allows the plugin to remove the invalid markup from the story URL.

## Expected Behaviour

No validation errors on the story URL with WP Rocket.

## Steps to Reproduce

1) Enable the JS _Minify_ and _Combine_ options in WP Rocket
2) See validation errors on the URL

## Additional Context

- Plugin Version: 1.0.0-rc.1
- Operating System: MacOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by LuckynaSan** [comment]
WP Rocket released their latest version 3.7.5 with the fix. Disabled the JS Minify and Combine options in WP Rocket. Validation errors on the Story URL no longer occur.
