### ISSUE TITLE
SmartCrawl SEO Compatibility: conflicts with editor

### ISSUE THREAD

**Issue by ernee** [GoogleForCreators/web-stories-wp#4491]
## Bug Description

The [SmartCrawl SEO plugin ](https://wordpress.org/plugins/smartcrawl-seo/)conflicts with the editor causing it to be unusable:
<img width="1204" alt="Screen Shot 2020-09-11 at 12 23 37 AM" src="https://user-images.githubusercontent.com/8108643/93167580-c1e99880-f6d5-11ea-9805-07dde4c96d93.png">

Console errors: 

<img width="1277" alt="Screen Shot 2020-09-14 at 10 13 58 PM" src="https://user-images.githubusercontent.com/8108643/93168484-cf078700-f6d7-11ea-82bf-634cbb3498d6.png">

When attempting to add media or other elements the following error is thrown:

```
TypeError: Cannot read property 'elements' of undefined
    in StoryProvider
    in Unknown
    in SnackbarProvider
    in Unknown
    in HistoryProvider
    in Unknown
    in Media3pApiProvider
    in Unknown
    in APIProvider
    in Unknown
    in ConfigProvider
    in Dz
    in ThemeProvider
    in StyleSheetManager
    in App
    in FlagsProvider
```

Reports:

https://github.com/google/web-stories-wp/issues/4181
https://github.com/google/web-stories-wp/issues/4406

The issue looks to only occur with the free version of the plugin. The issue does not occur with the most recent pro version (2.8.0).

## Expected Behaviour

The editor works with the SmartCrawl SEO plugin. 

## Steps to Reproduce

1) Configure the SmartCrawl plugin.
2) Either create a new story or open a template in the editor
3) See the editor with missing elements (no media in the library) and no page controls
4) Attempt to add elements and see error

## Additional Context

- Plugin Version: 1.0.0-rc.1
- Operating System: MacOs
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
@swissspidy @amedina This seems to have come up quite a bit during the Beta period. Although the SmartCrawl SEO plugin seems to have just around ~30k active installs, should we reach out and see if this can be fixed? (highest number of reports)

**Comment by swissspidy** [comment]
Yes, that's what's we usually do in these cases.

@ernee Can you reach out to them? It looks like they might be messing with the REST API interactions using some custom middleware.

**Comment by khaxan** [comment]
The issue has been resolved in the latest free version of SmartCrawl (2.8.0)

**Comment by ernee** [comment]
@khaxan indeed and thanks for the update! The WPMU Dev team has helped us confirm this is the case with the release of 2.8.0 today. I will close this as resolved.
