### ISSUE TITLE
Video Element

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#45]
## Feature description

Needs to come with support for automatically extracting the mandatory poster image from video if missing.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by spacedmonkey** [comment]
Should the video element support fullbleed? Should it be fullbleed by default?

@dvoytenko @pbakaus

**Comment by pbakaus** [comment]
> Should the video element support fullbleed? Should it be fullbleed by default?

Yes. Most common use-case for video is background, in which case it would be fullbleed automatically. I'd say we shouldn't make full bleed default for videos that are dragged on top of the canvas.

**Comment by spacedmonkey** [comment]
> Loop ( Checkbox - true / false - Default to true)
> Poster - ( User uploaded Image - User override for poster image)
> Caption ( Text field below video )
> Assistive Text ( Text field for accessibility )

@samitron7 Can these fields be reflected in the figma please ^

**Comment by swissspidy** [comment]
@jauyong We need to get some ACs here based on the media epic.

#259 covers the design panel, which is fine, but there's much more to the video element. https://github.com/google/web-stories-wp/labels/Media covers some parts, but not all.

**Comment by spacedmonkey** [comment]
After some changes in the figma, we also now need to display the duration of the video. Not sure if this information is stored in WP.

**Comment by jauyong** [comment]
Closing this ticket as dev will be broken down. Here are the first 2 new tickets for Video:
#441 
#442
