### ISSUE TITLE
Use `/web-stories/` as the default base for stories, instead of `/stories/`

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#4501]
A user reported that our plugin's use of /stories/ slug for the archive page interfered with their existing pages. To lower the chances of this happening, suggest using `/web-stories/` as the default base slug.

If possible, for those who upgrade we can redirect /stories/ to /web-stories/, but only if we think that will safely work. 

------

Perhaps `/web-stories/` would be a safer default base?

_Originally posted by @westonruter in https://github.com/google/web-stories-wp/issues/4459#issuecomment-691160979_

**Comment by o-fernandez** [comment]
@swissspidy @pbakaus @choumx can you evaluate / see if this makes sense to do for 1.0 Stable? We may not need if if #4459 is easy and fast to implement, but regardless, this seems like a safer base slug to use.

**Comment by pbakaus** [comment]
+1.

**Comment by swissspidy** [comment]
Happy to change, with one note: I doubt we‘ll be able to set up redirects easily due to the way WP‘s rewrites system work, but maybe WP already handles that for us.

**Comment by o-fernandez** [comment]
I'm not sure how to test this. @swissspidy 
https://stories-new-wordpress-amp.pantheonsite.io/ still publishes to /stories/

**Comment by swissspidy** [comment]
@o-fernandez Looks like the deployment here didn't work... Let me deploy manually real quick.

**Comment by swissspidy** [comment]
@o-fernandez Please try again

**Comment by o-fernandez** [comment]
This seems to work pretty well, the only thing is that if I try going to /stories/some-story it will only redirect me to /web-stories/ index page. 

This is unfortunate for existing story linking, people will need to set their own redirects if they want to ensure inbound links go to the right place. But, good to make this change now rather than after Beta.

**Comment by swissspidy** [comment]
@o-fernandez I cannot confirm that, the redirects work fine here. Could you provide more info please?
