### ISSUE TITLE
The attribute name is set to the invalid value 

### ISSUE THREAD

**Issue by netnaps** [GoogleForCreators/web-stories-wp#4528]
## Bug Description

the attribute name is set to the invalid value 
## Expected Behaviour

AMP Validation Error 

## Steps to Reproduce

See a screenshot below 

## Screenshots
![Screenshot 2020-09-17 at 3 31 36 PM](https://user-images.githubusercontent.com/67054369/93456378-3e10f580-f8fb-11ea-825b-f4381a9a92a6.png)

## Additional Context

- Plugin Version:1.0.0-rc.1
- Operating System: macOS 
- Browser:Chrome

---

![Screenshot 2020-09-17 at 3 36 26 PM](https://user-images.githubusercontent.com/67054369/93456695-ad86e500-f8fb-11ea-9435-abbac42343ff.png)

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Hi @netnaps, thanks for your report!

This is already known and will be resolved in the upcoming 2.0.2 of the AMP WordPress plugin. It should be released today or tomorrow, so stay tuned! Or better yet: enable automatic updates so you don't have to do that manually 🙂

**Comment by netnaps** [comment]
Thanks @swissspidy this works now just checked as always you have been very helpful.
