### ISSUE TITLE
Layer panel behavior (not implemented to spec, improper behavior)

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#4532]
## Bug Description

TBD, need to work with UX to specify the issues. 

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by samitron7** [comment]
Closing this ticket out. Seems like its been fixed. I'll re-open if I find further issues.
