### ISSUE TITLE
Ability to enter partial hex value

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#4533]
## Feature Description

Fixes: Ability to enter partial hex value (3-digit code) 
[Designs](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Stable-Release?node-id=987%3A2)

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by samitron7** [comment]
Let's just start with the 3 letter shortcode. [Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Stable-Release?node-id=987%3A2)

**Comment by o-fernandez** [comment]
Review #4597 as part of this.

**Comment by samitron7** [comment]
Verified in UAT!
