### ISSUE TITLE
Minor visual updates for Dashboard

### ISSUE THREAD

**Issue by samitron7** [GoogleForCreators/web-stories-wp#4549]
Brittany and I chatted offline and agreed that the following minor updates are doable:

- [x] 1. To reduce crowding in the left nav, increase the width of the column
- [x] 2. To reduce crowding in story cards, remove a card
- [x] 2.5 spacing between cards should be 20px
- [x] 3. Change the color of the Create new story button to a gray. The bright blue is in competition with out logo.
- [x] 4.  Add some top/bottom breathing space to the filters (ie viewing all stories, last modified etc) for My Stories and Explore Templates
- [x] 5. Add breathing room between the rows in the cards in My Stories

**Comment by csossi** [comment]
According to details in 4565, this should be on one line:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/225e9f7b-49be-499d-ad38-6fe2e9e398ce)

**Comment by swissspidy** [comment]
@csossi Good catch, but not an issue in this instance. The version is that long on our development enviroment (because it's a dev version), and it's not possible to fit 100 chars on one line there 🙂 

Our end users will see versions like `1.0.0` instead

**Comment by BrittanyIRL** [comment]
Thanks, @csossi and @swissspidy - i should have been clearer with my word choice there, i just meant i removed the forced line break so when possible it'll be on one line.
