### ISSUE TITLE
Amp Stories Error, Crashed My Site

### ISSUE THREAD

**Issue by newmuis** [GoogleForCreators/web-stories-wp#4578]
Originally reported in https://github.com/ampproject/amphtml/issues/30310 by @DanielCryptoK

> Please see below
> 
> This message was triggered by web-stories.
> 
> Call stack:
> 
> wp_die()
> wp-includes/functions.php:4704
> dead_db()
> wp-includes/wp-db.php:1866
> Yoast\W\L\ORM::execute()
> wp-content/plugins/wordpress-seo/lib/orm.php:1945
> Yoast\W\L\ORM->run()
> wp-content/plugins/wordpress-seo/lib/orm.php:401
> Yoast\W\L\ORM->find_many()
> wp-content/plugins/wordpress-seo/src/repositories/indexable-repository.php:404
> Yoast\W\S\R\Indexable_Repository->get_ancestors()
> wp-content/plugins/wordpress-seo/src/generators/breadcrumbs-generator.php:137
> Yoast\W\S\G\Breadcrumbs_Generator->generate()
> wp-content/plugins/wordpress-seo/src/presentations/indexable-presentation.php:613
> Yoast\W\S\P\Indexable_Presentation->generate_breadcrumbs()
> wp-content/plugins/wordpress-seo/src/presentations/abstract-presentation.php:69
> Yoast\W\S\P\Abstract_Presentation->__get()
> wp-content/plugins/wordpress-seo/src/generators/schema/breadcrumb.php:46
> Yoast\W\S\G\S\Breadcrumb->generate()
> wp-content/plugins/wordpress-seo/src/generators/schema-generator.php:88
> Yoast\W\S\G\Schema_Generator->generate()
> wp-content/plugins/wordpress-seo/src/presentations/indexable-presentation.php:602
> Yoast\W\S\P\Indexable_Presentation->generate_schema()
> wp-content/plugins/wordpress-seo/src/presentations/abstract-presentation.php:69
> Yoast\W\S\P\Abstract_Presentation->__get()
> wp-content/plugins/wordpress-seo/src/presenters/schema-presenter.php:58
> Yoast\W\S\P\Schema_Presenter->get()
> wp-content/plugins/wordpress-seo/src/presenters/schema-presenter.php:42
> Yoast\W\S\P\Schema_Presenter->present()
> wp-content/plugins/wordpress-seo/src/surfaces/values/meta.php:143
> Yoast\W\S\S\V\Meta->get_head()
> wp-content/plugins/wordpress-seo/src/actions/indexables/indexable-head-action.php:68
> Yoast\W\S\A\I\Indexable_Head_Action->for_post()
> wp-content/plugins/wordpress-seo/src/routes/yoast-head-rest-field.php:105
> Yoast\W\S\R\Yoast_Head_REST_Field->for_post()
> wp-includes/rest-api/endpoints/class-wp-rest-controller.php:433
> WP_REST_Controller->add_additional_fields_to_object()
> wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php:1795
> WP_REST_Posts_Controller->prepare_item_for_response()
> wp-includes/rest-api/endpoints/class-wp-rest-attachments-controller.php:681
> WP_REST_Attachments_Controller->prepare_item_for_response()
> wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php:328
> WP_REST_Posts_Controller->get_items()
> wp-content/plugins/web-stories/includes/REST_API/Stories_Media_Controller.php:58
> Google\W\R\Stories_Media_Controller->get_items()
> wp-includes/rest-api/class-wp-rest-server.php:1050
> WP_REST_Server->dispatch()
> wp-includes/rest-api.php:464
> rest_do_request()
> wp-includes/rest-api.php:1984
> rest_preload_api_request()
> array_reduce()
> wp-content/plugins/web-stories/includes/templates/admin/edit-story.php:63
> Google\W\Story_Post_Type->replace_editor()
> wp-includes/class-wp-hook.php:287
> apply_filters('replace_editor')
> wp-admin/post.php:182

**Comment by ernee** [comment]
closing since this was addressed in the originally reported issue.
