### ISSUE TITLE
Unable To Add Text Links

### ISSUE THREAD

**Issue by DanielCryptoK** [GoogleForCreators/web-stories-wp#4580]
Web Stories for WordPress is dreadful and urgently needs a revamp. Extremely slow, not possible to add link attributes, what information is suppose to be included in the text accessibility? The whole text of the page or just the title? The side menu is awful and makes it very hard to navigate when trying to add link.

The main issue I need solving is the ability to add text links in the description as I am not able to do. I can add a link for the page but not on selected text.

There is also a conflict with yoast which is one of the most popular plugins.

**Comment by swissspidy** [comment]
Thanks a lot for using our plugin and sharing your feedback!

We're in an early phase of the whole launch, so the plugin is still rough around the edges. So your feedback is very useful for us.

For adding links, select an element and then scroll down to "Link" in the design panel on the right hand side:

<img width="994" alt="Screenshot 2020-09-22 at 23 18 55" src="https://user-images.githubusercontent.com/841956/93938732-fdb1dd00-fd29-11ea-9a9c-63314b633a0d.png">

As for Yoast SEO, we're not aware of any issues. In fact, we've been working together with Yoast SEO on ensuring compatibility with Web Stories out of the box. If you encounter any problems, please share some details with us, or report them to Yoast SEO directly.
