### ISSUE TITLE
Can Not Upload Brand Image

### ISSUE THREAD

**Issue by DanielCryptoK** [GoogleForCreators/web-stories-wp#4581]
I get the following error

Crypto Thrills Casino.png
Post-processing of the image failed likely because the server is busy or does not have enough resources. Uploading a smaller image may help. Suggested maximum size is 2500 pixels.

See attached
![Edit Story ‹ Bitcoin Casino No Deposit Bonus — WordPress (4)](https://user-images.githubusercontent.com/45933242/93736534-df08f480-fc0a-11ea-987a-c0cd5e459d7f.png)

**Comment by swissspidy** [comment]
Thanks for your report. As the error message says, your image might be too large (both file soze and dimensions). Can you share file details with us and try uploading a smaller image?

**Comment by DanielCryptoK** [comment]
I have managed to upload an icon rather than an image. The navigation menu is one of the worst I have ever experienced. It is so hard selecting an element and then moving down to see the options.  To be able to see the options below the elements I have to find a blank space in the box and then left click and drag down on my mouse pad. See attached

Also the plugin is SO SLOW at loading, I have never had a plugin this slow ever before.

![Edit Story ‹ Bitcoin Casino No Deposit Bonus — WordPress (5)](https://user-images.githubusercontent.com/45933242/93738005-e205e400-fc0e-11ea-9f54-5310f64523a2.png)

**Comment by swissspidy** [comment]
Thanks for the screenshot!

We'll definitely incorporate your feedback going forward. We're just getting started, so while we're ramping up things might still be a bit bumpy here and there.

Performance is one of the areas we'll particularly focus on in the near future. I do want to point out though that your site seems be running quite a lot of plugins and database queries (according to Query Monitor on your screenshot), which of course can also negatively impact performance.

Notice that I shared some details on adding links over at #4580.

Thanks again for sharing this with us and please don't hesitate to check back for new updates regularly as we keep improving the plugin.
