### ISSUE TITLE
Link URL sometimes not preserved

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#4582]
## Bug Description

Originally reported by @pbakaus, and I also just ran into this.

I ended up with link data like this:

```json
"link": {
  "url": "",
  "icon": "https:\/\/s.w.org\/images\/home\/screen-themes.png?3",
 "desc": "Blog Tool, Publishing Platform, and CMS \u2014 WordPress.org"
}
```

This means I got a URL preview when hovering over the element, but the actual link input field in the design panel was empty

## Expected Behaviour

* Link URLs should not be dropped like this.
* No URL preview should be displayed if there's no URL. -> sounds like an easy & testable fix

## Steps to Reproduce

Not yet 100% clear how to reproduce

## Screenshots

<img width="282" alt="Screenshot 2020-09-21 at 09 45 29" src="https://user-images.githubusercontent.com/841956/93742881-31d4b300-fbef-11ea-87cb-1c5f720a152a.png">
<img width="313" alt="Screenshot 2020-09-21 at 09 46 17" src="https://user-images.githubusercontent.com/841956/93742942-4dd85480-fbef-11ea-9880-9b3692820f50.png">

## Additional Context

- Plugin Version: 1.0.0-rc.1
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
We should add this to the sprint and have a developer do proactive investigation about what could be happening, rather than waiting for more and more users to report.

**Comment by bmattb** [comment]
@o-fernandez This will not make 1.0, ok to move to 1.1, or is this a showstopper?

**Comment by o-fernandez** [comment]
Moved to 1.1. Thanks for flagging @bmattb

**Comment by barklund** [comment]
@miina, can you please link the PR with the ticket here?

**Comment by miina** [comment]
Oops, looks like I moved this accidentally! Moving back to "Ready for Sprint", sorry for that.

**Comment by o-fernandez** [comment]
Per PR, just looked that nothing broke, no repro steps.
