### ISSUE TITLE
Creator updating numerical entries are hindered by sanitization

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#4595]
## Bug Description

Currently, when a creator attempts to enter line-height manually (or any other number input), the sanitization starts working and it can be impossible to make corrections.

## Steps to Reproduce
1. Add a Text element
2. Resize the width to 300
3. Now try to delete the "3" in the width and replace it with "2"
4. See the sanitization getting in the way

Try the same with trying to change just the first number of the line-height (e.g. replacing "1" with "2" in "1.5")

## Screenshots
![numbers](https://user-images.githubusercontent.com/3294597/93791785-f65cd780-fc34-11ea-9226-adc45f5fb88c.gif)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

<!-- One or more bullet points for how to technically implement the feature. --

**Comment by barklund** [comment]
We need to figure out a number of things.

* What do we do if the input is invalid, e.g. `'horse'`? Revert to the old value?
* What do we do if the input is partially invalid, e.g. `1.5.2 horse`?  Revert to the old value or use the partially valid input (`1.5` in this case)?

How do you commit or discard your changes? Assuming:

* <kbd>enter</kbd> submits the value, leaves focus in the input field, and selects everything
* <kbd>up</kbd> adds 1 to the currently valid input (or old value), submits the value, leaves focus in the input field, and selects everything
* <kbd>down</kbd> subtracts 1 from the currently valid input (or old value), submits the value, leaves focus in the input field, and selects everything
* <kbd>esc</kbd> reverts to the old value, leaves focus in the input field, and selects everything
* <kbd>tab</kbd> submits the value and moves focus to the next input/button
* Clicking outside the input field submits the value and moves focus to wherever you click

@samitron7, @pbakaus to confirm.

**Comment by maxyinger** [comment]
I think most adobe products revert to the old value if invalid & partially invalid. could be a good reference point for behavior since I think a lot of users will be used to the behavior on those inputs

**Comment by carloskelly13** [comment]
I think we could be clever with partially valid inputs too, but perhaps in some edge cases we'd likely apply something the user didn't want at all. Reverting to the last valid is usually safest.

**Comment by bmattb** [comment]
deferred to 1.1

**Comment by o-fernandez** [comment]
And per conversation - we won't be doing validation during input, just when someone presses enter or clicks away/blurs the focus.

**Comment by csossi** [comment]
Verified in QA
