### ISSUE TITLE
Line height can accept 2 decimal points

### ISSUE THREAD

**Issue by samitron7** [GoogleForCreators/web-stories-wp#4596]
## Bug Description

I'm able to enter in values with 2 decimal in the line height input field. Steps to reproduce
1. enter a value
2. Select all
3. Type in value. Note that the previous value does not clear.

![image.png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/b5522caf-cf75-4698-a942-f1a14660e950)

## Steps to Reproduce

1. I click to enter a value
2. I click again to change the value 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
This will most likely be fixed in #4595. @carlos-kelly to confirm if duplicate.

**Comment by mariano-formidable** [comment]
This bug will be fixed once this PR #4608 is merged.

**Comment by csossi** [comment]
Verified in QA

**Comment by mariano-formidable** [comment]
Do not merge the PR associated with this ticket until #4595 passes QA too.
