### ISSUE TITLE
Inconsistent hex input field behavior

### ISSUE THREAD

**Issue by samitron7** [GoogleForCreators/web-stories-wp#4597]
## Bug Description

The Hex input field behaves differently from the rest of the input fields.

## Expected Behaviour

1. When you click inside the input field, the placeholder value should be hilited
2. Enter a value and hit enter to apply the value

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
may be fixed by the work being done by the panel redesign, will reassess once that is completed.

**Comment by barklund** [comment]
I believe this one is now magically fixed by #4533, @mariano-formidable?

**Comment by mariano-formidable** [comment]
Yup, the PR for #4533 will fix this issue too 🎉

**Comment by samitron7** [comment]
Verified in UAT
