### ISSUE TITLE
Release 3P GIF integration

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#4599]
## Feature Description

Finalize and release 3P Media GIF integration.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
@diegovar can we ensure we have everything in place for the GIF integration to go out in 1.1 (so it needs to be done this or next sprint)? When do you think the team can resolve anything outstanding?

**Comment by send2cloud** [comment]
Bug on iOS Browsers - when I use a transparent animated GIF (downloaded from Giphy), on publish, it doesnt animate & shows a black bounding box. It looks & plays fine on in the desktop WP editor.

Tested on existing template here: http://p0ke.com/web-stories/yum/ - the chili animates fine on desktop, but doesnt on iOS.

**Comment by swissspidy** [comment]
@send2cloud Hi there, please open a new issue for your inquiry as it is unrelated to the topic at hand. For what it's worth, what you're experiencing is a bug in WordPress itself, see https://core.trac.wordpress.org/ticket/28474. I'll see if we can add a workaround for that though...

Edit: opened #4890

**Comment by csossi** [comment]
Verified in QA
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/e341536f-e1e8-4079-9191-476b8215d6d8)
