### ISSUE TITLE
Research solution to pasting formatted text

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#4602]
## Task Description

If a user copy/pastes text that has previously been styled into the editor, we currently strip out all formatting. That may be OK, but as part of #760 we'd like to understand whether there's an option to preserve the formatting and make it easier for creators to paste pre-formatted text into the editor. 

This ticket is to research the options and provide a potential solution and size estimate. P2 task.

**Comment by bmattb** [comment]
@o-fernandez - flagged in backlog grooming as possibly not be completed in S39, however this is not a priority ticket for v1.1 and will be carried over

**Comment by barklund** [comment]
Example text to paste with formatting:

### Headline
Text with **Bold**, _Italic_, <ins>Underline</ins>, ~Strikethrough~, `Code` and [Link](http://google.com).

> *Fancy quote* by Author

* Bullet list
* Extra

1. Regular list
1. Number two

```
multi
line
pre
```

![Alt text](https://i.pinimg.com/236x/77/08/0d/77080d2b168a45ce5934bc1cc1cbb329.jpg)

1. One more list
1. 1. with multiple levels

---

| Column | Head |
|-|-|
| Cell | Extra cell |

**Comment by barklund** [comment]
PR incoming with implementation fixing #760.
