### ISSUE TITLE
A11Y: Avoid "<verb>:" prefixes in announced names

### ISSUE THREAD

**Issue by dreamofabear** [GoogleForCreators/web-stories-wp#4604]
## Bug Description

- Story title text field's announced name is "Edit: Story title"
- Background color picker's announced name is "Edit: Background color"
- Page attachment text field's announced name is "Edit: Page attachment link"

## Expected Behavior

- A11Y names for input fields don't include "Edit:" or other verb prefixes

## Additional Context

- Plugin Version: 1.0.0
- Operating System: macOS 10.15.6
- Browser: Chrome 85

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by zidianlyu** [comment]
Done. Just to confirm, we only need to update those `3` places or do we need to remove all the "Edit:" around the project?

Here are what I found:
![Screen Shot 2020-11-12 at 8 28 42 AM](https://user-images.githubusercontent.com/11252886/98967396-4b90c900-24c1-11eb-8ba6-c766a32bfffb.png)

**Comment by swissspidy** [comment]
All of them

**Comment by zidianlyu** [comment]
Got it! Thanks for clarifying @swissspidy ! I will remove all 'Edit: ' & 'Enter: ' and etc.

**Comment by csossi** [comment]
Verified in QA
