### ISSUE TITLE
Workspace: The selected page should be persisted on refresh

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#4605]
## Bug Description

Persist the selected page (let's attach this as hash to the current URL, like Google Slides)

Do not alter or remove anything below. The following sections will be managed by moderators only.

## Acceptance Criteria

On page refresh of the editor, the selected page in the editor should remain.

## QA Instructions

1. Edit a story with multiple pages in the editor
2. Select a page that is not the first one
3. Refresh the browser and see the previously selected page is the current one that is active in the workspace

**Comment by csossi** [comment]
Verified in QA

**Comment by swissspidy** [comment]
Needs UAT
