### ISSUE TITLE
 Fatal error: Uncaught Error: Class 'DOMDocument' not found 

### ISSUE THREAD

**Issue by rsullivan2525** [GoogleForCreators/web-stories-wp#4607]
I had no issues installing or configuring.  I published my first story, but I can't view it.  when I do click to view it I get this error (with debug enabled in wordpress)

 Fatal error: Uncaught Error: Class 'DOMDocument' not found in /var/www/html/wp-content/plugins/web-stories/includes/Story_Renderer/HTML.php:173 Stack trace: #0 /var/www/html/wp-content/plugins/web-stories/includes/Story_Renderer/HTML.php(115): Google\Web_Stories\Story_Renderer\HTML->load_html('<!DOCTYPE html>...') #1 /var/www/html/wp-content/plugins/web-stories/includes/templates/frontend/single-web-story.php(38): Google\Web_Stories\Story_Renderer\HTML->render() #2 /var/www/html/wp-includes/template-loader.php(106): include('/var/www/html/w...') #3 /var/www/html/wp-blog-header.php(19): require_once('/var/www/html/w...') #4 /var/www/html/index.php(17): require('/var/www/html/w...') #5 {main} thrown in /var/www/html/wp-content/plugins/web-stories/includes/Story_Renderer/HTML.php on line 173

Site is self-hosted on Google cloud.

PHP Version `7.3.19-1+0~20200612.60+debian9~1.gbp6c8fe1`

**Comment by swissspidy** [comment]
Thanks for your report @rsullivan2525 

`DOMDocument` is part of DOM PHP extension that is enabled by default in PHP, but _can_ be disabled. Please make sure that extension is enabled on your environment.

We'll see if we can add some safeguards for this, but in the meantime I recommend double checking your PHP configuration and if necessary reach out to the respective support channels for your setup.

**Comment by rsullivan2525** [comment]
That fixed it for me thanks!
