### ISSUE TITLE
Home page doesn't render properly on mobile devices

### ISSUE THREAD

**Issue by morsssss** [GoogleForCreators/web-stories-wp#4622]
If I go to wp.stories.google on my Pixel 2 - or look at the site in the mobile emulator in Chrome DevTools, choosing any mobile device, this is what I see:

![wp stories google_(Pixel 2)](https://user-images.githubusercontent.com/29419498/93923348-45f8dd00-fce1-11ea-8077-025965e6afe1.png)

Text overlaps, and I need to scroll to see the whole page.

**Comment by patrickkettner** [comment]
@morsssss Is this still an issue for you? I am getting this

![image](https://user-images.githubusercontent.com/465414/94055135-86705d80-fdaa-11ea-8a75-5b90bcc4ec6a.png)

**Comment by morsssss** [comment]
It's been fixed! I think by @swissspidy .
