### ISSUE TITLE
Long menu items wrap in way that makes menu look confusing

### ISSUE THREAD

**Issue by morsssss** [GoogleForCreators/web-stories-wp#4623]
When I open the menu on wp.stories.google with Chrome on my MacBook, this is what I see:

<img width="1205" alt="Screen Shot 2020-09-22 at 2 32 02 PM" src="https://user-images.githubusercontent.com/29419498/93923554-88bab500-fce1-11ea-95ce-9a9fac56520a.png">

**Comment by CrystalOnScript** [comment]
I closed mine, but I still think the drop down should be removed until there is more than one page of documentation :)

**Comment by swissspidy** [comment]
Looks like this has been fixed
