### ISSUE TITLE
Long gap in scrolling on home page

### ISSUE THREAD

**Issue by morsssss** [GoogleForCreators/web-stories-wp#4624]
If I scroll down on https://wp.stories.google on my Mac on Chrome, the header text and "Get the plugin" button vanish rather quickly. I then need to scroll for quite a while until "Find your template" appears. While I'm scrolling, the bulk of the page is blank.

**Comment by patrickkettner** [comment]
@morsssss can you confirm if this is still an issue?

**Comment by morsssss** [comment]
No - it's all good now!

I think a bunch of content wasn't loading.
