### ISSUE TITLE
Documentation drop down menu needs to be fixed or removed

### ISSUE THREAD

**Issue by CrystalOnScript** [GoogleForCreators/web-stories-wp#4635]
<img width="1256" alt="Screen Shot 2020-09-22 at 2 36 01 PM" src="https://user-images.githubusercontent.com/23297417/93940312-1a75f280-fce1-11ea-8f52-01d357d92e92.png">
Documentation drop down looks weird. Since it all leads to a single page, I would just remove it for now.

**Comment by morsssss** [comment]
See also https://github.com/google/web-stories-wp/issues/4623

**Comment by CrystalOnScript** [comment]
I closed mine, but I still think the drop down should be removed until there is more than one page of documentation :)

**Comment by CrystalOnScript** [comment]
Closed, dupe.
