### ISSUE TITLE
Loading issues and link problems not solved

### ISSUE THREAD

**Issue by DanielCryptoK** [GoogleForCreators/web-stories-wp#4643]
Hi,

I posted yesterday but someone close before I get a chance to reply.

The issue I reported was that you can not add text links. The person that answered misunderstood as they showed how it was possible to add a link to stories but ignored the fact that the question was how to add a text link. It is only possible to link a whole block and not individual text.

There is also loading issue when opening in editor. 

Please see attached
![Edit Story ‹ Bitcoin Casino No Deposit Bonus — WordPress (8)](https://user-images.githubusercontent.com/45933242/93956822-3333e600-fd7d-11ea-818f-b99d3c121391.png)
![Edit Story ‹ Bitcoin Casino No Deposit Bonus — WordPress (7)](https://user-images.githubusercontent.com/45933242/93956826-35964000-fd7d-11ea-890b-e8fe503d3ac7.png)
![My Stories ‹ Web Stories − WordPress](https://user-images.githubusercontent.com/45933242/93956827-35964000-fd7d-11ea-8732-246d4094c7fb.png)
![Edit Story ‹ Bitcoin Casino No Deposit Bonus — WordPress (6)](https://user-images.githubusercontent.com/45933242/93956952-768e5480-fd7d-11ea-9135-f8d9e41eeb82.png)

**Comment by swissspidy** [comment]
Hi @DanielCryptoK 

My apologies for closing your other issues too soon. Please don't hesitate to reply even on closed issues as we still get notified and can easily reopen them.

Also, sorry for misunderstanding your question about links.

Thanks for bearing with me here and taking your time to write down your thoughts and annotating your screenshots, I really appreciate it!

You are indeed correct that it is currently only possible to link a whole block and not individual text. However, links for text selection is something we are considering supporting in the future.

This enhancement is being tracked in #1158. Please follow that ticket for any progress on that matter.

Adding support for `rel="nofollow"` or `rel="sponsored"` is also something we're planning on implementing. Please follow #4440 for progress on that.

-----

On the performance side of things, as I've previously said it's something we're devoted to improving in the near future. We're just getting started, so the plugin can still be a bit rough around the edges.

You should see lots of performance improvements over the next weeks and months as we continue to develop the plugin.

Now, it's difficult to say from screenshots alone what exactly is causing the performance issues, as there are tons of factors: your computer's hardware, the server capabilities, internet connection, set of installed plugins, etc.

I do want to highlight that your site is running lots of other plugins that seem to impair your site's performance. What I am seeing at first glance:

- Over 18 seconds for PHP site generation itself  
  That should be < 5 seconds usually.
- Over 1600 database queries  
  For comparison: a new site has maybe 50 database queries on that screen

While we're doing everything we can to improve things on our side, it might be worth looking into this regardless of Web Stories.
