### ISSUE TITLE
Footer layout is broken on mobile devices

### ISSUE THREAD

**Issue by morsssss** [GoogleForCreators/web-stories-wp#4644]
I noticed this on https://wp.stories.google in Chrome's mobile emulator, for various devices.

For example, here's how the footer looks on a Pixel 2:

<img width="402" alt="Screen Shot 2020-09-22 at 10 39 23 PM" src="https://user-images.githubusercontent.com/29419498/93958543-bb39d180-fd24-11ea-8577-4d5ca07e127d.png">

**Comment by swissspidy** [comment]
Looks like this has been fixed
