### ISSUE TITLE
Dashboard: Settings Page; Cannot scroll to the right of the page at 1280px width

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#4648]
## Bug Description

In Chrome, under Windows, perhaps macOS, I cannot scroll to the right in the settings page thus cutting off the button.

## Expected Behaviour

I should be able to see all the page content. This should likely scale down the size.

## Steps to Reproduce

1. Visit the Settings Page from the Dashboard
2. Ensure your browser is 1280px width.

## Screenshots

![image.png](https://images.zenhubusercontent.com/5ea09bca6a44046f869bafe0/60086660-2241-4c5d-a408-67067c7e6890)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Instead of scrolling, maybe the labels should be really above the input fields on smaller screens like this? Not a designer though :)

**Comment by csossi** [comment]
Verified in QA
