### ISSUE TITLE
Zoom Capability When Editing

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#4649]
## Feature Description

User requested feature to zoom in and out when creating or editing. 
## Alternatives Considered

You can use your trackpad or mouse to zoom in and out.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
@LuckynaSan FYI there's #4022 for this already 🙂

**Comment by swissspidy** [comment]
Duplicate of #4022
