### ISSUE TITLE
TypeError: e.toFixed is not a function

### ISSUE THREAD

**Issue by joeygeo** [GoogleForCreators/web-stories-wp#4651]
TypeError: e.toFixed is not a function
    in SizePositionPanel
    in Unknown
    in form
    in designPanel__Form
    in DesignPanel
    in DesignPanels
    in div
    in designInspector__TopPanels
    in div
    in designInspector__Wrapper
    in DesignInspector
    in div
    in inspectorContent__InspectorPane
    in section
    in inspectorContent__InspectorPanes
    in Inspector
    in div
    in inspectorLayout__InspectorContainer
    in section
    in inspectorLayout__Layout
    in InspectorLayout
    in div
    in dropTarget__Content
    in Unknown
    in div
    in dropTarget__DropTargetComponent
    in UploadDropTarget
    in Unknown
    in InspectorProvider
    in ZG
    in hH
    in div
    in layout__InspectorArea
    in Unknown
    in RichTextProvider
    in Unknown
    in UnitsProvider
    in Unknown
    in CanvasProvider
    in Workspace
    in section
    in layout__Editor
    in sZ
    in Unknown
    in DropTargetsProvider
    in Unknown
    in TransformProvider
    in Unknown
    in MediaProvider
    in Unknown
    in FontProvider
    in Unknown
    in StoryProvider
    in Unknown
    in SnackbarProvider
    in Unknown
    in HistoryProvider
    in Unknown
    in Media3pApiProvider
    in Unknown
    in APIProvider
    in Unknown
    in ConfigProvider
    in hH
    in ThemeProvider
    in StyleSheetManager
    in App
    in FlagsProvider

**Comment by swissspidy** [comment]
Thanks for your report @joeygeo!

What was the last action you've taken prior to getting this error?

**Comment by joeygeo** [comment]
Searching for old images in media library, was not returning anything... so I clicked on Upload button, and selected the image from media library explicitly. But that image was dropped as a point... null-null position, with null-null size. I had to struggle with the image handles a bit, and somehow managed to change the parameters, and when saving it ... it showed the crash report message in settings panel.

**Comment by joeygeo** [comment]
I have a big problem... I cannot save/publish this story, I had been creating for an hour.
I still have the editor screen with all stuff, but on saving, there is an error - failed to save.

I tried opening All stories on another tab... But that gives a red balloon error:
Unable to Load Stories
The response is not a valid JSON response.

**Comment by swissspidy** [comment]
@joeygeo Could you please share your Site Health info with us (Tools -> Site Health -> Info -> copy to clipboard). It could be that another plugin is interfering, so please try the following to help us debug:

1. Open your browser's dev tools (usually by pressing F12), for example in Chrome
1. Click on the "Network" tab and select "XHR"
1. Go to the Stories Dashboard (where you see the the red balloon error)
1. In the list of requests, click on the one containing "web-story" in it, and then click on the "Response" tab
1. You should see something like this:

<img width="1100" alt="Screenshot 2020-09-23 at 19 54 50" src="https://user-images.githubusercontent.com/841956/94050659-dcf39100-fdd6-11ea-9553-40af1e85da32.png">

Can you share such a screenshot with us?

**Comment by swissspidy** [comment]
Also, as a general helpful advice, try temporarily disabling all other plugins to see if the error still occurs.

**Comment by joeygeo** [comment]
I did the F12 steps... there is no response in the webstory? XHR url...
you are probably right abt plugin conflict... my seo plugin could be interfering.. I try disabling that next.

**Comment by joeygeo** [comment]
Site Info:

`
### wp-core ###

version: 5.5.1
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 9
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/runcloud/webapps/bitscoins
wordpress_size: 97.00 MB (101713107 bytes)
uploads_path: /home/runcloud/webapps/bitscoins/wp-content/uploads
uploads_size: 1.63 GB (1749463005 bytes)
themes_path: /home/runcloud/webapps/bitscoins/wp-content/themes
themes_size: 3.70 MB (3880890 bytes)
plugins_path: /home/runcloud/webapps/bitscoins/wp-content/plugins
plugins_size: 142.99 MB (149938844 bytes)
database_size: 155.68 MB (163237151 bytes)
total_size: 2.02 GB (2168232997 bytes)

### wp-dropins (1) ###

object-cache.php: true

### wp-active-theme ###

name: GeneratePress (generatepress)
version: 2.4.2
author: Tom Usborne
author_website: https://tomusborne.com
parent_theme: none
theme_features: core-block-patterns, automatic-feed-links, post-thumbnails, post-formats, woocommerce, title-tag, html5, customize-selective-refresh-widgets, align-wide, responsive-embeds, custom-logo, menus, editor-style, widgets
theme_path: /home/runcloud/webapps/bitscoins/wp-content/themes/generatepress
auto_update: Disabled

### wp-themes-inactive (1) ###

Twenty Twenty: version: 1.5, author: the WordPress team,Auto-updates disabled

### wp-mu-plugins (2) ###

0-ninjafirewall.php: version: 1.0, author: The Ninja Technologies Network
ManageWP - Worker Loader: author: GoDaddy, version: (undefined)

### wp-plugins-active (39) ###

404 Solution: version: 2.22.10, author: Aaron J, Auto-updates disabled
Ad Inserter: version: 2.6.14, author: Igor Funa, Auto-updates disabled
AMP: version: 2.0.4, author: AMP Project Contributors, Auto-updates disabled
Anti-Spam by CleanTalk: version: 5.146.1, author: СleanTalk <welcome@cleantalk.org>, Auto-updates disabled
Async JavaScript: version: 2.20.03.01, author: Frank Goossens (futtta), Auto-updates disabled
Automatic Post Tagger: version: 1.8.2, author: Devtard, Auto-updates disabled
BunnyCDN: version: 1.0.7, author: BunnyCDN, Auto-updates disabled
Cityom: version: 1.3.7, author: Coversine LLC, Auto-updates disabled
Cloudimage - Responsive Images as a Service: version: 2.9.4, author: Cloudimage, Auto-updates disabled
Elementor: version: 3.0.8.1, author: Elementor.com (latest version: 3.0.10), Auto-updates disabled
Elementor Pro: version: 2.10.3, author: Elementor.com, Auto-updates disabled
GP Premium: version: 1.11.3, author: Tom Usborne, Auto-updates disabled
iThemes Security: version: 7.8.0, author: iThemes, Auto-updates disabled
LoginPress - Customizing the WordPress Login: version: 1.4.6, author: WPBrigade, Auto-updates disabled
LoginPress - Hide Login: version: 1.2.2, author: WPBrigade, Auto-updates disabled
LoginPress Pro: version: 2.4.0, author: WPBrigade, Auto-updates disabled
ManageWP - Worker: version: 4.9.7, author: GoDaddy, Auto-updates disabled
Massive Cryptocurrency Widgets: version: 3.1.6, author: Blocksera, Auto-updates disabled
NextScripts: Social Networks Auto-Poster: version: 4.3.18, author: NextScripts, Auto-updates disabled
NinjaFirewall (WP Edition): version: 4.2.5, author: The Ninja Technologies Network, Auto-updates disabled
NinjaScanner: version: 2.0.9, author: The Ninja Technologies Network, Auto-updates disabled
OneSignal Push Notifications: version: 2.1.4, author: OneSignal, Auto-updates disabled
Post SMTP: version: 2.0.15, author: Yehuda Hassine, Auto-updates disabled
Really Simple SSL: version: 3.3.5, author: Really Simple Plugins, Auto-updates disabled
RunCloud Hub: version: 1.0.4, author: RunCloud, Auto-updates disabled
ShortPixel Image Optimizer: version: 4.20.2, author: ShortPixel, Auto-updates disabled
Simple Author Box: version: 2.3.18, author: WebFactory Ltd, Auto-updates disabled
Table of Contents Plus: version: 2002, author: Michael Tran, Auto-updates disabled
TablePress: version: 1.12, author: Tobias Bäthge, Auto-updates disabled
The GDPR Framework: version: 1.0.40, author: Data443, Auto-updates disabled
URL Shortener Pro by MyThemeShop: version: 1.0.13, author: MyThemeShop, Auto-updates disabled
Website Tools by AddThis: version: 3.2.6, author: The AddThis Team, Auto-updates disabled
Web Stories: version: 1.0.0, author: Google, Auto-updates disabled
Wordpress Automatic Plugin: version: 3.50.7, author: ValvePress, Auto-updates disabled
Wordpress Auto Spinner - Post Rewriter: version: 3.7.5, author: ValvePress, Auto-updates disabled
WP Admin UI Customize: version: 1.5.12, author: gqevu6bsiz, Auto-updates disabled
WP External Links: version: 2.46, author: WebFactory Ltd, Auto-updates disabled
WP GDPR Compliance: version: 1.5.4, author: Van Ons, Auto-updates disabled
WP User Avatar: version: 2.2.7, author: ProfilePress, Auto-updates disabled

### wp-plugins-inactive (3) ###

Play.ht: version: 3.1.1, author: Play.ht, Auto-updates disabled
Rank Math SEO: version: 1.0.47.1, author: Rank Math, Auto-updates enabled
Search & Replace: version: 3.2.1, author: Inpsyde GmbH, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
file_uploads: File uploads is turned off
post_max_size: 256M
upload_max_filesize: 256M
max_effective_size: 256 MB
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 4.15.0-117-generic x86_64
httpd_software: nginx/1.19.2
php_version: 7.4.10 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: 60
upload_max_filesize: 256M
php_post_max_size: 256M
curl_version: 7.58.0 OpenSSL/1.1.1
suhosin: false
imagick_availability: false
pretty_permalinks: true

### wp-database ###

extension: mysqli
server_version: 10.4.14-MariaDB-1:10.4.14+maria~bionic-log
client_version: mysqlnd 7.4.10

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/runcloud/webapps/bitscoins/wp-content
WP_PLUGIN_DIR: /home/runcloud/webapps/bitscoins/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### amp_wp ###

amp_mode_enabled: transitional
amp_reader_theme: legacy
amp_templates_enabled: post, post, page, attachment, elementor_library, donotsellrequests, is_singular, is_front_page, is_home, is_archive, is_author, is_date, is_search, is_404, is_category, is_tag, is_post_type_archive[web-story]
amp_serve_all_templates: true
amp_css_transient_caching_disabled: n/a
amp_css_transient_caching_threshold: 5000 transients per day
amp_css_transient_caching_sampling_range: 14 days
amp_css_transient_caching_transient_count: undefined
amp_css_transient_caching_time_series: 
	20200701: 554
	20200702: 557
	20200703: 583
	20200705: 599
	20200706: 639
	20200707: 654
	20200708: 653
	20200709: 669
	20200711: 700
	20200712: 630
	20200713: 618
	20200716: 600
	20200717: 529
	20200718: 529
amp_libxml_version: 2.9.4

`

**Comment by joeygeo** [comment]
Sorry, siteinfo has too much sensitive info... it shows no problems, though.

**Comment by joeygeo** [comment]
Tried disabling SEO plugin RankMath, but still same issue... Funny thing is the editor is able to open the preview page without issues. All seems good from the editor, except the story fails to save. But if I refresh the editor tab, all changes are still there... I am nervous to close this tab... is there a way for me to get this cached editor tab's data ... so that I can use it to create a new stry from scratch...

**Comment by joeygeo** [comment]
ok, I tried loggin in via incognito browser window, and opened same editor tab's url, and I can see the editor loading all my changes fine... which means my changes are saved into the database... somehow, the errors are preventing me to see/edit the story.

**Comment by joeygeo** [comment]
Actually, the story has been successfully published, and is available to view on main site. The issue is only with the editor not giveing the correct message on save... and web stories not being listed on Stories Dashboard.

**Comment by swissspidy** [comment]
Thanks for the quick updates so far!

You can share your Site Health info privately via https://docs.google.com/forms/d/1CSdMaWCwfivOaImRfcUpMJELhjO9Lk7sbqbQlzvh0u0 if you want.

I'm afraid there's not an easy way to get the editor date for copy&paste.

You mention there's no in the XHR tab, would you mind sharing a screenshot of your developer tools "Network" tab open nevertheless? Make sure to open it _before_ saving the story. Or a video would be superb too.

My guess is that some other WordPress plugin breaks the REST API response, causing the error message while still making the saving work behind the scenes.

**Comment by joeygeo** [comment]
I sent the siteinfo details on your gdocs form... I had to create support issue on wordpress.org 
https://wordpress.org/support/topic/unable-to-load-stories-the-response-is-not-a-valid-json-response/

**Comment by joeygeo** [comment]
It seems the problem is with Stories Dashboard page... the "All Stories" option is listing the published story fine.

**Comment by joeygeo** [comment]
https://www.dropbox.com/s/g3drcw7waozhitr/MBHVWiXDg8.mp4?dl=0

**Comment by joeygeo** [comment]
Honestly, I do not think this is a huge problem anymore. The Stories Dashboard is of no use anyway. 
I can safely access my stories from All Stories link. Perhaps, you should remove the Dashboard link from this plugin.

**Comment by swissspidy** [comment]
@joeygeo Apologies for the silence here, we're still trying to reproduce the issue based on the data you sent via the form. But if you don't feel like it's a big deal we can deprioritize this of course.

I am still curious though what the issue is. One quick way to help find the issue is for you to install the [Health Check & Troubleshooting](https://wordpress.org/plugins/health-check/) plugin.
After installing the plugin, go to the plugins page and click "Troubleshoot" on the Web Stories plugin.

This will enable troubleshooting mode, with only that plugin active by default, and let you test further from there.

If the issue disappears in that mode, we at least know it's caused by another plugin and can continue from there.

-----

As for the dashboard, it's _the_ place to see your stories, explore templates, and change settings like your Google Analytics ID. So we cannot just remove it 🙂

**Comment by swissspidy** [comment]
Hi @joeygeo, we've released some big updates to the plugin this past week. And I think these errors should no longer occur. Could you give it another try?
