### ISSUE TITLE
Embedded Stories not loading

### ISSUE THREAD

**Issue by tahanzania** [GoogleForCreators/web-stories-wp#4653]
## Bug Description

When stories are embedded to Wordpress sites they have an infinity load screen. But work completely fine when loaded as individual URLS i.e site.com/web-stories/test-story works fine but once embedded using the plugin it doesn't work

## Expected Behaviour

Embeded stories should work with latest version of Wordpress and Gutenberg blocks

## Steps to Reproduce

Any Wordpress installation paired with Gutenberg should replicate this issue

## Screenshots

![image](https://user-images.githubusercontent.com/30271769/94036111-f3c3c480-fd91-11ea-99a8-64d9c6ade5f0.png)

Here's it working without the embed
![image](https://user-images.githubusercontent.com/30271769/94036218-135aed00-fd92-11ea-875f-10c501aaba28.png)

## Additional Context

- Plugin Version: V.1.0,0
- Operating System: 
- Browser: Tested on Chrome and Safari

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Hi @tahanzania 

Embeds work fine here on multiple sites. Do you perhaps any other plugins or chrome extensions active?

If you could share the URL to a blog post with the block in it that'd be helpful.

**Comment by tahanzania** [comment]
Doesn't load on this URL https://www.tahadharamsi.com/uncategorized/my-first-web-story/ 

Also I don't have AMP enabled, is that the reason why? I assume it works without AMP enabled.

**Comment by swissspidy** [comment]
@tahanzania Thank you!

No, you don't need AMP enabled. The error on your site seems to be that you have mixed content (HTTPS vs HTTP).

In Gutenberg, you entered `http://www.tahadharamsi.com/web-stories/my-first-web-story/`, but your story is available at `https://www.tahadharamsi.com/web-stories/my-first-web-story/`. Notice the difference between `https://` and `http://`.

To fix this, edit the block (or remove it and create a new one) in Gutenberg and use the `https://www.tahadharamsi.com/web-stories/my-first-web-story/` URL with `https` in it to embed the story.

This should fix this issue immediately.

In the meantime, we'll try to come up with a good way to fix this automatically for you.

**Comment by tahanzania** [comment]
@swissspidy  worked perfectly! I used the feature from the plugin that auto embedded the story to the post, it looks like the auto post creator embeds as HTTP.  Thanks for your help!

**Comment by swissspidy** [comment]
@tahanzania Awesome, glad to hear that! And thanks for the additional info.

We use whatever URL is provided by WordPress. I recommend checking your URL settings under Settings -> General to make sure they start with `https://`.

PS. If you like the plugin so far, please consider adding a review for it at https://wordpress.org/support/plugin/web-stories/reviews/#new-post 🙂

**Comment by tahanzania** [comment]
@swissspidy  I just left a review. Also since I use GCP for hosting so I have to do the URL settings from the SSH (thanks tho forgot to change that)

**Comment by nqcm** [comment]
Hi @swissspidy 

I am having the same issue, although my story URL is starting with https. It never worked even when I let the plugin create a post automatically for me. Here is the test page https://stories.naveeraashraf.com/2020/10/21/sea-fever-test/
