### ISSUE TITLE
Text - Highlight

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#468]
## Feature Description

As an author I want to be able to highlight text

**Design and UX**
Textbox color s defaulted to none. As soon as you add a color, you should see option for textbox fill or highight. It is defaulted to fill. Heads up that I need to add additonal rules for how textbox color works with border radius and how to adjust line height for textbox highlight state but this shouldn't block initial work on just getting the basic functionality in.

![image](https://user-images.githubusercontent.com/5874851/76866352-67f93a80-683a-11ea-95fd-d71d1d4f97e7.png) 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. The author is able to add highlights to text (not the entire box)

**Comment by jauyong** [comment]
@jauyong to add design link

**Comment by obetomuniz** [comment]
Any plan about adding the expected designs on it? Should it be flagged as UX Needed?

**Comment by jauyong** [comment]
@samitron7 Can you add highlight to the panel here in the designs please?

![image](https://user-images.githubusercontent.com/5874851/76319912-44704600-62b6-11ea-9655-28d566f77a49.png)

**Comment by samitron7** [comment]
Textbox icolor s defaulted to none. As soon as you add a color, you should see option for textbox fill or hilight. It is defaulted to fill. Heads up that I need to add additonal rules for how textbox color works with border radius and how to adjust line height for tectbox hilite state but this shouldn't block initial work on just getting the basic functionality in.

![Group 4434](https://user-images.githubusercontent.com/10889431/76462154-7066f680-639e-11ea-8846-d552ae47f267.png)

**Comment by barklund** [comment]
Should we close this one? Current iteration is merged, and future iterations have new issues already created – @jauyong?

**Comment by jauyong** [comment]
Closing per the above
