### ISSUE TITLE
Edit Font Color of Page Attachment Link Text

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#4682]
## Feature Description

Customize color of the call to action text displayed on the UI when opening page attachment. Default: "Learn More" is white text: https://jmp.sh/734Hdvx

## Alternatives Considered

Use a shape to add a dark overlay or a shape to make the link text more visible. 
In this example story the user added a linear overlay that makes "Learn More" more visible: https://jmp.sh/zWZ8uZf 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
This can be achieved using the light and dark theme options
