### ISSUE TITLE
Element link won't work while no page attachment

### ISSUE THREAD

**Issue by lucemia** [GoogleForCreators/web-stories-wp#4688]
## Bug Description

The element link feature only work while page define page attachment.

## Expected Behaviour

The element link should work w/wo page attachement.

## Steps to Reproduce

1. on a page without page attachment, add link on an element

![截圖 2020-09-25 下午2 08 32（2）](https://user-images.githubusercontent.com/432851/94232479-acc40380-ff38-11ea-8228-330aa8aaa685.png)

2. preview, the element link won't work
![截圖 2020-09-25 下午2 11 52（2）](https://user-images.githubusercontent.com/432851/94232654-1512e500-ff39-11ea-9c4e-e4659afc36de.png)

3. back to editor, add a page attachment 
![截圖 2020-09-25 下午2 10 41（2）](https://user-images.githubusercontent.com/432851/94232604-f44a8f80-ff38-11ea-8a30-43648152cc21.png)

4. preview again, the element link works
![截圖 2020-09-25 下午2 10 52（2）](https://user-images.githubusercontent.com/432851/94232626-0298ab80-ff39-11ea-80f5-63d4ab01e590.png)

## Additional Context

- Plugin Version: Version 1.1.0-alpha
- Operating System: Mac
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Thanks for your report!

I see you are using our local dev environment—thanks for testing!

I really thought we had fixed this already. @miina can you take a quick look?

**Comment by swissspidy** [comment]
@lucemia I'm afraid I can't really reproduce this:

1. Create a new story
1. Add text element
1. Add link
1. Preview story
1. Link is there

On your step 2) from your report, when you go back to the editor after previewing the story, do you still see the link option in the Design Panel? Does it look like this:

<img width="828" alt="Screenshot 2020-09-25 at 11 19 38" src="https://user-images.githubusercontent.com/841956/94250064-028cb180-ff21-11ea-86ba-18a3eacae7ee.png">

**Comment by miina** [comment]
Tried to reproduce this as well -- without luck.
The issue did exist but was fixed within https://github.com/google/web-stories-wp/pull/4323

I'm also seeing this icon on the screenshots:
<img width="187" alt="Screenshot 2020-09-25 at 12 54 51" src="https://user-images.githubusercontent.com/3294597/94253756-0f5fd400-ff26-11ea-8308-cb38ebac50f3.png">

That was also removed recently -- it hints as if the version used is not fully up to date. Thoughts?

**Comment by swissspidy** [comment]
The version above says 1.10-alpha, which would be the current main branch.

Maybe need to run `npm run build`

**Comment by lucemia** [comment]
@miina @swissspidy 
thanks!!

after `npm run build` , the issue is gone.

Sorry for misleading
