### ISSUE TITLE
"Delete Page" button not working when there is only 1 page

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#4690]
## Bug Description

The "Delete Page" button does nothing when there's only 1 page. It doesn't clear the canvas or anything.

## Expected Behaviour

Button should be disabled

**Note:** For accessibility reasons, it should probably only appear disabled, but still be able to receive focus. Otherwise it won't get announced to screen readers.

## Steps to Reproduce

1. Create new story
1. Try to click on "Delete Page" button

## Screenshots

<img width="390" alt="Screenshot 2020-09-25 at 11 13 21" src="https://user-images.githubusercontent.com/841956/94249521-4df29000-ff20-11ea-87a9-05e6d764606f.png">

## Additional Context

- Plugin Version: 1.0.0
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by samitron7** [comment]
This ticket is a dup of [783](https://app.zenhub.com/workspaces/web-stories-5e94d3aced449034e1e9b226/issues/google/web-stories-wp/783) and will close.
