### ISSUE TITLE
Safe Zone markers not matching frontend output

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#4694]
## Bug Description

A user just reported this [on the forums](https://wordpress.org/support/topic/location-of-story-after-publishing-and-error/#post-13454614).

I was able to reproduce this too.

It appears that the safe zone markers don't match the actual frontend output.

Is this expected and just needs documentation, or do we need to change anything?

## Expected Behaviour

Safe zone markers should be reliable

## Screenshots

<img width="777" alt="1" src="https://user-images.githubusercontent.com/841956/94289114-84e49800-ff58-11ea-925b-ababa31e5cda.png">
<img width="1019" alt="2" src="https://user-images.githubusercontent.com/841956/94289116-8615c500-ff58-11ea-80e7-3c29caa51e35.png">

## Additional Context

- Plugin Version: 1.0.0
- Operating System: macOS
- Browser: Chrome 85

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
I know it's a bit odd, but I think this can be expected. The safe zone marks what would avoid text getting cutoff across all popular mobile screen sizes, but the preview doesn't necessarily represents that worse case scenario. 

We have a goal to improve the preview so a user can see what the output would look like on multiple device aspect ratios, that should help a ton here. #50

**Comment by swissspidy** [comment]
Until then it's probably a matter of documentation I suppose

**Comment by bmattb** [comment]
@swissspidy / @o-fernandez - we feel that this is no longer relevant as the new preview is implemented, can you validate? ty
