### ISSUE TITLE
Unable to Scroll on an Embedded Web Story 

### ISSUE THREAD

**Issue by netnaps** [GoogleForCreators/web-stories-wp#4700]
## Bug Description

Have tried scrolling on the Embedded Web Story, on AMP CDN Url and Normal Direct Url 

I am unable to Scroll on the Story that is Embedded, 
I can scroll on the Area around the Embed. 

Only about the Mobile Devices Touch Screen When Scrolling.
You can check with a similar situation, on an AMP Standard Mode I have Tested.

## Expected Behaviour

Should be Able to Scroll on the Embedded Story 

## Steps to Reproduce

Ton Mobile Devices, iPhone Latest Version, Samsung Latest Android Versions.
Browser Chrome and Safari

## Additional Context

- Plugin Version: Latest
- Operating System: ios, Android 
- Browser: Chrome, Safari

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by LuckynaSan** [comment]
@netnaps Hi there! We've moved support to the [WordPress.org forums](https://wordpress.org/support/plugin/web-stories/). Please open a [new support topic](https://wordpress.org/support/plugin/web-stories/#new-post) with the above information and we'll happily continue troubleshooting with you there.

**Comment by swissspidy** [comment]
@netnaps FYI, I believe this issue is was reported upstream in the AMP project: https://github.com/ampproject/amphtml/issues/28009

That means they're already aware of this issue and tracking this accordingly.

**Comment by netnaps** [comment]
@swissspidy thanks before I reported this I was unable to find this error on searching out 
A visitor to my blog reported this with my post, shall await this to be rectified. So far, the plugin looks good and works well.

Thanks again.
