### ISSUE TITLE
Editor: input fields use placeholders for labels, impairing usability

### ISSUE THREAD

**Issue by westonruter** [GoogleForCreators/web-stories-wp#4706]
## Bug Description

I uploaded a video and right as I saw the Accessibility section show as follows:

![image](https://user-images.githubusercontent.com/134745/94356216-85f0f480-0040-11eb-9106-69a45b985c9f.png)

The filename was populating these two text fields, but I didn't know what these fields were for. I had to delete the text out of the field to then see that the first one was for the "Title" and the second was for the "Assistive text". Even so, I'm not entirely sure as a user what the difference is between these two fields.

## Expected Behaviour

Placeholders should not be used as labels.

See also:
https://www.nngroup.com/articles/form-design-placeholders/
https://www.smashingmagazine.com/2018/06/placeholder-attribute/

## Steps to Reproduce

Upload a video and add to a story page.

## Additional Context

- Plugin Version: 1.1.0-alpha
- Operating System: MacOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by westonruter** [comment]
Update: The "Assistive text" (`alt` attribute) appears to not actually serve a purpose on `amp-video`. See https://github.com/google/web-stories-wp/issues/4708.

**Comment by swissspidy** [comment]
@aaskedall any thoughts on how we can best fix this? We use placeholders instead of labels in multiple places, which is really an a11y anti-pattern.

**Comment by swissspidy** [comment]
@agingoldseco any thoughts on how we can best fix this? We use placeholders instead of labels in multiple places, which is really an a11y anti-pattern.

**Comment by agingoldseco** [comment]
@swissspidy I noticed this issue—my design updates for the right column actually fix it, at least in the accessibility panel, by putting the instructions above the text box. We can have a broader discussion on doing that for all text fields, but to my knowledge that's the only one that automatically populates and obscures description text right now. This is the updated version:

<img width="298" alt="Screen Shot 2021-11-10 at 12 16 52 PM" src="https://user-images.githubusercontent.com/90645922/141161101-80f4cd8d-7d76-426a-ae9c-e0cc2f294b53.png">

**Comment by BrittanyIRL** [comment]
Hi, just combing through the backlog and noticed this. So, there is a `VisuallyHidden` util in the design system that we'd been using in the dashboard to make a hidden label. When we were given designs that didn't visibly show the label in the form, I figured this approach would be taken. 

I think it'd be useful at this point to create a component in the ds that is a `VisuallyHiddenLabel` and then just use that to fix this problem across the editor. Adding descriptions like the above would be helpful but that's still not a label. 

Thoughts? If that sounds good pea pod has capacity this month and I feel a little responsible for this not getting caught when the ds was getting implemented last year. 

The Dashboard settings page uses this approach I'm suggesting if you wanna see it in action.

**Comment by swissspidy** [comment]
A visually hidden label helps for screen readers but does not help sighted users.

I know the input field originally reported in this ticket has since been updated, but take a look at that screenshot again:

![image](https://user-images.githubusercontent.com/134745/94356216-85f0f480-0040-11eb-9106-69a45b985c9f.png)

A visually hidden label does not help you understand what either of those fields mean.

Quote:

> I had to delete the text out of the field to then see that the first one was for the "Title" and the second was for the "Assistive text".

**Comment by BrittanyIRL** [comment]
thanks, @swissspidy i did a poor job of reading through this before chiming in.
