### ISSUE TITLE
TypeError: Object.fromEntries is not a function

### ISSUE THREAD

**Issue by youseffi1661** [GoogleForCreators/web-stories-wp#4709]
TypeError: Object.fromEntries is not a function
    in RichTextProvider
    in Unknown
    in UnitsProvider
    in Unknown
    in CanvasProvider
    in Workspace
    in section
    in layout__Editor
    in sZ
    in Unknown
    in DropTargetsProvider
    in Unknown
    in TransformProvider
    in Unknown
    in MediaProvider
    in Unknown
    in FontProvider
    in Unknown
    in StoryProvider
    in Unknown
    in SnackbarProvider
    in Unknown
    in HistoryProvider
    in Unknown
    in Media3pApiProvider
    in Unknown
    in APIProvider
    in Unknown
    in ConfigProvider
    in hH
    in ThemeProvider
    in StyleSheetManager
    in App
    in FlagsProvider

**Comment by swissspidy** [comment]
Hi there, which browser are you using?

**Comment by LuckynaSan** [comment]
@youseffi1661 As we haven’t received a response, this issue will be closed. Please feel free to open a new support topic on the [WordPress.org support forum](https://wordpress.org/support/plugin/web-stories/#new-post) if you continue to experience any issues. Thank you!
