### ISSUE TITLE
Media Hotlinking: Embed hotlinked images and video

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#471]
## Feature Description

As an author I want to be able to embed external sources via hotlink. In other words, when working in the editor, I can add an image or video by specifying the image or video URL. 

A few specs: 
- It would only work for video or image file formats supported by the editor. 
- The UI should let the user know if there's an error inserting the image or video and explain why as possible (e.g., couldn't access the image or video, URL is not a valid image or video, format not supported, etc.) 
- If a video is added to the story by hotlink and it is not optimized for web serving (e.g., resolution/size is too high) we should alert the user in the pre-publish checklist. However, we need to let the user know that this file can't be optimized by us as it is not hosted in their WordPress media library. **(NOTE: we can consider a future enhancement to optimize the video and upload it into the user's WordPress library in the future, but TBD if that's needed, not in scope for this one)** 

For consideration: 
- The MVP should be simple, as per above specs. 
- For future iterations (separate tickets) we can consider making it easier for the user to reuse the same media element on multiple stories by updating the media library to include media they "added by URL" somewhere. These items not hosted on the WP library should be easily distinguishable from their local WP library, similar to how 3P media is separate and distinguishable today. 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
1. I am able to embed an external image via hotlink
2. I am able to embed an external video via hotlink

Does not work in AMP Story:
1. As an author I want to be able to embed youtube videos
2. As an author I want to be able to embed instagram posts

**Comment by jauyong** [comment]
Hey @samitron7 as discussed today, I'm flagging you for designs on this feature

**Comment by jauyong** [comment]
Paul and Sam to review, will not be part of sprint 25

**Comment by samitron7** [comment]
Sorry, what's a hotlink and is there a brief for this? @pbakaus @o-fernandez (Paul, apologize in advance if it's buried somewhere but I can't find it)

**Comment by swissspidy** [comment]
@samitron7 Hotlinking means taking an arbitrary image URL and embedding it in the story, without uploading it to the library. E.g. inserting the image http://someotherwebsite.com/picture.jpg

**Comment by samitron7** [comment]
@swissspidy Do you know what is needed from me for the ui? I'm not sure what I should be doing her.e

**Comment by swissspidy** [comment]
@samitron7 First of all, I don't know whether we want to support this functionality or not, but if we want to, there would need to be a way to enter a URL to embed an image. For example, Gutenberg offers this:

<img width="677" alt="Screenshot 2020-07-02 at 17 04 35" src="https://user-images.githubusercontent.com/841956/86375586-32138100-bc86-11ea-946f-b2aee178d0a3.png">

**Comment by o-fernandez** [comment]
I think this would be nice functionality, and we'll need it eventually, but should wait for user feedback before working on this. This is (properly) in the icebox, so we shouldn't work on it for now.

**Comment by pbakaus** [comment]
+1. I sense that users will want this, but OK for me to wait until this turns out to be true.

**Comment by samitron7** [comment]
+1 on waiting for feedback :)

**Comment by RobertoDonPedro** [comment]
Regarding feedback...:): I definitely encourage you to embed external urls, especially for youtube videos. This helps prevent unnecessary bloating of WordPress sites. Personallly I think this feature should be available as soon as possible.

**Comment by swissspidy** [comment]
@RobertoDonPedro Embedding YouTube videos is actually not possible from a technical perspective, i.e. it's not allowed in the AMP spec. So it's nothing we can implement. Instead of embedding YouTube videos, would you want to embed external videos or images by entering a URL?

**Comment by RobertoDonPedro** [comment]
@swissspidy I'm sorry that I have expressed myself badly. I would want to embed an external YouTube video by entering its URL, that should be possible, right?

**Comment by swissspidy** [comment]
@RobertoDonPedro I understood it :-) Yes, theoretically that would be _possible_, however  it is now _allowed_ due to restrictions by the underlying AMP specification Web Stories are built on. So we cannot support embedding YouTube videos in stories in any way.

**Comment by RobertoDonPedro** [comment]
@swissspidy Hmm, so it would be allowed to embed other external video URLs but no YouTube URLs???

**Comment by swissspidy** [comment]
@RobertoDonPedro Currently supported is embedding videos from a specific video URL like `https://example.com/mycoolvideo.mp4`. No YouTube or the like as it‘s not allowed in Web Stories.

**Comment by ai-Apps-coder** [comment]
this is an important feature if we need to insert images from google maps like this https://lh5.googleusercontent.com/p/AF1QipOR4RX87kJCARnqv-oV0blUTxFe-ciFxJf7Flau=w600-h485-p-k-no

or images from google my company posts like https://posts.gle/JxbF6

**Comment by blogtutor** [comment]
> @RobertoDonPedro Currently supported is embedding videos from a specific video URL like `https://example.com/mycoolvideo.mp4`. No YouTube or the like as it‘s not allowed in Web Stories.

It seems that the WordPress Web Stories plugin does not allow embedding videos from an external URL -- it _only_ embeds videos hosted from within the WordPress media library. This is a huge problem for both server storage and bandwidth usage.

Can a feature to use externally-hosted video be added to the WordPress plugin?

**Comment by blogtutor** [comment]
I just found the [public roadmap](https://docs.google.com/spreadsheets/d/10DZZrWJdkjcJXD1vL0VG0PqRhsIqaHkacF_ujOdEwJc/view#gid=0), and am very glad to see these:

> Support hotlink: allow users to hotlink to images or videos (in supported formats) and use them in stories without adding to WP library.

> Embed videos from other sites (TBD services)

I hope they can be bumped up on the priority list! Thanks!  🤞🙏

**Comment by Vindulge** [comment]
Hi all, first time contributor, be kind. (vindulge.com is the site with stories) I concur with being able to embed for a few reasons. We have 16 stories currently, at least half with video. If there was a way to embed URL or video segments versus essentially duplicating them again as a media upload and running the video twice (once in the story sequence and one in the underlying content we are hoping to get people to see), it would do a few things:

- Right size the amount of storage needed for essentially the same content. I find this especially important when it comes to video as we are leaning into video specific stories (and see dramatically more pick ups from video than our photo only stories)
- Easier for us to make. I have a whole word document on my experience in the editor. If we can simply add some source code or a link and it pulls the video for us and sequences it, so much easier to make and for the user.
- Somehow create better continuity to the video and content between the story and the post we may want to introduce the user to. So if I want to show the steps in making a smoked beef brisket and the video we have on the site is 15 minutes, I just want to bring at most a few highlights of that video or find a better place to store the video so I can simply take the 7 second clip and have you pull the clip media feature into that frame. 

Right now I am essentially adding the video (again) to my story slide(s) which then causes the other unintended storage and bandwidth issues. Happy to share some examples.

I look forward to adding more feedback, but I am learning at ludicrous speed in this space. - Sean

**Comment by bemyhre** [comment]
Yes please. If I want to add video, I have to host it on my own server and bear the burden of costs. Not only space, but bandwidth. If I want to have 1 or 2, no big deal. If I want to create lots of web story content, it can be a huge issue. Space will become a problem over time and if I have one that happens to do really well, my costs might skyrocket, all for something that can be great, but requires a conversion from my own website to my actual website... which then needs another conversion to actually pay my costs.

**Comment by feastdesignco** [comment]
> Can a feature to use externally-hosted video be added to the WordPress plugin?

Agreed with this. It's critical to be able to embed external videos, as the bandwidth costs are burdensome.

**Comment by paulam20** [comment]
Completely agree with this thread. As an author I want to be able to embed external sources.

**Comment by blogtutor** [comment]
Are there any updates on this?  When Web Stories go viral on Discover, it can burn through a MASSIVE amount of bandwidth.  We have one client who has just used 7TB of bandwidth in the last 24 hours, almost exclusively from MP4's that are self-hosted in stories.  The video really needs to be able to be served from proper video providers, not regular web hosting companies -- this is now URGENT because we cannot sustain this traffic! It's costing us a fortune...

**Comment by swissspidy** [comment]
> Are there any updates on this? When Web Stories go viral on Discover, it can burn through a MASSIVE amount of bandwidth. We have one client who has just used 7TB of bandwidth in the last 24 hours, almost exclusively from MP4's that are self-hosted in stories. The video really needs to be able to be served from proper video providers, not regular web hosting companies -- this is now URGENT because we cannot sustain this traffic! It's costing us a fortune...

Thanks for sharing your experience and raising this concern! I don't have an update on this particular ticket, but there is definitely some progress in this area.

First, we are currently working on built-in client-side video optimization that will help greatly reduce the size of videos (savings of up to 90%!) and thus the bandwidth usage.

Then, there is some ongoing exploration towards serving videos from the AMP cache. So if your story goes viral on Discover, the videos could be served from the AMP cache instead of your server. Again massively reducing bandwidth usage.

Also, you can easily combine the Web Stories plugin with existing video transcoding solutions like [Jetpack’s video-hosting service](https://jetpack.com/features/design/video-hosting/). That's the great thing about the WordPress ecosystem: there's always a plugin for that!

**Comment by blogtutor** [comment]
Thanks @swissspidy for the reply on this.  I noticed the built-in optimization on the roadmap yesterday, and that would certainly help in many cases -- but when a web story takes off in the Discover feed, that wouldn't be nearly enough to stop the hemorrhaging. 

Serving video from the AMP cache would be fantastic. I was actually surprised to  learn that it wasn't already.

And in the meantime, I'm keen to learn more about Jetpack's solution.  Looks like that's available on the "Security" or "Complete" plans (which is fine).  But I'm wondering how that actually integrates with the Web Stories plugin?  Can you tell us more about how to tie the two together?  Thanks!

**Comment by swissspidy** [comment]
> And in the meantime, I'm keen to learn more about Jetpack's solution. Looks like that's available on the "Security" or "Complete" plans (which is fine). But I'm wondering how that actually integrates with the Web Stories plugin? Can you tell us more about how to tie the two together? Thanks!

If that Jetpack module is active, any videos you upload through the WordPress media library will be actually uploaded to Jetpack's CDN behind the scenes and optimized along the way. To WordPress and the Web Stories editor it will look like any other video hosted on your site, but it will actually be served from their CDN.

I'd assume you could achieve similar bandwidth reductions by using any other CDN solution on the market that works with WordPress. After all, serving from a CDN is usually way cheaper than from your own server.

**Comment by blogtutor** [comment]
Ah! Thanks for clarifying how that works. For the Jetpack flat monthly rate, this would probably blow away any usage-based CDN.  (Considering our one client yesterday burned through 7TB of data in just 24 hours...).  I'll work on that with this client and hopefully we can have it process video that's already been uploaded. (And, flat-rate pricing is nicely predictable.)

The "CDN Enabler" plugin also works well with the Web Stories plugin to rewrite domains on-the-fly (and it can be set to rewrite for only `.mp4` files) -- so we could do that with another CDN service provider, as you suggested.  Thanks!

**Comment by blogtutor** [comment]
@swissspidy So we gave Jetpack's Video CDN a try. Unfortunately, when we tried to insert videos that had been "intercepted" by Jetpack during upload (so they'd be hosted on their CDN), they showed up as images rather than videos in the Web Stories editor.

So we're back to using BunnyCDN for the hosting, and the Cache Enabler plugin to rewrite the domains for .mp4 files.

(Also, as a heads-up for anyone else who wants to try this: Using the "Add New" option will not work to upload videos and have Jetpack intercept them. You must drag & drop the video into the grid view...)

![image](https://user-images.githubusercontent.com/24479276/113492868-b7cf9180-948f-11eb-9445-2945498baf18.png)

https://jetpack.com/support/video-hosting/

**Comment by swissspidy** [comment]
@blogtutor Thanks for the update. We're tracking that particular conflict in #6909, please follow that ticket for any updates.

While we're working on addressing this, you might be able to work around it using the following code (in a plugin or theme):

```php
add_filter(
	'web_stories_allowed_mime_types',
	static function( $mime_types ) {
		$mime_types['video'][] =  'video/videopress';
		return $mime_types;
	}
);
```

(untested!)

**Comment by shanemery** [comment]
As another author who is struggling with the load web stories place on my bandwidth can you provide a current update as to if/when there will be a feature in the near future that will give authors the ability to host our videos on platforms that are actually designed to host and serve video?

Also, what are the current recommendations for web story video file type as well as recommended resolution and frame rate for a web story?

Thank you

**Comment by dreamofabear** [comment]
> can you provide a current update as to if/when there will be a feature in the near future that will give authors the ability to host our videos on platforms that are actually designed to host and serve video?

You can do this today with various video CDNs that integrate into WP (see blogtutor's comments above). 

We're also working on a solution that automatically redirects self-hosted videos to Google's CDN, which should be available in several weeks and is expected to reduce hosting costs to ~0.

> Also, what are the current recommendations for web story video file type as well as recommended resolution and frame rate for a web story?

Current recommendation is 720p @ 24fps. We'll update our video optimization feature to match this soon (probably v1.7), so simply you can get much smaller, optimized self-hosted video by simply dragging and dropping them into the editor.

**Comment by o-fernandez** [comment]
In addition to all the great discussion here, we are working on allowing insertion by link (hotlink) in the next 1-2 releases. So, you'll get a few different options, to summarize: 

- For now, you can use WP plugins to use other CDNs (e.g., JetPack VideoPress with compatibility [fixes done](https://github.com/google/web-stories-wp/issues/6909) with our release 1.7.2 - check if you're on the latest)
- For videos inserted into stories, use the video optimization to reduce their size to recommended dimensions for web serving, which will improve load times and can reduce your bandwidth costs (see comment right above) 
- We are working on a feature to, when possible, allow you to serve videos from the Google AMP Cache even when serving on your own site (e.g., not on Discover/Search where that should already be happening most of the time)

AND... we will be adding support for embedding/inserting images and videos into your story by hotlink in the next ~1-2 releases (hopefully), so keep tracking this ticket for more details.

**Comment by spacedmonkey** [comment]
We discussed this ticket in sprint planning. In my mind, hotlinking images / videos, means that there a text input that allows users to input a url. If this is the case, validation with client or server level. So if I inputted a url to a pdf or exe file, the editor would reject it. It is do some validation, we could ping the url, ensure that url is valid, returns 200 state and get the returned mime type. From the mime type we could workout what which type element to insert into the page. 

If the validation might need to be done on server level. So we would add a new REST API, that takes the url as a param, then hits the url and checks it. If it requires new REST API for validation, that would require some work from the Infra pod.

**Comment by blogtutor** [comment]
All that validation sounds nice, but at this point, to get this implemented as quickly as possible, why not simply check for a valid file extension? (And sanitize the text field for security, of course.)

If the editor doesn't then display an image or video, then the user will figure out pretty quickly that it's not working.

**Comment by swissspidy** [comment]
It's a nice idea but probably not something to bother for V0 of this feature.

First we need to specify specifics for how this feature should work.

@o-fernandez @choumx I think there are still some unanswered product and UX questions here:

* Should hotlinking the story poster or publisher logo be possible?
* Should hotlinking video posters be possible?
* If I hotlink a video element, how do I add a poster image?

**Comment by o-fernandez** [comment]
Good questions! Some thoughts below, we can iterate as we build and find constrains as well.  

**Should hotlinking the story poster or publisher logo be possible?**
I'd say this is P2, not necessary for MVP. 

**Should hotlinking video posters be possible?**
I'd also say this is P2, can be added later? I recognize this makes it so that the user is still uploading some assets to their WP media library and serving from their WP host, but seems like we can keep those small enough to not be a significant problem? 

**If I hotlink a video element, how do I add a poster image?**
I don't know what the options are here. Are we able to autogen a poster image (storing it in WP) by fetching the video and processing it, even if we don't store and serve the video from that WP? If not, that will be a problem... since we've had issues with video poster images... but we may need to then rely on creators to upload a poster image (I'd say similar to the above that hotlinking is P2 for video poster image, but let me know if I'm missing something. )

**UX for this interaction**
We don't have a design for this and don't have UX resources at the moment to look at this ticket. I was hoping to minimize scope by having an "add by link" button (either in WordPress media or 3rd Party Media tabs, similar to the upload button) that opens a box where you can enter the URL and click insert. Basic validation happens there. Then the element is added to the canvas like any other 3P image/video would. We can make it more user friendly/refine over time, but I think that'd be an acceptable MVP scope. Open to suggestions! 

**Re: Poster images for hotlinked videos**
For each hotlinked video, we should add the poster image to the media library hidden (like we do for other poster images). If the same video is hotlinked multiple times, we'd save a poster image for each time the video is hotlinked - this means that there will be a duplication of poster images in cases when the same video is used multiple times in one/multiple stories, but it keeps a 1-1 mapping between the hotlinked item and it's poster image, so we can delete the poster image if the hotlinked video is deleted.

**Comment by spacedmonkey** [comment]
> why not simply check for a valid file extension? 

Because it is possible to file extension could be wrong. So a js file saved and uploaded as jpg file. Automatically generated images can not have any file extension at all. 

Is there an security issue like Cross Site Scripting (XSS) without going any validation on the url? 

It is worth noting, we already have a rest api that does much of the work for us.The `Link_Controller` controller, take a url, curls the url, checks if the link is valid. A couple more line, would also check the mime type as well. I honestly don't think it is a lot of work..

**Comment by swissspidy** [comment]
As suggested above, for MVP we can do some basic validation when entering the URL (e.g. check if it's a valid URL), all client-side.
We can look at server-side validation afterwards.

**Comment by csossi** [comment]
Was unable to add a link to an mp4 video

Link is https://samplelib.com/lib/preview/mp4/sample-5s.mp4 :
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/43e8fd3b-d906-4fa5-ad58-2f76595ead21)

Got this error message when trying to insert:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/328b725e-d02f-4882-b420-e104668af24b)

**Comment by swissspidy** [comment]
@csossi That is expected as per the QA instructions:

> Note: Not all sites allow linking externally like this, in that case, an error starting with "Media failed to load" will be displayed under the input.

Use some URL like `https://media1.giphy.com/media/oKQHyK4yKMpLqkf0qh/giphy.gif?cid=790b76117161f82a76ab0feea8adbd10d48b38a3e033d063&rid=giphy.gif&ct=g` 

Other URLs will be made working in future iterations.

**Comment by csossi** [comment]
Verified in QA

**Comment by o-fernandez** [comment]
> In addition to all the great discussion here, we are working on allowing insertion by link (hotlink) in the next 1-2 releases. So, you'll get a few different options, to summarize:
> 
> * For now, you can use WP plugins to use other CDNs (e.g., JetPack VideoPress with compatibility [fixes done](https://github.com/google/web-stories-wp/issues/6909) with our release 1.7.2 - check if you're on the latest)
> * For videos inserted into stories, use the video optimization to reduce their size to recommended dimensions for web serving, which will improve load times and can reduce your bandwidth costs (see comment right above)
> * We are working on a feature to, when possible, allow you to serve videos from the Google AMP Cache even when serving on your own site (e.g., not on Discover/Search where that should already be happening most of the time)
> 
> AND... we will be adding support for embedding/inserting images and videos into your story by hotlink in the next ~1-2 releases (hopefully), so keep tracking this ticket for more details.

For everyone that has been watching this issue for a while, note that in addition to adding media hotlinking in the coming release, in this past release we also released https://github.com/google/web-stories-wp/issues/8310

Try it out as a way to optimize video serving. You can enable it from **Web Stories-> Settings -> Video Cache**

**Comment by swissspidy** [comment]
Just noting that media hotlinking is still being worked on and behind a feature flag

**Comment by mxbclang** [comment]
@swissspidy Is there an open ticket(s) that for the continued work? We have had several requests for this in the forums so I want to make sure I can follow along and follow up with users accordingly when this is ready to go.

**Comment by dreamofabear** [comment]
@bethanylang Very timely comment -- there's an open technical issue (#8803) which we discussed today and will prototype a solution in the coming weeks.

However, we were also curious if the hotlinking feature is still needed today given: 
1. Our video optimization feature significantly reduces video sizes and corresponding bandwidth costs, and
2. Our new video caching feature will automatically serve videos from Google's servers which should eliminate bandwidth costs for most videos (Omar describes [how to use it above](https://github.com/google/web-stories-wp/issues/471#issuecomment-902879171))

Could you (a) list the forum posts here and (b) follow up with those users in the posts and ask them if (1) and (2) above satisfy their needs? This would be very useful for the team in designing the right solution to hotlinking.

**Comment by blogtutor** [comment]
Yes, "hotlinking" is still valuable! We need users to be able to store their "source" videos somewhere other than their media library (even if they're being served by Google's servers).

I've seen users uploading very, very large video files. This takes up storage space on the host, and can make backups (and restores, if necessary) significantly more challenging.

**Comment by swissspidy** [comment]
@blogtutor Even if the built-in video optimization massively reduces video file size? Are you manually offloading videos to some other location or are you using some CDN WordPress plugin?

**Comment by blogtutor** [comment]
The vast majority of our clients are just using the normal library (no offloading).  In some cases, we implemented CDN serving to solve bandwidth usage issues (which should be solved it Google's now serving the videos!).

We have clients uploading _hundreds_ of videos. So I guess it depends on what "massively reduces" means?

**Comment by swissspidy** [comment]
That's good to know, thank you!

> We have clients uploading _hundreds_ of videos. So I guess it depends on what "massively reduces" means?

In our testing, a 50MB video would easily be reduced to <1MB in file size, about the same size as a high-res image.

**Comment by blogtutor** [comment]
> In our testing, a 50MB video would easily be reduced to <1MB in file size, about the same size as a high-res image.

That sounds great -- and probably very workable for most people.  But we've got clients who will upload, say, 8 or 10 videos for one web story... so that's still ~10MB of space.  And then they're creating hundreds of web stories. So it still adds up fast.

(We also work with our clients to keep them from uploading 1MB images! That's far too large... Our recommendation is 1200px wide, around 200-400kb...and then we use Shortpixel to compress/optimize them even further.)

**Comment by mxbclang** [comment]
@choumx Thanks for following up! Here are the forum topics:

* https://wordpress.org/support/topic/web-story-video-picture-storage/
* https://wordpress.org/support/topic/videos-and-personal-images/
* https://wordpress.org/support/topic/plugin-questions-comments-and-concerns/
* https://wordpress.org/support/topic/how-to-adjust-my-videos-to-be-smaller-so-my-website-is-not-so-slow/
* https://wordpress.org/support/topic/best-practices-for-video-hosting/

You'll notice I've dropped a reply on each of them explaining our two new video hosting features to the users and asking them if these address their concerns or if they'd still prefer to have the option to hotlink. I'll update here as I get their feedback.

**Comment by mxbclang** [comment]
@choumx Update on https://wordpress.org/support/topic/web-story-video-picture-storage/ – this particular user says that the current options of optimization and serving via Google cache solve their storage issues, so they no longer see a need for offloading. No other replies so far.

**Comment by campiotto** [comment]
Please add a field to input media directly from a public CDN like BackBlaze, Amazon, Digital Ocean...

Our VPS server is getting full of videos and it would be horrible to resize it for misused storage.

**Comment by campiotto** [comment]
Is there a beta version that already has this feature?

**Comment by swissspidy** [comment]
@campiotto Thanks for sharing your feedback. We don't yet have a beta version of this but expect to have something more shareable in a month or so. There will be an input field to embed media from external sources simply by entering the URL.

**Comment by campiotto** [comment]
@swissspidy This is really great news. I've kept all the video files with a name like name-webstories.mp4, do you think this might make it easier later for me to move everything I've already created to the CDN?

I thought about exporting posts from webstories, fixing the url via regexp and reimporting. Is this the way?

**Comment by swissspidy** [comment]
If you're careful and perhaps first run the regex on a staging site then it should work, yeah.
