### ISSUE TITLE
Cannot paste text in dialog inputs

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#4710]
## Bug Description

If you try to paste some text into a text field in a modal dialog (anything that opens "above" the editor such as font picker search input), it fails. No paste in the input is performed. Instead, pasting creates a new text element.

## Expected Behaviour

I should be able to paste text in the font picker search input and similar modal inputs

## Steps to Reproduce

1. Create a new text element
1. Open font picker
1. Paste text

## Additional Context

- Plugin Version: 1.1.0-alpha
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@barklund @bmattb FYI Pulling this into 1.2 as the Sprint backlog is empty.

**Comment by csossi** [comment]
Verified in QA

**Comment by samitron7** [comment]
Verified in UAT
