### ISSUE TITLE
Highlight currently used items in media library

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#472]
## Feature Description

As an author I want to be able to identify which items from the media library were used

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
If this is still applicable, we'll need some ux help, moved to the ux needed column

**Comment by BrittanyIRL** [comment]
Talked about this with @agingoldseco in our design sync today and we agreed that this isn't something we need in the editor. The initial ask was well over a year ago and the description was quite vague. If the media in the editor is noise-y (like many variations of 1 media element present) then perhaps there's something else to do to make sure everyone's on the same page about how media works in the editor. Regardless, this 'highlight current items' doesn't need to happen. Closing so it stops circulating.
