### ISSUE TITLE
`.mask` in text element causing undesired cropping

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#4721]
Many Web Stories have part of their text cropped at the bottom. See example: 
![image.png](https://images.zenhubusercontent.com/5e98486db524b82fc96aeaf6/4f5bf864-6f64-444e-9dfd-f7e552920cf4)

Per @merapi's  review, this is due to .mask `overflow:hidden` which should be removed from the text element. 
Per @choumx's review, .mask is also causing issues with text padding in some cases.

Suggestion: remove .mask unless necessary for something else, otherwise remove `overflow: hidden` regardless, per @merapi discussion with text-sets channel. 

Needs to be properly reviewed and QA'd to ensure no adverse negative effects.

**Comment by swissspidy** [comment]
This could benefit from some Percy snapshots

**Comment by csossi** [comment]
Verified in QA
