### ISSUE TITLE
Masking

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#474]
## Feature Description

As an author I want to be able to mask elements

**[Feature Brief - Epic: Selection & in-place editing](https://docs.google.com/document/d/1_3-_v4zH6bW9hOplOO8wYxj8l4C0soMgEbD7XLiXrrg/edit#heading=h.laz27n36bom8)**

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
![image](https://user-images.githubusercontent.com/5874851/75945403-247cf480-5e68-11ea-95e9-8aa3ad40d78c.png)

Note: Media elements are masks from the get-go, as they always come with a media asset as “filling”.

**Comment by jauyong** [comment]
Was this covered in #35 ?

**Comment by wassgha** [comment]
An initial implementation is already existing, #269 will complete this

**Comment by jauyong** [comment]
Thanks Wassim. Closing.
