### ISSUE TITLE
Blocks: Stories Carousel

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#4747]
## Feature Description

**Story carousel: featuring any story published on the site.** 
- Sorting options: Recency (newest to oldest) → Default; P2: All time views; P2: Last X days views
- Filters: Number of stories to include (Default: 5); Dates to include (last X days, specific dates, etc.); P2: Story tags/categories to include or exclude from carousel. 

Dependencies for P2 items: categories and tags support for filtering, story pageviews/analytics integration for sorts. 

**Story grid: similar to story carousel, but in grid format.**
- Same configurable parameters as Story carousel, just a different UI and layout. 

-> covered by #3064

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
I think #3064 covers the grid part and has a good overview of possible options.

We should use the existing "Latest Posts" block as orientation, to know what kind of options people would expect.

> Dates to include (last X days, specific dates, etc.)

That sounds uncommon. Is there a use case for only including stories from specific dates? 🤔

**Comment by o-fernandez** [comment]
> > Dates to include (last X days, specific dates, etc.)
> 
> That sounds uncommen. Is there a use case for only including stories from specific dates? 🤔

I was thinking of a page with separate grids or carousels by season/month/etc. 
Similar to an archive, but the user decides what time frames to use. 

We can make that P2, for sure.

**Comment by o-fernandez** [comment]
@amedina @swissspidy assigning this issue to the two of you, I know Alberto has a plan here, let me know if you need anything from me.

**Comment by swissspidy** [comment]
Closing as this is being worked on by rtCamp.
