### ISSUE TITLE
Dashboard loading all users, causing performance issues

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#4753]
## Bug Description

The dashboard uses `useUserApi` which loads **all** existing users on a site. On sites with hundreds of users that's going to massively impact performance.

## Expected Behaviour

I don't see why we'd need to load **all** user data. We get all relevant user data when fetching stories, no need to fetch them separately.

## Additional Context

- User report: https://wordpress.org/support/topic/cloudflare-waf-block-json-issues/
- Plugin Version: 1.0.0
- Operating System: macOS
- Browser: Chrome 85

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
I agree here, I don't think that getting all users here is the best idea. 

As far as I understand, users data is only used for the users name when displaying lists of stories. This information can be returned in web stories endpoint with the embed param. Example url would look like this. 

https://stories-new-wordpress-amp.pantheonsite.io/wp-json/web-stories/v1/web-story/?_embed=true

Which will give an output like this 
```
    "_embedded": {
      "author": [
        {
          "id": 18,
          "name": "Marcin Pietruszka",
          "url": "",
          "description": "",
          "link": "https://stories-new-wordpress-amp.pantheonsite.io/author/marcin/",
          "slug": "marcin",
          "avatar_urls": {
            "24": "https://secure.gravatar.com/avatar/5a3ed7bda35d561c9e34c16fa9bbbc68?s=24&d=mm&r=g",
            "48": "https://secure.gravatar.com/avatar/5a3ed7bda35d561c9e34c16fa9bbbc68?s=48&d=mm&r=g",
            "96": "https://secure.gravatar.com/avatar/5a3ed7bda35d561c9e34c16fa9bbbc68?s=96&d=mm&r=g"
          },
          "_links": {
            "self": [
              {
                "href": "https://stories-new-wordpress-amp.pantheonsite.io/wp-json/wp/v2/users/18"
              }
            ],
            "collection": [
              {
                "href": "https://stories-new-wordpress-amp.pantheonsite.io/wp-json/wp/v2/users"
              }
            ]
          }
        }
      ]
    }
```

This should give all you all the information you need.

**Comment by swissspidy** [comment]
Yup, that was my recommendation too at https://xwp.slack.com/archives/C0134J07HV3/p1601415113021000 👍 Thanks for adding this here.

**Comment by BrittanyIRL** [comment]
Hey @csossi - for testing this: 

You should no longer see a call to `wp-json/wp/v2/users?per_page=100&_locale=user` if you open your dev tools -> network tab on dashboard load but you should still see your story creator listed in the dashboard (admin in the screen shot).
 
<img width="216" alt="Screen Shot 2020-10-08 at 1 58 32 PM" src="https://user-images.githubusercontent.com/10720454/95512906-5dd19180-096e-11eb-8e97-ddeb7f1ea084.png">

**Comment by csossi** [comment]
Verified in QA
