### ISSUE TITLE
Yoast SEO: stale cache after permalinks changed

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#4754]
## Bug Description

In 1.0.0 release, we switched the base URL for stories to be at domain.com/web-stories/ instead of the prior domain.com/stories/. However, some stories on sites using Yoast are still pointing to the old /stories/ URL as their canonical, triggering an issue with non-self canonical pages. 

## Expected Behaviour

Canonicals should be updated/fixed to point to the latest /web-stories/ canonical URL. 

## Steps to Reproduce

Examples where this has been seen: 
https://lsv-paf.de/stories/sunrise2020/
https://knaptonwright.co.uk/stories/website-copywriting/
https://wecomm.fr/web-stories/pourquoi-creer-site-web/

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
@swissspidy would love your review and thoughts here.

**Comment by swissspidy** [comment]
I meant to reply via email first, but alas :)

Yoast SEO caches this stuff in the database. There should be a way for us to re-index those entries to fix this.

**Comment by swissspidy** [comment]
Easier to implement than I thought. Should be able to push a fix tomorrow.
