### ISSUE TITLE
Story title field is unexpectedly truncated in editor

### ISSUE THREAD

**Issue by westonruter** [GoogleForCreators/web-stories-wp#4755]
## Bug Description

I provided my story with a title of “Running on Mount Tabor” which isn't particularly long. Nevertheless, the `input` field for the the Title is not wide enough to contain it:

![image](https://user-images.githubusercontent.com/134745/94624553-8e794300-026b-11eb-8893-dec55f875d7a.png)

It gets cut off. This is in spite of there seeming to be a _lot_ of “grayspace” between the field and the buttons on the right. In fact, the container `div` does stretch that entire width:

![image](https://user-images.githubusercontent.com/134745/94624663-d1d3b180-026b-11eb-8c18-9cd36ed3f687.png)

Perhaps the only thing needed is to give that `input` a `width:100%`:

![image](https://user-images.githubusercontent.com/134745/94624735-f891e800-026b-11eb-8bdf-06a99e4eeccd.png)

## Expected Behaviour

Story title field should not be truncated unnecessarily.

## Additional Context

- Plugin Version: 1.0.0
- Operating System: MacOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Yup, it's a known issue. It's been bugging me since day 1. The whole title/header area is pending some overhaul though, see #41
