### ISSUE TITLE
Allow decimal degrees for rotation

### ISSUE THREAD

**Issue by westonruter** [GoogleForCreators/web-stories-wp#4756]
## Feature Description

I wanted to align some text precisely against a flat edge which would have required providing a rotation of 0.5deg. I tried entering 0.5 it but I was unable to enter the period, so I had to settle with 1deg:

![image](https://user-images.githubusercontent.com/134745/94628371-ab664400-0274-11eb-8630-193bc31b3049.png)

I understand that clamping to a step of 1deg makes sense for rotating with the grab handle, but it would be nice if I could enter a precise rotation degrees in the text field.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by Sidsector9** [comment]
Hi @swissspidy, can I please pick this up?

**Comment by swissspidy** [comment]
@Sidsector9 we haven‘t yet decided how/if we want to support this; plus this will likely depend on #4608 to be merged first
