### ISSUE TITLE
Flipped elements on the dashboard reset the position when the user pass the mouse over the preview 

### ISSUE THREAD

**Issue by fellyph** [GoogleForCreators/web-stories-wp#4758]
## Bug Description

I've created some stories with some elements flipped horizontally on the first page, those elements are displaying on the dashboard preview. When I pass the mouse over the stories those flipped elements reset their rotation properties. 

## Expected Behaviour

When the user passes the mouse over those elements should keep their defined rotation.

## Steps to Reproduce

1 - Create more than one story
2 - Add shape or image on the first page click flip horizontally
3 - Save the story go back to the stories dashboard
4 - Pass the mouse over the stories to see the behaviour 

## Screenshots

![test web stories plugin (1)](https://user-images.githubusercontent.com/330792/94658209-6a187780-02fa-11eb-9f79-68c0ff348a2a.gif)

## Additional Context

- Plugin Version: 1.0
- Operating System: MacOS
- Browser: Chrome 85

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Thanks for your report!

I noticed the same the other day but thought it was just a glitch on my end. Good to know it's actually a bug!

**Comment by BrittanyIRL** [comment]
This appears to be fixed! @csossi do you mind verifying when you get a sec?

**Comment by fellyph** [comment]
Hi @BrittanyIRL 

The bug was fixed you can close it.

Thanks !

**Comment by csossi** [comment]
Verified in QA
