### ISSUE TITLE
Compact Interface

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#476]
## Feature Description

**[Design](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=2610%3A192)**

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
1. A compact element panel is part of the UI
2. Breaking points: ?

**Comment by jauyong** [comment]
@samitron7 to provide breakpoints. Are there multiple or just one?

**Comment by o-fernandez** [comment]
This has been discussed and addressed, we even reverted some of it. Closing the issue.
