### ISSUE TITLE
Text sets internationalization 

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#4767]
Consider internationalization of text sets into other languages. Need to think through many languages requirements to ensure the text sets would look and work well for the text density needed in various languages. 

@o-fernandez @barklund Has internationalization been considered for text sets? I suppose they should be translatable..?

_Originally posted by @swissspidy in https://github.com/google/web-stories-wp/issues/491#issuecomment-693656617_

**Comment by BrittanyIRL** [comment]
If we want to translate these, there's going to look a little weird because the whole point is that you're grabbing a set of styles based on the text. we'll def need some UX coordination.
