### ISSUE TITLE
Template asset sizes are very large

### ISSUE THREAD

**Issue by dreamofabear** [GoogleForCreators/web-stories-wp#4768]
## Bug Description

Assets in templates are very large -- some images are in the 2-4MB range.

Related: #4751

## Expected Behavior

Images/video in templates should be appropriately sized for mobile consumption on median devices and connections. Should also use standard APIs like `srcset`.

## Steps to Reproduce

N/A

## Screenshots

![image](https://user-images.githubusercontent.com/20525523/94713473-d4401500-0318-11eb-9a23-5ef54f5eab2b.png)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
@choumx is there anything else we'd want to do here? or should we close?
