### ISSUE TITLE
Import Text From a File

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#4771]
## Feature Description

As mentioned in the topic below, this is a feature request to have the ability to import text from Word files or rich text format.

## Additional Context

Related topic: [https://wordpress.org/support/topic/importing-text/](https://wordpress.org/support/topic/importing-text/)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Closing this old ticket as I believe copy & pasting text should suffice. No plans for having text file import.
