### ISSUE TITLE
Remove publisher-logo-src fallback to WordPress logo

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#4772]
## Bug Description

Currently, we fallback to using the generic WP logo if a user has not set a publisher logo. We should not do that moving forwrad.

## Expected Behaviour

If there's no publisher logo, keep empty, instead of using WP logo as fallback.  

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Duplicate of #4762
