### ISSUE TITLE
Expected behavior for page attachment link

### ISSUE THREAD

**Issue by robflaherty** [GoogleForCreators/web-stories-wp#4773]
The GIF demo in the [AMP docs](https://amp.dev/documentation/components/amp-story-page-attachment/) shows the page attachment sliding up in a drawer like we see on Instagram or Snapchat. But when I tap or swipe up on the Learn More page attachment link it navigates to a new page.

Is there a way to enable the sheet/drawer behavior so the user remains in the story context? Is it a limitation of linked content vs inline content?

**Comment by swissspidy** [comment]
Yes, we currently only support linked content for page attachments, not inline content. Only inline content is opened in a drawer.

**Comment by robflaherty** [comment]
Ah, got it. Thanks!
