### ISSUE TITLE
Pinch Scale & Rotate

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#478]
## Feature Description

In preparation for tablets

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
@miina Was this essentially fixed by #7569?

**Comment by miina** [comment]
@swissspidy Could it be that this issue is for elements generally since the epic is "Creator can Transform an Element"?

If it's for generally zooming then this issue can be closed and was fixed indeed. It was created quite a long time ago before the redesign so might be safe to close it.

**Comment by swissspidy** [comment]
Ah you're right. Especially the rotate would obviously only be element-specific, not for the whole canvas.
