### ISSUE TITLE
Check for required PHP extensions upon plugin initialization

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#4791]
## Feature Description

Our plugins requires on things like `libxml`, `DOMDocument`, etc. to be available. Let's add some checks for these required features upon plugin initialization so that users know immediately when their server is not compatible.

The AMP plugin does this like so:

https://github.com/ampproject/amp-wp/blob/5f42cde04d84046e106fa9784d4cf2e61f3ba204/amp.php#L22-L154

We can refactor `includes/namespace.php` to have similar checks.

* [ ] Evaluate currently needed extensions, classes, and functions (likely `libxml`, `DOMDocument`)
* [ ] Evaluate needed extensions once #4513 is merged

## Additional Context

There have been some user reports where `DOMDocument` was not available, or `libxml` was outdated. Hence the requirement for this.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
@spacedmonkey FYI. I think we discussed this at some point

**Comment by spacedmonkey** [comment]
We like the logic from the amp plugin. I think we should move the logic from amp plugin into the stories plugin. However, I think that the logic should be formatted in a class, called say `Compatibility`. It would take a `WP_Error` object as a dependancy and would have method that would add errors to this object. 

As an object, this makes the code really easily to reuse. 

Here is what I had in mind for implementations. ( dumby code ). 

```php
 * @return void
 */
function activate( $network_wide = false ) {
      $_error         = new \WP_Error();
      $compatibility  = new Compatibility( $_error );
      $compatibility->run_checks(); 
      $error          = $compatibility->get_error();
      if ( $error->errors ) {
             wp_die( $error );
     }

```

Similar logic can be reused like this. 
```php
 * @return void
 */
 function _print_admin_notice() {
      $_error         = new \WP_Error();
      $compatibility  = new Compatibility( $_error );
      $compatibility->run_checks(); 
      $error          = $compatibility->get_error();
      if ( ! $error->errors ) {
          return;
      }
		?>
	<div class="notice notice-error">
		<p>
			<strong><?php esc_html_e( 'Web stories plugin unable to initialize.', 'amp' ); ?></strong>
			<ul>
			<?php foreach ( array_keys( $error->errors ) as $error_code ) : ?>
				<?php foreach ( $error->get_error_messages( $error_code ) as $message ) : ?>
					<li>
						<?php echo wp_kses_post( $message ); ?>
					</li>
				<?php endforeach; ?>
			<?php endforeach; ?>
			</ul>
		</p>
	</div>
	<?php
}
```
or in CLI 
```php
if ( ( defined( 'WP_CLI' ) && WP_CLI ) || 'true' === getenv( 'CI' ) || 'cli' === PHP_SAPI ) {
      $_error         = new \WP_Error();
      $compatibility  = new Compatibility( $_error );
      $compatibility->run_checks(); 
      $error          = $compatibility->get_error();
      if ( ! $error->errors ) {
         $body = $error->get_error_message();
         if ( class_exists( '\WP_CLI' ) ) {
		\WP_CLI::warning( "$body" );
         } else {
	    echo "$body\n"; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
         }
      }
}
```

Each check could be a different method, 
- `missing_extensions_check`
- `missing_classes_check`
- `missing_functions_check`
- `php_version_check`
- `wp_version_check`
- `code_built_check`

With way you could bundle multiple checks together or just call what you need.

**Comment by swissspidy** [comment]
> `function activate( $network_wide = false ) { ... }`

I don't see why this check would need to run on site activation? 🤔 

> Similar logic can be reused like this.
> or in CLI

There's some repetition when doing `new Compatibility( $_error ) [...]` once for each context. Why not just do the checks once and print the results differently depending on the context?

> missing_extensions_check
> missing_classes_check
> missing_functions_check

If a class or a function is missing, it's because it's part of an extension that is missing/incomplete. So I'd just move this into one function that checks for the extension requirement.

> code_built_check

Just noting that, if the plugin hasn't been built yet, then there is no autoloader and the `Compatibility` class won't be available.

Also, today we only care about JS being built if not using WP-CLI. If using WP-CLI it doesn't matter whether the JS has been built or not. Need to preserve this.

----

/cc @westonruter - perhaps you could share some insights into how you came up with the current solution in the `amp.php` plugin file and if there is something we haven't considered?

Perhaps we could collaborate on this to create something both plugins could use?

**Comment by spacedmonkey** [comment]
> I don't see why this check would need to run on site activation? 🤔

I think these checks should also happen on activation. If you try and activate the plugin and there is a missing extension, this should show a `wp_die` message, the same as a wrong version of PHP or WordPress IMO. 

> There's some repetition when doing new Compatibility( $_error ) [...] once for each context. Why not just do the checks once and print the results differently depending on the context?

Sounds good. Again, this was dumby code, we can talk about this in implementation stage. 

> If a class or a function is missing, it's because it's part of an extension that is missing/incomplete. So I'd just move this into one function that checks for the extension requirement.

This was just copied from the AMP implementation, but this is good through when writing the code and something to note in CR.

> Just noting that, if the plugin hasn't been built yet, then there is no autoloader and the Compatibility class won't be available.

If the class doesn't exist, we can just load the file in manually, "the old fashioned way". 

I would love to find a way to share code between these two projects would be great. 

Keeping this as a class, that you can set class properties of functions, extenstions, class, min php and WP versions, that would keep it very generic and reusable for any WordPress plugin.

**Comment by westonruter** [comment]
> perhaps you could share some insights into how you came up with the current solution in the `amp.php` plugin file and if there is something we haven't considered?

Yes. The reason why all of the checks are inside of `amp.php` is primarily because of the PHP version. We do these checks _before_ and _without_ the autoloader because we want to make sure that all of the checks work in PHP 5.2. If we used the autoloader, then the `amp.php` to do this, then we'd not be able to use any PHP language features newer than 5.2. Only if all checks pass do we then proceed with loading the autoloader and bootstrapping the plugin. 

This is probably less important now that WordPress core has PHP version checks built-in, but that's the original reason for doing this.

**Comment by spacedmonkey** [comment]
We do not have to use namespacing or autoloading this `Compatibility` class to be a class. As said above, we can just load this class ( file ) in the old fashioned way and not namespace it.

**Comment by swissspidy** [comment]
Let's try this then 👍

**Comment by swissspidy** [comment]
Note that we now have a polyfill for mbstring (#4898), no need to check for that.
