### ISSUE TITLE
Optimize text strings for localization

### ISSUE THREAD

**Issue by Zodiac1978** [GoogleForCreators/web-stories-wp#4801]
## Feature Description

There are many string duplicates, like "Date Created" and "Date created" (just capitalization differs!), "Clear Input/input", "Close/close menu", "Close Preview/close preview", "Default/default", "Delete Page/page", "Draft/draft", "Duplicate Page/page", "Multiple/multiple", "No more/More Stories/stories", "No more templates"/"No more templates." (with and without trailing point), "Pre-Publish/Prepublish", "Select an Option/option", Size & position/Position", "Story published./Story published!" and so on ...

You should also avoid splitting up sentences like x: "Jump into the y" // y: "Editor"
https://translate.wordpress.org/projects/wp-plugins/web-stories/stable/de/default/?filters%5Boriginal_id%5D=10536312

## Additional Context

> Use entire sentences – in most languages word order is different than that in English.

Source: https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#best-practices-for-writing-strings

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Thanks for opening this Torsten!

I‘ll take a look at this soon.

The full-sentence-issue is unfortunately a known technical limitation that we still have to address: #1578
