### ISSUE TITLE
Local Environment: Outdated WP-CLI version

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#4802]
## Bug Description

When starting local dev environment I get the following error message. 

```
STATUS: Import default set of media assets...
Imported file '/var/www/html/wp-content/e2e-assets/example-1.jpg' as attachment ID 1965.
Success: Imported 1 of 1 items.
Imported file '/var/www/html/wp-content/e2e-assets/example-2.jpg' as attachment ID 1966.
Success: Imported 1 of 1 items.
Imported file '/var/www/html/wp-content/e2e-assets/example-3.png' as attachment ID 1967.
Success: Imported 1 of 1 items.
STATUS: Current WordPress version: 5.6-alpha-49085...
STATUS: Updating WordPress to the latest version...
[05-Oct-2020 11:25:06 UTC] PHP Warning:  Declaration of WP_CLI\Core\CoreUpgrader::download_package($package, $check_signatures = true) should be compatible with WP_Upgrader::download_package($package, $check_signatures = false, $hook_extra = Array) in phar:///usr/local/bin/wp/vendor/wp-cli/core-command/src/WP_CLI/Core/CoreUpgrader.php on line 30
Warning: Declaration of WP_CLI\Core\CoreUpgrader::download_package($package, $check_signatures = true) should be compatible with WP_Upgrader::download_package($package, $check_signatures = false, $hook_extra = Array) in phar:///usr/local/bin/wp/vendor/wp-cli/core-command/src/WP_CLI/Core/CoreUpgrader.php on line 30
```

## Expected Behaviour

It works. 

## Steps to Reproduce

Type `npm run env:start`

## Additional Context

- Plugin Version: 1-RC1-1.0.0
- Operating System: Mac OS 10.15.7

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
WP-CLI is not compatible yet with the changes in WordPress 5.5.

A new release of WP-CLI will be out soon though.

No change required on our side.

**Comment by swissspidy** [comment]
Closing as the new WP-CLI release should be out soon

**Comment by spacedmonkey** [comment]
Reopening, as I am still seeing this issue.

**Comment by spacedmonkey** [comment]
Found as part of #7269

**Comment by spacedmonkey** [comment]
@schlessera Can you provide any advice here?

**Comment by schlessera** [comment]
If you need an immediate solution here, you'll need to use an image that uses WP-CLI nightly instead of stable.

A new stable is in the works and we're finally working on the last blocker: https://github.com/WordPress/Requests/pull/471. As soon as that release of Requests is published, I'll prepare a WP-CLI v2.5.0 release as well.

**Comment by swissspidy** [comment]
Perhaps we can simply run `wp cli update --nightly` in our script. If not, I'm inclined to just close this issue (again) as this will be resolved with the upcoming release.

**Comment by schlessera** [comment]
Just as a heads-up, the Requests library has finally had its [v1.8.0 release](https://github.com/WordPress/Requests/releases/tag/v1.8.0), and I'm working on a release of WP-CLI now.

**Comment by spacedmonkey** [comment]
I tried using `wp cli update --nightly` but the container doesn't let me update. 

```
Error: /usr/local/bin/wp is not writable by current user.
```

I think might be best to wait until WP CLI 2.5.0 comes out. We can then set `WORDPRESS_CLI_VERSION` as a [env variable](https://github.com/docker-library/wordpress/blob/394c79eafd5b345514f87cec590577e641c030ef/cli/php8.0/alpine/Dockerfile#L77).

**Comment by swissspidy** [comment]
I don't think that's how `ENV` directives work in Dockerfiles. You can't just override them from the outside.

Let's wait for WP-CLI  2.5 to be released and the Docker images to be updated.

Don't want to spend any more time on this.
