### ISSUE TITLE
Rotation Snap & Stepping

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#481]
## Feature Description

it's impossible to rotate two elements to the same degree – stepping to specific degrees & snapping during the rotation itself 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. Author is able to rotate via stepping

Note: Stepping is hidden behind a keyboard shortcut

**Comment by jauyong** [comment]
@samitron7 to add stepping to rotation in designs.

**Comment by swissspidy** [comment]
Check out Moveable demo here at the top: https://daybrush.com/moveable/
Stepping is enabled by pressing <kbd>Shift</kbd> while rotating
