### ISSUE TITLE
When snapping elements, sometimes coordinates don't match

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#4813]
## Bug Description

When you drop an element to a snap target, sometimes (actually quite often) the coordinates don't actually match the expected target.

This is probably due to rounding errors.

## Expected Behaviour

When dropping an element using a snapping guideline (either to page or to an object), the coordinates of the elements should match (as well as possible - sometimes it's not possible for center snapping due to the requirement of whole pixels).

## Steps to Reproduce

1. Add two elements to a page
1. Move one element to x=100
1. Try to align the second element to have the same left edge as the first element
1. Notice that the x of the second element varies on subsequent drops, only occasionally matching the 100 of the first element

## Screenshots

![snap-rounding-off](https://user-images.githubusercontent.com/637548/95148010-59c82880-0750-11eb-83de-45f33387f1cf.gif)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

This should (probably) be fixed by remembering which (if any) snap targets an element is dropped near, and if so, use the coordinates of **that** target instead of the regular _original position + delta movement_  math currently used (as it suffers from rounding errors.

**Comment by bmattb** [comment]
@barklund / @carlos-kelly - can we get confirmation of which pod will be taking this on for 1.2 thankls

**Comment by miina** [comment]
Amy reported that this bug also makes it hard to snap elements to be exactly next to each other and has been reported by some users -- there's a 1px area between the two elements when trying to snap next to each other.
