### ISSUE TITLE
Settings: Optimize publisher logos image sizes

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#4816]
## Feature Description

On the editor settings screen we currently display the publisher logos in their full size, which can be quite large.

Some thoughts:

* We should use `srcset` here for optimization.  
  (`calculateSrcSet` util might serve as inspiration)
* The publisher logos are displayed in 100x100px (`Logo` component). The AMP format uses/recommends 96x96 - let's also use that size? Otherwise a 96x96 image will get resized a bit.
* Let's set explicit `width` and `height` attributes on the `img`
* Pick reasonable sizes limit so we don't unnecessarily load large images.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by maxyinger** [comment]
@swissspidy I'm not seeing any sizes on the logo image media. Are there smaller images generated from uploads somewhere? or a way to request smaller image sizes from WP through some url params or something?

**Comment by swissspidy** [comment]
If there are no sizes it means there are no smaller ones. Just using 96x96px consistently should be good enough.

**Comment by BrittanyIRL** [comment]
@csossi  - all this ended up being for right now is updating the size of the publisher logos on the dashboard settings to 96x96px

**Comment by csossi** [comment]
Looks like it's slightly larger
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/cd947d70-c8f4-44e5-b197-cff9af2d79d1)

**Comment by swissspidy** [comment]
@csossi That is OK, as you are just inspecting the `div`, not the actual `img` element inside it. The `img` is a bit smaller. I just verified that it's 96x96 so I'll merge this.
