### ISSUE TITLE
Directly use phpstan-wordpress extension

### ISSUE THREAD

**Issue by szepeviktor** [GoogleForCreators/web-stories-wp#4817]
I've contributed static analysis to project when the WordPress extension was not published.
Now it is. And more advanced then ever.

Please consider using it.
https://packagist.org/packages/szepeviktor/phpstan-wordpress

Plus one: depends on php-stubs/wordpress-stubs so you don't have to depend on it

----

## Acceptance Criteria

Ping szepeviktor on the final PR for this

**Comment by swissspidy** [comment]
Pretty sure it was already published back then. We‘ved used the extension in the past on CI. But that was on CI only, with ignoring platform reqs option.

Due to different PHP version requirements we‘re using phpstan via phar only, which I don‘t think is possible with the extension.

Hence the current approach with copying some of the files, as inspired by the amp-wp repo.

**Comment by szepeviktor** [comment]
Would you accept a PR that installs these tools in CI?
As that job of the CI run on PHP 7.4.

**Comment by swissspidy** [comment]
That's what we had before, see #4540.

It basically did `composer require --no-interaction --dev szepeviktor/phpstan-wordpress --ignore-platform-reqs`

Ideally we he have a setup that works identically both locally and on CI.

**Comment by szepeviktor** [comment]
I see!

How do you mean "both locally and on CI"? PHPStan does not start on PHP < 7.2

**Comment by szepeviktor** [comment]
Ah! You mean locally with adequate version of PHP.

**Comment by szepeviktor** [comment]
These conditions are very tough!
I come back with a solution...

**Comment by swissspidy** [comment]
Correct :) That's why we have the current solution, and I think it works fine at the moment.

Once we bump the PHP requirement we can easily remove this workaround.

**Comment by szepeviktor** [comment]
I am thinking about a Composer script - where all commands should live.

```json
"script: {
  "analyze": [
    "composer info --path szepeviktor/phpstan-wordpress || composer require --dev szepeviktor/phpstan-wordpress",
    "vendor/bin/phpstan analyze"
  ]
}
```
