### ISSUE TITLE
Overlay/Scrim

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#482]
## Feature Description

**[Design](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=2671%3A55920)** - See overlay section in design panel

**[Feature Brief - Product spec: Design Panel](https://docs.google.com/document/d/1EQ12sD4a1plmMeBu7YMWOdUSg0FeegB9qi2_OlV3Tp0/edit#heading=h.8gx268u5ireb)**

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
See design link for details
1. Author can choose overlay option: None
2. Author can choose overlay option: Solid
3. Author can choose overlay option: Linear
4. Author can choose overlay option: Radial

**Comment by bmattb** [comment]
as per Paul this is clearly outlined in Figma. If you click the bg there is a new subpanel called overlay w/ 4-5 options. Background gradient etc.

**Comment by obetomuniz** [comment]
What happens when the Author chooses an overlay option in the canvas? I can't see the expected result on the designs. cc @jauyong @pbakaus

**Comment by obetomuniz** [comment]
Hey @wassgha do you know where I found the overlay result in the designs when the Author chooses an overlay option in the panel?

**Comment by jauyong** [comment]
@samitron7 @obetomuniz @pbakaus I also only see the layout of overlay in the Design Panel section. I don't see details about the behaviour.

Also just pointing out that this is still [TBD in the brief. ](https://docs.google.com/document/d/1_3-_v4zH6bW9hOplOO8wYxj8l4C0soMgEbD7XLiXrrg/edit#heading=h.l439jlo9cx52)

**Comment by pbakaus** [comment]
This is now in the [product spec](https://docs.google.com/document/d/1EQ12sD4a1plmMeBu7YMWOdUSg0FeegB9qi2_OlV3Tp0/edit#heading=h.8gx268u5ireb).
