### ISSUE TITLE
Repository size is too large

### ISSUE THREAD

**Issue by szepeviktor** [GoogleForCreators/web-stories-wp#4821]
> Receiving objects: 100% (88892/88892), 1.12 GiB | 11.26 MiB/s, done.

# 1.12 GiB

Do we keep old Britney Spears videos? Or what?

**Comment by szepeviktor** [comment]
_Baby One More Time_ is available on [YouTube](https://www.youtube.com/watch?v=C-u5WLJ9Yk4&t=15) for free :)

I feel like `git clone`-ing something unnecessary...

**Comment by swissspidy** [comment]
🙂 

The repo is indeed quite large at the moment. We ended up adding lots of assets for story templates, and eventually moved them all to the `static-site` branch. We'll likely move most/all of them to Firebase though. See #4751 #4752

**Comment by szepeviktor** [comment]
A repository restart is a brave thing!

We only have a handful of PR-s...

**Comment by szepeviktor** [comment]
FYI Current contents weights 26 MB.
Which makes content:repo ratio 1:46!

**Comment by swissspidy** [comment]
Closing in favor of #5961

**Comment by szepeviktor** [comment]
This is a work-around: `git clone --depth=1 https://github.com/google/web-stories-wp.git`
Finishes in 4 seconds.
