### ISSUE TITLE
Build and adopt new visual redesign components in the Dashboard

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#4829]
Epic to capture the work needed to build and use the new components per the latest WP visual design. 

**[Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Stable-Release?node-id=1%3A44325)**

Related Epic for Workspace efforts: #4830 

---

TL;DR on the flow for this update since it has been going on in the background for a while (updated Jan 11, 2021) 

**Dashboard Redesign General Order and Prioritization** 

- Finish adding basic components to design system that we know are getting used in the dashboard. Adding components just into storybook.   Should be wrapping this initial phase up this week or next depending on page layouts. The last things I want to get done for this initial group are form components we'll use in settings - basic input, radio, checkbox, toggle as well as wrapping up our search component. 
- Start tackling Dashboard iteratively (general order) 
    1. Anything that only appears when interacted with - dialogs, snack bars, popover menus, scroll to top buttons
    2. Left Nav 
    3. Page headers 
    4. Settings view
    5. Grid elements 
    6. Table elements 
    7. Single template view
    
While tackling this list, anything that comes up that isn't in the design system yet that should be will be added as part of acceptance.

**Comment by o-fernandez** [comment]
@carlos-kelly @BrittanyIRL can we make sure we have tickets for this work? (Adopting the new visual design components in the Dashboard)

**Comment by BrittanyIRL** [comment]
@o-fernandez I created tickets for each section of the design system foundation and light mode components as well as the sections of the dashboard at a high level that will be updated based on these foundational elements. We won't need to create _all_ of these (like the panels for instance have no place in the dashboard) but I wanted to create tickets to track progress of where we're at with the whole design system getting implemented as a whole.

**Comment by o-fernandez** [comment]
Awesome, there's also an epic for the Workspace, which we can move things to if we decide not to build as part of this effort. We can always double-tag to both epics and see where it gets picked up. :) 

#4830

**Comment by BrittanyIRL** [comment]
@o-fernandez @bmattb I updated the description of this story to include a brief review of the order I'm tackling things in. Talked it over a bit with Sam and this is what she was after. cluing you in too. Let me know if you need more info.

**Comment by o-fernandez** [comment]
> @o-fernandez @bmattb I updated the description of this story to include a brief review of the order I'm tackling things in. Talked it over a bit with Sam and this is what she was after. cluing you in too. Let me know if you need more info.

This is great - thanks @BrittanyIRL !

**Comment by BrittanyIRL** [comment]
Closing this epic! Dashboard has been redesigned. Further work will have a separate epic as needed.
