### ISSUE TITLE
Font size / Preview  

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#483]
## Bug Description

In editor preview of font

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by wassgha** [comment]
@pbakaus I believe the UX is locked on this, right? Can we proceed with it?

**Comment by pbakaus** [comment]
yes!

**Comment by wassgha** [comment]
Sounds good then, I'll take it on the next sprint

**Comment by dvoytenko** [comment]
Is this the same as  https://github.com/google/web-stories-wp/issues/309 ?

**Comment by ndev1991** [comment]
@pbakaus @jauyong what is the details of this issue? Is this same with #309 ?

**Comment by jauyong** [comment]
Closing this as duplicate of #309
