### ISSUE TITLE
Selecting multiple elements with Text Color as "Multiple" can cause Design panel to crash

### ISSUE THREAD

**Issue by mariano-formidable** [GoogleForCreators/web-stories-wp#4832]
**Steps to Repro:**
1.) Open up a new story in the Editor.
2.) Click on "T" to open the text panel in the library.
3.) Click on "Heading 1" to add text to editor.
4.) Click on "Paragraph" to add text to editor.
5.) Double click on "dolor" in the paragraph text element.
6.) Change the color of "dolor" to any non-black color (i.e. #FF6600)

Your setup should look something like this:
<img src="https://images.zenhubusercontent.com/5b35729a5b51b10bd4dd5fd1/d911e696-42db-495f-8a01-0851e83cdaac" height="200">

Your layer panel should look like this (paragraph text should be above header text):
<img src="https://images.zenhubusercontent.com/5b35729a5b51b10bd4dd5fd1/d71f963e-25c2-4ca7-b4b4-7a5967f4ed21" height="200">

7.) Drag and select both text elements.

**Expected**
- Both items are selected.  Design panel works as expected.

**Actual**
- Both Items are selected.  Design panel crashes.
<img src="https://images.zenhubusercontent.com/5b35729a5b51b10bd4dd5fd1/9cf29811-b00a-46fb-a077-12e378b0d024" height="200">

**Console Error Message**
![image](https://user-images.githubusercontent.com/40646372/95353685-6778cd80-0878-11eb-9752-7af16859563f.png)

**Something more**

8.) Save and refresh the page to the design panel back with both elements on the page.
9.) In the `Layers` panel, drag "Heading 1" to above the paragraph element.  It should look like this:
<img src="https://images.zenhubusercontent.com/5b35729a5b51b10bd4dd5fd1/3f447b10-b42b-47fa-8c4b-b061306f3af7" height="200">
10.) Now, drag and select both elements again and watch as the design panel does _not_ crash:
<img src="https://images.zenhubusercontent.com/5b35729a5b51b10bd4dd5fd1/67b8e723-3439-4466-a089-417590586362" height="200">

**Comment by mariano-formidable** [comment]
@o-fernandez Can you take a look at this bug and rank it's priority?  It's an odd use case but it does force a refresh of the screen.

**Comment by o-fernandez** [comment]
This is really weird, but anything that makes the editor crash should really be looked into. I'll mark this as P1 so someone looks at it soon, we can deprioritize if we feel it's too edge-case of a scenario and the root cause seems isolated. cc: @choumx

**Comment by swissspidy** [comment]
@mariano-formidable What's the actual error message for the crash?

**Comment by mariano-formidable** [comment]
@swissspidy The error message is "Uncaught TypeError: Cannot read property 'r' of undefined" in `generatePatternStyles.js`.  I updated the description with a full screenshot of the error.

**Comment by swissspidy** [comment]
Thank you!

This sounds like the reports we got in #3544 and #4354, so it's definitely something users ran into in the past. Your report seems to give us an easier way to reproduce this reliably 🚀 

Let's consolidate the issues :-)

**Comment by csossi** [comment]
Verified in QA
