### ISSUE TITLE
Use shortcode when classic editor plugin is active 

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#4833]
## Feature Description

If a user has the classic-editor plugin active, the embed story block does not preview and seems broken. Instead of using the embed when classic-editor / TinyMCE is active, using the shortcode. See #3135 

## Additional Context
Video to show the user experience. 
https://www.youtube.com/watch?v=Id4Cr_HJoCA

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Good catch!

We should be able to use `use_block_editor_for_post()` in `Admin.php` or similar for this one.

Maybe worth adding the Classic Editor plugin in our Docker environment and use it for a small E2E test for this scenario in `publishingFlow.js`.

**Comment by spacedmonkey** [comment]
I went to look out an IB for this and completed it in 15 minutes. So submitted a PR at #4849

**Comment by swissspidy** [comment]
@spacedmonkey Awesome! WDYT about an E2E test as mentioned above; worth adding? Or at least adding the plugin for testing.

**Comment by spacedmonkey** [comment]
@swissspidy I added a unit test, but if you want an e2e test, I will add one now.

**Comment by 4jassikingg** [comment]
I am sorry as I was looking for a solution to this problem. I am not able to embed web stories in my post with classic editor plugin active. When I disabled that then I was able to embed it. 

Can you please help me if the solution will be released soon..

**Comment by swissspidy** [comment]
@4jassikingg This enhancement will be included in our next release, which is due at the end of this month.

**Comment by 4jassikingg** [comment]
Many thanks for the update.
