### ISSUE TITLE
Snapping to Common Distances

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#484]
## Feature Description

As and author I want to snap to common distances based on other elements on the page for a consistent look

Please see this[ video on slack](https://xwp.slack.com/files/UNKJGEE2W/FUWQB0HHP/snap2closestdistance.mov). .mov is not allowed in Github.

![image](https://user-images.githubusercontent.com/5874851/76865306-e48b1980-6838-11ea-8580-59ec1008d6f4.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
1. Snapping to Common Distances
Note: multi-selection is treated as a single element.

## QA Instructions

1. You need 3 equal size elements
2. Position 2 next to each other
3. Take the third and try to position it with teh same distance between the first 2 elements.

**Comment by jauyong** [comment]
Closing this. See PR #488 and #285

**Comment by jauyong** [comment]
@samitron7 to add screenshots

**Comment by jauyong** [comment]
@samitron7 I know this ticket is closed but you mentioned you added a screencast link here but I don't see it.

**Comment by jauyong** [comment]
I have linked the slack message containing the .mov and added the screenshot to the issue.

**Comment by wassgha** [comment]
Tracking https://github.com/daybrush/moveable/issues/200
