### ISSUE TITLE
Discovery: HTML entities shown for story title in bookend

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#4841]
## Bug Description

The story title used for the `headLine` in the schema data (as printed by the `Discovery` class) is used for the automated story bookend. Currently, that title is being displayed with HTML entities.

## Expected Behaviour

No HTML entities should be displayed

## Steps to Reproduce

1. Create a new story
1. Use “これはサンプルです。” as title
1. Publish story
1. View story on smartphone / in smartphone emulation

## Screenshots

![2020-10-07_21h47_52](https://user-images.githubusercontent.com/841956/95347172-e55ec800-08bc-11eb-9d9a-a9f67ffb1439.jpg)

## Additional Context

Originally reported at https://wordpress.org/support/topic/the-title-in-japanese-is-an-entity/
Additional report: https://wordpress.org/support/topic/bugged-when-in-hebrew-letters-and-url/
- Plugin Version: 1.0.0
- Operating System: macOS
- Browser: chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
Looking at this [example](https://monoxa.net/web-stories/sample-dog/) you can see the html entries are in the markup. 
```
<meta property="og:title" content="&#12371;&#12428;&#12399;&#12469;&#12531;&#12503;&#12523;&#12391;&#12377;&#12290;">
```

```
<title>&#12371;&#12428;&#12399;&#12469;&#12531;&#12503;&#12523;&#12391;&#12377;&#12290; &ndash; &#12514;&#12494;&#12464;&#12469;&#12395;&#12362;&#28792;</title>
```

```
<amp-story standalone="" publisher="&#12514;&#12494;&#12464;&#12469;&#12395;&#12362;&#28792;"
```

For some reason all the text has been converted to html entries. In my testing, I was unable to replicate with current version of main on three different VM ( local env, WordPress develop local env and VVV ). I was able to see the editor in 1.0.0 version, just once and I saved it again and the error went away. 

I believe the issue has something to do with html entries being saved in the database and them not being displayed correctly on render. But it is pretty hard to debug something that you can't replicate. As it is hard to replicate, I think we should wait until after 1.1 and see if this fixes the issue. 

Thoughts?

**Comment by o-fernandez** [comment]
@spacedmonkey @swissspidy if the hypotheses is that this has been fixed in the latest version, we should ensure we follow-up with the user after the 1.1 release and ask them to upgrade and try again. Is that your proposal? 

@LuckynaSan FYI

**Comment by swissspidy** [comment]
Indeed looks like the recent AMP sanitization & encoding improvements fixed this. So yeah, they should retry with 1.1.
