### ISSUE TITLE
Workspace: Design Updates to Text Panel

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#4851]
## Feature Description

In the screenshot, design mock on the left and what's currently in the editor on the right. Can we make these 2 adjustments:
Decrease the left and right gutter padding is 16px for all the element panel. I'm not sure how this will impact the scrollbar (ie if scrollbar is additional px space?).
The space between the text set boxes are 12px.

Additionally drop the "Add New Text" blue link

![Group 5588.png](https://images.zenhubusercontent.com/5ea09bca6a44046f869bafe0/edf03146-b73d-433c-a018-0932036a32f4)

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

The text panel should match the mocks on the left.

**Comment by csossi** [comment]
Verified in QA
