### ISSUE TITLE
Clicking an element selects it but doesn't show frame around it

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#4857]
## Bug Description
Sometimes, when clicking on an element, the frame around it doesn't show up even though the element is actually selected.

## Expected Behaviour
When an element gets selected, it should always display a selection frame around it.

## Steps to Reproduce
1. Add a story with a text element (or some)
2. Unselect the text (e.g. click on the page to select the page instead)
3. Now click once on the Text element
4. Repeat steps 2. and 3. until eventually you'll see the issue -- the element gets selected but frame won't show.
5. Additionally, sometimes it seems that a new history entry is created as well (See [Pascal's comment](https://github.com/google/web-stories-wp/issues/4857#issuecomment-706130418) below to reproduce this consistently.)

## Screenshots
![lag](https://user-images.githubusercontent.com/3294597/95576150-393dee00-0a30-11eb-8daa-18c5a2bb786f.gif)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
> Click on the page to select the page.

That step was not needed in my testing.

> Additionally, sometimes it seems that a new history entry is created as well

This happened when I clicked on the element again (to enter edit mode) and then clicked outside the canvas to leave edit mode. Creates a history entry every time.

**Comment by miina** [comment]
> That step was not needed in my testing.

True, that was just necessary for unselecting the added text element, will update the wording.

**Comment by miina** [comment]
Note: Looks like the history issue is a completely unrelated thing, will create a separate issue for it: https://github.com/google/web-stories-wp/issues/4876

**Comment by csossi** [comment]
Verified in QA
