### ISSUE TITLE
Workspace: Page hash causes issues with browser history

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#4858]
## Bug Description

This is a follow-up to #4605.

Due to the page ID being persisted in the address bar, I cannot reliably use the back button in my browser anymore.

Not sure if this can be easily resolved.

Storing the current page as a hash like this was originally suggested in #825. But maybe we should just use localStorage?

## Expected Behaviour

1. Click on "Add New" in the admin menu.
1. Click on "Back" button in browser.
1. Get back to previous page.

## Steps to Reproduce

1. Click on "Add New" in the admin menu.
1. Notice the URL in the address bar looks like `wp-admin/post-new.php?post_type=web-story#page=%2522a69b45a9-8cd9-46c2-b6a0-81f76005ba26%2522`
1. Click on "Back" button in browser.
1. Notice that nothing happens, except for the URL changing to `wp-admin/post-new.php?post_type=web-story#page=null`
1. Click on "Back" button in browser.
1. Notice that nothing happens, except for the URL changing to `wp-admin/post-new.php?post_type=web-story`
1. Click on "Back" button in browser.
1. **Finally** you are back on your previous page.

## Additional Context

- Plugin Version: 1.1.0-alpha
- Operating System: macOS
- Browser: Chrome 85

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
FYI @carlos-kelly @o-fernandez I created this follow-up ticket to #4605. Basically did UAT on it by accident and thought that this is quite annoying.

**Comment by csossi** [comment]
Verified in QA

**Comment by samitron7** [comment]
Verified in UAT
