### ISSUE TITLE
Allow customization of archives page

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#4862]
## Feature Description

Right now we simply use the built-in WordPress archives for the `/web-stories/` site. Depending on the theme, this archive page can look very bleak as they don't usually accommodate for a visual format like stories. But because it's a built-in feature that's steered by the theme, the user has no control over its appearance.

To fix this, we could do it [like WooCommerce](https://docs.woocommerce.com/document/woocommerce-pages/) and give the user an option to define a custom archive page.

<img width="692" alt="woocommerce-page-setup" src="https://user-images.githubusercontent.com/841956/95609932-ce0c1000-0a5f-11eb-866c-1f3512968061.png">

If set, we disable the built-in archive and instead refer to that page as the archive.

They can then edit this custom archive page using Gutenberg and insert whatever content they'd like. For example a Latest Stories block.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
In #4863 the rtCamp adds a [theme supports](https://github.com/rtCamp/web-stories-wp/blob/c852f9892a4d45b708ffaa3f632c265afc6733ba/includes/Traits/ThemeSupport.php#L41). 

Maybe we have some conditional logic, that allows developers to support improved archives, otherwise, fallback to the default   behavior we have now. Sadly this would make this feature opt-in but may fix some issues around styling etc.

**Comment by swissspidy** [comment]
Yeah this might be something to look into, but that's another topic I think.

We'd still want to give the user full power for customizing the archive page to their liking.

Imagine editing the archive page in Gutenberg, adding some paragraph blocks and a "Latest Stories" block below.

So the user could basically choose between two options

```
Web Stories Archive Page:

[ ] Use default page generated by theme / WordPress / us

[ ] Use custom page
```

Aside: If theme developers want to have improved archives, it's probably easiest to just create a `archive-web-story.php` template file and improve the layout using the blocks provided by us.

**Comment by spacedmonkey** [comment]
WordPress core also as a method of marking pages as special pages. The example is the privacy policy page. 

<img width="333" alt="Screenshot 2021-01-26 at 13 17 48" src="https://user-images.githubusercontent.com/237508/105850094-2ea46600-5fd9-11eb-9add-9e44cb546e1f.png">

There is also precedent for post type / taxonomy features relaying on theme supports. Take post format for [example](https://github.com/WordPress/WordPress/blob/5c663524c28fccb8853fe1f6f6e6086507d3d652/wp-includes/taxonomy.php#L172).

So we could so something like this 
``` 
	register_post_type(
	   self::POST_TYPE_SLUG,
           ...
          'has_archive' => current_theme_supports( 'web-stories', 'archives' ), 
```

It would then be up to theme developers to add this support. We could even shim in support in core themes, similar to jetpack.

**Comment by swissspidy** [comment]
> So we could so something like this [...]

interesting idea, but at this point this would be quite the breaking change for users, resulting in tons of 404s.

**Comment by rajpalsaurabh** [comment]
A big +1 to the need for this. It's been an ongoing ask from a lot of people we've been working with. Apart from allowing the customisations, which'd be ideal to have more managed O&O experiences, an additional ask has been to somehow disable this archive page by default, giving an option to the website owner for enabling it when desired (and customise it eventually, if that's possible sometime later).

**Comment by swissspidy** [comment]
@spacedmonkey Here's what I had in mind:

Add a new section to the settings page with a dropdown offering these three options:

1. Default
2. Disable
3. Custom

Here are some mocks:

**Default**

![Screenshot 2021-08-12 at 15 39 31](https://user-images.githubusercontent.com/841956/129209665-04647846-1b44-41fa-ab1c-86ffa3291407.png)

For convenience, a link to the current archive page can be displayed.

**Note:** We might offer an option to customize the `/web-stories/` slug in the future

**Disable**

![Screenshot 2021-08-12 at 15 56 08](https://user-images.githubusercontent.com/841956/129209617-2e39410d-c053-4fb3-b945-164944c74b72.png)

**Custom**

![Screenshot 2021-08-12 at 15 43 36](https://user-images.githubusercontent.com/841956/129209582-24260583-fcc9-4446-9498-62f746e3b2f9.png)

For convenience, a link to the current archive page can be displayed.

There's an autocomplete dropdown to select the page.

The custom page can be annotated as such in the posts list table:

![Screenshot 2021-08-12 at 15 40 06](https://user-images.githubusercontent.com/841956/129210024-ce68c9ce-eb45-4ff1-a2d8-9b229b3c5dbc.png)

**Note:** The "Custom" feature can be done in a separate ticket. Just referencing here for completeness.

---

**Also:** In places like the Web Stories block, the TinyMCE button and the customizer, we should hide the UI option for displaying an archive link if there is no archive link.

![Screenshot 2021-08-12 at 15 57 19](https://user-images.githubusercontent.com/841956/129210559-b10b3793-98cf-45ee-89d9-5e6403bab7e6.png)

----

**Note:** we can put this behind a feature flag and then refine UX afterwards.

----

Curious to hear your thoughts.

**Comment by spacedmonkey** [comment]
What does having a custom page here give us? Will this custom page be populated with new custom blocks that allow you edit the page to changing styling. Just trying to understand what the page gives us. Apart from maybe being able to change the title of the page or some content before the list of stories. I feel like their are other ways of doing this. 

I personally believe, we should hold off doing anything to customize there pages, as I feel like full site editing with solve a lot of these problems. We should put effect into custom blocks for that and making that experience work amazing. If we do this page work, then we have two ways of customizing this page...

**Comment by swissspidy** [comment]
> What does having a custom page here give us? Will this custom page be populated with new custom blocks that allow you edit the page to changing styling.

That, yes.

> I personally believe, we should hold off doing anything to customize there pages, as I feel like full site editing with solve a lot of these problems. We should put effect into custom blocks for that and making that experience work amazing. If we do this page work, then we have two ways of customizing this page...

It's a long time before FSE becomes the norm and we still support WP 5.5+ which does not yet have any FSE capabilities. Support requests indicate that this is desired already _today_.

Also, just reiterating here that the "Custom" feature can be done in a separate ticket. The first step is to allow _disabling_ the archives page.

What's your thought on that part?

**Comment by Gaurav-Patil-G** [comment]
Hi there, can anybody tell me the solutions for this?

**Comment by swissspidy** [comment]
@Gaurav-Patil-G We are still working on this, no solution as of yet.

**Comment by swissspidy** [comment]
> > I personally believe, we should hold off doing anything to customize there pages, as I feel like full site editing with solve a lot of these problems. We should put effect into custom blocks for that and making that experience work amazing. If we do this page work, then we have two ways of customizing this page...
> 
> It's a long time before FSE becomes the norm and we still support WP 5.5+ which does not yet have any FSE capabilities. Support requests indicate that this is desired already _today_.

In last week's meeting we agreed that FSE is too far away. We just synched on the general idea that "Custom" would mean selecting a custom page for the archives and that users would simply edit that page in the block editor, using the Web Stories block if they want to. But with no pagination or anything.
