### ISSUE TITLE
Story Editor stuck on "Please Wait..."

### ISSUE THREAD

**Issue by SilvioDiaz** [GoogleForCreators/web-stories-wp#4864]
Bug Description:

Story Editor stuck on "Please Wait" 

![image](https://user-images.githubusercontent.com/57494579/95626144-191e2700-0a50-11eb-8a50-b88a161b42f3.png)

Console Image: 

![image](https://user-images.githubusercontent.com/57494579/95626189-34893200-0a50-11eb-8a09-23adacef287a.png)
![image](https://user-images.githubusercontent.com/57494579/95626224-48cd2f00-0a50-11eb-9c8c-953f0b45c2d7.png)

**Comment by swissspidy** [comment]
Hi there,

What‘s your browser version? Does this still happen in incognito mode with all plugins disabled?

**Comment by SilvioDiaz** [comment]
> Hi there,
> 
> What‘s your browser version? Does this still happen in incognito mode with all plugins disabled?

Chrome 86.0.4240.75 (Official Version) 64 bits and yeas, still happening in incognito or with all plugins disabled. I try on Opera and don't work either. 

OBS: Work well this morning.

**Comment by swissspidy** [comment]
And which version of the plugin are you using?

For testing, could you try updating to our current development version to see if the issue persists?  Download: https://github.com/google/web-stories-wp/suites/1317276935/artifacts/20896282

If the issue still happens with that version, you can then download this one here to get better understandable error messages: https://github.com/google/web-stories-wp/suites/1317276935/artifacts/20896284

**Comment by SilvioDiaz** [comment]
> And which version of the plugin are you using?
> 
> For testing, could you try updating to our current development version to see if the issue persists? Download: https://github.com/google/web-stories-wp/suites/1317276935/artifacts/20896282
> 
> If the issue still happens with that version, you can then download this one here to get better understandable error messages: https://github.com/google/web-stories-wp/suites/1317276935/artifacts/20896284

I'm using 1.0, the Web Stories from the first link, work. Why?

**Comment by swissspidy** [comment]
Good to know! And I don‘t know why exactly it works, but it contains a few bug fixes and improvements. These will be part of our upcoming release, so stay tuned for that update later this month :-)

**Comment by ghost** [comment]
same error 
![Ekran görüntüsü 2020-10-12 080653](https://user-images.githubusercontent.com/12281163/95707332-e8add700-0c61-11eb-9092-21ba519a97f9.jpg)

**Comment by SilvioDiaz** [comment]
We have the problem again, look's like, change one version to another solve the problem just for some time.

**Comment by swissspidy** [comment]
In that case please install https://github.com/google/web-stories-wp/suites/1317276935/artifacts/20896284 and share the error message in the console.

**Comment by SilvioDiaz** [comment]
> In that case please install https://github.com/google/web-stories-wp/suites/1317276935/artifacts/20896284 and share the error message in the console.


[stories editor stuck.log](https://github.com/google/web-stories-wp/files/5363097/stories.editor.stuck.log)

**Comment by SilvioDiaz** [comment]
[stories editor stuck new storie.log](https://github.com/google/web-stories-wp/files/5363107/stories.editor.stuck.new.storie.log)


> In that case please install https://github.com/google/web-stories-wp/suites/1317276935/artifacts/20896284 and share the error message in the console.

New storie: 

[stories editor stuck new storie.log](https://github.com/google/web-stories-wp/files/5363108/stories.editor.stuck.new.storie.log)

**Comment by swissspidy** [comment]
That looks alright. And it‘s still stuck?

**Comment by SilvioDiaz** [comment]
> That looks alright. And it‘s still stuck?

With the dev version it work, very slow, but work. Now with 1.0 and 1.10 alpha, the editor stuck on "please wait"

**Comment by spacedmonkey** [comment]
Related: #1369

**Comment by swissspidy** [comment]
@ajanskartal Please open a new issue in the [WordPress.org support forums](https://wordpress.org/support/plugin/web-stories/) and include as much information as possible, including browser version and your Site Health information. Thanks!

@SilvioDiaz Since you previously mentioned it worked only for some time, let us know if it happens again with this one. Also, was there a specific action you took that caused this error to appear again? Does it happen when creating a new story, or editing an existing one?

It's important for us to have as much information as possible, so if you could provide your Site Health information as well that would be great.

**Comment by ghost** [comment]
> @ajanskartal Please open a new issue in the [WordPress.org support forums](https://wordpress.org/support/plugin/web-stories/) and include as much information as possible, including browser version and your Site Health information. Thanks!

Hi,
I found the error. it is not related with the plugin. it is about my server settings.

**Comment by SilvioDiaz** [comment]
> > @ajanskartal Please open a new issue in the [WordPress.org support forums](https://wordpress.org/support/plugin/web-stories/) and include as much information as possible, including browser version and your Site Health information. Thanks!
> 
> Hi,
> I found the error. it is not related with the plugin. it is about my server settings.

Hey, can you share the error and how you solve?

**Comment by SilvioDiaz** [comment]
> @ajanskartal Please open a new issue in the [WordPress.org support forums](https://wordpress.org/support/plugin/web-stories/) and include as much information as possible, including browser version and your Site Health information. Thanks!
> 
> @SilvioDiaz Since you previously mentioned it worked only for some time, let us know if it happens again with this one. Also, was there a specific action you took that caused this error to appear again? Does it happen when creating a new story, or editing an existing one?
> 
> It's important for us to have as much information as possible, so if you could provide your Site Health information as well that would be great.

It's Happens randomly on story editor, both in a new and already created.

**Comment by ghost** [comment]
I was blocking the following keywords in urls:
wp-json and wp-plugin
For this reason, the page has not load...

**Comment by LuckynaSan** [comment]
@SilvioDiaz Hi there! Could you confirm if this issue still occurs with the latest Web Stories version 1.1.0? We've moved support to the [WordPress.org forums](https://wordpress.org/support/plugin/web-stories/) and this issue will be closed here. Please open a [new support topic](https://wordpress.org/support/plugin/web-stories/#new-post) with related information and we'll happily continue troubleshooting with you there.

**Comment by SilvioDiaz** [comment]
if i stop using the web-stories for dev the problem comeback. Someone know why?

**Comment by swissspidy** [comment]
@SilvioDiaz Are there any console errors? Are there any failed requests in the dev tools Network tab?

**Comment by SilvioDiaz** [comment]
> @SilvioDiaz Are there any console errors? Are there any failed requests in the dev tools Network tab?

![Screenshot_3](https://user-images.githubusercontent.com/57494579/109424821-469a4b80-79c4-11eb-9345-4ee1a341771f.png)
@swissspidy

**Comment by swissspidy** [comment]
Hey @SilvioDiaz, does this still happen with the latest version of the plugin?

What's your hosting provider?

**Comment by SilvioDiaz** [comment]
@swissspidy  Hostgator and yes, i took the print from webstories 1.4.0

**Comment by swissspidy** [comment]
> @swissspidy Hostgator and yes, i took the print from webstories 1.4.0

Thanks for the info! We're aware of some HostGator related issues that cause this exact issue, see #6173. It is caused by HostGator's SiteLock security feature that breaks probably a whole bunch of other plugins too.

Please follow #6173 for any updates on this matter.

Of course it can't hurt if you also reach out to HostGator directly yourself and tell them that something on their side is breaking this plugin

**Comment by SilvioDiaz** [comment]
I spoke with Hostgator and it doesn't have much to do. in 1.4 the problem takes longer to happen, at least that
