### ISSUE TITLE
Entering Text element edit mode and leaving creates a history entry

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#4876]
## Bug Description
Original issue: #4857 

## Expected Behaviour
Entering and leaving text edit mode without changes should behave as if no changes were added and not create a History entry.

## Steps to Reproduce
1. Add a Text.
2. Save. 
3. Enter edit mode.
4. Leave edit mode
5. See that the "Save draft" is active and the "Undo" icon is active, too.

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Since the edit mode was initially always updating the element, even if nothing changed, I assumed that was the issue, however, apparently...

...it looks like entering edit mode recalculates the height, and also the height is adjusted in display mode when any relevant values change. The height calculations are different, however, so each time going into edit mode changes the height and then later the display mode changes it to something else again.

E.g. the text presets all have "incorrect" height in the "eyes" of the edit mode, so adding a Text preset, entering the edit mode, and then leaving causes changes to happen.

**Comment by miina** [comment]
@o-fernandez Could you advise if this is a priority issue? This was split out from a priority issue since it was completely unrelated, seemed to be an easy fix originally, however, seems like it might have a bit more to it, so would be good to confirm the priority before spending too much time on it.

Moved it to 1.1 originally since the origin issue was high priority, we can move it out if this one is not.

**Comment by o-fernandez** [comment]
> @o-fernandez Could you advise if this is a priority issue? This was split out from a priority issue since it was completely unrelated, seemed to be an easy fix originally, however, seems like it might have a bit more to it, so would be good to confirm the priority before spending too much time on it.
> 
> Moved it to 1.1 originally since the origin issue was high priority, we can move it out if this one is not.

Thanks for flagging this. I think this is a nice to have, labeled as P3 and removed from any release.

**Comment by miina** [comment]
FI: This is not ready for review, I started it but it got deprioritized due to being much more complex than originally assumed. Moved it back to "Ready for Sprint" and re-estimating to 5.
