### ISSUE TITLE
WordPress Admin Menu not highlighting the right page

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#4891]
If I navigate to a dashboard page (e.g., Explore Templates) the wordpress nav menu is still highlighting "My Stories" instead of the appropriate dashboard page. 
![image.png](https://images.zenhubusercontent.com/5e98486db524b82fc96aeaf6/0b701603-edcc-4b08-8ff6-cf30efaf8cf5)

_Originally posted by @o-fernandez in https://github.com/google/web-stories-wp/issue_comments/707953717_

**Comment by swissspidy** [comment]
@carlos-kelly assigning to pea pod since it sounds like something the dashboard app would need to do. Similar to how it already changes the document `<title>`

We can help with e2e tests if needed

**Comment by maxyinger** [comment]
@swissspidy Just for my own learning purposes, what's the reason for having sub-menu slug as 'stories-dashboard-explore' with a redirect for that route to `stories-dashboard#/templates-gallery` vs just making the sub-menu slug `stories-dashboard#/templates-gallery` ?

https://github.com/google/web-stories-wp/blob/34d6e7f2e49c32b6ca9a8759d6e65952d899f430/includes/Dashboard.php#L129
https://github.com/google/web-stories-wp/blob/34d6e7f2e49c32b6ca9a8759d6e65952d899f430/includes/Dashboard.php#L190

Doesn't fix the highlighting issue, but does prevent a full page refresh when in the dashboard and clicking on the wp nav to get to templates. I'm sure there's some context here that I'm missing tho

Also, just to verify, for this fix are you suggesting just using some js to get & manipulate the WP sub-link's classes when we're on this route?

**Comment by swissspidy** [comment]
> Just for my own learning purposes, what's the reason for having sub-menu slug as 'stories-dashboard-explore' with a redirect

Unfortunately WordPress doesn't make it easy to add the pages in way we needed them to be in. That's why we did this redirect thing. But I don't think we've tried `dashboard#/templates-gallery` as it didn't occur to me that this could work. So I am a bit surprised to learn that it does indeed work! Let me simplify this then :-) PR: #5009

> Also, just to verify, for this fix are you suggesting just using some js to get & manipulate the WP sub-link's classes when we're on this route?

Yep, that was my idea. Let me know if this could work or if there are better ways.

**Comment by maxyinger** [comment]
Awesome. sounds good. 

> Yep, that was my idea. Let me know if this could work or if there are better ways.

Yea will absolutely work. Feels a little weird to reach out from the app to alter the WP interface, but I don't see any better way to accomplish this

**Comment by swissspidy** [comment]
Yeah I know 😬 In the future we'd want to move this out of the app into a dedicated WP integration layer.

**Comment by csossi** [comment]
WP side nav isn't changing when returning to My Stories from Setting or Explore Templates:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/572dca2e-5a0c-45d2-815b-7ab8b0e4b7a0)

**Comment by maxyinger** [comment]
@csossi ahh good catch. thanks! 

Just pushed up a change to fix this behavior and added tests for this behavior in our e2e tests.

Will move this back to QA ready once it passes CI.

**Comment by csossi** [comment]
Verified in QA

**Comment by samitron7** [comment]
Verified in UAT
