### ISSUE TITLE
Update AMP PHP Library Integration

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#4897]
## Feature Description

Tracking ticket for once we need to update our usage of the AMP PHP library.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
There's now https://packagist.org/packages/ampproject/amp-toolbox in the works

**Comment by swissspidy** [comment]
I think this is blocked as long as there's no AMP plugin release which also uses that library.
