### ISSUE TITLE
Indicator in Dashboard for Errors in Published Stories

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#4902]
## Feature Description

An indicator in the Dashboard lets a user know if we detect errors in a published story that would hinder or prevent distribution. This would only be surfaced for Errors as outlined in the pre-publish checklist (#78)

This will help users know whether they need to review and update a story they previously published to improve its chances for distribution. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by carloskelly13** [comment]
This will be doable once all the logic stories inside this parent epic are completed. That way the dashboard can reuse the verification logic once they are built and show the indicator on the dashboard.

**Comment by swissspidy** [comment]
> That way the dashboard can reuse the verification logic once they are built and show the indicator on the dashboard.

We probably want to store the verification result in the story data or WordPress post data so that the dashboard doesn't have to re-run all the verifications but can just display the results

**Comment by BrittanyIRL** [comment]
It might be cool to revisit this now that the checklist's been refactored. It seems pretty straightforward now to save issue counts by type (priority, design, accessibility) to the story which could then be accessed in the dashboard. 

@swissspidy @littlemilkstudio @choumx  thoughts?

**Comment by swissspidy** [comment]
If we save the issue count with the story, the count can quickly become stale. Example: checklist flags missing site title, but users adds a site title in the meantime.

Also, this will not cover situations where users installed a new plugin in the meantime that causes AMP validation errors (which clearly hinders distribution). And this is what the ticket is about, at least that's my understanding. It certainly an important scenario.

So the only reliable way to do this is by checking AMP validation in the background, either async client-side or in a worker, or server-side in a cron job.
Of course that doesn't cover things like missing video captions. So the question is whether that's in scope.

**Comment by BrittanyIRL** [comment]
😢   Great points about those newer checks that are included. This makes sense to keep in the backlog. Still think it's an interesting idea but probably not where we need to spend energy at the moment. Bit of a tangent, when we updated the placement of the checklist we started tracking if users are toggling open the checklist - i'm curious if those numbers have proven significant - if people are using this tool with it out of the panel, could help us determine if this is something we want to eventually see in the dashboard or otherwise think about how to improve the feature itself.

**Comment by swissspidy** [comment]
Some anecdotal evidence before I dig into telemetry stats:

From talking to creators/publishers directly and also from the support forums, I know that the checklist is definitely being used a lot and people pay very close attention to it. Sometimes perhaps even a little too much, as they worry about little things having a negative impact on their SEO.
They really try to have 0 issues at the time of publishing.

So IMO the dashboard would be a good way to show issues that arise after publishing. But even then we'd need to be careful: when installing a rogue plugin, suddenly _all_ your stories would have a big validation error bubble in the dashboard.

**Comment by BrittanyIRL** [comment]
yeah, this is definitely a bigger lift than just "add an indicator". 

I'm glad people are using the feature though!
