### ISSUE TITLE
Swap text combos text with generic / non quotes and non-real names. 

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#4903]
## Feature Description

Some text combos have designer names, quotes and text. We should swap that out for generic text prior to shipping the text sets. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by dmmulroy** [comment]
Starting on Cover - Will follow up with link to PR

**Comment by BrittanyIRL** [comment]
Starting on List 1 - will follow up with link to PR

**Comment by dmmulroy** [comment]
Cover PR - https://github.com/google/web-stories-wp/pull/4984

**Comment by dmmulroy** [comment]
Starting on Quote

**Comment by dmmulroy** [comment]
Quote PR - https://github.com/google/web-stories-wp/pull/4985

**Comment by dmmulroy** [comment]
Starting on Table

**Comment by BrittanyIRL** [comment]
Also doing list 2 while in list 1

**Comment by BrittanyIRL** [comment]
Lists 1 + 2 PR - https://github.com/google/web-stories-wp/pull/4988

**Comment by BrittanyIRL** [comment]
Starting on Editorials, PR to follow

**Comment by dmmulroy** [comment]
Table PR - https://github.com/google/web-stories-wp/pull/4987

**Comment by dmmulroy** [comment]
Starting on Contact

**Comment by dmmulroy** [comment]
Starting on Editorial

**Comment by dmmulroy** [comment]
Editorial PR - https://github.com/google/web-stories-wp/pull/4991

**Comment by BrittanyIRL** [comment]
> Starting on Editorials, PR to follow

Abandoning since Dillon tackled this :)

**Comment by BrittanyIRL** [comment]
Starting Steps

**Comment by dmmulroy** [comment]
Section header PR- https://github.com/google/web-stories-wp/pull/4992

**Comment by BrittanyIRL** [comment]
Steps PR - https://github.com/google/web-stories-wp/pull/4993
