### ISSUE TITLE
Embed Block: Do not use amp-story-player in `save` function

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#4907]
## Feature Description

As discussed at https://github.com/google/web-stories-wp/pull/4671#issuecomment-709966538, the goal of the embed block's `save` component is to provide a fallback so that there's still some content when the user deactivates the plugin.

The current output - `<amp-story-player>` - fails to do that because we don't print the necessary JavaScript with it. And we cannot print the necessary JavaScript because it requires `unfiltered_html` caps.

So we should be saving something else!

Possibilities:

* Just print the story URL as a fallback (like some other embed blocks do)
* Print the story with an image as fallback (could be using `Image` class)  
  _This would be very similar to #3879 / #3868 - almost a resurrection of that work_

I _think_ using the `Image` class should be fine, so let's try that.

**Important consideration**: this change requires block deprecation.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

- Replace [hardcoded](https://github.com/google/web-stories-wp/blob/1e606f9cd3fd4b0b72f22399f39f8960c47abb35/includes/Admin.php#L113-L156) block in admin.php with `Image` render class output. 
- Change [save](https://github.com/google/web-stories-wp/blob/1e606f9cd3fd4b0b72f22399f39f8960c47abb35/assets/src/story-embed-block/block/save.js#L50-L56) method to not save amp story player. 
- Add migration for old style block content to new image.

**Comment by spacedmonkey** [comment]
Do we have to write a migration here to convert old stories into image in content?

**Comment by spacedmonkey** [comment]
Add IB.

**Comment by swissspidy** [comment]
As mentioned in the ticket description it needs a block deprecation. But we're not going to migrate all posts automatically if that's the question. Block deprecations should suffice.

**Comment by spacedmonkey** [comment]
Sorry by migration here, I mean if we change save method we will need a deprecation. Like the one found [here](https://github.com/google/web-stories-wp/pull/3879/files#diff-bd3e011392904d41825851f4bfb9fd926adec6b2a69972cfd074c88e25cd60c0R1-R103). This would mean that any post opened with the old style would be migrated / updated to the new style. I didn't mean a WP CLI script or anything.

**Comment by swissspidy** [comment]
Got it. Yes we do.

> Important consideration: this change requires block deprecation.
