### ISSUE TITLE
Text Sets MVP (Text and Shape Combinations)

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#491]
## Feature Description

This epic is to add text set functionality (multi-element presets) to the editor. This is also known as Text Combos, but will simply be referred to as Text Sets in all related tickets for simplicity.

It is primarily a text feature related to having a list of 100+ predefined text sets available in the text pane to quickly add multiple text fields (and often also simple shapes) to the current slide.

- Text Sets will be displayed as combinations of text and shapes (e.g., a header and body text, or 3 different elements, or even 10 texts and 8 shapes). Upon clicking on a text set it will be added to the canvas with placeholder text that the user can easily update. 
- The elements in a text set, are added to the canvas styled as seen in the text panel.
- When first added, all elements are pre-selected so the user can easily re-positioned the elements to where they’d like, and (for text-only sets) quickly change the font color, font family, etc.
- Once in the canvas, the elements are independent elements. The user can select just one of them and modify it independently from any other elements in the set.

**[Product brief](https://docs.google.com/document/d/1hAAa1WFD6GTK3e3QoEJt2_AHReIHG_KpPn1j5ROIauc/edit#heading=h.ont12myuc7t9)**

**[Text Set UX designs](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Book?node-id=710%3A0)**

## Reviews
- [x] Product brief reviewed by UX
- [x] Product brief reviewed by eng (TL and/or dev)
- [ ] UX Design reviewed and approved by PM
- [ ] UX Design reviewed and approved by eng
- [ ] Eng design reviewed by TL (if needed)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
@jauyong Can you add some details to this?

**Comment by jauyong** [comment]
@swissspidy @pbakaus @samitron7 
I don't see a brief for text combinations written yet. (Nor for Font Presets #353)
I only see the section included in designs, but couldn't find any UX details. 
![image](https://user-images.githubusercontent.com/5874851/80027200-5f3afa80-84b1-11ea-8e5c-a237fa2ffa5e.png)

**Comment by o-fernandez** [comment]
Text combinations being developed by design agency, adding to UX backlog, but need to manage through agency.

**Comment by samitron7** [comment]
@jauyong Work for this will start in possibly 1-2 weeks. Will update this ticket once things get rolling. We'll try to get the curated list first then work on the combinations. Considered blocked till then.

**Comment by bmattb** [comment]
update - @samitron7  to bring into the new design system and share the Figma files

**Comment by samitron7** [comment]
This ticket should probably be broken into smaller pieces:

1. Text sets (there are ~125 of them) [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Stories-Stable?node-id=858%3A40764)
2. Implementation of the harmonic type scale [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Stories-Stable?node-id=837%3A1962)
3. Filter text set [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Stories-Stable?node-id=837%3A1962)
4. Add text to page [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Stories-Stable?node-id=885%3A9)

**Comment by bmattb** [comment]
This ticket requires further breakdown by @carlos-kelly and estimation on those tix

**Comment by carloskelly13** [comment]
The first three tickets of work are #3965, #3966, #3967.

**Comment by bmattb** [comment]
@o-fernandez I think that this ticket should be transformed to an epic called Text Sets / Combinations where we can effectively track the related work, LMK if you are okay with this.

**Comment by o-fernandez** [comment]
> @o-fernandez I think that this ticket should be transformed to an epic called Text Sets / Combinations where we can effectively track the related work, LMK if you are okay with this.

Agreed! Just updated to be an Epic. Will link the subtickets that @carlos-kelly mentioned above. Also moved it to the Epics column.

**Comment by o-fernandez** [comment]
Let's add this to 1.1, based on @barklund and @carlos-kelly input we can split this work between sprints 37 and 38.

**Comment by swissspidy** [comment]
@o-fernandez @barklund Has internationalization been considered for text sets? I suppose they should be translatable..?

**Comment by o-fernandez** [comment]
I don't think so, but:

- translating them would probably also require design review and updates per language to fit text properly, sizing, etc. 
- the content of the text set itself is not important/critical IMO, it's the layout. 

Given that, I think that translating the text in the text sets is probably lower priority and not blocking to launching the feature. But, LMK if it is low efforts/we can still fit it in when building it. @samitron7 for thoughts.

**Comment by swissspidy** [comment]
Not something I'd consider a blocker either. I just wanted to raise awareness for it :-)

It's not a straightforward to implement as internationalization also means support for languages like Arabic or Japanese, and for this feature it has to be well thought out it seems.

**Comment by samitron7** [comment]
@o-fernandez do you want to still do translation? If so, can we create a separate ticket and prioritize. Considering everything else we have, translation seems low on the list of to-do.

**Comment by o-fernandez** [comment]
@samitron7 no text sets translation needed for this ticket. Just filed a new ticket for the i18n part. #4767 We can tackle that at a future time.
