### ISSUE TITLE
Pre-Publish Checklist: Missing Critical Metadata Logic

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#4910]
## Feature Description

Implement the logic to throw an error if one or more of the critical issues are present:

- Missing title
- Missing story portrait cover
- Story portrait cover size too small (less than 640 x 853) or wrong aspect ratio (not 3:4) ← we should try to prevent this
- Publisher logo is too small (less than 96x96) ← we should just prevent this. 
- Link and page attachment conflicts: there’s a link in the page attachment region, and page attachment is enabled for that page. ← we will try to prevent this in most cases, but capturing a final check to avoid edge cases. 

These are critical issues and a story should not be publishable with these present.

https://docs.google.com/document/d/1GJZljicdXcP7oRdywsF3EGUaCVpCHsDrK2gUMubnrbk/edit?pli=1#

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
I created #5105 to expose cover image size in the API

**Comment by swissspidy** [comment]
> Publisher logo is too small (less than 96x96) ← we should just prevent this.

Opened #5107 to prevent this
