### ISSUE TITLE
Pre-Publish Checklist: General Guidance Logic

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#4912]
## Feature Description

- Story has less than 4 pages or more than 30 pages (per guidelines, though dev guidelines suggest 5-30 w/ 10-20 being ideal)
- Story title is longer than 40 characters (recommended)

**_UPDATE 10/30/2020:_** Propose skipping the rest of the checks below for now as we don't have support for multiple cover images, we should focus the user only on the portrait image (covered in #4910)

_- Missing story landscape poster/cover_
_- Story landscape poster/cover size too small (less than 853 x 640) or wrong aspect ratio (not 4:3) ← we should try to prevent this_
_- Missing story square poster/cover_
_- Story square poster/cover size too small (less than 640 x 640) or wrong aspect ratio (not 1:1) ← we should try to prevent this_

**Comment by swissspidy** [comment]
The recommendations for square and landscape posters are interesting.

Right now we just crop the original (portrait) poster into square/landscape formats. But that means if a user uploads a 640x853 portrait poster (correct sizes), we cannot crop a 853x640 landscape version out of that.

Should we give the users an option to upload square and landscape versions instead?

To my knowledge these formats are not really used anywhere today.

The square format would be useful though if we want  to display stories as circles somewhere.

**Comment by swissspidy** [comment]
@o-fernandez I think some clarification is needed on the checks for the cover image, as per my comment above.

**Comment by o-fernandez** [comment]
Sorry, reading through this now. Currently, as far as I can see from a user perspective, the user only sets one cover image. The most critical dimensions for the cover image are the portrait cover dimensions, so we should focus the checks on those dimensions (which is covered as part of #4910)

Given [this thread](https://docs.google.com/document/d/1GJZljicdXcP7oRdywsF3EGUaCVpCHsDrK2gUMubnrbk/edit?pli=1&disco=AAAAGuRCCho) it seems that there's ambiguity as to the criticality of square and landscape cover images. If those become important, I imagine that we'd want to let users preview all three cover images and edit them/customize each of them, so we should think of the UX holistically to properly support them, **when they become important.**

So, for now, I propose that we:
* Add a check here/guidance to focus the user on portrait cover image - if the height/width ratio is off we can let the user know that it may get cropped when the portrait image is used. 
* Skip the checks for landscape and square cover images, show only the portrait one. If they are already implemented, propose avoiding showing them in the UI for now, until we have a good flow for the user to review the square and landscape cover images and update them as needed. 

@swissspidy @carlos-kelly @samitron7 @choumx does that work for you all? 

I'll update the bug description - sorry for the changes.
