### ISSUE TITLE
Jetpack: Metadata Duplication

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#4913]
## Feature Description

This is a follow-up to #3092

While that one works great, it results in duplicate Open Graph tags being printed because Jetpack does not remove existing ones.

Seems like they'd need to do this:

```php
$instance = Google\Web_Stories\get_plugin_instance()->discovery;
\remove_action( 'web_stories_story_head', [ $instance, 'print_open_graph_metadata' ] );
\remove_action( 'web_stories_story_head', [ $instance, 'print_twitter_metadata' ] );
```

Not sure if they're open to do this.

Alternatively we remove those two actions if we detect Jetpack.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
@swissspidy I have closed the existing PR in favour of a cleaner solution with a new filter and a PR on the jetpack project. Can you take a look and get back to me.

**Comment by spacedmonkey** [comment]
Would it is easier just to do this?

```
add_filter( 'jetpack_enable_open_graph', function( $current ){
      if ( is_singular( Story_Post_Type::POST_TYPE_SLUG ) ) {
	    return false;
      }
      return $current;
});
```
Just disable jetpack's meta data on web stories meaning we have full control of metadata.

**Comment by swissspidy** [comment]
Well yeah maybe. If our implementation is on par or even superior, then that would be a strong reason.

I've asked for clarification at https://github.com/Automattic/jetpack/pull/17815#issuecomment-728283382

Let's wait to hear what the recommendation is.

**Comment by spacedmonkey** [comment]
The problem with my solution, is the meta data would be different across the site.
