### ISSUE TITLE
HTTP video sources despite HTTPS available

### ISSUE THREAD

**Issue by dreamofabear** [GoogleForCreators/web-stories-wp#4928]
## Bug Description

Stories can be rendered with HTTP video sources despite HTTPS support on the domain, which causes the stories to fail AMP validation.

Example: [this story](https://thetinyherbivore.com/web-stories/fall-outfits-for-easy-hikes/) contains a [HTTP video](http://thetinyherbivore.com/wp-content/uploads/2020/10/Outfit-1-4.mp4) > `source[src]`, but the domain [supports HTTPS](https://thetinyherbivore.com/web-stories/fall-outfits-for-easy-hikes/). See [validation errors](https://validator.amp.dev/#url=https%3A%2F%2Fthetinyherbivore.com%2Fweb-stories%2Ffall-outfits-for-easy-hikes%2F).

## Expected Behavior

- Render story URLs as HTTPS if supported by the domain. 
- If the domain doesn't support HTTPS, display a warning (perhaps in the prepublish checklist).

## Steps to Reproduce

Perhaps WP admin is used in HTTP mode? 

TODO(choumx): Follow up with creator.

## Screenshots

N/A

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
I think there are a number of things think about here. But the best way to explain them is to give some scenarios. 

Scenario 1.

Users logins into http://www.example.com, creates story, uploads videos / images. 
Another user views story on https://www.example.com. There are references in content to http version. 

In this case we should change the content on https. This is all references, like links. 
Replace http://www.example.com -> https://www.example.com

No issue. 

Scenario 2. 

Users logins into https://cms.example.com, creates story,  uploads videos / images. ( I have done this for a project to lock down the CMS url ). 
Another user views story on https://www.example.com. There are references in content to cms.example.com. 

We should replace https://cms.example.com -> https://www.example.com . This will save DNS lookup. 

Scenario 3. 
Users logins into http://www.example.com, creates story,  uploads videos / images. Site uses a plugin to serve images from a different url. Example [S3 Uploads](https://github.com/humanmade/S3-Uploads), [Jetpack Photon](https://jetpack.com/support/site-accelerator/) or [Google Cloud Storage](https://wordpress.org/plugins/gcs/). 

Users logins into http://www.example.com, uploads videos / images. Image references are saved in content. Example http://spacedmonkey.ams3.digitaloceanspaces.com/

Another user views story on https://www.example.com. There are references in content to http version. 
We need to check that third party store of assets, supports https before we replace references in content. 
In this case, I think this is unlikely to be a problem. Most popular asset management services like S3, GCS and Photon do support https. But we need to have a test case for this in unit tests, I would say. 

So when the story renders, we should replace site_url ( cms url ) with home url ( public facing url ). It is also safe to change http link to https, if the user is viewing the site on https, as we know we can support it.

**Comment by swissspidy** [comment]
FWIW, there are some initiatives about fixing this in WordPress core led by our team at Google:

https://core.trac.wordpress.org/ticket/47577
https://core.trac.wordpress.org/ticket/51437
