### ISSUE TITLE
Video playback fails (.mov file) in unsupported browsers, try to avoid/fix

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#4931]
## Bug Description

This story was created using the WP plugin: https://www.tedisarah.com/web-stories/vegan-sneakers-2/

In page 3, there's a video that consistently shows "video failed to play" in Chrome/laptop. May also be Chrome-wide. 
![image](https://user-images.githubusercontent.com/13389997/96627625-230d1900-12df-11eb-80c4-063970c58edb.png)

It's a .mov video. **Only older versions of Safari, plus other browsers that supported Apple's QuickTime plugin.**

Can we explore solutions to this problem? Can we optimize/convert the video? If not, at a minimum we should discourage the use of .mov. 

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by dreamofabear** [comment]
+1 to just disable selecting videos with `.mov` container for now.

**Comment by bmattb** [comment]
@o-fernandez - what's the call?

**Comment by o-fernandez** [comment]
I'm good with @choumx's suggestion to disable the selection of `.mov` for now.

**Comment by swissspidy** [comment]
That's nice and all, but I don't see how one can currently even select `.mov` files?!

Dragging an `.mov` file onto the canvas results in an error message saying

```
Please choose only gif, jpe, jpeg, jpg, m4v, mp4, png, webm to upload.
```

And if I already have a `.mov` file in the WordPress media library, it will not be listed in the editor's media library.

**Comment by dreamofabear** [comment]
Just tried it and this worked for me:
1. Tap blue "Upload" button in media tab.
2. Select `.mov` file
3. Tap "Insert into page".

> And if I already have a .mov file in the WordPress media library, it will not be listed in the editor's media library.

Looks like `.mov` files will be filtered out of the editor media library eventually (except if immediately uploaded above), but you can still view them by tapping "Upload" and switching to the "Media Library" tab in the "Upload to Story" popup.

**Comment by swissspidy** [comment]
Ah, the media modal!

Sounds like an easy fix:

In `MediaPane` we call `useMediaPicker()`. There we just have to provide the `type` param specifying that we only allow a specific set of videos and images:

Before:

```js
const openMediaPicker = useMediaPicker({
  onSelect,
  onClose,
});
```

After:

```js
const {
    allowedMimeTypes: {
      image: allowedImageMimeTypes,
      video: allowedVideoMimeTypes,
    },
  } = useConfig();
const allowedMimeTypes = useMemo(
  () => [...allowedImageMimeTypes, ...allowedVideoMimeTypes],
  [allowedImageMimeTypes, allowedVideoMimeTypes]
);

const openMediaPicker = useMediaPicker({
  onSelect,
  onClose,
  type: allowedMimeTypes
});
```

But @spacedmonkey can probably confirm

Edit: Alternatively `useMediaPicker` could use that as a default, since it rarely needs to be overridden.

**Comment by spacedmonkey** [comment]
Related: https://github.com/google/web-stories-wp/issues/5118

**Comment by csossi** [comment]
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/d382bc56-75f7-4d76-86a9-091231c4087a)

Verified in QA

**Comment by samitron7** [comment]
I'm still able to upload .mov files. It's not a great experience to allow to upload .mov files just to be greeted with the snack bar error that they are not allowed when I attempt to place it on the page.
