### ISSUE TITLE
Add button component to design system

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#4936]
https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=30%3A21

Acceptance criteria:

Creates light mode button variants as components
Storybook updates
Should have unit tests

**Comment by BrittanyIRL** [comment]
Hey @samitron7 

I noticed that the colors on the buttons don't sync 100% with the colors listed in the theme, is this intentional? 

These hexes are taken from [figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=1286%3A456428) for the button component - I bolded values that are set on the buttons that do not sync with theme colors: 
1) primary colors: #CBACFF (normal), **#B695EE** (hover, focus), **#EFEFE**/ #A1A09B (disabled)
2) Secondary colors: **#D1D1CC** (normal), #A1A09B (hover, focus), **#EFEFE**/ #A1A09B (disabled)
3) Tertiary colors:  #fff (normal), **#EFEFEF** (hover, focus), white/#A1A09B (disabled)

<img width="198" alt="Screen Shot 2020-10-26 at 9 26 54 AM" src="https://user-images.githubusercontent.com/10720454/97200279-3f410800-176e-11eb-9ce7-f76ea65d375d.png">
<img width="165" alt="Screen Shot 2020-10-26 at 9 26 43 AM" src="https://user-images.githubusercontent.com/10720454/97200281-40723500-176e-11eb-9930-82bfad2b6f9e.png">

**Comment by samitron7** [comment]
@BrittanyIRL For context, we had to expand the color theme to better support accessibility. As for the mismatch, I have a check-in with the visual designer tomorrow so let me get back to you on this. I think it might be an oversight.
