### ISSUE TITLE
Redesign: New slider component

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#4938]

**Comment by BrittanyIRL** [comment]
Ticket added to keep track of new design system components - unnecessary for dashboard, not part of initial set up to start using design system external to dashboard.

**Comment by miina** [comment]
This is needed for the Workspace area (media edit mode) -- should we move this over to Prometheus pod?
cc @barklund

**Comment by csossi** [comment]
Verified in QA
