### ISSUE TITLE
Add control - checkbox to design system

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#4940]
Add checkbox to design system from figma.
https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=1533%3A260040

**Comment by samwhale** [comment]
The checkbox is not in use anywhere in the application, can go straight to UAT

**Comment by BrittanyIRL** [comment]
Can be UAT'd on staging: https://google.github.io/web-stories-wp/storybook/?path=/story/designsystem-components
