### ISSUE TITLE
Add control - toggle to design system

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#4942]

**Comment by BrittanyIRL** [comment]
Ticket added to keep track of new design system components - unnecessary for dashboard, not part of initial set up to start using design system external to dashboard.

**Comment by samwhale** [comment]
Sam said the UX team is looking into usability issues for this toggle. Pausing work for now.

**Comment by samwhale** [comment]
This can be UAT'd on staging: https://google.github.io/web-stories-wp/storybook/?path=/story/designsystem-components-toggle--default

**Comment by tmagalhaes-huge** [comment]
@samwhale @BrittanyIRL The green colors on the toggle don't seem to match the latest DS designs and the checkmark icon looks different too, thinner and slightly different shape. Can we double check? Maybe it's a browser rendering issue only?

**Comment by samwhale** [comment]
@tmagalhaes-huge The checkmark is different from when I initially made the toggle. Looks like that was changed here: https://github.com/google/web-stories-wp/pull/6311 (Icon update).

---

Looks like I'm seeing the colors in the code and browser dev tools match the listed colors in figma but the browser is rendering a slightly different color 😕 

|State|Designs|Storybook|
|--|--|--|
|Normal|<img src="https://user-images.githubusercontent.com/22185279/110500927-eb98e080-80b6-11eb-9b66-892046180075.png" width="300px" />|<img src="https://user-images.githubusercontent.com/22185279/110500981-f8b5cf80-80b6-11eb-9b7a-4782c2313901.png" width="300px" />|
|Hover|<img src="https://user-images.githubusercontent.com/22185279/110501714-b17c0e80-80b7-11eb-83b6-97321154fa2c.png" width="300px" />|<img src="https://user-images.githubusercontent.com/22185279/110501690-aa550080-80b7-11eb-811d-9413a8226234.png" width="300px" />|

|Color|Designs|Storybook|
|--|--|--|
|Normal track background ![image](https://user-images.githubusercontent.com/22185279/110501912-e7b98e00-80b7-11eb-9bdf-62a6599811b0.png)|<img src="https://user-images.githubusercontent.com/22185279/110501938-eee09c00-80b7-11eb-96f4-a6061401dd87.png" width="300px" />|<img src="https://user-images.githubusercontent.com/22185279/110501958-f607aa00-80b7-11eb-8976-52a7fe79ced9.png" width="300px" />|
|Hover track background![image](https://user-images.githubusercontent.com/22185279/110502163-2fd8b080-80b8-11eb-822e-e897ad353292.png)|<img src="https://user-images.githubusercontent.com/22185279/110502226-3f57f980-80b8-11eb-9741-f682ea0bc82d.png" width="300px" />|<img src="https://user-images.githubusercontent.com/22185279/110502285-4c74e880-80b8-11eb-8aef-a730c1fbfaf6.png" width="300px" />|
|Circle Background![image](https://user-images.githubusercontent.com/22185279/110502183-36672800-80b8-11eb-856c-4d95ed60a833.png)|<img src="https://user-images.githubusercontent.com/22185279/110502252-44b54400-80b8-11eb-91ce-b8fbbc5ec96b.png" width="300px" />|<img src="https://user-images.githubusercontent.com/22185279/110502330-572f7d80-80b8-11eb-8f2d-98f2d004ece5.png" width="300px" />|

**Comment by BrittanyIRL** [comment]
Looking at the current icons available in the design system - foundation it looks like the checkmark in the toggle matches the [checkmark available in the icons ](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3441%3A80829)- which is the update @samwhale mentioned above in #6311 : 
<img width="273" alt="Screen Shot 2021-03-09 at 9 46 13 AM" src="https://user-images.githubusercontent.com/10720454/110506495-5f89b780-80bc-11eb-97cb-dc1ae65668ed.png">

Do we need a variation of the checkmark?

**Comment by tmagalhaes-huge** [comment]
@BrittanyIRL I wonder if it's because the toggle is using the XS size of that icon and the current toggle is using the S size?

**Comment by BrittanyIRL** [comment]
I just tried swapping it real quick (I know it's a little off center) - is this icon better?
<img width="256" alt="Screen Shot 2021-03-09 at 1 26 23 PM" src="https://user-images.githubusercontent.com/10720454/110533332-1dbc3980-80db-11eb-8c37-4adc04dcfc7e.png">

**Comment by tmagalhaes-huge** [comment]
Yes! @BrittanyIRL Looks better. Thank you!

**Comment by BrittanyIRL** [comment]
ok i will make a new ticket 👍
