### ISSUE TITLE
Add input field - dropdown to design system

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#4950]
Outstanding questions for design team: https://docs.google.com/document/d/1w06W9T3sxbiqveoz9Zk9_sO87JPO4seQzjo1FIDBK54/edit#

Acceptance Criteria: 
Run storybook locally and navigate to designsystem/components/dropdown. These dropdown demos should mimic our existing dropdown functionality.

- On default, if no value is currently selected the first list item should be focused
- On default, when a new item is selected the menu should close
- if isKeepMenuOpenOnSelection is true, the menu should not close when a new item is selected
- A menu should not open if the disabled knob is true in storybook
- 'No options available' should show up when menu is expanded if there are no items in an array
- If there is a currently selected value when a menu is opened it should be in focus and in view.
- You should be able to navigate dropdown list with your arrow keys. If isRTL knob is false then Up and Left arrows should move you up in the list. If isRTL knob is true then Up and Right arrows should move you up the list. (And respectfully, Down and Right arrows move you down, or Down and Left arrows move you down if isRTL is true).
- You should be able to select a new item by pressing Enter
- You should be able to close the menu by pressing Tab or Escape

**Comment by BrittanyIRL** [comment]
Ticket added to keep track of new design system components - unnecessary for dashboard, not part of initial set up to start using design system external to dashboard.

**Comment by BrittanyIRL** [comment]
Pending some feedback from design team. WIP PR is here: https://github.com/google/web-stories-wp/pull/5795

**Comment by BrittanyIRL** [comment]
This is visible on storybook, here: https://google.github.io/web-stories-wp/storybook/?path=/story/designsystem-components-dropdown--default

Please also note questions that came up as building it: https://docs.google.com/document/d/1w06W9T3sxbiqveoz9Zk9_sO87JPO4seQzjo1FIDBK54/edit#

**Comment by o-fernandez** [comment]
@samitron7 mind reviewing this as it is mainly about the UX of the new components?

**Comment by ivayloklissarov** [comment]
From looking at what has been built so far in the Storybook, I think we need to reconsider a little bit the UX of the component. Mainly in the theme of width behavior. @samitron7 @aaecheverria @tmagalhaes-huge

**Comment by BrittanyIRL** [comment]
@ivayloklissarov - Sam had mentioned just this week that width should be controlled by the parent container, when work was done on this it wasn't clear how to set boundaries on widths so more guidance is always appreciated! Plus this is exactly why storybook exists so we can iterate safely between design and development. 

Sam and I are meeting briefly today to discuss dropdowns and focus styles.

**Comment by aaecheverria** [comment]
Hi @BrittanyIRL 
Are you still waiting for additional guidance here or did you clarify them during your meeting with Sam?

**Comment by BrittanyIRL** [comment]
@aaecheverria - We're good i think but if there's further issues noticed by your team we can open new tickets to address anything.

**Comment by ivayloklissarov** [comment]
Sounds good! Closing the tickets.
