### ISSUE TITLE
Add system - snackbar to design system

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#4957]
Add new snackbar from figma to design system.
https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=1533%3A260040

**Comment by BrittanyIRL** [comment]
hey @samitron7 - few questions about snackbars for you. 

1. Do we ever need a dismiss button? 
2. Will messages always be aligned center-bottom of screen? 
3. Are you ok with messages potentially stacking? 
4. Do we need to have a severity of the message like material does? ie) error, warning, default, success 
5. What should the timeout be for these to dismiss?

**Comment by samitron7** [comment]
@BrittanyIRL We're pretty much following material [guidelines](https://material.io/components/snackbars#behavior) for snack bar. I also added a section for snack bar in [Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=1983%3A3). Will expand to banner, inline messages, banner and tooltips soon.

**Do we ever need a dismiss button?**
Snackbars appear without warning, and don't require user interaction. So no to dismiss button

**Will messages always be aligned center-bottom of screen?**
Place them at the bottom of the screen

**Are you ok with messages potentially stacking?**
If multiple snackbar updates are necessary, they should appear one at a time. This is the material recommendation.

**Do we need to have a severity of the message like material does? ie) error, warning, default, success
What should the timeout be for these to dismiss?**
Snackbars automatically disappear from the screen after a minimum of four seconds, and a maximum of ten seconds. They are the lowest in severity than banner than dialog boxes and really should be used for app processes.

Do we capture a list of error messages anywhere?

**Comment by BrittanyIRL** [comment]
Thanks for the details, @samitron7 ! 

> Do we capture a list of error messages anywhere? 

We're exposing error messages in the dashboard with alerts in a snackbar. 
Do you mean something different?

**Comment by samitron7** [comment]
Something different. In previous team, eng usually provides a list of errors for UX (some errors can be better captured b eng as it's hard for me to trigger). This just makes it easier for us to map out all the message/notification types. Its definitely not a blocker but just makes things easier if this list already exist somewhere.

[Here's](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=1989%3A0) a round-up of for messaging using the new design language.

**Comment by BrittanyIRL** [comment]
Hey @samitron7  - I think there is a discrepancy in blue 80 and the light theme linkNormal value - maybe has something to do with it being called `linkEnabled` in the snackbar. I went with the true blue 80 according to the blues in the color palette. Let me know if this is wrong. 

from the blue palette: 
<img width="190" alt="Screen Shot 2020-11-13 at 12 17 15 PM" src="https://user-images.githubusercontent.com/10720454/99112326-b8cc5900-25aa-11eb-9a7f-a16441e05c34.png">

as linkNormal by theme
<img width="373" alt="Screen Shot 2020-11-13 at 12 16 36 PM" src="https://user-images.githubusercontent.com/10720454/99112308-b407a500-25aa-11eb-8af5-0512cd068227.png">

in snackbar:
(should match light theme)
<img width="318" alt="Screen Shot 2020-11-13 at 12 18 25 PM" src="https://user-images.githubusercontent.com/10720454/99112311-b538d200-25aa-11eb-98c3-04c26ad896a3.png">

**Comment by samitron7** [comment]
Ah thanks for the catch. Let's use Blue 50 (#4F7ED9) for this. I reflected the change on Figma.

**Comment by BrittanyIRL** [comment]
perfect, thank you! (I also dropped the hover to be blue 60) 
<img width="413" alt="Screen Shot 2020-11-17 at 9 05 12 AM" src="https://user-images.githubusercontent.com/10720454/99414599-339bb980-28b4-11eb-9365-a16c5be2a038.png">

**Comment by samitron7** [comment]
@BrittanyIRL For snackbar with longer message, the cta should still be docked to the right and vertically centered. The version in storybook now would still be valid (ie for longer cta so we can keep that). Can we create one other one so that we can keep snackbar to 2 line minimal and not have the cta stretch to 3 lines.

**Comment by BrittanyIRL** [comment]
> @BrittanyIRL For snackbar with longer message, the cta should still be docked to the right and vertically centered. The version in storybook now would still be valid (ie for longer cta so we can keep that). Can we create one other one so that we can keep snackbar to 2 line minimal and not have the cta stretch to 3 lines.

@samitron7 Sure! I just created this ticket shell: https://github.com/google/web-stories-wp/issues/5490 Add to it what you are envisioning?

**Comment by samitron7** [comment]
@BrittanyIRL thank you. Will verify and close this ticket.
