### ISSUE TITLE
Add system - tooltip to design system

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#4958]
Add tooltip to design system based on figma. 
Also add to circular button on hover/active. 

https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=1533%3A260040

**Comment by BrittanyIRL** [comment]
Hey @samitron7 - I am curious about another discrepancy in colors in [figma.]( https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3398%3A83619) 

Dark mode is using interactive BG / primaryNormal as the background color of tooltips 
<img width="319" alt="Screen Shot 2020-11-17 at 2 25 45 PM" src="https://user-images.githubusercontent.com/10720454/99452787-437dc280-28e1-11eb-9923-e827b07a29ff.png">

While light mode is using FG / tertiary 
<img width="313" alt="Screen Shot 2020-11-17 at 2 25 25 PM" src="https://user-images.githubusercontent.com/10720454/99452790-44165900-28e1-11eb-9256-7a162bfdafd2.png">

I need this color in the theme to be in sync so we can toggle the theme (eventually). 

Are you ok with the light mode tooltip bg looking like this? 
<img width="234" alt="Screen Shot 2020-11-17 at 2 33 47 PM" src="https://user-images.githubusercontent.com/10720454/99453266-f1896c80-28e1-11eb-977d-3986de6403bd.png">

**Comment by samitron7** [comment]
Thanks for the catch. This has been fixed on Figma.

**Comment by BrittanyIRL** [comment]
Tooltips should be visible in storybook: https://google.github.io/web-stories-wp/storybook/?path=/story/designsystem-colors--default (designsystem/components/tooltip)

**Comment by ivayloklissarov** [comment]
I checked and Tooltips are created in the Design System and also present in the platform. Closing the ticket. @tmagalhaes-huge
