### ISSUE TITLE
Update dashboard header styles

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#4960]
Update header to new styles per https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=467%3A13745 

Heading and pills should be pulled in from the design system. Search to follow.

**Comment by BrittanyIRL** [comment]
This is fixed in feature/4960-dashboard-header (#6434) 
Regression testing for header (filtering stories on my stories), rendering appropriate headlines for settings and explore templates.  Headline on templates is updated to "Explore Templates".

**Comment by csossi** [comment]
Verified in QA
