### ISSUE TITLE
Update dashboard search styles

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#4962]
Use typeahead from design system and replace the custom one in the dashboard. 

https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=1533%3A260040

**Comment by BrittanyIRL** [comment]
This is updated in feature/4960-dashboard-header (#6434)

No new functionality, just regression testing on search in dashboard my stories

**Comment by csossi** [comment]
Horizontal scroll not appearing:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/ffe14449-4c82-4ab0-a06c-cb694cb86f48)

Was on PC/Chrome 88.0.4324.190

**Comment by BrittanyIRL** [comment]
I'm having a heck of a time reproducing this bug, Claudio. Can you try again? Is it not scrolling or is that a horizontal scrollbar doesn't appear?  

It doesn't show a scrollbar horizontally, it should just scroll when you scroll.

**Comment by csossi** [comment]
Verified in QA
