### ISSUE TITLE
update dashboard filter styles

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#4963]
Update dashboard results area (right above the grid or table) to the new specs - some stuff has swapped places. https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=467%3A13745

![Screen Shot 2021-02-16 at 12 50 14 PM](https://user-images.githubusercontent.com/10720454/108114530-27133280-7056-11eb-905b-699d23662a98.png)

Can use Text, Button, Icon, Tooltip and Dropdown from Design System

**Comment by csossi** [comment]
Verified in QA
