### ISSUE TITLE
Update dashboard grid styles

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#4964]
Ensure dashboard grid is accurate to new figma specs: https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=467%3A13745

Grid itself should be maintained in the dashboard however the Text, Menu, Input, Buttons and links associated with each card item should be used from the design system. 

This ticket should also allow for the spacing and dimensions to be tightened up per figma (see shared gutter spacing).

**Comment by iamsriranga** [comment]
@BrittanyIRL, can you add more description, so that I can try this.

**Comment by BrittanyIRL** [comment]
@saideepesh000 

Hi there! Appreciate you jumping in but this ticket is not ready to be worked on yet. Thanks!

**Comment by BrittanyIRL** [comment]
Testing (copied from PR) 

**My Stories (Regression testing)**

- On hover see 'Open in Editor'
- On focus see 'Open in Editor'
- Story titles should remain clickable, they are links that send you to the editor.
- Resizing the grid will recalculate space for story previews and keep the grid tight and justified.

**Explore Templates (Regression testing)**

- Keyboard focus works the same as my stories does as outlined above.
- Resizing the grid will recalculate space for template previews and keep the grid tight and justified.

**Comment by BrittanyIRL** [comment]
@csossi if you have time today, this would be really helpful to get through.

**Comment by csossi** [comment]
Verified in QA, @BrittanyIRL

**Comment by BrittanyIRL** [comment]
a billion thanks, @csossi !!!
