### ISSUE TITLE
Update dashboard table styles

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#4966]
Reference figma: https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=467%3A13745

Replace Text and Icons with design system versions, make sure list view matches the new designs

**Comment by BrittanyIRL** [comment]
@csossi if you get a chance today, this PR is blocking me from finishing the dashboard redesign.

**Comment by csossi** [comment]
Verified in QA
