### ISSUE TITLE
Update dashboard dialogues 

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#4968]
Update existing dashboard dialogs with new component from design system

**Comment by BrittanyIRL** [comment]
For details on testing, please reference this PR description: https://github.com/google/web-stories-wp/pull/5193 
This is only a surface level UI update, so the dialogs should all still function the same - they just should look like the updated figma designs (found here: https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3398%3A83619)

**Comment by csossi** [comment]
Unable to test in QA environment - looks like I need Storybook installed there?

**Comment by csossi** [comment]
Verified in QA

**Comment by BrittanyIRL** [comment]
Waiting to merge this until Sam has a second to review the general dialog added a while ago to storybook: https://google.github.io/web-stories-wp/storybook/?path=/story/designsystem-components-dialog--default

**Comment by samitron7** [comment]
Verified in UAT. Good to go @BrittanyIRL

**Comment by BrittanyIRL** [comment]
What was good to go earlier were the dialogs in storybook with the new designs, to UAT this actual ticket need to verify the 3 dialogs in the dashboard: 
- Delete story
- Delete publisher logo
- Preview story (this isn't following any pattern from figma, it's just using the same functionality)

**Comment by o-fernandez** [comment]
@BrittanyIRL I checked the first two, but can you clarify where in the "Preview story" flow I should see a dialog?

**Comment by BrittanyIRL** [comment]
> @BrittanyIRL I checked the first two, but can you clarify where in the "Preview story" flow I should see a dialog?

Ah, it's only if you have the "story preview" flag enabled. If enabled, "preview" shows up on hover of a story in the grid.
