### ISSUE TITLE
Update dashboard settings page to new designs

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#4969]
Use new design system components to update settings page. 

- All form components should be used from the design system. 
- Follow figma specs here: https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=467%3A13745

<img width="746" alt="Screen Shot 2021-01-25 at 8 34 41 AM" src="https://user-images.githubusercontent.com/10720454/105727316-31735e00-5ee8-11eb-99ae-5d4365525c74.png">

**Comment by csossi** [comment]
Unable to have multiple logos. When I upload a 2nd logo it replaces the first rather than appear as another logo option

https://share.getcloudapp.com/04uJP64W

**Comment by swissspidy** [comment]
@csossi Is this issue new with this specific change, or does it also happen on `main` / the stories-new site?

**Comment by BrittanyIRL** [comment]
@csossi weird! I just tested staging and the branch and they're working as expected. Can you open your console log and show what your API response is when that POST and GET happen?

**Comment by samwhale** [comment]
I just tested it as well and saw that it was adding a new one, but maybe mine is different since I already started with an image loaded in first.
![upload](https://user-images.githubusercontent.com/22185279/107243639-70c2a400-69ea-11eb-8f4d-ce5c4a98dff7.gif)

**Comment by BrittanyIRL** [comment]
Yeah i'm really curious about this. I went back and reset my entire environment so I started with a blank slate and it's still working. 🤔

**Comment by csossi** [comment]
> @csossi Is this issue new with this specific change, or does it also happen on `main` / the stories-new site?

just checked Main, @swissspidy  - happening there as well. Cleared cache and checked PC/Chrome and PC/Opera as well as Mac/Chrome - all with the same "replace" result

**Comment by swissspidy** [comment]
> > @csossi Is this issue new with this specific change, or does it also happen on `main` / the stories-new site?
> 
> just checked Main, @swissspidy - happening there as well. Cleared cache and checked PC/Chrome and PC/Opera as well as Mac/Chrome - all with the same "replace" result

thanks for testing. since this happens on `main` it's clearly not a bug caused by this change here and would warrant its own ticket. it should obviously not block QA on this change. any other findings there?

**Comment by csossi** [comment]
All good other than that, @swissspidy - setting this to "pass"
