### ISSUE TITLE
Automatic "set as background" for foreground images that cover page

### ISSUE THREAD

**Issue by samitron7** [GoogleForCreators/web-stories-wp#4971]
## Bug Description

If you add an image and stretch it to cover the entire page, we should automatically turn it into a bg image and not allow you to add a link.

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
@samitron7 should we take a harder stance? Something like... if an image/video/element covers > X% of the page, it can't have a link. And maybe some messaging to the user around this. WDYT? 

X% could be something like... 60% of the page based on image size/area on canvas. Ofc, the cropped version used, not the original media file size.

**Comment by dreamofabear** [comment]
I believe this only affects desktop -- mobile has glass panes over the page navigation areas. Also the format team will probably patch this soon, which is a better solution since it avoids the strange user messaging we'd need to figure out.

**Comment by dreamofabear** [comment]
- https://github.com/ampproject/amphtml/issues/30825 tracks the desktop navigation trapping in the format.
- https://github.com/ampproject/amphtml/issues/30322 tracks the larger "CTA is too large" issue.

**Comment by dreamofabear** [comment]
Factoring out the CTA issues from this issue. Some points in my offline conversation with @samitron7:

- Problem: "Set as background" button is not discoverable
  - Corollary: Background and foreground images have different functionality (e.g. page attachments, background color only available when background is selected)
- Solution A: Automate this for foreground images that cover 100% of the page
  - Requires changing behavior of background image that unsets rotation/scale 
- Solution B: Reduce delta between handling of background/foreground images
  - E.g. change UI to not require selecting background to set page attachment or background color

**Comment by swissspidy** [comment]
Duplicate of #5356
