### ISSUE TITLE
Add default value for padding to BG textfill

### ISSUE THREAD

**Issue by samitron7** [GoogleForCreators/web-stories-wp#4972]
## Bug Description

Text is wrapped very tightly inside the textbox. When I add a text bg fill, the results are quite ugly.

1. Can we add a behind the scene default padding of 6px horizontal and 4px vertical for fill
2. Add a corner radius of 2px (this should be visible to users)
![Screen Shot 2020-10-20 at 5.23.26 PM.png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/70611b58-634a-473a-a33f-25867e5f8eed)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
@choumx - after discussion with @carlos-kelly we would like to do the following : 
1. split this into two separate issues
2. complete 1 in this sprint (1hr work)
3. get priority and estimate against 2 - this one is more of a challenge and could have impact on implementing updating the copyrighted text in the text sets in this sprint as planned - we would need to know from stakeholders which is the priority here.

**Comment by bmattb** [comment]
Issue #2 was removed from this bug ticket and seperated out into #4980

**Comment by samitron7** [comment]
@bmattb The 2 links in your comment "Issue #2 was removed from this bug ticket and seperated out into #4890" don't appear to point to the bg hi-lite for this ticket.

**Comment by bmattb** [comment]
@samitron7 apologies - I transposed two numbers, should have been #4980 - i've updated it now, thanks!

**Comment by samitron7** [comment]
Thank you!

**Comment by samitron7** [comment]
When a user applies a text fill (regardless where it's fill or hilight), the result should look good. To do this we need to add additional padding before the scene that the user does not see in the padding input field:

**Adding text fill:**
Note the the defaulted padding value is not visible to users but the corner radius value is.
![Group 5720](https://user-images.githubusercontent.com/10889431/102397966-7f18b480-3f93-11eb-9e6b-e1c8fe5a558f.png)


**Adding text hilite:**
![Group 5718](https://user-images.githubusercontent.com/10889431/102396743-bb4b1580-3f91-11eb-8d92-d62b504b8a4a.png)

**Comment by carloskelly13** [comment]
@samitron7 I see what you are saying. These should not be the values they see in the editor, but rather behind the scenes values.

**Comment by samitron7** [comment]
@carlos-kelly Yes!!!

**Comment by maxyinger** [comment]
I think this ticket should be repointed.

As far as I see it, involves all these steps to have a inherent padding since it kinda touches all aspects of positioning/sizing code across all versions of the text element (display in editor, display in editor while editing, resizing display, output in generated story):

1) augment display element wrapper x, y, height & width to be larger given the inherent padding
2) alter the innermost fg display element to take up the full width/full height minus the padding
3) augment frame element wrapper x, y, height & width to be larger given the inherent padding
4) figure out how to make this not mess up resizing the text element
5) apply this padding to the text element when it's getting edited as well as the resizing frame (steps 1 & 2 but for in editing mode)
6) apply padding to the output story text element

**Comment by BrittanyIRL** [comment]
Thanks for these outlined steps, @littlemilkstudio. It feels like there was a significant amount of discovery to figuring out implementation details. Given the complexity, what would you re-point to? 5? 

@bmattb - would you rather see this ticket (4972) become discovery and a new one, linked, is created for the actual work?

**Comment by maxyinger** [comment]
Yea I would say a 5 feels accurate given it touches so much and should necessitate some extra tests.

**Comment by maxyinger** [comment]
Figured out a better approach for this that wasn't as involved as the approach above, but still took some work. Have it in review now. I would say this definitely wasn't a 1 unless this is just the discovery ticket, but just wanted to mention it here

**Comment by BrittanyIRL** [comment]
🎉 Great job, Max, on this. I updated the ticket point estimate since the work is in review - we probably don't need further tickets on this.

**Comment by maxyinger** [comment]
Is this considered a bug? feels a lot like an enhancement

**Comment by BrittanyIRL** [comment]
> Is this considered a bug? feels a lot like an enhancement

Great question, feels like an enhancement to me too. @bmattb , @samitron7 ?

**Comment by csossi** [comment]
Verified in QA
