### ISSUE TITLE
Unable to scroll over web story embed on mobile

### ISSUE THREAD

**Issue by Kunal-Parihar** [GoogleForCreators/web-stories-wp#4973]
## Bug Description

When you embed a web story in a post and scroll the embedded story then you are unable to scroll through. This happens on mobile because there you are using hands/fingers to scroll and somehow the web story embed doesn't let you scroll. The screen doesn't respond. Then you have to find an area out of the embed region to scroll further. On the desktop, this is not a problem because you are not interacting with your fingers there. You are using a mouse to scroll, so no problem there.

## Expected Behaviour

One should be able to scroll over the story on mobile as well when interacted with the fingers.

## Steps to Reproduce

1. Create a Web Story
2. Create a WordPress post
3. Embed web story in the WordPress post using the web story block (using the web story plugin)
4. Load the post in the mobile
5. Scroll over the post
6. The post stops scrolling when you encounter the embedded web story

## Additional Context

- Plugin Version: 1.0.0
- Operating System: Windows 10 Pro
- Browser: Google Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by dreamofabear** [comment]
Thanks for the report. The tracking issue in story format: https://github.com/ampproject/amphtml/issues/28009

Closing as dupe of #4700 and #4977.

**Comment by swissspidy** [comment]
Duplicate of #4700
