### ISSUE TITLE
Add nicely styled default colors to "saved colors" by default

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#4976]
## Feature Description

When working on a new story, by default the color picker is overwhelming. 
![color picker.png](https://images.zenhubusercontent.com/5e98486db524b82fc96aeaf6/b02f2820-f8a4-4d52-bafa-50fed49a93c5)

We should make it easy to get started by having some nice colors pre-saved, so a user doesn't have to start from a choice of.. every hex out there. 

## Alternatives Considered

Could also just have a simpler color picker overall (similar to Google Docs) and hex input for custom selection, so the default color picker is much simpler than the existing one. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Closing since we have that now.

cc @agingoldseco / @gajasinski Feel free to reopen in case you feel like we should plan more changes for the color picker.
