### ISSUE TITLE
User reports not being able to scroll over an embedded web story on mobile

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#4977]
See report: https://wordpress.org/support/topic/some-serious-bugs/

And link for reference: https://kunalparihar.in/what-is-google-web-stories/

I've tested on my mobile and witnessed it happening. In essence, when the web story embed is covering the screen, if you swipe up/down it doesn't scroll the page/screen. That makes it so that the user has to leave the page/site in order to keep navigating. 

This is a P0 bug we should fix ASAP. @choumx @spacedmonkey @swissspidy FYI

**Comment by dreamofabear** [comment]
This is actually easily fixable by the publisher in the Gutenberg editor by changing the size/alignment of the story embed block. 

However, we should do two things to provide a more sensible default. The current default size is too wide for most mobile devices (I've seen a lot of unintentional horizontal truncation).

1. Change default static size 360x600 to 280x500.
2. Support a new "responsive sizing" mode that preserves 9:16 aspect-ratio with the `padding-bottom` trick (AMP also uses this for `layout=responsive`). 
    - Add this as an option to the "Story dimensions" settings section and make it the default (enabling it disables the static size text fields and vice versa).

**Comment by spacedmonkey** [comment]
Responsive sizing is handled in #3581 . If we have responsive embeds, why do have to change the size of the default block help here?

**Comment by spacedmonkey** [comment]
I am also unable to reproduce this on my iPhone. Maybe this is an android issue. 

As for default size, the values are spread across the codebase. [See](https://github.com/google/web-stories-wp/search?l=PHP&q=360). 

I think we can add a filter to make it easier for developers to change these values. Maybe adding a filter [here](https://github.com/google/web-stories-wp/blob/87048d9e224d82e015ef833bf0e28d3d7614b442/includes/Embed_Base.php#L91-L100).

WordPress also has the idea of [content_width](https://codex.wordpress.org/Content_Width). This is a variable defined in the theme, to define how wide the content area. An example this is from a popular WordPress core theme [twentyseventeen](https://github.com/WordPress/twentyseventeen/blob/fa09211f54799dd03e8acda9d19108aafb1a8c77/functions.php#L105-L122).  Should the default width me half of content_width. So 600 width would make default 300 width.

**Comment by swissspidy** [comment]
This is a known issue in amphtml upstream

**Comment by dreamofabear** [comment]
The format tracking issue: https://github.com/ampproject/amphtml/issues/28009

**Comment by spacedmonkey** [comment]
Once the fix is out, do we have to do anything on our end, like upload version number of player or does this happen automatically?

**Comment by swissspidy** [comment]
If it‘s fixed upstream we don‘t have to do anything on our end

**Comment by spacedmonkey** [comment]
So are their anything we can / should do on our end? If not, maybe close this ticket.

**Comment by swissspidy** [comment]
Moved it out of the sprint backlog as it's blocked. No further action needed.

**Comment by dreamofabear** [comment]
Fixed upstream in https://github.com/ampproject/amphtml/pull/31051 which should roll out early December.

**Comment by swissspidy** [comment]
^ FYI @ernee @LuckynaSan
