### ISSUE TITLE
Bug: Horizontal Padding on Text Highlight only Applies to First Line

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#4980]
## Bug Description

~Can we add default padding of 8px H and 4px V for highlight (with line height 1.2).~
Also, this does seem like a bug but note that the horizontal padding only applies to first line.

![68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3565396463366533343735346664613963636432366538362f35383430353163342d313031662d343262312d393136632d643865363932613632323136](https://user-images.githubusercontent.com/58738530/96754372-367fb900-139f-11eb-8809-321d2df46422.png)

## Expected Behaviour

Text bg hilite should look like this:
![Screen Shot 2021-01-11 at 9.01.26 AM.png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/4ed53a3d-0fba-4a02-849f-f26ae8890887)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by samitron7** [comment]
Same comment from[ #4972 ](https://github.com/google/web-stories-wp/issues/4972)
When a user applies a text fill (regardless where it's fill or hilight), the result should look good. To do this we need to add additional padding before the scene that the user does not see in the padding input field:

**Adding text fill:**
![Group 5719](https://user-images.githubusercontent.com/10889431/102396225-fef14f80-3f90-11eb-85e1-2e11267b06cb.png)

**Adding text hilite:**
![Group 5718](https://user-images.githubusercontent.com/10889431/102396743-bb4b1580-3f91-11eb-8d92-d62b504b8a4a.png)

**Comment by BrittanyIRL** [comment]
Bumping this to 5 points because there could be some extra effort in here re how the editor perceives this should be handled.

**Comment by maxyinger** [comment]
I think this ticket is two separate tickets:

> Can we add default padding of 6px H and 2px V for highlight. 

This is an enhancement and was able to come up with a solution for hidden padding for both bg fill and bg highlight in [this PR](https://github.com/google/web-stories-wp/pull/5839), so this part is in review. Also just to clarify, is the hidden padding supposed to be 6x2 or 6x4?

> Also, this does seem like a bug but note that the horizontal padding only applies to first line.

This is a bug I can look into today. We can use this ticket to track this bug,

**Comment by BrittanyIRL** [comment]
Thank you for clarifying what's going on with this ticket. I'm glad all the hidden padding tickets came up together, the descriptions on them have definitely been a little hard to suss out the differences (at least to me!).

**Comment by maxyinger** [comment]
Looks like maybe at the time of the screenshot we were using `box-decoration-break: slice;` but I'm unable to reproduce and looks like we've updated to using `box-decoration-break: clone;` everywhere needed.

https://developer.mozilla.org/en-US/docs/Web/CSS/box-decoration-break

Seems to be working now tho!
![Screen Shot 2021-01-08 at 10.36.52 AM.png](https://images.zenhubusercontent.com/5ea0a3e2f739259b2b0b092a/54e2bcc0-1f4e-4fe0-aab3-2fc012fb5a0b)

**Comment by csossi** [comment]
Which PR am I testing here, @littlemilkstudio ?

**Comment by swissspidy** [comment]
@csossi #5839 I think

**Comment by maxyinger** [comment]
@csossi sorry for the confusion on this one for you. I believe you already tested 5839 which included this part of the ticket:

> Can we add default padding of 6px H and 2px V for highlight.

You don't need to test that the hidden padding was there since it was already taken care of and went through the QA process.

However this ticket has a separate bug task in it:

> Also, this does seem like a bug but note that the horizontal padding only applies to first line.

That I believe has already been fixed, and I just wanted to go through QA to verify. So I just wanted you to check that when you apply padding on highlighted text it applies to all lines and not just the first. I'll update the ticket title to reflect this. Thanks!

**Comment by csossi** [comment]
Verified in QA
