### ISSUE TITLE
Allow developers modify default attributes on embed block

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#4982]
## Feature Description

Add a filters to enable developers to modify default height / width of a emblocks block / shortcodes. This will help improve styling and theme integrations. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

- Add a filter in the [default_attrs](https://github.com/google/web-stories-wp/blob/87048d9e224d82e015ef833bf0e28d3d7614b442/includes/Embed_Base.php#L84-L100) method. 
- Change [default params](https://github.com/google/web-stories-wp/blob/87048d9e224d82e015ef833bf0e28d3d7614b442/includes/Block/Embed_Block.php#L75-L97) on block. 
- Remove defaults [here](https://github.com/google/web-stories-wp/blob/main/assets/src/story-embed-block/block/block.json#L16-L20).
- Pass defaults to through in block [settings](https://github.com/google/web-stories-wp/blob/87048d9e224d82e015ef833bf0e28d3d7614b442/includes/Block/Embed_Block.php#L112-L116).

**Comment by swissspidy** [comment]
Curious about the context, was there any user/dev feedback about this?
