### ISSUE TITLE
Preload REST API calls

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#499]
## Feature Description
Currently when the editor loads, it calls the REST API to get data. 

<img width="606" alt="Screenshot 2020-03-06 at 13 44 26" src="https://user-images.githubusercontent.com/237508/76088887-b2fc8d80-5fb0-11ea-8368-570738339d8c.png">

These calls are 
- Load media ( Video and images ) for library.
- Load post ( story ) from editor. 
- Load list of fonts to display fonts. 

When the documents panel is active, two more calls are made. 

<img width="217" alt="Screenshot 2020-03-06 at 13 47 12" src="https://user-images.githubusercontent.com/237508/76089307-4f269480-5fb1-11ea-8c04-e40971313a24.png">

These calls are 
- Load a list of Post statuses,
- Load of list of users. 

We currently load from data into the editor via config which is a [js variable](https://github.com/google/web-stories-wp/blob/c29f388b8135b9b20e061d036c01222f8fa10cbb/includes/Story_Post_Type.php#L301-L323) on the page. This could be expanded to include some or all data listed above. 

Or we could use `rest_preload_api_request`, which preloads from REST API [before the editor](https://github.com/WordPress/wordpress-develop/blob/437ac63d7652b08095dc7f77b6ba4ef52db44dbb/src/wp-admin/edit-form-blocks.php#L41-L87) is loaded. 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
- What data should be preloaded 
- How should it be preloaded

**Comment by swissspidy** [comment]
Need to identify which parts we'd like to preload.

For example, fonts API will be made obsolete in #1348

Media & the current story seem like a good start.
