### ISSUE TITLE
Remove safe zone marker and icon

### ISSUE THREAD

**Issue by samitron7** [GoogleForCreators/web-stories-wp#4995]
The safe zone tick mark was a temporary solution implemented for Stable. Now that we have the design safe zone in the editor, we can remove the tick marks and the safe zone icon at the bottom right of the workspace.

**Comment by samitron7** [comment]
This is possibly a 5min task. The new design safe zone should address all safe zone needs and is now in conflict with the tick marks (which was quickly implemented as a stop gap). Can we add this to the next sprint.

**Comment by bmattb** [comment]
@samitron7 this is in queue now

**Comment by csossi** [comment]
Verified in QA

**Comment by samitron7** [comment]
Verified in UAT
