### ISSUE TITLE
Design panel menu - stateful and behavior

### ISSUE THREAD

**Issue by samitron7** [GoogleForCreators/web-stories-wp#4996]
I have mapped out several use cases for menu behavior in the design panel:

**DEFAULTS**
Default expand style panels for newly added text and shape element since the natural progression is to change the element's style
1. I add text to the page. The **Style** section is defaulted open.
2. I add a shape to the page. Similarly, the **Style** section is defaulted open. 

**STATEFUL**
If a user expands a section in the design panel, it should remain expanded until the users explicitly closes it.
1. I add text to the page. I expand the **Layer** and Link **panel**
2. I add another text element to the page.
3. Style section is defaulted open while **Layer** and **Link** panels should remain open
4. I close the Link panel.
5. I add a shape element to the page. 
6. Style section is defaulted open while **Layer** panel should remain open

**DEFAULT TAKES PRECEDENCE OVER STATEFUL**
1. I add text to the page. The Style section is defaulted open. 
2. I collapsed the Style section
3. I add another text box to the page.
4. The **Style** section is defaulted open.

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@barklund @bmattb FYI Pulling this into sprint 41.

**Comment by csossi** [comment]
Verified in QA

**Comment by samitron7** [comment]
Verified in UAT
