### ISSUE TITLE
Template page as zero state for new users

### ISSUE THREAD

**Issue by samitron7** [GoogleForCreators/web-stories-wp#4997]
## Feature Description

All new users should land on the template page. Currently we land user on the My Stories page.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
- If you have no stories on the dashboard, the first page you should see is explore templates when you load the dashboard. 
- If you have Stories in My stories the dashboard should behave as it has and you should land on My Stories when first loading the dashboard

**Comment by BrittanyIRL** [comment]
@csossi friendly ping on this, it's been waiting for qa for about 2 weeks now.

**Comment by csossi** [comment]
verified in QA
