### ISSUE TITLE
Clicking on one element in multi-selection does not select it

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#5]
## Bug Description

When multi-selection is active, then clicking on an element in that multi-selection does not select that element, the multi-selection stays as is was.

## Expected Behaviour

Clicking on a single element should select it, even if previously in multi-selection.

More details [from UX in deck](https://docs.google.com/presentation/d/1ZiZWrmLiX40rt3n_1LMSGJxYWI-xsWFsS9bkzdbRIV8/edit?ts=5ec3754c#slide=id.g77fdc779d5_0_94) and [Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=2625%3A6793)

## Steps to reproduce

1. Add two elements.
2. Select both.
3. Click on one of them
4. See nothing happening.

## Screenshots

![selecting](https://user-images.githubusercontent.com/3294597/72839236-33ca2900-3c92-11ea-8b60-d6cd05bde9e0.gif)

## Additional context

N/A

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
@miina is this still an issue?

**Comment by miina** [comment]
Yep, looks like it.

**Comment by jauyong** [comment]
Omar to review this with Sam. 
Scenarios to consider:

1.  Clicking in between elements
2.  Double clicking on an element
3. Single Clicking on a single element.

**Comment by o-fernandez** [comment]
Synced with Sam and agreed on general principles (following good design tool patterns):

- If the user just clicks, then it should select the individual element the user clicked. 
- If the user clicks within the selection and drags, then it drags the whole selection (multiple elements). 

Applying that to the various scenarios above: 

> Clicking in between elements

By this logic, this is the same as "clicking on a single element" the element being the background. So it should deselect the selection and select the background. 

> Single Clicking on a single element.

Selects that specific element.

> Double clicking on an element

Same as double clicking on a single element if there is no pre-selection of multiple items. 

Click and drag (anywhere within the selection) will drag all elements around.

**Comment by miina** [comment]
FI: There's another related issue which will get fixed here, too, with reworking the multi-selection events -- selecting a few elements with `Shift` and then trying to select additional element which happens to stay in the middle of the selection box (but unselected) is currently not possible:
![multiselection](https://user-images.githubusercontent.com/3294597/82059405-472c5480-96c6-11ea-81b5-bb5df393e762.gif)

**Comment by csossi** [comment]
Verified in QA
