### ISSUE TITLE
Implement multi-resolution/aspect ratio preview

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#50]
## Feature description

As an author I want to be able to preview my story across multiple resolutions for a final check before publishing it.

**[Feature Brief - Epic:Document Workflow](https://docs.google.com/document/d/1GJZljicdXcP7oRdywsF3EGUaCVpCHsDrK2gUMubnrbk/edit?pli=1#heading=h.l4xkp1ba4nok)**

Use `#development=1` to the preview URL to use the format feature. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. Author is able to preview the entire story
2. When previewing a story, the preview opens a new tab or modal with the entire story as if it were published, with the ability to preview on multiple aspect ratios.
3. When previewing a story, it is a final testing mode, and needs to produce valid AMP. 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jauyong** [comment]
@pbakaus the brief says previewing a story is a "new tab or modal". Are we still considering modal?

**Comment by pbakaus** [comment]
good question, nope, it's new tab for now (for previewing entire stories). But I think we want to revisit a preview modal after launch.

**Comment by miina** [comment]
Probably should split out the issue for modal / Page preview.

**Comment by jauyong** [comment]
@pbakaus and @samitron7 to review preview functionality.

**Comment by pbakaus** [comment]
Split into two issues, other issue is now at https://github.com/google/web-stories-wp/issues/1163

**Comment by samitron7** [comment]
@pbakaus Is this the preview the same preview in 3 representative mobile aspect ratio? If yes, this should open inside the editor as a modal? Can you confirm so I can attach the figma flow.

**Comment by pbakaus** [comment]
@samitron7 that's correct.

**Comment by samitron7** [comment]
Figma flow [here](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=1009%3A192) but added comment to brief in regards to the the page view mode auto-closing when video/animations stops playing for @pbakaus

**Comment by o-fernandez** [comment]
I believe there are designs already, but they are new/updated from what was last added here, so adding back to the UX queue for review when it's closer to implementation (likely 1.2 or 1.3)

**Comment by samitron7** [comment]
@pbakaus @o-fernandez One thing that is needed here is the exact dimensions for the chrome browser ui for each aspect ratios. Everything in the mock are estimates.

**Comment by o-fernandez** [comment]
Note that the solution has been updated to... 
**Use `#development=1` to the preview URL to use the format feature.**

**Comment by swissspidy** [comment]
Reopening for UAT. Even though this didn't go through QA, it looks like the code reviewers did verify functionality.
