### ISSUE TITLE
3P Media: Use videos instead of gifs in library

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5006]
## Feature Description

This might have a positive impact on performance as otherwise loading tons of large GIFs in the library is quite a heavy task.

See #5005, #4885

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
@swissspidy is there remaining work here? I thought this was done.

**Comment by swissspidy** [comment]
@o-fernandez Thanks for the ping! Turns out I just duplicated this ticket here two days ago 🤦 

Yes, this is still an issue!

We use videos instead of GIFs on the frontend nowadays (good), but the images displayed in the 3P media library still use GIFs (bad). So if you search for a lot of GIFs on Tenor, that's gonna eat a lot of bandwidth.

**Comment by o-fernandez** [comment]
@swissspidy woah, TIL. OK, this is good to fix then. Will move to "ready for sprint" so it's picked up during triaging (hopefully), SG?

**Comment by BrittanyIRL** [comment]
@swissspidy @o-fernandez is this something you want pea pod to handle? I see the pod tag but this isn't something we have historically touched so i want to make sure.

**Comment by swissspidy** [comment]
> @swissspidy @o-fernandez is this something you want pea pod to handle? I see the pod tag but this isn't something we have historically touched so i want to make sure.

IIRC originally we said pea pod would take over media from the previous Sydney pod, hence the label.

**Comment by o-fernandez** [comment]
> > @swissspidy @o-fernandez is this something you want pea pod to handle? I see the pod tag but this isn't something we have historically touched so i want to make sure.
> 
> IIRC originally we said pea pod would take over media from the previous Sydney pod, hence the label.

Yeah, ideally Pea pod would take over media bugs, given that it's the largest pod, but please LMK if you have any concerns @BrittanyIRL. For now, I'd just look at tackling this based on team bandwidth.

**Comment by BrittanyIRL** [comment]
yeah, i'd just seen it linger here for a few sprints so i figure we might as well get this through!

**Comment by BrittanyIRL** [comment]
@csossi for QA on this, confirm that "gifs" in media library of editor play on hover or focus and are have no regression in usability. Swapping out media type behind the scenes.

**Comment by csossi** [comment]
Verified in QA
