### ISSUE TITLE
Fix react/no-array-index-key error in the dashboard

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#5017]
## Feature Description

Follow up from #4986. Now this linting rule is enabled, the dashboard team needs fix the warnings / errors generated by adding this linting rule. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
This was fixed in PR #5073
