### ISSUE TITLE
Dashboard: Author Embed Data is missing on duplication 

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#5020]
## Bug Description

- The user is unable to duplicate a story because the embedded author data is missing 

## Steps to Reproduce

1. Visit the dashboard
2. Duplicate a story with the dropdown
3. See that the story shows up

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
