### ISSUE TITLE
E2E Tests: Add some more percy snapshots for RTL

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#5021]
## Feature Description

Add some precy snapshots for editor and dashboard in RTL mode. 

We should see visual regressions on RTL. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
The editor karma tests has some snapshots for that already FWIW

**Comment by spacedmonkey** [comment]
I could only see one when I looked and it was only the editor. I think there should be a number of tests for this. We need dashboard, activation message and block.
