### ISSUE TITLE
Dashboard: Story renaming not possible

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5031]
## Bug Description

Renaming a story currently fails because the data format isn't as expected.

Updating a post should work like this:

```
curl -X POST https://example.com/wp-json/wp/v2/posts/<id> -d '{"title":"My New Title"}'
```

But the app currently sends a completely different object that looks like this:

```json
{
 "author": "Pascal",
 "title": { "raw": "My New Title" }
}
```

## Expected Behaviour

1. Renaming a story should be possible.

## Steps to Reproduce

1. Try to rename a story on the dashboard.

## Screenshots

![image](https://user-images.githubusercontent.com/841956/97366791-37857e80-18a8-11eb-99c0-19e3cbce3f8a.png)

## Additional Context

- Plugin Version: 1.1.0
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
