### ISSUE TITLE
Text: Changing font family wipes out text content and reverts back to newly added text box

### ISSUE THREAD

**Issue by samitron7** [GoogleForCreators/web-stories-wp#5035]
## Bug Description

Changing font family wipes out text content and reverts back to newly added text box

## Expected Behaviour

If I hi-lite a word in a sentence then change the font family, I expect for the font family for the word to change.

## Steps to Reproduce

1. Add Heading 1 text element
2. Type Hey. Hit enter then type hey again
3. Hi-lite the second "Hey"
4. Go to font picker and select any font family
5. Reverts back to heading 1 text element

## Screenshots
![text.gif](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/49da72ef-7140-4bd4-b211-d795e843a265)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Note that this even happens without step 3.

Not the best user experience for sure.

cc @o-fernandez 

----

@samitron7 FYI moving issues directly from "New Issues" to "Ready for Sprint" or another column without assigning pods etc. might result in the teams being unaware of the ticket. Best to leave it in "New Issues" so it can be triaged from there

**Comment by csossi** [comment]
Verified in QA

Font family changed in textbox and content remained
