### ISSUE TITLE
Snap guides have variable line width

### ISSUE THREAD

**Issue by samitron7** [GoogleForCreators/web-stories-wp#5037]
## Bug Description

Snap guides have variable line width. Some lines appear to be more than 1px thick.

![Group 5238.png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/6ddb4c00-67f8-44e0-8cdc-9d049a15bc96)

## Expected Behaviour

Snap guides should have the same line width (ie 1px).

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
@samitron7 - This is an expected response from the library, as the snapping line is displayed as such when the element boundary and the design guideline are snapped together and this is used to communicate that reality to the user. 

Can you provide some clarity around what your expectation is in this scenario? See the gif below!

![snapping_bold_guideline](https://user-images.githubusercontent.com/637548/98133847-17e3ec80-1e8c-11eb-99be-3a049a90dcdb.gif)
Observe how the "bold" guideline is used where the vertical line intersects with the two snapping elements and the thin guideline in between. Also, observe how the horizontal guideline (being a "page-wide" guideline and not an element-specific one) is "bold" all the way.

**Comment by zidianlyu** [comment]
May I have any update or clarification on this issue?

**Comment by samitron7** [comment]
@bmattb Let me throw this ticket back into UX Needed. There are some new visual design work on snap guides and it would be best to do all this work at once.
