### ISSUE TITLE
Document Panel - Metadata UI

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#504]
## Feature Description

#405 was for the functionality of the Metadata. This ticket is a placeholder for when designs are added to figma.

**[Design](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=5837%3A99)**

**[Feature Brief - Epic: Document Workflow](https://docs.google.com/document/d/1GJZljicdXcP7oRdywsF3EGUaCVpCHsDrK2gUMubnrbk/edit#heading=h.epbi26vaa94r)**

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by ndev1991** [comment]
@samitron7 Is there any update for UX this issue?
