### ISSUE TITLE
Page navigation not always working

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5041]
## Bug Description

Sometimes clicking on the pages in the carousel to change pages does not work, nothing happens. You'd have to click multiple times.

Quote: "every couple clicks one click simply doesn't register"

See https://xwp.slack.com/archives/CCCAUAH6F/p1603758103190400

Related: #5040

## Expected Behaviour

Page navigation should work reliably.

## Steps to Reproduce

Unclear how to reproduce this yet.

## Additional Context

- Plugin Version: 1.0.0
- Operating System: macOS
- Browser: Chrome 86

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
High priority, but it seems difficult for QA to reproduce.
