### ISSUE TITLE
E2E Tests: Story Actions on Dashboard

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#5043]
## Feature Description

To avoid regressions like #5020 and #5031 we should add e2e tests, as flagged by @swissspidy 

Let's add e2e tests for these actions

* Delete story
* Rename story
* Duplicate story

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Our pod can easily do that, moving back to ready for sprint
