### ISSUE TITLE
Dashboard Settings: Active Site Kit Configuration

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#5051]
## Feature Description

This relates to https://github.com/google/web-stories-wp/issues/3809 - creating separate ticket to not affect scope or resources necessary. 
We need a way to tell if Site Kit is active but the GA module is not. We have this set up in Analytics.php but this will call for the functionality to also exist in Dashboard.php, so we need to figure out a [good way to share that](https://github.com/google/web-stories-wp/issues/3809#issuecomment-718225004). 

Depending on if a user has permissions to configure site kit we should swap out the link that is given in the dashboard settings view re site kit. 

Reference https://github.com/google/web-stories-wp/issues/3809#issuecomment-718221119 for more context

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

**Determine whether Site Kit analytics module is active**

Re-use code from `Analytics` in a good way (TBD)

**Making the link to Site Kit dynamic depending on Site Kit plugin status**

pseudo code:

```php
// ...
$can_install = current_user_can( 'install_plugins' );
$can_activate => current_user_can( 'activate_plugin', 'google-site-kit/google-site-kit.php' );
$can_manage_site_kit = current_user_can( .... );
$is_analytics_active = // ....

$link = __( 'https://wordpress.org/plugins/google-site-kit/', 'web-stories' )

if ( $is_active && can_manage_site_kit ) {
	$link = 'link to Site Kit settings so user can connect analytics';
} else if ( $is_active ) {
	$link = 'link to Site Kit dashboard or site kit website/docs ';
} else if ( $is_installed ) {
    $link = 'link to analytics module in site kit settings';
}

```

**E2E Tests**

Covered by #4461

**Comment by swissspidy** [comment]
Copying @spacedmonkey's thoughts from https://github.com/google/web-stories-wp/pull/5049#discussion_r515009007:

> Two options on sharing code.
> 
> 1. Move the `is_site_kit_analytics_module_active` and `get_site_kit_active_modules_option` to a trait. Both analytics and dashboard could use this trail.
> 2. Pass an Analytics object into the dashboard constructor, make the above methods public.
>
> I think option 1, is cleaner personally, as it seems like that other part of the code base will have sitekit intergrations at some point. The method is_site_kit_plugin_installed could be trait for example.

**Comment by swissspidy** [comment]
Added some info in the IB section to describe what's needed.

-----

I don't think option 2) above makes sense. The Analytics class serves a very different purpose: printing analytics on the frontend.

So the option 1) makes more sense.

However, I'd like to propose a third option:

Creating a new class that deals with this. For example a class named `Google\Web_Stories\Integrations\Site_Kit` with a public method like this.

* `get_plugin_status()`

That class would also:

* Filter `googlesitekit_amp_gtag_opt` (like `Analytics` currently does)
* Call `remove_action( 'web_stories_print_analytics', [ $analytics_instance, 'print_analytics_tag' ] );`

We could have more integration classes in the future:

* `Google\Web_Stories\Integrations\AMP` - for filtering all the AMP things `Story_Post_Type` currently does
* `Google\Web_Stories\Integrations\Jetpack` - for filtering `wpcom_sitemap_post_types`/`jetpack_sitemap_post_types` like `Story_Post_Type` currently does
