### ISSUE TITLE
Embed block cut off when centered

### ISSUE THREAD

**Issue by DanielCryptoK** [GoogleForCreators/web-stories-wp#5053]
When ever I click on next or previous it sends my screen shooting down to the bottom of the page where it is blank. This is very annoying as have to move back up the page each time I change pages.

Also when I embed a story and change it to show in the center of a page, half of the story is missing. When embed to the left the story shows as it should.
![BitStarz Casino Promos, Reviews   Ratings - Bitstarz com](https://user-images.githubusercontent.com/45933242/97512224-938cf780-19bb-11eb-862b-5e27eb80e59d.png)

**Comment by swissspidy** [comment]
Just to confirm, both these issues are related to the embed block?

Note that we've moved support for the Web Stories plugin to the [WordPress.org support forums.](https://wordpress.org/support/plugin/web-stories/)

Could you perhaps open a [new topic](https://wordpress.org/support/plugin/web-stories/#new-post) there and share as much details as possible there? Ideally with your Site Health information or at very least the name of your theme, and the URL to the affected post/story.

Also try common debugging stels like temporarily disabling other plugins and using a different theme to see if the issue goes away.

**Comment by DanielCryptoK** [comment]
No, when it
![Edit Story ‹ Bitcoin Casino No Deposit Bonus — WordPress](https://user-images.githubusercontent.com/45933242/97516210-35fda880-19c5-11eb-9718-5bd982bba9d2.png)
 sends my screen shooting down to the bottom of the page where it is blank that is when editing the story

**Comment by swissspidy** [comment]
Thanks for the clarification! This has come up before in #4517. I've opened #5077 to fix this for our next release. Please follow that ticket for any updates if interested.

As for your other issue with the embed block, I'll see if we can fix this on our end, but it looks like a theme issue.

You can add the following to the "Custom CSS" section in the customizer to work around the issue:

```css
.web-stories-embed.aligncenter {
	text-align: initial;
}
```

**Comment by DanielCryptoK** [comment]
Also the side black menu makes it very hard to see there is a menu. A light grey or other color would much improve user experience.

**Comment by DanielCryptoK** [comment]
I forgot to say that by limiting heartbeat in wordpress greatly improved loading speed when editing so if you can make any changes to improve that side it would help the performance of the plugin. I had to install another plugin to stop heartbeat when editing.

**Comment by swissspidy** [comment]
> Also the side black menu makes it very hard to see there is a menu. A light grey or other color would much improve user experience.

Are you referring to the tabs above the media library? Or the Design / Document tabs?

> I forgot to say that by limiting heartbeat in wordpress greatly improved loading speed when editing so if you can make any changes to improve that side it would help the performance of the plugin. I had to install another plugin to stop heartbeat when editing.

The plugin does not use heartbeat in any way. But WordPress itself does, for example to check whether you are still logged in. There's nothing we can really do about that.

**Comment by DanielCryptoK** [comment]
SEE ATTACHED
![Uploading Edit Story ‹ Bitcoin Casino No Deposit Bonus — WordPress (1).png…]()

**Comment by swissspidy** [comment]
I think you've submitted the comment too early while it was still uploading. Could you try again?

**Comment by DanielCryptoK** [comment]
![Edit Story ‹ Bitcoin Casino No Deposit Bonus — WordPress (1)](https://user-images.githubusercontent.com/45933242/97725025-41a1ba00-1b00-11eb-953c-fa7956c5c050.png)

**Comment by swissspidy** [comment]
Ah, you are referring to the scrollbar. Agreed that this is hard to see! I'll open a ticket for improving this.

**Comment by DanielCryptoK** [comment]
Why can I not add the attached picture as optional brand icon in editor. I get the following message

Bitcoin Casino US logo.jpg
Post-processing of the image failed likely because the server is busy or does not have enough resources. Uploading a smaller image may help. Suggested maximum size is 2500 pixels.
![Bitcoin Casino US logo](https://user-images.githubusercontent.com/45933242/97770268-47c98200-1b64-11eb-9ba2-8bf74cf74ba9.jpg)

**Comment by DanielCryptoK** [comment]
Also there are problems with the loading of authors.
![Edit Story ‹ Bitcoin Casino No Deposit Bonus — WordPress (2)](https://user-images.githubusercontent.com/45933242/97770900-118f0100-1b6a-11eb-8482-3d4db710bc89.png)

**Comment by DanielCryptoK** [comment]
It works but there is a very long time delay to show the results of authors to choose from

**Comment by swissspidy** [comment]
> Why can I not add the attached picture as optional brand icon in editor. I get the following message

It's difficult to say what the issue is with the image, because the error message is coming directly from WordPress and there might be other plugins interfering with it, or it is simply a server configuration issue.

If this happens with all images, please open a new thread in the [WordPress.org support forums](https://wordpress.org/support/plugin/web-stories/) (where we handle support) and provide as much information as possible, including your Site Health info.

> Also there are problems with the loading of authors.

Thanks, we're aware of this and already working on addressing this in #4749.

**Comment by DanielCryptoK** [comment]
The user experience of changing the order of the pages needs to be improved.

**Comment by swissspidy** [comment]
Thanks, I'll happily pass this on. There's some work underway in this area already, so I am pretty sure this is already a known area of improvement.

For further suggestions, I recommend opening new issues - one per suggestion.

Thanks again
