### ISSUE TITLE
Update dashboard side nav to new designs

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#5054]
## Description 
Update side nav to new design specs 

![Screen Shot 2021-01-15 at 10 01 17 AM](https://user-images.githubusercontent.com/10720454/104756141-a55b7c80-5718-11eb-9bca-e2fb5be43b01.png)

https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=467%3A13745

## Implementation Details 
- Try to use the design system (DS) components as much as possible. If something isn't in the DS yet, start a conversation about if it should be (if it's reused or not one off). Everything needed that is reusable should already be in the DS. You can see what is available by spinning up storybook and going to the design system section. 

## Acceptance Criteria 
- Nav should be collapsable for smaller view ports as it currently is.
- All functionality should be maintained. 
- Nav u should be responsive. 
- Nav should be keyboard accessible
- Nav should be SR accessible 
- Nav should maintain specs if `isRTL` config in wordPress is true

**Comment by BrittanyIRL** [comment]
@samitron7 I wanted to check with you - the figma specs use "settings" to title the stories settings, in some spots right now we've made the distinction of "editor settings" to separate them from wordPress. Wanted to make sure that the text used in Figma for the nav is accurate. 

https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=467%3A13745

**Comment by csossi** [comment]
Getting a blank Dashboard when trying to test #5940 

![image](https://user-images.githubusercontent.com/16945664/106849826-69fdff00-6681-11eb-9cfc-653d5015b6ed.png)

**Comment by swissspidy** [comment]
Confirmed:

<img width="517" alt="Screenshot 2021-02-04 at 10 03 26" src="https://user-images.githubusercontent.com/841956/106869443-3d250880-66d0-11eb-80b4-aa2dce6b00ff.png">

**Comment by swissspidy** [comment]
@csossi I just synched the PR with latest changes from `main` and it's now working again as expected. PTAL!

**Comment by csossi** [comment]
Verified in QA
