### ISSUE TITLE
GIF element guidelines are not always presented

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5056]
## Bug Description

When inserting a Tenor GIF on the canvas and move it around, I don't always see the snap guidelines.

#1979 is related, but this also happens after dragging is done.

## Expected Behaviour

Snap guidelines should be shown reliably for GIFs.

## Steps to Reproduce

1. Insert GIF element
1. Drag it around
1. See absent guidelines

## Additional Context

- Plugin Version: 1.1.0
- Operating System: macOS
- Browser: Chrome 86

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
We need to be able to reproduce this consistently.

**Comment by bmattb** [comment]
This is now acknowledged as a valid bug. :)

**Comment by miina** [comment]
@barklund @bmattb @swissspidy I haven't been able to reproduce this bug.
Thinking of moving on to something else and fixing it when I happen to see it -- or if one of you notices it again and could get the base64 of the story for trying to reproduce it in the same conditions. Thoughts? Has any of you seen the bug recently?

**Comment by swissspidy** [comment]
It was pretty obvious before, but now I can't reproduce it anymore.

Let's close it for now.
