### ISSUE TITLE
GIFs not animated while dragging onto canvas

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5057]
## Bug Description

When dragging a Tenor GIF onto the canvas, the GIF is not animated.

Possibly related: #1930, #1979, #5006

## Expected Behaviour

GIF should stay animated while dragging.

## Steps to Reproduce

1. Drag GIF from Tenor 3P Media tab onto canvas
1. Notice it isn't animated anymore

## Additional Context

- Plugin Version: 1.1.0
- Operating System: macOS
- Browser: Chrome 86

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
Need to change from native D&D to movable so that the animation can occur during the drag process

**Comment by miina** [comment]
Assigning 1 SP to this since it should get fixed by #5335 but we should still track it and test it.

**Comment by csossi** [comment]
Verified in QA

**Comment by tmagalhaes-huge** [comment]
Looks good.
