### ISSUE TITLE
Admin Menu should not be collapsed on dashboard

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5058]
## Bug Description

For the editor we collapse the admin menu to have more space.

On the dashboard that's not really needed though, and causes [frustrations with users](https://wordpress.org/support/topic/cloudflare-waf-block-json-issues/#post-13596283) as it's an unexpected change.

## Expected Behaviour

Admin menu should not be collapsed on dashboard

## Steps to Reproduce

1. Open dashboard

## Additional Context

- Plugin Version: 1.1.0
- Operating System: macOS
- Browser: Chrome 86

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
@o-fernandez WDYT about this?

**Comment by o-fernandez** [comment]
Makes sense to only collapse when in the editor, not in dashboard/etc. Would be great to tackle.

**Comment by csossi** [comment]
Verified in QA
