### ISSUE TITLE
Code Quality: Refactor Story_Post_Type class

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5062]

**Comment by spacedmonkey** [comment]
The `Story_Post_Type` class is extremely long. I recommend the method in it's class should be broken up into multiple classes. 

I recommend the following methods to be moved.

### Capabilities
This class would be in charge of managing capabilities, adding / removing. 
- `add_caps_to_roles`
- `remove_caps_from_roles`

### Editor
This class would be in charge of rendering the web stories editor, including rendering PHP, script tags and post locking. 
- `replace_editor`
- `filter_use_block_editor_for_post_type`
- `admin_enqueue_scripts`
- `get_editor_settings`
- `setup_lock`

### FileTypes
This class would be in change of adding removing file types to allow lists. I would also think about merge this class with the Types trait. 
- `filter_list_of_allowed_filetypes`

### StoryRender
This class would be in charge of highjacking the normal rendering with our own. Note, a better name should be found. 
- `embed_image`
- `embed_image`

**Comment by swissspidy** [comment]
> This class would be in change of adding removing file types to allow lists. I would also think about merge this class with the Types trait.

+1 on using a proper class instead of a trait. Maybe it could be merged with the `Media` class instead?

> This class would be in charge of highjacking the normal rendering with our own. Note, a better name should be found.

Should this also include the `filter_template_include` method (hijacks rendering of single stories)

**Comment by spacedmonkey** [comment]
In https://github.com/google/web-stories-wp/pull/6964 there is also an new method for hijacking rendering that would make sense in a `StoryRender` class.
