### ISSUE TITLE
Code Quality: Refactor Link_Controller class

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5064]
`\Google\Web_Stories\REST_API\Link_Controller::parse_link()` has high complexity and could be refactored

**Comment by spacedmonkey** [comment]
This chunk could be converted to be array and a loop 
https://github.com/google/web-stories-wp/blob/c8df85e53ba824bb22e9a7ad05817eac48adee1f/includes/REST_API/Link_Controller.php#L188-L220

Also some repeated code from this class and the embed class, could be moved to a abstract class / trait.

**Comment by swissspidy** [comment]
Both these classes use a `Document_Parser` trait. I think that can be easily turned into a class, with some public methods to get the document title, site icon, and a representative image.

Also, the `html_to_xpath()` method is superfluous too and can be replaced by using `$document = Google\Web_Stories_Dependencies\AmpProject\Dom\Document::fromHtml( $markup )`
