### ISSUE TITLE
SVG Support Design Doc

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5070]
## Task Description

Create a design document re: SVG upload in WordPress Media Library

In order to properly solution #798 we need to understand clearly the issue and impact of proposed solutions. Please prepare a document which clearly outlines the following:

1. Core problem
2. Potential solutions w/ Pros & cons
3. Proposal

Please present this document to the team in the #google-design-review slack channel

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
While doing some research into the ticket, I found this [plugin](https://wordpress.org/plugins/svg-support/). ( Recommended by WP Engine's docs ). 

This answered / solved a number of the problems with SVG uploads for me. 

1. Getting height and width of image. 
1. Checking for scripts tags. 
1. Handling difference between image/svg and image/svg+xml files. 

To that end, to make sure I am was on the right track, I created https://github.com/google/web-stories-wp/pull/5103 . 

I am not sure this doc is required, through I can write it up, if required.

**Comment by swissspidy** [comment]
Thanks Jonny, that looks pretty promisiing 👍 🎉 💪   Thanks for the write-up!

I also came across https://wordpress.org/plugins/safe-svg/ which is similar but simpler and seems to have a better take at sanitizing bad SVGs (using https://github.com/darylldoyle/svg-sanitizer) and supporting gzipped svgs (svgz). It also seems to cover a few edge cases like skipping attachment metadata regeneration

While #5103 and also that other plugin are quite comprehensible, it would be good if you could write everything up. Basically expanding on the `Relevant Technical Choices` section from #5103

**Comment by swissspidy** [comment]
One thing to mention in this design brief: how this could work on WordPress.com - there probably should be a filter to simply disable svg support

**Comment by spacedmonkey** [comment]
As discussed in meeting, I think this feature should have a setting to disable it by the user as well as having a filter for developers / hosts.

**Comment by spacedmonkey** [comment]
I have created a doc for your review - https://docs.google.com/document/d/1WhI9uMkmFNVHB1QHCsLokP2sMiUqKYGd5n_lYCQ5ulM/edit?usp=sharing

**Comment by swissspidy** [comment]
Left a few comments, otherwise looks good 👍 Will share this on the overarching SVG support ticket #789
