### ISSUE TITLE
UI difficulties when admin menu is long

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5076]
## Bug Description

Splitting this out from #4517

There are issues when the admin menu excessively long (e.g. when lots of plugins are active)

## Expected Behaviour

The editor should be usable even if the admin menu is excessively long or sometimes also when the screen is smaller

## Steps to Reproduce

1. Install many plugins to make admin menu super long **or** just make your window smaller
1. Observe behavior

## Screenshots

<img width="1432" alt="Screen Shot 2020-10-05 at 11 02 54 AM" src="https://user-images.githubusercontent.com/841956/95097995-6b003d80-072e-11eb-88e3-5449dd872f2a.png">

## Additional Context

- Plugin Version: 1.1.0
- Operating System: macOS
- Browser: Chrome 86

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by felipebochehin87** [comment]
@mwritter @sblinde @swissspidy please let me ask you, I still see this issue, but only when the window is reeeeally small, like on the screenshot below. Is this OK (given that the window is too small) or is this something that we need to fix? If that's ok, we can approve this PR.

![11506.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/0dfc9cfa-6bb4-4941-aa71-0d4b85a91804)
