### ISSUE TITLE
PageSpeed Insights flagging suboptimal image sizes

### ISSUE THREAD

**Issue by prakash4mail** [GoogleForCreators/web-stories-wp#5080]
Web Stories AMP version: Page Speed insights flags image sizes.
Need image size option(thumbnail/medium/) & cropping option when insert.
Request is as plain as it is.

**Comment by swissspidy** [comment]
Hi there,

Could you perhaps share a URL to your story?

**Comment by prakash4mail** [comment]
> Hi there,
> 
> Could you perhaps share a URL to your story?

https://developers.google.com/speed/pagespeed/insights/?url=https://biggbossfans.in/web-stories/s14-ep19-next-captain/
Properly size images  :: 2.85 s

**Comment by prakash4mail** [comment]
@swissspidy any further updates on this ?

**Comment by swissspidy** [comment]
Apologies, I seem to have missed your previous comment.

Thanks for sharing!

The Web Stories plugin already utilizes multiple image sizes to improve image loading. It looks though that we might be able to register some additional image sizes to further improve this under certain conditions.

In the meantime I suggest following the advice to compress your images or even automatically convert them to webp as that should be the first thing to improve.

Thanks again for your help.

**Comment by prakash4mail** [comment]
What i'm saying is there is no option in web stories to select image size like thumbnail or medium etc.. by default it is linking & showing the original big size. Just for this plugin sake we cannot bring down the size/dimensions of original image. This plugin must adopt to the WordPress standards of providing option to insert the correct image size.
Please look from this perspective, im sure im making a valid point & which is also crucial too (especially mobile devices)

**Comment by swissspidy** [comment]
I see your point. Ideally the plugin should be making the correct choices and pick the image sizes. You as a user should not have to worry about it, which is why adding an option would put an unnecessary burden on your shoulders. So all I am saying is that we'll have to look into improving this where necessary
