### ISSUE TITLE
AMP Sanitization breaks gradients (again)

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5081]
## Bug Description

This is essentially #4529, but now the other way around:

When _not_ using the AMP plugin, gradients will be stripped on the frontend.

The reason is a bug in PHP-CSS-Parser, which the AMP plugin solves by patching the package.

Since we cannot just let the AMP plugin deal with the patches because of https://github.com/cweagans/composer-patches/issues/315, we copied all the patches to our repo.

However, the `patches` section was accidentally omitted.

But even with that set I'm currently getting issues with patches not applying cleanly.

So this needs some investigation.

## Expected Behaviour

PHP-CSS-Parser patches should be applied cleanly.

## Steps to Reproduce

1. Apply gradient to element
1. Notice that gradient disappears on frontend.

Workaround: install AMP plugin.

## Additional Context

- Plugin Version: 1.1.0
- Operating System: macOS
- Browser: Chrome 86

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA

FE - radial and liner:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/8c57201d-0659-4984-b3f6-375efc190686)

**Comment by o-fernandez** [comment]
I see beautiful gradients! ![image.png](https://images.zenhubusercontent.com/5e98486db524b82fc96aeaf6/e582441d-3667-4074-867a-9c1ccbe435e1)
