### ISSUE TITLE
Composer 2 Support

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5083]
## Task Description

This is currently blocked as some dependencies need to be updated first.

https://github.com/civicrm/composer-downloads-plugin/pull/1
https://github.com/ampproject/amp-wp/issues/5551

**Comment by seamuslee001** [comment]
Just FYI civicrm/composer-downloads-plugin now has a new version 3.0.0 which includes that PR mentioned

**Comment by seamuslee001** [comment]
just FYI i found a small php issue and fixed it so have pushed up 3.0.1 which should be used

**Comment by spacedmonkey** [comment]
Current issues.
```
  Problem 1
    - cweagans/composer-patches is locked to version 1.6.7 and an update of this package was not requested.
    - cweagans/composer-patches 1.6.7 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 2
    - cweagans/composer-patches 1.6.7 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - ampproject/amp-wp 2.0.5 requires cweagans/composer-patches 1.6.7 -> satisfiable by cweagans/composer-patches[1.6.7].
    - ampproject/amp-wp is locked to version 2.0.5 and an update of this package was not requested.
```

**Comment by swissspidy** [comment]
Once AMP plugin 2.0.6 is out this should all go away as we can then safely update all dependencies.

**Comment by pierlon** [comment]
AMP plugin [2.0.6](https://github.com/ampproject/amp-wp/releases/tag/2.0.6) is now out :tada:.

**Comment by swissspidy** [comment]
Moving back to backlog since AMP 2.0.7 reverted this due to compat issues
