### ISSUE TITLE
Date: Issues with certain date / time formats

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5089]
## Bug Description

As reported in #5087 and #5050, there seem to be issues with certain date format and time format settings. Depending on the configuration in WordPress, our date package cannot transform the format and causes an error, crashing the document panel.

While we don't yet know all formats are causing this, there's definitely a need to make `convertFormatString()`  / `format()` more robust. 

One of the formats was `G \h h \m\i\n`

## Expected Behaviour

Document panel should not crash on unexpected formats.

Date library should be more robust

## Steps to Reproduce

Use a date format like `G \h h \m\i\n` to crash the editor.

Add & run tests

## Additional Context

- Plugin Version: 1.1.0
- Operating System: macOS
- Browser: Chrome 86

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA

**Comment by o-fernandez** [comment]
Tested already by Brittany, Pascal and Claudio, so closing out. No additional UAT performed.
