### ISSUE TITLE
Layer re-ordering

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#51]
## Feature description

Controls that allows moving blocks backwards and forwards (e.g. behind another block or bring on top of another block). Implemented in sidebar and dedicated layer panel.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by barklund** [comment]
Only panel refactor has been completed - still needs actual layer panel.

**Comment by pbakaus** [comment]
@barklund this seems done except for the keyboard shortcuts, right?

**Comment by barklund** [comment]
> @barklund this seems done except for the keyboard shortcuts, right?

Yes, and keyboard shortcuts were actually added in #320, also merged.
