### ISSUE TITLE
Editor: Provide featured media details via API

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5105]
## Feature Description

As per #5072 / #4910, we need to expose the following information in the REST API:

* Featured image width
* Featured image height

**Suggestion:**

Use `?_embed=wp:featuredmedia` for REST API requests, so that the media information is embedded in the response.

The size information can then be access via `_embedded['wp:featuredmedia'].media_details.width`/`_embedded['wp:featuredmedia'].media_details.height`

To do that:

* Set `$_GET['_embed'] = 1` in `edit-story.php`
* Update `$preload_paths` in `edit-story.php` to use `?_embed=wp:featuredmedia`
* Update `getStoryById` callback in `apiProvider.js` to pass `_embed`
* Update `useLoadStory` to extract size information from response and process accordingly

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by embarks** [comment]
@swissspidy will we need a similar check for the publisher logo size or we just going to prevent that? That fell under [critical metadata](https://app.zenhub.com/workspaces/web-stories-5e94d3aced449034e1e9b226/issues/google/web-stories-wp/4910), as well.

**Comment by swissspidy** [comment]
@embarks Ah yes, good point. Since publisher logos are quite different this would warrant its own ticket. But I agree that it should just be prevent in the first place. We already do that on the dashboard, so we should do the same in the editor. Will open a ticket.

**Comment by swissspidy** [comment]
Opened #5107 for this

**Comment by swissspidy** [comment]
@embarks featured media dimensions are now available in the editor, FYI
