### ISSUE TITLE
Feature Request to Add User Roles Settings

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#5106]
## Feature Description
This ticket is to track a possible enhancement to add a setting in the Web Stories plugin which offers control over user roles and capabilities for Stories.

## Alternatives Considered

Users can use plugins like this: https://wordpress.org/plugins/members/ to change which user roles can edit stories. 

## Related topic

https://github.com/google/web-stories-wp/issues/4102
https://wordpress.org/support/topic/rights-and-visibility-per-roles/

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Closing for now as this is out of scope for this plugin. Other plugins are better suited for this job.
