### ISSUE TITLE
Update Presets in Text Panel to reflect fractional sizes in spec

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#5109]
## Feature Description

When we implemented text presets in the text panel, we didn't accept fractional text sizes so we rounded up. Now that we accept fractional text sizes, revisit per the spec: https://github.com/google/web-stories-wp/issues/3639#issuecomment-680287737

![image](https://user-images.githubusercontent.com/13389997/97925933-3d5be380-1d30-11eb-86d3-6f62d62a5fe4.png)

H3 and Caption sizes need to be updated. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
need to check https://github.com/google/web-stories-wp/pull/4775

**Comment by barklund** [comment]
Based on [`textPresets.js` edit history](https://github.com/google/web-stories-wp/commits/f2f3dfdd394d6bef44606fa7b1b80055a4122c87/assets/src/edit-story/components/library/panes/text/textPresets.js), it's hard to tell if this was already done.

Ping @miina.

**Comment by barklund** [comment]
This is done - font sizes are correctly set to the specified sizes (achieved in #4775).

**Comment by samitron7** [comment]
Verified in UAT
