### ISSUE TITLE
AMP Sanitizer added too late, missing analytics tag

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5113]
## Bug Description

When rendering a single story and the AMP plugin is active, we short-circuit and let the AMP plugin do all the heavy lifting. We do add our own sanitizer though:

https://github.com/google/web-stories-wp/blob/6f8cfb8b381c79b7b3be0b98cff428eb59bf9016/includes/Story_Renderer/HTML.php#L80-L86

This way we can pass story-specific information to the sanitizer args.

However, it seems that at this point filtering `amp_content_sanitizers` has no effect at all.

## Expected Behaviour

`AMP_Story_Sanitizer` should run for stories when the AMP plugin is active.

## Steps to Reproduce

1. Install both Web Stories and the AMP plugin.
1. Notice that `AMP_Story_Sanitizer` is not being called
1. Notice that no analytics code is printed (if configured)

## Additional Context

- Plugin Version: 1.1.0
- AMP Plugin Version: 2.0.5
- Operating System: macOS
- Browser: Chrome 86

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
The `HTML` class runs after `template_include`, while the AMP sanitizers actually seem to be initialized on `wp`, which is a bit earlier.

So it seems like I simply need to move the `amp_content_sanitizers` earlier:

1. Move `add_filter( 'amp_content_sanitizers', [ $this, 'add_amp_content_sanitizers' ] ); ` to `Story_Post_Type::init`
1. Add method like this to `Story_Post_Type`:

```php
/**
 * Filters the AMP plugin's sanitizers.
 *
 * @since 1.1.0
 *
 * @param array $sanitizers Sanitizers.
 * @return array Sanitizers.
 */
public function add_amp_content_sanitizers( $sanitizers ) {
	$post = get_post();
	if ( ! ( $post instanceof WP_Post ) ) {
		return $sanitizers;
	}

	$story = new Story();
	$story->load_from_post( $post );
	$sanitizers[ AMP_Story_Sanitizer::class ] = [
		'publisher_logo'             => $this->get_publisher_logo(),
		'publisher_logo_placeholder' => $this->get_publisher_logo_placeholder(),
		'poster_images'              => [
			'poster-portrait-src'  => $story->get_poster_portrait(),
			'poster-square-src'    => $story->get_poster_square(),
			'poster-landscape-src' => $story->get_poster_landscape(),
		],
	];

	return $sanitizers;
}
```

This works. So far so good.

Now, the problem is that `AMP_Story_Sanitizer` does also do some output buffering that seems to clash:

https://github.com/google/web-stories-wp/blob/6f8cfb8b381c79b7b3be0b98cff428eb59bf9016/includes/AMP/Traits/Sanitization_Utils.php#L106-L117

When `ob_start()` / `ob_get_clean()` is called there I get a blank page. Without it, everything works.

Not sure yet why as nested output buffers should work.

cc @westonruter

**Comment by westonruter** [comment]
> When `ob_start()` / `ob_get_clean()` is called there I get a blank page. Without it, everything works.

I don't think you can open an output buffer in an output buffer callback, which is where the sanitization is being done. Therefore, you should do the `web_stories_print_analytics` action during template rendering, such as in the `\Google\Web_Stories\Story_Renderer\HTML::render()` method. 

> 2\. Add method like this to `Story_Post_Type`:

Minor point, but I think this can do a check for `is_singular( 'web-story' )` and then use `get_queried_object()` rather than `get_post()` to be safe.

**Comment by swissspidy** [comment]
Ah right, forgot that it's running in that context!

**Comment by csossi** [comment]
Verified in QA

AMP activated:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/55a9ac57-96df-4775-b4f7-ae8010668b2c)

AMP deactivated:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/561fb077-1b1e-44ac-88c0-21560a81405b)
