### ISSUE TITLE
E2E Tests: Test AMP Plugin Integration

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5114]
## Feature Description

To catch things like #5113

## Additional Context

Related: #4461

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
Same question as here. https://github.com/google/web-stories-wp/issues/4461#issuecomment-728051973

**Comment by swissspidy** [comment]
No mock plugin. We'd want to test with the real AMP plugin.
