### ISSUE TITLE
Use Composer 2 in build process

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#5117]
## Feature Description

Composer 2 was announced on [24th OCTOBER 2020](https://blog.packagist.com/composer-2-0-is-now-available/). We have already had some issues with composer 2. See https://github.com/google/web-stories-wp/pull/4999

However, from the linked articles 

> Composer 1.x, it is now more or less EOL. 

Compsoer 2 has a number of benefits, mostly including speed and performance. 

Many of the plugins we use will have be updated and lots of testing. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Already opened #5083 for this
