### ISSUE TITLE
Media: Filter REST API responses by media types allowed by plugin

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#5118]
## Feature Description

If the first 20 items in returned in the REST API, are not a supported media format, then nothing is displayed and infinite scroll does not kick in. 

Found, after uploading 40+ SVGS. See screenshot.

<img width="1122" alt="Screenshot 2020-11-03 at 13 59 10" src="https://user-images.githubusercontent.com/237508/97994160-e95b0880-1ddc-11eb-8797-66a62d547e68.png">
<img width="1884" alt="Screenshot 2020-11-03 at 14 00 48" src="https://user-images.githubusercontent.com/237508/97994310-19a2a700-1ddd-11eb-97e2-0264b00a560a.png">

REST API responses should be limited to only MIME types the media library supports. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
The editor already filters media results by type (either 'image' or 'video'):

https://github.com/google/web-stories-wp/blob/af38560ff5ab6b79392948f67ed494cf2aa85a9c/assets/src/edit-story/app/api/apiProvider.js#L126-L128

So it should filter by specific mime types instead.

Sounds like a pea pod ticket to adjust the JS code accordingly

**Comment by spacedmonkey** [comment]
I thought about tweaking the API at the REST API level, so it doesn't return unsupported mime types. 

We also have to check that we are doing mime type queries that are performant.

**Comment by swissspidy** [comment]
I see. Well, then I think all that's needed is this:

```php
class Stories_Media_Controller extends \WP_REST_Attachments_Controller {
	use Types;

	/**
	 * Retrieves the supported media types.
	 *
	 * Media types are considered the MIME type category.
	 *
	 * @since 1.2.0
	 *
	 * @return array Array of supported media types.
	 */
	protected function get_media_types() {
		return $this->get_allowed_mime_types();
	}

	// ...
}
```

This way, the REST API will filter only by the mime types allowed by our plugin, not all mime types allowed by WordPress.

As for performance, WordPress already does the mime type checks in a performant way. No need to reinvent the wheel.

**Comment by spacedmonkey** [comment]
The approve didn't fix the issue for me. But does seem like a valid change.

**Comment by spacedmonkey** [comment]
The above change, would only limit what is can be passed to the api. We need to limit what is passed to WP_Query / get_items.

**Comment by swissspidy** [comment]
That's what the above should do, actually.

`\WP_REST_Attachments_Controller::prepare_items_query()` uses `get_media_types()` method to determine what is passed to `WP_Query`.

So if the editor says "I want all images"...

BEFORE: It would get all images with types supported by WordPress
NOW: It gets all images with types supported by the editor
