### ISSUE TITLE
Text Sets: Filter by matching font in story not built to spec

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#5122]
## Bug Description

Filter my matching font in the story designs are [here](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=2%3A31546)

![image](https://user-images.githubusercontent.com/13389997/98042704-02ba7f80-1df2-11eb-959a-ad47ca4392f5.png)
![image](https://user-images.githubusercontent.com/13389997/98042721-0a7a2400-1df2-11eb-8e86-a683e3a044b3.png)
![image](https://user-images.githubusercontent.com/13389997/98042733-0ea64180-1df2-11eb-830a-64b7d72d2d2a.png)

However, in the editor it's implemented as one of the filter chips saying "Fonts In Use":
![image](https://user-images.githubusercontent.com/13389997/98042802-2da4d380-1df2-11eb-9171-234410246ce3.png)

We should update the UX to match the spec. 

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA

**Comment by o-fernandez** [comment]
Looks so good!
