### ISSUE TITLE
Filter image picker to only supported image types

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#5124]
## Feature Description

There are a number of image picker that use the WordPress media picker. These include 
- Cover image. 
- Publisher image.
- Video poster image. 

These picker should be limited only image mime types that the story editor supports. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

Related: #5118 #4931

**Comment by spacedmonkey** [comment]
<img width="1884" alt="Screenshot 2020-11-04 at 10 06 11" src="https://user-images.githubusercontent.com/237508/98097795-6772ea00-1e85-11eb-9b28-3a85fee2d38b.png">
Here is an SVG in this picker, even through it is not supported until #5103 is merged.

**Comment by kkalarickal** [comment]
Verified on https://stories-qa-wordpress-amp.pantheonsite.io/ running © 2021 Google Version 1.3.0+e1cf611

1. Tested upload by drag-and-drop vs file selection in the Stories > Settings: https://share.getcloudapp.com/8Luk7950
2. Tested change of publisher/cover image via stories editor for existing and new stories: 
- the unsupported file was uploaded to media library but did not get applied to the publisher logo/cover image
- this might need a new ticket to send notify the end user that their image is unsupported @swissspidy 
3. Tested uploading file masquerading as jpg: https://share.getcloudapp.com/qGuXKRLj
