### ISSUE TITLE
Redirect for child pages with stories slug

### ISSUE THREAD

**Issue by serge-0v** [GoogleForCreators/web-stories-wp#5128]
## Bug Description

Redirect from /stories to /web-stories redirects all pages that have slug _stories_. For example, _example.com/client/stories_ redirects to _example.com/web-stories_ 

## Expected Behaviour

_example.com/client/stories_ does not redirect to _example.com/web-stories_, _example.com/stories_ redirects to _example.com/web-stories_

## Steps to Reproduce

Create child page with the slug _stories_ under any parent page.
## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Thanks for your report!

Is `example.com/client/stories` an actual static page in your WordPress site, or just an example?

**Comment by serge-0v** [comment]
> Thanks for your report!
> 
> Is `example.com/client/stories` an actual static page in your WordPress site, or just an example?

/client/stories is an actual page we have. Child page /client/stories/story-name works, but /client/stories/ redirects to /web-stories.

**Comment by swissspidy** [comment]
Got it, thanks! Was able to reproduce this, definitely should be addressed on our side

**Comment by swissspidy** [comment]
```diff
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
modified: includes/Story_Post_Type.php
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
@ includes/Story_Post_Type.php:782 @ class Story_Post_Type {
     * @return bool Whether to pass-through or not.
     */
    public function redirect_post_type_archive_urls( $bypass, $query ) {
-        global $wp_rewrite;
+        global $wp_rewrite, $wp;

        // If a plugin has already utilized the pre_handle_404 function, return without action to avoid conflicts.
        if ( $bypass ) {
@ includes/Story_Post_Type.php:794 @ class Story_Post_Type {
        }

        // 'pagename' is for most permalink types, name is for when the %postname% is used as a top-level field.
-        if ( 'stories' === $query->get( 'pagename' ) || 'stories' === $query->get( 'name' ) ) {
+        if (
+            'stories' === $wp->query_vars['pagename'] &&
+            ( 'stories' === $query->get( 'pagename' ) || 'stories' === $query->get( 'name' ) )
+        ) {
            $redirect_url = get_post_type_archive_link( self::POST_TYPE_SLUG );
            if (
                $query->get( 'page' ) &&
```

@spacedmonkey FYI I think this ^ should fix it
