### ISSUE TITLE
Image taking a long time to populate on page and page thumbnail

### ISSUE THREAD

**Issue by samitron7** [GoogleForCreators/web-stories-wp#5132]
## Bug Description

Add an image to the page and observe that it can take awhile for it to appear on the page and the page thumbnail

## Expected Behaviour

Image should immediately appear

## Steps to Reproduce

1. Drag an image to the page or into a shape.
2. Observe the time it takes before the image appears on the page or in the page thumbnail.

## Screenshots

[Video](https://drive.google.com/file/d/1wbVBxdIzRTYTdCoESPtadUNldZ92EnPV/view?usp=sharing)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Can't access the video but closing since I'm not able to reproduce this. Perhaps it's related to the general performance issue of having many pages in a story, that will be resolved elsewhere.
