### ISSUE TITLE
Match font in story cta not designed to spec

### ISSUE THREAD

**Issue by samitron7** [GoogleForCreators/web-stories-wp#5133]
## Bug Description

Match font cta (Font in Use) is currently found inside the categories pill dropdown. 

## Expected Behaviour

The cta is a checkbox that resides outside of the category dropdown. When "Match font in story" is checked, it should display all text sets in each category with a match.

## Screenshots

[Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=2%3A31546)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by dreamofabear** [comment]
Duplicate of #5122.
