### ISSUE TITLE
Safe zone box randomly disappears

### ISSUE THREAD

**Issue by samitron7** [GoogleForCreators/web-stories-wp#5134]
## Bug Description

1. The design safe zone (pink-purple box) do not always appear for me
2. Safe zone also randomly disappear as I build my story
3. Safe zone sometimes stay stuck on the page

## Expected Behaviour

The design safe zone is part of the snap guideline system and should also appear in accordance with snap guide rules

## Screenshots
Safe zone not showing up:
![safeZoneMissing.gif](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/e1424b58-cd44-46ae-b781-2c66a69ccc36)

Safe zone stuck:
![Screen Shot 2020-11-04 at 10.38.06 AM.png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/552adc0a-1dd5-4e67-a481-3895f75eaddd)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
@samitron7 I think your GIF was too large for GitHub. Could you perhaps upload it as a video somewhere, e.g. https://imgur.com/upload?

**Comment by samitron7** [comment]
@swissspidy Re-created a smaller version of the gif.

**Comment by dreamofabear** [comment]
Possibly the same root cause as #5056.

**Comment by samitron7** [comment]
@choumx The link you provided links to this ticket.

**Comment by dreamofabear** [comment]
Oops, fixed. Thanks.
