### ISSUE TITLE
Performance: Sluggish scroll performance in text sets

### ISSUE THREAD

**Issue by samitron7** [GoogleForCreators/web-stories-wp#5136]
## Bug Description

Text sets are taking a long time to show up. Often time you get a completely blank area.

## Expected Behaviour

Text set should load quickly. When loading takes time, we should include a loading animation.

## Steps to Reproduce

1. Click on a text set category
2. Observe that loading takes a long time
3. Observe that you may get an empty space before the entire text area panel loads

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Related: #5797

**Comment by BrittanyIRL** [comment]
I _feel like_ this isn't so bad anymore. Perhaps we use this ticket to implement a loading spinner for when more items are rendering. This seems like something good to do after redesign is done.

**Comment by swissspidy** [comment]
Could this be closed in favor of #7987, #8117?

cc @miina

**Comment by miina** [comment]
Yep, closing in favour of #7985 and #8117.
