### ISSUE TITLE
Website: XML Sitemap

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5139]
## Task Description

Let's add an XML sitemap for all our content and stories on wp.stories.google.

https://www.npmjs.com/package/sitemap looks simple enough to create a sitemap based on all the stories plus the static content (homepage + `/docs`)

edit: https://wp.stories.google/sitemap.xml

**Comment by Steellgold** [comment]
What is XML

**Comment by swissspidy** [comment]
XML: https://en.wikipedia.org/wiki/XML
XML Sitemaps: https://en.wikipedia.org/wiki/Sitemaps

**Comment by Steellgold** [comment]
ok
