### ISSUE TITLE
Editor crashes when custom time format is selected and blank

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#5154]
## Bug Description

If you change your time format to "custom" on settings and clear the input so it's blank and save, when you navigate to the editor it will crash.

## Expected Behaviour

There should be a fallback time format to avoid crashes. 

## Steps to Reproduce

Settings > custom time format > clear input > save
Navigate to editor (new story or existing), see that it has crashed.

## Screenshots

![Screen Shot 2020-11-06 at 4.01.14 PM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/b8f9b947-f9e9-4929-9e44-09794563bf77)
![Screen Shot 2020-11-06 at 4.01.53 PM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/31619ff2-ce99-460a-b7a0-9b389b8f02ce)
![Screen Shot 2020-11-06 at 4.01.44 PM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/41928203-a23e-4585-b95d-4e13c8d48e31)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
This is the issue I fixed in my last PR actually

**Comment by swissspidy** [comment]
Fixed by #5104

**Comment by BrittanyIRL** [comment]
🤦‍♀️ ooph i even reviewed that! I thought that date fix had been merged and that this was an edge case that i didn't test. my apologies.
