### ISSUE TITLE
TypeError: Cannot read property 'elements' of undefined

### ISSUE THREAD

**Issue by Dfirvida** [GoogleForCreators/web-stories-wp#5165]
TypeError: Cannot read property 'elements' of undefined
    in StoryProvider
    in Unknown
    in SnackbarProvider
    in Unknown
    in HistoryProvider
    in Unknown
    in Media3pApiProvider
    in Unknown
    in FileProvider
    in Unknown
    in APIProvider
    in Unknown
    in ConfigProvider
    in aU
    in ThemeProvider
    in StyleSheetManager
    in App
    in StrictMode
    in FlagsProvider

**Comment by swissspidy** [comment]
Thanks for your report!

What was the last action you've taken before this error happened?

Could you perhaps share your Site Health info with us so we can better understand how this happened?

**Comment by swissspidy** [comment]
Hi there,

I'm closing this for now since we haven't gotten any feedback. If it still happens with the latest 1.2.1 version of the plugin, please let us know.
