### ISSUE TITLE
Clicking on Web Stories menu item should highlight Dashboard

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#518]
## Feature Description

When I click on the "Web Stories" top level menu item, I land on `wp-admin/admin.php?page=stories-dashboard` and it looks like this:

<img width="207" alt="Screenshot 2020-03-10 at 16 22 11" src="https://user-images.githubusercontent.com/841956/76328605-ca5ab400-62eb-11ea-8769-17a16a272216.png">

When I click on the "Dashboard" sub menu item, I land on `wp-admin/edit.php?post_type=web-story&page=stories-dashboard`

<img width="203" alt="Screenshot 2020-03-10 at 16 22 05" src="https://user-images.githubusercontent.com/841956/76328619-cfb7fe80-62eb-11ea-9ebf-903d89447914.png">

Ideally, "Dashboard" should be highlighted in both cases.

Another thing I noticed: because we're within the "Web Stories" section / post type, the admin menu is also folded here because of this:

https://github.com/google/web-stories-wp/blob/793356081d45f5fe73cd8d9003cbb5de00f693c2/includes/Story_Post_Type.php#L532-L535

The question is: should the admin menu be folded on the Dashboard?

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment]
Reviewing during grooming (Beta, sprint 27). Not a priority right now.
