### ISSUE TITLE
Make video poster generation more robust

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5190]
## Feature Description

Splitting this off from #5119. Video poster generation should be made more robust if the poster generation failed the first time around.

Needs investigation on why/where poster generation fails (timeouts maybe?) and how this can be mitigated (e.g. by a number of retries?)

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
I think that any solution for this should include https://github.com/google/web-stories-wp/issues/969. I think that one of the issues here, is that this error state ( poster is not being generated ) is not visual to user. Showing progress bar, will help in QA and get users feedback.

**Comment by spacedmonkey** [comment]
I also think that poster generation should be retried multiple times, say 3 times and if it is fails, an error shown to user. 

Other ideas I had for why this is happening, there maybe something odd with the video's encoding and the user's computer is slow.

**Comment by dreamofabear** [comment]
This may only be part of the problem, but looks like posters are consistently missing for videos if inserted into the story via the WP media popup > "Insert into page" button. This affects videos whose posters were already generated!

Tangent: I've noticed posters being set on the wrong video (!) when deleting and reuploading videos for testing. I'll figure out the minimal repro and file a separate issue for this.

@zidianlyu to share his investigation notes.

**Comment by zidianlyu** [comment]
Here are my investigation notes

Issue: 
The poster will never show up under `Accessibility` after user upload a new video.

![Screen Shot 2020-11-11 at 1 31 18 AM](https://user-images.githubusercontent.com/11252886/98866608-0e292e80-2422-11eb-9ad4-67d5016ca3e8.png)

Step to trigger:
Click on `Upload` -> `Select Files` -> `Insert into Page`

On UI rendering level, we will have:
<img width="297" alt="Screen Shot 2020-11-11 at 1 27 13 PM" src="https://user-images.githubusercontent.com/11252886/98866429-c3a7b200-2421-11eb-8d1c-7575deca5d77.png">

By backtrack, the `poster` property should be passed from the `selectedElements` variable.

**Comment by swissspidy** [comment]
`updateElementsByResourceId` is used to update the elements after the poster has  been generated, so you are saying that is not working as intended?

**Comment by zidianlyu** [comment]
Place where we generate the poster:
`getFirstFrameOfVideo.js` the output will be a blob object.

Data flow after user upload the video and click `Insert into page`, it triggers (helpful breakpoints, for debugger purpose):
- mediapane.js -> useMediaPicker({onSelect,onClose});
- useMediaPicker.js -> onSelect(mediaPickerEl);
- mediaPickerEl is created from `fileFrame.state().get('selection').first().toJSON()` which does not contain and `poster` images.

Therefore, all the remaining logic will not take in any poster value.

**Comment by zidianlyu** [comment]
Suspicious observation:
In `getResourceFromMediaPicker`, there is a object(mediaPickerEl) distracter with key `poster` under a field `featured_media_src`. With debugger, I find that the field `featured_media_src` will always undefined.

Based on my understanding to the context and documentation, we should be able to get the poster in here, so that the UI can pick up the poster value. Any hints why the poster is missing?

My guess(please correct me if I am wrong) is we that we have a place somewhere to async update the media value globally, and the getResourceFromMediaPicker call is made before the poster is fully retrieved.

**Comment by zidianlyu** [comment]
I also check the logic of poster generation, it works perfectly fine.

For reference, I put it here:
In `useUploadVideoFrame.js`, there is a method `ProcessData`.
The `poster` value can be generated by 2 async calls `getFirstFrameOfVideo()` and `uploadFile()`

**Comment by zidianlyu** [comment]
@swissspidy follow your suggestion, just researched on `updateElementsByResourceId`, here are the details:

On `useUploadVideoFrame.js`, under `processData()`, we can get the `poster` value as expected.  

I also take a closer look at the follow snippet, and think there might be some issues:

```js
  const { updateElementsByResourceId } = useStory((state) => ({
    updateElementsByResourceId: state.actions.updateElementsByResourceId,
  }));
  const setProperties = useCallback(
    (id, properties) => {
      updateElementsByResourceId({ id, properties });
    },
    [updateElementsByResourceId]
  );
```

```js
      const newState = ({ resource }) => ({
        resource: {
          ...resource,
          posterId,
          poster,
          ...newSize,
        },
      });
      setProperties(id, newState);
      updateMediaElement({
        id,
        posterId,
        poster,
        ...newSize,
      });
```

The `setProperties()` method does NOT seems update the `poster` value correctly. And I also tried adding `await` in the context in case there are any async calls in the context, but that does not resolve the issue either.

**Comment by spacedmonkey** [comment]
Related: #5249

**Comment by csossi** [comment]
Verified in QA
