### ISSUE TITLE
Text Sets - Recommended design space doesn't show when dragging in a text set

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5192]
## Bug Description

When a story author drags a text set into the editor the recommended design space is not presented to the end user

## Expected Behaviour

Expectation is that the recommended design space would be presented in this scenario.

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by zidianlyu** [comment]
Hi Team, would you mind provide some screenshots on this issue, I would love to know more about it and pick it up.

**Comment by BrittanyIRL** [comment]
@bmattb Can you clarify a bit? This is what the drag currently looks like, which feels accurate to me. 


https://user-images.githubusercontent.com/10720454/103800165-4a83a000-5009-11eb-9240-464836fb7bc3.mp4



![drag text set space](https://user-images.githubusercontent.com/10720454/103800235-625b2400-5009-11eb-8fb9-62cf9dae4c9c.gif)

**Comment by swissspidy** [comment]
@BrittanyIRL You don't see the safe zone and snapping guidelines though. This will be addressed by #5337

**Comment by swissspidy** [comment]
Hmm #5337 was merged though today. Could you perhaps re-check?

**Comment by BrittanyIRL** [comment]
Confirming that we see safe zone and snapping guidelines:

![resolved design space on drag](https://user-images.githubusercontent.com/10720454/107276783-c447e880-6a10-11eb-84a5-573b1aef0369.gif)
