### ISSUE TITLE
Audio in Media Library

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#52]
## Feature description

Find elegant way to display audio in the media gallery when you need it.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
Related: #48

**Comment by swissspidy** [comment]
Duplicate of #8585
