### ISSUE TITLE
Remove "Still Empty" Sections

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#520]
## Feature Description

There are sections we are "alpha" launching without and need to remove those sections from the UI.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
1. Remove Element Panel - Elements section
2. Remove Element Panel - Animations section
3. Remove Prepublish list (Ensure stories are published after hitting the publish button)
4. Remove search bar from shapes tab on element panel (Pending Sam's confirmation)
5. Remove search bar from text tab on element panel (Pending Sam's confirmation)

**Comment by jauyong** [comment]
@pbakaus @samitron7 Should we hide the search bar in the element panel while on the shapes and text tabs for the Alpha release? Currently it is not functional.

**Comment by pbakaus** [comment]
@jauyong I'd say yes. @samitron7 to confirm.
