### ISSUE TITLE
Line-height for Highlight seems to be broken

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#5200]
## Bug Description
Line-height doesn't seem to be applied correctly in case of Highlight mode for text.
Note that this happens in the output only, not in the editor

## Expected Behaviour
1. Line-height should match in the editor and in the output

## Steps to Reproduce
1. Add a text element
2. Create a text of 3 lines and set the background mode to Highlight
3. Assing line-height to 3
4. Preview / Save and see the output.

## Screenshots
Editor:
![Screenshot 2020-11-10 at 14 15 55](https://user-images.githubusercontent.com/3294597/98672991-fafd5c80-2356-11eb-84a8-b6633ce8a9a4.png)

Output:
![Screenshot 2020-11-10 at 14 16 08](https://user-images.githubusercontent.com/3294597/98673004-fdf84d00-2356-11eb-9742-d5221cd14169.png)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Can reproduce this. Even with the default line height (1.5) or a line height of 1 the output is different from the editor.

**Comment by csossi** [comment]
Verified in QA
