### ISSUE TITLE
Save

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#521]
This is a followup from #221 to make it specific to save only. (no autosave)

As an author I want to be able to save my progress so I don't lose my work. 

[Feature Brief - Epic: Document Workflow](https://docs.google.com/document/d/1GJZljicdXcP7oRdywsF3EGUaCVpCHsDrK2gUMubnrbk/edit?pli=1#heading=h.omxvhkxr4hgd)

**Acceptance Criteria**
1. Saving & updating works similar to regular posts in WordPress, with some special casing (see below)
3. If a story is unpublished, save by triggering the Save button
5. If a story is published, Save by triggering the Update button
6. After the author navigates away(e.g. refresh) from the page without saving, a notification is shown. 

Note:  Save/update does not save the undo/redo stack. Undo/redo is tied to the current client state.

**Comment by spacedmonkey** [comment]
Gutenberg also has a save as save button. Should we have this?

<img src="https://user-images.githubusercontent.com/237508/75875736-2f09a080-5e0c-11ea-8635-603cab11ebd7.png" />

**Comment by spacedmonkey** [comment]
<img width="281" alt="Screenshot 2020-03-11 at 13 54 02" src="https://user-images.githubusercontent.com/237508/76424177-cc7e4a80-639f-11ea-88ca-a28ac6036889.png">
There is also private post visablity to support.

**Comment by miina** [comment]
Probably we can implement it as it is in WordPress currently (Save Draft + Preview + Publish) and shuffle the buttons around later if needed.

@pbakaus Let me know if following the way how it's in WP currently is fine for now:
- Displaying "Save Draft" (if it's a draft)
- Displaying "Preview" (Always visible, as now)
- Displaying "Publish" (if draft)
- Displaying "Update" instead of "Publish" (if published)

**Comment by spacedmonkey** [comment]
@miina What about scheduled posts? It is currently possible to set the published date to the future and schedule.

**Comment by miina** [comment]
I  had the impression from the last grooming that we'd currently mainly just get the Publish (Save) button implemented and worry about the rest of the things post-beta. LMK if you understood differently.

**Comment by spacedmonkey** [comment]
No you are correct, but it currently possible to do scheduled posts with what we have and is already kind of working. I think it is worth looking into if it is a quick win.

**Comment by pbakaus** [comment]
@miina yes, that looks fine to me.
@spacedmonkey if schedule is an easy win, I'd say let's add it. It's an important feature.
