### ISSUE TITLE
Stories redirect doesn't work with different permalink structures

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#5211]
## Bug Description

If permalink structure is to a custom and set with `/blogs/%postname%/`, the `/stories` -> `/web-stories` does not work. 

Discovered while working on #5128

## Steps to Reproduce

- Go to Setting -> permalink. 
- Set custom and set value to `/blogs/%postname%/`. 
- Go to `/stories`, i.e www.example.com/stories

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Closing in favor of #5234
