### ISSUE TITLE
Add system - banner to design system

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#5214]
Create a reusable banner from designs in figma: https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=1983%3A0

There should be two style deviations here - one for editor and one for dashboard (see figma).

Acceptance criteria: 
Banner exists in designsystem storybook with variation for dashboard and editor

**Comment by BrittanyIRL** [comment]
Create a reusable banner from designs in figma: https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=1983%3A0 

There should be two style deviations here - one for editor and one for dashboard (see figma).

**Comment by samitron7** [comment]
Verified in UAT. Will confirm font sizing with @BrittanyIRL offline.

**Comment by BrittanyIRL** [comment]
@samitron7 Re font size - I did notice a discrepancy this AM in font size and have an update here: https://github.com/google/web-stories-wp/pull/5497 Is this the sizing you wanted to confirm?
