### ISSUE TITLE
update dashboard to use new banner from design system

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#5215]
Use the new banner in the design system to update the existing banner in dashboard.
Currently the only banner in use is the telemetry banner. 
Rip out any banner styles that have been replaced with shared resources. 

Acceptance criteria: 
- Telemetry banner works as expected
- Banner in dashboard is updated to [match figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=1983%3A0)

**Comment by csossi** [comment]
@samwhale , should line breaks match figma here?

The site has:
![image](https://user-images.githubusercontent.com/16945664/106846814-99117200-667b-11eb-807e-e876568c25fb.png)

Figma has:
![image](https://user-images.githubusercontent.com/16945664/106846853-b1818c80-667b-11eb-8151-2753d7cd630f.png)

**Comment by swissspidy** [comment]
Line breaks seem to be quite viewport-dependant, although there could perhaps be a max-width.

**Comment by BrittanyIRL** [comment]
> Line breaks seem to be quite viewport-dependant, although there could perhaps be a max-width.

There is a max-width so it's ok, but the font seems small?

**Comment by samwhale** [comment]
@BrittanyIRL The designs look like a bigger font but they both have 12px as the font size. I'm happy to make the font bigger though if that's what we'd like 👍 

![image](https://user-images.githubusercontent.com/22185279/106929639-d7d21700-66d1-11eb-97b9-b288e9878821.png)
![image](https://user-images.githubusercontent.com/22185279/106929660-e02a5200-66d1-11eb-9ea8-76a09bc0d833.png)

**Comment by samwhale** [comment]
@csossi 

> @samwhale , should line breaks match figma here?


Yeah these are viewport dependent. As we stretch the screen it'll eventually look the same as the designs. If we shrink it, then the text will continue to wrap to make sure it's readable.

**Comment by BrittanyIRL** [comment]
> @BrittanyIRL The designs look like a bigger font but they both have 12px as the font size. I'm happy to make the font bigger though if that's what we'd like 👍
> 
> ![image](https://user-images.githubusercontent.com/22185279/106929639-d7d21700-66d1-11eb-97b9-b288e9878821.png)
> ![image](https://user-images.githubusercontent.com/22185279/106929660-e02a5200-66d1-11eb-9ea8-76a09bc0d833.png)

It must have been a weird zoom thing that was making me think the font was too small, you're right!

**Comment by BrittanyIRL** [comment]
I'm a little confused about where line-breaks need to be defined here since it should respond to the available space on the screen. The max width the text will stretch is 480px.  Otherwise, it should line up nicely and flow responsively. 

@csossi if there's something particular that I'm not noticing or you're asking about can you please elaborate?

**Comment by csossi** [comment]
Verified in QA
