### ISSUE TITLE
Clicked "add new saved color" with multiple text elements selected, added multiple instances of the same color

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#5216]
## Bug Description

Was editing the color for 4 different text elements, selected a new color. Clicked "Save color" button. 

## Expected Behaviour

Expected the color to be added once, since it was the same color. Instead, got 4 different color swatches saved. 

## Steps to Reproduce

1. add multiple text elements - i used a text set
2. select multiple text elements
3. apply a new color to all of the text elements
4. click on add new saved color

## Screenshots

![ezgif-3-72cc813f0a34.gif](https://images.zenhubusercontent.com/5e98486db524b82fc96aeaf6/c2231565-afa2-483d-89b4-409c14964213)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@barklund @bmattb FYI pulling this into the super sprint.

**Comment by csossi** [comment]
Verified in QA
