### ISSUE TITLE
Migrate "borders" from being 4 individual shapes to being one shape using an actual border

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5221]
## Bug Description

On some text sets it appears that the border is 4 individual shapes, which is a problem when the text set is moved off canvas and moved back on, the border on the side moved out of view is clipped/removed.

eg:
![Screen Shot 2020-11-10 at 4 14 19 PM](https://user-images.githubusercontent.com/58738530/98734341-d19cfa80-236f-11eb-93cd-6741590554ee.png)

## Expected Behaviour

The border on this text set should be a single shape so that a move off canvas isn't destructive.

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA

![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/add1d26d-6718-4b2d-9ec8-c364a97907dc)

**Comment by samitron7** [comment]
Same as ticket [5435](https://app.zenhub.com/workspaces/web-stories-5e94d3aced449034e1e9b226/issues/google/web-stories-wp/5435):

Added the hairline text set to the page and selected the outline box. Note that color input field is completely empty.
![Screen Shot 2020-11-25 at 11.39.01 PM.png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/3b7b622f-3b9f-424f-8a10-300fd4b1f7fc)

**Comment by o-fernandez** [comment]
I see the same issue as Sam, but that seems to be what we do right now when the transparency of the color is set to 0% (I was able to replicate by adding my own shape and setting to 0%). https://github.com/google/web-stories-wp/issues/5369
