### ISSUE TITLE
Text Set - Cover | Robots: "Category" should use a bg fill instead of a seperate shape

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5222]
## Bug Description

Currently the Text Set | Cover | Robots - The Category is using a seperate shape, this should be a background fill instead

context:
![Screen Shot 2020-11-10 at 4 25 29 PM](https://user-images.githubusercontent.com/58738530/98735461-66542800-2371-11eb-9774-52c434cd328c.png)

## Expected Behaviour

Category should use a background fill instead of being a seperate shape.

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
verified in qa

**Comment by samitron7** [comment]
Verified in UAT
