### ISSUE TITLE
Use poster image size for feature image

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#5228]
## Feature Description

When setting poster image, medium image size is used. See 

https://github.com/google/web-stories-wp/blob/8f92a30e2c4a20ce22be900604ed39e5e279a789/assets/src/edit-story/components/inspector/document/publish/index.js#L108-L110

If a poster image size is available, it should be used.  

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
So seems to be an issue [here](https://github.com/google/web-stories-wp/pull/5039/files#diff-6a56215f456b8c527051e501214de0f2296e2182e660a4cb297e0ba0a43e89c3R80-R83).

**Comment by swissspidy** [comment]
Probably should be the full size URL and dimensions, to make #5229 work

**Comment by spacedmonkey** [comment]
Either way I think we should change this.

**Comment by swissspidy** [comment]
@carlos-kelly Was this fixed by #5444 and can be closed?
