### ISSUE TITLE
Pre-Publish Checklist: Check cover image size

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5229]
## Feature Description

This is a follow-up to #4910 / #5086.

Since #5105 has been merged, we now pass the necessary information about the story cover image size in the API and handle it in `useLoadStory`, which means this item is unblocked:

> Story portrait cover size too small (less than 640 x 853) or wrong aspect ratio (not 3:4)

Note: When updating the cover image, the right image size is not yet saved, see #5228. That likely needs updating.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by embarks** [comment]
@swissspidy looks like this was implemented last week?

**Comment by carloskelly13** [comment]
Yeah, I think this is a bug bash dupe!

**Comment by swissspidy** [comment]
Yep
