### ISSUE TITLE
Recommended design zone outline is not presented when drag and dropping a text set into it.

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5230]
## Bug Description

When drag & dropping a text set into the canvas the recommended design zone outline is not presented to user

## Expected Behaviour

As with other elements, it's expected that the recommended design design zone outline is presented to users.
## Steps to Reproduce
1. open the editor
2. select the text panel
3. select a text set and drag onto canvas
4. note the error :)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
This is the same thing reported in #1979 - no guides are displayed when dragging any element from the library to page be it image, video, gif, shape, text, or text set. We should probably create a new feature ticket for doing this work, as it'll fix a number of problems - including this bug, #1979 and #1930 (and one more I think, but can't find right now).

**Comment by bmattb** [comment]
this will be fixed by #5337

**Comment by csossi** [comment]
Verified in QA
