### ISSUE TITLE
Blocks: Usage difficulties due to theme styling

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5239]
## Bug Description

- Bug: On theme Twenty Sixteen 2.2 (stories-lab.dev), Gutenblock has ~0 height with left or right alignment (due to CSS float)
- Impact: Hard to select the block (need to use arrow keys or block navigation)

## Screenshots
![Screen Shot 2020-11-11 at 3.14.48 PM.png](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/01988bf3-bb11-4b5c-a706-930413e1a02d)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

* Frontend: Force `display: block;` for `.web-stories-embed` element
* Editor: Don't set `width: 100%` for `.web-stories-embed.alignleft, .web-stories-embed.alignright`

**Comment by swissspidy** [comment]
I cannot reproduce this in the default theme, so this sounds like a theme-specific issue

**Comment by dreamofabear** [comment]
I reproduced this on stories-lab.dev which is using the Twenty Sixteen 2.2 theme by WP.

**Comment by dreamofabear** [comment]
Related issue WRT sizing: The embed block on [this EAP story](https://beautywithinofficial.com/2020/08/28/7-exfoliating-serums-for-oily-acne-prone-skin/) is hidden due to implicit width and `.alignnone { display: inline-block }`.

**Comment by spacedmonkey** [comment]
There is a larger problem here, the right and left alignment is not working.

**Comment by csossi** [comment]
Testing 5317 - can't seem to be able to embed a story here:

![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/231a5fff-19bd-4f10-bf43-cc4281cf3a22)

**Comment by swissspidy** [comment]
@csossi that seems totally unrelated because this PR only changes styling. Please try again with pretty permalinks and file an issue if problem persists

**Comment by csossi** [comment]
Verified in QA
