### ISSUE TITLE
Lighthouse error occurs when adding shortcode in widget

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#5241]
## Bug Description

Embedding a story using Web Stories shortcode in a widget causes a lighthouse error: <frame> or <iframe> elements do not have a title.

## Expected Behaviour

No lighthouse error occurs when using Web Stories shortcode in a widget.

## Steps to Reproduce

1. Create story. Publish. Copy shortcode for story post.
      Example: [web_stories_embed url="http://testsite.cmsdevrel.com/web-stories/901/" title="test" poster="http://testsite.cmsdevrel.com/wp-content/uploads/2020/08/image-524-1.png" width="360" height="600" align="none"]
2. Add "Text" widget. Paste shortcode for story post.
3. Run lighthouse report. See [report](https://jmp.sh/if4KhF8).

## Related topic
https://wordpress.org/support/topic/or-elements/#post-13650982

- Plugin Version: 1.1.0
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
This is something that should be reported in the amphtml repo as this is using `amp-story-player`

**Comment by LuckynaSan** [comment]
Thanks @swissspidy I've opened a ticket: https://github.com/ampproject/amphtml/issues/31110

**Comment by LuckynaSan** [comment]
Closing this ticket for now as the issue is no longer reproducible.
