### ISSUE TITLE
Prefer vertical/portrait 3P media 

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#5243]
## Feature Description

When using 3P media (images, video, GIFs) it's sometimes hard to find ones that look very good in portrait mode/vertical cropped. It'd be great if the editor can surface higher in the results the media that is optimized/better for portrait mode. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
That‘d mean adjustments on the media3p API side, which is internal.

**Comment by swissspidy** [comment]
Closing in favor of #9287
