### ISSUE TITLE
The editor has crashed

### ISSUE THREAD

**Issue by cad59** [GoogleForCreators/web-stories-wp#5246]
The plugin's editor is out of order.
Report error : RangeError: Format string contains an unescaped latin alphabet character `n`
[See the screenshot](https://snipboard.io/ANRgaI.jpg)

My configuration:
Wordpress 5.5.3
Theme : Blocksy 1.7.14

**Comment by swissspidy** [comment]
@cad59 Hi there, please update to the new 1.1.1 of the plugin if you haven't done so already. That should fix this issue.
