### ISSUE TITLE
Stop composer from automatically updating

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#5250]
Now that composer released version 2, we no longer want composer to update when dev environment spins up.

**Comment by swissspidy** [comment]
We'd want to replace `composer self-update` with `composer self-update --1` until #5083 is fixed

**Comment by spacedmonkey** [comment]
Yeah, just lock down to composer v1. This has what I have been using locally. `composer self-update 1.10.1`. So we have control of the version of composer. But either way works for me.
