### ISSUE TITLE
Ad Manager Support

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#5290]
## Feature Description

We already have people doing this manually using other plugins ([sample support thread](https://wordpress.org/support/topic/ads-with-admanager/)). Allow for something similar in the settings panel of the plugin.

**[product brief draft](https://docs.google.com/document/d/1Xs4uOZ3KCNlTMdjDT6q7cvTUpA1xk-kzrnVLQALltQk/edit#heading=h.tuoynqlc00)** 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Assigning WP pod too because this will require PHP changes

**Comment by o-fernandez** [comment]
And, per your comment on #4803 these two efforts are related (AdSense and Ad Manager support) so I'll merge into one ticket.
