### ISSUE TITLE
Image size smaller than recommended size

### ISSUE THREAD

**Issue by DanielCryptoK** [GoogleForCreators/web-stories-wp#5304]
Image size smaller than recommended size

https://bitcoin-casino-no-deposit-bonus.com/web-stories/fairspin-casino-bonus/

see attached
![AMP](https://user-images.githubusercontent.com/45933242/99148065-3e89fa80-26b8-11eb-80d7-8e43519bf83d.png)

**Comment by ernee** [comment]
@DanielCryptoK thanks for reaching out! We're providing support in the [WordPress support forums](https://wordpress.org/support/plugin/web-stories/) now. Feel free to [open a new topic ](https://wordpress.org/support/plugin/web-stories/#new-topic-0)there with this issue and we'll be happy help.

**Comment by swissspidy** [comment]
@DanielCryptoK note that your poster image does not the requirements of being at least 640x853px in size. You should fix that

**Comment by DanielCryptoK** [comment]
Which is the poster image? You mean the front page image?

**Comment by swissspidy** [comment]
The "cover image" you upload here:

<img width="282" alt="Screenshot 2020-11-18 at 09 28 53" src="https://user-images.githubusercontent.com/841956/99504926-7aef7c00-2980-11eb-96f7-9b5acdb89719.png">
