### ISSUE TITLE
Page Duration Reset to 7 Seconds

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#5319]
## Bug Description

The default page duration resets back to 7 seconds after publishing a story that was set to 12 seconds. 

## Expected Behaviour

The page duration setting should remain the same.

## Steps to Reproduce

Create new story
Upload video longer than 7 seconds
Change default page duration from 7s to 12s (or any other number)
Publish story. 
Go back to edit your published story and notice the page duration reset to 7s. 

## Screenshots

Published story at 12s: https://jmp.sh/laSwUA5
Click back into story and it reset to 7s: https://jmp.sh/3ot7uMl

## Additional Context
Issue was reproducible. 

## Related Topic
https://wordpress.org/support/topic/default-page-duration-resetting-itself/#post-13669137

- Plugin Version: 1.1.1
- Operating System: MacOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
Oops, merged the wrong PR. @csossi, can you QA on main branch and if you find anything, just comment here and I'll follow-up in a new ticket.

**Comment by csossi** [comment]
Verified in QA (tested in Main branch)

**Comment by samitron7** [comment]
Verified in UAT
