### ISSUE TITLE
Story progress bar not aligned with top of content

### ISSUE THREAD

**Issue by dreamofabear** [GoogleForCreators/web-stories-wp#5322]
## Bug Description

On tall devices (e.g. iPhone X) in the Discover carousel, WP stories show a gap between the story progress bar and the top of the 9:16 content.

Impact: The progress bar gap and partially overlapping volume icon look bad. It's particularly jarring when swiping between stories that don't have this visual artifact (generated by other tools).

## Expected Behavior

There are at least two ways to fix this issue:
1. Long-term, add aspect ratio flexibility: https://github.com/ampproject/amphtml/issues/31032
2. Short-term, add a media query that top-aligns the 9:16 content area if the size of the gap is not too large.
  - One definition of "not too large" is "progress bar + icons overlap with 9:16 content area"

## Steps to Reproduce

View WP stories in Discover carousel on a tall device.

## Screenshots

![Image from iOS (1)](https://user-images.githubusercontent.com/20525523/99307437-82017780-2824-11eb-88d1-4a112a137ddd.png)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA

**Comment by dreamofabear** [comment]
Verified for UAT
