### ISSUE TITLE
Create a document which details the scope of testing for a Smoke Test

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5329]
## Task Description

Please create a document that details the scope of what a smoke test would contain. Typically these tests are requested prior to a release, and are expected to take less than (X) hours to complete. 

This definition will be used by stakeholders to align on the definition of this testing.

**Comment by swissspidy** [comment]
Wouldn't it be on us as the product team to define what we are looking for in a pre-release smoke test?

(I am also advocating for smoke testing to be done by anyone who happens to be around for a release)

**Comment by bmattb** [comment]
I've asked Claudio to provide his perspective on what he covers when he's been asked to do this first. That can then be reviewed by relevant project team members to understand where misalignment lies, and what steps to resolution are. Resolution might include:

- alignment in definition of scope of smoke testing
- abandonment of the process and term "smoke testing"
- alternative QA processes to be introduced
- something else
