### ISSUE TITLE
Dashboard: Organize error message text to single source of truth

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#5330]
## Feature Description
@samitron7 and I were discussing the new designs for snackbars in figma and she mentioned how it would be helpful to have a list or the messages getting displayed to have the designs better equipped, we do have a spreadsheet for the dashboard with this but it would be better to move towards having these all in the same file as a reference point. Eventually this can be extracted and messages for dashboard and editor can be unified. This is just a first step. I am prepping to get the new snackbar in place in the dashboard and this is a good thing to do in advance of that update. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

All error messages in dashboard will be combined into one file under src/dashboard/app/textContent. This shouldn't have any impact on functionality, there should be no visible changes. 

Since this is vague for QA - This should just get some regression testing around CRUD of dashboard. Try blocking some APIs to test error messages out. They should match this list: https://docs.google.com/spreadsheets/d/1eG77iwDbKSdOIQCOl2ROSMvSegMq4qm1gophOubcu5w/edit#gid=0. We have robust unit tests set up to error messages. 

## Implementation Brief

Extract text into single file, import corresponding text to file.

**Comment by csossi** [comment]
Hi @BrittanyIRL - any guidance you can offer on how I can test this? Is there some modification I can do through DevTools or something?

**Comment by BrittanyIRL** [comment]
For testing: 

There shouldn't be any visible updates to the dashboard. I've only updated the text that shows up when error messages pop up on the screen. This should be treated as regression testing around CRUD of dashboard. 

To see error messages, try blocking the API in dev tools. 
![Screen Shot 2020-11-30 at 9 07 57 AM](https://user-images.githubusercontent.com/10720454/100633636-909f6280-32eb-11eb-8b9f-4d8df1d1da02.png)


They should match this list: https://docs.google.com/spreadsheets/d/1eG77iwDbKSdOIQCOl2ROSMvSegMq4qm1gophOubcu5w/edit#gid=0

**Comment by csossi** [comment]
Verified in QA
