### ISSUE TITLE
Use Moveable for dragging Media from Library

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#5335]
## Feature Description

Use Moveable for dragging Media from the library instead of the default drag. This way we can display the snapping lines, display the element as it is added to the canvas.

This issue should fix #1979, #5057 and #1930.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
