### ISSUE TITLE
Use Moveable to drag shapes from the element library

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#5336]
## Feature Description
Use Moveable to drag shapes onto the canvas from the element library instead of using the default drag. This way the dragged shape can be displayed as it will look like after inserting on Page.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
When dragging-and-dropping to lower portion of canvas, the image "jumps" up a bit. User has to reselect and drop again to the lower position.

https://share.getcloudapp.com/nOuD97Gk

**Comment by miina** [comment]
@csossi Thanks for flagging this.

That's actually unrelated to this PR and was added in purposefully for Text Sets for ensuring none of the elements would be left out of Page. This "feature" will be removed separately.

Moving to QA Passed in case that was the only issue found.

**Comment by miina** [comment]
Note: Waiting for #5721 to get merged to run all the tests again before merging this.

**Comment by tmagalhaes-huge** [comment]
Closing. @samitron7 @ivayloklissarov @aaecheverria
