### ISSUE TITLE
Use Moveable to drag text sets onto the canvas from the library

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#5337]
## Feature Description

Replace using the default dragging logic and use Moveable instead to drag the text sets from the library to the canvas. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@littlemilkstudio Is #5426 related to this issue? For some reason the PR closed this issue even though this doesn't have anything to do with animations. Thoughts?

**Comment by maxyinger** [comment]
ope, looks like I just mis linked the issue number. will go update. not related at all

**Comment by o-fernandez** [comment]
@miina is there anything here to test from a UAT perspective? Or is this mainly technical?

**Comment by swissspidy** [comment]
> @miina is there anything here to test from a UAT perspective? Or is this mainly technical?

AFAICT two things to verify:

- Dragging text sets works as expected
- Snapping works (see #1979)

**Comment by miina** [comment]
@o-fernandez -- what Pascal said.
It's mainly technical, however, the logic of dragging changed completely so it would be good to verify briefly that it's still happening as it should be.

**Comment by tmagalhaes-huge** [comment]
This looks good, closing. @samitron7 Maybe we should look into making an improvement so when the user drags a text set on top of a background image, they don't see a white background behind before dropping it? See below.

<img width="1792" alt="Screen Shot 2021-02-18 at 2 58 43 PM" src="https://user-images.githubusercontent.com/73555855/108414165-e3f1c480-71f9-11eb-91ef-c40523bfe980.png">
