### ISSUE TITLE
E2E Tests: Update CI build matrix

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5338]
## Task Description

It would make sense to run the tests against both the latest version of WordPress (5.5 / 5.6 at the time of writing, as well as the oldest supported version (5.3 at the time of writing).

Percy snapshots would probably only need to be taken for the latest one.

**Comment by spacedmonkey** [comment]
I have created a PR in #5423. Unlike the description, I have set the value to 5.4 over 5.3. There are are number of issues with 5.3. So I have create a new [tag](https://github.com/google/web-stories-wp/issues?q=is%3Aissue+is%3Aopen+label%3A%22WP+5.3%22) for adding support. 

I plan to fix these issues and lower the number to 5.3.
