### ISSUE TITLE
Reorganize video settings in design panel

### ISSUE THREAD

**Issue by dreamofabear** [GoogleForCreators/web-stories-wp#5340]
## Bug Description

IMO, the current structure of video settings in design panel doesn't make sense.

- Video settings
  - Loop / play once
- Captions
  - Upload captions
- Accessibility
  - Poster image selector
  - Title (text field)
  - Alt (text field)
  - "Text for visually impaired users." (label)

Issues:
- Captions is an A11Y feature
- Poster image and title are not A11Y features
- The sections should probably be merged

## Proposed Behavior

- Video
  - Playback
    - Loop / play once
  - Performance
    - "Poster:" (label)
    - Poster image selector
    - "Burned-in text:" (`title` and `alt` label)
    - "Enter burned-in text in the video (if any)"
  - Accessibility
    - "Captions:" (label)
    - Upload captions button

Not sure if there's precedence for double-nesting in these sections -- could also divide into "Video playback", "Video performance", "Video accessibility".

References:
- https://blog.amp.dev/2020/02/12/seo-for-amp-stories/

## Steps to Reproduce

N/A

## Screenshots

![Screen Shot 2020-11-18 at 12 16 38 PM](https://user-images.githubusercontent.com/20525523/99564897-007f2600-2999-11eb-85d1-7fc7ca809d8e.png)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by zidianlyu** [comment]
Here are the screenshots that I have in local, please feel free to comment:

![Screen Shot 2020-12-10 at 12 32 53 PM](https://user-images.githubusercontent.com/11252886/101826439-d7f3d300-3ae3-11eb-870f-82742ea4a505.png)

**Comment by dreamofabear** [comment]
Sorry for the churn, let's actually do this:

- Playback
  - Loop / play once
- Poster
  - [Poster selector]
  - "For improved loading experience on slower connections."
- Description
  - [Text field]
  - "For indexability and accessibility. Include any burned-in text inside the video."
- Captions
  - [Captions selector]

**Comment by zidianlyu** [comment]
Here is the update of the UI:

![Screen Shot 2020-12-10 at 11 04 34 PM](https://user-images.githubusercontent.com/11252886/101873620-1f0db280-3b3c-11eb-903f-a70c58a7f655.png)

**Comment by csossi** [comment]
Verified in QA
