### ISSUE TITLE
Change Foreground "Zoom" to "Scale" for users

### ISSUE THREAD

**Issue by maxyinger** [GoogleForCreators/web-stories-wp#5343]
Change the user facing name of the foreground zoom animation effect to be "scale"

**Comment by csossi** [comment]
Verified in QA

**Comment by samitron7** [comment]
Failed in UAT. @littlemilkstudio Can we change the name in the dropdown field to Scale In and Scale out as well. Currently it reads scale in/out the dropdown but Zoom in the dropdown field.

<img width="1022" alt="Screen Shot 2020-11-30 at 11 05 02 PM" src="https://user-images.githubusercontent.com/10889431/100708046-7fdd0400-3360-11eb-942f-6fd841c016f3.png">

**Comment by BrittanyIRL** [comment]
Thanks, Sam, this was me not Max - I created a follow up ticket and will address this today.
https://github.com/google/web-stories-wp/issues/5511
