### ISSUE TITLE
jest run reports "A worker process has failed to exit gracefully ..."

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5345]
## Bug Description

> I’m getting `A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks.`  pretty consistently when running test:js

## Additional Context

https://github.com/testing-library/dom-testing-library/issues/524

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

* Make sure Jest and ti sub-deps are up-to-date
* Remove `@testing-library/dom` from package.json. `@testing-library/react` is enough

**Comment by bmattb** [comment]
trigger for this https://xwp.slack.com/archives/C0134J07HV3/p1605730927000500

**Comment by bmattb** [comment]
requires discovery for estimation

**Comment by bmattb** [comment]
pulled out of sprint as per our review today

**Comment by swissspidy** [comment]
Closing for now, doesn't seem to be an issue anymore
