### ISSUE TITLE
Autoset image/video as bg if user scales it to fit the page

### ISSUE THREAD

**Issue by samitron7** [GoogleForCreators/web-stories-wp#5356]
## Feature Description

Autoset image/video as bg if image/video is stretched to fill the entire page. Impetus for doing this:

1. Prevent users from applying link to an asset that covers the entire page
2. Allow user to set only page color or image and not both. When a full bleed image is place on top of a page and a user attempts to set a page color, there has been confusion as to why the page color has not been set. This is caused by the fact that the full bleed image is obscuring the page.
3. Page can always be selected. When a user sets a page attachment and has a an image that is fullbleed, it is not possible to select the page if they want to edit/remove the page attachment.
4. Performance issues: Avoid situation where a full bleed bg image is set over a bg image

Todo:

- [x] If the page does not have background media, detect if a video/image is resized so that it covers all edges. If yes, set it as a background automatically.
- [x] In terms of keeping properties, it will behave the same way as currently setting media as background.
- [x] Make sure the history works as expected: if the user clicks Undo, it should undo only setting as background.
- [x] Add Snackbar message: "Full bleed images and videos are automatically set as background. Double click to scale and position at any time."

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@agingoldseco @gajasinski Since this is quite an old issue and related to UX/Product then tagging you just in case to confirm if we should move forward with this feature.

If yes, should the media be assigned as background once it covers all edges fully?

Note: I've seen a few cases where the editors don't know that media can be applied to background directly, have resized the image to cover the background and are then unable to select the Page by clicking on it (since the covering media gets selected always instead)

**Comment by agingoldseco** [comment]
I like this idea cause of the issues listed—have any good reasons not to do it come up? 

Wondering if what would trigger auto-background can make a pop-up appear asking if the user wants to make that image a background. I'm not a big fan of pop-ups, but it could give them the option of never seeing the pop-up again and also serve as a quick tip about the "set as background" button on the right side for future use. @miina Would that potentially fix the issue of people not knowing media can be applied to the background?

**Comment by miina** [comment]
> I like this idea cause of the issues listed—have any good reasons not to do it come up?

Not at all, it's a good idea. Just wanted to confirm details for behaviour. 

> Would that potentially fix the issue of people not knowing media can be applied to the background?

Sounds like it could potentially fix the issue but if it allows users to cover the whole page area with media without setting it as background, it might still cause some issues (e.g. not being able to select the Page anymore). But this sounds more like a product question for @gajasinski

**Comment by gajasinski** [comment]
If I set my image/video as a background are there certain things I can/cannot do to it that I might not encounter if it was just stretch across the page and _NOT_ set as the background?

Is there any visual way the user would know their stretched image/video is now the background. Not a fan of pop-ups, so let's try to avoid that path

**Comment by miina** [comment]
> If I set my image/video as a background are there certain things I can/cannot do to it that I might not encounter if it was just stretch across the page and NOT set as the background?

@gajasinski When using a regular element stretched across the background, it can be rotated, it can have opacity, border, corner radius (these last two wouldn't likely be visible though if stretched across the page), and a link can be added to it (so clicking anywhere on that stretched media would trigger the link).

To a background, the user can add Page Outlink and Background audio (which can be added to a background without media as well)

> Is there any visual way the user would know their stretched image/video is now the background.

A snackbar message could be used for just notifying in case that would be enough.

**Comment by gajasinski** [comment]
@miina thanks for this. I'm trying to think through examples of why a user would _not_ want the image set as the background, but instead take up the entire page. 

I think a snackbar message would work. @agingoldseco thoughts?

**Comment by agingoldseco** [comment]
The thing I'm stuck on is opacity for the background, I can see someone wanting to design a story with a translucent image or pattern in the background that they didn't upload to the platform like that. A potential workaround for this is adding an opacity changer to the Page Background panel. Otherwise, do like the idea of a snackbar message too!

**Comment by miina** [comment]
Moving the issue to UX Needed -- mostly needs the Snackbar (and the opacity if we go that way).

Q: Would the media be set as background as soon as it covers all the area of a Page fully? This can happen when either resizing or dragging previously resized media.

**Comment by agingoldseco** [comment]
Considering some real-world examples of this, it's not that I don't think we can/should do it, but we have to think through what happens when someone uses something like a transparent pattern full-canvas and it has to be over a color. It also occurred to me that if we allowed the user to change the full-background image opacity, we'd have to allow them to add a color there too. So would it make sense to allow users to choose a background color _and_ background image? Should we not automatically make an image the background if there's already a user-chosen background color? 

Some other questions—

1. If someone added a link to the image when it was smaller, can we keep it connected when it becomes the background? 
2. If the user gets layer-happy (or confused) and tries to add a second canvas-sized image when there already is one, would we replace the background or keep it a different layer? (I think the latter.)

**Comment by miina** [comment]
> If someone added a link to the image when it was smaller, can we keep it connected when it becomes the background?

It would need to be converted to a Page Attachment then (from regular link to a Page outlink) which could be very unexpected and unnoticeable if a previous Page Attachment already existed. Maybe if it didn't exist before, it could be converted and this also mentioned in the Snackbar message?

> If the user gets layer-happy (or confused) and tries to add a second canvas-sized image when there already is one, would we replace the background or keep it a different layer? (I think the latter.)

If we'd keep it a separate layer then all the issues brought out in the description of this issue that it was originally trying to solve could still happen:
- The whole page could be covered by another layer and the user wouldn't be able to select the Page anymore, this can make the editing experience quite stressful (have seen editors struggling with it)
- In case of adding a link, clicking anywhere would result in following the link (discouraged behaviour)
- Performance: having multiple fullsize media at the same time, if the user is not aware of how to switch / use the background image, they might even not know this at all, and the media below couldn't be seen anyway in the Story.

 Also, if the user is not aware of how to apply a background image in other ways, the user might purposefully try to assign a background image by resizing it large enough, so I'd expect that if it adds the background once, it would generally work like this.

> So would it make sense to allow users to choose a background color and background image?

Initially, the background actually allowed both color and image, I'm not exactly sure what was the specific reason to disallow this and make sure the background media can't have opacity. Wondering if there was a specific reason for not allowing opacity, or it was just a preference.

**Comment by agingoldseco** [comment]
> It would need to be converted to a Page Attachment then (from regular link to a Page outlink) which could be very unexpected and unnoticeable if a previous Page Attachment already existed. Maybe if it didn't exist before, it could be converted and this also mentioned in the Snackbar message?

I could see this either way—if a user is unaware their image is becoming the background when they make it large, and the link disappears, that could also be confusing. Then they have to go find that link again outside of the editor and put it in a new place they may not have been aware of. If those instances outnumber a page attachment link being replaced by an image link (would they?), I wonder if, when that happens, we could just have a rare pop-up asking if they want to replace the page link. 

> If we'd keep it a separate layer then all the issues brought out in the description of this issue that it was originally trying to solve could still happen

Perhaps this would be a happy medium situation, where all of this _can_ happen but they're much less likely to if the first image someone covers the canvas with becomes the background. I hypothesize we would still be cutting instances of these photo issues by more than half, but users who want to add a texture or photo effect layer over a background image would be able to. Problem is I have no idea how common that is—am just wary of taking away that functionality. I'm thinking about how, on platforms like Instagram, adding full-canvas overlays/effects to stories are a HUGE part of their appeal. 

I believe we are implementing layer locking soon—perhaps that, if the user is made aware of it, can help with the page selection issue? I absolutely understand that the issues you've outlined are major, just thinking out loud about how these changes could actually affect use.   

> Initially, the background actually allowed both color and image

Am curious about this too—we can't keep people from being able to use a pattern :/

Do these points make sense? Trying to think about this from all possible angles.

**Comment by miina** [comment]
@agingoldseco Could be, I don't have any insights either into the intended usage of photo effect layer in the editor, I'm happy whichever option you and George choose in this case.

@gajasinski Product thoughts would be helpful here again on Amy's suggestions.

**Comment by gajasinski** [comment]
@miina i need to walk through this issue again as it seems fraught with nuances that could be confusing and also complex to solve if not messaged correctly. We know this is a problem today, but I want to make sure we wouldn't make it worse by implementing the above suggestions.

**Comment by miina** [comment]
@gajasinski Any new thoughts on this? :)

**Comment by andrew-askedall** [comment]
I believe this should cover the outstanding issues: 

The current behavior if a linked image is placed as the background, the link is removed. So this feature would not be a regression. 

If we feel its necessary we could keep the link associated with it but disable the link section of the design panel. A tooltip could read “background images can not contain a link” 

In regards to a transparent .png added as the bg. A user can choose the bg color before adding an image with transparency and that works. But once the image is added, a user can’t change the color without detaching the image. We could add a page color picker under page background if we detect a transparent .png. 

If an additional image is scaled up to the size of the bg it does not replace the current bg if there is one.

**Comment by miina** [comment]
@andrew-askedall Thanks for the details!

> In regards to a transparent .png added as the bg. A user can choose the bg color before adding an image with transparency and that works. But once the image is added, a user can’t change the color without detaching the image. We could add a page color picker under page background if we detect a transparent .png.

I believe the main question was about having a transparent image (not .png but configured to have transparency from the editor) and then setting it as a background. It seems to me now that this, however, a general question and out of scope for this issue -- since currently it's also the same way -- when the user sets a semi-transparent image as background, it will loose the transparency. I'll create a separate issue for that part, to discuss if background media should allow transparency in the editor generally.

**Comment by miina** [comment]
Follow-up issue on the topic of background transparency: https://github.com/google/web-stories-wp/issues/10298

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin, using PR #10458.

1. Added a video
2. Increased width/height to cover canvas - added as background
3. Repeated steps above for gifs and videos - working as expected


https://user-images.githubusercontent.com/96055551/153282891-6dab7b61-93cf-4deb-8495-79e959c1f1f3.mp4
