### ISSUE TITLE
FTUE | Educational | Drag and Drop

### ISSUE THREAD

**Issue by aecheverriam** [GoogleForCreators/web-stories-wp#5358]
## Context

First Time User Experience, or FTUE, helps a new user familiarize themselves with certain parts of the product. We strive to keep the product generally intuitive and easy to understand by following common app patterns. As such, we focus FTUE on a narrow set of features that may be more novel to users and we believe will be useful to the majority of users.

Explaining new concepts
A few concepts in web story creation may be new to users, thus the editor introduces them to the user at the appropriate time. 
 
## Feature Description

1. Drag and drop/masking: 
From product brief:

Drop zones are an expedient way to set a background or apply a mask to a media element. The interaction is intuitive once the user first sees it, but it is not a standard pattern users may have seen. As such, the editor lets users know about drop zones: 

## Alternatives Considered

- The first time the user clicks to add a media element to the page → drag to page borders to set as background. 
- When a user adds a shape to the page → drag any media to shape borders to apply as mask.

## Additional Context

See Ux research

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
@aaecheverria checking in on this and moving to UX needed. This is from November so I'm not sure if it's still relevant?

**Comment by aaecheverria** [comment]
Hi @BrittanyIRL Thanks for checking. This is not relevant anymore since we already released this with FTUE helper menu. 

I'm closing it out!
