### ISSUE TITLE
PHP Refactoring Design Doc

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5359]
## Task Description

- [ ] Create a doc that just outlines all the classes we currently have and what they do?

**Comment by swissspidy** [comment]
@spacedmonkey This is something that becomes more pressing now with all of the new code we'll be merging soon. Maybe we could start with a small doc that just outlines all the classes we currently have and what they do?

**Comment by spacedmonkey** [comment]
While reviewing PHP code, I had some thoughts on moving some of the existing classes around and create some new namespaces. 

Create a new Admin namespace to capasalate functionality only found in the WP Admin. These classes include.
- Activation_Flag 
- Activation_Notice
- Admin
- Meta_Boxes
- Customizer
- TinyMCE

I would also create a new Adtech namespace and add these classes.
- AdSense
- Ad_Manager

I also thought about the idea of having a Post_Type namespace and add these classes. 
- Story_Post_Type ( Rename space to Story ).
- Template_Post_Type  ( Rename space to Template ).

I would also merge Stories_Renderer and Story_Renderer in a Renderer. So
- Stories_Renderer -> Renderer/Stories
- Story_Renderer -> Renderer/Story

**Comment by spacedmonkey** [comment]
I did some research into the amp and sitekit plugin structures. On a close inspection, I believe the format of the AMP plugin, maps to how we layout code in this plugin and should be the plugin we emulate. 

Somethings I noticed. 

The amp plugin treats functionality as a "service". This follows a common pattern in PHP of [service containers](https://laravel.com/docs/8.x/container). So each class is designed for one piece of functionality is contained inside it. This stop classes getting too big. This is not too different to how we are making our classes at the moment. However it would mean, a class like `Story_Post_Type` would be broken up into multiple classes, as this handles, post type register, handling editor script output and capabilities. These would like be better as three classes. The are likely other classes that should be broken up like this to be a little more single purpose. 

If a class needs to register and activation hook/deactivation hook, this is done within the class, but implementing Deactivatable, interface. This is a tidier way of handling different activation hooks. 

A service contain is used spinning up of all classes and registering. A list of the amp plugin's services can be found [here](https://github.com/ampproject/amp-wp/blob/5b37621d971fab9a6a434a11ac4d0c437bcfa1c2/src/AmpWpPlugin.php#L61-L99). This is a much tidier way then just spinning up classes and using class properties, that is currently used in this plugin. 

All services all implement a service interface, that means that WordPress action that the service will be hooked into is defined with the class. If the hook is not [register](https://github.com/ampproject/amp-wp/blob/5b37621d971fab9a6a434a11ac4d0c437bcfa1c2/src/Infrastructure/ServiceBasedPlugin.php#L137-L146), the a new instance of the class is spun up instead. 

There also shared instance of classes that are used for dependency injection. This would be especially useful for the experiments class we injection into many of our classes. 

We using the code found in amp plugin would be pretty simple. It is well written and generic enough to be reused. We could simple copy the [Infrastructure](https://github.com/ampproject/amp-wp/tree/develop/src/Infrastructure) directory to our plugin. When add implements `Service` to all of services, along with what wp hook they should be registered with. Then we just need to convert plugin class to look more like [AmpWpPlugin](https://github.com/ampproject/amp-wp/blob/develop/src/AmpWpPlugin.php). This looks like a lot, but it is just automated what spinning up classes and dependency injection, the classes, for the most part would stay the same. 

As for the above, moving of classes around, this is still [valid](https://github.com/google/web-stories-wp/issues/5359#issuecomment-801856907). It worth noting, that amp plugin for example has an [admin namespace](https://github.com/ampproject/amp-wp/tree/develop/src/Admin) similar to what I suggested.

I would be good to have a chat with the amp team to get there thoughts and feedback. But this is just refactor of existing code and copy things over, it I don't believe it should be too much work.
