### ISSUE TITLE
TypeError: Cannot use editor

### ISSUE THREAD

**Issue by 2bfound** [GoogleForCreators/web-stories-wp#5363]
Hi,

I just wanted to report that i cannot use the editor in the Web stories for WordPress plugin at all.

Is there anything I'm doing wrong? I just want to create a new story and I checked all the boxes in the settings area.

Thank you very much, I'm looking forward for your answer.

**Comment by swissspidy** [comment]
Hi there, thanks  for your report!

Please note that we aim to provide support via [the WordPress.org support forums](https://wordpress.org/support/plugin/web-stories/). But since you're already here:

A few questions:

- What kind of TypeError do you get? Full error message is important.
- Could you perhaps upload a screenshot?
- What browser are you using?
- Could you share your Site Health information with us.

**Comment by 2bfound** [comment]
Hi!

Excuse me, I didn't think of the support area in this case. A screenshot of
the error, when i'm trying to upload an image or choosing one from the
library:
[image: image.png]

I'm using the Chrome browser. Site speed:
[image: image.png]

Hope this helps solving the problem.


Met vriendelijke groet,


   * Bas de Roy | *SEO Specialist
     bas@2bfound.nl <tim@2bfound.nl>
     078 844 52 71


*        2Bfound – Online marketing*
   078 - 8445 271 | 2bfound.nl <http://www.2bfound.nl/>
    Vriesestraat 119 | 3311 NP, Dordrecht


Op vr 20 nov. 2020 om 11:21 schreef Pascal Birchler <
notifications@github.com>:

**Comment by swissspidy** [comment]
Unfortunately uploading screenshots via email does not work. Please use the Github.com website for uploading them.

**Comment by 2bfound** [comment]
![screenshot error - web stories for wordpress](https://user-images.githubusercontent.com/74767687/99946479-b7ebb200-2d76-11eb-9b05-f2e97209c3bd.JPG)
Hi Swisspidy,

I uploaded the error message.

**Comment by swissspidy** [comment]
Thanks @2bfound! When you clicked on "Report Error" and were redirected to GitHub, what was the exact error message you received? Could you paste it here?

Also, does this still happen with all other plugins disabled?

**Comment by 2bfound** [comment]
Sure:
TypeError: Cannot read property 'elements' of undefined

TypeError: Cannot read property 'elements' of undefined
    in StoryProvider
    in Unknown
    in SnackbarProvider
    in Unknown
    in HistoryProvider
    in Unknown
    in Media3pApiProvider
    in Unknown
    in FileProvider
    in Unknown
    in APIProvider
    in Unknown
    in ConfigProvider
    in lK
    in Ge
    in se
    in App
    in StrictMode
    in FlagsProvider

**Comment by 2bfound** [comment]
I can not disable other plugins at the moment, is that nescessary? The Stories plugin is the one I last installed.

**Comment by swissspidy** [comment]
Thanks for sharing the error message.

The idea behind disabling other plugins is to see whether any other plugins cause a conflict. And that error message does in fact suggest such a conflict.

To do so, you can also install the [Health Check & Troubleshooting plugin](https://wordpress.org/plugins/health-check/) and follow the instructions at https://make.wordpress.org/support/handbook/appendix/troubleshooting-using-the-health-check/#troubleshooting-with-a-specific-plugin to troubleshoot the Web Stories plugin.

This way you can use the plugin in way that all the other plugins appear to be disabled, without actually having to disable them.

Also, please share your Site Health information (Tools -> Site Health) with us by using the "Copy to clipboard" button.

**Comment by 2bfound** [comment]
```
### wp-core ###

version: 5.5.1
site_language: nl_NL
user_language: nl_NL
timezone: Europe/Amsterdam
permalink: /blog/%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 15
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/c2bfound/public_html/2bfound.nl
wordpress_size: 1,05 GB (1123779228 bytes)
uploads_path: /home/c2bfound/public_html/2bfound.nl/wp-content/uploads
uploads_size: 2,07 GB (2219099566 bytes)
themes_path: /home/c2bfound/public_html/2bfound.nl/wp-content/themes
themes_size: 14,03 MB (14715233 bytes)
plugins_path: /home/c2bfound/public_html/2bfound.nl/wp-content/plugins
plugins_size: 81,22 MB (85167054 bytes)
database_size: 38,34 MB (40206336 bytes)
total_size: 3,24 GB (3482967417 bytes)

### wp-active-theme ###

name: 2Bfound (2bfound)
version: 1.0
author: Melvin van der Ven & Miljan Janjetovic
author_website: http://illusiv.nl
parent_theme: none
theme_features: core-block-patterns, html5, title-tag, post-thumbnails, soil-clean-up, soil-nav-walker, soil-relative-urls, soil-js-to-footer, soil-disable-trackbacks, soil-disable-asset-versioning, menus, widgets, editor-style
theme_path: /home/c2bfound/public_html/2bfound.nl/wp-content/themes/2bfound
auto_update: Uitgeschakeld

### wp-themes-inactive (1) ###

Twenty Twenty: version: 1.5, author: het WordPress team,Auto-updates uitgeschakeld

### wp-mu-plugins (2) ###

ManageWP - Worker Loader: author: GoDaddy, version: (undefined)
WP Migrate DB Pro Compatibility: version: 1.2, author: Delicious Brains

### wp-plugins-active (21) ###

Advanced Custom Fields PRO: version: 5.9.1, author: Elliot Condon (latest version: 5.9.3), Auto-updates uitgeschakeld
AMP: version: 2.0.5, author: AMP Project Contributors (latest version: 2.0.7), Auto-updates uitgeschakeld
Anti-Spam by CleanTalk: version: 5.147.1, author: СleanTalk <welcome@cleantalk.org> (latest version: 5.149), Auto-updates uitgeschakeld
Classic Editor: version: 1.6, author: WordPress Contributors, Auto-updates uitgeschakeld
Disqus for WordPress: version: 3.0.17, author: Disqus, Auto-updates uitgeschakeld
EWWW Image Optimizer: version: 5.8.0, author: Exactly WWW (latest version: 5.8.2), Auto-updates uitgeschakeld
Formidable Forms: version: 4.08, author: Strategy11 (latest version: 4.09.01), Auto-updates uitgeschakeld
Formidable Forms Pro: version: 4.08, author: Strategy11, Auto-updates uitgeschakeld
Imsanity: version: 2.6.0, author: Exactly WWW (latest version: 2.7.0), Auto-updates uitgeschakeld
Intuitive Custom Post Order: version: 3.1.2, author: hijiri, Auto-updates uitgeschakeld
ManageWP - Worker: version: 4.9.7, author: GoDaddy, Auto-updates uitgeschakeld
Postmark (Official): version: 1.13.3, author: Andrew Yates & Matt Gibbs, Auto-updates uitgeschakeld
Redirection: version: 4.9, author: John Godley (latest version: 4.9.2), Auto-updates uitgeschakeld
SG Optimizer: version: 5.6.8, author: SiteGround (latest version: 5.7.6), Auto-updates uitgeschakeld
Soil: version: 3.7.1, author: Roots, Auto-updates uitgeschakeld
wBounce: version: 1.8.1, author: Kevin Weber, Auto-updates uitgeschakeld
Web Stories: version: 1.1.1, author: Google, Auto-updates uitgeschakeld
WP Migrate DB Pro: version: 1.9.13, author: Delicious Brains, Auto-updates uitgeschakeld
WP Migrate DB Pro Media Files: version: 1.4.15, author: Delicious Brains, Auto-updates uitgeschakeld
Yoast Duplicate Post: version: 3.2.6, author: Enrico Battocchi & Team Yoast, Auto-updates uitgeschakeld
Yoast SEO: version: 15.1.1, author: Team Yoast (latest version: 15.3), Auto-updates uitgeschakeld

### wp-media ###

image_editor: EWWWIO_GD_Editor
imagick_module_version: Niet beschikbaar
imagemagick_version: Niet beschikbaar
file_uploads: File uploads is turned off
post_max_size: 128M
upload_max_filesize: 128M
max_effective_size: 128 MB
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 9.26

### wp-server ###

server_architecture: Linux 3.12.18-clouder0 x86_64
httpd_software: Apache
php_version: 7.1.33 64bit
php_sapi: cgi-fcgi
max_input_variables: 3000
time_limit: 120
memory_limit: 768M
max_input_time: 120
upload_max_filesize: 128M
php_post_max_size: 128M
curl_version: 7.59.0 OpenSSL/1.0.2r
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.6.40-84.0-log
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 38fea24f2847fa7519001be390c98ae0acafe387 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/c2bfound/public_html/2bfound.nl/wp-content
WP_PLUGIN_DIR: /home/c2bfound/public_html/2bfound.nl/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 768M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### amp_wp ###

amp_mode_enabled: reader
amp_reader_theme: legacy
amp_templates_enabled: post
amp_serve_all_templates: This option does not apply to Reader mode.
amp_css_transient_caching_disabled: false
amp_css_transient_caching_threshold: 5000 transients per day
amp_css_transient_caching_sampling_range: 14 days
amp_css_transient_caching_transient_count: 192
amp_css_transient_caching_time_series: 
	20201110: 280
	20201111: 258
	20201112: 230
	20201113: 218
	20201114: 202
	20201115: 192
	20201116: 188
	20201117: 188
	20201118: 188
	20201119: 183
	20201120: 192
	20201121: 192
	20201122: 192
	20201123: 192
amp_libxml_version: 2.7.8

```

**Comment by swissspidy** [comment]
Hi @2bfound, we've released a big update to the plugin that should hopefully address some of this too, would you be able to give it another try?

**Comment by 2bfound** [comment]
Hey Pascal,

Glad to hear from you. I just updated the web stories plugin, but the
editor has crashed again. I'm getting the same message as before the update.


Met vriendelijke groet,


   * Bas de Roy | *SEO Specialist
     bas@2bfound.nl <tim@2bfound.nl>
     078 844 52 71


*        2Bfound – Online marketing*
   078 - 8445 271 | 2bfound.nl <http://www.2bfound.nl/>
    Vriesestraat 119 | 3311 NP, Dordrecht


Op vr 18 dec. 2020 om 11:55 schreef Pascal Birchler <
notifications@github.com>:

**Comment by swissspidy** [comment]
Thanks for the update!

I'd love to get to the bottom of this, but for that I'd need your help. Unfortunately the Site Health info didn't give me any additional clues.

First, could you perhaps try to install this development version real quick? [web-stories.zip](https://github.com/google/web-stories-wp/files/5716372/web-stories.zip). The error report should be a bit more comprehensive that way. (albeit the editor will be a bit slower)

Second, could you open your browser's dev tools (press F12) and observe the "Network" tab for any "XHR" requests that fail when opening the editor?

Third, please install the [Health Check & Troubleshooting plugin](https://wordpress.org/plugins/health-check/) and follow the instructions at https://make.wordpress.org/support/handbook/appendix/troubleshooting-using-the-health-check/#troubleshooting-with-a-specific-plugin to troubleshoot the Web Stories plugin. This will _simulate_ a scenario with all other plugins disabled except for Web Stories. If it works fine in that scenario, we'll know there's a conflict.

Thanks again for your help here.

**Comment by LuckynaSan** [comment]
@2bfound Your topic will be closed as we haven’t received a response. Please feel free to open a <a href="https://wordpress.org/support/plugin/web-stories/#new-post">new support topic</a> in the WordPress Support Forum if you continue to experience any issues. Thank you!
