### ISSUE TITLE
Captions Panel crashes upon video multi-selection

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5365]
## Bug Description

The captions panel does not account for multi-selection, where `tracks` is not an array but instead has the value of `MULTIPLE_VALUE`.

When selecting multiple videos, the whole design panel therefore crashes.

## Expected Behaviour

No crash.

## Steps to Reproduce

Insert multiple videos and select them

## Additional Context

- Plugin Version: 1.1.1 / `main`
- Operating System: macOS
- Browser: Chrome 87

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
adding to sprint and agreed that this can make v1.2

**Comment by csossi** [comment]
Verified in QA

**Comment by o-fernandez** [comment]
didn't crash for me anymore
