### ISSUE TITLE
TypeError: Cannot destructure property 'x' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#5367]
TypeError: Cannot destructure property 'x' of 'undefined' as it is undefined.
    in Provider
    in DisplayLayer
    in div
    in selectionCanvas__Container
    in Unknown
    in ForwardRef(WithOverlay)
    in SelectionCanvas
    in div
    in canvasElementDropzone__Container
    in CanvasElementDropzone
    in div
    in dropTarget__Content
    in Unknown
    in div
    in dropTarget__DropTargetComponent
    in UploadDropTarget
    in CanvasUploadDropTarget
    in section
    in canvasLayout__Background
    in se
    in CanvasLayout
    in Canvas
    in bq
    in div
    in layout__CanvasArea
    in Unknown
    in RichTextProvider
    in Unknown
    in UnitsProvider
    in Unknown
    in CanvasProvider
    in Workspace
    in section
    in layout__Editor
    in Unknown
    in LayoutProvider
    in MJ
    in PrepublishChecklistProvider
    in Unknown
    in DropTargetsProvider
    in Unknown
    in TransformProvider
    in Unknown
    in MediaProvider
    in Unknown
    in FontProvider
    in Unknown
    in StoryProvider
    in Unknown
    in SnackbarProvider
    in Unknown
    in HistoryProvider
    in Unknown
    in Media3pApiProvider
    in Unknown
    in FileProvider
    in Unknown
    in APIProvider
    in Unknown
    in ConfigProvider
    in bq
    in Ge
    in se
    in App
    in StrictMode
    in FlagsProvider

**Comment by o-fernandez** [comment]
I had an image, applied an animation (whoosh In, Left ot Right) then set it as Bg, editor crashed.

**Comment by carloskelly13** [comment]
This ticket seems to be fixed with the work Max has done in his background animations PR. I tested it out and I cannot get the crash anymore.

**Comment by samitron7** [comment]
Verified in UAT
