### ISSUE TITLE
Fully transparent color looks weird

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#5369]
## Bug Description

If you have a fully transparent solid color anywhere (text color, border color, text background color, shape color), the result is really weird in the preview. See screenshots below

## Expected Behaviour

* The preview should somehow reflect the transparent color

## Steps to Reproduce

1. Add a shape
1. Change the color opacity to 0%
1. Observe weird behavior

## Screenshots

![disappearing color and opacity](https://user-images.githubusercontent.com/637548/99828700-4bc83e80-2b29-11eb-8573-96f410d7b01f.gif)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. Show the non-transparent color in color preview
1. Write the actual hex in the editable text field
1. Show the opacity input with 0% as the value

It should work similarly to a fully-transparent gradient:
![Screen Shot 2020-11-20 at 12 14 22](https://user-images.githubusercontent.com/637548/99829216-ff313300-2b29-11eb-8dfc-b9e5d30e46f9.png)

**Comment by zidianlyu** [comment]
Hi team, are we looking for something like this?

![Screen Shot 2020-12-17 at 11 13 23 AM](https://user-images.githubusercontent.com/11252886/102532564-054afe80-4059-11eb-8f61-8ca12de9c4c1.png)

@barklund 
I saw that in the code comment, you put down comment: 'If opacity is 0, no extra styling needed'. Is there any caveat we need to consider about?

**Comment by csossi** [comment]
Verified in QA

![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/1eaeae0b-4e89-467a-8690-d78d5746830f)

**Comment by tmagalhaes-huge** [comment]
Closing. @samitron7 @ivayloklissarov @aaecheverria
