### ISSUE TITLE
Border preview is very different from editor

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#5371]
## Bug Description

The border preview shown in the page carousel is very different from the actual page design due to 5px border being a 5px border regardless of scale. This looks horrible in an extreme case as below with the page thumbnails being the minimum size.

## Expected Behaviour

The border preview in a page thumbnail should at least somewhat represent the actual border on the page

## Steps to Reproduce

1. Add a thick border (10px) with a large border-radius (20px)
1. Observe different in page thumbnail and editor look.

## Screenshots

![Screen Shot 2020-11-20 at 15.01.55.png](https://images.zenhubusercontent.com/5e9877d5cc796e8868614c8d/965c65b6-3694-4a27-b04e-ba74cbc0a733)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. Page preview does not have to be perfect but should be less misleading than it currently is.

**Comment by miina** [comment]
Note: needs implementation for outside border only, the inside and center border are already "responsive" in terms of width. Radius needs a look into for each type.

**Comment by csossi** [comment]
Verified in QA

**Comment by tmagalhaes-huge** [comment]
Looks good, closing. @samitron7 @aaecheverria @ivayloklissarov
