### ISSUE TITLE
Improve the visibility of the alert flag on the Checklist tab

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5373]
## Feature Description

Need an easier way to tell that the checklist has issues. I can’t even see the red alert. Should that red alert have more/stronger contrast? 

Currently here is how it looks:

![Screen Shot 2020-11-20 at 3.33.30 PM.png](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/c1f656ae-ab85-41c4-825d-37a17a81c6c8)

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by samitron7** [comment]
Badging should always be at be at 100% opacity even when the checklist tab is not active. FYI @angelapgUX 
![Screen Shot 2020-11-20 at 11 48 12 PM](https://user-images.githubusercontent.com/10889431/99870843-f755ab00-2b8a-11eb-9a06-2b83528412ce.png)

**Comment by csossi** [comment]
Tested with instructions in 5508 - not seeing the hex value for colour:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/88267aa4-5eed-40f8-9eec-552abd854a90)

**Comment by swissspidy** [comment]
@csossi If you click on the colored square in dev tools you'll get the color value in different formats (RGB, Hex, etc.). `228, 95, 83` in RGB is the same as `#e45f53` in Hex (which is what you saw in Emily's screenshot on #5508. Whether you see RGB or Hex in dev tools doesn't really matter, what we want to verify is that it has 100% opacity :-)

**Comment by csossi** [comment]
thanks, @swissspidy 

Verified in QA
