### ISSUE TITLE
Prepublish checklist "Story Title too long error" triggered on a title less than 200 chars

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5378]
## Bug Description

“Story title too long” error says “should have 200 characters or fewer” but it should say **Story title should have 40 characters or fewer.**

## Expected Behaviour

Error should be triggered when there are over 40 characters in the title and help text should say **Story title should have 40 characters or fewer.**

See [text strings sheet](https://docs.google.com/spreadsheets/d/1PjaRp4bueQ3Cv14A7I696m0vjGCIX_kN9tIGh-V-Bkc/edit?pli=1#gid=0)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
Looking into the spec, I think the issue is with the help text. It should be saying: **Story title should have 40 characters or fewer.**

Updated ticket and marking as high priority
