### ISSUE TITLE
Prepublish checklist is missing a text contrast check 

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5380]
## Bug Description

 In this page, I don’t get any text contrast issues in the checklist even though you can’t read the text. (there’s black text on top of the gray at the top left)

![Screen Shot 2020-11-20 at 4 21 34 PM](https://user-images.githubusercontent.com/58738530/99851404-1b929700-2b4d-11eb-9ba2-f0c94aba9c3d.png) source - https://stories-new-wordpress-amp.pantheonsite.io/wp-admin/post.php?action=edit&post=13581#page=%25225c4f2f9d-21ea-4ffa-a45d-f0707fa3da0f%2522

Funny enough, this triggers the text contrast check issue. So it seems that we are only checking within a specific element, not an element on top of another element, but not sure this merits the low contrast error. 

![Screen Shot 2020-11-20 at 4 27 54 PM](https://user-images.githubusercontent.com/58738530/99851680-77f5b680-2b4d-11eb-81e4-f5605f4cf34a.png)
source - https://stories-new-wordpress-amp.pantheonsite.io/wp-admin/post.php?action=edit&post=13581#page=%25226357900a-5dca-42db-be57-01e066ca78f3%2522

## Expected Behaviour

Error message should be presented in this case

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
@carlos-kelly @choumx seems that we only do a contrast check today in a specific element, but don't check contrast between a text element and the section of the background that the text sits on. I wasn't expecting that, since I think most text contrast issues will be with text and their background, not text and the fill color. Can we look into this? It's OK if this is an enhancement we do post MVP.

But, we probably want to remove the current check for the release as I don't think it's working that well. 

So...
* P0/P1: disable the text contrast check until improved (this ticket)
* P2: improve the text contrast check to check against bg as well. (covered by #5383)

**Comment by swissspidy** [comment]
> seems that we only do a contrast check today in a specific element, but don't check contrast between a text element and the section of the background that the text sits on. I wasn't expecting that, since I think most text contrast issues will be with text and their background, not text and the fill color.

AFAIK this is on purpose, at least according to the various Slack discussions about this. So the current implementation only checks text color against fill color, nothing else, as it was deemed too complex

**Comment by carloskelly13** [comment]
@o-fernandez Pascal is correct. We have experimented with a couple ways to do a canvas render to actually do a contrast test but this will likely need to be an effort in its own right to build in the foundation.

**Comment by dreamofabear** [comment]
> P0/P1: disable the text contrast check until improved (this ticket)

+1. Shouldn't bother checking text contrast without background image support.

**Comment by o-fernandez** [comment]
> > P0/P1: disable the text contrast check until improved (this ticket)
> 
> +1. Shouldn't bother checking text contrast without background image support.

Filed #5525 for this since it doesn't seem there was a ticket for it specifically. Will keep this ticket around for the P1+ of improving the text contrast check inc. bg.

**Comment by swissspidy** [comment]
> P2: improve the text contrast check to check against bg as well.

The scope for that is not 100% clear to me here.

@o-fernandez @choumx Looking at #5568, could you perhaps clarify if we want to simply check the text element against the page background image, neglecting the fact that there could be any number of elements in-between? To me that doesn't sound like a huge improvement over not having any checks at all. I thought we'd want to take the whole background into account here, including e.g. shapes behind a text element.

**Comment by o-fernandez** [comment]
> > P2: improve the text contrast check to check against bg as well.
> 
> The scope for that is not 100% clear to me here.
> 
> @o-fernandez @choumx Looking at #5568, could you perhaps clarify if we want to simply check the text element against the page background image, neglecting the fact that there could be any number of elements in-between? To me that doesn't sound like a huge improvement over not having any checks at all. I thought we'd want to take the whole background into account here, including e.g. shapes behind a text element.

Yes, to me check against bg means that we check holistically vs. anything affecting the colors around the text, not just the bg image. If there's a shape behind the text and the bg image doesn't impact text contrast, then it makes sense to account for the shape. 

A better way to rephrase this may be -- text contrast should check the text color vs. the text surrounding color, be it a bg image colors, text fill/highlight color, shapes colors, etc.

**Comment by swissspidy** [comment]
Makes sense. Then I think this definitely needs a technical design doc/brief to establish a proper architecture.

**Comment by embarks** [comment]
@swissspidy @choumx [Here's my draft](https://docs.google.com/document/d/1qdwI900Ku7XOnqejXxs8c_bjvP9KwXXGqUpCBVFfumk/edit?usp=sharing) for a technical explainer for the current solution.

I have some pieces left to write, such as what I learned about rotating image layers, etc. and some more charts so it's not so dense. I just wanted to get my thoughts down before the weekend. :)

**Comment by csossi** [comment]
Tested in QA env - 5568

Not seeing contrast warning for black text on black portion of background:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/9b823716-c168-463f-8f70-43e062a6a21f)

**Comment by dreamofabear** [comment]
@embarks Can you look into @csossi's repro case?

**Comment by embarks** [comment]
@choumx I wasn't able to repro, so I'm working on making sure the correct code was deployed to QA. :)

**Comment by embarks** [comment]
@csossi let's give it another try. I rebased on the current main and pushed it up. This is what I'm seeing now in QA: 
![Screen Shot 2021-01-05 at 4 00 14 PM](https://user-images.githubusercontent.com/41136059/103709220-50c53e00-4f6f-11eb-891d-18db8d816611.png)

**Comment by csossi** [comment]
Verified in QA

![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/4f2b30b9-e84a-43d8-9c0a-a99b641ce61d)
