### ISSUE TITLE
Prepublish "Too Many links on page" error message is incorrect

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5381]
## Bug Description

Too many links on page shows up only if we add more than 3 links, but the direction/description only says try to keep it to just 1 link. Update help text to: Avoid having more than 3 links per page. 

## Expected Behaviour

Error messaging text should be aligned with the logic behind it -- in this case, update the error message to say: **Avoid having more than 3 links per page.**

## Steps to Reproduce

1. Place more than 3 links on a page to trigger the error 
2. note the text of the error states "Avoid having more than 1 link per page"

## Screenshots
![Screen Shot 2020-11-20 at 4 35 20 PM](https://user-images.githubusercontent.com/58738530/99852156-695bcf00-2b4e-11eb-8112-9f0ffce8c404.png)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by samitron7** [comment]
@o-fernandez Do we want to relax this rule a bit? Product pages tend to have more than a link.

**Comment by o-fernandez** [comment]
@samitron7 the fix here is to only show this if there are more than 3 links. Is that not enough?

**Comment by samitron7** [comment]
@o-fernandez Yes, thanks for updating the help text. Alerting when you have 4+ link it perfect.

**Comment by csossi** [comment]
Hi @carlos-kelly - Im testing in 5417 and am not seeing the error message. Wondering if I'm missing this somehow - where should this message be appearing?

**Comment by csossi** [comment]
Verified in QA

**Comment by samitron7** [comment]
Failed in UAT. The message should read "Avoid having more than 3 links per page."

**Comment by swissspidy** [comment]
@samitron7 Note that this wasn't merged yet (is in QA Passed column, not UAT). The message will be changed to: `Avoid having more than three links per page.`. Could you verify if this OK or if it must be `Avoid having more than 3 links per page.` (three vs 3)

**Comment by o-fernandez** [comment]
> @samitron7 Note that this wasn't merged yet (is in QA Passed column, not UAT). The message will be changed to: `Avoid having more than three links per page.`. Could you verify if this OK or if it must be `Avoid having more than 3 links per page.` (three vs 3)

That would be fine - three vs 3.
