### ISSUE TITLE
Prepublish checklist references "alt" text

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5382]
## Bug Description

Checklist references “alt” text for image/video but we don’t use this terminology elsewhere. “Assistive text” for images and “description” for videos ([after this PR](https://github.com/google/web-stories-wp/pull/5332/files))
![Screen Shot 2020-11-20 at 4 43 27 PM](https://user-images.githubusercontent.com/58738530/99852848-cf952180-2b4f-11eb-960e-d50f39e3ea08.png)

## Expected Behaviour

Updated the text strings as follows: 

- **Image missing assistive text** 
- Add meaningful assistive text to images to optimize accessibility and indexability.

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Tested 5417

Not seeing message for assistive text (for neither image nor vid)
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/6b9eccd0-bbc9-4d70-9a2d-e8964ee91766)

**Comment by swissspidy** [comment]
@csossi That's because images by default have assistive text defined, so you wouldn't see the message. Remove the assistive text from the image first to trigger the message.

**Comment by carloskelly13** [comment]
This was part of https://github.com/google/web-stories-wp/pull/5417 which was approved.

**Comment by csossi** [comment]
Verified in QA
