### ISSUE TITLE
Prepublish checklist contrast error is not triggered on bg images

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5383]
## Bug Description

Text contrast calculation doesn’t appear to account for background images
filed by @choumx 

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Isn‘t this a duplicate of #5380?

**Comment by dreamofabear** [comment]
Duplicate of #5380.
