### ISSUE TITLE
Improve the disambiguation of the errors in the Prepublish checklist

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5384]
## Feature Description

Checklist items don’t disambiguate which text/image element they’re referring to — users have to guess
![Screen Shot 2020-11-20 at 4 50 00 PM](https://user-images.githubusercontent.com/58738530/99853244-9c9f5d80-2b50-11eb-8e31-c17ee9d4ab25.png)
source - https://stories-new-wordpress-amp.pantheonsite.io/wp-admin/post.php?action=edit&post=13581#page=%25226357900a-5dca-42db-be57-01e066ca78f3%2522

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by samitron7** [comment]
Eng was not able to add the thumbnail or truncated string of the offending element in MVP but this will be a fast follow. Once we create the northstar version, we can deprecate this ticket.

**Comment by carloskelly13** [comment]
This is better captured via https://app.zenhub.com/workspaces/web-stories-5e94d3aced449034e1e9b226/issues/google/web-stories-wp/5629
