### ISSUE TITLE
Make amp-story-page ID Easier to Discover

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#5386]
## Feature Description

At the moment, to create a direct link to a specific page in a Web Story, a user has to find the id="" attribute of the <amp-story-page> element of the respective page and insert it in this URL form: https://www.mydomain.com/web-stories/#page=<page-id>

Is it possible to make the page IDs exposed somewhere or easier to discover?

## Additional Context

Related topic: https://wordpress.org/support/topic/direct-link-to-a-specific-story-page/
Related documentation: https://amp.dev/documentation/components/amp-story/?format=stories#branching

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Closing due to low priority, unlikely to be implemented
