### ISSUE TITLE
Prepublish checklist - change the default collapse state of the guidance.

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5399]
## Feature Description

Currently when the creator selects the Checklist tab all recommendations are presented with the accordion for High Priority and Recommended items in the open state :

![Screen Shot 2020-11-23 at 12.12.48 PM.png](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/dc502845-16c0-4471-8650-65acd307f122)

It has been suggested that instead we should present HIgh priority items as open by default, and the recommended items can be collapsed as default.

![Screen Shot 2020-11-23 at 12.08.09 PM.png](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/27580789-5168-48fe-9db7-dfa9793ae6bb)
## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
