### ISSUE TITLE
Prepublish checklist panel width changes depending on accordion status

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5400]
## Bug Description

When reviewing a list of the recommendations in the Prepublish checklist, collapsing the Recommended section seems to change the text spacing in the "High priority" section, and this looks bad

## Expected Behaviour

Collapsing a section of recommendations should not impact the display of other sections

## Steps to Reproduce

1. View a story that has both Critical and Recommended items noted in the prepublish checklist eg https://stories-new-wordpress-amp.pantheonsite.io/wp-admin/post.php?action=edit&post=13243#page=%252217fa9c85-89c7-47d0-a7a8-29f6ef56e161%2522
2. collapse the Recommended section
3. Note the line length / margins on the section above have changed.

## Screenshots

Both sections expanded - last line of High Priority is "3:4 aspect ratio"

![Screen Shot 2020-11-23 at 12 24 36 PM](https://user-images.githubusercontent.com/58738530/99994862-9b0baa80-2d87-11eb-9f02-0dbe60f7f17d.png)

Collapsed Recommended section - last line of High Priority is "maintain a 3:4 aspect ratio" now

![Screen Shot 2020-11-23 at 12 24 44 PM](https://user-images.githubusercontent.com/58738530/99994920-b080d480-2d87-11eb-9a3b-e2169dc53ad5.png)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
@csossi I added some testing details on the PR - https://github.com/google/web-stories-wp/issues/5549

**Comment by csossi** [comment]
Seeing some shifting as I toggle Recommended section
https://share.getcloudapp.com/OAuWBWl1

**Comment by BrittanyIRL** [comment]
@csossi you are correct there's still a shift in the accordion labels. This fix is more focused on the accordion content, per the acceptance criteria above about the shifting paragraph lines being distracting. 
If you look at the screenshot section it supplies more context: 

> Both sections expanded - last line of High Priority is "3:4 aspect ratio"
> Collapsed Recommended section - last line of High Priority is "maintain a 3:4 aspect ratio" now

Fixing the labels to not shift is tricky because the available space for that label is shifting with a scrollbar showing up. This is more just a hold over for the time being. Not the greatest, but it's better than everything moving with the scrollbar showing up on expanding multiple accordions.

**Comment by csossi** [comment]
understood - thanks, @BrittanyIRL 

Verified in QA

**Comment by tmagalhaes-huge** [comment]
Looks good. Would be great to add to the backlog to address the label caret and count badge shifting as well. Understood it's related to the scroll bar @o-fernandez

**Comment by o-fernandez** [comment]
Filed this ticket for the issue Claudio raised above: https://github.com/google/web-stories-wp/issues/5901
