### ISSUE TITLE
Pre-Publish Checklist: Update warning about story description to provide guidance to resolve

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5403]
## Feature Description

Currently when a creator has not provided a story description the prepublish checklist provides a Recommendation as follows:

![Screen Shot 2020-11-23 at 2 16 15 PM](https://user-images.githubusercontent.com/58738530/100005152-8256c100-2d96-11eb-9b56-6de4a57087f8.png)

However, there is no guidance provided on where to set this. 

Additionally, this field is referred to as "excerpt" in the document panel, so there should be some alignment between the field name and the recommendation verbiage.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
@o-fernandez - do you mind providing some updated copy for this?

**Comment by o-fernandez** [comment]
I think that what we need to do is rename "Excerpt" to be Story description, per [this thread](https://docs.google.com/document/d/1ztnv9lmV7BOtQYa8Q6WFLSsegofmRprMDiW0sLVx_10/edit?disco=AAAAK0MFw3M)

If we have the functionality, then "Story description" could be a clickable link that takes you to the right field directly, but that's not necessary for this ticket if not easily feasible. 

@samitron7 @choumx FYI and for any add'l comment.

**Comment by o-fernandez** [comment]
Ok, agreed in the thread to: 

- Update **Excerpt** under Document tab to be **Story Description**
- Correspondingly, we can update this pre-publish checklist text to say: **Missing Story Description** (capitalized to match the field) and the help text can be **Add a Story Description in the Document panel** which would direct people to look at the Document panel, I hope. 

@BrittanyIRL does this work?

**Comment by BrittanyIRL** [comment]
@o-fernandez perfect, thank you!

**Comment by BrittanyIRL** [comment]
@o-fernandez - one thing to clarify before UAT
![Screen Shot 2020-12-02 at 1.29.41 PM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/9b6e2f05-54f7-4b8c-84f1-b42bfe90b33b)

the placeholder text here: "Write an excerpt" and the helper text "Stories with an excerpt tend to do better on search and have a wider reach" - I left these as excerpt because the story itself refers to this as an "excerpt" not a "description" so I thought that having "description" here with the labeling and then "excerpt" in the associated helper text ties the two together. Let me know if you want something different.

**Comment by dreamofabear** [comment]
IMO we should change "excerpt" to "story description" as well.

> **Story Description**
> *Write a description of the story*
> Stories with a description tend to do better on search and have a wider reach.

**Comment by BrittanyIRL** [comment]
![Screen Shot 2020-12-02 at 4 42 57 PM](https://user-images.githubusercontent.com/10720454/100944920-75844c80-34bd-11eb-9c63-ea5047e6944d.png)

@choumx @o-fernandez - this good?

**Comment by o-fernandez** [comment]
> ![Screen Shot 2020-12-02 at 4 42 57 PM](https://user-images.githubusercontent.com/10720454/100944920-75844c80-34bd-11eb-9c63-ea5047e6944d.png)
> 
> @choumx @o-fernandez - this good?

Yeah, looks great!

**Comment by BrittanyIRL** [comment]
@csossi for testing, the accurate text updates by screenshot are in the PR: https://github.com/google/web-stories-wp/pull/5557

**Comment by csossi** [comment]
Verified in QA

**Comment by swissspidy** [comment]
> Ok, agreed in the thread to:
> 
> * Update **Excerpt** under Document tab to be **Story Description**
> * Correspondingly, we can update this pre-publish checklist text to say: **Missing Story Description** (capitalized to match the field) and the help text can be **Add a Story Description in the Document panel** which would direct people to look at the Document panel, I hope.
> 

Just noting that `Add a Story Description in the Document panel.` uses some unusual capitalization. It's not even title case.
