### ISSUE TITLE
Prepublish checklist is double triggering on the "image too small" recommendation on pages with only one video

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5404]
## Bug Description

We are seeing double instances of the "Video or image too small on the page" reccomendation on pages which only have a single video on them. eg - https://stories-new-wordpress-amp.pantheonsite.io/wp-admin/post.php?action=edit&post=13619#page=%252285017c75-2303-4bff-b379-f7626da80bfa%2522

## Expected Behaviour

Error / recommendation should only be triggered once per image on each page

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
