### ISSUE TITLE
Prepublish checklist presenting "Image too small" message on very large shapes

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5406]
## Bug Description

If I make a shape very large and add a masked image, then I still have the image too small message.

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by carloskelly13** [comment]
@bmattb @csossi This might be an older ticket that has been addressed but I no longer see this issue as shown. If this still exists then we can fix it, but I might need more direction or a video of the bug. Thanks!

![Kapture 2021-01-05 at 08.50.59.gif](https://images.zenhubusercontent.com/5ea09bca6a44046f869bafe0/655c7c9f-16bf-4984-9a51-0f543229c1a6)

**Comment by bmattb** [comment]
Closing as this is no longer reproducible and was likely addressed elsewhere.
