### ISSUE TITLE
Text sets with shadows

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5409]
## Bug Description

when I use a text set that has a “shadow” (aka another text element below to create the shadow effect for the time being) and I have a background image set, I lose sight of the gray text element and think I’ve updated the text. Then I add an animation and see a flash of the original text. I know the shadow is pretty, but is it possibly adding confusion for the time being until that’s an option with the text itself that’s harder for users to update? Demo:

![template text returns on animation preview.gif](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/93be78d7-6d3e-4631-9414-638ef6778266)
## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
This was just an observation (i had) during a bug bash. I feel like we can close this and move forward - we'll have updated templates and that should resolve this. It's not a bug.
