### ISSUE TITLE
Animation panel display displays "coming soon" message

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5411]
## Bug Description

The animation panel displays a coming soon message:

<img width="318" alt="Screen Shot 2020-11-23 at 4 15 29 PM" src="https://user-images.githubusercontent.com/58738530/100017022-47f61f80-2da8-11eb-9f6a-11051904de97.png">

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by carloskelly13** [comment]
We can close this as an extra feature flag was enabled on staging. This is not a bug.
