### ISSUE TITLE
Animation on background media should be limited to pan & zoom

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5412]
## Bug Description

Animation of background media is limited to pan and zoom so as to not expose an empty background. 

## Expected Behaviour

1. Images that are set to background should only permit pan and zoom effects
2. Images with existing animations other than pan & zoom that are transformed into background images should have those animations removed

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by maxyinger** [comment]
I believe this is in staging and should be good to move to UAT. Anyone else care to verify?

**Comment by csossi** [comment]
Hi @carlos-kelly - which PR am I testing for this one?

**Comment by swissspidy** [comment]
it sounded like it was already merged, so `main` branch (perhaps with animations feature flag on)

**Comment by carloskelly13** [comment]
Yup. This was a bug ticket created before the background animations story was completed. So a duplicate in a sense.

**Comment by csossi** [comment]
Verified in QA
