### ISSUE TITLE
Animation default easing value is linear

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5413]
## Bug Description

Default easing function is linear, which looks pretty bad. @samitron7 has indicated that default should not be linear for any of the animations

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by samitron7** [comment]
@philipbell is experimenting with a curve to replace the linear one. Meanwhile, cubic-bezier(0, 0, 0.5, 1) is a good placeholder. Please let me know if this doesn't work for some animations.

@carlos-kelly @littlemilkstudio Do we know why this ticket is in UAT?

**Comment by PhilipBell** [comment]
> @PhilipBell is experimenting with a curve to replace the linear one. Meanwhile, cubic-bezier(0, 0, 0.5, 1) is a good placeholder. Please let me know if this doesn't work for some animations.
> 
> @carlos-kelly @littlemilkstudio Do we know why this ticket is in UAT?

Uhh did you mean to @ me? Pretty sure I'm not doing animation curves Lol

**Comment by maxyinger** [comment]
I think this is just an outdated ticket to update our system to use the curves the amp story presets got updated to months ago. I don't think there's any outstanding work on either project that I'm aware of 🤷
