### ISSUE TITLE
Video playback not always working on canvas

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5421]
## Bug Description

A couple of publishers mentioned to us that video playback on the canvas doesn't work (reliably)

## Expected Behaviour

Video playback on canvas should work reliably.

## Steps to Reproduce

1. Insert video onto page from library
1. Drag it around
1. Click play button
1. Notice that nothing happens

## Screenshots

Can't tell from this screenshot but the video playback is simply not happening. Can provide a screencast via Slack.

<img width="1225" alt="Screenshot 2020-11-24 at 15 52 13" src="https://user-images.githubusercontent.com/841956/100110453-3b87ca80-2e6d-11eb-98f0-e5a161f4126d.png">

## Additional Context

- Plugin Version: 1.1.1
- Operating System:
- Browser: multiple

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Both @zidianlyu and I were not able to reproduce the issue, and the screencast made us think that there must be something wrong with the source video (as it doesn't even autoplay in the media library). Maybe it's super big or otherwise broken. Asked the creator for the source image so we know more.

Otherwise, without more information I feel like we have to close this one.

**Comment by zidianlyu** [comment]
After discussion, we think this might be related to media format (i.e. .mov files not playable etc.) And this issue is resolved by: https://github.com/google/web-stories-wp/pull/5121
