### ISSUE TITLE
Animations not preserved when copying elements

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5424]
## Bug Description

When duplicating an element with animation (either by copy-pasting or Cmd+d), the duplicate element has no animation.

## Steps to Reproduce

1. On a page copy an element such as shape/text that have an animation applied to them
2. Copy the element
3. Paste the element back into the editor
4. Observe that the animation on the first element is not applied to the newly created copy of it.

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
