### ISSUE TITLE
Embed block previewing not working WordPress 5.3.

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#5425]
## Bug Description

Embed block doesn't work in WordPress 5.3. 

## Steps to Reproduce

In WordPress 5.3
- Create new post
- Create web stories embed block. 

## Screenshots

<img width="1884" alt="Screenshot 2020-11-24 at 18 03 31" src="https://user-images.githubusercontent.com/237508/100133992-65e28380-2e7f-11eb-8f60-a94a32b32a3d.png">

## Additional Context

The issue seems to be on this [line](https://github.com/google/web-stories-wp/blob/4e698bf7d3383a8e0402eab3690cc8d0d97c582d/assets/src/story-embed-block/block/edit.js#L64). [useViewportMatch](https://github.com/WordPress/gutenberg/blob/0f5a0e38d4621e276a99c7090da4f146becde63f/packages/compose/src/hooks/use-viewport-match/index.js) was commited 8 months ago. It may not be part of 5.3 build. 

- Plugin Version: 1.1.1
- WordPress: 5.3
- Operating System: Mac OS
- Browser: Chrome ( Latest )

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
If `useViewportMatch` is not available we could fall back to `withViewportMatch` from the [`@wordpress/viewport`](https://www.npmjs.com/package/@wordpress/viewport) package.

Example:

```js
import * as compose from '@wordpress/compose';
import { withViewportMatch } from '@wordpress/viewport';

function StoryEmbedEdit({ attributes, setAttributes, className, isSelected, _isResizable }) {
	// ...

	const isResizable = compose?.useViewportMatch('medium') || _isResizable;
}

export default withViewportMatch( { _isResizable: 'medium' } )( StoryEmbedEdit );
```

Or just use `@wordpress/viewport` itself directly.

**Comment by spacedmonkey** [comment]
Doing some more research, there seems to be number other issues in this same file. 

On the component `EmbedPlaceholder`, icon is not support in 5.3 and generates a console warning. 

On the component `ResizableBox`, showHandle is not support in 5.3 and generates a console warning. 

I am going to add these as issues as part of this ticket as well.
