### ISSUE TITLE
Pulse animation is changing the presentation of text

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5427]
## Bug Description

There are some issues with text elements and the pulse animation, where the element slightly jumps before and after the animation plays. And the height also seems to be adjusted slightly, which can be seen when the element has a border - see second page in [this story](https://stories-new-wordpress-amp.pantheonsite.io/web-stories/awesome-animations/). The jumping text is best observed on page 1 in the same story. Not sure if either of these apply to other animation types too.

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
I'm no longer able to duplicate this jump on the screen. Sending to UAT to confirm. There's a strong change this has been fixed as a side effect in some other ticket in the 2 months since this was reported.
