### ISSUE TITLE
Animation popup on wrong side of screen in RTL

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5428]
## Bug Description

When viewing the editor in RTL, the animation popups shows on the wrong side of screen. It is also hard to use in RTL as the box is 10% off the screen. 

## Screenshots
![Screen Shot 2020-11-24 at 1 42 34 PM](https://user-images.githubusercontent.com/58738530/100137830-12f6d500-2e5b-11eb-8e4b-8e1ffd8f600a.png)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA

**Comment by tmagalhaes-huge** [comment]
Looks good. Closing @samitron7 @aaecheverria
