### ISSUE TITLE
Design System: Use new tooltips in editor

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5430]
## Feature Description

Tooltip style when hovering “Publish” (right) doesn’t match provided designs (left):
![Screen Shot 2020-11-24 at 2 27 58 PM](https://user-images.githubusercontent.com/58738530/100142165-7126b680-2e61-11eb-9f11-f6406df5d1b3.png)

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
this got fixed a while back. 
![Screen Shot 2021-07-06 at 12 10 07 PM](https://user-images.githubusercontent.com/10720454/124654202-20ddf100-de53-11eb-89fe-2265a58b5020.png)
