### ISSUE TITLE
New web stories have 2 recommendations right from the start

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5431]
## Bug Description

When a creator makes a new web story and does nothing there are already a number of items in the prepublish checklist which are flagged. We should give users the opportunity to do things before we start correcting them 

Here are the checklist items that are presented immediately upon story creation:

![Screen Shot 2020-11-24 at 2 31 51 PM](https://user-images.githubusercontent.com/58738530/100142607-29ecf580-2e62-11eb-9d7f-084b10e15924.png)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by carloskelly13** [comment]
Do we want to not show any warnings except maybe for title until they've made a single modification or addition to a blank story?

**Comment by BrittanyIRL** [comment]
(this is getting taken care of in #6968)
