### ISSUE TITLE
Prepublish checklist line spacing is incorrect

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5432]
## Bug Description

Line spacing should reflect figma file (14pt/20) - Overall design should be as vertically tight as possible 

## Expected Behaviour

Line spacing should reflect figma file 
![Screen Shot 2020-11-24 at 2 47 47 PM](https://user-images.githubusercontent.com/58738530/100144024-2f4b3f80-2e64-11eb-99a3-a3f201d4e488.png)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
Setting status to blocked since this will be updated when we implement new designs

**Comment by BrittanyIRL** [comment]
Designs have been updated, new version of pre-publish is in staging. Design to confirm.
