### ISSUE TITLE
Panel name / content should be the font size/face 

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5433]
## Bug Description

As per designs the font size & face of the panel names should match that of the contents 
eg: High Priority & Checklist should match font size & face

![Screen Shot 2020-11-24 at 2 52 32 PM](https://user-images.githubusercontent.com/58738530/100144483-d7f99f00-2e64-11eb-8f08-157fbd2cf85e.png)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
Setting status to blocked since this will be updated when we implement new designs

**Comment by BrittanyIRL** [comment]
Designs have been updated, new version of pre-publish is in staging. Design to confirm.
