### ISSUE TITLE
Embed block missing component ToolbarGroup in WP 5.3

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#5447]
## Bug Description

In WordPress 5.3, there is a missing component called `ToolbarGroup`. 

## Additional Context

- Plugin Version: 1.1.1
- WordPress Version: 5.3
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
recco is to confirm what it does and if it doesn't do much stub it in with an empty component.  @swissspidy  to provide additional instructions

**Comment by swissspidy** [comment]
maybe something like this: (untested)

```js
import * as Components from '@wordpress/components';
const ToolbarGroup = Components.ToolbarGroup || FallbackComponent
```
