### ISSUE TITLE
Prepublish checklist changes size on mouse over

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5449]
## Bug Description

The prepublish checklist icon changes size when there is mouseover

## Expected Behaviour

The icon should not change

## Screenshots

![image2.gif](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/fa90f615-dcea-4843-99cf-b9873912a6be)
## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
This has been resolved.

**Comment by csossi** [comment]
Verified in QA
