### ISSUE TITLE
Prepublish checklist notification messages are not the correct color

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5450]
## Bug Description

The messaging to user within the prepublish checklist should have variance in the presentation of the text as follows:

The color of the message should be: 
Title(awesome work): FG (dark) - Secondary
Subtitle (no issues found): FG (dark) - Tertiary

Currently there does not appear to be any variance in the presentation of this text

## Screenshots

Currently:

![image10](https://user-images.githubusercontent.com/58738530/100254657-91fa1500-2f10-11eb-8284-7367b31c3b19.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
Designs have been updated, new version of pre-publish is in staging. Design to confirm.
