### ISSUE TITLE
Animation panel doesn't present an active state when no effect is applied

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5451]
## Bug Description

When a user selects the animation panel and an object without animation (@angelapgUX - can you provide more detail on this issue as I didn't understand)

## Screenshots

![image9](https://user-images.githubusercontent.com/58738530/100255736-e6ea5b00-2f11-11eb-9f35-3d4490074f78.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by maxyinger** [comment]
As far as I know, this involves:
- updating `no effect` when active to have a purple background like in designs
- not closing the effect panel when choosing a new effect selection

Let me know if this involves anything else

**Comment by csossi** [comment]
Verified in QA
