### ISSUE TITLE
Animation panel appears in incorrect location

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5453]
## Bug Description

When many tabs are open the animation panel appears up to the animation section so there is no context where the panel animation belongs to. (@angelapgUX  - can you provide some additional detail on this issue please)

## Screenshots

![image6 2020-11-25 11_38_19](https://user-images.githubusercontent.com/58738530/100256627-003fd700-2f13-11eb-8879-043a3d054a41.gif)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
Suggested update to solve this in the existing structure here: https://github.com/google/web-stories-wp/pull/5503 

Pending 👍  from @angelapgUX  

(We've been chatting in slack, posting here for posterity and inclusion)

**Comment by BrittanyIRL** [comment]
hey @angelapgUX / @o-fernandez  / @samitron7  

could I get one of you to confirm that this interim solution to get a "label" onto the open animation effect dropdown is ok? I'd love for it to be done for this release.  It's just the "Select Animation" on top of the "No Effect" button. 

![](https://user-images.githubusercontent.com/10720454/100662037-9871fd80-3311-11eb-94f2-fb597dce0682.png)

**Comment by BrittanyIRL** [comment]
Tadeu and I discussed this in slack today and he is ok with this solution with the current implementation. 

@csossi for testing: 
1) There should be a visible "Select Animation" bit of text right about the "None" button (formerly, and in the above screenshots "No Effect")
2) If you test with a screen reader, when you expand the list of available animations should announce "Available Animations To Select"

**Comment by csossi** [comment]
Verified in QA

**Comment by samitron7** [comment]
@BrittanyIRL and I chatted offline and adding our convo here. This quick fix is ok but we'll run into this issues for all the dropdown so I filed a more robust solution [here](https://github.com/google/web-stories-wp/issues/5835).

**Comment by tmagalhaes-huge** [comment]
@samitron7 Ok to close this ticket since you opened a new one for a more robust solution?

**Comment by swissspidy** [comment]
> @samitron7 Ok to close this ticket since you opened a new one for a more robust solution?

sounds like it!
