### ISSUE TITLE
Prepublish checklist chevrons are in the wrong location

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5454]
## Bug Description

As discovered during the UX bug-bash the accordion chevrons should be left aligned, currently they are on the right

![image7](https://user-images.githubusercontent.com/58738530/100258304-e901e900-2f14-11eb-8294-43b48e360cb5.jpg)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
Setting status to blocked since this will be updated when we implement new designs

**Comment by BrittanyIRL** [comment]
Designs have been updated, new version of pre-publish is in staging. Design to confirm.
