### ISSUE TITLE
Design Safe Zone is stuck

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5456]
## Bug Description

The design safe zone should appear and disappear much like the snap guides. Currently, while using the editor the design safe zone will remain stuck on screen even when you are have nothing selected. 

## Expected Behavior
The expected behavior is for the design safe zone to appear and guide you as you move an element around. The minute you let go of the element, the design safe sone should disappear.

## Steps to Reproduce

1. Add an image and resize it to fit the design safe zone
2. Position so that the design safe zone appears
3. Unselect the element and observe that the design safe zone remains frozen on the page.

![Screen Shot 2020-11-28 at 7.19.37 AM.png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/7504cfa7-d49b-4cbc-b8c0-5b9507c50ec8)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by samitron7** [comment]
@bmattb Updated the description!

**Comment by csossi** [comment]
Verified in QA
