### ISSUE TITLE
Video Controls: Uncaught TypeError

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5457]
## Bug Description

When fiddling around with video elements there can be a TypeError in this code:

https://github.com/google/web-stories-wp/blob/88676979cad547698d0aa3be01b9e8a04510e459/assets/src/edit-story/elements/video/controls.js#L183-L184

`videoNode` might not exist at this point.

## Expected Behaviour

No error should occur

## Steps to Reproduce

Not yet clear how to reproduce. Try moving a video around, panning/zooming, playing it, etc.

## Screenshots

<img width="408" alt="Screenshot 2020-11-25 at 17 58 40" src="https://user-images.githubusercontent.com/841956/100260054-431ca180-2f49-11eb-93df-2941557f0122.png">
<img width="476" alt="Screenshot 2020-11-25 at 17 58 58" src="https://user-images.githubusercontent.com/841956/100260061-46179200-2f49-11eb-8493-75146205c1d3.png">

## Additional Context

- Plugin Version: 1.1.1
- WordPress Version: 5.6
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
@zidianlyu Perhaps you can reproduce or even fix this? Using `videoNode?.paused` would be a quick fix, but curious to know the root cause of this...

**Comment by zidianlyu** [comment]
Got it! I will take a look.

**Comment by zidianlyu** [comment]
I tried the following cases, but cannot reproduce the issue:

Insert videos and play
1. Insert from left panel
2. Choose from Media Library
3. Upload from uploader and invert into page
3. Upload to uploader, close and reopen uploader, choose from Media Library

Zoom and move around
1. Move the video and set it to full screen in the background and play
2. Set video overlap and play
3. Multi-select videos and hit play


@swissspidy my suggestion for now it not change anything, what do you think?

**Comment by swissspidy** [comment]
Works for me 👍  Seems to be quite the edge
