### ISSUE TITLE
Default justification is not shown for all text element

### ISSUE THREAD

**Issue by samitron7** [GoogleForCreators/web-stories-wp#5463]
## Bug Description

Default justification hilite state (on design panel) is not shown for all text element

## Expected Behaviour
Every text element should have a default justification hilite state in the design panel.

## Steps to Reproduce

Add any text presets to the page (H1, H2, H3..etc) and noticed that none of these have a default justification hilite state in the design panel. Same situation with some text element in the text sets.

![Screen Shot 2020-11-25 at 10.36.24 PM.png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/39b51138-4967-4a76-82dd-03a58c3f2db4)
![Screen Shot 2020-11-25 at 10.34.22 PM.png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/404957e7-bb86-475e-9afb-b97ef4d362f7)

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Closing as this seems to be working fine currently.
