### ISSUE TITLE
Image edit mode: Frame snaps to original size when attempting to crop image

### ISSUE THREAD

**Issue by samitron7** [GoogleForCreators/web-stories-wp#5464]
## Bug Description

Image edit mode: Frame snaps to original size when attempting to crop image

## Steps to Reproduce

1. Add an image/video to the page
2. Enter edit mode and attempt to crop the image
3. Observe that cropped frame snaps back to the size of the image.

![imadeEditModeWeirdness.gif](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/ecffe4be-9b63-4e8a-8594-d110e18c7332)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Got fixed within #7363
