### ISSUE TITLE
Dashboard - UI Components

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#547]
## Feature Description

Build the UI components for the dashboard

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

- [x] Buttons
- [x] Pills
- [x] Dropdown
- [x] Grid
- [x] Icons 
- [ ] Popover Menus 
- [x] Typeahead
- [x] Grid Item (just the base ui component) 
- [x] responsive search (just the search icon, expands when active)
- [x] bookmark type chip

**Comment by BrittanyIRL** [comment]
popover menus will be completed in page work
