### ISSUE TITLE
TypeError: Cannot read property 'elements' of undefined

### ISSUE THREAD

**Issue by TimesIndiaNews** [GoogleForCreators/web-stories-wp#5486]
TypeError: Cannot read property 'elements' of undefined
    in StoryProvider
    in Unknown
    in SnackbarProvider
    in Unknown
    in HistoryProvider
    in Unknown
    in Media3pApiProvider
    in Unknown
    in APIProvider
    in Unknown
    in ConfigProvider
    in hH
    in ThemeProvider
    in StyleSheetManager
    in App
    in FlagsProvider

**Comment by swissspidy** [comment]
Hi there,

Thanks for your report! Do you recall the last action you took before this error appeared? Does it still happen with all other plugins disabled?

**Comment by swissspidy** [comment]
Hi there,

I'm closing this for now since we haven't gotten any feedback. If it still happens with the latest 1.2.1 version of the plugin, please let us know.
