### ISSUE TITLE
Design System: Add long form snackbar message

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#5490]
## Feature Description
Create a new snackbar version for longer messages where the following is true: 
Cta should still be docked to the right and vertically centered. 
See #4957  for more context. 

## Additional Context

https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3398%3A83619

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by samitron7** [comment]
@BrittanyIRL Correct me if I'm wrong but this ticket might have been completed already? The design for a 2-line snack here is here in [Design Sys](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3398%3A83619) and [Stories experience](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=1983%3A3). FYI, we should avoid lengthy messages stretching pass 2 lines.

**Comment by BrittanyIRL** [comment]
i think we need to adjust this still because the dismiss early button was added after the initial component was created. We'll pull snackbar updates in next sprint and fix these both.

**Comment by samwhale** [comment]
This is fixed by https://github.com/google/web-stories-wp/pull/6220

**Comment by samwhale** [comment]
https://google.github.io/web-stories-wp/storybook/?path=/story/designsystem-components-snackbar--default
