### ISSUE TITLE
Duplicate Checklist Message re: Low Image Res

### ISSUE THREAD

**Issue by csossi** [GoogleForCreators/web-stories-wp#5491]
Started a new story and added only 1 image. When I inspect checklist, there are TWO messages re: image resolution (copy for message is slightly diff for each though saying the same thing):

![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/395a1a7f-a347-494e-bde3-ff37f07a0488)

**Comment by BrittanyIRL** [comment]
@embarks can you confirm that this is resolved?

**Comment by embarks** [comment]
@BrittanyIRL Yes, this is fixed. I only see the one. :)
![image](https://user-images.githubusercontent.com/41136059/103805956-8ae71c00-5011-11eb-97a9-0820ec98e802.png)

**Comment by csossi** [comment]
Verified in QA
