### ISSUE TITLE
Design System: Responsive tweaks to banners

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#5495]
Missed some smaller viewports and text isn't respecting the block breaks, see: https://github.com/google/web-stories-wp/pull/5224#issuecomment-734352521 

Add necessary breakpoints and text wrap.

**Comment by BrittanyIRL** [comment]
Hey @samitron7 question for ya - 

I remember discussing how the banners should be a fixed height for each dashboard and editor, to fix the breakpoint issues with text overflowing, how do you want to handle smaller viewport sizes? Like this for example: 

<img width="531" alt="Screen Shot 2020-11-30 at 2 43 45 PM" src="https://user-images.githubusercontent.com/10720454/100669355-7df05200-331a-11eb-806f-b8c075bf7979.png">

Given the nature of the product this hardly feels like a large portion of users, but I wanted to check with you for your preference. Should we allow the height to grow or do you want to maintain the rigid height?

I think allowing the height to grow for those cases is probably the most malleable?  There's some screenshots here: https://github.com/google/web-stories-wp/pull/5504

**Comment by samitron7** [comment]
Yes to allow for scaling for the smaller breakpoints.

**Comment by ivayloklissarov** [comment]
I've had a look and banners are now responsive. Closing the ticket.
