### ISSUE TITLE
Pre-Publish Tab & Checklist v1.1

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#5498]
Pre-publish checklist follow ups from MVP to be included in the next major release (1.3.0)

- When a user clicks on a checklist item, they should be taken to the offending element/page and field (e.g., if missing description open item with description field highlighted)
- Show preview thumbnail of impacted item.

**Comment by o-fernandez** [comment]
@carlos-kelly to link the tickets to this.

**Comment by BrittanyIRL** [comment]
Version 1.1 of pre-publish checklist is complete.
