### ISSUE TITLE
Baseline RTL Support

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#55]
## Feature description
The editor should support languages that are RTL.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jauyong** [comment]
Editing my comment, I see from the feature sheet this is a 1.1 not 1.0

**Comment by jauyong** [comment]
Should this be put on pause as it is a 1.1? @swissspidy

**Comment by pbakaus** [comment]
Not required. 1.1 feature.

**Comment by pbakaus** [comment]
But if @swissspidy is close and want to merge his initial thing, I'm not opposed.

**Comment by swissspidy** [comment]
Yeah I only started it because it was rather easy, despite the lower priority.
The remaining part is a bit of a blocker though, but merging this current state could help think of RTL in advance the future. Basically gets us 95% there.

**Comment by spacedmonkey** [comment]
I think we should merge what we have in #351 and create a follow up ticket to get the final 5%. I am worried if we leave it as it is, it will become unmergable as the code base is in such flux still.

**Comment by swissspidy** [comment]
@spacedmonkey I was about to comment the same 🙂 Wanna review the PR again?
