### ISSUE TITLE
Dashboard Foundation

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#550]
## Feature Description

Foundational work for dashboard, utils, navigation

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

- The ability to navigate between the different sections of the dashboard defined by the designs.

**Comment by carloskelly13** [comment]
I am taking this one and starting with the page navigation work.

**Comment by jauyong** [comment]
@carlos-kelly would it be possible to add some AC or notes so we can define the outcome of this issue?

**Comment by carloskelly13** [comment]
Able to verify the navigation and header is deployed to https://stories-new-wordpress-amp.pantheonsite.io/
