### ISSUE TITLE
Animations don't play immediately on selection

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5500]
## Bug Description

An animation should play immediately on the page once you select and applied an option from the drop down menu. Additionally updates such as direction changes, duration, delays, etc. should also play immediately.

## Expected Behaviour

Applying or changing an animation should be previewed in the editor immediately.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Duplicate of #5357?

**Comment by csossi** [comment]
Animation is playing immediately upon selection of animation type, but not for other selections (duration, delay, etc.)

https://share.getcloudapp.com/2Nu050Dr

**Comment by carloskelly13** [comment]
I just verified this works, I was able to do what your video did and see the animation play.

**Comment by csossi** [comment]
Verified in QA
