### ISSUE TITLE
Duplicating a page with an animation on it causes the editor to crash

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5501]
## Bug Description

When duplicating a page with an animation on it, the editor crashes. This happens for bg image with zoom effect as well

## Expected Behaviour

not this, that's for sure

## Steps to Reproduce

This was noted by @o-fernandez  on this page here specifically: https://stories-new-wordpress-amp.pantheonsite.io/wp-admin/post.php?post=13900&action=edit#page=%25221bf764b1-48ba-4b35-bfa3-db93c6e87240%2522

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA

**Comment by o-fernandez** [comment]
Not crashing! :D
