### ISSUE TITLE
3 scrollbar in the Author dropdown

### ISSUE THREAD

**Issue by samitron7** [GoogleForCreators/web-stories-wp#5509]
## Bug Description

There are 3 scrollbars in the Author dropdown (2 vertical bar and 1 horizontal bar)

## Expected Behaviour

There should only be 1 vertical scrollbar

## Screenshots

![Screen Shot 2020-11-30 at 11.23.59 PM.png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/946c8e8d-08f3-4325-b884-2a125f777e4b)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
cc @miina

**Comment by BrittanyIRL** [comment]
new scrollbar styles have resolved this.

![now there are two](https://user-images.githubusercontent.com/10720454/111338990-9f105080-8634-11eb-98eb-0a6fa979ca89.gif)
