### ISSUE TITLE
Animation Panel: Dropdown update to read scale in/out not zoom

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#5511]
## Bug Description
Follow up from #5343 
> Can we change the name in the dropdown field to Scale In and Scale out as well. Currently it reads scale in/out the dropdown but Zoom in the dropdown field.

## Expected Behaviour

Dropdown to read scale in/out not zoom

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
