### ISSUE TITLE
Animation Panel - No effect styling is incorrect

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5513]
## Bug Description

Change the styling of No effect to google sans. This cta should not be visually similar to the rest of the animation options. [Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=1687%3A8065)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by maxyinger** [comment]
I think this is a duplicate and taken care of with this PR:
https://github.com/google/web-stories-wp/pull/5586
