### ISSUE TITLE
Disabled Animations should have a tool tip to provide context on unavailability

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5514]
## Bug Description

Add tooltip to any animation options that is disabled to make it clear to users why it’s disabled.

If an image/video is too small to support an animation direction (ie pan up or down), disable it and provide a tooltip, do not remove it. Users may not understand that the options are still available. 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
