### ISSUE TITLE
Animation directionality is not presented to the user correctly. 

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5515]
## Bug Description

Animation directionality is not presented to the user correctly. 

## Expected Behaviour

The directionality of the animation should be reflected in the animation input field. (ie if you selected pan left from the dropdown, the input field should read Pan left. If you change animation direction using the direction UI (the arrows), the direction should also be reflected in the animation dropdown input field. 

[Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=2320%3A247381)

## Screenshots
Current:
![Screen Shot 2020-12-01 at 1 48 18 PM](https://user-images.githubusercontent.com/58738530/100783538-e8b59200-33db-11eb-9cd9-c55fc2245c62.png)

Expected:

![Screen Shot 2020-12-01 at 1 47 34 PM](https://user-images.githubusercontent.com/58738530/100783489-d76c8580-33db-11eb-92c1-4bb990ebfda6.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by maxyinger** [comment]
I believe this got fixed a sprint or 2 ago. Should no longer be an issue

**Comment by bmattb** [comment]
confirmed no longer an issue.
