### ISSUE TITLE
Animation Pulse label should be single line

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5520]
## Bug Description

Currently:
![Screen Shot 2020-12-01 at 2 36 15 PM](https://user-images.githubusercontent.com/58738530/100788126-a9d70a80-33e2-11eb-972c-3cab92c9325f.png)

## Expected Behaviour

"# of Pulses" should be presented on a singe line

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by maxyinger** [comment]
included in this PR:
https://github.com/google/web-stories-wp/pull/5587

**Comment by csossi** [comment]
Tested in 5587 - still on 2 lines:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/686331dc-50dc-4c20-81e8-54122dc25558)

**Comment by maxyinger** [comment]
> Tested in 5587 - still on 2 lines:
> [screenshot]

Weird. on mine I'm getting one & I see the change in the PR. I'll rerun CI on it
<img width="377" alt="Screen Shot 2020-12-08 at 12 11 09 PM" src="https://user-images.githubusercontent.com/35983235/101530068-a8f82880-394e-11eb-9817-f18edcfa15c0.png">

**Comment by swissspidy** [comment]
Since #5587 was already merged, I verified expected behavior on `main`:

<img width="421" alt="Screenshot 2020-12-09 at 10 19 17" src="https://user-images.githubusercontent.com/841956/101610152-26cc3a80-3a08-11eb-8274-112420c972d4.png">
