### ISSUE TITLE
Animations - update the background zoom effect to new designs

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5521]
## Feature Description

There are new updated designs for the background zoom effect that need to be implemented - [Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=1923%3A424212)

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA

**Comment by ivayloklissarov** [comment]
All animations are synced from Figma to the platform. Closing the ticket. @tmagalhaes-huge
