### ISSUE TITLE
Dates: editor and dashboard not using WordPress timezone

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#5522]
## Bug Description
The time stamped in the editor displays the user's local time instead of the timezone set in WordPress. Notice the timestamps in the below screenshots:
- User 1 who drafted the story in PST: https://jmp.sh/XPocoVG
- User 2 who accessed the story in EST: https://jmp.sh/Lk6FPC2
Both users' timezone was [set to Los Angeles in WordPress settings](https://jmp.sh/Cn6oZ0x).

## Expected Behaviour

The editor should use the timezone from the WordPress timezone.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Fine for the Honalulu case, but for Moscow "Schedule" appeared rather than "Publish"
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/8a80312a-2d9a-49fd-a319-2221589be117)

**Comment by swissspidy** [comment]
@csossi Good catch! This should be fixed now. Could you try again? Thanks!

**Comment by csossi** [comment]
Verified in QA
