### ISSUE TITLE
Pre-Publish Checklist: Disable the text contrast check until improved

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#5525]
## Bug Description

Until #5380 is fixed, we should disable the "text contrast" check in the pre-publish checklist. Showing a text contrast issue without checking for actual bg, just fill, is rarely useful and more confusing. 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Still seeing message:

![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/c518f007-a6a0-4575-b60d-ab84c627313e)

**Comment by embarks** [comment]
@csossi I'm not able to reproduce what you're seeing on my branch... I think perhaps it failed to build so you're not seeing the most recent version. I'm going to rerun the checks and put it back to QA when there's more success there. :)

**Comment by csossi** [comment]
that seemed to do it, @embarks - all good

Verified in QA
