### ISSUE TITLE
Default scale value for pulse animation is not large enough

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5526]
## Bug Description

Default scale for pulse animation is almost not visible.

## Expected Behaviour

A default value that presents the animation correctly should be provided 

## Screenshots

Current default scale value:

![Screen Shot 2020-12-01 at 3 01 02 PM](https://user-images.githubusercontent.com/58738530/100791407-371c5e00-33e7-11eb-868b-114fb786daef.png)

What this looks like:
![Screen Recording 2020-12-01 at 3 11 19 PM 2020-12-01 15_12_29](https://user-images.githubusercontent.com/58738530/100791856-ca559380-33e7-11eb-9fc8-79febfa739e0.gif)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by maxyinger** [comment]
This is what amp-story has for their presets, but I agree this is unnoticably small. We can update to whatever tho since nothing prohibits us code wise from deviating from the amp animation defaults/presets

**Comment by bmattb** [comment]
@samitron7 - Is there an updated default value for this that you'd like to recommend?

**Comment by maxyinger** [comment]
Ope, realizing now that we have some small calculations I missed in here that make it slightly smaller than the amp preset value. Will push up an update shortly to make it match the amp preset and if that's still not satisfactory, I can update again

**Comment by maxyinger** [comment]
^^ above PR makes it so whatever is in the `scale` input is true to the deviation you see in the `pulse` animation. Before we were multiplying the input by `0.1` which was making it go from `0.995 -> 1.005`, but removed that so now if you have `scale: 0.05` in the editor input it should now be true to animation scale deviation and be `0.95 -> 1.05` which amp uses as it's preset value

**Comment by csossi** [comment]
Verified in QA
