### ISSUE TITLE
Remove Inside and Center border options

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5529]
## Bug Description

We don’t need the 3 options for borders (inside, center, outside). Remove and keep to just “outside” as the default/only option. 

## Expected Behaviour

Borders should now only permit outside as an option

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
switching this to enhancement as this is a change from previous direction, not a bug.

**Comment by csossi** [comment]
Verified in QA
