### ISSUE TITLE
Border radius editor view and preview mismatch

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5530]
## Bug Description

Border radius, view in editor and in preview looking very different. 

## Expected Behaviour

Editor and preview should appear the same

## Screenshots
![image6](https://user-images.githubusercontent.com/58738530/100793610-654f6d00-33ea-11eb-83fe-95206ece9327.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
As [the discussion around this continues](https://meet.google.com/linkredirect?authuser=0&dest=https%3A%2F%2Fxwp.slack.com%2Farchives%2FC01ESBB8ZN1%2Fp1607360542003900), I need to flag that this is not ready for sprint, and is being pulled from Sprint backlog and is in jeopardy of not being completed in time for the v1.2.1 release next week.

**Comment by miina** [comment]
The conclusion from Slack discussion: We will implement border-radius with % and keep the border-width in px -- we can look into responsive border-width separately later.

**Comment by csossi** [comment]
Verified in QA
