### ISSUE TITLE
Border & Border radius control update

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5531]
## Description

Borders & Border Radius: from conversation, make border-radius and border follow a similar pattern as padding - one input field that changes all 4, only show all 4 options (each side/corner) if the user “unlocks”. 

Design in [Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=1391%3A118).

NB: Make sure that the lock-buttons are the exact same HTML elements both locked and unlocked so that keyboard focus stays on the button when pressed (the former is the easiest way to implement the latter).

**Comment by bmattb** [comment]
As with #5530 this is in danger of not making it for next week's v1.2.1 release as there is still outstanding design needed here.

**Comment by csossi** [comment]
Verified in QA

**Comment by o-fernandez** [comment]
Looks great!
