### ISSUE TITLE
Prepublish checklist tooltip on previously published stories does not display

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5532]
## Bug Description

“There are items in the checklist to resolve” tooltip
Doesn’t display over “Update” button (if story is already published)
Too subtle

## Screenshots

Before publish:
![Screen Shot 2020-12-01 at 3.56.31 PM.png](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/e8f1a8c4-0109-4e8b-aa38-d6f3d5682018)

After publish (now an update)
![Screen Shot 2020-12-01 at 3.56.22 PM.png](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/bdc214a2-5237-40d3-8b47-9703ee450665)
## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA

**Comment by o-fernandez** [comment]
@carlos-kelly @csossi I still don't see any warning in the "update" button if there are checklist warnings/errors. Can you clarify what's expected? I'm testing in 

https://stories-new-wordpress-amp.pantheonsite.io/wp-admin/post.php?action=edit&post=14849#page=%2522e3579ada-1fb7-453f-ba1c-2a5666d58b44%2522

![image.png](https://images.zenhubusercontent.com/5e98486db524b82fc96aeaf6/bc20cc1b-ed52-4c2c-95b7-b92a4cec319d)

**Comment by Cecil921** [comment]
@carlos-kelly @csossi There is still no warning but is the message an expected action for hoverstate only for the update button?

**Comment by o-fernandez** [comment]
@carlos-kelly @csossi @BrittanyIRL I still don't see anything here, what is this ticket/fix meant to capture?

**Comment by BrittanyIRL** [comment]
Well, it should look like this PR specifies: https://github.com/google/web-stories-wp/pull/5548 

but it appears that in the time this passed QA and revising for UAT something happened and it got overwritten.

**Comment by BrittanyIRL** [comment]
New ticket or send this one back?

**Comment by swissspidy** [comment]
> New ticket or send this one back?

@BrittanyIRL New ticket in this case.

**Comment by ivayloklissarov** [comment]
Just as heads up, I have tested and the bug is still there.

**Comment by BrittanyIRL** [comment]
@ivayloklissarov thanks, there's a follow up ticket since the issue resurfaced, you can see it linked above your comment (also here: https://github.com/google/web-stories-wp/issues/5972) so the fix is in ready for QA and hasn't been merged so it's not on staging quite yet.

**Comment by ivayloklissarov** [comment]
Working good, closing the ticket.
