### ISSUE TITLE
Selecting the text in the animation dropdown triggers the dropdown to re-open

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5533]
## Bug Description

With the dropdown open, clicking the dropdown again (so the text above the list of options), will weirdly re-open the dropdown. This should just close the dropdown.

Actually, if at all possible, please reuse the regular “advanced dropdown” component (which might require some extension to allow the unusual layout of items, but maybe not even that) - then many of the above issues will be (almost magically) fixed (keyboard stuff, highlight stuff, re-opening bug).

## Screenshots

![Screen Recording 2020-12-01 at 4 06 29 PM 2020-12-01 16_08_45](https://user-images.githubusercontent.com/58738530/100797060-89fa1380-33ef-11eb-8c3b-b497533f3771.gif)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by tmagalhaes-huge** [comment]
Looks good. Closing. @samitron7 @aaecheverria
