### ISSUE TITLE
Update animations to retain the animation direction and not the one set by the rotation

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5534]
## Feature Description

A rotated item with a drop-animation “drops” in the rotated direction and not in the “natural” top-to-bottom direction. 

The above also goes for fly-in, whoosh-in, and rotate-in effect. If you rotate an element 90 degrees and apply “fly-in” ,”whoosh-in” or “rotate-in” from left, the element actually flies/whooshes/rotates in from the top.

As per discussion from @littlemilkstudio 

> Right now we're animating a wrapper element that's a child of, & taking up the full size of the top level static positioning container. This approach leads to these stacked transforms you're seeing.
> 
> I think fixing this will require rethinking our targeting approach for animation elements, but I want to be considerate in not causing regressions for composing animations in the future.
> 
> I think this requires some further discussion and would be happy to chat about it, but don't see an "easy" fix beyond disabling animation options when there is certain transforms present on the element

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by maxyinger** [comment]
this is a duplicate of #5601

Which is in QA ready rn. I'll move this one there too

**Comment by csossi** [comment]
Duplicate

**Comment by tmagalhaes-huge** [comment]
Looks good. Closing @samitron7 @ivayloklissarov @aaecheverria
