### ISSUE TITLE
Duplicating a template page with animations produces a duplicate with unselectable page elements

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5535]
## Bug Description

When duplicating an existing template page w/ animations, the page duplicates, but none of the elements are selectable and the animations are not playable. If you click back to another page then return, the elements are selectable, but the animations still don’t run.

## Expected Behaviour

Duplicating a template page should duplicate the page, it's elements should be selectable, and animations should play.

## Steps to Reproduce

1. Select a template with animations built in to use
2. select a page with animations to duplicate, and duplicate it
3. result is a page without any selectable elements, and no animation playback - eg - https://stories-new-wordpress-amp.pantheonsite.io/wp-admin/post.php?post=14111&action=edit#page=%2522cee84355-e1f1-4371-a09b-7862a2c2bbda%2522
## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
This is a duplicate of #5424  and will be addressed by that issue, so closing this.

**Comment by maxyinger** [comment]
@bmattb 

>This is a duplicate of #5424 and will be addressed by that issue, so closing this.

Sorry should've been more clear in description. This is different functionality than #5424 . This is for the functionality to use the duplicate page button, whereas #5424 is for copy and paste (although similar, they use different code under the hood)

Anyway, 5424 still needs to get QA'd and merged
