### ISSUE TITLE
Enable browser spell checking with spellcheck=true

### ISSUE THREAD

**Issue by dreamofabear** [GoogleForCreators/web-stories-wp#5538]
## Bug Description

Spell checking is a top partner FR. We should consider enabling browser spell checking on editable text, starting with text elements.

For text elements, this should be as simple as setting [spellCheck](https://draftjs.org/docs/api-reference-editor/#spellcheck) in `<Editor>` under `edit-story/components/richText/editor.js`.

## Expected Behavior

- Browser spell check is enabled for text elements.

## Steps to Reproduce

- Add a new text element with some misspelled words. 
- Notice that browser spell check is not enabled (no red squiggly line under misspelled words).

## Screenshots

N/A

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
If we could make sure any text input field except URL all get spell check that'd be great: 

- title
- story excerpt/summary
- image accessibility text
- video title/accessibility text/description
- media search text box - both WP library and 3P media search

For text elements in the canvas, I'm torn on whether we should only display the squiggly line when the user is not editing the text box. It can be annoying to see squiggly lines if you are not editing the text -- thoughts? @samitron7

**Comment by samitron7** [comment]
I wouldn't display the squiggly line when not editing. I think it's enough if we catch text errors when it's happening (ie edit mode) and bonus if we can do autosuggest tooltip.

**Comment by dreamofabear** [comment]
We can try only toggling it on text elements when they have focus.

**Comment by csossi** [comment]
Verified in QA
