### ISSUE TITLE
E2E Tests: Improve poster generation tests

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5540]
## Task Description

This is a follow-up to #5249 to address a few points:

1. Need a test for _uploading_ a new video via the WordPress media modal.  
  This was not covered by  #5353 as `insertWebmVideo.js` only inserts an existing video.
1. Need to reset data between tests in `insertWebmVideo.js`.  
  A poster will have been generated already when the first test runs, so any checks for poster generation in the following tests are pointless.\*

\* Actually, the poster will likely be generated already way earlier, the first time the editor is opened during tests, because of this code in the media library:

https://github.com/google/web-stories-wp/blob/c170896a31487c8c55a234f3f770baf5b5d076f6/assets/src/edit-story/app/media/local/useContextValueProvider.js#L157-L183

**Comment by spacedmonkey** [comment]
As part of #5103 I added a little helper to upload files in the WordPress media library. See [fileUpload.js](https://github.com/google/web-stories-wp/pull/5103/files#diff-204b5f718fe65c5a08e6d8771548403c7e49c70b878fbfa65f4e07104927cc07). Maybe we could use something like that.

**Comment by swissspidy** [comment]
Yeah definitely. That helper in particular is one  I wanna look at a bit more closely, as I wanna see how other projects are doing that.

**Comment by spacedmonkey** [comment]
Adding a helper to upload a file within the editor is hard. Both the WordPress (wp.media) dialogs and editor self use drag and drop for file upload. This, as I understand is hard to emulate in an e2e test. But @barklund might have some thoughts on the matter.

**Comment by spacedmonkey** [comment]
Worth noting that puppeteer does not support drag and drop out of the box. See https://github.com/puppeteer/puppeteer/issues/1376

Any solution is going to use input[type=file] somehow.
