### ISSUE TITLE
Video posters: use taxonomy instead of post meta

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5545]
## Feature Description

Using `web_stories_is_poster` for posters hurts performance. Would be better to use a custom taxonomy.

See #5316

Needs a migration in `Database_Upgrader` 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
Could we reuse the existing taxonomy. We already have a hidden taxonomy called [media source](https://github.com/google/web-stories-wp/blob/main/includes/Media.php#L134-L144) added to attachments. We already set the media source to [editor](https://github.com/google/web-stories-wp/blob/7cf07181c4a39995df3552a4f50b86036c2b43af/assets/src/edit-story/app/uploader/useUploader.js#L120-L125). We could either add to existing terms, making it `['editor', 'video-poster']` or just set it to `'video-poster'`. This would mean very simple implementation.

**Comment by swissspidy** [comment]
Good idea! We could extend the list of allowed terms to `['editor', 'video-poster']`, and then set the source accordingly. Until we have a migration in place, we could set both the is_poster meta key _and_ the term.
