### ISSUE TITLE
Pre-Publish Checklist: Add a badge or indicator when there are issues

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#5547]
## Bug Description

Add a badge/some indicator that's stronger in the publishing button for MVP.

https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=2172%3A244419.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
