### ISSUE TITLE
Prepublish Checklist - remove feature flag and do a holistic QA on the feature set

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5554]
## Feature Description

Now that the Prepublish checklist is fairly good shape, let's remove the feature flag and have it QA'd

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. The strings noted in this document can be used as a guideline to behaviour and expected messages presented to the user - https://docs.google.com/spreadsheets/d/1PjaRp4bueQ3Cv14A7I696m0vjGCIX_kN9tIGh-V-Bkc/edit?pli=1#gid=0
2. Please review all active bugs against this issue first so as to understand where know issues exist - https://github.com/google/web-stories-wp#workspaces/web-stories-5e94d3aced449034e1e9b226/board?labels=bug%20bash%3A%201.2,group%3A%20pre-publish%20panel&notFullScreen=false&repos=235435637&showPRs=false&showClosed=false

**Comment by csossi** [comment]
Verified in QA

Issues logged in new tickets

**Comment by o-fernandez** [comment]
Closing as we've already done plenty of testing on this feature (UAT)
