### ISSUE TITLE
Animations MVP - remove feature flag and do holistic QA

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5556]
## Feature Description

Now that animations v1 is approaching ready for deployment,  we should remove the feature flag and test it.

Please note:

1. There are existing known issues with some of the functionality, and these have been identified and prioritized, with P0 bugs being addressed as part of the v1.2 release, and all others being addressed later. Please review this list to understand what has already been identified - https://github.com/google/web-stories-wp#workspaces/web-stories-5e94d3aced449034e1e9b226/board?labels=bug%20bash%3A%201.2,group%3A%20animations&notFullScreen=false&repos=235435637&showPRs=false&showClosed=false

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA

Issues logged as new tickets
