### ISSUE TITLE
Embed block: not working for non-pretty permalinks

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5560]
## Bug Description

As @kkalarickal just found out, the embed block does not work for URLs with non-pretty permalinks. The reason for that is a lack of URL-encoding.

While investigating this, I also realized that embedding local stories with plain permalinks did cause extra HTTP requests, even though we have some logic in place to avoid that (using `url_to_postid()`). Turns out `url_to_postid()` does not recognize plain permalinks like `https://example.com/?web-story=my-story`. It only looks for `https://example.com/?p=123` and pretty permalinks.

## Expected Behaviour

Embedding local stories with plain permalinks should work, and should not cause an extra HTTP request.

## Steps to Reproduce

1. Disable pretty permalinks in the settings
1. Add new embed block in Gutenberg and try to embed local story

## Additional Context

- Plugin Version: 1.1.1
- WordPress Version: 5.6
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Finding that I have to select the EMBED button twice:
https://share.getcloudapp.com/KoullEgk

**Comment by swissspidy** [comment]
@csossi thanks for testing! I think you've uncovered another issue here that is unrelated and needs to be fixed separately of this. Since it is otherwise working as intended, that's a sign this change here does what it has to.

**Comment by swissspidy** [comment]
@csossi I am able to reproduce this error, but it also happens with pretty permalinks, so definitely not related.

**Comment by swissspidy** [comment]
The reason is testing with a story that has neither title nor poster.

**Comment by swissspidy** [comment]
Filed here: #5617

**Comment by csossi** [comment]
thanks for the info, @swissspidy 

Verified in QA
