### ISSUE TITLE
Story embedded on AMP page displays larger than non-AMP page

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#5562]
## Bug Description

A story embedded on an AMP page displays larger than a story embedded on a non-AMP page.
AMP enabled: https://jmp.sh/ySDYRXQ
AMP disabled: https://jmp.sh/chnTgHn

## Expected Behaviour

Story shouldn't enlarge on AMP version of the page.

## Steps to Reproduce

Embed a story with AMP disabled. 
View it and notice size of story.
Enable AMP and view the story again. Notice enlargment. 

## Additional Context
Site URL:  https://www.sunskitchen.biz/?amp
Story URL: https://www.sunskitchen.biz/web-stories/amp-enabled/
Related WordPress topic (with AMP site and large story): https://wordpress.org/support/topic/optimize-webstory-images/

- Plugin Version: 1.1.1
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

* Use `intrinsic` layout option for `amp-story-player` everywhere

**Comment by swissspidy** [comment]
Seems like we need to use `intrinsic` layout instead of `responsive` here:

https://github.com/google/web-stories-wp/blob/a3648a06b57c1af90cd73a75d0b8448a9e5a3d2b/includes/Story_Renderer/Embed.php#L100-L109

Reference: https://amp.dev/documentation/guides-and-tutorials/learn/amp-html-layout/layouts_demonstrated/

**Comment by swissspidy** [comment]
cc @westonruter correct me if I am wrong

**Comment by westonruter** [comment]
The `intrinsic` layout will ensure that the player does not get larger than the supplied `width`/`height`, but it will resize to be smaller if the container is smaller than those dimensions. Nevertheless, for some reason `amp-story-player` does not currently allow the `intrinsic` layout: 

https://github.com/ampproject/amphtml/blob/fc76c7607e6aa64e9465527c37f342a105b00947/extensions/amp-story-player/validator-amp-story-player.protoascii#L32-L38

**Comment by swissspidy** [comment]
Yeah that's exactly what we'd want. Odd though that it's not supported. Filed an issue: https://github.com/ampproject/amphtml/issues/31432

**Comment by spacedmonkey** [comment]
<img width="1884" alt="Screenshot 2021-01-18 at 12 04 29" src="https://user-images.githubusercontent.com/237508/104913884-2ff4e380-5986-11eb-8855-393d020240e6.png">

Changing layout to `intrinsic` didn't work by itself, it meant that nothing shows. 

So we need to work on different solution. 

CC @westonruter @swissspidy for ideas as they know the amp spec better than me.

**Comment by swissspidy** [comment]
@bmattb FYI moving out of sprint as it's currently blocked

**Comment by spacedmonkey** [comment]
Seems like https://github.com/ampproject/amphtml/pull/32371 and https://github.com/ampproject/amphtml/issues/32040 are now merged.

**Comment by swissspidy** [comment]
Yes, saw the notifications. Will take a couple of weeks for this to get to stable.

**Comment by csossi** [comment]
Verified in QA

Non-Amp:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/9359605f-f7a4-46e9-b2a4-2302428a4358)

Amp:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/867509c2-83b2-465d-a786-0b90155d2e67)
