### ISSUE TITLE
Allow role privacy to be customized

### ISSUE THREAD

**Issue by johnsiciliano** [GoogleForCreators/web-stories-wp#5569]
IMHO, it would be really useful to be able to pick the roles that can view the stories, instead of just saying "Public" or "Private"

This is helpful for creators who have different roles set up on wordpress (i.e. subscription sites)

**Comment by swissspidy** [comment]
Is this something you‘d be using yourself? Subscription sites usually have dedicated plugins that enable this kind of functionality, so it seems counter-intuitive to duplicate such efforts.

**Comment by swissspidy** [comment]
Closing for now as this is out of scope and can be resolved with dedicated plugins like "Members" and similar.
