### ISSUE TITLE
Animation: Update Page Autoadvance calculation

### ISSUE THREAD

**Issue by maxyinger** [GoogleForCreators/web-stories-wp#5590]
Right now behavior is:
- if animation or media present, use max duration of either for page duration
- if neither is present, use auto advance duration for page duration

We want to update to:
- use the max of auto advance duration, media duration and animation duration
- this only applies if the story is set to auto-advance, if set to manual advance then ignore all this. :)

**Comment by o-fernandez** [comment]
Looks good! Can we fit in this fix for the release on Wednesday? @carlos-kelly @littlemilkstudio @choumx

**Comment by maxyinger** [comment]
> Looks good! Can we fit in this fix for the release on Wednesday?

yea absolutely! I'll put up a PR for this rn

**Comment by csossi** [comment]
Verified in QA
