### ISSUE TITLE
Unable to Create Story From Template The response is not a valid JSON response. 

### ISSUE THREAD

**Issue by vinipineschi** [GoogleForCreators/web-stories-wp#5591]
## Bug Description

**I´ve tried to use the plugin but it isn´t working. I can neither select a template nor publish a story from scratch.**
This error message below pop-ups every time I try to use it: 
**Unable to Create Story From Template
The response is not a valid JSON response.**

This error below pops up every time I try to publish a new story:
**Failed to save story**

 

## Additional Context

- Plugin Version: 1.1.1
- WordPress Version: 5.5.3
- Operating System: macOS Big Sur
- Browser: Chrome
- PHP version: 7.4

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Hi there,

Thanks for your report.

Does this still happen with all other plugins disabled?

Is your site behind a Web Application Firewall like Succuri or Cloudflare?

**Comment by vinipineschi** [comment]
Hi, thanks for answering.

Hmm, I didn't try it because I have contactform7, jetpack, and other native plugins of my website theme running. Should I disable all of them?
About the second question, yes, I am using the extra security mode of Dreamhost. It is not Cloudflare, I guess the name of the WAF is OWASP mod_security.

**Comment by vinipineschi** [comment]
Hi, I´ve just uninstalled my WAF and now it is working. Thanks.
However, let me know when you guys fix that error because I am not sure if it is a good idea to run a website without WAFs. 
Cheers

**Comment by swissspidy** [comment]
Glad to hear that helped! An alternative to fully disabling the WAF is to disable it only for certain routes, for example `/wp-json/web-stories/v1`.

With that said, our next release will include some compatibility improvements in this area. This way you won't need to do any of that.

If there are still issues with our upcoming release and the WAF, please let us know in the [support forums](https://wordpress.org/support/plugin/web-stories/).

Thanks!

**Comment by vinipineschi** [comment]
Great tip! Thanks for the help Pascal.

See you
