### ISSUE TITLE
Ability to  preview story cover/poster image in the editor

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#5593]
## Feature Description

Currently, when I create and publish a Web Story I don't have a way to see what the story preview would look like in other surfaces or in the embed blocks we have created. This leads to many publishers not setting an appropriate story cover image or including one that has burned-in text, etc. 

Propose that in the editor's preview and publishing flow, we make sure that the user can preview how their story would look like in other surfaces such as Discover storytime or similar. It should follow the standards of: 

1. Show the story cover/poster image
2. Include title and relevant metadata overlaid

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
@aaskedall  Flagging that this requires UX direction in prep for next sprint, thank you!

**Comment by BrittanyIRL** [comment]
@o-fernandez We need more info on this before we can commit to it in 1.12

**Comment by o-fernandez** [comment]
I think we can punt on this if the designs are not ready, but @aaskedall can TAL and chime in re: timelines.

**Comment by bmattb** [comment]
Pulled the 1.12 release tag as this will not be in there and is not a roadmap item for this release

**Comment by BrittanyIRL** [comment]
This will be done with #10115 !!

**Comment by BrittanyIRL** [comment]
Think the new publish modal covers this! 
<img width="266" alt="Screen Shot 2022-03-01 at 9 11 31 AM" src="https://user-images.githubusercontent.com/10720454/156205458-dc70b081-220d-4082-b6f8-c15bb1660039.png">
