### ISSUE TITLE
Animation: Update rotation effect inputs to match latest figma designs

### ISSUE THREAD

**Issue by maxyinger** [GoogleForCreators/web-stories-wp#5600]
For the rotation effect, the latest designs remove the `angle` and `rotations` inputs we currently have. This will simplify user experience and remove some bugs where these inputs allow the user to deviate from our animation contract.

https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=1923%3A424212

**Comment by csossi** [comment]
Verified in QA

**Comment by tmagalhaes-huge** [comment]
@littlemilkstudio This looks good to me. Are we not including "auto easing" for now? I see it in the Figma designs but not on the panel in the editor.

**Comment by maxyinger** [comment]
> @littlemilkstudio This looks good to me. Are we not including "auto easing" for now? I see it in the Figma designs but not on the panel in the editor.

Yeaup, I believe that was deprioritized in the last release that included animation work. I think there's a ticket for adding that easing input to all animations somewhere tho

**Comment by ivayloklissarov** [comment]
Looking all good to me, closing the ticket. @tmagalhaes-huge
