### ISSUE TITLE
Animations: Include element rotation in effects that necessitate off screen coordinate calculations

### ISSUE THREAD

**Issue by maxyinger** [GoogleForCreators/web-stories-wp#5601]
Right now effects that need to calculate offscreen coordinates don't take into account if the element has a top level rotation. This can lead to miscalculations leaving elements partially onscreen before their animation plays.

**Steps to reproduce:**
-> Create a new story or edit existing one
-> Add a square shape to the current page
-> Under the `size & position` panel, give the element a rotation of `34deg` and a height and width of `200x200`
-> Under the animation panel apply the `rotate` from the right effect
-> Add a `delay` to the animation of `5000ms`
-> click preview and see that the element doesn't start completely off the canvas

**Completion**
Completion of this task involves accounting for this rotation in all animation effects that need off screen coordinate such that the element starts off the page.

**Comment by maxyinger** [comment]
I want to explore prefixing all the non-leaf node targeting effect transforms with a counter rotation then postfixing them with the original rotation. Something like this:

```js
function someAnimationEffecct({
  element,
  ...,
}) {
  const keyframes = [
    transform: `rotate(${-1 * element.rotation}deg) translate3d(...) rotate(rotate(${element.rotation}deg))`,
    transform: 'none',
  ]
}
```

This should allow all of our calculations to be computed in a non-rotated coordinate space, then reapply the rotation after necessary calcs are complete. I also think this should retain composability with nesting multiple effects. If both of those statements prove to be true, could make animating rotated elements just work :tm: without needing extra fancy math or behavior :tada:

**Comment by csossi** [comment]
Tested in 5632

Followed steps above:
-> Create a new story or edit existing one
-> Add a square shape to the current page
-> Under the size & position panel, give the element a rotation of 34deg and a height and width of 200x200
-> Under the animation panel apply the rotate from the right effect
-> Add a delay to the animation of 5000ms
-> click preview and see that the element doesn't start completely off the canvas

Still seeing starting point on canvas:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/a3063804-29a5-49fa-a10e-e2084f5581a0)

**Comment by ivayloklissarov** [comment]
I have tested and I am still seeing the issue. I've seen that the ticket has been closed but opened again. Just wanted to check the status on this @littlemilkstudio

**Comment by maxyinger** [comment]
Ah yeaup. I think is a result of two separate issues. the first being what we fixed, which is:
- when you rotate an element then apply an animation to it, the animation direction is not affected by the elements rotation.

The second which still seems to be causing the issue to persist is:
- off screen coordinates should be calculated using the longest point of the geometry from the center

so we should be using the distance between the center and a corner in our calculations, not half the width.

**Comment by maxyinger** [comment]
@ivayloklissarov thanks for catching this.

 I can create a separate ticket to track that second behavior update I mentioned above and link it here. or we can just use this one. @BrittanyIRL any preference?

**Comment by BrittanyIRL** [comment]
@littlemilkstudio Let's track it separately - if you could create a new ticket that would be great!

**Comment by ivayloklissarov** [comment]
We've had a talk with Sam concerning this. I will close the ticket as it's not a major blocker.
