### ISSUE TITLE
PHP Tests: ensure no errors on PHP 8

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5609]
## Feature Description

Follow-up to #5608 / see #4789

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
I have done testing locally and I can't see any errors. As they are no php unit tests, can we mark this as done or do we need it validated by QA?

**Comment by swissspidy** [comment]
Yeah if there are no issues we can of course close it :-)
