### ISSUE TITLE
Animation panel: effect dropdown navigate with arrow left/right

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#5616]
Currently the animation effect dropdown allows navigation by arrow up and down which is in line with standard dropdown functionality, however because this dropdown sometimes can appear to have 2 options in one "line" (as it is a grid) we should allow navigation by left/right arrow as well. 

More info here: https://github.com/google/web-stories-wp/pull/5615#issuecomment-742033724 

Acceptance Criteria: 
- Using the left and right arrows in the animation effect dropdown allows navigation of effects like up and down arrows.

**Comment by csossi** [comment]
Verified in QA

**Comment by tmagalhaes-huge** [comment]
This works well, closing it @samitron7 @aaecheverria @ivayloklissarov
