### ISSUE TITLE
Embed block: story without title requires two clicks to embed

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5617]
## Bug Description

Embedding a story without title requires two clicks to embed.

## Expected Behaviour

Embedding a story without title should work with a single click.

## Steps to Reproduce

1. Publish a new story without title nor content.
1. Create a new blog post and insert a Web Stories block
1. Paste story URL
1. Click on embed button
1. Get "Sorry, this content could not be embedded" message  
  The HTTP response will be 200 with `{"title":"","poster":""}`
  Because of this line, this message will be triggered:
  https://github.com/google/web-stories-wp/blob/d1fceaac02bdd901a5e9471a84591bbd1a80031c/assets/src/story-embed-block/block/edit.js#L107
1. Click on embed button again
1. See that story successfully embedded

## Screenshots

https://share.getcloudapp.com/KoullEgk

## Additional Context

- Plugin Version: 1.2.0
- WordPress Version: 5.6
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

* Changing `setCannotEmbed(!data?.title);` to `setCannotEmbed(!(typeof data?.title === 'string'));`

**Comment by spacedmonkey** [comment]
I think this is the same bug as https://github.com/google/web-stories-wp/issues/5446 . I couldn't replicate as I always put a title on. 

See should add a e2e test for this.

**Comment by swissspidy** [comment]
I thought that one was on WP 5.3 specifically and was fixed.

But yeah a test would be good.

(Even though I wish we had unit tests here. I'll need to look into setting this up again...)
