### ISSUE TITLE
Animation - Link Appears on Page When Video Has a Delay

### ISSUE THREAD

**Issue by csossi** [GoogleForCreators/web-stories-wp#5620]
## Bug Description

Set an Coverrr video with a drop animation with a 3 second delay. On Previewing, the link icon appears right away on its own for the 3 seconds before the video drops in

## Expected Behaviour

Expected link to appear only when video does

## Steps to Reproduce

- create/edit story\
- select an Coverr video from third party category
- set animation with a delay (i had set to 3000ms)
- preview

## Screenshots

https://share.getcloudapp.com/xQuYYBO6

(icon appears on its own for a sec or two here)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System: Win10
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Hey @csossi,

This doesn't appear to be an icon that we use anywhere in the editor. Links don't generally have any visible icon unless you tap on them. Then it looks like this:

<img width="469" alt="Screenshot 2020-12-10 at 09 47 32" src="https://user-images.githubusercontent.com/841956/101748355-bb986c00-3acc-11eb-8d85-9307760e2014.png">

Are you perhaps using a browser extension or anything?
