### ISSUE TITLE
E2E Tests: Improve cleanup between tests

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5623]
## Task Description

In `bootstrap.js` there's an existing section where we can do cleanup before and after tests, but we're not actually doing any of that.

https://github.com/google/web-stories-wp/blob/4a2e1784b2ca64f3d1e1f8621df17c1f7446e509/tests/e2e/config/bootstrap.js#L224-L248

Let's fix this to avoid issues with test order, Percy flakiness, etc.

This includes things like deleting stories, posts, uploaded media.

Caveat: doing this via the UI is slow. So it's easier to do this via a helper plugin in `tests/e2e/plugins`

**Option A**

1. Create a new helper plugin in `tests/e2e/plugins` that, upon activation, resets everything.
2. In `beforeAll` and `afterAll`, activate & immediately deactivate that plugin.

**Option B**

1. Create `tests/e2e/mu-plugins` and change `docker-compose.yml` and `install-wordpress.sh` to mount this directory & chmod it correctly.
1. Create a new mu-plugin that registers a REST route that resets everything (e.g. like this https://github.com/google/site-kit-wp/blob/80c932da36bc35fae7637015e4ba31099979d543/tests/e2e/mu-plugins/e2e-rest-credentials.php)
2. In `beforeAll` and `afterAll`, call that REST endpoint to reset everything.

Advantage: A simple HTTP request is faster than activating & deactivating a plugin.

**Alternative**

Every test itself could be responsible for doing cleanup, but that is easily forgotten.

**Comment by swissspidy** [comment]
This is what Gutenberg does:

https://github.com/WordPress/gutenberg/blob/4086795396720c2f0f6d5f6bef844e67ba4cac90/packages/e2e-tests/config/setup-test-framework.js#L219-L220

https://github.com/WordPress/gutenberg/blob/4086795396720c2f0f6d5f6bef844e67ba4cac90/packages/e2e-tests/config/setup-test-framework.js#L219-L220

Edit: we do that now too before starting tests

https://github.com/google/web-stories-wp/blob/0994fd1808777a2907e3369c5f93f85438cedb3a/tests/e2e/config/bootstrap.js#L239-L240

**Comment by spacedmonkey** [comment]
I noted in #5849 that we now have helpers to add and remove media. I think we should stop importing image and video files on e2e setup and only upload files when they are needed for a test and then delete the after is complete. 

That along with deleting stories after each test case would go a long way to this goal.

**Comment by swissspidy** [comment]
> I think we should stop importing image and video files on e2e setup and only upload files when they are needed for a test and then delete the after is complete.

Hmm I always found it useful to have _some_ media files readily available for tests just in case.
