### ISSUE TITLE
Story title input is very small

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5628]
## Bug Description

The display of the story title in the editor is limited to 23 chars, whereas our guidance in the Prepublish checklist is to keep the title less than 40 chars.

There seems to be a mismatch in what we recommend, what we permit, and what the editor will display to the user.

## Expected Behaviour

1. Unsure if this was intentional - @samitron7 ?

## Steps to Reproduce

1. In the editor create a story with a title that is longer than 40 characters
2. Note that the editor only displays 23 chars
3. Note that the prepublish checklist correctly advises the creator to limit the title to 40 chars.

## Screenshots

![68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3565613038356534373034653732633061393963363939372f33643235343939642d323036342d346165312d386439332d333734316439303634366661](https://user-images.githubusercontent.com/58738530/101800444-48e2bd00-3adb-11eb-8baf-a409734e824a.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by carloskelly13** [comment]
This could be as simple as making the input field larger or adjusting the check to match the size of the input field.

**Comment by swissspidy** [comment]
Duplicate of #41 I believe

This has come up many many times before, e.g #4755
