### ISSUE TITLE
Pre-Publish Panel: Select the offending element from the list

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#5629]
## Feature Description

An item in the list should be able to select an issue and it take you to the offending element and (ideally) highlights the right thing to modify (e.g., if title missing it takes you to the title, if image missing alt text it opens the image with focus in the alt text section in the design panel, etc.)

This ticket is step 1; step 2 for reference since it's a sequential body of work.
**1. The first step is selecting the element and switching to that page if required**
2. The second step is if a fix exists in another panel, like missing assistive text, switching to that panel and then focusing the text box.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA (#5836)
