### ISSUE TITLE
Pre-Publish: Missing Image Description Showing when a Description Exists

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#5630]
## Bug Description

https://github.com/google/web-stories-wp/pull/5585#issuecomment-742544132

I have been unable to recreate this issue and it could be a data model inconsistency error.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Looks like more people are running into this, just got a report from a publisher about this.

**Comment by carloskelly13** [comment]
@swissspidy Since it is happening on Claudio's story I wonder if we could run QA in dev mode to see where the discrepancy or I can pull the JSON via the shortcuts to see if I can recreate it.

**Comment by swissspidy** [comment]
@carlos-kelly You can enable dev mode with the click of a button on the QA site. Feel free to do so for testing.

<img width="610" alt="Screenshot 2020-12-16 at 14 31 27" src="https://user-images.githubusercontent.com/841956/102354841-63b9a380-3fab-11eb-90f3-f4708e98d6d8.png">

**Comment by csossi** [comment]
Verified in QA
