### ISSUE TITLE
Pre-Publish Checklist: Navigate to the fix in the design panels 

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#5631]
## Feature Description

An item in the list should be able to select an issue and it take you to the offending element and (ideally) highlights the right thing to modify (e.g., if title missing it takes you to the title, if image missing alt text it opens the image with focus in the alt text section in the design panel, etc.)

This ticket is step 2; step 1 for reference since it's a sequential body of work.
1. The first step is selecting the element and switching to that page if required
**2. The second step is if a fix exists in another panel, like missing assistive text, switching to that panel and then focusing the text box.**

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
@o-fernandez @bmattb We're going to need to schedule a meeting to run through some missing pieces of this feature with you to get some clarity before this can really be completed. @embarks is out today, if we could schedule something for tomorrow 1/20 or 1/21 that would be really helpful.

**Comment by csossi** [comment]
Verified in QA
