### ISSUE TITLE
Pre-Publish: Update Title Dialog to match new visual style

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#5644]
## Feature Description

Currently the Publish Flow shows a dialog when there is a missing title. Update it to reflect the new design language.

![image.png](https://images.zenhubusercontent.com/5ea09bca6a44046f869bafe0/632bf5b3-5547-4fc2-b75f-aac8a95b6b8b)

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by carloskelly13** [comment]
Moved to backlog, while approved and QA'd this is on hold until the larger scope of re-design work is in play.

**Comment by BrittanyIRL** [comment]
![Screen Shot 2021-03-30 at 3 56 23 PM](https://user-images.githubusercontent.com/10720454/113067059-847bc280-9170-11eb-99b6-68af36849cd1.png)

This has been resolved with design system updates, moving to UAT
