### ISSUE TITLE
Animation drop down & Layer panel display issue in Firefox

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5645]
## Bug Description

Visual bug in Firefox when the animation drop down is over the Layers panel. Hovering over where a layer is underneath the dropdown (doesn’t occur when Layers is collapsed):

## Screenshots

![image5](https://user-images.githubusercontent.com/58738530/101947699-e531c000-3bbe-11eb-93be-276935d1e5ca.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by maxyinger** [comment]
Unable to reproduce on macOS & firefox 84.0

![Screen Shot 2020-12-15 at 9.36.00 AM.png](https://images.zenhubusercontent.com/5ea0a3e2f739259b2b0b092a/e7fa0cbb-82a1-4272-8beb-9538a34e5b61)

**Comment by csossi** [comment]
Unable to reproduce

![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/24ca850e-78ab-432a-810b-fe4d6f30e3bf)
