### ISSUE TITLE
Dashboard: Cannot scroll through WordPress admin menu

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5647]
## Bug Description

Originally reported by @kkalarickal 

When the user clicks into My Stories or any of the sub-menu items, the mouse scroll seems to be captured so that user is unable to scroll past the other wp-admin menu items (like Plugins - Users - Tools - … etc). This is debilitating since to get to another wp-admin menu, the user first has to click out of My Stories.

## Expected Behaviour

As with any standard WP-Admin context, the user should be able to scroll independently around the User Interface. Capturing the scrolling event should be restricted to the Stories Editor or Stories Dashboard.

## Steps to Reproduce

- Open browser and reduce the height (i.e. don’t make it full window)
- Click on My Stories in wp-admin and try to access the wp-admin menu items below stories.
- The wp-admin menu is frozen… in fact only mouse scroll within the dashboard area is allowed.
- 

## Screenshots
![image5](https://user-images.githubusercontent.com/58738530/101953016-9ccad000-3bc7-11eb-9aff-43c28e665b86.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
Super interesting! I tested this out and do see the bug, I think this is going to be something that Pascal or Jonny can debug a lot faster since it appears to be an issue with the wordPress menu, just on first glance. (If I'm wrong, please feel free to toss it back)

**Comment by swissspidy** [comment]
@BrittanyIRL I assume the issue is this `overflow: hidden` in combination with the positioning. It just happens to be noticeable when the admin menu is very long, but you could also see this with the default admin menu when making the window a bit smaller

https://github.com/google/web-stories-wp/blob/dc90437c2d8e7de22df90fc66d905d6eb66c21f5/assets/src/dashboard/style.css#L41-L51

https://github.com/google/web-stories-wp/blob/dc90437c2d8e7de22df90fc66d905d6eb66c21f5/assets/src/dashboard/style.css#L58-L62

**Comment by BrittanyIRL** [comment]
@swissspidy ah yup, you're right - totally overlooked that. Thanks, i'll take this back!

**Comment by carloskelly13** [comment]
This will get addressed with new designs + some rethinking on the sticky headers. We will keep this story open to track the bug specifically.

**Comment by maxyinger** [comment]
something seems off with the page preview when views are in mobile/tablet size, but we’ll deal with that as we refactor the dashboard designs this next release cycle. Seems to be unrelated to these changes and a current issue in staging

**Comment by csossi** [comment]
Verified in QA
