### ISSUE TITLE
In RTL mode, clicking Published keyword results in All Stories being underlined and vice versa

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5648]
## Bug Description

Setting the view mode from left hand side menu to right hand side shows a discrepancy in how the underline/highlight of Published / All Stories keyword within Stories Dashboard

## Expected Behaviour

When Published is clicked, the keyword Published should be underlined. Same with All Stories.

## Steps to Reproduce

- Go to My Stories Dashboard
- Click the “Switch to RTL” button to change the mode to right-to-left
- Click Published - note that the All Stories is underlined
- Click All Stories - note that the Published is underlined
- 

## Screenshots

![image7](https://user-images.githubusercontent.com/58738530/101953316-25497080-3bc8-11eb-864d-9d3f3428049e.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
Let's revisit this once we update to the new designs.

**Comment by BrittanyIRL** [comment]
This is getting fixed by updating new designs, pulling this ticket in to track with the updates.

**Comment by BrittanyIRL** [comment]
This is fixed in feature/4960-dashboard-header (#6434)

**Comment by csossi** [comment]
Verified in QA
