### ISSUE TITLE
Issues with usability of drop down arrow for Saved colors/styles

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5649]
## Bug Description

It is possible to click the Saved colors > Edit/Pencil and Saved styles > Edit/Pencil icons even when those sub-panels are collapsed resulting in a weird ‘Exit’ word without the ability to see what is being edited.

## Expected Behaviour

The edit/pencil icon should only be allowed when the Saved colors/style sub panels are expanded. Alternately, when the pencil icon is clicked, the sub panel should automatically open as well so that the user can see what she is editing.

It should probably also open automatically when clicking on the "+" button

## Steps to Reproduce

- Create a new web story
- Add a text box with some text in it
- Select the text box and collapse the Saved colors/styles sub panel in the Design tab
- Click the pencil/edit icon and see a weird “Exit” button pop up without seeing the contents of the Saved colors/styles.

## Screenshots
![image4](https://user-images.githubusercontent.com/58738530/101953635-ae60a780-3bc8-11eb-98f7-7b9f69b920e3.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
Irrelevant by later work.
