### ISSUE TITLE
Stories set to Status:Private, cannot be found in My Stories Dashboard

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5650]
## Bug Description

While it is possible to set the status of a web story to Private (as visible to admin/editors), once this is done, the Dashboard > My Stories stops showing the newly Private story. The user has to go to Classic WP List view to find stories marked Private. 

## Expected Behaviour

This is a shortcoming that needs to be addressed - either the ability to mark as Private should be disabled, OR a filter for Private stories enabled in the My Stories Dashboard, similar to Published and Draft stories.

## Steps to Reproduce

- Go to a web story that you have authored and change the Document > Status & Visibility to Private
- Go back to the My Stories  Dashboard and look for the story
- It will not be possible to find or search for the private story in the dashboard
- 

## Screenshots

![image12](https://user-images.githubusercontent.com/58738530/101953941-4363a080-3bc9-11eb-84aa-c9857f78e671.png)
![image3](https://user-images.githubusercontent.com/58738530/101953951-465e9100-3bc9-11eb-86ac-9bd791938640.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
