### ISSUE TITLE
Inconsistent behavior of numerical input within Design/Document panel

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5651]
## Bug Description

Originally reported by @kkalarickal 

There are several input fields in the various sub panels of the Design / Document panel. These are giving inconsistent user interaction for entering the numerical values:

1. Unable to manually enter decimal values in Default Page Duration even though moving the slider causes a decimal value to appear in the box
![image11](https://user-images.githubusercontent.com/58738530/101955160-50818f00-3bcb-11eb-9714-8719aea84262.png)

2. Design > Layer > Opacity can be changed by using the keyboard up/down arrows. But the Design > Style > Text Color Opacity CANNOT be edited by keyboard up/down
![image6](https://user-images.githubusercontent.com/58738530/101955197-62fbc880-3bcb-11eb-9f56-6e9df55183a5.png)

3. Design > Style > Font thickness & height can be edited to within 1 decimal place. However, the Design > Style > Padding (H & V) CANNOT be fine tuned to decimal

## Expected Behaviour

As a user of a visual editor, the ability to change numerical values should be consistent across the different input fields. It's possible that the editor cannot accept decimal values for some settings, but that restriction being relaxed for another form of input can cause user confusion.

## Steps to Reproduce

- Create/edit a web story and add a Text box with some text in it
- Open the different sub panels in the Design panel and manipulate the numerical inputs
- Open the Document > Page Advancement sub panel and you can see the difference in manual vs scroll input for the page duration.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
Irrelevant due to later work.
