### ISSUE TITLE
Weird ghost rectangle in Checklist > Recommendation

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5652]
## Bug Description

Originally reported by @kkalarickal and also by @bmattb , @spacedmonkey , @swissspidy 

Within the Checklist > Recommendation section, in front of each Page reference, there is a weird rectangle. Perhaps it is some indicator of severity or a link to the page or something. But it's confusing.

## Expected Behaviour

Said rectangle should be removed or its inclusion be made clear to the user.

## Steps to Reproduce

Create a web story which is imperfect ;)
Checklist recommendation will have the page reference and the said rectangle

## Screenshots

![image1](https://user-images.githubusercontent.com/58738530/101955588-182e8080-3bcc-11eb-9746-522973cef6e0.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by carloskelly13** [comment]
This is the icon for a page from the original designs but we can drop the icon if that's preferred.

**Comment by bmattb** [comment]
@samitron7 - not sure if this is something you want to action this or not, but multiple ppl (myself included) have noted that this icon appears to be out of place, and seems to be indicative of a missing asset as opposed to intentional.

**Comment by samitron7** [comment]
@carlos-kelly Let's drop the icon for now and @tmagalhaes-huge can look into an enhancement for the V2 version.

**Comment by csossi** [comment]
Verified in QA

**Comment by tmagalhaes-huge** [comment]
@aaecheverria Let's make sure we address this icon for V2.
