### ISSUE TITLE
Discovery: Video Optimization / Transcoding

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#5670]
See details in #5669

**Comment by swissspidy** [comment]
Discovery was summarized here: https://docs.google.com/document/d/10N4ktt71ulfuUfpSXLPmRCCzc5VltDXfVXDnjTyr4H8/edit?resourcekey=0-GaScD55DtnyxO5RBFinQBQ

Will take it from there
