### ISSUE TITLE
Library: Remove animation tab & experiment

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#5691]
## Feature Description

~Now that we have a page layouts library we need to make the library bar scrollable.~

![image.png](https://images.zenhubusercontent.com/5ea09bca6a44046f869bafe0/2949e2b8-3657-4fca-92d4-a1caba6b797d)

Animation tab is legacy. Will provide more room for page layouts tab when we remove it.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. Open or create a new story
2. Ensure there's no animation tab in the library
3. Ensure there's no animation library tab in experiments
~2. Ensure page layouts or the animation library is enabled to get an overflow of options~
~3. See that the options scroll~

**Comment by maxyinger** [comment]
Hmph do we need to do this or just remove the animation tab here? I'm not aware of any designs using the library for animations yet. Pretty sure they're only in the design inspector, then there's eventually gonna be a timeline.

@samitron7 can you verify this?

**Comment by maxyinger** [comment]
confirmed with same that the animation tab here is legacy. Will update the ticket to remove it from the experiments and remove the flag
