### ISSUE TITLE
Update page carousel to new layout

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#5692]
## Feature Description

Update page carousel in the following ways:

1. Make thumbnails one-size only (not scalable):
-> 36x64px with 16px spacing if workspace width <700px
-> 40x72px with 16px spacing if workspace width >=700px
-> Carousel is still a regular scrollable container

1. Add arrows to the ends of the carousel. 
-> 32px button area with regular arrow icon inside spaced 16px from the carousel itself.
-> Pressing an arrow does not change the current page, it just offsets the carousel by a full page in the chosen direction.
-> Arrow color is FG Dark Primary, unless inactive, then FG Dark Tertiary.

1. Make the page carousel container fit the center of the footer of the workspace such that there's 167px of space gap on each side of the arrows (so `maxWidth = canvasWidth - 2 * (167 + arrowWidth + arrowSpacing)` with arrows being 32px and arrow spacing 16px) but make sure it shows a whole number of pages (so that the width matches the following for some page count, `n`: `actualWidth = n * thumbnailWidth + (n - 1) * spacingWidth`, where thumbnail width varies as listed above and spacing width is always 16px).
-> On a very-wide workspace (>=1000px) the gap increases by 8px to 175px.

1. Position right-side icons (_keyboard shortcuts_ + _grid mode_) horizontally rather than vertically
-> Right-most icon (_keyboard shortcuts_) is placed 16px from right edge
-> On a very-wide workspace (>=1000px) the right gap is increased by 8px to 24px from right edge

1. Do **not** implement any of the following (will come with future design implementation):
-> New arrows
-> New icons for buttons
-> New selection outline for thumbnails

See designs in [Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=1009%3A4560).

Current design:
![Screen Shot 2020-12-15 at 21 12 30](https://user-images.githubusercontent.com/637548/102267532-543e4a00-3f1a-11eb-894f-aa1ee1cf4943.png)

New design for wide (>=700px) workspace:
![Workspace](https://user-images.githubusercontent.com/10889431/102452066-8faa4880-3fee-11eb-8371-c83876418ad6.png)

New design for narrow (<700px) workspace:
![Group 5751](https://user-images.githubusercontent.com/10889431/102452078-946efc80-3fee-11eb-8339-a5628ca2e044.png)

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by samitron7** [comment]
@barklund Updated the description with some minor value changes but everything is good to go here!

**Comment by bmattb** [comment]
@o-fernandez confirmed that this unfortunately will not be making the 1.3 release tomorrow

**Comment by csossi** [comment]
Verified in QA

**Comment by tmagalhaes-huge** [comment]
This looks good to me. Closing it. @samitron7 @aaecheverria FYI.
