### ISSUE TITLE
Update page menu and header to new layout

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#5694]
## Feature Description

Update the page header in the following ways:

1. Do not update the Save Draft, Preview, Publish button 
1. [TODO later] Change the icons in the page menu depending on workspace width:
-> On very-wide workspace (>=1000px):
`page # | trash-page duplicate-page add-page | undo redo | play-animation`
use 16px spacing between icons
-> On narrow workspace (<700px):
`trash-page duplicate-page add-page | play-animation`
use 10px spacing between icons
1. Allow title to be longer and truncate with an ellipsis
1. Add rounded corners to canvas (8px)
1. Do **not** update the colors and types of buttons used or icons if exists - also don't add the dropdown menu to the title field

See designs in [Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=1009%3A4560).

Current design:
![Screen Shot 2020-12-15 at 21 12 30](https://user-images.githubusercontent.com/637548/102267532-543e4a00-3f1a-11eb-894f-aa1ee1cf4943.png)

New design for very-wide (>=1000px) workspace:
![Workspace](https://user-images.githubusercontent.com/10889431/102462056-2a5e5380-3ffe-11eb-825a-1e67304f7cde.png)

New design for narrow (<700px) workspace:
![Group 5751](https://user-images.githubusercontent.com/10889431/102462067-2e8a7100-3ffe-11eb-9d36-07f808664922.png)

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by samitron7** [comment]
@barklund I reduced the scope quite a bit here by leaving the page actions docked to the bottom of the page.

**Comment by csossi** [comment]
Verified in QA
