### ISSUE TITLE
Improve JS error tracking

### ISSUE THREAD

**Issue by dreamofabear** [GoogleForCreators/web-stories-wp#5714]
### Background

After release of v1.2, there's been a coincident spike in "error" events in GA. 

![Screen Shot 2020-12-16 at 2 29 50 PM](https://user-images.githubusercontent.com/20525523/102410409-843f2900-3fbe-11eb-8569-c993e636ba07.png)

However, it's unclear how to fix these errors given currently available "error" event data in GA. We also don't know with certainty which plugin versions are causing the errors.

### Goals

Let's improve our GA usage for errors so we can easily:
1. Monitor and notify when error spikes occur
2. Debug and fix top errors (i.e. error names and stack traces)
3. Segment errors by plugin version/browser/etc.

### Notes 
- We track JS runtime errors with a GA event where name/action == "error"
  - Looks like this happens in `src/components/errorBoundary/index.js` and `src/tracking/trackEvent.js`
- The error name and stack trace (`error_info`) don't appear to be visible in GA dashboard 
- We should probably use GA's [exception tracking API](https://developers.google.com/analytics/devguides/collection/gtagjs/exceptions) for this instead

/cc @swissspidy

**Comment by swissspidy** [comment]
👋 chiming in because I wrote all that tracking code initially

>   * Looks like this happens in `src/components/errorBoundary/index.js` and `src/tracking/trackEvent.js`

`trackEvent` is just the function being called for this. Error events are currently tracked in both the error boundary as well as the status check (new after 1.2)

> * We should probably use GA's [exception tracking API](https://developers.google.com/analytics/devguides/collection/gtagjs/exceptions) for this instead

Probably makes sense, but the list of parameters is a bit limited :/

For easier usage, I'd suggest creating a new `trackError.js` helper function that is similar to `trakEvent`, but with some fields pre-filled. Something like this:

```js
// trackError.js

async function trackError(
  eventCategory,
  description,
  fatal = false,
  additionalData = {}
) {
  if (!isTrackingEnabled()) {
    return Promise.resolve();
  }

  const eventData = {
    send_to: config.trackingId,
    event_category: eventCategory,
    description,
    fatal,
    ...additionalData,
  };

  return track('exception', eventData);
}
```

Although not sure exactly how the error boundary would use this to send both error description and stack trace.

Maybe `trackError('editor', error, true, { errorInfo })`?

Whereas status check might simply do `trackError('editor', 'Status Check')`?

Just an idea

> 3. Segment errors by plugin version/browser/etc.

Since we don't currently have the plugin version available in GA data, it probably makes sense to set `config.app_version` accordingly.

This can be done by extending the `webStoriesTrackingSettings` in `Tracking.php`:

```php
public function get_settings() {
	return [
		'trackingAllowed' => $this->is_active(),
		'trackingId'      => self::TRACKING_ID,
		'appVersion'      => WEBSTORIES_VERSION,
	];
}
```

And then added to the default config in `tracking/shared.js`:

```js
const { trackingAllowed, trackingId, appVersion } = global.webStoriesTrackingSettings || {};

export const config = {
  ...DEFAULT_CONFIG,
  trackingAllowed,
  trackingId,
  appVersion,
};
```

And then, ultimately, the `app_version` can be set in `loadTrackingScript()`.

**Comment by swissspidy** [comment]
Probably a good time to [upgrade to Google Analytics 4 ](https://support.google.com/analytics/answer/9744165?hl=en) as well...

GA4 doesn't have a special `exception` event though: 
https://developers.google.com/gtagjs/reference/ga4-events
So we could probably just stick with `error`

**Comment by dreamofabear** [comment]
GA4 sounds good, though we should track that separately. I was just thinking the old UI is so ugly. :)

> https://developers.google.com/gtagjs/reference/ga4-events

I think that's the list of pre-defined (non-custom) events. I think this is the relevant GA4 docs: https://developers.google.com/analytics/devguides/collection/ga4/exceptions

**Comment by swissspidy** [comment]
Opened #5767 to track GA4 migration

**Comment by swissspidy** [comment]
> We track JS runtime errors with a GA event where name/action == "error"
> Looks like this happens in s`rc/components/errorBoundary/index.js`

Error boundaries are React components that catch JavaScript errors anywhere in their child component tree. They do not catch errors errors in event handlers, async code like `setTimeout`, or errors in the error boundary itself.

@choumx To catch more stuff, WDYT about doing `window.addEventListener('error', function(event) { ... })`?

----

What @zidianlyu and I just found about about exception tracking in GA:

Standard report for Exceptions and Crashes exists for App properties only.
Until #5767 is resolved, we have to create a custom report / dashboard for it.

So I'd suggest I'll get to #5767 soon-ish as well, to make our lives easie

**Comment by zidianlyu** [comment]
Here is the dashboard @swissspidy and I setup: 
![AD5FRBHq9UKgKqX](https://user-images.githubusercontent.com/11252886/104217695-90b57680-53f0-11eb-80ec-4f9ca77653d0.png)


@swissspidy, I just edited the dashboard a bit and added a `App Version` table on it.

**Comment by dreamofabear** [comment]
> To catch more stuff, WDYT about doing `window.addEventListener('error', function(event) { ... })`?

Sounds good, `unhandledrejection` should be useful too.

**Comment by dreamofabear** [comment]
Cross-referencing AMP, we also set a sentinel property on JS error objects that are reported to avoid duplicates.

https://github.com/ampproject/amphtml/blob/master/src/error.js

Other features like exponential backoff and sampling are probably not necessary for our use case with GA.
