### ISSUE TITLE
Video posters not being set

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#572]
## Bug Description

After location of poster, posterId and videoId was changed [here](https://github.com/google/web-stories-wp/commit/006f101e6ebd39357907d36e6097ba64e4a04c0b#diff-1434b7df9abe4968c6d35ac35639aeeaR34), poster function is completely broken. Other parts of the code base were not changed to save / read from this differently formatted data. 

Places I have found so far. 
- [Poster generation](https://github.com/google/web-stories-wp/blob/c026efed1ab544b8fad122796f46ee6f0ff85240/assets/src/edit-story/app/media/utils/useUploadVideoFrame.js#L57-L58)
- [Poster panel](https://github.com/google/web-stories-wp/blob/4ce16b744d3d0b708ef0ff31566b557bca1aca7a/assets/src/edit-story/components/panels/videoPoster.js#L36-L37)
- [Layer panel](https://github.com/google/web-stories-wp/blob/8df44220c28e61b0a11cb0b0a36ca84cab7696e3/assets/src/edit-story/elements/video/layer.js)

There may will be more places it is broken, I have not found yet.
## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment]
@spacedmonkey thanks for flagging this. Do you have an estimate for the size of this?

**Comment by spacedmonkey** [comment]
> @spacedmonkey thanks for flagging this. Do you have an estimate for the size of this?

XS, I think.

**Comment by spacedmonkey** [comment]
Some work has been done to fix this in - https://github.com/google/web-stories-wp/pull/553
