### ISSUE TITLE
Workspace: Editor shrinks when a GIF is searched for

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#5720]
## Bug Description

When a user searches for a GIF in images, the editor viewport shrinks

## Steps to Reproduce

1. Open/Edit a new Story
2. Switch to the Media library
3. Search "Hello" for GIFs
4. See the viewport shrink

## Screenshots

![image.png](https://images.zenhubusercontent.com/5ea09bca6a44046f869bafe0/b3d0a45a-da9f-4fad-be83-772a1ab71c90)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Probably caused by #5512

**Comment by csossi** [comment]
Verified in QA (5721)
