### ISSUE TITLE
KSES: Page Attachment link stripped for authors

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5728]
## Bug Description

Got an error report saying that the link was dropped when using page attachments when not having `unfiltered_html` caps.

## Expected Behaviour

Page attachment should work for authors too.

## Steps to Reproduce

1. Log in as author
2. Add page attachment to story
3. View story on frontend
4. Notice that page attachment links to empty page.

## Additional Context

- Plugin Version: 1.2.1
- WordPress Version: 5.6
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
