### ISSUE TITLE
Exclude stories from WordPress search results

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5731]
## Feature Description

We received multiple reports so far from users who wanted to exclude stories from their WordPress site's search results. I pointed them to a little plugin I wrote for this: https://gist.github.com/swissspidy/737f608f140b6034abd0d38539ac6eb5

But perhaps we should do that by default.

The problems with search:

* WP search is really crappy  
  Since we store complete generated HTML markup in the database, any search for let's say "amp" will return all stories.
* We don't yet have the better-looking blocks.  
 Stories look misplaced in  search results
* Crappy theme styling for stories. (see #5962)

This causes more harm than good.

## Alternatives Considered

* Add option for users

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by Vindulge** [comment]
I would support this as the default to exclude from WP search. I'd rather people who search see the more specific content versus the story.
