### ISSUE TITLE
Karma: Add Tests for Duplicating Page

### ISSUE THREAD

**Issue by maxyinger** [GoogleForCreators/web-stories-wp#5737]
Add karma tests for duplicating page. I mainly want this to be tested on elements with any of the possible animations applied, but we may find a need for other tests in here around page duplication too.

We should be able to recycle a lot of this code from this karma test for copy and paste to test the outward facing api here:
https://github.com/google/web-stories-wp/pull/5736

**Comment by maxyinger** [comment]
@carlos-kelly I remember creating a ticket like this earlier, but wasn't able to find it on the board. So heads up, There's a chance this is a duplicate.

**Comment by BrittanyIRL** [comment]
@littlemilkstudio has this been done already? I'm searching the code base and see some references to karma tests for duplicate pages.

**Comment by maxyinger** [comment]
Nope, I don't believe so. I was thinking we could just put it next to the copy & paste cuj karma tests
