### ISSUE TITLE
Document Team Onboarding Tasks

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5759]
## Task Description

Add small checklist to docs to cover things like:

* GitHub access
* Percy invites
* Staging site
* QA site
* Slack access
* Mailing list

**Comment by bmattb** [comment]
I'm using this

https://docs.google.com/spreadsheets/d/185hl2wJ09q-0RcZbeNKPqUO8R57wffZ7Wp0E1Rww9Bs/edit#gid=0
