### ISSUE TITLE
QA - Text

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#576]
This issue is for testing the Text functionality. Below are steps intended to aid with testing. These are the features covered in this issue:
drag (move)
resize, text scaling
color
highlight
RTE(size, italic, bold)
font picker (change font)
snap
rotate
Add
Padding

**[UX](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=3462%3A2868)**

**QA Steps**
1. Add text to a page via the (+) icon shortcut in nav
2. Edit the text copy
3. Edit the text via size, alignment, bold, italics, underline, padding...
3. Highlight part of the text copy
3. Add text via the ""Add Text"" button in the Text panel
4. Ensure it is staggered when compared to the first text box added
5. Move the second text box below the first one so they are not ovelapping
6. Edit the text copy in the second box
7. Edit the color of the text in the second box
8. Change the font in the second text box
9. Add a third text box to the page
4. Ensure it is staggered when compared to the other text boxes added
10. Move it below the second text box and ensure snapping to common distances is working (snaps to below the second box with the same distance between the first and second boxes)
11. Rotate the first text box
12. Grab the corner of the second text box to resize it, ensure the text size scales as you increase / decrease the text box size
13. Using the left or right side of the third text box, decrease the width and ensure text wraps (text box grows vertically, as width decreases)

**Comment by csossi** [comment]
@jauyong 

Created text with font settings as you see here:
![image](https://user-images.githubusercontent.com/16945664/77255085-526d8180-6c3b-11ea-8ff7-2464b39e3017.png)
Font looks different when Previewing:
![image](https://user-images.githubusercontent.com/16945664/77255107-7af57b80-6c3b-11ea-90b1-22c32db557ab.png)


Default size on selecting "AddText" is much too small:
![image](https://user-images.githubusercontent.com/16945664/77255149-c0b24400-6c3b-11ea-99fb-830d9463d027.png)

**Comment by claudiosossi** [comment]
@jauyong 
- Underline appearing outside of text box after adjusting padding to what you see here:
![image](https://user-images.githubusercontent.com/59885614/77463990-e034a280-6ddc-11ea-8cb5-8d459cc26558.png)

**Comment by claudiosossi** [comment]
@jauyong - happened to notice that color presets section has some off behaviour. There doesn't seem to be a difference between these two buttons:
![image](https://user-images.githubusercontent.com/59885614/77475045-90f76d80-6dee-11ea-8331-0752371b9fa4.png)

**Comment by jauyong** [comment]
@claudiosossi I'm not able to replicate the underline appearing outside the text box. Can you provide steps to replicate?

**Comment by wassgha** [comment]
> @jauyong - happened to notice that color presets section has some off behaviour. There doesn't seem to be a difference between these two buttons:
> 
> ![image](https://user-images.githubusercontent.com/59885614/77475045-90f76d80-6dee-11ea-8331-0752371b9fa4.png)
> 


Not implemented yet, should be hidden in the alpha release

**Comment by claudiosossi** [comment]
@jauyong - When a user adds text, they see the hint within the text box (fine):
![image](https://user-images.githubusercontent.com/59885614/77542152-1f660080-6e7c-11ea-965f-a196d0718c71.png)
But when they click within, they have to manually delete or overwrite this tip ("Double-click..."). Should the tip automatically "clear" when user clicks within the field?

**Comment by claudiosossi** [comment]
@jauyong 
Text box not resizing on increasing font size
- when replicating, create text that is a single line
https://drive.google.com/file/d/1sSdxD4DOqRi6BPjFd9TJsU1jvIyCVolm/view

**Comment by claudiosossi** [comment]
@jauyong 

Unable to edit text in Win10/FFox. Clicked the "+" to add. Then tried to click within the text box to edit and am unable to.

**Comment by jauyong** [comment]
closing this as CUJ testing will cover any required tests
