### ISSUE TITLE
Design System: Set up ability to test global keyboard hook events 

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#5764]
## Feature Description

As we make progress on implementing the new design system that can be a source of truth for UI of editor and dashboard, we are pulling in some existing utils that have served the project extremely well the last year. One of these is the global keyboard hook that handles events and helps manage focus given the complexity of the editor. 

In the design system we need a way to be able to unit test keyboard events that utilize these hooks. Currently, we can't. 

This ticket is to create a mock of `useKeyDownEffect` in src/design-system and implement the three commented out tests in `src/design-system/components/dropDown/tests/dropDown`. 

## Alternatives Considered

Karma testing for keyboard events using the global hook would also serve us well, but since this hook is currently only used in storybook in the design system, I feel like we would benefit from a way to mock this in our unit tests before getting to the point where Karma tests can be implemented. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Why are the tests in `src/design-system/components/dropDown/tests/dropDown` commented out instead of marked as skipped? 🤔

**Comment by BrittanyIRL** [comment]
> Why are the tests in `src/design-system/components/dropDown/tests/dropDown` commented out instead of marked as skipped? 🤔

Might have been that way waiting for a ticket to get made or just an accident. Good note to fix with this.
