### ISSUE TITLE
Improve Prepublish Checklist side effects

### ISSUE THREAD

**Issue by embarks** [GoogleForCreators/web-stories-wp#5768]
**Context** discussion on [this PR](https://github.com/google/web-stories-wp/pull/5739#issuecomment-749135131):

The pre-publish checklist could be enhanced by improving the way the checklist runs checks. Specifically, running The pre-publish checklist provider should be explicitly subscribed to the properties it is concerned about so that a deep equality check on the entire story object is not necessary.

**Suggestion**
Create an effect in `assets/src/edit-story/app/story/effects`. Refactor the `error`/`warning`/`guidance` index files to subscribe the checklist functions explicitly to the part of the context the function itself is concerned with.

_note: this is a placeholder, needs more details_

[design draft out here](https://docs.google.com/document/d/1-9mnhzx28dFtlPI3gFFL3YDHX16nyy_F5hGL7Ajg-RI/edit)

**Comment by maxyinger** [comment]
Just to update everyone as to the latest here. We set up some flexible infrastructure to subscribe and emit events centered around changes in the story.

General concept is roughly based on DOM events where there are internal events dispatched when the DOM changes, but you can also dispatch events manually if needed.

For internally dispatched events, we set up a scalable way to look at changes to parts of the story and dispatch events from there.

Rough API as far as listening to changes on the story looks like this:
```
 useStoryTriggerListener(
      STORY_EVENTS.onSomeStoryEvent, 
      useCallback((story) => {
        // do something with new story data
        // on this event
      }, [])
    )
```
general architecture outlined in this PR here:
https://github.com/google/web-stories-wp/pull/7259

Right now we're only using it to selectively compute the `error` / `warning` / `guidance` messages at certain checkpoints, but in the future we can always break them up more and trigger message computation with more fine tuned events as outlined by the doc above.

These triggers are primarily targeted at interacting with PPC right now, but in the future we should be able to just put all the functionality triggering FTUE in here too (and remove `useUserOnboarding` hook). Something like:
```
   useStoryTriggerListener(
      STORY_EVENTS.onBackgroundMediaAdded, 
      useCallback(() => {
        openBackgroundMediaQuickTip();
      }, [openBackgroundMediaQuickTip])
    )
```    

Could also be extensible to other features as a common trend in all of our UX updates seem to be centered around implicit user flows based on updates to the current story in the editor

**Comment by BrittanyIRL** [comment]
we did this with the #7721 epic! 

further perf wins on the checklist will be done specific to each check.
