### ISSUE TITLE
Animations: 0ms duration not persisted

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5769]
## Bug Description

Changing the animation duration to 0ms is not persisted when de-selecting an element and selecting it again.

Probably some loose type check somewhere.

## Expected Behaviour

Chosen value should persist.

## Steps to Reproduce

1. Add animation to element
2. Set duration to 0ms
3. Preview story, verify that change has been saved successfully
4. De-select element, select it again
5. See that 0ms is gone, and 1000ms is displayed (or whatever the animation default is)

## Screenshots

<img width="488" alt="Screenshot 2020-12-21 at 21 52 17" src="https://user-images.githubusercontent.com/841956/102821270-1720fe80-43d7-11eb-935f-7fd11ad5edef.png">

## Additional Context

- Plugin Version: 1.2.1
- WordPress Version: 5.6
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
