### ISSUE TITLE
Adding web stories to Post categories on WordPress

### ISSUE THREAD

**Issue by wisdomtoshine** [GoogleForCreators/web-stories-wp#5779]
## Feature Description

I would like to request for the feature that allows web stories to be categorized as we do it for other posts on our website. 
Would 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Thanks for your suggestion!

We're already tracking this enhancement in #489. Please follow that ticket for any updates on the matter.
