### ISSUE TITLE
QA - Image

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#578]
This issue is for testing the Image functionality. Below are steps intended to aid with testing. These are the features covered in this issue:

resize
add to page (drag)
set as background (resize, move)
add to page (double click)
stagger        
rotate        
snapping        
drag (move)

**[UX](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=4646%3A77568)**

**QA Steps**
1. Add an image to a page as a background (try to find a bigger picture to allow for modifcations)
2. Double click on the background image to enter edit mode
3. Move the image so a different part of the image is displayed as the backgorund
4. Exit edit mode
5. Ensure the new portion of the image is displayed
2. Double click on the background image to enter edit mode
3. Zoom In/Out of the image so a different section of the image is displayed as the backgorund
5. Ensure the new portion of the image is displayed
2. Add a second image to the page via double click on the media library panel
3. Add a third image to the page via drag and drop
4. Ensure it is staggered when compared to the other image added
5. Move the second image on the page below the first one so they are not ovelapping
9. Add a third image to the page
10. Move it below the second image and ensure snapping to common distances is working (snaps to below the second box with the same distance between the first and second images)
11. Rotate the first image
12. Grab the corner of the second image to resize it, ensure the aspect ratio is maintained
13. Using the left or right side of the second image, change the width and ensure the width grows but height does not
14. Grab the botoom of the second image, change the height and ensure the height grows but width does not

**Comment by csossi** [comment]
@jauyong 
- what CTA should user see to know that they can double-click on the background image in order to be able to resize/scale? Should there be a cue on hovering?

**Comment by jauyong** [comment]
@csossi here is the UX for background images: https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=2895%3A76886

**Comment by claudiosossi** [comment]
@jauyong 
What cue does the user have on getting OUT of edit mode for a background?:
![image](https://user-images.githubusercontent.com/59885614/77541000-7074f500-6e7a-11ea-871a-0cfa63c99d02.png)

**Comment by claudiosossi** [comment]
@jauyong 

Should maskedd images not be allowed to be set as a background?:
![image](https://user-images.githubusercontent.com/59885614/77654444-7389e700-6f47-11ea-8e98-4ec8365edfe9.png)

**Comment by swissspidy** [comment]
> Should masked images not be allowed to be set as a background?:

Fixed by #827

**Comment by claudiosossi** [comment]
@jauyong 
- Newly uploaded image appears upside-down:
![image](https://user-images.githubusercontent.com/59885614/77762001-430d8000-700f-11ea-951e-6e7a94cf917a.png)

**Comment by jauyong** [comment]
@claudiosossi how did you get that upside down upload? I couldn't replicate

**Comment by jauyong** [comment]
@claudiosossi SEE #678 RE:

> What cue does the user have on getting OUT of edit mode for a background?:

**Comment by claudiosossi** [comment]
> @claudiosossi how did you get that upside down upload? I couldn't replicate

just selected a local image to upload - didn't do anything else to it

**Comment by claudiosossi** [comment]
![20120528_133424000_iOS](https://user-images.githubusercontent.com/59885614/77854367-ea2d1b80-71b7-11ea-8378-ecde2a3c71f6.jpg)

@jauyong - original image

**Comment by claudiosossi** [comment]
https://www.screencast.com/t/tan9SWbrfFF

**Comment by claudiosossi** [comment]
@jauyong - This one only seems to be a prob in FFox (74)
- opted to create New story
- selected an image
- selected "Set As Backgrpound"
- in right panel, selected option to flip (top arrow):
![image](https://user-images.githubusercontent.com/59885614/77855527-008aa580-71bf-11ea-8a48-bf0420695895.png)
- image flipped but I'm automatically redirected to Add Post:
![image](https://user-images.githubusercontent.com/59885614/77855558-2617af00-71bf-11ea-8dd3-44226cdc0562.png)

**Comment by claudiosossi** [comment]
@jauyong - layout prob re: Opacity fields in Win10/FFox(74):
![image](https://user-images.githubusercontent.com/59885614/77855930-c373e280-71c1-11ea-8b83-55f7f4b16607.png)

**Comment by swissspidy** [comment]
> in right panel, selected option to flip (top arrow):
> ![image](https://user-images.githubusercontent.com/59885614/77855527-008aa580-71bf-11ea-8a48-bf0420695895.png)

Those buttons shouldn't be aligned like this. They should be next to each other according to the designs.

**Comment by jauyong** [comment]
@claudiosossi I uploaded an image in firefox and it wasn't flipped. I can't for the life of me get flash working to view your screencast. I'm on a Mac and I know you are on Windows, but when I upload an image (upload button, drag and drop) It is not coming inverted.

**Comment by jauyong** [comment]
closing this as CUJ testing will cover any required tests
