### ISSUE TITLE
Add Social Sharing Options

### ISSUE THREAD

**Issue by wisdomtoshine** [GoogleForCreators/web-stories-wp#5780]
## Feature Description

I would like to request a feature that allows me to directly send my story to different social networks, such as Pinterest, Instagram, FB, Whatsapp, and so on. 

Currently, when we click on the share button, it allows copying the URL/link for the story. I would like to directly share to different social sites from that point onwards.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Good suggestion! We initially didn't add this because there are plans to deprecate the bookend, but apparently the social sharing options will stay.

**Comment by csossi** [comment]
Verified in QA

Note: Nothing happens on clicking "More" - assuming this is a known issue for now
