### ISSUE TITLE
QA - Video

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#579]
This issue is for testing the Video functionality. Below are steps intended to aid with testing. These are the features covered in this issue:

Add
resize
add to page (drag)
set as background (resize, move)        
add to page (double click)        
stagger        
rotate        
snapping        
drag (move)
one per page
autoplay
pause

**[UX](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=4646%3A77568)**

**QA Steps**
1. Add a video to a page as a background 
2. Double click on the background video to enter edit mode
3. Move the image so a different part of the image is displayed as the backgorund
4. Exit edit mode
5. Ensure the new portion of the video is displayed
2. Double click on the background image to enter edit mode
3. Zoom In/Out of the video so a different section of the video is displayed as the backgorund
4. Exit edit mode
5. Ensure the new portion of the video is displayed
6. Ensure you are not able to add another video to the page (Only 1 video per page allowed)
7. Remove the background video completely from the page
2. Add a video to the page (not as background video)
3. Drag the video to the centre of the page
12. Grab the corner of the video to resize it, ensure the aspect ratio is maintained
13. Using the left or right side of the video, change the width and ensure the width grows but height does not
14. Grab the bottom of the video, change the height and ensure the height grows but width does not
11. Rotate the video
12. Preview the story and ensure the video auto plays by default
13. Ensure you are able to pause the video by clicking on it

**Comment by csossi** [comment]
@jauyong 

- set video as background, but video isn't playing in workspace. Also selected Video from Media/Video tab - also not playing. Note that this means I'm unable to see the "hover" functionality noted in Figma:
![image](https://user-images.githubusercontent.com/16945664/77255468-053edf00-6c3e-11ea-97c9-3ed9290a36f3.png)

- Was able to add a 2nd video to page (when one was set as the background. (Note: On Preview, the background video plays, the newly added one does not):
![image](https://user-images.githubusercontent.com/16945664/77255562-decd7380-6c3e-11ea-911b-8639ed21c371.png)

**Comment by jauyong** [comment]
closing this as CUJ testing will cover any required tests
