### ISSUE TITLE
Text: Normalize padding on text highlight and fill

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#5791]
## Feature Description

This is the base for 
https://app.zenhub.com/workspaces/web-stories-5e94d3aced449034e1e9b226/issues/google/web-stories-wp/4980
https://app.zenhub.com/workspaces/web-stories-5e94d3aced449034e1e9b226/issues/google/web-stories-wp/4972

The goal is to ensure when padding and fill-style change, the text is kept in place and the frame grows around it.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. Create a new story or edit an existing story
2. Add some text boxes
3. Add a highlight or fill mode to the text box and see the text stays in place
4. Add some padding to the text box and see the text stays in place and the frame grows around it

**Comment by csossi** [comment]
Which PR # am I testing here, @carlos-kelly ?

**Comment by carloskelly13** [comment]
Merged as part of another PR!
