### ISSUE TITLE
Performance: Improve DisplayElement Wrapper Styled Component

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5797]
## Feature Description

Getting the following console warning sometimes:

```
Over 200 classes were generated for component displayElement__Wrapper with the id of "displayElement__Wrapper-sc-143lj7s-0".
Consider using the attrs method, together with a style object for frequently changed styles.
Example:
  const Component = styled.div.attrs(props => ({
    style: {
      background: props.background,
    },
  }))`width: 100%;`
```

Code in question is here:

https://github.com/google/web-stories-wp/blob/00db4dae0aa1764fce5f9404d39389fabd6d50f8/assets/src/edit-story/components/canvas/displayElement.js#L45-L51

There might be more areas where this could be immproved.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
This also affects other places where elements are displayed, like  text sets.

**Comment by swissspidy** [comment]
@barklund this could be something for next sprint perhaps, WDYT?

**Comment by miina** [comment]
Reopening as this would need a more thorough logic change for transformation as well.

Let's look at this again as part of #7637
