### ISSUE TITLE
Telemetry: Let links open in new tab

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5799]
## Bug Description

The `trackClick()` util uses `event.preventDefault()` and `document.location = url` to track links to ensure the beacon is transmitted before opening the URL.

However, this is quite annoying and unnecessary if the link is being opened in a new tab anyway.

## Expected Behaviour

My suggestion would be to do something like this (untested!):

```js
async function trackClick(event, eventName, eventCategory, url) {
  if (!isTrackingEnabled()) {
    return Promise.resolve();
  }

  const eventData = {
    send_to: config.trackingId,
    event_category: eventCategory,
    event_label: url,
  };

  const openLinkInNewTab =
    event.target === '_blank' ||
    event.ctrlKey ||
    event.shiftKey ||
    event.metaKey ||
    event.which === 2;
  
  if (openLinkInNewTab) {
    return track(eventName, eventData);
  }

  event.preventDefault();

  return track(eventName, eventData).finally(() => {
    document.location = url;
  });
}
```

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
@zidianlyu In case you're interested in more telemetry stuff :)

**Comment by spacedmonkey** [comment]
We could also do something like this. 
```
async function trackClick(event, eventName, eventCategory, url, openLinkInNewTab = false ) {
  if (!isTrackingEnabled()) {
    return Promise.resolve();
  }

  const eventData = {
    send_to: config.trackingId,
    event_category: eventCategory,
    event_label: url,
  };
  
  if (openLinkInNewTab) {
    return track(eventName, eventData);
  }

  event.preventDefault();

  return track(eventName, eventData).finally(() => {
    document.location = url;
  });
}
```

Adding another param to function means we have more control.

**Comment by swissspidy** [comment]
That seems kinda confusing and gives wrong expectations about what it does. Plus it‘s redundant as we can already infer the necessary information from the event.

**Comment by csossi** [comment]
Verified in QA

**Comment by swissspidy** [comment]
@o-fernandez The issue with links not opening in a new tab  in the monetization section is now resolved, if you wanna give it a spin.
