### ISSUE TITLE
Add page grid view

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#58]
## Feature description

Add a page grid view as a new global state for the entire editor as well as a button in the page carousel that enables it.

In grid view, show page outlines of all pages in story and allow them to be both dragged and cut-pasted as designed.

Page reordering/duplication takes immediate effect.

Page outlines can be resized using the slider in the footer.

The close button in the footer will close grid view (changes have been persisted instantly when made).

This ticket does not include showing actual previews of the pages in the grid view.

The keyboard interactions are dependent on the outcome of ampproject/amp-wp#3826.

This is still pending UX review.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Users can enter grid view when pressing the button in the footer.
* Users can reorder pages in grid view by dragging.
* Users can focus pages and spaces in grid view by clicking and navigate between the pages using arrow keys or tabs.
* Users can move pages in grid view by using keyboard shortcuts as designed.
* Users can delete pages in grid view by pressing delete/backspace when focused.
* Users can resize the page preview in the grid by using the slider at the bottom of the view.
* Users can exit grid view.

## Implementation brief

* 

## QA testing instructions

1. Create a new story with a few pages and elements
1. Verify that clicking on the grid view icon in the bottom right opens the grid view
1. Verify that the size of the thumbnails changes with the range slider
1. The grid view follows the Figma design
1. The thumbnails show the preview of the pages as in the carousel
1. Drag & drop of pages to reorder them works
1. The grid view can be closed by using <kbd>ESC</kbd> and by clicking on the back link

## Demo

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
@samitron7 Sounds good. The three sizes are currently like this:

* Small: 90x160
* Medium: 180x320 (like on Figma)
* Large: 270x480

**Comment by jauyong** [comment]
Hey @swissspidy are you able to add QA instructions for this?

**Comment by swissspidy** [comment]
Added some, sorry for the delay!
