### ISSUE TITLE
QA - Masking

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#580]
This issue is for testing the Masking functionality. Below are steps intended to aid with testing. These are the features covered in this issue:

**[UX](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=0%3A1)**

**QA Steps**
1. Add a shape to the page
2. Add a different shape to the page and move it so it does not overlap with the first shape
3. Drag an image onto the first shape to achieve a masking effect
4. Drag a video onto the second shape to achieve a masking effect

**Comment by claudiosossi** [comment]
@jauyong - able to successfully mask both image and video

How can a user remove the image/video from mask if they change their minds? Unless I missed it somehow, I don't see anything in Figma about that

**Comment by jauyong** [comment]
closing this as CUJ testing will cover any required tests
