### ISSUE TITLE
Animations: Lazily Import Some or All of Animation Module

### ISSUE THREAD

**Issue by maxyinger** [GoogleForCreators/web-stories-wp#5807]
At the very least lazily import the web animations api polyfill, but possibly move the entire animation module to be lazily loaded.
https://github.com/google/web-stories-wp/pull/5806#discussion_r549343935

**Comment by samwhale** [comment]
Looking around the code - looks like this is already dynamically imported: 

https://github.com/google/web-stories-wp/blob/main/packages/animation/src/components/provider.js#L32-L36

Can work on dynamically importing other stuff in the module. Seems like it's mostly prop type definitions, static objects, and animation definitions. There's other stuff too though!

**Comment by swissspidy** [comment]
Yeah the polyfill is already imported dynamically if needed.

I think the second part refers to lazily importing `@web-stories-wp/animation` within the `story-editor` package.

But that is really used in lots of places, so I don't see how that could be done.

So seems like a wontfix

**Comment by samwhale** [comment]
Okay, I'll close this as a wontfix.
