### ISSUE TITLE
Dashboard: Support GA4 Measurement ID for Analytics

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5808]
## Feature Description

GA4 uses a `G-XXXXXXX` format for the measurement ID ([docs](https://support.google.com/analytics/answer/7372977?hl=en)).

The GA setting field in the dashboard doesn't currently support that format.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
@BrittanyIRL Perhaps a small one for you to address? Just need to update the regex I think.

**Comment by BrittanyIRL** [comment]
> @BrittanyIRL Perhaps a small one for you to address? Just need to update the regex I think.

Yes, I'll add it to the next sprint since this one ends Friday.

**Comment by BrittanyIRL** [comment]
Testing directions pulled from PR: https://github.com/google/web-stories-wp/pull/5856
> Go to dashboard settings and try changing the analytics ID, try this format: UA-000000-2 (tracking id) and G-XXXXXXX (measurement id) and see that both are valid options to save.

**Comment by csossi** [comment]
Am unable to edit this field in the QA environment
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/9292cb8a-d52c-4b07-adb4-21c07c3979c8)

**Comment by swissspidy** [comment]
@csossi Ah, good point. That's because Site Kit is installed (as per the note below the label). Any chance you could test this locally on your machine on another testing site? Plugin ZIP file to install: https://github.com/google/web-stories-wp/suites/1815182970/artifacts/34916483

@BrittanyIRL we should fix #5877 to make testing this easier

**Comment by BrittanyIRL** [comment]
yes we absolutely should!! I'll keep an eye on space for this in the next set of sprints but should be a really simple quick ticket to get through.

**Comment by csossi** [comment]
Thanks, @swissspidy - can and will test on a local installation

**Comment by csossi** [comment]
Verified in QA
