### ISSUE TITLE
Design System: Add in keyboard functionality 

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#5810]
## Feature Description

Design system needs access to the `useKeyboardOnly` util used by editor and dashboard. Ideally, this helps the design system become the source of truth for that.

## Additional Context

Realized this ticket was missing while working on #4950 dropDown. Creating a new ticket in an effort to avoid scope creep.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
This will get tested with components, background work. There's no real reason to spend time in UAT on this alone, my thoughts - but I'll let you make that call, @o-fernandez  :)

**Comment by ivayloklissarov** [comment]
Not quite sure to understand this ticket, but I don't see any Keyboard section in the DS.

**Comment by BrittanyIRL** [comment]
Understandable, @ivayloklissarov  - I thought as much with this comment here: https://github.com/google/web-stories-wp/issues/5810#issuecomment-755698270 

Essentially what this is for is a shared style for all keyboard focuses. which are these: 
![keyboard focus](https://user-images.githubusercontent.com/10720454/109233376-07cb8200-7787-11eb-995c-206a9082be1f.gif)

So this'll get tested every time you test anything with focus, there's nothing to really uat. just doing due diligence with the ticket pipeline by passing it to UAT. We can probably just close this.
