### ISSUE TITLE
QA - Page Carousel

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#583]
This issue is for testing the Page Carousel functionality. Below are steps intended to aid with testing. These are the features covered in this issue:

reorder (drag, cut/paste)        
grid view
add page

**[UX](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=2663%3A7344)**

**QA Steps**
1. Go to a story with at least 4 pages
2. Reorder the pages in the story by dragging in the page carousel
3. Click on the grid icon to enter the grid view
2. Reorder the pages in the story by cut & paste in the page carousel
4. Use the slider to zoom in/out
5. Go back to the editor
6. Select the third page in the page carousel
7. Ensure the workspace is now focused on that page
8. Add a page
9. Ensure the new page is added as the fourth page

**Comment by csossi** [comment]
@jauyong 
- Unable to change order by cut-and-paste

**Comment by csossi** [comment]
@jauyong 

Went into Grid view to reorder pages. When I clicked and dragged the first page, I can see a "transparent" version of it being dragged (fine):
![image](https://user-images.githubusercontent.com/16945664/77258508-6fad4a80-6c51-11ea-9f02-ad297fb29fe5.png)

but when I selected and dragged the 2nd image, it looks like I'm dragging the previous and next pages along with it:
![image](https://user-images.githubusercontent.com/16945664/77258534-94092700-6c51-11ea-9180-3caa0c7d1c09.png)

**Comment by jauyong** [comment]
closing this as CUJ testing will cover any required tests
