### ISSUE TITLE
QA - Layers

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#584]
This issue is for testing the Layers functionality. Below are steps intended to aid with testing. These are the features covered in this issue:

reorder items        
cut/paste

**[UX](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=2683%3A260)**

**QA Steps**
1. Go to a page with at least 4 elements of mixed type (shape, image, text)
2. Arrange them so they overlap with eachother on the page
3. Drag an item that is towards the bottom in the layers section of the design panel to the top
4. Ensure that element is now at the top on the page as well (it shouldn't be covered by anything)
5. Use keyboard shortcut for cut an element that is towards the bottom in the layers section of the design panel and paste it at the top
6. Ensure that element is now at the top on the page as well (it shouldn't be covered by anything)

**Comment by claudiosossi** [comment]
@jauyong 
Was able to move a layer to a new position, but unable to move it back to original position
Vid - https://drive.google.com/file/d/16MtsHg3dfmrGAFhvM29zYUqoBJKoXqQW/view

**Comment by jauyong** [comment]
closing this as CUJ testing will cover any required tests
