### ISSUE TITLE
Update text set to make use borders instead of 4 shapes

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#5840]
This text set: ![image.png](https://images.zenhubusercontent.com/5e98486db524b82fc96aeaf6/fe06c23f-4cde-4cda-a024-a685e153856c)

On canvas uses 4 shapes to create the border around "Category"

![image.png](https://images.zenhubusercontent.com/5e98486db524b82fc96aeaf6/6975caba-7a55-43c1-be18-cb65f68fc3c3)

Can we change this to use regular borders? If we see other instances of this we should also flag them.

**Comment by csossi** [comment]
Verified in QA
