### ISSUE TITLE
Text set preview doesn't look good

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#5841]
This text set: 
![image.png](https://images.zenhubusercontent.com/5e98486db524b82fc96aeaf6/78fafabd-8488-4c80-8616-838965e3479c)

Looks like this in the text sets panel: ![image.png](https://images.zenhubusercontent.com/5e98486db524b82fc96aeaf6/e29d424b-8450-4c03-8294-8cbebb6d4a4b)

Can we come up with a solution so that the preview is clearer? @samitron7 

Similarly, this text set has the text white in "Contact Us" but with that shape behind it's hard to see. On the canvas it's black text. 
![image.png](https://images.zenhubusercontent.com/5e98486db524b82fc96aeaf6/774817cb-68da-440f-96a0-e825af80ed8d)
![image.png](https://images.zenhubusercontent.com/5e98486db524b82fc96aeaf6/6bdef342-55b8-41a4-bf5c-c32fb4b0c932)

**Comment by BrittanyIRL** [comment]
related to the text magic work prometheus handled a few releases ago.
