### ISSUE TITLE
TypeError: URL is not a constructor

### ISSUE THREAD

**Issue by lightscamerabake** [GoogleForCreators/web-stories-wp#5843]
TypeError: URL is not a constructor
    in MediaProvider
    in Unknown
    in FontProvider
    in Unknown
    in StoryProvider
    in Unknown
    in SnackbarProvider
    in Unknown
    in HistoryProvider
    in Unknown
    in Media3pApiProvider
    in Unknown
    in FileProvider
    in Unknown
    in APIProvider
    in Unknown
    in ConfigProvider
    in q
    in Ge
    in se
    in App
    in StrictMode
    in FlagsProvider

**Comment by swissspidy** [comment]
Hi there

what are the last steps you‘ve taken before this error occured?

**Comment by LuckynaSan** [comment]
@lightscamerabake We are closing this issue as there has not been any activity since your initial report. Please open a <a href="https://wordpress.org/support/plugin/web-stories/#new-post">new support topic</a> in the WordPress support forum if you continue to experience any issues. Thank you!
