### ISSUE TITLE
QuotaExceededError: The quota has been exceeded.

### ISSUE THREAD

**Issue by GDMarket** [GoogleForCreators/web-stories-wp#5845]
What I was doing : create a new web storie (the first one), add two pictures, select one of them, then click on "layer".

QuotaExceededError: The quota has been exceeded.
    in Panel
    in SimplePanel
    in LayerStylePanel
    in Unknown
    in form
    in designPanel__Form
    in DesignPanel
    in DesignPanels
    in div
    in designInspector__TopPanels
    in div
    in designInspector__Wrapper
    in DesignInspector
    in div
    in inspectorContent__InspectorPane
    in section
    in inspectorContent__InspectorPanes
    in Inspector
    in div
    in inspectorLayout__InspectorContainer
    in section
    in inspectorLayout__Layout
    in InspectorLayout
    in div
    in dropTarget__Content
    in Unknown
    in div
    in dropTarget__DropTargetComponent
    in UploadDropTarget
    in Unknown
    in InspectorProvider
    in Yh
    in q
    in div
    in layout__InspectorArea
    in Unknown
    in RichTextProvider
    in Workspace
    in Unknown
    in UnitsProvider
    in Unknown
    in CanvasProvider
    in section
    in layout__Editor
    in Unknown
    in ForwardRef(WithOverlay)
    in Unknown
    in LayoutProvider
    in rm
    in PrepublishChecklistProvider
    in Unknown
    in DropTargetsProvider
    in Unknown
    in TransformProvider
    in Unknown
    in MediaProvider
    in Unknown
    in FontProvider
    in Unknown
    in StoryProvider
    in Unknown
    in SnackbarProvider
    in Unknown
    in HistoryProvider
    in Unknown
    in Media3pApiProvider
    in Unknown
    in FileProvider
    in Unknown
    in APIProvider
    in Unknown
    in ConfigProvider
    in q
    in Ge
    in se
    in App
    in StrictMode
    in FlagsProvider

**Comment by swissspidy** [comment]
Thanks for your report @GDMarket! Which browser are you using, and were you perhaps using it in private/incognito mode?

**Comment by GDMarket** [comment]
> 
> 
> Thanks for your report @GDMarket! Which browser are you using, and were you perhaps using it in private/incognito mode?

I'm using Firefox 84.0.2 64bits, and I was in non-private mode. In fact, when I click on any menu item on the right, it "crashes".

**Comment by swissspidy** [comment]
@GDMarket Very helpful, thanks! One last question: if you go to https://arty.name/localstorage.html in Firefox, what does the line below `Results will appear below:` say?

**Comment by GDMarket** [comment]
> 
> 
> @GDMarket Very helpful, thanks! One last question: if you go to https://arty.name/localstorage.html in Firefox, what does the line below `Results will appear below:` say?

You're welcome.

It says: "5200000 characters were stored successfully, but 5300000 weren't."

**Comment by swissspidy** [comment]
@carlos-kelly Another Pea pod ticket I believe. There should be  `try { } catch` blocks **everywhere** when working with `localStorage.setItem`
