### ISSUE TITLE
QA - Media Library Panel

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#585]
This issue is for testing the Media Library Panel functionality. Below are steps intended to aid with testing. These are the features covered in this issue:

search        
infinite scroll        
filter        
hover to play video

**[UX](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=0%3A1)**

**QA Steps**
1. Use the search bar in the media panel to search for a file
2. Ensure results are filtered on each keystroke
3. Clear your search query 
4. Ensure you are brought back to the "zero state" with all media shown/no filtering
5. Click on the "Images" filter, ensure the results are filtered
6. Click on the "Video" filter, ensure the results are filtered
6. Hover over a video, ensure it begins to play
7. Click on the "All" filter, ensure you are brought back to the "zero state" with all media shown/no filtering
8. Sroll through the media library to test "infinite scroll"

**Comment by csossi** [comment]
- Deleted image from Media Library. Returned to Stories and saw that images I deleted are appearing as "broken":
![image](https://user-images.githubusercontent.com/16945664/77078470-01585600-69cd-11ea-8aa1-76185a871c75.png)

**Comment by csossi** [comment]
Note: The images eventually disappeared from stories after a long delay (approx 5 min)

**Comment by swissspidy** [comment]
I cannot seem to reproduce that behavior. When I reload the editor after deleting the image from the library, the image was no longer listed in the editor.

@csossi When you "returned to Stories", did you just go the a different tab, or did you go through Stories -> All Stories to open the editor afresh? A quick screencast might help.

**Comment by csossi** [comment]
Video with steps taken, @swissspidy  - https://drive.google.com/file/d/1qBDWpEmMuwDVk4MPptpb3HOKp-wj36tZ/view

Note: the image I'm deleting in this vid was the background image in the story

**Comment by csossi** [comment]
@jauyong - "X" to clear field is missing:
![image](https://user-images.githubusercontent.com/16945664/77233013-ff33fa00-6b7a-11ea-993d-8d7c5e988406.png)

**Comment by csossi** [comment]
@jauyong 

Dragged-and-dropped a 1.02 MB jpg. Appeared on page as rotated and stretched:
![image](https://user-images.githubusercontent.com/16945664/77233313-107e0600-6b7d-11ea-8e0c-a689d91ca400.png)

**Comment by diegovar** [comment]
I can't reproduce this issue.

**Comment by jauyong** [comment]
closing this as CUJ testing will cover any required tests
