### ISSUE TITLE
Update Naming and Filtering of Page Layouts by page type

### ISSUE THREAD

**Issue by zachhale** [GoogleForCreators/web-stories-wp#5872]
## Feature Description

Page type names should follow the structure above, corresponding to each page in the matrix on the right. For example:

DIY Cover
DIY Section
DIY Quote
DIY Editorial
Fashion Cover
Fashion Section
Fashion Quote
[...]

Some page types (section, editorial, list) may include more than one design option per layout. If unique names are needed for dev, please use numbers at the end of each name. End users should not see numbers.

When user opens layouts panel for first time (default state), page types should be grouped together, in the same order from the explore templates section in the Stories dashboard.

When user selects one or more filter pills, the corresponding page types only appear in the panel.
## Additional Context

Figma: https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=4176%3A81

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
Let's also make sure the proper alt text is attributed to each page layout here.

**Comment by zachhale** [comment]
This has already been merged to `main`.

**Comment by csossi** [comment]
Verified in QA
