### ISSUE TITLE
Replace rogue images with shapes in templates/page layouts

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#5873]
## Feature Description

There are a few image assets in templates/page layouts that should be shapes. These are just overlooked images that have had no negative impact to usability - now with page layouts and removing the bulk of the image assets, we have realized these should be updated to be shapes to create continuity. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

Images that should be shapes: 
(round 1)
- DIY socials 
- Travel socials 
- Entertainment stars 

(round 2, added on review) 
- Arrow on trends 
- Music note on entertainment 

(round 3) 
- trends: hearts on "i woke up like this" 
- fashion: arrow on the handbag page that is next to "learn more" 
- wellness: arrow on left of learn more of yoga page

**Comment by swissspidy** [comment]
Just let me know once you remove those images and I can remove them from the CDN as well.

**Comment by csossi** [comment]
Verified in QA

**Comment by swissspidy** [comment]
@littlemilkstudio With #5899 now QA'd & merged, only round 3 is missing now I believe?

**Comment by maxyinger** [comment]
@swissspidy could you highlight which 3 you're seeing that need updated?

**Comment by swissspidy** [comment]
@littlemilkstudio I was just referencing "round 3" mentioned in the ticket description:

> * trends: hearts on "i woke up like this"
> * fashion: arrow on the handbag page that is next to "learn more"
> * wellness: arrow on left of learn more of yoga page

It's not clear to me  whether #5899 addressed those as well or not. Could you shed some light on this for me? :)

**Comment by maxyinger** [comment]
Oh haah. I see. Yup I ended up including all of those changes in #5899 so this ticket should be done and no outstanding work needed

**Comment by swissspidy** [comment]
Got it, thanks!
