### ISSUE TITLE
Remove "squish" from dashboard header 

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#5874]
## Feature Description

The new dashboard designs do not have the same "squish" of the header on scroll that currently exist. Let's remove this proactively from the dashboard to minimize changes all at one in the dashboard and make sure that we don't cause regression bugs. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

- Dashboard header should stay 1 size on scroll. 
- Scroll up button should work as it currently does. 
- If wordpress menu is longer than the viewport and you expand part of it, the page should still scroll (bug #5647)

**Comment by csossi** [comment]
Verified in QA
