### ISSUE TITLE
Animation panel: Use blue accent colors not purples

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#5875]
## Feature Description

[Request from Sam]: 
Update dropdown animation effect button colors and direction inputs to use the same button colors that exist in the editor now, not the purples that are part of the new design.

## Additional Context

Animation effect dropDown is located in the right side panel and available when you have an element selected on a page. 
![Screen Shot 2021-01-14 at 8.42.14 AM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/9f755661-0cc6-4772-a16e-f71e864441bd)

The animation direction inputs are also in the animation panel on the right side, it appears for a few different animation types that allow for direction specifications (fly, whoosh, scale, rotate). Pick one of those animations and see this new input: 
![Screen Shot 2021-01-14 at 8.44.44 AM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/17c32b7e-5685-4052-8ec8-e85ed269391d)

![Screen Shot 2021-01-14 at 8.45.05 AM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/6cdf3abd-89db-418e-96dd-d8a5121f7fe4)

The purple color that shows the various hover/active of these two inputs is currently purple - which is the new accent color that will be part of the redesign. The animation panel was only ever intended to be implemented as the new designs, but we're caught in limbo currently as we fast track a few features ahead of the redesign. This request is to tweak those purple shades to use the existing theme instead so that there's no color shift and mixture of color themes 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

The purple parts of the above screen shot animation panel forms are now blue.

## Implementation Brief

Inside `edit-story/theme` you'll see available colors. Use the blue buttons visible in the editor as a guidepost for the colors to replace the purples with in `edit-story/components/panels/design/animation/directionRadioInput` and  `edit-story/components/panels/design/animation/directionChooser`.

To expedite this, since it's a request with no designs - take screenshots of the change and run the update past @samitron7 in slack to make sure the color swap is what she wants before the change is merged.

**Comment by csossi** [comment]
Verified in QA

**Comment by tmagalhaes-huge** [comment]
Looks good, closing. @samitron7 @ivayloklissarov @aaecheverria
