### ISSUE TITLE
Settings: only disable GA input field if Site Kit Analytics module is active

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5877]
## Feature Description

Right now, the input field to enter the Google Analytics ID is disabled even when Site Kit is installed, but not actually active. It makes more sense to do this when Site Kit is active, and its Analytics module is active as well.

Otherwise this is confusing for users ([case in point](https://wordpress.org/support/topic/story-not-displaying-properly/#post-13894326)).

Code in question:

https://github.com/google/web-stories-wp/blob/ed95fb387de1921cd6906980f3c9dd5b7dc9a850/assets/src/dashboard/app/views/editorSettings/googleAnalytics/index.js#L178

Should check for `siteKitCapabilities.analyticsModuleActive` instead of `siteKitCapabilities.siteKitInstalled`.

The helper text can still be displayed when Site Kit is installed, as we then simply point the user to activate the plugin. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Another issue here:

https://github.com/google/web-stories-wp/blob/ed95fb387de1921cd6906980f3c9dd5b7dc9a850/assets/src/dashboard/app/views/editorSettings/googleAnalytics/index.js#L129-L131

The "Site Kit by Google has already enabled Google Analytics for your Web Stories" message should only be displayed when the analytics module is active. Confusing for users otherwise.

**Comment by swissspidy** [comment]
Bumping priority as we got yet another report from a confused user.

**Comment by BrittanyIRL** [comment]
Added to sprint so we can prioritize.

**Comment by csossi** [comment]
Verified in QA (except for full live setup)
