### ISSUE TITLE
Pre Publish Checklist: Some updates not getting noticed 

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#5879]
## Bug Description

It appears that some updates to stories aren't getting caught by the pre publish checklist and updating the list of warnings/errors when former issues are resolved: 

- After adding more than 4 pages and applying page layouts to all, the pre-publish checklist still lists “Story too short” and “too little text”
- After populating a title, the pre-publish checklist still shows “Missing story title”

## Expected Behaviour

The checklist should not still show these issues once resolved 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Reminds me of #5768

**Comment by zachhale** [comment]
I'm having a hard time reproducing this. Who reported this and what browser was it on?

**Comment by BrittanyIRL** [comment]
@bmattb Do you have more context on this or a person who reported it from bug bash?

**Comment by LuckynaSan** [comment]
@BrittanyIRL The original report was from @tmagalhaes-huge. It was also reported by a [user in the forum](https://wordpress.org/support/topic/errors-with-new-update-2/). 

I was able to reproduce it on Chrome (Version 88.0.4324.96) & MacBook Pro (13-inch). 

Steps to reproduce: 
1. Open a story that has a title and cover image: https://jmp.sh/QyqpKzZ 
2. See the checklist errors: https://jmp.sh/feiTJgC

Note:
1. The errors display in an incognito window, after re-uploading the cover image, updating the title, and re-publishing the story. 
2. Error occurs after duplicating the story as well. (Example video: https://jmp.sh/zf28eNm)

**Comment by BrittanyIRL** [comment]
Thank you, @LuckynaSan  this is extremely helpful. 

@embarks or @zachhale  could you take a look at this when you've got a sec?

**Comment by embarks** [comment]
@BrittanyIRL also having trouble with repro using the steps provided. I tried different scenarios, like duplicating a large story, running with the checklist open/closed, and everything gone over in the comments above. Running Chrome 88 on MacOS as well.

**Comment by BrittanyIRL** [comment]
@embarks dang. Well, let's keep an eye on it then. We'll leave the ticket in the backlog just so it can be tracked. @LuckynaSan if you notice any other uses having the same or similar issues, will you tag me?

**Comment by LuckynaSan** [comment]
I created a new story with the title and cover image present. I duplicated the story and there is a brief moment where the checklist shows missing cover image and title messages. See [video](https://jumpshare.com/v/rrdZT3gJPtyITm4nT0OK).

**Comment by jamesozzie** [comment]
I'm unable to recreate this on a new story or with existing stories. 
- Windows 10 OS
- Chrome browser, both incognito and regular browsing session. 
- Plugin version 1.3.0

I can however recreate the same flicker as @LuckynaSan (Windows OS, Chrome browser) above. This occurs with a newly created story only.

**Comment by zachhale** [comment]
Thanks for that video @LuckynaSan. It's very helpful to know that it's just on initial load that this is happening. I can reproduce this!

**Comment by BrittanyIRL** [comment]
@zachhale if you can reproduce and want to do some discovery/fix this if you have bandwidth this week feel free to add this to the sprint and move to in progress (and point :) )

**Comment by maxyinger** [comment]
Couldn't reproduce. I believe it's all resolved with the updates to make ppc less annoying

**Comment by BrittanyIRL** [comment]
@csossi this is just testing on staging, pretty sure it's resolved from other updates.

**Comment by csossi** [comment]
Verified in QA
