### ISSUE TITLE
FTUE: REST API endpoint for tips

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#5881]
## Description
Ability to keep track of what help center items a user has read, stored as part of user data.

## Acceptance Criteria 

- Ability to update what tips are read
- Ability to read what tips are read
- Ability to reset what tips are read

## Added Context 

- This also needs to correspond to some sort of ID system for the tips

**Comment by swissspidy** [comment]
> This should be flagged by release so that when more FTUE is added we can be graceful in what to show users.

As long as we know which tips are new/read/unread, we don‘t really need to know about releases, no? Seems like redundant info.

**Comment by BrittanyIRL** [comment]
The only use case I can think of where we'd want to flag it by a version/release is if the language surrounding a tip has been updated or something added? Probably not something we really need to worry about I suppose. Mostly just wanted to be thorough in thoughts about what all is necessary. I'll update the description.

**Comment by swissspidy** [comment]
So I was thinking about this a little bit and storage wise there are two possibilities:

1. Use special WordPress user settings cookie  
  This would save data in a cookie that is mirrored to the database by WordPress. Kinda clever, but it also means having to deal with cookies.
2. Use existing `/users/me` REST API endpoint  
  Same thing we already use for the telemetry opt-in on the Settings screen. Easy to implement and use in the editor, as it's nothing new. Plus we could preload the data so there's no extra HTTP request on initial page load.

Given the drawbacks of (1), I'd go with the latter.

The data format could be a simple as this, with the key being the tip's ID, and `true`/`false` indicating read/unread:

```json
{
 "awesome_design_panel_trick": true,
 "yet_another_tip": true,
 "safe_zone_coolness": false
}
```

When interacting with the tips, just send the new object with updated data to the API.

You'd want to do this in bulk though so you only send 1 HTTP request, not 10 for each tip I'm reading.

> The only use case I can think of where we'd want to flag it by a version/release is if the language surrounding a tip has been updated or something added?

If there's a significant change to a tip we could just give it a new name? Or append a `_v2` suffix or something.

**Comment by BrittanyIRL** [comment]
Big fan of mirroring the process of telemetry opt-in, i think the plan you lay out is perfect. @embarks thoughts? 

(yeah, doing `_v2` for drastically different versions of a tip sounds good, just wanted to make sure we were thinking beyond the initial 7)

**Comment by embarks** [comment]
> 
>     2. Use existing `/users/me` REST API endpoint
>        Same thing we already use for the telemetry opt-in on the Settings screen. Easy to implement and use in the editor, as it's nothing new. Plus we could preload the data so there's no extra HTTP request on initial page load.

I'm in favor of this approach

> Given the drawbacks of (1), I'd go with the latter.
> 
> The data format could be a simple as this, with the key being the tip's ID, and `true`/`false` indicating read/unread:
> 
> ```json
> {
>  "awesome_design_panel_trick": true,
>  "yet_another_tip": true,
>  "safe_zone_coolness": false
> }
> ```
> 
> When interacting with the tips, just send the new object with updated data to the API.
> 
> You'd want to do this in bulk though so you only send 1 HTTP request, not 10 for each tip I'm reading.
> 
> 
> If there's a significant change to a tip we could just give it a new name? Or append a `_v2` suffix or something.

extremely straightforward. Thanks Pascal!

**Comment by swissspidy** [comment]
Awesome, then we'll get it done!

**Comment by spacedmonkey** [comment]
@BrittanyIRL Do you have a structure of what you want this object to look like or just keep it a freeform object. Should the REST API return a default value if nothing has been set. Can provide details on what you would like. 

@swissspidy Where should this code live? New class for FTUE or somewhere else?

**Comment by swissspidy** [comment]
> Do you have a structure of what you want this object to look like or just keep it a freeform object. Should the REST API return a default value if nothing has been set.

I'd say freeform object is fine for now, with an empty object being the default

> Where should this code live? New class for FTUE or somewhere else?

New class sounds fine. I'd call it something else though, perhaps `Onboarding` or even `User_Preferences` (we could move `web_stories_tracking_optin` user meta registration there too)

**Comment by spacedmonkey** [comment]
`User_Preferences` sounds good to me.
