### ISSUE TITLE
Quick Tips Main Menu

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#5883]
## Description
List of tips displayed in open help center main menu
https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=2%3A91941

![Screen Shot 2021-01-11 at 4.50.35 PM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/f9630df6-fae7-4c24-9692-78bf4e4711a7)

## Acceptance Criteria 

- Should show when help center toggle button is set to open
- Should be collapsable by clicking the 'x' button
- Should have translated list of tips
- Should show unread icon at front of items that are not read (UX only, logic separate),
- 
- Each list item should be clickable
- When list item is clicked that tip should be the active view in the help center.

**Comment by maxyinger** [comment]
Updating footer links to:
- [Read start guide](https://wp.stories.google/docs/)
- [Visit support forum](https://wordpress.org/support/plugin/web-stories/)
- [Storytime YouTube series](https://www.youtube.com/watch?v=MCcHkmzrIVY&list=PLfVPq9A6B0RNoQ3HTE9LQzgAdVzcb7tmt)

as per discussion here: https://xwp.slack.com/archives/CCCAUAH6F/p1612369517091700
