### ISSUE TITLE
Quick Tips Animated Transitions 

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#5884]
## Description
When changing tips in help center there should be a "swipe" move in animation for fluidity

## Acceptance criteria

(Try to get early buy in on this from Tad) 
Applies to clicking a tip in main menu and navigation in tip view (go to main menu, previous, next)

## Still to find out
- Are entrance/exit animations index dependent for direction? or do they always swipe out to the left and in from the right?

## Current scope
- Adds utility for exit animation
- Adds custom layout to animate bg to new heights of different views
- Adds "swipe" animation on view transitions with panel animating to new height
- Adds open/close anim when opening or closing help center modal

**Comment by maxyinger** [comment]
Taking off the estimate cus this could be more or less work depending on mockups.

With "Swipe in/out", There's some complexity I still need clarification on:
- Different tips are different heights. Would the popup need to animate height between tips?
- Would tips/views need to animate out before they unmount?
- Would animations be directional depending on order of tips?

All these factors are doable, but would add significant complexity to the logic & layout for this feature. They are also more foundational and harder to add after the feature is already built out. 

Having a mockup would answer a lot of questions here. There's not really any animations currently being used in the editor UI besides the animation panel, so we don't really have any existing motion language to pull from.

I want to avoid adding complexity to the codebase unless it's an explicit requirement. Let me know where this stacks up as a priority for y'all & what your thoughts are. Until then, gonna add a "UX needed" flag on this.

 @tmagalhaes-huge @aaecheverria

**Comment by aaecheverria** [comment]
Hi @littlemilkstudio ,

Thanks for the detailed feedback and clarification. We are discussing them with the team to get back to you ASAP. 

Q.q Could you please elaborate a bit more on the second question? We are not quite sure we understand it.

Thank you!

**Comment by maxyinger** [comment]
Awesome @aaecheverria Thanks!

> Q.q Could you please elaborate a bit more on the second question? We are not quite sure we understand it.

Yea absolutely. 
Say you were on a tip and you pressed the `next` button to view the next tip. Would the tip you're on animate out? or just disappear while the next tip animated in? 

I only ask cus animating out would require some extra engineering effort. Still obtainable, just relevant to estimating work

**Comment by tmagalhaes-huge** [comment]
@littlemilkstudio I see, thanks for clarifying. We were hoping the tips would have a swipe motion left and right (within the panel) as the user clicks next or previous, to indicate continuity. As if the tips were all in a row, in a carousel. If that's not doable, please let us know. If we need to keep the panel sizes consistent in order to make that happen, we can explore that option too.

**Comment by maxyinger** [comment]
@tmagalhaes-huge Awesome! Definitely doable, just wanted to verify it's what y'all were asking for. I can make the height of the panel animate too. would you prefer that or would you like the height just to be static?

**Comment by tmagalhaes-huge** [comment]
@littlemilkstudio Ideally the height would animate to avoid lots of empty areas on some of the tips. Since the next/previous buttons stay in the same place, that should be ok. Thank you!
