### ISSUE TITLE
Quick Tip Navigation Menu

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#5885]
## Description 
Navigation with pagination displayed in help center once a user leaves the main menu.

![Screen Shot 2021-01-11 at 4.58.57 PM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/b2766484-5ced-46b5-9af8-7b4150dca98f)

## Acceptance Criteria 
Visible once a user leaves main menu of quick tips. 
Should have ability to go back to all tips. 
Should have ability to go to previous and next tips. 
Previous and Next buttons should be disabled (respectively) when there is not a previous or next tip to go to.

**Comment by tmagalhaes-huge** [comment]
@BrittanyIRL @littlemilkstudio Minor thing here but the spacing between the left arrow icon and "All tips" isn't matching our design (should be 4px), and the spacing between "Previous" and "Next" should be 12px. See below.
<img width="371" alt="Screen Shot 2021-03-09 at 10 51 29 AM" src="https://user-images.githubusercontent.com/73555855/110498681-8a2c3e00-80c5-11eb-8268-2abdfaac496d.png">

Also, the pressed state should not be purple, but gray. We updated the global active state for tertiary buttons in the DS to Interactive BG (Dark)

**Comment by BrittanyIRL** [comment]
Thanks, @tmagalhaes-huge ! Could you make new issues for these? There's an 'enhancement' and a 'bug' template, pick which ever you view these as and assign the issues to me so that I can triage.  

Typically issues are assigned to TLs for the pod that did the work that the issue stems off of. 

Let me or @bmattb know if you have questions or if this process won't work! It should allow UAT to become a more active process of our board, which is exciting.

**Comment by tmagalhaes-huge** [comment]
@BrittanyIRL @bmattb Sounds good. Just a bit confused here then, when should we make comments on the existing tickets here vs. closing them and then creating a new bug/improvement ticket? We were under the impression that the goal of the UAT column was for us to verify everything looks good or make comments until addressed, then closing all in one ticket vs. multiple tickets. Happy to discuss on a call or Slack if that's easier.

**Comment by BrittanyIRL** [comment]
@tmagalhaes-huge - totally fair. 

We (as eng) have always made new tickets out of things discussed in UAT. I thought it might be worth streamlining by including design in that process. The reason is that in UAT everything's already merged. So, its additional work to be done that needs to be scoped and planned for.

**Comment by tmagalhaes-huge** [comment]
@BrittanyIRL Gotcha. So is it safe to say after we review the tickets in UAT we either:

a) close the ticket without any additional action (if it looks good)
b) identify bugs and/or improvements, create tickets for those, then close the ticket here (should we link to the original ticket in this case?)

Thanks!

**Comment by BrittanyIRL** [comment]
that's perfect, yes!

**Comment by tmagalhaes-huge** [comment]
@ivayloklissarov Please see above for moving forward on reviewing UAT tickets. I can walk you through the process of creating bug/improvement tickets.
