### ISSUE TITLE
Quick Tip Screens 

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#5886]
## Description
Should add initial 7 quick tip screens to help center. 
Each view should have an animated image (mp4 file), a title, and some body text. 

https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=4184%3A294993

## Acceptance Criteria 

Should have 7 screens for the following (please reference Figma) 
1. Add background media 
2. Crop Selected element
3. Crop elements using shapes 
4. Stay within the safe zone 
5. Preview your web story 
6. Add links to design elements 
7. Enable swipe-up option

Assets here: https://drive.google.com/corp/drive/folders/1Iabww-Bs6p6kycqeQ0DxYLKkKI5AYjG6

**Comment by BrittanyIRL** [comment]
Convo in slack started by @aaecheverria  Jan 13, 2021 about checking early if lottie files will work for us. Copying here: 

> This is the Lottie file example for the animations within the companion/helper module. Please let us know if this is working ok so we can prepare and hand-off  the rest of the animations

[Creator_Module_1.zip](https://github.com/google/web-stories-wp/files/5816913/Creator_Module_1.zip)

@embarks can you do a quick sanity check that this will pan out?

**Comment by aaecheverria** [comment]
Hi guys @embarks @BrittanyIRL @swissspidy 

Please find below the drive folder link with the exported assets for the tips animations (in the format we discussed in the slack channel: MP4 and webm).

https://drive.google.com/corp/drive/u/0/folders/1Iabww-Bs6p6kycqeQ0DxYLKkKI5AYjG6

There is one missing (preview tip), we will be adding it on Monday.

**Comment by aaecheverria** [comment]
Hi @embarks @BrittanyIRL 

We are making some tweaks to some of the assets. . We will post the new ones tomorrow at last. Please let me know if this works for you.

On the other hand, copy for the FTUE companion helper is final now and approved by Sam.

**Comment by BrittanyIRL** [comment]
@aaecheverria Thanks for the update! 

Asset updates for tomorrow should be fine. It's great to know the copy is approved. This is the copy that is currently in figma or is there a doc somewhere? 

@littlemilkstudio ^^ above thread just for context since you're the one building!

**Comment by aaecheverria** [comment]
Hi @BrittanyIRL @embarks 

In the same shared folder you can find the latest versions of the motion assets: 
https://drive.google.com/corp/drive/folders/1Iabww-Bs6p6kycqeQ0DxYLKkKI5AYjG6 **(please dismiss the Old version and the Future version folders for now).** 

Thanks!

**Comment by aaecheverria** [comment]
Hi @BrittanyIRL @littlemilkstudio @embarks 

Tad, told me there were some transparency issue with the assets. In the same folder you can find the updated version of the 7 tips. Please let us know if they are working as intended now :) 

Thanks!

**Comment by embarks** [comment]
@aaecheverria thank you so much for updating all the assets! I really appreciate it. Could you check on Module 1 and Module 7 again for me? I'm still seeing a black background just on those two. These look great. ✨
