### ISSUE TITLE
Done Screen + Tip Pagination to Prioritize Unread Tips

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#5888]
## Description
If a user starts with the 6th tip and hits the "next" button they would see a grayed out "next" while on the 7th tip. We should prioritize unread tips to keep users reading in the help center until they are out of tips. 

This might require a little finesse with Tad for exact functionality. 

Currently not in scope for MVP

## Acceptance criteria 
- Done screen to display when all tips are read
- Unit tests

**Comment by maxyinger** [comment]
**scenario 1**
lets say tips looks like this:
```
{
  tip_1: read, <-- user viewing tip_1
  tip_2: read,
  tip_3: read,
  tip_4: unread,
  tip_5: read,
}
// next clicked
{
  tip_1: read,
  tip_2: read, <-- would user go here?
  tip_3: read,
  tip_4: unread, <-- or here?
  tip_5: read,
}
```
Based off the description, I'm assuming the answer is `tip_2`.

**scenario 2**
```
{
  tip_1: read,
  tip_2: unread,
  tip_3: unread,
  tip_4: read,
  tip_5: read, <-- user viewing tip_5
}
// next clicked
{
  tip_1: read,
  tip_2: read, <-- user viewing tip_2, updates to read
  tip_3: unread,
  tip_4: read,
  tip_5: read,
}
// previous clicked
{
  tip_1: read, <-- would user go here to tip_1?
  tip_2: read,
  tip_3: unread,
  tip_4: read,
  tip_5: read, <-- or here to tip_5?
}
```

**scenario 3**
Last question, is next only disabled if they're at the last tip AND all tips have been read? or is it disabled if all tips are unread. scenario:

```
{
  tip_1: read,
  tip_2: unread,
  tip_3: unread,
  tip_4: read,
  tip_5: read, <-- user viewing tip_5
}
// next clicked
{
  tip_1: read,
  tip_2: read, <-- user viewing tip_2, updates to read
  tip_3: unread,
  tip_4: read,
  tip_5: read,
}
// next clicked
{
  tip_1: read,
  tip_2: read,
  tip_3: read, <-- user viewing tip_3, updates to read
  tip_4: read,
  tip_5: read,
}
// would the next button be disabled at this point? or would it take you to `tip_4`?
```

**Comment by BrittanyIRL** [comment]
Great questions, @littlemilkstudio  thank you for the examples! 

@tmagalhaes-huge @aaecheverria @Cecil921  could you shed some light on what the intentions are?

**Comment by tmagalhaes-huge** [comment]
Hey guys. Here's what I'm thinking:

Scenario 1: agreed with @littlemilkstudio 

Scenario 2: tip_5, if we can calculate where they are coming from. It would be weird to click "previous" and not go to the tip the user was just viewing before.

Scenario 3: former, "next only disabled if they're at the last tip (**done panel**) AND all tips have been read"
