### ISSUE TITLE
Page Layouts: Enter key should confirm dialog without re-opening

### ISSUE THREAD

**Issue by zachhale** [GoogleForCreators/web-stories-wp#5890]
## Bug Description

When tabbing then clicking enter on layout to overwrite a page and confirming the modal, hitting enter on the confirmation dialog re-triggers the layout enter. 

## Expected Behaviour

Click enter and the page layout should apply and close dialog.

## Steps to Reproduce

1. Click to apply page layout
2. Tab to "Apply Page Layout"
3. Click enter
4. Layout applies, but page dialog stays open

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
In general, the dialog should always move keyboard focus to the first focusable element inside the dialog as [per WCAG guidelines](https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/dialog.html).

Similarly, when the dialog is closed, focus should return to where it came from.

**Comment by zachhale** [comment]
@BrittanyIRL ^

**Comment by BrittanyIRL** [comment]
@csossi let me know if you need more details on this, we need this one for release so if you can prioritize it that would be really helpful.

**Comment by csossi** [comment]
Verified in QA
