### ISSUE TITLE
Media Library: cannot edit or delete media items anymore

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5893]
## Bug Description

One can no longer edit or delete media items anymore in the media library.

When clicking on the three dots it inserts the media item instead of opening the a menu.

## Expected Behaviour

1. Hover over media item in media library
2. Click on three dots
3. Be able to edit or delete media item

## Steps to Reproduce

1. Hover over media item in media library
2. Click on three dots
3. Notice that media is inserted on page instead

## Screenshots

https://user-images.githubusercontent.com/841956/104295874-47812780-54c1-11eb-83de-30f6b17ddbe0.mov

## Additional Context

- Plugin Version: 1.2.1 / current `main`
- WordPress Version: 5.6
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
