### ISSUE TITLE
Editor: Update Text Presets to Latest Designs

### ISSUE THREAD

**Issue by maxyinger** [GoogleForCreators/web-stories-wp#5900]
I think this just involves updating line height and bg text mode for the presets. Updates here:
https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable

**Comment by csossi** [comment]
The highlight background for the paragraph default extends beyond blue border

Also, shouldn't I be seeing values for padding (according to figma H=8px V=4px)?

![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/7463acd9-3df8-4d98-ac79-f4dcda71fa48)

**Comment by maxyinger** [comment]
@csossi the padding extending beyond the border box is an existing bug that's not related to this update. we can try to increase it's width so that it gets mitigated a little bit, but its a known unrelated bug

Also the padding value there is correct. Sam requested a hidden padding that shows up on the element but isn't seen in the inspector. So at the displayed values on the element this is what should show up in the inspector:
element on canvas : input showed to user
8x4.                          : 0x0
12x8                         : 4x4
28x14.                      : 20x10

**Comment by csossi** [comment]
Ah, ok - thanks so much for clarifying @littlemilkstudio 

Verified in QA
