### ISSUE TITLE
Pre-Publish Panel: layout shift due to scrollbar

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#5901]
Seeing some shifting as I toggle Recommended section
https://share.getcloudapp.com/OAuWBWl1

_Originally posted by @csossi in https://github.com/google/web-stories-wp/issues/5400#issuecomment-739417250_

**Comment by BrittanyIRL** [comment]
This is resolved now that new scrollbar styles are in play. @csossi when you get time, can you verify on stagin?

**Comment by csossi** [comment]
Verified in QA
