### ISSUE TITLE
Templates Project: Batch 0 (5 new Food & Drink templates)

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#5902]
## Feature Description

Food & Drink stories are very popular on the web. We would like to add to the templates gallery in the editor a few new Food & Drink templates for users to be able to use. \

[**Figma link**](https://www.figma.com/file/RTzSw47oi6pEZXEfP2JoBo/Templates?node-id=1%3A7)

![Screenshot 2021-04-16 at 17 29 28](https://user-images.githubusercontent.com/841956/115047968-5b319500-9ed9-11eb-8289-0dc7b4429f22.png)

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by samitron7** [comment]
@pbakaus @o-fernandez @choumx  Created 4 new cooking templates and using one entertainment. Can you guys glance through [these](https://www.figma.com/file/RTzSw47oi6pEZXEfP2JoBo/Templates?node-id=1%3A7) and give me a thumbs up on narration/visual before I start looking for video assets

**Comment by o-fernandez** [comment]
@swissspidy @amedina as templates in general is being handled by you in collab with rtCamp, I'm going to go ahead and assign these tickets to you two. Would that work? I'll keep pea Pod assigned as a collaborator for code reviews, etc. Does that work? @BrittanyIRL

**Comment by csossi** [comment]
Video isn't playing when previewing for the "Toss the beans" page - chicken template (in neither Editor nor FE):

![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/f93c6d41-6d70-413c-a873-a6c86949c1fb)

Not hearing any audio on this display (third page - baking bread)
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/e29838e4-06e6-42dd-b787-160676235027)

No audio (2nd page - artichoke template)
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/816ca945-907b-4152-9f87-7f49de41bdd5)

**Comment by swissspidy** [comment]
@csossi the missing audio is intentional. The othef thing I‘ll have to test.
