### ISSUE TITLE
Page Layouts : Use of a filter prevents the Page Layout Name from appearing

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5908]
## Bug Description

When the user has applied a filter to the presentation of page layouts it prevents the page layout name from appearing to the user on mouse over as expected

## Expected Behaviour

On mouseover of the page layout there is a page layout title/name presented to the user at the bottom of the image:
![Screen Shot 2021-01-12 at 3 47 47 PM](https://user-images.githubusercontent.com/58738530/104371156-a066b500-54ed-11eb-9c35-493e68178c8d.png)

## Steps to Reproduce

1. Open the editor and select the page layout 
2. Mouseover any of the layouts and note the name/title presented
3. Select a filter pill from those presented
4. Note that Page layout name/title is no longer presented on mouseover

## Screenshots

![Screen Shot 2021-01-12 at 3 46 09 PM](https://user-images.githubusercontent.com/58738530/104371974-e28ff680-54ed-11eb-8145-05358e910487.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
This should be resolved now with updates made for filtering. Leaving here for now, if bug still persists after we are done with page layouts as a feature I'll escalate.

**Comment by BrittanyIRL** [comment]
@zachhale - mind double checking that this bug is gone?

**Comment by zachhale** [comment]
This was already resolved when refactoring the filters in #5889
