### ISSUE TITLE
Page Layouts : switching to RTL alters the layout preview 

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5909]
## Bug Description

Switching to RTL is changing the presentation of some of the layouts.

eg: default (RTL) layout preview
![Screen Shot 2021-01-12 at 4 06 40 PM](https://user-images.githubusercontent.com/58738530/104375063-c772b600-54f0-11eb-87c5-7951fe8c671e.png)

switched to RTL layout preview - note the Sun Protection done right layout has changed!
![Screen Shot 2021-01-12 at 4 07 03 PM](https://user-images.githubusercontent.com/58738530/104375089-d48fa500-54f0-11eb-80d6-9eeccb783fa1.png)

Seeing the layout applied to page in editor:
![Screen Shot 2021-01-12 at 4 08 47 PM](https://user-images.githubusercontent.com/58738530/104375123-df4a3a00-54f0-11eb-8f65-b246eb960dd2.png)

## Expected Behaviour

The preview of the page layout should consistently reflect what will be applied to the page.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

- See thread below and Pascal's shared solution for how the editor handles this issue. 
- We should wrap both templates in dashboard as well as page layouts to prevent this.
- Add tests

**Comment by swissspidy** [comment]
@bmattb thus falls under the i18n label, FYI

**Comment by swissspidy** [comment]
I assume this is also happening for templates in the dashboard?

In the editor canvas we fixed this by wrapping the necessary components in `<StyleSheetManager stylisPlugins={[]}></StyleSheetManager>` without the stylis RTL plugin:

https://github.com/google/web-stories-wp/blob/d38a449fcac8d1b2d94a652e48da76511a2b1d3b/assets/src/edit-story/components/canvas/canvasLayout.js#L69-L88

**Comment by BrittanyIRL** [comment]
It sure is! This solution is really helpful to know,  I'll add this to the next sprint for pea pod and we can wrap templates as well as page layouts.

**Comment by zachhale** [comment]
@swissspidy thanks for the tips! Adding `StyleSheetManager` like specified does fix the major issues and brings them in line with what you see when you apply it to the story in the editor, but this highlighted a new issue with text elements behaving unexpectedly in the editor when in RTL mode that is different than how they appear when published/previewed. I think this fix does the fix for the page layouts, but I think we should open a separate issue for text elements appearing inconsistently in RTL in the editor than when they are published.

Editor content of the same exact same story page (from template/page layout):
| Editor RTL | Editor LTR |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/3869/105907900-61029300-5fda-11eb-80a0-a8d201e08bd7.png) | ![image](https://user-images.githubusercontent.com/3869/105907920-6a8bfb00-5fda-11eb-8b31-5f390f7c8ce8.png) |

They look like the LTR when published.

**Comment by swissspidy** [comment]
Thanks for the screenshots!

> I think we should open a separate issue for text elements appearing inconsistently in RTL in the editor than when they are published.

SGTM 👍

**Comment by zachhale** [comment]
Created bug for the inconsistent rendering in editor in #6068

**Comment by kkalarickal** [comment]
QA Status: Fail  -- Unable to access layout preview/dashboard

After applying the code for PR #6069 onto the test server, I am unable to access My Stories dashboard: https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/edit.php?post_type=web-story&page=stories-dashboard

![image](https://user-images.githubusercontent.com/3719412/107040101-0da0f980-67bf-11eb-9405-6335b7bf7f03.png)

Following console error observed:
![image](https://user-images.githubusercontent.com/3719412/107040008-ef3afe00-67be-11eb-9ebc-ad378e77439a.png)

**Comment by swissspidy** [comment]
@kkalarickal I just refreshed the PR, please try again.

**Comment by kkalarickal** [comment]
Thanks @swissspidy 

Status: PASS 

Notes:
- My Stories dashboard loaded successfully and switching RTL - LTR - RTL did not change the presentation of the layouts
- Same result for "Explore Templates"
- Verified that RTL script (arabic) is appearing unchanged during the above transitions
- Noticed that the justification of text is changing ( #6068 )

Also found a side effect in the display of time/date picker within Story > Document > Publishing time

LTR shows up as
![image.png](https://images.zenhubusercontent.com/5fc17739d77478a91f8d75e3/7e618158-ae05-4aa7-8ab4-9136adcd24f5)

RTL shows up with the calendar chopped off
![image.png](https://images.zenhubusercontent.com/5fc17739d77478a91f8d75e3/0528d3c8-b8ec-4dae-827b-124ddbe90c22)

@swissspidy - should this go into #6068 or another bug ?

**Comment by swissspidy** [comment]
@kkalarickal #6068 is about text elements on the canvas, which is completely unrelated to the date picker. So this warrants a new bug ticket :-)
