### ISSUE TITLE
Page Layouts - Prepublish checklist low contrast warning triggered by font colours

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5913]
## Bug Description

orginally reported by @embarks:

The font colors for many of the simple templates trigger the low contrast warning which are to w3 standards. Could be addressed with checking font size as well, but the smaller fonts will always trigger.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
Let's go ahead and double check as you suggest against the font size for best practices of contrast. @o-fernandez @samitron7 if you disagree, let me know!

**Comment by csossi** [comment]
Verified in QA
