### ISSUE TITLE
Frontend: Twitter Card markup incorrect and incomplete

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5918]
## Bug Description

Our Twitter card markup currently consists two meta tags:

https://github.com/google/web-stories-wp/blob/13f1a40966d5213ba7ec6832777b317d84a29e8e/includes/Discovery.php#L266-L279

**First**, the latter tag is incorrect, as it should be `<meta name="twitter:image"`, not `<meta property="twitter:image"`.

Because of that, Twitter is actually falling back to the `og:image` version, so it _seems_ like it works as expected.

**Second**, I think we should also implement `twitter:image:alt` as there's no `og:*` fallback for that.

Documentation for reference:

https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image
https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/markup

**On that note...**

I think it might be worth adding filters to `Discovery::print_open_graph_metadata()` and `Discovery:: print_twitter_metadata()`, just like `Discovery::get_schemaorg_metadata()` has a filter already as well.

This way devs could extend the markup to include things like their twitter username, or different descriptions for Twitter, etc. if they're not already using another plugin for this, of course.

## Additional Context

- Plugin Version: 1.2.1 / `main`
- WordPress Version: 5.6
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
What should the alt value be? Should it be the alt value of image attachment or should it be the site name?

**Comment by spacedmonkey** [comment]
For reference, code fallbacks to site name if alt is empty for the custom logo. 

https://github.com/WordPress/wordpress-develop/blob/fdfe1830175822bca3ee1517b5ac420091bc45a3/src/wp-includes/general-template.php#L1042-L1045

**Comment by swissspidy** [comment]
Site name doesn‘t make much sense for the story cover image on a singky story page. So I‘d say the story title should be used for now
