### ISSUE TITLE
Website: Improve storage for static assets

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5961]
## Task Description

This is a long-standing open to-do item related to our static assets hosting. With more templates in the making, the repo size will grow considerably, so we need a solution here.

We can keep the microsite and small images in `static-site` as today, but the template assets we should move at some point.

In other words:

There will be 50 templates that we need to host somewhere and make available via some API.

Some thoughts:

* Move assets to separate repository  
  * This will just move the problem and make another repository very big
* Use [Git LFS](https://docs.github.com/en/github/managing-large-files/about-storage-and-bandwidth-usage)  
  * Comes with storage & bandwidth quotas
  * makes the repo less portable
  * is more meant for _large_ files, not _many_ files
* Move everything to GCP bucket / Firebase Storage
  * Less easy to contribute

----

<details>
<summary>Current git-sizer output</summary>

```
$ git-sizer
Processing blobs: 48401                        
Processing trees: 57445                        
Processing commits: 12597                        
Matching commits to trees: 12597                        
Processing annotated tags: 0                        
Processing references: 121                        
| Name                         | Value     | Level of concern               |
| ---------------------------- | --------- | ------------------------------ |
| Overall repository size      |           |                                |
| * Blobs                      |           |                                |
|   * Total size               |  13.8 GiB | *                              |
|                              |           |                                |
| Biggest objects              |           |                                |
| * Commits                    |           |                                |
|   * Maximum size         [1] |  60.2 KiB | *                              |
| * Blobs                      |           |                                |
|   * Maximum size         [2] |  34.8 MiB | ***                            |
|                              |           |                                |
| Biggest checkouts            |           |                                |
| * Maximum path depth     [3] |    11     | *                              |
| * Maximum path length    [4] |   143 B   | *                              |
| * Total size of files    [5] |  1.19 GiB | *                              |

[1]  8616cbca8b04dba66f16c85dc84204947b78c430
[2]  7bbf0ee5cae3d6f49ddb4745b8734d0af2131c49 (refs/heads/static-site:public/video/NoDaysCycle-v1.mp4)
[3]  01b18435bb1897cb1cd522581171f197884f0ba0 (9f715490f21f1ef139194ca7afdabe815e5a6167^{tree})
[4]  b4fbe6fae6c474162502a14798175be21af8cd5b (468501b165a6249b270947f64c04ffa18720dc56^{tree})
[5]  706025ec537f5027d35b45e12c7015f7a3661e83 (d3cf04a00c3b73b0fd3ef575a47d964990650d78^{tree})
```

</details>

**Comment by swissspidy** [comment]
@choumx would love to hear your thoughts on that

**Comment by Vindulge** [comment]
Is there a thread for those of us wanting to store custom templates? Canva is a short term fix, downside, the text potential when the story is indexed is not there versus using the editor and adding the text. So if we had the ability to upload our own templates, even if I hosted those templates myself on my server, it would save a lot of time.

**Comment by swissspidy** [comment]
@Vindulge Heya, great question! There is a couple of related tickets for this, #223 and #4357. They're not on the immediate roadmap though. The tricky part is that you'd need to create templates in a data format that is supported by the editor. In the meantime, you could create your templates in the editor as draft stories, and then just duplicate the drafts for any new stories you create.

**Comment by Vindulge** [comment]
@swissspidy ok, great idea. Make sense to just have a running draft of our own template(s).

Is there a specific ticket for any editor specific feedback? Like our wish list of making the editor itself more user friendly?

**Comment by swissspidy** [comment]
@Vindulge Not really. Feel free to create a new ticket with your suggestions!

**Comment by dreamofabear** [comment]
I don't have experience with it but Git LFS sounds promising due to git versioning and GitHub support. It should be [very inexpensive](https://docs.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-git-large-file-storage#purchasing-additional-storage-and-bandwidth) for our expected usage.

**Comment by swissspidy** [comment]
I'm a bit worried about the steps required to turn off LFS again if needed, but we can give it a try.

No matter what option we choose, the current repo size will probably remain the same since git history is left untouched.

**Comment by dreamofabear** [comment]
> current repo size will probably remain the same

We could purge history for the template assets. It might speed up some of our CI steps.

**Comment by swissspidy** [comment]
> > current repo size will probably remain the same
> 
> We could purge history for the template assets. It might speed up some of our CI steps.

Checking out the repo in CI only takes a couple of seconds, don't think we can speed that up more.

Any improvements due to purging history would mostly benefit contributors cloning the repo. Right now new contributors will clone 1GB worth of files even when never using the `static-site` branch.

**Comment by swissspidy** [comment]
Documenting the steps required to set up Git LFS (WIP):

1. Install Git LFS (e.g. via `brew install git-lfs` or by following https://docs.github.com/en/github/managing-large-files/installing-git-large-file-storage)
2. Run `git lfs install --manual`  
  This avoid conflicts with Husky's Git hooks (see https://github.com/typicode/husky/issues/108 and https://github.com/typicode/husky/pull/729), but requires manually updating the Git hooks in `.git/hooks`

And here's what I've been doing to migrate the `static-site` branch:

1. Check out `static-site` branch
2. Run the following command:  
    ```bash
    git lfs track "./public/static/**/*.png"
    git lfs track "./public/static/**/*.jpg"
    git lfs track "./public/static/**/*.mp4"
    git lfs track "./public/static/**/*.webm"
    ```
    This will update the `.gitattributes` file and track existing + new files in Git LFS.
3. Dry run to see object sizes:
    ```bash
     git lfs migrate info static-site --include="public/static/**/*.png,public/static/**/*.jpg,public/static/**/*.mp4,public/static/**/*.webm"
    ```
4. Run actual migration:
    ```bash
    git lfs migrate import static-site --include="public/static/**/*.png,public/static/**/*.jpg,public/static/**/*.mp4,public/static/**/*.webm"
    ```  
    ⚠️ This will [rewrite history](https://github.com/git-lfs/git-lfs/blob/main/docs/man/git-lfs-migrate.1.ronn) for the `static-site` branch (but not others)


All contributors modifying assets in `static-site` will have to install Git LFS, see https://docs.github.com/en/github/managing-large-files/collaboration-with-git-large-file-storage

**Note:**

I am not updating the website images+videos to use LFS with this (yet). But it could be done:

```bash
git lfs track "./public/img/*.png"
git lfs track "./public/img/**/*.png"
git lfs track "./public/img/*.jpg"
git lfs track "./public/img/**/*.jpg"
git lfs track "./public/video/*.mp4"
git lfs track "./public/video/**/*.mp4"
git lfs track "./public/video/*.webm"
git lfs track "./public/video/**/*.webm"

git lfs migrate info static-site --include="public/img/*.png,public/img/**/*.png,public/img/*.jpg,public/img/**/*.jpg,public/video/*.mp4,public/video/**/*.mp4,public/video/*.webm,public/video/**/*.webm"

git lfs migrate import static-site --include="public/img/*.png,public/img/**/*.png,public/img/*.jpg,public/img/**/*.jpg,public/video/*.mp4,public/video/**/*.mp4,public/video/*.webm,public/video/**/*.webm"
```

**Comment by swissspidy** [comment]
Closing for now

**Comment by szepeviktor** [comment]
Please be very brave and remove those files with their commit history breaking all forks but
SAVING VERY LONG MINUTES for everybody for the foreseeable future, causing joy 😂

**Comment by szepeviktor** [comment]
Downloading 1.17 GB of data makes contributors go away.
