### ISSUE TITLE
Improve default experience of stories in archives / search results

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5962]
## Feature Description

We currently surface stories on archive pages (like `/web-stories/`) and in search results. For this, we filter the excerpt & content on these screens to display the story in an interactive player.

Most of the time this doesn't always make for a great experience out of the box. Usually because of one of these reasons:

* The theme displays the featured image above the story,  making for an odd layout with a (potentially large) cover image followed by the story player with the same cover  image
* The theme displays both the excerpt and the content, resulting in two players
* The theme displays the excerpt without filters, resulting in some plaintext being displayed that looks more like gibberish.

Some ideas to improve this:

* Do not filter excerpt and title by default
* Hide stories from search results (#5731)
* Allow customization of archives page (#4862)

## Additional Context

Related: #5731

<details>
<summary>Screenshots of current experiences</summary>

<img width="742" alt="Screenshot 2021-01-18 at 18 48 53" src="https://user-images.githubusercontent.com/841956/104948583-d1e3f280-59bd-11eb-9229-92ece3ef646b.png">
<img width="1256" alt="Screenshot 2021-01-18 at 18 46 23" src="https://user-images.githubusercontent.com/841956/104948481-a6f99e80-59bd-11eb-988b-fb66390e99c8.png">
<img width="1055" alt="Screenshot 2021-01-18 at 18 46 12" src="https://user-images.githubusercontent.com/841956/104948490-a9f48f00-59bd-11eb-90d4-182e1e5868b1.png">
<img width="994" alt="Screenshot 2021-01-18 at 18 45 59" src="https://user-images.githubusercontent.com/841956/104948505-ad881600-59bd-11eb-8279-779c71c7071f.png">

</details>

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

Remove the following code:

https://github.com/google/web-stories-wp/blob/bb40603809d5923b9acc156da5bca165afe3594b/includes/Story_Post_Type.php#L209-L211

https://github.com/google/web-stories-wp/blob/bb40603809d5923b9acc156da5bca165afe3594b/includes/Story_Post_Type.php#L697-L726

**Comment by spacedmonkey** [comment]
> Do not filter excerpt and title by default 

Checking the code, we do not filter the title, apart when we insert the database. 

I do personally agree that excerpt doesn't make sense to filter, specially [after](https://github.com/google/web-stories-wp/pull/4264) was merged. Also it is not really the spirit of an excerpt which is meant to be a short version of the content, not the full content.

**Comment by swissspidy** [comment]
> > Do not filter excerpt and title by default
> 
> Checking the code, we do not filter the title, apart when we insert the database.
> 
> I do personally agree that excerpt doesn't make sense to filter, specially [after](https://github.com/google/web-stories-wp/pull/4264) was merged. Also it is not really the spirit of an excerpt which is meant to be a short version of the content, not the full content.

Ah, I think I meant to write "Do not filter excerpt and _content_ by default"

**Comment by spacedmonkey** [comment]
I think that we should remove excerpt. But I am really not sure about removing it on the content. If it is not filtered on content, that the custom post type, then it could fallback to the text in the content or excerpt. This is also a breaking change, people maybe using this archive in main navigation. 

The other option would be not to render the player but image version. But this would likely result in the featured image being displayed twice. 

Could we give the user some options at what they would want to do with these archive pages? Some options in the customize like
- Enable web stories archive [checkbox]
- Display options
   
   - Web stories embed
   - Image
   - Text ( excerpt ) 

Just removing this functionality with giving users an option, may enrage some users.

**Comment by swissspidy** [comment]
> Could we give the user some options at what they would want to do with these archive pages? Some options in the customize like

That's what #4862 is for. Given the unpredictability of how themes display archive content, that's the only feasible solution besides themes adding explicit support.

> I think that we should remove excerpt. But I am really not sure about removing it on the content.

True, we should not remove it for content, but make sure to return the excerpt instead of the player.

Anyway, as you suggested, moving this back.

**Comment by swissspidy** [comment]
Related: https://wordpress.org/support/topic/exit-button-3/

Showing the image + opening lightbox is preferred in some cases
