### ISSUE TITLE
Use proper preview links for stories

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5963]
## Feature Description

There are multiple things to consider:

* Use `preview_link` for autosaves as provided by autosaves REST API endpoint  
  Will contain `?preview=true` and `?preview_nonce=` query args
* Add `?preview=true` query arg otherwise

## Additional Context

Implementation in Gutenberg:

https://github.com/WordPress/gutenberg/blob/aaa9e8301ba6c82d707dc402248c928c40f46700/packages/editor/src/store/selectors.js#L861-L887

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
Why are we not using the preview link given the config object

https://github.com/google/web-stories-wp/blob/d38a449fcac8d1b2d94a652e48da76511a2b1d3b/includes/Story_Post_Type.php#L538

Another idea, would be to add a field to the rest api called "preview_link" that only appears context=edit and that to update on every update. This would refresh the nonce on every save. 

Thoughts?

**Comment by swissspidy** [comment]
> Why are we not using the preview link given the config object

We already do that.

> Another idea, would be to add a field to the rest api called "preview_link" that only appears context=edit and that to update on every update. This would refresh the nonce on every save.

For autosaves `preview_link` already exists and has the correct nonce. For everything else we can use `previewLink`, as we don't need a nonce

I should clarify that this issue is _also_ about the **dashboard**. If you have any draft stories and got to "My Stories" and click on "Open in new tab" for this draft story, it should also use the correct preview link with `?preview=true`

**Comment by spacedmonkey** [comment]
Doing a little research into this, not seeing the issue into the current implementation. I can't replicate the issue detailed in #4566 . Any thoughts on what is need to "fix" this issue?

**Comment by swissspidy** [comment]
Yeah #4566 might be something different.

The issue that was originally reported to me here is that  "Open in new tab" in the dashboard is not working properly. But clicking on "Preview" on the "All Stories" screen worked.
The difference is that we are not adding `?preview=true` to the links, so `WP_Query` will not necessarily know that it's a post preview.

**Comment by spacedmonkey** [comment]
So the issue is in the dashboard? I will take a look

**Comment by swissspidy** [comment]
Yes, but I assume it could also happen in the editor. Needs some verification.

**Comment by spacedmonkey** [comment]
I think the best thing to do is add a new field to web stories endpoint. We can do this by simply copying [this](https://github.com/WordPress/wordpress-develop/blob/ee4c2cf322ebb8b2d0afed5c1a783e6d2fdbfaa0/src/wp-includes/rest-api/endpoints/class-wp-rest-autosaves-controller.php#L410-L421) into our controller. 

Then both the editor and dashboard can just use this field.

**Comment by swissspidy** [comment]
@spacedmonkey makes things easier for the client for sure. so dashboard would do `if ( story is a draft ) { use preview link } else { use normal link }`. let's give it a try 👍

**Comment by csossi** [comment]
Verified in QA
