### ISSUE TITLE
Error: Minified React error 

### ISSUE THREAD

**Issue by onemillionplaces** [GoogleForCreators/web-stories-wp#5964]
Hi,

I can create a new story. This is no problem:
https://one-million-places.com/web-stories

But it is not possible to open or edit an existing story!

1) I open the Story dashbord and I can see my stories
2) Then I click on "Open in Editor"
3) The main screen in the Editor is empty
4) When I click on an image or an button like "Document" I get the error: 

_Something went wrong!
The editor has crashed. Please try reloading the page and report the error using the button below.
Apologies for the inconvenience._

5) In the Console I get the error: **Minified React error #185**
6) This happens in Chrome and Firefox

![screenshot](https://user-images.githubusercontent.com/67807397/104968146-5ac25480-59e5-11eb-89bb-5b3ca5019ef8.jpg)

![screenshot2](https://user-images.githubusercontent.com/67807397/104968154-5dbd4500-59e5-11eb-9cc6-067bb1fe4c9b.jpg)

**Comment by swissspidy** [comment]
Hi @onemillionplaces 

Thanks a lot for your report

Could you perhaps install the current development version and then try again? It should give you a more human readable error message that I'm curious to see.

Download: https://github.com/google/web-stories-wp/suites/1855200705/artifacts/36012665

**Comment by onemillionplaces** [comment]
Hi Pascal,

here is the error report. Does this help?
We can also talk in german if you like ;)

Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    in PublishPanel (at documentInspector.js:32)
    in DocumentInspector (at inspectorContent.js:50)
    in div (created by inspectorContent__InspectorPane)
    in inspectorContent__InspectorPane (at inspectorContent.js:44)
    in section (created by inspectorContent__InspectorPanes)
    in inspectorContent__InspectorPanes (at inspectorContent.js:42)
    in Inspector (at inspectorLayout.js:71)
    in div (created by inspectorLayout__InspectorContainer)
    in inspectorLayout__InspectorContainer (at inspectorLayout.js:70)
    in section (created by inspectorLayout__Layout)
    in inspectorLayout__Layout (at inspectorLayout.js:61)
    in InspectorLayout (at inspector.js:29)
    in div (created by dropTarget__Content)
    in dropTarget__Content (at dropTarget.js:112)
    in Unknown (at dropTarget.js:111)
    in div (created by dropTarget__DropTargetComponent)
    in dropTarget__DropTargetComponent (at dropTarget.js:96)
    in UploadDropTarget (at inspector.js:28)
    in Unknown (at inspectorProvider.js:168)
    in InspectorProvider (at inspector.js:27)
    in Inspector (at workspace/index.js:36)
    in ErrorBoundary (at workspace/index.js:35)
    in div (created by layout__InspectorArea)
    in layout__InspectorArea (at workspace/index.js:34)
    in Unknown (at provider.js:141)
    in RichTextProvider (at workspace/index.js:28)
    in Workspace (at layout/index.js:84)
    in Unknown (at unitsProvider.js:56)
    in UnitsProvider (at canvasProvider.js:223)
    in Unknown (at canvasProvider.js:222)
    in CanvasProvider (at layout/index.js:80)
    in section (created by layout__Editor)
    in layout__Editor (at withOverlay.js:47)
    in Unknown (at withOverlay.js:46)
    in ForwardRef(WithOverlay) (at layout/index.js:79)
    in PrepublishChecklistProvider (at layout/index.js:78)
    in Unknown (at layoutProvider.js:47)
    in LayoutProvider (at layout/index.js:77)
    in Layout (at editorApp.js:76)
    in Unknown (at provider.js:232)
    in DropTargetsProvider (at editorApp.js:68)
    in Unknown (at transformProvider.js:82)
    in TransformProvider (at editorApp.js:67)
    in Unknown (at mediaProvider.js:40)
    in MediaProvider (at editorApp.js:65)
    in Unknown (at fontProvider.js:163)
    in FontProvider (at editorApp.js:64)
    in Unknown (at storyProvider.js:179)
    in StoryProvider (at editorApp.js:63)
    in Unknown (at snackbarProvider.js:73)
    in SnackbarProvider (at editorApp.js:62)
    in Unknown (at historyProvider.js:83)
    in HistoryProvider (at editorApp.js:61)
    in Unknown (at media3pApiProvider.js:163)
    in Media3pApiProvider (at editorApp.js:60)
    in Unknown (at provider.js:43)
    in FileProvider (at editorApp.js:59)
    in Unknown (at apiProvider.js:330)
    in APIProvider (at editorApp.js:57)
    in Unknown (at configProvider.js:28)
    in ConfigProvider (at editorApp.js:56)
    in ErrorBoundary (at editorApp.js:55)
    in Ge (at editorApp.js:54)
    in ye (at editorApp.js:53)
    in App (at edit-story/index.js:55)
    in StrictMode (at edit-story/index.js:54)
    in FlagsProvider (at edit-story/index.js:53)

**Comment by swissspidy** [comment]
That's already very helpful, thank you!

To clarify: there is no error message _before_ you click on "Document", but the editor is just empty?

Does this still happen if you temporarily deactivate all other plugins?

----

> We can also talk in german if you like ;)

Let's keep it in English so my teammates can understand it as well if they want to chime in :)

**Comment by onemillionplaces** [comment]
> there is no error message before you click on "Document", but the editor is just empty?

Yes, that´s correct.

> Does this still happen if you temporarily deactivate all other plugins?

Ok, I checked this and I found out that it is a plugin conflict with this Plugin:
https://codecanyon.net/item/affiliate-links-wordpress-plugin-for-link-shortening-and-masking/16917669

**Comment by swissspidy** [comment]
Ah, good to know!

Since it's a commercial plugin I can't take a look at its source code to find out what's going on.
Because of that I recommend reaching out to their support so they can fix any issues on their side.
