### ISSUE TITLE
Initial Help Companion State Open When Unread Tips Present

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#5971]
## Description 

After further discussion between @aaecheverria and @samitron7  - adding conditional open state as initial state of helper companion (the help center with quick tips in it) to be _open_ or _expanded_ when there are unread tips present. 

## Acceptance Criteria 
- If a user has unread tips in their helper companion the box should have the initial state be be expanded/open
![Screen Shot 2021-01-19 at 8 49 58 AM](https://user-images.githubusercontent.com/10720454/105058471-7a806980-5a33-11eb-9772-ebedbad067c8.png)

- If a user has read all tips in their helper companion the box should have the initial state be collapsed/closed  ![Screen Shot 2021-01-15 at 4 12 27 PM](https://user-images.githubusercontent.com/10720454/105057457-7bfd6200-5a32-11eb-9b16-a5ec6308c180.png)
- If a user has unread tips but has dismissed the helper companion, that toggle should be stored in local storage and respected on future visits to the editor (see thread for additional context) 
- Work should include updated unit tests

**Comment by aaecheverria** [comment]
Hi team, @BrittanyIRL @swissspidy,

Is it feasible/possible to add the following AC?
- If the user dismisses the helper companion (click on the X button), then the default state  for the next time they open the editor should be collapsed/closed.

**Comment by BrittanyIRL** [comment]
> Is it feasible/possible to add the following AC?
> 
> * If the user dismisses the helper companion (click on the X button), then the default state  for the next time they open the editor should be collapsed/closed.

We should figure out what qualifies as "the next time" - could this be something we use a cookie for so we don't store this as part of the user (seems like excessive info to track via API). 

@swissspidy is there an ideal way you'd like to store user info about FTUE like this?

**Comment by maxyinger** [comment]
> If the user dismisses the helper companion (click on the X button), then the default state for the next time they open the editor should be collapsed/closed.

This seems counter intuitive to reopening the menu on load if there are any new notifications. Maybe I'm missing some context.

> We should figure out what qualifies as "the next time"

Agreed. Maybe if we walk through some possible user flows it might clear up the requested UX:

**Scenario 1**
-> User opens editor for first time.
-> There's 5 unread quick tip notifications
-> User closes quick tips/help center
-> User exits editor
-> User comes back to editor
-> Theres still 5 unread quick tip notifications
-> is helper companion open or collapsed?

**Scenario 2**
-> User opens editor for first time.
-> There's 5 unread quick tip notifications
-> User closes quick tips/help center
-> User exits editor
-> User comes back to editor
-> There's a new quick tip notification
-> Theres now 6 unread quick tip notifications
-> is helper companion open or collapsed?

**Comment by swissspidy** [comment]
> is there an ideal way you'd like to store user info about FTUE like this?

Tracking open/collapsed seems more fitting for localStorage I think

**Comment by aaecheverria** [comment]
Hi @littlemilkstudio 

Thank you! Love the way you structured the flows, so these are our suggestions for each escenario:
For scenario 1, helper companion should be collapsed
For scenario 2, helper companion should be open

Please let me know if you need additional clarification.
