### ISSUE TITLE
Prepublish checklist tooltip on "publish" and "update" button disappeared

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#5972]
## Bug Description

This was fixed with #5532 in PR #5548 but it seems to have resurfaced. We need to bring back the tooltip as specified in the PR description, please reference that. 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA

**Comment by ivayloklissarov** [comment]
Working good, closing the ticket.
