### ISSUE TITLE
FTUE: Remove Feature Flag

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#5978]
## Feature Description

After feature has been through QA and UAT and stakeholders feel the feature is ready for users we need to remove the feature flag and the conditional code around it so that the flag is on by default. 

This should be done in 2 parts. 

1) PR that sets `default: true` on the existing feature flag. This is so that it can be easily reversed if something goes wrong. 
2) After release, removing the actual feature flag and the conditional code. 

## Additional Context

![image](https://user-images.githubusercontent.com/10720454/107857047-3a6d9600-6de9-11eb-963d-33aa35a8a25a.png)

Screencast: https://drive.google.com/file/d/1rAHJzuv9FNzTlVoVP5vHDoJm9zmQmkZv/view?usp=sharing

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

This ticket turns on the help center first time user experience that shows on the bottom left (ltr) or right (rtl) of the canvas section of the editor. All functionality from tickets included in MVP of epic should be testable by default at this point.

- There should be a button that says "help", clicking or hitting enter/space on this button should expand the help center.
- The help center should have 7 "tips" as a main menu
- You can click any tip from the main menu and cycle through the available content.
- Each tip should have an accompanying graphic
- As you view tips, the 'unread' count on the badge displayed on the 'help' button should decrease.
- When you have no more unread tips you should no longer see the badge icon but a chevron instead.
- When you go to the last tip you should see a done screen.
- You should only see the done screen after you have read all the tips no matter what order you began in.
- If you exit the help center and come back you should always begin on the main menu that has all 7 tips with arrows displayed.
- Your read count should be maintained on all sessions.

If you need to clear out your read tips type this and hit 'enter' in your console:
`await wp.apiFetch({ path: '/web-stories/v1/users/me', method: 'POST', data: { meta: { web_stories_onboarding: {} }}})`

**Comment by BrittanyIRL** [comment]
@csossi this is needed for the release that's scheduled for feb 16, if there's anyway you can prioritize it!

**Comment by csossi** [comment]
Verified in QA
