### ISSUE TITLE
Swap image | retain styles

### ISSUE THREAD

**Issue by samitron7** [GoogleForCreators/web-stories-wp#5980]
## Feature Description
Templates come with baked in styles and animations. Currently, if you replace an image/video from the template with one of you won (by dragging into the existing frame on the page), the styles and animations are removed. We need a better way to allow users to 
keep or remove a style for templates and all stories in general.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
