### ISSUE TITLE
Video Optimization: Show accurate progress bar

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5982]
## Feature Description

Show an accurate progress bar instead of the current loading indicator / spinner.

Gives the user a better sense of how long it actually takes.

Ideally this is done if/once we have an accurate progress bar for the upload itself

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
Is this just getting integrating the existing processing bar and a new processing queue as mentioned in the last meeting.

**Comment by spacedmonkey** [comment]
Related: https://github.com/google/web-stories-wp/issues/869 https://github.com/google/web-stories-wp/issues/969

**Comment by spacedmonkey** [comment]
The ffmpeg files has a [progress](https://github.com/ffmpegwasm/ffmpeg.wasm/blob/master/docs/api.md#ffmpegsetprogressprogress) callback.

We can also use the [progress tag](https://www.w3schools.com/TAgs/tag_progress.asp) built into the browser.
