### ISSUE TITLE
Video Optimization: Add media source

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5983]
## Feature Description

When we upload an optimized video, let's make sure we keep track of this so that we don't accidentally optimize it twice.

Could just be another term in the `web_story_media_source` taxonomy I suppose, calling it `video-optimization`.

Might need a database upgrade routine to add this new term.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
Just to confirm, would it have more than one term, so 'editor' and 'video-optimization' or just 'video-optimization'.  See
https://github.com/google/web-stories-wp/blob/80f570c600fde3f1df10aeaac62f4fd3fe022d9a/includes/Media.php#L339-L353

What about this example. Two users trigger the video optimization on two different user accounts on two different computers. Should we set some post meta, like processing, so it doesn't process twice and rewrite each other.

**Comment by swissspidy** [comment]
> Just to confirm, would it have more than one term, so 'editor' and 'video-optimization' or just 'video-optimization'.

Just one, 'video-optimization'

> What about this example. Two users trigger the video optimization on two different user accounts on two different computers. Should we set some post meta, like processing, so it doesn't process twice and rewrite each other.

I don't think so, since the process is happening client-side. The worst thing that could happen is that an already optimized video is overwritten by the same optimized video.

Plus, we're first focusing on newly uploaded videos, where this isn't relevant. Once we get to existing items we can revisit
