### ISSUE TITLE
Video Optimization: Cropping

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5985]
## Feature Description

We should be able to cut off-screen parts of videos upon request (cropping the visible parts of the image).

Example use cases:

* A video element is partially off canvas
* Video is scaled/zoomed in the editor

## Additional Context

https://ffmpeg.org/ffmpeg-filters.html#crop

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
Is this possible with ffmpeg.wasm? I can't see options in the docs for this. I may have missed it.

**Comment by swissspidy** [comment]
Yes, ffmpeg supports cropping: https://ffmpeg.org/ffmpeg-filters.html#crop

**Comment by spacedmonkey** [comment]
To confirm, we mean, cropping the image or cropping the video length? Or both?

**Comment by swissspidy** [comment]
Cropping the visible image.

Cropping the length (trimming) is something for waay in the future.
