### ISSUE TITLE
Video Optimization: Telemetry

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5990]
## Feature Description

We'd want to know how often videos get transcoded, and how long it takes.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

* [ ] Track media upload events themselves
* [ ] Track transcoding events themselves
* [x] Track errors
* [ ] Track timing

**Comment by spacedmonkey** [comment]
> Track media upload events themselves

- Is this all upload events or just for video files? 
- Does this include files uploaded via WP media picker?
- Does the event need context, like source of upload, like canvas, media library or WP media picker?

> Track transcoding events themselves

- By this do you mean when a when a transcode is started? 
- What context data do we need here? File name, mime type, file size etc? Is this useful information in this context?

> Track timing

Tracking timing of uploading or transcoding? Or both?

**Comment by spacedmonkey** [comment]
Related: https://github.com/google/web-stories-wp/issues/5785

**Comment by swissspidy** [comment]
> > Track media upload events themselves
> 
> * Is this all upload events or just for video files?

All uploads, not just videos

> * Does this include files uploaded via WP media picker?

Not for now

> * Does the event need context, like source of upload, like canvas, media library or WP media picker?

Not for now

I was thinking something simple like this:

```js
trackEvent('upload_media', 'editor', '', '', {
  type: mimeType,
});
```

> > Track transcoding events themselves
> 
> * By this do you mean when a when a transcode is started?

Yeah. Could be at the beginning of the `transcodeVideo()` function.

```js
trackEvent('video_transcoding', 'editor');
```

> * What context data do we need here? File name, mime type, file size etc? Is this useful information in this context?

> > Track timing
> 
> Tracking timing of uploading or transcoding? Or both?

Ah, yes, let's see if we can do both.

Once in `useTranscodeVideo.js`. Perhaps like this:

```js
const trackTiming = getTimeTracker('video transcoding', 'editor', 'Media');

const ffmpeg = createFFmpeg(...)

// ...

await ffmpeg.run(...)

trackTiming();
```

And then in `useUploadMedia` for the uploading part:

```js

setIsUploading(true);
const trackTiming = getTimeTracker('upload_media', 'editor', 'Media');

// ...

setIsUploading(false);
trackTiming();
```

----

Not sure how well this all works in analytics, I'll have to check that.
