### ISSUE TITLE
Ezoic integration results in validation error 

### ISSUE THREAD

**Issue by jamesozzie** [GoogleForCreators/web-stories-wp#5999]
Some users reported a _Tag 'amp-story-bookend', if present, must be the last child of tag 'amp-story_' validation error with Ezoic Analytics active on their sites. 

The issue occurs as the Ezoic Analytics snippet is placed between `<amp-story-bookend>` and `</amp-story>`, with the amp-story-bookend element required to be placed right before the closing amp-story element ([layout documentation](https://amp.dev/documentation/components/amp-story-bookend/)). 

[One user](https://wordpress.org/support/topic/amp-bookend-improper-placement/#post-13938109) contacted Ezoic, who are currently investigating, with a fix possibly incoming on their side. 

This only started occurring recently, with impacted users below:
- https://wordpress.org/support/topic/amp-bookend-improper-placement/#post-13938109
- https://wordpress.org/support/topic/amp-validation-fail-tag-amp-story-bookend-must-be-last-child-of/
- https://wordpress.org/support/topic/web-stories-no-longer-amp-validated/

## Additional Context
- Web Stories Plugin version: 1.3.0
- Ezoic Plugin Version: 1.3.13
- WordPress Version: 5.6.0
- Unable to reproduce on support side so far, using the Ezoic plugin or manually inserting the required Ezoic header code between <head> elements. 

Labelling as support at present, with ticket opened from support on Ezoic website. 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jamesozzie** [comment]
For those impacted Ezoic provided an update to the ticket raised:
`I actually just got another update from our engineers right after I sent you my last message. The issue should now be fixed on our end with the plugin. They fixed the code to move all instances of amp-analytics before bookend tag. 

`

**Comment by LuckynaSan** [comment]
Closing this as the issue was resolved.
