### ISSUE TITLE
SVG Upload: Conflict with Safe SVG

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6003]
## Bug Description

It was mentioned by rtCamp folks that there are issues when both our SVG experiment and the Safe SVG plugin are active.

Let's verify this and ensure that there are no conflicts.

## Additional Context

- Plugin Version: 1.3.0
- WordPress Version: 5.6
- Operating System: 
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
I did a quick of this by activating the svg safe plugin and svg feature flag. Seemed to work fine and uploaded an svg. Can you ask rtCamp to provide details to replicate the issue?

**Comment by swissspidy** [comment]
Here's a video: https://www.youtube.com/watch?v=ci4N6O4puXU

**Comment by swissspidy** [comment]
> The difference between Safe-SVG and Web Stories implementation of the SVG Sanitize package,
Safe SVG takes the input SVG, runs it through the sanitizer, modifies the code of SVG if its not sanitized and stores the output.
Web Stories, takes the input SVG, runs it through the sanitizer, if anything is found incorrect by sanitization function, it simply rejects the upload rather than storing the sanitized output.
Both of these are not compatible with each other, as I tested, when both are enabled, Web Stories stop taking SVG files, both of these might be overriding the same hook.

So to me this sounds as working as intended.

Because we are simply more strict than Safe SVG.

**Comment by swissspidy** [comment]
@spacedmonkey So the issue is this:

1. Activate Safe SVG plugin
2. Enable SVG experiment
3. Try uploading SVG to editor
4. Upload fails

**Comment by swissspidy** [comment]
Screenshot for the above error:

<img width="476" alt="Screenshot 2021-01-22 at 20 38 29" src="https://user-images.githubusercontent.com/841956/105537216-e2fc6e80-5cf1-11eb-85a8-83bd1e03259a.png">

See how SVG is not in the allowed list
