### ISSUE TITLE
Web Story Editor Enhancements

### ISSUE THREAD

**Issue by Vindulge** [GoogleForCreators/web-stories-wp#6004]
Since using the editor since early October 2020, we have some thoughts on potential enhancements to the editor. To be able to easily create a story in the editor will likely optimize the intent to index and pull meaningful information for a user versus using a third party option like Canva that is just a photo.

## Feature Description

Web Story Helpful Edits
•	Be able to load own fonts - For those of us with specific brand boards and font elements this is especially helpful (because we paid for them).
•	Be able to use [holding down alt key] like in adobe programs to copy something and to stay centered when growing in size
•	Be able to zoom in and out of design 
•	Have nudge (pressing an arrow key) be a smaller increment 

## Alternatives Considered

•	When you are adding/ choosing a font or color I would like to click the plus sign, then change the modifiers, then apply it to some text, rather than tweaking an element of my text and then clicking the + to save it (the current process is not intuitive).
•	When I scroll this large white space appears at the bottom of the screen which is weird and unnecessary
•	If there is a note in the checklist I would like to be able to click it and have it highlight what I need to edit. 

## Additional Context

- We're using WordPress, Genesis, Feast Theme
- Web Story Version 1.2.1 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Thanks so much for sharing this! I'll happily share this with the team, but here is some preliminary feedback:

> Be able to load own fonts - For those of us with specific brand boards and font elements this is especially helpful (because we paid for them).

It's not on the immediate roadmap, but there are plans for this: #4717 

> Be able to zoom in and out of design

We are actively working on this for our upcoming release! #4022 

You can check out the [roadmap](https://docs.google.com/spreadsheets/d/10DZZrWJdkjcJXD1vL0VG0PqRhsIqaHkacF_ujOdEwJc/edit#gid=0) for other things currently in the making

> Have nudge (pressing an arrow key) be a smaller increment

With <kbd><kbd>Shift</kbd>+<kbd>Arrow</kbd></kbd> you can move elements more precisely

> If there is a note in the checklist I would like to be able to click it and have it highlight what I need to edit.

We are actively working on this for our upcoming release! #5965

**Comment by samitron7** [comment]
> When you are adding/ choosing a font or color I would like to click the plus sign, then change the modifiers, then apply it to some text, rather than tweaking an element of my text and then clicking the + to save it (the current process is not intuitive).

@Vindulge Can you specify what you mean by 'change the modifiers'.

> When I scroll this large white space appears at the bottom of the screen which is weird and unnecessary

This is definitely a bug I thought we had fixed. @barklund Can you help look into this issue.

**Comment by barklund** [comment]
> > When I scroll this large white space appears at the bottom of the screen which is weird and unnecessary
> 
> This is definitely a bug I thought we had fixed. @barklund Can you help look into this issue.

We have issue #5458 dealing with this. Just prioritized it and looking for a way to reproduce it.
