### ISSUE TITLE
Bookend: Facebook Sharing requires App ID

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6008]
## Bug Description

I [just learned](https://amp.dev/documentation/examples/components/amp-social-share/#basic-usage) that using `amp-social-share` with `type="facebook"` requires to specify the facebook app id via `data-attribution`. Might have been a new requirement by Facebook.

Since this component is [used by the story bookend](https://amp.dev/documentation/components/amp-story-bookend/) under the hood, it means that sharing with Facebook is actually not possible at all without an app ID.

**Note**: The bookend is a new addition in 1.3.0

Possible options:

1. Remove Facebook share button
2. Give user option to add app ID  
  A bit unnecessary for something simple as a sharing button
3. Provide our own app ID  
  I doubt that we can create our own Facebook app and let everyone use it.

I think only (1) is feasible.

Also note that developers can hook into the bookend already, so if a user has a Facebook plugin installed, they could add the sharing button back.

## Expected Behaviour

No issue when sharing to Facebook, or no Facebook button being presented at all.

## Steps to Reproduce

1. View story on frontend
2. Click on share button
3. Click on Facebook icon

## Screenshots

<img width="1005" alt="Screenshot 2021-01-22 at 10 40 49" src="https://user-images.githubusercontent.com/841956/105474189-4ceb2880-5c9e-11eb-8d69-17f312aef9f4.png">

## Additional Context

- Plugin Version: 1.3.0
- WordPress Version: 5.6
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

* Remove Facebook sharing

**Comment by swissspidy** [comment]
@o-fernandez any thoughts on this one?

**Comment by o-fernandez** [comment]
Agree with removing and working on a better solution longer term if needed (based on user feedback and feasibility) @choumx FYI

**Comment by spacedmonkey** [comment]
Facebook option was removed in #6054. Should we create a follow up ticket for finding a solution for this @o-fernandez ?

**Comment by o-fernandez** [comment]
> Facebook option was removed in #6054. Should we create a follow up ticket for finding a solution for this @o-fernandez ?

That'd be great, not a critical issue, but something to track and prioritize.

**Comment by swissspidy** [comment]
Done: #6065
