### ISSUE TITLE
Improve Site Kit Analytics detection to check if its tracking snippet is inserted

### ISSUE THREAD

**Issue by ernee** [GoogleForCreators/web-stories-wp#6014]
## Feature Description

Since version 1.3.0, Web Stories automatically detects if the [Site Kit plugin](https://wordpress.org/plugins/google-site-kit/)'s Analytics module is enabled and disables the tracking ID field under _Editor Settings > Google Analytics_ (https://github.com/google/web-stories-wp/pull/3549).

However, in Site Kit's settings the user can toggle off or the plugin can automatically remove Site Kit's snippet under certain conditions (detection of an existing Analytics snippet inserted by another method or when Tag Manager's Analytics Tag is configured):
<img width="688" alt="Screen Shot 2020-10-06 at 9 14 29 AM" src="https://user-images.githubusercontent.com/8108643/105527563-b831fc00-5c98-11eb-8e06-bb3c3949ccee.png">

Detecting for this case and allowing the Web Stories' tracking ID field to be enabled would allow the ability for tracking to still be implemented on story URLs if the other methods do not support it. 

## Additional Context

Site Kit forum support topic: https://wordpress.org/support/topic/using-google-web-stories-and-site-kit-for-analytics-no-web-story-data-is-showin/

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

In `Site_Kit.php`, change `is_analytics_module_active ` method like so:

```php
/**
 * Determines whether the built-in Analytics module in Site Kit is active.
 *
 * Also checks whether the "Let Site Kit place code on your site" option
 * is actually checked in its settings.
 *
 * @since 1.2.0
 *
 * @return bool Whether Site Kit's analytics module is active.
 */
protected function is_analytics_module_active() {
	$analytics_module_active = in_array( 'analytics', $this->get_site_kit_active_modules_option(), true );
	$analytics_options       = get_option( 'googlesitekit_analytics_settings' );
	$analytics_use_snippet   = ! empty( $analytics_options['useSnippet'] );

	return $analytics_module_active && $analytics_use_snippet;
}
```

Update tests accordingly.

**Comment by swissspidy** [comment]
@felixarntz How can we detect whether the above option is toggled? e.g. using `get_option(..)`

**Comment by felixarntz** [comment]
@swissspidy It could be something like
```php
$analytics_options     = get_option( Google\Site_Kit\Modules\Analytics\Settings::OPTION );
$analytics_use_snippet = ! empty( $analytics_options['useSnippet'] );
