### ISSUE TITLE
Dragging from library doesn't respond instantly

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#6027]
## Bug Description
Originally reported by Paul:
"try dragging a picture, and release right away, then drag again...every second drag doesn't register."

## Expected Behaviour
When dragging from the library, the dragging should start immediately.

## Steps to Reproduce
1. Open Media tab in the library
2. Drag and release quickly multiple times in a row -- see the image not always being visually dragged.

## Screenshots
![dragging](https://user-images.githubusercontent.com/3294597/105675735-cf1b5d00-5ee9-11eb-9155-1a33e09ee01a.gif)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
A related bug to this is, that when hovering a large first image in media library (like below), the draggable clone image actually covers up some relevant functionality including the small three-dot image menu:

![Screen Shot 2021-04-02 at 15 03 58](https://user-images.githubusercontent.com/637548/113445955-c9983280-93c4-11eb-8a62-f4bda25bb764.png)

I think both might be fixed by adding `pointer-events: none` to the clone, but that might cause other problems in turn.

**Comment by miina** [comment]
Oh, good catch. That's quite problematic indeed. Will test your recommendation out, thanks!

**Comment by miina** [comment]
@barklund -- I added [a PR](https://github.com/google/web-stories-wp/pull/7028), doesn't help with the instant dragging issues unfortunately but should avoid other issues, thanks.

**Comment by barklund** [comment]
@miina, which part of this is not solved by your fix? I don't see the issue anymore. Can you confirm if it's still an issue for you?

**Comment by miina** [comment]
@barklund The dragging is not happening instantly -- it takes some time for the image to appear visibly, for example:
![dragging](https://user-images.githubusercontent.com/3294597/117107595-1e431a80-ad82-11eb-84a9-9dc05397fecf.gif)

Ideally, the image would always appear right away when starting dragging. There's a slight delay on the canvas, too, when dragging media a few times in a row, however, it's not that noticeable there, maybe because it's faster, or maybe because it's usually not dragged so quickly more than once in a row on the canvas. Thoughts?

**Comment by csossi** [comment]
Verified in QA
