### ISSUE TITLE
Update Moveable to latest 0.27 release

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6028]
## Feature Description

There have been a few new releases of `react-moveable`. As per #5952, it would be wise to address the failing tests the latest update causes, and otherwise adjust the code where needed.

> It looks like the update breaks the rotation indeed, will need some adjustments probably. On the changelog -- checking quickly it looks like there are some things that would clean up the code a little bit but nothing urgent. Perhaps we can create an enhancement issue for it. It might be better anyway to keep it up to date in case we encounter an update that we require in the future.

Seems like it might be the last release before a planned 1.0.0 version of Moveable.

Changelog: https://github.com/daybrush/moveable/blob/master/CHANGELOG.md?rgh-link-date=2021-01-25T09%3A18%3A25Z

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Ping @barklund FYI and for prioritizing.

**Comment by csossi** [comment]
Verified in QA
