### ISSUE TITLE
Vide Optimization: Confirm or switch CDN used  for ffmpeg

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6030]
## Feature Description

The ffmpeg core library and WASM needed for video processing is quite large and therefore cannot be bundled with the plugin.

By default, the ffmpeg package we use would load it from [unpkg.com](https://unpkg.com/).

In #5798 I implemented loading it from wp.stories.google so we have more control over it.

The question now is whether we should keep loading it from our CDN or if we should simply also use unpkg.com to keep maintenance simple.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
@choumx any thoughts on preferred storage method here?

**Comment by dreamofabear** [comment]
There are some small benefits to serving from the same CDN e.g. HTTP2 multiplexing and same uptime behavior.

**Comment by swissspidy** [comment]
Let's leave as-is then for now. We can always revisit, it's just 1 line of code to change.
