### ISSUE TITLE
Stickers: In Page Layouts, Don't set placeholder grid for stickers in templates

### ISSUE THREAD

**Issue by maxyinger** [GoogleForCreators/web-stories-wp#6032]
Stickers will look like an image, but should be the only images using .svg in templates. For page layouts, we'd want to retain the stickers and replace them with the placeholder image grid.

Completion of this task includes:
- images with svg source should be retained in page layouts

**Comment by maxyinger** [comment]
Zach, just assigned you to give an estimate for this real quick since you're the closest to page layouts

**Comment by maxyinger** [comment]
Eh it's still unclear to me if we're just using normal images with srcs to svgs held in our repo or if we want to do inline svgs. Maybe hold off on any estimates until we get a little clarity here

**Comment by zachhale** [comment]
I worry that just putting a SVG filter will produce unexpected side-effects as templates are developed. If we're gonna get into the situation of omitting some images, I am more inclined to suggest that we just add a `pageLayoutsOmit` attribute in the templates or something.

**Comment by dreamofabear** [comment]
> still unclear to me if we're just using normal images with srcs to svgs held in our repo or if we want to do inline svgs

Can we still use SVGs committed to the repo and treat them as images, but render them as inline SVG in the output?

**Comment by maxyinger** [comment]
Hmph. I think it would have to be one or the other. 

We could write alternative conditions if the media type is svg and derive a key off of the src to index a bunch of inline svgs:
```
const stickerKey = deriveKeyOffOfSrc(svgEl.src);
return (
  <STICKERS[stickerKey] />
)
```

But I worry that will add complexity and muddy the waters between user uploaded svgs and svgs used in templates that are supposed to be stickers.

If we want inline SVGs I think the cleanest approach would be creating a new sticker element type that just holds a key that maps to an svg component held in our repo. But this would be more engineering work than just having local images for stickers (at that point tho, there'd really be no reason to make stickers specifically svg)

Maybe I'm not seeing an easier approach tho. Anyone else thinking of anything that would mitigate all the problems highlighted above?

**Comment by swissspidy** [comment]
> Maybe I'm not seeing an easier approach tho. Anyone else thinking of anything that would mitigate all the problems highlighted above?

I think a new `sticker` element type could work well and give us all the flexibility we might need in the future. We could use it for both built-in stickers as well as user-uploaded SVGs (if we want to). The existing GIF element is some prior art for a recent addition of a new element type.

For built-in images, the element object could look like this:
```js
{
  ...
  type: 'sticker',
  resource: {
    src: '<svg ....',
    stickerName: 'internalAwesomeStickerName',
  }
}
```

Yes, `src` could be derived from `stickerName`, but it needs to be copied here in case the sticker is ever updated, so we could perform proper data migration.

For user-provided SVGs `stickerName` would be `null`.

This way internal and user-provided SVGs can be treated equally in the editor.

**Comment by csossi** [comment]
Verified in QA
