### ISSUE TITLE
Stickers: Design Stickers Library Panel for Editor

### ISSUE THREAD

**Issue by maxyinger** [GoogleForCreators/web-stories-wp#6033]
This ticket is to design the stickers panel for the editor. It will contain non-editable svgs used in templates.

Current spec being figured out here:
https://docs.google.com/document/d/1K3U79BxRU4v1xYMD1p3fg-jFS0iNhxERTHGe3SWfKbw/edit#heading=h.nyvd75mn73a5

Once technical implementation & design are figured out, we can create some more clearly defined tickets around this and more accurately point it.

**Comment by ivayloklissarov** [comment]
Concerning the identifiers of the stickers, so far we have established this as guidelines:

"name of template _ description of sticker" for instance, "entertainment_star" in Batch 01 Story 1. If certain elements are repeating but different, we are adding a numeration at the end.

**Comment by swissspidy** [comment]
Nitpick: isn't "entertainment" really the vertical name rather than the template name? ie there are multiple entertainment templates across all batches. So it's rather "name of vertical _ description"?

**Comment by ivayloklissarov** [comment]
Yes that's correct.
