### ISSUE TITLE
Packages: Move `page-layouts` to new structure

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6045]
## Feature Description

* [ ] Move `assets/src/edit-story/app/api/getAllPageLayouts.js` to `/packages/page-layouts/src/`
* [ ] Update imports where necessary.  
  Use `@web-stories-wp/...` imports for anything that is already a package, relative imports for everything else.
* [ ] Create `/packages/page-layouts/package.json` referencing its dependencies
* [ ] Create `/packages/page-layouts/README.md` with short documentation.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
Just looking at this ticket, I noticed in `getAllPageLayouts.js` there is a dependency on the edit-story codebase. 

```
/**
 * Internal dependencies
 */
import { PAGE_WIDTH } from '../../constants';
```

It is also worth noting that `PAGE_WIDTH` is a dependiency in  https://github.com/google/web-stories-wp/issues/6042

**Comment by spacedmonkey** [comment]
Also wonder if we should take the opportunity to lazy load the template package in. 

```
export default async function getAllPageLayouts({ cdnURL, assetsURL }) {
  const getAllTemplates = await import(
    /* webpackChunkName: "chunk-templates" */ '@web-stories-wp/templates'
  );
  const templates = await getAllTemplates({ cdnURL });
```

**Comment by swissspidy** [comment]
> Just looking at this ticket, I noticed in `getAllPageLayouts.js` there is a dependency on the edit-story codebase.
> 
> ```
> /**
>  * Internal dependencies
>  */
> import { PAGE_WIDTH } from '../../constants';
> ```
> 
> It is also worth noting that `PAGE_WIDTH` is a dependency in #6042

Ugh, missed that 🤦 

Marking as  blocked for now until we figure out how to best extract those consts.

> Also wonder if we should take the opportunity to lazy load the template package in.
> 
> ```
> export default async function getAllPageLayouts({ cdnURL, assetsURL }) {
>   const getAllTemplates = await import(
>     /* webpackChunkName: "chunk-templates" */ '@web-stories-wp/templates'
>   );
>   const templates = await getAllTemplates({ cdnURL });
> ```

If you look closely you'll see that this is already in place :-)

`getAllPageLayouts` calls `getAllTemplates` which in turn calls `getTemplates` / `loadTemplate` that dynamically imports all templates one by one.

**Comment by swissspidy** [comment]
Closing for now as it doesn't seem fitting anymore given the move of templates to an API and such. The page templates part is only a small abstraction on top of that.
