### ISSUE TITLE
Packages: Move `dashboard` to new structure

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6052]
## Feature Description

* [ ] Move code from `/assets/src/dashboard` to `/packages/dashboard/src/`
* [ ] Update imports where necessary.  
  Use `@web-stories-wp/...` imports for anything that is already a package, relative imports for everything else.
* [ ] Create `/packages/dashboard/package.json` referencing its dependencies
* [ ] Create `/packages/dashboard/README.md` with short documentation.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
Related: https://github.com/google/web-stories-wp/issues/8614
