### ISSUE TITLE
Video Optimization: UX for unsupported video types

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6053]
## Feature Description

When uploading a video to the editor, it will be immediately added to the canvas so the user can interact with it, preview it, etc.

With transcoding in the works, this means unsupported media types will be uploaded. These can't really previewed on the canvas before they're optimized.

We need to define what to do in this case.

Hide playback button? Don't add to canvas? Display some "preview unavailable" placeholder?

https://user-images.githubusercontent.com/841956/105774075-214d9400-5f65-11eb-8186-10ee8a324950.mov

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
Some video files have a poster image embed in them using [ID3](https://id3.org/) tagging system. It seems unlikely that a user generated video would have these images, but whatever tool used to generated the file, might have added it.

**Comment by samitron7** [comment]
@swissspidy Let me know if this [experience](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=4795%3A362145) looks good to you.

**Comment by spacedmonkey** [comment]
@samitron7 Little confused by the link you sent there. 

Just to be clear, there are three scenarios here. 

1. File format supported by browser, like mp4 or webm, video preview and poster generation ( current solution ). 
2. File format not support by browser by can be converted to support format ( webm / mp4 ). Video preview / poster generation are not possible, as broswer can play file until the file is transcoded ( converted ). Once trasncoded, file will act normally. 
3. File format not support by browser and transcoded. Needs to be rejected and error message shown to use. 


I think your UX covers 3, completely unsupported file types and not 2, files that can be converted in browser. Unless I am missing something.

**Comment by swissspidy** [comment]
@samitron7 I don't think it does. Will leave comments on Figma

**Comment by swissspidy** [comment]
Closing now that we got this [settled](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=5511%3A441672)!
