### ISSUE TITLE
Story Locking

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6055]
## Feature Description

The story editor does not support editing a story at the same time by multiple authors. In order to avoid collisions, only one author should be able to edit a story at a time.

WordPress has this useful feature called [Post Locking](https://codex.wordpress.org/Post_Locking) for that.

As soon as you start editing a post/story, it will be marked as "locked". Anyone else trying to edit the story after you will get a warning like this:

<img width="422" alt="68747470733a2f2f636c2e6c792f33473435326b3356327634322f496d61676525323532353230323031382d30382d31392532353235323061742532353235323031312e31382e353925323532353230504d2e706e67" src="https://user-images.githubusercontent.com/841956/87138287-7a422d00-c29e-11ea-983c-d4eb92673486.png">

**[[DRAFT] Product brief](https://docs.google.com/document/d/1GJZljicdXcP7oRdywsF3EGUaCVpCHsDrK2gUMubnrbk/edit?pli=1#heading=h.3azpde4bkxzj)**

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
When do we want to release this, @o-fernandez ? It feels done - just gave the ux in the dashboard some love for 1.10. We just need to flip the flag right? 

@spacedmonkey is there something else here that needs doing?

**Comment by swissspidy** [comment]
Final implementation is dependant on proper autosave handling.

If someone takes over editing from you, we must be able to autosave your changes.

That part is still missing.

Apart from that it's ready.

**Comment by BrittanyIRL** [comment]
ah, thank you! i was curious

**Comment by miina** [comment]
> Final implementation is dependant on proper autosave handling.

Looks like there's no issue for the missing autosaving part currently, should we create one to have it in the plan? Otherwise it doesn't have much visibility.
LMK if there is one already but I just couldn't find it.

(The feature was asked about, so bringing it up)

**Comment by swissspidy** [comment]
There is #1402 for that and I actually created an epic for everything around it the other day: #9859

I am planning on writing a summary on autosaves with some further information.

**Comment by miina** [comment]
> There is #1402 for that and I actually created an epic for everything around it the other day: #9859

Ah, alright, for some reason I thought it would be under this epic if it existed. But it's true that currently there is no autosaving for published stories at all. Thanks for the update!
