### ISSUE TITLE
E2E Tests: Fix flakey Publishing Flow test

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6062]
## Task Description

Example: https://github.com/google/web-stories-wp/runs/1768135044?check_suite_focus=true#step:13:18

**Comment by spacedmonkey** [comment]
The timeout here is very short at 500ms. Maybe just increasing the timeout here.

**Comment by spacedmonkey** [comment]
I also think we need to copy and paste the [following](https://github.com/WordPress/gutenberg/blob/c31555d4cec541db929ee5f63b900c6577513272/packages/e2e-test-utils/src/create-new-post.js#L37-L63) and replace [this](https://github.com/google/web-stories-wp/blob/712ab8554beec402e772b3522ffdd803134a2dbc/tests/e2e/specs/editor/publishingFlow.js#L72-L81).

**Comment by swissspidy** [comment]
> I also think we need to copy and paste the [following](https://github.com/WordPress/gutenberg/blob/c31555d4cec541db929ee5f63b900c6577513272/packages/e2e-test-utils/src/create-new-post.js#L37-L63) and replace [this](https://github.com/google/web-stories-wp/blob/712ab8554beec402e772b3522ffdd803134a2dbc/tests/e2e/specs/editor/publishingFlow.js#L72-L81).

I removed that on purpose because it doesn't work on 5.3 and was more flakey than our custom solution.

**Comment by swissspidy** [comment]
> The timeout here is very short at 500ms. Maybe just increasing the timeout here.

I'm always cautious e to just increase timeouts everywhere without knowing why. It's better to explicitly await something specific. Makes it easier to understand and more robust.

**Comment by spacedmonkey** [comment]
> I removed that on purpose because it doesn't work on 5.3 and was more flakey than our custom solution.

Can you provide more detail on why this didn't work in WP 5.3? Seems it like would...

**Comment by swissspidy** [comment]
Oh, sorry, I think I confused multiple things here. You're right, it should probably work. Feel free to  try.
