### ISSUE TITLE
Video Optimization: Display Snackbar Message

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6066]
## Feature Description

Display a snackbar notification during video transcoding, saying that the file is being optimized.

> Video optimization in progress.

<img width="612" alt="Screenshot 2021-02-15 at 18 02 08" src="https://user-images.githubusercontent.com/841956/107975135-ed8bea00-6fb7-11eb-8457-e4dc7de69ab2.png">

**[View on Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=5511%3A441091)**

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

* Telemetry: clicks on the snackbar CTA links are being tracked
* If optimization is skipped, just upload the originally provided file instead
* When cancelling, remove the video element from story / media library

## Implementation Brief

**`useTranscodeVideo.js`**

* Use `const [isProcessing, setIsProcessing] = useState(false);`
* Call `setIsProcessing()` appropriately in `transcodeVideo()`
* Return `isProcessing` from the hook

**`useUploadMedia.js`**

* Use `const { isProcessing } = useTranscodeVideo();`
* Use `useEffect` to call `showSnackbar()` if `isProcessing`

**Comment by spacedmonkey** [comment]
As noted in this [comment](https://github.com/google/web-stories-wp/issues/6053#issuecomment-772439323) there are 3 different types of 3 video. Supported, transcodable and  unsupported. 

@swissspidy Have you got an ideas of how to workout if a file is unsupported or transcodable? We already have supported [here](https://github.com/google/web-stories-wp/blob/3298bd4d0a44a7bc3ae98d897db65b90ad29bf00/includes/Traits/Types.php#L82-L85).

**Comment by swissspidy** [comment]
> As noted in this [comment](https://github.com/google/web-stories-wp/issues/6053#issuecomment-772439323) there are 3 different types of 3 video. Supported, transcodable and unsupported.
> 
> @swissspidy Have you got an ideas of how to workout if a file is unsupported or transcodable? We already have supported [here](https://github.com/google/web-stories-wp/blob/3298bd4d0a44a7bc3ae98d897db65b90ad29bf00/includes/Traits/Types.php#L82-L85).

I've looked into it before for in #6012 but deprioritized it. I'll look into it again.

In any case, the `unsupported` case can be neglected in this ticket for now.

Eror handling for `unsupported` can be handled in #6012 and #5991

**Comment by spacedmonkey** [comment]
So to confirm, the code might look a little like this. 

```
        ...
        const {
             allowedMimeTypes: {
              video: allowedVideoMimeTypes,
              },
          } = useConfig();
          ....
      if ( showSnackBar ) {
             let message = '';
             if( allowedVideoMimeTypes.includes( file.type ) ){
                   message = __('Video optimization in progress due to large video size.
If you skip this step, the original file will be uploaded.');
             } else {
                  message = __('Video optimization in progress due to unsupported file type.
If you cancel this step, the video will be removed.');
            }
      }

      // Transcoding is enabled, let's give it a try!
      try {
        // TODO: Only transcode & optimize video if needed (criteria TBD).
        const newFile = await transcodeVideo(file);
```

Transcoding a file is an async function. How would you trigger it to abort once it has started? 
We could do something odd with rejecting promise [here](https://github.com/google/web-stories-wp/blob/main/assets/src/edit-story/app/media/utils/useTranscodeVideo.js#L88). Maybe we could use a generator? Some advice here would be useful.

**Comment by swissspidy** [comment]
Implementation brief added to the issue description for review.

**Comment by spacedmonkey** [comment]
IB looks good to me 👍
