### ISSUE TITLE
Global story colors: Display a warning before deleting a color

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#6070]
## Feature Description
Per [Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=5%3A220534), when a global color is deleted, a modal should be displayed for confirming the action and letting the user know that this would delete the color for all users.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@barklund FYI for prioritizing

**Comment by csossi** [comment]
Verified in QA

Note: if user opts to no longer see warning for Saved Colours, the rule is applied to Saved Styles as well

**Comment by miina** [comment]
> Note: if user opts to no longer see warning for Saved Colours, the rule is applied to Saved Styles as well

Hm, I wonder if there should be 2 different trackers for that or it's ok to have just one. Thoughts, @swissspidy / @barklund?

**Comment by swissspidy** [comment]
A shared one seems unintuitive, especially since the two panels don't look the same. Once I dismissed the warning for Saved Colors, it would not be clear to me at all that Saved Styles are global too. So 👍 to 2 trackers.
