### ISSUE TITLE
Page and Saved Colors: only allow using/adding from Color Picker

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#6071]
## Feature Description
Per [Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=5%3A220520), Page should not have Saved Colors section in the design panel and should only allow adding and applying colors from the Color Picker.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@barklund FYI for prioritizing

**Comment by csossi** [comment]
Figma has "excerpt" instead of "story description" for Document panel:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/73f6952e-c20a-4228-81d4-72cd0daaee15)

**Comment by miina** [comment]
Figma is incorrect here, it should be "Story description", merging since this was the only found issue.
