### ISSUE TITLE
KSES not applied when editing stories via "All Stories" page

### ISSUE THREAD

**Issue by chelseycontier** [GoogleForCreators/web-stories-wp#6076]
## Bug Description

When a non-superadmin user causes a story to hit the WP save_post filter, the story HTML is aggressively sanitized, effectively deleting the story content.

## Expected Behaviour

Non-superadmin users should be able to make edits (such as changing the post status, applying categories, etc.) via the WP interface (i.e. 'quick edit', 'bulk edit' or 'bin' actions) in the 'All Stories' view of stories.

## Steps to Reproduce

1. When logged in as a non-superadmin user, make a change to a story via the 'All Stories' screen such as changing the post status, adding or changing a category, or moving a story to the bin (all actions that use the WP save_post filter).
2. The post's content is sanitised before it's inserted into the database, stripping the head off the content resulting in malformed HTML
3. The story displays no content either on the edit screen or on the preview/published URL

This problem does NOT occur when logged in as a superadmin.

A similar sanitization issue was noticed here: https://github.com/google/web-stories-wp/pull/5765

## Screenshots

https://d.pr/jVaqHq

## Additional Context

- We are on a multisite instance of WordPress
- Plugin Version: 1.3
- WordPress Version: 5.6

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Hey @chelseycontier

Thanks for your report.

Just to confirm, this happens only when editing stories via the 'All Stories' view, not when using the editor directly?

Aside: stories don't currently support tags and categories (yet!), did you manually add that taxonomy?

**Comment by chelseycontier** [comment]
That's right @swissspidy, this isn't a problem with the stories dashboard/editor. The problem is isolated to the 'All Stories' view. 

We did add the category taxonomy ourselves, but we understood that categories were already supported via All Stories based on your comment here: https://github.com/google/web-stories-wp/issues/489#issuecomment-630206988.

**Comment by chelseycontier** [comment]
Not sure if it was clear in the initial bug report, but moving a story to the bin from the 'All stories' screen also damages the HTML. To be clear, if a non-superadmin moves a story to the bin from the 'All stories' screen, they are not able to successfully restore the content from the bin.

**Comment by swissspidy** [comment]
@chelseycontier It wasn't, so thanks for the clarification! We'll take a look at this scenario too.

cc @spacedmonkey

**Comment by csossi** [comment]
Verified in QA
