### ISSUE TITLE
Blocks Project: Cleanup, Prepare, Merge new Code

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6078]
## Task Description

Tracking ticket for implementation of all the new functionaltiy.

**Comment by spacedmonkey** [comment]
<img width="273" alt="Screenshot 2021-03-01 at 14 29 17" src="https://user-images.githubusercontent.com/237508/109643509-39a86400-7b4c-11eb-9ef7-8a63fc919767.png">
Weird styling on view all stories. 

<img width="1884" alt="Screenshot 2021-03-01 at 12 51 40" src="https://user-images.githubusercontent.com/237508/109643574-517fe800-7b4c-11eb-9acb-12de243ffd41.png">
Error when no poster image is set.

**Comment by spacedmonkey** [comment]
<img width="555" alt="Screenshot 2021-03-02 at 17 03 35" src="https://user-images.githubusercontent.com/237508/109686118-e3eab080-7b79-11eb-879a-385d4bb74a2c.png">
<img width="702" alt="Screenshot 2021-03-02 at 17 03 30" src="https://user-images.githubusercontent.com/237508/109686126-e5b47400-7b79-11eb-857f-e412e15b3f00.png">e p
<img width="712" alt="Screenshot 2021-03-02 at 17 03 18" src="https://user-images.githubusercontent.com/237508/109686135-e6e5a100-7b79-11eb-9fd2-16f3fd7336da.png">

More places where no poster image not being present renders something odd looking.

**Comment by spacedmonkey** [comment]
The interdependencies between the web stories block and dashboard should be documented. 

I wonder what effect #6546 will have on the web stories block.

**Comment by spacedmonkey** [comment]
I asked some questions about namespaces here - 
https://github.com/google/web-stories-wp/pull/6543#issuecomment-787864999 https://github.com/google/web-stories-wp/pull/6543#discussion_r584628167

**Comment by spacedmonkey** [comment]
I wonder if we should create theme for web block.  See https://github.com/google/web-stories-wp/pull/6543#discussion_r584655541

**Comment by spacedmonkey** [comment]
<img width="163" alt="Screenshot 2021-03-03 at 10 52 33" src="https://user-images.githubusercontent.com/237508/109795303-ac7a1380-7c0e-11eb-9ea7-6a85578a0cb3.png">
Spacing and styling of this button in classic editor seems odd. Questsions. 

1. None of the other button have a title. Why does this one. 
2. The position of the button text seems odd. Need more space on the left hand side. 
3. The wording on the model is strange Okay. 
4. Slides broken in RTL. 

<img width="1904" alt="Screenshot 2021-03-03 at 10 56 28" src="https://user-images.githubusercontent.com/237508/109795785-4a6dde00-7c0f-11eb-9e42-0e2a994952e5.png">

**Comment by spacedmonkey** [comment]
<img width="324" alt="Screenshot 2021-03-03 at 11 31 46" src="https://user-images.githubusercontent.com/237508/109799898-78095600-7c14-11eb-9228-f72f0404d64b.png">
First option of custom dropdown is empty and doesn't do anything.

**Comment by csossi** [comment]
@swissspidy 

re: Tiny MCE
- Should the layout be limited to Circle Carousel here as well (like it is when using Custimizer)
- set the number of stories to 5 here:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/0833283d-c891-410c-9f3b-35205847e7b8)
but 10 appeared when previewing:
(PC/Chrome)

**Comment by swissspidy** [comment]
> Should the layout be limited to Circle Carousel here as well (like it is when using Custimizer)

No, all layout options should be visible there.

The customizer only shows the layout options supported by the theme, which is most likely only the circle carousel option (anything other than circles doesn't really look good in the header 🙂).

> set the number of stories to 5 here:
> but 10 appeared when previewing:

Good catch, fixed now!

**Comment by csossi** [comment]
Issues logged in Variances logged in #6543
