### ISSUE TITLE
Identify Outstanding Animation Updates 

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6079]
## Task Description

There's some known discrepancies surrounding animations used by templates vs what users have available when they animate their own elements. Ideally, there's no animations that the users cannot replicate which means some updates need to happen to the existing templates. There's some missing points about what all is needed to make this happen. This ticket is to identify the gaps so we can update the animations epic and have a concrete list of what all needs to happen and the desired effects. 

Per slack conversation Jan 28, 2021 and Omar's input: 

>  we should definitely do the audit that @littlemilkstudio  suggests around reviewing the existing template animations (plus any new ones introduced in the new set of templates)  and identify which of these we'd want to:
> - support in the editor for users to select and edit
> - simplify to make it just match one of the supported animations
> - eliminate altogether

Audit results should be attached to this ticket as a google doc and sent to review by Omar and Sam. When consensus is reached @BrittanyIRL  will add desired updates to animation epic and we can proceed from there! 

Slack thread for reference: https://xwp.slack.com/archives/C0144TS0EFJ/p1611617759002000

**Notes from meeting Feb 22, 2021**

- Given the nuances of identifying animations that are custom vs. available in the editor and having to decide whether to replace the animations or make due with what's available in the templates page by page, element by element we (Will, Omar, Sam, Max, Morten, Brittany) agreed that Omar and Sam would take this work on because it requires the least amount of back and forth.

**Comment by BrittanyIRL** [comment]
After getting @littlemilkstudio 's input, who is far more knowledgable about what is involved with this effort, I am repointing. 
This is significantly more of a time commitment - and essentially will involve going through all templates and pinpointing the discrepancies so that design can decide what they want to replace them with, if we should simplify existing animations on templates or create new effects based on what they do and make those accessible to users. 

It's a bit of a moving target really. I'm curious if these early 8 templates should just be replaced when the new batch of 50 templates is added so that this discrepancy is no longer an issue moving forward since it'll be a good bit of time (this ticket teeters on an 8) for eng to handle documenting all of these differences and the back and forth on design.

**Comment by maxyinger** [comment]
@BrittanyIRL I think from our meeting we concluded that this is more of a product task. Would you like me to mark it as done on our end? or use this ticket to track product's progress on it?

**Comment by BrittanyIRL** [comment]
@littlemilkstudio thanks for bringing this up! 

I'm gonna send it over to @o-fernandez and @samitron7
