### ISSUE TITLE
Pre-Publish Checklist: Display page number for "Link conflict with page attachment" error

### ISSUE THREAD

**Issue by jamesozzie** [GoogleForCreators/web-stories-wp#6081]
At present is a user places a link within the footer area on a page with an attachment they'll encounter the below in their 
Worth noting also that should this same conflict occurs a number of times the checklist item appears only once.  

```
Link conflict with page attachment
Links in the bottom of a page with a Page Attachment are disabled.
```
![image](https://user-images.githubusercontent.com/41326532/106179009-5ab71700-6192-11eb-8f48-9436a65cb951.png)

[Here you'll find a video](https://recordit.co/pKcfFUp7q7) displaying the issue 
- No link to the offending page
- No evident when there are multiple such conflicts 

## Steps to Reproduce

- Create a page and add an attachment
- Create a link element and place it within the attachment area
- Notice the error when visiting the checklist
- Repeat the same page and there are also no duplicate checklist items created 

## Additional Context

- Plugin Version: 1.3.0
- WordPress Version: 5.6
- Operating System: Windows 10
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
FYI @samitron7 @BrittanyIRL 

We should be able to highlight offending elements too.

**Comment by BrittanyIRL** [comment]
@embarks can you review the above and estimate this bug for the next sprint?

**Comment by embarks** [comment]
@BrittanyIRL I believe I resolved this for #5631, I'll pull it in

**Comment by swissspidy** [comment]
@csossi could you test #5965 again to see whether it properly addresses this issue as well?

If there is a link conflicting with a page attachments, the checklist should say the page number and allow you to click on the warning to select the offending element.

**Comment by csossi** [comment]
Verified in QA

Redirects to offending element on canvas (note tha panel remains on Checklist)
![image](https://user-images.githubusercontent.com/16945664/107403175-ca060280-6ad2-11eb-991b-934188ea78e5.png)
