### ISSUE TITLE
Video Optimization: User Setting in REST API

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6086]
## Feature Description

Video optimization can be disabled globally per-user on the settings page (#5981)

For this, we need a new user setting (a simple bool) that's exposed via the REST API, similarly to the telemetry opt-in.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

* Extend `User_Preferences` with new field for `web_stories_media_optimization` (keep it more generic)
* Add/Update tests accordingly
* Default value for this is **true**

**Comment by spacedmonkey** [comment]
Just confirm that reasoning behind, the user level optimization. Where is this documented?

**Comment by swissspidy** [comment]
This is a user-level setting rather than a site-level setting because users have various environments (i.e. one user has a super high-end computer, the other a smartphone)

Here are the current mocks on Figma: https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=4765%3A3 (still a bit WIP)

And I am currently working on updating the design doc for all of this as well
