### ISSUE TITLE
Video Optimization: First Time Usage Dialog

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6087]
## Feature Description

By default, video optimization is set to **opt in**. When the user encounters this feature for the first time, they will see a dialog with an explanation.

The dialog is displayed while optimization is already in prgoress, so it does not pause/stop the process or anything.

**Note:** "For the first time" means this is recorded in localStorage, not user meta.

Dialog text:

> Video optimization in progress
>
> Optimization is automatically enabled for all videos to ensure smooth playback. You can disable optimization any time in Settings. 
> We automatically optimize videos for smooth playback. To opt out, go to Settings.
>
> [Disable optimization] [Sounds good]

* [Disable optimization] - this will directly update the video optimization opt-in user meta value
* [Sounds good] - this will simply close the dialog

**Note:** exact wording TBD.

<img width="511" alt="Screenshot 2021-02-15 at 18 16 02" src="https://user-images.githubusercontent.com/841956/107976450-de0da080-6fb9-11eb-8e68-86dfebe0fb0e.png">

**[View on Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=5511%3A441091)**

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

* If the user is encountering video optimization for the first time, display snackbar with special wording
* Telemetry: click on settings page link is being tracked

## Implementation Brief

**`useTranscodeVideo.js`**

Export `isProcessing` state (see #6066)

**`useUploadMedia.js`**

Don't show snackbar message if it's the first time usage (see #6066)

**`mediaPane.js`**

This seems like a good fit to display a new `VideoOptimizationInfoDialog`.

* Consume `isProcessing` state from `useTranscodeVideo()`
* Check `localStore.getItemByKey()` to see if dialog was already shown
* If dialog was never shown, and `isProcessing` is true, display dialog

Something like this:

```js
<VideoOptimizationInfoDialog
  open={isProcessing & isFirstTimeUsage}
  onClose={updateLocalStore}
/>
```

**`VideoOptimizationInfoDialog`**

Could live as `videoOptimizationDialog.js` next to `mediaPane.js`.

Renders a dialog with two actions: one to acknowledge info and simply close dialog (`onClose`), the other one to opt out of video processing. For the  latter, use the `useCurrentUser` hook:

```js
const { updateCurrentUser } = useCurrentUser(
  ({ actions }) => ({
    updateCurrentUser: actions.updateCurrentUser,
  })
);

// ...

updateCurrentUser({
  meta: {
    web_stories_media_optimization: false,
  },
});
```

**Comment by spacedmonkey** [comment]
Is this part of FTSE?

**Comment by swissspidy** [comment]
> Is this part of FTSE?

This is not related to FTUE efforts around the help center

**Comment by spacedmonkey** [comment]
Can we reuse the `web_stories_onboarding` user meta to save that you seen the message the first time to not show it again?

**Comment by swissspidy** [comment]
> Can we reuse the `web_stories_onboarding` user meta to save that you seen the message the first time to not show it again?

That meta is particalurly used for the quick tips in the help center.

local storage suffices here. We already use it for similar one-time messages like the telemetry banner

**Comment by spacedmonkey** [comment]
> local storage suffices here.

So if I login to a different browser / clear my cache I see the message again? Why not save as as user meta, adding another key doesn't take long and the date is already preloaded on the page.

**Comment by swissspidy** [comment]
> > local storage suffices here.
> 
> So if I login to a different browser / clear my cache I see the message again? Why not save as as user meta, adding another key doesn't take long and the date is already preloaded on the page.

Yes, I think that would be acceptable. I know it doesn't take long but let's use localStorage for now while I get definitive confirmation.

**Comment by swissspidy** [comment]
Updated the ticket now based on recent UX updates.

It's gonna be a lot simpler. Also: confirmed to use localStorage.

**Comment by swissspidy** [comment]
Added partial implementation brief for review.
