### ISSUE TITLE
Video Optimization: Display tooltip for resource being transcoded

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6089]
## Feature Description

In addition to the snackbar message, there should be a tooltip when hovering over a local media item in  the library that is currently being uploaded/processed.

<img width="316" alt="Screenshot 2021-01-29 at 12 31 42" src="https://user-images.githubusercontent.com/841956/106270240-f2b60e80-622d-11eb-9baf-595994b1e0e1.png">

Same goes for the editor

**[Figma link](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=4846%3A254306)**

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
Isn't this ticket blocked by https://github.com/google/web-stories-wp/issues/5982 ?

**Comment by spacedmonkey** [comment]
@swissspidy I don't seem to have access to the figma link here. Any chance you can grant me access?

**Comment by swissspidy** [comment]
No, it's not blocked by #5982 — we don't need % progress, just need to know whether it's in progress or not. 

It is blocked by #6088 though (as stated) — and probably the adoption of the new design system as well.

**Comment by csossi** [comment]
Verified in QA
