### ISSUE TITLE
Video Optimization: Respect user setting

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6092]
## Feature Description

Since there's an opt-out on the dashboard settings screen for video optimization, we need to respect that setting when doing the transcoding in the editor.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

* [ ] Preload `users/me` REST API response in editor
* [ ] Add new `getCurrentUser` method to API provider to fetch current user
* [ ] In API provider, set `currentUser` as state (`const [currentUser, setCurrentUser] = useState({});)`
  (we don't want to call `getCurrentUser` every time we need the user info)
* [ ] In `useTranscodeVideo`, update `canTranscodeFile` to return `false` if user opted out.

**Comment by spacedmonkey** [comment]
I decided to see if there was an simpler way to add a check for video optimization. It felt like it would be simplier to map it a capability and pass it in with config. We don't need to get a api request here, even preloaded it adds some overhead we may not need.  Can you have a look at #6123 @swissspidy see what you think? Other explain the need for REST API request here?

**Comment by swissspidy** [comment]
@spacedmonkey The API request is needed because of #6087. The user can disable optimization via the REST API right from within the editor, which means that by simply passing it to the config it won't get the updated value after opt-out.

Screenshot:

<img width="525" alt="Screenshot 2021-01-29 at 11 02 46" src="https://user-images.githubusercontent.com/841956/106261147-86351280-6221-11eb-9325-f910204a610a.png">

**Comment by spacedmonkey** [comment]
> The API request is needed because of #6087. The user can disable optimization via the REST API right from within the editor, which means that by simply passing it to the config it won't get the updated value after opt-out.

This context is extremely useful before start writing, so thanks for sharing it. Okay, if this seeming that the state of this will change within the editor, so I think that it should live in it's own provider that wraps the editor, as other compontent depend on this state. Or should storing the state be handled by #6087

**Comment by swissspidy** [comment]
I think it could work just fine in the `APIProvider` like we already do in the dashboard. That's why I originally proposed it like that in the ticket description. But of course there can also be a simple `CurrentUserProvider`, with `APIProvider` just providing `getCurrentUser` & `updateCurrentUser` methods

**Comment by spacedmonkey** [comment]
> But of course there can also be a simple CurrentUserProvider, with APIProvider just providing getCurrentUser & updateCurrentUser methods

I think this makes more sense. The api provider doesn't manage any state at all at the moment and I think managing in it's own provider makes a lot of sense. Specially for FTE if we expand it.

**Comment by swissspidy** [comment]
Then let's do it that way.
