### ISSUE TITLE
Default font preset should not be defaulted with hilite bg styling

### ISSUE THREAD

**Issue by samitron7** [GoogleForCreators/web-stories-wp#6097]
## Bug Description

Default text presets are added to the page with bg hilite style. They should not contain any bg styles at all.

![Screen Shot 2021-01-29 at 10.13.20 AM.png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/8af6587b-4a1c-4796-b6e4-b4ed9611dd89)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
