### ISSUE TITLE
Min Width for Dashboard

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6098]
## Feature Description
Per discussion with Sam, we should implement a minimum width in the dashboard so that when viewports shrink to a certain size the contents will scroll horizontally.  Let's use a standard tablet size. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
Sets a minimum width for the dashboard to where everything in the viewport is still usable and readable.

**Comment by kkalarickal** [comment]
QA passed via #6166
