### ISSUE TITLE
Attach Target ID when Updating Property

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#610]
## Bug Description
From this [comment](https://github.com/google/web-stories-wp/pull/526#discussion_r390670881) in #526 

There's already a race condition happening when you update a property then select a different element (the property will be applied to the newly selected element instead of the target you intended to update). This will worsen it. 

## Expected Behaviour

Essentially when we issue a property update we need to ensure that its respective target ID is attached to it.

## Screenshots

![Kapture 2020-03-18 at 13 41 31](https://user-images.githubusercontent.com/1680157/76984950-47a2ac00-691e-11ea-8a54-d24944a78afb.gif)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Was this resolved with #621?

**Comment by dvoytenko** [comment]
Yes.
