### ISSUE TITLE
Early Dismiss Snackbar

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6103]
A new requirement for the updated snackbar is that they have the ability to early dismiss with an 'x' button. this should be an optional prop that if present will allow users the option to dismiss early. 
![Screen Shot 2021-01-29 at 3 19 41 PM](https://user-images.githubusercontent.com/10720454/106333227-6dd6ef00-6245-11eb-822c-4a5b990a04bc.png)

**Comment by samwhale** [comment]
This can be UAT'd on staging: https://google.github.io/web-stories-wp/storybook/?path=/story/designsystem-components-snackbar--default
