### ISSUE TITLE
Icon Library Updated

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6105]
The icons in figma have updated again! Let's audit what we have in the design system and make sure what's available is current to figma.

https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3441%3A80829

**Comment by webmasterbits** [comment]
There are icons available in the design system?
I've searched for "google icon fonts" and found one font but it was not available in the design system.

**Comment by swissspidy** [comment]
@webmasterbits I don't think this ticket here is what you are looking for... This is about the UI components and their icons as used in the Web Stories WordPress plugin, not about icon fonts for use by anyone in their projects or the plugin itself.

**Comment by BrittanyIRL** [comment]
@barklund already did this in #6311! Closing.
