### ISSUE TITLE
Add Pill to Storybook

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6106]
## Feature Description

Adds a light and dark variant of a pill to storybook that can be imported to editor and dashboard.

https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3447%3A64541

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

Light and Dark mode. 
Accessible. 
Complies to best practices for forms. 
Should include example in storybook.

**Comment by samwhale** [comment]
Pill is already in design system: https://google.github.io/web-stories-wp/storybook/?path=/story/designsystem-components-pill--default
