### ISSUE TITLE
Add Logos 

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6107]
## Feature Description

Add Logo section from figma design to design system for consistent use. 

https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=1906%3A0## Alternatives Considered

## Additional Context

if resources available, sub this new logo out in the dashboard while here!

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

- Adds logo and assets to design system

**Comment by BrittanyIRL** [comment]
@csossi this is a really easy one, just a regression test that the logo on the side nav of the dashboard is still rendering - updated the source.

**Comment by csossi** [comment]
Verified in QA
