### ISSUE TITLE
UseRovingKeyIndex RTL direction odd

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6108]
## Bug Description

This was noticed while implementing `useRovingKeyIndex` on page layouts:
In RTL the left and right arrow keys both go "right/down", and the up and down arrow keys both go "down". So it's like only having two arrow keys rather than four.

See #5989 for more details

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
