### ISSUE TITLE
Resizing the Layer Panel is not working

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#6122]
## Bug Description
Resizing the layer panel is not working, it seems to collapse the panel instead.

## Expected Behaviour
Resizing the layer panel should work

## Steps to Reproduce
1. Add some elements
2. Open the layer panel
3. Try to resize it
4. See the layer panel collapsing

## Screenshots
![Feb-01-2021 12-04-26](https://user-images.githubusercontent.com/3294597/106443915-63069f00-647d-11eb-9780-0ab7e254b104.gif)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
Moved to ready for sprint so someone takes a look soon.

**Comment by csossi** [comment]
Verified in QA
