### ISSUE TITLE
Monetization: AdSense Site Kit detection

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6124]
## Feature Description

Site Kit is working on direct support for AdSense monetization in Web Stories (https://github.com/google/site-kit-wp/issues/2602). Site owners can choose their Web Stories Ad Unit in Site Kit and Site Kit will automatically print the required ads configuration on the frontend.

Since there can only be 1 ad configuration on the frontend, it means we'll have to disable ours in favor of Site Kit.

I suppose that we want to have some sort of Site Kit detection similar to the one for analytics, where we disable the monetization section in the settings screen if Site Kit is already doing its thing.

Also, we could point the user to use Site Kit instead if they simply want AdSense.

## Additional Context

Analytics setting with Site Kit info:

<img width="983" alt="Screenshot 2021-02-01 at 14 29 32" src="https://user-images.githubusercontent.com/841956/106465226-f948be00-6499-11eb-8a97-359f72ba0f86.png">

Current monetization section:

<img width="996" alt="Screenshot 2021-02-01 at 14 29 28" src="https://user-images.githubusercontent.com/841956/106465241-fe0d7200-6499-11eb-91a0-d38639917c5c.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
> /cc @samitron7 @o-fernandez

Yeah, I'd love it if we do the same treatment for ads as we do for analytics.

**Comment by swissspidy** [comment]
This will be in the imminent Site Kit release (out in the next few days):

![image](https://user-images.githubusercontent.com/73545194/109011960-70b1ec00-76ec-11eb-8364-5eb030e6c4d3.png)

![image](https://user-images.githubusercontent.com/73545194/109012156-a6ef6b80-76ec-11eb-9e8b-c0c6b663a7cc.png)

It would be good to have detection for this in our plugin soon, otherwise users will be confused.

**Comment by swissspidy** [comment]
@samitron7 is this something we could pick up soon? Needs some wording similar to the Google Analytics Site Kit detection.

**Comment by o-fernandez** [comment]
@aaecheverria @tmagalhaes-huge wondering if the Huge team could TAL at this ticket - should be a quick one?

**Comment by tmagalhaes-huge** [comment]
@swissspidy Trying to ensure I understand this correctly: we need messaging that will clarify to the user that monetization is disabled if they activate Site Kit? If so, this would potentially appear in place of the monetization input fields? Apologies if I'm confusing things!

**Comment by swissspidy** [comment]
@tmagalhaes-huge Yeah, when a user has set up _AdSense for Web Stories_ in Site Kit, our own monetization configuration will be disabled (in other words, Site Kit takes precedence). We need to communicate that to the user somehow.

We have a similar situation for Analytics already: if you activate Analytics in Site Kit, we _disable_ our own Analytics input field (it's read-only). See screenshot below:

![Screenshot 2021-05-07 at 15 07 38](https://user-images.githubusercontent.com/841956/117454041-f997a000-af45-11eb-9621-b4eec94efda6.png)

(Site Kit info message on the left, disabled input field on the right)

Unfortunately this actually confuses users because they don't realize the field is read-only. So I like the idea of displaying a message _in place of the input fields_ instead of making them read-only.

**Comment by tmagalhaes-huge** [comment]
@swissspidy Got it. Let me talk to the team and Ivo so we can create a quick mockup of what that message should look like in place of the input field. In terms of copy, we lost our UXW resource for the remainder of this quarter. Sam mentioned you'd take a stab at it and we'll provide input? Let me know if this works for you. @aaecheverria FYI.

**Comment by swissspidy** [comment]
@tmagalhaes-huge Sounds good to me 👍

**Comment by ivayloklissarov** [comment]
@swissspidy We've adjusted Analytics and Monetization in order to get the idea of the pattern. Note that copy is FPO.

Figma link: [https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/?node-id=2%3A71517](url)

![Screen Shot 2021-05-11 at 2 02 33 PM](https://user-images.githubusercontent.com/77846281/117870584-e9433600-b261-11eb-9da5-b2df4ca0eaef.png)
![Screen Shot 2021-05-11 at 2 02 30 PM](https://user-images.githubusercontent.com/77846281/117870586-e9dbcc80-b261-11eb-964a-da6da34d28f4.png)

**Comment by swissspidy** [comment]
Thanks! The only concern I have is displaying those long paragraph in a disabled input field. I‘d just display them as paragraphs, so no border around the text and no save button. Thoughts?

**Comment by ivayloklissarov** [comment]
Good point @swissspidy let's get rid of it, to make things simplier. Thus, we have the input field only if the user decides to not install the Site Kit plugins.


![Screen Shot 2021-05-11 at 2 50 44 PM](https://user-images.githubusercontent.com/77846281/117875990-6f627b00-b268-11eb-9e91-8eaab29c1a1b.png)
![Screen Shot 2021-05-11 at 2 50 47 PM](https://user-images.githubusercontent.com/77846281/117875994-6ffb1180-b268-11eb-8d24-a61d025fb011.png)

**Comment by swissspidy** [comment]
Let's also remove that monetization dropdown so both sections would be displayed in the same way.

As long as Site Kit is active, the user cannot really change this dropdown — Site Kit would still take precedence. So it makes sense to remove that dropdown.

----

For the copy let's go with the following for now:

**Site Kit not installed**

Under "Monetization":

```
Monetize your content by showing ads in your Web Stories. <a>Learn more</a>.

Install <a>Site Kit by Google</a> to easily enable Google AdSense for Web Stories.
```

**Site Kit installed, but no AdSense configured**

Under "Monetization":

```
Monetize your content by showing ads in your Web Stories. <a>Learn more</a>.

Use Site Kit by Google to easily<a>activate Google AdSense</a> for Web Stories.
```

**Site Kit installed and AdSense configured**

Under "Monetization":

```
Monetize your content by showing ads in your Web Stories. <a>Learn more</a>.
```

On the right side:

```
<a>Site Kit by Google</a> has already enabled Google AdSense for your Web Stories, all changes to your ad configuration should occur there.
```

**Comment by ivayloklissarov** [comment]
Sounds good, I've updated the figma file with the 3 situations. 
https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/?node-id=2%3A71517

<img width="705" alt="Screen Shot 2021-05-18 at 9 00 16 AM" src="https://user-images.githubusercontent.com/77846281/118665114-a7614500-b7b7-11eb-951a-71005895b36a.png">
<img width="673" alt="Screen Shot 2021-05-18 at 9 00 22 AM" src="https://user-images.githubusercontent.com/77846281/118665119-a7f9db80-b7b7-11eb-9d7d-c1e527abc1ef.png">
<img width="690" alt="Screen Shot 2021-05-18 at 9 00 29 AM" src="https://user-images.githubusercontent.com/77846281/118665120-a8927200-b7b7-11eb-9f6f-8ed3e358cfd0.png">

**Comment by csossi** [comment]
Verified in QA
