### ISSUE TITLE
Low contrast between font and background color

### ISSUE THREAD

**Issue by webmasterbits** [GoogleForCreators/web-stories-wp#6125]
## Bug Description

In the Checklist -> Recommended, I get the this message for all slides that I have created: "Low contrast between font and background color".

Even though the background is #000 and the text is #FFF.

This is not a big deal for me but I don't know about the Google bot. If it thinks the same, my story might not get recommended.

## Steps to Reproduce
Here's the story: https://upcominglist.com/web-stories/upcoming-movies-on-dvd-in-february/

## Additional Context

- Plugin Version: 1.3.0
- WordPress Version: Latest

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Thanks for your report. We're already tracking this issue in #5905.
Feel free to ignore this message for now as it's clearly a false positive.
