### ISSUE TITLE
Shapes: Support uploading custom SVG icons

### ISSUE THREAD

**Issue by webmasterbits** [GoogleForCreators/web-stories-wp#6126]
## Feature Description
Would be nice to be able to add SVG icons.
Maybe there could be a place for them in the Shapes tab.

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
Thanks for the Feature Request! We have SVG support in the roadmap, but this ticket is a good use case for consideration. Will link up with the roadmap ticket.
