### ISSUE TITLE
Ability to toggle layout assets 

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6130]
## Description 
Currently on the page layouts tab the layouts, which are individual pages from templates, have their image assets getting replaced with a single grid asset. 
This ticket is to create a toggle button (pending new design system implemented in editor) to give users the ability to see the layouts either _with_ the given assets of a page as it would a template or with the placeholder grid in its stead. 

https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=5101%3A456645

## Acceptance Criteria 
- Whatever view the user has turned on, when the layout is selected the current page will be replaced with that layout with the proper assets for the view the user has toggled to. If a user has the placeholder grid visible in layouts the page will be rendered in the canvas with the placeholder grid. If a user has the traditional assets visible in the layouts the page will be rendered with those image assets. 
- All animations should be preserved the same as they currently are on page replacement 
- Panel should be keyboard navigable without focus trapping. 
- Toggle button should be accessible with proper labeling for screen readers. 
- Also adds a label to the panel section above the grid. 

![Screen Shot 2021-02-01 at 10 14 03 AM](https://user-images.githubusercontent.com/10720454/106493326-3b600880-6476-11eb-85ca-503d21fb15ed.png)

**Comment by BrittanyIRL** [comment]
This enhancement needs the new design system available in the editor before it can be exposed. 

We have 2 options here: 1) separate the logic and the UI so we could do the logic in the next release, hide it behind a flag, and replace the toggle button with the new designs after the designs are implemented and available. Or 2) Wait and do the whole thing after the editor gets the new theme and redesign. 

@o-fernandez @choumx Thoughts?

**Comment by swissspidy** [comment]
> This enhancement needs the new design system available in the editor before it can be exposed.

What exactly from the design system is required? The editor already has a [switch/toggle component](https://google.github.io/web-stories-wp/storybook/?path=/story/stories-editor-components-switch--default) that can be used here until design system is available.

**Comment by BrittanyIRL** [comment]
The huge team specified they want the new toggle. If they ok the present designs we can add it to the next sprint. 

@aaecheverria @samitron7 @o-fernandez  Thoughts?

**Comment by aaecheverria** [comment]
Hi @BrittanyIRL @swissspidy ,

After chatting with @tmagalhaes-huge we think the option that Pascal is proposing makes sense (use the current toggle component: switch/toggle component).

Once the new design system is available we would just update the toggle.

**Comment by BrittanyIRL** [comment]
Thanks for the reply, @aaecheverria - Asking Omar where this lands for prioritization!

**Comment by BrittanyIRL** [comment]
This might not get done in this sprint. Focus is on helping redesign. @o-fernandez @bmattb  - is this ok to push back 1 sprint in an effort to help redesign efforts?

**Comment by o-fernandez** [comment]
> This might not get done in this sprint. Focus is on helping redesign. @o-fernandez @bmattb - is this ok to push back 1 sprint in an effort to help redesign efforts?

yeah, i don't see this as a requirement for this sprint.

**Comment by BrittanyIRL** [comment]
This will be a fast follow from the work needed on sticker support. leaving in ready for sprint to pick up next release cycle as time permits.

**Comment by BrittanyIRL** [comment]
this is a nice follow up to #6032 if there's time in the sprint

**Comment by csossi** [comment]
Verified in QA
