### ISSUE TITLE
Foreground Media Menu

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6136]
## Description
Implement v1 foreground media element right click menu found in figma: https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=5034%3A442122

## Acceptance Criteria
All actions associated with menu options are functional
Proper snackbars show up when actions are taken
Unit tests added
Proper menu actions are disabled according to logic outlined in figma 

![Screen Shot 2021-02-01 at 10 37 42 AM](https://user-images.githubusercontent.com/10720454/106495949-89c2d680-6479-11eb-8472-1db8438df5b0.png)

**Comment by csossi** [comment]
Assuming this should be working for Tenor animated gifs as well, which doesn't show any back/forward options on right-click:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/19f36b5c-e834-4d87-b801-1247f4d9cf36)

**Comment by samwhale** [comment]
Oh great catch @csossi, I'll fix that right away.

**Comment by samwhale** [comment]
okay @csossi should be fixed now! Thank you 👍

**Comment by csossi** [comment]
Hi @samwhale - unable to move the slider here when I choose to "scale and crop image"
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/7bbf74ca-c680-4347-8657-cf4f5adc198c)

**Comment by samwhale** [comment]
@BrittanyIRL @csossi investigated the above issue - seems like for gifs the slider doesn't slide but _does change_ the value. This is present in staging right now, so it seems unrelated to this pr.

Here's a gif of scaling and cropping an image, a video, and a gif. It works for the image and video, but the gif slider doesn't move:
![scale-and-crop](https://user-images.githubusercontent.com/22185279/127380331-16d37619-341d-4b88-bf87-117db8f838f8.gif)

Added and issue for that here: #8504

**Comment by samwhale** [comment]
also, @csossi this is actually not visible to user's yet so we may just merge it and qa it more when the feature is finished. Your feedback has been super helpful so far, thank you so much!

**Comment by csossi** [comment]
Verified in QA

PR 8504 created re: slider for GIF
