### ISSUE TITLE
Context (Right Click) Menus 

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6139]
The Right-click Menu provides additional functionality to the user.  These options and actions displayed on this Menu will change depending on which type of Element the user has selected on the canvas: Page, text, Media, and Shapes. 
The Right-click Menu will contain four different categories of options/actions to help the user with:
- Main actions 
  - Here the user will find a set of actions that can apply across any element or media: Copy, Paste and Delete.
- Layer distribution options/actions 
  - These options will help the user move the selected element between the different layers (objects in the canvas): Send to Back, Send Backward, Bring Forward, Bring to Front.
- Element styling options/actions 
  - This set of options/actions will help the user manage the Element's style properties.
- Page action options
  -  These options/actions will help the user manage the different Pages in the story: Add a new page after, Add new page before, Duplicate page, and Delete page.

**[Figma designs](https://www.figma.com/file/1YM3jA9h4QGc4xLdyaXIJS/Stories-Sprint-1.7?node-id=7347%3A61451)**

**Comment by swissspidy** [comment]
There's some feedback on the Figma designs over at #97. Let's consolidate the two issues.

**Comment by BrittanyIRL** [comment]
Extra context is here: https://github.com/google/web-stories-wp/issues/97#issuecomment-774200592

**Comment by BrittanyIRL** [comment]
> There's some feedback on the Figma designs over at #97. Let's consolidate the two issues.

Sorry @swissspidy your comment got lost in the shuffle for me. I'm transferring necessary feedback this am to our epic and closing the old ticket.
