### ISSUE TITLE
Foreground Image Quick Menu

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6143]
## Description

Adds quick action menu to foreground image when selected element is foreground image. 
https://www.figma.com/file/1YM3jA9h4QGc4xLdyaXIJS/Stories-Sprint-1.7?node-id=7347%3A50908

Should have the following abilities: 
- Replace media 
- Add animation
- Add link to element
- Clear filters and animations

![Screen Shot 2021-02-01 at 10 52 36 AM](https://user-images.githubusercontent.com/10720454/106497714-a3651d80-647b-11eb-9442-a46a923e1d8c.png)
![Screen Shot 2021-02-01 at 10 52 42 AM](https://user-images.githubusercontent.com/10720454/106497716-a3fdb400-647b-11eb-8586-9d318f326255.png)

**Updated designs**
<img width="671" alt="Screen Shot 2021-05-18 at 11 08 58 AM" src="https://user-images.githubusercontent.com/10720454/118702180-738f1b00-b7c9-11eb-815a-156dd3046cdd.png">

## Acceptance Criteria 

- Clear element action should only appear if the element has styles applied. If the element doesn't have any styles applied the styles icon should be hidden. 
- Menu should have unit tests

**Comment by samwhale** [comment]
It looks like the designs show less actions: ![image.png](https://images.zenhubusercontent.com/5b1032a1348b7966b43421a4/c52f72aa-e0fc-403a-ba47-91c54042412b)

**Comment by BrittanyIRL** [comment]
You're right! looks like it was updated since february when i was walked through the designs. I'll update screenshots but just follow what's in the 1.7+ figma file and it's all good.
