### ISSUE TITLE
Quick Action Menus

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6147]
The Quick action menu should always be present at the  the top-right, outside of canvas of the current working page.
The actions inside the quick action menu change  depending on which element is selected.

**Comment by swissspidy** [comment]
@BrittanyIRL Is there also a ticket for adding Karma tests? We shouldn't wait until _after_ release to add those :-)

**Comment by BrittanyIRL** [comment]
> @BrittanyIRL Is there also a ticket for adding Karma tests? We shouldn't wait until _after_ release to add those :-)

We're adding them as we go, they're baked into the acceptance criteria.
