### ISSUE TITLE
Quick Action Menu Feature Flag Removed 

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6149]
After development is over and feature is QA'd and we are ready for the menus to be included by default, remove feature flag and logic surrounding it.

**Comment by BrittanyIRL** [comment]
@csossi reference the PR description in #7795 for details on this feature!

**Comment by csossi** [comment]
Nothing Selected
- Insert Media - the tooltip sez "Insert Background Media", but this just insert media on canvas (not on background)

Background Image Selected
- 7795 indicates:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/7e70f9e4-c001-4ef6-8f1e-f84117870313)
but options on canvas are uctually Change Background Colour, Insert Background Media, and Insert Text
- note also that Insert Background Media just inserts media (foreground)

Foreground Image
- Selecting Replace Media isn't replacing the selected media. it's just adding additional media
- Reset element  clears the animation - question: should it clear any link entered as well?

Video
- Selecting Replace Media isn't replacing the selected media. it's just adding additional media

**Comment by BrittanyIRL** [comment]
> Nothing Selected
> 
> * Insert Media - the tooltip sez "Insert Background Media", but this just insert media on canvas (not on background)

This is intentional,  the design directions are to take the user to the media panel so that they can select what media they want, they still have to drag and drop as usual. 


> 
> Background Image Selected
> 
> * 7795 indicates:
>   ![image.png](https://camo.githubusercontent.com/f7d4c363301835236cb7bba2f2f9513a367d968435ba05bcad4c8d709555e2cf/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3565613038356534373034653732633061393963363939372f37653730663965342d633030312d346566362d386631652d663834313137383730333133)
>   but options on canvas are uctually Change Background Colour, Insert Background Media, and Insert Text
> * note also that Insert Background Media just inserts media (foreground)

It sounds like you didn't actually have the background media layer selected? 

> Foreground Image
> 
> * Selecting Replace Media isn't replacing the selected media. it's just adding additional media
> * Reset element  clears the animation - question: should it clear any link entered as well?

Same here for the "replace media" -  it just takes you to the media panel that existing media is from (if you have a 3p media image in use it will take you to that tab, whereas if you have a local media item it'll take you to that tab). 

For reset, good clarification. For now it will not clear the link. It will clear the following: animation, overlay, border radius, border, and opacity 

> Video
> 
> * Selecting Replace Media isn't replacing the selected media. it's just adding additional media

Same thing here for the media replacement. 


sounds like maybe the copy is misleading. We'll see what happens for that in bugbash.

**Comment by csossi** [comment]
Verified in QA
