### ISSUE TITLE
Dashboard: Snackbar message updates 

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6157]
## Feature Description

The new snackbar designs don't have a title area. The Dashboard's messages that show up in snackbars have previously relied on the title area to give context to the messages. We should update accordingly. 

These are the messages that rely on titles for context. We're using the actual API error text for the body of the message unless a 'default message' is provided. 

https://docs.google.com/spreadsheets/d/1eG77iwDbKSdOIQCOl2ROSMvSegMq4qm1gophOubcu5w/edit?usp=sharing

We could always string together titles and the error text received from API on error. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
@o-fernandez @samitron7 I want to flag this as needing copy. I can take a first swing at it if that's helpful but I'd rather get your input right off the bat.

**Comment by BrittanyIRL** [comment]
This should be QA'd here: https://github.com/google/web-stories-wp/issues/4967 per my last comment there. Let me know if anything's confusing.

**Comment by csossi** [comment]
Trying to rename story displays "Unable to update story" instead of "Unable to rename story" (All good otherwise)

**Comment by BrittanyIRL** [comment]
Thanks for the thorough testing! 
So the updated text doc is actually attached to the[ PR that has the testing directions](https://github.com/google/web-stories-wp/pull/6312), since this ticket is _so old_ i'm really sorry for the confusion. 

renaming a story should display 'unable to update story' so that's all good. 

![Screen Shot 2021-02-12 at 9 27 27 AM](https://user-images.githubusercontent.com/10720454/107794429-ae8a3a00-6d14-11eb-84f8-c6e1d1d40640.png)
https://docs.google.com/spreadsheets/d/1PjaRp4bueQ3Cv14A7I696m0vjGCIX_kN9tIGh-V-Bkc/edit#gid=412530555

**Comment by csossi** [comment]
Verified in QA

**Comment by tmagalhaes-huge** [comment]
@BrittanyIRL What's the best way to trigger some of these to show you on the editor so we can validate?

**Comment by BrittanyIRL** [comment]
@tmagalhaes-huge - try copying a story from a menu: 

![Screen Shot 2021-03-09 at 8 46 06 AM](https://user-images.githubusercontent.com/10720454/110497673-ea19e900-80b3-11eb-8179-d5b80522b066.png)

Otherwise they are all error based and require some request blocking to simulate.
