### ISSUE TITLE
Unable to enter Media edit mode

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#6163]
## Bug Description
Entering media edit mode via double click is not working.

## Expected Behaviour
Double-click on media element should enter edit mode.

## Steps to Reproduce
1. Add media
2. Double-click on it
3. See nothing happening

## Screenshots
![edit](https://user-images.githubusercontent.com/3294597/106622202-a5aaa300-6573-11eb-809b-3d07d22586ae.gif)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@bmattb FYI Pulling this into the sprint.

**Comment by bmattb** [comment]
I approve of your selection here. 😃

**Comment by swissspidy** [comment]
@miina does this explain #6162? 😅

**Comment by miina** [comment]
> @miina does this explain #6162? 😅

 It better! 😄  How did it get through though 🤔  I guess it needs some test adjustments, too!

**Comment by csossi** [comment]
Verified in QA
