### ISSUE TITLE
Page Layouts: key prop warnings

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6164]
## Bug Description

Getting the following warnings when running tests:

```
Warning: Encountered two children with the same key, `65359a38-f1fa-4048-9b99-9415147b74d3`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version

in div (created by pageLayouts__PageLayoutsRow)
in pageLayouts__PageLayoutsRow (at pageLayouts.js:108)
in div (created by pageLayouts__PageLayoutsContainer)
in pageLayouts__PageLayoutsContainer (at pageLayouts.js:103)
```

Looks like it's this code:

https://github.com/google/web-stories-wp/blob/57f102fbf9e2a1de465f606aa1ae987b938032d4/assets/src/edit-story/components/library/panes/pageLayouts/pageLayouts.js#L108-L112

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
<img width="1302" alt="Screenshot 2021-02-03 at 17 52 02" src="https://user-images.githubusercontent.com/841956/106780715-8fbae200-6648-11eb-9531-e4698edb5dd3.png">

Not quite the right key I'd say :-)

**Comment by BrittanyIRL** [comment]
Pretty sure this got resolved with the updates I did that got merged today in #6549. Sending to QA.

**Comment by csossi** [comment]
Testing was already done for #6549 successfully, so not quite sure what I should be looking at here. Is this for a developer to look at, or can it be moved to QA Passed as is, @BrittanyIRL  ?

**Comment by swissspidy** [comment]
Yeah this kind of stuff is better for a dev to verify, more like technical QA.

Closing as I can no longer reproduce.
