### ISSUE TITLE
Investigate discrepancy in letter spacing 

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6174]
There seems to be a new discrepancy within the letter-spacing of some text in figma's design system vs what we have currently. This ticket is to get to the root of what the letter-spacing defaults are and adjust the theme and existing components to use a consistent letter-spacing since it appears to have been updated.

**Comment by BrittanyIRL** [comment]
Per note from Pascal - google sans doesn't have a 300 weight, so we should make sure that's not given in the presets.

**Comment by BrittanyIRL** [comment]
@csossi there's specific things to test in the PR description under "user facing changes" - if you have questions let me know!

**Comment by csossi** [comment]
Verified in QA
