### ISSUE TITLE
Pre-Publish Checklist: TypeError: `backgroundColor` is not iterable

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#6176]
## Bug Description

Recurring "Uncaught (in promise) TypeError: backgroundColor is not iterable" browser console error appears when using a template.

The error happens in this part of the pre-publish checklist:

https://github.com/google/web-stories-wp/blob/017fe34cff32c7805b1943d8c044bc2a9314abda/assets/src/edit-story/app/prepublish/warning/accessibility.js#L237

## Expected Behaviour

No console errors should appear.

## Steps to Reproduce

1. Open any of the following templates: Fashion, Fitness, Cooking.
2. Notice browser errors.

## Screenshots
![image](https://user-images.githubusercontent.com/66372350/106792217-dba76000-6623-11eb-871d-e2216499dedd.png)
![image](https://user-images.githubusercontent.com/66372350/106793408-6dfc3380-6625-11eb-9e64-8bd6abece0cc.png)
![image](https://user-images.githubusercontent.com/66372350/106793478-83715d80-6625-11eb-9df5-4119863ac290.png)

## Additional context

User was getting the same error message in this related topic: https://wordpress.org/support/topic/failed-to-save-the-story-error-2/. However, the issue with the story failing to save was not reproducible.

- Plugin Version: 1.3.0
- WordPress Version: 5.6
- Operating System: macOS
- Browser: Chrome, Safari

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
This also happens when visiting `wp-admin/post-new.php?post_type=web-story&web-stories-demo=1`

**Comment by csossi** [comment]
Verified in QA
