### ISSUE TITLE
Move FTUE video resources to CDN

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6177]
Videos in use from this PR: https://github.com/google/web-stories-wp/pull/6167  (located at assets/images/editor/helpCenter) need to be moved to the CDN and source replaced in src/edit-story/components/helpCenter/constants.  

If the infra pod can ready the CDN and then pass the rest of it to Peapod?

**Comment by swissspidy** [comment]
@BrittanyIRL FWIW, adding assets to the CDN is super simple and documented in `docs/cdn.md`. I'll do it now, but there's no reason for this to be blocked by this pod in the future

**Comment by BrittanyIRL** [comment]
I had no idea that was documented, apologies!
