### ISSUE TITLE
Pinch to zoom

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6179]
## Feature Description

Add pinch-to-zoom functionality as per [Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=2241%3A2).

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

* Change the possible zoom settings to just `FIT`, `FILL`, and `FIXED` (bonus points for alliteration, right?)
* Add a new zoom level property, which will contain the actual zoom in a ratio (so 1 for 100%, 2 for 200%, etc)
* Add a new function to set a fixed zoom percentage, which will convert the setting to fixed
* Update the options for setting the fixed zooms in the dropdown to use this
* Update the (collapsed) dropdown to be able to show any fixed zoom percentage
* Calculate and set the zoom level property also when `FIT` and `FILL` are the settings, but still display labels _"Fit"_ and _"FILL"_ respectively in the (collapsed) dropdown.
* Listen for [pinch events](https://medium.com/@auchenberg/detecting-multi-touch-trackpad-gestures-in-javascript-a2505babb10e) (`evt.deltaY` on scroll events with `evt.ctrlKey` set)
  * For extra points, listen to "true" pinch events as well for users on a touch device either [manually](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events/Pinch_zoom_gestures) or [using a library](https://manuelstofer.github.io/pinchzoom/).
* Decrement or increment current zoom level using the new set fixed zoom level function on pinch

**Comment by csossi** [comment]
Verified in QA
