### ISSUE TITLE
Viewport inconsistent when switching zoom level

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6181]
## Bug Description

In the current zoom implementation, the viewport jumps inconsistently when switching zoom level.

## Expected Behaviour

One of these three things could happen, which would make it consistent and logical. Each has its drawbacks though.

1. Always reset the viewport to a certain fixed position when changing the zoom level. This could be the top left corner or the page center.
2. Keep the same center as the old viewport - so when switching from FIT to any other zoom, the scroll will always be at the center. When switching from 200% to 300%, the current center will also be the center in the new zoom.
3. Keep the currently selected element(s) in the center of the viewport as well as possible. This would mean that being on FIT, selecting an element in the bottom right corner, and switching zoom to 300% would update the viewport to be in the bottom right corner.

## Steps to Reproduce

1. Zoom to 300%
1. Scroll somewhere to the middle
1. Change zoom to 200%
1. Observe that the resulting viewport is somewhere in the bottom of the page, not anywhere near where it was before.

## Screenshots
![zoom-viewport-bug](https://user-images.githubusercontent.com/637548/106843793-de7e7100-6674-11eb-9ede-e317555f8722.gif)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
My vote would be for keeping the same center as you switch zoom levels. But @samitron7 to chime in.

**Comment by csossi** [comment]
Verified in QA
