### ISSUE TITLE
New elements can appear out of view when zoomed 

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6182]
## Bug Description

Adding a new element by clicking on the element in the libraries will add it in a fixed position according to the general rules. When zoomed, this same thing still happens, regardless of whether this fixed position is in view.

Furthermore, the added element will always appear at default size, regardless of current zoom. This deviates from the behavior of dragging an element on to the canvas, where the resulting size will vary with the canvas.

## Expected Behavior

~The expected behavior is unknown. Maybe the current behavior is expected even?~

Edit: When the user starts dragging an element from the library or adds a new element, the Zoom is reset to Fit right away first.

## Steps to Reproduce
1. Change zoom to 200%
2. Scroll to the bottom of the page
3. Drag in an image to the canvas
4. Click the same image and observe the difference

## Screenshots
See the page preview in the bottom carousel to better understand what's happening here when the second image is added.
![zoom-add-element-bug](https://user-images.githubusercontent.com/637548/106844566-dd4e4380-6676-11eb-8155-efa3376e2635.gif)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
That's a good callout. I'd want @samitron7 to chime in, but my guess would be that the rules on when things are added when clicked should be updated to focus on adding it to the visible canvas area. But, we should look at effort required to do that.

**Comment by samitron7** [comment]
The rules need to be updated so the image is added to the visible area using an appropriate size. Basically we apply the old rules on the new zoomed in viewport (ie don't scale or position using the old canvas).

**Comment by miina** [comment]
From discussion with @samitron7 :
- When the user is zoomed in and clicks on an element in the library, the new element is added in the original size.
- When the user is dragging an element from the media library, it will be added to the page in its original size.
- When the user has zoomed in and click on an element in the library, the new element is added to the centre of the user's current view (but in original size) (the centre of the element matches the centre of the visible area.
- When dragging, the element will be added to where it's being dragged but added to the page in its original size.

**Comment by miina** [comment]
Moving this back to the backlog since this still needs [confirming the specs ](https://xwp.slack.com/archives/C01ESBB8ZN1/p1617302443049800)

**Comment by miina** [comment]
Update on specs: 
When starting dragging a new element from the library, or when adding an element, the zoom is reset to Fit right away first.

**Comment by csossi** [comment]
Verified in QA
