### ISSUE TITLE
Packages: Make `i18n` wrapper for `@wordpress/i18n`

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6183]
## Feature Description

Right now, the editor and dashboard packages use `@wordpress/i18n` directly.

To reduce this direct dependency on a CMS-provided package across tons of files, we could move that usage to our custom `i18n` package which simply re-exports `@wordpress/i18n`.

So in dashboard and editor we'd do this everywhere:

```js
import { __, TranslateWithMarkup, sprintf } from '@web-stories/i18n';
```

And in the `i18n` package (`packages/i18n/src/index.js`:

```js
export { __, _x, _n, _nx, sprintf } from '@wordpress/i18n';
```

This makes it easier to eventually swap out `@wordpress/i18n` for something else.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

* No direct dependencies on `@wordpress/i18n` in dashboard and editor packages

## Implementation Brief

* Replace `@wordpress/i18n` imports in `editor` and `dashboard` packages with `@web-stories/i18n` imports
* Fix any duplicate imports
* Remove any stray `WordPress dependencies` doc blocks to fix lint errors.

**Comment by spacedmonkey** [comment]
Should I do this as part of https://github.com/google/web-stories-wp/issues/6049 ?

**Comment by swissspidy** [comment]
@spacedmonkey Sure, but I'd prefer two separate PRs. This one might cause some more merge conflicts.
