### ISSUE TITLE
Pre-Publish Checklist: Integrate AMP Validation

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6184]
## Feature Description

It would be very interesting to explore a direct integration of the AMP validator with the pre-publish checklist. For this, I've experimented with using `https://cdn.ampproject.org/v0/validator.js` directly in the browser.

<img width="553" alt="Screenshot 2021-01-28 at 21 37 03" src="https://user-images.githubusercontent.com/841956/106888977-a106fb80-66e7-11eb-9154-bdc1d7a2e9be.png">

### Considerations

* Don't want to show validation errors for things that are already covered by other checklist items (e.g. missing poster image)
* Don't want to run validation all the time (resource intensive), perhaps only before publishing
* Needs some actionable steps for the user (e.g. visit https://search.google.com/test/amp, disable plugins, open support request, etc.)

## Alternatives Considered

Instead of https://cdn.ampproject.org/v0/validator.js we could try doing the validation in PHP, like the AMP plugin does.

Advantage: we could try to find the source of the invalidation (i.e. the offending plugin)
Disadvantage: lots of overhead and complexity, would need to be done in an async way, user might not know what to do with the additional information

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

- Implement new check in checklist for amp validation following Pascal's prototype for reference of what we are checking and the rules around it. 
- Only published stories should get this check 
- We should make sure that other checks covering amp issues are prioritized so that they are rendered over showing the generic amp issue (see prototype for checks) 
- Include tests

**Comment by swissspidy** [comment]
@o-fernandez pinging you for consideration

**Comment by dreamofabear** [comment]
Related: the STAMP preview tool uses the JS validator to surface AMP validation errors. 

For example: https://www.usatoday.com/amp-stories/hawaii-volcano-big-island-update-one-year-later/#development=1&tab=logs

**Comment by swissspidy** [comment]
> For example: [usatoday.com/amp-stories/hawaii-volcano-big-island-update-one-year-later/#development=1&tab=logs](https://www.usatoday.com/amp-stories/hawaii-volcano-big-island-update-one-year-later/#development=1&tab=logs)

That link 404s for me, but this one works: https://wp.stories.google/stories/intro-to-web-stories-storytime/#development=1

**Comment by dreamofabear** [comment]
Haha wow, I guess country content restrictions are not just for Netflix.

**Comment by westonruter** [comment]
For the AMP plugin, we're also going to be incorporating AMP validation status in the pre-publish panel in the block editor: https://github.com/ampproject/amp-wp/issues/5304#issuecomment-769358550 cc @jwold

**Comment by dreamofabear** [comment]
This came up again recently in the creator program. I think what Pascal proposed is a good start.

> Don't want to show validation errors for things that are already covered by other checklist items (e.g. missing poster image)
> Don't want to run validation all the time (resource intensive), perhaps only before publishing

Let's consider a fallback check that displays when (a) there are AMP validation errors AND (b) there are zero "high priority" PPC items. It can be triggered on preview/publish when there are no "high priority" items.

> Needs some actionable steps for the user

We can link to a help article that explains how to debug validation errors. E.g. start by triangulating an offending WP plugin (with messaging our support team already uses), and create a support forum post if that fails.

/cc @o-fernandez

**Comment by bmattb** [comment]
@o-fernandez friendly reminder that this requires some additional product direction (and UXD) to be incorporated into the v1.10 release.

**Comment by BrittanyIRL** [comment]
Our rewrite of the checklist should make this easier (🤞 ) on the UXD side of things. If this is trying to get into the 1.10 release let's keep comms open on this and align on what each pod is doing to avoid another situation like video optimization 🙈

**Comment by BrittanyIRL** [comment]
@choumx @swissspidy This is on our roadmap for 1.10, which we're half way through. Is there an update on how we're all implementing this or should we bump it?

**Comment by BrittanyIRL** [comment]
Linking to @swissspidy 's helpful prototype which clears up my vagueness from last week: https://github.com/google/web-stories-wp/pull/6185/files 

We should definitely track clicks through for this helper link since it could be frustrating to a user to not know where their story is violating AMP. If possible, tracking the errors seen would give us good data to add more helpful checks. I think that for this initial implementation a generic check is a good step forward.
