### ISSUE TITLE
Stickers: Clean up panel

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#6187]
## Feature Description

Currently, our shapes panel only includes basic shapes which also act as masks. We'd like to expand this section to include stickers - svg elements that are not maskable. Many of these will be used in the new templates we are building. 

The request in this ticket is to:

1. Update the shapes panel so that it clearly differentiates between shapes and stickers
2. Load up the initial set of stickers into it (the ones needed to build our upcoming templates)

~@samitron7 adding this to the UX pipeline for the designs on how shapes and stickers would be seen. We should also attach the list of SVGs/Stickers that will be needed for the templates (it's OK if it's a superset and we end up using less).~

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief (Updated 7/17/2021)

- Follow the design system panel of 'shapes' to implement the design for stickers. 
- Stickers will be kept separate from shapes but share a panel (as they currently do) 
- Make sure that stickers are navigable via keyboard and no focus trapping occurs. 
- Stickers should be draggable 
- Stickers should be able to click to be added 
- Add tests accordingly 

While right now we are not implementing a 'search' or a filter, do keep in mind that that will be happening later based on sticker metadata - a bit like the text sets. 

Further implementation of this feature will be scoped as its own tickets.

**Comment by samitron7** [comment]
@o-fernandez You can find the design to differentiate between shapes and stickers [here](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=5193%3A331218). As for the sets of stickers, rtCamp is taking that task on. @swissspidy can we get coordination on this effort.

**Comment by swissspidy** [comment]
We‘ll first have to define how we‘re going to implement this from a technical perspective. We have a sync on that next week.

**Comment by bmattb** [comment]
@o-fernandez can we remove the v1.6 tag from this?

**Comment by o-fernandez** [comment]
> @o-fernandez can we remove the v1.6 tag from this?

Yeah, I'll add to the roadmap a new line item for this.

**Comment by dreamofabear** [comment]
> @o-fernandez You can find the design to differentiate between shapes and stickers here.

The mock displays a joint shapes & stickers panel with a toggle for showing only stickers. Just chatted with @BrittanyIRL and I think it may make more sense to keep these separate since they're distinct use cases e.g. as Canva does.

Other things to consider:
- Toggle for "stickers used in this story" (maybe useful for easily reusing stickers from a template)
- Search/filtering stickers

@o-fernandez FYI

**Comment by BrittanyIRL** [comment]
@csossi  there's testing instructions in the PR

**Comment by csossi** [comment]
Verified in QA
