### ISSUE TITLE
Help Center: Explore srcsets to improve performance (v2)

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6190]
## Feature Description

Let's explore using srcsets in the video assets used in the FTUE help companion. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Note that `video`, other than `img`, doesn't support `srcset`. But the `source` element supports a `media` attribute to define a media query.

That said, most of the help center webm videos are currently super small (< 50 KB). I don't think you can get any better performance there :-)

**Comment by BrittanyIRL** [comment]
> Note that `video`, other than `img`, doesn't support `srcset`. But the `source` element supports a `media` attribute to define a media query.
> 
> That said, most of the help center webm videos are currently super small (< 50 KB). I don't think you can get any better performance there :-)

Thanks, we can probably just remove this ticket altogether then. Thanks for the eyes. Video elements aren't something I've dealt with much!
