### ISSUE TITLE
Flickering carousel at critical width

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6197]
## Bug Description

When the workspace is between 992px and 1000px wide, the carousel flickers due to bad handling of near-critical value.

## Expected Behaviour

No flicker - either the carousel has margin or not.

## Screenshots
![carousel-flicker-bug](https://user-images.githubusercontent.com/637548/106972150-46d55d00-671e-11eb-9dfd-6405d3220e8a.gif)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
@bmattb, FYI, adding this to sprint.

**Comment by csossi** [comment]
Verified in QA
