### ISSUE TITLE
Redesign: Canvas selection

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6200]
## Feature Description

Update design for canvas selection based on [Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=1009%3A4323).

- [x] Update edge thickness and color
- [x] Update handle color, border and shape

| Current design | New design |
|-|-|
| ![Screen Shot 2021-02-04 at 22 16 09](https://user-images.githubusercontent.com/637548/106985347-4a291280-6737-11eb-8258-c14c817c53ef.png) | ![Screen Shot 2021-02-04 at 22 16 16](https://user-images.githubusercontent.com/637548/106985344-49907c00-6737-11eb-9c77-a4060879e056.png) |

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by claudiosossi** [comment]
Verified in QA
