### ISSUE TITLE
Redesign: Snap guides and design guide

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6201]
## Feature Description

Update design for guidelines based on [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=274%3A250).

- [x] Update design guide color
- [x] Update snap guideline style and color
- ~Add the _SAFE ZONE_ text (translatable) in proper typography using design system~

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
