### ISSUE TITLE
Redesign: Workspace iconography

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6204]
## Feature Description

Update iconography for workspace buttons based on [Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=1009%3A4323).

Pay attention to both sizing and spacing.

- [x] Update next/previous arrows for both page and carousel
- [x] Update page menu icons (delete, duplicate, add, undo, redo)
- [x] Update carousel menu icons (keyboard, gridview)

For this ticket: Ignore version number, ignore zoom dropdown.

| Current design | New design |
|-|-|
| ![Screen Shot 2021-02-04 at 22 39 46](https://user-images.githubusercontent.com/637548/106986716-ed7b2700-6739-11eb-96b7-86dd71f3f9fd.png) | ![Screen Shot 2021-02-04 at 22 37 49](https://user-images.githubusercontent.com/637548/106986717-ee13bd80-6739-11eb-885b-22addeb7e2df.png) |

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
