### ISSUE TITLE
Redesign: Page header

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6205]
## Feature Description

Update page header based on [Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=1009%3A4323).

Pay attention to both sizing and spacing including that of the entire header.

- [ ] Update page header sizing and spacing
- [ ] Update primary button design to use design system primary button
- [ ] Update secondary buttons to be icons (using design system icon button)

| Current design | New design |
|-|-|
| ![Screen Shot 2021-02-04 at 22 44 02](https://user-images.githubusercontent.com/637548/106987110-bd805380-673a-11eb-9a7f-4e4f2ac5e08c.png) | ![Screen Shot 2021-02-04 at 22 43 54](https://user-images.githubusercontent.com/637548/106987112-bd805380-673a-11eb-853d-b2a6e6af7c12.png) |

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Will the Save Draft icon go darker when it's disabled? (Edit: or well --  it will still be disabled, right? When there are no unsaved changes)

**Comment by miina** [comment]
Adding UX Needed label since it's waiting for the confirmation about the Save to Draft button -- will it be a text or a button.

**Comment by csossi** [comment]
Verified in QA
