### ISSUE TITLE
Redesign: Gridview

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6206]
## Feature Description

Update page grid view mode based on [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=298%3A1113).

- [x] Update background opacity (should be fully opaque)
- [x] Update back button (using design system button)
- [x] Update slider (blocked by #4938)
- [x] Update spacing and sizing for all elements in view
- [x] Update to new focus rectangle (could be generalized from carousel page focus rectangle)
- [x] Update drag and drop styling (it might need native drag and drop rather than current fake, but that would go in a separate less important ticket)

| Current design | New design |
|-|-|
| ![Screen Shot 2021-02-04 at 22 48 25](https://user-images.githubusercontent.com/637548/106987313-2c5dac80-673b-11eb-9fb1-1ad35a5361d7.png) | ![Screen Shot 2021-02-18 at 9 15 46 PM](https://user-images.githubusercontent.com/10889431/108460918-7f049180-722e-11eb-82cb-69baef7dd4dc.png) |

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Will the number of pages per row remain the same for each level?

**Comment by barklund** [comment]
@samitron7, awaiting confirmation on design as Figma has diverged from above screenshots as [per thread](https://xwp.slack.com/archives/C01ESBB8ZN1/p1613680159307100).

**Comment by csossi** [comment]
Verified in QA
