### ISSUE TITLE
Redesign: Library

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6207]
## Feature Description

Update library design based on [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=257%3A817).

- [ ] Update library tab icons using the design system (awaiting a decision on icon sizing)
- [ ] Update tab-to-tabpanel border opacity (`divider.secondary`)
- [ ] Update current tab indicator (24px `interactiveBg.brandNormal`, but extended to 38px wide on text tab)
- [ ] Update upload button using design system
- [ ] Update text tab animation according to new designs linked above and this small gif:
![elementNav](https://user-images.githubusercontent.com/637548/107830762-8a514c00-6d5a-11eb-842b-11047779fe2b.gif)
- [ ] Update tooltip to new component where applicable

Do not update search input, this will happen in #6322

Do not remove or change the image type dropdown.

| Current design | New(ish) design |
|-|-|
| ![Screen Shot 2021-02-04 at 23 00 34](https://user-images.githubusercontent.com/637548/106988273-6039d180-673d-11eb-95b3-d5969d09a5f4.png) | ![Screen Shot 2021-02-04 at 23 00 26](https://user-images.githubusercontent.com/637548/106988274-6039d180-673d-11eb-9f2e-f4591a6b6c5c.png) |

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Will the dropdown for switching between the types be removed / is that a separate issue?

**Comment by barklund** [comment]
> Will the dropdown for switching between the types be removed / is that a separate issue?

It will not be removed. It is an error in the design, that it was removed.

Also, I've updated the ticket with information about active tab indicator and particular instructions for the text tab as per conversations.

**Comment by csossi** [comment]
Verified in QA

**Comment by miina** [comment]
Note: the colors in Figma changed while this issue was already in QA -- the line below the active tab might be of a different color while the UAT is being done.
