### ISSUE TITLE
Redesign: Color picker

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6208]
## Feature Description

Update color picker based on [Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=1965%3A326019).

- [ ] Update background color and border-radius
- [ ] Update color type selector using design system
- [ ] Update cross icon using design system
- [ ] Update layout and style of saturation, hue and alpha pickers plus active selection indicators
- [ ] Update layout and style of gradient line and gradient stops (including logic to add, move and remove using both mouse and keyboard)
- [ ] Update gradient reversal and rotation icon buttons using design system
- [ ] Update design and layout of hex and alpha inputs using design system
- [ ] Update tooltip to new component where applicable

Things not to do in this PR:
- Make sure the color dropper is still hidden
- Do not update dropdown

| Current design | New design |
|-|-|
| ![Screen Shot 2021-02-04 at 23 11 42](https://user-images.githubusercontent.com/637548/106988860-c70bba80-673e-11eb-815d-625df953f320.png) | ![Screen Shot 2021-02-04 at 23 12 02](https://user-images.githubusercontent.com/637548/106988859-c70bba80-673e-11eb-8857-3b248b5942f1.png) | 
| ![Screen Shot 2021-02-04 at 23 13 34](https://user-images.githubusercontent.com/637548/106988857-c6732400-673e-11eb-9ca5-b698d56978b8.png) | ![Screen Shot 2021-02-04 at 23 13 40](https://user-images.githubusercontent.com/637548/106988856-c5da8d80-673e-11eb-9579-e5b29ff1fc2d.png) |

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA

(tested according to:
"Testing Instructions
Add a shape and open the color picker
Verify that Solid color style looks similar to Figma
Verify that Linear and Radial also look similar to Figma
Note: there is a bug related to moving stops by dragging -- there's jumpiness and the stops aren't placed properly. This is an unrelated bug and will be addressed in a separate PR.

Note 2: The dropdown in the saved colors area will be redesigned separately."

Noting here to indicate exclusions
