### ISSUE TITLE
Redesign: Color scheme

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6209]
## Feature Description

Update general color scheme based on [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3211%3A70090).

- [ ] Update all colors

Note that this includes the widely used background colors of the entire workspace.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
This would then mean switching over to the new design system where the colors are already defined + removing the old theme usage fully + going through the colors to see if there are any that are hardcoded right now, yes?

There are quite a few places where something like `rgba(theme.colors.bg.white, 0.1)` or just hex values etc is used, these should probably all be checked. It might take a bit more time to go through all these. WDYT?

**Comment by barklund** [comment]
We should use this opportunity to start the switch to the new system, and if it requires more subsequent tickets for sections not already planned in the redesign walkthrough, we should create those tickets.

For now, I think it's about updating the very main colors of the entire application and figuring out how to do so in this ticket (so just the main background and foreground color probably - or a couple of them). Do we still use a theme (probably) and how do we inject it (dunno)? We should keep the old theme around for now, but see it as something to be (very slowly) deprecated.

**Comment by barklund** [comment]
Thinking a bit about it, the idea of adding it to the current theme is okay, but let's just call it `system`, so it's just:
```js
const theme = {
  system: designSystemTheme,
  ...
};
```

Would that work for you?

**Comment by barklund** [comment]
Options as I see it:

1. Add system theme to current theme
2. Add current theme to system theme (e.g. as `theme.old....`)
3. Create a separate provider for system theme

I'm open to all three. 2 is probably too much work at this point though.

**Comment by barklund** [comment]
Some other work settled this.

We actually need to do item 2 above - or at least have the correct keys from the system theme. Because the design system components expect the theme to be the design system theme **and** will look for properties on it _as if it is_. This just made my work impossible in #6204, because our theme doesn't have a `colors.border.focus` property so the whole workspace component fails hard.

And this is going to clash for sure - because both the current theme and the new design system theme have a property located at `theme.colors.fg.primary`. Many other duplicates exist. This particular duplicate happens to be almost the same color (`#E4E5E6` vs `#EDEFEC`), but that's not going to be the case for all colors nor all the other properties.

So, I think we need to move the old theme into a property called just that - and auto-replace all references to it. And then the theme will be:

```js
const theme = {
  ...designSystemTheme
  old: {
    ...
  }
};
```

This will also make it clear, what needs to be deprecated in the future. We can even add a linter warning at some future date to warn about not using `theme.old` - and finally delete it when completely phased out.

And we need to prioritize this ticket higher, as it will be blocking (almost) all the other work.

I've [asked](https://xwp.slack.com/archives/CCCAUAH6F/p1612842825151400) @swissspidy to come up with a plan for how to have a temporary main branch for this work so we can work off of other work. If the two of you can solve that in the EU morning, that would be awesome! @swissspidy can also help you with the automated renaming required above. Most of it is probably a simple _search-and-replace_, but there might be some more tricky instances - especially in cases of `useTheme()`.

**Comment by miina** [comment]
Option 2 SGTM!

**Comment by swissspidy** [comment]
For the theme I'd recommend doing it the same way as was done for the dashboard so migrations can be done similarly.

See https://github.com/google/web-stories-wp/blob/fad69347fd5dc6f99f1831bca3f8e33542d30ad3/assets/src/dashboard/app/index.js#L124-L128 and the PR #5073

**Comment by miina** [comment]
> For the theme I'd recommend doing it the same way as was done for the dashboard so migrations can be done similarly.

Ok, will replace `old` in the PR to `DEPRECATED_THEME` for consistency.
