### ISSUE TITLE
Redesign: Layer panel

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6210]
## Feature Description

Update design for layer panel based on [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3360%3A63235).

- [ ] Update overall size and shape (notice how the layer panel is narrower than the full inspector and has rounded corners on top)
- [ ] Add lock icon for background using design system
- [ ] Make sure layers are correctly laid out and spaced

Do not update the panel header including title, arrow and border in this PR.

| Current design | New design |
|-|-|
| ![Screen Shot 2021-02-04 at 23 46 35](https://user-images.githubusercontent.com/637548/106991172-b1e55a80-6743-11eb-96fe-e02c7dccec01.png) | ![Screen Shot 2021-02-04 at 23 49 19](https://user-images.githubusercontent.com/637548/106991171-b1e55a80-6743-11eb-864a-1e38633a9f3a.png) |
| ![Screen Shot 2021-02-04 at 23 46 31](https://user-images.githubusercontent.com/637548/106991174-b27df100-6743-11eb-874a-0bcfd87e22c6.png) | ![Screen Shot 2021-02-04 at 23 49 47](https://user-images.githubusercontent.com/637548/106991199-bf9ae000-6743-11eb-8a49-972ee51e9050.png) |

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Does this also include showing a mini-version of the real background instead of just the icon?

**Comment by csossi** [comment]
Verified in QA
