### ISSUE TITLE
Redesign: Inspector og library tab lists

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6212]
## Feature Description

Update design for inspector and library tab lists based on [Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=1009%3A4323).

- [x] Update tab icons
- [x] Update tab typography and current tab indicator
- [x] Update colors for background and border
- [x] Update tooltip to new component where applicable

| Current design | New design |
|-|-|
| ![Screen Shot 2021-02-05 at 00 00 38](https://user-images.githubusercontent.com/637548/106991931-4d2aff80-6745-11eb-9a95-c514b2046cf2.png) | ![Screen Shot 2021-02-05 at 00 00 32](https://user-images.githubusercontent.com/637548/106991932-4dc39600-6745-11eb-8785-f5c305a69c68.png) |

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
