### ISSUE TITLE
Redesign: Update text preset buttons

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6213]
## Feature Description

Update design for text presets based on [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3360%3A63235).

- [ ] Update typography and colors for normal, hover and focus
- [ ] Update tooltip to new component where applicable

| Current design | New design |
|-|-|
| ![Screen Shot 2021-02-05 at 00 04 22](https://user-images.githubusercontent.com/637548/106992123-bc085880-6745-11eb-9b36-daf768d227e5.png) | ![Screen Shot 2021-02-05 at 00 04 06](https://user-images.githubusercontent.com/637548/106992125-bc085880-6745-11eb-924a-2831decfb4d6.png) |

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
