### ISSUE TITLE
Redesign: Update text set buttons

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6214]
## Feature Description

Update design for text sets based on [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=257%3A817).

- [ ] Update normal, hover and focus styling for individual text sets ([additional Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3360%3A63235))
- [ ] Update position of font match and headline
- [ ] Update toggle from design system
- [ ] Update tooltip to new component where applicable

| Current design | New design |
|-|-|
| ![Screen Shot 2021-02-05 at 00 06 53](https://user-images.githubusercontent.com/637548/106992347-3802a080-6746-11eb-8cf1-da9ac8418708.png) | ![Screen Shot 2021-02-05 at 00 06 19](https://user-images.githubusercontent.com/637548/106992348-389b3700-6746-11eb-8f24-5b979f580154.png) | 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Will the pills part be a separate issue? Looks like that also needs adjustments.

**Comment by samwhale** [comment]
Looks like the `headline` and the toggle label got moved back: 
<img src="https://images.zenhubusercontent.com/5b1032a1348b7966b43421a4/8ef98c9a-d6c0-4a7b-bfce-979c4afe09f6" width="300px" />

https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=257%3A817

Unless I'm looking in the wrong place

**Comment by miina** [comment]
> Looks like the headline and the toggle label got moved back:

Yep -- looks like it -- it can be expected that the design has changed since the creation of the ticket and some screenshots can be inaccurate.

**Comment by csossi** [comment]
Verified in QA

**Comment by samwhale** [comment]
Pill updates will be done here: #6873
