### ISSUE TITLE
Redesign: Update shape buttons

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6215]
## Feature Description

Update design for shapes tab content based on [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=257%3A817).

- [x] Update normal and focus style (note normal styling has background color rather than border) ([additional Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3360%3A63235))
![Screen Shot 2021-02-05 at 00 12 28](https://user-images.githubusercontent.com/637548/106992840-6339bf80-6747-11eb-9265-c4d9bf905db9.png)

- [x] Add keyboard navigation using roving tab index so they're focusable (currently they're not at all)
- [ ] Add "read more" link using design system and figure out what to link to
- [x] Update styling of header using design system
- [x] Update grid spacing
- [ ] Update tooltip to new component where applicable

Note: Do not add a search box, do not update tab icons in this PR.

| Current design | New design |
|-|-|
| ![Screen Shot 2021-02-05 at 00 12 34](https://user-images.githubusercontent.com/637548/106992830-5fa63880-6747-11eb-8df9-902e2532ff0c.png) | ![Screen Shot 2021-02-05 at 00 12 50](https://user-images.githubusercontent.com/637548/106992827-5fa63880-6747-11eb-88ed-991ab525470f.png) |

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
When I highlight a shape, it appears within a blue border and has a lighter grey background:
https://share.getcloudapp.com/RBuYKv7x

according to 6769, should just be black:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/06b5390c-40d7-4620-9ab5-2e0a69580ea9)

**Comment by miina** [comment]
@csossi Figma changed meanwhile, blue border and grey background is actually correct: https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3387%3A72571

It's always good to verify with Figma -- the screenshots in the issues might be out of date since these are often added quite a long time before implementing.

Moving to QA Passed since this seems to be the only finding.
