### ISSUE TITLE
Publish Date/Time picker is partially blocked when stories editor is in RTL direction

### ISSUE THREAD

**Issue by kkalarickal** [GoogleForCreators/web-stories-wp#6218]
## Bug Description

Within RTL directional view, the date/time picker is not fully visible.

## Expected Behaviour

Just like in LTR direction, the RTL view should allow the user to see the entire date/time picker.

## Steps to Reproduce

1. Open/create a story in the stories-editor and click the "Switch fo RTL" button
2. Select the Document panel (on the left) and then the Publishing drop down
3. Click the arrow next to Publish element
4. The date/time picker that appears is partially chopped off

## Screenshots

![image.png](https://images.zenhubusercontent.com/5fc17739d77478a91f8d75e3/1e4b1a4b-eb2e-4f9a-9cf3-51522cec99df)

## Additional Context
Found during QA of #5909

- Plugin Version: 1.3.0+5296f56
- WordPress Version: 5.6.1
- Operating System: Windows-10
- Browser: Chrome 88

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
Duplicate of #6662
