### ISSUE TITLE
Discovery: Determine number of content partners need <WP5.x support

### ISSUE THREAD

**Issue by kmyram** [GoogleForCreators/web-stories-wp#624]
## Feature Description

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment]
Hey @pbakaus did you find out how many publishers are on <WP5.x?

**Comment by pbakaus** [comment]
@jauyong we're still finalizing the first set of publishers, so the answer is sadly no. I'd say let's punt on this for now, and revisit at a later stage.
