### ISSUE TITLE
Pre-Publish Checklist: Video Optimization integration

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6241]
## Feature Description

Users should be able to optimize existing videos in the library/story from within the pre-publish checklist.

Example:

<img width="228" alt="Screenshot 2021-01-29 at 11 16 34" src="https://user-images.githubusercontent.com/841956/106262520-73bbd880-6223-11eb-8350-bbb3b24fcf74.png">

**[Figma link](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=4765%3A3)**

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

*  Extract logic to test whether a video needs to be optimized so it's reusable by upload & pre-publish checklist
* Add pre-publish checklist warning for non-optimized videos
* Do not show warning for videos that are already optimized (check media source)
* Allow video optimization by click on a button
* Same UX as for video optimization during upload, with snackbar messages, etc.

**Comment by o-fernandez** [comment]
Per design team, this will be UX-ready/designs ready by Apr 16.

**Comment by swissspidy** [comment]
@BrittanyIRL FYI here's a ticket y'all can use. #7130 is the PR for implementing the necessary hooks for this.

**Comment by Cecil921** [comment]
@BrittanyIRL Hey, here's the finished specs for video optimization. https://www.figma.com/file/1YM3jA9h4QGc4xLdyaXIJS/?node-id=7091%3A0

**Comment by BrittanyIRL** [comment]
This ticket's a little confusing because since this ticket's creation I have fleshed out the entire epic for the feature and sliced the work up into more manageable pieces. This work is done (more or less) and remaining logic is to be sorted out in #7355. I am going to close this as duplicative.
