### ISSUE TITLE
Media Resizing not working as expected

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#6247]
## Bug Description
Media Resizing does not work as expected.
When going into edit mode and using resize, the resize box stays the same size and zoom happens instead -- the area that was left in the resize will fill all the area available based on the element size. It basically changes the focal point and the zoom level.
This could be expected behavior in theory, however, when leaving the edit mode, the element itself has changed the size, unlike the edit mode.

## Expected Behaviour

When resizing media in edit mode, the element should get resized and the resize box should not jump back to the size that it originally was. Then, when exiting the edit mode, the element should be the same size as it showed in the edit mode.

## Steps to Reproduce
1. Add Media
2. Enter edit mode
3. Resize smaller
4. See the general size not changing
5. Not exit edit mode
6. See the general size has changed.

## Screenshots
![resizing](https://user-images.githubusercontent.com/3294597/107231825-0a0cad00-6a21-11eb-93bc-91cfd2490aa0.gif)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
