### ISSUE TITLE
Indicator for links opening in new page

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#6254]
## Feature Description

Could we add an indicator next to links that open on a new tab/window to show that they are external links? 
For example, the "support" link here, could have a little indicator that lets the user know this will open on a new page. 
![image](https://user-images.githubusercontent.com/13389997/107256795-f0ab3700-6a07-11eb-89b0-094ca1062e07.png)

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

One possible way to do this is looking to the design system `Link` - marking as `isExternal` so that we don't have to track what the internal url is and when that bool is true showing the icon `:after` - that'd let us see how much this would impact the editor and dashboard.

**Comment by BrittanyIRL** [comment]
hey @o-fernandez - wanted to revisit this, what do you think the 'indicator' should be? This is otherwise really straight forward to implement. Are you thinking like an asterisk?

**Comment by o-fernandez** [comment]
I was thinking an icon like this: https://commons.wikimedia.org/wiki/File:External_link_font_awesome.svg
WDYT? @BrittanyIRL

**Comment by swissspidy** [comment]
Does this apply to editor as well? (e.g. links in help center)

**Comment by BrittanyIRL** [comment]
That works for me! We don't have an icon like that yet so we will need design help to get an SVG.

**Comment by BrittanyIRL** [comment]
(+1 to Pascal's ask)

**Comment by swissspidy** [comment]
Material Design has an icon for this: https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Alaunch

**Comment by BrittanyIRL** [comment]
@o-fernandez  circling back to this. 

Re pascal's ask - do we want this same indicator on the editor or just the dashboard? 

Do we want to proceed with this using Material Design's icon or should this remain in the icebox until we get designated design that can assist with the icon creation?

**Comment by o-fernandez** [comment]
I'd use the Material Design icon Pascal suggested, and ideally everywhere with links that go to an external page (which should all hopefully open in a new window?) 

Let me know if that works! If we find tricky ones where adding the icon would break the UI, LMK and we can rethink it. @BrittanyIRL

**Comment by csossi** [comment]
Verified in QA
