### ISSUE TITLE
Help Center: RTL arrow in wrong direction

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6259]
Per @spacedmonkey during bug bash

Should be opposite this: 
![Screen Shot 2021-02-08 at 11 17 21 AM](https://user-images.githubusercontent.com/10720454/107263661-43ccbc00-69ff-11eb-960e-81e6d72e18c0.png)

**Comment by spacedmonkey** [comment]
<img width="367" alt="Screenshot 2021-02-08 at 17 50 49" src="https://user-images.githubusercontent.com/237508/107264468-e8202400-6a3a-11eb-9dfb-18865abf4927.png">
And this.
