### ISSUE TITLE
Media upload overlay covers FTUE popup

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6260]
Happens when dragging an image onto the canvas.

![Screen Shot 2021-02-08 at 11 15 50 AM](https://user-images.githubusercontent.com/10720454/107263467-023c1100-69ff-11eb-8c79-43021be2d876.png)

It's more of a DOM hierarchy issue (which will cause a lot of side effect regression cleanups) than a simple z-index fix.

Is an edge case fix for a considerable amount of work. I'll defer to @o-fernandez for importance here. But going to put in backlog for now unless specified otherwise.

**Comment by o-fernandez** [comment]
Seems ok as a P3, no need to tackle right away.

**Comment by BrittanyIRL** [comment]
So, 8 months ago when this ticket was created it I remember this being an edge case within Firefox. Now, looking at Chrome it's the same behavior and I'm not actually convinced this is bug at all. It feels like proper behavior. If I am dragging media into my canvas and I have one of the popups open I would expect to drop my media into the canvas area including the area which the popup is covering. In this case, the overlay makes total sense. 

https://images.zenhubusercontent.com/235435637/414de04e-1d7d-4f78-922c-8444653ade5e/kapture_2021_10_19_at_13_12_10.mp4

@agingoldseco can I get your input here?

**Comment by agingoldseco** [comment]
@BrittanyIRL I think this is working properly too! Someone might be following instructions from Help and have to click around the editor or drag media to the canvas—I don't think allowing the pop-ups to stay open through that is an issue even if some text overlaps. 

I _am_ a little concerned by the two scrollbars in that checklist though...
<img width="448" alt="Screen Shot 2021-10-19 at 5 04 33 PM" src="https://user-images.githubusercontent.com/90645922/137990482-eed4f57f-7bdc-4f33-ab12-ba0b51d47114.png">

**Comment by BrittanyIRL** [comment]
Cool, thanks @agingoldseco  - i'll close this issue. 

@samwhale is fixing the double scrollbars - he's got a PR up already for it!
