### ISSUE TITLE
Link URLs show broken site icon

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6264]
## Bug Description

After adding a URL to a link attached to an object in the editor the LINK panel is updated to show the site icon when available. In some cases this appears as a missing image

## Expected Behaviour

Broken images should not be shown

## Steps to Reproduce

1. In the editor, add a link an existing object
2. Use the URL 'heavy.com"
3. Watch as the URL is updated with the protocol \
4. Note that the site icon is attempted to be displayed, but appears to be missing

## Screenshots

![Screen Shot 2021-02-08 at 1 01 52 PM](https://user-images.githubusercontent.com/58738530/107264986-b777c480-6a11-11eb-970e-e5cab98d9ef4.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
That's because the `og:image` declared on that site does not exist: https://heavy.com/wp-content/themes/heavy/images/fbshare.jpeg. Seems like quite the edge case.

**Comment by bmattb** [comment]
I actually saw it twice yesterday during my limited testing of this feature on two sites
