### ISSUE TITLE
Link URL optional site icons are not updated when URL is changed

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6265]
## Bug Description

Sometimes after changing the URL of an object's link, the optional brand logo is not updated with the new site's icon, and the old one appears to be retained. This may be problematic

## Expected Behaviour

If the updated URL doesn't have a site icon that can be used, I would expect that any existing site icon would be removed from the link and not shown to end users.

## Steps to Reproduce

1. Open the editor and select an object to apply a link URL to
2. Add the URL to the object - eg: TSN.ca
3. Preview the story - the brand icon is shown to the end users
4. Update the URL on the same object - eg: Bell.ca
5. Preview the story - the URL has been updated, but the previous site's icon remains in place

## Screenshots

![Screen Shot 2021-02-08 at 1 29 18 PM](https://user-images.githubusercontent.com/58738530/107265738-a1b6cf00-6a12-11eb-95a8-02ca204dd22f.png)

![Screen Shot 2021-02-08 at 1 36 29 PM](https://user-images.githubusercontent.com/58738530/107265782-aed3be00-6a12-11eb-96e7-70851e5d4120.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System: Mac 11.2
- Browser:  Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
