### ISSUE TITLE
Redesign Scrollbars

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6285]
## Feature Description

Scrollbar appearance should be consistent as much as possible while respecting users' settings. 

Per slack conversation with @samitron7 on Feb 8, 2021: 

1. We should reuse the work Paul did that's visible in this panel and update the colors: 
![Property 1=Text](https://user-images.githubusercontent.com/10720454/107391745-3e7e7880-6ab6-11eb-9178-97d0f01ba3e5.png)

This is what it looks like in Figma
![Screen Shot 2021-02-08 at 2 50 25 PM](https://user-images.githubusercontent.com/10720454/107391871-5e15a100-6ab6-11eb-850f-48c011090eee.png)
![Screen Shot 2021-02-08 at 2 50 31 PM](https://user-images.githubusercontent.com/10720454/107391875-5eae3780-6ab6-11eb-84c5-14ef68fdbb23.png)

Easiest to see if you look at panels: https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=257%3A817 

## Additional Context

This will probably be three things: 

- Scrollbar styles will need to be exportable as css from the design so they can be added to apps internally
- Scrollbar styles need to be set in design-system/components/popup (just like they were in edit-story/components/popup)
- a `createGlobalStyle` import from the design-system so that it can be added at the top level of apps like <themeGlobals.OverrideScrollbar />

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

Regardless of if a scrollbar is visible, if there's a possibility of a scrollbar being there white space should be handled the same. A good demo of this is a dropDown menu. The side with the scrollbar should have the same whitespace if the scrollbar is present vs. not.

**Comment by BrittanyIRL** [comment]
@barklund heads up on this - just talked to Sam about scrollbars. We've left these to the browser so far in the design system. Either of our pods should pick this up depending on availability.  (I think pea pod can pick this up next week, just depends how much we clear this week)

**Comment by barklund** [comment]
@BrittanyIRL, we [discussed it briefly](https://github.com/google/web-stories-wp/pull/6273/files#r573174323) in the "new color scheme PR", but found it a bit too complex to include there, so great with a dedicated ticket for this.

With that PR now merged, the design system color scheme is readily available.

However, do note that there are scrollbar color definitions all over the place. Any attempt at centralizing the CSS would also be very welcome.

**Comment by BrittanyIRL** [comment]
> However, do note that there are scrollbar color definitions all over the place. Any attempt at centralizing the CSS would also be very welcome.

This is why I put a pin in it when I thought I could lump it in with pulling the popup into the design system! Ok cool, dedicated ticket and some cross pod review ✅
