### ISSUE TITLE
Allow deleting the selected element(s) via keyboard

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#63]
## Feature description

Deleting element via delete icon/link was implemented within ampproject/amp-wp#3837 but it should also be possible to use keyboard for doing that.

Deleting selected elements (one or more) should be possible via keyboard interaction by pressing "Delete".

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The user should be able to remove selected elements by clicking the "Delete" key on the keyboard (Backspace on Mac).

## Implementation brief

* 
* This includes setting focus to a proper element so `document.activeElement` refers to a relevant element and continues to do so whenever other elements loses focus (e.g. when you blur an input field in the inspector). This part is rather complex, FYI.

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by barklund** [comment]
This can be closed now, no? @dvoytenko @swissspidy
