### ISSUE TITLE
Move capabilities out of history

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#630]
## Feature Description

Follow-up discovery issue for potentially reworking how capabilities are stored.

See discussion thread starting from [here](https://github.com/ampproject/amp-wp/pull/4122#discussion_r367949420) with the conclusion to follow up in a separate issue.

Edit after testing:
Capabilities seem to create extra history entries which can "mess up" the user's history, especially if the offset of the current history state is something else than 0.

To replicate:
- Open a new story without history
- Go to Document tab
- See new history entry (Undo becoming available).

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
@miina This is a duplicate #196

**Comment by miina** [comment]
@spacedmonkey Thanks, saw that issue but it wasn't clear from the description it was a duplicate. 
Will close this.

**Comment by miina** [comment]
Reopening as #196 seems to cover the capabilities wider, including leveraging more capabilities in the editor, whereas this issue is specifically about the architecture.

**Comment by miina** [comment]
Although it's an old issue and not very visibly user-facing, it's still odd that capabilities are tracked in history, it would be good to rework how capabilities are stored and get this fixed.

Might not be a priority for beta but tagging you here just in case if you think otherwise:
cc @dvoytenko @pbakaus 

Note after testing: it looks like capabilities are actually causing extra history entries so this issue is really a bug issue as well.

**Comment by swissspidy** [comment]
Ha, I was just looking for this! Definitely needed, especially since we want to decouple the editor from WP.

**Comment by dvoytenko** [comment]
IMHO, we need to prioritize it relatively high.

**Comment by spacedmonkey** [comment]
I think that #196 will fix this issue. How we deal with capabilities in general is very messy, I still think this needs fixing before we go wider with this plugin.

**Comment by barklund** [comment]
We could move it to the config provider. I guess we can even load it in statically on initial page load as a parameter for the editor. Or load it initially - but still store it in the config provider. It's not clear-cut what config it provides and what it doesn't, but this could fit the bill.

**Comment by jauyong** [comment]
Closing in favour of #196
