### ISSUE TITLE
Infrastructure: update to webpack v5

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6304]
## Task Description

webpack 5 contains a ton of improvements and bug fixes, and will also help in our endeavour to further optimize our bundles. There are some caveats though. See #5792 for more info.

**Comment by swissspidy** [comment]
@BrittanyIRL This one is at the interesction of Karma and performance improvements, perhaps another thing that Pea pod wants to look into?

#5792 has the WIP for this.

**Comment by BrittanyIRL** [comment]
> @BrittanyIRL This one is at the interesction of Karma and performance improvements, perhaps another thing that Pea pod wants to look into?
> 
> #5792 has the WIP for this.

Sure! This will be a big one but it would be so great to complete.

**Comment by swissspidy** [comment]
The good thing is the majority of the work should done, what's left is fixing the storybook and — surprise — Karma tests. Admittedly, it still might take some time to crack these two.

**Comment by swissspidy** [comment]
cc @merapi as you might have some ideas on how to fix the Karma tests in #5792 - the PR has all the details

**Comment by swissspidy** [comment]
Regarding the open todos on #5792: One of the storybook issues might be fixed by ` v6.5.0-alpha.23`, see https://github.com/storybookjs/storybook/issues/14877#issuecomment-1020290378

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #5792.

Regressed/smoke tested editor:

1. Created new story
2. Updated existing one
3. Added images/videos/shapes/text
4. Updated colors, layouts
5. Preview
6. Tested checklist
7. Published
8. Added and remove links, background images

Working as expected.
