### ISSUE TITLE
adding close on the stories page

### ISSUE THREAD

**Issue by AJOO7** [GoogleForCreators/web-stories-wp#6313]
## Feature Description

on the story page to provide a  efficient user experience a close button redirecting back to hamepage must be provided

## Additional Context

it could be something like insta feed
![issue4](https://user-images.githubusercontent.com/67185443/107557208-501f6780-6bff-11eb-91ca-d4c14409cc17.PNG)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by LuckynaSan** [comment]
@AJOO7 Thank you for your feedback. We are currently working on an exit feature where the story will be opened in a fullscreen lightbox with a close button. Please stay tuned for this in our future release or you can monitor this [ticket](https://github.com/google/web-stories-wp/issues/3452) for any updates.
