### ISSUE TITLE
Remove backgroundColor property from background element

### ISSUE THREAD

**Issue by embarks** [GoogleForCreators/web-stories-wp#6315]
## Task Description
**Context**
This is a tech debt ticket.

Per Morten's comment [here](https://github.com/google/web-stories-wp/issues/5905#issuecomment-771227657)

The `backgroundColor` property on the background element is not active or used. The `backgroundColor` property lives on the page for page background colors. It should be removed from the element to reduce confusion.

**Comment by swissspidy** [comment]
@barklund @BrittanyIRL is this still relevant?
