### ISSUE TITLE
Asset CleanUp: Page Speed Booster Conflict with Stories Dashboard

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#6316]
## Bug Description
The following error message occurs when accessing My Stories on the dashboard: Unable to load stories. The response is not a valid JSON response. 

## Steps to Reproduce

1. Use a site that uses Cloudflare as a CDN
2. Install and activate the Web Stories plugin
3. Create a story
4. Install and activate [Asset CleanUp: Page Speed Booster](https://wordpress.org/plugins/wp-asset-clean-up/) plugin
5. Access My Stories. Notice the error message and the story no longer on the dashboard.

## Additional Context
The error occurs on a test site using Cloudflare security. 
No browser console errors and the network response is blank. 

Current workarounds:
Excluding the /web-stories/(.*?)/ URL under Asset CleanUp Settings > Plugin Usage Preferences > Do not load the plugin on certain pages > enter in the [exclusion /web-stories/(.*?)/](https://jumpshare.com/v/YHBL98vGW17gE2fCi3Gh).

Related Topics:
https://wordpress.org/support/topic/unable-to-load-stories-the-response-is-not-a-valid-json-response-2/
https://wordpress.org/support/topic/web-stories-unable-to-load-error/
https://wordpress.org/support/topic/json-error-unable-to-load-stories/

- Plugin Version: 1.3.0
- WordPress Version: 5.6.1
- Operating System: macOS 13-inch
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Sharing my findings from our joint debugging session earlier:

When the plugin is active, any REST API requests to the stories endpoint will _succeed_, but the response body is completely blank (`Content-Length: 0`).

It's not clear yet why this plugin affects the REST API and what exactly causes this issue, as there are no indicators whatsoever in the logs.

**Comment by the-gap-decaders** [comment]
I have also had this issue this morning. Not using a CDN and no other errors. Excluding web-stories in Asset CleanUp works, as does deactivating the plug in.
