### ISSUE TITLE
Percy Font Loading Flakiness

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6317]
Nothing new here really, ticket for tracking purposes. 

Seems that snapshots are sometimes taken at a marginally different size or speed and reporting 'changes' when nothing actually changed. 

For example, I had to approve percy changes in a recent documentation update I made here: https://percy.io/google/web-stories-wp/builds/8765894/changed/497717303?browser=chrome&browser_ids=14%2C16&subcategories=approved&viewLayout=side-by-side&viewMode=new&width=1600&widths=1600  where the only diff was a markdown file.

**Comment by swissspidy** [comment]
Thanks for filing!

At first glance it seems like the Roboto font with weight 700 wasn't fully loaded in one of the screenshots.

While we check for font loading here:

https://github.com/google/web-stories-wp/blob/1ea476bb315d2618cfdd95f6ffd9775593064a69/assets/src/edit-story/karma/fixture/fixture.js#L299-L306

We actually only load Roboto 400 here:

https://github.com/google/web-stories-wp/blob/1ea476bb315d2618cfdd95f6ffd9775593064a69/assets/src/karma-fixture/client_with_context.html#L14-L21

We need to make sure the 700 weight (and potentially others if not all weights) are loaded too.

That should hopefully reduce flakiness here.

Same can be done for Google Sans in the dashboard too.

@spacedmonkey is this something you could look into?
