### ISSUE TITLE
Redesign: Update search input in Library

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#6322]
## Feature Description
Update the search input based on [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3398%3A79991)

Dashboard is using a similar search input so the component should come from design-system.

- [ ] Replace the search input with a component based on Figma.
- [ ] Update spacing around search box

| Current design | New(ish) design |
|-|-|
| ![Screen Shot 2021-02-04 at 23 00 34](https://user-images.githubusercontent.com/637548/106988273-6039d180-673d-11eb-95b3-d5969d09a5f4.png) | ![Screen Shot 2021-02-04 at 23 00 26](https://user-images.githubusercontent.com/637548/106988274-6039d180-673d-11eb-9f2e-f4591a6b6c5c.png) |

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
