### ISSUE TITLE
Add links to plugin row meta

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6326]
## Feature Description

Site Kit has added two subtle links on the plugins page to encourage reviews / opening support topics:

![image](https://user-images.githubusercontent.com/73545194/104025738-0a3a4280-5200-11eb-871e-42b4958c495c.png)

Perhaps we could do the same? With some telemetry it could provide us some insights on usefulness too.

Even if it's not used much, could be a subtle, unobtrusive, nice-to-have enhancement.

## Additional Context

Site Kit implementation: https://github.com/google/site-kit-wp/issues/2516 & https://github.com/google/site-kit-wp/pull/2596

AMP implementation: https://github.com/ampproject/amp-wp/pull/5924

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
@o-fernandez WDYT?

**Comment by spacedmonkey** [comment]
I like adding the link to the settings page next to activate. I did something similar with Unsplash. 

<img width="515" alt="Screenshot 2021-02-12 at 10 17 43" src="https://user-images.githubusercontent.com/237508/107756125-aa154f80-6d1b-11eb-9de7-44ff5568e8b2.png">

**Comment by o-fernandez** [comment]
I think this all sounds good. Why don't we copy the same implementation and just do it following the site kit approach?

**Comment by csossi** [comment]
Verified in QA
