### ISSUE TITLE
Design System: Input Variant

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6329]
## Feature Description

Now that the editor's getting redesigned (yay!) we're noticing some additions to the new designs that weren't sketched out as components in the design system that we originally based all of our work on. There are inputs in the editor that have a label (either text based or icon w/ aria-label) that are right aligned inside the input. 

## Additional Context

Screenshots of panels in[ figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=221%3A13978) as of Feb 11, 2021
![Screen Shot 2021-02-11 at 8.43.01 AM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/dc588b5a-b401-484f-96d6-390678389d8e)![Screen Shot 2021-02-11 at 8.42.47 AM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/9e2086c2-1ad2-41cb-99c0-89ccb7898b87)![Screen Shot 2021-02-11 at 8.40.49 AM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/e711f43e-de00-46db-b5d4-13639f8596be)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

- Input variant should be added to design system 
- Should have storybook 
- Any relevant tests
- Should have RTL version 
- Should be accessible 
- Should meet i18n requirements

## Implementation Brief

This can probably be a variant on the existing input.

**Comment by BrittanyIRL** [comment]
@barklund - any other variants I missed? I just went through figma and I'm not seeing anything centered? Screenshot/link if I missed them, please?

**Comment by barklund** [comment]
> @barklund - any other variants I missed? I just went through figma and I'm not seeing anything centered? Screenshot/link if I missed them, please?

There's the [search input in the element library](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=257%3A817). It's basically just an input with an icon prepended to the placeholder and nothing else special about it:
![Screen Shot 2021-02-11 at 23 51 28](https://user-images.githubusercontent.com/637548/107731473-12d0dd80-6cc4-11eb-9a03-acfc92add837.png)

But as I discussed with @miina elsewhere, we'd ideally be able to create this where we need it by just passing the icon along with the text as `placeholder` and then style the input centered with a `className` (so we can use S-C to style it). I don't think it requires a special variant, rather just the ability to customize existing variants.

**Comment by miina** [comment]
The search input has one more detail: when the input is active and has text in it, the icon is displayed on the left ([see the main component design](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3398%3A79991)):
![Screenshot 2021-02-12 at 09 59 03](https://user-images.githubusercontent.com/3294597/107743172-b5af4900-6d10-11eb-9c30-c17244b8e53a.png)

I'm guessing the same search input will be used [in the dashboard](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=1012%3A230254) as well?

**Comment by BrittanyIRL** [comment]
Cool! I have the search separate since it behaves differently, PR here: https://github.com/google/web-stories-wp/pull/5844 it's just taken a lot of back and forth because I keep getting my attention stolen 😝  

@samwhale is adding an input variant that allows icons: https://github.com/google/web-stories-wp/pull/6355

Thoughts welcome!

**Comment by samwhale** [comment]
Added a new ticket to track extra variants that are needed:
1. Unit
2. Number
3. Allow empty

https://github.com/google/web-stories-wp/issues/6414
