### ISSUE TITLE
Dashboard: admin notices not hidden

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#6330]
## Bug Description

If a WP core update is present, a message shows on all pages in the admin. However, the dashboard title covers this. See screenshot. 

## Expected Behaviour

Admin notices should be hidden on the dashboard

## Screenshots

![title](https://user-images.githubusercontent.com/237508/107672400-bef6d200-6c8c-11eb-8234-a2c840ff7d7b.png)

## Additional Context

- Plugin Version: 1.4.0
- WordPress Version: 5.6
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
I'm assuming we'll just want to make sure that this message is above anything on the dashboard but would like design input. Additionally, how should we handle cases where a banner is present? Should this wordpress message be converted into a banner of our own?  @samitron7

**Comment by swissspidy** [comment]
We hide these notices completely on the editor already. We should just hide them on the dashboard too.
