### ISSUE TITLE
Unable to click button after selecting element with prepublish

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6346]
## Bug Description

editor elements with buttons to click after getting sent to them by clicking on a warning in pre publish checklist is blocked. Found in bugbash by @littlemilkstudio 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
