### ISSUE TITLE
Dashboard: Create New Story Focus Color Off

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6347]
When the 'Create New Story' button is in focus on the side nav it is blue, it should be black. The button styles are getting overridden by default link handling in wordpress.

![Screen Shot 2021-02-11 at 12.44.56 PM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/8c2398ce-7022-4ad6-bf21-a9027a2cfe52)

**Comment by csossi** [comment]
Verified in QA
