### ISSUE TITLE
FTUE: Update arrow color

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6348]
## Bug Description

The arrow color in the main menu has been updated to `fg.secondary` in figma, currently they are white.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
