### ISSUE TITLE
Dashboard: Stories no longer preloaded in PHP

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6349]
## Bug Description

This is a regression. Return to preloading stories. 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
@spacedmonkey can you take a look at this? Nothing changed in the dashboard that could be affecting this as far as I see. private stories are missing from preload path in Dashboard.php - i have a sad lil PR here to fix that (https://github.com/google/web-stories-wp/pull/6356) but i'm drawing a blank on why this would have stopped working, feels php centered to me.

**Comment by swissspidy** [comment]
@BrittanyIRL You're right, it's because we now support private stories in the dashboard but the preloading hasn't been updated to reflect that. The PR looks correct to me.

**Comment by BrittanyIRL** [comment]
> @BrittanyIRL You're right, it's because we now support private stories in the dashboard but the preloading hasn't been updated to reflect that. The PR looks correct to me.

huh, when i added it in to the preloading i still wasn't seeing the preloaded stories come through but perhaps that's just my tiny amount of stories (recently reset my env).
