### ISSUE TITLE
Saved Style preview appears incorrectly

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6354]
## Bug Description

When I add a preformatted style of text to a page the preview of the style in the Saved Style panel appears oddly

## Steps to Reproduce

1. Add a preformatted text block to a story page
2. open the Saved Styles panel and observe the preview displayed there

## Screenshots

![Screen Shot 2021-02-11 at 2 13 12 PM](https://user-images.githubusercontent.com/58738530/107698578-bef1d480-6c82-11eb-8118-6ee9d620312b.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

Enforce using 12px font-size inside the style presets.

**Comment by BrittanyIRL** [comment]
@barklund - Feel like this might be something that is fixed with new designs getting implemented?

**Comment by barklund** [comment]
I'll let @miina review this one - she's way more familiar with this part of the codebase.

**Comment by BrittanyIRL** [comment]
thanks! happy to take it on if we still need to after redesign. Absolutely appreciate any insight!

**Comment by miina** [comment]
The new design should actually already be implemented for this part specifically.
The issue seems to come from the content of the style also considering the original font-size of the source text -- that should not be done since large font size won't really fit into the preview.

The saved style previews should probably use fixed font-size per Figma (12px), in this case, this should be an easy fix.

**Comment by BrittanyIRL** [comment]
> The new design should actually already be implemented for this part specifically.
> The issue seems to come from the content of the style also considering the original font-size of the source text -- that should not be done since large font size won't really fit into the preview.
> 
> The saved style previews should probably use fixed font-size per Figma (12px), in this case, this should be an easy fix.

thanks, miina!

**Comment by csossi** [comment]
Verified in QA
