### ISSUE TITLE
Bundler: SVG stroke/fill is not removed as expected

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6357]
## Bug Description

Storybook build does not replace fill/stroke with `currentColor` as the primary build does. This makes the Storybook build less reliable as a reference.

However, width/height **is** removed, so some SVGO plugins are running.

This SVG:

```svg
<svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M21 8.5V23.5" stroke="green" stroke-linecap="round" stroke-linejoin="round"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M12 14C11.1716 14 10.5 14.6716 10.5 15.5V16.5C10.5 17.3284 11.1716 18 12 18H17C17.8284 18 18.5 17.3284 18.5 16.5V15.5C18.5 14.6716 17.8284 14 17 14H12Z" fill="hotpink"/>
</svg>
```

Results in this list of icons:
![Screen Shot 2021-02-11 at 20 09 37](https://user-images.githubusercontent.com/637548/107719007-2fa9e880-6ca5-11eb-9c9c-d75da1cc6486.png)

With this source in place of the SVG:
```svg
<svg viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M21 8.5v15" stroke="green" stroke-linecap="round" stroke-linejoin="round"></path><path fill-rule="evenodd" clip-rule="evenodd" d="M12 14a1.5 1.5 0 00-1.5 1.5v1A1.5 1.5 0 0012 18h5a1.5 1.5 0 001.5-1.5v-1A1.5 1.5 0 0017 14h-5z" fill="#ff69b4"></path></svg>
```

Also, notice how the fill color name is normalized to a hex value, but the stroke is not.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
As per https://github.com/google/web-stories-wp/pull/6272#discussion_r574936829, it could be that the svgo config is not found in the root of the project for the storybook webpack config, which kinda makes sense.

Seems like we'd need to duplicate that config and pass it directly to the webpack config here:

https://github.com/google/web-stories-wp/blob/c9956a4aa83d970f43951e7d8f985bf6c470277e/.storybook/main.cjs#L50-L53

Something like this should work:

```js
config.module.rules.unshift({
  test: /\.svg$/,
  use: [
    {
      loader: '@svgr/webpack',
      options: {
        titleProp: true,
        svgoConfig: {
          plugins: [
            {
              removeViewBox: false,
              removeDimensions: true,
              convertColors: {
                currentColor: /\b(?!url|none)/i,
              },
            },
          ],
        },
      },
    },
    'url-loader',
    assetLoader,
  ],
});
```

----

> However, width/height is removed, so some SVGO plugins are running.

That's not SVGO, but SVGR itself. See https://react-svgr.com/docs/options/#dimensions

**Comment by swissspidy** [comment]
So I just took your SVG:

```svg
<svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M21 8.5V23.5" stroke="green" stroke-linecap="round" stroke-linejoin="round"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M12 14C11.1716 14 10.5 14.6716 10.5 15.5V16.5C10.5 17.3284 11.1716 18 12 18H17C17.8284 18 18.5 17.3284 18.5 16.5V15.5C18.5 14.6716 17.8284 14 17 14H12Z" fill="hotpink"/>
</svg>
```

And in the editor it is turned into this:

```svg
<svg viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M21 8.5v15" stroke="green" stroke-linecap="round" stroke-linejoin="round"></path><path fill-rule="evenodd" clip-rule="evenodd" d="M12 14a1.5 1.5 0 00-1.5 1.5v1A1.5 1.5 0 0012 18h5a1.5 1.5 0 001.5-1.5v-1A1.5 1.5 0 0017 14h-5z" fill="#ff69b4"></path></svg>
```

Which is identical to what you shared in you post:

```svg
<svg viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M21 8.5v15" stroke="green" stroke-linecap="round" stroke-linejoin="round"></path><path fill-rule="evenodd" clip-rule="evenodd" d="M12 14a1.5 1.5 0 00-1.5 1.5v1A1.5 1.5 0 0012 18h5a1.5 1.5 0 001.5-1.5v-1A1.5 1.5 0 0017 14h-5z" fill="#ff69b4"></path></svg>
```

Soo... it's not working at all?! 🤔 😩 

Only when I manually added the SVGO config to `webpack.config.cjs` and removed the `.svgo.yml` did it work...

But apparently the `currentColor` regex doesn't work as expected either.

**Comment by swissspidy** [comment]
OK #6361 should fix this... 🤞
