### ISSUE TITLE
Update carousel thumbnail page sizes

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6358]
## Feature Description

Update carousel thumbnail sizes to 36x54 and 40x60 respectively to have the proper page ratio (2:3).

[Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=327%3A10229).

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
