### ISSUE TITLE
Toggle Button should support three-state for "multi" values

### ISSUE THREAD

**Issue by dvoytenko** [GoogleForCreators/web-stories-wp#636]
Examples: "bold", "italic", "flip", etc - buttons.

**Comment by pbakaus** [comment]
what's an example for a multi value / three way toggle?

**Comment by dvoytenko** [comment]
Examples are above in the description. E.g. "bold" visually could show:
- on for all selected elements
- off for all selected elements
- multiple values are selected

This is low priority, I think, since we can survive for quite some time with "multiple" == "off". Or you can decide that we don't need it at all. I just called this out b/c I ran into some inconsistency in the code and cleaned it up.

**Comment by swissspidy** [comment]
Oh, you mean when you select multiple elements (one bold, one not), the toggle button should show some third state to indicate this?

**Comment by dvoytenko** [comment]
Yes. But the more i think of this, the lower the priority seems. I'll close this for now to avoid the distraction.
