### ISSUE TITLE
Stickers: Update template creation docs

### ISSUE THREAD

**Issue by dreamofabear** [GoogleForCreators/web-stories-wp#6363]
## Task Description

Once basic sticker support is implemented:
- [x] Do a dry-run of the template creation workflow with SVG stickers
- [x] Update `docs/external-template-creation.md` with step-by-step instructions

I'd be happy to guinea pig this too. 

/cc @littlemilkstudio

**Comment by maxyinger** [comment]
I'm happy to go through a dry run of adding a sticker into the codebase and adding that to a template with someone, or pair on the flow, or hand it off and be available for questions. @choumx @BrittanyIRL @swissspidy any preference?

**Comment by dreamofabear** [comment]
Looking good! Just did a partial dry run. 

Here are a couple things that I noticed (and probably should've pointed out earlier).

### 1. JSON conversion

After a new template is handed off from design, engineering will have to convert all SVG images to stickers in the story JSON. For example:

A SVG image:
```
{
  ...
  "resource": {
    "type": "image",
    "mimeType": "image/svg+xml",
    "creationDate": "2021-03-31T16:10:19",
    "src": "https://stories-new-wordpress-amp.pantheonsite.io/wp-content/uploads/2021/03/sam1.svg",
    "width": 175,
    "height": 295,
    "posterId": 0,
    "id": 16850,
    "title": "sam1",
    "alt": "sam1",
    "sizes": [],
    "local": false
  },
  "type": "image",
  ...
}
```

A sticker:
```
{
  ...
  "type": "sticker",
  ...
  "sticker": {
    "type": "foo-sticker"
  },
  ...
},  
```
And creation of `foo-sticker` involves committing a new React component and updating `src/edit-story/stickers/index.js`, per Max's instructions in #6905.

This seems like it would be a time consuming and error-prone process if done manually. We should write (or ask the template creation team to write) a Node.js script that automates this.

### 2. Stickers as code

All stickers are added as code vs. as standalone SVG files. This is nice since it means SVGs are automatically rendered inline in the output, but it also has a few downsides:

- The edit-story.js bundle is coupled to stickers (bundle size will increase with every SVG added)
- It's hard to preview the SVGs in the stickers directory (like we can do for `src/edit-story/icons/*.svg`)

**Comment by swissspidy** [comment]
> After a new template is handed off from design, engineering will have to convert all SVG images to stickers in the story JSON. For example:

IMO they should just add the sticker to the repo before creating the template. Way less friction. Especially since stickers and images might behave differently in the editor, so better to work directly with the sticker.

> The edit-story.js bundle is coupled to stickers (bundle size will increase with every SVG added)

They could/should be loaded lazily in a separate chunks.

Even if we use SVG files, they could be loaded as React components (like we do already for all icons), and be loaded that way.

> It's hard to preview the SVGs in the stickers directory

True. Plus harder for designers to submit new SVGs.

**Comment by BrittanyIRL** [comment]
Thanks for testing this out, @choumx 

I agree with Pascal - he types faster than me! Stickers should be prepped before creating new templates going forward.  

Previewing SVGs wasn't really a priority here when we did the discovery and mapped out the plan to get stickers available since we just want them to create templates. Maybe I'm misreading.  

For context of how we got here: https://github.com/google/web-stories-wp/issues/6586#issue-820208070 

We're updating the 8 existing templates next sprint and will go through the process of adding quite a few stickers then, so that might shed some light too on further enhancements.

**Comment by dreamofabear** [comment]
> IMO they should just add the sticker to the repo before creating the template.

That works, but it might be hard to find a specific sticker in the panel without grouping or searching functionality (e.g. with up to ~50 templates and several stickers per template). 

How might we make this easier?

**Comment by BrittanyIRL** [comment]
> How might we make this easier?

I think with this? https://github.com/google/web-stories-wp/issues/6033

**Comment by maxyinger** [comment]
> That works, but it might be hard to find a specific sticker in the panel without grouping or searching functionality (e.g. with up to ~50 templates and several stickers per template).
> How might we make this easier?

We could just have a naming convention and add a filter based on keys if necessary when we get there. For now can start with a naming convention and add to doc. something like:
```
sticker: {
  type: <template>-<pageNumber>-<descriptor>,
},
``` 


> It's hard to preview the SVGs in the stickers directory + harder for designers to submit new SVGs.

I'm personally not a fan of the svg loader. Kinda ruins all control over the svg. My main rational for not having it is easily disabling SMIL animations (depending on where you're viewing sticker like layers panel) & simple to remove `height` and `width` attributes on there.

Removing HxW on there Makes it so you don't need much if any logic to scale the svg and viewbox dictates ratio. Although this only really simplifies the display layer and we're explicitly setting HxW in the frames layer so the housekeepings already there and we can use this for the display layer too if we want 🤷 .
```
const SomeSticker = ({ style, enableSMIL }) => (
    <svg style={style}>
      <otherMarkup />
      {enableSMIL && <someSmilMarkup />}
    </svg>
);
```

If you don't see these for as much of a benefit as I do, we can look into using svg loader instead. I believe it will add some extra logic around altering the svg to our liking but does have its benefits.



>After a new template is handed off from design, engineering will have to convert all SVG images to stickers in the story JSON. For example:

> IMO they should just add the sticker to the repo before creating the template. Way less friction. Especially since stickers and images might behave differently in the editor, so better to work directly with the sticker.

Yeaup. we shouldn't have to touch the story json. Design should just have the non facing sticker button to use before they make the template, so they can insert it with a simple button when they need it.

> creation of foo-sticker involves committing a new React component and updating src/edit-story/stickers/index.js, per Max's instructions in #6905. This seems like it would be a time consuming and error-prone process if done manually. We should write (or ask the template creation team to write) a Node.js script that automates this.

I think it's gonna involve some sort of commiting code no matter what unless we change the implementation to treat it as media served from an endpoint (which I thought the downsides of were greater than the current proposed approach).

We could write a simple node script to dynamically generate the react components from an svg file at run time, but at that point I feel like we should just use the svg loader and alter the existing approach to just work with that. that being said, it does have the downsides I mentioned above. With that, I'm still open to it if we feel it addresses our priorities better.

**Comment by dreamofabear** [comment]
> We could just have a naming convention and add a filter based on keys if necessary when we get there.

Probably worth implementing a simple tag feature here. I.e. add string array of keywords to each sticker and add a search field in the sticker panel. Filter stickers that have at least one matching tag string in a space-delimited search query.

---

Note that a stickers-first workflow adds an additional handoff/step between eng and design, i.e.

1. Eng/design exports SVGs from Figma and commits them to codebase
2. Design authors templates in editor with new SVG stickers
3. Eng commits new template story JSON to codebase

But let's try it out for the first round of new templates and get feedback. Lack of searching/filtering stickers probably won't be a serious issue immediately.
