### ISSUE TITLE
Change safe zone color so it doesn't clash with snap guidelines

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#6366]

**Comment by o-fernandez** [comment]
@samitron7 can we add the new color we want to use here? If already in the specs, great, just want to make this ticket very easy to resolve.

**Comment by bmattb** [comment]
@samitron7 - need the colour specified in time for Monday sprint start :)

**Comment by bmattb** [comment]
closed via https://github.com/google/web-stories-wp/issues/6201
