### ISSUE TITLE
Safe zone should always be visible when moving/editing an element

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#6367]

**Comment by o-fernandez** [comment]
@samitron7 I think this is already meant to be, so it may be a bug that it doesn't always show or it goes away. Can you confirm? Maybe a dupe of https://github.com/google/web-stories-wp/issues/5134

**Comment by samitron7** [comment]
Yes, this ticket is a dupe of #5134.

**Comment by miina** [comment]
@o-fernandez One clarification: "should always be visible when moving/editing an element" -- does this mean that it should also be visible when in edit mode for an element, e.g. for text or media? Or is this just when moving/rotating/resizing?

**Comment by o-fernandez** [comment]
> @o-fernandez One clarification: "should always be visible when moving/editing an element" -- does this mean that it should also be visible when in edit mode for an element, e.g. for text or media? Or is this just when moving/rotating/resizing?

That's a good question, I think when editing text may be helpful as well, since I may type enough to add a new line that bleeds below the safe zone. But @samitron7 @choumx WDYT?

**Comment by csossi** [comment]
Verified in QA
