### ISSUE TITLE
Open the Safe Zone help center tooltip if unread and the user places element outside of the safe zone

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#6368]
### Description 

When a user places an element outside of the safe zone and has yet to read the safe zone ftue tip the help center should open if not already open and show the safe zone tip. Once the tip is read (so the first time the tip is open after going out of the safe zone) the help center shouldn't open to the tip on repeat placement outside of safe zone.

**Comment by bmattb** [comment]
@o-fernandez Some confirmation required:

Assumption - this case only applies when element is dragged, or positioned with the use of keyboard arrows, outside the safe zone

**Comment by o-fernandez** [comment]
So long as part of the element is positioned outside of the safe zone, this should trigger. The idea is that if a user is making the potential (and frequent) mistake of putting elements where they may get cropped, that they are aware of the possibility.

**Comment by BrittanyIRL** [comment]
Hey @o-fernandez I see that you added this to "ready for sprint" 😄  I'm curious where this is on the priority list with 1.6 efforts that we're prepping for. There's some questions off the bat about this, like is it triggered _every_ time something is put outside the safe zone? _how far_ outside the safe zone should trigger it? 

It's a gray area between FTUE and pre publish checklist and I am unable to properly point it. ~Unless this is a high priority it feels like this would be better grouped with v2 of FTUE or possibly a version of prepublish that would link a user to the FTUE tip about safe zones if the element is outside of the safe zone?~

I think we need to nail down use case/ux before eng can do this. 

**Edit** 
I see this under the 1.6 roadmap now! I have the same questions above about when this should happen and how many times 🙃

**Comment by o-fernandez** [comment]
To answer your questions @BrittanyIRL 

Q: is it triggered every time something is put outside the safe zone?
A: no, it would only be triggered if the tip around safe zone is still marked as unread, so only open it *if unread* and the user places the element outside the safe zone

Q: how far outside the safe zone? 
A: I'd just be aggressive and say even if just a tiny little bit we can trigger it. The point is for them to look at the Safe Zone explanation at least once. 

Q. FTUE vs. pre-publish
A: I hear you. The key thing here is to ensure people see the Safe Zone tip if they haven't already and are doing something potentially harmful. The pre-publish checklist is more difficult because a "check" for this is probably too aggressive, since people probably have good reasons to put some things partially outside the safe zone. But a one-time trigger to show the tooltip should be pretty harmless (I hope!)

**Comment by BrittanyIRL** [comment]
thank you! this is all really really helpful! 🔑

**Comment by BrittanyIRL** [comment]
I'm gonna bump this to a 5 to give a cushion for writing tests.

**Comment by csossi** [comment]
Verified in QA
