### ISSUE TITLE
FTUE: Update Tip 7 text

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6369]
Per bug bash feedback from @choumx and @o-fernandez  update `Scroll down to Swipe-up Link and enter...` to `Scroll down to Page Attachment and enter...` 

![Screen Shot 2021-02-12 at 11 43 14 AM](https://user-images.githubusercontent.com/10720454/107809043-be5f4980-6d27-11eb-9eab-edbe94f5c46f.png)

**Comment by swissspidy** [comment]
"Scroll down to ..." is not really inclusive to screen reader users.

What about "Navigate to ..."?

**Comment by BrittanyIRL** [comment]
Fine by me! @o-fernandez  You good with that?

**Comment by BrittanyIRL** [comment]
![Screen Shot 2021-02-12 at 12 28 27 PM](https://user-images.githubusercontent.com/10720454/107813575-d5089f00-6d2d-11eb-9ccb-65017946692e.png)

i think 'Navigate to Page Attachment and enter...' makes the most sense because that is what the section is called on the design tab.

**Comment by o-fernandez** [comment]
Yeah, that sounds good. "Navigate to Page Attachment and enter..."
