### ISSUE TITLE
Change "Cover Image" to "Poster image" in the Document Panel

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#6370]
## Bug Description

Our current terminology of "Cover Image" doesn't match the overall documentation in Web Stories that use "Poster image" for this field. We should change the UI to say Poster image. (noticed the casing)
![image](https://user-images.githubusercontent.com/13389997/107810684-105d9a80-6d3b-11eb-899f-97537f796856.png)

Also, make "Required" have capital R. 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
