### ISSUE TITLE
Redesign: Element hover/droptarget frames

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6378]
## Feature Description

Update element hover and droptarget frames based on [Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=5646%3A2).

- [x] Update droptarget frames for background, media, and shapes (note how it resembles the selection state for the background) - and make sure they also perform correctly for general hover
- [x] Update text box frame used for hover

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
