### ISSUE TITLE
Redesign: Update play/stop icons on video element

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6380]
## Feature Description

When a video element is on canvas and selected, it can be played and stopped. Update the icons for this in the video element controls to the newest in [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3441%3A80829) using design system components.

In these extraordinary circumstances, the design system icons will be scaled up to 72x72px rather than used at their regular scale of 32x32px.

If the icons are not already imported into the design system, make sure to do so.

Also consider contrast for darker videos.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
