### ISSUE TITLE
Move keyboard icon to left side

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6381]
## Feature Description

In the current zoom implementation in #4022, the new icons haven't been merged in yet. When this happens, the keyboard icon should be moved to the left side along the help center toggle button to make space for everything.

[Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=327%3A10229)

![Screen Shot 2021-02-12 at 17 28 50](https://user-images.githubusercontent.com/637548/107829497-d949b200-6d57-11eb-88b3-7132bff4f845.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
