### ISSUE TITLE
Limit carousel page count to 10 pages

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6382]
## Feature Description

In the current zoom implementation in #4022, the carousel layout has been updated radically. In this PR, the following restriction should be added before merge:

* [ ] Limit the number of pages possible in the carousel to max 10

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by rushatgabhane** [comment]
Hi, I would like to take this issue.

**Comment by miina** [comment]
@rushatgabhane Sorry for the delay in answering and thanks for the interest. Feel free to proceed!

**Comment by Yash621** [comment]
@miina can i work on this ?

**Comment by miina** [comment]
@Yash621 Let me confirm quickly if this is still relevant -- otherwise, definitely. Will let you know ASAP.

**Comment by Yash621** [comment]
Sure! Thanks :)

**Comment by miina** [comment]
@Yash621 Looks like this issue is not relevant anymore due to some UX changes that happened meanwhile since opening it.

Closing as irrelevant for now.
