### ISSUE TITLE
Disable automatic drop targeting by shortcut

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6383]
## Feature Description

Per user feedback, it would be nice to be able to place images on top of each other without them dropping into each other because of the automatic drop targeting currently in function.

* [ ] Disable drop targeting by shortcut: <kbd>Cmd</kbd> on Mac, <kbd>Win</kbd> on Windows.
* [ ] Add description of shortcut to the list of shortcuts (by mentioning it under "disable snapping" as per below design)

![Screen Shot 2021-02-12 at 17 35 16](https://user-images.githubusercontent.com/637548/107829918-b370dd00-6d58-11eb-904e-8bd36bea1202.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
