### ISSUE TITLE
Redesign: Keyboard shortcuts dialog

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6385]
## Feature Description

Update keyboard shortcut dialog based on [Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=361%3A340).

- [x] Update dialog content as per design
- [x] Update dialog placement and background as per design
- [x] Make sure dialog scrolls correctly on a smaller viewport

| Current design | New large viewport | New small viewport |
|-|-|-|
| ![Screen Shot 2021-02-12 at 17 38 46](https://user-images.githubusercontent.com/637548/107830378-a7d1e600-6d59-11eb-8ebc-53983936fd1e.png) | ![Screen Shot 2021-02-12 at 17 41 44](https://user-images.githubusercontent.com/637548/107830381-a99ba980-6d59-11eb-839d-5713476f3263.png) | ![Screen Shot 2021-02-12 at 17 42 01](https://user-images.githubusercontent.com/637548/107830390-ab656d00-6d59-11eb-96ec-c0cd92109d66.png) |

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Some cutoff along right edge. Seeing this on PC only (looked fine in Mac/Chrome)
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/79559994-3274-4c87-9f8c-aa889d402bfe)

**Comment by barklund** [comment]
> Some cutoff along right edge. Seeing this on PC only (looked fine in Mac/Chrome)

Thank you for this - hadn't considered that. Have brought it up with UX!

**Comment by barklund** [comment]
Awaiting UX decision by @samitron7 in [this thread](https://xwp.slack.com/archives/C01ESBB8ZN1/p1613673816304100).

**Comment by samitron7** [comment]
@barklund If we reduce the white spacing inside the button, I think it'll fit. Let me know if this works [Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=361%3A340)

![Screen Shot 2021-02-18 at 9 38 34 PM](https://user-images.githubusercontent.com/10889431/108462593-b6c10880-7231-11eb-88fa-eee18d82671e.png)

**Comment by barklund** [comment]
> @barklund If we reduce the white spacing inside the button, I think it'll fit. Let me know if this works [Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=361%3A340)


This has now been implemented - back to you, @csossi!

| Mac | Windows |
|-|-|
| ![Screen Shot 2021-02-19 at 17 08 29](https://user-images.githubusercontent.com/637548/108576087-488c4c80-72ea-11eb-82bf-34a37b0670fa.png) | ![Screen Shot 2021-02-19 at 17 07 57](https://user-images.githubusercontent.com/637548/108576090-4aeea680-72ea-11eb-9f6f-a9ff1742c7c8.png) |

**Comment by csossi** [comment]
Verified in QA
