### ISSUE TITLE
Update font family to Google Sans

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6386]
## Feature Description

Throughout the editor (and dashboard and design system if applicable), update the font family to _Google Sans_ rather than _Roboto_.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
GIF categories still appearing as Roboto:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/ce93a865-04b7-4e0c-8c3b-1f988e3cfbe7)

Image categories appearing as Roboto:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/ef9a0d2e-52c1-4342-81f1-0bab01580981)

**Comment by BrittanyIRL** [comment]
@csossi - the fonts for the pills are getting updated here: https://github.com/google/web-stories-wp/issues/7052 

Max and Samuel split that work to avoid merge conflicts. I'm sorry for not communicating that to you.

**Comment by csossi** [comment]
Verified in QA - thanks for the update, @BrittanyIRL
