### ISSUE TITLE
Media: Improve Blob Memory Management

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6400]
## Feature Description

[As per MDN:](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL)

Each time you call `createObjectURL()`, a new object URL is created, even if you've already created one for the same object. Each of these must be released by calling `URL.revokeObjectURL()` when you no longer need them.

Browsers will release object URLs automatically when the document is unloaded; however, for optimal performance and memory usage, if there are safe times when you can explicitly unload them, you should do so.

We currently use `createObjectURL()` in two places, yet we don't use `revokeObjectURL`:

* ~`getResourceFromLocalFile()`~ this was addressed by #6088
* `EditorSettings`

That means there's room for improvement!

~Interestingly, the object URLs are no longer needed once the image has been loaded by the browser. This means we can set up the image's load event handler to release these blobs by using `URL.revokeObjectURL()` method and passing in the object URL string as specified by `img.src`.~

~In addition to that, we should cache calls to `createObjectURL` so that we don't call it twice on the same image. Basically like https://github.com/WordPress/gutenberg/tree/master/packages/blob does. This is going to be super simple.~

^ This was addressed by #6088

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
While testing #8770 I noticed that blobs of video posters are still around even after successful upload, as can be confirmed via the "Sources" tab in dev tools. So there's still some room for improvement.

**Comment by spacedmonkey** [comment]
We call removeBlob in finishUploading

https://github.com/google/web-stories-wp/blob/c3a3b997babddaae9a87ae6c47c8fbd1e65f9a47/packages/story-editor/src/app/media/utils/useMediaUploadQueue/reducer.js#L113-L137


We could also call it in cancelUploading, if a transcode / upload fails.
https://github.com/google/web-stories-wp/blob/c3a3b997babddaae9a87ae6c47c8fbd1e65f9a47/packages/story-editor/src/app/media/utils/useMediaUploadQueue/reducer.js#L148-L160

**Comment by swissspidy** [comment]
`revokeBlob` is also called in `replacePlaceholderResource `, FWIW:

https://github.com/google/web-stories-wp/blob/c6f0b2ba660662e8bdeb22b08cde858403459887/packages/story-editor/src/app/media/utils/useMediaUploadQueue/reducer.js#L287-L299

In my case the lingering blobs were for successful uploads, not cancelled ones. Although adding that there might make sense too.

In short, this needs some testing before it's actionable.

**Comment by spacedmonkey** [comment]
The idea to also was on cancelled uploads, was yours Pascal. I remember you mentioning, but I can't find the PR where you did that. 

 Question about these lines 

```
 if (queueItem.resource.src !== resource.src) { 
     revokeBlob(queueItem.resource.src); 
     revokeBlob(queueItem.resource.poster); 
   } 
```

Would it be better if we did this?

```
if (isBlobURL(queueItem.resource.src)) { 
     revokeBlob(queueItem.resource.src); 
} 
if (isBlobURL(queueItem.resource.poster)) { 
     revokeBlob(queueItem.resource.poster); 
} 
```

**Comment by swissspidy** [comment]
`revokeBlob` already checks whether the blob URL is created by the editor and in the blob cache, so adding an `isBlobURL` check would be redundant.

**Comment by spacedmonkey** [comment]
I did some testing and I am seeing the blob in the sources tab. But even after calling `window.URL.revokeObjectURL` in the console, I do not see the blob disappear. We may not have a problem here.
