### ISSUE TITLE
Edge case: disabled button text disappears 

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6405]
## Bug Description

If a button is enabled and clicked and becomes disabled the text will disappear. 
![button disable focus old.gif](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/1195856b-ed17-4e30-a300-1a5818247c0a)

## Expected Behaviour

Text should remain visible. 

## Steps to Reproduce

Go to dashboard -> settings and update any input, hit save have your cursor stay on the button. Text will disappear. 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
