### ISSUE TITLE
Dashboard Redesign: Update Settings Dropdown 

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6406]
Update Settings Dropdown to new designs. 
Skipped on initial pass due to hiccup with popup component not being prepared for measuring vertical scroll. 

Old
![Screen Shot 2021-02-16 at 10.33.35 AM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/69de72c5-23f9-41e3-a011-52f382e7fe4a)

New

![settings update](https://user-images.githubusercontent.com/10720454/108100124-be6e8a80-7042-11eb-94b6-ade09f592b34.gif)

**Comment by BrittanyIRL** [comment]
@csossi - there's really specific QA steps to help on regression testing in the PR if you want to look there for more details as needed.

**Comment by csossi** [comment]
Verified in QA
