### ISSUE TITLE
Release: 1.4.0

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6408]
- [x] Update readme (#6409)
- [x] Create release candidate: https://github.com/google/web-stories-wp/releases/tag/v1.4.0-rc.1
- [x] Smoke testing
- [ ] Create stable release
  - [ ] Approve WordPress release in email notification
- [ ] Communicate widely!

**Comment by bmattb** [comment]
@swissspidy Can we close this?
