### ISSUE TITLE
Image Link not brought over when dropping into target

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#641]
## Bug Description

Image link disappears when dropping into a target.

Note: Might be good to confirm with @samitron7 to understand the behavior if drop target/dropped element has a link.

## Steps to Reproduce

1. Add a shape.
2. Create an Image
3. Add a link.
4. Drop the image into the shape.
5. The link wasn't brought over.

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by dvoytenko** [comment]
/to @pbakaus and @samitron7 to confirm the behavior. IMHO it could go either way.

**Comment by pbakaus** [comment]
No strong preference, but I'm leaning towards proactive preservation of data, so transferring the link to the shape seems reasonable.

**Comment by dvoytenko** [comment]
/to @wassgha . In this case we'll have to repeat the one/two-tap calculations.

**Comment by samitron7** [comment]
Figma flow for link preservation can be found [here](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=9467%3A0)

**Comment by miina** [comment]
There were no issues left in the Spring backlog so started working on this FYI @barklund @bmattb

**Comment by csossi** [comment]
Verified in QA
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/962e3cea-1e94-4d40-a2d6-411af7563154)
