### ISSUE TITLE
Design System: Input Variants - Number & Unit

### ISSUE THREAD

**Issue by samwhale** [GoogleForCreators/web-stories-wp#6414]
## Feature Description

Add remaining input variants. 
[Designs](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3397%3A800)

### Unit
Sometimes inputs will have a unit suffixed (or technically prefixed if that's a thing in some languages) but it's removed on data entry (focus). This happens for `%` for opacity, `°` (degree) for rotation, and `ms` for durations (in the animation panel).

The current implementation calls this `symbol`, but I tend to think that `unit` (default `''`) might be a better name

### Number
Numbers are a bit special as we do several magic things today to make them easier to work with.

* Only parse the input to a number on blur, enter or arrow key (allow invalid input until then) and only then submit up the chain
* ⬆️   and ⬇️   changes the value 1 up or down
* Some inputs will allow negative numbers, others won't

We have this as a completely separate input field type (`<Numeric />` rather than `<Text />`) with the property `canBeNegative` (default `false`) today, but I think something like `isNumeric` and `canBeNegative` (both default `false`) works better.

### Allow empty
Some inputs revert to their previous value if emptied and blurred, while others are allowed to be empty on blur and thus submit `null` up the chain.

We currently have this as `canBeEmpty` (default `false`).

### Float or integer
We actually also have a boolean flag for telling whether only integers or also floats are allowed. Currently this is called `float`, but `isFloat` (default `false`) is probably better aligned with existing props.

## Alternatives Considered

n/a

## Additional Context

The editor already has this built in to the input it is using. We need to add these variants to the input in the design system: https://github.com/google/web-stories-wp/pull/6355#issuecomment-780749936

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
Please see the existing implementation in [`<Numeric />`](https://github.com/google/web-stories-wp/blob/9a31a26e740265b8dc27ca89448df4f0ad3b433c/assets/src/edit-story/components/form/numeric.js) and steal all that you can from there - no need to reinvent if not necessary 🎉

**Comment by samwhale** [comment]
This can be UAT'd in storybook on staging: https://google.github.io/web-stories-wp/storybook/?path=/story/designsystem-components-input--default-numeric
