### ISSUE TITLE
FTUE: Add Link Text Update

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6418]
## Feature Description

Text has been updated on tip #6 (Add links to design elements) to be `Add Links to Story elements`
Please make this update to text on the main menu for this tip. (replace 'design' with 'Story')

![Screen Shot 2021-02-17 at 3.03.00 PM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/ace7d2c5-269a-4b95-bbbe-46fd29c9edec)

**Comment by csossi** [comment]
Verified in QA
