### ISSUE TITLE
Page Advancement auto-advance slider missing

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#6432]
## Bug Description

Default page duration used to have a blue slider bar that it is no longer there. 

## Expected Behaviour

There should be a slider bar when on auto-advance to indicate another method for changing the page duration.

## Steps to Reproduce

Select Auto under Page Advancement. 
Notice missing slider bar.

## Screenshots

![image](https://user-images.githubusercontent.com/66372350/108402104-18aa4f80-71eb-11eb-8ad3-7a886f994392.png)

## Additional Context

- Plugin Version: 1.4.0
- WordPress Version: 5.6.1
- Operating System: macOS
- Browser: Chrome, Safari, MS Edge, Firefox

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
Irrelevant due to new design.
