### ISSUE TITLE
Dashboard: Filter Discrepancy based on search

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6433]
## Bug Description

Currently, we get a `Private` story filter on the dashboard header if there are any private stories present for the user. Sometimes, we'll have a search term in the dashboard that results in 0 private stories. Currently, when this is the case the `Private` filter disappears. However, when a search term results in 0 drafts or published stories those filters stay visible and are simply disabled. I feel like there should be consistency? 

## Expected Behaviour

Personally, I feel like the filter functionality should be consistent. So just disabling the private filter when there are 0 and private stories are readable. 

## Steps to Reproduce

Search on the dashboard for something that will garner no private results.

## Screenshots

![Screen Shot 2021-02-18 at 1.09.49 PM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/3eeb14a4-91a8-4b7c-9424-ca206b331579)
![Screen Shot 2021-02-18 at 1.09.42 PM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/eb705355-c361-44d6-ba34-53c26aaff5d2)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
(To revisit after https://github.com/google/web-stories-wp/pull/8598 is merged)

**Comment by BrittanyIRL** [comment]
This was fixed by Jonny here: https://github.com/google/web-stories-wp/pull/8976  and here: https://github.com/google/web-stories-wp/pull/8598 so there is no longer a discrepancy on search. 

@csossi this can all be confirmed in staging.

**Comment by csossi** [comment]
Verified in QA
