### ISSUE TITLE
Design System: Distinguish active toggle state on buttons

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6435]
Some buttons can be toggled 'on' or 'off'. Let's add a `isToggled` prop to our `Button` in the design system (default is `false`) and add appropriate styling. 

Toggled on secondary button receives `bg.secondary` 

@samitron7 Can you add in a toggled on state to the buttons in figma?

**Comment by barklund** [comment]
This was implemented in #6491.
