### ISSUE TITLE
FTUE: Help Button Should be `Tertiary`

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6436]
## Feature Description

Currently the toggle button for the 'Help' FTUE display is using the secondary variant, this causes a purple bg flash on focus. We do not want this purple flash and so should use the tertiary variant instead. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

No purple bg on active state of help toggle.

**Comment by csossi** [comment]
Verified in QA
