### ISSUE TITLE
Dashboard: Update Empty State Views

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6437]
## Feature Description

When users have no stories yet we should help them navigate Web Stories a little more. 
Add new variants to empty views in dashboard: 

1. All Stories 
- Display new desert svg (linked here) 
- Update text below desert to `Create Stories readers love.` 
- Two buttons (primary, secondary) - 'Create Story with template' (goes to explore templates on dashboard) and 'Create Story from scratch' (goes to editor) 

2. If somehow the user navigates to 'Drafts' or 'Published' w/ no stories created (perhaps this is new UX? @samitron7 ) 
- Same desert svg as all stories 
- Text displayed is `You have no Drafts` or `You have no Published stories` 
- No buttons 

Figma Designs: https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=6113%3A471585

## Alternatives Considered

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

- Updated empty messages and view to figma: 
(Feb 18, 2021)
![Screen Shot 2021-02-18 at 3.27.41 PM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/06683b8c-9819-486b-861c-6e47670e0979)
![Screen Shot 2021-02-18 at 3.27.29 PM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/d6e3a4f8-d408-490f-b276-f88c46f65563)

## Implementation Brief

- Update relevant empty view tests in dashboard/karma 
- New empty views present

![desert.svg](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/3183a69f-1c3f-465c-a9de-cfb866771d0a)

**Comment by BrittanyIRL** [comment]
@embarks let's hold on this until we get the thumbs up from @samitron7 about designs being done, per slack convo.

**Comment by BrittanyIRL** [comment]
Design update: https://user-images.githubusercontent.com/10720454/109994664-c2e5a500-7cca-11eb-90d2-325245cad3bc.png

**Comment by csossi** [comment]
Verified in QA
