### ISSUE TITLE
How can we use Web Stories editor for non WordPress website

### ISSUE THREAD

**Issue by santoshgistto** [GoogleForCreators/web-stories-wp#6440]
## Question
how can we use web stories editor for non wordpress website (react based) ?

## Documentation says 
>Whitelabel: The editor is written from scratch as a modern React codebase, with only thin layers (usually REST endpoints) connecting it to the underlying CMS. This careful design makes it possible to quickly port the editor to subsequent CMS’, beyond WordPress.
Ref: https://github.com/google/web-stories-wp/blob/main/docs/architecture.md
## Help
Is there any documentation to follow or any help will be appreciated

**Comment by swissspidy** [comment]
Hi there,

Thanks for reaching out.

While the editor is purely React written in a mostly platform-agnostic way, it is not yet at a point where you could simply install some npm packages and get your own standalone editor. Thus there's no documentation that guides developers from A-Z on how to adapt the code base. It's not an immediate priority at this moment to streamline this.

However, feel free to poke around the existing source code and use and adapt it to your needs. It's all open source for exactly this reason :-)

**Comment by ruskid** [comment]
Agree, it's not easy at all. How can I install google/web-stories-wp? and extend the editor?

I don't want to copy over the components

**Comment by swissspidy** [comment]
@ruskid We're actively working on decoupling the editor from WordPress and eventually making the relevant packages available via npm. Until then you'd have to resort to forking the repository, copying over components, sylinking, etc. as you see fit (all while adhering to the license of course)

**Comment by pietrop** [comment]
>@ruskid We're actively working on decoupling the editor from WordPress and eventually making the relevant packages available via npm. Until then you'd have to resort to forking the repository, copying over components, sylinking, etc. as you see fit (all while adhering to the license of course)

@swissspidy  was there any progress being made on this?

**Comment by swissspidy** [comment]
Yes. Please check out https://github.com/GoogleForCreators/web-stories-wp/blob/main/docs/third-party-integration/story-editor/getting-started.md for more information on how to achieve this. All the relevant packages are [published on npm](https://www.npmjs.com/org/googleforcreators) and updated regularly.

**Comment by pietrop** [comment]
> Yes. Please check out https://github.com/GoogleForCreators/web-stories-wp/blob/main/docs/third-party-integration/story-editor/getting-started.md for more information on how to achieve this. All the relevant packages are [published on npm](https://www.npmjs.com/org/googleforcreators) and updated regularly.

Awesome, thanks! 🙏

**Comment by pietrop** [comment]
There are two instructions 
- [minimal setup guide](https://github.com/GoogleForCreators/web-stories-wp/blob/main/docs/third-party-integration/story-editor/getting-started.md#minimal-setup-guide)
- [standalone tutorial](https://github.com/GoogleForCreators/web-stories-wp/blob/main/docs/third-party-integration/story-editor/tutorial.md#step-1-setting-up-the-editor-with-minimum-config)

Unless I am missing something, they seem to describe the same thing? how to use the editor in a CRA. But they recommend installing different packages.
```diff
- npm install @googleforcreators/story-editor @googleforcreators/element-library @googleforcreators/elements
+ npm install @googleforcreators/story-editor @googleforcreators/design-system @googleforcreators/migration @googleforcreators/elements @googleforcreators/element-library
```

I was wondering which instructions should I follow?

I tried both in a CRA, and in [Vite](https://vitejs.dev/) and I get this "could not resolve error" when importing the `Editor` example component into `App.jsx`.

```
✘ [ERROR] Could not resolve "../../../node_modules/date-fns/locale/_lib/buildLocalizeFn/index.js"

    node_modules/@googleforcreators/date/dist-module/getOptions.js:1:56:
      1 │ ...port a from"../../../node_modules/date-fns/locale/_lib/buildLocalize...
        ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

<details> <summary>Full error message</summary>

```
✘ [ERROR] Could not resolve "../../../node_modules/date-fns/locale/_lib/buildLocalizeFn/index.js"

    node_modules/@googleforcreators/date/dist-module/getOptions.js:1:56:
      1 │ ...port a from"../../../node_modules/date-fns/locale/_lib/buildLocalize...
        ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "../node_modules/react-color/lib/components/common/index.js"

    node_modules/@googleforcreators/story-editor/dist-module/components/colorPicker/currentColorPicker.js:1:515:
      1 │ ...()=>import("../node_modules/react-color/lib/components/common/index....
        ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "../node_modules/react-color/lib/components/common/index.js"

    node_modules/@googleforcreators/story-editor/dist-module/components/colorPicker/editablePreview.js:1:389:
      1 │ ...()=>import("../node_modules/react-color/lib/components/common/index....
        ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

11:47:38 PM [vite] error while updating dependencies:
Error: Build failed with 3 errors:
node_modules/@googleforcreators/date/dist-module/getOptions.js:1:56: ERROR: Could not resolve "../../../node_modules/date-fns/locale/_lib/buildLocalizeFn/index.js"
node_modules/@googleforcreators/story-editor/dist-module/components/colorPicker/currentColorPicker.js:1:515: ERROR: Could not resolve "../node_modules/react-color/lib/components/common/index.js"
node_modules/@googleforcreators/story-editor/dist-module/components/colorPicker/editablePreview.js:1:389: ERROR: Could not resolve "../node_modules/react-color/lib/components/common/index.js"
    at failureErrorWithLog (/Users/pietropassarelli/CODE/vite-gws-editor-test/node_modules/esbuild/lib/main.js:1604:15)
    at /Users/pietropassarelli/CODE/vite-gws-editor-test/node_modules/esbuild/lib/main.js:1056:28
    at runOnEndCallbacks (/Users/pietropassarelli/CODE/vite-gws-editor-test/node_modules/esbuild/lib/main.js:1476:61)
    at buildResponseToResult (/Users/pietropassarelli/CODE/vite-gws-editor-test/node_modules/esbuild/lib/main.js:1054:7)
    at /Users/pietropassarelli/CODE/vite-gws-editor-test/node_modules/esbuild/lib/main.js:1166:14
    at responseCallbacks.<computed> (/Users/pietropassarelli/CODE/vite-gws-editor-test/node_modules/esbuild/lib/main.js:701:9)
    at handleIncomingPacket (/Users/pietropassarelli/CODE/vite-gws-editor-test/node_modules/esbuild/lib/main.js:756:9)
    at Socket.readFromStdout (/Users/pietropassarelli/CODE/vite-gws-editor-test/node_modules/esbuild/lib/main.js:677:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
```

</details>

Any 💡 ? has anyone seen this before? Is it a probl with CRA/Vite or with these modules?

**Comment by swissspidy** [comment]
Looks like something is not right with the latest versions of our packages. I'll look into it.

**Comment by pietrop** [comment]
That's great thanks, I see the version is `"@googleforcreators/output": "^0.1.202212191259",` 
In the meanwhile, how do I identify an earlier version that I could try out?

**Comment by swissspidy** [comment]
You can see all the earlier versions on npm

**Comment by pietrop** [comment]
ok @swissspidy it's still not working, I've raised it as a separate issue, and provided as much context as I can and a sample repo to reproduce https://github.com/GoogleForCreators/web-stories-wp/issues/12965

**Comment by desis123** [comment]
> ok @swissspidy it's still not working, I've raised it as a separate issue, and provided as much context as I can as well as a sample repo to reproduce #12965

It's working, Just downgrade the react and react-dom to version 17 and also "@testing-library/react": "^12.0.0", testing to version 12 .
