### ISSUE TITLE
Drop Targets: Outline of the selected element visible even if not a target

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#645]
## Bug Description

When drop targets are displayed on a Page with a note that drop targets have blue outline around them, the selected element displays the blue outline regardless of being a drop target or not.

## Expected Behaviour

Only drop targets should have blue outline when dragging.

## Steps to Reproduce

1. Add a Text block.
2. Select the Text block.
3. Start dragging an Image from the Media Library onto the Page.
4. See the blue outline around the Text (which is not a drop target).
 

## Screenshots
![deceiving-outline](https://user-images.githubusercontent.com/3294597/77050293-d7e9fb00-69c9-11ea-905a-c8b6584f33a2.gif)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@jauyong Would be good to confirm this with UX.

**Comment by wassgha** [comment]
This is alright because the background is always a drop target but we can recycle this issue to implement drop targets on the background element (needs to constantly keep one empty element as the background)

**Comment by miina** [comment]
> This is alright because the background is always a drop target but we can recycle this issue to implement drop targets on the background element (needs to constantly keep one empty element as the background)

Note that this issue is about the selected element having a blue outline even if it's not a target, not related to background :)

**Comment by miina** [comment]
As mentioned in https://github.com/google/web-stories-wp/pull/687#issuecomment-602480118 then this still needs looking into.

When a Text element is selected and media is dragged from the Media Library, the Text element has blue line around it due to selection. Should the selection be hidden while dragging?

cc @pbakaus @samitron7

**Comment by wassgha** [comment]
Hey @miina the blue box is part of the selection UI so as a user I wouldn't expect it to disappear with drop targets because that would make me think I lost my selection (this is especially true in the case of a text element which does not support drop targets) so this is expected behavior.

**Comment by miina** [comment]
When testing with one image and one Text box, I did find having the blue outline (even though selection) around the Text box unexpected. E.g. if an Image is first selected, I'd also expect it to show just the drop target blue outline around the image, not the selection -- it's more consistent this way. However, might be just me then.

Will close this for now then assuming it's expected to mix selection + drop target outline.
