### ISSUE TITLE
Redesign: Color Input

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#6456]
## Feature Description

- [ ] Move the color input from the editor codebase to the design system
- [ ] Adjust the style
- [ ] Update hex parsing logic
- [ ] Add a story/stories

See [Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=987%3A2)

## Additional Context
<img width="841" alt="Screenshot 2021-02-17 at 12 35 27" src="https://user-images.githubusercontent.com/3294597/108192187-407ab400-7114-11eb-85e8-cb2ef751a49e.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
