### ISSUE TITLE
Redesign: Checkbox variant

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#6458]
## Feature Description

- [ ] Add a checkbox variant that allows customizing which side the labels are positioned
- [ ] Update storybook

See [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3483%3A385)

## Additional Context
<img width="443" alt="Screenshot 2021-02-17 at 12 12 13" src="https://user-images.githubusercontent.com/3294597/108189479-14116880-7111-11eb-8382-6f814e6cd846.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
The label is already not part of the checkbox and can be styled any way you want, so there's no issue to fix here.
