### ISSUE TITLE
Redesign: Media Picker

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#6459]
## Feature Description
See [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=5850%3A460)

- [ ] Move the current Media picker from the editor codebase to design system
- [ ] If empty use the default landscape image
- [ ] Add circle and square variants
- [ ] Add stories

NB! Ignore the "Manage" link for now.

## Additional Context

<img width="541" alt="Screenshot 2021-02-22 at 11 37 16" src="https://user-images.githubusercontent.com/3294597/108689900-f752a780-74f9-11eb-828d-ca0e92d4e703.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Does this make sense to live in the design system or should it be only in the editor?

https://github.com/google/web-stories-wp/blob/main/docs/design-system.md#what-goes-in-the-design-system

**Comment by miina** [comment]
> Does this make sense to live in the design system or should it be only in the editor?

Hm, it seems like something that's easily generalized. So far we have been adding components into the design-system that are used only in the editor but can be generalized and are used in multiple places. This also makes it easier to replace items in the editor as needed.
@barklund WDYT? E.g. currently we've added the hex input, slider, lock toggle (and possibly some other components I'm missing) to the design-system even though these are only used in the editor.

**Comment by barklund** [comment]
> > Does this make sense to live in the design system or should it be only in the editor?
> 
> Currently we've added the hex input, slider, lock toggle (and possibly some other components I'm missing) to the design-system even though these are only used in the editor.

Yeah, I like to put some generic components in there, even though they're (currently) only used in the editor. Some could be moved to the editor-only codebase, but I don't see a strong need for this. As long as we tree-shake only the components we need (so this code won't end up in the dashboard if it doesn't need it), I'm good with this.
