### ISSUE TITLE
Links: Restricted/safe zones

### ISSUE THREAD

**Issue by wassgha** [GoogleForCreators/web-stories-wp#646]
Part of #253 

- [ ] Implement visual aid for safe/prohibited zones where links can't be dragged.
- [ ] Make sure safe zones and 1-tap/2-tap areas respect transforms (more specifically rotation)

**Comment by swissspidy** [comment]
> Make sure safe zones and 1-tap/2-tap areas respect transforms (more specifically rotation)

See also #633
