### ISSUE TITLE
Redesign: Update no-selection "panel"

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#6460]
## Feature Description
See [Figma ](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=1799%3A48842)

- [ ] Update the sizing
- [ ] Update typography

## Additional Context

![Screenshot 2021-02-22 at 11 55 50](https://user-images.githubusercontent.com/3294597/108692150-8cef3680-74fc-11eb-8923-75ff4193875b.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
