### ISSUE TITLE
Redesign: Update page background panel

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#6461]
## Feature Description
See [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3399%3A78544)

- [x] Merge with page background size position
- [x] Update title
- [x] Update toggles for media bg
- [x] Update media display for media bg
- [x] Update color for shape bg

## Additional Context
![Screenshot 2021-02-22 at 11 59 40](https://user-images.githubusercontent.com/3294597/108692586-16066d80-74fd-11eb-97d9-cc079a260560.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
