### ISSUE TITLE
Redesign: Update background size position panel

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#6462]
## Feature Description
See [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3399%3A78544)

- [ ] Update title
- [ ] Update media display
- [ ] Update toggles
- [ ] Add tooltips

## Additional Context
![Screenshot 2021-02-22 at 11 59 40](https://user-images.githubusercontent.com/3294597/108693787-89f54580-74fe-11eb-8c14-d223333a8917.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
Closing this ticket as we are merging with #6461
