### ISSUE TITLE
Redesign: Update background filter panel

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#6463]
## Feature Description
See [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3404%3A198113)

- [x] Update title
- [x] Update color input
- [x] Update the name of the panel

Note: Keep the same filter toggle buttons for now as in the old panel. Updating those happen in #6527.

## Additional Context

![Screenshot 2021-02-22 at 12 16 02](https://user-images.githubusercontent.com/3294597/108694467-5ebf2600-74ff-11eb-8bc0-f42bc7882a4b.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
