### ISSUE TITLE
Redesign: Update page attachment panel

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#6464]
## Feature Description
See [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3483%3A322)

- [ ] Update panel order
- [ ] Update the URL input
- [ ] Update the link text input

## Additional Context
<img width="746" alt="Screenshot 2021-02-22 at 18 03 49" src="https://user-images.githubusercontent.com/3294597/108734688-ff2d3e80-752f-11eb-8d58-4ba03cb675d1.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Assigning UX needed to confirm changing the link text

**Comment by csossi** [comment]
Verified in QA
