### ISSUE TITLE
Redesign: Update image accessibility panel

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#6465]
## Feature Description
See[ Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3399%3A157583)

- [ ] Use multiline input for image

## Additional Context
![Screenshot 2021-02-22 at 12 24 30](https://user-images.githubusercontent.com/3294597/108695405-8cf13580-7500-11eb-9991-9d5b714a6ab1.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
