### ISSUE TITLE
Redesign: Update alignment panel

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#6467]
## Feature Description
See [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=742%3A45961)

- [x] Update toggles
- [x] Remove divider
- [x] Switch tooltips

## Additional Context
![Screenshot 2021-02-22 at 12 33 49](https://user-images.githubusercontent.com/3294597/108696473-e27a1200-7501-11eb-8c9a-d2d08d61992d.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
