### ISSUE TITLE
Redesign: Update size+position panel

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#6468]
## Feature Description
See [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3399%3A99714)

- [x] Remove "Set as background"
- [x] Update inputs
- [x] Update toggles
- [x] Replace tooltips
- [x] Update all karma tests using "Set as background" to drag to canvas edge instead
- [x] Make sure all other tests still function

## Additional Context
![Screenshot 2021-02-22 at 12 38 46](https://user-images.githubusercontent.com/3294597/108696976-8c599e80-7502-11eb-81cc-1af03d7acdb0.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
@embarks, I discovered some minor visual issues with both the panels and the numeric inputs in #6592 (edit: sorry, meant #6592, not #6591), so you might want to hold off with this one until that one is merged - it just makes sure we can align and style things as they're supposed to. Or copy the edits in to get going and handle it in the merge. 🤷

**Comment by miina** [comment]
This will also collide a bit with the Page background panel (#6461 ) which uses the flip toggles -- I'll be replacing the general flip controls in the same place most likely.

**Comment by csossi** [comment]
Verified in QA
