### ISSUE TITLE
Redesign: Update layer style panel

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#6469]
## Feature Description
See [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3399%3A157584)

- [x] Update the input

## Additional Context
<img width="464" alt="Screenshot 2021-02-22 at 12 44 31" src="https://user-images.githubusercontent.com/3294597/108697591-5a950780-7503-11eb-93ab-aae26d2bb335.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
