### ISSUE TITLE
Media not always entering the edit mode

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#647]
## Bug Description

In some cases (seems to depend on the size of the image element since the edges seem to not react to double-click) the image does not go into edit mode.

Might be related to Drop Target indicator highlights (the blue wide outline on top of media)

## Expected Behaviour

Media should always enter edit mode on double-click

## Steps to Reproduce

1. Add on image
2. Resize it to be quite small.
3. Try to go to edit mode via double click

## Screenshots

See how resizing the image to be larger enables the edit mode again.
![edit-mode](https://user-images.githubusercontent.com/3294597/77050945-cb19d700-69ca-11ea-829f-adc3d135e71a.gif)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@wassgha Not sure but this might be related to Drop Target blue highlighting lines on top of Media. Tagging you just in case.

**Comment by wassgha** [comment]
Looks like it! Thanks for reporting
