### ISSUE TITLE
Redesign: Update link panel

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#6470]
## Feature Description
See [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3404%3A198519)

- [ ] URL
- [ ] Input
- [ ] Media picker

## Additional Context
![Screenshot 2021-02-22 at 14 34 09](https://user-images.githubusercontent.com/3294597/108709216-b1560d80-7512-11eb-89b9-51236097e2f0.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
The screenshot shows the Permalink panel, not  the Link panel?

**Comment by miina** [comment]
Oops, thank you! Fixed.

**Comment by csossi** [comment]
Verified in QA
