### ISSUE TITLE
Redesign: Saved Styles / Saved colors

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#6471]
## Feature Description

See [Figma](Update preset panel) for colors and for [styles](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3404%3A202930)

- [ ] Make sure all looks correct

## Additional Context
<img width="498" alt="Screenshot 2021-02-22 at 12 50 39" src="https://user-images.githubusercontent.com/3294597/108698234-34bc3280-7504-11eb-923c-2c99e0f996ac.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
@miina, one thing I noticed for this one: The panel header jumps a bit when moving in and out of edit mode. Seems like one of them is a pixel taller than the other somewhere. But other than that, it looks pretty good! 😎

**Comment by miina** [comment]
@barklund I also noticed that the text is not aligned correctly in the saved text styles + since it was implemented before the design-system colors, the colors need replacement. 

The color swatches also seem to be displayed a bit "off the grid" -- will check that, too.

Changing the estimate to 2 FYI @bmattb

**Comment by csossi** [comment]
Verified in QA
