### ISSUE TITLE
Redesign: Update text style panel 

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#6473]
## Feature Description
See [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3483%3A611)

- [ ] Update dropdowns (which component for the font picker!?)
- [ ] Update inputs
- [ ] Update toggles
- [ ] Update colors
- [ ] Update tooltips

## Additional Context
<img width="691" alt="Screenshot 2021-02-22 at 12 53 16" src="https://user-images.githubusercontent.com/3294597/108698968-fd9a5100-7504-11eb-8b8e-bdb568b8af0d.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
This one needs dropdowns, which haven't been fully prepared yet. I'll deal with dropdowns Wednesday whilst tackling this one.

**Comment by csossi** [comment]
Verified in QA
