### ISSUE TITLE
Redesign: Update text box panel

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#6474]
## Feature Description
See [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3404%3A210041)

- [ ] Use pills from design system
- [ ] Update color input
- [ ] Update input
- [ ] Update toggles
- [ ] Update tooltips

## Additional Context
<img width="782" alt="Screenshot 2021-02-22 at 12 53 33" src="https://user-images.githubusercontent.com/3294597/108699473-929d4a00-7505-11eb-8751-7ac6cf1f5404.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
