### ISSUE TITLE
Redesign: Update border width panel

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#6475]
## Feature Description
See [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3471%3A7322)

- [x] Use inputs from design system
- [x] Use toggle from design system
- [x] Use color from design system
- [x] Use tooltip from design system

## Additional Context
<img width="668" alt="Screenshot 2021-02-22 at 13 03 48" src="https://user-images.githubusercontent.com/3294597/108699818-0b9ca180-7506-11eb-92ec-623da5ed20d2.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
