### ISSUE TITLE
Redesign: Update border radius panel

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#6476]
## Feature Description
See [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3471%3A4831)

- [ ] Use inputs from design system
- [ ] Use toggle from design system
- [ ] Use tooltips from design system

## Additional Context

<img width="718" alt="Screenshot 2021-02-22 at 13 07 15" src="https://user-images.githubusercontent.com/3294597/108700196-89f94380-7506-11eb-8367-25d84e4684f1.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
