### ISSUE TITLE
Settings: Undo "Measurement ID" support

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#6479]
## Bug Description

Measurement ID doesn't work with AMP Analytics, so only encourage the use of Tracking ID, remove reference to measurement ID. 

![image](https://user-images.githubusercontent.com/13389997/108724543-6d9fdb80-74f3-11eb-84f4-c9e914e7c407.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Basically need to revert #5856.

* Update help text
* Update regex

**Comment by csossi** [comment]
Verified in QA
