### ISSUE TITLE
Permalink: special characters URL-encoded in slug

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#6480]
## Bug Description

Special characters like commas or colons are URL encoded in the permalink slug. 

## Expected Behaviour
Special characters should be stripped.

Example:
“Hello, World” becomes “hello-world”
“Foo: Bar” becomes “foo-bar”

## Steps to Reproduce
1. Create a new story with a comma or colon
2. See characters in permalink field URL-encoded 

## Screenshots

![image](https://user-images.githubusercontent.com/66372350/108745745-7a2f2e80-7509-11eb-8d27-e08bc2a41622.png)

![image](https://user-images.githubusercontent.com/66372350/108745598-49e79000-7509-11eb-8212-0da8515844fd.png)

Expected slug: 
![image](https://user-images.githubusercontent.com/66372350/108748137-40135c00-750c-11eb-997f-77a226f8c95e.png)

## Additional Context

Related topic: 
https://wordpress.org/support/topic/error-in-linking-with-special-characters-in-title-url/

- Plugin Version: 1.4.0
- WordPress Version: 5.6.1
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
