### ISSUE TITLE
Permalink field not automatically updating

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#6481]
## Bug Description

The permalink field is not automatically updating when the story is still in draft mode. 

## Expected Behaviour
The slug in the story draft should automatically update.

## Steps to Reproduce

1. Enter a title. Notice slug updating.
2. Change the title. Slug does not update.
3.  Save draft. Slug does not update.

Note: slug updates after you publish.

## Screenshots

https://user-images.githubusercontent.com/66372350/108749881-5de1c080-750e-11eb-9b61-f35e0867b38e.mov

## Additional Context

- Plugin Version: 1.4.0
- WordPress Version: 5.6.1
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
This seems to be working as expected now, closing.
