### ISSUE TITLE
Link Panel: issues with special characters

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#6482]
## Bug Description

The link title was incorrectly filled in automatically when there are special characters.

https://user-images.githubusercontent.com/66372350/108758901-a6eb4200-7519-11eb-872b-7e91a7030bfb.mov

## Expected Behaviour

Link title should automatically fill in description field with correct special character

![image](https://user-images.githubusercontent.com/66372350/108755885-ce401000-7515-11eb-92bf-04cbaea0a182.png)

## Steps to Reproduce

1. Enter a URL to apply a link. URL should contain a link title with a special character like this: https://www.selectgame.com.br/chizuru-kagura-estara-em-the-king-of-fighters-xv-novo-trailer/ 
2. Notice instead of `estará` the description field automatically filled in `estarÃ¡`

## Screenshots
Inserted this [link](https://www.selectgame.com.br/chizuru-kagura-estara-em-the-king-of-fighters-xv-novo-trailer/) that contained special character `Chizuru Kagura estará em` but it automatically displayed the following: 
![image](https://user-images.githubusercontent.com/66372350/108755312-19a5ee80-7515-11eb-8981-b68a05a6e4cf.png)

## Additional Context
Related topic: 
https://wordpress.org/support/topic/error-in-linking-with-special-characters-in-title-url/ 

Workaround: Manually edit the link description.

- Plugin Version: 1.4.0
- WordPress Version: 5.6.1
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Changing pods because it looks like an issue with the REST API controller fetching the title.

**Comment by csossi** [comment]
Verified in QA

![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/6930836e-e242-4482-bbd0-eb95b1ca10a4)
