### ISSUE TITLE
Redesign: Generic switch component

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#6492]
## Feature Description

See [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3900%3A466)

- [ ] Move switch to the design-system
- [ ] Adjust stories

## Additional Context
<img width="330" alt="Screenshot 2021-02-23 at 19 06 05" src="https://user-images.githubusercontent.com/3294597/108879723-d2e1f280-7601-11eb-8927-dea264c3d36b.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by samwhale** [comment]
The switch was added to the design system and #6824 updates the switch in the editor
