### ISSUE TITLE
Redesign: Generic URL input field component

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#6494]
## Feature Description

See [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3404%3A198519)

- [ ] Move URL input to design-system (including the URL parsing logic)
- [ ] Update storybook
- [ ] Use in element link panel
- [ ] Use in page attachment panel
- [ ] Default to `https://` rather than `http://` (#6261)

Note: this is just for the URL input separately.

## Additional Context
<img width="287" alt="Screenshot 2021-02-23 at 19 15 27" src="https://user-images.githubusercontent.com/3294597/108880984-21dc5780-7603-11eb-9ed8-a66168592fac.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
Please make sure to incorporate the issue in #6261 while solving this.

**Comment by barklund** [comment]
Can you link the PR solving this? Otherwise it's hard to review :)

**Comment by samwhale** [comment]
@barklund sorry, I linked the wrong issue in the pr I put up 😓. It's correct now!
