### ISSUE TITLE
Redesign: Generic multiline input component

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#6495]
## Feature Description
See [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3398%3A78512)

- [ ] Variants with/without count to design-system
- [ ] Adjust storybook

## Additional Context
<img width="675" alt="Screenshot 2021-02-23 at 19 18 26" src="https://user-images.githubusercontent.com/3294597/108881387-8ac3cf80-7603-11eb-8501-0aae01a4284c.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/8d21e14f-d71a-46b9-8344-6436f6420a70)

**Comment by miina** [comment]
UAT will be done for #6465
