### ISSUE TITLE
Redesign: Generic Media Display component

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6498]
## Feature Description

See the [Figma link](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3398%3A94450)

- [ ] Create component + storybook story
- [ ] Optional media URL
- [ ] Clearable using X

![Screen Shot 2021-02-25 at 11 02 22](https://user-images.githubusercontent.com/637548/109186440-eb1b5400-775e-11eb-9d8c-c7dbdb2a8208.png)

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@barklund Do we need this as a separate component? It seems to be currently being used in one place only. Thoughts?

**Comment by miina** [comment]
Closing as irrelevant for now since it's used only in one place. The state after removing Media would also be a bit unclear for the component since it only exists when there is Media.
