### ISSUE TITLE
Redesign: Generic bordered fieldset component

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6500]
## Feature Description

[See Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3398%3A94450)

- [ ] Implement as actual `<fieldset>` 
- [ ] `<Fieldgroup>` component

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
This was intended for the bordered form grids in captions and animation panel, but as they've been implemented very differently, this ticket will be shelved for now. This might come up again once multiple captions and/or multiple animations can be added, but now, this is not relevant.
