### ISSUE TITLE
Redesign: Update video playback panel

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6503]
## Feature Description

See [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=1533%3A260040)

- [ ] title
- [ ] checkboxes

## Additional Context

![Screen Shot 2021-02-23 at 2 52 40 PM 1](https://user-images.githubusercontent.com/58738530/108899795-d74ce200-75e6-11eb-8fdd-cf492e25e64f.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
