### ISSUE TITLE
Redesign: Update video captions panel

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6504]
## Feature Description

See [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3398%3A94450)

- [ ] Title
- [ ] Input
- [ ] Fieldset

## Additional Context

![Screen Shot 2021-02-23 at 3 31 21 PM](https://user-images.githubusercontent.com/58738530/108904189-34976200-75ec-11eb-99c7-0ccfcd5d32b1.png)
---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
