### ISSUE TITLE
Redesign: Update animation panel

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6505]
## Feature Description

See [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3398%3A94450)

- [ ] inputs
- [ ] toggles
- [ ] tooltips
- [ ] fieldset

## Additional Context

![Screen Shot 2021-02-23 at 3 34 39 PM](https://user-images.githubusercontent.com/58738530/108904717-db7bfe00-75ec-11eb-86e8-7a11b422ff5b.png)
![Screen Shot 2021-02-23 at 3 35 39 PM](https://user-images.githubusercontent.com/58738530/108904727-df0f8500-75ec-11eb-9b92-8c7cf233f47d.png)
![Screen Shot 2021-02-23 at 3 35 15 PM](https://user-images.githubusercontent.com/58738530/108904730-dfa81b80-75ec-11eb-8c16-0bc9763e52c5.png)
![Screen Shot 2021-02-23 at 3 35 06 PM](https://user-images.githubusercontent.com/58738530/108904731-dfa81b80-75ec-11eb-9e0c-d4f88bb2560b.png)
![Screen Shot 2021-02-23 at 3 34 55 PM](https://user-images.githubusercontent.com/58738530/108904733-dfa81b80-75ec-11eb-9bad-af14cb8891cc.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Tested as per 6821 (PC/Chrome)

Two things in the video here:
- setting duration and delay on Pan And Zoom has no effect
- If I select animation type dropdown, editor crashes
https://share.getcloudapp.com/yAu6pwgE

**Comment by miina** [comment]
@csossi Thanks for testing! Should be fixed now, moving back to QA.

**Comment by csossi** [comment]
Testing 6821 PC/Chrome

Not seeing the Pan And Zoom option for background

![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/4fa09caa-ba14-4fbf-8969-a6e50f01c400)

**Comment by miina** [comment]
Moving this to QA Passed since Pan & Zoom is behind a feature flag.

**Comment by csossi** [comment]
Verified in QA
