### ISSUE TITLE
Redesign: Update shape style panel (colour)

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6506]
## Feature Description

See [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3398%3A94450)

- [x] Update color input

## Additional Context

![Screen Shot 2021-02-23 at 3 41 33 PM](https://user-images.githubusercontent.com/58738530/108905368-a1f7c280-75ed-11eb-8275-bd6f4fcd3020.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## UAT

1. Add a Shape
2. Look at the Style Panel & verify the style looks as expected.

**Comment by miina** [comment]
This got done within #6456, sending directly to UAT.
