### ISSUE TITLE
Redesign: Update document status panel

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6513]
## Feature Description

See [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=1533%3A260040)

- [ ] update title
- [ ] update radios
- [ ] update input

## Additional Context

![Screen Shot 2021-02-24 at 1 11 18 PM](https://user-images.githubusercontent.com/58738530/109045634-d331ca80-76a1-11eb-85c8-9d7450ed01d6.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Not seeing the "Password Protected" section
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/cd37598d-d6df-426e-9979-e768f10d2a9c)

**Comment by swissspidy** [comment]
> Not seeing the "Password Protected" section
> ![image.png](https://camo.githubusercontent.com/bd3a9eff63b6d0d7639e1937c43085e3c8e5c627d2d6c5fd55995805efc038ab/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3565613038356534373034653732633061393963363939372f63643337353938642d643664662d343236652d393937392d653736386631306432613963)

@cssosi This is currently expected. Password protection is not currently supported by the editor and will be handled in #2335

**Comment by csossi** [comment]
Thanks, @swissspidy 

Verified in QA then
