### ISSUE TITLE
Redesign: Update publishing panel

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6514]
## Feature Description

See [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3483%3A1021)

- [ ] update titles
- [ ] update dropdowns
- [ ] update media selectors

## Additional Context
![Screen Shot 2021-02-24 at 1 16 16 PM](https://user-images.githubusercontent.com/58738530/109046221-7f73b100-76a2-11eb-9dcf-e102df74fb11.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
