### ISSUE TITLE
Redesign: Update excerpt panel

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6515]
## Feature Description

See [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=1533%3A260040)

- [ ] Multiline input

## Additional Context

![Screen Shot 2021-02-24 at 1 18 21 PM](https://user-images.githubusercontent.com/58738530/109046494-cd88b480-76a2-11eb-90e3-be204fd89121.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
According to Figma, "Story Description" should be "Excerpt":
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/6b5fc5ae-b5cf-4774-b473-0cbc50a98e65)

Figma:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/d2008e0b-f430-45ce-b7df-f3e5c0db0be1)

**Comment by miina** [comment]
@csossi Thanks for flagging that -- information came from the UX meanwhile that we should keep it "Story Description" -- looks like Figma wasn't changed.

Will move to "QA Passed" since that was the only finding.
