### ISSUE TITLE
Redesign: Update permalink panel

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6518]
## Feature Description

See [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=1533%3A260040)

- [ ] input

## Additional Context
![Screen Shot 2021-02-24 at 1 23 12 PM](https://user-images.githubusercontent.com/58738530/109047416-db8b0500-76a3-11eb-9bd6-dfe0f584e4c4.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
