### ISSUE TITLE
Redesign: Update page advancement panel

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6519]
## Feature Description

See [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=1533%3A260040)

- [ ] update switch
- [ ] update input

## Additional Context

![Screen Shot 2021-02-24 at 1 28 30 PM](https://user-images.githubusercontent.com/58738530/109047734-3886bb00-76a4-11eb-8112-0823a6d3fac0.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
PC/Chrome (cleared cache)

Seeing these white boxes beside "Auto" and "Manual"
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/7742b338-176d-4687-9f5a-65043dc1d7a0)

**Comment by samwhale** [comment]
I'll check it out!

**Comment by samwhale** [comment]
@csossi I couldn't reproduce locally but I did add an `opacity: 0` to that checkmark box. I think it should be invisible now. If it isn't, let me know!

**Comment by csossi** [comment]
Verified in QA
