### ISSUE TITLE
Redesign: Snackbar

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6521]
## Feature Description

See [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=1533%3A260040)

- [ ] Implement in editor

## Additional Context
![Screen Shot 2021-02-24 at 1 48 35 PM](https://user-images.githubusercontent.com/58738530/109050102-07f45080-76a7-11eb-87f7-215a3a556b42.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
@embarks, could this be completed and get through both review and QA for Thursday's bugbash? If so, I'd really love to see this one getting into the 1.5 release as well. But if not, we can delay.

**Comment by embarks** [comment]
> @embarks, could this be completed and get through both review and QA for Thursday's bugbash? If so, I'd really love to see this one getting into the 1.5 release as well. But if not, we can delay.

@barklund I'll check in with Tad in the morning to align expectations. I think I'll need to add the `dismissable` option to the `showSnackbar` calls in the editor code as that is new functionality, and I'll do that first thing tomorrow. That will add the close buttons. Retry functionality (and so the retry action buttons) probably won't make it by tomorrow.

I should have said that the screenshots were a simulation to verify the designs, sorry about that. :/ As for QA I am trying to find a way to simulate some of the errors (most of the snackbars show when errors happen) without changing code.

**Comment by embarks** [comment]
@csossi If you get a chance today or in the morning to look at this one it would be greatly appreciated! Has been requested to merge before bug bash tomorrow. Thank you! 🙏

**Comment by csossi** [comment]
Not seeing close buttons here (testing #6696)
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/3237540e-7dcb-410e-ad12-1834fbd03451)
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/d8088cbf-4e8b-42ff-9b7f-7b33a6389e62)

Expected to see "retry" and "close" - let me know if I'm not understanding the expectation here

**Comment by embarks** [comment]
@csossi looks like that last one failed to propagate to the QA environment. I've tried rerunning the pipeline, it should take a bit, but I'll reassign it to you when I correct the CI/CD issues.

**Comment by embarks** [comment]
@csossi it should be deployed to QA now. Note, (I should have made this more clear, sorry) that the `Retry` button should not be visible. I have another ticket out to implement retry functionality. The close button will be visible on most of them. The dev tools copy to clipboard snackbar only shows up for a second so I did not add the close button to that one.

**Comment by csossi** [comment]
Verified in QA
