### ISSUE TITLE
Redesign: Update all dialogs

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6522]
## Feature Description

[See Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=1533%3A260040)

- [x] Status check
- [x] title missing
- [x] post publish
- [x] preview error
- [x] media delete
- [x] media edit
- [x] missing upload permission
- [ ] story delet
- [x] 3rd party terms
- [x] confirm page layout
- [x] retire old dialog component

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
I don't see any references to a `story delete` dialog? But I did go ahead and update the video optimization dialog as well. Safe to say all dialogs are updated.

**Comment by BrittanyIRL** [comment]
@csossi the PR description for this one is pretty robust if you need additional context!

**Comment by csossi** [comment]
Regarding the User Permissions message - it only appears when I try to upload an image via "upload" button. Shouldn't it appear if I try to click-and-drag onto canvas or media panel as well? Video shows what's happening know - let me know if ok-as-is
https://share.getcloudapp.com/WnuY2Brl

**Comment by BrittanyIRL** [comment]
(1 more dialog were created while this has been in QA limbo since testing the permissions dialog is rather obtuse. taking back to in progress to add those dialogs)

**Comment by BrittanyIRL** [comment]
> Regarding the User Permissions message - it only appears when I try to upload an image via "upload" button. Shouldn't it appear if I try to click-and-drag onto canvas or media panel as well? Video shows what's happening know - let me know if ok-as-is
> https://share.getcloudapp.com/WnuY2Brl

@barklund is this right? I can't get the user permissions dialog to trigger either, wondering if this is accurate or just me being unfamiliar with this part of the app.

**Comment by BrittanyIRL** [comment]
@csossi I finally figured this out! 

So you need to make sure your user doesn't have upload media abilities. It looks like a `contributor` level of access will get ya there. Then try to upload something on a new story and it'll trigger.

**Comment by BrittanyIRL** [comment]
@csossi - if you have capacity today it would be amazing to get this through QA, it's a rather big chunk of code and I know it's going to start holding up the pipeline.

**Comment by csossi** [comment]
I'm still not seeing the dialog if I click-and-drag to canvas or media section. The only time I see the new dialog is if I click the upload button and try to upload that route. See original video above - that was done as a contributor

**Comment by csossi** [comment]
Verified in QA
