### ISSUE TITLE
Redesign: Grid view drag'n'drop using preview

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6525]
## Feature Description

The designs call for using native drag'n'drop in the grid view with a preview while dragging. Current implementation does not show _what_ you're dragging, only _where_ you can drop it when hovering those locations.

Changing this is not trivial and probably requires switching to native drag'n'drop API rather than the current "fake" drag'n'drop.

[Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=298%3A1113).

## Additional Context

![Screen Shot 2021-02-24 at 18 07 37](https://user-images.githubusercontent.com/637548/109078439-54ea1e00-76cb-11eb-8e3c-73c5a52a7636.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@barklund Perhaps we could skip using the native drag-drop and instead add a clone of the element being dragged while dragging? Another page preview but with opacity and smaller. Then we should be able to build on what we currently have.
WDYT?
