### ISSUE TITLE
Allow image filter to be applied to all media, not just background media

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6526]
## Feature Description
See [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=221%3A13978)

- [ ] Allow filters for all media, not just background, place panel correctly in order
- [ ] Make sure merging media works correctly (dragging one media item into another)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@barklund What's the correct way for merging? Is it the same as for flipping? That in case of background, the background filter has priority, otherwise, the origin media?

**Comment by csossi** [comment]
Verified in QA
