### ISSUE TITLE
Redesign: Update image filter buttons to proper design system component

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6527]
## Feature Description

Once #6499 is implemented, update the filter panel to use this component.

See [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3404%3A198113)

## Additional Context

![Screenshot 2021-02-22 at 12 16 02](https://user-images.githubusercontent.com/3294597/108694467-5ebf2600-74ff-11eb-8bc0-f42bc7882a4b.png)
---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
