### ISSUE TITLE
Redesign: Transparent background

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#6535]
## Feature Description
Currently, various places are using variations of a transparent background with different square sizes. E.g. color picker, saved color, color input color preview.
The same background should be used everywhere.

See [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3360%3A63235).

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Ping @barklund FYI

**Comment by csossi** [comment]
Verified in QA
