### ISSUE TITLE
Design System: Pill has faint outline on keyboard focus

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6537]
## Bug Description

There is a faint 1px outline that shows on pills with focus that are not active. 

![Screen Shot 2021-02-25 at 1.15.49 PM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/3667992c-50ea-4512-87a8-49cd9a4f7ea0)

## Expected Behaviour

There should be no 1px outline. 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by samwhale** [comment]
After some investigation it looks like adding a border radius makes this happen naturally:

![border-radius.gif](https://images.zenhubusercontent.com/5b1032a1348b7966b43421a4/e0d0e3dd-e4af-4bcb-a77b-9b3f36b07aa0).

Using a color other than white makes it harder to see:
![border-radius-2.gif](https://images.zenhubusercontent.com/5b1032a1348b7966b43421a4/031ad1f0-1696-4a58-9b70-261081124475)

---

Can see the same thing happen for our pills:
![border-radius-3.gif](https://images.zenhubusercontent.com/5b1032a1348b7966b43421a4/7f89c82d-7cd1-481a-8cf7-572b05248161)

I'm going to keep looking for a way to get around it, but it looks like it's a consequence of using box shadows on rounded corners. This happens in both chrome and firefox/

**Comment by samwhale** [comment]
Best way to test this @csossi is to:
1. Go to dashboard
2. Focus the pills using the keyboard
3. Should see less of those weird lines on the inside of the pills. It won't be all the way gone, but it should be hardly noticeable.

**Comment by csossi** [comment]
Verified in QA
