### ISSUE TITLE
KSES: width attribute removed for images in all post types

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6540]
## Bug Description

As reported at https://wordpress.org/support/topic/bug-web-stories-1-4-0-removes-post-width-for-author/, there seems to be an issue with the allowlist in our KSES class.

I assume it's because how we merge our allowed tags with the [existing allowlist in WordPress](https://github.com/WordPress/wordpress-develop/blob/a280d5704b9265c528a4a04c5152e5fee18716d0/src/wp-includes/kses.php), as the attributes seem to be overridden. Ours doesn't contain the `width` attribute.

There's actually quite the mismatch:

https://github.com/WordPress/wordpress-develop/blob/a280d5704b9265c528a4a04c5152e5fee18716d0/src/wp-includes/kses.php#L227-L239

https://github.com/google/web-stories-wp/blob/a21c394d6c59b1290f4efad589823f164de74823/includes/KSES.php#L536-L551

That is probably the case for other tags as well, not just `img`. So need to check those too.

## Expected Behaviour

`width` attributes of images in other post types should not be removed.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

Use `array_merge_recursive`?

Tests?

**Comment by spacedmonkey** [comment]
After a number of issues with KSES https://github.com/google/web-stories-wp/issues/5728 https://github.com/google/web-stories-wp/issues/5763 https://github.com/google/web-stories-wp/issues/6076, it is becoming clear, our solution doesn't work well. 

As [discussed](https://xwp.slack.com/archives/C013J2EGH8R/p1614337538027600?thread_ts=1614333895.026700&cid=C013J2EGH8R) on slack, I think we should save the amp markup in a piece of post meta registered against the story post type. 

So would need to do the following. 
- Update the database version
- Add a migration script to copy existing post_content to post meta. 
- Add a check in [Story](https://github.com/google/web-stories-wp/blob/a21c394d6c59b1290f4efad589823f164de74823/includes/Model/Story.php#L108), to if post meta exists, if does use this value over `post_content`. 
- Depending on database version, submit amp markup to different field and save as post meta. 
- Depending on database version, generate text / html preview and save it post_content. 

This is a big change could be seen as a breaking change to many. We may need discuss this wider.

**Comment by spacedmonkey** [comment]
Context from the original discussion https://github.com/google/web-stories-wp/issues/57

**Comment by swissspidy** [comment]
Let's just fix this pressing bug here fist before going down that path.

**Comment by spacedmonkey** [comment]
Using `array_merge_recursive` seems like it would work. I will take a look

**Comment by spacedmonkey** [comment]
Looking closer into this, `array_merge_recursive` will not work. It does not deduplicate fields. I think something like this [array_merge_recursive_distinct](https://github.com/Yoast/wordpress-seo/blob/219014897b95465fa1cd4d23a72b0c74864f6dba/inc/class-wpseo-meta.php#L938-L983). I will do some more testing

**Comment by swissspidy** [comment]
At the very least we should simply add `width` to the list of attributes to fix the issue,  and add any other missing attributes.

Something like `array_merge_recursive` is a nice improvement on top of that to make it more robust. We can do that in another ticket too if needed.

**Comment by spacedmonkey** [comment]
I have created a PR https://github.com/google/web-stories-wp/pull/6542 that uses array_merge_recursive_distinct. Added some tests.
