### ISSUE TITLE
Make Story Ad Setup instructions clearer in the Settings panel

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#6563]
## Feature Description

Since the setting launched to configure Story Ads in the editor, a few questions come up frequently: 

- I configured my Ads but no ads are showing up, why is that? Did I do something wrong? 
- What is a slot ID? 

We should find ways to make the set up instructions clearer in the story editor so that users don't need to ask in the Support forums for these. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
> I configured my Ads but no ads are showing up, why is that? Did I do something wrong?

@gajasinski FYI this comes up a lot in support, maybe there's a good way to answer this question from right within the settings page.

**Comment by gajasinski** [comment]
@agingoldseco and @bethanylang for thoughts on this?

**Comment by mxbclang** [comment]
@gajasinski Thanks for the tag!

@swissspidy Agreed that adding some text on the left side of the Monetization setting (for AdSense only) could be really helpful here. Maybe something like:

It can take up to a few days for ads to begin displaying in your stories. To confirm that you have set up AdSense properly, you can use the <a href="https://support.google.com/adsense/workflow/10383839?hl=en">AdSense troubleshooting tool</a>.
