### ISSUE TITLE
Stickers: Add Sticker Icon

### ISSUE THREAD

**Issue by maxyinger** [GoogleForCreators/web-stories-wp#6582]
Get an icon for stickers and update `elements/sticker/icon.js` to use it. Right now we just have the `Shapes` icon as a temporary substitute:
![Screen Shot 2021-03-02 at 9.12.24 AM.png](https://images.zenhubusercontent.com/5ea0a3e2f739259b2b0b092a/118b5f93-ac8e-4524-b86c-52fb33054e26)

I believe we still need this designed, so tagging with UX needed for now

**Comment by BrittanyIRL** [comment]
Looking at `Stories - Post Stable` in Figma the stickers/shapes panel has this icon:
<img width="204" alt="Screen Shot 2021-03-02 at 2 32 48 PM" src="https://user-images.githubusercontent.com/10720454/109718194-4042d580-7b64-11eb-89c0-cbc673ae2ef7.png"> 

Which is currently available in the design system as `Shapes`
![Screen Shot 2021-03-02 at 2 32 58 PM](https://user-images.githubusercontent.com/10720454/109718234-4f298800-7b64-11eb-845c-3f4a0ec94524.png)

**Comment by maxyinger** [comment]
Ah yea, I wasn't sure if the stickers panel would end up in there or in a separate panel. Is there any work on stickers in the designs yet?

**Comment by BrittanyIRL** [comment]
there's this: https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=5193%3A331218
<img width="278" alt="Screen Shot 2021-03-02 at 2 45 32 PM" src="https://user-images.githubusercontent.com/10720454/109719488-f529c200-7b65-11eb-9f0c-849a9f49c046.png">

**Comment by maxyinger** [comment]
Oh nice. yup, looks like stickers to me. right on

**Comment by BrittanyIRL** [comment]
Confirmed with @tmagalhaes-huge - the shapes icon that is in the design system is to be used for stickers since stickers coexist in the same panel as shapes.
