### ISSUE TITLE
Stickers: Bake in latest display render into story schema for sticker story output

### ISSUE THREAD

**Issue by maxyinger** [GoogleForCreators/web-stories-wp#6586]
This was discussed in the original sticker implementation brief.

The original idea was to read the markup rendered in the display version, which is rendered as an inline-svg, of the sticker in the editor and save it as a dataURI in the schema, then for the actual rendered story `elements/sticker/output.js` we could render the svg with an `amp-img` element and have the src be the dataURI derived from the latest render in the editor:
```
function StickerOutput({ element, box }){
  return (
    <Box box={box} element={element}>
      <amp-img src={element?.sticker?.dataURI}  />
    </Box>
  );
} 
```

Currently, we're just rendering the svg inline for the output (the same as in the display). 

I'd like to hear if the URI encoding is necessary (or not) as it would add complexity to the sticker implementation. 

Right now, it feels like it has the same behavior as our shapes or animations which is: it's referenced and baked in when generating the output. This behavior feels fine to me since we want a minimal implementation and other outputs from our story also follow the same behavior.

@choumx @swissspidy Any thoughts or context here around storing and using the dataURI vs just referencing the inline svg and baking that into the output?

**Comment by BrittanyIRL** [comment]
@bmattb - this needs some discussion between @swissspidy @choumx and @littlemilkstudio before it can be pointed per issue description.

**Comment by bmattb** [comment]
@littlemilkstudio  will check async

**Comment by dreamofabear** [comment]
Maybe I'm missing something but I think the original proposal was for stickers to render SVGs inline (not as image) in the output.

The issue was that uploading SVGs through WP media library treats them as images.

**Comment by swissspidy** [comment]
Yeah same, I don't think we'd want dataURI & amp-img here, inline SVGs sounds reasonable.

Uploaded SVGs could also use be displayed as inline SVGs if we want to.

**Comment by maxyinger** [comment]
@choumx nope not missing anything. Sounds like we're all on the same page and can close out this ticket. Thanks for the input y'all
