### ISSUE TITLE
Alignment shortcuts not working

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6595]
## Bug Description

Alignment is supposed to work with the shortcuts:

* <kbd>mod</kbd> + <kbd>{</kbd>: Align left
* <kbd>mod</kbd> + <kbd>H</kbd>: Align center
* <kbd>mod</kbd> + <kbd>}</kbd>: Align right

However, these shortcuts don't seem to work (at least on my current non-US keyboard layout). They might be US-keyboard layout only, though.

## Expected Behaviour

Shortcuts should work

## Steps to Reproduce

1. Select two elements
2. Press <kbd>mod</kbd> + <kbd>{</kbd> in an attempt to align left
3. Observe that nothing happens

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Closing in favor of #10489
