### ISSUE TITLE
Update dashboard template details view

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6596]
Update dashboard template details view to use design system and match figma: https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=467%3A13745

![Screen Shot 2021-03-03 at 8.18.04 AM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/a6719955-dfe6-4822-86a4-dcde01c6a827)

### Acceptance Criteria
- No regressions in a11y usability of detail view 
- View should match updates in figma

**Comment by BrittanyIRL** [comment]
@bmattb I'm sorry i'm adding to scope in the final 3 days of the sprint, I didn't realize I'd missed the template detail view when I made tickets for the dashboard rewrite. I'm almost done with this now.

**Comment by BrittanyIRL** [comment]
Testing directions copied from PR: 

Go to 'explore templates' and click on 'see details' when you hover over any template. 
- See that pagination still works as expected
- See that 'use template' button still works as expected
- See that 'close' button still works as expected

**Comment by csossi** [comment]
Verified in QA
