### ISSUE TITLE
Prevent Layer Panel from dragging past last item

### ISSUE THREAD

**Issue by samwhale** [GoogleForCreators/web-stories-wp#6600]
## Feature Description

The Layer Panel should not be draggable past the last layer. (ie, you shouldn’t be able to pull it pass Background.)
<img src="https://user-images.githubusercontent.com/22185279/109853304-ffee6080-7c12-11eb-8235-b2d00fafaf6f.gif" width="300px" />

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
