### ISSUE TITLE
Typo on Travel Section page layout

### ISSUE THREAD

**Issue by mxbclang** [GoogleForCreators/web-stories-wp#6601]
## Bug Description

There is a typo in the default text of the Travel Section page layout. The text in the lower half of the layout currently reads: "Tips and tricks for caturing [sic] this iconic city in a day." It should read "Tips and tricks for capturing this iconic city in a day."

## Steps to Reproduce

1. In the Story Editor, choose the Page Layouts tab
2. Select the Travel Section layout

## Screenshots

![image](https://user-images.githubusercontent.com/12189958/109854547-2ae1b000-7c25-11eb-991b-2957c0297da6.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
