### ISSUE TITLE
Embeds: Telemetry for new features

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6610]
## Feature Description

Want to make sure we track usage information for all these new features.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
One particular use case I had today, wanted to see whether we are seeing embedding of carousels (e.g., non single page embeds) happening. Would be good to capture that in our events - embed event of a "latest stories" carousel, or embed event of a fixed list of stories.
