### ISSUE TITLE
Story Locking User Experience

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6612]
## Feature Description

We require designs on the implementation of the UX for the story locking 

UX for the workspace dialog - notification that the story has been taken over
UX for the workspace dialog - opening a locked story to take over
UX for the dashboard presentation (lock, tooltip) etc

Some questions / use cases that are still to be understood

1. When editor B takes over editor A's story, what version of editor A's story is transferred to B (last autosaved, last edit?)
2. If you are editing a published story, how does this work (revision vs autosave)
3. What happens to user A's progress if there are unsaved changes, is there any UI to user A to notify them of this? Really want to avoid situation where there is the potential for significant work/edits to be lost.

to do:

- [x] Add documentation on how WP works with post locking
- [ ] Add documentation on how this MVP works with story locking

## Additional Context

**Behavior in the WordPress block editor**

1. User A opens post in editor
2. User A makes some edits
3. User B opens the post in editor as well
4. User B sees post content as in step (1), because no changes were saved since
5. User B takes over editing from A
6. User A is informed of takeover. Their changes are autosaved

Message when opening a locked post (what B sees in step 3):

![Screenshot 2021-02-25 at 17 42 13](https://user-images.githubusercontent.com/841956/110149471-5e1b6f00-7dde-11eb-8c14-15e7bc7b5014.png)

Message when someone took over editing from you (what A sees in step 6):

<img width="522" alt="Screenshot 2021-02-25 at 17 42 46" src="https://user-images.githubusercontent.com/841956/110149512-6c698b00-7dde-11eb-9c7a-b9e08fcada8f.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
discovery required for Gutenberg

**Comment by spacedmonkey** [comment]
I did some discovery, and gutenberg do not trigger an auto save or revision when a post it taken over. So the process we have is very similar to gutenberg process. 

1. User A, creates story. 
2. Editor sets lock to User A.
3. User A, save story ( either draft or publish ).  
4. User B navigates to dashboard / all stories. 
5. User B will be presented with lock icon very to story title. 
6. User B open story in editor. 
7. Is present to with dialog like this. 

<img width="678" alt="Screenshot 2021-03-26 at 12 33 17" src="https://user-images.githubusercontent.com/237508/112632022-81f73100-8e2f-11eb-827d-bef5166973c3.png">

8. If User B clicks take over, User A will see this dialog. 
<img width="515" alt="Screenshot 2021-03-26 at 12 36 11" src="https://user-images.githubusercontent.com/237508/112632320-df8b7d80-8e2f-11eb-96e7-17c644c0f080.png">

One major difference, the gutenberg implementation checks for a lock every 15 seconds. Our implementation checks every 150 seconds.

**Comment by swissspidy** [comment]
> I did some discovery, and gutenberg do not trigger an auto save or revision when a post it taken over.

Are you sure? The code says otherwise:

https://github.com/WordPress/gutenberg/blob/13b956a79ac425fa1683f1b886b659cc41ebfc3f/packages/editor/src/components/post-locked-modal/index.js#L87-L97

**Comment by swissspidy** [comment]
@spacedmonkey can you confirm the above about autosaves?

**Comment by spacedmonkey** [comment]
@swissspidy Sorry I can confirm. In my testing, I didn't make a change, so a REST API request was not triggered. I can confirm an autosave is triggered. The current author is shown a notice to say a newer version of the post is present. 

<img width="524" alt="Screenshot 2021-03-31 at 17 02 05" src="https://user-images.githubusercontent.com/237508/113175044-eb69ac00-9242-11eb-9802-ebbff4050ff0.png">

**Comment by swissspidy** [comment]
@samitron7 I am moving this ticket to the UX column to get feedback on this feature.

It's a bit difficult to get this to show on staging as it requires opening two windows etc., so  check out the demo in #6497 in addition to this summary.

**Note:** the dialogs will be updated to the new design.

It seems like there are two questions that need to be answered here:

1) Does the current experience as depicted in the demo work for now? Any changes required?
2) In the WordPress block editor, when someone takes over from you, your changes are saved locally in the browser so they aren't lost. We currently don't have that functionality - should we implement this? This would also allow saving changes offline when losing internet connection. See #3842

**Comment by juanhuge** [comment]
@swissspidy 1. the experience works ok, I don't see any required changes. 2. I think it would be useful to handle the last of the use cases to be understood: What happens to user A's progress if there are unsaved changes, is there any UI to user A to notify them of this? Really want to avoid situation where there is the potential for significant work/edits to be lost.

**Comment by swissspidy** [comment]
> I think it would be useful to handle the last of the use cases to be understood: What happens to user A's progress if there are unsaved changes, is there any UI to user A to notify them of this? Really want to avoid situation where there is the potential for significant work/edits to be lost.

We can extend the dialog user A sees to include messaging like this:

<img width="522" alt="Screenshot 2021-02-25 at 17 42 46" src="https://user-images.githubusercontent.com/841956/110149512-6c698b00-7dde-11eb-9c7a-b9e08fcada8f.png">

It does mean we'd need to implement saving in a way that the saving doesn't conflict with user B's edits, but that's an eng thing to worry about I think.

**Comment by juanhuge** [comment]
Yes, this would keep it consistent with the post lock experience for other post types.

**Comment by aaecheverria** [comment]
HI @swissspidy I just removed the UX needed label, please let me know if there is additional feedback/info needed.

Thanks!
