### ISSUE TITLE
Dashboard: Story Previews In Page

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6615]
## Feature Description

This is a follow up ticket for https://github.com/google/web-stories-wp/issues/3391 to assess how we want this/if we want this feature still. 

Last year there was discussion/ask for a "preview overlay" in stories (and templates, which got axed in discussion with design last fall) that is available when clicking on a middle button on hover/focus of a story in grid mode. When clicked, a dialog opens and gives you a preview of the story without opening another tab. 
![story preview](https://user-images.githubusercontent.com/10720454/109992797-db54c000-7cc8-11eb-94e8-a82987cdc135.gif)

There is functionality to view story in a new tab available from story menus:
<img width="405" alt="Screen Shot 2021-03-04 at 8 20 30 AM" src="https://user-images.githubusercontent.com/10720454/109992758-d132c180-7cc8-11eb-904e-0fbcf39a49b5.png">

Since this work was developed behind the feature flag `Story Previews` some things have changed with how "Preview" is done on the editor. 

Suggestions about resurrecting this issue and getting the feature released: 
- Use the actual URL not the generated AMP markup. 
- Add `#development=1` to preview mode to match editor. 

Do we need this functionality still? If so, do we want it to work for templates too? Are we "Previewing" just the story itself or giving it development mode? I think perhaps we're in the weeds on this and that we didn't stop to define the actual goal originally.

## Additional Context

I vaguely remember some weird hoops to jump through to get stories to preview/play in an iframe.
https://github.com/google/web-stories-wp/pull/3447 - a big part of this (if memory serves) was that we wanted this to work for templates too, which have no associated URL so we have to generate the preview on the spot. 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

- If we keep the feature: get the questions above resolved and set the flag to true. 
- If we axe it, remove the code for previews in dashboard.

**Comment by o-fernandez** [comment]
I think this entry point to preview is confusing and easy to click in error when just interested to see the template details, so I'd be in favor of removing it. 

One consideration would be whether we update the "open in new tab" menu to match what we do in preview, including the #development=1 flag as well. @choumx @samitron7 thoughts?

**Comment by BrittanyIRL** [comment]
> I think this entry point to preview is confusing and easy to click in error when just interested to see the template details, so I'd be in favor of removing it. 

To clarify, this is meant to be on 'my stories' view. So a "Preview" or "View" button not template related.

**Comment by swissspidy** [comment]
> One consideration would be whether we update the "open in new tab" menu to match what we do in preview, including the `#development=1` flag as well. @choumx @samitron7 thoughts?

Please don't take away the last and only way to actually see my story in its full glory without the debugging stuff.

**Comment by dreamofabear** [comment]
Personally not a fan of the "Preview" button as-is, since it's center-aligned in the story thumbnail (vs. bottom-aligned) and a different color than "Open in editor".

Tangent: for the overflow menu, I think we should simplify our verbs here (the inconsistent capitalization also bugs me):
- Open in editor -> Edit
- Open in new tab -> Preview
- Copy Story URL -> Copy link
- Rename -> Rename
- Duplicate -> Duplicate
- Delete Story -> Delete

> Please don't take away the last and only way to actually see my story in its full glory without the debugging stuff.

The `#development=1` preview mode does have an "open story" button on the top right. 

We could support both "open" and "preview" actions. But I think only having "preview" is simpler and probably better, since most users will be consuming these stories on mobile (while creation is on desktop). This forces creators to see their content closer to the delivered form.

**Comment by BrittanyIRL** [comment]
<img width="453" alt="Screen Shot 2021-07-06 at 12 40 24 PM" src="https://user-images.githubusercontent.com/10720454/124657435-5ab0f680-de57-11eb-99b9-0eefa86820a4.png">
