### ISSUE TITLE
Animations: Update BG Effect Panel to Latest Designs

### ISSUE THREAD

**Issue by maxyinger** [GoogleForCreators/web-stories-wp#6617]
Latest mockups for effects panel update the type, alter the animation examples to use a bg image and add some directionality. Once design settles on this, this ticket is to implement this in the editor.

Latest updates (Zoom in shows active state)
![Screen Shot 2021-03-04 at 10.06.59 AM.png](https://images.zenhubusercontent.com/5ea0a3e2f739259b2b0b092a/24b63ba0-568b-4919-976c-3618b047b576)

**Comment by BrittanyIRL** [comment]
@barklund is this in scope for the animations panel redesign?

**Comment by BrittanyIRL** [comment]
This may have iterated, let's confirm it's ready before doing dev work on it. 
![Screen Shot 2021-03-30 at 4 04 34 PM](https://user-images.githubusercontent.com/10720454/113067687-ad508780-9171-11eb-8343-4eeff1627058.png)
![Screen Shot 2021-03-30 at 4 04 40 PM](https://user-images.githubusercontent.com/10720454/113067690-ade91e00-9171-11eb-8d3e-ce9e442e83ae.png)

https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=5889%3A418 

@tmagalhaes-huge @aaecheverria @ivayloklissarov @samitron7 could you confirm what "latest designs" mean for the dropdown options in the animation menus?

**Comment by samitron7** [comment]
@BrittanyIRL I've created some animated background for these that I like for Huge to take over as the work was a concept and has not been fully completed. Are we looking to update to the new visual design system here? If so the system can be implemented but just no that the actual animation for each animation option will come later. FYI @tmagalhaes-huge 

![animationKenBurns](https://user-images.githubusercontent.com/10889431/113068465-31efd580-9173-11eb-8115-cc0ebb612a9d.gif)

**Comment by BrittanyIRL** [comment]
This is SOOOO helpful, thank you @samitron7  - I'll remove this from the next sprint.

@o-fernandez can updating the animations panel options be their own feature in the roadmap?

**Comment by o-fernandez** [comment]
> @o-fernandez can updating the animations panel options be their own feature in the roadmap?

Added a new line item in the roadmap. We should look at priority vs. effort here. cc: @choumx

**Comment by BrittanyIRL** [comment]
@choumx is this something that we should still do?

**Comment by dreamofabear** [comment]
Seems like a nice-to-have. Let's have @aaskedall and @agingoldseco comment. I'll throw it on the roadmap backlog for now.

**Comment by BrittanyIRL** [comment]
(seeking some design confirmation here before committing to it!)

**Comment by BrittanyIRL** [comment]
@choumx given what we discussed about the roadmap today - and adding in some knobs/toggles/simplifying the animations - should we just close this and #6881 which are re-skinning the dropdowns? It feels like it might be redundant design work.

**Comment by dreamofabear** [comment]
SGTM
