### ISSUE TITLE
Media Library - Infinite Scroll - Loading Indicator Styling

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#662]
## Feature Description

This is a followup to #23 to add styling. 

**[Design](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=4644%3A299408)**

![image](https://user-images.githubusercontent.com/5874851/77170823-fc110f00-6a91-11ea-8ff5-7862bab9f8ac.png)

Note: The requirement here is just a static loading message that is needed and not a button that the user needs to hit to trigger loading of the next set of media. ie. This for when the user is scrolling too fast and it's taking a while to load so show the loading indicator
---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
1. When the user scrolls to the bottom, a "loading" animation is displayed

**Comment by spacedmonkey** [comment]
@merapi ^
