### ISSUE TITLE
Dashboard: Loading State

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6622]
## Feature Description

This has been brought up a few times in conversation, I might be duplicating a ticket that I can't find. We need a loading state on the dashboard to prevent flashing "empty" content. This will also help decrease perceived time to interaction. 

We need design guidance to implement this. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

Dashboard shows loading state while loading.

**Comment by ivayloklissarov** [comment]
I've added a solution here @BrittanyIRL , also with a reference for motion at the bottom: https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/?node-id=6113%3A471417

**Comment by BrittanyIRL** [comment]
Thanks @ivayloklissarov that was fast!

**Comment by csossi** [comment]
Verified in QA
