### ISSUE TITLE
Set up infrastructure to interact with Help Center

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6633]
## Feature Description

Ahead of automagically opening FTUE when elements go outside the safezone we need the infrastructure to have this event (and others to follow) occur in a way that is uniform and testable. 
This ticket is for that foundation. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Please add QA Instructions - Thanks!
