### ISSUE TITLE
Packages: Move `web-stories-block` to new structure

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6634]
## Task Description

The embed block should be moved to a new `@web-stories-wp/stories-block` package or similar.

**Comment by spacedmonkey** [comment]
This is going to be hard, as embed block has lots of interdependence with dashboard and edit story.

**Comment by swissspidy** [comment]
Only dependency right now is the design system I think, but yes, those need to be resolved first.

Putting this in the backlog for now.

**Comment by swissspidy** [comment]
Tons of dependencies in `package.json` can be moved to `packages/web-stories-block/package.json` now
