### ISSUE TITLE
Dashboard: Template Details UI follow up

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6637]
## Feature Description

There are a few new things in the template details view for the dashboard from[ figma ](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=467%3A13745)that weren't doable in scope of #6599 because we lacked details from Design. 
This ticket is to complete that work after discussing with Design.  

### Buttons 
What are these labels? Are these only on hover? What should they actually say? 
|<img width="80" alt="Screen Shot 2021-03-05 at 10 48 25 AM" src="https://user-images.githubusercontent.com/10720454/110153523-65bc2300-7da0-11eb-828e-99ce2ea2cca3.png">|<img width="114" alt="Screen Shot 2021-03-05 at 10 48 21 AM" src="https://user-images.githubusercontent.com/10720454/110153527-6654b980-7da0-11eb-831a-6feda59305ec.png">|

## Grids
The grid seems skinnier than our current aspect ratio, is this intentional? We've implemented this to be responsive to the viewport size. What's the max width you want the small grid items and what is the max width you want the current page (large)? Is the goal to just have 3 rows always be the same total height of the active view page?

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

Make updates necessary from the above questions.

**Comment by BrittanyIRL** [comment]
Additional content here from bug bash 1.5.0-A: the focus styles of thumbnails is getting cut because of padding a bit and should be addressed with the above grid updates
![Screen Shot 2021-03-09 at 1 11 08 PM](https://user-images.githubusercontent.com/10720454/110531555-f1072280-80d8-11eb-8eb8-5387bbb4d10b.png)

**Comment by BrittanyIRL** [comment]
We should fix this, especially with more templates coming in regularly. 

I think we can give it the good ol' college try without design.

**Comment by maxyinger** [comment]
So just to clarify, completion of this task includes:
- we want to update the previews and the active page to mirror the sizes in figma better
- I'm not seeing any answers for the labels. Happy to look into this or just try and use my best judgement here. Just want to make sure there's not already an existing request from design that's out there.
- Make sure focus styles on thumbs look good and aren't getting cut off

**Comment by BrittanyIRL** [comment]
> So just to clarify, completion of this task includes:

😝 

> * we want to update the previews and the active page to mirror the sizes in figma better

✅ 

> * I'm not seeing any answers for the labels. Happy to look into this or just try and use my best judgement here. Just want to make sure there's not already an existing request from design that's out there.

For this, I did notice the pattern in the editor - these just show up on focus only (keyboard user) - use your best judgment on what text to display.  Probably just "Back to Templates" and "Previous" or "Next Template". 

> * Make sure focus styles on thumbs look good and aren't getting cut off

✅ 

One other thing that if it's easy to sneak in here, it would be soooo nice to have the arrows stop moving vertically on the page depending on the amount of rows of page previews a template has.

**Comment by maxyinger** [comment]
> One other thing that if it's easy to sneak in here, it would be soooo nice to have the arrows stop moving vertically on the page depending on the amount of rows of page previews a template has.

Awesome. yup, will definitely include this in here. Thanks for all the clarifying comments!

**Comment by csossi** [comment]
Verified in QA
