### ISSUE TITLE
TypeError: l(...) is not a function

### ISSUE THREAD

**Issue by HIGHSPEEDMag** [GoogleForCreators/web-stories-wp#6639]
TypeError: l(...) is not a function
    in StoryProvider
    in Unknown
    in MetaBoxesProvider
    in Unknown
    in SnackbarProvider
    in Unknown
    in HistoryProvider
    in Unknown
    in Media3pApiProvider
    in Unknown
    in FileProvider
    in Unknown
    in APIProvider
    in Unknown
    in ConfigProvider
    in b
    in Ge
    in se
    in App
    in StrictMode
    in FlagsProvider

**Comment by LuckynaSan** [comment]
@HIGHSPEEDMag Thank you for opening this issue. 
- What action did you take before encountering this error? 
- Do you see any [browser console errors](https://imgur.com/KyLAzgH) where this issue occurs? 
- Could you please share details about your browser, browser version, and operating system?

**Comment by LuckynaSan** [comment]
@HIGHSPEEDMag Your topic will be closed as we haven’t received a response. Please feel free to open a <a href="https://wordpress.org/support/plugin/web-stories/#new-post">new support topic</a> in the WordPress Support Forum if you continue to experience any issues. Thank you!
