### ISSUE TITLE
Redesign: Make sure all the panels consistently handle "Mixed" value

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#6640]
## Feature Description
When multiple elements are selected with different values, the inputs should show placeholder "Mixed".
We need to ensure that this is actually happening across the panels using consistent logic.

Currently, some of the panels are using `isIndeterminate` to indicate the input value could not be determined and then the placeholder is displayed instead, some panels aren't addressing this at all, however.

## Alternatives Considered

There have been some arguments against using the `isIndeterminate`, see [here for example](https://github.com/google/web-stories-wp/pull/6608#discussion_r587700176).

[See here](https://github.com/google/web-stories-wp/pull/6608#discussion_r587805526) for a potential alternative for numeric input by @samwhale .

Within this issue we can adjust the existing logic as needed for all the inputs.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
- When multiple elements are selected with different value for any input (numeric/text/color, etc.), "Mixed" placeholder should be displayed
- When typing a new value to the input, it should change for all the elements.

**Comment by csossi** [comment]
Verified in QA

![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/25dfac01-7bdc-42af-906f-1a8992c62f48)
