### ISSUE TITLE
Redesign: Implement new dropdowns

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6644]
## Feature Description

Implement the new design system dropdowns in the editor.

- [x] Implement new dropdown in media library file type selector
- [x] Implement new dropdown in media item context menu
- [x] Implement new dropdown in color picker

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
