### ISSUE TITLE
Styling of Publish button wrong in RTL

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#6661]
## Bug Description

Styling of Publish button wrong in RTL, see screenshot. 

## Screenshots

<img width="346" alt="Screenshot 2021-03-08 at 11 13 32" src="https://user-images.githubusercontent.com/237508/110314128-60a8df00-7fff-11eb-8f19-a9bf9b5f8bc4.png">

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
Possibly related to and/or fixed by #6804.

**Comment by barklund** [comment]
@miina, is this still relevant?

**Comment by miina** [comment]
Yes, I think so.

**Comment by miina** [comment]
Looks like this got fixed with the updates to Checklist:
![Screenshot 2021-05-11 at 15 34 33](https://user-images.githubusercontent.com/3294597/117815807-214c7800-b266-11eb-83a1-c14383b31f46.png)

 Closing.
