### ISSUE TITLE
Styling of date picker broken in RTL

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#6662]
## Bug Description

The date picker goes off the editor the screen is mostly unusable in RTL. 

## Screenshots

<img width="332" alt="Screenshot 2021-03-08 at 11 17 33" src="https://user-images.githubusercontent.com/237508/110314711-1e33d200-8000-11eb-96ac-3ea31bd13b13.png">

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
Possible related to #6804.

**Comment by csossi** [comment]
possible to see this without these scrollbars?:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/c781e054-a07b-49ae-9cda-f84df8e39458)

**Comment by barklund** [comment]
> possible to see this without these scrollbars?:
> ![image.png](https://camo.githubusercontent.com/97cb43491ae1b731b8b3584fe1ca76e75ef43be14f0df17944bc21a09737f751/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3565613038356534373034653732633061393963363939372f63373831653035342d613037622d343961652d396364612d663834646638653339343538)

@csossi, please re-test this. I think it works better now, but unsure how the horizontal scrollbar appeared though.

(this does refer to the color picker, though it's posted in the date picker issue)

**Comment by csossi** [comment]
Verified in QA
