### ISSUE TITLE
Tooltip not visible in RTL.

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#6663]
## Bug Description

While in RTL, when hovering over tooltip on icon, the tooltip goes over the edge of the screen. 

## Expected Behaviour

Text should be readable. 

## Screenshots

<img width="144" alt="Screenshot 2021-03-08 at 11 32 18" src="https://user-images.githubusercontent.com/237508/110315987-f80f3180-8001-11eb-87a6-a7d4676b1257.png">

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Sounds like it needs `placement.right` instead of `placement.left` for RTL

**Comment by samwhale** [comment]
This and #6755 are the same bug. Both are fixed by #6887

**Comment by csossi** [comment]
Verified in QA
