### ISSUE TITLE
SVG Upload: unstable Percy snapshot due to random image name

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6665]
## Task Description

Uploaded images get random file names. This leads to this Percy snapshot always changing due to the random file name.

We should probably just not use random image names. There's no reason they _have to_ be random.

**Example:**

https://percy.io/google/web-stories-wp-e2e/builds/9216440/changed/521740708

<img width="1133" alt="Screenshot 2021-03-08 at 16 46 36" src="https://user-images.githubusercontent.com/841956/110344520-da57c180-802d-11eb-9a3d-15250f39b8ec.png">

**Aside:** why is the SVG inserted at such a small size?

**Comment by spacedmonkey** [comment]
The issue are these lines. 

https://github.com/google/web-stories-wp/blob/12765a9cabd48a1ab9b96f67fb0c6e3b867cbad2/packages/e2e-test-utils/src/uploadFile.js#L43-L47

Instead of copying file with new filename. We do just not do this and use the even file name of the file

**Comment by swissspidy** [comment]
Yeah I'd be in favor of removing randomness from tests.
