### ISSUE TITLE
Code Quality: Fix React props warnings for SVGs

### ISSUE THREAD

**Issue by maxyinger** [GoogleForCreators/web-stories-wp#6667]
We're getting a lot of warnings like this from passing props to a styled svg:
i.e:
```js
import styled from 'styled-components';
import Icon from './icon.svg';

const StyledIcon = styled(Icon)`
  transform: rotate(${p => p.isOpen ? 0 : 180}deg);
`

...
<StyledIcon isOpen={isOpen} />
```
![Screenshot 2021-03-08 at 11.05.12.png](https://images.zenhubusercontent.com/5ea0a3e2f739259b2b0b092a/431ac740-a7d2-42e1-8098-a932ed8a175d)

To fix this warning, we should use transient props on svgs (https://styled-components.com/docs/api#transient-props)
```js
import styled from 'styled-components';
import Icon from './icon.svg';

const StyledIcon = styled(Icon)`
  transform: rotate(${p => p.$isOpen ? 0 : 180}deg);
`

...
<StyledIcon $isOpen={isOpen} />
```

This ticket is to go through and address all of these warnings in the editor by updating all styled svgs to use transient props

**Comment by swissspidy** [comment]
Note that 5b40a57ea947eda3b9547b2eafeeec14fb1d0bd2 fixed many warnings for SVGs already, but there are plenty of other places where we could use styled components transient props to de-clutter the DOM.

Fixing that would be really nice
