### ISSUE TITLE
ESLint: Add styled components transient props rule

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6669]
## Task Description

See discussion at https://xwp.slack.com/archives/CCCAUAH6F/p1615198406017400

Would be cool if there's a way to enforce usage of transient props as much as possible, to avoid things like https://github.com/google/web-stories-wp/pull/6565#pullrequestreview-600967806 and #6667

**Comment by maxyinger** [comment]
I think the only worry with strictly enforcing this is this scenario:
```js
const Vegetable = ({ isTomato, ...props }) => <div {...props}>{isTomato ? 'tomato' : 'potato'}</div>

const StyledVegetable = styled(Vegetable)`
  display: ${p => p.$isDisplayed ? 'block' : 'none'};
`;
...
// forcing isTomato to be transient here would cause an error no?
<StyledVegetable $isDisplayed={isDisplayed} isTomato={isTomato} />
```

**Comment by swissspidy** [comment]
Yeah the rule would need to be smart enough to see which props are consumed by the styled component and which ones would actually end up in the DOM. So ideally only `isDisplayed` would be forced to be transient, but not `isTomato`.
