### ISSUE TITLE
Page Templates: Clicking on a template after applying a different one causes the thumbnails to jump

### ISSUE THREAD

**Issue by tmagalhaes-huge** [GoogleForCreators/web-stories-wp#6678]
## Bug Description

If I scroll through the Page Layouts panel and apply one page, confirm and then scroll through it again and click on a different page layout, the panel automatically jumps to a different position, without applying the layout I clicked on.

## Expected Behaviour

Panel should not automatically jump, and user should be able to click any page layout visible on the panel at any moment to apply it.

## Steps to Reproduce

Apply a page layout, confirm, scroll through panel and click on a different page layout

## Screenshots

https://images.zenhubusercontent.com/235435637/72a65a24-703d-4e77-9ae5-b37c1b261477/screen_recording_2021_03_09_at_11_06_41_am.mp4

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System: MacOS
- Browser: Chrome Version 88.0.4324.192 (Official Build) (x86_64)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
Added priority label, leaving it to TLs to add to an upcoming sprint as feasible.

**Comment by BrittanyIRL** [comment]
This is going to be weird. It's about the keyboard roving hook + grid virtualization. I'm pointing to take into consideration possible wrenches in this. It'll also be the same thing on the text sets.

**Comment by BrittanyIRL** [comment]
+1 findings by @bmattb in bug bash v1.11, flagging to add to next sprint for pea pod.

**Comment by BrittanyIRL** [comment]
(same issue persists in text sets)

**Comment by BrittanyIRL** [comment]
First, let's look into https://github.com/google/web-stories-wp/issues/8826 to do some discovery about how to best structure the page layouts panel going forward. 

We can now swap out the page previews with snapshots. We'll have to modify the template cli (add a new variation) to generate screenshots using placeholder images.  
We'll want to test out if we even need to load the virtual scroll anymore. At that point, if there are benefits to keeping that intact then we'll explore fixing this issue. 

At its core, it's an issue of keyboard vs mouse focus + the DOM changing on scroll to have different issues present + their ids. However, if that becomes unnecessary based on the above then it's time saved.

**Comment by BrittanyIRL** [comment]
Should be irrelevant with #9089

**Comment by BrittanyIRL** [comment]
@csossi this is getting solved based on updates in #9093 so you can use that branch to check on this.
