### ISSUE TITLE
Design System: Dropdown placeholder should use Google Sans

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6683]
Dropdown placeholder font is Arial. Should be Google Sans.

Bug reported on dropdown sort but this will be in the design system. 

![Screen Shot 2021-03-09 at 12.40.23 PM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/81d53f34-6729-45e1-a97e-03aa7300857c)

**Comment by csossi** [comment]
Verified in QA

![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/3bb0d3bb-40e6-44ce-82ad-910bb388ba0d)
