### ISSUE TITLE
Dashboard: List View Titles should be 14px 

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6684]
## Bug Description

On dashboard > my stories > list view the title of stories should be 14px not 16px. 
![Screen Shot 2021-03-09 at 12 47 48 PM](https://user-images.githubusercontent.com/10720454/110528698-ab952600-80d5-11eb-8fdb-0a4b48e1f569.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA

![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/9657bbda-dea7-41b3-81dc-d36f174a8799)
