### ISSUE TITLE
Dashboard: Search improvements

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6685]
## Feature Description

This came up in bug bash. The header counts update with search entry which could be seen as flashing content and avoided. However, the page's view is getting updated _as_ you search. This is already being debounced. 

The above begs the question: Should a user have to hit 'enter' before search results are shown? Should we be updating the page as users type as we currently are? 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
It feels like this is working as expected now with the items and the associated counts above it updating in sync. 
@agingoldseco do you see anything that you want improved? This issue was created on vague feedback from a bugbash from before we made the last round of updates to the dashboard, so i think it's obsolete. 


https://user-images.githubusercontent.com/10720454/138498079-8b056cc0-4429-4036-b9f9-678cd9c3e0bf.mp4

**Comment by gajasinski** [comment]
IMO this is working as expected. Are there any latency issues this might introduce for users that have large numbers of stories  on their dash?

If not, leave it.
If so, we might want to introduce the friction of hitting "Enter" to create a better experience.

**Comment by BrittanyIRL** [comment]
There's no latency that I'm experiencing, you'd get some if your internet is slow. Search within the dashboard is triggered on 'enter', so that would be consistent. I haven't heard anyone complain that the search in dashboard is laggy. Should we just leave this ticket be for the time being to see if it becomes an issue?

**Comment by swissspidy** [comment]
> Should a user have to hit 'enter' before search results are shown?

From an a11y point of view that might be desired. It would also be inline with other search forms in the app (e.g. the media library search). Would need confirmation though.

**Comment by gajasinski** [comment]
@swissspidy +1 would keep our patterns aligned with other search forms in the app. @agingoldseco - thoughts?

@BrittanyIRL would leave the ticket as is and can revisit.
