### ISSUE TITLE
Dashboard: Template Details thumbnail borders 

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6686]
## Bug Description

Found during bug bash. Border radius isn't getting applied to actual thumbnail. 
![Screen Shot 2021-03-09 at 1 08 48 PM](https://user-images.githubusercontent.com/10720454/110531279-9b327a80-80d8-11eb-8628-cb43d8ddc7ba.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
