### ISSUE TITLE
Dashboard: Create Story Button border should be 1px

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6687]
## Feature Description

Currently the 'Create new Story' outline/border is 2px in left nav of dashboard. It should be 1 px.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA

**Comment by BrittanyIRL** [comment]
confirmed and closing (UAT is too full and this is a really basic update)
