### ISSUE TITLE
Design System: checkbox hover cursor should be pointer

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6688]
## Bug Description

On hover of a checkbox cursor remains 'default'. Since it can be clicked it should be a pointer. 
Discovered on dashboard/settings however stems from design system. Should be fixed at the root of the issue. 

## Expected Behaviour

On hover of checkbox, cursor should be a pointer. 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
