### ISSUE TITLE
Dashboard: Content below header, above grid not resizing right

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6689]
## Bug Description

The filter bar with results listed is not resizing correctly with the rest of the page. 

![Screen Shot 2021-03-09 at 1 16 50 PM](https://user-images.githubusercontent.com/10720454/110532161-bb166e00-80d9-11eb-870e-dfa9ef015107.png)

## Expected Behaviour

Content should remain justified. 
Search should have an enforced larger min-width. 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
@samwhale I can't reproduce this. I tried in safari, firefox, and chrome. Can you look again?
![Screen Shot 2021-03-09 at 4 05 11 PM](https://user-images.githubusercontent.com/10720454/110550676-5f57df00-80f1-11eb-8312-efc24a9762ae.png)
![Screen Shot 2021-03-09 at 4 05 06 PM](https://user-images.githubusercontent.com/10720454/110550678-5ff07580-80f1-11eb-81dd-919338615439.png)
![Screen Shot 2021-03-09 at 4 04 53 PM](https://user-images.githubusercontent.com/10720454/110550680-5ff07580-80f1-11eb-8247-08a6bae0cdd1.png)

**Comment by samwhale** [comment]
I'll look again!

**Comment by BrittanyIRL** [comment]
@csossi this one is a little goofy, but the bug is that if you resize the dashboard on 'my stories' you'll get this "gap" between 1120px to 1098px, this is because the search input is wider than the space and it's overflowing. The below link is to what we want it to do now, which is for the header to collapse gracefully when there's not enough room and then once the dashboard gets to viewport sizes of 1098px or smaller we want the width to stick at 1098px and have horizontal scroll. 

https://github.com/google/web-stories-wp/pull/6727#issuecomment-799779347

**Comment by csossi** [comment]
Verified in QA
