### ISSUE TITLE
Refactor Design Panel inputs and update logic

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#6690]
## Description

With the new Floating menu logic (#10112), many buttons will have a simple structure that's also more performant due to using specific selectors (e.g. button renders only if the value specific to that button changes, not if anything changes). The buttons, however, are quite often duplicated now since these are visually the same and also behave the same in both the floating menu and the design panel (except for multi-selection handling).

Ideally we would have a button "library" that we can just reuse anywhere so that the Design Panel would also have the new simplified logic.

This can be done in batches that can be defined once #10112 is ready.

The current design panel updating logic needs refactoring anyway, an example:
We are currently using `pushUpdate` with the second arg `true` for every input since otherwise the change is not applied at all. This seems to cause lagging as well, for example in case of text areas (Edit: the TextArea design system component now has its internal `onChange` handling which avoids lagging but is not ideal system either since the `onChange` that comes from the editor is ignored until `onBlur`). 
Additionally, if we need to trim values with `onBlur`, this currently would cause a separate history entry.

The `pushUpdate` logic should be reviewed/adjusted, if we need to use it with the second arg always `true`, it doesn't really fulfil its purpose.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by littlemilkstudio** [comment]
referenced update logic here. Hopefully it helps out this ticket!

https://github.com/GoogleForCreators/web-stories-wp/pull/11389

**Comment by littlemilkstudio** [comment]
outlined some perf exploration here. Hopefully can be used to help dictate some design decisions around the update logic rewrite as well:
#11390

**Comment by littlemilkstudio** [comment]
outlined some perf exploration here. Hopefully can be used to help dictate some design decisions around the update logic rewrite as well:
#11390
