### ISSUE TITLE
Design System: Use XS checkmark icon in toggle

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6691]
## Feature Description

The XS version of the checkmark (`CheckmarkSmall`) should be used as the checkmark in the toggle component. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

Updated icon.

**Comment by BrittanyIRL** [comment]
Follow up from #4942

**Comment by csossi** [comment]
Verified in QA
