### ISSUE TITLE
Phantom saved colors show up when switching saved color source in color picker

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6700]
## Bug Description

When switching between "Current story" and "All stories" in color picker, phantom gray colors show up.

I am unable to recreate locally, but the issue has been confirmed by multiple people (including me) on [QA environment](https://stories-new-wordpress-amp.pantheonsite.io/wp-admin/).

## Expected Behaviour

No phantom colors should appear.

## Steps to Reproduce

1. Make sure you have saved colors both in the current story and all stories (and maybe even a different number of each type)
2. Open color picker for page background
3. Switch between "current story" and "all stories" in the dropdown
4. Observe phantom gray colors appear in the list when switching

## Screenshots
![saved-color-bug](https://user-images.githubusercontent.com/637548/110564380-b1f9c100-811a-11eb-9ebc-64ed24f6802b.gif)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Followed these instructions:
Do this on main first without checking out this PR first:
1. Download this file
2. Create a new story and click Shift + Option + Command + J at the same time
3. The debug window opens. Choose "base64", paste the content of the downloaded file into the area to replace what's there and click "Load"
4. Save the story.
5. Verify that now you have multiple grey colours in the "All stories" and when you open the colour picker and switch between the Current and the All colours, more grey colours start appearing.
6. Check out this PR.
7. Verify that now there are no multiple identical grey colours under "All Stories"
8. Verify that now switching between the two modes in the colour picker does not make the pseudo colours appear.

Still getting the same error - multiple greys, etc.

**Comment by miina** [comment]
@csossi Testing now and I'm not seeing the same error on the QA environment:
![Mar-11-2021 07-47-24](https://user-images.githubusercontent.com/3294597/110741873-aea72800-8235-11eb-84d7-3d683471eacd.gif)

Can you confirm if you still see the pseudo-grey colours appearing as in [this description](https://github.com/google/web-stories-wp/issues/6700#issue-826943942)?

Thanks!

(I do see multiple grey colours still but it's not behaving buggy anymore.)

**Comment by miina** [comment]
Just realized the build didn't finish before, perhaps that was the issue and it didn't load properly in the QA environment.

**Comment by csossi** [comment]
Verified in QA
