### ISSUE TITLE
Phantom colors and lingering edit mode in saved color panel

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6701]
## Bug Description

Somehow phantom colors + lingering edit mode appeared in the saved color panel

## Expected Behaviour

This shouldn't happen

## Steps to Reproduce

_Unable to recreate. Contact @bethanylang here or in Slack._

## Screenshots
![saved-color-bug-2](https://user-images.githubusercontent.com/637548/110564844-85927480-811b-11eb-905e-d1a6e2c2086f.gif)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
This is related to duplicate saved colours and will be fixed together with #6700.

**Comment by csossi** [comment]
Verified in QA
