### ISSUE TITLE
Dashboard: Remove all DEPRECATED_THEME

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6707]
## Feature Description

Now that new designs are in, we should be able to gut everything old, this should surround the `DEPRECATED_THEME` instances in the dashboard codebase. Should also eliminate all dead old components that are now being used out of the design system instead. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

Dashboard functions as it currently does. Entirely regression test based.

**Comment by csossi** [comment]
Verified in QA
