### ISSUE TITLE
Fix Line Height and Kerning

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#671]
## Bug Description

There is an issue with the line height and kerning (letter spacing). This was discussed during grooming on March 18. 

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment]
@miina do you recall the specific issues with this one?

**Comment by miina** [comment]
@jauyong The line height and letter spacing are not working properly currently in the sidebar, these are also not supporting comma values properly currently. This issue might get fixed within #621 though, cc @dvoytenko

**Comment by dvoytenko** [comment]
Both issues are fixed. Line height couldn't accept the fractional part (now it does in #621). And the letter spacing was fixed a bit earlier: it had the wrong base and needed to be recalculated to 100% == 1em base.
