### ISSUE TITLE
Templates - the Travel cover template prevents the user from advancing to next page in the editor

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6712]
## Bug Description

When a user uses the Travel cover template, there is are a couple of extraneous boxes outside of the display area, one of which prevent the user from accessing the arrow to advance to the next page of the story.

## Expected Behaviour

User should be able to select the arrow to advance to next page in the story

## Steps to Reproduce

1. Create a new story
2. Select Template -> Cover -> Travel
3. Add another page to the story
4. Try to navigate to that next page using the arrow in the editor

## Screenshots

![bad travel cover](https://user-images.githubusercontent.com/58738530/110678562-70adf380-81a4-11eb-80bc-caf4209114ff.png)

https://user-images.githubusercontent.com/58738530/110678814-b5d22580-81a4-11eb-889b-185ca249ae7b.mp4

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
this isn't specific to templates, it's just the z-index of the pagination arrow on the canvas area of the editor.  @barklund  is this documented anywhere else?

**Comment by swissspidy** [comment]
Is this by design? 🤔  See #2814, #2463

**Comment by maxyinger** [comment]
Yea I think in general for the travel template, it would be worth updating this bg animation to one of our effects so it's more user friendly. would negate this specific instance of the issue.

That being said, I've seen this reported a couple of other times in other places (selection vs navigation precedence). I think it's just one of those things that's tricky either way. Feels like more of UX work to me than us flipping it back n forth on engineering side

**Comment by BrittanyIRL** [comment]
Thanks, @swissspidy and @littlemilkstudio - with that info, this is probably ok to let sit and should resolve with the updated templates that @ivayloklissarov is working on.

**Comment by BrittanyIRL** [comment]
This will no longer be an issue with new template designs

**Comment by BrittanyIRL** [comment]
![fixed](https://user-images.githubusercontent.com/10720454/117865326-b5a8e180-b24a-11eb-8c0d-d594fa6a3b5d.gif)

Indeed it is fixed, closing.
