### ISSUE TITLE
Incorrect padding on Publish/Update buttons when issue icon presented

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6716]
## Bug Description
originally reported by Tad

Internal right padding in the “Publish” and “Update” buttons is inconsistent with the internal left padding when there’s an issues icon.

## Expected Behaviour

right padding should be consistent

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
The screenshot in this issue seems to be for the RTL, there is a separate issue for RTL though: #6661 
Is this issue for LTR or RTL? @bmattb

**Comment by miina** [comment]
@bmattb FYI Pulled this into sprint since the Publish button needs some new style updates anyway.

Edit: Removing the screenshot since it was not related to this issue.

**Comment by csossi** [comment]
Verified in QA
