### ISSUE TITLE
Colour picker panel is cut off from window

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6719]
## Bug Description

If window is not high enough, color picker panel gets cut off at the bottom and doesn’t allow users to scroll through it.
![image17.png](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/d5773fc0-6917-4a3b-935a-206444aec078)
## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
