### ISSUE TITLE
Colour picker: Input/buttons styling incorrect

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6721]
## Bug Description

The focus styles need to be updated for some of the buttons. Some focus styling is getting hidden (the focus styling is a box shadow so there needs to be some extra padding)

## Screenshots
![image7](https://user-images.githubusercontent.com/58738530/110701386-1a9a7980-81bf-11eb-9a02-f5c2cdff4b7e.gif)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by Ayushsunny** [comment]
Hello @barklund I wanna work on this issue

**Comment by miina** [comment]
Hey @Ayushsunny, sorry for the long delay in answering and thanks for the interest. You're more than welcome to work on this issue!

**Comment by csossi** [comment]
Verified in QA
