### ISSUE TITLE
Grid view  tooltip lingers after exiting Grid view

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6723]
## Bug Description

Grid view pop up lingers after exiting grid view

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
@bmattb does this still happen?

**Comment by miina** [comment]
It's still happening.

The issue seems to be that the tooltip is being shown on `onFocus` and it looks like that's what's happening once closing the modal -- the button is set to focus again. Not sure what would be a good solution here. 🤔

**Comment by swissspidy** [comment]
Setting focus back to the button seems kinda expected from an a11y perspective.

**Comment by miina** [comment]
It is expected yep, so not sure if there's a good solution here to focus but not show the tooltip -- we shouldn't remove showing the tooltip when focusing either.

**Comment by swissspidy** [comment]
Indeed. In that case I'd say this is working as intended.
