### ISSUE TITLE
Size & Position panel doesn't accept keyboard arrow input for stepping in numeric fields

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6724]
## Bug Description

Arrow keys for stepping don’t work in numeric inputs in this panel (but do in numeric inputs in other panels)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Related: #6793 #6803 #6828 

I feel like this can all be done in one issue since it seems to be a fix needed for the numeric input generally (or related at least since these all use numeric input but it's not working as expected)
Thoughts @barklund?

**Comment by miina** [comment]
@bmattb @barklund FYI I've changed the story points of this to `1`. I've also pulled #6793 #6803 #6828 to this Sprint with each of these assigned `1` point -- all of these related issues will be fixed together within #6890.
