### ISSUE TITLE
Adding a link to a video element is not possible

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6725]
## Bug Description

Reported by Tad during bug bash 1.5.0-A, however subsequent attempts to reproduce this have proven challenging

> If I select a video element and try to add a link, I can select the Link input text but can’t type. If the user can’t add links to video elements, maybe we should disable the Link panel altogether for that use case?

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
I am not able to reproduce this, however there are some prop type warnings for the link element. Perhaps that is related.

<img width="974" alt="Screenshot 2021-03-11 at 14 06 28" src="https://user-images.githubusercontent.com/841956/110795557-44af7280-8277-11eb-8292-aba2baa8efcd.png">

**Comment by bmattb** [comment]
no longer reproducible
