### ISSUE TITLE
Opacity Default on Text Box Colouring

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#673]
## Bug Description

The opacity is defaulted to 0% for the text box colouring. This means when you select a colour you don't see any changes right away as you might expect to and think that the feature is broken. You actually have to change the opacity from 0% AND select a colour to see any change. Having the default set at 0% makes this harder to use and figure out. 

![image](https://user-images.githubusercontent.com/5874851/77204779-dacc1500-6ac9-11ea-835a-ca6506c564ee.png)

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
This will most likely be fixed by #684, as it will also require the user to actively switch to a background (and default it to a non-transparent one).
