### ISSUE TITLE
Video playback button lacks contrast on darker videos

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6731]
## Bug Description

On the canvas we display a custom playback button on videos.

This button is hardly noticeable when the video itself is quite dark, as it then has almost the same color as the playback button

## Expected Behaviour

The button should have better contrast

## Steps to Reproduce

1. Add darker video to canvas

## Screenshots

<img width="711" alt="Screenshot 2021-03-11 at 11 38 27" src="https://user-images.githubusercontent.com/841956/110774622-4d477f00-825e-11eb-9e73-f59dd0c231f5.png">

## Additional Context

- Plugin Version: 1.4.0
- WordPress Version: 5.7.0
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
this will be addressed with the implementation of the updated design for this button in #6380
