### ISSUE TITLE
Working with Layers on the Page

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#674]
## Bug Description

I’m not able to grab the picture behind the text box even though the borders of each element are staggered. In order to do so, I would have to change focus to the picture using the layers panel or I would have to move the text box out of the way to be able to grab the image. 

![image](https://user-images.githubusercontent.com/5874851/77205008-5cbc3e00-6aca-11ea-91da-98bc9d494b1d.png)

Another example:
![image](https://user-images.githubusercontent.com/5874851/77205216-c63c4c80-6aca-11ea-86b6-320709eea51c.png)

## Expected Behaviour

I should be able to use my mouse because the border of the text box is staggered with the image. 

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by dvoytenko** [comment]
This is not quite clear. But if the issue is that a frame up top prevents the pointer from grabbing an element behind it, that seems as WAI?

**Comment by jauyong** [comment]
Issue appears to be fixed. closing.
