### ISSUE TITLE
Minimum height of the saved colours panel is incorrect

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6740]
## Bug Description

When I initially opened up the saved colours panel I was unable to see all the panel content and had to manually use the drag handles to resize the panel to be able to see that. 

![image11](https://user-images.githubusercontent.com/58738530/110851540-2cdbec80-827f-11eb-8490-34a29d3ddd17.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Only seeing the one key here:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/4fb8f744-f87b-4c0a-92da-0ede903f6f2d)

**Comment by samwhale** [comment]
Thanks for flagging this @csossi. I labeled the instructions incorrectly 🤕 

To see the new value in local storage we need to actually show the panel. So new steps:
1. Add an element that can be styled with a color (like the text element)
2. the `saved colors` panel should should up
3. Should see the new value in local storage

**Comment by csossi** [comment]
Verified in QA

![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/21514f4a-1297-4c27-815c-835397c0f292)
