### ISSUE TITLE
Saved Colour Panel: Elements missing new focus styling

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6741]
## Bug Description

Looks like there’s some elements that don’t have the new focus styling: The heading, the pencil icon button, and the ‘add’ color button. The colors have the correct focus styling.

![image14.gif](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/1052f80f-48e5-481c-864a-9b6bbc328776)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Looks like this got fixed meanwhile already, closing.
