### ISSUE TITLE
Duplicate "more" icon on social sharing config

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#6743]
## Bug Description

Sharing configuration lists a duplicate "more" icon in mobile devices.

## Expected Behaviour

One 1 "more" icon should be configured.

## Steps to Reproduce

1. Open a Web Story (example [story URL](https://sgsite.cmsdevrel.com/web-stories/example-story-1/)) on BrowserStack or on any of the following devices: iPhone 11, iPhone 12, Galaxy S9
2. Wait until the last slide to see social sharing options pop up. Notice duplicate "more" icon. 

## Screenshots
![image](https://user-images.githubusercontent.com/66372350/110851473-146bd200-827f-11eb-909c-ce2343810c67.png)
![image](https://user-images.githubusercontent.com/66372350/110852226-17b38d80-8280-11eb-873e-c5dd36feaebb.png)

## Additional Context

- Plugin Version: 1.4.0
- WordPress Version:
- Operating System:
- Browser: Safari, Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Not sure, but perhaps this is better reported upstream.

**Comment by LuckynaSan** [comment]
Done (see https://github.com/ampproject/amphtml/issues/33220)!
