### ISSUE TITLE
Border Panel & Corner radius panel : Lock icon missing tooltip

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6744]
## Bug Description

The Lock toggle is not presenting a tool tip on mouseover

![image33](https://user-images.githubusercontent.com/58738530/110854533-16d02b00-8283-11eb-83c1-2ada78abb98e.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
