### ISSUE TITLE
Borders suppressed on element with move animation

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6745]
## Bug Description

 An element in a standard page layout with a move animation applied cannot have a border shown outside the element itself (see the border only visible in the carousel thumbnail and in the rounded corners):

![image27](https://user-images.githubusercontent.com/58738530/110855094-eb9a0b80-8283-11eb-8c83-48c9c1a981e6.png)

## Expected Behaviour

Borders should be shown as expected.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
I am not clear if this if for PEA or PROMETHEUS, apologies if I've incorrectly assigned it.

**Comment by BrittanyIRL** [comment]
Thanks, Matt! I'm sure Morten's going to have a better knowledge of this than me.

**Comment by BrittanyIRL** [comment]
`Move` was only exposed to the editor as a custom animation, in this latest release of 1.7 when we updated all of the templates (#6966 ) those custom animations were removed from templates. I just retested and the border's staying intact on all animations now. Passing to QA to confirm.

**Comment by csossi** [comment]
Verified in QA
