### ISSUE TITLE
Layers - Shape preview is distorted

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6746]
## Bug Description

The preview of the layer shape is distorted, in this example I have a round circle which is appearing oval in the preview icon 
![image15](https://user-images.githubusercontent.com/58738530/110856845-256c1180-8286-11eb-8d3b-5b65c2413a75.png)

## Expected Behaviour

The icon in the shape layer should display a shape its the original transformation but with proper color applied.

So, if you add a heart shape to the canvas, make it green, rotate it, and stretch it, the layer panel should display a green heart not rotated, not stretched, but in the original size and shape.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
