### ISSUE TITLE
Layer Panel: Thumbnail for video shows asset title instead

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6747]
## Bug Description

This was originally reported by @choumx during bug bash - I am unable to duplicate this 
The placeholder/fallback thumbnail for videos displays text of the asset title.

If the image cannot be loaded, a proper replacement image should be displayed rather than HTML image alt fallback text.
![image20](https://user-images.githubusercontent.com/58738530/110857829-4f720380-8287-11eb-9052-82026d3ac6ca.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
This happens when there is no poster image. What you see is the image's **alt** text.

This will be fixed by #6738.

Suggest to close in favor of that.

**Comment by barklund** [comment]
@swissspidy, can you confirm that this ticket is now irrelevant?

**Comment by swissspidy** [comment]
Yep!

When there is no poster we now display an icon instead:

https://github.com/google/web-stories-wp/blob/416ebe3fddda1e32e20c5233a88937951107c122/assets/src/edit-story/elements/video/icon.js#L34-L38
