### ISSUE TITLE
Resizing an image over the next page navigation arrow prevents navigation to that next page.

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6748]
## Bug Description

If you place an image in the editor workspace, and resize it over the navigation arrow, you will no longer be able to use that arrow to navigate to the next page in the story.

Note that the page actions menu below the page is always on top of frames, so page navigation should similarly be.

![image23](https://user-images.githubusercontent.com/58738530/110858538-3027a600-8288-11eb-96e5-815fd5dcad71.gif)

## Expected Behaviour

The navigation arrows should always be usable.

## Steps to Reproduce

1. In a page, add an image 
2. Resize the image to extend over the next page navigation arrow.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Closing as this is working as expected now.
