### ISSUE TITLE
UX for Managing Background

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#675]
## Bug Description

I was playing around and looking for a quick easy way to swap an image on the page with the currently selected background. Via the layers panel, I tried dropping an image onto the Background (locked) layer to see if it would switch, but it didn't. Maybe that could be an easy shortcut to update the background? 

![image](https://user-images.githubusercontent.com/5874851/77205473-52e70a80-6acb-11ea-94aa-45be0edf0cef.png)

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by pbakaus** [comment]
+1, would be a nice bonus feature.

**Comment by samitron7** [comment]
lol - but the drop target to this is so much smaller than the page and you have to really drag a long distance to get to the layers panel. Also not easy to make discoverable. I have to veto this feature unless everyone wants it.

**Comment by pbakaus** [comment]
To me, this is one of those P3's that is a very delightful surprise if discovered, doesn't do any harm, but also is definitely not important :)

**Comment by samitron7** [comment]
Closing this ticket. In observing our users, this would be an incredibly hard to discover feature and its not worth out energy to build feature plus create ftue for.
