### ISSUE TITLE
Dashboard: Template "See details" button improvements 

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6752]
## Feature Description

Noted in bug bash 1.5.0-A by @o-fernandez about the "see details" button on Explore Templates seen when you hover or focus on a template in the grid: 
> Seems a bit bland or "unfinished" as a user.  

![Screen Shot 2021-03-09 at 1.38.40 PM (1).png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/c760120a-e450-455b-aef8-b19eb74c07af)

The question here is, is there something to do here that will make this feel more polished?

## Additional Context

This is something that has no updated designs in Figma so eng ( @BrittanyIRL ) improvised off of the hover/focus of the stories grid for 'use template' to be the same CTA/Primary button and figured that the tertiary style button would be ok for the 'see details' since it's not as important and doesn't draw a way from the preview you're watching as you hover. 

Just to note, Brittany and Tadeu discussed "offline", design is OK with how this is currently implemented for the time being. So i've set this as a p3.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1) New designs for the "See details" button of Explore Templates template hover 
2) Implement said new design

**Comment by BrittanyIRL** [comment]
@agingoldseco took a look at this and DM'd me an update to try out. 

<img width="880" alt="Screen Shot 2021-11-16 at 3 03 53 PM" src="https://user-images.githubusercontent.com/10720454/142485081-7cf1d175-c7a6-4e3c-b28b-35032129c2d4.png">


(left is hover, right is focus)
<img width="783" alt="Screen Shot 2021-11-16 at 3 41 51 PM" src="https://user-images.githubusercontent.com/10720454/142485088-8e413734-d11e-42f1-b609-cf76b155350a.png">

**Comment by BrookeGraham** [comment]
Waiting to hear back from @agingoldseco. Transparent background may not be the best solution for all templates.
<img width="239" alt="white bg" src="https://user-images.githubusercontent.com/1820266/142675791-e3b3eca8-57a0-476a-8d14-2e612a984eb7.png">

**Comment by BrittanyIRL** [comment]
This was discussed in slack: https://xwp.slack.com/archives/C01ESBB8ZN1/p1637686477021000?thread_ts=1637347640.010700&cid=C01ESBB8ZN1 

We're going to update the see details button to be the `tertiary` button in the DS and override the default background color to be white.
