### ISSUE TITLE
`Switch to list view` tooltip being hidden in RTL

### ISSUE THREAD

**Issue by samwhale** [GoogleForCreators/web-stories-wp#6755]
## Bug Description

Tooltip for `Switch to list view` icon button falls off screen:

## Expected Behaviour

Tooltip should not be hidden by edge of screen

## Steps to Reproduce

1. Switch to RTL
2. Hover the icon button

## Screenshots

![oops](https://user-images.githubusercontent.com/22185279/110988584-f7420c80-832d-11eb-9f0b-3df905228b0b.gif)

## Additional Context

- Plugin Version: 1.5.0-alpha
- WordPress Version: 5.7
- Operating System: macOSX BigSur 11.2.2
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
Relates to #6663

**Comment by samwhale** [comment]
This and #6663 are the same bug. Both are fixed by PR #6887
