### ISSUE TITLE
Design System: Update Dialog Background 

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6757]
## Feature Description

Styles for dialog have been updated slightly after initial implementation. 
Updates: 
- Dialog bg needs to be inverted, (so instead of colors.fg.primary, it's colors.inverted.fg.primary) 
- Dialog "scrim" (modal opacity) needs to be updated: 
  - Dark should have 32% opacity, dark base 
  - Light theme should have 8%, light base 

## Additional Context

Modal content needs to respect the inversion. This probably means we need to wrap dialogs in their own theme provider so that everything inside it is actually aware that it should follow the inversion colors, otherwise it's going to get weird. 

Based on this slack thread: https://xwp.slack.com/archives/C01ESBB8ZN1/p1615500873111300?thread_ts=1615487265.109400&cid=C01ESBB8ZN1

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

Dialog colors are updated to be inversion of current theme. 
Update design system and give all dialogs necessary update.

**Comment by BrittanyIRL** [comment]
Testable at same branch as #6753

**Comment by csossi** [comment]
Tested according to 6753 (PC/Chrome)

Not seeing the appropriate "permissions" message:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/cb54f52b-500f-4fa3-b2ff-37d5609470b8)

Not seeing the appropriate video optimization mesage:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/7ad41089-18b9-4523-9739-fe2318111cae)

**Comment by BrittanyIRL** [comment]
@csossi  For video optimization you need to enable the flag called `Transcode and optimize videos before upload` in the general section of experiments settings. 

I'm actually unsure how to get the permissions dialog to trigger, i tested manually. @barklund @miina  - do you know how to get the dialog for upload permissions to trigger? https://user-images.githubusercontent.com/10720454/110987831-e9d85280-832c-11eb-9828-88d791ecbd48.png

**Comment by csossi** [comment]
Still not seeing message re: video optimization:
https://share.getcloudapp.com/7KuPdlGp

video optimization checked in dashboard settings and experiment flagged as well

**Comment by BrittanyIRL** [comment]
@csossi  sending this back to you to try once more. there's a local storage setting that needs to be removed for the dialog to trigger. To see video optimization dialog do the following: 

- delete `web_stories_video_optimization_dialog_dismissed` from local storage
- enable experiment for video optimization
- enable video optimization in dashboard settings
- new story - drag in a video

**Comment by csossi** [comment]
Verified in QA
