### ISSUE TITLE
Design System: Add Quaternary Button

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6758]
## Feature Description

Design has added a quaternary button style in response to the "Create new story" button on the dashboard which has just been its own thing. 

Add this new button style to the design system: https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3438%3A125786
Swap out custom button in dashboard for this. 

![Screen Shot 2021-03-12 at 1 44 01 PM](https://user-images.githubusercontent.com/10720454/110996551-55282180-8339-11eb-9d22-234d36dca6a1.png)

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
@csossi the only thing this is in QA for is verifying the new style of the "create new story" button on the dashboard.

**Comment by csossi** [comment]
Verified in QA
