### ISSUE TITLE
Request for bigger Page Icon in Carousel

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#676]
## Bug Description

When trying to add a new page to my story, my eye misses the + icon. I've clicked on duplicate a few times thinking it was the new page button. Perhaps it's because the + icon has a lot less “weight” than the trash can and duplicate icon?

![image](https://user-images.githubusercontent.com/5874851/77205583-8de93e00-6acb-11ea-89a9-239d08cf867a.png)

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
New icons will be implemented in #6204.
