### ISSUE TITLE
Exiting the Edit Background Mode

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#678]
## Bug Description

When I enter the “edit background” mode, I struggle to exit. I naturally try to exit by clicking outside into the black area but that doesn't exit. I have to click on the greyed out areas of the image to exit. I feel like clicking on anything other than the image should exit the background edit mode. 

![image](https://user-images.githubusercontent.com/5874851/77205842-149e1b00-6acc-11ea-854a-de63a61a7029.png)

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by dvoytenko** [comment]
Maybe. /cc @pbakaus. There are, however, some relevant settings in the design panel that the user might want to set while the while still in the edit mode. Less controversial, perhaps, is going to the elements panel should cancel edit mode. Alternatively, we could cancel edit mode upon any interaction and if user needs to use the design panel, they would just have to double-click to edit again after.

**Comment by pbakaus** [comment]
This has been bugging me as well, tbh. Definitely in favor of exiting whenever you click outside the edit mode. I'd be OK carving out an exception for the design panel, or even better, only the controls that actually do something to the inner element.

**Comment by wassgha** [comment]
Re-opening this, closed by mistake
