### ISSUE TITLE
Settings: Add additional helpful messaging for AdSense

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#6782]
## Feature Description

From Support: 
Just want to quickly report on the commonly asked questions around ads. 

Generally, users inquire about how long would it take before ads will display. Then, they'll ask us to confirm if the configuration is correct, or if a script needs to be added to the page before they can see ads, etc. I've also noticed that users do frequently ask what a slot ID is or if it is required. 

Based on that, I would suggest that we consider providing additional helpful messaging on the settings page. For example:
After the users have inserted their IDs, include a message indicating, "AdSense has been successfully configured" 
Include a message indicating the configuration has been set and to please allow additional time until the ads can be served

Here is the list of ad topics where these questions were asked: 
https://wordpress.org/support/topic/web-stories-monetisation/
https://wordpress.org/support/topic/ads-settings/
https://wordpress.org/support/topic/amp-story-auto-ads/
https://wordpress.org/support/topic/ads-not-showing-62/#post-13943743
https://wordpress.org/support/topic/1-3-0-monetization-option-not-visible-under-settings/

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
Some simple tweaks that I think may help here. 

- Under "Enter your Slot ID" for AdSense, update the copy to add after Example: 1234567890 the following: 
> [Copy data-ad-slot from your ad unit for Web Stories](https://support.google.com/adsense/answer/10175505). The same ad unit will be used for all of your Web Stories. 

- After "Learn more about how to monetize your Web Stories using AdSense." add: 
> Once configured, AdSense will determine where and how to insert ads into the story. Consult [AdSense Help](https://support.google.com/adsense/) for any further assistance. 

@swissspidy @LuckynaSan do you think this would help? Any other ideas? 

![image](https://user-images.githubusercontent.com/13389997/117158175-30768600-ad8d-11eb-8577-9e925e471db1.png)

**Comment by swissspidy** [comment]
It would be good to understand how the Web Stories ad unit setup works in the AdSense dashboard, so we can better tailor the messaging to this experience.

----

> * Under "Enter your Slot ID" for AdSense, update the copy to add after Example: 1234567890 the following:
> 
> > [Copy data-ad-slot from your ad unit for Web Stories](https://support.google.com/adsense/answer/10175505). The same ad unit will be used for all of your Web Stories.

Note that the "how to monetize your Web Stories" link already points to this page. I don't think we should link to it twice.

(Aside: [the Web Stories page](https://support.google.com/adsense/answer/10175505) tells users to modify their HTML `<head>` and insert the ad code manually — something that is not needed with this plugin as we do this automatically. Perhaps some clarifying note would be good so)

I'd use a different link that explains how to get the code:

> Copy the slot ID from [your ad unit’s code](https://support.google.com/adsense/answer/9274019). The same ad unit will be used for all of your Web Stories.

----

> * After "Learn more about how to monetize your Web Stories using AdSense." add:
> 
> > Once configured, AdSense will determine where and how to insert ads into the story. Consult [AdSense Help](https://support.google.com/adsense/) for any further assistance.
> 

I recommend using similar wording as already used in the AdSense help.

[Example](https://support.google.com/adsense/answer/9261309):

> Once configured, Google will automatically show ads in your stories at optimal times when they're likely to perform well and provide a good experience. Consult [AdSense Help](https://support.google.com/adsense/) for any further assistance.

**Comment by o-fernandez** [comment]
^ I'm OK with those suggestions, @swissspidy

**Comment by swissspidy** [comment]
Awesome. Any UX input needed here? We're just adding two paragraphs.

**Comment by o-fernandez** [comment]
I wouldn't block on UX, want to go ahead and make the changes? We can review it ourselves and so long as it looks/reads reasonably launch this. @swissspidy

**Comment by spacedmonkey** [comment]
@o-fernandez @swissspidy 

Is this what is expected. 

<img width="728" alt="Screenshot 2021-05-12 at 16 18 10" src="https://user-images.githubusercontent.com/237508/118000434-b66e7000-b33d-11eb-992c-9429799f05c8.png">

**Comment by o-fernandez** [comment]
@spacedmonkey there are two periods/dots at the very end of the slot ID help text, otherwise looks great!

**Comment by csossi** [comment]
Verified in QA
