### ISSUE TITLE
Blocks: Story not playing from beginning in lightbox

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6787]
## Bug Description

During the bug bash @BrittanyIRL created a post with a block of embedded stories and noted that one of the stories, when clicked, did not show the correct first page of that story.

It should be noted that this story was a copy of an exisitng template (fashion), and that I was unable to reproduce the issue during the creation of this bug, however @littlemilkstudio verified that this happened for him as well.

## Expected Behaviour

Clicking on the story should present the user with the story, starting on the front page

## Steps to Reproduce

1. Create a story eg https://stories-new-wordpress-amp.pantheonsite.io/2021/03/16/brittany-bug-bash-1-5-0-b/
2. Embed the story into a post/page using the Grid layout option eg https://stories-new-wordpress-amp.pantheonsite.io/2021/03/16/brittany-bug-bash-1-5-0-b/
3. Click on the associated story and observe that the first page shown is incorrect

## Screenshots

![image15.gif](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/89b0880f-afbb-4b83-95db-b33f5c7cea00)
## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
@bmattb @BrittanyIRL @o-fernandez  As mentioned on the doc, the block shows the story's poster image. If you don't have a poster image you can't/won't see a preview. So this is working as intended. In the screenshot it looks like no poster was set for the story.

Suggesting to close this as it's working as intended.

**Comment by maxyinger** [comment]
Yea, I'm wondering if I was happening upon a malformed story that someone was messing around with in staging. If y'all can't reproduce it I bet I was looking at weird data instead of weird behavior

**Comment by bmattb** [comment]
I don't believe that is the error being flagged. If you see the screenshot, the first page presented in the actual story isn't the story's first page. But @littlemilkstudio point above may still hold true

**Comment by swissspidy** [comment]
Here's a story that explains the difference between the **poster image** and the **cover page**: https://wp.stories.google/stories/poster-and-cover/

In the screenshot above I see the fashion story with a nice **cover page** (= the first page of the story). But it does not have a **poster image** (which needs to be set in the Document panel).

The block displays the **poster image**, _not_ the cover page.

**Comment by swissspidy** [comment]
Wow, sorry about that 🤦  after re-reading three times I finally got that it's about the story not rewinding. Apologies!

Unfortunately, I can't really reproduce that behavior either.

Especially since we specifically implemented a change yesterday to leverage a new amp-story-player feature to make sure users always start on the first page when opening the lightbox (See #6771).

If this doesn't work as expected for everyone, it's most likely out of our hands as it would require an upstream change to the amp-story-player.

Still suggesting to close as it cannot be reproduced
