### ISSUE TITLE
Controlling the Overlay Color

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#679]
## Feature Description

This is a follow up to this [slack conversation](https://xwp.slack.com/archives/CCCAUAH6F/p1584687592232600)

**[UX](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=6531%3A49)**

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
1. Expose the color swatch when you apply an overlay 
2. If you toggle to radial in the color picker then it should also toggle the radial in the design panel. ie. They should map. 
![image](https://user-images.githubusercontent.com/5874851/77206358-246a2f00-6acd-11ea-801e-124e2cc90c00.png)

**Comment by barklund** [comment]
Duplicate of #1207. @jauyong?

**Comment by barklund** [comment]
We also need to consolidate priority on this one - it's P0 on Fishfood feedback.

**Comment by jauyong** [comment]
Closing in favour of #1207
