### ISSUE TITLE
Text Style Panel: Cannot change the font size value using arrow keys

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6793]
## Bug Description

A user cannot use the arrow keys to step through the font size values as expected

## Expected Behaviour

Arrow keys should allow the user to step through the values up/down

## Screenshots

![image30](https://user-images.githubusercontent.com/58738530/111373694-9f2f4100-8672-11eb-9705-9b79008c9310.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Related: #6828 (Again -- probably we should do this in the `NumericInput` directly)
