### ISSUE TITLE
Text styles panel - focus on colour picker needs more padding

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6795]
## Bug Description

Focus around the colors (after adding a color) is getting cut off, needs some more padding

## Screenshots

![image27](https://user-images.githubusercontent.com/58738530/111374355-62b01500-8673-11eb-9280-a209355c07ec.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Closing as this seems to be fixed now.
