### ISSUE TITLE
Color picker input fields wrong style

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6797]
## Bug Description

In the colour picker for text styles panel there is the incorrect style on the inputs.

Please update to design system components.

![image18](https://user-images.githubusercontent.com/58738530/111377516-1d8de200-8677-11eb-82f5-2b8c88d17d75.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
Let's see if we can use our own, and if not, change the built in ones.

**Comment by csossi** [comment]
Verified in QA
