### ISSUE TITLE
Text Styles panel - Colour picker - Current story dropdown incorrect location

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6798]
## Bug Description

In the colour picker of the text styles panel the dropdown for the Current Story is not in the correct location 

![image28](https://user-images.githubusercontent.com/58738530/111378078-c63c4180-8677-11eb-9f89-e56c36189ca7.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
Fixed for now, but will be reworked again once the simplified dropdown is implemented during #6415.
