### ISSUE TITLE
Video Trimming

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#680]
## Feature Description

For videos, I’d like to be able to choose the start and end time within any uploaded video to be able to cut the video displayed in my story.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by diegovar** [comment]
Can you link to the designs or any PRD parts that mention this functionality?

**Comment by jauyong** [comment]
@diegovar I don't think this has been spec'd at all. I originally filed this as a feature request a while back. 
@o-fernandez I see its a TBD P1 in the CUJ sheet in row 18. Are there further details for this feature right now?

**Comment by o-fernandez** [comment]
I just looked through the spec and [this is all I could find](https://docs.google.com/document/d/1EQ12sD4a1plmMeBu7YMWOdUSg0FeegB9qi2_OlV3Tp0/edit#bookmark=id.3oa4doedhryq). Needless to say, no real spec for this yet (neither PM nor UX) so adding the necessary labels for Sam and I to take a look. 

@diegovar is this something you were planning to work on in the near future? If so, we may need to figure out how to prioritize to get the right specs to you.

**Comment by diegovar** [comment]
I was trying to better understand which issues were available to grab and which ones need more info or are blocked. My objective is for the issues tagged as "media" to be in a good enough state so that it's clear whether an issue can be grabbed before having to open and read the discussion.

**Comment by o-fernandez** [comment]
Ok got it. For now, if you find anything that is not spec'd, just add the "Needs More Info" or "UX Needed" labels and those are understood to need either a product spec or UX. I'll try to clean this up somewhat as well, so hopefully things are actionable for you!

**Comment by aaskedall** [comment]
<img width="360" alt="description" src="https://user-images.githubusercontent.com/4030811/131363443-8b5a5edf-bd51-4fc1-9a45-a6232fb07959.png">
<img width="344" alt="video settings trim" src="https://user-images.githubusercontent.com/4030811/131363444-65487e01-6823-4fa4-ba16-ce162bb036dd.png">
<img width="1142" alt="If video is smaller than canvas" src="https://user-images.githubusercontent.com/4030811/131363447-b614446f-4ae6-48a5-8a11-43595f3e3e90.png">
<img width="1142" alt="full screen editor" src="https://user-images.githubusercontent.com/4030811/131363448-c368aeb0-1b91-4f88-b9a3-e49ada1f5f3f.png">
<img width="17" alt="trim" src="https://user-images.githubusercontent.com/4030811/131363451-05fd8c07-7858-4a98-a666-8abe7a7eee04.png">

**Comment by aaskedall** [comment]
[Video Trimming.fig.zip](https://github.com/google/web-stories-wp/files/7077849/Video.Trimming.fig.zip)
