### ISSUE TITLE
Layers Panel - Panel view is truncated and requires resizing

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6800]
## Bug Description

Layers panel is cutted off at the bottom. It should be expanded a bit more so users are able to see all the elements.

## Expected Behaviour

Users should be able to see all the layers or a scrollbar to be able to view all layers

## Screenshots

![image9](https://user-images.githubusercontent.com/58738530/111472966-e5cb7c80-8700-11eb-8aa4-c8d9bc083619.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
Currently, it keeps the height you set it to - like the other resizable panels. If we want to change that behavior, we need UX guidance.

**Comment by BrittanyIRL** [comment]
Out of date, layers panel has been pulled out to be opposite sidepanel.
