### ISSUE TITLE
Link Panel - Brand icon tool tip is misplaced 

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6801]
## Bug Description
reported by @ivayloklissarov :
Tooltip in the Link section seems a bit off. Should be centered like the other ones currently in the design panel.

![image29.png](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/8e4c93bf-ee62-495d-a70b-81f7aca9e8a4)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by ivayloklissarov** [comment]
We should ignore my comment concerning the tail. They should not have tails, sorry for that. We should just fix the alignment if possible.

**Comment by bmattb** [comment]
updated the description, no problem

**Comment by swissspidy** [comment]
There's no tooltip there anymore, closing.
