### ISSUE TITLE
Text panel - cannot change the Position input value using arrow keys

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6803]
## Bug Description

We should be able to change the position input value with the up and down arrow.

## Screenshots

![image24](https://user-images.githubusercontent.com/58738530/111477067-1e6d5500-8705-11eb-8fcc-2530b2bf3667.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Related #6828 -- maybe the `NumericInput` needs to be updated.

**Comment by csossi** [comment]
Verified in QA
