### ISSUE TITLE
Text Panel - Pill styling is incorrect

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6805]
## Bug Description

The styling on the Fill / Highlight pills is incorrect:

- Focus border overlaps on pills
- ~Inner box shadow is the default black but should be the theme.colors.bg.secondary of the panel~ to be fixed in #6858.

## Screenshots
![image26](https://user-images.githubusercontent.com/58738530/111478426-73f63180-8706-11eb-98a2-dbdeba950504.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Note: The inner box-shadow should actually be transparent ideally -- so that it could be used independently of the background colour changes.

Edit: Looks like that's not possible currently, see [this conversation](https://github.com/google/web-stories-wp/pull/6817#discussion_r597762926)

**Comment by miina** [comment]
Added an issue for fixing the focus style generally since this seems to be happening across all the panel: #6858

**Comment by BrittanyIRL** [comment]
<img width="320" alt="Screen Shot 2022-01-11 at 1 30 08 PM" src="https://user-images.githubusercontent.com/10720454/149016624-f35ad496-de1c-4313-a21f-825846274662.png">

Fixed
