### ISSUE TITLE
Add a message when text sets are empty

### ISSUE THREAD

**Issue by samwhale** [GoogleForCreators/web-stories-wp#6806]
## Feature Description

We should show a message or image to the user letting them know when there are no text sets. Currently the panel is empty when there are no text sets.

## Alternatives Considered

none

## Additional Context

<img src="https://user-images.githubusercontent.com/22185279/111498831-efa4ae00-8707-11eb-9a23-4117f4c39f69.png" width="500px" />

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
This would be good to get some input on from design. 

@aaecheverria @tmagalhaes-huge @samitron7 could we request a mock for an empty state in text sets?

**Comment by BrittanyIRL** [comment]
I think we can move forward with this relying on the 'empty' state of the media search.

So we can copy the same desert svg (that's in the design system already) and just say there's no text sets currently available. Something similar to the no search results on the dashboard. 

![Screen Shot 2021-07-06 at 12 22 49 PM](https://user-images.githubusercontent.com/10720454/124655668-03118b80-de55-11eb-96ca-d37ea079d46e.png)

**Comment by csossi** [comment]
Hi @samwhale - Read the qa instructions in 8825 and don't know how to edit that code directly. On thing I did notice is that I see the "no text available" state when I turn on "Match fonts from story" when there is no actual text in the story:
![image](https://user-images.githubusercontent.com/16945664/131266984-747447cc-265f-4cc6-b9fe-fb7385b33b65.png)

So I am seeing the new "no text sets" message, but am unsure if that satisfies testing here

**Comment by samwhale** [comment]
> Hi @samwhale - Read the qa instructions in 8825 and don't know how to edit that code directly. On thing I did notice is that I see the "no text available" state when I turn on "Match fonts from story" when there is no actual text in the story:
> 
> So I am seeing the new "no text sets" message, but am unsure if that satisfies testing here

This satisfies testing too and it's a way better way to test it. Nice find @csossi !

**Comment by samwhale** [comment]
> > Hi @samwhale - Read the qa instructions in 8825 and don't know how to edit that code directly. On thing I did notice is that I see the "no text available" state when I turn on "Match fonts from story" when there is no actual text in the story:
> > So I am seeing the new "no text sets" message, but am unsure if that satisfies testing here
> 
> This satisfies testing too and it's a way better way to test it. Nice find @csossi!

@BrittanyIRL maybe we should change the message here when trying to match a font in the story and there's no text in the story?

**Comment by BrittanyIRL** [comment]
> maybe we should change the message here when trying to match a font in the story and there's no text in the story?

great idea! yes!

**Comment by samwhale** [comment]
I'll fix that up real quick 👍

**Comment by samwhale** [comment]
@csossi should see new text for the test case that you tested: 
<img src="https://user-images.githubusercontent.com/22185279/131381014-0b5231df-1e4a-4cdc-8bd7-1381958914c0.png" height="300px" />

**Comment by csossi** [comment]
Verified in QA
