### ISSUE TITLE
Text Presets sometimes crash the Text panel

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#6807]
## Bug Description
Sometimes when opening the text panel, the panel crashes with the following error:
![Screenshot 2021-03-17 at 10 21 16](https://user-images.githubusercontent.com/3294597/111504738-3e723800-8748-11eb-8758-1bd8f95f8037.png)

It seems to happen due to this being `undefined`:
https://github.com/google/web-stories-wp/blob/5ac7794a11a2aa8734b2b573540f7afcd5638b08/assets/src/edit-story/components/library/panes/text/textSets/textSetsPane.js#L103

Looks like the text sets are loaded only when switching to that pane, not before. So when switching, it’s not ready yet and thus gives `{}` (at first). And trying to get `editorial` (the default visible text sets) from `{}` => `undefined`.

We should make sure the code is not using the text sets before they're ready.

## Expected Behaviour
The text pane should not crash!

## Steps to Reproduce
1. Open the Text pane after going to the page.

## Screenshots
![crash](https://user-images.githubusercontent.com/3294597/111505035-7da08900-8748-11eb-8b2e-b2233dafbbbc.gif)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@barklund FYI tagging you here for priority & points.

**Comment by BrittanyIRL** [comment]
@barklund I can fix this really quick, it's from me and em both doing work on this panel around the same time.

**Comment by csossi** [comment]
Verified in QA
