### ISSUE TITLE
Make the story selector responsive. 

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#6808]
## Feature Description

Currently if viewed in smaller view ports, the story selector screen ( in the stories gutenberg block ), is not specially usable. See screenshots. However the rest of the gutenberg editor is completely responsive. Our view should match the rest of gutenberg and be responsive. 

![Screenshot 2021-03-17 at 10 53 53](https://user-images.githubusercontent.com/237508/111509855-11705600-8745-11eb-9363-3506846b62cc.png)
![Screenshot 2021-03-17 at 10 53 33](https://user-images.githubusercontent.com/237508/111509871-1503dd00-8745-11eb-97f7-1c68a20cd717.png)

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
With #6790 it currently looks like this on iPad:

<img width="413" alt="Screenshot 2021-03-18 at 14 14 44" src="https://user-images.githubusercontent.com/841956/111631963-4d162900-87f4-11eb-8aa8-122306fccdd4.png">

Smartphone doesn't look as good
