### ISSUE TITLE
Text Panel - Padding inputs should be numeric inputs

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6811]
## Bug Description

The user is unable to use arrow keys to step through the values of the padding input
 ![image8.png](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/5decdb9b-569b-4f3a-a765-b375c4c412df)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
Has been fixed (probably in #6890)
