### ISSUE TITLE
Text box - Selecting multiple elements results in undefined values

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6812]
## Bug Description

Selecting multiple elements shows `undefined` as the value rather than `mixed`. Clicking on a different pill sets this value to `0`.

## Screenshots

![image6](https://user-images.githubusercontent.com/58738530/111526364-06adc500-8735-11eb-86ff-e1c1f75ae695.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
Has been fixed (probably in #6640):

![Screen Shot 2021-03-30 at 09 30 57](https://user-images.githubusercontent.com/637548/112997095-cdb11f80-913a-11eb-945b-a49b83c40d05.png)
