### ISSUE TITLE
Design Panel dividers

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6814]
## Bug Description

Originally reported / asked by @ivayloklissarov 
Just double checking that we are using 1px stroke for the dividers as it seems very subtle currently.

## Screenshots
![image2](https://user-images.githubusercontent.com/58738530/111535771-da4b7600-873f-11eb-8b18-ca5251aaa1dd.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
We are currently using `1px solid rgba(0,0,0,0.24);` which seems to match
Figma:
<img width="212" alt="Screenshot 2021-03-18 at 19 39 44" src="https://user-images.githubusercontent.com/3294597/111671557-58c81680-8819-11eb-828d-f9b0503d5207.png">

From the editor:
<img width="169" alt="Screenshot 2021-03-18 at 19 37 40" src="https://user-images.githubusercontent.com/3294597/111671600-68475f80-8819-11eb-9ca5-15268b75f81e.png">

**Comment by bmattb** [comment]
Asssigning to @ivayloklissarov to confirm if this requires further action or not / CC - @tmagalhaes-huge
