### ISSUE TITLE
All panel & chevrons should change colour when expanded

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6815]
## Bug Description

originally reported by @ivayloklissarov 
The Title and chevron state should turn to Primary Grey once expanded.

## Screenshots
![image2](https://user-images.githubusercontent.com/58738530/111536361-89884d00-8740-11eb-8598-dbfa8c8236dc.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
@miina, didn't you deal with this in an existing issue somewhere? I believe I saw this implemented already?

**Comment by miina** [comment]
[Here](https://github.com/google/web-stories-wp/pull/6737/files#r592444174), but only for the heading colour. I'll create a quick fix PR for it to make it "final".

**Comment by csossi** [comment]
Colour change is fine and focus looks as expected for all fields except for Animation Type, where it's just white instead of blue (please let me know if that's intentional):

![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/6612c30a-a9d7-47bf-93b3-cac954973f36)

**Comment by miina** [comment]
@csossi Thank you for testing! This issue is only about the panel title and the chevron next to the panel, the contents of the panels are irrelevant here.

(The animation panel restyle has not been done yet here).

Moving this to QA Passed since this seemed to be the only found issue.
