### ISSUE TITLE
Keyboard Nav when Editing Masked Image

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#682]
## Bug Description

When focused / editing the masked image position, the keyboard should move the image in terms of the mask itself. Currently the keyboard moves the shape on the page.

![image](https://user-images.githubusercontent.com/5874851/77206761-241e6380-6ace-11ea-8367-bacfa7bc7757.png)

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## QA Instructions

1. Insert a media element
1. Press arrow keys to move the entire media element around
1. Press <kbd>enter</kbd> to enter edit-mode
1. Press <kbd>tab</kbd> to focus the image size slider and observe the slider handle have focus color
1. Press arrow keys to change size (leave it bigger than the minimum size)
1. Press <kbd>shift</kbd> + <kbd>tab</kbd> to return focus to image (no visible focus indication available unfortunately)
1. Press arrow keys to move the image inside the mask
1. Press <kbd>esc</kbd> to exit edit-mode
1. Press arrow keys to move the entire media element around

_Note_: you **can** end up in a state, where you are in edit-mode but the edited image does not have focus. In such a case pressing the arrow keys would do nothing. To be able to move the image inside the mask, make sure to focus it (it will be focused when entering edit-mode but focus does not magically return to it).

**Comment by csossi** [comment]
Verified in QA
