### ISSUE TITLE
Animation panel doesn't indicate that it has content on expansion

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6825]
## Bug Description

originally reported by @ivayloklissarov 

Behaviour of the Animation panel is a bit weird. It does not give any indication of content once expanded for the user to scroll down.

## Screenshots

![image4](https://user-images.githubusercontent.com/58738530/111663108-e1798f00-87e6-11eb-994d-12e82580475e.gif)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
Think this is out of date now that animation has its own section in the style tab.
