### ISSUE TITLE
Redesign: Use DropDown from the design-system for the animation effect selection

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#6827]
## Feature Description
Currently, we're using only the `DropDownSelect` from the design-system but not the dropdown itself.
We should switch the custom solution to use what's available in the design system.

See [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=6534%3A1889).
There's more in the dedicated [Animation section](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=1923%3A424212) but that might not be relevant for this issue.

<img width="261" alt="Screenshot 2021-03-18 at 19 15 19" src="https://user-images.githubusercontent.com/3294597/111668325-eefa3d80-8815-11eb-903f-a55cbdb2e295.png">

**Comment by csossi** [comment]
Verified in QA
