### ISSUE TITLE
Border panel - should be able to use the arrow keys to change the values

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6828]
## Bug Description
User cannot use the keyboard arrow keys to step through both the border and the opacity values in this panel

## Expected Behaviour

The value should change when using arrow keys while being focused in the input.

## Steps to Reproduce
1. Focus on one of the numeric inputs in the border panel
2. Click arrow up/down
3. See nothing happening

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
~Hm, should we really be able to do that? These are separate inputs even though in the same panel. If I am currently focused in the input and hit an arrow key, I expect the cursor to move, not the focus to jump to the next input.~

@barklund Thoughts?

EDIT: Chatted with Matt who reported this and apparently the idea behind it is changing the input value (increase/decrease), I misunderstood the description a bit, added steps now 😛 

These both are using `NumericInput` so perhaps it's something to change there directly?
