### ISSUE TITLE
FTUE: Done SVG has disappeared 

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6850]
## Bug Description

The SVG that shows up in the help center when all tips are read has disappeared. 
![Screen Shot 2021-03-18 at 3.09.03 PM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/c7746713-d683-4620-887c-068c4c4af571)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/51c30d88-1318-461d-9f99-04829f5be051)
