### ISSUE TITLE
Redesign: Update the inner box shadow for all focus used in the panel/library

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#6858]
## Bug Description
The focus line is using `bg.primary` as the default box-shadow between the blue line and the input edge, making it seem transparent, however, the panels have different background color and many (or most) of the inputs are having visibly different colour due to that.

We should update the colours in the panel for all inputs.

## Screenshots
<img width="480" alt="Screenshot 2021-03-19 at 20 21 40" src="https://user-images.githubusercontent.com/3294597/111825996-73b58c00-88e8-11eb-859a-463815b75133.png">

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@samwhale FYI -- logged this issue since it looks like most of the inputs in the panel are currently using the incorrect box-shadow.

**Comment by samwhale** [comment]
Good call!

**Comment by csossi** [comment]
Verified in QA
