### ISSUE TITLE
Library: Text Presets - button text not centered vertically in firefox

### ISSUE THREAD

**Issue by samwhale** [GoogleForCreators/web-stories-wp#6860]
## Bug Description

The text in the text preset buttons are not vertically centered in firefox but are centered in chrome and safari. Should be visible once this pr is merged: #6759.

**NOTE**: could be fixed when we update the font to Google Sans in #6386.

## Expected Behaviour

Text in the buttons regardless of browser should be vertically aligned.

## Steps to Reproduce

1. Open editor in firefox
2. Open text presets library panel
3. Look at text presets

## Screenshots

|Chrome|Safari|Firefox|
|--|--|--|
|![image](https://user-images.githubusercontent.com/22185279/111830852-261f2c00-88b4-11eb-81e5-8f869b307f70.png)|![image](https://user-images.githubusercontent.com/22185279/111830864-2b7c7680-88b4-11eb-8fc1-3eb1cd4b5e82.png)|![image](https://user-images.githubusercontent.com/22185279/111830905-36370b80-88b4-11eb-942b-18e8eba628ca.png)|

After removing the padding we can see that text is pushed up to the top of its content box. Not sure if this is just a firefox feature 🤷 
![image](https://user-images.githubusercontent.com/22185279/111830424-88c3f800-88b3-11eb-9456-00aca82d2e5c.png)

## Additional Context

- Plugin Version: 1.5.1 alpha
- WordPress Version: 5.7
- Operating System: macOSX Big Sur 11.2.2
- Browser: Firefox

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
