### ISSUE TITLE
Redesign: Update Pill Group and Collapse Button in Text Sets Panel

### ISSUE THREAD

**Issue by samwhale** [GoogleForCreators/web-stories-wp#6873]
## Feature Description

Update design for the pill group and collapse button in the text sets panel. [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=257%3A817).

- [ ] Update pill group from design system
- [ ] Update collapse button - use icon from design system

| Current design | New design |
|-|-|
| ![image](https://user-images.githubusercontent.com/22185279/112006877-c0b48080-8ae9-11eb-81a1-03f2ec2ece2c.png) | <img width="524" alt="Screen Shot 2021-03-22 at 8 35 58 AM" src="https://user-images.githubusercontent.com/22185279/112006797-ab3f5680-8ae9-11eb-9b97-05691660ff52.png"> | 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by samwhale** [comment]
The buttons in the designs are `Chips` and not `Pills`: https://google.github.io/web-stories-wp/storybook/?path=/story/designsystem-components-chip--default

**Comment by csossi** [comment]
Verified in QA
