### ISSUE TITLE
Widget: Fix flakey customizer e2e test

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6879]
## Task Description

This test often fails.

```
Web Stories Widget › Customizer › should be able to add widget

Node is either not visible or not an HTMLElement
```

**Comment by spacedmonkey** [comment]
@swissspidy I was completely unable to replicate this issue locally, even after a trying throlling CPU and network to see if that was the issue. 

I even tried to debug but pushing changes to github. As the bug does not happen all the time, I had to run 2-3 times to even gete the bug to happen. I could likely work this out by a process of removing one line a time I don't see the error. However, this will a long long time to debug ( 1 day / 1 1/2 days ) to debug. I am not sure it is worth effort. 

I think we should just skip the test for now and rewrite the test better at future date. Thoughts?

**Comment by swissspidy** [comment]
Yes please skip for now
