### ISSUE TITLE
DropDown missing visible outline when in focus

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#688]
## Bug Description

DropDown field is missing visible outline when in focus

## Expected Behaviour

It should be visibly understandable where focus is when tabbing to DropDown field.

## Steps to Reproduce

1. Add a Text element
2. Start tabbin in design panel
3. See no visibile indication of dropDown being in focus.

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Consolidating with #737
