### ISSUE TITLE
New Thumbnail for Pan & Zoom

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6881]
After sync with @samitron7 , new visual for the `pan and zoom` option in the animation dropdown is needed that just uses animated text.

@samitron7 to get new thumbnail to @littlemilkstudio , @littlemilkstudio to implement. 

Acceptance criteria: 
- New visual for pan and zoom in dropdown option that only animates text

**Design Mockups**

https://images.zenhubusercontent.com/235435637/2ecb1cdc-167a-4142-b1d9-18547d47fae2/panzoomthumb.mp4

**Comment by maxyinger** [comment]
Added design mockup to description. g2g for eng 🎉

**Comment by BrittanyIRL** [comment]
Holding on this until rest of panel is ready. See #6617

**Comment by BrittanyIRL** [comment]
Closed per discussion in 6617 - out of date
