### ISSUE TITLE
Pan & Zoom: Enable Feature Flag

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6885]
When pan and zoom is ready for release, we need to enable the feature flag.

Let's not remove the feature flag, or set it's default to `true` because we may want to use it as a testing ground for other animation effects in the future. For this ticket, we should just remove the conditional rendering (based on the feature flag) for the `pan + zoom` animation effect in the effect chooser

**Comment by BrittanyIRL** [comment]
This feature looked good in bug bash so we can merge as soon as Claudio is done with QA.

@csossi we need this one for the 1.6 release 🙃

**Comment by csossi** [comment]
Verified in QA
