### ISSUE TITLE
`Publish` button text overlaps with icon in right-to-left

### ISSUE THREAD

**Issue by samwhale** [GoogleForCreators/web-stories-wp#6886]
## Bug Description

The `Publish` text in the button overlaps with the 'info' icon

## Expected Behaviour

Icon in `Publish` button should be spaced away from the text

## Steps to Reproduce

1. Open editor
2. Switch to RTL
3. Look at `Publish` button.

## Screenshots

![image](https://user-images.githubusercontent.com/22185279/112056029-2706c680-8b1d-11eb-9296-614bbaefc0e3.png)

## Additional Context

- Plugin Version: 1.5.0
- WordPress Version: 5.7
- Operating System: macOSX Big Sur 11.2.2
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by Ayushsunny** [comment]
Hello @samwhale I wanna work on this issue.

**Comment by BrittanyIRL** [comment]
> Hello @samwhale I wanna work on this issue.

hi @Ayushsunny thanks so much for your interest in the project! This bug is actually getting taken care of already and isn't a great first issue (we mislabeled it). If you're interested in contributing, there are better first issues if you want to look further at our backlog.

**Comment by Ayushsunny** [comment]
> > Hello @samwhale I wanna work on this issue.
> 
> hi @Ayushsunny thanks so much for your interest in the project! This bug is actually getting taken care of already and isn't a great first issue (we mislabeled it). If you're interested in contributing, there are better first issues if you want to look further at our backlog.

okay Sir, Thanks

**Comment by BrittanyIRL** [comment]
Fixed this while cleaning up PPC

![Screen Shot 2021-05-06 at 2 53 05 PM](https://user-images.githubusercontent.com/10720454/117370143-d0f6a400-ae7a-11eb-9a6a-ec5416f94efd.png)

**Comment by csossi** [comment]
Verified in QA
