### ISSUE TITLE
Color Swatch: button used inside button

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#6889]
## Bug Description
The following error appears in console for the `Swatch` component:
<img width="525" alt="Screenshot 2021-03-23 at 09 29 14" src="https://user-images.githubusercontent.com/3294597/112109521-fcb31880-8bb1-11eb-992e-8ba370a823b6.png">

## Expected Behaviour
A button should not have another button as a child.

## Steps to Reproduce
1. Add a Shape.
2. Ensure you have some saved colors.
3. See the error in console.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Closing as I'm not seeing this issue anymore.

**Comment by swissspidy** [comment]
@miina At least in the JS unit tests I still see it, if that helps:

https://github.com/google/web-stories-wp/runs/2507675728?check_suite_focus=true#step:9:8

**Comment by miina** [comment]
> At least in the JS unit tests I still see it, if that helps:

Hm, interesting. Reopening to investigate this more.
