### ISSUE TITLE
Masking Not Rendered on Mobile

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#689]
## Bug Description

Mobile (iPhone, Chrome):
![image](https://user-images.githubusercontent.com/5874851/77230342-f38c0780-6b69-11ea-896c-1b30ea715188.png)
Mobile:
![image](https://user-images.githubusercontent.com/5874851/77230376-246c3c80-6b6a-11ea-9136-d17b4808baa8.png)

Macbook (Chrome):
![image](https://user-images.githubusercontent.com/5874851/77230356-0ef71280-6b6a-11ea-99e0-7227587de27b.png)
Macbook:
![image](https://user-images.githubusercontent.com/5874851/77230385-30f09500-6b6a-11ea-8c2e-878e9662a450.png)

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by dvoytenko** [comment]
/to @wassgha @pbakaus Do we have a critical browser compatibility problem? This is very uncommon for a Chrome desktop to differ from mobile in something like this.

**Comment by wassgha** [comment]
looks like for iOS we need to use `-webkit-clip-path`, any conflict with AMP on that?

**Comment by dvoytenko** [comment]
Shouldn't be. I thought that was set up automatically in our codebase? Or is it output only?

**Comment by wassgha** [comment]
It looks like stylelint didn't think it was necessary. Didn't dive into why.
