### ISSUE TITLE
Block: Allow embedding single story with preview / lightbox

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6894]
## Feature Description

When using "Latest Stories" or "Selected Stories", stories are displayed as images and upon clicking open in a lightbox.

When using the story block's "Story URL" mode, the story is displayed using the story player.

Ideally, we would give the user the option to display the story with a preview image + lightbox as well.

This likely requires some refactoring of the underlying renderers.

In the editor it would be a simple toggle.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by rodrigofglima** [comment]
One suggestion: a check-box with set proportional height and width scale in properties. If i increase width for wordpress theme, its increase the height size.

**Comment by swissspidy** [comment]
In our meeting, we discussed making this similar to the image block, allowing to choose between selecting an existing story or inserting from URL:

Mock:

![Screenshot 2021-08-12 at 16 07 51](https://user-images.githubusercontent.com/841956/129211562-2a454f90-a08f-44d9-92a2-a22855e76b2a.png)

The URL option would show the URL input field in a popup/tooltip like in the Image block.

The "Select Story" button would open the story selector we already have today, but only allow selecting 1 story.

@spacedmonkey WDYT?

**Comment by spacedmonkey** [comment]
I think I would go deeper with this. 

If you click on select, you are force only to pick one story. Once you have selected one story, it is treated selected stories. Giving you options to switch between layout types like this. 

<img width="659" alt="Screenshot 2021-08-20 at 17 02 23" src="https://user-images.githubusercontent.com/237508/130261537-0f6b232e-cd15-4575-8b85-8e285c80644f.png">

But if there is one 1 story in that array, you get given a 5th option of player. 

We should be pushing users to select stories via the story picker. Copying and pasting a url of the current site in, is a little strange and error prone to me.

**Comment by swissspidy** [comment]
> If you click on select, you are force only to pick one story. Once you have selected one story, it is treated selected stories. Giving you options to switch between layout types like this.
> But if there is one 1 story in that array, you get given a 5th option of player.

I see.

So basically for when the user says „I want to embed a single story and display it as a circle“, correct?

I think for that we would need to revamp the layout options quite a bit. For example, we would need to add only a single circle, not a full blown circles carousel. A circles carousel with only 1 story doesn‘t make sense.

In short, this warrants its own ticket.

> Copying and pasting a url of the current site in, is a little strange and error prone to me.

Absolutely. Hence offering the option to either select a story _or_ insert a URL. URL is especially useful for external stories.

(Aside: realizing that we might want to split this ticket into two: one for the single story selection, one for the lightbox implementation)

**Comment by spacedmonkey** [comment]
For what is worth, you can currently only select one story in the "select stories" workflow. It looks like this. 

<img width="669" alt="Screenshot 2021-08-20 at 18 21 40" src="https://user-images.githubusercontent.com/237508/130270835-0909e6ed-5da7-4842-b6c2-fa293c855cff.png">

<img width="1781" alt="Screenshot 2021-08-20 at 18 23 06" src="https://user-images.githubusercontent.com/237508/130270877-a6fa9431-ff94-4a18-bbab-2ade7b11f1cf.png">

So there is no change here. It is just doesn't look great with one story. Maybe we should fix this...

Current the story selection works like this. 

1. Create block. 
2. Select block type - selected story. 
3. Select layout type. 
4. Select stories. 
5. Complete. 

If we change 4 and 3 around we can do this. 
1. Create block. 
2. Select block type - selected story. 
3. Select stories. 
4. Select layout type. ( detect if one story is selected and show different options, like adding player as option). 
5. Complete. 

Then if go through Story URL flow, would do do this. 
1. Create block. 
2. Select type - Story url. 
3. Select type, url or select. 
4. If you select url, is current input box for url. If you select "select story", then it takes you to Step 3 of select stories workflow. 

Does that make sense? It makes it a little cleaner and we can reuse much of the existing code, just a different workflow.

**Comment by swissspidy** [comment]
Let me split this into new dedicated tickets, as we‘re talking about multiple efforts at the same time.

I think your suggestion to allow choosing the layout type for single stories makes sense, but is probably best done in a separate step.

Allowing selecting a story via the story selection can be implemented independently of that.

> If we change 4 and 3 around we can do this.

I don‘t think we should change them around. This would be very confusing because you select stories but don‘t immediately see the results because you first have to select a layout type.

We should actually rather consider **removing step 4**. The layout type can be changed via the block toolbar.

> detect if one story is selected and show different options, like adding player as option

On that note, just reiterating that the options would be conpletely different (i.e. circle instead of circles carousel, perhaps not offering the list option, etc.)

**Comment by spacedmonkey** [comment]
My worry is that by remove the layout selection screen means that, you are hiding the ability to have different layouts. I was looking at different core blocks, wondering if we should add a preview to layout types, like with buttons. 

<img width="434" alt="Screenshot 2021-08-24 at 11 21 05" src="https://user-images.githubusercontent.com/237508/130600836-d06bc8dc-2db6-43c1-837e-fc593190844c.png">

<img width="278" alt="Screenshot 2021-08-24 at 11 25 18" src="https://user-images.githubusercontent.com/237508/130601038-e3556d2e-b754-42d8-833e-336aadf3e450.png">

This is the more gutenbergy way of it doing. But might be out of scope this change.

**Comment by swissspidy** [comment]
> This is the more gutenbergy way of it doing.

Sort of. Block styles are just CSS classes to style elements differently, for example to display quotes a bit larger. But our different layout types require entirely different HTML structure. So block styles are not quite the right match.

> But might be out of scope this change.

Agreed

**Comment by swissspidy** [comment]
## Next Steps

As a first step, I want us to create an **MVP** for this solution **without touching the layout selection** at all.

There should be a single **toggle** in the block sidebar for switching between player and preview/lightbox display.

The preview/lightbox option would display the story in a rectangular preview image just like you'd get from the box carousel option.

That probably requires a new renderer in addition to `Embed`/`HTML`/`Image`

I created #8845 as a dedicated ticket for improving the story selection.

**Comment by Spacena** [comment]
I just learnt that there is a feature request for my issue that I raised here: https://wordpress.org/support/topic/embed-is-broken/#post-15947785

Just checking in to see what's the status. When can we expect the concerned feature rolling out?
