### ISSUE TITLE
Media: upload pre-existing poster image if available

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6904]
## Feature Description

We're currently a bit wasteful with the poster generation, as we don't upload the poster to WordPress that we have already generated during upload, but instead generate a new one after upload completes.

The current scenario for uploading a a video is as follows:

1. Drop video onto canvas
2. If possible, create a poster using canvas
3. If video cannot be played and there is no poster, display a placeholder
4. Transcoding begins
5. In parallel, if there is no poster, a poster is being generated using FFmpeg
6. Transcoding finishes, upload begins
7. Upload finishes, video resource is updated with final one
8. A poster is generated and uploaded to WordPress

Part (8) is the issue here. We generate a poster even though (2) or (5) will most likely have created one already.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

* Remove `uploadVideoPoster()` call from `onUploadSuccess` callback in `useUploadWithPreview` -> this can be done directly in `useMediaUploadQueue`
* In `useContextValueProvider`, add a new callback in addition to `uploadVideoPoster` to upload a pre-existing poster file/blob.
* Perhaps extract parts of `useUploadVideoFrame` so it can be re-used
* In `useMediaUploadQueue`, add an effect for items with state `UPLOADED`  
  * If the resource does **neither** have a `posterId` nor a `poster` ->  call `uploadVideoPoster` (which calls `getFirstFrameOfVideo`, `uploadFile`, and `updateMedia`) (**current behavior**)
  * If the resource does not have a `posterId` **but** a `poster` -> use new callback  (which can call `uploadFile`, and `updateMedia` directly as we already have a poster)

**Comment by csossi** [comment]
Verified in QA
