### ISSUE TITLE
Keep Page selected after removing Background Media

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#6907]
## Feature Description
Currently, when background media is removed from the Page, the media gets selected, however, the Page should be selected after that.

See [Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=5%3A220109)

## Acceptance Criteria
- When a user has background media added then removing it from the "Page background" panel or via Keyboard delete should result in the Page being selected.

**Comment by miina** [comment]
@barklund Ping for priority and story points.

**Comment by csossi** [comment]
Verified in QA
