### ISSUE TITLE
Internationalization: JS strings not properly exctracted

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6910]
## Bug Description

It appears that, probably ever since we switched to use  `@web-stories-wp/i18n` internally, our JS-side translation calls are not being extracted on WordPress.org. That means the editor and dashboard are currently not really localizable at all ⚠️ 

Our minified JS looks like `Object(i.b)("Thin","web-stories")` wherreas it should be `Object(i.__)("Thin","web-stories")` for it to be able to be extracted.

## Expected Behaviour

All strings should be able to be exctracted.

## Steps to Reproduce

1. Build plugin.
2. Extract strings using `wp i18n make-pot . --exclude=tests,.storybook,build,assets/src,packages --debug` (note: might need to `wp cli update --nightly` first)
3. Output will mention ~288 extracted strings, but there should be more like ~1000.

## Additional Context

- Plugin Version: 1.5
- WordPress Version: 5.7
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
OK I think the only way I've gotten this to work is by changing the export in the `i18n` package to this:

```js
export * from '@wordpress/i18n';
```

Otherwise webpack gives it a new name.

But with the above I get `Object(m.__)("Thin","web-stories")` as expected`

**Comment by swissspidy** [comment]
```
Debug (make-pot): Extracted 1195 strings (32.022s)
Success: POT file successfully generated!
```

That's more like it!

I also see a few warnings:

```
Warning: The string "Google" has 2 different translator comments. (assets/js/stories-dashboard.js:44)
Warning: The string "My Stories" has 2 different translator comments. (includes/Dashboard.php:138)
Warning: The string "%s hour" contains placeholders but has no "translators:" comment to clarify their meaning. (assets/js/edit-story.js:3)
Warning: The string "in %s" contains placeholders but has no "translators:" comment to clarify their meaning. (assets/js/edit-story.js:4)
Warning: The string "%s ago" contains placeholders but has no "translators:" comment to clarify their meaning. (assets/js/edit-story.js:4)
Warning: The string "Duration" has 2 different translator comments. (assets/js/edit-story.js:16)
```

Let's fix those as well.

**Comment by dreamofabear** [comment]
A bit concerned about brittleness here. Can we add a regression test? E.g. a GitHub action to release that runs `wp i18n make-pot` and verifies that the number of strings > 1000.

**Comment by swissspidy** [comment]
Yeah I'll try to think of something here. Could run on a schedule even so we catch things earlier
