### ISSUE TITLE
Fix lasso selection in new zoom canvas

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6911]
## Feature Description

The new zoom implementation has broken canvas selection - both with and without zoom enabled.

This ticket should:

- [x] Fix lasso selection when zoom is disabled or zoom is set to fit
- [x] Fix lasso selection when zoom is enabled and the zoom is applied with scrollbars visible on screen
- [x] Make sure tests in `lasso.karma.js` work again and add extra tests for zoomed canvas

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@barklund I suspect that this might be related to some of the broken tests, too.

It looks like currently, the fullbleed area doesn't match the "real" Page area anymore. Perhaps there's some renaming and reassigning refs needed?
![Screenshot 2021-03-31 at 10 29 06](https://user-images.githubusercontent.com/3294597/113107002-ac683600-9203-11eb-8fa6-e704bef23fdd.png)

**Comment by csossi** [comment]
Unable to lasso at all in QA env.:

https://share.getcloudapp.com/E0uYqX11

**Comment by csossi** [comment]
Verified in QA

**Comment by miina** [comment]
I'm assuming this doesn't need separate UAT since the Zoom feature hasn't even been abled yet so leaving it Closed.
