### ISSUE TITLE
Update zoom dropdown to align with help center

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6912]
## Feature Description

This ticket should:

- [ ] Update the dropdown for zoom to use the new design system dropdown
- [ ] Make sure the design corresponds to the Figma guide
- [ ] Make sure the zoom dropdown and help center toggle are perfectly aligned as in Figma
- [ ] Make sure that there are no references to `DEPRECATED_THEME`
---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Can we adjust the spacing within the button in the RTL version?:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/b9e8b0e1-0de8-42a6-bdc8-f4f40141cdc5)

**Comment by samwhale** [comment]
Nice catch, this should be fixed now @csossi 
![image.png](https://images.zenhubusercontent.com/5b1032a1348b7966b43421a4/d5e1c630-83ed-484c-9fd6-849bf04c2de3)

**Comment by csossi** [comment]
Verified in QA
