### ISSUE TITLE
Replace tildes in filenames with dashes

### ISSUE THREAD

**Issue by ioneill** [GoogleForCreators/web-stories-wp#6917]
## Bug Description

Filenames with a tilde (~) are blocked as standard by many Web Application Firewalls. 4 Javascript files contain tildes and requires reconfiguration of the WAF. 

## Expected Behaviour

Filenames should follow standard WordPress practice, and use dashes instead of tildes.

## Steps to Reproduce

Open the Plugin page behind a WAF e.g CA Siteminder, Barracuda. Files with a tilde return a 404.

## Additional Context

- Plugin Version: 1.5.0
- WordPress Version: any
- Operating System: any
- Browser: any

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Thanks for your report!

TIL!

We'll take a stab at this and check back with you to see if this results in the desired effect.

Should be easy enough thanks to the [`splitChunks.automaticNameDelimiter`](https://webpack.js.org/plugins/split-chunks-plugin/#splitchunksautomaticnamedelimiter) option in webpack.
