### ISSUE TITLE
Issue when Deleting BG Image from Media Library in WP

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#692]
## Bug Description

1. Add a background image in your story
2. Go to the Media Library tab in WP (exit out of your story and the Stories section)
3. Delete the background image
4. Go back to your Story
5. See that the image placeholder is still in the Media Library Panel under the "All" filter

Video with steps taken: https://drive.google.com/file/d/1qBDWpEmMuwDVk4MPptpb3HOKp-wj36tZ/view

Taken from Claudio in #585

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Closing the issue since this is due to the caching issue in Pantheon, not related to the editor.

Wasn't able to replicate this locally nor in the testing environment when cache is turned off.
