### ISSUE TITLE
Pre-Publish Checklist: Do not suggest adding captions for videos without audio tracks

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6922]
## Feature Description

Initially reported in the forums: https://wordpress.org/support/topic/captions-on-video-with-no-audio/

Would be nice if we could detect whether a video actually has an audio track and if so, do not show a message in the checklist about missing captions.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
pinging @o-fernandez for consideration

**Comment by o-fernandez** [comment]
@swissspidy @choumx @BrittanyIRL @samitron7 This seems like a valid ask - how easy is it for us to check for audio track on videos? If not too high effort, we should do this - no audio track, no "error" in checklist.

**Comment by swissspidy** [comment]
Seems like there is no unified browser API for that.

In Firefox there's a simple but proprietary `HTMLVideoElement.mozHasAudio` property we can look for.

A similar property, `HTMLVideoElement.audioTracks`, works in Safari but has still [not landed](https://bugs.chromium.org/p/chromium/issues/detail?id=851160) in Chromium (behind a flag). Also behind a flag in Firefox.

In Chrome there's `HTMLVideoElement.webkitAudioDecodedByteCount` but it requires `playing the video~ loading video data to load the audio track and then checking whether any audio has been received. Also, there are [plans to deprecate it](https://bugs.chromium.org/p/chromium/issues/detail?id=632380).

All in all, not ideal.

I see two alternatives:

1. Use FFmpeg to find audio tracks in video element. A bit more expensive to load, but could be done & saved during initial upload where we already use FFmpeg for video optimization.
2. Give user the option to say that video has no sound / to dismiss the checklist warning

**Comment by o-fernandez** [comment]
Thanks @swissspidy.  Given that, I think that we should explore #2 (give the user the option to dismiss if n/a) as part of future checklist work. For now, let's keep this in the roadmap/backlog for review. 

@samitron7 and @choumx for your thoughts.

**Comment by swissspidy** [comment]
Closing in favor of #7371
