### ISSUE TITLE
Fix Copy & Paste Background Animation Karma Tests

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6936]
## Feature Description

Karma tests for background animations in `edit-story/karma/copyAndPaste.cuj.karma.js` are failing because of the following: 
`ResizeObserver loop limit exceeded thrown` which can be traced back to the fixture not finding the proper region `Unable to find an accessible element with the role "region" and name "Edit layer"`.  

This ticket is to fix that test so it can run.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
~@BrittanyIRL I'm assigning this to myself since #6993 is fixing a bunch of tests needing the same fix (including this test)~

Edit: Unassigning again since apparently, the failure of this test has more to it than this one issue. Sorry for the confusion!
