### ISSUE TITLE
Integration Tests failing for Dropdown

### ISSUE THREAD

**Issue by samwhale** [GoogleForCreators/web-stories-wp#6937]
## Bug Description

5 integration tests are failing for the new dropdown:
- `should make black+bold selection non-bold when toggling`
- `should make black+bold+regular selection black when toggling`
- `should make bold+regular selection bold when toggling`
- `should make black+bold+regular text field bold when toggling`
- `should display the link tooltip correctly`

This is due to [this fixture file](https://github.com/google/web-stories-wp/blob/main/assets/src/edit-story/karma/fixture/containers/common/select.js#L40-L48) not finding the options with the specified roles.

The dropdown may need some accessibility updates. Check these docs:
- https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html
- https://www.w3.org/TR/2010/WD-wai-aria-20100916/roles#option

## Expected Behaviour

Tests should pass.

## Steps to Reproduce

1. Replace `it` with `fit` for those five tests
2. Run karma tests

## Additional Context

- Plugin Version: 1.5.0
- WordPress Version: 5.7
- Operating System: macOSX Big Sur 11.2.2
- Browser: Chromium (karma tests)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Is this an instance of a PR that was merged but shouldn't have been due to the failing status checks?

**Comment by BrittanyIRL** [comment]
> Is this an instance of a PR that was merged but shouldn't have been due to the failing status checks?

Probably. There's been so much happening with the redesign I think some tests just got ignored. I'm cleaning this up now.
