### ISSUE TITLE
Media: Support video optimization for existing videos (MVP)

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6943]
## Feature Description

For the pre-publish video optimization we need to implement the foundation for actually supporting this kind of functionality. Specifically, to allow optimizing existing videos in a story and uploading that optimized video to WordPress.

**For testing purposes only** we can add a button somewhere in the design panel to trigger this. Perhaps in the "Video Settings" panel:

<img width="369" alt="Screenshot 2021-03-29 at 23 01 08" src="https://user-images.githubusercontent.com/841956/112900062-38cf0780-90e3-11eb-8058-52b839b4db98.png">

This will **not** be the final UI.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

* Any visual UI changes should be behind a feature flag
* There should be a way for QA  to trigger this video optimization for testing, so needs _some_ debug UI
* Implement functionality to process existing videos in a story
* Existing video on canvas is replaced with optimized video
* Original & optimized video are linked to eventually allow for a "Restore original" functionality
* Media source is added to optimized video to avoid processing already optimized videos (videos that are already optimized can't be optimized again)
* Need to know whether optimization is currently in progress for a video. This way we can display a spinner / loading indicator while in progress (**not** a real accurate progress bar, see #5982 for that)

## Implementation Brief

* Add feature flag for pre-publish video optimization (separate from pre-upload video optimization)
* Add baseline functionality to allow processing existing videos
* Upload optimized video to WordPress media library **but leave original untouched**
* In the story, the original video file is replaced with the optimized version
* The attachment metadata or post meta of the optimized video references the original video
  * This allows restoring original video in the future

## Non-Goals

* Any usage of a video in _other_ stories is not affected by this (since the original is left untouched)

**Comment by swissspidy** [comment]
@spacedmonkey please let me know if I forgot to add anything here.

Given the requirements I'd say it's easily 8pts.

**Comment by spacedmonkey** [comment]
What do we do about the poster image here? Do we re-use the existing one? What if a user has set a custom one? 

I would say that this is a min of 8pts here!

**Comment by swissspidy** [comment]
This shouldn't tangent poster images at all. If there is a poster image we can keep it. If there isn't, we have the logic to generate one.
