### ISSUE TITLE
Videos: Playback button position wrong if element too small

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6958]
## Bug Description

The video playback button is oddly positioned outside of the element if the element is not large enough so it can fit it.

## Expected Behaviour

Playback button is positioned correctly. Perhaps smaller? Not sure what's best here.

## Steps to Reproduce

1. Make video element rather small.

## Screenshots

<img width="338" alt="Screenshot 2021-03-30 at 22 49 15" src="https://user-images.githubusercontent.com/841956/113054938-4ac7ad80-91aa-11eb-9c01-429dab43dc10.png">

## Additional Context

- Plugin Version: 1.5.0 / 1.6.0-alpha
- WordPress Version: 5.7
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
As per #7163 this also happens with canvas zoom

**Comment by bmattb** [comment]
Note from bug bash 

> Got the same odd behavior as Matt but when I set the video as full screen/background - NOTE: only happens if the original size of the video on the canvas (before setting as background) is small. If I expand first and then set as BG then the button shows properly at the center of the canvas.

**Comment by barklund** [comment]
FYI: The controls are generally positioned wrong if RTL - both for small and large videos!

**Comment by miina** [comment]
@swissspidy Displaying the play button outside of the video element is actually per design, see also the [PR where it got implemented](https://github.com/google/web-stories-wp/pull/1948). See also: https://github.com/google/web-stories-wp/issues/1894 for a consistently sized Play button (the size used to vary).
 The UX rule was: When the video element is too small we want to display the play button above the element.

The idea here was that the play button should have a consistent size but at the same time it can't cover the whole video either and would interfere with dragging, too, thus, it was moved outside of the element in this case (videos resized small).

Thoughts?

**Comment by swissspidy** [comment]
Ha, good find. Perhaps UX can confirm whether this is still intended behavior? Just to be sure.

Any RTL issues should be addressed either way though :-)

**Comment by miina** [comment]
@swissspidy Looks like the RTL issue will be addressed in a separate issue (to be created shortly, will tag it here once ready).

(Also [pinged UX for feedback](https://xwp.slack.com/archives/C01ESBB8ZN1/p1620227289044500) just in case).

**Comment by swissspidy** [comment]
You mean #7397?

**Comment by miina** [comment]
> You mean #7397?

Yes!

**Comment by swissspidy** [comment]
Closing since this is per design
