### ISSUE TITLE
Remove Story Preview in Dashboard

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6962]
We have an old "preview" experiment in the dashboard that enables a second button on hover/focus of a story in the dashboard to "Preview" the story. This preview opens a dialog in the dashboard (instead of a new tab which is an option in the context menu associated with the story), we have to generate the preview in an iframe though and it's a little hacky. 

We should either update to use best practices for the iframe (use the actual URL instead of AMP output) or we should remove it entirely. 

This ticket is to figure out what to do with this experiment since it is severely out date. 

__________
**March 30, 2021 Update** 

Remove story preview experiment and all associated code in dashboard for it (storyPreview)

Acceptance Criteria: 
- No more story preview experiment

**Comment by BrittanyIRL** [comment]
Per internal conversation with TLs, Sam and Omar we will be killing this experiment and the code associated with it. This feature will be abandoned. 

This ticket is now for that. Updating accordingly.

**Comment by BrittanyIRL** [comment]
@csossi my PR description has more detail on testing. Tl:DR is needing to test for regression on dashboard and making sure that there's no more "preview" experiements.

**Comment by csossi** [comment]
Verified in QA
