### ISSUE TITLE
Video poster: setting video as background resets the poster

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#6963]
## Bug Description
When a video with custom poster is set as background, the poster is reset.

Likely `combineElements` needs an adjustment.

## Steps to Reproduce
1. Add a video
2. Set custom poster
3. Set the video as background media
4. See the custom poster being reset

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
