### ISSUE TITLE
Custom Page Templates: Set up Custom Post Type

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6965]
## Feature Description

Custom page templates are pages created by end users, that can be saved and easily recalled from any other story. Basically it's one big storage of single-page templates that can be accessed by all users of the same WordPress installation with the correct permissions (more on permissions later).

All page-level properties can be saved to a page template including elements, background element, background color, and animations.

Story-level properties are **not** saved along with a page template including settings like status, publication date, page advancement, excerpt, saved colors and styles, etc.

See visual user flow in [this Figma section](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=7082%3A531446).

### Terminology

**Page templates** is the name for this feature as exposed to end users.

**Story templates** is the name for the pre-designed full-story examples, that user can also take advantage of. These are two separate concepts.

However, for ease of communication internally, we can call the former ***layouts*** and the latter ***templates*** to properly distinguish these. That's up to the API to define.

### Access model

* Any user that can create a story, can create or delete a custom layout/page template
* A custom layout/page template is a big JSON blob, no meta-data.
* A custom layout/page template cannot be edited, only deleted
* Any user that can create a story, can list all the custom layouts/page templates sorted by creation date descending (newest first).
* There will be no need for other sort methods or even filters.
* Pagination might be needed in the long run, but probably not for v1
* Search is also not needed for v1, but perhaps later we can search the actual text string in the JSON blob for matches?

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
I took sometime to review the [figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=7082%3A531386)

There are references to deleting page layouts. So the api must contain this functionality. But we need to decide how has this capability to added to users roles. Currently author / contributor roles are not able to delete / update others stories. See [add_caps_to_roles](https://github.com/google/web-stories-wp/blob/f272ee001da4a149c95e5404ad97d7ef195cf948/includes/Story_Post_Type.php#L230). However, I not sure if this maps well to this functionality. At the very least, all users should be able view page layouts in the api. See https://github.com/google/web-stories-wp/issues/6613 for more details. I think that maybe for this functionality even authors, should be able to delete others page templates. Page template are a little different from content, in that they are easier to recreate. I think capability are a big question here that needs answering. 

What we do about capabilities, as recommended [here](https://github.com/google/web-stories-wp/issues/5062#issuecomment-805744061), we should create a new `Capabilities` class incase this logic. 

A very simple design for the REST API, would be to reuse the api for templates / stories. Meaning that a custom page template would just be saved ( in post content filtered field ) as a story with a single page. Then in javascript all the page data would need to be extracted. This would keep the REST API design pretty simple, but may mean that storing some unnecessary data. But it would make running migration of data formatting the same as stories. It would also open us up to the option of "Story templates" in the future, meaning multiple page could be saved as a template. This is just an idea for now. 

As the number of custom post type grows, I believe that we should create a new namespace called Post_Types, and move stories and templates into this namespace. We could even add an class interface for Post types. 

Another question, will custom page templates be tagged in anyway, like giving them name or tagged into groups, like fashion etc. If there is a large editorial being able to sort and find templates might be useful. Again, not in document, just a thought I had when reviewing the doc.

**Comment by swissspidy** [comment]
I updated the ticket description, consolidating with Morten's comments from #7054. Capbility-wise it becomes pretty simple. If a user can edit stories, they can create/edit/delete custom page templates.

We have REST controllers for stories and (story) templates. Now we need an additional one for (story) page templates.

Interfaces and namespaces can be looked into in a separate ticket.

**Comment by spacedmonkey** [comment]
> Capbility-wise it becomes pretty simple. If a user can edit stories, they can create/edit/delete custom page templates.

So to confirm what I said above, author level should get full CRUD support?

**Comment by spacedmonkey** [comment]
> We have REST controllers for stories and (story) templates. Now we need an additional one for (story) page templates.

> Meaning that a custom page template would just be saved ( in post content filtered field ) as a story with a single page.

Yes, that is clear, but I had a recommendation of using a story with a single page as a way of keeping api the same and not needing to design a new api. It may also make preview much simpler. What do we think?

**Comment by swissspidy** [comment]
> > We have REST controllers for stories and (story) templates. Now we need an additional one for (story) page templates.
> 
> > Meaning that a custom page template would just be saved ( in post content filtered field ) as a story with a single page.
> 
> Yes, that is clear, but I had a recommendation of using a story with a single page as a way of keeping api the same and not needing to design a new api. It may also make preview much simpler. What do we think?

Yeah storage-wise it would be the same JSON format stored in post_content_filtered as for stories. It would indeed just be a story with a single page in practice.
