### ISSUE TITLE
Make Checklist Less Annoying

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6968]
This is in scope for 1.7 release.

Figma link: https://www.figma.com/file/1YM3jA9h4QGc4xLdyaXIJS/Stories-Sprint-1.7?node-id=7045%3A7520 
Copy update: https://docs.google.com/spreadsheets/d/1PjaRp4bueQ3Cv14A7I696m0vjGCIX_kN9tIGh-V-Bkc/edit?ts=5fbd398a#gid=920793050

Ways the checklist is getting addressed: 
- Remove 'Increase Video or image size on page' check so that images that are not full page size don't flag (april 6, 2021)
- V2 of PPC panel: silencing suggestions on new stories, gradually introducing recommendations and then high priority items to limit noise; minor design updates; new copy; new tooltips; new dialog (april 7, 2021)

**Comment by aaecheverria** [comment]
Hi guys @BrittanyIRL @o-fernandez @embarks 

The scope of this deliverable includes:
1. Delaying the messages when starting a story from scratch and adding some triggers
2. Updating the copy of the messages (see spreadsheet)
3. Reducing the # of critical items and deleting 2 checks (see spreadsheet)
4. Update tooltips and add a new dialog box
**Figma link:** https://www.figma.com/file/1YM3jA9h4QGc4xLdyaXIJS/Stories---Sprint-1.7%2B?node-id=7045%3A7
**Copy Spreadsheet** (please see Huge tab): https://docs.google.com/spreadsheets/d/1PjaRp4bueQ3Cv14A7I696m0vjGCIX_kN9tIGh-V-Bkc/edit?ts=5fbd398a#gid=920793050
- **Column D:** New issues categorization (we reduced the number of the hi-priority items) 
- **Column F:** Issues tittle
- **Column G:** Secondary copy (if needed)
 **Note:** The bundle category and the body copy underneath each category  that we have in columns E and K are for the v.2) 
Thank you!

**Comment by BrittanyIRL** [comment]
This epic was for release 1.7, closing as it is done.
