### ISSUE TITLE
Template Updates: Beauty

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6969]
## Description 

**Bolded** text are updates from April 6, 2021: https://docs.google.com/spreadsheets/d/1MFtHj7Xwdol9jSk80PXrxWNz_0h1tSfyEe3K7Bn2yZs/edit#gid=0

| Page | Animations | Cosmetics |
| --- | --- | --- |
| 1 |  Fresh & Bright headline animation updated from custom "Bounce" to editor's "Pulse"; Remove animation on pink shape. **Anonymous by line to fly in** | Remove grid shape from background; Remove secondary white layer from headline; update type color to: #28292B |
| 2 | Remove animations on heart shapes; Update Text animation from custom "Bounce" to editor's "Pulse". | Combine heart shape (done); Remove second layer for type; change type color to #28292B |
| 3 |  Need to know what "3" animation update is called; Remove animation on sage shape; change the custom animation on text to Fade In (3000ms); **Headline and Image to fade in 3000ms**  |  N/ A |
| 4 |  Change little hearts custom "bounce" to "pulse".  Remove background animation. | Remove second layer for type. Increase little heart radius for more tappable space (60x60). |
| 5 | Update custom "bounce" on headline  to "pulse". **Image to Fly in** | Remove grid shape; remove stars; make image larger; update color to #28292B. |
| 6 | Update number headline from custom bounce to editor's pulse; text area animation update to fade in. Remove animation on pink shape and link area and buy now. **Headline and Image to fade in 3000ms** | Remove grid shape; remove second layer for type; change type color to #28292B. |
| 7 | Update custom bounce to editor's pulse; remove animations on buy now, background shapes, links.  **Both images to Fly in** | Remove grid shape; remove star |
| 8 | Update headline. and image from. custom bounce to editor's pulse; Update text to fade in; remove animation on get the look. **Background shape behind image to fade in 3000ms** | Remove text frame shape; portrait changed |
| 9 | Update headline custom bounce to editor's pulse; Update images to fade in; remove animations on all shapes and subheading text. | remove second layer for type. images updated. |

See Figma for specifications: https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=7216%3A549493 

If design requests have updated please make note in a comment here so that testing is aware of updated specs. 

## Acceptance 
- Template is updated 
- Relevant stickers are created 
- No more custom animations

**Comment by csossi** [comment]
Verified in QA

**Comment by BrittanyIRL** [comment]
These were bug bashed by design so i feel like we can close them.
