### ISSUE TITLE
Template Updates: Cooking

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6970]
## Description 

April 6, 2021 - Updates from Figma since original creation of ticket are **BOLD**, please cross reference with figma.

| Page | Animations | Cosmetics |
| --- | --- | --- |
| 1 |  Headline should be updated to editor "fly in" instead of custom "move". Border animation updated to fade in. **Oranges image to fade in (3000ms)** | change orange color to **#3A566E** |
| 2 | Quote should be fly in animation instead of custom "move"; fade in radishes; remove animation from background.  | Combine radish shapes; change background color to  **#3A566E** ; remove frame shape. |
| 3 |  Headline and text changed to fly in animation instead of custom "move"; frame shape to fly in; **Image to fade in (3000ms)** remove animation on persimmon on left; |  Combine persimmon shape; combine frame shape; combine arrow shape; increase view more font to 12px; change orange color to **#3A566E**; |
| 4 |  Headline and subheading should change to fly in animation instead of custom "move". Background color should fly in (double check this one); remove animation on veggies.  | Combine all the veggie shapes; combine frame shape; update orange color to #000; remove frame shape.  |
| 5 | headline and subheading should change to fly in animation instead of custom "move"; background animation should be removed; remove animation on everything else.  | Remove frame shape. |
| 6 | heading and text updated to fly in instead of custom move; fade in numbers; remove animation on image.  | **Remove** grid shape; combine arrow shape; increase "discover them" font to 12px; change orange color to  **#3A566E** **Text Updated** |
| 7 | frame should be updated to fade in; headline and text should fly in. **Image to fade in (3000ms)**  | **Remove** grid shape; combine arrow shape; increase learn more font to 12px; change orange color to  **#3A566E**. |
| 8 | frame should be updated to fade in; headline and text should fly in. **Image to fade in (3000ms)** | **Remove** grid shape; combine arrow shape; increase view more font to 12px; change orange color to  **#3A566E**. **Page went through some redesign - number is over text now.** |
| 9 |  Frame should be updated to fade in; headline should fly in, text should fly in. **Image to whoosh in (2000ms)**| **Remove** grid shape; change orange to  **#3A566E**. |

See Figma for specifications: https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=7216%3A549493 

If design requests have updated please make note in a comment here so that testing is aware of updated specs. 

## Acceptance 
- Template is updated 
- Relevant stickers are created
- - No more custom animations

**Comment by maxyinger** [comment]
For Page 5 anim updates:
We don't have a background fade animation. Worth adding to the **new requested effects** if we'd like to add one. for now, just going to leave it without an animation.

**Comment by maxyinger** [comment]
For Page 7 what does this mean?

> combine grid shape; combine arrow shape;

Rn, these are already each a single shape?

**Comment by BrittanyIRL** [comment]
> For Page 5 anim updates:
> We don't have a background fade animation. Worth adding to the **new requested effects** if we'd like to add one. for now, just going to leave it without an animation.

This was just me doing a bad job of copy and paste for updates. The background animation is just getting removed, so we're good on this.

**Comment by BrittanyIRL** [comment]
> For Page 7 what does this mean?
> 
> > combine grid shape; combine arrow shape;
> 
> Rn, these are already each a single shape?

Just means combine the layers (like you did for the hearts on the beauty template). If they are already combined, awesome. This is just making sure.

**Comment by BrittanyIRL** [comment]
@samwhale or @embarks could one of you take this over? Angie just let me know that they changed the designs in figma for this template so we'll need to make those adjustments since this is still in review? Since this is recently updated, we'll just want to comb through figma and make necessary updates that are out of sync with the table above of the original updates. I'm so sorry for the extra scope. 
https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=7357%3A544924

**Comment by BrittanyIRL** [comment]
Additionally, the text has just been updated on page 7 - @embarks heads up

**Comment by BrittanyIRL** [comment]
@csossi - had design (@ivayloklissarov ) take a look for visual updates already - so you can focus on any regression/do your qa magic without worrying about figma!

**Comment by csossi** [comment]
Verified in QA

**Comment by BrittanyIRL** [comment]
These were bug bashed by design so i feel like we can close them.
