### ISSUE TITLE
Template Updates: DIY

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6971]
## Description 

Edits in **BOLD** are new from April 6, 2021.

| Page | Animations | Cosmetics |
| --- | --- | --- |
| 1 |  headline updated to fly in; remove background image animation. **Issue No text to fly in**  | combine 'x' shape; change font colors.  |
| 2 | headline updated to fly in; remove background animation.  | change font colors. |
| 3 |  avatar updated to scale in instead of move/zoom. **Quote to fly in**  |  N/A  |
| 4 |  headline updated to fly in; remove background animation.  | change font colors.  |
| 5 | all text updated to fly in. **Image/Shape Fade in (3000ms)** | combine arrow shape; change color of fonts and rectangle shapes; change background color.  |
| 6 |  Swap plus sign and circle to pulse; headline changed to fly in; remove animations on background image and left band.   | combine + shape and change color. |
| 7 | text updated to fly in.  **Image/Shape Fade in (3000ms)** | Change colors of fonts and rectangle shapes; change background color.  |
| 8 | Headline, text, and images should change to fly in. **Tan shape Fade in (3000ms)** | Combine arrow shapes; change background color; change font color; change rectangle shape color. |
| 9 |  Headline change to fly in. **Image/Shape Fade in (3000ms)** | Combine dot shape; change font color; increate tappable spots. |
| 10 | Headline, Text, image change to fly in. **Background Shape Fade in (3000ms)** | combine social media shapes and change color; change background color; change font and rectangle shape color.  |

See Figma for specifications: https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=7216%3A549493 

If design requests have updated please make note in a comment here so that testing is aware of updated specs. 

## Acceptance 
- Template is updated 
- Relevant stickers are created 
- No more custom animations

**Comment by BrittanyIRL** [comment]
@csossi - had design (@ivayloklissarov ) take a look for visual updates already - so you can focus on any regression/do your qa magic without worrying about figma!

**Comment by csossi** [comment]
Verified in QA

**Comment by BrittanyIRL** [comment]
These were bug bashed by design so i feel like we can close them.
