### ISSUE TITLE
Template Updates: Entertainment

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6972]
## Description 

**Bolded* changes from April 6, 2021: https://docs.google.com/spreadsheets/d/1MFtHj7Xwdol9jSk80PXrxWNz_0h1tSfyEe3K7Bn2yZs/edit#gid=0

| Page | Animations | Cosmetics |
| --- | --- | --- |
| 1 |  Headline text changed to fly in. Remove animation on image. **Music Note to fade in (3000ms)**  | rename music shape? (needs clarification)  |
| 2 | headline and subheading text changed to fly in; remove animation on image.   | N/A |
| 3 |  **Everything should Fly in** | Remove one of the "pink" words in background, change position.  |
| 4 |  spotlight text updated to fly in; remove image animation. **Headline to fly in**  | N/A  |
| 5 | stars and ratings updated to fly in; remove image animation. **Text and Button to fade in (3000ms)**  | N/A |
| 6 | remove image animation; **Text to fly in**  | N/A |
| 7 | remove image animation ; **Text to fly in** | N/A  |
| 8 | **Headline to fly in; Images Fade in 3000ms; Text fly in**  | N/A |
| 9 |  Headline and subheading updated to fly in; remove image animation; **Grammys to Fade in (3000ms)** | N/A |

See Figma for specifications: https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=7216%3A549493 

If design requests have updated please make note in a comment here so that testing is aware of updated specs. 

## Acceptance 
- Template is updated 
- Relevant stickers are created 
- No more custom animations

**Comment by BrittanyIRL** [comment]
@csossi - had design (@ivayloklissarov ) take a look for visual updates already - so you can focus on any regression/do your qa magic without worrying about figma!

**Comment by csossi** [comment]
Verified in QA

**Comment by BrittanyIRL** [comment]
These were bug bashed by design so i feel like we can close them.
