### ISSUE TITLE
Template Updates: Fashion

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6973]
## Description 

**Bolded** text are updates from April 6, 2021: https://docs.google.com/spreadsheets/d/1MFtHj7Xwdol9jSk80PXrxWNz_0h1tSfyEe3K7Bn2yZs/edit#gid=0

| Page | Animations | Cosmetics |
| --- | --- | --- |
| 1 | Headline updated to fly in instead of "move"; remove image animation.  | font color change  |
| 2 | Headline updated to fly in instead of move; change round shape to rotate. **Byline to Fly In** | combine starburst arrow shape; change orange color.  |
| 3 |  Headline updated to fly in instead of move; remove image animation.  |  N/A  |
| 4 |  Everything should fly in instead of move.  | change orange color  |
| 5 | Subheading should fly in instead of move, same as learn more. Remove animation on sideways text.  | Combine arrow shape, change orange color.  |
| 6 | headlines change to fly in. **Circle Text to fade in 3000ms**  | combine starburst shape, update orange color.  |
| 7 | zigzag circle should rotate; text should fly in, image shouldn't have an animation. **Prag to fly in**  | combine starburst shape, update orange color, change paragraph text color. **Text updated**   |
| 8 | image should twirl. | combine starburst shape; change orange color; increase tappable shape and remove one of them.  **Get the look to fly in**   |
| 9 |  images should fly in - little weird, check figma;  **Headline to fly in** .  | N/A |

See Figma for specifications: https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=7216%3A549493 

If design requests have updated please make note in a comment here so that testing is aware of updated specs. 

## Acceptance 
- Template is updated 
- Relevant stickers are created 
- No more custom animations

**Comment by BrittanyIRL** [comment]
@csossi - had design (@ivayloklissarov ) take a look for visual updates already - so you can focus on any regression/do your qa magic without worrying about figma!

**Comment by csossi** [comment]
Verified in QA

**Comment by BrittanyIRL** [comment]
These were bug bashed by design so i feel like we can close them.
