### ISSUE TITLE
Template Updates: Fitness

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6974]
## Description 

**Bolded** text are updates from April 6, 2021: https://docs.google.com/spreadsheets/d/1MFtHj7Xwdol9jSk80PXrxWNz_0h1tSfyEe3K7Bn2yZs/edit#gid=0

| Page | Animations | Cosmetics |
| --- | --- | --- |
| 1 | Headline should change to Pulse; remove animation on logo and background image.   | N/A |
| 2 | Quote should update to Fly In since move is custom; remove animation on blocked images in background. **By line to fly in** | N/A |
| 3 |  change 'Run' to pulse animations; like you mean it and other text should be fly in; remove animation on image.  |  N/A  |
| 4 |  Update '5' to pulse; remove animation on image; text updated to fly in instead of move.   | N/A |
| 5 | Headline and text update to fly in; '3' updated to pulse; remove background image animation on shoe.  **Buy Now Button to Fade in at 3000ms** | N/A |
| 6 | Headline, watch, and text area should all fly in instead of move; remove background animation. | N/A |
| 7 | Headline should update to fly in; little circles should change to pulse; background animation removed.  | Combine circle shapes; increase radius of tappable shape.  |
| 8 | Headline should fly in instead of move; **Blocks to whoosh 2000ms**  | N/A |

See Figma for specifications: https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=7216%3A549493 

If design requests have updated please make note in a comment here so that testing is aware of updated specs. 

## Acceptance 
- Template is updated 
- Relevant stickers are created 
- No more custom animations

**Comment by BrittanyIRL** [comment]
@csossi - had design (@ivayloklissarov ) take a look for visual updates already - so you can focus on any regression/do your qa magic without worrying about figma!

**Comment by csossi** [comment]
Verified in QA

**Comment by BrittanyIRL** [comment]
These were bug bashed by design so i feel like we can close them.
