### ISSUE TITLE
Template Updates: Travel

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6975]
## Description 

**Bolded** text are updates from April 6, 2021: https://docs.google.com/spreadsheets/d/1MFtHj7Xwdol9jSk80PXrxWNz_0h1tSfyEe3K7Bn2yZs/edit#gid=0

| Page | Animations | Cosmetics |
| --- | --- | --- |
| 1 | Remove headline animation. **Logo to fly in; Background image to fade in 3000ms**  | N/A |
| 2 | Remove image animation; headline updated to Fly in. **Byline to fly in** | N/A |
| 3 |  Headline and text updated to fly in; remove animation on image.  |  Change background of 'learn more' shape.   |
| 4 |  Says to make it the same as the animation on page 10, so fly in?  | N/A |
| 5 | Remove animation on headline and text. **Background image fade in 3000ms**  | N/A |
| 6 | Headline updated to fly in; map shape updated to fade in; remove background animation. | combine map shape.  |
| 7 | Remove animation on image; headline and text updated to fly in.  **image to fade in 3000ms** | Update background of learn more shape.  |
| 8 | Headline and text updated to fly in; remove background animation. **Learn more to fade in 3000ms**  | update background color of learn more shape; update font color.  |
| 9 | **Images to whoosh in 2000ms** | N/A |
| 10 | Headline to fly in; remove animation on social icons. **images to whoosh in 2000ms** | combine social media shapes. |
 
See Figma for specifications: https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=7216%3A549493 

If design requests have updated please make note in a comment here so that testing is aware of updated specs. 

## Acceptance 
- Template is updated 
- Relevant stickers are created 
- assistive text is updated so that prepublish checklist is happy

**Comment by BrittanyIRL** [comment]
Edits: 

- Since background images cannot fade in or fly in - after talking to Ivo decided to do the following: 
1) Elephant bg image will zoom in on page 1 (was supposed to fade in) 
2) Photographer bg will pan in from left on page 5 (was supposed to fly in)

I also made up assistive text for images per request of design so that the pre publish checklist doesn't complain about that in the template. Text is as follows: 
Page 1 elephant: Close up of elephant's face
Page 2 food: Variety of prepared food dishes
Page 3 food: Preparing a street food dish
Page 4 boats: Aerial view of floating market boats
Page 5 photographer: Tourist taking a photo
Page 6 temples: Temples surrounded by greenery
Page 7 statue: Close up of statue in 3 Kings Monument
Page 8 boat: Boat with many passengers near island mountain
Page 9 squares from top to bottom: Boat near beach in Phuket / Person riding a scooter on a road / Close up of red curry dish / Close up of palm branch
Page 10 rectangles from top to bottom: Variety of peppers / Person hiking during sunset / Two monkeys swimming

**Comment by csossi** [comment]
Verified in QA

**Comment by BrittanyIRL** [comment]
These were bug bashed by design so i feel like we can close them.
