### ISSUE TITLE
Template Updates: Wellbeing

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6976]
## Description 

**Bolded** text are updates from April 6, 2021: https://docs.google.com/spreadsheets/d/1MFtHj7Xwdol9jSk80PXrxWNz_0h1tSfyEe3K7Bn2yZs/edit#gid=0

| Page | Animations | Cosmetics |
| --- | --- | --- |
| 1 |  Logo updated to fly in; remove animation on image. **Headline to fly in**  |  For all frames, only use 3 blob shapes to create less shape in library.  |
| 2 | Quote mark update to Fly in; **Byline to fly in** | N/A |
| 3 |  Text area updated to fly in; remove animation on learn more. **Headline to fly in**   |  Combine arrow shape.  |
| 4 |  Remove animation on headline; Update circles to Pulse.  | Combine arrow shapes? Increase tappable shapes. (this image has branding in it, is that ok? has this always been here?) |
| 5 | Remove animation on learn more; text area updated to Fly in. **Headline to fly in**  | Combine arrow shape (same arrow as wellbeing 3)  |
| 6 |  All text updated to fly in; remove animation on white rectangle.  | N/A  |
| 7 | **Text and Number to fly in**  | N/A  |
| 8 | Text area updated to fly in; remove animation on learn more. **Headline and number to fly in**  | Combine arrow shape (same as wellness 3); Move yellow shape to the right;   |
| 9 |  All updated to fly in.  | move blue shape down a little.  |
| 10 | Remove animation on headline; update images and text next to them to fly in. | N/A  |
 
See Figma for specifications: https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=7216%3A549493 

If design requests have updated please make note in a comment here so that testing is aware of updated specs. 

## Acceptance 
- Template is updated 
- Relevant stickers are created 
- No more custom animations

**Comment by BrittanyIRL** [comment]
@csossi - had design (@ivayloklissarov ) take a look for visual updates already - so you can focus on any regression/do your qa magic without worrying about figma!

**Comment by csossi** [comment]
Verified in QA

**Comment by BrittanyIRL** [comment]
These were bug bashed by design so i feel like we can close them.
