### ISSUE TITLE
Render lightbox on top of other elements in the page

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#6979]
## Feature Description

This [OneClick Chat to Order](https://wordpress.org/plugins/oneclick-whatsapp-order/) plugin has the z-index set to [999999](https://jmp.sh/8b38UjQ) which positions the display of the floating button on top of the lightbox. See [example](https://jmp.sh/nKKeVAL).

Consider increasing the z-index in the Web Stories plugin to have the lightbox render on top of other elements in the page.

## Additional Context
Noticed in this related [support topic](https://wordpress.org/support/topic/the-plugin-not-working-fine-in-rtl-control-panel/)  site [URL](https://designs.marketing.limited/default_arabic/) 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

Increase z-index to 999999?

**Comment by spacedmonkey** [comment]
@LuckynaSan I am able to replicate this issue in a browser. Can you provide a screencast or a link where this is happening?

**Comment by LuckynaSan** [comment]
@spacedmonkey When you click a story in the carousel layout on the user's site:  https://designs.marketing.limited/default_arabic/ you'll notice the floating button pull in on the left-hand corner. 

To replicate, activate the plugin, enable the floating button, then view the story. 

![image](https://user-images.githubusercontent.com/66372350/115558681-f97a7d80-a280-11eb-9f91-1f6c1fd1f76a.png)
