### ISSUE TITLE
Inconsistent story navigation

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#6982]
## Bug Description

The purpose of this ticket is to monitor an issue with irregularities in story navigation as reported in this [topic](https://wordpress.org/support/topic/the-plugin-not-working-fine-in-rtl-control-panel/). At the moment, it is unclear if this issue is caused by the RTL layout, theme, or unique site configuration. 

The following is a list of inconsistencies found on the user's [site](https://designs.marketing.limited/default_arabic/):
- exit button not functioning after several clicks
- skip forward button disabled
- stories in carousel layout jumping out of place
- story in the carousel doesn't start after clicking on it

## Steps to Reproduce

Currently unable to reproduce.

## Screenshots

Here is a screen recording of the issue: https://jmp.sh/YQKJMaF
These are the console errors:
<img width="859" alt="Screen Shot 2021-03-30 at 10 39 16 AM" src="https://user-images.githubusercontent.com/66372350/113314938-c759a980-92da-11eb-97ab-3410f1e3df10.png">
<img width="1427" alt="Screen Shot 2021-03-30 at 10 36 40 AM" src="https://user-images.githubusercontent.com/66372350/113314959-caed3080-92da-11eb-944a-4a78f9b0f630.png">

## Additional Context

related topic: https://wordpress.org/support/topic/the-plugin-not-working-fine-in-rtl-control-panel/

- Plugin Version: 1.5.0
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
@LuckynaSan Is this still an issue & reproducible?

**Comment by LuckynaSan** [comment]
The issue still occurs on this specific site. We need additional information to try to reproduce or troubleshoot but the user has been unresponsive.

**Comment by swissspidy** [comment]
Is this still an issue & reproducible?

I'll close this and we can reopen if it ever comes up again.

**Comment by LuckynaSan** [comment]
It is not. We'll keep an eye out. Thanks!
