### ISSUE TITLE
Ability to use 3P Media for story poster image

### ISSUE THREAD

**Issue by shishirm** [GoogleForCreators/web-stories-wp#6984]
## Feature Description

Right now, it is only possible to set an image from the media library as the poster for the Story. The request is to be able to set a Stock image from Unsplash as the poster from within the editor window.

## Alternatives Considered

The alternative is to download every image onto local systems and then reupload to the media library. But this is cumbersome and might potentially circumvent any copyright restrictions.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Thanks a lot for sharing your idea!

Given the requirements and recommendations for the poster image (see  https://www.youtube.com/watch?v=nKi1QWPwZng and https://developers.google.com/search/docs/advanced/appearance/web-stories-creation-best-practices for example) it seems unlikely that any image from a third-party media provider will make for a great poster image without any cropping or similar.

But curious to see whether this is a more common request.
