### ISSUE TITLE
Pre-Publish-Checklist: Enable and improve e2e tests

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#6985]
## Feature Description

Now that prepublish checklist are merged, we should be able to unskip these tests / or if not, remove them all together. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Which tests does this refer to? Please share links to the code.

**Comment by spacedmonkey** [comment]
https://github.com/google/web-stories-wp/blob/b5ff77d53e6125235023f140f6820890f6d6c096/packages/e2e-tests/src/specs/editor/prepublishChecklist.js#L24-L48

**Comment by swissspidy** [comment]
Hmm interesting. Don't know why they weren't enabled from the beginning, just with toggling the feature flag before and after. :shrug:

Not sure how much value they add though. I'd probably remove the second test there.

The first check could be improved a little with improved `toMatchElement` and `toClick` calls.
Also, a percy snapshot seems feasible.

The pre-publish checklist has good test coverage at lower levels already, so I don't want to overdo it here.

**Comment by csossi** [comment]
Verified in QA

**Comment by swissspidy** [comment]
@BrittanyIRL Why was this sent to QA? There's nothing @csossi can really test here (so IDK what exactly was verified here...)
