### ISSUE TITLE
Dashboard: Focus Trap after focusing away from context menu

### ISSUE THREAD

**Issue by samwhale** [GoogleForCreators/web-stories-wp#6996]
## Bug Description

Unable to click anything except the context menu after:
1. Opening the context menu
2. Tabbing into the menu to focus an item
3. Clicking the `Delete Story` button

## Expected Behaviour

Should be able to click anywhere after above steps

## Steps to Reproduce

Go to dashboard

1. Opening the context menu for a story
2. Tab into the menu to focus an item
3. Click the `Delete Story` button
4. Click `Cancel` in the modal
5. Click the `Search` bar. Can't enter it and the animation replays for the story you were looking at.

## Screenshots

![broke](https://user-images.githubusercontent.com/22185279/113459071-9c9e4c80-93d1-11eb-9af1-dfcc1d792225.gif)

## Additional Context

- Plugin Version: 1.6.0-alpha.0+b5ff77d
- WordPress Version: 5.7
- Operating System: macOSX Big Sur 11.2.2
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by samwhale** [comment]
**Note**: This happens specifically when the dialog is opened!

**Comment by csossi** [comment]
Verified in QA
