### ISSUE TITLE
Media Panel - Search Bar Missing X to Clear Query

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#701]
## Bug Description

After entering a search term there is no X icon to clear the search field.

![image](https://user-images.githubusercontent.com/5874851/77255932-51d7e980-6c41-11ea-84d1-57ede89c2789.png)

Taken from Claudio in #585

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
![Screenshot from 2020-03-23 18-11-25](https://user-images.githubusercontent.com/237508/77348685-cb4f0500-6d31-11ea-91a4-0286c622710d.png)
See have styling for this elsewhere.

**Comment by winterDroid** [comment]
@samitron7 shall the search button UI stay as is just with the added X, or shall it be like in the link form input?
