### ISSUE TITLE
Video Optimization: 3P Media not loading with cross-origin isolation

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7016]
## Bug Description

This is a follow-up to #6875 .

With these new headers, 3P media are no longer loaded due to missing `crossorigin` attributes.

## Expected Behaviour

All 3P media (images, videos, GIFs) should load just fine

## Steps to Reproduce

1. Enable video optimization
2. Go to 3P media tab
3. See console errors

## Screenshots

<img width="1263" alt="Screenshot 2021-04-04 at 16 36 00" src="https://user-images.githubusercontent.com/841956/113512214-d99a4880-9563-11eb-92f4-e5f6728d8b19.png">

## Additional Context

- Plugin Version: 1.6.0-alpha
- WordPress Version: 5.7
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

All 3P media (images, videos, GIFs) should load just fine when cross-origin isolation is enabled.

**Comment by csossi** [comment]
Verified in QA
