### ISSUE TITLE
Aspect Ratio Changed after Dragging Video to Upload as Background

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#703]
## Bug Description

Dragged a video from Win Explorer onto page as background. Video appears like this, rather than taking up the entire background:
![image](https://user-images.githubusercontent.com/5874851/77256489-06273f00-6c45-11ea-8930-a88d6f4f40bd.png)

## Steps to Reproduce

1. Drag a video from local onto the page to upload it and set it as the background
2. On initial "load" on the page it appears as expected
3. Wait a few seconds and it changes from filling the background to a smaller size

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by ndev1991** [comment]
Q: @pbakaus @jauyong @barklund @swissspidy When image or video set as background should they have full page size? Like 
```const MEDIUM_EDITOR_PAGE_WIDTH = 268;
const MEDIUM_EDITOR_PAGE_HEIGHT = 476;```
