### ISSUE TITLE
Create a new simplified dropdown

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#7056]
## Feature Description

Create a new simplified dropdown to be used in various places. Features:

* Dropdown arrow is left-aligned after the text and will move with the current text as it grows longer or shorter
* Dropdown will open so that the popup aligns top left with the initial text button to open the dropdown and will resize in width according to content

This dropdown is to be used:

* As the media type filter in the element library
* As the saved color source in the color picker
* As the custom or default page template selector in the page template library

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
