### ISSUE TITLE
Add delayed tooltip to the element library tabs

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#7057]
## Feature Description

Add a tooltip to the element library tabs that will appear instantly on keyboard focus but only delayed on mouse hover. Delay to be aligned with UX.

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Tooltip not changing when using keyboard nav:

https://share.getcloudapp.com/nOuoKzNr

**Comment by csossi** [comment]
Verified in QA
