### ISSUE TITLE
Use custom page template API 

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#7060]
## Feature Description

Use the custom page template API to:

* Save the current page as a page template when clicking the relevant button
* Display all available page templates when switching to the custom template view

Note that when adding a custom page template, it is added first to the list and the view switches to custom page templates even if the user is currently viewing default page templates.

No error handling for now.

See [Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=7082%3A531446) for further details

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@barklund Should we add a separate issue for pagination of the saved templates?
