### ISSUE TITLE
Delete custom template functionality

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#7062]
## Feature Description

Add a mini-menu to a custom template on hover, that allows the user to delete a custom template with confirm dialog. When confirming, use API to correctly delete the template and make sure it's removed from local view instantly.

Check [Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=7082%3A531446) for details.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
