### ISSUE TITLE
Make sure empty pages cannot be added as a page template

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#7064]
## Feature Description

If the user attempts to add an empty page as a page template, do nothing and inform the user in a snackbar message.

Only a page without elements, with a white background color, and no background media, is considered empty. As soon as an element is added or the background color is changed, the page is considered non-empty.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
