### ISSUE TITLE
Remove custom page template feature flag

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#7065]
## Feature Description

Remove the feature flag and all relevant code and make sure the feature has full test coverage (both automated and QA).

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA

**Comment by miina** [comment]
Note: Not sending this to UAT because the previous issues addressing different parts of Page templates have already been sent to UAT.
