### ISSUE TITLE
Rename "page layouts" to "page templates"

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#7102]
## Feature Description

Rename _"(page) layouts"_ to _"page templates"_ throughout the editor in both user-visible labels and internal variables.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Could also rename the labels here on GitHub I think :-)

**Comment by csossi** [comment]
Verified in QA
