### ISSUE TITLE
Revert change from "Cover image" back to "Poster image"

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#7105]
## Bug Description
"Poster image" was incorrectly changed to "Cover image" as part of redesign, see also https://github.com/google/web-stories-wp/pull/6373

We should revert this back to "Poster image".

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
