### ISSUE TITLE
Remove 'Increase video or image size on the page' check

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#7108]
## Description 
This check flags images that aren't full size and is pretty limiting to design implementations so the design team has recommended we remove this check. 

## Implementation suggestions 
- Let's just remove the check from the array that decides what checks to run and leave the actual code for the check intact just in case we want it later.

## Acceptance Criteria 
- Image/video size is no longer flagged in checklist no matter how small the image or video is.

**Comment by csossi** [comment]
Verified in QA
