### ISSUE TITLE
Redesign: Update tabs within the 3rd party Media panel

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#7121]
## Feature Description
See [Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=5511%3A441664)

- [x] Redesign the tabs in the 3rd party media panel (Images, Video, GIFs).
- [x] Make sure not to leave any unused components/styles to the codebase.

![Screenshot 2021-04-07 at 11 41 52](https://user-images.githubusercontent.com/3294597/113837209-e5695300-978d-11eb-92a9-c307a840c2d4.png)

**Comment by csossi** [comment]
Verified in QA
