### ISSUE TITLE
Block: Remove DEPRECATED_THEME usage

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7122]
## Feature Description

Just like #6707 / #6990, but for the Web Stories block.

Now that new designs are in, we should be able to remove all the `DEPRECATED_THEME` instances in the block.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

Block still works as it currently does. Entirely regression test based.

**Comment by spacedmonkey** [comment]
I can only find two references to the theme. 

https://github.com/google/web-stories-wp/blob/291f8d11d88ede9a0180b7c4fd2c429f6c327892/assets/src/web-stories-block/block/block-types/selected-stories/storyPreview.js#L46-L47

What would we do about this? Just hard code the values or can we get these colours from somewhere else?

**Comment by spacedmonkey** [comment]
@miina @BrittanyIRL Do either of you have an recommendation on what I should replace these `DEPRECATED_THEME` references?

**Comment by BrittanyIRL** [comment]
you could hard code it to keep it the same as before the theme update, that would be 
```
border-radius: 4px;
border: 1px solid #D9DBDD;
``` 

Or if you want to update to new theme just swap it out for this: 
```
border-radius: ${theme.borders.radius.small};
border: `1px solid ${theme.colors.border.defaultNormal}`;
```


(pulled this from the updated cardPreview in dashboard)

**Comment by swissspidy** [comment]
Please use the new theme.
