### ISSUE TITLE
Animations: Missing internationalization

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7123]
## Bug Description

Some strings in `defaultAnimationProps.js` aren't translatable, which seems like a bug.

https://github.com/google/web-stories-wp/blob/07c07c1af196da69ef13dfeceb2af87d83fc2ee6/assets/src/animation/parts/defaultAnimationProps.js#L54-L89
## Expected Behaviour

All user-facing strings should be localizable (translatable)

## Additional Context

- Plugin Version: 1.6.0-alpha
- WordPress Version: 5.7
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Testing in 7361 - am unable to get PAN to work at all regardless of resizing bg element

**Comment by csossi** [comment]
Retried PR 7361

No change - still unable to use Pan animation even after resizing bg image

**Comment by swissspidy** [comment]
^ @littlemilkstudio

**Comment by maxyinger** [comment]
Thanks for the ping. I'll check it out

**Comment by maxyinger** [comment]
I just rebased the main branch while this PR was back in review, but other than that didn't touch anything. Wasn't able to replicate pan not working. Here's my experience on that branch:

https://images.zenhubusercontent.com/235435637/0c2cbf0e-2934-4437-bc82-70e2418ea337/kapture_2021_05_14_at_10_50_24.mp4

@csossi do you have any further details on how you got `pan` not to work on your end?

**Comment by BrittanyIRL** [comment]
@csossi if possible, i'd like to give this issue priority for testing as it blocks additional work. Thanks!

**Comment by LuckynaSan** [comment]
@BrittanyIRL Hey, I am also seeing this on [Stories-new](https://stories-new-wordpress-amp.pantheonsite.io/) and our test site.

<img width="1093" alt="Screen Shot 2021-05-19 at 12 26 21 PM" src="https://user-images.githubusercontent.com/66372350/118852074-6c870c00-b8a0-11eb-8dd2-47e02cd6dd2c.png">

<img width="1434" alt="Screen Shot 2021-05-19 at 12 44 01 PM" src="https://user-images.githubusercontent.com/66372350/118851772-1e720880-b8a0-11eb-8d51-28c2cd105da3.png">

The issue has also been [reported by a user](https://wordpress.org/support/topic/background-pan-effect-not-working-after-upgrade-to-1-7-1/) using v1.7.1. 


Steps to reproduce: 
- Set an image as the background
- Set the animation to pan

**Comment by swissspidy** [comment]
Note that #7361 hasn't been merged yet, so you won't see its effect on stories-new just yet.
But not sure if the above screenshot is related to it or if it's a separate issue.

**Comment by swissspidy** [comment]
^ @littlemilkstudio could you perhaps clarify whether #7361 is addressing that bug?

**Comment by maxyinger** [comment]
Yeaup. #7361 fixes that pan regression bug

**Comment by csossi** [comment]
Pan and Zoom behaviour changes to be the same as Zoom In on image resize

added image background
checked Pan And Zoom - worked fine
enlarged the image (needed to be enlarged to allow Pan Up, Pan Down, and Zoom In to work)
Pan Up, Pan Down, and Zoom In work fine - but now Pan And Zoom (which was fine before enlarging) changes to be the same as Zoom In

**Comment by csossi** [comment]
Verified in QA
