### ISSUE TITLE
Animation preview not triggered for background video on effect selection

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#7132]
Found in bugbash 1.6 by @barklund  

When you swap out or add a background animation to a background video it should trigger the animation just like it does for images, right now it doesn't.  (the animation will play when you trigger 'play' on the canvas, just not automatically when you make a choice in the dropdown)

(3 points is probably overkill, but allows time for any needed discovery)

### Acceptance Criteria 
- Animation should play on effect select for background video same as it does for a background image.

**Comment by embarks** [comment]
@BrittanyIRL (hopefully) resolved by [#7069](https://github.com/google/web-stories-wp/pull/7069)
https://images.zenhubusercontent.com/235435637/a9d2ce87-8e69-4285-a488-671a051199b7/kapture_2021_04_12_at_14_13_31.mp4

@csossi let's QA this for good measure:

1. Create a new story (any environment, this fix should already be in production)
2. Add a video as the background (either third party or uploaded should work)
3. The animation input will remind you, but the video needs to extend past the edges of the canvas to use background animatiosn (double click the bg and make it larger than the canvas with the slider)
4. Open the animation panel, animation dropdown, and select an effect.
5. The animation should play on the canvas as shown in the above video.

**Comment by csossi** [comment]
Verified in QA
