### ISSUE TITLE
Page Templates: Loading View

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#7133]
## Feature Description

The first time page templates is loaded or toggled can be an intensive load as the templates are prepped and then stored for future use in the editor. Having a loading screen to let users know nothing is frozen would be helpful. 

This would be helpful to get design input on. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
Let's just use existing loading components here

**Comment by BrittanyIRL** [comment]
@csossi - all this is is checking to see that when page templates are loading (default or saved) you get a loading spinner now instead of just a blank section.

**Comment by csossi** [comment]
Verified in QA
