### ISSUE TITLE
Layers Panel: Add Sticker Support 

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#7134]
## Feature Description

Sticker feature development and the layers panel redesign were done in tandem and missed each other so it wasn't noticed that stickers were missing in the layers panel. We need to add support for them. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

- Stickers show up in a readable manner on the layers panel with display text of "Sticker".  (Right now stickers are really limited, to test this use the beauty template and go to the page with the hearts on it, the hearts are stickers)

**Comment by BrittanyIRL** [comment]
@csossi this is the last of the bug bash tickets pea pod is hoping to get in for 1.6 release, if you have time.

**Comment by csossi** [comment]
Verified in QA
