### ISSUE TITLE
Update Checklist Copy

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#7136]
## Description

Update PPC checklist copy according to the "HUGE" tab of this document: https://docs.google.com/spreadsheets/d/1PjaRp4bueQ3Cv14A7I696m0vjGCIX_kN9tIGh-V-Bkc/edit?ts=5fbd398a#gid=920793050 

## Acceptance Criteria 
- Text is updated

**Comment by csossi** [comment]
Verified in QA
