### ISSUE TITLE
PPC cosmetic updates

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#7137]
## Description

Pre Publish Checklist has some design updates that are not related to logic. This ticket is for that work. Check Figma to be sure, however these updates should include: 
- Updates to list structure (bullets are now on the suggested title not the body text since the text is getting updated to not be lists anymore). 
- Icon colors have been updated.
- Panel sections should have a 'disabled' state now 

## Acceptance Criteria 
- PPC checklist UI is updated to mirror figma: https://www.figma.com/file/1YM3jA9h4QGc4xLdyaXIJS/Stories-Sprint-1.7?node-id=7045%3A7520

![Screen Shot 2021-04-07 at 3 14 07 PM](https://user-images.githubusercontent.com/10720454/113941448-f462fc00-97b3-11eb-92a4-b0fd6f83b643.png)
![Screen Shot 2021-04-07 at 3 14 21 PM](https://user-images.githubusercontent.com/10720454/113941449-f4fb9280-97b3-11eb-8252-cf76bc415ae7.png)
![Screen Shot 2021-04-07 at 3 14 14 PM](https://user-images.githubusercontent.com/10720454/113941450-f5942900-97b3-11eb-9b14-42dac3b4a11f.png)

**Comment by BrittanyIRL** [comment]
To test this specific issue is just the following: 
- icon color of the exclamation mark on the prepublish panel is now always a white color not red or blue or yellow
- the tooltip text has updated to be: `Make updates before publishing to improve discoverability and performance on search engines` (instead of `There are items in the checklist to resolve`)
- The little discs showing list items on the checklist have been moved up one text level.

Everything else will show up as we add triggers and is not user facing.

Branch to test is #7277

**Comment by csossi** [comment]
Getting this crash on loaded branch 7277:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/ec3149ec-6fd1-4757-886d-b2f0a33cf3f6)

**Comment by BrittanyIRL** [comment]
Weird! I rebased and this issue seems gone? Will you look again, @csossi ?

**Comment by csossi** [comment]
Verified in QA
