### ISSUE TITLE
PPC Trigger: Recommendations

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#7139]
## Description

When a user adds a second page to their web story they should be able to interact with recommended PPC items. 

(from figma system response)
```
If the user is on a different panel (Design or Document), we will not change it. Next time the user goes to the PPC panel, then:

As a default state, display both categories on the PPC: 
High priority (collapse and disable).
Recommended (expanded).

Use a notification count number to indicate the amount of incurring issues on the Recommended category.

Exclude all Priority issues. To know when to display Priority recommendations, follow the PPC notification icon triggers.

Publish button; on hover display tooltip.
```

Points of clarification: 
- While recommended panel will expand when the flag to show recommended checklist items is flipped for the first time, from there the user settings should be respected. Should only auto expand once. 

## Implementation Suggestions 
-  Some sort of flag to delineate between only recommendations and all items would be useful since we'll need to reference it on the publish button for tooltips. 

## Acceptance Criteria 
- Still no icons on publish button or checklist panel title. 
- Tooltip on hover of publish that says `Review checklist to improve performance before publishing` 
- Recommended tab is expanded
- Recommended tab now has badge with count of items populated 
https://www.figma.com/file/1YM3jA9h4QGc4xLdyaXIJS/Stories-Sprint-1.7?node-id=7045%3A7520

![Screen Shot 2021-04-07 at 3 25 23 PM](https://user-images.githubusercontent.com/10720454/113942339-7acc0d80-97b5-11eb-8440-5969ab566ccc.png)

**Comment by csossi** [comment]
I see the High Priority section becoming enabled when i add a fifth page, but shouldn't it become disabled again when I delete a page to bring it down to 4 or less?

https://share.getcloudapp.com/4gu24Poz

**Comment by samwhale** [comment]
@csossi good call out! Once it's enabled it shouldn't disable again, right @BrittanyIRL?

The PrePublish Checklist 'checkpoints' can be hit only once. Once they've been hit, there is no 'undo'

**Comment by BrittanyIRL** [comment]
It should stay enabled, yup!

**Comment by csossi** [comment]
Verified in QA
