### ISSUE TITLE
Error when dragging text on page with animation on different element

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#7146]
## Bug Description

This was a weird one to debug and reproduce, but I narrowed it down to the below reproduction steps.

## Expected Behaviour

Text element should be dropped without an error occurring.

## Steps to Reproduce

1. Create a new story
2. Add a shape element to the page and apply an animation to the shape
3. Add a new text element
4. Start dragging the text element around and observe that the text field jumps around, the safe-zone is stuck, and an error is reported in the console.

## Screenshots

![text-drag-bug](https://user-images.githubusercontent.com/637548/113941061-765f1f00-97cc-11eb-9635-c5e395005916.gif)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
