### ISSUE TITLE
Canvas Zoom: Video play button is placed above the media asset even when it shouldn't

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#7163]
## Bug Description

When a page is zoomed in, the video play button fits inside the video, but is still displayed above:

## Expected Behaviour

The play button should appear within the asset when there is enough space for it to do so.

## Screenshots

![image9.png](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/41ba4c37-4f04-4d98-8bf8-5a498d32cc9a)
## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Possible duplicate of or at least closely related to #6958

**Comment by bmattb** [comment]
yep dupe
