### ISSUE TITLE
Sticker object drag handle doesn't do anything

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#7164]
## Bug Description

Selecting and moving a sticker's drag handle doesn't do anything.

## Expected Behaviour

It should alter the presentation of the sticker

## Screenshots

![image3.png](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/619091a1-06ac-45b3-8c9a-cc81f405efc7)
## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
We'll fix this when we actually make the sticker panel! https://github.com/google/web-stories-wp/issues/6033

**Comment by csossi** [comment]
Verified in QA
