### ISSUE TITLE
Update color palettes on templates

### ISSUE THREAD

**Issue by embarks** [GoogleForCreators/web-stories-wp#7169]
## Task Description
The color palettes on the template details page are out of date from the template updates in the 1.7 relase. E.g.
![image.png](https://images.zenhubusercontent.com/5f7b469a8022e02e0b23aea1/54623a03-62d4-4ecb-9882-8e993fc5f305)

Need to choose which colors that show on the template details page.

**Comment by embarks** [comment]
@BrittanyIRL Following up with Pascal and Sam later on this one. There's a discussion thread in the design channel. With incoming templates this creates a lot of work to make human readable color lists. We may decide to get rid of it.

**Comment by csossi** [comment]
Verified in QA
