### ISSUE TITLE
3P Media: Attribution pill styling broken

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7189]
## Bug Description

Styling for the 3P media provider attribution pills (for Tenor and Coverr) is broken since the recent redesign efforts.

## Expected Behaviour

No broken styling

## Steps to Reproduce

Go to 3P media tab

## Screenshots

Broken styling:

<img width="323" alt="Screenshot 2021-04-12 at 12 15 05" src="https://user-images.githubusercontent.com/841956/114379398-0e705600-9b89-11eb-81d0-f8f96c2d1a77.png">

<img width="214" alt="Screenshot 2021-04-12 at 12 18 37" src="https://user-images.githubusercontent.com/841956/114379531-3790e680-9b89-11eb-9acb-aed2237d6f73.png">

In version 1.5.0 it looks like this:

<img width="302" alt="Screenshot 2021-04-12 at 12 16 06" src="https://user-images.githubusercontent.com/841956/114379260-dd902100-9b88-11eb-85af-48fcd28b144e.png">
<img width="254" alt="Screenshot 2021-04-12 at 12 16 03" src="https://user-images.githubusercontent.com/841956/114379478-26e07080-9b89-11eb-8e32-516921485722.png">

## Additional Context

- Plugin Version: 1.6.0-alpha
- WordPress Version: 5.7
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
@miina @barklund - does this look familiar to you? Tagging for awareness, will add it to pea pod for the next release cycle - if you have a quick fix feel free to take it.

**Comment by miina** [comment]
@BrittanyIRL Not 100% sure but it might have gotten broken within #6935 when replacing all the old theme, if that's the case, it should be due to a missing/incorrect colour assignment. I did make some adjustments based on [design](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=1799%3A32348) there.

**Comment by BrittanyIRL** [comment]
Makes sense, thanks Miina! I'll update :)

**Comment by csossi** [comment]
Verified in QA
