### ISSUE TITLE
Allow usage of editor on WordPress frontend

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#7207]
## Feature Description

As mentioned in this [support topic](https://wordpress.org/support/topic/support-for-multi-vendor-website-running-on-wcfm-by-wclovers-com/#post-14265705), [WCFM front-end manager plugin](https://wordpress.org/plugins/wc-frontend-manager/) inquired about a way to enable story editing from the frontend / non-wp-admin side for vendor/ custom user roles. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
There are no plans to support displaying a story editor on the frontend, but with the decoupling effort it would be possible for a developer to implement this on their own. Hence closing for now.
