### ISSUE TITLE
Page Templates: Display the button for saving new template as part of the list

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#7219]
## Feature Description

See [Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=7082%3A532191)

Currently, the Save new template button is displayed separately, however, it should be part of the list as per Figma for both saved and default templates. There are some issues with it since the grid is created by virtual list and adding the button to be part of the virtual list is not that straightforward. There are some possible approaches for this, see [this comment](https://github.com/google/web-stories-wp/pull/7208/files#r613188637). 

Additionally, @barklund is suggesting to potentially change it so that it would be take the whole row + potentially be sticky as well.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by AceTheCreator** [comment]
@miina can i give this issue a shot?

**Comment by miina** [comment]
@AceTheCreator This issue might need some input from @barklund regarding potential design change first.
@barklund Can you confirm?

**Comment by AceTheCreator** [comment]
@miina I'd wait for @barklund response, but in the meantime i can't access the figma link you provided above

**Comment by miina** [comment]
@AceTheCreator The issue is still waiting for design confirmation so Figma is not accurate right now. The description will be updated with a screenshot once it's done. Note that this issue is already assigned to a team and is a small non-functional part of a feature that's already being worked on (Page Templates, assigned to Pod Prometheus) so it might be a bit complicated to pick up. Let me know if there was a specific reason you were thinking of this issue to work on, perhaps there is a ready to work on issue that's still unassigned instead. Thoughts?

**Comment by AceTheCreator** [comment]
@miina Guess you're right. I just found the issue interesting, so I thought I could tackle it. Can you specify some of the unassigned issue to me? I'd be glad to work on them.

**Comment by barklund** [comment]
@AceTheCreator, hi there and thanks a lot for volunteering to lend a helping hand. I have marked [a number of issues with the label **_Good First Issue_**](https://github.com/google/web-stories-wp/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22), that you probably will be able to pick up without interfering with other developers while still having something challenging to deal with. Let me know if any catch your fancy and if you require additional information to deal with any of them.
