### ISSUE TITLE
Settings: Add e2e tests for publisher logo file upload 

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#7224]
## Feature Description

Spawned from #7215 - we should have an e2e test on publisher logo upload to prevent regression as we witnessed in 7215 where the query stopped recognizing multiple instances of the same key.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

New e2e test for publisher logo file upload

**Comment by swissspidy** [comment]
Assigning pea pod to this.

Would be good if you could prioritize this to prevent regressions.

**Comment by BrittanyIRL** [comment]
Yup 100%, we should have space in our next sprint.
