### ISSUE TITLE
Templates: Reset page/element selection and `globalStoryStyles`

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7227]
## Task Description

As mentioned at https://github.com/google/web-stories-wp/pull/6988/files#r614312125, some templates do have `current` (the page selection) and `selection` (the selected element(s)) set.

We should reset those in all templates.

`current` should be set to `null`
`selection` should be an empty array

A new test should be added in `packages/templates/src/test/raw.js` to test for this.

**Comment by maxyinger** [comment]
Does it matter if this info is in the raw or not? Just double checked the function that loads in the templates and seems that it selectively takes the selected properties off the raw data and ignores others:

 https://github.com/google/web-stories-wp/blob/37908fd08b72de83621f074136e4ebd189200eba/packages/templates/src/getTemplates.js#L23

**Comment by swissspidy** [comment]
Where does it selectively take selected properties there? That function does `...data.default` and `data.default` is the whole template object, including `current` and `selection`

**Comment by swissspidy** [comment]
Amendment: `globalStoryStyles` in templates should also be reset. It's not used when opening a template in the editor, so not a big deal if it's there, but it makes sense to remove everything that's not really related to the template itself.
