### ISSUE TITLE
PPC: Add toggle to enable auto media optimization 

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#7256]
## Description 
If there is at least 1 instance of a video in the active story that has not been optimized show a toggle button in the Prepublish Checklist to allow users to enable video optimization automatically for future uploads. This toggle will live in a new section of the panel called "general". In v2 of the ppc there will be more added to this section, for now we're not worrying about that. The General panel should follow the same design cadence as the nested pages structure of recommended and high priority. 

This functionality is already present in the editor via a dialog that shows up on first video upload (you will have to wipe your local storage to see it probably) as well as on the dashboard settings page. 

## Implementation Details 
- Not all users can upload media, this toggle should only be present if users can upload media. See Dashboard Settings for an example of this. 

## Acceptance Criteria 
- New toggle button with accompanying text to automatically optimize further video uploads to the editor.
- Toggle should show up if there is an unoptimized video present. 
If the user toggled the switch to optimize future uploads then the toggle should disappear on future returns to the PPC panel but it should stay intact while the panel remains open in that action so that it's not jarring. 
- New unit tests should be added, karma should test functionality as well as when the toggle disappears on return visits to the panel after panel view is swapped.

Ignore the "optimize all videos" button in this screenshot and figma. Link for the blue text "Settings" should go to dashboard settings. This link should probably get tracked. 

https://www.figma.com/file/1YM3jA9h4QGc4xLdyaXIJS/Stories-Sprint-1.7?node-id=7122%3A22242

![Screen Shot 2021-04-19 at 9 25 09 AM](https://user-images.githubusercontent.com/10720454/115270517-3adc2300-a0f1-11eb-9b14-c3a359cee05c.png)

**Comment by BrittanyIRL** [comment]
@choumx do we want to continue to have this behind a feature flag? I would think yes, but I want to confirm.

**Comment by dreamofabear** [comment]
Do you mean the opt-in setting for users? Or a feature flag for development? (I think yes in either case, just clarifying).

**Comment by BrittanyIRL** [comment]
i mean for the toggle on the pre publish checklist 🙃  - think it makes sense to keep using the same feature flag that Jonny started in his PR #7130 but i wanted to just make sure we were being transparent.

**Comment by csossi** [comment]
Verified in QA
