### ISSUE TITLE
PPC: Add check for unoptimized video

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#7257]
## Description 
Add a new check to the pre publish checklist for unoptimized video.

## Implementation details
- There's a new `isOptimized` attribute on resources that we can use to flag this recommendation 
- Not all users can upload media to WordPress, only do this check for users that can upload media. 

## Acceptance Criteria 

- If a video is not optimized in a story we should display a recommendation to optimize the video with poster image. 
- There is no element to navigate to for this recommendation.
- Actual video optimization will be done in #7258 
- Ignore UI with red cross through it. 
- New tests for this check that follow structure of existing ppc checks. 

https://www.figma.com/file/1YM3jA9h4QGc4xLdyaXIJS/Stories-Sprint-1.7?node-id=7122%3A22242

![Screen Shot 2021-04-19 at 9 44 23 AM](https://user-images.githubusercontent.com/10720454/115273077-f8681580-a0f3-11eb-94c9-f9301adedb14.png)

**Comment by BrittanyIRL** [comment]
@choumx do we want to continue to have this behind a feature flag? I would think yes, but I want to confirm.

**Comment by BrittanyIRL** [comment]
Per slack discussion with @choumx - we're going to try and limit this suggestion based on video resolution so that our recommendations are more conservative since there's a chance that users optimized their video elsewhere. 

Only trigger the recommendation for video that is larger than 1080x1920, so if videos are smaller than that they do not get suggested to be optimized. 

This trigger should be behind the same feature flag used for the optimize all uploads toggle.

**Comment by BrittanyIRL** [comment]
This branch (#7321) should be used for testing of #7258 and #7343 

Acceptance Criteria consolidated from these two issues: 

- If a video is not optimized in a story we should display a recommendation to optimize the video with poster image.
- Ability to optimize individual videos from PPC
- When the optimize button is hit for a video disable the button so that users can't keep clicking it

This is behind the feature flag `Video optimization pre-publish checklist` 

Further development of this feature will be done in later releases.

**Comment by csossi** [comment]
Verified in QA
