### ISSUE TITLE
Page Templates: Use pagination for saved templates

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#7271]
## Feature Description
Currently, all the templates are loaded to the virtual list. We should add more dynamically, however, to display all the existing templates using pagination.

We need to use the virtual list for performance so we can't use "normal" list with pagination as in case of media.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
