### ISSUE TITLE
Text edit mode often conflicts with dragging operation

### ISSUE THREAD

**Issue by dvoytenko** [GoogleForCreators/web-stories-wp#729]
## Bug Description

Try to randomly drag text elements around. Especially short moves. Regularly, instead of completing the dragging behavior, the element goes into the edit mode. In such cases it often shows a misaligned frame:

## Expected Behaviour

That should practically never happen.

## Steps to Reproduce

Do short drag operations with a text element: short moves and quick delay between grab and release.

## Screenshots

Broken state:
![image](https://user-images.githubusercontent.com/726049/77393909-5395d000-6d5b-11ea-8308-78e2e4c96a30.png)

Screencast:

![capture](https://user-images.githubusercontent.com/726049/77394327-4decba00-6d5c-11ea-94c7-56c1205a982b.gif)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment]
Noted in sprint 26 sheet

**Comment by miina** [comment]
This issue needs more investigation to detect that the user is not dragging for going into edit mode instead of relying on the length of the click. See conversation [here](https://github.com/google/web-stories-wp/pull/829#discussion_r400325781).
