### ISSUE TITLE
Jetpack Boost + AMP incompatibility

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#7295]
## Bug Description
As reported in this [support topic](https://wordpress.org/support/topic/web-stories-do-not-appear-with-stock-content-media/#post-14356509), Stories that contain stock photos and have animations applied to them do not render if you have [Jetpack Boost](https://wordpress.org/plugins/jetpack-boost/) (newly launched this week)+ AMP enabled. 

## Expected Behaviour

Stories render successfully. 

## Steps to Reproduce

1. Enable AMP & Jetpack Boost setting: [Defer Non-Essential Javascript](https://jmp.sh/1ybtjHs). 
2. Add stock photo
3. Add animation
4. Preview story → Image does not display
5. Console error message: https://jmp.sh/BVItuh7

## Screenshots

https://user-images.githubusercontent.com/66372350/115914810-6daf4f80-a440-11eb-82ab-e95ee0c6ece7.mov

## Additional Context
1. Without animation on the stock photo and this setting enabled, then the story renders fine but validation errors occur.
2. Without AMP, and this Jetpack Boost setting enabled, stories are okay.

- Plugin Version: 1.6.0
- WordPress Version:
- Operating System: MacOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Please report this to Jetpack Boost on their GitHub repo.

cc @westonruter for Jetpack Boost AMP compatibility

**Comment by westonruter** [comment]
cc @milindmore22 who found that Jetpack Boost was AMP-compatible 😄

**Comment by davidlonjon** [comment]
> Please report this to Jetpack Boost on their GitHub repo.
> 
> cc @westonruter for Jetpack Boost AMP compatibility

Hi @swissspidy, just to confirm that the issue has now been raised also in the Jetpack Boost Github private repo

**Comment by davidlonjon** [comment]
Hi @swissspidy, @westonruter,

We have now created a fix for this issue in the Jetpack Boost Github repo, which is pending review and merge. Hopefully it will be included in the next release. I'll keep you updated.

**Comment by davidlonjon** [comment]
Hi @swissspidy, @westonruter, @milindmore22,

Just co confirm that [Jetpack Boost latest release (v 1.0.4)](https://wordpress.org/plugins/jetpack-boost/) is including a patch which should fix the compatibility issue with Web Stories (+ AMP).

**Comment by LuckynaSan** [comment]
@davidlonjon Thank you for the update! I can confirm the errors have subsided.
