### ISSUE TITLE
Color input: hex value should be editable as in the side panel

### ISSUE THREAD

**Issue by dvoytenko** [GoogleForCreators/web-stories-wp#730]
## Feature Description

The hex value of the color should be editable as text in the side panel input, similar to the color opacity; not just a preview. Clicking on the preview space, should go into the hex input mode. The color picker is shown only when the color preview button is clicked (e.g. red or checked square below). Only a hex color can be entered this way, or a "transparent" color if the input is cleared out completely.

![image](https://user-images.githubusercontent.com/726049/77394564-ee42de80-6d5c-11ea-9645-1c95df89943e.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## QA Instructions

/cc @barklund

**Comment by jauyong** [comment]
Noted in sprint 26 sheet

**Comment by barklund** [comment]
@dvoytenko, what if it's a gradient? Then the "hex" preview area will just say "radial" or similar. What happens if you click this text then?

**Comment by barklund** [comment]
> @dvoytenko, what if it's a gradient? Then the "hex" preview area will just say "radial" or similar. What happens if you click this text then?

Answered by @samitron7 elsewhere:

> Gradient is the exception. If it's gradient, the input value is set to the name of the gradient (linear, radial) and clicking on it opens the color picker

**Comment by samitron7** [comment]
Please note that I changed the UI on the textbox fill and hilight feature (ie mainly there will no longer with a none value). Waiting for review with Paul. Once that happens, I'll update figma and provide a link in this ticket.

**Comment by samitron7** [comment]
Created a [prototype](https://xwp.slack.com/files/UNKJGEE2W/F010P9BNMN0/textbox_addnewchangecolor.mov) to illustrate that hex value is editable . One thing to note is if a gradient is applied, the hex value will read linear or radial and clicking on the color or the text will just open the color picker.
