### ISSUE TITLE
Dialog Prop Clean Up

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#7306]
There were inconsistencies in naming of dialog props, this ticket is to clean that up.

## Acceptance Criteria ## 

All dialogs and modals function as expected (same as staging).

List of dialogs present in editor: 

- Grid view for carousel
- Post Publish
- Preview Error
- Title Missing on Publish
- Delete media
- Update media
- Media permissions (clear cache then go to new story -> 3p media tab to see this one)
- Video optimization (make sure the experiment is on, clear cache, upload a video to the editor by dragging it in)
- Post lock
- Post takeover
- Status Check Failed

**Comment by csossi** [comment]
layout error on checking grid view:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/8422bd17-eb39-4984-9221-62c8179aa6c7)

**Comment by BrittanyIRL** [comment]
@csossi  you're right! 

Should be fixed: 
![Screen Shot 2021-04-27 at 2 42 39 PM](https://user-images.githubusercontent.com/10720454/116316517-ed059180-a766-11eb-8d60-62dbaecbc730.png)

**Comment by csossi** [comment]
Verified in QA
