### ISSUE TITLE
Cleanup scrollbar UX in the visible mode

### ISSUE THREAD

**Issue by dvoytenko** [GoogleForCreators/web-stories-wp#731]
## Feature Description

When a mouse is connected on MacOS, the browser shows all the scrollbars. This mode can be triggered manually as "Scrollbar behavior" in MacOS settings like this:

<img src="https://user-images.githubusercontent.com/726049/77394984-d750bc00-6d5d-11ea-92fb-5660acd3a997.png" width="400">

The editor will show scrollbars which could be jarring.

The scrollbars standout in the color scheme:
<img src="https://user-images.githubusercontent.com/726049/77395045-f64f4e00-6d5d-11ea-9bcc-dac2af9e0cc5.png" width="200">

Sometimes scrollbars get stacked up on top of each other making it hard to tell them apart:
<img src="https://user-images.githubusercontent.com/726049/77395199-462e1500-6d5e-11ea-8eec-c6dc070e2a55.png" width="200">

Sometimes a presence of a scrollbar misaligns the UI, as is the case with some of the chevrons here:
<img src="https://user-images.githubusercontent.com/726049/77395255-69f15b00-6d5e-11ea-845b-08c549c41c72.png" width="200">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by pbakaus** [comment]
Part of this was addressed by https://github.com/google/web-stories-wp/pull/946
