### ISSUE TITLE
Optimize video capability in canvas

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#7310]
## Description 

If a video hasn't been optimized and fits the criteria we've established in the prepublish checklist then it should have an option to be optimized from the video in the canvas. 
https://www.figma.com/file/1YM3jA9h4QGc4xLdyaXIJS/Stories-Sprint-1.7?node-id=7122%3A22242

This button is the same functionality as in the prepublish checklist (#7258 ) just in the canvas instead. 

If it's successful, show the same optimization successful message as established in #7314 
If it's a failure, show the same optimization error message as established in #7314 and #7315

![Screen Shot 2021-04-27 at 1 42 49 PM](https://user-images.githubusercontent.com/10720454/116310126-76fd2c80-a75e-11eb-906c-eba9bd02b9e4.png)

## Acceptance Criteria 
- New button on videos in canvas that when clicked will optimize the video. 
- Should have a tooltip that says `Optimize video` 
- New tests, please

**Comment by swissspidy** [comment]
Is it confirmed that we want to implement this? IIRC it was just an exploration last time.

I fear that adding so many options for users to optimize videos clutters the UI too much and gives the feature more importance than needed. The PPC integration should suffice for now, IMO.

**Comment by BrittanyIRL** [comment]
(not part of release 1.9)

**Comment by BrittanyIRL** [comment]
we will likely not implement this per conversation in design syncs in June

**Comment by BrittanyIRL** [comment]
@choumx @o-fernandez LMK if I misunderstood anything with this - but these optimize buttons seem to me the same amount of clutter on the canvas as having checklist warnings show up.

**Comment by o-fernandez** [comment]
Yeah, we don't need this.
