### ISSUE TITLE
Optimize video capability in layers panel

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#7311]
## Description
If a video hasn't been optimized and fits the criteria we've established in the prepublish checklist then it should have an option to be optimized from the video's layer in the layer panel. 

https://www.figma.com/file/1YM3jA9h4QGc4xLdyaXIJS/Stories-Sprint-1.7?node-id=7122%3A22242

This button is the same functionality as in the prepublish checklist (#7258 ) just in the layers panel instead. 

If it's successful, show the same optimization successful message as established in #7314
If it's a failure, show the same optimization error message as established in #7314 and #7315 
This button also gets the fancy CTA treatment found here: #7312  

![Screen Shot 2021-04-27 at 1 51 01 PM](https://user-images.githubusercontent.com/10720454/116311037-9c3e6a80-a75f-11eb-8c27-6ac1839d4f9e.png)

## Acceptance Criteria 
- New button in the layers panel for videos that can be optimized according to PPC standards 
- When clicked it has the same 'processing' UI of the button border moving (see #7312) 
- Snackbars show success and failure
- New tests, please

**Comment by swissspidy** [comment]
Is it confirmed that we want to implement this? IIRC it was just an exploration last time.

I fear that adding so many options for users to optimize videos clutters the UI too much and gives the feature more importance than needed. The PPC integration should suffice for now, IMO.

**Comment by BrittanyIRL** [comment]
(Not part of release 1.9)

**Comment by BrittanyIRL** [comment]
we will likely not implement this per conversation in design syncs in June

**Comment by swissspidy** [comment]
Cool. Let's close this for now then.
