### ISSUE TITLE
PPC: Batch video optimization suggestions

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#7314]
## Description 
If the same video is used in multiple pages we should only show the recommendation to optimize it once.

**This is in line with Design updates for 2.0 version of prepublish checklist and should be delayed until that work is done**

## Acceptance Criteria

**Comment by spacedmonkey** [comment]
It is worth noting, that the implementation I wrote, if you generate a new optimized version, it will update of references in all pages when the transcode is complete.

**Comment by BrittanyIRL** [comment]
@embarks after batching is done, i'm curious if this ticket is obsolete. Given what Jonny said, it seems like this will take care of itself.
