### ISSUE TITLE
Implement mod+K shortcut to add/update element link

### ISSUE THREAD

**Issue by dvoytenko** [GoogleForCreators/web-stories-wp#732]
## Initial Feature Description (Original, from 2020)

Activate link editing with mod+K. Based on this shortcut, and if the linking is allowed for the element, the URL field should be focused and scrolled in the design panel.
[Brief](https://docs.google.com/spreadsheets/d/17pZLd0faYZc9Xt7mG1KYtaZ0Krn5ppThIisz3TOsv8w/edit#gid=0)

## Feature Description (Updated, 2022)

When an element is selected, user should be able to press `mod+k` keyboard shortcut and be sent to the 'link' section of the side panel. This is the same functionality as offered by the 'quick actions' menu that is located to the right (when in LTR) (see below demo). 

![quick action link](https://user-images.githubusercontent.com/10720454/164263452-33e816a7-4f49-4fb9-8d2a-ce7edd7bffec.gif)

Currently, the `mod+k` keyboard shortcut is used to play animations on the canvas. You can see this in action by adding an animation to an element on your current page (not page 1) and then hitting "play" below the canvas. The play animation shortcut will need to be updated to something else. Some research may be required for this, seeing what other like minded (Google) products use to preview is a good place to begin. 

The keyboard shortcuts popup will require updates to keep it current. The below is the keyboard shortcuts popup. 

![keyboard shortcuts 2](https://user-images.githubusercontent.com/10720454/164265110-123224b2-8643-4b96-8136-d00a4f8162ed.gif)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
- `mod+k` shortcut will take a user to the 'link' section of the sidepanel for an element just like the quick action does. This functionality works for elements with and without links, allowing a user to add or update a link. When the shortcut is used, the focus should move to the link so that the user can type into the input. 
- `mod+k` shortcut in keyboard shortcuts updated to specify use for 'add/update element link' (confirm with design on verbage - probably 'Add link' mirroring tooltip text for quick menu) 
- Replacement keyboard shortcut to play animation in canvas 
- Replacement keyboard shortcut listed in keyboard shortcuts for playing animation in canvas. 
- Karma tests should be added for new shortcut and updated for play/stop. 

## QA Instructions

Please refer to acceptance criteria.

**Comment by barklund** [comment]
Hi @wassgha, have you started working on this?

👍  If you have, please push whatever branch you have (so we can track progress) and move to "in progress".
👎  If not, please un-assign yourself, so someone else can pick this up.

**Comment by samitron7** [comment]
[Figma flow](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=7736%3A85399)

**Comment by swissspidy** [comment]
For anyone picking this up, there's some prior art in #2767 that might be useful

**Comment by swissspidy** [comment]
@gajasinski @agingoldseco It would be nice to implement this. It's just such a common functionality in all applications, even here on GitHub.

Right now mod+k (cmd+k) does play/stop animations instead, so we would need a new shortcut for that

**Comment by BrittanyIRL** [comment]
To clarify here, this is updating the `mod+k` keyboard shortcut to instead take the user to the 'add link' section of the 'style' tab? Just like the quick action menu? 

Do we want both of these implemented? Or is this ticket now obsolete with the quick action menus?

**Comment by swissspidy** [comment]
> To clarify here, this is updating the `mod+k` keyboard shortcut to instead take the user to the 'add link' section of the 'style' tab? Just like the quick action menu?

That's what I would say, yes. And finding a new keyboard shortcut for play/stop animations of course (which currently uses mod+k).

**Comment by BrittanyIRL** [comment]
Awesome, thanks for clarifying. I'll update the description and acceptance criteria. Pea pod can do this.

**Comment by mwritter** [comment]
> > To clarify here, this is updating the `mod+k` keyboard shortcut to instead take the user to the 'add link' section of the 'style' tab? Just like the quick action menu?
> 
> That's what I would say, yes. And finding a new keyboard shortcut for play/stop animations of course (which currently uses mod+k).

@swissspidy - do you have any suggestions for the new keyboard shortcut for play/pause animation?

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin, using PR #11481.

1. Opened editor
2. Added an element
3. Clicked on the element
4. Used Command (or Control on Windows) + K - add link is displayed and focused

Tested on Firefox, Chrome and Safari

**Comment by mwritter** [comment]
Hey @felipebochehin87, Idont see it in your last comment, but did you also test and confirm `ctrl+space` functions correctly as the new animations play/stop keyboard shortcut?

**Comment by felipebochehin87** [comment]
@mwritter sorry, I didn't add a comment about that, but yes, it works, fn+Command (or Control on Windows) + Space plays the animations (fade in, drop, rotate, etc...).
