### ISSUE TITLE
Set PPC video optimization feature flag to true

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#7322]
This will be the last ticket to go through for the new video optimization experiment. Just set the experiment to `true` and use this as the QA step for the video optimization bulk.

## Acceptance criteria 
- Experiment set to true 
- Detailed QA steps for Claudio

**Comment by swissspidy** [comment]
Note that we usually set `default => true` for flags in 1 PR, and then completely remove it in the next PR. In case we need to revert rollout quickly.

**Comment by embarks** [comment]
To Pascal's comment above, I'll make two prs: one set to true and one to remove it completely

**Comment by BrittanyIRL** [comment]
@csossi the PR itself has really helpful QA steps for you :)

**Comment by swissspidy** [comment]
> To Pascal's comment above, I'll make two prs: one set to true and one to remove it completely

@embarks Note that the second PR is usually done weeks later, after release. Not right afterwards.

**Comment by BrittanyIRL** [comment]
I have separate issues for these actually :) 

https://github.com/google/web-stories-wp/issues/8168

**Comment by csossi** [comment]
Verified in QA
