### ISSUE TITLE
AMP validation errors with WP Rocket JS file optimization 

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#7323]
## Bug Description

The [JavaScript file optimization option](https://jmp.sh/HXnVSZ0) in the [WP Rocket plugin](https://wp-rocket.me/) can surface [validation errors](https://jmp.sh/xEqR4Tq) on the story URL, when the official AMP plugin is enabled (and the supported template is turned on or off) . Currently, it looks like the Minify JavaScript files options on the File Optimization tab:
<img width="712" alt="Screen Shot 2021-04-28 at 8 08 58 PM" src="https://user-images.githubusercontent.com/66372350/116487503-20771780-a85e-11eb-85f7-0f1a6719d052.png">

Current workarounds:

Disabling the option
Excluding the /web-stories/ url on the [Advanced Rules tab](https://jmp.sh/EkwIZrh)

## Expected Behaviour

No validation errors on the story URL with WP Rocket and AMP enabled. 

## Steps to Reproduce
Enable AMP plugin
Enable the JS Minify options in WP Rocket
See validation errors on the URL

## Additional Context

Web Stories and WP Rocket together are okay. Issues surface when AMP is enabled. 

- Web Stories Plugin Version: 1.6.0
- AMP Plugin Version: 2.0.11
- WP Rocket Plugin Version: 3.8.8
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
This should reported in the WP-Rocket repo. This should be disabled for AMP and Web Stories

**Comment by LuckynaSan** [comment]
Done: https://github.com/wp-media/wp-rocket/issues/3879

**Comment by swissspidy** [comment]
@LuckynaSan I can't seem to reproduce this at the moment

**Comment by LuckynaSan** [comment]
@swissspidy The issue no longer occurs when using Web Stories v1.7.1 and v1.7.2.
