### ISSUE TITLE
Revert Story description max size to 200

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#7325]
## Bug Description
During the redesign, the story description max size for reduced to 100 but it should be 200.

## Expected Behaviour
Story description max size should be 200.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
