### ISSUE TITLE
Editing link should exit edit mode

### ISSUE THREAD

**Issue by dvoytenko** [GoogleForCreators/web-stories-wp#733]
## Bug Description

Both for text and image (and others) editing the link should exit the edit mode.

## Steps to Reproduce

Double click on an element to enter edit mode. Then select the Link in the design panel and enter a valid URL. The edit mode should exit as soon as the link is entered.

Possibly the behavior should be expanded to most other clicks/focus outside the edit-mode area. Possibly dedup with https://github.com/google/web-stories-wp/issues/678.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment]
Noted in Sprint 26 sheet
