### ISSUE TITLE
Page does not advance after page duration time has been met

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#7331]
## Bug Description

The page advancement time setting does not take effect in the story. I set the duration to 3 seconds and the slide did not advance after 3 seconds. This is happening inconsistently across sites.  Here is an example story (https://cmsdevrel.com/web-stories/test-duration/) where the [duration was set to 3 seconds](https://jmp.sh/sCRQlbB), but the page did not advance. 

## Expected Behaviour

Page should advance once the duration time set has been met.

## Steps to Reproduce

1. Set duration on story
2. Preview story
3. Observe page duration time vs actual time on the page

## Additional Context

Related support topic: https://wordpress.org/support/topic/plugin-questions-comments-and-concerns/

- Plugin Version: 1.6.0
- WordPress Version:
- Operating System:
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Auto advancement on https://cmsdevrel.com/web-stories/test-duration/ works fine for me on Chrome. It's currently set to 7s.

Could you perhaps share more details on how to reproduce? Does the above story work for you?

**Comment by swissspidy** [comment]
Looks like the feature is working fine, but of course the page advancement logic will be overridden by any non-looping videos. See also #7053
