### ISSUE TITLE
Dashboard Settings: Ability to pick publisher logo from WP media library

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#7337]
## Feature Description

In the dashboard settings page, when a user clicks on upload logo, it opens a default file picker dialog. However, in the editor, it opens the WordPress media picker. User should be able to select existing files in the media library. 

### Current implementation 
<img width="1884" alt="Screenshot 2021-04-29 at 18 10 47" src="https://user-images.githubusercontent.com/237508/116591431-b79fa600-a916-11eb-9ac7-85f7c2cc1319.png">

### Publisher logo implementation in editor
<img width="1782" alt="Screenshot 2021-04-29 at 18 14 05" src="https://user-images.githubusercontent.com/237508/116591558-dc941900-a916-11eb-9441-ac5c2994d410.png">

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
This seems like a good candidate to bundle with this feature in the roadmap: `Easily toggle between publisher logos from within the workspace` since that's to give continuity in publisher logo behavior between settings and the document panel of the workspace. This feature doesn't have a slated release yet.

**Comment by spacedmonkey** [comment]
After working on https://github.com/google/web-stories-wp/pull/8067, I wonder if [mediaPicker](https://github.com/google/web-stories-wp/tree/main/assets/src/edit-story/components/mediaPicker), should be moved to it's own package. This makes sharing code between easier and it will make decoupling from WordPress a little easier too.

**Comment by swissspidy** [comment]
Related: #4148

Shared utilities like that can be extracted as part of the ongoing decoupling work. It's not 100% clear yet how the code sharing there will look like, so this is not actionable just yet.
