### ISSUE TITLE
Dismiss Quick Tips in E2E test

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#7338]
## Feature Description

Dismiss quick tips when editor is opened in E2E tests.

![image](https://user-images.githubusercontent.com/237508/116596336-259a9c00-a91c-11eb-8f62-2aab6d527865.png)

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Any suggestions on how to best achieve this?

Currently thinking of either updating user meta before tests (in setup script or a WP plugin) or by adding a flag similar to the `DISABLE_PREVENT` flag we have.

A plugin might be best, as then we could have 1 e2e test to verify the popup is open by default, but hide it for all other tests.

**Comment by spacedmonkey** [comment]
State is stored in both user meta and in locale storage. 

<img width="471" alt="Screenshot 2021-05-05 at 16 54 17" src="https://user-images.githubusercontent.com/237508/117171363-b6f98a80-adc2-11eb-8f3a-2167ed00a761.png">
<img width="255" alt="Screenshot 2021-05-05 at 16 54 42" src="https://user-images.githubusercontent.com/237508/117171386-b9f47b00-adc2-11eb-9f94-10eab3dc9f8c.png">


I thought maybe add something to `createNewStory` check for a selector for the close button on quick tips, if present to clear, click it. 

I am not sure. CC @BrittanyIRL to add her thoughts.

**Comment by swissspidy** [comment]
Local storage is derived from user meta I think.

I'd want to avoid checking for selectors and clicking in all the tests, when possible :-)

**Comment by spacedmonkey** [comment]
I have been looking at either making an REST API to user meta or saving the user meta. The only way to get it to not open is set all the tip to read like this. 

```js
web_stories_onboarding: {
     addBackgroundMedia: true,
     addLinks: true,
     cropElementsWithShapes: true,
     cropSelectedElements: true,
     embedWebStories: true,
     enableSwipe: true,
     previewStory: true,
     safeZone: true,
}
```

I don't like this solution, as we would have to keep track of all new tips added / removed. 

CC @BrittanyIRL / @littlemilkstudio so if they have any recommendation on how best to archive this.

**Comment by swissspidy** [comment]
Another approach I already mentioned before is setting some simple build-time flag, like we already do for `DISABLE_PREVENT`, ie `DISABLE_QUICK_TIPS`.

If you run `DISABLE_QUICK_TIPS=true npm run build`, the quick tips would not auto-open by default.

**Comment by spacedmonkey** [comment]
I like the idea, but I am not sure how we would `isOpen`: false with this flag. `isOpen` defaults to `false` then the set to true when the number of unread tips is more than 0. 

We could add a value to the config object on the page and filter it in an e2e test plugin. If `autoOpenQuicktips` is set to false, then hide the quick tips.

**Comment by swissspidy** [comment]
The help center effects could be updated like this:

```js
export function deriveAutoOpen(previous, next) {
  if (process.env.DISABLE_HELP_CENTER_AUTO_OPEN === 'true') {
    return {};
  }

  if (isInitialHydrate(previous, next)) {
    const hasNewTips = previous.unreadTipsCount < next.unreadTipsCount;
    return hasNewTips ? { isOpen: true } : {};
  }
  return {};
}

// If there are any unread tips, we respect users last open setting.
// If all tips are read, we want the popup closed regardless of user setting.
export function deriveInitialOpen(persisted) {
  if (process.env.DISABLE_HELP_CENTER_AUTO_OPEN === 'true') {
    return {};
  }

  const hasUnreadTips = Boolean(persisted?.unreadTipsCount);
  return hasUnreadTips && persisted?.isOpen !== undefined
    ? {
        isOpen: persisted?.isOpen,
      }
    : {};
}
```

That should do the trick.

**Comment by spacedmonkey** [comment]
I was trying to avoid hardcoded a env variable like this. But you are happy with it, seems simple enough to me.
