### ISSUE TITLE
The title field should be centered in the editor on big surface

### ISSUE THREAD

**Issue by dvoytenko** [GoogleForCreators/web-stories-wp#734]
## Bug Description

Per Figma, the Title field should be centered on a bigger surface. Only smaller surfaces (~iPad) the title should be left-aligned.

## Screenshots

![image](https://user-images.githubusercontent.com/726049/77396035-1f70de00-6d60-11ea-9a8b-aa0b5825c60a.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment]
Noted in sprint 26 sheet

**Comment by jauyong** [comment]
Closing. Will use #41
