### ISSUE TITLE
Add back "Set as background" button

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#7340]
## Feature Description
We need to add back the "Set as background" button.

See [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=7997%3A1304)

## Additional Context
The button was removed here: https://github.com/google/web-stories-wp/pull/6642/files#diff-102f91ad82a7e16538fb9042a24d6f37169422fe4b49b4318e492ed2876dc1aaL166

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Not seeing the Set As Background button:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/6fb155c4-7cf5-4540-8f0b-9b9b5108956d)

**Comment by miina** [comment]
Looks like the build failed... Rerunning.

**Comment by csossi** [comment]
Verified in QA
