### ISSUE TITLE
Improve interaction with dragging and dropping media to shape borders 

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#7344]
## Feature Description

Make interaction more intuitive when a user adds a shape to the page and drags any media to shape borders to apply a mask.

## Additional Context

Related support topic: https://wordpress.org/support/topic/plugin-questions-comments-and-concerns/
Example of user's experience with dragging and dropping media to shape: https://share.getcloudapp.com/nOuoLrjg 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
@tmagalhaes-huge @aaecheverria would you mind reviewing this ticket and adding to your design backlog. We can prioritize in an upcoming planning session. 

@samitron7 FYI

**Comment by miina** [comment]
cc @agingoldseco / @aaskedall since the team has changed meanwhile.
