### ISSUE TITLE
Stickers: Add library of animated stickers

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#7345]
## Feature Description

A user would like to see a library of animated elements. Is this something Web Stories would support? 
Here is an example:

https://user-images.githubusercontent.com/66372350/116740348-e7a48300-a9c2-11eb-929a-985bc49ca73e.mov

## Alternatives Considered

Animate elements elsewhere and upload them into the editor. 

## Additional Context

Related topic: https://wordpress.org/support/topic/plugin-questions-comments-and-concerns/
---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by maxyinger** [comment]
There's currently support for this with our existing stickers setup. We just have to upload stickers with animations embedded in them.

We still have yet to make the stickers panel user facing which is a separate task. but little animated svgs like this should be possible when we do

**Comment by BrittanyIRL** [comment]
The stickers panel is now user facing as of 1.10 release. @LuckynaSan can we close this?

**Comment by swissspidy** [comment]
The original request was for a library of _lots_ of _animated_ stickers. Don't think we have either today :-)

We don't even support Tenor stickers yet.

**Comment by BrittanyIRL** [comment]
> The original request was for a library of _lots_ of _animated_ stickers. Don't think we have either today :-)
> 
> We don't even support Tenor stickers yet.

haah ok i jumped the gun! I'm going to move this to the backlog needed so I stop thinking it's something new.

**Comment by swissspidy** [comment]
Closing in favor of #11878, which will make available a wide range of animated stickers from Tenor.
