### ISSUE TITLE
Layers panel: the shape element should show the mask outline/fill preview and label should reflect the name

### ISSUE THREAD

**Issue by dvoytenko** [GoogleForCreators/web-stories-wp#735]
## Bug Description

Currently, the layer display just says "Shape" and the label is some generic shape message.

## Expected Behaviour

1. The layer icon should be "shape" icon.
2. The layer display should show the actual shape (possibly with fill and shadow for blending fills as we do for images now).
3. The label should reflect the shape/mask name. E.g. "Heart" and not just "Shape".

## Screenshots

![image](https://user-images.githubusercontent.com/726049/77396113-4fb87c80-6d60-11ea-8378-f2b8582f0374.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## QA Instructions

/cc @wassgha @pbakaus @barklund

**Comment by jauyong** [comment]
Noted in Sprint 26 sheet

**Comment by barklund** [comment]
> 1. The layer icon should be "shape" icon.

The current icon is per design the same as for media elements:

![Screen Shot 2020-03-24 at 10 21 34 AM](https://user-images.githubusercontent.com/637548/77435991-52938b80-6db9-11ea-85a9-39a3ca371bd4.png)

If we want a specific shape icon, we need UX lead for that. We can of course just reuse the icon from the shapes library tab:

![Screen Shot 2020-03-24 at 10 23 27 AM](https://user-images.githubusercontent.com/637548/77436168-8a023800-6db9-11ea-851d-94f8cf3166b3.png)

@samitron7?

**Comment by dvoytenko** [comment]
Yeah. I assumed we will just reuse the icon from the tab. But, of course, @samitron7 feel free to overrule me on that point.

**Comment by samitron7** [comment]
Oh, we should reuse the shape icon (the thing with the circle square and triangle) and not the picture icon. Sorry - I missed that but yes in general let's reuse the same (but correct icon) because we want a consistent message and iconography for things.
