### ISSUE TITLE
Preview: Border radius not respected while animating

### ISSUE THREAD

**Issue by maxyinger** [GoogleForCreators/web-stories-wp#7356]
**Summary**
If an animation is applied to an element with a border radius, the border radius is not respected in the story preview while animating:

https://images.zenhubusercontent.com/235435637/05894e6c-4e79-4668-a462-a854fa8fc94d/balldropanimation.mov

**Successful completion of this ticket**
Border radius of elements in preview should be maintained while animating

**Comment by BrittanyIRL** [comment]
@csossi the PR linked has a helpful video of what to expect here if you need any clarification.

**Comment by csossi** [comment]
Verified in QA
