### ISSUE TITLE
Side panel: select all on input focus

### ISSUE THREAD

**Issue by dvoytenko** [GoogleForCreators/web-stories-wp#736]
## Bug Description

The inputs in the side panel (and likely elsewhere) should consistently do "select all" on keyboard focus. Currently it's not consistent. In my tests, the "width" and "height" fields do "select all", but "rotation angle" and "opacity" do not. The only thing I notice different about these fields is that some non-auto-select-all fields have suffixes (e.g. "%").

## Steps to Reproduce

Press <kbd>tab</kbd> and observe.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment]
Noted in sprint 26 sheet
