### ISSUE TITLE
Gap between image and border

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#7360]
## Bug Description

There is a gap of space between an image and its border on the Chrome browser. See story URL: https://bluehost.cmsdevrel.com/web-stories/test-spaces-between-image-and-border/

Using MacBook Pro 13.3-inch (2560 × 1600). 

## Expected Behaviour

There should not be any space between the image and the border applied. 

## Steps to Reproduce

1. Add image
2. Add a border on the image 
3. Notice spaces around the image when you
     - Turn on/off the setting to hide the computer dock
     - preview the story on chrome

## Screenshots

https://user-images.githubusercontent.com/66372350/116921243-bd9ccc00-ac21-11eb-80bf-d64dd7f67e03.mov

<img width="651" alt="Screen Shot 2021-05-03 at 3 11 38 PM" src="https://user-images.githubusercontent.com/66372350/116921399-efae2e00-ac21-11eb-85e5-135103c43601.png">

## Additional Context

Issue is not present on Safari. 
<img width="1425" alt="Screen Shot 2021-05-03 at 3 02 30 PM" src="https://user-images.githubusercontent.com/66372350/116921068-79113080-ac21-11eb-8d65-413543d2b6c3.png">

- Plugin Version: 1.6.0
- WordPress Version:
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Is this still an issue?
