### ISSUE TITLE
Update High Priority Tooltip Text

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#7367]
## Feature Description

Tooltip text that is seen on publish button hover/focus should be updated from: 
`[For priority issues]: Make updates before publishing to improve discoverability and performance on search engines `
to 
[HUGE TO PROVIDE]

## Acceptance Criteria

Tooltip text is updated.

**Comment by o-fernandez** [comment]
@BrittanyIRL should we close this? Huge is no longer on the project, so if this wasn't provided, we should just... close and reevaluate when we have a designer looking at this again.

**Comment by BrittanyIRL** [comment]
@o-fernandez  Sounds great to me!
