### ISSUE TITLE
Side panel: buttons, toggles, switches have no keyboard-focusable outline or highlight

### ISSUE THREAD

**Issue by dvoytenko** [GoogleForCreators/web-stories-wp#737]
## Bug Description

![image](https://user-images.githubusercontent.com/726049/77396890-d0c44380-6d61-11ea-89c8-04589383be39.png)

In this screenshot, the "Flip horizontally" button has been focused by keyboard, but it's impossible to tell.

[figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=9396%3A400304)

## Expected Behaviour

An outline or a highlight of some sort is shown.

## Steps to Reproduce

Navigate through side panel fields using <kbd>tab</kbd>.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment]
Noted in sprint 26 sheet

**Comment by swissspidy** [comment]
Same goes for the `DropDown` component, see #688.

**Comment by samitron7** [comment]
Verified in UAT
