### ISSUE TITLE
Update Starburst Sticker

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#7373]
Previously, the starburst used in the fashion template page 2 was cut off as an asset on page end, we should update the asset to use the whole starburst now that it is available .

Acceptance criteria: 
- Update sticker to use full starburst 
- Update Page 2 Fashion Template to use new asset

**Comment by BrittanyIRL** [comment]
![layoutfashion_singlesvg_starbustarrow.svg](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/3338cb63-5ccd-4f43-a07d-79905a5c01cc)

**Comment by csossi** [comment]
Verified in QA
