### ISSUE TITLE
Templates with Checklist Recommendations

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#7374]
Sometimes templates break with recommendations. As noted by @aaecheverria in Bug Bash 1.7 this is the case on the cooking template. 

She wrote: 
> When using an existing template (i.e cooking)  I still get some suggestions in the PPC related to “design’ page elements: i.e Increase font size, Increase color contrast, reduce text amount on page, etc. 

![Screen Shot 2021-05-04 at 10.50.47 AM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/f97b071a-a143-43e4-9d27-e390a20129f2)

This will require further design tweaks to completely eliminate or tweaking/eliminating some checks and should be discussed before doing anything.

**Comment by dreamofabear** [comment]
I think Brittany's suggestion to ask UX to do a pass and fix existing templates to conform to PPC guidelines is a good idea here. This could be done directly in the editor, reviewed by PM, and handed off to eng afterwards. 

- UX should reflect on whether the changes necessary to eliminate PPC warnings would negatively impact the intended design
- There may be some warnings that may not be easily fixed without an eng-side change e.g. text contrast
- We'll probably need to do this for the incoming new templates too

@aaecheverria Is this something design can take a pass at?

@o-fernandez FYI

**Comment by BrittanyIRL** [comment]
I think we can close this, I don't think we're going to update these original 10 templates again and the checklist recommendations are more organized now for suggestions so it's not as glaring. 

<img width="329" alt="Screen Shot 2021-07-08 at 1 00 40 PM" src="https://user-images.githubusercontent.com/10720454/124983200-844f5680-dfec-11eb-9a99-1119090a3fd9.png">
