### ISSUE TITLE
Empty State for Prepublish Checklist

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#7375]
In our 1.5 designs for the checklist we were going to disable the different tabs and then enable them after certain points in the story. This has caused some confusion and in the 2.0 designs that are still in flight, we're going to update this to hide the disabled sections instead of disabling them. 

That work's not quite done yet but it's done enough to the point where a quick place keeper can be implemented to avoid confusion in our pending release for 1.7. 

Acceptance Criteria: 
- when checklist has not been triggered yet (0 state) show the empty state like so: 
![Screen Shot 2021-05-04 at 12.55.25 PM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/f25fa58c-c8d0-4a39-b4c9-fc09115ee763)
- Only show the enabled checklist sections 

Recommended is exposed as soon as there's another element besides a background on 1 page or you try to publish a story. 
High priority is exposed as soon as there are either 5 pages or you try to publish a story.

**Comment by BrittanyIRL** [comment]
Hey @csossi , i'm sorry for the last minute ask but if there's anyway you could test this before 9am PST tomorrow that would be incredibly helpful, we are doing a second bug bash and this PR is critical to that happening. There's details for testing in the PR description. I will make myself available on slack after hours if that's when you are working on this. Really appreciate your help!

**Comment by csossi** [comment]
Verified in QA
