### ISSUE TITLE
Keyboard: default focus is broken in the editor

### ISSUE THREAD

**Issue by dvoytenko** [GoogleForCreators/web-stories-wp#738]
## Bug Description

Very often the active element in the editor ends up being top-level `<body>` element. We tried to keep away from adding too many shortcuts on the `<body>` element to avoid collisions with WP and to reduce the scope of overlapping shortcuts such as arrow keys. The typical issue is that many canvas shortcuts (e.g. "del" to delete the selected element(s), etc) are not handled.

The editor should either do a better job at defaulting the active area back to the canvas area. Or it should push key handlers deeper into the DOM.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## QA Instructions

/cc @dvoytenko @barklund

**Comment by jauyong** [comment]
Noted in sprint 26 sheet

**Comment by dvoytenko** [comment]
Related to #511 .

**Comment by dvoytenko** [comment]
@barklund Are you actively working on this or planning to in the next 2-3 days?

**Comment by barklund** [comment]
> @barklund Are you actively working on this or planning to in the next 2-3 days?

This is not my focus currently, no. Haven't look at it recently
