### ISSUE TITLE
Allow WebP images if supported by WP

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7389]
## Feature Description

Now that initial WebP support has landed in WP trunk (https://core.trac.wordpress.org/changeset/50810), it would be good to add support in the editor as well.

In `\Google\Web_Stories\Traits\Types::get_allowed_mime_types()` and `\Google\Web_Stories\Traits\Types::get_allowed_image_mime_types()` we should add support the WebP mime type if it's supported by the site (either via core or a plugin).

So we should not be doing `$wp_version` comparisons or anything, but feature detection.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

* WebP images are visible in the editor media library
* WebP images can be uploaded in the editor
* WebP images can be uploaded as publisher logos

**Comment by spacedmonkey** [comment]
This should be extremely simple. 

If we add 'image/webp' to `Types::get_allowed_mime_types`, then if WordPress doesn't support it, this this line will filter it out. 

https://github.com/google/web-stories-wp/blob/515eb8694efa49a3947bb0e431fcce3eb8bd807a/includes/Traits/Types.php#L119

Should webp supported by `Types::get_allowed_image_mime_types()`

**Comment by swissspidy** [comment]
> Should webp supported by `Types::get_allowed_image_mime_types()`

WebP should be allowed for things like publisher logos, so yes :-)
