### ISSUE TITLE
Set PPC video optimization flag to true

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#7393]
Prior to release, we need to enable the ppc video optimization flag **and** remove the test panel (assets/src/edit-story/components/panels/design/videoProcessing/videoProcessing.js)

**Comment by dreamofabear** [comment]
#7476 is merged. :)

**Comment by BrittanyIRL** [comment]
@csossi this is just eliminating the need to set the flag for video optimization experiment. The flag should be disabled and `true` on the experiments view. 

video optimization in prepublish checklist panel should work as expected in #7476 which you just tested :)

**Comment by csossi** [comment]
Verified in QA
