### ISSUE TITLE
Text Set Toggle Crashing App

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#7394]
Think we missed this in our last bug bash! 

Toggling the text sets to use the story fonts is crashing the app. 
![Screen Shot 2021-05-05 at 10.53.17 AM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/63915d20-45d3-4005-a837-77ae81f96306)
![crash t reduce.gif](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/8225323f-0f46-49ed-bbb1-2d1f33695d76)

**Comment by csossi** [comment]
Verified in QA
