### ISSUE TITLE
Videos: Playback button placement and sizing issues

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#7397]
## Bug Description

When a video asset is resized to a small size, the playback button is displayed outside of the asset, directly above it. Currently, there's a couple of issues with this presentation:

1. Button is presented with scrollbars - 
![Screen Shot 2021-05-05 at 3 03 41 PM](https://user-images.githubusercontent.com/58738530/117195733-a42b8980-adb3-11eb-93a2-1cc3c3c726f6.png)

2. RTL changes the centering of the button and the way it's presented and the button is cutoff.
![Screen Shot 2021-05-05 at 3 04 15 PM](https://user-images.githubusercontent.com/58738530/117195756-ad1c5b00-adb3-11eb-85d3-d10658ffa548.png)

3. Even for a large video, the button is still displayed off-center in RTL. Note that this will still happen, albeit slightly differently, after #7376 is merged.
![Screen Shot 2021-05-05 at 10 39 18](https://user-images.githubusercontent.com/637548/117211442-fa55f800-adc6-11eb-8cd5-15f0213ed135.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Renamed title to make it somewhat better distinguishable from #6958. Although still seems like a duplicate.

**Comment by barklund** [comment]
> Renamed title to make it somewhat better distinguishable from #6958. Although still seems like a duplicate.

#6958 is not a bug - it's by design. The three scenarios described in this bug are all actual bugs where the result differs from the defined UX.

**Comment by csossi** [comment]
Verified in QA
