### ISSUE TITLE
Media Library Panel - Use Thumbnails 

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#741]
## Feature Description

As an editor I want to browse the media library with high performance and in a beautiful view

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. The media library uses thumbnails instead of full images

**Comment by spacedmonkey** [comment]
In https://github.com/google/web-stories-wp/pull/837 I have added a new image size that we control. However all existing images will not have this image size. 

@swissspidy @miina  What our your thoughts on forcing regenerating thumbnail sizes in this error?

We could write a little REST API to generate these image sizes, but not sure it is worth it. Anyone using jetpack or is on WP.com will get the image size auto completely generated. Everyone else, I think WP is clever enough to give the closes possible size. 

What does everyone think?

**Comment by miina** [comment]
@spacedmonkey Perhaps we could detect the closest available size which would be at least 150 in those cases?

Also not sure it's worthwhile to generate these sizes for all the images. If, then for the most recent images only, e.g. last week/month.
However, this might be a product decision.
