### ISSUE TITLE
Stickers Panel: Add human readable names to template stickers

### ISSUE THREAD

**Issue by samwhale** [GoogleForCreators/web-stories-wp#7425]
## Feature Description

Add human readable names to the stickers in the stickers panel for accessibility. Other things to consider:
- May need to add the same name to the layer in the layer panel

## Alternatives Considered

n/a

## Additional Context

Stems from [this comment](https://github.com/google/web-stories-wp/pull/7408#issuecomment-834528420).

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
Stickers are exported like this: 

```
export default {
  aspectRatio: 60 / 60,
  svg: HeartCta,
};
```

So we can add a label easily here. The UX for the sticker panel is not done yet. It is here:  #6187

**Comment by csossi** [comment]
Verified in QA
