### ISSUE TITLE
Animations: Update duration and ease of background animations to bring users peace and tranquility

### ISSUE THREAD

**Issue by maxyinger** [GoogleForCreators/web-stories-wp#7433]
Currently the default for background animations feel a little jarring. This task is to design a new easing curve & or duration such that the defaults feel nice.

https://xwp.slack.com/archives/C01ESBB8ZN1/p1620398347060200

**Comment by dreamofabear** [comment]
For reference, the STAMP defaults use cubic-bezier curves for some animation types that we use linear curves for. I'd be curious if matching the STAMP defaults to start would achieve sufficient peace and tranquility. :)

https://github.com/ampproject/amphtml/blob/main/extensions/amp-story/1.0/animation-presets.js

**Comment by BrittanyIRL** [comment]
Completed with release 1.8
