### ISSUE TITLE
Templates: Saved Colors

### ISSUE THREAD

**Issue by embarks** [GoogleForCreators/web-stories-wp#7449]
## Description
- View a template's details by exploring templates in the dashboard and clicking "See details" when hovering on a template
- The color list is highlighted below
![image.png](https://images.zenhubusercontent.com/5f7b469a8022e02e0b23aea1/a4a6be93-6ed2-4f2f-afd9-781818402a1d)

## Additional details 
- The template's colors should show up in the story saved colors, not global. 

## Acceptance Criteria 
- The colors described above should be shown in the to "**STORY** Saved Colors" when the template is used from the dashboard.

## Implementation Brief
- The colors' hex codes are in the `metaData` file of each respective template in the template package (`packages/templates/src/raw/[template-name]/`). They are stored as an array with a label for description and a hex code (`{label: 'winter blue', color: '#a4deff'}`). 
- The `saved colors` isn't new, users can save their own colors already. Saved colors live in `style_presets`, accessible through the `useStory` context. When a story's loaded the saved colors get structured (see `story-editor/src/app/story/effects/useLoadStory`)
- Right now the `colors` of a template (`template.colors`) are not getting passed to `getStoryPropsToSave` when the 'use template' button is clicked and `createStoryFromTemplate` request is triggered. 
- Pretty sure that the logic is all set up on the editor side to handle this, but that the saved colors of a template aren't quite making it into the story when the editor loads.

**Comment by swissspidy** [comment]
cc @miina as she worked on the Saved Colors feature.

Note: this change should only affect the colors for the current story, not the global colors:

![Screenshot 2021-05-07 at 23 59 31](https://user-images.githubusercontent.com/841956/117512635-46a06400-af90-11eb-8e0d-fa08615b6757.png)

There might be some need for some REST API changes here, not sure.

**Comment by swissspidy** [comment]
@BrittanyIRL FYI I assigned this to Pea pod for now, but I think we can collaborate on this as it might require some PHP changes.

**Comment by BrittanyIRL** [comment]
> @BrittanyIRL FYI I assigned this to Pea pod for now, but I think we can collaborate on this as it might require some PHP changes.

thank you! i'm excited about this one.

@o-fernandez we should add this one to the roadmap as well.

**Comment by o-fernandez** [comment]
@BrittanyIRL added for now as a TBD milestone.
