### ISSUE TITLE
Limit One Video Per Page

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#745]
## Bug Description

I am able to add multiple videos per page:

e.g. 
Added a bg video and 2 videos:
![image](https://user-images.githubusercontent.com/5874851/77443422-6e9b2b00-6dc1-11ea-9719-b957ee7a50b3.png)

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment]
Possibly no longer a requirement per @pbakaus.
Should I close this?

**Comment by pbakaus** [comment]
Yes let's close. Let's allow multiple videos.
