### ISSUE TITLE
Video Optimization: Remove feature flag code

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7466]
## Feature Description

The `videoOptimization` flag has been enabled by default for the last release cycle. Now it's time to remove the code completely.

https://github.com/google/web-stories-wp/blob/f8d0599820d5cf1959b5b129ab297013274b670a/includes/Experiments.php#L356-L367

https://github.com/google/web-stories-wp/blob/58cdb6b35adaaa92a80058d6d3c765899f777c3f/assets/src/edit-story/app/media/utils/useFFmpeg.js#L59-L81

https://github.com/google/web-stories-wp/blob/58cdb6b35adaaa92a80058d6d3c765899f777c3f/assets/src/edit-story/app/media/utils/useMediaUploadQueue/index.js#L104

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
Let's also remove these

https://github.com/google/web-stories-wp/blob/a31592468d3145c266a2577692f53a0aeb028a10/includes/Admin/Cross_Origin_Isolation.php#L45-L59

https://github.com/google/web-stories-wp/blob/a31592468d3145c266a2577692f53a0aeb028a10/includes/Admin/Cross_Origin_Isolation.php#L285-L287
