### ISSUE TITLE
SVG rendering for thumbnails

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#7468]
## Feature Description

Add (static) SVG rendering for thumbnails.

## Additional Context

Caveats:
* Texts are still using fonts, not rendering as glyphs
* Line breaks implemented implicitly using either svg 1.2 textarea or svg 2.0 autowrap (depending on browser support)
* Videos are displayed as poster image only (even if video playing on canvas)
* Animations never play in thumbnails
* Use strict memoization
* Explore render to string rather than render elements

### Future work
This is just important to keep in mind while doing this work to make sure these future work items are possible or figure out why they're not.

#### Future use cases to expand to

* Expand to text sets display in text panel
* Expand to page templates in template panel (when not animated)
* Expand to story preview in the dashboard (when not animated, if not replaced by story cover image)
* Expand to canvas while using color picker

#### Future functionality to be added

* Render texts as glyphs rather than using fonts (reduce font load in the future)
* Convert animations to SVG

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
> Expand to story preview in the dashboard (when not animated, if not replaced by story cover image)

Ditto for the story preview in the Web Stories Gutenberg block

**Comment by miina** [comment]
@merapi Assigning the issue to you since the PR was assigned to you by Morten and looks like you already started working on it, too.

**Comment by miina** [comment]
Closing this issue as we're going to use image rendering instead.
