### ISSUE TITLE
Video Optimization PPC: Respect `local` attribute when loading/optimizing

### ISSUE THREAD

**Issue by maxyinger** [GoogleForCreators/web-stories-wp#7472]
`Video not Optimized` tip should not show while `element.resource.local === true` . this prevents the check from prematurely showing while optimization is in progress

**Comment by spacedmonkey** [comment]
Video where `element.resource.isOptimized === true` should also be ignored.

**Comment by maxyinger** [comment]
> Video where element.resource.isOptimized === true should also be ignored.

Yup. Is already built in there:
https://github.com/google/web-stories-wp/blob/06d921a7a7e1080a52cb3ff07c8fe7ad5493809f/assets/src/edit-story/app/prepublish/guidance/media.js#L156

**Comment by swissspidy** [comment]
Aside: That `isCoverrMedia` check in `videoElementOptimized` seems a bit brittle...
We should rather set `isOptimized` in `getResourceFromMedia3p`, perhaps adding a migration if needed.

**Comment by spacedmonkey** [comment]
> Yup. Is already built in there:

This is what I get for commenting on my phone without checking. 

> We should rather set isOptimized in getResourceFromMedia3p, perhaps adding a migration if needed.

Adding `isOptimized: true` to `getVideoResourceFromMedia3p` is a good idea.

**Comment by BrittanyIRL** [comment]
@littlemilkstudio will you point?

**Comment by swissspidy** [comment]
Just adding the `local` check should be a matter of minutes :-)

> Aside: That `isCoverrMedia` check in `videoElementOptimized` seems a bit brittle...
> We should rather set `isOptimized` in `getResourceFromMedia3p`, perhaps adding a migration if needed.

I'll create a ticket for this.

**Comment by maxyinger** [comment]
yeaup. can add the local check in and remove the `isCoverrMedia` rq once I finish up this stickers pr

**Comment by swissspidy** [comment]
@littlemilkstudio This would warrant a data migration for existing resources. Best to handle in a new PR & ticket.

**Comment by swissspidy** [comment]
Opened #7529 for the follow-up task.
