### ISSUE TITLE
Video Optimization PPC: Inform user they need to reload after enabling auto-optimization

### ISSUE THREAD

**Issue by maxyinger** [GoogleForCreators/web-stories-wp#7473]
When auto-optimization is enabled from the PPC, a reload is required for the auto-optimization to start working. We should either provide the user a note saying they must refresh the page, or refresh for them

**Comment by spacedmonkey** [comment]
A reload should not be required to work. Users are opted in automatically. The cross origin headers sent by default. Reloading should not be required. Can you explain this behavior that lead to this issue.

**Comment by swissspidy** [comment]
@spacedmonkey A reload **is** required if users previously opted out but then opt in again in the pre-publish checklist.

**Comment by spacedmonkey** [comment]
> @spacedmonkey A reload is required if users previously opted out but then opt in again in the pre-publish checklist.

Right, that is what I didn't understand here. Thanks for the clarification.

**Comment by BrittanyIRL** [comment]
@tmagalhaes-huge @aaecheverria I think we could use a little help figuring out the best way to communicate this to users. Could we make a little time in our call tomorrow?

**Comment by BrittanyIRL** [comment]
Given our design limbo how should we handle this one? 

Should we:
a) force a reload when they opt in
b) show a dialog asking if they'd like to reload 
c) update verbiage saying something about how you need to reload the page for changes to take effect

@swissspidy @spacedmonkey @o-fernandez thoughts?

**Comment by swissspidy** [comment]
A & B are tricky because unsaved changes need to be saved first.

**Comment by BrittanyIRL** [comment]
> A & B are tricky because unsaved changes need to be saved first.

when users enable auto optimization we could trigger a dialog and say they need to refresh to have changes take effect - if they say "ok, refresh screen" as the CTA we could just fire a save action and then refresh the page that way. 

might be annoying to have a dialog pop up but it's probably the best way to ensure users actually read and respond. thoughts?

**Comment by BrittanyIRL** [comment]
<img width="314" alt="Screen Shot 2021-11-30 at 11 38 58 AM" src="https://user-images.githubusercontent.com/10720454/144107928-f310952c-e7b2-4cb9-a1e5-173a63ffdd1a.png">

**Comment by BrittanyIRL** [comment]
Circling back to this screenshot - in our design sync on tuesday 11/30 discussed this with @agingoldseco who is going to work on mocking something up to make it clear to users that they need to reload the screen after enabling auto-optimization. Because it's rather hard to trigger this checkbox if it's already enabled I've included a screenshot to save design some time. 

The solution we discussed was when the checkbox is checked rather than having it just disappear immediately, swap it out with a confirmation message of some sort that says 'great, in order for this change to take effect please refresh your browser'. Amy to work on design mocks.

**Comment by agingoldseco** [comment]
Here's a screenshot of the options we talked about today—Figma soon! 

@choumx I've heard you're the designated copy guru :), how do you feel about the language here? 
Also, happy to hear if you have an opinion on these options. 

<img width="1522" alt="Screen Shot 2021-12-07 at 4 46 43 PM" src="https://user-images.githubusercontent.com/90645922/145111159-b7f644e8-e6cd-491e-8103-7a234ef55259.png">

**Comment by dreamofabear** [comment]
How about: 

> Automatic video optimization enabled. Reload the page to apply changes.

**Comment by swissspidy** [comment]
My proposal [as shared on Slack](https://xwp.slack.com/archives/C0134J07HV3/p1639077620032500) is to add a "Save & Refresh" button below the text.

Text should not be green either.

----

Also, note for implementors: this should be announced to screen readers via `useLiveRegion()`

**Comment by dreamofabear** [comment]
I don't have a strong opinion other than "reload" vs. "refresh" (the former is what browser tooltips say). :)

**Comment by agingoldseco** [comment]
I like refresh, but if the tooltips say reload we should be consistent. In which case, I think this is our guy:

<img width="753" alt="Screen Shot 2021-12-13 at 7 25 42 PM" src="https://user-images.githubusercontent.com/90645922/145910498-7088d72e-7201-4056-b88f-7317d1252de1.png">

**Comment by spacedmonkey** [comment]
For reference, when you enable custom fields in the gutenberg editor. 

<img width="777" alt="Screenshot 2021-12-14 at 12 13 35" src="https://user-images.githubusercontent.com/237508/145996281-d29ee894-9d83-45b0-a450-11b563f2dd20.png">

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin, using PR #10063.

1. Turned off video optimization
2. Added a new video to the story
3. Checked the messages displayed on "Checklist" - Accessibility displays option to optimize all videos in the story
4. Clicked on the checkbox to enable automatic optimization - Save & Reload button is displayed
5. Clicked on Save & Reload - page is reloaded, videos are displayed in the canvas

![opt 1](https://user-images.githubusercontent.com/96055551/149162120-0fc40bde-f59c-4f63-b8d8-5776a4f2d302.png)

![opt 2](https://user-images.githubusercontent.com/96055551/149162132-8fac8a8e-18ff-463d-8042-3c59e0311922.png)

![opt 3](https://user-images.githubusercontent.com/96055551/149162148-f91c753b-1273-4403-8850-e4557320e35b.png)

![opt 4](https://user-images.githubusercontent.com/96055551/149162157-b7b7cbde-9196-4e1a-8966-ee666df00cb4.png)
