### ISSUE TITLE
Media: Transcode videos inserted from WordPress media modal

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7480]
## Feature Description

When users have previously uploaded MOV files to the WordPress media library, there is currently no way to insert those MOV files in the story editor, because it's not an allowed file type.

Since we now have the ability to transcode videos using FFmpeg, we are in a position to change this.

Here's where this would need to happen:

https://github.com/google/web-stories-wp/blob/06d921a7a7e1080a52cb3ff07c8fe7ad5493809f/assets/src/edit-story/components/library/panes/media/local/mediaPane.js#L166-L208

1. Ensure MOV files are visible in the WP media modal
2. When selecting a MOV file, insert a placeholder resource (if needed)
    1. For this, `getResourceFromMediaPicker` probably needs to use `getPlaceholderResource`
3. Then, directly call `useProcessVideo` to optimize that video.  
   1. Caveat: placeholders don't have a `src`, but `optimizeVideo` needs one. Need to figure out how to best get that `src` there.

**Considerations:**

Since transcoding takes some time, we shouldn't run FFmpeg on _all_ videos, but only ones that **must** be transcoded (i.e. MOV files). MP4 videos can still be optimized later by the user through the pre-publish checklist.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by dreamofabear** [comment]
@o-fernandez FYI this would be necessary to support the "upload videos on phone" workflow.

**Comment by o-fernandez** [comment]
Let's do this. Do we need UX input or do we think we can sort this out on our end based on the patterns we already have in the editor today? @swissspidy @choumx 
Seems like it's in "ready for sprint" so it may just be a matter of prioritizing.

**Comment by swissspidy** [comment]
I think I intended to move this to the backlog when I created this, but yeah it should be possible to create a first working version of this based on existing patterns in the editor.

**Comment by csossi** [comment]
Verified in QA

**Comment by o-fernandez** [comment]
> Verified in QA

👏🏼👏🏼👏🏼
