### ISSUE TITLE
E2E Tests: Fix inserting media elements

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#7481]
## Feature Description

A number of e2e tests inserting media elements are unstable. This is probably due to the moveable-overlay on top of the media elements, that cause clicks to sometimes be ignored, sometimes work correctly.

These tests are skipped for that reason and need fixing:

* [`Pre-Publish Checklist`](https://github.com/google/web-stories-wp/blob/main/packages/e2e-tests/src/specs/editor/prepublishChecklist.js)
* *  [`should show that there is no poster attached to the story`](https://github.com/google/web-stories-wp/blob/main/packages/e2e-tests/src/specs/editor/prepublishChecklist.js#L37)
* [`Inserting 3P Media`](https://github.com/google/web-stories-wp/blob/main/packages/e2e-tests/src/specs/editor/media/insert3PMedia.js)
* * [`should insert an Unsplash image`](https://github.com/google/web-stories-wp/blob/main/packages/e2e-tests/src/specs/editor/media/insert3PMedia.js#L32)
* * [`should insert an coverr video`](https://github.com/google/web-stories-wp/blob/main/packages/e2e-tests/src/specs/editor/media/insert3PMedia.js#L53)
* * [`should insert an tenor gif`](https://github.com/google/web-stories-wp/blob/main/packages/e2e-tests/src/specs/editor/media/insert3PMedia.js#L72)

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
@barklund as you updated this ticket and seem to have more context. Can you update more details why you think this issue has started and any possible solutions.

**Comment by swissspidy** [comment]
FWIW, when Morten noticed this, it was a long time after you've created this ticket, so any flakiness was already there _before_ his work on #8335.

IIRC one potential culprit was the Moveable integration in the library.

cc @miina
