### ISSUE TITLE
Center alignment of embedding Stories via Gutenberg does not look centered

### ISSUE THREAD

**Issue by shishirm** [GoogleForCreators/web-stories-wp#7486]
## Bug Description

When trying to center align a Story within a blogpost in WP using the Gutenberg blocks, the Story does not look center aligned. This specifically happens when trying to use the "List" or "Grid" style embed. It does work for the "Boxed Carousel" embed but the creator might want to only have a single story that is centered and not in a carousel. I've attached a screen recording of the issue.

## Expected Behaviour

The expectation is that when we select the centered module, the Story will appear centered in the blogpost.

## Steps to Reproduce

Follow steps in the video below.

## Screenshots

https://drive.google.com/file/d/1X6lN7JfA1elqsmfLnKemChwLZqZPPEBn/view?usp=sharing&resourcekey=0-issFtqpbDc1yI_4mZiQ4ew

## Additional Context

- Plugin Version: 1.6
- WordPress Version:5.7+
- Operating System: Mac
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Thanks a lot for your thorough report!

We're working on related bug fixes for aligning the Gutenberg block and will make sure to address this specific issue soon as well.

**Comment by swissspidy** [comment]
Closing in favor of #6987

**Comment by swissspidy** [comment]
> but the creator might want to only have a single story that is centered and not in a carousel.

#6894 would solve this
