### ISSUE TITLE
Page Templates: Hide Save new template button for blank page

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#7498]
## Feature Description
Currently, the button for saving a new page template is shown for a blank page even though a blank page can't be saved as a button. Let's hide the button for a blank page.

We can also remove the snackbar logic currently used for displaying information when trying to add a blank page since this will not be even possible anynore.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
