### ISSUE TITLE
Blurry images due to small images in `srcset`

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7500]
## Bug Description

There were a few reports where images were blurry due to how `srcset` and `sizes` are applied on images. The browser will unexpectedly pick a low-res thumbnail instead of a more reasonable high-quality thumbnail.

## Expected Behaviour

No blurry images

## Steps to Reproduce

**Note:** depends on the viewport.

On this story: https://google-webstories.rt.gw/web-stories/batch-1-story-8-home-and-garden/

With the following markup on the first page:

```html
<amp-img
        layout="fill"
         src="https://google-webstories.rt.gw/wp-content/uploads/2021/04/batch1_story8_homeandgarden_screen1_img1-1.jpg"
        alt="batch1_story8_homeandgarden_screen1_img1"
        srcset="
        https://google-webstories.rt.gw/wp-content/uploads/2021/04/batch1_story8_homeandgarden_screen1_img1-1.jpg 977w,
        https://google-webstories.rt.gw/wp-content/uploads/2021/04/batch1_story8_homeandgarden_screen1_img1-1-760x1024.jpg 750w,
        https://google-webstories.rt.gw/wp-content/uploads/2021/04/batch1_story8_homeandgarden_screen1_img1-1-223x300.jpg 223w"
        class="i-amphtml-layout-fill i-amphtml-layout-size-defined"
        i-amphtml-layout="fill">
</amp-img>
```

AMP runtime will turn it into:

**Note:** `1540px` below is dynamic depending on the viewport.

```html
<amp-img
    layout="fill"
    src="https://google-webstories.rt.gw/wp-content/uploads/2021/04/batch1_story8_homeandgarden_screen1_img1-1.jpg"
    alt="batch1_story8_homeandgarden_screen1_img1"
    srcset="
    https://google-webstories.rt.gw/wp-content/uploads/2021/04/batch1_story8_homeandgarden_screen1_img1-1.jpg 977w,
    https://google-webstories.rt.gw/wp-content/uploads/2021/04/batch1_story8_homeandgarden_screen1_img1-1-760x1024.jpg 750w,
    https://google-webstories.rt.gw/wp-content/uploads/2021/04/batch1_story8_homeandgarden_screen1_img1-1-223x300.jpg 223w"
    class="i-amphtml-layout-fill i-amphtml-layout-size-defined i-amphtml-element i-amphtml-built i-amphtml-layout"
    i-amphtml-layout="fill"
    style="--loader-delay-offset:84ms !important;">
    <img
        decoding="async"
        sizes="(max-width: 1540px) 72px, 100vw"
        alt="batch1_story8_homeandgarden_screen1_img1"
        srcset="
        https://google-webstories.rt.gw/wp-content/uploads/2021/04/batch1_story8_homeandgarden_screen1_img1-1.jpg 977w,
        https://google-webstories.rt.gw/wp-content/uploads/2021/04/batch1_story8_homeandgarden_screen1_img1-1-760x1024.jpg 750w,
        https://google-webstories.rt.gw/wp-content/uploads/2021/04/batch1_story8_homeandgarden_screen1_img1-1-223x300.jpg 223w"
        src="https://google-webstories.rt.gw/wp-content/uploads/2021/04/batch1_story8_homeandgarden_screen1_img1-1.jpg"
        class="i-amphtml-fill-content i-amphtml-replaced-content"
    />
</amp-img>
```

## Screenshots

See how the browser chooses the 223w version, even though it's smaller than the actual size on the page

![Screenshot 2021-05-12 at 18 56 14](https://user-images.githubusercontent.com/841956/118014727-ce50ee80-b353-11eb-98a1-650cfb83dace.png)

![Screenshot 2021-05-12 at 18 56 09](https://user-images.githubusercontent.com/841956/118014741-cf821b80-b353-11eb-9030-6040a7f980f9.png)

Removing the `position: absolute` on the image somewhat improves the experience. Seems like this trips up the browser's `srcset` picking

![Screenshot 2021-05-12 at 19 04 04](https://user-images.githubusercontent.com/841956/118015829-fe4cc180-b354-11eb-83c6-3610d0b20245.png)
![Screenshot 2021-05-12 at 19 03 57](https://user-images.githubusercontent.com/841956/118015838-0147b200-b355-11eb-9195-05b3f8059e7c.png)

## Additional Context

- Plugin Version: 1.6.0
- WordPress Version: 5.7
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
cc @choumx ~@barklund~ for input

**Comment by swissspidy** [comment]
@choumx  @BrittanyIRL @miina one of you / your pods familiar with this area?

**Comment by miina** [comment]
@swissspidy The `sizes` value of the `img` tag seems off:
<img width="865" alt="Screenshot 2021-05-26 at 18 45 13" src="https://user-images.githubusercontent.com/3294597/119690753-40dcc680-be4a-11eb-906a-4af86c257d64.png">

Where does the `72px` come from, does this seem right to you?

**Comment by swissspidy** [comment]
That `<img>` element with the `sizes` attribute is added by the AMP runtime. We only add the `<amp-img>` element with the `srcset` attribute (compare 1st vs 2nd code snippet above)

**Comment by miina** [comment]
Hm, okay, there seems to be something off with the `sizes`. When saving this story locally and viewing it, a different (and correct) `sizes` value is added to the `img` tag. Or well, it looks like initially, it adds just the `72px`, and then right away also adds another `img` element with the correct `sizes`, too. Which then visually replaces the stretched out image with the correct sized image:
<img width="428" alt="Screenshot 2021-05-26 at 18 57 53" src="https://user-images.githubusercontent.com/3294597/119692805-02480b80-be4c-11eb-8abc-7dec4894b814.png">

**Comment by swissspidy** [comment]
@newmuis Sam mentioned that you had briefly looked into this issue before, mentioning how the `sizes` part is wrong. Since this is not added by the plugin, any advice on how we could fix this in WP? Or does this need fixing on the format side?

**Comment by swissspidy** [comment]
@newmuis @choumx friendly ping, would love some advice on this one :)

**Comment by dreamofabear** [comment]
Sorry for the delay here! Looks like the poor image selection is due to `amp-img`'s [autogenerated `size` attribute](https://amp.dev/documentation/components/amp-img/#sizes):

> If the srcset attribute is provided, `<amp-img>` will autogenerate the HTML5 definition of the sizes attribute for the underlying `<img>`, when none is specified. 

```
sizes="(max-width: <current_viewport_width_px>) 72px, 100vw"
```

The `72px` in this case comes from the image's calculated size during AMP layout, which is happens too early (relative to amp-story and fill layout) and is inaccurate (way too small). 

We can fix this by rendering a correct `sizes` attribute for images, which we can calculate given the image element's size on the canvas (accounting for the desktop viewing mode). I'll try to make time to take a stab at a fix this week.

**Comment by csossi** [comment]
Verified in QA
