### ISSUE TITLE
New Web Story Embed Methods, suggested by Google

### ISSUE THREAD

**Issue by panchammsinghh** [GoogleForCreators/web-stories-wp#7502]
## Feature Description

Yesterday, Google shared this article on improving visibility of Web Stories. I like the new integration (embed) methods, like Singleton, Compact display, and Dedicated page.

Is there any way to add it now? to homepage?

here's the link of Google's article - https://blog.google/web-creators/raise-visibility-web-stories/

Detailed Methods (PDF Document) - https://services.google.com/fh/files/events/web_stories_playbook.pdf

Figma link - https://www.figma.com/community/file/972549350664888470

![image](https://user-images.githubusercontent.com/61957280/117969100-a1490f80-b344-11eb-9921-2134056ef8e0.png)

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Thanks for sharing your interest in these various embedding options and Web Stories in general!

The Web Stories WordPress plugin already supports many options to embed stories on your website. See this blog post for some details: https://blog.google/web-creators/embedding-web-stories-across-your-site/

We're working on adding more such capabilities to the plugin, resembling the examples from that document you shared. 

So stay tuned for more updates coming your way! :-)

**Comment by panchammsinghh** [comment]
Customization capabilities in PlayBook embeds - https://makestories.io/story-player/
