### ISSUE TITLE
The Quick Tip for "Preview" shows a different UX 

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#7504]
## Bug Description

Currently in the Quick Tip for "Preview your Web Story" there is a button shown in the animation which does not match the GUI that is currently in place. 

Here is what the tip shows:

![Screen Shot 2021-05-12 at 12.01.25 PM.png](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/673d5056-2e9d-4135-b961-e8c40b195411) 

and
 
![Screen Shot 2021-05-12 at 12.06.01 PM.png](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/b2de7389-765e-4830-883f-3f7b881130d4)

Here is the UX that is in place

![Screen Shot 2021-05-12 at 12.07.01 PM.png](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/d632b8ff-1164-438e-ba22-56efe11c4b50)

## Expected Behaviour

The tip and the UX should match for it not to be confusing

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
@Cecil921 @aaecheverria ^^

**Comment by swissspidy** [comment]
Are other images out of date too?

**Comment by BrittanyIRL** [comment]
> Are other images out of date too? 

@swissspidy  Nope! Just this one, it got added before the design system was ready and then there was something on slack i think (because i can't find a ticket) talking about how it was confusing to use the new design system in the tip so let's use the old. And now here we are where it's reversed. Will be an easy update once we get a new asset.

**Comment by ivayloklissarov** [comment]
Concerning this, we had implemented already in the DS a new design of how it should work. The idea was to use the stroke of the button as the loader. @BrittanyIRL @swissspidy 

Poste Stable: https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/?node-id=361%3A0
DS: https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/?node-id=25%3A1312

![image](https://user-images.githubusercontent.com/77846281/119396597-abe79b00-bc9a-11eb-842b-ca425a1cc673.png)

**Comment by BrittanyIRL** [comment]
hey @ivayloklissarov  - this is just a ticket to update the asset in the help center so it shows the new UI instead of the old one. We just need to know what/where the updated asset is for this tip in the help center.

**Comment by ivayloklissarov** [comment]
Oh got it! This is the most recent video with the updated UI of the buttons. @BrittanyIRL 
https://drive.google.com/drive/u/1/folders/1DqQ8mbl-N9x9lJwontYpBvd2yiUBRQ5F

**Comment by BrittanyIRL** [comment]
thank you!
