### ISSUE TITLE
Incompatibility with AMP plugin 2.1.1

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7506]
## Bug Description

This was reported while testing the [1.7.0 release](https://github.com/google/web-stories-wp/releases/tag/v1.7.0).

If the user has an up-to-date version of the AMP plugin installed, we defer all AMP sanitization & optimization to the AMP plugin.

It appears that some change in the AMP plugin 2.1 broke this behavior, where the output is now no longer going through the AMP plugin.

My suspicion is that it's in these areas of the code base:

https://github.com/google/web-stories-wp/blob/8564961daac656d844b4720448aa051b452cb064/includes/Integrations/AMP.php#L74-L90

https://github.com/google/web-stories-wp/blob/8564961daac656d844b4720448aa051b452cb064/includes/Integrations/AMP.php#L244-L299

`get_request_post_type` checks for the `wp` action and `is_singular`, but now `AMP_Options_Manager::get_options()` is called on the `wp_loaded` hook, which is earlier.

## Expected Behaviour

No incompatibility with AMP v2.1.1

## Steps to Reproduce

1. Install AMP 2.1.1
2. Publish a story and view it on the frontend
3. See tons of AMP validation errors

## Screenshots

<img width="1436" alt="Screen Shot 2021-05-12 at 1 04 09 PM" src="https://user-images.githubusercontent.com/841956/118020507-6fdb3e80-b35a-11eb-8ae8-2321be08dcbc.png">

## Additional Context

- Plugin Version: 1.7.0
- WordPress Version: 5.7
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
cc @westonruter

**Comment by westonruter** [comment]
In my testing, the following patch results in a valid AMP page when used with AMP plugin v2.1.0, v2.1.1, and v2.2.0-alpha:

```diff
diff --git a/includes/Integrations/AMP.php b/includes/Integrations/AMP.php
index 48e94cdb2..f9bac7b27 100644
--- a/includes/Integrations/AMP.php
+++ b/includes/Integrations/AMP.php
@@ -233,7 +233,7 @@ class AMP extends Service_Base {
 			&&
 			defined( '\AMP__VERSION' )
 			&&
-			version_compare( WEBSTORIES_AMP_VERSION, AMP__VERSION, '>=' )
+			version_compare( WEBSTORIES_AMP_VERSION, AMP__VERSION, '>' )
 		) {
 			return true;
 		}
```
