### ISSUE TITLE
Font preview is no longer working

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#7507]
## Bug Description

Font preview in the drop down selector for fonts is no longer working as it was

![Screen Shot 2021-05-12 at 12.21.13 PM.png](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/5e675737-eacd-4650-9258-e156e20ae51d)

## Expected Behaviour

Fonts should be presented with the name in the font.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
