### ISSUE TITLE
Color picker: remove gap when there's no opacity

### ISSUE THREAD

**Issue by dvoytenko** [GoogleForCreators/web-stories-wp#751]
## Bug Description

When opacity is disabled, the color picker has a gap:

![image](https://user-images.githubusercontent.com/726049/77487443-b5a01500-6def-11ea-829f-e8a61bd5eefd.png)

## Expected Behaviour

Instead, the color space area should be stretched to cover for the gap:
![image](https://user-images.githubusercontent.com/726049/77487492-d10b2000-6def-11ea-8dc4-bc74548700f4.png)

## Steps to Reproduce

Open the color picker for "Page color" setting in the design panel.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## QA Instructions

/cc @barklund

**Comment by jauyong** [comment]
Noted in sprint 26 sheet
