### ISSUE TITLE
Preview development/ debug mode missing

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#7516]
## Bug Description
The preview link goes straight to the story view.

## Expected Behaviour

Development modal should display before the story view when previewing. 

## Steps to Reproduce
Preview story. 
Notice preview/debug screen skipped and the story view displays.

## Screenshots

Current view:

https://user-images.githubusercontent.com/66372350/118154314-e58bec80-b3e4-11eb-8c1c-ff3ff6a48067.mov

Previous view:
![Screen Shot 2021-05-13 at 11 32 14 AM](https://user-images.githubusercontent.com/66372350/118154351-efadeb00-b3e4-11eb-8408-d48b431e2649.png)

## Additional Context

- Plugin Version: 1.7.1
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
