### ISSUE TITLE
Border radius not working consistently

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7524]
## Bug Description

This is a follow-up to #7356 / #7380 

There are still issues with border radius in a few browsers, notably Safari and Chrome.

## Expected Behaviour

Border radius should work consistently **in all browsers**, including viewing stories in mobile devices (previously [issues had been reported](https://github.com/google/web-stories-wp/issues/7359) for iPhone 12 and iPhone 11)

## Steps to Reproduce

1. Insert animated shapes
2. Add border radius
3. Preview in browser

## Screenshots

**No border radius whatsoever**

For [story 1 of batch 1](https://google-webstories.rt.gw/web-stories/batch-1-story-1-entertainment/), no border radius is applied to any Rectangle shapes _in Safari_.
Affected pages: 2, 4, 6, 8, 9, 11 , 12
Screenshot:
![story_1-corner_radius_issue](https://user-images.githubusercontent.com/841956/118244756-31e83280-b4a0-11eb-8931-a59b031da361.jpeg)

**Border radius being applied late**

For [story 5 of batch 1](https://google-webstories.rt.gw/web-stories/batch-1-story-5-technology-2/), the issue still seems appear randomly on few screens on Chrome browser but does not replicate on Safari or Firefox
Affected pages: 2, 9
Demo:

https://user-images.githubusercontent.com/841956/118245056-960af680-b4a0-11eb-997e-58ee2c288abe.mov

Personally, I was not able to reproduce this one.

## Additional Context

- Plugin Version: 1.8.0-alpha
- WordPress Version: 5.7
- Operating System: macOS
- Browser: Safari 14.1 / Chrome 90

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
This feels like an issue with borders not necessarily animation? @miina could you weigh in here? 

I can't get the issue to replicate on Chrome at all. I see the missing borders on Safari and could have sworn we had a bug ticket lurking around for this specific browser bug but I cannot find it.

**Comment by miina** [comment]
Yep, that's a problem with Safari, not related to the animations. `overflow: hidden` doesn't seem to work the same way in Safari as elsewhere apparently. The rounded parent has `overflow:hidden` which doesn't have any effect in Safari in this case.

**Comment by swissspidy** [comment]
The same Safari bug was reported in #7359.

Apparently border-radius + overflow is a well-known issue with Safari and there several workarounds circulating.

Related webkit bugs references I found:

* https://bugs.webkit.org/show_bug.cgi?id=140535
* https://bugs.webkit.org/show_bug.cgi?id=98538

You can work around it in recent builds by making the element with overflow:hidden into a stacking context (e.g. position:relative, z-index:0).

Things that seem to work:

* Removing the `will-change: transform` workaround added in #7380
* Move the `will-change: transform` to the parent
* Setting `z-index:0` on the parent (affecting [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context))
* Set `-webkit-mask-image: -webkit-radial-gradient(white, black);` on the parent

**Comment by swissspidy** [comment]
@BrittanyIRL @miina Since this is not about animations, should I assign Prometheus pod instead? Should be a simple fix it seems, so would be great if anyone could pick this up

**Comment by miina** [comment]
@swissspidy Sure, sounds good to me. I'll reassign.

**Comment by csossi** [comment]
Verified in QA
