### ISSUE TITLE
Media: Media library is jumpy on first render. 

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#7525]
## Bug Description

When the media library is first loads, it renders is a odd jumpy way. See video. 

## Screenshots

https://user-images.githubusercontent.com/237508/118253325-b7b8ad80-b4a1-11eb-8999-4c01cbefd41e.mov

## Additional Context

- Plugin Version: 1.7.0
- WordPress Version: 5.7.1
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
I assume this is because `react-virtual` doesn't know the items' exact dimensions initially.

Perhaps @barklund or @miina know more about how `react-virtual` works here.

**Comment by spacedmonkey** [comment]
it worth noting, this change seems to have with the last say month. I feel like i would have noticed if it was always like this...

**Comment by miina** [comment]
Hm, seems like the scrollbar appearing pushes the placeholders and then it adjusts again to correct. Perhaps reducing the available space for media by the width of the scrollbar would fix the issue.
