### ISSUE TITLE
Stories block: Story selector screen styling issue. 

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#7526]
## Bug Description

Styling issues with WordPress 5.3.6

## Screenshots

<img width="1784" alt="Screenshot 2021-05-14 at 11 40 12" src="https://user-images.githubusercontent.com/237508/118259600-454bcb80-b4a9-11eb-9c73-29857ea989c6.png">

## Additional Context

- Plugin Version: 1.7
- WordPress Version: 5.3.6
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Is this limited to 5.3 or also happening on newer WP versions?

**Comment by spacedmonkey** [comment]
Seems to be an issue in 5.4 and 5.5 as well. 
## WP 5.4
<img width="1780" alt="Screenshot 2021-05-14 at 12 26 13" src="https://user-images.githubusercontent.com/237508/118264564-ca39e380-b4af-11eb-9547-41d4261edc58.png">

## WP 5.5
<img width="1779" alt="Screenshot 2021-05-14 at 12 27 23" src="https://user-images.githubusercontent.com/237508/118264569-cc9c3d80-b4af-11eb-8639-81f4570e09d5.png">

**Comment by csossi** [comment]
Verified in QA
