### ISSUE TITLE
Stories block: toolbar styling issues. 

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#7527]
## Bug Description

Block toolbar is styling issues. See screenshot. 

## Screenshots

![Screenshot 2021-05-14 at 11.51.44.png](https://images.zenhubusercontent.com/5e42a37e17fa4507e92c591f/628853b6-b91e-4873-bdfe-2b5dc5de3a5e)

## Additional Context

- Plugin Version: 1.7.
- WordPress Version: 5.3.6
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Is this only on 5.3? Or also on newer WP versions?

**Comment by spacedmonkey** [comment]
It seems to fix as of 5.4

## WP 5.4
<img width="723" alt="Screenshot 2021-05-14 at 12 25 55" src="https://user-images.githubusercontent.com/237508/118264810-2ef53e00-b4b0-11eb-99f6-c93b2e09244d.png">

There are other issues here. Compare it to WP 5.5.

## WP 5.5
<img width="651" alt="Screenshot 2021-05-14 at 12 31 20" src="https://user-images.githubusercontent.com/237508/118264895-521fed80-b4b0-11eb-9868-aa8c52fbbc51.png">

**Comment by swissspidy** [comment]
Closing in favor of #7551 as it looks good on WP 5.5+ and we're bumping our minimum requirement to that version.
