### ISSUE TITLE
Media: Mark 3P Media resources as optimized

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7529]
## Feature Description

Splitting this out from #7472, 3P media should be marked as `isOptimized` directly on the resource.

This check should _not_ be done in the pre-publish checklist.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

* Add a new data migration to mark any `resource` as `isOptimized=true` if its ID starts with `media/coverr:` (i.e. `resource.id.startsWith('media/coverr:')`)
* Add tests for this new migration
* Set `isOptimized=true` in `getResourceFromMedia3p` (specifically in `getVideoResourceFromMedia3p`)
* Update tests for `getResourceFromMedia3p` accordingly
* Remove any Coverr-specific logic from `videoElementOptimized`

**Comment by swissspidy** [comment]
@spacedmonkey Is this perhaps something you'd like to pick up? Otherwise I'll assign to pea pod.

**Comment by spacedmonkey** [comment]
I can take a look at this.
