### ISSUE TITLE
Media: Media picker shown to contributors  

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#7532]
## Bug Description

When logged in as a contributor, the upload button is still enabled and media picker is shown. Message is only shown after picker is close. 

## Expected Behaviour

Either the button should be disabled and hidden. 

## Steps to Reproduce

- Login as contributors
- Open the editor 
- Click on upload button. 
- Either upload a file or click media library. 

## Screenshots

https://user-images.githubusercontent.com/237508/118294379-90c69f80-b4d2-11eb-9d66-2591825e5c46.mov

## Additional Context

- Plugin Version: 1.7.1
- WordPress Version: 5.7.1
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Sounds like there is a missing `return;` statement here:

https://github.com/google/web-stories-wp/blob/68a24ab54992e66633b4f25a5c9ee1282504e600/assets/src/edit-story/components/mediaPicker/useMediaPicker.js#L88-L94

It was a UX decision to show this nice dialog for users without permission, but simply removing the button makes more sense to me as well.

It would need to be done in many places though (e.g. video captions, publisher logo, etc.)

We can add the missing `return` statement for now and then following up with UX about disabling/removing the buttons.

Thoughts?

**Comment by spacedmonkey** [comment]
Another option might be a disabled / greyed out button. Either way, this should be a simple fix. I will defer to the UX team here.

**Comment by swissspidy** [comment]
Let's fix the `return` statement first to restore expected behavior.
Removing the button can be discussed in a follw-up.

**Comment by csossi** [comment]
Verified in QA
