### ISSUE TITLE
Animation: Update Background animation ease default from `linear` to `ease-in-out`

### ISSUE THREAD

**Issue by maxyinger** [GoogleForCreators/web-stories-wp#7533]
Design requested that the ease default for bg animations be ease-in-out vs the current default of linear. this ticket is to make that update

**Comment by maxyinger** [comment]
Animations: Missing internationalization fixes a regression in disabled pan animations which is needed to see the latest update to pan

**Comment by maxyinger** [comment]
Visual update here for design sign off:
https://images.zenhubusercontent.com/235435637/c0eafcfa-b229-4547-a2d9-a4d57eb7e063/kapture_2021_05_17_at_10_10_04.mp4

**Comment by csossi** [comment]
Verified in QA
