### ISSUE TITLE
Bumping minimum version requirements

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7551]
## Task Description

The Web Stories plugin currently requires at least PHP 5.6 and WordPress 5.3

On the PHP and Gutenberg side of the plugin there's lots of compatibility code to ensure it works fine on these versions and we run all our tests against them too. This leads to accumulating tech debt and increasing maintenance cost for our pod. See #7526, #7527 and #7531 for some recent examples.

Thus, I am proposing to bump our minimum version requirements to PHP 7.0 and WP 5.5.

Some usage stats:

- More than 85% of active users are on WP 5.7+
- Less than 0.45% of active users are on WP 5.3.* 
- Less than 0.75% of active users are on WP 5.4.*
- Less than 0.3% of active users are on PHP 5.6.*

To put this into perspective, this would affect less than 100 users or so.

**Comment by spacedmonkey** [comment]
I am not sure where were you getting your information. How does it compare to [WordPress stats](https://wordpress.org/about/stats/). 

Looking at this page, some highlights

- 9.4% users are using PHP 5.6
- 5.5% users are using WP 5.3
- 8.9% users are using WP 5.4

Just for reference other min requires
- Jetpack, WP 5.6, PHP: 5.6
- WordPress SEO,  WP 5.6, PHP: 5.6.20
- Woocommerce - WP 5.5, PHP: 7.0
- Contact form 7  - WP 5.5, PHP: 5.6
- Gutenberg - WP 5.6, PHP: 5.6

**Comment by swissspidy** [comment]
@spacedmonkey I'm getting the data from telemetry (Google Analytics). So it only counts users who've opted into it. While this excludes users who've opted out, I'd say it's still far more representative than general WP usage stats.
