### ISSUE TITLE
Web Stories Playbook

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7558]
Publishers and creators of all sizes are adopting Web Stories to create compelling narrative experiences for readers. There is now [a new playbook](https://services.google.com/fh/files/events/web_stories_playbook.pdf) (as well as [a design kit](https://www.figma.com/community/file/972549350664888470)) to help them incorporate Web Stories into their website.

This ticket here groups our related work on bringing features from this playbook to WordPress publishes.

**Comment by panchammsinghh** [comment]
Hey @swissspidy the new embedding ways are great, when it will be available in Web Stories for Wordpress plugin? any idea?

**Comment by swissspidy** [comment]
@panchammsinghh A lot of this is already possible, see https://blog.google/web-creators/embedding-web-stories-across-your-site/. We don't have a timeline for all the other features yet.
