### ISSUE TITLE
Assets served from different domain failed to load in media picker. 

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#7560]
## Bug Description

Assets served from different domain failed to load in media picker. If transcoding is enabled, media picker is open and assets are served from S3. 

## Screenshots

<img width="1884" alt="Screenshot 2021-05-17 at 20 21 44" src="https://user-images.githubusercontent.com/237508/118544670-89f79100-b74d-11eb-9b63-b5688610c0ed.png">

## Additional Context

- Plugin Version: 1.7.1
- WordPress Version: 5.7.1
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Yikes. Sounds like we'd need to filter all these Underscore.js templates used for the media modal to add `crossorigin` attributes.

![Screenshot 2021-05-17 at 21 27 41](https://user-images.githubusercontent.com/841956/118545316-b8c63500-b756-11eb-88b3-e14e392be714.png)

`wp_print_media_templates()` is the function printing those.

Maybe something like 

```php
add_action(
	'wp_enqueue_media',
	static function() {
		remove_action( 'admin_footer', 'wp_print_media_templates' );
		add_action( 'admin_footer', 'our_custom_print_media_templates' );
	}
)

function our_custom_print_media_templates() {
	ob_start();
	wp_print_media_templates();
	$result = ob_get_clean();

	// Turn <img into <img crossorigin using regex...
}
```

Or perhaps we could add those via JS?

**Comment by swissspidy** [comment]
So this is where the `str_replace( 'class="wp-video-shortcode', 'crossorigin="anonymous" class="wp-video-shortcode', $html )` workaround in the Jetpack integration is coming from in #7520? 💡

**Comment by spacedmonkey** [comment]
> So this is where the str_replace( 'class="wp-video-shortcode', 'crossorigin="anonymous" class="wp-video-shortcode', $html ) workaround in the Jetpack integration is coming from in #7520? 💡

Yeah, that is my quick workaround for video tags. It doesn't fix images of course. I had something in mind around output buffering the underscore templates. Not done a lot of discovery yet.

**Comment by spacedmonkey** [comment]
<img width="1884" alt="Screenshot 2021-05-21 at 11 12 33" src="https://user-images.githubusercontent.com/237508/119143424-7c892200-ba3f-11eb-87a3-e85268b0cf31.png">

Worth noting that I tested 1.7.2 on my person site with s3 and seems to work fine.
