### ISSUE TITLE
PPC: Optimize video check doesn't trigger sometimes

### ISSUE THREAD

**Issue by dreamofabear** [GoogleForCreators/web-stories-wp#7561]
## Bug Description

The new video optimization pre-publish check unexpectedly doesn't trigger when videos are inserted by (a) clicking on a video in the media panel or (b) opening the WP media popup and inserting a video from the "Media Library" tab.

## Expected Behaviour

The video optimization check should consistently trigger for videos that have a resolution larger than 720p.

## Steps to Reproduce

Upload a large video (resolution greater than 720x1280) by:

1. Clicking the "Upload" button, click the "Media Library" tab in the popup, select the already uploaded video, and click "Insert into page" to add it to the current page
2. Click the video in the editor's media panel to add it to the current page

Notice that in both workflows, the optimize video check doesn't show up in the pre-publish checklist.

## Screenshots

N/A

## Additional Context

- Plugin Version: HEAD (1.8.0-alpha.*)
- WordPress Version: 5.7.2
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
