### ISSUE TITLE
Prevent `blob:` URLs from appearing in published stories

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7562]
## Bug Description

This previously came up in #2706 and #2547

Background: when uploading an image or video, browsers will generate temporary `blob:` URLs to display them in the browser while uploading. After upload, these will be replaced by the actual attachment URL pointing to the video/image.

During upload, the Save/Update button (+ autosaves) is disabled to avoid saving stories with `blob:` URLs in them.

Now, despite this safeguard we've seen published some stories in the wild with `blob:` URLs in the source code, both in `amp-video source[src]` as well as in `amp-video[poster]`

_This needs some research/debugging_

While disabling the Save/Update button makes sense, I think we can do more to prevent these URLs from appearing on the frontend. Some ideas:

* Disable Save/Update while poster is being uploaded (or any upload anywhere, actually)
* On the frontend, _remove_ any elements with `blob:` URLs to ensure valid AMP, or mark page as non-AMP (remove `amp` attribute)  
  We currently already do the latter if `amp-video source[src]` is invalid, but not for other attributes/tags.
* Add pre-publish checklist message à la "There are some corrupted media files"
* Remove offending elements in the editor upon saving
* Highlight offending elements in the editor to raise awareness
* Collect telemetry data (of what?)
* ... ?

## Expected Behaviour

No `blob:` URLs should appear in published stories, ever.

## Steps to Reproduce

For video posters:

1. Upload a video
2. Right after upload has finished, _but before poster upload has finished_, preview the story
3. See `poster="blob:...."` in the source code

## Additional Context

- Plugin Version: 1.7.1
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
@choumx curious to hear your thoughts on what to do on the frontend here, should `blob:` URLs ever slip through.

**Comment by spacedmonkey** [comment]
Wonder if we should add a check into the prepublish checklist for checking if the src of poster is an blob.

**Comment by spacedmonkey** [comment]
I wonder if this change will help this issue - #7317.

**Comment by dreamofabear** [comment]
Since we don't have a solid repro, it's unclear if a new item in the PPC would ever be viewed.

I'm leaning towards just filtering out the problematic element in this case, and perhaps sending a telemetry event (or JS error) to gauge volume/rarity.

**Comment by spacedmonkey** [comment]
I wonder if this is still happening. There has been lots of changes to the poster generation / preview process.

**Comment by swissspidy** [comment]
It‘s an edge case, but it can certainly still happen.

**Comment by swissspidy** [comment]
To accomplish this:

* Disable saving when any media upload is in progress, be it a user-initiated upload (e.g. video drag & drop from desktop to canvas) or an editor-initiated upload (e.g. automated poster generation).  
  We already do this to some degree, but we really need to ensure this is happening across the board.
* In AMP output generation, don't include any URLs if they're `blob:` URLs
* In AMP sanitization, remove any URLs if they're `blob:` URLs
