### ISSUE TITLE
Zoom: Page Attachment not positioned correctly.

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#7566]
## Bug Description
Page Attachment is not positioned correctly when present and using zoom. The size is also not adjusted.

## Expected Behaviour
Page Attachment should be positioned at the bottom of the page and change size according to zoom, too.

## Steps to Reproduce
1. Add Page Attachment
2. Zoom to 200%.

## Screenshots
![Screenshot 2021-05-18 at 13 18 33](https://user-images.githubusercontent.com/3294597/118634760-30d24080-b7d3-11eb-82c1-699ac08960a1.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
