### ISSUE TITLE
Missing video posters despite being generated

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7571]
## Bug Description

We're seeing quite a few published stories where some or all videos in the story don't have any poster image associated with them.

Interestingly, most of the time the poster image seems to have been generated and uploaded to WordPress, but the element has simply not updated. _(This can be tested by enumerating file names on the website e.g. if looking at `/wp-content/uploads/video.mp4`, check that `/wp-content/uploads/video-poster.jpeg` exists)_

Some thoughts:

* There might have been an error or timeout in the time between poster upload and updating the video.
* There could be a bug where the video is not properly updated after insertion

Related:

* #7562
* #5190
* #6963

Workaround:

* In most cases, it should be enough to remove the video from the story and re-add it in order to get the poster.

Other ideas:

* In the design panel or the pre-publish checklist, provide user a way to "fix" videos by (re-)generating video posters and ensure the video<->poster connection is correct.

## Expected Behaviour

Users should be able to rely on video posters being generated automatically for them in the background and correctly attached to the video they've inserted.

## Steps to Reproduce

One bug I've found so far:

1. Click on "Upload" to open WP media modal
2. Upload video
3. After upload, insert the video to the story
4. See how video poster is successfully being generated and attached on the video
5. See how the video in the media library on the left is **not** being updated to include the poster (unless you refresh the page)

There are many more scenarios of course.

## Screenshots

The video with the poster is from step (4) above, the video without the poster is the one from step (5) above.

![Screenshot 2021-05-18 at 19 04 20](https://user-images.githubusercontent.com/841956/118694050-efaa5280-b80b-11eb-9842-c93881bdca77.png)

## Additional Context

- Plugin Version: 1.7.1
- WordPress Version: 5.7
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

* Users should be able to rely on video posters being generated automatically for them in the background and correctly attached to the video they've inserted.

**Comment by shishirm** [comment]
Would it be possible to add in missing posters for videos as a checklist item, maybe something that runs when the creator tries to hit publish or update?

Alternatively, given a missing poster makes a Story as invalid, could we go as far as to prevent publishing. I understand this might be very restrictive, but some less restrictive flavor of this would work as well.

**Comment by swissspidy** [comment]
> Would it be possible to add in missing posters for videos as a checklist item, maybe something that runs when the creator tries to hit publish or update?

Absolutely. I mentioned the pre-publish checklist in the ticket description above as well.

But to be honest I thought this was _already implemented_. _Some code_ exists for this already at least (this was added way back in #5244):

https://github.com/google/web-stories-wp/blob/c646e5bd76d3825d7ef355d1720f4d4ad741b6d9/assets/src/edit-story/app/prepublish/constants.js#L194-L207

But it's not mentioned [in the product spec](https://docs.google.com/document/d/1GJZljicdXcP7oRdywsF3EGUaCVpCHsDrK2gUMubnrbk/edit). cc @o-fernandez 

I'd really want to make this whole poster process so robust that this check won't be needed for long though.

**Comment by o-fernandez** [comment]
Yes, it's already in the pre-publish checklist. I think that the neat improvement that we should make here is that, if we detect the poster is missing, instead of just asking them to upload a poster we make it easy for the creator to click a button to retry "generate poster". 

If it fails often, they can report to support for us to debug. 

@swissspidy @choumx wdyt?

**Comment by swissspidy** [comment]
> Yes, it's already in the pre-publish checklist.

@o-fernandez What I am saying is that it actually _isn't_. This check doesn't appear to have ever been fully implemented.

**Comment by spacedmonkey** [comment]
I wonder if this change will help this issue - https://github.com/google/web-stories-wp/pull/7317. Posters are uploaded after the video file is uploaded, so there is no gap between the two things.

**Comment by o-fernandez** [comment]
> > Yes, it's already in the pre-publish checklist.
> 
> @o-fernandez What I am saying is that it actually _isn't_. This check doesn't appear to have ever been fully implemented.

Then, let's add. We have the copy of what should be added in the [trix here](https://docs.google.com/spreadsheets/d/1PjaRp4bueQ3Cv14A7I696m0vjGCIX_kN9tIGh-V-Bkc/edit?userstoinvite=jusalazar%40hugeinc.com&ts=609bf0c6&actionButton=1#gid=920793050&range=A21:F21). 

Filed this to track https://github.com/google/web-stories-wp/issues/7613
