### ISSUE TITLE
Quick Action Menus: Hide on Zoom

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#7572]
This came up in #7563 that the menu looks a bit out of place when the canvas is zoomed. 
Absent of design this week, this ticket is to hide the quick action menu on zoom in. Tests should be included.

**Comment by maxyinger** [comment]
Just blocking this until ticket below gets merged in:
https://app.zenhub.com/workspaces/web-stories-5e94d3aced449034e1e9b226/issues/google/web-stories-wp/7509

The ticket above moves the quick actions from the display layer to the nav layer, just waiting till that gets merged in should simplify any merge conflicts or anything. 

Also the ticket above should get merged in relatively soon cus it's been in ready for QA for a couple days now, so just waiting for it to pass that.
