### ISSUE TITLE
Carousel: incorrect `role` usage

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7576]
## Bug Description

The page carousel in the editor uses `role` in a way that causes some weird nesting (see also screenshot below):

* `[role=listbox]`  
  * `[role=presentation]`  
    * `[role=option]`  
      * `[role=option]`  

Especially the duplicate, nested `option`s are worrisome here.

Not to mention that the second one is on a `button` element, which looks wrong too.

See docs on these roles:

https://www.w3.org/TR/2010/WD-wai-aria-20100916/roles#listbox
https://www.w3.org/TR/2010/WD-wai-aria-20100916/roles#option
https://www.w3.org/TR/2010/WD-wai-aria-20100916/roles#presentation

## Expected Behaviour

Correct `role` usage that passes automated and manual accessibility tests

## Screenshots

![Screenshot 2021-05-18 at 23 38 07](https://user-images.githubusercontent.com/841956/118729623-88ee5e80-b836-11eb-8881-b4ab54f076e1.png)

## Additional Context

- Plugin Version: 1.7
- WordPress Version: 5.7
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by samwhale** [comment]
Looks like this is already fixed. There are no more nested `options`. This passes axe dev tool plugin tests.

![Screen Shot 2021-10-27 at 3.14.31 PM.png](https://images.zenhubusercontent.com/5b1032a1348b7966b43421a4/98b202b8-9ab9-41b7-a45f-a5983441964a)

---

However, we still have the issue where the `button` has `role="option"`. Lifting the `option` role to the list element gives us a problem where the `option` has focusable descendants.

Seems like having a button with `role="option"` passes the automated axe tests so I'm tempted to leave it. @swissspidy do you think it's okay to leave as-is?

**Comment by samwhale** [comment]
There are no accessibility issues here anymore. While the button having a role of `option` is strange - I think it works here. The `<li>`s can't have the role of `option` because the buttons are focusable, and options can't have focusable children.
