### ISSUE TITLE
Update AMP to 2.1.2

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7579]
## Task Description

[v2.1.2](https://github.com/ampproject/amp-wp/releases/tag/2.1.2) of the AMP WordPress plugin was released yesterday with some bugfixes. Should be able to update it & the AMP PHP toolbox to the latest version easily.

**Comment by spacedmonkey** [comment]
Would this land in 1.7.2?

**Comment by swissspidy** [comment]
None of the [changes](https://github.com/ampproject/amp-wp/compare/2.1.1...2.1.2) in that release affect us directly, so it can wait for 1.8.0
