### ISSUE TITLE
PHP: remove direct `phpunit/phpunit` dependency

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7593]
## Task Description

If I understand https://github.com/Yoast/PHPUnit-Polyfills correctly, we don't need to manually require `phpunit/phpunit` in `composer.json`, as it will be required automatically through `yoast/wp-test-utils` and thus `yoast/phpunit-polyfills`.

https://github.com/google/web-stories-wp/blob/c4b2f02b98713b17962f283a5f2205f93d56fbce/composer.json#L34

**Comment by spacedmonkey** [comment]
Does the dependency boot find things in the compser.lock file? Just want to make sure that removing the dependency will not break that behaviour

**Comment by swissspidy** [comment]
I think so, yeah. It should just work. Can be quickly verified though I suppose.
