### ISSUE TITLE
Bump PHP requirement in plugin

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7596]
## Task Description

Need to bump the PHP 5.6 requirement in two places:

https://github.com/google/web-stories-wp/blob/c4b2f02b98713b17962f283a5f2205f93d56fbce/web-stories.php#L17

https://github.com/google/web-stories-wp/blob/c4b2f02b98713b17962f283a5f2205f93d56fbce/web-stories.php#L50

**Comment by spacedmonkey** [comment]
There is also 

#### Remove from unit tests.

https://github.com/google/web-stories-wp/blob/c4b2f02b98713b17962f283a5f2205f93d56fbce/.github/workflows/tests-unit-php.yml#L48

https://github.com/google/web-stories-wp/blob/c4b2f02b98713b17962f283a5f2205f93d56fbce/.github/workflows/tests-unit-php.yml#L56

#### Remove it from composer


https://github.com/google/web-stories-wp/blob/c4b2f02b98713b17962f283a5f2205f93d56fbce/composer.json#L43

By changing this value in composer.json, we should also build the composer lock file and see what dependencies we can remove / update.

#### Update coding standards. 

On a similar note we can also change this line 

https://github.com/google/web-stories-wp/blob/c4b2f02b98713b17962f283a5f2205f93d56fbce/phpcs.xml.dist#L61-L62

We can then review what languages, like Scalar type declarations, Return type declarations and Group use declarations we would want to use. This is an epic in it's self.

**Comment by swissspidy** [comment]
Yup! I split these all up into different tickets, and turned #7551 into an epic.

> Remove from unit tests.

#7599 

> Remove it from composer

#7594 

> Update coding standards.

#7595 

> We can then review what languages, like Scalar type declarations, Return type declarations and Group use declarations we would want to use. This is an epic in it's self.

#7597

**Comment by swissspidy** [comment]
**Note:** Do not merge before 1.8.0
