### ISSUE TITLE
Leverage PHP 7 language features

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7597]
## Task Description

With the PHP version requirement bump we can use language features introduced in PHP 7, like scalar type declarations, return type declarations, and the null coalescing operator.

See https://www.php.net/manual/en/migration70.new-features.php for a full list of changes.

I expect the IDE can help with a lot of these optimizations.

**Comment by spacedmonkey** [comment]
Useful features. 

- Scalar type declarations
- Return type declarations
- Group use declarations

**Comment by swissspidy** [comment]
PHPStorm gives me tons of recommendations for automatically adding types and using null coalescing operators throughout the code base. That seems like a good start. Don't think grouping use statements provides much value, so we can skip that for now.

We have to be careful adding type declarations to `add_action`/`add_filter` callbacks, as it's not guaranteed that we get the expected type.

**Comment by spacedmonkey** [comment]
> PHPStorm gives me tons of recommendations for automatically adding types and using null coalescing operators throughout the code base

How do you see these recommendations?

**Comment by swissspidy** [comment]
I think the ones I get are provided by the https://plugins.jetbrains.com/plugin/7622-php-inspections-ea-extended- plugin. Can highly recommend installing it 👍

**Comment by spacedmonkey** [comment]
This might be useful as well - https://github.com/rectorphp/rector

**Comment by spacedmonkey** [comment]
After trying out refactor, here is the output. 

https://github.com/google/web-stories-wp/commit/55d3a46e07a8595d024e39464be91bed617fd4cf

**Comment by swissspidy** [comment]
Looks promising 👍 

We'll probably have to remove some of those for `add_filter`/`add_action` callbacks as mentioned above.
Also, we can add return type declarations.
