### ISSUE TITLE
Update Foreground Zoom Animation

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#7608]
## Description
We have a motion designer now! Per request of design team we are updating some of our existing animations to be better. 

## Acceptance Criteria 
- Zoom in / out FG (aka scale in/out) animation now has a timing function of `cubic-bezier(.3,0,.55,1)` and is defaulted to a duration of 2 seconds 

(Screen shot of slide deck as of May 19, 2021 12PM PST)
![Screen Shot 2021-05-19 at 12 17 37 PM](https://user-images.githubusercontent.com/10720454/118871208-33e53380-b89c-11eb-8756-d9059fbe1183.png)

https://docs.google.com/presentation/d/1Ny9o8qAiVmiQiJ4_wSIOhInBM_h2_O5p_IlfZT-xi0E/edit#slide=id.gdb3242d678_0_6

**Comment by csossi** [comment]
Verified in QA
