### ISSUE TITLE
Update Pulse Animation

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#7609]
## Description
We have a motion designer now! Per request of design team we are updating some of our existing animations to be better. 

## Acceptance Criteria 
- Pulse animation to scale from 100% to 150% then 95% and back to 100%, default time of 1.45 seconds.

(Screen shot of slide deck as of May 19, 2021 12PM PST)
![Screen Shot 2021-05-19 at 12 29 07 PM](https://user-images.githubusercontent.com/10720454/118872786-d0f49c00-b89d-11eb-9c7d-81d42ab5febc.png)

https://docs.google.com/presentation/d/1Ny9o8qAiVmiQiJ4_wSIOhInBM_h2_O5p_IlfZT-xi0E/edit#slide=id.gdb3242d678_0_21

**Comment by maxyinger** [comment]
We can't apply easing like this directly since we're constrained to beziers and keyframes. we can do our best to recreate it tho using beziers and keyframes

**Comment by csossi** [comment]
Verified in QA
