### ISSUE TITLE
Paste to Upload

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#761]
## Feature Description

As an editor I want to be able to paste a file which will also upload it to the media library. 

**[Feature Brief](https://docs.google.com/document/d/1aZH_TI_be2t5Ywyqx4jcPTPdhFGEt7xh-uLzBp2AV4A/edit#)**

Note: This is a followup to #231 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. This should behave like drag and drop from local filesystem or other browser window to Workspace:
2. After pasting, the media shows up instantly in the panel. (DONE)
3. Behind the scenes, the editor will try to upload the image and if that fails, we will show an error message. (DONE)
4. Pasting instantiates a new element with the media asset on the current page.
5. The position of the element is not dependent on anything, the Workspace is considered a single drop zone for this action, and we will automatically put the element in a sensible, visible position as topmost layer.
6. After pasting preview of the file is available
7. Once the file is uploaded switch from a preview to the fully qualified URL
8. GIFS should be able to be pasted (currently uploaded as png when pasted) See comments in #677 

## Alpha / Current state:
1. After pasting, the file name is pasted as a textbox onto the page but I also see the file showing up in the library panel
2.

**Comment by pbakaus** [comment]
Note to whoever will work on this: Needs to work for gifs (they're currently uploaded as png when pasted).

**Comment by pbakaus** [comment]
This seems like a weirdly big issue, I think a bunch of these things are done? @jauyong and @spacedmonkey can you please close and file more specific follow ups for the outstanding work?

**Comment by jauyong** [comment]
reopening this ticket to work on regression. 
@miina to check text pasting code for conflicts
See #1242

**Comment by miina** [comment]
Note: the text element thing (#1242) will get fixed within #1316 if it gets merged, however, it doesn't look like an element is/ever was created in addition to uploading -- the only existing logic I can see currently for pasting is uploading an image to the library which works, too.

Dragging an image to canvas creates an image + uploads, the same logic has not been implemented for pasting though, so the AC-s related to that have not been done. Will mark notes behind the AC-s accordingly.

**Comment by spacedmonkey** [comment]
I have a fix for preview not working. https://github.com/google/web-stories-wp/pull/1329

In my testing there are a lot of differences between browsers when it comes to pasting. These issues effect, not just us, but other web editors. In my testing, gutenberg and google docs, both struggled to handle paste events. In my tests, I made the following findings.

- MacOS Chome - Image pasting upload works. Video ( and other file format ) will paste a path to file. 
- MacOS Firefox - Pasting files doesn't nothing.
- Linux Chrome - All file formats paste path to file. 
- Linux Firefox - Pasting files doesn't nothing.

I have been about to test in windows so far. 

Also worth noting that in Chrome if file is large, say 20mb, it can take some time for a preview to appear. I know that @pbakaus wants preview straight away, but I think this is impossible, as the browser doesn't give us the file until the data is copied across. 

CC @miina as text is also pasting is also not working in Firefox, as this file.

**Comment by miina** [comment]
@spacedmonkey Looks like copying and pasting elements doesn't work in FF either. Perhaps `useClipboardHandlers` needs taking a look to see if there are adjustments to be made for FF -- independent of file pasting (which perhaps will not work), text pasting and elements pasting should work in FF -- probably deserves a separate issue though.

**Comment by spacedmonkey** [comment]
Will / should this be fixed in https://github.com/google/web-stories-wp/issues/519 @miina ?

**Comment by miina** [comment]
Bug issue created: https://github.com/google/web-stories-wp/issues/1330

Seems to be a bug and oversight of the previous implementation and not specifically related to moving to global level from canvas (#519).

**Comment by spacedmonkey** [comment]
In my tests of this PR, paste to upload did not work in Linux in my testing. It seems like the broswer / OS mixture is important here. For that reason, it is impossible to run e2e for this PR in linux, as they give different results in different OS. 

Would love to know thoughts on testing from @dvoytenko and @swissspidy

**Comment by spacedmonkey** [comment]
I just retested the PR against the browsers I have to hand. 

- MacOS Chrome, edge, and safari. Paste upload works. Firefox also works, but not as snappy. 
- Linux Chrome, path to file is pasted, creating a text element. Firefox pasting does nothing. 

At a guest, I would say, that firefox only allow for text to be pasted if focused on an editable field. 

I am going to do some more testing on a window machine.

**Comment by miina** [comment]
Hmm, paste to upload in FF doesn't seem to work for me on MacOS -- there's a separate issue for looking into that though: #1330 -- I guess it's related for all pasting, even though the issue mentions only text and elements pasting.

**Comment by dvoytenko** [comment]
> In my tests of this PR, paste to upload did not work in Linux in my testing. It seems like the broswer / OS mixture is important here. For that reason, it is impossible to run e2e for this PR in linux, as they give different results in different OS.
> 
> Would love to know thoughts on testing from @dvoytenko and @swissspidy

From the call it sounds like we may have to fallback to synthetic events. Alternatively, we could explore SauceLabs to target platforms that do work for tests.

**Comment by spacedmonkey** [comment]
In my testing so far. I got the following results. 

- Mac OS - Safari, Chrome, Edge ( for Mac ) and Firefox. Paste to upload works. 
- Windows 10. 
   - Edge ( Editor doesn't load ).
   - Chrome - Nothing happens on paste. 
   - Firefox - Nothing happens on Paste. Paste not on option in context menu. 
- Linux. 
   - Chrome - Create a text block with path to file.
   - Firefox - Nothing happens on paste. 

I am awaiting details on ChromeOS.

I think the above is the best we are going to do, as these limitation are on OS level :(

**Comment by dvoytenko** [comment]
@spacedmonkey quick follow up: Windows 10 + Chrome/Firefox: does the file paste work with docs.google.com?
