### ISSUE TITLE
Update Rotation Animation

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#7610]
## Description
We have a motion designer now! Per request of design team we are updating some of our existing animations to be better. 

## Acceptance Criteria 
- Rotation animation to update from -135degress to 45 degrees, 1 second long, while position update takes .87 seconds. 

(Screen shot of slide deck as of May 19, 2021 12PM PST)
![Screen Shot 2021-05-19 at 12 31 33 PM](https://user-images.githubusercontent.com/10720454/118873066-2761da80-b89e-11eb-84d5-74e2454a7e3e.png)

https://docs.google.com/presentation/d/1Ny9o8qAiVmiQiJ4_wSIOhInBM_h2_O5p_IlfZT-xi0E/edit#slide=id.gdb3242d678_0_21

**Comment by maxyinger** [comment]
We can't apply easing like this directly since we're constrained to beziers and keyframes. we can do our best to recreate it tho using beziers and keyframes

**Comment by maxyinger** [comment]
Just commenting on here. We can't set the final angle at all. Breaks the first rule of our animations:
> Animations final position must be the static position the user set

That being said, gonna make the amount it rotates `135deg + 45deg = 180deg`  so it travels the same amount of rotation as what was requested

**Comment by csossi** [comment]
Verified in QA
