### ISSUE TITLE
Animations: Switch zoom-in/out behavior

### ISSUE THREAD

**Issue by maxyinger** [GoogleForCreators/web-stories-wp#7611]
Currently in the editor the thumbnail in the effect chooser shows the correct behavior for zoom in and zoom out. However in the applied animation this behavior is actually reversed.

This ticket is to update `src/animation/effects/zoom/index.js` to reverse the zoom from values depending on zoom direction passed to it.

**Comment by csossi** [comment]
Verified in QA
