### ISSUE TITLE
Rotation handle is wrongly placed for non-zero rotation

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#7616]
## Bug Description

Rotation handle is wrongly placed for non-zero rotation.

## Expected Behaviour

* Rotation handle should stick to the element frame.

## Steps to Reproduce

1. Add an image to a page
2. Rotate it
3. Observe that the rotation handle is suddenly not connected to the element bug moving away from it.

Issue observed both locally and confirmed on QA environment.

## Screenshots

![rotate-handle-bug](https://user-images.githubusercontent.com/637548/118932716-5451d400-b916-11eb-86e7-c6fd23eadb63.gif)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
