### ISSUE TITLE
Quick Actions: expand collapsed panel when a quick action is triggered

### ISSUE THREAD

**Issue by samwhale** [GoogleForCreators/web-stories-wp#7624]
## Feature Description

If a quick action is triggered that focuses a panel in the design pane that is collapsed - it should expand the panel.

## Alternatives Considered

n/a

## Additional Context

![example](https://user-images.githubusercontent.com/22185279/119024735-a61f4c00-b960-11eb-9352-d6428339434a.gif)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by maxyinger** [comment]
Taken care of in https://github.com/google/web-stories-wp/pull/7629
