### ISSUE TITLE
Delete Element By Dragging Off Page

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#763]
## Feature Description

As an editor I want items that I drag off the page and onto the workspace to be deleted

**[UX](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=2832%3A208)**

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. When elements are dragged halfway off teh page ,the elements are all clipped in the workspace (see UX link)
2. Once elements are dragged off the work space and the user "let's go" the elements are deleted.

**Comment by miina** [comment]
FI: There's a duplicate: https://github.com/google/web-stories-wp/issues/445
