### ISSUE TITLE
Yoast SEO meta boxes do not work in Editor

### ISSUE THREAD

**Issue by mxbclang** [GoogleForCreators/web-stories-wp#7630]
## Bug Description

<a href="https://wordpress.org/support/topic/breadcrumb-error-in-google-search-console-2/">As reported by a user in the forums</a>, when the Third-Party Meta Boxes icon at the bottom of the Editor screen is clicked, the Yoast SEO tab displays, but clicking on any of the options does not do anything.

## Expected Behaviour

Selecting items in the Yoast SEO metabox loads the appropriate options.

## Steps to Reproduce

1. Install the Yoast SEO plugin
2. Go to Stories > My Stories
3. Create a new Story or select an existing one and open in Editor
4. Click the Third-Party Meta Boxes icon
5. Click on any of the options

## Screenshots

Video: https://jmp.sh/n9VASHz

You can see that the metaboxes for the AIO SEO plugin are working, but the Yoast ones are not.

## Additional Context

- Plugin Version: 1.7.1
- WordPress Version: 5.7.2
- Operating System: Big Sur 11.3.1 
- Browser: Chrome v90

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
This is a known issue with Yoast SEO and I just pinged them about it again the other day. It's because none of their CSS & JS is loaded in the editor. See https://github.com/Yoast/wordpress-seo/pull/16298

The user might want to report this to Yoast so they can re-assess the priority on that one.

**Comment by swissspidy** [comment]
Styles & scripts should load correctly with Yoast SEO 16.5 (due out next week).
