### ISSUE TITLE
Pre-Publish Checklist: Video Optimization displays thumbnail for missing poster

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7635]
## Bug Description

In the checklist, the video optimization section shows the video's poster image in a thumbnail. But sometimes videos don't have posters. In this case, the image is broken and the alt text is displayed.

https://github.com/google/web-stories-wp/blob/8a3a115b3fe868f8ef9412511c42ee05d7bf6bd0/assets/src/edit-story/app/prepublish/components/videoOptimization.js#L71-L75

## Expected Behaviour

No thumbnail should be displayed

## Screenshots

![pre-publish-checklist poster bug](https://user-images.githubusercontent.com/841956/119059308-5710ff80-b9d0-11eb-8fe0-ad0b7a3f8757.png)

## Additional Context

- Plugin Version: 1.7.2
- WordPress Version: 5.7
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Not a high priority because videos rarely don't have a poster, but would be good to address nonetheless.

**Comment by csossi** [comment]
Verified in QA
