### ISSUE TITLE
Refactor SVG page rendering

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#7636]
## Feature Description

Currently, the SVG page rendering has a few areas for improvement:

- The inner-most rendered element shares a lot of logic and structure with the innermost element of the display ditto. This should be generalized (in particular for the media elements and the text element).
- The sticker element needs an SVG renderer
- Part of the SVG renderer is currently located inside the carousel in the page preview component. This should be extracted from there to a new generalized place, so the component can be reused elsewhere in the editor.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Closing as this is not relevant anymore due to SVG rendering not bringing the expected performance improvements (alternatives to be explored within other PRs).
