### ISSUE TITLE
Use SVG rendering for text sets

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#7637]
## Feature Description

Extend SVG rendering (once generalized in #7636) to text sets.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Within this issue let's also make sure that the text elements within the Text Sets would use the [inline styles on the elements](https://github.com/google/web-stories-wp/pull/7719/files#diff-752f30efcca90415ec1b1f705d7712899cf8111724f6b69b704dd2548bd30ac2R102-R125) to avoid the creation of excess classes by Styled Components.

**Comment by miina** [comment]
Closing this for now as SVG rendering doesn't seem to bring significant performance issues and we'll explore rendering images instead. New issues to be created shortly.
