### ISSUE TITLE
Issue when reordering layers

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#764]
## Feature Description

Was able to move a layer to a new position, but unable to move it back to original position
Vid - https://drive.google.com/file/d/16MtsHg3dfmrGAFhvM29zYUqoBJKoXqQW/view
Taken from Claudio in #584 

I did some additional testing and there seem to be issues with reordering layers. 
I am never able to drag a layer to the very top layer making it the new top. 
Other times I just can drag a layer to another spot, but I can't see a pattern as I've tried multiple variations of positions and element types. 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
This is related to the issues introduced by #693 and will probably be fixed by rework of this done by @wassgha. If not, we'll deal with it after @wassgha's rework of the background element (because of the extra element, the layer order is off-by-one causing issues in reordering).

**Comment by wassgha** [comment]
Will be fixed in #709
