### ISSUE TITLE
Dashboard - Gridview - UI / Page Foundation

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#765]
## Feature Description

As an author I want to see stories in an elegant way

**[Feature Brief](https://docs.google.com/document/d/1Xs4uOZ3KCNlTMdjDT6q7cvTUpA1xk-kzrnVLQALltQk/edit#heading=h.oj6z3quhazn5)**

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. Build the layout for the main element of the page which is a grid view of all stories that users of the current site have created.
2.  A ‘card’ includes the following elements:
      1. Preview of cover page (this should be the focus)
    2. Story title
    3. 🔗 Views (only visible when Site Kit is installed)
    4. Author
    5. Modified date
    6. State (only visible when in “Draft” or “Template State)
3. The author is able to filter the stories
4. The author is able to sort the stories by:
    1. Last modified
    1. Name
    1. Date Created
    1. Last opened
    1. created by

Note: Tapping the card previews the selected story in a new window (or modal on Desktop). A secondary tappable affordance on the card opens the current story for editing in the story editor.
This will be handled in #766

**Comment by carloskelly13** [comment]
Completed with #926 #995
