### ISSUE TITLE
Dashboard - Gridview - Preview & Edit Story

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#766]
## Feature Description

As an author I'd like to be able to preview a story

**[Feature Brief](https://docs.google.com/document/d/1Xs4uOZ3KCNlTMdjDT6q7cvTUpA1xk-kzrnVLQALltQk/edit#heading=h.oj6z3quhazn5)**
**[Design](https://www.figma.com/file/hUTw97921an0e3uU28JoDn/Dashboard?node-id=1936%3A78603)**

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. After tapping on a card in the dashboard, the selected story is previewed in a new window (or modal on Desktop). 
2. A secondary tappable affordance on the card opens the current story for editing in the story editor.
3. On hover these CTAs are shown (see Figma and animation prototypes)

**Comment by jauyong** [comment]
@carlos-kelly is ok to have AC2 in here or would it be better to split these up?

**Comment by carloskelly13** [comment]
I think `the selected story is previewed in a new window (or modal on Desktop).` is big enough to be its own story.

**Comment by carloskelly13** [comment]
The Edit Story portion is completed with #995
