### ISSUE TITLE
Dashboard - Gridview - Contextual Menu

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#767]
## Feature Description

As an editor I want an easy way to access all the options for managing stories

**[Feature Brief](https://docs.google.com/document/d/1Xs4uOZ3KCNlTMdjDT6q7cvTUpA1xk-kzrnVLQALltQk/edit#heading=h.oj6z3quhazn5)**
**[Design](https://www.figma.com/file/hUTw97921an0e3uU28JoDn/Dashboard?node-id=1936%3A78603)**

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. While hovering below the card, show the more icon to open the contextual menu
2. The menu should have the following (see design for separation):
   3. Open in editor
   3. Preview
   3. See #768 for Rename, Duplicate, Delete
   3. Create Template (Copies the current story into a new template, and navigates to the template section.)

**Comment by carloskelly13** [comment]
From Sam w.r.t. the position of the menu: If so we should spawn the menu on the top or bottom depending on the available space.
