### ISSUE TITLE
Analytics: Update message when Site Kit is installed

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#7672]
## Feature Description

As of https://github.com/google/web-stories-wp/issues/6124, the message around Adsense is changed when when adsense is the sitekit plugin is enabled. But @swissspidy brings up a valid point in 
https://github.com/google/web-stories-wp/pull/7622#issuecomment-845401577 that the messaging / styling should also change with google analytics as well. 

For reference, here is new styling for adsense messaging. 
<img src="https://user-images.githubusercontent.com/237508/119018371-e9df7900-b993-11eb-9865-86a076ef30d3.png" />

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Apologies for not making it clear in #6124, ideally we fix this in one go.

Moving to Sprint Backlog accordingly.

**Comment by spacedmonkey** [comment]
> Apologies for not making it clear in #6124, ideally we fix this in one go.

No it was clear, but it should not be part that ticket. See https://github.com/google/web-stories-wp/pull/7622#issuecomment-845926338

**Comment by csossi** [comment]
Verified in QA
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/8be3b2b8-52aa-4f6c-9999-bd411788c652)
