### ISSUE TITLE
Force support for mp4/webm in multisite. 

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#7677]
## Feature Description

Pre WordPress 4.0, if you had a single site you converted into multisite you would have a very limited list of allow file types. As of https://github.com/WordPress/wordpress-develop/commit/1c947d9ef1e5ede68e5f5c860cb8cd20b2054ec3 this list was expanded. But there maybe older multisite, that do no support uploading mp4, webm and other filter types. Not being able to upload mp4 is pretty limiting for the editor. Consider forcing support for these file types by filter the allowed list of these content types. 

At the very lease, we could/should document this as an issue with uploading videos / unsupported image types in multisite. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
Worth noting, I found this one while looking at my person multisite. Setup in WordPress 3.7. 

![Screenshot 2021-05-21 at 17 25 16](https://user-images.githubusercontent.com/237508/119169195-a2232500-ba59-11eb-9c4e-17fad5e0c261.png)

**Comment by swissspidy** [comment]
Would this mean filtering `site_option_upload_filetypes` like the SVG class does?

**Comment by spacedmonkey** [comment]
Worth noting that we do this for vtt files. 

https://github.com/google/web-stories-wp/blob/a5c6ec86e0852ab343b57737847589bf75781e75/includes/Media/Video_Captions.php#L44-L62

The question here, is we changing the expected behaviour here. We have to question, is the mp4 file extension missing here because network admin do not know about this setting or have network admin gone out of their way to limit it because of some reason, like file size, security or otherwise.  

Maybe we need a network settings page...

**Comment by spacedmonkey** [comment]
Related [#53167](https://core.trac.wordpress.org/ticket/53167)
