### ISSUE TITLE
Dashboard - Gridview - Contextual Menu - Rename, Duplicate & Delete

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#768]
## Feature Description

**[Feature Brief](https://docs.google.com/document/d/1Xs4uOZ3KCNlTMdjDT6q7cvTUpA1xk-kzrnVLQALltQk/edit#heading=h.oj6z3quhazn5)**
**[Design](https://www.figma.com/file/hUTw97921an0e3uU28JoDn/Dashboard?node-id=1936%3A78603)**
This is a followup to #767 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. Add Rename to the menu
2. Rename allows the author to edit the title of a story without leaving the page.
3. Add Duplicate to the menu
4. Duplicate duplicates the current story, suffixes the title with “(copy)”, and automatically puts the duplicate into draft mode.
5. Add Delete to the menu
6. Delete produces a warning, and upon confirmation of said warning deletes the story.

**Comment by BrittanyIRL** [comment]
I think this could be broken up into three separate stories - one for each action.
