### ISSUE TITLE
Dashboard - Gridview - Contextual Menu - Template

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#769]
## Feature Description

As an editor I want an easy way to access all the options for managing stories

**[Feature Brief](https://docs.google.com/document/d/1Xs4uOZ3KCNlTMdjDT6q7cvTUpA1xk-kzrnVLQALltQk/edit#heading=h.oj6z3quhazn5)**
**[Design](https://www.figma.com/file/hUTw97921an0e3uU28JoDn/Dashboard?node-id=1936%3A78603)**
This is a followup to #767 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
1. Add "Create Template" to the menu
2. "Create Template" Copies the current story into a new template, and navigates to the template section. See #780

**Comment by carlos-kelly** [comment]
This should probably be blocked since there are no template APIs yet, we can add the menu UI, but it will not be functional.

**Comment by BrittanyIRL** [comment]
Updated context menu from recording just for reference

![Screen Shot 2020-04-30 at 1 05 43 PM](https://user-images.githubusercontent.com/10720454/80754115-5797d900-8ae3-11ea-8847-e5f8885251b2.png)
