### ISSUE TITLE
Editor: Cannot publish story 'immediately'

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7692]
## Bug Description

In the WordPress block editor, one can start creating a blog post, save regularly, and once you publish, it will use that moment's current date as the publish date.

In the story editor, once you start creating a story, that moment's date is set as the publish date. So even if you actually publish your story a week later, the week before will be the publish date.

This is wrong, and causes lots of stories to be published with the incorrect date.

**Possible solution**

I assume this can be easily fixed by not setting the publish date in the editor and keep it as `null`. So once you publish, WP will simply use the current date.

## Expected Behaviour

Users should be able to publish "immediately".

## Steps to Reproduce

1. Create a new story, save it
2. Publish it 10 minutes later
3. Notice the publish date is the date from 10 minutes earlier

## Screenshots

"Publish Immediately" in Gutenberg:

<img width="313" alt="Screenshot 2021-05-24 at 13 38 01" src="https://user-images.githubusercontent.com/841956/119345152-c9b40080-bc98-11eb-88d0-38a0b5960d40.png">

Publish date in the story editor:

<img width="483" alt="Screenshot 2021-05-24 at 13 37 19" src="https://user-images.githubusercontent.com/841956/119345156-cae52d80-bc98-11eb-9818-2ab9190b8660.png">

## Additional Context

- Plugin Version: 1.7.2
- WordPress Version: 5.7
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

- When updating a draft story and it doesn't have a published date yet, keep the publish date as `null`. Display "Immediately" as the placeholder instead of a date.
- When the story gets published either by changing the status to `Public` in the Status & Visibility panel (and then saving the story) or by clicking the "Publish" button, update the Publish date to the current date.
- Once the publish date exists, use the set published date (no matter the following status changes) unless the user manually changes the date.
- Note: if the user manually sets the date instead of `Immediately` for a draft, that date will be used as the publish date.
- Bonus: As in the WordPress post editor, add a "Reset" button to the calendar in case of `draft` that would reset the date to `null` and display `Immediately` again.

**Comment by swissspidy** [comment]
Assigning to Prometheus but perhaps it's more of a WP thing.

cc @miina

**Comment by miina** [comment]
> So once you publish, WP will simply use the current date.

@swissspidy What if the user will mark the story temporarily a draft and then publishes it again? Should it always use the original publish date (unless explicitly changed by the user to a later date)? Thoughts?

**Comment by swissspidy** [comment]
> > So once you publish, WP will simply use the current date.
> 
> @swissspidy What if the user will mark the story temporarily a draft and then publishes it again? Should it always use the original publish date (unless explicitly changed by the user to a later date)? Thoughts?

Yes. Once the user publishes the story, the publish date will be set and left untouched until the user changes it manually.

Other scenarios can be compared to how it works in Gutenberg, as that is the experience our users are familiar with and expecting.

**Comment by miina** [comment]
Hm, in this case, should we display "Immediately" or something similar instead of a specific date (unless it's already set), as in WP? Otherwise, displaying the date is not really accurate for a draft.

Edit: the calendar would need a "Reset" button then, too.

**Comment by miina** [comment]
Or is this exactly what you've meant with this issue? :)

**Comment by miina** [comment]
To consider when implementing: a difference in the editor vs in Gutenberg -- in the editor, the user can publish the post by changing the status to `publish` from the Status & visibility panel, too. Then the "Update" button needs to be clicked to save the changed status.

**Comment by csossi** [comment]
Verified in QA
