### ISSUE TITLE
Media: Show duration while uploading files

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#7693]
## Feature Description

While uploading a file from local using drag and drop, it should be possible to get length / duration of the video to preview. 

#### Example code:

```js
const getVideoResource = async (file) => {
  const fileName = getFileName(file);
  const mimeType = file.type;

  let length = 0;
  let lengthFormatted = '';

  const reader = await createFileReader(file);

  const src = createBlob(new Blob([reader.result], { type: mimeType }));

  const videoEl = document.createElement('video');
  const canPlayVideo = '' !== videoEl.canPlayType(mimeType);
  if (canPlayVideo) {
    videoEl.src = src;
    videoEl.preload = 'metadata';
    videoEl.addEventListener('loadedmetadata',  () => {
      length = Math.ceil(videoEl.duration);
      let seconds = length % 60;
      const minutes = parseInt(length / 60);
      if (0 === seconds) {
        seconds = '00';
      }
      lengthFormatted = `${minutes}:${seconds}`;
    });
  }
  const frame = await getFirstFrameOfVideo(src);

  const poster = createBlob(frame);
  const { width, height } = await getImageDimensions(poster);

  return createLocalResource({
    type: 'video',
    mimeType,
    src: canPlayVideo ? src : '',
    width,
    height,
    poster,
    length,
    lengthFormatted,
    alt: fileName,
    title: fileName,
  });
};
```

#### In action. 
<img width="231" alt="Screenshot 2021-05-24 at 13 13 13" src="https://user-images.githubusercontent.com/237508/119346221-d8e38000-bc91-11eb-9ac5-46fb9a163de1.png">

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Great idea!

On that note, is that upload indicator broken? Shouldn't it be at the bottom of the thumbnail instead of going right through the duration text?

**Comment by swissspidy** [comment]
Setting estimate at 1 since it seems you basically wrote this already. Sounds good? Then we can even include it in this sprint.

If we want to fix the styling in this ticket as well, we can increase it. Otherwise that can be a new ticket.

**Comment by spacedmonkey** [comment]
> On that note, is that upload indicator broken? Shouldn't it be at the bottom of the thumbnail instead of going right through the duration text?

I don't think it is has ever been an issue before. We haven't had duration while uploading. But you are right, it does look odd / broken. We could easily move to the bottom. 

Again, I mocked this up locally in about 5 minutes and it worked a charm.

**Comment by spacedmonkey** [comment]
<img width="1884" alt="Screenshot 2021-05-24 at 13 41 11" src="https://user-images.githubusercontent.com/237508/119349328-f4508a00-bc95-11eb-8d18-ebe621ebcaf2.png">
 
Putting the progress bar at the bottom looks weird as the progress bar does not have rounded corners but moving it down 6px seems to work well.

**Comment by spacedmonkey** [comment]
Worth noting, having the duration like this, is specially useful in transcoding. It denotes that it is a video while it is uploading/transcoding. This can take 3/5 minutes, so it makes super clear.

**Comment by csossi** [comment]
Verified in QA
