### ISSUE TITLE
Activate Site Kit directly from dashboard screen

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#7700]
## Feature Description

In the dashboard screen there is a call to action to install / activate the sitekit plugin. This currently is a link to another page where users can activate or install the sitekit plugin. 

In WordPress 5.5, ( https://github.com/WordPress/wordpress-develop/commit/b2cc1dfd70663178786a2b1ea56e6f2084fccb41#diff-33c9246b7bd721893d411c0f6ef248e0b2611963cbf252808a1a4b17873589af ), there was a plugin REST API controller added. This controller would allow for ( if the user has the correct permissions ) a request to be made to the REST API and sitekit plugin installed / activated. This would mean, that user would not have to leave the dashboard interface to do these actions. 

It would require WordPress 5.5, something that is noted in https://github.com/google/web-stories-wp/issues/7598

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
I remember talking about this before.

In theory this would not need the REST API enhancement to work. The Shiny Updates script in WordPress would allow for the same already today. But of course it's easier via the API.

UX would be important here, as it's important that the user sees the Site Kit onboarding wizard, so they would need to go to the plugins page for that.

**Comment by spacedmonkey** [comment]
Still think we could use this api to make the experience cleaner.

**Comment by swissspidy** [comment]
Not saying otherwise. Just calling out that the onboarding is important.
