### ISSUE TITLE
Update AMP Plugin & Toolbox to 2.1.3 / 0.6.0

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7713]
## Task Description

Tracking ticket for one of our upcoming releases.

Once a new version of the AMP plugin is out, we need to update the dependencies accordingly.

This time, we can even remove and improve some code. See https://github.com/ampproject/amp-wp/pull/6303 and specifically https://github.com/ampproject/amp-wp/pull/6303/files/094d354ddf5eb2e440b17df60f3ec9d95aac8df4#r638534057.

**Comment by swissspidy** [comment]
The AMP plugin 2.1.3 release is tentatively slated for next week.

It would be great to include it in the 1.8.0 release.

Same goes for the AMP Toolbox package.

**Comment by spacedmonkey** [comment]
amp-toolbox-php was updated to 0.6.0. 
https://github.com/ampproject/amp-toolbox-php/releases/tag/v0.6.0

**Comment by swissspidy** [comment]
We'll need to update our AMP optimizer configuration to replace `PreloadHeroImage` with `OptimizeHeroImages`:

https://github.com/google/web-stories-wp/blob/71e71281fd73c42e956578f5d188bd13be8fa0a5/includes/AMP/Optimization.php#L136-L148

See https://github.com/ampproject/amp-wp/blob/6f1d2c26cba313cf70dcc36bdffee6dda78cecf1/src/Optimizer/AmpWPConfiguration.php#L54-L67

We don't need `OptimizeAmpBind`.

Should update this comment accordingly:

https://github.com/google/web-stories-wp/blob/71e71281fd73c42e956578f5d188bd13be8fa0a5/includes/AMP/Optimization.php#L120
