### ISSUE TITLE
Dashboard - List View - Filters

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#772]
## Feature Description

As an author I want to see and filter stories in an elegant way

**[Feature Brief](https://docs.google.com/document/d/1Xs4uOZ3KCNlTMdjDT6q7cvTUpA1xk-kzrnVLQALltQk/edit#heading=h.mgdx02j3ibol)**
**[Design](https://www.figma.com/file/hUTw97921an0e3uU28JoDn/Dashboard?node-id=1853%3A93070)** Note as of Mar 25, Sam will be adding a "simple" view to figma

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
1. Stories can be filtered by an "All Stories" pill. 
2. All Stories is the default filter.
3. Stories can be filtered by a "Shows all stories" pill
4. Stories can be filtered by a "Drafts" pill
5. For the "Drafts" filter, only shows stories that are in draft state (unpublished).
6. Stories can be filtered by a "Published Stories" pill
7.  For the "Published Stories" filter, Only shows stories that have been published.
8. The user is able to sort by:
    1. Title
    1. Date created
    1. Last modified (default)
    1. Last opened
    1. Created by (Sorts stories by author. Always puts the author’s own stories first.)
    1. 🔗 Most Popular
    1. Only available when Site Kit is installed. Sorts stories by number of unique visits in the last 30 days.

Note: The My templates filter has been omitted for now

**Comment by jauyong** [comment]
@carlos-kelly notes from our meeting today:

1. Updated Sorting options / UX. Note AZ vs ZA for Author and Categories columns. 
![image](https://user-images.githubusercontent.com/5874851/79599029-d8ea7700-80b2-11ea-9ff9-40ed1fe0b14f.png)
![image](https://user-images.githubusercontent.com/5874851/79599046-dd169480-80b2-11ea-9096-6a6e0639710e.png)
2. Identifier is placed on the right for Publish items: 
![image](https://user-images.githubusercontent.com/5874851/79599373-5ca46380-80b3-11ea-883e-1bd5d6dfa3a2.png)

**Comment by BrittanyIRL** [comment]
Some of these filters are custom - https://github.com/google/web-stories-wp/issues/1195
