### ISSUE TITLE
VideoPress Deep Integration

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7723]
## Feature Description

Now that we have better support for VideoPress videos in the media library, we could consider going even further.

Right now, when one drops a video into the editor it is optimized locally and then uploaded to WordPress.

If using VideoPress, one might want to skip the local optimization and upload straight to VideoPress.

This requires some discovery to see whether this is actually feasible.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
For reference we could look into 
 - [gutenberg-video-upload.js](https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/modules/videopress/js/gutenberg-video-upload.js) - Gutenberg intergration. 
 - [videopress-plupload.js](https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/modules/videopress/js/videopress-plupload.js) - Plupload intergation. 
 
We should disable transcoding / cross origin isolation if videopress is in use. We will like need to add a PR to jetpack for this integration. I am hoping it is matter of enqueue these two scripts in the right place.
