### ISSUE TITLE
Fix contrast checking for SVG rendering

### ISSUE THREAD

**Issue by embarks** [GoogleForCreators/web-stories-wp#7724]
# Bug Description
Unexpected behavior seen while working on [SVG rendering](https://app.zenhub.com/workspaces/web-stories-5e94d3aced449034e1e9b226/issues/google/web-stories-wp/7519) in the pre-publish checklist. Contrast checking seems to be showing contrast issues when it shouldn't. (see screenshot)

# Expected Behaviour
The contrast check should only appear when there is insufficient contrast between the foreground text and background color.

# Steps to Reproduce

[After SVG rendering is being used in the editor] 
1. Start a new story
2. Add a background color to the page (e.g. #397AED) and some text (e.g. #fff)
3. Open the pre publish checklist
4. There are too many recommendations for fixing the contrast between the text and the background.

# Screenshots
![image.png](https://images.zenhubusercontent.com/5f7b469a8022e02e0b23aea1/c48a85e1-9e3e-4c95-a09c-a7e2cdc5559b)

Additional Context

    Plugin Version: 1.1.0
    Operating System: macOS
    Browser: Chrome 86

**Comment by csossi** [comment]
Verified in QA
