### ISSUE TITLE
Improving poster and logo CTA by bringing them to the forefront.

### ISSUE THREAD

**Issue by shishirm** [GoogleForCreators/web-stories-wp#7729]
## Feature Description

The poster and logo within a Story is an important artifact for various surfaces. However, at the moment it is fairly easy for any creator to skip adding a poster or logo into their Story. While we don't want to enforce Stories having posters and logos, the resulting Stories are definitely lacking and we should make it hard for creators to not set these.

Could we make the CTA for setting posters and logos be more front and center, beyond just the checklist. This would mean repeated warnings and explanations for why these are important to be set.
Could we also provide previews for how the Story would appear on various surfaces. This has the added advantage of avoiding burned in text in posters and creators will be able to see how these will look bad when surfaced

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
cc @o-fernandez 

> Could we also provide previews for how the Story would appear on various surfaces. This has the added advantage of avoiding burned in text in posters and creators will be able to see how these will look bad when surfaced

This is already being tracked in #5593.

**Comment by o-fernandez** [comment]
> Could we make the CTA for setting posters and logos be more front and center, beyond just the checklist. 

We can explore options, but my preference is to fix the checklist in a way that people don't ignore the priority items in there.

**Comment by swissspidy** [comment]
Closing in favor of #10115
