### ISSUE TITLE
Telemetry: Excessive number of events fired

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7738]
## Bug Description

Looks like usage of `useEffect()` for tracking events causes lots of tracking events being fired

## Expected Behaviour

Tracking events should only be fired upon user interaction.

## Steps to Reproduce

1. Open editor
2. See a bunch of events being fired

## Screenshots

Just on example:

<img width="450" alt="Screenshot 2021-05-26 at 11 21 05" src="https://user-images.githubusercontent.com/841956/119636947-6ef3e380-be15-11eb-8ea1-441ab4f6f5e3.png">

## Additional Context

- Plugin Version: 1.7.2
- WordPress Version: 5.7
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
@swissspidy - i think we actually fixed the search issue. happy to see about fixing any other ones.

**Comment by swissspidy** [comment]
@BrittanyIRL That would be great!

Any telemetry usage within `useEffect()` is potentially problematic as events can be fired multiple times and even on initial page load without any user action
