### ISSUE TITLE
Migrate to use  `<amp-story-auto-analytics>`

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7739]
## Feature Description

Going forward we might want to exclusively use [`<amp-story-auto-analytics>`](https://amp.dev/documentation/components/amp-story-auto-analytics/).

Perhaps we want to use it in conjunction with `amp-analytics` during a migration period.

**Considerations**

What about Site Kit? Site Kit currently prints an `<amp-analytics>` tag on stories. Should they also switch? Needs coordination.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Pinging @felixarntz for awareness. We might want to update Site Kit to print `<amp-story-auto-analytics>` instead of `<amp-story-analytics>`.

**Comment by felixarntz** [comment]
@swissspidy Please keep me in the loop on whether this should be done or not. I've created a tracking issue on Site Kit side. What I'm mostly curious about is whether that new component has any drawbacks in using - for example the `amp-analytics` component allows for more flexibility in the events setup, even though it is missing the useful defaults that the new one provides.

**Comment by swissspidy** [comment]
> @swissspidy Please keep me in the loop on whether this should be done or not. I've created a tracking issue on Site Kit side. What I'm mostly curious about is whether that new component has any drawbacks in using - for example the `amp-analytics` component allows for more flexibility in the events setup, even though it is missing the useful defaults that the new one provides.

One would not be able to customize the events anymore, but with auto analytics there's a guaranteed set of events configured out of the box. Which makes it easier to develop stories-specific analytics dashboards and the like, as we 100% know what data is being collected.

**Comment by felixarntz** [comment]
> One would not be able to customize the events anymore, but with auto analytics there's a guaranteed set of events configured out of the box. Which makes it easier to develop stories-specific analytics dashboards and the like, as we 100% what data is being collected.

Hmm that sounds like a trade-off I'm not sure about what's better for Site Kit. I wonder whether it would be possible for the `amp-story-auto-analytics` component to still support an (optional) JSON configuration for _additional_ configuration and events. As it currently stands, I don't see enough of a benefit (since Site Kit & Web Stories take care of the whole event setup anyway) from what I know so far.

**Comment by swissspidy** [comment]
Suggestion by @choumx in sprint planning meeting just now:

Use `amp-story-auto-analytics` for new users freshly installing the plugin or setting up GA for the first time, and keep pre-existing users on the "old" amp-analytics configuration if they have GA set up already.

For pre-existing users, show a note on the settings page about them using the "old" configuration including documentation on how to migrate to the new configuration (location TBD) and offer CTA to switch to the new way (UX TBD).

Needs some UX and clarity on where that documentation resides, what it should cover, who writes it, etc.

**Comment by bmattb** [comment]
@aaskedall flagging that the UX for this is needed for next Monday sprint start.

**Comment by aaskedall** [comment]
![image](https://user-images.githubusercontent.com/4030811/133105805-2223dae5-8f7f-4066-b3f2-01f32806748d.png)

"An improved version of analytics is now available. Learn how to migrate to our recommended version. "

Added some additional copy and an alert badge. Can the user make this change right inline or do they have to make it elsewhere and this settings view will update to reflect that?

**Comment by swissspidy** [comment]
> Can the user make this change right inline or do they have to make it elsewhere and this settings view will update to reflect that?

Yeah that could all be done inline. As simple as clicking on a "Migrate" button that saves their choice.

**Comment by dreamofabear** [comment]
For copy I'd suggest:
> [ Migrate ] An improved analytics configuration is now available (learn more)."

Avoids the word "version" which may be conflated with version of Google Analytics itself.

**Comment by swissspidy** [comment]
I created #9045 to implement this behind a feature flag while UX is being finalized.

@aaskedall Could you perhaps provide an updated mock that takes into account our feedback above? There should be some button to perform that migration. Clicking the button could simply display a success snackbar message.

**Comment by aaskedall** [comment]
Here is an updated mock. Just need to some language for the snackbar. How instant is this change or is it a comeback in a few minutes?

![image](https://user-images.githubusercontent.com/4030811/133660892-2ca22811-455c-4417-acb4-94b1c26ca45c.png)

**Comment by swissspidy** [comment]
> Just need to some language for the snackbar.

I'd have gone with something like "Successfully migrated analytics configuration" or "Settings saved"

> How instant is this change or is it a comeback in a few minutes?

It's instant

**Comment by swissspidy** [comment]
@aaskedall Oh, btw, we already have some text below the "Google Analytics" label. So the migration text would need to be displayed below.

![Screenshot 2021-09-16 at 22 20 36](https://user-images.githubusercontent.com/841956/133680431-e92a821e-d986-40b7-a982-d4662fac16f2.png)

**Comment by swissspidy** [comment]
Also, perhaps it should be a secondary button and not a primary one?

**Comment by swissspidy** [comment]
@aaskedall @choumx See #9050 for a demo of how it currently works.

**Comment by swissspidy** [comment]
#9050 is merged now. PTAL again at the demo there.

Documentation is the biggest remaining point besides design.
