### ISSUE TITLE
Safari: Text edit mode selection not possible

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#7745]
## Bug Description
It looks like the text edit mode in Safari has broken meanwhile. Selecting part of the text doesn't seem to be possible, the cursor does not show up at all. 
Additionally, in display mode, the cursor is also different compared to other browsers (`text` in Safari vs `default` in others)

## Expected Behaviour
The user should be able to select part of the text in edit mode and style it.

## Steps to Reproduce
1. Open the editor in Safari
2. Add text
3. Try to select part of the text and mark it bold.

## Screenshots
![sfari](https://user-images.githubusercontent.com/3294597/119664182-5f839300-be33-11eb-98b0-028e2e47123e.gif)

## Additional Context

- Browser: Safari Version 14.0 (14610.1.28.1.10) (will test with the latest version shortly, too)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
From investigation so far:

Apparently `doc.caretRangeFromPoint` is not working properly anymore and is for some reason returning incorrect element for `range.offsetNode`. This results in the final offset being larger number than the length of the text causing unexpected behaviour. Since `caretRangeFromPoint` is deprecated anyway and discouraged from using then we could fix this issue by just removing the usage of it and setting the cursor always to position `0` when entering edit mode.

I'll first search for alternatives for `doc.caretRangeFromPoint` though -- perhaps there's a workaround for Safari to still being able to set the cursor to where the user clicked.

**Comment by swissspidy** [comment]
> Apparently `doc.caretRangeFromPoint` is not working properly anymore and is for some reason returning incorrect element for `range.offsetNode`. This results in the final offset being larger number than the length of the text causing unexpected behaviour. Since `caretRangeFromPoint` is deprecated anyway and discouraged from using then we could fix this issue by just removing the usage of it and setting the cursor always to position `0` when entering edit mode.

Is it deprecated? All information I could find says that it's non-standard. [MDN recommends](https://developer.mozilla.org/en-US/docs/Web/API/Document/caretRangeFromPoint#javascript) `document.caretRangeFromPoint` with a fallback to `document.caretPositionFromPoint`

**Comment by miina** [comment]
> Is it deprecated?

Hm, my IDE shows it's deprecated:
<img width="442" alt="Screenshot 2021-05-31 at 17 57 55" src="https://user-images.githubusercontent.com/3294597/120211591-647c8400-c231-11eb-9a85-c30ff2ad56b0.png">
<img width="433" alt="Screenshot 2021-05-31 at 17 57 29" src="https://user-images.githubusercontent.com/3294597/120211595-65adb100-c231-11eb-80e2-5911bd7c1333.png">

In either case, it doesn't seem to be working correctly so it might be better to remove its usage to avoid unexpected results for users. I'll investigate this a bit more to see if there are any alternatives though.

**Comment by csossi** [comment]
Verified in QA
