### ISSUE TITLE
Solve for existing publisher logos and story posters with incorrect dimensions/aspect ratios

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#7746]
## Feature Description

Related to #7744, if a user already has publisher logos set or story poster images that don't follow our guidelines, we should find the appropriate place to (1) warn them and (2) make it easy for them to fix the issue either by cropping the existing asset or (if too small) requiring them to change it. 

This also includes figuring out how the Settings page, which allows for publisher logo setting, may need to accommodate for this. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Closing for now as this hasn't come up anymore since we've added cropping
