### ISSUE TITLE
Quick Actions: Should collapse unused panels on click

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#7750]
(Tentatively the last small detail of quick action menus that was missing from general implementation) 

When users click on a quick menu button and the action is to go to a certain input on a panel it should collapse panels that are not related to that action if there are any open on that panel. For instance, if I click on 'animation' in a quick action menu and i have border and corner radius panels expanded, those 2 panels should collapse as the animation panel expands. 

## Acceptance criteria 
- above functionality
- tests added

**Comment by BrittanyIRL** [comment]
@miina  I'm hoping we can get your perspective on this. 

Design has asked in the new quick action menus (https://www.figma.com/file/1YM3jA9h4QGc4xLdyaXIJS/Stories-Sprint-1.7?node-id=7347%3A60536) that when a user clicks on one of these actions that take the user to a specific input in one of the panels that any other panels that were expanded are now collapsed (and the one that is navigated to is expanded). 

This feels like a breach in how the panel has been designed and the rules surrounding its logic since panel collapse/expansion is stored in localStorage and honored for the user to keep things consistent. 

If you agree, I'll go to design and see if we can scrap this part of the requirements - we have the same functionality implemented in the prepublish checklist right now without the panels collapsing.

Let me know what ya think or if you have questions!

**Comment by miina** [comment]
@BrittanyIRL Thanks for bringing this up, I definitely agree! Since we're storing the information (expanded/collapsed) to keep the panels how the user left these then this requirement seems like a conflicting behaviour with the general logic of how the panels work.

**Comment by BrittanyIRL** [comment]
Thanks for confirming, @miina! I'll see if design's ok with this.

**Comment by BrittanyIRL** [comment]
Per discussion with design team, we're not going to do this 🙃  closing.
