### ISSUE TITLE
Animation: Update BG Zoom to Zoom Delta of 50% (Exploration)

### ISSUE THREAD

**Issue by maxyinger** [GoogleForCreators/web-stories-wp#7752]
### Brief
Background images can be statically placed anywhere between 100% -> 300% scale. The goal of this ticket is to only make it travel 50% in either direction with regard to zoom in/out.

### Expected Behavior

**Fixed Delta**
Here are some scenarios the behavior should follow:
-> BG Image is 100% scale: Zoom out equates to animating from 150% to 100%
-> BG Image is 200% scale: Zoom in equates to animating from 150% to 200%
-> BG Image is 300% scale: Zoom in equates to animating from 250% to 300%

**Duration and Ease**
Easing and duration of BG Zoom should still follow ones outlined in these slides:
https://docs.google.com/presentation/d/1Ny9o8qAiVmiQiJ4_wSIOhInBM_h2_O5p_IlfZT-xi0E/edit#slide=id.gdc9155b87c_1_0

Defaults:
- `duration: 2000ms`
- `ease: cubic-bezier(.3, 0, .55 ,1)`

### Edge Cases
What do we want to happen if the background image is set to `110%` and the user chooses `ZOOM IN` ?

Options:
- We could just make the background animate from `100% -> 110%` (would look small)
- We could disable `ZOOM IN` as an option unless the image's scale is greater than `150%`
- Other Ideas or options for behavior here?

**Comment by csossi** [comment]
Verified in QA
