### ISSUE TITLE
Contributor cannot submit story for review

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7762]
## Bug Description

Users with the Contributor role cannot publish content themselves in WordPress. Instead, they have to submit content for review.

## Expected Behaviour

Contributors should be able to submit a story for review

## Steps to Reproduce

1. Log in as contributor user
2. Try to publish a story / submit it for review

## Screenshots

Behavior in Gutenberg:

![Screenshot 2021-05-27 at 19 23 13](https://user-images.githubusercontent.com/841956/119870005-2fb2b900-bf21-11eb-8e80-90457dde739d.png)
![Screenshot 2021-05-27 at 19 23 06](https://user-images.githubusercontent.com/841956/119870007-304b4f80-bf21-11eb-81e9-27eb06755971.png)

In the story editor:

![Screenshot 2021-05-27 at 19 23 35](https://user-images.githubusercontent.com/841956/119870000-2f1a2280-bf21-11eb-994a-c0fe7fec08d0.png)

## Additional Context

- Plugin Version: 1.7
- WordPress Version: 5.7
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
I believe that @miina worked on this originally. CC because she maybe able to add context.

**Comment by miina** [comment]
For context:
There was some discussion about it previously with a decision [to just allow saving it as a draft](https://github.com/google/web-stories-wp/issues/1390#issuecomment-634028242) and [some suggestions from Sam](https://github.com/google/web-stories-wp/issues/1390#issuecomment-642461507) on displaying messages when the user doesn't have enough permissions.

**Comment by swissspidy** [comment]
Thanks for the context 👍  This way I found Jonny's #1975 PR were he basically added this support.

I feel like it's time to revisit this.

**Comment by miina** [comment]
Sounds good, this will need UX for the submitting for review part. And perhaps confirming if this should work exactly as in WP/Gutenberg.

**Comment by swissspidy** [comment]
There was just another feature request for this from a user.

Let's use the same UX flow as in Gutenberg for now.

**Comment by csossi** [comment]
Verified in QA
