### ISSUE TITLE
amp-onerror AMP validation issues

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7763]
## Bug Description

**Context:**

https://github.com/ampproject/amphtml/issues/22543
https://github.com/ampproject/amphtml/pull/34531
https://github.com/ampproject/amp-toolbox-php/pull/211

AMP upstream has very recently added `amp-onerror` validation, which causes validation errors on sites with transformed AMP that don't use ESM. _That's us._

Example site: https://testsite.cmsdevrel.com/web-stories/thailand-copy/

There have been multiple user reports in the forums so far about the AMP validation errors this causes.

**Possible Solutions**

1. Re-enable ESM usage (#7649)  
2. Update `AmpBoilerplateErrorHandler` transformer as per `https://github.com/ampproject/amphtml/pull/34531#issuecomment-849760418 / https://github.com/ampproject/amp-toolbox-php/pull/211
3. Disable `AmpBoilerplateErrorHandler` transformer altogether

## Expected Behaviour

No AMP validation errors.

## Steps to Reproduce

1. Validate any web story when using v1.7.2 of the plugin  
  Example: https://testsite.cmsdevrel.com/web-stories/thailand-copy/

## Additional Context

- Plugin Version: 1.7.2
- WordPress Version: 5.7
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
FYI @choumx

**Comment by karinclimber** [comment]
We have also now seen this same problem on 150 sites.

**Comment by zdenys** [comment]
We are seeing this on WordPress.com sites too. 

In one case specifically, on attempting to validate a page with https://search.google.com/test/amp there is a validation error `The mandatory text inside tag 'script amp-onerror' is missing or incorrect.`. The related HTML is:

```
<script amp-onerror="">document.querySelector("script[src*='/v0.js']").onerror=function(){document.querySelector('style[amp-boilerplate]').textContent=''}</script><style amp-boilerplate="">body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate="">body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
```

**Comment by LuckynaSan** [comment]
@karinclimber @zdenys Thank you both for your reports. While we are actively looking into how to best handle this issue, you can <a href="https://jmp.sh/CUY4Khj" rel="noopener" target="_blank">download</a> and <a href="https://gist.github.com/swissspidy/3d8503785ca452b82ad21e7c30bc1ac2" rel="noopener" target="_blank">install this mini-plugin</a> as a temporary workaround. We appreciate your patience ask to please standby for further updates.

**Comment by karinclimber** [comment]
It looks like that does fix it - I tested it on one site. But we will wait for you guys to get things sorted on your end before installing it and then later uninstalling it on 150 sites ;) Thanks for working on it!

**Comment by joannathenewsvoice** [comment]
This workaround helped to see the errors valid in the tool but every time when google hits the page from the webmaster the page is first considered as “invalid” web story and we have to fetch manually and test live its a valid page.

– Google first attempt is crawl the page is invalid so the pages don't consider as valid amp or amp story-
– if we fetch manually then it comes a valid but how many we fetch every day and we cant control what pages google is considering them as valid.

check the screenshots here.

Google first time hit – https://jmp.sh/U8ucb4t invalid web-story
Manually testing the page – https://jmp.sh/LwUrrlh

the work around is for plugin but not for google.

All the stories that we are publishing are considered as invalid and going waste.

– Joanna

**Comment by mobiliodevelopment** [comment]
Quick fix change script to:
`<script amp-onerror>[].slice.call(document.querySelectorAll("script[src*='/v0.js'],script[src*='/v0.mjs']")).forEach(function(s){s.onerror=function(){document.querySelector('style[amp-boilerplate]').textContent=''}})</script>
`
And this will fix error ASAP.

Peter

**Comment by westonruter** [comment]
This is an issue with the AMP Validator, not with the Web Stories plugin _per se_. See https://github.com/ampproject/amphtml/issues/22543#issuecomment-849734114. The AMP Validator should be fixed in the next day or so. In the mean time, patching the plugin per above or disabling `amp-onerror` via https://github.com/google/web-stories-wp/issues/7763#issuecomment-850445823 will prevent the error.

**Comment by mobiliodevelopment** [comment]
@westonruter Thank you!

**Comment by swissspidy** [comment]
As per https://github.com/ampproject/amphtml/issues/22543#issuecomment-852315041, this has already been fixed on https://validator.amp.dev. It should be fixed in Search Console as well by the end of the week.

So you can safely keep the mini-plugin active and then remove it again next week.

**Comment by swissspidy** [comment]
Closing now as this has been fixed in Search Console.

Feel free to delete the mini-plugin accordingly on your site.
