### ISSUE TITLE
Dashboard - Template Detail View Preview Widget

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#777]
## Feature Description

This is a follow up to #775 
**[Feature Brief](https://docs.google.com/document/d/1Xs4uOZ3KCNlTMdjDT6q7cvTUpA1xk-kzrnVLQALltQk/edit#heading=h.c9wym3xrjpkp)**
**[Design](https://www.figma.com/file/hUTw97921an0e3uU28JoDn/Dashboard?node-id=1777%3A27)**

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
1. The author is able to preview every page of the template (with animations/video playback)

**Comment by jauyong** [comment]
@pbakaus does this preview each page(by clicking on each page) of the story within the template detail view page or does it open a new tab / modal so the entire template is previewed as a whole story?

**Comment by pbakaus** [comment]
the former, clicking on a thumbnail in that view will highlight it in the big thumbnail, and "play" the page.
