### ISSUE TITLE
Video: Icons always using the default poster image 

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#7779]
## Bug Description
Currently, the icons (such as in the Layer panel, in background media, in the Filter panel) are using the default poster image of a video.

If the user changes the poster image, the default poster is still used.

## Expected Behaviour
Custom poster image should be used for icons everywhere if set.

## Steps to Reproduce
1. Add a video and set custom poster image
2. Add video as a background.
3. See the Filter, background media, and Layer panels -- still using the previous.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Why would we _not_ want to show the poster the user has chosen? Seems very confusing.

**Comment by miina** [comment]
> Why would we not want to show the poster the user has chosen? Seems very confusing.

IDK. Maybe since the default poster is part of the video and might more accurately display how the video would look like with a filter, for example, whereas the custom poster can be anything.
Assumed it was a bug but wasn't certain if it was purposefully left like this. Will move the issue forward since you also find it confusing.

**Comment by csossi** [comment]
Verified in QA
