### ISSUE TITLE
Dashboard - Bookmark Template Functionality

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#779]
## Feature Description

As an editor I want to be able to bookmark templates

**[Feature Brief (Being Written)](https://docs.google.com/document/d/1Xs4uOZ3KCNlTMdjDT6q7cvTUpA1xk-kzrnVLQALltQk/edit#heading=h.89cwdir5ijn5)**

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
1. Write the JS function in in order to bookmark a template
2. This is executed on the Template Grid View #774 and the Template Detail View #775 
3. Setup the data structure to be stored somewhere in WP (contact @swissspidy or @spacedmonkey for assistance)

**Comment by bmattb** [comment]
@carlos-kelly to confirm the 1.2 assignment for prioritization
