### ISSUE TITLE
Potential Regression: Page Template Dialog Missing

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#7798]
## Bug Description

It appears that the dialog that confirms that a user wants to switch page templates if the page is not empty isn't getting triggered. I'm guessing something got lost when adding in custom page templates?

## Expected Behaviour

If there's anything on a page and a page template is selected it should show a dialog for confirmation before swapping contents. 

## Steps to Reproduce

https://user-images.githubusercontent.com/10720454/120397178-ac141600-c2ec-11eb-8d8b-08683e62ebd7.mp4

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@BrittanyIRL This is actually [per spec now](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=7082%3A531898) -- note that the content of the Page is not being swapped but a new Page with the content is added instead.

![Screenshot 2021-06-02 at 10 12 51](https://user-images.githubusercontent.com/3294597/120439436-cf89a000-c382-11eb-988e-41b99d5415d2.png)

**Comment by BrittanyIRL** [comment]
ok awesome! I wasn't sure.
