### ISSUE TITLE
Library elements clickable area depends on zoom level

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#7802]
## Bug Description
When inserting elements from the library, the clickable area is currently influenced by the zoom level. If the page is very small, the clickable area is very small, too, making it hard to add an element from the library at all. 

When the zoom level is high, the clickable area is too large.

## Steps to Reproduce
1. Resize your window so that the Page would be tiny
2. Open the Shapes library
3. Click in the middle of the shape to add it
4. See nothing happening

## Screenshots
![library](https://user-images.githubusercontent.com/3294597/120485957-e0eba000-c3b4-11eb-9d40-9c6ddd381eeb.gif)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
Clicking anywhere on an element in the library should add a new element to a Page.

**Comment by csossi** [comment]
Verified in QA
