### ISSUE TITLE
Links: Don't emit description and icon attributes with empty values

### ISSUE THREAD

**Issue by shishirm** [GoogleForCreators/web-stories-wp#7805]
## Bug Description

When a link in the Story does not have any description or brand icon specified, the plugin still generates empty attributes for them `data-tooltip-icon=""` `data-tooltip-text=""` instead of omitting them altogether. As these are required to be completed when present, it causes the Stories to become Invalid AMP

## Expected Behaviour

Omit generating empty data-tooltip-icon and data-tooltip-text when those link fields are not entered by the user.

## Steps to Reproduce

1. Add a link to any Story page
2. Leave the description and brand icon empty
3. Run through AMP validator

## Screenshots

Error generated is here:

Missing URL for attribute 'data-tooltip-icon' in tag '$reference_point'.
line 13, column 2863
  
The tag 'a', a child tag of 'AMP-STORY-GRID-LAYER animate-in', does not satisfy the reference point 'AMP-STORY-GRID-LAYER animate-in'.

## Additional Context

- Plugin Version: Latest
- WordPress Version: Latest
- Operating System: All
- Browser: All

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
