### ISSUE TITLE
Links in Help Center do not work

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7818]
## Bug Description

(External) links in the help center are not working. Probably something messing with pointer events.

## Expected Behaviour

Links should work

## Steps to Reproduce

1. Open help center
2. Click on a link
3. See that it doesn't do anything.

## Screenshots

![image (2)](https://user-images.githubusercontent.com/841956/120693601-7b2d1000-c4a9-11eb-9815-636ed0c68d9f.png)

## Additional Context

- Plugin Version: 1.7.2
- WordPress Version: 5.7
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
@embarks or @littlemilkstudio if either of you have time tomorrow to do this it would be awesome!

**Comment by maxyinger** [comment]
cha. I'd be happy to look into it tomorrow

**Comment by csossi** [comment]
Verified in QA
