### ISSUE TITLE
Animations: Set Initial Opacity 0 for fly in

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#7819]
Per feedback from Huge we want to set the initial opacity of the  fly in element to 0 so that it is not a jarring transition. Essentially to avoi[d the following complaints: ](https://docs.google.com/document/d/1me4GMGIRNoBZ-qULNi9HRDf2FE-2pGaci6A86iWEJfM/edit?ts=60affbe4)

> Fly in Animation on title: The Title is visible before the animation. The position before that animation is not outside the page.

> Page 1> Fly in Animation on title: The Title is visible before the animation. 

https://images.zenhubusercontent.com/235435637/baa4c8ec-59bf-4b4b-9e59-460623debd3b/fg_flyin_animations.mp4

TODO: Marian to add demo story to staging

**Comment by BrittanyIRL** [comment]
I don't think we're going to get a demo story in staging on this one, @littlemilkstudio - do you feel like we have enough to go on to update this as is?

**Comment by BrittanyIRL** [comment]
Pretty sure this got fixed! @littlemilkstudio can you confirm and close?

**Comment by maxyinger** [comment]
just looked at this. looks like it's not in there right now. I think I added it to the scale-in animation recently which is causing the confusion. will hop on this now

**Comment by csossi** [comment]
Verified in QA
