### ISSUE TITLE
Drop target action should be a single undo/redo history item

### ISSUE THREAD

**Issue by wassgha** [GoogleForCreators/web-stories-wp#782]
## Bug Description

Drop targets are done on two steps: Changing the element's content then deleting the original dropped element. This needs to be combined into one action for undo/redo purposes.

Possible duplicate See #793 

## Expected Behaviour

Undoing a drop should restore the masked element and also restore the original element. Right now it restores the original element but doesn't restore the masked element's contents until a second undo is issued

## Steps to Reproduce
1. Create a star shape
2. Add an image to the canvas
3. Drag the image into the star's drop target
4. The star should now show the image as its contents
5. Press the "undo" button
6. The image comes back into the canvas but the star shape still has the image as its contents

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment]
Removing from the board, no longer required for alpha

**Comment by jauyong** [comment]
Set as p1 per the above
