### ISSUE TITLE
Video Optimization: MOV placeholder element position wrong

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7839]
## Bug Description

When dropping an MOV file into the editor, the video dimensions are not yet known. So we display a placeholder element in the center of the canvas.

However, this initial positioning seems to have broken recently, as in, it is not centered anymore. Perhaps with the introduction of zooming?

## Expected Behaviour

The placeholder element should not be displayed off-canvas.

The position should match the one from #7766.

## Steps to Reproduce

1. Drop MOV file into editor
2. See how the placeholder is positioned partly off-canvas

## Screenshots

Position off canvas:

![Screenshot 2021-06-07 at 11 55 02](https://user-images.githubusercontent.com/841956/120997858-d865e180-c787-11eb-9988-f71998cabcec.png)

In #6541 it looked like this:

![Screenshot 2021-06-07 at 12 00 49](https://user-images.githubusercontent.com/841956/120998112-0ea36100-c788-11eb-978d-4f0fc35a1a56.png)

## Additional Context

- Plugin Version: 1.7
- WordPress Version: 5.7
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

* Placeholder element not positioned off-canvas anymore
* Position should match the UX from #7766

## Implementation Brief

* This probably needs updating in `useUploadWithPreview.js`

**Comment by csossi** [comment]
Verified in QA
