### ISSUE TITLE
Enable Media library video optimization by default

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7842]
## Feature Description

Once #7480 / #7766 are complete, we'd like to enable that feature by default for 1.9.0.

This should be passed by UX first to ensure we're on the right track.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
This should **not** be merged before 1.8.0

**Comment by csossi** [comment]
Verified in QA
