### ISSUE TITLE
Convert Publisher PHP trait to class

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#7846]
## Feature Description

The Publisher trait is used in 5 classes. Converting this to a class should be pretty simple. See https://github.com/google/web-stories-wp/issues/7844 for more detail. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Let's also remove any `get_publisher_logo_placeholder()` usage while at it.

**Comment by spacedmonkey** [comment]
>Let's also remove any get_publisher_logo_placeholder() usage while at it.

Seems like it is being used in 3 places 😕 . I thought we had stopped using it..

**Comment by swissspidy** [comment]
Ah, you're right.

It's used in `get_publisher_logo()` for a filter, but it can be removed from that filter entirely.

It's also used in the AMP sanitization, but let's keep it there for the moment. This is for sanitizing older stories with the wrong logo.

So let's only remove it from the `web_stories_publisher_logo` filter for now

**Comment by swissspidy** [comment]
Made obsolete by #8946
