### ISSUE TITLE
Don't generate square and landscape poster images

### ISSUE THREAD

**Issue by shishirm** [GoogleForCreators/web-stories-wp#7849]
## Bug Description

Currently, we automatically generate a landscape and square version of the poster from the portrait version that a user uploads. This can often result in incorrectly sized posters that are flagged as such in AMP Linter.

The ask is to only generate the landscape and square versions of the poster if they can adhere to the recommended size guidelines (1:1 for poster, 4:3 for landscape). If not, then do not generate the incorrectly sized posters for landscape and square and instead in the future provide options to the user to set these themselves.

## Expected Behaviour

Only generate the landscape and square versions of the poster if they can adhere to the recommended size guidelines.

## Steps to Reproduce

Add a poster to the Web Story and look at the auto-generated landscape and square versions of the same.

- Plugin Version: 1.7.2
- WordPress Version: 5.7.2
- Operating System: All
- Browser: All

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

* Remove square + landscape poster image sizes and their usage everywhere (incl.  AMP sanitization)

**Comment by spacedmonkey** [comment]
So we should remove the poster image size? Or do we need to remove the file if it generates incorrect?

**Comment by swissspidy** [comment]
We'd like to completely remove the image sizes, which means eliminating a lot of code:

https://github.com/google/web-stories-wp/blob/0971a88fed37cf13a10f93c73946600f0d7d5672/includes/Media/Media.php#L54-L80

https://github.com/google/web-stories-wp/blob/0971a88fed37cf13a10f93c73946600f0d7d5672/includes/Media/Media.php#L196-L210

https://github.com/google/web-stories-wp/blob/a31592468d3145c266a2577692f53a0aeb028a10/includes/Model/Story.php#L78-L89

https://github.com/google/web-stories-wp/blob/a31592468d3145c266a2577692f53a0aeb028a10/includes/Model/Story.php#L146-L147

https://github.com/google/web-stories-wp/blob/a31592468d3145c266a2577692f53a0aeb028a10/includes/Model/Story.php#L206-L226

https://github.com/google/web-stories-wp/blob/a31592468d3145c266a2577692f53a0aeb028a10/includes/Renderer/Story/HTML.php#L160-L173

https://github.com/google/web-stories-wp/blob/b801d437b955ce9fa150b1a0433182812d92fbe5/includes/Integrations/AMP.php#L138-L142

Things get interesting with the circle carousel block, which currently uses the square image size for convenience:

https://github.com/google/web-stories-wp/blob/d46c0fcb65efc2269d07dcdb53855802c60798c3/includes/Renderer/Stories/Renderer.php#L542-L543

That renderer should use the portrait image instead; centering it within the circle.

**Comment by spacedmonkey** [comment]
@swissspidy I am not sure I understand why these image sizes are being removed.

**Comment by swissspidy** [comment]
Because more often than  not they lead to scenarios where the posters are incorrectly sized. We want to focus solely on the portrait poster image going forward.
