### ISSUE TITLE
Mark Coverr videos as having no sound

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7865]
## Bug Description

Currently, the pre-publish checklist shows a message for a video with missing captions.

Videos from Coverr inserted via the 3P Media tab don't have any sound though, so the message is very misleading in that case.

Just like we want to enable creators to mark videos as having no sound (see #7730), we should videos from Coverr as having no sound, and don't show the pre-publish checklist message in that case.

## Expected Behaviour

Videos from Coverr should not trigger this pre-publish check message.

## Steps to Reproduce

1. Insert video from 3P media tab
2. Go to pre-publish checklist
3. See message

## Screenshots

![Screenshot 2021-06-08 at 15 53 11](https://user-images.githubusercontent.com/841956/121216161-f06d5c00-c880-11eb-9124-2191eed2668f.png)

## Additional Context

- Plugin Version: 1.7.2
- WordPress Version: 5.7
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

* No PPC message for missing captions on Coverr videos.
* Coverr resources are marked as muted.
* Migration exists for pre-existing video resources in stories

## Implementation Brief

* Add new `isMuted` parameter to `createResource`, defaulting to `false`.  
  Update `Resource` JSDoc typedef accordingly.
* Update `getVideoResourceFromMedia3p()` to set `isMuted` to `true`.
* Add a new data migration similar to `mark3pVideoAsOptimized` to set the `isMuted` attribute to `false` for all existing videos, but to `true` for all existing Coverr resources.
* Update `videoElementMissingCaptions` to not return a message if `element.resource.isMuted` is `true`

**Comment by swissspidy** [comment]
Another suggestion from #7371 is to use a `hasAudio` flag instead of a `isMuted` flag. That seems reasonable.

**Comment by swissspidy** [comment]
Same thing will be needed for any videos in templates

**Comment by swissspidy** [comment]
Created: #7885

**Comment by swissspidy** [comment]
Here's how it could be implemented in the output & display layer (ignore the design panel changes): https://github.com/rtCamp/web-stories-ad-tool/pull/44

**Comment by csossi** [comment]
Verified in QA
