### ISSUE TITLE
Quick Actions: `Change Background Color` quick action not opening panel if collapsed

### ISSUE THREAD

**Issue by samwhale** [GoogleForCreators/web-stories-wp#7866]
## Bug Description

`Change Background Color` quick action is not opening the page background panel when the panel is collapsed. Other quick actions do collapse other panels.

## Expected Behaviour

Clicking the quick action should collapse the page background panel.

## Steps to Reproduce

1. Editor -> background element selected
2. Collapse the page background panel
3. Click the first quick action

## Screenshots

![page-background](https://user-images.githubusercontent.com/22185279/121220366-c6487980-c841-11eb-8880-42b4e20f111c.gif)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
