### ISSUE TITLE
Bug: Look into image srcset/sizes optimization and see if it can play better with animations

### ISSUE THREAD

**Issue by maxyinger** [GoogleForCreators/web-stories-wp#7867]
Marian shared these two screencasts of the image behaving weirdly (jumpy/flickery) in an animation. I believe this is AMP doing some `srcset` & `sizes` optimization and we're just seeing progressively better quality images load when they're first rendered.

This is an exploratory task to see if there's anyway we can mitigate this on our end, that being said it may ultimately just be a byproduct of the approach amp uses to optimize images (which is a good approach and is necessary).

Anyway, gonna set this as a 3 pointer to time box this as it has the potential to be a rabbit hole of a task.

https://images.zenhubusercontent.com/235435637/da2abbd9-05cb-401b-9ce2-a8c244bd03d5/fg_scalein_batch2_story4_page01.mov

https://images.zenhubusercontent.com/235435637/8fe3cdd6-b241-4a0a-87ba-d5435b6a0832/fg_scalein_batch2_story3_page07.mov

**Comment by BrittanyIRL** [comment]
@csossi - there's testing directions in the PR :)

**Comment by swissspidy** [comment]
Which plugin version was this tested with?

> I believe this is AMP doing some srcset & sizes optimization and we're just seeing progressively better quality images load when they're first rendered.

Worth noting that we _just_ implemented some **significant** changes to `sizes` logic in #8099 that fixed a long-standing issue with blurry images when viewing stories.
Most certainly this will have an affect on this behavior reported here as well.

So if this was tested under v1.8.0, I highly recommend testing again, as it might have been fixed already by this change.

**Comment by csossi** [comment]
Verified in QA
