### ISSUE TITLE
Live updating permalink in case of ugly permalinks

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#787]
## Feature Description

Follow up from #667 

In the permalink panel, live-updating the link is currently not implemented if the user has not enabled pretty permalinks on the website.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

- The URL in the Permalink panel is live updated independent of the permalink settings.

**Comment by miina** [comment]
Hm, should the Permalink input be disabled perhaps if pretty permalinks are not enabled?

**Comment by swissspidy** [comment]
What does Gutenberg do in that case?

**Comment by miina** [comment]
Same -- or actually, doesn't display the input at all, just the URL.

**Comment by swissspidy** [comment]
Just displaying the URL as well sounds reasonable 👍

**Comment by csossi** [comment]
Verified in QA
