### ISSUE TITLE
Document Panel: Calendar partly hidden for narrow screens

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#788]
## Bug Description
Follow up from #667 

On narrow screens, the calendar displayed for the Publish date is partly not visible.

## Expected Behaviour

The calendar should be fully visible on narrow screens.

## Screenshots

<img width="349" alt="Screenshot 2020-03-26 at 11 17 21" src="https://user-images.githubusercontent.com/3294597/77635789-63780480-6f53-11ea-82d3-22c3ea77b7e4.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
The main issue here seems to be the inline-styled width:
<img width="459" alt="Screenshot 2020-03-31 at 19 28 22" src="https://user-images.githubusercontent.com/3294597/78056746-e64ef400-7385-11ea-8681-af118549bd23.png">

Not sure how easy it is to change that, perhaps we should float the calendar instead (like the color picker)? Not sure it would look the best pressed into a narrow sidebar either. Thoughts?
cc @swissspidy @samitron7 @pbakaus

**Comment by pbakaus** [comment]
the calendar should definitely float.

**Comment by dvoytenko** [comment]
If we want to use calendar as a color picker, then I think sidebar (/cc @barklund) should fit very well for that.

**Comment by miina** [comment]
Yep, using sidebar was the idea. Will rework the calendar to float, this means the calendar won't be inside the panel as in Figma, however, that doesn't seem to be the final design anyway.

**Comment by dvoytenko** [comment]
It looks like, depending on the desired UX, we either have to place calendar into the sidebar, or hoist it into `<body>` element with `position:fixed`.

**Comment by miina** [comment]
PR here: #935

>It looks like, depending on the desired UX, we either have to place calendar into the sidebar, or hoist it into <body> element with position:fixed.

Perhaps it should be `fixed` for the color picker as well, or generally for the floating Sidebar content.

**Comment by dvoytenko** [comment]
@pbakaus @samitron7 could you pls clarify which elements should show up in a sidebar or which should float inline?

**Comment by miina** [comment]
For reference: Here is how it's in the PR to fix the "not fitting into sidebar" issue:
<img width="595" alt="Screenshot 2020-04-01 at 17 50 09" src="https://user-images.githubusercontent.com/3294597/78158259-4b1b5480-7441-11ea-8728-437c9a5fc049.png">

**Comment by miina** [comment]
@dvoytenko If I understood correctly from Paul then [the recommendation](https://github.com/google/web-stories-wp/issues/788#issuecomment-606838462) for the calendar was to float and it should be OK using the Sidebar.

> Paul: the calendar should definitely float.

**Comment by dvoytenko** [comment]
I'm afraid @pbakaus's statement of "floating" means to float under the element's chevron, not in the sidebar (from some other contexts). That's why I'm asking him to clarify.

**Comment by pbakaus** [comment]
1. by 'float' I meant hoisted to be body (never clipped by other elements).
2. The datepicker should imo appear directly under the element. Same as with other form controls (dropdowns etc).

@samitron7 to chime in if she has other thoughts.

**Comment by miina** [comment]
@pbakaus In case of a narrow sidebar, would it then be ok if the calendar would be directly under the element but partly be in the workspace area (since it doesn't fit in case of narrow sidebar)?

@dvoytenko AFAIK the layers are all hiding the overflow so it might not be so straightforward to have an element belonging to a sidebar but partly being visible in the workspace as well? I might be mistaken, of course, haven't looked Into it, thoughts?

**Comment by pbakaus** [comment]
> @pbakaus In case of a narrow sidebar, would it then be ok if the calendar would be directly under the element but partly be in the workspace area (since it doesn't fit in case of narrow sidebar)?

Yes, absolutely.

> 
> @dvoytenko AFAIK the layers are all hiding the overflow so it might not be so straightforward to have an element belonging to a sidebar but partly being visible in the workspace as well? I might be mistaken, of course, haven't looked Into it, thoughts?

Yeah, that was my point :) The browser does the same thing: If you use a native select, the actual dropdown that appears when you click on the select is *not* logically placed next to the element in the z-layer stack, it's above almost anything else at OS level. Thus, we should almost always append these types of controls to the body.

**Comment by dvoytenko** [comment]
> AFAIK the layers are all hiding the overflow so it might not be so straightforward to have an element belonging to a sidebar but partly being visible in the workspace as well? I might be mistaken, of course, haven't looked Into it, thoughts?

Yeah. Per Paul's note, I think we just have to portal the dropdown body as a fixed element into the document's body. The inline placement is two fragile - we are dependent on every single element up the DOM tree. This is very similar to react-modal I believe.

**Comment by dvoytenko** [comment]
To note - I think probably all dropdowns (except for sidebar) should work the same way, so there's a clear component composition that's needed for this.
