### ISSUE TITLE
Mark videos in templates as having no sound

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7885]
## Bug Description

Currently, the pre-publish checklist shows a message for a video with missing captions.

Videos in our templates don't have any sound though, so the message is very misleading in that case.

Just like we want to enable creators to mark videos as having no sound (see #7730), we should mark those videos as having no sound, and don't show the pre-publish checklist message in that case.

## Expected Behaviour

Videos in templates should not trigger this pre-publish check message.

## Steps to Reproduce

1. Create a new story from a template which contains videos
2. Go to pre-publish checklist
3. See message

## Screenshots

https://google-webstories.rt.gw/web-stories/batch-1-story-2-travel-1/

![Screenshot 2021-06-09 at 10 19 36](https://user-images.githubusercontent.com/841956/121319136-33c0dc80-c90c-11eb-807d-9056b645a63c.png)

## Additional Context

- Plugin Version: 1.7.2
- WordPress Version: 5.7
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

* No PPC message for missing captions on videos in templates.
* Template video resources are marked as muted.

## Implementation Brief

* Add new `isMuted` parameter to `createResource`, defaulting to `false`.  
  Update `Resource` JSDoc typedef accordingly.
* Add `isMuted` parameter to all templates' videos (not all videos are muted!
* Add test to check for `isMuted` not being `undefined` in `packages/templates/src/test/raw.js`
* Update `videoElementMissingCaptions` to not return a message if `element.resource.isMuted` is `true` (pre-publish checklist)

**Comment by swissspidy** [comment]
Here's how it could be implemented in the output & display layer (ignore the design panel changes): https://github.com/rtCamp/web-stories-ad-tool/pull/44

**Comment by csossi** [comment]
Verified in QA
