### ISSUE TITLE
Custom calendar implementation

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#789]
## Feature Description

Follow up from #667 

Currently, the calendar implementation is based on Gutenberg's (WP default) calendar component. This, however, could be replaced with a custom implementation for the following advantages:
- Replacing using `moment` library to significantly reduce the build size.
- Custom design more fitting with the editor generally
- Using the Apache License as elsewhere in code.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. A "basic" react date picker is chosen and implemented
2. The date picker should be style-able
3. Consider the licensing when choosing the date picker

Styling to be done in #1391 based on this [design](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=6113%3A618)

A follow up ticket will be created for advanced date picker functionality / design

A custom calendar solution is implemented providing the advantages listed above

**Comment by miina** [comment]
@jauyong FI: This is a follow-up issue from #667

**Comment by pbakaus** [comment]
This is also critical if we want to unbundle the editor from WordPress. Not critical for the alpha, but very important after.

**Comment by swissspidy** [comment]
A few packages I found in a quick search:

https://www.npmjs.com/package/@material-ui/pickers
https://www.npmjs.com/package/react-datepicker
https://www.npmjs.com/package/react-datetime-picker (has tons of similar packages for just calendar, etc.)

**Comment by miina** [comment]
Perhaps I missed the discussion last grooming being absent, but doesn't it make sense to already implement the styling as well if we'll replace it?
Or is the idea to currently just replace it with whichever most suitable style comes by default and worry about the style later?
Or should we maintain the current style?

**Comment by pbakaus** [comment]
My point was that replacing the current picker is urgent (P0), customizing the styles is not (P2 or so), which is why I requested the split. Of course, if it is a matter of minutes, makes sense to do it in one PR.

**Comment by miina** [comment]
Alright, makes sense. I suppose in this case it's just OK to use the default(-ish) style that comes with the library that is chosen.

Will remove the UX Needed and add it to #1391 instead.

**Comment by miina** [comment]
Have been testing out various options today and it looks like either https://www.npmjs.com/package/react-datepicker or https://www.npmjs.com/package/react-datetime-picker could work well in terms of customization, package size, developer activity and dependencies (or lack of these, e.g. not requiring moment as the current implementation does).

One note for both options: the 12/24 hours format depends on the locale, it doesn't seem to be possible to configure that directly as WP is currently doing.

However, both of these options allow using only the date-picker. We could keep the current timepicker logic which supports 12/24h based on WP settings, and modify it:
1. Replace using `moment`
2. Remove the separate date picking option (since that already comes from the calendar anyway)
<img width="269" alt="Screenshot 2020-05-11 at 16 42 01" src="https://user-images.githubusercontent.com/3294597/81574728-7b420580-93a6-11ea-8fad-6b59c0acaaa3.png">


OR we could actually use the locale based on what `get_locale()` gives us.

The `react-datetime-picker` package's default visual presentation of the time picker is a clock (with clock hands/pointers) -- which doesn't seem to be interactive (at least when testing) -- that IMHO needs replacing anyway:
<img width="396" alt="Screenshot 2020-05-11 at 16 36 05" src="https://user-images.githubusercontent.com/3294597/81574020-8b0d1a00-93a5-11ea-9ec7-688cc21afd55.png">


The `react-datepicker`'s time picker might look quite acceptable as is though:
<img width="316" alt="Screenshot 2020-05-11 at 16 34 50" src="https://user-images.githubusercontent.com/3294597/81573916-6b75f180-93a5-11ea-8747-ac958900ec52.png">


 This, also, has a better accessibility, supporting moving around with arrow keys, whereas `react-datetime-picker` seems to support tab only -- which is quite unusable in case of a calendar really.

Thoughts?

**Comment by miina** [comment]
Will go with the `react-datepicker` for now due to the reasons mentioned in the previous comment. Since the supported date is in the same format it should be very easy to replace it later if it should become necessary for some reason. The main "trouble" of replacing `moment` and removing the duplicate date fields will be done anyway.

EDIT: decided to go with `react-calendar` instead, please see the reasoning [in the PR](https://github.com/google/web-stories-wp/pull/1743).
