### ISSUE TITLE
Filter applied to background media is not preserved when the media is removed from the background

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#7893]
## Bug Description
Originally reported by @embarks in Bug Bash 1.8

After editing a filter’s color and opacity on background media and then removing that image from the background, the filter is removed from the media and does not carry over to the now foreground image.

Does not occur in the other direction: can edit a filter and make the media a background image, the filter is not removed

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
