### ISSUE TITLE
Layers Panel: Drag Handle Improvements

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7894]
## Feature Description

In a recent support request, the user didn’t know they could drag the layers panel to make it taller/smaller (and double click to expand to full height).

Explaining that in the help center could be a nice enhancement.

### Update from Design 10/18/2021 
_This makes this ticket actionable, follow the below: _

- the “resize icon” (chevron icon) is getting updated to have a background when hovered.  See figma for exact specs, should be able to use the icon variety `Button` from the design system. 
- New drag bar UI introduced to make the drag functionality more obvious.

functionality isn't changing, the below should still hold true:
- can click when collapsed on the layers panel header to expand it
- can click when expanded on the layers panel header to collapse it
- can drag the panel open or collapsed

Figma: https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor-Sprint-Feature-Level-Designs_?node-id=9946%3A421619 

<img width="840" alt="Screen Shot 2021-10-18 at 10 06 00 AM" src="https://user-images.githubusercontent.com/10720454/137776365-2a8c964a-45af-4da3-9551-6870ee7a0fc4.png">

## Additional Context

There's potential this gets a little weird since the drag functionality of the layers panel is the same as other panels, so for now just limiting this update to the layers panel. 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
@o-fernandez what do you think about adding a tip for this?

**Comment by o-fernandez** [comment]
I agree that the layers panel (finding it and knowing how to use it) is not super easy for people to find out. That said, with the layers functionality coming into the right-click menu (https://github.com/google/web-stories-wp/issues/6139) it may not be as necessary to add to the help center, so I would ship right click menu first and reevaluate.

**Comment by BrittanyIRL** [comment]
Adding to the layer panel improvements epic to get @aaskedall and @agingoldseco 's take on if this is needed given updates in flight.

**Comment by agingoldseco** [comment]
I'm very curious if people—once the panel automatically pops up—will wonder if they can adjust it and just try to, in which case they'll see their mouse turn into drag arrows. But I did some experimenting last week with adding some sort of signifier for this—does anyone think something like this may be a good idea or any more helpful than adding to the help center?

<img width="930" alt="Screen Shot 2021-10-04 at 4 21 06 PM" src="https://user-images.githubusercontent.com/90645922/135919968-7c4e6626-012b-4f8c-87b5-56cdb74fec21.png">

**Comment by BrittanyIRL** [comment]
@choumx  ^^

**Comment by swissspidy** [comment]
3️⃣  (bottom left) would be niiice

**Comment by dreamofabear** [comment]
+1 to bottom left, though I still feel like this is very subtle and will be missed by many users. 

~@agingoldseco How about a maximize button and/or a panel header tooltip that says "Drag edge to resize"?~

Touched base with George/Andrew and here's the working proposal for Amy to refine:
1. Increase the resize hover area from the edge of the panel to the entire header
2. Highlight collapse icon (">" or "v") when hovering over the header title

(1) should make it easier for users to resize the panel (also more discoverable by seeing the mouse cursor change).

Related nitpicks:
1. Saved Colors and Saved Styles have the same issue (below)
2. Users must click the header text of panels to toggle display (vs. other parts of header)

![Screen Shot 2021-10-05 at 12 03 04 AM](https://user-images.githubusercontent.com/20525523/135958317-aae827ef-20a4-4188-84f1-85d9b3fcaa85.png)

**Comment by BrittanyIRL** [comment]
Since we just got this today for the sprint there's a chance it doesn't get into the upcoming release, especially if the draggable design update is hard to separate to show just for this one panel (i just think there's going to be some back and forth here).

**Comment by agingoldseco** [comment]
"The “resize icon” (chevron icon) is getting updated to have a background when expanded. See figma for exact specs, should be able to use the icon variety Button from the design system."

To avoid confusion, this is no longer accurate—the new idea more resembles Will's last comment. The chevron icon should only have a background (or "highlight") when the header is hovered over to indicate a click will expand or collapse it. 

Hovering over the pull bar area/whole top of the panel will turn your cursor into a resize handle.

**Comment by samwhale** [comment]
I see the `Group: Help Center` tag on this, but it's only for the design panel, right @swissspidy (post update)?

**Comment by BrittanyIRL** [comment]
i'm sure that was an accident! this is for the layers panel! 🙈 😂

**Comment by samwhale** [comment]
When this ticket was first created it mentioned the help center, so I think now that it's updated we just don't need it anymore 👍

**Comment by BrittanyIRL** [comment]
OH right! originally this was going to just be a new tip in the help center. What a journey this issue has gone on.

**Comment by csossi** [comment]
Verified in QA
