### ISSUE TITLE
Transparency filter shows the word "#transparent" in the filter control

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#7896]
## Bug Description

When you set apply a filter to an object, and open the color picker to to set the gradient curves, and colour picker is in the bottom left color #00000 and the opacity is set to 100% (ie transparent), it displays the word "transparent" instead of showing the color hex code

## Expected Behaviour

Should probably just still show the color hex code regardless

## Steps to Reproduce

1. Select an object in the canvas that is eligible to have a filter applied
2. Select the Linear filter
3. open the color picker to set the curves for the gradient
4. ensure that the color selected is bottom left corner ie: #000000
5. set the transparency slider to 0%

## Screenshots

![Screen Shot 2021-06-09 at 11.57.21 AM.png](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/cf2c6465-ea46-4439-84cf-d1a039dc6cc3)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
