### ISSUE TITLE
Classic Editor: Add integration to allow embedding single stories

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#7898]
## Feature Description

The button in the classic editor inserts the [web_stories] shortcode, not the [web_stories_embed] one.
Is there a way to allow inserting a single web story via the [web_stories_embed] shortcode directly from the Classic Editor?

## Alternatives Considered

Manually copying the embed code you get after publishing the story and entering that it into an existing post. 

## Additional Context

Related topics from the support forum:
- https://wordpress.org/support/topic/where-to-find-the-embed-code/#post-14397815
- https://wordpress.org/support/topic/grab-shortcode-after-first-publish/#post-14537933

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Closing since we should focus on Gutenberg
