### ISSUE TITLE
Provide warnings for text that could potentially overflow/be cut off.

### ISSUE THREAD

**Issue by shishirm** [GoogleForCreators/web-stories-wp#7909]
## Feature Description

While we do have the safe zone as a guide to having creators keep text within it to avoid being cut off or overflowing, not all creators adhere to this. This often results in a degraded experience on certain devices.

The ask is to provide more visual cues to creators so they are aware of this. Ideally, a "High Priority" checklist item that alerts them to this i.e. a text box that fits outside of the safe zone, but other approaches can work as well.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
We've discussed in the past (UX/eng syncs) whether we should just prevent text from overflowing. We'd prevent the text box from ever being above/below the top/bottom lines in the safe zone, and would need to ensure the text fits within the text box. Some complexities on how to handle (e.g., what if I paste in a very long text into a text box with a large font size? etc.) but that would be a more robust way to do this. 

Let's keep this (adding to the checklist) as a potential solution, but will monitor for now and prioritize in a future release.
