### ISSUE TITLE
Update PPC Paneling 

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#7918]
## Feature Description

The PPC is getting moved to a popup. The accordion panels inside of the checklist have some new requirements.

## Additional Context

https://www.figma.com/file/1YM3jA9h4QGc4xLdyaXIJS/Stories-Sprint-1.7?node-id=8378%3A2077

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

Each expanded checklist category panel should have a fixed height of 560px and be scrollable.

**Comment by samwhale** [comment]
This footer is not being made, this has been agreed on already but the designs still have it. Please do not add!
![image](https://user-images.githubusercontent.com/22185279/122826507-3aa70200-d2b1-11eb-9ff7-4a8b9ec72e91.png)
