### ISSUE TITLE
Background image Play icon displayed on top of other elements

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#792]
## Bug Description

When background video is set, the play icon appears every time when hovering on the background and on top of other elements.
## Steps to Reproduce

1. Add a Page with video as background media
2. Add an image and center it
3. Hover on the background
4. See the play button appearing on top of the image.

## Screenshots

![video-play](https://user-images.githubusercontent.com/3294597/77640573-e9e41480-6f5a-11ea-867b-dbb91cf04028.gif)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by merapi** [comment]
What is the _Expected Behaviour_ here? @samitron7 @pbakaus

**Comment by pbakaus** [comment]
The playback UI should be logically z-indexed with the element it applies to.

We could consider revealing a translucent play icon when an element that is otherwise obstructed is actually selected, but not on hover. To me, that's v2 though.

@samitron7 to chime in as well.

**Comment by swissspidy** [comment]
One related thing that bugs me here: I don't think the play button should be shown during lasso selection. Is it a known thing?

**Comment by merapi** [comment]
> To me, that's v2 though.

Ok, let's do this after Alpha (some UX needed, how exactly should it work).

**Comment by miina** [comment]
@merapi We should still keep the issue open though.

**Comment by merapi** [comment]
@samitron7 response:

> If you add a video to the page (as a fg or set as a bg) then an another element on top of it and blocking the play button. Now try to play the video. You can't because the play button is not accessible. If the element is selected, we should have the CTA appear on the top.

@miina Alright. Just had a sync with @kmyram and we agreed on closing, but just removing it from Alpha sprint seems better.

**Comment by merapi** [comment]
> If the element is selected, we should have the CTA appear on the top.

What about hover, should we show the icon in this scenario (when element is not selected)?:
![play-hover](https://user-images.githubusercontent.com/21036224/78135428-2bc0ff00-7422-11ea-82ef-b974b757b58a.gif)

[Video Playback Behaviour](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=6022%3A284838) needs to be updated to cover more cases.

**Comment by pbakaus** [comment]
Nope, we should not show it on hover if it is obstructed. We should never show it on top of other elements, as that just looks broken.

**Comment by merapi** [comment]
Great, so we can say: if ~80% of a button will be visible - display it.

It would work like below, but if we move red rectangle ~20px lower - play button will not show up.
![hovercase](https://user-images.githubusercontent.com/21036224/78339848-7020dc00-7595-11ea-97e5-51ccf9427943.gif)

**Comment by pbakaus** [comment]
@merapi I'm curious: If the play button was on the same z-index as the video element, you wouldn't have to deal with any of that 80% logic, right? Technically it would always appear on hover, but would just be obstructed when it is....actually obstructed :D your method is fine, but mine seems a little simpler...but maybe I'm missing something.

**Comment by dvoytenko** [comment]
I believe the icon is currently positioned in the frame and all frames are always above the display layer to make sure that the borders/targeting/etc is always possible. One approach is to put the icon inside the display layer. And we can switch play/pause in the video if any part of the frame (or any part of the frame with some inset) is clicked. This would make the hover logic a bit harder though.

**Comment by miina** [comment]
@merapi Assigning this to you since it'll be covered by #1948 per description of the PR.

**Comment by samitron7** [comment]
Marcin and I have been working on media issues offline and the media flow on figma are up-to-date. @swissspidy All media controls are hidden on multiple select.

Removing UX label.

**Comment by csossi** [comment]
Hover capability disappears:

- create new page
- select a video
- set as background
- note that play/pause icon appears on hover:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/7152152a-b8d2-460d-bf55-8abc1877d406)
- now add an image
- note that play/pause icon still appears (image isn't overlapping)
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/85873dad-592f-4bfd-9e35-3c51a796243e)
- move image to center of canvas
- play/pause no longer appears on hover (so far so good):
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/85765d98-e9a2-470b-b3a5-249321f7e7d9)
- now, return image to where it was. now the play/pause icon doesn't appear at all on hover:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/0a99868b-3dc6-44f0-9321-9ced5ff16670)

**Comment by merapi** [comment]
@csossi This is now fixed.
Note: the play button will appear above the image (in center) if the BG video is selected (as in spec).

**Comment by csossi** [comment]
retested PR#1948

Play is appearing on hover on TOP of centered image rather than above:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/6ab92bb0-b7db-4dfd-bf1a-6ef6fdc83638)

**Comment by merapi** [comment]
> Play is appearing on hover on TOP of centered image rather than above:

Isn't that according to spec? We just display the control above (currently selected element) when it's too small to display it inside the element.
Will ping you on Slack to clarify.

**Comment by csossi** [comment]
ah, ok @merapi - I thought it was supposed to appear above in all cases of a centered image regardless of size. All good here

**Comment by samitron7** [comment]
Verified in UAT
