### ISSUE TITLE
Reorganize prepublish checklist issues

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#7920]
## Feature Description

We are now organizing issues by ISSUE TYPE not by page number!  With this, we are updating the structure of the checklist codebase to gain perf wins and make the checklist easier to manage. This ticket will be used as a base for these updates. Each issue in the checklist will be ported over to the new structure (see #7965 and submitted as its own PR. When PRs are submitted, add them by the issue below so that we can easily track when all issues are ported over to the new structure).

| Issue | Type | Logic PR | UI PR |
| --- | --- | --- | --- |
| storyMissingExcerpt | warning | #7980 | #8042 |
| storyPosterAttached | error | #8009 | #8042|
| storyTitle | error | #8009 | #8035 |
| storyPosterPortraitSize | error | #8009 | #8035 |
| storyPosterAspectRatio | error | #8009  | #8035 |
| publisherLogoSize | error | #8009  | #8035 |
| storyPagesCount | guidance | #8008  | #8042 |
| storyTitleLength | guidance | #8008 | #8042 |
| storyTooLittleText | guidance | #8008  | #8042  |
| pageTooMuchText | guidance | #8008  | #8042  |
| video mediaElementResolution | guidance | #8008  | #8042 |
| videoElementLength | guidance | #8008 | |
| videoElementMissingPoster | guidance | #8008 | #8042 |
| videoElementOptimized | guidance |  | |
| gif mediaElementResolution | guidance | #8008  | #8042 |
| image mediaElementResolution | guidance | #8008 | #8042 |
| distributionWarnings | warning |  | |
| pageTooManyLinks | warning | #7980  | #8042 |
| pageBackgroundTextLowContrast | warning | #7980  | #8042 |
| textElementFontSizeTooSmall | warning | #7980  | #8042 |
| text elementLinkTappableRegionTooSmall | warning | #7980  |  #8042 |
| image imageElementMissingAlt | warning | #7980  | #8042 |
| shape elementLinkTappableRegionTooSmall | warning | #7980  | #8042 |
| image elementLinkTappableRegionTooSmall | warning | #7980  | #8042 |
| gif imageElementMissingAlt | warning | #7980  | #8042 |
| gif elementLinkTappableRegionTooSmall  | warning | #7980  | #8042 |
| videoElementMissingDescription | warning | #7980  | #8042 |
| videoElementMissingCaptions | warning | #7980  | #8042 |
| video elementLinkTappableRegionTooSmall | warning | #7980  | #8042 |

## Additional Context

See figma for demo and more context: https://www.figma.com/file/1YM3jA9h4QGc4xLdyaXIJS/Stories-Sprint-1.7?node-id=8378%3A1112

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

Checklist recommendations are now sorted by issue type.  

This will require updating a lot of tests.

**Comment by BrittanyIRL** [comment]
@littlemilkstudio maybe we can use this ticket also to refactor the checklist like you and @embarks were talking about last week in slack? Or we can make new tickets for that - could be more work than 5 points.

**Comment by BrittanyIRL** [comment]
@littlemilkstudio @em 
<img width="452" alt="Screen Shot 2021-06-16 at 11 01 18 AM" src="https://user-images.githubusercontent.com/10720454/122269684-5619a380-ce92-11eb-9822-7bef6871f08c.png">
I would add here with the reorganization, to be conscious of this new grouping established in the updated designs: `High Priority`, `Design`, `Accessibility` rather than `error`, `warning`, and `guidance`

**Comment by maxyinger** [comment]
@BrittanyIRL sounds gucci
