### ISSUE TITLE
Drop targeting not working as expected with History

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#793]
## Bug Description

When dropping media into a drop target and then clicking "Undo", the "Undo" does not seem to take back the dropping action, at least not visibily.

Possible duplicate: See #782 

## Expected Behaviour

Dropping media into target and clicking "Undo" should visibly undo the action.

## Steps to Reproduce

1. Add a background image
2. Drag a different image to the background
3. Click "Undo"
4. See no visible change.

## Screenshots
![history](https://user-images.githubusercontent.com/3294597/77641126-cff70180-6f5b-11ea-8d0e-9d8c63230588.gif)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment]
@miina @wassgha is this the same as #782 ?

**Comment by wassgha** [comment]
Oh yes, sorry for the duplicate

**Comment by miina** [comment]
@jauyong Looks like it! The slight difference is that in my testing, the dropped image always stayed, no matter how many times I clicked "Undo", so it was more than just combining steps.

Will close this, #782 will most likely resolve the issue generally, thanks for noting!

Closing as duplicate.
