### ISSUE TITLE
Warn Users when saving story without title

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#794]
## Bug Description

Title is a required field. However, the story can be save with the field empty with no error message or working. The story is saved with a the title auto-draft, which is confusing.

Notes:

1. Need to consider conflicts with autosave
2. Consider publishing without a title
3. See #1241 for prepublish checklist

## Acceptance Criteria
1. Recommend a solution for the UX on saving without a title
2. Recommend a solution for the UX on publishing without a title

## Expected Behaviour

Error message should be displayed to user if empty title is save.
@samitron7 to add in figma: Use textfield inline error messaging

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
As per https://xwp.slack.com/archives/CCCAUAH6F/p1585799683325200, this needs a product decision and clear path forward first.

**Comment by spacedmonkey** [comment]
@pbakaus @samitron7 Has any thought when put into this ticket? I would like to get this resolved before beta.

**Comment by swissspidy** [comment]
Please correct me if I'm wrong, but IIRC the consensus was to not make it required. Users will be reminded to enter titles during pre-publish checks, but before that they shouldn't be forced to enter something.

Stories without titles can be listed as "(Auto Draft)" or "Untitled"

**Comment by pbakaus** [comment]
Yes, but we should encourage it. Sam has mocks for this soon. /cc @samitron7

**Comment by jauyong** [comment]
Moving this out of Sprint 27 and to be done when we do #78

**Comment by samitron7** [comment]
Apologize but really thought I added the [Figma link](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=7304%3A0). If a story is published without a title, can we change it to "Untitled Story"

Just note that all the dialog box will be converted to dark theme in the new visual pass

**Comment by o-fernandez** [comment]
I think we handle this OK for now, and we'll have an additional check for title in the pre-publish checklist, so closing this separate ticket.
