### ISSUE TITLE
Using the crop functionality in media library incorrectly adjusts image dimensions

### ISSUE THREAD

**Issue by shishirm** [GoogleForCreators/web-stories-wp#7940]
## Bug Description

When using the crop functionality of the media library, if I crop an image down to 640 x 853, once completed the actual dimensions are 640 x 851 which are not acceptable as a poster for the editor.

I've captured a video here to showcase this behavior.

## Expected Behaviour

The image should be cropped to the expected dimensions.

## Steps to Reproduce

Please find a video on how to repro this -> https://www.youtube.com/watch?v=FUvseSIFjK8

## Screenshots

Please see above

## Additional Context

- Plugin Version: 1.7.2
- WordPress Version: 5.7.2
- Operating System: Latest
- Browser: All

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
That‘d be a bug in WordPress itself, as this is not part of our codebase.

Related: we‘re revamping the poster + cropping workflow anyway in #7744

**Comment by swissspidy** [comment]
Closing as we now have a dedicated step for image cropping in 1.9.0 and any rounding errors there might be server-related or bugs in WP itself.
