### ISSUE TITLE
Upload overlay clears up canvas when shown

### ISSUE THREAD

**Issue by wassgha** [GoogleForCreators/web-stories-wp#795]
## Bug Description

This might not have been clear from the Figma since it uses an empty page but the drag and drop upload overlay on the canvas should be displayed as an overlay on top of any existing elements and should not be clearing up the page when shown

## Screenshots

![ezgif com-video-to-gif (35)](https://user-images.githubusercontent.com/591655/77642449-eaf55180-6f1a-11ea-9411-3ac17f64e5a3.gif)

/cc @dvoytenko if you wanna take it, otherwise assign it to me

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by dvoytenko** [comment]
I believe this is intentional by @samitron7, to remove the misunderstanding that dnd on canvas can target any particular placement and not to be confused with drop targets.

**Comment by samitron7** [comment]
Wassim is correct. Sorry if it wasn't clear but the scrim is an overlay.
![Group 4595](https://user-images.githubusercontent.com/10889431/77719547-c349cc00-6fa2-11ea-81b7-caefea5bc4dc.png)

**Comment by wassgha** [comment]
@dvoytenko I'll take this as part of the refactor I'm doing for dnd

**Comment by dvoytenko** [comment]
Sure. To clarify though: this just involves removing the screen over the page area, right? I added an extra element on top specifically to support what I thought was required to completely screen out the content. There shouldn't be otherwise any structure issues, right?

**Comment by wassgha** [comment]
I was planning to do some renaming since the Dropzone name will be free after #803 is merged and try to simplify the structure by attempting to combine the two drop zones since the text is now simply centered in both directions, with no need to use the css grid structures

**Comment by dvoytenko** [comment]
That all sounds good. The grid strcuture/css should already be used there. I think the only delta is that we no longer need these three lines: https://github.com/google/web-stories-wp/blob/13ec65435bfa54332c5937a21cc423a58b53dd28/assets/src/edit-story/components/canvas/canvasUploadDropTarget.js#L103-L105. Or maybe they will just look different.
