### ISSUE TITLE
Background doesn't complete fill up the canvas

### ISSUE THREAD

**Issue by wassgha** [GoogleForCreators/web-stories-wp#796]
## Bug Description

There's a thin line of pixels when setting an image as background, see screenshot

## Screenshots

<img width="396" alt="Screen Shot 2020-03-26 at 4 32 17 AM" src="https://user-images.githubusercontent.com/591655/77642620-33ad0a80-6f1b-11ea-9e56-9126b605fc93.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by wassgha** [comment]
As per #819, this is also true for the page thumbnails
/cc @pbakaus

**Comment by miina** [comment]
Looks like adjust using the clip-path in masking seems to cause the issue. E.g. assigning -1 values here "fixes" it:
https://github.com/google/web-stories-wp/blob/f272e875c9e4fff8ea4632cebad5858ae2ca2217/assets/src/edit-story/masks/display.js#L29-L34

Not sure if the background element should be masked at all though.

**Comment by miina** [comment]
Okay, just saw a [comment](https://xwp.slack.com/archives/CCCAUAH6F/p1585106392015100) from @samitron7 as well that shapes should not be allowed to be set as background. So for now, I'll see if I can disable mask for background. Probably better, otherwise it might look something like this:
<img width="333" alt="Screenshot 2020-03-27 at 10 19 23" src="https://user-images.githubusercontent.com/3294597/77740957-7272bb80-7014-11ea-9965-1441db3a057c.png">

**Comment by wassgha** [comment]
@miina that makes sense, but the mask is supposed to cove 100% of the width/height anyway so there's another underlaying issue here. Do you mind looking into that? are masks not filling the entire shape?

**Comment by miina** [comment]
The clip-path is the one that seems to use `1px` from the edges.

And yes -- it looks like masks are filling the entire space -1px. I can look into it but not before Monday, probably good to follow up in a separate issue.

**Comment by miina** [comment]
@wassgha This issue was specifically for the background and that is fixed.

Will create a separate issue for investigating if we should generally consider the 1px the clip-path reduces.

**Comment by miina** [comment]
Follow-up issue for clip-path + masking: https://github.com/google/web-stories-wp/issues/855
