### ISSUE TITLE
Remove prepublish checklist from panel

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#7978]
When the new checklist is done, remove the old one from the panel. Rip out all code that is out of date. Ensure panel is working as expected. 

Set new 2.0 checklist experiment to `default: true` in experiments.

**this is the final ticket to go through for the new checklist and should be sent to QA for the feature.**

**Comment by csossi** [comment]
Verified in QA

**Comment by BrittanyIRL** [comment]
This has been out a full release cycle, moving to closed to avoid cluttering UAT. It went through QA, bug bash, feels stable.
