### ISSUE TITLE
Blocks/Renderer: Consider lazy-loading images

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#7981]
## Feature Description

[As of](https://make.wordpress.org/core/2020/07/14/lazy-loading-images-in-5-5/) WordPress 5.5, all images have the loading="lazy" attribute added. This has a number of preference benefits not to mention resource saving. 

There are a number of places where raw image tags at output. See 

 https://github.com/google/web-stories-wp/blob/a31592468d3145c266a2577692f53a0aeb028a10/includes/Renderer/Story/Image.php#L83-L89

https://github.com/google/web-stories-wp/blob/823cd1af97c5f124948758d429e63d32ccb90667/includes/Renderer/Stories/Renderer.php#L571-L576

We should ensure that these image tags are out with the lazying loading attribute, while making sure that compile with the `wp_img_tag_add_loading_attr` filter. This could be done by sampling passing the generated image tag through the [wp_img_tag_add_loading_attr](https://developer.wordpress.org/reference/functions/wp_img_tag_add_loading_attr/) function. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Worth noting that not **all** images need to be loaded lazily. It needs some consideration.

**Comment by swissspidy** [comment]
> Worth noting that not **all** images need to be loaded lazily. It needs some consideration.

To give an example:

If adding a carousel of stories at the top of the page, they probably don't need to be lazy loaded as they're always in the viewport.

**Comment by spacedmonkey** [comment]
Interesting article from Felix regarding lazy loading images - https://make.wordpress.org/core/2021/07/15/refining-wordpress-cores-lazy-loading-implementation/

**Comment by swissspidy** [comment]
Yup, main reason for my comments above. Now with some public explanation :-)
