### ISSUE TITLE
Render amp-img tag in Image Class

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#7982]
## Feature Description

In the [Image](https://github.com/google/web-stories-wp/blob/main/includes/Renderer/Story/Image.php) render class, there is a image tag render. However in the [Renderer](https://github.com/google/web-stories-wp/blob/main/includes/Renderer/Stories/Renderer.php) as check is done to see if the page is amp and `amp-img` tag is rendered. 

https://github.com/google/web-stories-wp/blob/50a0225d8edc8166006ec739d3dd471425a412a4/includes/Renderer/Stories/Renderer.php#L558-L577

This same check could be done in the image class. 

## Alternatives Considered

The renderer class could be converted to the use the image class. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Shouldn‘t be absolutely necessary, as the AMP plugin should do this automatically.

**Comment by spacedmonkey** [comment]
> Shouldn‘t be absolutely necessary, as the AMP plugin should do this automatically.

Either way, it should be consistent. So either way, we should add or remove some code.

**Comment by swissspidy** [comment]
The difference in `Renderer` seems to be the zero width & height (`// Set the dimensions to '0' so that we can handle image ratio/size by CSS per view type.`). So it makes sense to keep that.

**Comment by spacedmonkey** [comment]
Closing in favour of https://github.com/google/web-stories-wp/issues/10213
