### ISSUE TITLE
Text Sets: use images for displaying text sets

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#7985]
## Feature Description
Currently, when rendering the Text Sets in the panel, all the elements are rendered separately every time when the text sets are loaded. This causes performance issues (visible lagging) and is also not very useful since the text sets are static and changed very rarely.

We should instead create images of the text sets and display just the images. If the text sets are changed, the images can be updated, too.

## Alternatives Considered
SVG rendering -- did not bring the expected performance improvements. 
Replaces the previous SVG rendering issue: #7637 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

See #8117 
^ Conclusion from discovery:

- We'll be [generating PNG](https://github.com/google/web-stories-wp/issues/8117#issuecomment-873676127)-s (see Marcin's gist for generating the PNGs [here](https://gist.github.com/merapi/621934658713ea0e632f05d8443acd52)) that are stored in `wp.google.stories` (see more about storing [here](https://github.com/google/web-stories-wp/blob/2d9acc4d03288514b7e1ba5cf765a2328cd8972c/docs/cdn.md))

- If the PNG does not exist, render as usual, otherwise use the image.

**Comment by miina** [comment]
The issue still needs figuring out what would be the best way to store / easily generate and regenerate the images for the initial text sets and in case there's a change. The initial idea was:

- Create a new `npm` action that uses Puppeteer and creates images of the Text Sets. This could potentially be done just by using Puppeteer's screenshots. Alternative would be using `html-to-image`.
- Each text set should also store the information about which image file is related to it and render the current way if missing.
- For improving the performance of the action, we could recreate the images only if anything has changed meanwhile in the text sets. For that, we could for example store a hash of all the text set contents and only recreate it if the hash has changed.

@swissspidy had a different suggestion:
> The ticket‘s approach sounds a bit complicated.
We‘d want to serve templates and ideally also text sets from the CDN / an API, so these images should be created & live there.
IIRC SVG rendering was slow on the fly, and on the fly image rendering was considered faster. But is it also slow when rendering pre-generated static SVGs served from there?
Screenshots would need to be transparent, I doubt Puppeteer could do that. Also responsiveness is needed.
So I think in this case we‘d want pre-generated, static SVGs served from the CDN.

**Comment by miina** [comment]
cc @merapi -- you mentioned having tried out Puppeteer with transparent bg, feel free to chime in here with the information you have.

**Comment by merapi** [comment]
I was able to generate transparent PNG from Puppeteer (`omitBackground` + setting `background: transparent` on all parent nodes).
I also rendered the preview at 2x (`deviceScaleFactor: 2`) - I think that's pretty good in terms of responsiveness.

![image](https://user-images.githubusercontent.com/21036224/122730221-475c3380-d27a-11eb-9cbf-67e08236b052.png)

We can also look at SVGs (especially the external resources [fonts] part).

**Comment by miina** [comment]
If the preference would be serving the images from an external site, we could also use `html-to-image` for generating PNGs if there are problems with SVGs and fonts.

**Comment by swissspidy** [comment]
Whatever file format, I don't think we should be bundling these with the plugin and instead host them on wp.stories.google. Definitely want to avoid loading a ~100KB large file for every text set. An SVG would be much smaller.

That said, we should probably do an ad-hoc call just so we're all on the same page about all of this.

**Comment by swissspidy** [comment]
@merapi How did you take the screenshots in Puppeteer, just by opening the editor directly?

**Comment by merapi** [comment]
@swissspidy Yes ([used this code](https://gist.github.com/merapi/621934658713ea0e632f05d8443acd52))

**Comment by csossi** [comment]
Please add QA instructions to the PR - many thanks

**Comment by csossi** [comment]
Verified in QA
