### ISSUE TITLE
Easier/smarter text font & color styling: Text Presets (not text sets)

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#7986]
## Feature Description
If I add a new text element using the presets (not the Text Sets, but just the basic presets on top) the text element added can have accessibility issues due to low contrast with the background.

As the first improvement for smarter text styling, we should check the contrast and ensure it's at least level AA by using either white/black colour for the text, or black/white highlight.

This issue does NOT include the text sets.

See [Figma](https://www.figma.com/file/1YM3jA9h4QGc4xLdyaXIJS/Stories---Sprint-1.7%2B?node-id=8336%3A26464).

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
- When user clicks to add a text element, the text element will be added so that it's contrast with the background will pass AA accessibility level.

## Implementation Brief
- When the user clicks on a preset, create an image of the page using `html-to-image` library.
- Calculate the contrast for the text (see [Paul's codepen](https://codepen.io/pbakaus/pen/gOpZXbW) for inspiration)
- If the contrast is OK for the default (black) colour, add it as is.
- If the contrast is not OK, try other options: white colour; black colour + white highlight; white colour + black highlight
- Consider font size in the calculation (use the values from the elements, not the visually displayed font size)

Note: this issue partially depends on #7961 since that PR adds the needed adjustments to the `html-to-image` library.

**Comment by csossi** [comment]
Verified in QA
