### ISSUE TITLE
Image rendering for thumbnails

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#7987]
## Feature Description
Render images for thumbnails instead of rendering all the elements one by one every time.

See the [discovery PR](https://github.com/google/web-stories-wp/pull/7887) that uses `html-to-image` for creating images from the thumbnails on initial render and uses those.

The current page preview should still be rendered normally since the changes on the page should be reflected right away.
This also means that after a page update, its image should be updated, too.

## Alternatives Considered
SVG rendering, see https://github.com/google/web-stories-wp/issues/7468

SVG rendering didn't seem to bring a significant performance improvement, see https://github.com/google/web-stories-wp/pull/7615#issuecomment-853368302

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
