### ISSUE TITLE
Show an error message if user leaves editor without saving

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#799]
## Bug Description

If a user leaves the editor without saving the story, all progress / changes will be lost. 

## Expected Behaviour

Some kind of error message would be shown to user if they try and navigate away.

## Steps to Reproduce

- Create a story
- Add some elements.
- Click on any link in the left hand sidebar.

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
![Screenshot from 2020-03-26 12-17-50](https://user-images.githubusercontent.com/237508/77646147-e2713b00-6f5b-11ea-8500-4dbdc0a58337.png)

**Comment by spacedmonkey** [comment]
![Screenshot from 2020-03-26 12-30-01](https://user-images.githubusercontent.com/237508/77647005-91624680-6f5d-11ea-9449-778d82a85992.png)

**Comment by pbakaus** [comment]
Yes, that's perfect!

**Comment by swissspidy** [comment]
cc @jauyong for keeping track of this
