### ISSUE TITLE
Use the filter `safe_style_disallowed_chars` to make KSES class simplier

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#7992]
## Feature Description

Follow up from https://github.com/google/web-stories-wp/pull/7951. Added in WordPress 5.5 ( https://github.com/WordPress/wordpress-develop/commit/fa96d5931826b936095022013e30ee5934018779 ), the `safe_style_disallowed_chars` filter could be used to make the logic in KSES simpler. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
While I originally added that comment, today I don't think it's wise to use the filter like this. Our custom rgba logic is much more robust than that. Plus, there's stuff in there that can't be accomplished with this filter alone. I'd rather port our solution to core (see e.g. https://core.trac.wordpress.org/ticket/24157).

Marking as P4 for the time being.
