### ISSUE TITLE
Page loading issues: Failed to load: [object HTMLVideoElement]​​​

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#7993]
## Bug Description

The following page loading issues occur with Stories containing videos: 

- Failed to load: [object HTMLVideoElement]​​​
- Uncaught (in promise) Error: Failed to load: [object HTMLVideoElement]​​​at ka (https://cdn.ampproject.org/v0.mjs:2:1299) at lb.createError (https://cdn.ampproject.org/v0.mjs:2:12028) at https://cdn.ampproject.org/v0.mjs:4:14882

Example story URL: https://testsite.cmsdevrel.com/web-stories/testing123video

## Expected Behaviour

No page loading issues. 

## Steps to Reproduce

1. Create and publish a story containing a video
2. Test the story on https://search.google.com/test/rich-results
3. View page loading issues

## Screenshots

Rich results screen: https://jumpshare.com/v/EnavPypUNIkFqeKm4f7Q

## Additional Context

Related support topic: https://wordpress.org/support/topic/uncaught-in-promise-error-failed-to-load-object-htmlvideoelement

No console error
network response: https://jmp.sh/tBiEDSK

- Plugin Version: 1.8.0
- WordPress Version:
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by dreamofabear** [comment]
Looks like a harmless intermittent loading error in RRT. 

Tracked internally: `b/191665033`
