### ISSUE TITLE
Text sets: Easier/smarter text font & color styling

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#7995]
See [Figma](https://www.figma.com/file/1YM3jA9h4QGc4xLdyaXIJS/Stories-Sprint-1.7?node-id=8898%3A2153).

Note: this issue is for Text Sets specifically, please see the Text Sets part in Figma only, it's together with the Text Presets there.

## Description 

When adding text sets, we need to ensure the added text set will have enough colour contrast with its background.
Some or the ground work has been done for color calculation and image generation within #8118.

The following rules apply:
- If any of the texts in the set has a predefined color (anything else than the default black), ignore this text set and handle as it's currently being done (without any changes).
- The text elements within one text set have to get assigned the same color. E.g. we should not assign white color to one of the texts and black to the other within the same text set.
- If all the elements within one text set have at least AA level contrast using white color, all the elements will be assigned white color. If all the elements have AA contast using black color, all the elements will be assigned black color.
- If some of the elements need black color and some of the elements need white color, we will use a scrim behind the text set, depending on the better contrast, either 30% opacity white or 30% opacity black shape will be used to ensure the AA level for all elements. Note that for doing this we'll need to add a shape behind each relevant text set and either omit it upon insertion or use the scrim.
- If we're changing the colors of the texts, we should also change the colors of borders and shapes.

Note: Text Sets can also be dragged onto the page! To be confirmed if we should already change the color while dragging or only when dropping.
**^ Edit: for now, only when dropping.**

See [`contrastUtils`](https://github.com/google/web-stories-wp/blob/main/assets/src/edit-story/utils/contrastUtils.js) for the existing utils for contrast calculation.

## Examples
![Screenshot 2021-07-02 at 15 13 57](https://user-images.githubusercontent.com/3294597/124273009-c89bac00-db3f-11eb-92ac-10ef804a4485.png)
![Screenshot 2021-07-02 at 15 13 52](https://user-images.githubusercontent.com/3294597/124273024-ccc7c980-db3f-11eb-83f3-e135412de47a.png)

**Comment by bmattb** [comment]
@tmagalhaes-huge friendly reminder that we require the UX on this for inclusion into the 1.10 release and that work begins next week.

**Comment by csossi** [comment]
Verified in QA
