### ISSUE TITLE
Color picker improvements for easier text color styling

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#7996]
See [Figma](https://www.figma.com/file/1YM3jA9h4QGc4xLdyaXIJS/Stories-Sprint-1.7?node-id=9078%3A353191) for design.

## Description

We're reworking the color picker for making it easier for the users to choose colors.

- Color picker's default view will be with default preset colors with saved color below (view 1).
![Screenshot 2021-07-02 at 15 21 48](https://user-images.githubusercontent.com/3294597/124273878-def63780-db40-11eb-9600-2e1cc0e825cd.png)
- The Saved colors are only the global colors. Current story colors feature will remain but will be usable only from the panel.
- If the user wants to choose a custom color, the "Custom" button needs to be clicked.
- When clicking the Custom button, the current color picker view (view 2) will appear:
![Screenshot 2021-07-02 at 15 24 03](https://user-images.githubusercontent.com/3294597/124274124-2bda0e00-db41-11eb-8b32-f44206dde9e6.png)
- The user can choose a color from there and also use the "Add" button to save the color to _global_ colors.
- Note: If the user has selected an element that already has gradient assigned, and opens the color picker then, the View 2 will be opened by default right away.

**Comment by bmattb** [comment]
@tmagalhaes-huge friendly reminder that we are waiting on UX for this to get picked up next sprint for v1.10. thanks!

**Comment by csossi** [comment]
Verified in QA
