### ISSUE TITLE
Add Video Resolution Too High PPC check

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#7998]
Add a new check to the prepublish checklist for the following: 
`Video resolution too high to display on most mobile devices (e.g., >4k)` 

https://docs.google.com/spreadsheets/d/1PjaRp4bueQ3Cv14A7I696m0vjGCIX_kN9tIGh-V-Bkc/edit?ts=5fbd398a#gid=920793050

The display title is: `Reduce video resolution to less than 4000p` 
Category: Design 

New check should be visible if the video resolution exceeds 4000p. 

**There is no associated UX for this check yet however, it should follow suit of like minded checks, so a thumbnail should be included as well as optimize the video or if it's already been optimized to replace it?**  
^^ this should be verified by product

Acceptance criteria: 
- in addition to the above, new check should be accompanied by tests.

![Screen Shot 2021-06-21 at 9.20.53 AM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/e64952bd-7107-4c06-a2f6-90c37c68eed8)

**Comment by BrittanyIRL** [comment]
Hey, @o-fernandez - want to double check with you that this is a checklist issue we still want to add. It is the only one on the spreadsheet that wasn't accounted for already when we swapped over to the new checklist that lives in a popup but nobody ever mentioned it - just found it when moving issues and cross referencing copy as I went.

**Comment by o-fernandez** [comment]
Thanks for catching that! It's an issue that Paul and team ran into, though I don't know how often it's a problem out in the wild... Curious, would the video optimization take care of this? 

@swissspidy I imagine that if the video resolution is too high as described here we'd prompt the user to optimize the video in the checklist, so this may be accounted for already?

**Comment by swissspidy** [comment]
Well we don't check for the resolution being _too high_, but we do check for videos being optimized or not. And optimizing videos always fixes resolution, so it would indeed be covered by that.

**Comment by BrittanyIRL** [comment]
> Well we don't check for the resolution being _too high_, but we do check for videos being optimized or not. And optimizing videos always fixes resolution, so it would indeed be covered by that.

so, adding this check is super redundant, yah?  If so, i'll just close it and leave a comment on that copy spreadsheet.
