### ISSUE TITLE
Ensure that embedded resources in templates have correct accessibility data 

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#7999]
## Feature Description

Ensure that resources that are embedded in templates files have correct accessibility data, such as.

- Images tags.
- Titles
- Video caption files

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
> We need to ensure that accessibility data can be translated..

This is covered by #1722.
