### ISSUE TITLE
Do not allow trashing story from within the editor

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#800]
## Feature Description

Per UX guidance in comments below: 

> I would like remove the Move to trash button from the Document settings and allow managing stories only in the dashboard.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Note: trashing a story isn't currently in Figma, at some point, there was an ongoing discussion between @pbakaus and @samitron7 on how to do it and if being in the Document sidebar is the best place.

Might need some additional UX to confirm if the sidebar is the best place for this. Although perhaps this might already be for a separate issue.

**Comment by spacedmonkey** [comment]
Related #799

**Comment by spacedmonkey** [comment]
Worth noting that gutenberg does not have a dialog to confirm trashing posts.

**Comment by pbakaus** [comment]
Will wait for @samitron7 to confirm and design a flow before prioritizing this. But agree we should have this somewhere. I just don't know if we really need this in the editor, or whether it is enough to be able to do this from the dashboard..?

**Comment by spacedmonkey** [comment]
I am guessing we could reuse #251

**Comment by spacedmonkey** [comment]
Related #802

**Comment by samitron7** [comment]
Sorry I dropped the ball on this but I have always thought it to be a little weird to be able to delete your story from inside the editor:

1. I've created a story
2. I delete it from inside the editor
3. This takes me away from the editor and throws me in the dashboard (currently it goes to the WP list view)

Most app and editor separate managing and creating. I would like remove the Move to trash button from the Document settings and allow managing stories only in the dashboard. @pbakaus If you're good with this?

**Comment by pbakaus** [comment]
> Most app and editor separate managing and creating. I would like remove the Move to trash button from the Document settings and allow managing stories only in the dashboard. @pbakaus If you're good with this?

yep. @o-fernandez chime in if you have thoughts here as well. I always found it supremely strange behavior in Google Docs, for instance..

**Comment by swissspidy** [comment]
Curious to hear user feedback on this once we release without a trash button :-)

**Comment by o-fernandez** [comment]
Given that there's a risk, as @swissspidy points out, that users will react adversely to not having an option to trash their story from within the editor, I've marked this as a Beta change. That way we can get Beta feedback on this prior to releasing the editor out on stable.

**Comment by spacedmonkey** [comment]
User should be able to remove stories. Will this functionality move to the dashboard then? @o-fernandez @swissspidy ?

**Comment by miina** [comment]
@spacedmonkey It will be available from Dashboard, see a few comments above: https://github.com/google/web-stories-wp/issues/800#issuecomment-631880643

Also, currently, it's still possible from "All Stories".

**EDIT**: Correction: It **is** already possible from Dashboard.

**Comment by csossi** [comment]
Verified in QA:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/a712e979-2f79-4759-82b1-86c656c297db)
