### ISSUE TITLE
Classic Editor: Radio buttons misaligned in stories modal

### ISSUE THREAD

**Issue by mxbclang** [GoogleForCreators/web-stories-wp#8011]
## Bug Description

In the Web Stories modal in Classic Editor, the Image Alignment options that appear when List is selected as Layout are misaligned:

![image](https://user-images.githubusercontent.com/12189958/122937445-fdd61c00-d33f-11eb-9cb8-4ea34a27c1a8.png)

## Steps to Reproduce

1. Install Classic Editor plugin if needed
2. Go to a post or page
3. Click Web Stories button
4. Select List as Layout type
5. See misaligned options

## Additional Context

- Plugin Version: 1.8.0
- WordPress Version: 5.7.2
- Operating System: macOS Big Sur
- Browser: Replicated in Chrome and Firefox

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
IIRC this is a known issue with the WordPress/Gutenberg component we're using for these radio buttons. Not much we can do about it.

cc @spacedmonkey @divyarajmasani

**Comment by divyarajmasani** [comment]
It seems this has been resolved, 

![Screenshot 2022-01-26 at 4 57 39 PM](https://user-images.githubusercontent.com/6906779/151155715-a3a5d69b-b800-4093-abb8-5a1fce45ce1d.png)

## Additional Context
- WordPress v5.9
- Classic Editor v1.6.2
- Web Stories v1.16.0
- Theme: Twenty Twenty-Two v1.0

**Comment by swissspidy** [comment]
Excellent! Closing this then.

Thanks for testing!
