### ISSUE TITLE
Show snackbar message when story fails to trash

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#802]
## Feature Description

Show snackbar message when story fails to trashed. 

Related: #801 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@o-fernandez Is this still relevant now when we're removing the trashing functionality from the editor within #800? Or should it be closed?

**Comment by spacedmonkey** [comment]
Related: #2078

**Comment by o-fernandez** [comment]
I assume we can close it, since it is workspace specific. Will Close.
