### ISSUE TITLE
Show error if chosen Link has errored on the server-side

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#806]
## Feature Description

The user should be let know if a chosen link is incorrect, especially since we already do have that information.

Currently, it's possible to add a broken link.

<img width="730" alt="Screenshot 2020-03-26 at 14 26 47" src="https://user-images.githubusercontent.com/3294597/77651975-daba9200-6f6d-11ea-8786-d9c17162d613.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

- User should be let know if a broken link is used in "Link"

**Comment by spacedmonkey** [comment]
This needs UX.

**Comment by obetomuniz** [comment]
Just addressed this UX needed in #983 @spacedmonkey since this issue proposal was already merged in #912
