### ISSUE TITLE
Coverr logo is incorrect in 3P media library

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#8062]
## Bug Description

The Coverr logo is missing the colors, which is incorrect. This is a partner reported issue. We should revert back to the regular Coverr logo as it used to be. 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Looks like a simple issue where the SVG optimizer inadvertently strips the color.
