### ISSUE TITLE
3P media library 3P services logos not clickable

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#8063]
## Bug Description

In the 3P media library, the logos for the service providers should be clickable and open in a new tab the service provider's website (Unsplash, Coverr, Tenor). This used to be how it worked, but for some reason doesn't work like that now. This needs to be fixed ASAP.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Looks like a simple z-index issue, trivial to fix.

**Comment by csossi** [comment]
Verified in QA
