### ISSUE TITLE
Various console log errors for Media elements

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#807]
## Bug Description

Various console error messages show up when using Image/Video.

## Expected Behaviour

There should be no console errors.

## Steps to Reproduce

1. Add image and video elements
2. See console.

## Screenshots

<img width="1346" alt="Screenshot 2020-03-26 at 14 21 57" src="https://user-images.githubusercontent.com/3294597/77652165-210ff100-6f6e-11ea-8f1b-06bb9a412855.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
The `webkitClipPath` one was fixed in #791.
The `WithMask` one was also highlighted in #381
