### ISSUE TITLE
Silence `renderToStaticMarkup` / `useLayoutEffect` console warnings

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8090]
## Feature Description

We use `renderToStaticMarkup` from `react-dom/server` in `getStoryMarkup()`, which causes tons of `Warning: useLayoutEffect does nothing on the server` console errors, making debugging in the browser quite difficult as they pollute the entire console.

Since there is no proper way to disable that warning, it can only be done in a hacky way like this:

```js
const originalConsoleError = console.error;
console.error = function( error, ...args ) {
	  if ( error && ! error.startsWith( 'Warning: useLayoutEffect does nothing on the server' ) ) {
	    originalConsoleError( error, ...args );
	  }
};

const markup = renderToStaticMarkup(...);

console.error = originalConsoleError; // eslint-disable-line no-console

return markup;
```

## Alternatives Considered

An alternative would be to use a custom function for this kind of serialization, like `renderToString` in `@wordpress/element`.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Related: #8159 

Comment that can be removed with this:

https://github.com/google/web-stories-wp/blob/6c3764cdc40af757f35a750182f3640b7a9d11fa/assets/src/edit-story/output/utils/getStoryMarkup.js#L38-L41

**Comment by spacedmonkey** [comment]
@swissspidy I am not sure what needs to be done here. There error messages are already silenced as of https://github.com/google/web-stories-wp/pull/5697

Also can you detail where errors shows up? What kind of tests?

In the react package, we do this. 
```
import { useEffect, useLayoutEffect } from 'react';

const isBrowser = typeof window !== 'undefined';
const useIsomorphicLayoutEffect = isBrowser ? useLayoutEffect : useEffect;

export default useIsomorphicLayoutEffect;
```
Then export this as

```
export { default as useLayoutEffect } from './useIsomorphicLayoutEffect';
```

**Comment by swissspidy** [comment]
This is not about tests or useLayoutEffect directly.

Run

npm run dev

And open the editor in the browser. You‘ll see all these warnings.

To fix this, we need to stop exporting renderToStaticMarkup directly and instead export the function with the code above.
