### ISSUE TITLE
Storybook: Replace deprecated knobs addon

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8091]
## Task Description

[`@storybook/addon-knobs`](https://www.npmjs.com/package/@storybook/addon-knobs) is deprecated in favor of `@storybook/addon-controls` (part of `@storybook/addon-essentials`), which actually can also replace `@storybook/addon-actions`.

I've played around with this locally already to see how feasible it would be.

Switching to `@storybook/addon-essentials` would mean we have to update **all** our storybook components, which will take some time.

**Comment by BrittanyIRL** [comment]
@swissspidy  - pea pod could def tackle this in the next few months. Would you be ok with us taking it?

**Comment by swissspidy** [comment]
@BrittanyIRL Yes absolutely! That would be fantastic.
