### ISSUE TITLE
Block: interaction issues on mobile

### ISSUE THREAD

**Issue by mxbclang** [GoogleForCreators/web-stories-wp#8111]
## Bug Description

When using the Circle Carousel feature via the Web Stories Gutenberg block (with either Latest Stories or Selected Stories), the circles for each story are not selectable/tappable on the mobile Chrome browser. This appears to be specific to the mobile browser (on both iPhone and Android), as this issue does not occur when shrinking down the desktop screen on Chrome desktop.

## Expected Behaviour

Circles in the Circle Carousel should display the selected story when tapped.

## Steps to Reproduce

1. On a post or page, add the Web Stories Gutenberg block
2. Select Latest Stories or Selected Stories
3. Select Circle Carousel
4. View on Chrome

## Screenshots

Video: https://jmp.sh/v/CE1UYVNoux2XevYzd95L

## Additional Context

- Plugin Version: 1.8.0
- WordPress Version: 5.7.2
- Operating System: Replicated on Google Pixel 5 OS v11 and iPhone 12 OS v14.6
- Browser: Chrome mobile v91

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Strange bug. I tested with the URL shared at https://wordpress.org/support/topic/circle-block-is-not-clickable-on-chrome-mobile/ and the click worked after first scrolling on the page.

Note that this also happens on "plain" iOS Safari itself and not just Chrome (which is just fancy Safari on iOS)

**Comment by swissspidy** [comment]
Related thread saying the same thing about having to scroll first: https://wordpress.org/support/topic/stories-only-work-if-i-move-the-page-before-mobile/

**Comment by csossi** [comment]
Verified in QA
