### ISSUE TITLE
Explore using images vs SVGs in Text Sets optimisation

### ISSUE THREAD

**Issue by merapi** [GoogleForCreators/web-stories-wp#8117]
## Task Description

Initially, the idea was to use images in https://github.com/google/web-stories-wp/issues/7985, but then the idea of using SVGs came.
This task is about comparing those solutions (especially across external resources loading/embedding) resulting in a suggestion for implementation.

**Comment by merapi** [comment]
Tested on 1st text set:
- PNG ([Puppeteer, transparent BG, render at 2x](https://github.com/google/web-stories-wp/issues/7985#issuecomment-864838247)): ~11KB.
- [SVG from html-to-image](https://gist.github.com/merapi/9a5451363fbaef2d8984ed14db7ea2e8): ~220KB without embedded fonts (containts unnecesary styles).
- SVG with dedicated text sets renderer: ~less than PNG but we need to solve external fonts part, option 1) embedding fonts would add another X-XXKB, alternatively 2) loading them as an external resource would add another request(s) but it should be cacheable per all texts sets.
Also in 2) we cannot use plain `img` tag, just `object`, I'm not sure if this will create any issues - probably not?.

PNG images seem to be the easiest/fastest option to implement, not sure if SVG text set renderer is worth the effort (potentially XKB per text set).

**Comment by miina** [comment]
@merapi Thank you for sharing the findings. Do you happen to have the branches somewhere where you tested the 2 options (creating the PNG with puppeteer / SVG with dedicated text sets renderer)?

@swissspidy Thoughts? WDYT if we start with the PNG-s (should already be a significant improvement) as a simpler solution? We could follow-up with switching PNGs to SVG-s if needed -- that will require some extra effort related to fonts + testing if it makes a difference compared to PNGs.
Let me know if you think it's still worthwhile to test it with SVGs right away (perhaps fonts as external resources then), too, and then compare to choose the best.

**Comment by swissspidy** [comment]
SGTM 👍  We could even consider looking into converting PNGs to WebP in the future

**Comment by miina** [comment]
Closing the issue with a recommendation to use PNGs for now.
