### ISSUE TITLE
Update title length check in pre-publish checklist from 40 to 70 characters

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#8119]
## Feature Description

Per the [latest Google guidelines](https://developers.google.com/search/docs/advanced/appearance/web-stories-creation-best-practices#seo), it is recommended to keep the title tag to 70 characters or less, with an absolute max of 90 characters. 

We should update the pre-publish checklist to align to this (currently says 40 characters or less)

Issue description: Story title is longer than 70 characters
Issue copy: Shorten title to 70 characters or less

Once these changes are implemented in the code, we should update our [tracking spreadsheet for text strings](https://docs.google.com/spreadsheets/d/1PjaRp4bueQ3Cv14A7I696m0vjGCIX_kN9tIGh-V-Bkc/edit?ts=5fbd398a#gid=920793050)

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
@BrittanyIRL for your review, hopefully not a difficult change.

**Comment by BrittanyIRL** [comment]
Thanks, @o-fernandez - I'll see if we can sneak it in this week.
