### ISSUE TITLE
Improve CTA components

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#8120]
## Feature Description

For reference, see the improved CTA components in Web Stories: 
* https://github.com/ampproject/amphtml/issues/34449
* https://github.com/ampproject/amphtml/issues/34450

We should review and determine what changes to make and new features to expose to creators (e.g., light/dark mode for CTAs, adding a CTA icon, etc.) Then implement those changes. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
We don't use `<amp-story-cta-layer>`, so https://github.com/ampproject/amphtml/issues/34450 does not affect us.

With `<amp-story-page-attachment>` for outgoing links being deprecated, we'll need to switch to `<amp-story-page-outlink>`. _This is something we'll have to do regardless of any other changes and could be a separate ticket._

Light/dark theme: IIRC this has been requested by users before and would be a nice enhancement. See #4682

Custom theme: this is a new feature and would be interesting to support. Basically requires a color picker + a toggle to say whether the color should be applied to the text or the background. (Could be called "Invert" perhaps)

CTA icon: would be a nice improvement. We already have this for regular links, so making this possible for page attachments would be trivial.

**Comment by swissspidy** [comment]
Note: some PHP work is needed to add new components to the KSES allowlist.

**Comment by bmattb** [comment]
@barklund will take a look at this and propose some UX for this

**Comment by o-fernandez** [comment]
For prioritization, I think that:
- P0: Toggle light/dark mode
- P1: add CTA icon

@barklund let me know if anything else you need here / blocking.

**Comment by swissspidy** [comment]
@o-fernandez Just to confirm, no custom themes for now?

**Comment by o-fernandez** [comment]
> @o-fernandez Just to confirm, no custom themes for now?

Yeah, I think we can keep this simpler with a simple light/dark mode toggle and revisit in a future ticket if we want to do custom colors/themes. 

In general, I'm hoping to simplify options/customization and reduce the number of knobs in the editor unless where they are needed/highly requested. We can revisit, of course.

**Comment by swissspidy** [comment]
@csossi Did you test the new page attachment functionality as well in #8578? Or just the protocol handling in #8377?

ZenHub moves both issues over because their connected to the PR. So not clear if you did the full testing or not.

**Comment by csossi** [comment]
Yes, both - will include a note in these cases, @swissspidy

**Comment by csossi** [comment]
Verified in QA
