### ISSUE TITLE
PPC Poster Check Has 2 Issues that are very similar

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#8129]
Uncovered while reorganizing the checklist. We have two checks on story poster aspect ratio: and poster size. 

This feels redundant to me. Is there any way we could combine these? 

![Screen Shot 2021-06-30 at 4.15.12 PM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/52878159-9c85-413e-bc87-8dca413f37a2)

**Comment by BrittanyIRL** [comment]
@choumx @swissspidy @spacedmonkey do any of you have thoughts on this?

I think we should only show `increase poster image` when the size is too small and then if the poster size isn't too small but still isn't right show `correct poster image` - but I wanted to ask you all because i want to be sure that I'm just not misunderstanding the core purpose of the check.

**Comment by swissspidy** [comment]
Since the bullet points are the same anyway, can‘t this just be 1 single check for the correct size & aspect ratio?

Also note that we‘re adding a cropping UI for the poster image (#7744), so this check shouldn‘t be needed for much longer.

**Comment by embarks** [comment]
yeah I think a change in the copy would be good that just asks for the “correct” size and aspect ratio, rather than having two separate checks with different copy. we can probably use our judgement on how it should read

**Comment by dreamofabear** [comment]
Combining sounds good, thanks for raising!

**Comment by BrittanyIRL** [comment]
> Since the bullet points are the same anyway, can‘t this just be 1 single check for the correct size & aspect ratio?
> 
> Also note that we‘re adding a cropping UI for the poster image (#7744), so this check shouldn‘t be needed for much longer.

@swissspidy now that cropping for poster images is in place, do you think we should ditch the aspect ratio check or keep it for edge cases?

**Comment by swissspidy** [comment]
I think we can keep it for now as older stories won't have cropped poster images.

**Comment by BrittanyIRL** [comment]
@csossi the PR description has QA directions in it.

**Comment by csossi** [comment]
Verified in QA
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/352d8bc8-8efe-452d-8d67-432fac824d37)
