### ISSUE TITLE
PPC v 2.0 Expand Panels

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#8132]
## Feature Description

As checkpoints are hit (see #8115 ) the corresponding tab section should expand if there isn't already a panel expanded. 
This means that when 'only recommended' checkpoint is hit, expand design. 
When 'all' checkpoint is hit, expand priority. 

It'd be great to preserve which tab is open on future expansions. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by samwhale** [comment]
A small addition: make the tablist have a height of `0` so that it does not obscure buttons when the checklist is closed.

<img src="https://user-images.githubusercontent.com/22185279/124167774-88fe9280-da61-11eb-8ebd-2aca6ef01a76.png" height="300px" />
