### ISSUE TITLE
Performance Sprint: WP & Infra

### ISSUE THREAD

**Issue by dreamofabear** [GoogleForCreators/web-stories-wp#8135]
## Feature Description

Part of the performance epic (#8006), this is an umbrella issue for work in the upcoming performance sprint (7/5 - 7/16) for the WP & Infra pod. 

Consider using this issue as a tracker and discussion forum for performance-related projects during the sprint. 

For reference and ideas, see the performance bug bash takeaways: https://github.com/google/web-stories-wp/issues/8006#issuecomment-871805740

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Related: #2390, #5328, #868

Useful resources:

https://github.com/addyosmani/puppeteer-webperf
https://media-codings.com/articles/automatically-detect-memory-leaks-with-puppeteer

Gutenberg's performance tests:

https://github.com/WordPress/gutenberg/blob/326ebc6044418d91df2d58c0c9dce7548e031ab1/packages/e2e-tests/specs/performance/post-editor.test.js
https://github.com/WordPress/gutenberg/blob/3da717b8d0ac7d7821fc6d0475695ccf3ae2829f/packages/e2e-tests/config/performance-reporter.js

**Comment by swissspidy** [comment]
> * Media or 3P media thumbnails take a long time to load (x2)
> * * Large assets like GIFs and video are especially painful

Potentially one area we could help with as well.

**Comment by dreamofabear** [comment]
Re: monitoring, one low-hanging fruit is to improve our usage of [GA Site Speed](https://support.google.com/analytics/answer/1205784?hl=en#zippy=%2Cin-this-article). 

For example, adding [User Timings](https://developers.google.com/analytics/devguides/collection/analyticsjs/user-timings) e.g. time from user gesture to UI update for known-slow actions, or time to load editor (unfortunately, default GA page load timings are dispersed due to story IDs in URLs). We might need to tweak current sampling rates too.

This should give us better understanding of real-world performance and help understand trends (improvements/regressions) over time.

**Comment by swissspidy** [comment]
There's already some user timings usage in the editor (search for `getTimeTracker`), but this can of course always be expanded.

Edit: this can of course be done by any pod, really.

> (unfortunately, default GA page load timings are dispersed due to story IDs in URLs).

I originally implemented URL overrides so that this doesn't happen 🤔  URLs should look like `/editor` or `/dashboard`
Sounds like a bug in the telemetry config. I'll take a look.

Edit: not seeing any issues with the configuration.

**Comment by dreamofabear** [comment]
Hmm, I see "0" values for page timings (e.g. Avg. Page Load Time) under `/editor`, but not for URLs like `/wp-admin/post.php?post=<id>&action=edit`. 

![Screen Shot 2021-07-08 at 5 42 43 PM](https://user-images.githubusercontent.com/20525523/124994623-1dde2e80-e014-11eb-83a3-d99272a383a8.png)

**Comment by dreamofabear** [comment]
Re: responsiveness, jank after user gestures are obviously shown as long event handlers. 

For example, 1s+ delay after mouseup after dropping a dragged text element:
![Screen Shot 2021-07-12 at 12 44 34 PM](https://user-images.githubusercontent.com/20525523/125325484-fbe3f500-e30e-11eb-97ef-cbba28507770.png)

Or ~0.5s delay after click when navigating to a different page:
![Screen Shot 2021-07-12 at 12 44 14 PM](https://user-images.githubusercontent.com/20525523/125325602-1ddd7780-e30f-11eb-912a-f5b26d942b11.png)

We can detect and monitor these with the [Event Timing](https://github.com/WICG/event-timing) performance API. For example, try running this in console and playing with the editor:
```js
const performanceObserver = new PerformanceObserver((entries) => {
  for (const entry of entries.getEntries()) {
      // The amount of time that it takes for all event handlers of this event to run.
      const handlersDuration = entry.processingEnd - entry.processingStart;
      console.log('EventTiming', entry.name, handlersDuration, entry.target);
  }
});
performanceObserver.observe({entryTypes:['event']});
```

Selecting and moving a text element prints:
```
EventTiming click 242.3400001525879 <span style=​"font-weight:​ 700;​ color:​ #fff9ee">​Food & Stuff​</span>​
EventTiming mousedown 241.39999985694885 <span style=​"font-weight:​ 700;​ color:​ #fff9ee">​Food & Stuff​</span>​
EventTiming mouseup 815.1800000667572 <span style=​"font-weight:​ 700;​ color:​ #fff9ee">​Food & Stuff​</span>​
```

I haven't tried it yet but here's an article for mapping event entries to specific user actions: https://phabricator.wikimedia.org/phame/live/7/post/168/tracking_down_slow_event_handlers_with_event_timing/

To start, we can instrument user actions on the canvas e.g. select element, move element, delete element, add new page, navigate to other page, etc. WDYT?

**Comment by swissspidy** [comment]
Opened these two tickets for looking into the above:

* #8458
* #8459

Using React's native APIs might give more accurate results and avoids having to try to map event entries to specific user actions.
