### ISSUE TITLE
Embed code for non-WordPress sites

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#8158]
## Feature Description
Some users want to embed their Stories on a non-WordPress site using an embed code (i.e. as you would get from YouTube).

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
It's a very interesting feature request!

I wonder if we could present users just some basic HTML snippet to display the story in an amp-story-player.

cc @amedina

**Comment by swissspidy** [comment]
Closing due to low priority. Users can use the WP oEmbed embed codes meanwhile.
