### ISSUE TITLE
Add `rel=canonical` link for drafts

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8162]
## Feature Description

When previewing drafts, users will see `Missing URL for attribute 'href' in tag 'link rel=canonical'.` warnings in the preview mode.

This is because WordPress's [`rel_canonical()`](https://developer.wordpress.org/reference/functions/rel_canonical/)/[`wp_get_canonical_url`](https://developer.wordpress.org/reference/functions/wp_get_canonical_url/) function does not print a canonical tag if a post is not published.

This is confusing.

Example: https://wordpress.org/support/topic/coding-error-with-my-web-story/

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

We should update `Canonical_Sanitizer` to use `get_permalink()` instead of `wp_get_canonical_url`.

**Comment by swissspidy** [comment]
@westonruter Is this perhaps something that has come up before in the AMP plugin?

**Comment by westonruter** [comment]
Yes. The AMP plugin forcibly adds a `link[rel=canonical]` if one was not output by WordPress: 

https://github.com/ampproject/amp-wp/blob/d2d441cf6f1f4e9a7268a9c6e3360be309852a2c/includes/class-amp-theme-support.php#L1425-L1437

**Comment by swissspidy** [comment]
Perfect, thanks! I searched through the codebase but didn't find this bit. Exactly what I was looking for!

**Comment by swissspidy** [comment]
So apparently we already have this 🤦 

Totally forgot that I wrote `Canonical_Sanitizer` for this, presumably based on that code you shared. But of course it doesn't work as expected because it uses `wp_get_canonical_url()`

https://github.com/google/web-stories-wp/blob/21b8eaaf30ff63c82a5aea77d9f6911faf88ca57/includes/AMP/Canonical_Sanitizer.php#L76
