### ISSUE TITLE
Ad Manager Integration: support child network slot IDs

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8164]
## Feature Description

In [Multiple Customer Management](https://support.google.com/admanager/topic/9470608?hl=en&ref_topic=28152) (MCM), slot IDs can have the format `/1234567,1234/Travel`, where `1234`, represents the network code for the child publisher and `1234567` represents the parent network code. ([example](https://support.google.com/admanager/answer/9579170?hl=en))

The regex on the settings page does not currently support this:

![Screenshot 2021-07-01 at 21 12 28](https://user-images.githubusercontent.com/841956/124177841-13221780-dab1-11eb-8db4-d1cbfe47c8ff.png)

It should be trivial to update the regex in `validateAdManagerSlotIdFormat` from `^\/\d+(\/[\w_-]+)*$` to `^\/\d+(,\d+)?(\/[\w_-]+)*$` to make that work.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
