### ISSUE TITLE
'Filters' effect issue for rounded edges - Mask/Shapes and Images

### ISSUE THREAD

**Issue by ganeshkerkar** [GoogleForCreators/web-stories-wp#8170]
## Bug Description

Filters (Tint, Linear and Vignette) does not follow the rounded corner images, rather extends at the corners.

## Expected Behaviour

It should only apply to the visible part of the image/mask.

## Steps to Reproduce

Upload an image with rounded corners or mask image into a rounded corner shape and apply any filter. ie: Tint, Linear and Vignette.

## Screenshots

_Image 1_
![linear-filter-tint-01](https://user-images.githubusercontent.com/17949658/124128251-368d9800-da9a-11eb-9282-144b800616f0.png)

_Image 2_
![linear-filter-linear-02](https://user-images.githubusercontent.com/17949658/124128262-3beae280-da9a-11eb-8744-4b80da6381a0.png)

_Image 3_
![linear-filer-vignette-03](https://user-images.githubusercontent.com/17949658/124128276-3e4d3c80-da9a-11eb-9973-1f184c1eafbf.png)

_Image 4 (Story preview after publishing)_
![linear-filer-04](https://user-images.githubusercontent.com/17949658/124287091-3f9b6980-db6d-11eb-9a52-0de618659bcd.png)

## Additional Context

- Plugin Version: 1.9.0-alpha.0
- WordPress Version: 5.7.2
- Operating System: MacOS Catalina - Version 10.15.7
- Browser: Chrome - Version 91.0.4472.106 (Official Build) (x86_64)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
cc @miina

**Comment by csossi** [comment]
Verified in QA

(7360 is a separate issue addressing very slight whitespace along edges)
