### ISSUE TITLE
Video optimization checklist error and video quality

### ISSUE THREAD

**Issue by ganeshkerkar** [GoogleForCreators/web-stories-wp#8171]
## Bug Description

- When video is uploaded using 'upload' button the video does not auto optimize, but if we drag the video into the editor space it does show a tool tip saying 'video is optimizing' and checklist does not throw any error for this video.
- However, inspite of having used the recommended video size of 720p, the checklist throws an error recommending to use optimised video. This is only if you upload via 'upload' button.
  - If we optimize video using the button provided in the checklist space, the video looses its quality quite a bit.
  - Also, once optmized it deletes the original video and makes a copy with the name 'unnamed-file.mp4' instead of retaining the original filename _(refer the image below)_

## Expected Behaviour

- Video optimization should happen when the video is either dragged into editor space directly or uploaded via 'upload' button.
- The optimized video obtained after using the optimized video from the checklist space should not compromise the video quality a lot and retain the original file name.

## Steps to Reproduce

- Try uploading video of 720p or lesser using 'upload' button in the left panel. Use the video on one of the story page and look for the error under checklist space.
  - If the checklist throws an error try to use the 'optimize video' button from the checklist space to check the video quality in the preview after publishing. To check the file naming you will have to check the media library _(refer the image below)_

## Screenshots

![video-01](https://user-images.githubusercontent.com/17949658/124289093-8d18d600-db6f-11eb-9aad-d20941091be1.png)
## Additional Context

- Plugin Version: 1.9.0-alpha.0
- WordPress Version: 5.7.2
- Operating System: MacOS Catalina - Version 10.15.7
- Browser: Chrome - Version 91.0.4472.106 (Official Build) (x86_64)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Thanks again for flagging this!

> Video optimization should happen when the video is either dragged into editor space directly or uploaded via 'upload' button.

As mentioned in our meeting, this will be addressed in v1.9 of the editor.

I'll therefore focus on the incorrect file name & the significant loss of quality.

**Comment by swissspidy** [comment]
> When video is uploaded using 'upload' button the video does not auto optimize, but if we drag the video into the editor space it does show a tool tip saying 'video is optimizing' and checklist does not throw any error for this video.
> 
> Video optimization should happen when the video is either dragged into editor space directly or uploaded via 'upload' button.

Just re-reading this again.

Right now, videos uploaded via the 'Upload' media modal will only get optimized once they are inserted into the editor. That is expected.

Directly optimizing them _while_ uploading through the media modal is tracked in #7469, but not a priority right now.

> If we optimize video using the button provided in the checklist space, the video looses its quality quite a bit.

Created a new ticket for this: #8233

> Also, once optmized it deletes the original video and makes a copy with the name 'unnamed-file.mp4' instead of retaining the original filename (refer the image below)

Created a new ticket for this: #8234
