### ISSUE TITLE
Bugfix: Checklist Panel Focus Border

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#8175]
The panel buttons inside the checklist are getting their focus states buried. This ticket is to fix that so that the focus outline is present around the button for each panel section. 

<img src="https://user-images.githubusercontent.com/22185279/124328235-7a3ddb80-db46-11eb-8a04-e98b9ce2f5b7.gif" height="350px" />

---

Background:

The container has `overflow: hidden` so the focus border (box shadow) falls out of the visible content. However, if we change that to `overflow: visible` then the animation breaks because the panels animate in from the bottom. Tricky tricky.

## Acceptance Criteria
- when using keyboard to go through new checklist the categories (priority, accessibility, design) should all have a full blue border now (see PR for demo)

**Comment by maxyinger** [comment]
🤔  I'm wondering if we can just shrink the width of the button a couple pixels and kinda add some outside padding so visually it looks the same, but there's room for the focus border to appear within the given width of the popup. Gotta look into the panels a bit more to know if this is an easy win. @samwhale any thoughts on this approach with the existing setup?

Everything else I can think of might alter how these panels are set up layout wise more significantly 🤷

**Comment by samwhale** [comment]
> 🤔 I'm wondering if we can just shrink the width of the button a couple pixels and kinda add some outside padding so visually it looks the same, but there's room for the focus border to appear within the given width of the popup. Gotta look into the panels a bit more to know if this is an easy win. @samwhale any thoughts on this approach with the existing setup?
> 
> Everything else I can think of might alter how these panels are set up layout wise more significantly 🤷

This would be good to explore. Our current 'focus' solution uses `box-shadow` which is ignored when calculating space since it lives outside of the element's frame. This ends up being annoying when we're using animations or needing to hide any overflow.

If we can fix this across the board for buttons then I think that would save us a lot of future pain when dealing with overflow stuff 😄

**Comment by csossi** [comment]
Verified in QA
