### ISSUE TITLE
Performance: Deep dive into the initial render

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#8185]
## Task Description
In the performance-specific bug bash, there were reports of the initial render being slow (e.g. when reloading a page / creating a new story). The goal of this task is to investigate the first render more thoroughly and profile different components to figure out:
- How much time different parts of the editor take to render
- What are the components taking more time (or re-rendering more times than needed)
- Determine the places that can be improved.

The task should result in:
- Performance testing results for areas / components.
- Follow-up issues for improvements.

## Findings / potential areas for improvement

1. Dynamic imports / `React.lazy` for libraries that are not required for the initial render when possible.
There are a few libraries that could be imported lazily, for example when on hovering or focusing on the button that would run the logic actually requiring the library. Such imports include (but are not limited to):
- `html-to-image`
- `react-color` (needed for the color picker only)
- `draft-js` (seemingly needed for text elements only)
- `colorthief` (could be loaded only when starting to use, that's happening in the background anyway)
- `react-calendar` (used for the calendar only)
- `react-moveable` (not needed for the initial render)

Note: some of these that we know are going to be used, could be used with `webpackPrefetch: true`

Added issue: #8251 

2. The content of the inactive tabs (both in the library and inspector) seems to take some seconds when initially loading the editor. Skipping that initially would improve the situation, Morten already created an issue for it: #8196

3. Consider using Web Workers for more expensive calculations. For example, `getPrepublishErrors` seems to run 3 times when loading initially, each of those times it took 60+ms when testing with just one element on the page. Perhaps all this could be done using Web Worker. When there are more elements on the page, it can take 1+ seconds.
Other potential places could be:
- average color calculation with `ColorThief` (need to check if it's possible since Web Workers can't access the DOM;
- color contrast calculations that will be related to the Smart/easier text.
Needs a discovery issue.

Issue created for following up: #8253

4. Skeleton for thumbnails, also Page.
Currently, the editor layouts shift / jump when more elements get loaded. This would look better using placeholders for the elements while they're still loading. One bottleneck for performance for the initial render is currently the carousel (page thumbnails). These are not really required for the initial render though and placeholders for the page previews could be displayed. Morten had the interesting idea of displaying the average color of the background (see `useAverageColor`) as the placeholder.

Added issue: https://github.com/google/web-stories-wp/issues/8254

5. Page rendering time
It looks like when there are many elements on the page, rendering the current page itself can take quite a lot of time.
Note: When testing with `React.Profiler`, it showed that the `FrameLayer` seems to take approximately the same time to render as the `DisplayLayer`. `FrameLayer`, however, is not really needed until the user starts interacting with the editor. Perhaps there's a way to improve the performance of rendering the Page, this would need a more thorough look into.

Added issue: https://github.com/google/web-stories-wp/issues/8255

**Comment by miina** [comment]
Related improvement: https://github.com/google/web-stories-wp/issues/8196

**Comment by miina** [comment]
The following issues have been created to improve the initial render time and general performance:
- #8251 - 
- #8253 - 
- #8254 - 
- #8255 -

(None of these are sized / prioritized yet.)

Other main places that require improvement already have issues (such as Text Sets, Page Templates, Pre-Publish checklist has already been improved meanwhile, and #8196 is being worked on already as well)

These issues might be a good start for improving the performance, so we could perhaps close this discovery issue as completed and start with the improvements. We can do a performance comparison within each of these issues (before/after).

I'd suggest pulling #8251 into this sprint since that should be ready to worked on without additional discovery and could make quite a difference.

@barklund / @choumx / @swissspidy Let me know if you have any thoughts / suggestions.

**Comment by dreamofabear** [comment]
Lazy loading 3P libraries sounds promising. How large is each of these?

- html-to-image
- react-color
- draft-js
- colorthief 
- react-calendar
- react-moveable

**Comment by miina** [comment]
Checking quickly from [this site ](https://bundlephobia.com/) then the minified / minified + gzipped bundle sizes are as following:
- html-to-image 13.7kB / 4.5kB
- react-color 143.1 kB / 36.3kB
- draft-js 217.3 kB / 64.9kB
- colorthief 6.4kB / 2.6kB
- react-calendar 52.3kB / 11.3kB
- react-moveable 166.5kB / 52.2kB

There are some additional packages that can be lazy-loaded (e.g. `sat` and some other `draft-js` related packages) but these should be the larger ones, I think.

**Comment by miina** [comment]
Closing this issue, follow-up GH issues have been created.
