### ISSUE TITLE
E2E tests: Flaky Preview with development mode screenshot

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#8187]
## Bug Description

Seeing lots of different from the "Preview with development mode" preview in percy. 

[Example](https://percy.io/google/web-stories-wp-e2e/builds/11335762/changed/636946677?browser=chrome&browser_ids=14%2C16&subcategories=approved&viewLayout=side-by-side&viewMode=new&width=1600&widths=1600)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Looks like we need to await some more selectors or wait for networkidle or something.

ALternatively, we can also remove the screenshot and just check for the presence of some string(s) to verify that the debug mode has loaded successfully.
