### ISSUE TITLE
Page and thumbnail area show transparent lines sometimes

### ISSUE THREAD

**Issue by pbakaus** [GoogleForCreators/web-stories-wp#819]
## Bug Description

Sometimes ugly transparent lines appear.

## Expected Behaviour

The user should *never* see a transparent line, anywhere, on the edge of page and thumbnails. Probably easy to fix by using `Math.ceil` as opposed to `Math.round` or `floor`.

## Steps to Reproduce

Drag some background into the page. Doesn't always happen, it seems to be a rounding bug.

## Screenshots

![image](https://user-images.githubusercontent.com/43004/77701688-22441c80-6f74-11ea-8746-7507f3b0a5e8.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by wassgha** [comment]
Duplicate https://github.com/google/web-stories-wp/issues/796
