### ISSUE TITLE
Discourage use of animated gif for poster / publisher logo

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#8193]
## Feature Description

As part of https://github.com/google/web-stories-wp/pull/7528 as a new [isAnimatedGif](https://github.com/google/web-stories-wp/blob/try/gif2video/packages/media/src/isAnimatedGif.js) was added to determinant if a gif is animated or not. We could use this when determinant if an image selected for poster / publisher logo, is animated and discourage users from use this image. This could be done via showing a snackbar message or PPC item. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Interesting idea! So far I am not aware of any cases where we encountered animated GIFs being used there, but if it becomes an issue this util could easily be used for that.

**Comment by swissspidy** [comment]
Closing for now for the reason stated above. We can reopen if this becomes an issue.
