### ISSUE TITLE
Performance: Change tab panels to only render current tab + manual activation for a11y

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#8196]
## Feature Description

This changes the tab implementation from "selection follows focus" with all panels preloaded in the DOM to "manual activation" as per WAI-ARIA guidelines.

This allows us to lazy-load initially inactive tabs + reduces initial render. It also improves keyboard navigation, as you can now switch from tab 1 to tab 4 without waiting for intermediate tabs to render. Instead, it requires the user to manually activate the fourth tab after moving focus there.

## Alternatives Considered

Current implementation is the primary alternative, but it's already being circumvented in some places.

## Additional Context

* [WAI-ARIA Authoring Practices 1.1 §6.4](https://www.w3.org/TR/wai-aria-practices-1.1/#kbd_selection_follows_focus)
* [_Example of Tabs with Manual Activation_](https://www.w3.org/TR/wai-aria-practices-1.1/examples/tabs/tabs-2/tabs.html) from WAI-ARIA Authoring Practices demo implementations.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by merapi** [comment]
> reduces initial render

From what I see it also improves responsiveness for some basic actions (#8259), here is the DND case (without that change it re-renders some expensive and completely unnecessary elements at that time like Text Sets or Document pane).

https://user-images.githubusercontent.com/21036224/126764375-6093867d-df5c-48e7-a0a0-9e1dbc3fbb65.mov

**Comment by swissspidy** [comment]
> without that change it re-renders some expensive and completely unnecessary elements at that time

This reminds me of https://github.com/google/web-stories-wp/pull/8316#discussion_r669428350

When dragging an element its dimensions change, causing `currentPage` (which contains `elements`) and some other variables to change.

For text sets and the like we use Moveable, which relies on on those. So whenever you drag an element, all Moveable components in the library re-render...

**Comment by csossi** [comment]
Verified in QA
