### ISSUE TITLE
Blocks: Story not muted after closing lightbox

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8206]
## Bug Description

As per [this report](https://wordpress.org/support/topic/videos-from-media-gallery-keep-playing-after-web-story-is-closed/), stories are not correctly muted when viewing them in the lightbox on the frontend.

## Expected Behaviour

Sound should be muted after closing lightbox.

## Steps to Reproduce

1. Insert carousel Web Stories block
2. View block on frontend
3. Click on a story within the carousel which has sound/video
4. Unmute story
5. Close lightbox
6. Notice that sound is not muted

## Additional Context

- Plugin Version: 1.8.1
- WordPress Version: 5.8
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
