### ISSUE TITLE
Media Library: Hide edit/delete options if lacking permissions

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8221]
## Feature Description

Originally reported in https://github.com/google/web-stories-wp/issues/7755#issuecomment-849804718

Users with the "Contributor" role are shown options to edit and delete items in the media library on the left hand side, but because they don't actually have permissions to do that it doesn't work of course.

We should hide the "..." menu if the user does not have permission to edit media.

I suppose checking for `hasUploadMediaAction` is good enough for now, but ideally this is better handled by #8276 in the future.

## Additional Context

Current behavior:

https://user-images.githubusercontent.com/841956/119869314-5fad8c80-bf20-11eb-933f-4f7e2a0ddb29.mov

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA

**Comment by miina** [comment]
@swissspidy Shouldn't the `Edit` option still be available (as that wouldn't be restricted by upload permissions)?

**Comment by swissspidy** [comment]
@miina No, since WordPress requires the `upload_files` capability for editing attachments.
