### ISSUE TITLE
AMP Sanitization: Make `amp-story[publisher]` check less strict

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8224]
## Feature Description

The Web Stories plugin currently removes the `amp` attribute from the `<html>` element if some required metadata is missing, such as the publisher name (`amp-story[publisher]`).

We do this in order to prevent errors from surfacing in GSC if users are already made aware of these issues elsewhere (e.g. through the pre-publish checklist).

However, in this particular case there are two issues with that:

1. An empty `amp-story[publisher]` is still valid AMP.
1. There's no pre-publish checklist warning for a missing publisher name

This leads to lots of confusion because creators don't know why the `amp` attribute is missing and thus making their stories invalid AMP documents.

### Proposed solution

For this reason, I think we should not remove the `amp` attribute if there's no publisher name.

**Consequences:**

Sites without a publisher name will now be properly recognized as valid stories.

Stories surfaced on Google won't have a publisher name though (what is shown instead?)

## Alternatives Considered

1. Add pre-publish checklist item for missing publisher name
2. Continue current practice

## Additional Context

Note: The publisher name can be missing/empty if the site doesn't have a site name set in WordPress under Settings -> General.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
cc @o-fernandez @choumx @shishirm - I created this ticket in the context of Shishir's AMP validation issues rundown email.

I have a patch ready for the proposed solution, but would like to hear your opinion on it + the possible alternatives.

**Comment by o-fernandez** [comment]
> We do this in order to prevent errors from surfacing in GSC if users are already made aware of these issues elsewhere (e.g. through the pre-publish checklist).

I may be missing historical context here, so let me know if there are good reasons to do this. Otherwise, I don't think we need to do this - if the user sees it in both GSC and in the PPC/in the editor that's OK. I'd rather they see it on both sides than to miss issues. 

Re: adding to the PPC, we could, but we can treat that as a separate ask. In general our PPC has too many checks and we're trying to keep it to only high importance items (causes invalid stories or glaring errors/issues in the consumption experience.) LMKWYT.

**Comment by swissspidy** [comment]
> > We do this in order to prevent errors from surfacing in GSC if users are already made aware of these issues elsewhere (e.g. through the pre-publish checklist).
> 
> I may be missing historical context here, so let me know if there are good reasons to do this. Otherwise, I don't think we need to do this - if the user sees it in both GSC and in the PPC/in the editor that's OK. I'd rather they see it on both sides than to miss issues.

This practice originates from the AMP plugin and is intended to not serve dirty AMP (an invalid AMP document), but rather a non-AMP document (intentionally not valid AMP) that contains the AMP runtime and AMP components. This way GSC does not complain about a validation error already surfaced inside of WordPress, which originally resulted in user confusion and caused lots of support requests.

In practice, tickets like this one right here and also some recent support requests through the creator program indicate that actually the opposite is true.

So I tend to agree; we don't need to do this. We can remove this logic and then see how it goes 👍
