### ISSUE TITLE
Video Optimization: resulting dimensions too small

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8233]
## Bug Description

Splitting this out from #8171 

**Original video** (2160x4096 MP4, H.264):
https://www.pexels.com/video/restaurant-man-coffee-bar-4255450/

**Converted video** (379x720 MP4, H.264):

https://user-images.githubusercontent.com/841956/124895212-a4771980-dfdc-11eb-9731-0e6b8ea1998f.mp4

## Expected Behaviour

379x720 is very small.

I'd have expected this video to be 720x1365 in size.

The video quality is otherwise quite good IMO. It's just a tad small.

## Steps to Reproduce

1. Upload original video to editor
2. See that it gets cropped to 379x720

## Additional Context

- Plugin Version: 1.9.0
- WordPress Version: 5.7
- Operating System: Chrome
- Browser: macOS

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
