### ISSUE TITLE
UI settings don't persist between reloads

### ISSUE THREAD

**Issue by pbakaus** [GoogleForCreators/web-stories-wp#825]
## Bug Description

UI settings such as collapsed panel states should persist across reloads. The following settings need to persist:

* Panel state (collapsed/open)
* Layer panel height
* Selected page (let's attach this as hash to the current URL, like Google Slides)

The following should not persist:

* Selected tab in design panel
* Selected tab in element panel

/cc @samitron7 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
Related: https://github.com/WordPress/gutenberg/issues/15105

**Comment by miina** [comment]
@pbakaus Should the settings persist when the user closes the story and comes back to it later as well, e.g. the next day? Or would that be just for a specific editing session when reloading and when reopening the story again after closing, it should be in the default state?

**Comment by pbakaus** [comment]
imo the settings should persist across sessions, analogous with almost every other design tool. @samitron7 to confirm (or disagree).

**Comment by ezxyz** [comment]
Should the settings be put in local storage? I'm assuming its across sessions on the same browser (not on different browsers, computers etc).

**Comment by swissspidy** [comment]
Yeah that'd be something for localStorage. Depending on the feedback above we could easily switch to sessionStorage if necessary.

Bonus: extensible  API that supports both, and potentially even persistent storage (e.g. WordPress user profiles) if we'd ever need that.

**Comment by pbakaus** [comment]
+1. We can start with localStorage (I wouldn't do sessionStorage for now, as I predict users might want some level of persistence per browser).

**Comment by samitron7** [comment]
Completely agree to paul's recommendation:

"imo the settings should persist across sessions, analogous with almost every other design tool. @samitron7 to confirm (or disagree)."

**Comment by maxyinger** [comment]
Persists Following:
- Panel state (collapsed/open)
- Layer panel height

https://github.com/google/web-stories-wp/pull/4601

**Comment by maxyinger** [comment]
Persisting active page moved to separate ticket & detailed here:
#4605

**Comment by csossi** [comment]
Verified in QA
