### ISSUE TITLE
Performance: Use dynamic imports

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#8251]
## Feature Description
There are quite a few libraries that we're always importing even though these are not really required for the first render.
It seems like the following libraries don't need to be imported for the initial display of the editor:
- `html-to-image`
- `react-color` (needed for the color picker only)
- `draft-js` (seemingly needed for text elements only)
- `colorthief` (could be loaded only when starting to use, that's happening in the background anyway)
- `react-calendar` (used for the calendar only)
- `react-moveable` (not needed for the initial render)

There might be more. 

Note: If during the implementation it comes out that implementing dynamic import for any of these libraries requires larger effort, feel free to split it out to a separate issue.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief
For libraries that return a component (such as `react-calendar` and `react-moveable`) we can use `React.lazy` and `React.Suspense`, e.g.
```
const loadComp = () => import('lib');
const Comp = React.lazy(loadComp);
...
        <React.Suspense fallback={<div>...</div>}>
          <Comp />
        </React.Suspense>

```
Additionally, for the libraries that are being used only occasionally (like `react-calendar`), we could import the library once hovering over the button/component that uses the library:
`<Button onPointerEnter={loadComp} onFocus={loadComp} />`

For libraries that we know will be most likely used, we can add the `webpackPrefetch` magic comment instead so it will always start fetching when idle:
`const Moveable = React.lazy(() => import(/* webpackPrefetch: true */ 'react-moveable'));`

For libraries that return functions and not components (e.g. `html-to-image`), we can do the following instead:
`import(/* webpackChunkName: "html-to-image" */ 'html-to-image').then((htmlToImage) => {...})`

**Comment by swissspidy** [comment]
> * `react-calendar` (used for the calendar only)

Jonny once experimented with this in #6728.

Never implemented because it would have been the first usage of `lazy`/`Suspense` in our code base and there was no UX for the fallback components (and there still isn't).

But there's really no reason why we shouldn't be using `lazy`/`Suspense` in our code base as much as possible where useful. I think especially in the dashboard there's lots of potential, but also in the editor.

**Comment by csossi** [comment]
Verified in QA
