### ISSUE TITLE
Performance: Consider using placeholders for areas that are slower to render

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#8254]
## Feature Description
When the editor is initially loading, it's loading for quite some time and there is also some jumpiness happening.
For reducing the time for the editor to load, and also to avoid the jumpiness, we could use placeholders at first.
Two places with the most influence would be:
- Page Carousel thumbnails. @barklund also had the idea that instead of just displaying a gray/white rectangle, we could use the background color or the average color of the background media (that's an attribute of the media elements).
- Page. When there are a lot of elements on the page, it takes quite some time to load. Displaying a placeholder meanwhile would remove the jumpiness.

There might be more places, e.g. page templates / text sets.

This would need product confirmation / potentially UX guidelines (for the color of the placeholder).

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@o-fernandez This issue was created related to performance. It should improve the first render time and also the user experience by reducing the jumpiness of the elements when loading the editor.

Since this issue has some user-facing implications and would require basic UX (e.g. which color to use for the thumbnails' placeholders), wanted to confirm with you first.

Thoughts?

**Comment by o-fernandez** [comment]
IIUC, would this just impact the initial editor load time? If so, I'd say that it can be helpful to do this, but I'd first prioritize items that impact the ongoing responsiveness of the editor as the user creates/edits a story, beyond initial load.

**Comment by miina** [comment]
> IIUC, would this just impact the initial editor load time?

Correct, initial only, thanks for your thoughts.

cc @barklund for prioritization / pointing.

**Comment by csossi** [comment]
Verified in QA
