### ISSUE TITLE
Limit checks by user role

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#8257]
## Description

This has come up a few times but we were always aiming for new interactivity or massive design changes so adding this in scope wasn't really ideal. 

We need to limit the checks in the prepublish checklist by user roles so that it's not suggested to fix something that they don't have capabilities to do. 

### Acceptance Criteria 
- Limit the checklist according to user role
- Document what users have the ability to do in the checklist.md doc 
- Add some tests

**Comment by BrittanyIRL** [comment]
@csossi there's really helpful specifications of how to test this in the PR

**Comment by BrittanyIRL** [comment]
hey @csossi - curious if you'll get a chance to look at this before this sprint is over on friday? It's been in the ready for QA column for over a week :(

**Comment by csossi** [comment]
Unable to test this until #8532 is resolved - cannot access a story as contributor

**Comment by swissspidy** [comment]
@csossi how is that even related? This is for the editor, whereas #8532 is a minor inconvenience in the dashboard

**Comment by csossi** [comment]
At this step:
Add a video that is very small with horrible resolution (less than 480px high and 852px wide). You should see Increase video resolution to at least 480p ratio card in the Design panel in the checklist ✅

Added video that was 240X160 (as admin user):
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/dbbc6ba0-b95f-4037-a9d2-e82d3d15067e)

But didn't see "increase video resolution" warning in checklist

**Comment by BrittanyIRL** [comment]
Hey @csossi - So checking for increasing video resolution only shows up if the user has the capability to upload media.  What type of role are you logged in as when you are not seeing this check? Are you seeing it when you are logging in as admin and not when you are a contributor?

**Comment by csossi** [comment]
was logged in as admin, @BrittanyIRL

**Comment by swissspidy** [comment]
So the actual image/video resolution checks were broken, not checking for the right values on a resource. Fixing those now in the PR...

**Comment by samwhale** [comment]
oh nice! I've been looking into those just now too 😓

**Comment by csossi** [comment]
Verified in QA
