### ISSUE TITLE
Perf: Improve responsiveness of basic actions in editor

### ISSUE THREAD

**Issue by dreamofabear** [GoogleForCreators/web-stories-wp#8259]
## Bug Description

From the perf bug bash, we've noticed that there is some noticeable latency for basic actions like element selection, drag+drop, page navigation, etc.

## Expected Behaviour

The editor should respond to user gestures within [50 to 100ms](https://developer.mozilla.org/en-US/docs/Web/Performance/How_long_is_too_long).

## Steps to Reproduce

See https://github.com/google/web-stories-wp/issues/8006#issuecomment-871805740 for context.

## Screenshots

N/A

## Additional Context

- Plugin Version: HEAD
- WordPress Version: 5.7
- Operating System: macOS
- Browser: Safari

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by dreamofabear** [comment]
I think a contributing factor is that selection state is part of the `useStory()` context. The story context has very wide usage and context selectors in callers don't seem to be used consistently which results in needless re-renders. 

A couple examples: checklist items are rerendered on selection changes, template previews are rerendered on drag-start, and the design panel is rerendered on drag-end.

Short-term, fixing context selectors in components that are truly independent of element selection should help. Long-term, it may make sense to refactor selection state into its own context to reduce misuse.

@barklund @BrittanyIRL FYI

**Comment by maxyinger** [comment]
Yea, we have yet to go through all the checks and update the context selectors for them on PPCv2, but I know we need to go through and do this.

@BrittanyIRL is this already being tracked? (not seeing anything in the zenhub board for it) if not, I can create a lil 3 pointer rn

**Comment by BrittanyIRL** [comment]
> @BrittanyIRL is this already being tracked? (not seeing anything in the zenhub board for it) if not, I can create a lil 3 pointer rn

Not tracked yet! Making a new ticket would be great, thanks @littlemilkstudio !

**Comment by maxyinger** [comment]
> Not tracked yet! Making a new ticket would be great, thanks @littlemilkstudio !

On it.

**Comment by maxyinger** [comment]
Ticket here:
https://app.zenhub.com/workspaces/web-stories-5e94d3aced449034e1e9b226/issues/google/web-stories-wp/8289

**Comment by dreamofabear** [comment]
FYI an idea on how we might monitor real-world performance of basic editor actions: https://github.com/google/web-stories-wp/issues/8135#issuecomment-878457280
