### ISSUE TITLE
Oddities with background + media + drop targets

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#826]
## Bug Description

There are bugs happening when using background + media + drop targets of the background.
For example, adding an image to an empty page and then clicking "Remove as background"  and then dragging it resulted in this view "getting stuck":
<img width="308" alt="Screenshot 2020-03-27 at 10 07 44" src="https://user-images.githubusercontent.com/3294597/77740146-03489780-7013-11ea-9e28-90506fd5ad46.png">

Similar behavior happened more but after other actions.

## Steps to Reproduce

Try doing various actions with an image, setting and unsetting it to background and dragging it around.

E.g.
1. Add an image to an empty page
2. Remove as background
3. Add again as background
4. Remove as background
5. Try dragging it around.

Try a few times if the weird stuff didn't start happening yet :)

## Screenshots
![oddity2](https://user-images.githubusercontent.com/3294597/77740676-f0829280-7013-11ea-9039-ff965be05afb.gif)
![oddity](https://user-images.githubusercontent.com/3294597/77740685-f4aeb000-7013-11ea-90f5-ced74974a6db.gif)

One console error:
<img width="1364" alt="Screenshot 2020-03-27 at 10 12 14" src="https://user-images.githubusercontent.com/3294597/77740792-245db800-7014-11ea-90a2-0de7ddcca276.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Looks like new shape elements are unexpectedly created when switching between background and off:
<img width="281" alt="Screenshot 2020-03-27 at 10 44 55" src="https://user-images.githubusercontent.com/3294597/77743280-1ca01280-7018-11ea-99bb-25f3a2721796.png">

cc @wassgha

**Comment by wassgha** [comment]
I believe this was fixed, can you please try to reproduce it?

**Comment by miina** [comment]
Correct, seems to be fixed. Which PR fixed this? Can you add that as a reference as well?
