### ISSUE TITLE
Eyedropper: noticeable latency after clicking the icon

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#8261]
## Bug Description
Discovered in bug-bash.

From Will:
> noticeable, confusing ~1s latency after clicking the eye dropper and before the color overlay appears — a loading indicator/spinner would help!

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA (spinner appearing)
