### ISSUE TITLE
Dashboard: author shown links to open in editor, when they should not

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#8269]
## Bug Description

While logged in as an author, I am shown "open in editor" links, for story I do not have access to edit.

Follow on from https://github.com/google/web-stories-wp/pull/8268

## Expected Behaviour

Options to edit stories that I, an author should be hidden are disabled. 

## Steps to Reproduce

1. Create a story as a admin. 
2. Login as author. 
3. Try to edit the story you just created as an admin. 

## Screenshots

https://user-images.githubusercontent.com/237508/125115186-e25e6580-e0e2-11eb-9a4a-c7233a791207.mov

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Previously reported at https://github.com/google/web-stories-wp/issues/6613#issuecomment-792608150

Suggested robust implementation approach in https://github.com/google/web-stories-wp/issues/6613#issuecomment-796894282

I'll create a dedicated ticket for that + an epic to track this kind of stuff.

**Comment by spacedmonkey** [comment]
The question is how we fix these issues. Do we simply not show the drafts of other users to authors, not this issue invalid, or do we keep all ticket and UX is required to show stories without editor links. 

It is also worth noting that there are rename and delete options that should also not be shown here.

**Comment by spacedmonkey** [comment]
As of https://github.com/google/web-stories-wp/pull/8268 , the `edit_link` is used to render the link to the editor. This field, is conditional depending on if the user has access to edit that story. If `edit_link` is not present, we should not render links to edit it.

**Comment by swissspidy** [comment]
> The question is how we fix these issues. Do we simply not show the drafts of other users to authors,

Not sure I follow. This ticket is about not hiding options, not hiding drafts. Was this comment perhaps intended for #6613?

We should hide all options the user does not have capabilities for. Including delete & rename (edit)

#8276 should make it easier to check all these capabilities

**Comment by spacedmonkey** [comment]
So we have two options to handle users that do not have access to some story. 

#### Option 1 

Tweak the REST API to only return story that the current user can access. A full PHP change with no UX. 

#### Option 2 

Keep the REST API as it is hide / grey out / disable options that the current user do not have access to do. Similar to how WP core does it currently. 

<img width="619" alt="Screenshot 2021-07-13 at 12 04 14" src="https://user-images.githubusercontent.com/237508/125441357-a8f8535b-83fd-4cdb-9812-2f2f790d5975.png">
<img width="491" alt="Screenshot 2021-07-13 at 12 04 25" src="https://user-images.githubusercontent.com/237508/125441368-29a0ce0a-0058-4adc-b366-25cdea64a219.png">


This ticket is for option 2.

**Comment by swissspidy** [comment]
Correct, we want to these remove options if user does not have the capabilities to perform the action(s).

**Comment by csossi** [comment]
Verified in QA
