### ISSUE TITLE
PPC - thumbnails in checklist ignore page background

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#8271]
## Bug Description

Originally reported by @choumx 
page thumbnails in checklist appear to ignore background images (non-background images are OK)
![image3.png](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/ae6d4fe2-9b46-4588-a996-e52e11c80188)
Looks like it might be a container issue in the checklist because the background element is showing up, but it looks like it’s getting pushed off to the side (see below screenshot)
![image6.png](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/cc9b36b4-56df-49b8-84dd-cdb5eceda4c8)

## Expected Behaviour

Page thumbnails should closely resemble their associated pages 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
Related: https://xwp.slack.com/archives/C0134J07HV3/p1625840964040600

**Comment by csossi** [comment]
Verified in QA
