### ISSUE TITLE
Media: Video poster image not always shown in Firefox

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#8272]
## Bug Description

originally reported by @embarks 
After uploading the gif (either via drag and drop or upload)  the poster doesn’t show the media gallery (Firefox, works great in Chrome! Great job) Firefox version: 89.0.2 (64-bit)

![image4](https://user-images.githubusercontent.com/58738530/125128649-4de90880-e0cc-11eb-949a-1f13087d745e.png)

response from Pascal 

> Very interesting Firefox bug! All the data is there correctly in the DOM, yet it somehow does not actually load/display the poster image.
This also seems to happen for videos that were already in the media library, so not specifically related to this new feature.

## Additional Context

- Plugin Version: 1.9.0
- WordPress Version: 5.8
- Operating System: macOS
- Browser: **Firefox**

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Closing this since I think #8449 fixed this for Firefox as well.
