### ISSUE TITLE
Infer User Capabilities from REST API Responses

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8276]
## Feature Description

In the editor and dashboard, we currently pass the current user's capabilities that we need in the app via inline JS / the `ConfigProvider`. This works OK-ish, but does not really scale well.

* Just checking for `can user edit stories` does not work for cases like the dashboard where we need to individually check for capabilities for the stories being displayed.  
  The user could be allowed to edit story X but not Y, so the checks would not be accurate.
* Every enhancement to the React apps requires PHP changes to pass the necessary capability information.

Lucky for us, the [WordPress REST API incorporates hyperlinking](https://developer.wordpress.org/rest-api/using-the-rest-api/linking-and-embedding/) throughout the API to allow discoverability and browsability, loosely based on the [HAL standard](https://en.wikipedia.org/wiki/Hypertext_Application_Language).

For example, the `_links` property of the response object contains a map of links to other API resources, grouped by “relation”. The relation specifies how the linked resource relates to the primary resource.

This includes capabilities! For each story, there is a `wp:action-assign-author` entry under `_links` if the user has the capability. So instead of passing `hasAssignAuthorAction` manually from PHP we can simply look for this entry.

**Note:** the WP Rest API does not currently add links for all actions that we need ([see this example](https://core.trac.wordpress.org/ticket/50388), but extending the REST API to do that is trivial.

So my suggestion:

1. Add new actions to `_links` for things we need
2. When fetching stories from the REST API, check for the `_links` to get the user's capability for each story
3. Use that information to have more granular capability checks

## Alternatives Considered

* [`targetHints`](https://tools.ietf.org/id/draft-handrews-json-schema-hyperschema-00.html#rfc.section.6.5.5) are an interesting idea as well, but not yet available.

## Additional Context

Gutenberg has implemented a really neat [approach](https://github.com/WordPress/gutenberg/tree/a6908dcc4cde747ee2879317597f73179bf6e4d1/packages/core-data#canUser) for this.
  Essentially, one calls a Redux selector to see whether the current user can perform the given action on the given REST resource.
  If the information hasn't been fetched yet, an `OPTIONS` request to the REST API is triggered via the `canUser()` resolver (basically a middleware that only runs once).

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
@spacedmonkey would love your input on this / the suggested approach

**Comment by csossi** [comment]
Verified in QA
