### ISSUE TITLE
Dashboard: Add loading screen

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#8280]
## Feature Description

When the dashboard is loading is a primitive loading screen is displayed, showing the words, "Please wait..." with a white background.

![Screenshot 2021-07-07 at 15 27 56](https://user-images.githubusercontent.com/237508/125261581-4b1f2b00-e2f9-11eb-8a7f-6215d2f24afb.png)

Styling on this loading page should improved, not only to make it look a little nicer, but also adds some sort of loading animation / progress bar ( that does not need to be actuate ), to give the user some feeling like that "something" is happening, to improve user's perception of speed of the application.

Follow up from https://github.com/google/web-stories-wp/issues/8279

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
@csossi  - this just updates the visual of the loading screen. 

it should match the screenshots of 'after' attached to the PR

**Comment by BrittanyIRL** [comment]
weird, so the build didn't finish. try again?

**Comment by csossi** [comment]
Verified in QA
