### ISSUE TITLE
Dashboard: remove usage of `getResourceFromLocalFile`

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8281]
## Task Description

The Dashboard currently imports `getResourceFromLocalFile` from `edit-story` just to display some images in the storybook demo in 1 place:

https://github.com/google/web-stories-wp/blob/ade355fc27631eab4484499683c86dd93d606bd4/assets/src/dashboard/utils/index.js#L33-L34

https://github.com/google/web-stories-wp/blob/ade355fc27631eab4484499683c86dd93d606bd4/assets/src/dashboard/app/views/editorSettings/publisherLogo/stories/index.js#L44-L50

There's really no need for this.

This could be simplified easily to this:

https://github.com/google/web-stories-wp/blob/f02da9e83a879b316e31b7d13bd62bd1dc8c9014/packages/dashboard/src/app/views/editorSettings/publisherLogo/stories/index.js#L53-L66

**Comment by spacedmonkey** [comment]
We could also just move this function to media package...

**Comment by swissspidy** [comment]
I thought about that, but for now I'd like to keep the various `getResourceFrom*` functions all in the editor as long as they are not really needed anywhere else.

In this case here the function was just imported out of convenience and it's really only a storybook util and no code that actually deals with Resource objects. So I prefer the suggested approach above.
