### ISSUE TITLE
Media: Remove usage of `title` attribute on resources

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8286]
## Feature Description

Historically, the `Resource` type in the editor has had both a `title` and an `alt` field as those are provided by WordPress out of the box.

However, they are somewhat confusing, so we've actually phased out usage of `title` at some point. For example, the "Accessibility" panel only allows editing the `alt` attribute of a resource. The media edit dialog in the library also only updates `alt`. On the frontend, we populate `title` and `alt` with the same data from the `alt` field.

There are a few places where `title` is still being referenced though (not a complete list):

https://github.com/google/web-stories-wp/blob/c13aa78cb5319e026555bdab74b0cf3975c01bf8/assets/src/edit-story/elements/gif/output.js#L43

https://github.com/google/web-stories-wp/blob/c13aa78cb5319e026555bdab74b0cf3975c01bf8/assets/src/edit-story/app/media/utils/useProcessMedia.js#L37-L55

https://github.com/google/web-stories-wp/blob/c13aa78cb5319e026555bdab74b0cf3975c01bf8/packages/media/src/createResource.js#L96

https://github.com/google/web-stories-wp/blob/c13aa78cb5319e026555bdab74b0cf3975c01bf8/packages/media/src/createResource.js#L125

We should:

* Remove `title` from the `Resource` type and `createResource`
* Do not use `title` from resources anywhere
* Add data migration to remove `title` from resources in all stories (and thus also templates)

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
https://github.com/google/web-stories-wp/blob/0cdbf8ea909b850a140b05b04390b6f42442e87b/assets/src/edit-story/app/media/utils/useProcessMedia.js#L154-L157

https://github.com/google/web-stories-wp/blob/0cdbf8ea909b850a140b05b04390b6f42442e87b/assets/src/edit-story/app/media/utils/useProcessMedia.js#L234-L240

https://github.com/google/web-stories-wp/blob/0cdbf8ea909b850a140b05b04390b6f42442e87b/assets/src/edit-story/app/media/utils/useProcessMedia.js#L302

Title is used in all these places, to copy data from old version to a transcoded/converted/muted version of video. 

Also, the title seems to be used in this screen. 

<img width="1904" alt="Screenshot 2021-08-06 at 17 05 05" src="https://user-images.githubusercontent.com/237508/128539434-cb4c396d-fa1a-4954-8ed3-6039b7917253.png">

Also, the title is used for searching. It is useful to be able label a image or video with the editor.

**Comment by swissspidy** [comment]
> Title is used in all these places, to copy data from old version to a transcoded/converted/muted version of video.

Let‘s stop copying that then

> Also, the title seems to be used in this screen.

I think that uses the alt text

> Also, the title is used for searching. It is useful to be able label a image or video with the editor.

Search happens on the server though, so not related?

**Comment by spacedmonkey** [comment]
> Let‘s stop copying that then 

I think we should still copy this data, but copy it server level. I am going to try and prototype and I see it if works. Out.
