### ISSUE TITLE
Enable Editing Text as soon as Text Box is in Focus

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#830]
## Bug Description

The default rules for selecting and editing text are not applied as specified in [figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=2625%3A7057)

When a user adds text, they see the hint within the text box (fine):
![image](https://user-images.githubusercontent.com/5874851/77761783-ef029b80-700e-11ea-8627-deb65fa04240.png)
But when they click within, they have to manually delete or overwrite this tip ("Double-click..."). Should the tip automatically "clear" when user clicks within the field?

Note: This issue does not deal with automatically enabling edit-mode when a new text field is added. This is only about being able to type while text box is in focus to edit content.

Reported by Claudio on #576
## Expected Behaviour

1. You should be able to just start typing once the text box is in focus

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### Alphanumeric: Replace with new content
1. Add a text field
1. Unselect and reselect the text field using the mouse to make sure it has keyboard focus
1. Type any alphanumeric character and observe text field going into edit mode with only the typed character (NB: this only supports a-z and 0-9)

### Enter: Select content
1. Add a text field
1. Unselect and reselect the text field using the mouse to make sure it has keyboard focus
1. Press <kbd>enter</kbd> and observe text field going into edit mode with all the currently present content selected and ready to be replaced by whatever is typed next. Also observe, that no actual newline is inserted despite pressing <kbd>enter</kbd>

**Comment by swissspidy** [comment]
Related: #1608

**Comment by csossi** [comment]
tested in QA Environment PR#2183

re: Instructions above
> ### Alphanumeric: Replace with new content
> 1. Add a text field
> 1. Make sure it is selected
> 1. Type any alphanumeric character and observe text field going into edit mode with only the typed character (NB: this only supports a-z and 0-9)

Not working as described here. selected text element:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/a6d49f19-ce13-4f28-b95f-8b0ecd95e11d)

And when I began typing, it looked like this - just seeing a horizontal line:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/56772835-f9f9-4a5c-a7e5-e7e379681f34)

**Comment by obetomuniz** [comment]
Hey @csossi, could you check it again using the PR#1810 env? At least, that's was the env that I addressed this issue, not PR#2183. Let me know if you have any doubt 😄

**Comment by csossi** [comment]
Verified in QA - thanks, @obetomuniz

**Comment by samitron7** [comment]
Verified in UAT
