### ISSUE TITLE
Text box not resizing on increasing font size

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#831]
## Bug Description

when replicating, create text that is a single line
https://drive.google.com/file/d/1sSdxD4DOqRi6BPjFd9TJsU1jvIyCVolm/view

Reported by Claudio on #576

## Expected Behaviour

The text box should grow with the size and the text should never be cut off.

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by dmmulroy** [comment]
This appears to have been resolved

![gif-recording](https://images.zenhubusercontent.com/5ed1482c796b702933b1c4b9/e8392eb2-016b-40bb-8283-7700daa7b725)
