### ISSUE TITLE
Eyedropper: #FFF color appearing for no reason over a solid color.

### ISSUE THREAD

**Issue by merapi** [GoogleForCreators/web-stories-wp#8312]
## Bug Description

From Claudio: Finding the eyedropper a little cumbersome to use. As I move it around a solid colour, I see flickers of #FFF appearing (if user inadvertently selects, colour selected will be white) and it requires user to be precise in selection. See video

https://share.getcloudapp.com/X6uAXXDG

When the full 6-digit code appears and user selects, everything's working fine - it just ain't pretty.

## Steps to Reproduce

I cannot reproduce it (tried Chrome/Safari on MacOS).
@csossi can you update the issue with OS/browser you used? is it on Windows? (cursor color). Does it also happen over an image? And what about if you change the BG to #000, does #000 flicker?

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Closing this a not able to repro it (Marcin also wasn't).

We can reopen if this gets reported again.
