### ISSUE TITLE
Failed thumbnail video optimization snackbar message

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#8315]
## Bug Description

If poster fails to generate and then the video optimization fails, the snackbar message looks broken. 

## Screenshots

<img width="768" alt="Screenshot 2021-07-13 at 12 44 13" src="https://user-images.githubusercontent.com/237508/125446462-200305ca-ada5-4c97-9a1d-a2e083f41191.png">

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
Added in https://github.com/google/web-stories-wp/pull/8079. CC @embarks

**Comment by swissspidy** [comment]
If you inspect the element in the dev tools, what's the image being displayed? 

I see two things we can optimize here:

https://github.com/google/web-stories-wp/blob/42b3d4249feedcd08a52bb6d0a9aa305e82df6d7/assets/src/edit-story/app/media/useUploadMedia.js#L169-L172

1. Check if `src` actually exists
2. Add `isBlobURL` checks

So it could look like this:

```js

const thumbnailSrc = ['video', 'gif'].includes(resource.type) ? resource.poster : resource.src;

// ...

thumbnail: thumbnailSrc && !isBlobURL(thumbnailSrc) && {
  src: thumbnailSrc,
  alt: resource?.alt,
},
```

**Comment by spacedmonkey** [comment]
<img width="678" alt="Screenshot 2021-07-13 at 15 19 15" src="https://user-images.githubusercontent.com/237508/125468564-6f76cb42-2118-46a6-bb63-f854d6c067db.png">

No the poster seems undefined. 

It also seems to generate some warnings and errors. 

<img width="464" alt="Screenshot 2021-07-13 at 15 19 40" src="https://user-images.githubusercontent.com/237508/125468707-1a879001-63c8-44dd-9107-86346733d8be.png">

<img width="872" alt="Screenshot 2021-07-13 at 15 19 44" src="https://user-images.githubusercontent.com/237508/125468734-20250712-a28a-43d2-8481-b328ed8a16da.png">

**Comment by swissspidy** [comment]
Great, then my code suggestion from above should fix this

**Comment by spacedmonkey** [comment]
Here is my workaround https://github.com/google/web-stories-wp/commit/1fc178086d0353ed7d5acbebb77fc590bb662643

It also adds support for failed image uploads as well. 

If we add a check for if is bloburl, then the likelyhood is the poster / image will never be displayed. At this point in the code, the only poster image will be a blob.

**Comment by spacedmonkey** [comment]
<img width="1904" alt="Screenshot 2021-07-13 at 15 53 41" src="https://user-images.githubusercontent.com/237508/125474270-ba321e7a-969a-48e7-adad-be4eccbe0552.png">
I forced an error after transcoding to see what happened. Here is a screenshot of it in action.

**Comment by swissspidy** [comment]
> At this point in the code, the only poster image will be a blob.

The blob URLs of failed uploads will be revoked using `revokeBlob` / `revokeObjectURL`, so they would not work anymore.

**Comment by spacedmonkey** [comment]
^ But this example works?

**Comment by swissspidy** [comment]
Looks like there's a missing `revokeBlob` call in `removeItem()` in `useMediaUploadQueue` then. That should be added to ensure proper cleanup.

But yeah I suppose if we remove the `isBlobURL` check for now this can be simplified like this:


```js
const thumbnailSrc = ['video', 'gif'].includes(resource.type) ? resource.poster : resource.src;

// ...

thumbnail: thumbnailSrc && {
  src: thumbnailSrc,
  alt: resource?.alt,
},
```
