### ISSUE TITLE
Document Panel: Story poster displayed with wrong aspect ratio

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8323]
## Bug Description

Story portrait posters are at least 640x853 and maintain a 4:3 aspect ratio.

Yet, in the document panel we display the story poster image in 9:16 aspect ratio, which means the image is stretched.

## Expected Behaviour

1. The story poster image is displayed with 4:3 aspect ratio
2. The `<img>` has `width` and `height` attributes

## Steps to Reproduce

1. Add story poster image
2. Inspect thumbnail in dev tools
3. See image is stretched

## Screenshots

![Screenshot 2021-07-13 at 19 17 40](https://user-images.githubusercontent.com/841956/125499994-f461e100-66fd-4dc8-a7b3-1ee0b0434c2c.png)
![Screenshot 2021-07-13 at 19 17 46](https://user-images.githubusercontent.com/841956/125499998-89b6bb65-0364-4a06-9b0f-58752b5f779d.png)

## Additional Context

- Plugin Version: 1.8.0
- WordPress Version: 5.8
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
