### ISSUE TITLE
Dashboard: My Stories Grid Visual Update

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#8325]
## Feature Description

Following #8274 to improve dashboard my stories performance, we should tweak the grid design to better follow the story preview on discovery/search: https://developers.google.com/search/docs/advanced/appearance/enable-web-stories 

## Additional Context

(Copied from https://github.com/google/web-stories-wp/pull/8274#issuecomment-879435996) 
- There's also a translucent scrim between the text and the poster. You can see the canonical example by viewing with mobile emulation: https://www.google.com/search?q=things+to+do+in+nyc

So this would mean that the story title gets pushed up into the grid, the 'open in editor' button that shows on hover is gone now.

Let's keep the author and date below the story so that the context menu that shows up has a place that makes sense still.

While we're here, let's see if there's a way to ditch the `usePageView` hook that's giving the width/height of each grid item based on resize. Seems unnecessary at this point. 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
@choumx what would you like to do about the ability to rename a story? Right now it turns the story name into an input. This would be a _little_ weird to do on top of the story poster.

<img width="438" alt="Screen Shot 2021-07-13 at 3 52 31 PM" src="https://user-images.githubusercontent.com/10720454/125535351-46ca1f48-ed97-4ac7-8811-927dc21e6028.png">

**Comment by dreamofabear** [comment]
Good call out though I think it isn't *too* weird, shall we try it?

**Comment by BrittanyIRL** [comment]
> Good call out though I think it isn't _too_ weird, shall we try it?

We can try it!

**Comment by BrittanyIRL** [comment]
hey @choumx  - got a draft up of a PR for this: https://github.com/google/web-stories-wp/pull/8397#issue-693947183 

Could you take a look at the visual changes I made and let me know what you think?  There's screencasts in the PR. I have a few things left to clean it up but visually it's there. 

@swissspidy or @spacedmonkey - I tweaked the story lock view a little here and it made me wonder - should we disable the ability to rename a story if a story is locked?

**Comment by swissspidy** [comment]
> should we disable the ability to rename a story if a story is locked?

Yes, totally! 👍

**Comment by BrittanyIRL** [comment]
> > should we disable the ability to rename a story if a story is locked?
> 
> Yes, totally! 👍

Great, i'm gonna add that into this then.

**Comment by BrittanyIRL** [comment]
@csossi  there's a lot of details about this and how/what to test in the PR description. This one is part of the upcoming release so if you can get to it sooner rather than later it would be really helpful!

**Comment by csossi** [comment]
Not seeing the avatar appear

Logged in as admin and began editing (in QA environment - story called "Dude"):
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/ebc34629-ab7e-42a4-8ecf-57f2f2cbd6b5)

Logged on at another machine and lock/avatar not appearing:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/4e630429-39de-4f7e-9dfa-a3729ef223a5)

**Comment by BrittanyIRL** [comment]
@csossi - did you turn on the post lock experiment first?

**Comment by csossi** [comment]
@BrittanyIRL - Nope. Retrying

**Comment by csossi** [comment]
Verified in QA
