### ISSUE TITLE
Unable to Remove Mask

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#833]
## Bug Description

No way to remove image from a shape after using drop targets

How can a user remove the image/video from mask if they change their minds? Unless I missed it somehow, I don't see anything in Figma about that
Reported by Claudio on #580 

## Expected Behaviour

UX should be clear on how to remove a masked image/video

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by samitron7** [comment]
There is no intent to remove the image from a mask that is not the page bg. Closing this ticket.
