### ISSUE TITLE
Calendar: time input does not show leading zeros

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#8334]
## Bug Description

Time is not formatted as a two-digit number with a leading zero in the date (time) picker but it is in the publishing bar timestamp.

## Expected Behaviour

A 0 should be added to single-digit timestamps (i.e. 8:05 versus 8: 5) inside the date (time) picker.

## Steps to Reproduce

1. Enter single-digit timestamp with a leading zero in the date (time) picker
2. Close out of the picker
3. Open up the picker and notice the leading zero is no longer there

## Screenshots

![Publishing TIme Format](https://user-images.githubusercontent.com/66372350/125709063-1d5f11c0-1132-4d2b-915b-1c9751c7201a.png)

![PUblishing Time Stamp Field](https://user-images.githubusercontent.com/66372350/125709158-273f81aa-c71c-46b7-a889-48be3ad22da3.png)
![Time Format Settings](https://user-images.githubusercontent.com/66372350/125709168-7dee7818-29ef-4229-868d-d25ed678c2f5.png)

## Additional Context

- Plugin Version: 1.9.0
- WordPress Version: 5.7
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
We allow leading zeros elsewhere in the design panel for numeric inputs and the Gutenberg date picker also shows & allows leading zeros. So seems reasonable to add this for consistency.

cc @miina

**Comment by miina** [comment]
cc @barklund For priority / points.
