### ISSUE TITLE
Performance: Dynamic import for `draft-js`

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#8336]
## Feature Description
This is a follow-up issue for #8251 for `draft-js` specifically that requires a bit more work since it's used in multiple files in the code.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
- `draft-js` is imported dynamically
- Bonus: there might be more modules to import dynamically, if trivial, could go through the list and include some of those, too.

## Implementation Brief

See the original issue (#8251) for details.

**Comment by miina** [comment]
cc @barklund For priority / points.

**Comment by swissspidy** [comment]
Perhaps this is relevant here:

I've experimented with moving draft-js related components to a dedicated `@web-stories-wp/rich-text` package in the past:

https://github.com/google/web-stories-wp/tree/try/next-level-packages/packages/rich-text/src

This might make dynamically importing draft-js easier as there are less entry points.

See #8126
