### ISSUE TITLE
Allow inserting text presets by drag and drop (Moveable)

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#8359]
## Feature Description
Currently, other elements can all be added to the page by dragging and dropping in addition to just clicking on the element.

Text presets, however, can only be added by clicking. For consistency, we should also allow dragging presets onto the page.

## Additional Context
Note that this will influence the smart text color feature since the color calculation needs to be done once dropped.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
cc @barklund For prioritisation.

**Comment by csossi** [comment]
Verified in QA
