### ISSUE TITLE
How To Add Voice Over Files To AMP Webstories Plugin

### ISSUE THREAD

**Issue by DanielCryptoK** [GoogleForCreators/web-stories-wp#8363]
How do I add a voice over file along with music to amp stories? There is no information on the web stories website, in google or on youtube. Can someone make a step by step guide or send me a link or tell me how to do?

**Comment by swissspidy** [comment]
Hi there,

Thanks for your request! The Web Stories WordPress plugin does not yet support adding background audio/sound to stories, but we're considering adding this capability in the future. Please follow #48 for any progress on that.

**Comment by DanielCryptoK** [comment]
That is crazy, how did this web story do it then?

https://www.refinery29.com/stories/how-stuff-is-made-money/

**Comment by swissspidy** [comment]
@DanielCryptoK This story was created with another editor, Newsroom AI, which already has this feature. The Stories format itself definitely supports audio, it's just that the WordPress editor does not yet have a UI for it.

**Comment by DanielCryptoK** [comment]
If I use that plugin as I need voice over, will it rank the exact same way as a story created by googles plugin does, or are there SEO benefits that can only be gained by using Google own plugin?

**Comment by DanielCryptoK** [comment]
The only option available to me to have web stories on their own url and voice over included is $499 per month !!!

Please can you include it in your plugin ASAP or point me in the direction of a much cheaper alternative???
![Pricing](https://user-images.githubusercontent.com/45933242/126147389-cfaf3f50-d82e-47c8-b0ee-3608dbe191f6.png)

**Comment by swissspidy** [comment]
There are no SEO advantages or anything if you use this plugin over any other solutions.

I understand your frustration with this missing feature. Again, please rest assured that this feature is on the roadmap. I just don't have a timeline for when it will be completed though.

If this is super urgent for you, there are also [lots of other tools](https://stories.google/tools/) like MakeStories that might work for you.
