### ISSUE TITLE
GIF not playing with amp-video v1.0

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8364]
## Bug Description

Originally reported for GIF elements at https://wordpress.org/support/topic/gifs-not-showing/.

Turns out the `amp-video` extension was not added by `getUsedAmpExtensions` (where we use version 0.1), so the PHP sanitization automatically loaded version 1.0, which doesn't work.

Reported upstream: https://github.com/ampproject/amphtml/issues/35277

## Expected Behaviour

Video should be playing

## Steps to Reproduce

1. Insert Tenor GIF
2. Preview
3. See no elements visible on the page
4. See `amp-notbuilt` attributes on the `amp-video` element in dev tools

## Additional Context

- Plugin Version: 1.9.0
- WordPress Version: 5.8
- Operating System: macOS
- Browser: Chrome

Console errors:

```
Uncaught (in promise) Error: expected global "bento" or specific "bento-video" experiment to be enabled​​​
```

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
cc @choumx @westonruter

**Comment by swissspidy** [comment]
#8366 is only a partial fix as that will cause v0.1 to be imported when creating a new story.

**Comment by westonruter** [comment]
> so the PHP sanitization automatically loaded version 1.0

This shouldn't be the case. The AMP plugin adds v0.1 as seen in this test: https://github.com/ampproject/amp-wp/blob/d2d441cf6f1f4e9a7268a9c6e3360be309852a2c/tests/php/test-amp-helper-functions.php#L1394

In the consumed spec, `0.1` is marked as the `latest` version: https://github.com/ampproject/amp-wp/blob/d2d441cf6f1f4e9a7268a9c6e3360be309852a2c/includes/sanitizers/class-amp-allowed-tags-generated.php#L18469-L18483

I just tested this by adding the the following markup to a Custom HTML block:

```html
<amp-video autoplay loop
    width="720"
    height="960"
    poster="https://amp.dev/static/samples/img/story_video_dog_cover.jpg"
    layout="responsive">
    <source src="https://amp.dev/static/samples/video/story_video_dog.mp4" type="video/mp4">
</amp-video>
```

This resulted in the following 0.1 script being added to the page:

```html
<script src="https://cdn.ampproject.org/v0/amp-video-0.1.mjs" async="" custom-element="amp-video" type="module" crossorigin="anonymous"></script>
<script async nomodule src="https://cdn.ampproject.org/v0/amp-video-0.1.js" crossorigin="anonymous" custom-element="amp-video"></script>
```

The 1.0 version should not be used because it is Bento and still requires the experiment.

**Comment by swissspidy** [comment]
> The AMP plugin adds v0.1 as seen in this test

Hmm the AMP plugin perhaps, but apparently not the Web Stories plugin where we use parts of the AMP plugin and the PHP toolbox directly in the `Sanitization` class.

**Comment by swissspidy** [comment]
Looks like the AMP plugin does this:

https://github.com/ampproject/amp-wp/blob/d2d441cf6f1f4e9a7268a9c6e3360be309852a2c/includes/amp-helper-functions.php#L931

where we do this:

https://github.com/google/web-stories-wp/blob/ef141d4305cc92a2ad0800723afceaa8f97ea8e4/includes/AMP/Sanitization.php#L310

So that's the issue 💡 

I'll whip up a PR to fix that method.

**Comment by westonruter** [comment]
Ah yes, that is a recent change to the AMP plugin which was done as part of https://github.com/ampproject/amp-wp/pull/6303.
