### ISSUE TITLE
Can I Do This To Add Audio?

### ISSUE THREAD

**Issue by DanielCryptoK** [GoogleForCreators/web-stories-wp#8367]
Can I slice the audio and then put it onto gradient video and use as background in amp webstories?

**Comment by swissspidy** [comment]
Sure, you can add any video with any audio in it to your story and set it as the page's background element. The behavior might be a little bit different though from the background audio support we'll be adding in #48. I suggest you to simply give it a try.

If you run into any issues with the editor, feel free to open a new thread in the [support forums](https://wordpress.org/support/plugin/web-stories/), as we don't provide regular support through GitHub

**Comment by mxbclang** [comment]
@DanielCryptoK As @swissspidy noted, we provide support for the Web Stories plugin via the [WordPress.org support forums](https://wordpress.org/support/plugin/web-stories/), so please post a new topic there if you have any follow-up questions and we'd be happy to help. I'll mark this issue as closed. Thanks!
