### ISSUE TITLE
Insert `https://` protocol to URL in Page Attachment

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#8377]
## Feature Description

Insert `https://` protocol at the start of the link in the Page Attachment field if the user doesn't add one. 

Without this prefix, the page attachment link cannot be opened or drives to a 404 page. 

## Additional Context

The protocol is automatically inserted for Links right now, so it would be great to add it to Page Attachment as well. 

https://user-images.githubusercontent.com/66372350/126195538-1b9929de-6ed1-4126-90f4-33ecd40ba850.mov

https://user-images.githubusercontent.com/66372350/126195548-eb2a504f-f229-49e2-9818-72acbc883413.mov

Related support topic: https://wordpress.org/support/topic/auto-add-www-etc-to-links/

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
pinging @barklund for consideration.

**Comment by miina** [comment]
Pulling this into the current sprint to implement together with #8120.
FYI @barklund

**Comment by csossi** [comment]
Verified in QA
