### ISSUE TITLE
Clicking on media in the gallery should never insert as background

### ISSUE THREAD

**Issue by pbakaus** [GoogleForCreators/web-stories-wp#838]
## Bug Description

Now that we have solid background masking, we'd like to change the behavior to image/video insertion, so that clicking an image or video will never set it as background, and always insert it to the page, consistently.

## Expected Behaviour

When clicking media in the media gallery, said media should be inserted on top of the current elements - it should never become the background media by default.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment]
noted in sprint 26 sheet under the "non alpha" section.

**Comment by spacedmonkey** [comment]
I couldn't agree with this ticket more!

**Comment by wassgha** [comment]
#841
