### ISSUE TITLE
Uncaught SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by pooran** [GoogleForCreators/web-stories-wp#8396]
## Bug Description
Getting this error in console
edit-story.js:7 Uncaught SyntaxError: Invalid or unexpected token

## Expected Behaviour
Ideally it should edit the template as new story
## Steps to Reproduce
Downloaded and added latest version
## Screenshots
![image](https://user-images.githubusercontent.com/116028/126373534-47211a14-5484-413b-afb3-09464832aad8.png)

## Additional Context

- Plugin Version: Version 1.9.0 
- WordPress Version: 5.8
- Operating System: Linux
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Thanks for your report.

Does this still happen with all other plugins disabled?

What's your hosting provider?

Also, if you click on the `edit-story.js` link on the right side, what do you see?

![Screenshot 2021-07-20 at 20 08 37](https://user-images.githubusercontent.com/841956/126373898-d8537475-d405-4cce-b82f-66baa56957d9.png)

**Comment by pooran** [comment]
Does this still happen with all other plugins disabled?

Which plugins need to be disabled? These are the activeones

10Web Builder	Version 1.2.57
10WEB manager	Version 1.3.31 
Elementor	Version 3.3.1
Jetpack		Version 9.9 
PG Export/Import	Version 1.1.7
Photo Gallery	Version 2.5.79
Photo Gallery Google Photos Integration	Version 1.0.2
Site Kit by Google	Version 1.37.0
SVG Support	Version 2.3.18
Toolset Types	Version 3.4.10 
Web Stories	Version 1.9.0
WP File Manager	Version 7.1.1
WPML CMS Nav	Version 1.5.5
WPML Media	Version 2.6.4
WPML Multilingual CMS	Version 4.4.10
WPML SEO	Version 2.0.1 
WPML Sticky Links	Version 1.5.4	
WPML String Translation	Version 3.1.8 
WPML Translation Management	Version 2.10.6 

What's your hosting provider?
Bitnami Wordpress - on AWS Lightsail

**Comment by pooran** [comment]
Also, if you click on the edit-story.js link on the right side, what do you see?

Nothing happens

**Comment by pooran** [comment]
Do you want to access? I can create a test a/c

**Comment by pooran** [comment]
created an account for you to test

**Comment by swissspidy** [comment]
**Something on your server is really, really messing with the JavaScript file contained in the Web Stories plugin, breaking it completely.**

The file on your server is located here:

http://web-stories.local/wp-content/plugins/web-stories-wp/assets/js/edit-story.js (hash `EF4AA92A338102A824490539FF188AE1C084B184`)

The original file in the plugin is located here:

http://plugins.svn.wordpress.org/web-stories/tags/1.9.0/assets/js/edit-story.js (hash `51AF0981BE29193D5D8C159CF890D9E60776730F`)

The file contents (and the hashes!) should be _identical_, but there are **substantial differences**, as you can see when comparing the files locally.

Example: your file contains the string `3rded`, the original does not.

I recommend deleting & reinstalling the plugin. If that doesn't help, reach out to your website administrator or hosting provider to look for any security measures or similar that could cause this file to differ from the original.

**Comment by pooran** [comment]
sure. let me give a try

**Comment by pooran** [comment]
I had downloaded an earlier plugin from https://wordpress.org/plugins/web-stories/

I uninstalled and installed the latest from GitHub releases.. Works like charm :)

Thanks @swissspidy  :)
