### ISSUE TITLE
ESLint rule for `use-context-selector` usage

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8399]
## Task Description

We could create a custom ESLint rule (if one does not exist already) to force using `useStory()` and others with selector functions.

The following pattern is considered incorrect:

```js
const {
    actions: { getCurrentUser, updateCurrentUser: _updateCurrentUser },
  } = useAPI();
```

The following pattern is considered correct:

```js
const {
    actions: { getCurrentUser, updateCurrentUser },
  } = useAPI(({ actions }) => ({ getCurrentUser, updateCurrentUser }));
```

https://github.com/DianaSuvorova/eslint-plugin-react-redux/blob/cfffab2691ded820b8a42134df21eef22be0f087/docs/rules/useSelector-prefer-selectors.md comes close but it's not the same.

**Comment by swissspidy** [comment]
Should be doable by creating a new `@web-stories-wp/eslint-plugin` with such a custom rule.

**Comment by BrittanyIRL** [comment]
@swissspidy think this goes well with discussing inflight about proper context usage and would be a nice follow to some updates in the editor for basic interactions. thoughts on pea pod taking this?

**Comment by swissspidy** [comment]
Feel free to! :-)
