### ISSUE TITLE
Document Panel - Auto Advance Functionality

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#84]
## Feature description

As an author I want to be able to set auto advanced settings for my story

[Epic: Document Workflow
](https://docs.google.com/document/d/1GJZljicdXcP7oRdywsF3EGUaCVpCHsDrK2gUMubnrbk/edit?pli=1#heading=h.wstk3e487ewk)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. The author is able to set the story to auto-advance between pages
2. Auto-advance is the default behaviour
3. After selecting auto-advance, a duration slider is shown
4. The author is able to set the default page duration via slider ranging from 1 - 20 seconds.
5. The default auto-advance is set to 7 seconds, 
6. The slider stepping should increment by 0.1 seconds. e.g. 1.0, 1.1, 1.2...
6. The default page duration is automatically overridden by video, audio or non-looping animation
7. If any of the above 3 elements are on the page, the page auto-advances after the element with the longest duration has finished playing.
8. The author is able to set the story to manually advance between pages
9. These settings are global (per story) not per page

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pbakaus** [comment]
This is now [defined in the product spec](https://docs.google.com/document/d/1GJZljicdXcP7oRdywsF3EGUaCVpCHsDrK2gUMubnrbk/edit?pli=1#heading=h.wstk3e487ewk). Over to UX.

**Comment by jauyong** [comment]
awaiting feedback on if this should be merged with #405

**Comment by jauyong** [comment]
Pinging @samitron7 for designs.

**Comment by samitron7** [comment]
@pbakaus @jauyong @miina Just chatted with Paul and the auto-advance feature is implemented in the Design Panel and not in the Story settings page. Closing this ticket out.

**Comment by miina** [comment]
@pbakaus @samitron7 The name "Story Settings" in the title was just meaning that it's a general story setting, not belonging to any specific element, doesn't indicate a separate story settings page.

If everything else is the same, should we just change the name of the issue for clarity and keep it as it was?

**Comment by swissspidy** [comment]
Makes sense to me
