### ISSUE TITLE
Integration tests for resizeable panels

### ISSUE THREAD

**Issue by wassgha** [GoogleForCreators/web-stories-wp#840]
See https://github.com/google/web-stories-wp/pull/704#discussion_r398939338

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment]
Related: #1170

**Comment by o-fernandez** [comment]
Not sure what the right "Type" label is for this, but dropping the "enhancement" one as that is being used for feature improvements, not testing/infra improvements.
