### ISSUE TITLE
Web Stories widget block e2e test is very flakey

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#8402]
## Bug Description
```
  ● Web Stories Widget Block › should insert a new web stories block

    TimeoutError: Element div.components-card__body (text: "Story URL") not found

      waiting for function failed: timeout 1000ms exceeded
```

https://github.com/google/web-stories-wp/runs/3107827213?check_suite_focus=true#step:13:13

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
The "Web Stories Widget Block › should insert a legacy web stories widget" test also appears to be flakey
