### ISSUE TITLE
Story Lock UX for List View

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#8423]
In #8397 we update the UX for the grid view of a locked story so that the rename story action in context menu is disabled when a story is locked as well as cleaning up the styles a bit. We need to do that same thing for the list view to show when a story is locked there.

**Comment by BrittanyIRL** [comment]
@csossi PR description holds testing details!

**Comment by csossi** [comment]
Verified in QA
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/afa8051f-a658-427b-9eed-642c1a916831)
