### ISSUE TITLE
E2E tests: Add a test for uploading webp 

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#8441]
## Feature Description

As of WordPress 5.8, webp files can be used in our editor. We should have some kind of test for it to make it works as expects. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
How is a webp e2e test different from one for a jpeg? If anything, should we have tests for all image types?
