### ISSUE TITLE
Editor: Add Play/Stop Animations Keyboard Shortcut

### ISSUE THREAD

**Issue by maxyinger** [GoogleForCreators/web-stories-wp#8448]
Right now the play animations button has a keyboard shortcut label for `command + z` however this shortcut isn't functional or in the keyboard shortcuts menu.

[Screenshot 2021-07-23 at 17.21.54.png](https://images.zenhubusercontent.com/5ea0a3e2f739259b2b0b092a/9745d7f9-73c3-4a4a-8eb5-e8c22e28a588)

This task is to add that shortcut to the editor as well as document it in the keyboard shortcuts menu.

**Comment by csossi** [comment]
Verified in QA
