### ISSUE TITLE
Video poster images do not render in Safari

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#8449]
## Bug Description

There is an issue with video poster images not loading and rendering in Safari as quickly as Chrome, Edge or Firefox. 
They load only on-hover of the video cards. 
The video images do not load until you hover over it. 

The issue also occurs with GIFs.

## Expected Behaviour

Videos & GIFs images should load and render in Safari the same as the other browsers. 

## Steps to Reproduce

1) Open Safari browser
2) Open Stories editor
3) Navigate to the 3P Video panel, and select Video tab
4) Note the video poster images are blacked out and are not rendering
5) Hover over videos one by one and notice the images now display. Note the videos that haven't been hovered over do not display/render. 

## Screenshots

The left browser is Safari, the right browser is Chrome.

https://user-images.githubusercontent.com/66372350/126820580-dea433e7-9430-4e73-83f9-cee40d1a38ac.mov

## Additional Context

Edge, Firefox, and Chrome behave as expected.

- Plugin Version: 1.9.0
- WordPress Version: 5.8
- Operating System: Mac
- Browser: Safari Version 14.1.1 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Related: #8272

**Comment by swissspidy** [comment]
Looks like we need to experiment with setting `preload` to `none` or `auto`.

Alternatively, we might want to always show the poster image and only display the video on hover (and subsequently play after a timeout).

The `MediaElement` and `InnerElement` components could use a refactor there to make this easier.

**Comment by spacedmonkey** [comment]
What is also interesting, is that the blurhash or base color do not render either here. 🤔
