### ISSUE TITLE
Linter changes WebkitClipPath to webkitClipPath

### ISSUE THREAD

**Issue by wassgha** [GoogleForCreators/web-stories-wp#845]
See https://github.com/google/web-stories-wp/pull/827#discussion_r399494891

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment]
@swissspidy is this something required for Alpha? Is it being worked on?

**Comment by swissspidy** [comment]
@jauyong not an issue at the moment. Will handle this at some point later.
