### ISSUE TITLE
Settings: Add checkbox for data removal upon uninstall

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8453]
## Feature Description

Continuing discussion at https://github.com/google/web-stories-wp/pull/2534#discussion_r441679994

In #2534 we've added an `uninstall.php` file to remove any plugin data when uninstalling the plugin in WordPress.

That data removal is off by default though and needs to be enabled by filtering `web_stories_erase_data_on_uninstall`.

The idea was to turn this into an actual UI option on the settings page.

## Additional Context

Interestingly, plugins like WooCommerce or Jetpack don't have a UI option for this and instead require setting a constant in `wp-config.php` to enable data removal.

This begs the question whether we really want to add yet another option to the settings page or keep it a developer-only option (perhaps also using a constant instead of a filter).

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by westonruter** [comment]
> Interestingly, plugins like WooCommerce or Jetpack don't have a UI option for this and instead require setting a constant in `wp-config.php` to enable data removal. ¶ This begs the question whether we really want to add yet another option to the settings page or keep it a developer-only option (perhaps also using a constant instead of a filter).

I find this quite surprising. Most users won't have any idea how to add such a constant. Even moreso, if an `uninstall.php` file is present with a plugin, then the confirm dialog in core indicates that deleting the plugin will _also_ delete all of its data. Nevertheless, if the `uninstall.php` is a no-op unless you also define a constant, then the core UI is lying to the user.

**Comment by swissspidy** [comment]
There's quite an old core ticket about that UI: https://core.trac.wordpress.org/ticket/20578

**Comment by westonruter** [comment]
Isn't that obsolete? The use case stated:

> One scenario: Alice wants to install the development version of a plugin, to test a certain bug fix.

Now that you can upload a plugin ZIP on top of an existing plugin installed, there isn't a need to uninstall nearly as much.

**Comment by westonruter** [comment]
In other words, perhaps the constants/filters used by plugins to prevent data removal are no longer needed?

**Comment by swissspidy** [comment]
> Isn't that obsolete? The use case stated:
> 
> > One scenario: Alice wants to install the development version of a plugin, to test a certain bug fix.
> 
> Now that you can upload a plugin ZIP on top of an existing plugin installed, there isn't a need to uninstall nearly as much.

For that particular use case perhaps, yeah, but I'd say that ticket is still useful in general. Anyway, just wanted to provide that as context :-)

> In other words, perhaps the constants/filters used by plugins to prevent data removal are no longer needed?

Maybe. I think these plugins really want to prevent accidental data loss when carelessly deleting a plugin for some reason. Ending up with an empty WooCommerce store is arguably worse than having some lingering data on your site.

**Comment by spacedmonkey** [comment]
I know this is not in scope, but something I thought while testing this. 

I would be amazing, if you uninstall via wp-admin, if you uninstall, a message like this. shows, prompting you to remove data.
<img width="1622" alt="Screenshot 2022-07-21 at 12 45 18" src="https://user-images.githubusercontent.com/237508/180206391-05bf3385-c247-4219-bc9a-9f09f30f07cc.png">

**Comment by swissspidy** [comment]
@spacedmonkey You mean displaying such a banner?

The thing is, when you want to uninstall a plugin, the plugin is already deactivated at that point and a deactivated plugin cannot display such a banner.

**Comment by spacedmonkey** [comment]
> The thing is, when you want to uninstall a plugin, the plugin is already deactivated at that point and a deactivated plugin cannot display such a banner.

Yeah. It is sad we can't do that. I was just dreaming. 😢
