### ISSUE TITLE
Video Muting: Enable by default

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8461]
## Feature Description

After #7730 and other blocking tickets are fixed, we'd want to enable this feature by default

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
I have marked this ticket as block by #8541

**Comment by swissspidy** [comment]
@spacedmonkey Could you address this today ahead of tomorrow's planned release?

**Comment by csossi** [comment]
Verified in QA
