### ISSUE TITLE
Video Muting UX

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8462]
## Feature Description

In #7730 / #8371 we added the MVP for video muting behind a feature flag.

Before we can show this to users, there are some UX considerations that we need to resolve.

Here's how the feature currently works:

1. Upload video with sound to editor.  
  It shows up on the canvas and in the library.
2. Under "Video Options" in the Design Panel there's a new "Mute video" button.
3. Clicking that button will:
    1. Disable the button and change the text to "Muting video"
    2. Remove audio channel from video
    3. Upload a muted copy of the video to the media library
    4. Hide the button
    5. Mark the video as muted in the resulting AMP markup
4. When previewing the story, there's no equalizer or option to unmute (because there's no sound).

Things that we probably should do:

1. Add some "No volume" icon to the muted video in the media library, to distinguish it from the original video. Example:  
  ![outline_volume_off_black_24dp](https://user-images.githubusercontent.com/841956/127014052-f00fcf44-9bc3-4892-b8dd-e50e5d958279.png)
2. Add some explanatory help text below the Mute button so user understands what it does (as it's not just simply a checkbox)
3. Announce button state change to screen readers for improved accessibility

Note: if you initially upload a video without sound, we detect this and don't show this option in the first place. Pretty cool.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
cc @o-fernandez for UX

**Comment by o-fernandez** [comment]
@swissspidy thanks so much! 

- Instead of "Mute video" I think we should call the button "Remove audio" or "Remove sound"
- In the media library, could we just add the "no sound" icon that you posted above next to the video duration that is overlaid already? I think that can be added to any video without sound, generically. WDYT?

**Comment by swissspidy** [comment]
> I think that can be added to any video without sound, generically. WDYT?

Yeah definitely would add that for all muted videos.

**Comment by spacedmonkey** [comment]
I need a SVG version of this icon to continue this ticket.

**Comment by swissspidy** [comment]
@spacedmonkey We're using Material Icons: https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Avolume_off

**Comment by spacedmonkey** [comment]
> Add some explanatory help text below the Mute button so user understands what it does (as it's not just simply a checkbox)

Do you have an wording in mind?

> Announce button state change to screen readers for improved accessibility

Do we do this elsewhere? If not, this should be done as part making all button does this.

**Comment by swissspidy** [comment]
> Do you have an wording in mind?

Let's go with something like this:

"Removing the audio from this video will upload a new muted version of it to the media library. This might take a couple of seconds."

For the styling something like this should work

```js
const HelperText = styled(Text).attrs({
  size: THEME_CONSTANTS.TYPOGRAPHY.PRESET_SIZES.SMALL,
})`
  color: ${({ theme }) => theme.colors.fg.secondary};
`;
```

(I used that for background audio)

Also, since there is now this text below the button, perhaps best to move the button _below_ the "Loop" checkbox

> Do we do this elsewhere?

We have a `useLiveRegion` hook. Using it is as simple as this:

```js
const speak = useLiveRegion();

useEffect(() => {
  if (isMuting) {
    speak('Removing audio.');
  }
}, [isMuting, speak]);
```

> If not, this should be done as part making all button does this.

Since it's super trivial to add, we could easily add this for the video optimization button as well in this PR.

**Comment by spacedmonkey** [comment]
<img width="310" alt="Screenshot 2021-07-30 at 14 14 12" src="https://user-images.githubusercontent.com/237508/127658105-488b7e78-c3f6-4ecc-a7e5-d8653a552c2f.png">
Here I changed the order and made the text smaller, as the text is long the smaller font size works better here. 

<img width="357" alt="Screenshot 2021-07-30 at 14 14 03" src="https://user-images.githubusercontent.com/237508/127658119-7afd7e5d-bad0-4ec3-bf1e-48cfb07e2710.png">

Here is my WIP version of these UX changes. 

I was wondering if we should move the muting option out to a new side panel, called "Audio settings".

**Comment by spacedmonkey** [comment]
Created a PR so people can see the UX changes https://github.com/google/web-stories-wp/pull/8517

**Comment by swissspidy** [comment]
Thanks @spacedmonkey!

Personally I find the chosen text size way too small. Especially with the low-contrast text color it makes the text even harder to read.

I would really stick with 14px (SMALL instead of X_SMALL).

We can remove the "This might take a couple of seconds." sentence to make the text shorter.

The icon in the bottom right looks good. Does it work in RTL too?

@o-fernandez thoughts?

**Comment by o-fernandez** [comment]
The button text size looks fine to me. But, I don't seem to be seeing the latest as I don't see the text description below (saying that it will upload a new video) nor do I see the "no audio" icons... I'll TAL again later.

**Comment by swissspidy** [comment]
@o-fernandez I was referring to the help text font size, not the button text size. Based on the screenshot above.

If you wanna take a look yourself in the plugin, you'll need to check out #8517 on the QA site.

**Comment by swissspidy** [comment]
> I was wondering if we should move the muting option out to a new side panel, called "Audio settings".

Adding yet another panel, especially only for this 1 action, would be detrimental to our efforts to reduce complexity in the editor. I'd keep this under Video Settings.

**Comment by o-fernandez** [comment]
> > I was wondering if we should move the muting option out to a new side panel, called "Audio settings".
> 
> Adding yet another panel, especially only for this 1 action, would be detrimental to our efforts to reduce complexity in the editor. I'd keep this under Video Settings.

Strong +1. If anything, I hope we can do a UX project to reduce the number of panels.

**Comment by spacedmonkey** [comment]
This what larger text looks like 

<img width="291" alt="Screenshot 2021-07-30 at 15 32 07" src="https://user-images.githubusercontent.com/237508/127668517-6f55d087-30d3-411c-8499-1299b53b7a44.png">

VS

<img width="310" alt="Screenshot 2021-07-30 at 14 14 12" src="https://user-images.githubusercontent.com/237508/127668548-5265c5d2-2178-430d-a7a8-a16a80e19fe0.png">

We have this size text elsewhere.

<img width="281" alt="Screenshot 2021-07-30 at 15 33 05" src="https://user-images.githubusercontent.com/237508/127668644-288e371a-a319-4f7c-85df-9b9d9a3674ae.png">

Honestly don't care either way, I will defer to others opinion on this. 

> The icon in the bottom right looks good. Does it work in RTL too?

Yes!
<img width="361" alt="Screenshot 2021-07-30 at 15 30 34" src="https://user-images.githubusercontent.com/237508/127668769-5a5caeba-cbb1-4bba-8e7e-f40dec26e9f0.png">

**Comment by swissspidy** [comment]
> We have this size text elsewhere.

Good point.

Let's leave as-is then for now and see how well it works.

**Comment by csossi** [comment]
Verified in QA
