### ISSUE TITLE
Add "X new" badge next to "Explore templates" when we've added new templates

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#8464]
## Feature Description

In a recent release, we added new templates. However, if users don't read our release notes (likely) they may not notice. 

Propose adding a badge next to "Explore Templates" in the dashboard that highlights that there are new templates added. We can have a number (X new templates) and keep it up for the ~3 months (open to suggestions) after any new templates were added, then drop it since we don't want it to be stale. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by maxyinger** [comment]
Per discussion here:
https://xwp.slack.com/archives/C01ESBB8ZN1/p1628876365017300

We'll just count any template created in the past 60 days as new, make it part of the badge count and put a lil purple dot next to the title to indicate its a newly added template

**Comment by csossi** [comment]
Verified in QA
