### ISSUE TITLE
Re-sort templates so that new ones are at the top

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#8465]
## Feature Description

On a small screen (e.g., the 13" MBP I use) I only see the top 4 templates so when I click through it looks the same at first glance from before we added templates. Suggest sorting new templates to show at the top of the templates gallery so that users can more quickly find and use the new templates. 

 NOTE: we may want to do this in the templates/layouts panel in the editor as well, let's consider it! 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
Thoughts on adding a `createdDate` to the `templates/raw/templateName/index` file to use to sort and also determine what's new for the badge mentioned in #8464 ?

@littlemilkstudio @swissspidy

**Comment by swissspidy** [comment]
Sounds good 👍  

Could even add a simple unit test to ensure a valid date is set.

**Comment by csossi** [comment]
Verified in QA - new templates appearing at top
