### ISSUE TITLE
Add a "what's new" update notice in the editor

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#8466]
## Feature Description

When a user opens the editor, we'd want to let them know of changes that they should be aware of since the last update. Ideally these are the more noticeable changes. 

Why? We had some users recently confused about where the pre-publish checklist went when we moved it from the right panel to be next to the canvas. We'd want a better way to handle this in the future. 

Considerations: 

- We'd want this notice to show to every user when they open the editor after an update. 
- If a user hasn't opened the dashboard/editor since multiple updates before, we'd want them to be able to see all of the notices/updates since they last visited.
- If it's the first time the users opens the editor/dashboard, then we can show just the most recent update, assuming that they are new. 
- Consider just re-using the release notes, ensuring that those are easy to follow and understand. 
- In some cases, we may want to include a link to a page or gifs that show the changes more visually.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
> If it's the first time the users opens the editor/dashboard, then we can show just the most recent update, assuming that they are new.

Need to make sure this does not clash with the help center (which opens by default in that case)
