### ISSUE TITLE
Video Muting: ensure VideoPress compatibility

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#8499]
## Feature Description

Follow up from https://github.com/google/web-stories-wp/issues/7730 . Ensure that this functionality works with videopress. Both testing the functionality and create a PR to patch the issue. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
