### ISSUE TITLE
Editor: Add link to revisions

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#85]
## Feature description

In Gutenberg there's a link to the revisions comparison screen in the document tab when there are some:

![11956-select-revisions-sidebar](https://user-images.githubusercontent.com/841956/185950921-a0d93a0a-e37e-482a-b9e5-c3ee0e088589.png)

It would be nice to do the same in the story editor as well, maybe in the `PublishPanel` component (`packages/wp-story-editor/src/components/documentPane/publish/publish.js`) below the poster image / publisher logo setting

![Screenshot 2022-08-22 at 16 47 39](https://user-images.githubusercontent.com/841956/185950521-4792d048-bc57-41cf-8696-efff28b0c9c7.png)

We can use a similar icon as well:

https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Ahistory%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048

**Comment by felipebochehin87** [comment]
![image.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/58f58628-6b1a-4322-81c1-c7a64ca781f7)


https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/revision.php?revision=19579

![image.png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/565feae6-490f-4c88-ae48-711a3e3a927c)
