### ISSUE TITLE
Canvas: Scale + crop slider doesn't visibly change value when dragging for GIFs

### ISSUE THREAD

**Issue by samwhale** [GoogleForCreators/web-stories-wp#8504]
## Bug Description

When in 'scale and crop'/'edit' mode for a gif element, the slider does not visibly change value. However, clicking and dragging does change the value, which will be reflected when the user clicks out of the 'edit' mode.

The GIF doesn't expand or shrink like images and videos.

## Expected Behaviour

1. The slider should display the current scaled and cropped value.
2. The GIF expands and shrinks as the slider changes value.

## Steps to Reproduce

1. Add GIF to editor
2. Double click on the GIF
3. Move slider

Can be compared to images and videos since they should share the same behavior.

## Screenshots

![scale-and-crop](https://user-images.githubusercontent.com/22185279/127380800-6eeddf71-81a6-4f4e-8705-108795477400.gif)

## Additional Context

- Plugin Version: alpha.0+44b7cc3
- WordPress Version: 5.8
- Operating System: Mac OSX Big Sur 11.5
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
