### ISSUE TITLE
De-duplicate stickers in output

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8511]
## Feature Description

Stickers in the final story content are simply inline `<svg>` elements.

When using the same sticker multiple times in a story, which happens frequently in templates, this will result in the same `<svg>` the page repeatedly. Since some stickers are quite large in file size, this unnecessarily bloats up the document.

We could use [`<defs>`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/defs) to define these SVG paths only once and then use [`<use>`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use) where the sticker is needed. This way, sticker SVGs are de-duplicated and the response size is decreased. This could improve performance as well.

Props to @divyarajmasani for the idea.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

* In `OutputStory`, add a new function similar to `getFontDeclarations` or `getPreloadResources` to go through all sticker elements, get the sticker contents  and then assemble one SVG with `<defs>`
* In `StickerOutput`, only return a simple SVG with `<use>` in it

**Comment by swissspidy** [comment]
@littlemilkstudio @choumx any thoughts on this proposal? Could there be negative effects?

**Comment by dreamofabear** [comment]
Interesting idea! I think we should do some profiling first to measure the expected benefit (generally this should be done for any performance intervention). 

A quick search suggests that we may be surprised by the answer, see this old StackOverflow answer: https://stackoverflow.com/questions/8604999/does-reusing-symbols-improve-svg-performance
