### ISSUE TITLE
PHP 8.1 Compatibility

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#8520]
## Feature Description

PHP 8.1 is coming. 

> The first generally available (GA) version of PHP 8.1 will be released on 25th of Nov, 2021.

With feature freeze soon. 

> PHP 8.1 feature-freeze is currently scheduled for 20th of July, 2021.

With any luck, our plugin will just work, but we need to validate, dev envs, CI and plugin functionality. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Related: #8607

**Comment by swissspidy** [comment]
Current status:

* #8607 fixes 1 tiny compat issue in our code base
* https://github.com/ampproject/amp-toolbox-php/issues/362 needs to be resolved
* There are also a bunch of warnings caused by core

So nothing major really. Once the latter two issues are resolved, we should be in very good shape.

**Comment by swissspidy** [comment]
I don't think anything is left to be done here.

**Comment by swissspidy** [comment]
Unfortunately the Requests upgrade in core was reverted, so there are tons of deprecation warnings again until at least WordPress 6.0

https://github.com/google/web-stories-wp/runs/4449009574?check_suite_focus=true
