### ISSUE TITLE
Refactor editor settings config object

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#8528]
## Feature Description

The  editor settings config object has gone for projects length. There are fields in it that likely are not being used / needed anymore. Others fields could more easily be reformats to be easier to use. Other fields could be groups together. 

This is a code quality task, but links into other effects, like removing capability checks from config object.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Are there concrete examples or is this just to look into it?
