### ISSUE TITLE
Discovery: Solution for story video export

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#8536]
## Feature Description

As highlighted in https://github.com/google/web-stories-wp/issues/7747, we need to research options and have a concrete proposal for how we'll enable this use case. This ticket is a research ticket for eng to look into the solution and proposal. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
@barklund Created a doc for us to collaborate on here: https://docs.google.com/document/d/15ePGOmtALMI_f0TAv3i8LbyK-9MoemXQ5j5r3vyGt3I/edit

**Comment by RainbowCali** [comment]
Thank you so much everyone for working on this feature! Super appreciate it!! Would it likely be launched this year?💖😊
