### ISSUE TITLE
Inconsistent toggling on Popups

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#8538]
## Bug Description

The toggle behavior on the popups in the editor for help center, checklist and keyboard menu should be consistent. They are not. 

## Steps to Reproduce

Try toggling menus. See inconsistent open/close patterning.

## Screenshots

https://images.zenhubusercontent.com/235435637/12e01379-7df9-4e98-9071-d7e21aac11d7/inconsistent_toggle.mp4

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
