### ISSUE TITLE
Masking: clip-path cutting off 1px of the original element

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#855]
## Bug Description

Follow-up issue to #796 

Clip-path used by masking is taking off 1 px of the original element. Even though it might be visibly noticeable mainly only for background media which got fixed within #796 then that seems to be the general behavior. 

## Expected Behaviour

The original size of the element should be kept with masking.

## Steps to Reproduce

1. Add an image 
2. Set background to some color that would contrast well with the image color.
3. Drag the image to the bottom via snapping lines
4. See the 1px difference between the bottom of the Page and the bottom line of the image.

## Screenshots

<img width="865" alt="Screenshot 2020-03-30 at 11 51 00" src="https://user-images.githubusercontent.com/3294597/77899380-e7482e80-727c-11ea-8fbe-0238186367d9.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment]
Noted in sprint 26 overview sheet

**Comment by wassgha** [comment]
Downgrading this to P2 since the background issue was fixed and it's no longer noticeable.
