### ISSUE TITLE
Context Menu: shortcuts not being read by voiceover

### ISSUE THREAD

**Issue by samwhale** [GoogleForCreators/web-stories-wp#8552]
## Bug Description

Context menu shortcuts are not being read when using voiceover. Wondering if other assistive technologies will have the same problem.

## Expected Behaviour

Voiceover should read the context menu button with the text and the shortcut text.

## Steps to Reproduce

1. If testing on mac, use`Cmd` + `F5` to open voice over.
2. Right click an image or the canvas
3. Try to move around the menu. Should not hear any shortcuts announced.

## Screenshots

![short-cutties](https://user-images.githubusercontent.com/22185279/127920401-337e0871-51ef-49d1-b3e4-4153535743e2.gif)

## Additional Context

- Plugin Version: 1.10.0-alpha.0+8ac805e
- WordPress Version: 5.8
- Operating System: MacOSX Big Sur 11.5.5
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by samwhale** [comment]
Should see something like this if using voiceover:

![voiceover-yay](https://user-images.githubusercontent.com/22185279/131862524-cb1e2114-8c73-43c9-8e8a-e287e0fb4d90.gif)

[Chromevox](https://chrome.google.com/webstore/detail/screen-reader/kgejglhpjiefppelpmljglcjbhoiplfn) is a good screen reader chrome plugin that can be used too

**Comment by csossi** [comment]
Verified in QA

Reviewed in ChromeVox, Voiceover(Mac), and NVDA(PC)
