### ISSUE TITLE
Remove duplicate icons 

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#8555]
## Feature Description

This spring, we implemented a new design system. Most icons were swapped to use that source, there's a few outliers that exist in the editor that should be retired and replaced with their twins in the design system. They are: 

- ArrowDown icon
- Checkmark icon
- Close icon
- Dropdown icon
- Search icon
- Media icon
- More icon
- Union icon

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

Removing the versions of these icons that exist in the editor and using the ones in the design system instead.

**Comment by csossi** [comment]
Verified in QA
