### ISSUE TITLE
Remove Duplicate Icons

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#8556]
## Feature Description

This spring, we implemented a new design system. Most icons were swapped to use that source, there's a few outliers that exist in the dashboard that should be retired and replaced with their twins in the design system. They are: 

- Edit icon

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

Removing the versions of these icons that exist in the dashboard and using the ones in the design system instead.

**Comment by g-sqiao** [comment]
Hi @BrittanyIRL ,

Is the `More icon` the same as the one in #8555?
Since it's a little bit hard to locate the edit icon, could you give some pointers? 

Thanks.

**Comment by BrittanyIRL** [comment]
> Hi @BrittanyIRL ,
> 
> Is the `More icon` the same as the one in #8555?
> Since it's a little bit hard to locate the edit icon, could you give some pointers?
> 
> Thanks.

The more icon is the same as the dots that you found. 

The edit icon is the pencil 

Here's a storybook link to icons available in the design system: https://google.github.io/web-stories-wp/storybook/?path=/story/designsystem-icons--all-icons

**Comment by BrittanyIRL** [comment]
@csossi some directions for ya: 

This update is purely cosmetic. 

1. Go to Dashboard Settings
2. Hover or focus on a publisher logo
3. The icon should be updated and the button is a little bigger, like this: 
https://user-images.githubusercontent.com/14279973/129640746-e5a28a68-b959-4727-86c9-179f94dea605.png
4. Please verify that clicking on the button still opens up the context menu as expected and that it looks like this screenshot.

**Comment by csossi** [comment]
Verified in QA - PR8668
