### ISSUE TITLE
Allow hiding 3rd party media tab

### ISSUE THREAD

**Issue by PatelUtkarsh** [GoogleForCreators/web-stories-wp#8559]
Allow programmer to hide 3rd party media tab.

Due to copyright issues, we would like to use local media and DAM integrated media and would like to hide 3rd party media tab.

We can currently hide that using JS:
```js
const thirdParty = document.getElementById("library-tab-media3p");
if (thirdParty) {
	thirdParty.parentElement.classList.add("hidden");
}
```

Should we add a variable which can be [filtered through](https://github.com/google/web-stories-wp/blob/4f0be63f3e61b47a92023b81ec338d54ea3ef0fe/includes/Admin/Editor.php#L344) `web_stories_editor_settings` to hide 3rd party media?

On JS, we can read that injected variable and skip [rendering of the component](https://github.com/google/web-stories-wp/blob/3b4446541105f8398c832847ea2dbc3132088642/assets/src/edit-story/components/library/libraryPanes.js#L66).
## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Sounds like a reasonable enhancement.

Adding this to the editor settings makes sense.

We just need to make sure that it gets disabled properly at all levels, i.e. not just hide the tab, but also ensure there are no outgoing HTTP requests, that the tab cannot be accessed via keyboard, etc.

I'll prioritize this for one of our next sprints.

**Comment by spacedmonkey** [comment]
Do we want to be able to disable all services or just single service?

**Comment by swissspidy** [comment]
Let's focus on disabling all for now and see how well it works. Might want to add some e2e tests to verify it working flawlessly.
