### ISSUE TITLE
Spinner unstyled: displays in HTML but not visible for the user

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#856]
## Bug Description

Related: https://github.com/google/web-stories-wp/issues/790

Spinner is not visible for the user even though it's displayed in HTML.

Note that another Spinner bug is [fixed within](https://github.com/google/web-stories-wp/pull/836/files#diff-4ba4aaa7478f2530815104270cd60e08R159-R161) #836 , please wait until that's merged or bring the fix over from there when looking into this.

## Expected Behaviour

Spinner should be visible for the user, too.

## Steps to Reproduce

1. Create a new Story and click "Save Draft"
2. Spinner should be visible on the left of the button but it's not.

## Screenshots

<img width="793" alt="Screenshot 2020-03-30 at 13 23 22" src="https://user-images.githubusercontent.com/3294597/77907273-a73b7880-7289-11ea-972c-8445ca2846b9.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment]
Noted in sprint 26 overview sheet
