### ISSUE TITLE
Code quality: Split the Media class into multiple classes

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#8564]
## Feature Description

The [media](https://github.com/google/web-stories-wp/blob/main/includes/Media/Media.php) class has become a bit of a dumping ground for different functionality related to media. This class currently do the following. 

- Add image sizes. 
- Register post meta
- Register taxonomy
- Register fields to be added to the REST API. 

I believe the class should be broken up in the following ways. 

- Create new Class called `Video_Poster`. Move all logic related to this into this class. 
- Create new Class called `Media_Source_Taxonomy`. Move all logic related to this into this class. 
- Create new Class called `Image_Sizes`. Move all logic related to this into this class. 

All remaining logic, should stay where it is. All new classes should live in the media namespace. 

Follow up from https://github.com/google/web-stories-wp/pull/8541 where all muting logic was removed to a different class. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Sounds reasonable 👍 

So we would split up the `Media` class into multiple dedicated classes and then removing the `Media` class itself?

**Comment by spacedmonkey** [comment]
> then removing the Media class itself?

I was going to start with the above listed items and then see what left over. There might be some stuff that doesn't map cleanly to anything.
