### ISSUE TITLE
Dashboard: Don't show image title when tooltip is open

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#8565]
Right now if you hover over a locked avatar on the dashboard grid you'll also see the  list item's title attribute. Let's not show the title on hover when a tooltip is open. 

![Screen Shot 2021-08-03 at 10.17.21 AM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/8d15c58b-0b0b-4fa9-8ee0-c22af644bce6)

**Comment by csossi** [comment]
Verified in QA

![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/2ebefd96-f293-47ca-98ff-04280d401273)
