### ISSUE TITLE
Dashboard: Inconsistent scroll to top button visibility

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#8566]
## Bug Description

(From Bugbash 1.10 reported by @spacedmonkey) 

After clicking up the scroll up button. It scroll up to the top and remains. But then I scroll with two fingers on my mac to top, once it gets to the top, the button is hidden. The behaviour should be same in both places. 

## Expected Behaviour

Scroll to top button should be hidden when user clicks on it and goes to top of page regardless of how it was clicked.

If a keyboard user hits 'enter' on the scroll to top, the button should be hidden once it's out of focus. 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
