### ISSUE TITLE
I18N: Use Tannin instead of `@wordpress/i18n`

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8577]
## Feature Description

The story editor and dashboard use `@web-stories-wp/i18n`, which currently is a simple wrapper around `@wordpress/i18n` plus some useful utility functions.

We did this in #6183 in order to remove a direct dependency on a GPL-licensed (but externalized!) dependency across tons of files, so that we could eventually swap out `@wordpress/i18n` for something else.

It's something we _have to_ to before being able to distribute the editor & dashboard package without this dependency being externalized.

And this "something else" is [Tannin](https://github.com/aduth/tannin), the library that also powers `@wordpress/i18n` but is MIT-licensed.

Since Tannin essentially offers the same API as `@wordpress/i18n`, no changes to `story-editor` & `dashboard` need to be made.

## Alternatives Considered

* Just wait for the Gutenberg package to be dual-licensed.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

In `@web-stories-wp/i18n`:

Instantiate a `new Tannin` instance. Export `__`, `_x`, etc. helper functions acting as wrappers around `dcnpgettext`, so that the API stays the same for consumers. Also export `sprintf` from `@tannin/sprintf`. Perhaps also export a `setLocaleData` method to set `tannin.data` from outside.

In `wp-story-editor` and `wp-dashboard`:

Option A:

Get locale data from `@wordpress/i18n` using `getLocaleData` and pass this to our Tannin instance.

Unfortunately `getLocaleData` is only available as of very recently and does not exist on WP 5.5.

Option B:

Don't use `wp_set_script_translations` but use something custom [like Site Kit does](https://github.com/google/site-kit-wp/blob/d6ea05554e20353df9e770abd193c98b006cdf79/includes/Core/Assets/Script.php) to pass locale data to our JavaScript via some inline script.

**Comment by spacedmonkey** [comment]
What is the benefit of change to tannin here? Is it just to decouple the editor from WordPress or does it give us other benefits.

**Comment by swissspidy** [comment]
It's mostly for the decoupling, because of the license. So the benefit is that we can actually ship this with the dependency bundled.

**Comment by csossi** [comment]
Verified in QA
