### ISSUE TITLE
Performance: Memoize direct descendants of context providers in the editor

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#8587]
## Feature Description

As [this article](https://dev.to/leighhalliday/that-react-component-right-under-your-context-provider-should-probably-use-react-memo-glm) argues it probably makes sense to memoize every direct child below a context provider to optimize the render tree.

This includes both the always-present global providers used in the global architecture of the editor, but also the smaller local providers used for panels, layers, etc.

This does not guarantee a performance increase for _all_ providers, but probably for _most_. Only apply it where it actually makes a difference (if the child component always re-renders anyway, it of course doesn't matter).

Please try to make some measurements of user experience before and after and add these to the PR.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by maxyinger** [comment]
knit: should this be _Performance: Memoize direct descendants of context providers in the editor_ ?

**Comment by maxyinger** [comment]
I think this is something worth noting in the article too: https://youtu.be/CDGBTjMBJzg?t=445

I think we're getting the memoization benefits by how we set up most of our providers like the second half of this video. Worth keeping an eye on, but we shouldn't have to worry about most of the providers because we have them set up like this:
```
function SomeProvider({ children }) {
  const value = useSomeStateHooks();
  return <Context.Provider value={value}>{children}</Context.Provider>;
}

function DeeperNestedChild() {
  const someValue = useContext(ContextFromProviderAbove);
  return <div>{someValue}</div>
}

// React basically treats this like a memoized component since `children` is a prop to the provider
// according to the article
function NestedChild() {
  return <div><DeeperNestedChild /></div>
}

function App() {
  return (
    <SomeProvider>
      <NestedChild />
    </SomeProvider>
  );
}
```

**Comment by barklund** [comment]
> ```
> // React basically treats this like a memoized component since `children` is a prop to the provider
> // according to the article
> ```

Hmm, very interesting point! If that's the case, we might be good, but let's definitely test it out!

I didn't know about this distinction actually... It only makes the design pattern of using `{children}` even stronger in general.
