### ISSUE TITLE
Story Locking: Permission error

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8588]
## Bug Description

I just encountered an issue with the story locking where an author user was not able to get the lock information for a story due to lack of permissions.

The reason for that is that we're getting the `wp:lockuser` information via `_embed` from the users controller. And since the `context` is `edit`, this requires `list_users` permission in WordPress, which only admins have.

Because of this, we don't actually get a user object in `wp:lockuser` but a 403 error due to lack of permissions.

I think the easiest way to solve this would be to not use `_embed` for getting the lock user, but instead make the user ID, name and avatar part of the lock response itself.

## Expected Behaviour

Authors should be able to see lock information from others, not risking issues because of `list_users` checks.

## Steps to Reproduce

1. Edit a story as an administrator
2. In a different browser or an incognito window, log in as an author user
3. Go to the dashboard
4. See that the dashboard does not load due to a JS error
5. Check preloaded API response to see that there's a 403 error.

## Additional Context

- Plugin Version: 1.10-alpha
- WordPress Version: 5.8
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Pinging @spacedmonkey for ideas

**Comment by spacedmonkey** [comment]
This issue has nothing to do with the list user capability. It is the edit_posts capability. See this check 

https://github.com/google/web-stories-wp/blob/0de09fdba2f5e96dce3d7467a5bf3568f61a8849/includes/REST_API/Lock_Controller.php#L198-L206

Changing the capability check to the view check, does fix this issue. 
https://github.com/google/web-stories-wp/tree/try/lock-1

**Comment by swissspidy** [comment]
> This issue has nothing to do with the list user capability. It is the edit_posts capability. See this check

Hmm I could swear the error message I got was `Sorry, you are not allowed to list users.`, which comes from `WP_REST_Users_Controller` if `list_users` cap is missing.

**Comment by swissspidy** [comment]
Just marked this as fixed by #8594 since that will apparently resolve this.
