### ISSUE TITLE
Editor not Loading in Legacy Edge

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#859]
## Bug Description

Getting a black screen when trying to create a new story in Edge browser
![image](https://user-images.githubusercontent.com/5874851/77916597-4c912500-7267-11ea-82a2-d2eb26ce5723.png)

Reported by Claudio

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by merapi** [comment]
Works on `Version 80.0.361.69 (Official build) (64-bit)`.

The screenshot looks like "old" Edge.
We only support the "new" Edge (Blink engine), the one that you can currently download from https://www.microsoft.com/en-us/edge

@csossi 

![image](https://user-images.githubusercontent.com/21036224/77919965-2470e880-729e-11ea-8bc9-ba943460418a.png)

**Comment by jauyong** [comment]
@csossi can you confirm what version you tested on?

**Comment by swissspidy** [comment]
@csossi Could you also share the detailed error information from dev tools (via pressing F12)?

**Comment by jauyong** [comment]
Confirmed with Claudio that he tested in Windows 10, Microsoft Edge 44.18362.449.0

**Comment by merapi** [comment]
Tested on `44.17763.1.0` (from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/).

It crashes at `.flat`, probably not the only place to fix for Legacy Edge.

**Comment by swissspidy** [comment]
Interesting. That is indeed [not supported](https://caniuse.com/#feat=array-flat) on EdgeHTML 18 but could be easily polyfilled by core-js / Babel.

**Comment by swissspidy** [comment]
Closing as legacy Edge is not supported
