### ISSUE TITLE
Story Locking: Dashboard crashes when there is no user avatar

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#8593]
## Bug Description
If avatars are disables with a lock post the dashboard errors.

## Steps to Reproduce

1. Disable Avatars, Settings > Discusssion > Show avatar
2. Go to dashboard.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
There are probably errors in the editor as well as there are no checks for the contents of the lockUser object.

Related: #8588

**Comment by csossi** [comment]
Verified in QA
