### ISSUE TITLE
Display recommended colors for contrast in basic color picker

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#8599]
## Feature Description

Inspired by this tweet from @siddhart I was considering whether we could do something similar when selecting font color or text background color where we highlight recommended colors for a proper text contrast between foreground and background.

Here's a quick mockup with a faded check mark inside the "recommended" colors:

| Before | After |
|-|-|
| <img width="463" alt="Screen Shot 2021-08-05 at 16 59 13" src="https://user-images.githubusercontent.com/637548/128373126-4d9b569b-c8ee-48dc-920b-2e8c14726996.png"> | <img width="463" alt="Screen Shot 2021-08-05 at 17 02 16" src="https://user-images.githubusercontent.com/637548/128373136-74839728-1014-4962-9a39-beafe1da1b26.png"> |

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Related: #7230

**Comment by eyeamkd** [comment]
Hello @swissspidy, I would like to place a PR for this, could you kindly assign me this?

**Comment by swissspidy** [comment]
@eyeamkd You're more than welcome to create a PR for this, even without assignment, but please note that we haven't yet defined the color contrast requirements or how this is announced to screen readers. So there might be more suitable tickets for you to pick up than this one.

**Comment by eyeamkd** [comment]
Noted @swissspidy! Thank you for the response :)

**Comment by Yash621** [comment]
@swissspidy can i work on this ?

**Comment by swissspidy** [comment]
Thanks for chiming in.

This is still an idea and we haven't decided yet whether we actually want to implement this. Thus, I'm afraid this is not actionable yet.
