### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#86]
## Feature description

This ticket was inspired by this [comment in slack
](https://xwp.slack.com/archives/CCCAUAH6F/p1574088937001800?thread_ts=1574088174.001600&cid=CCCAUAH6F)

![image](https://user-images.githubusercontent.com/5874851/69082199-97737400-0a0d-11ea-9153-702d78d8a406.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## QA testing instructions

*

**Comment by dvoytenko** [comment]
@jauyong are these shortcuts at all reconciled with our editor's needs? The description seems to follow the old editor and many items seem unrelated to the new one. Is there an epic for the keyboard shortcuts? Should this really be scheduled in any milestone?

/cc @pbakaus

**Comment by swissspidy** [comment]
Good call. Those are just the keyboard shortcuts that Gutenberg had. Ours will be different.

The feature brief for those doesn't exist yet, but there's a short overview on Figma:

![Screenshot 2020-02-14 at 10 17 58](https://user-images.githubusercontent.com/841956/74518074-87d3d080-4f13-11ea-9225-05edf26daeb1.png)

There will be more than that, e.g. #273 mentions some for layer reordering.

I see <kbd><kbd>Shift</kbd>+<kbd>[]</kbd></kbd> in the screenshot above and I can tell you that this shortcut will probably only work on a keyboard with US layout. 
So please keep i18n in mind when working on this list 🙂 

-----

Besides that: once we have keyboard shortcuts, we need a new issue for creating a dialog that shows all available shortcuts.

**Comment by jauyong** [comment]
Closing this ticket as a new one will be created to go back to add keyboard shortcuts where they are missing and any new sections being developed will include work for the keyboard shortcuts there.
