### ISSUE TITLE
Dashboard Context Menu Actions

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#8603]
In the latest bugbash, Jonny brought up a potential regression that wasn't noticed where some users don't have the ability to do all menu actions but those actions are still available in the context menu for stories. Let's look at that and make sure we've got tests set up to catch that moving forward. 

(Screen grab from bug bash for context) 

![Screen Shot 2021-08-06 at 7.17.07 AM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/8f020a4f-0f29-474a-a747-96faa48e7441)

**Comment by swissspidy** [comment]
@BrittanyIRL I _think_ #8591 fixes that. cc @spacedmonkey to confirm

**Comment by spacedmonkey** [comment]
> @BrittanyIRL I _think_ #8591 fixes that. cc @spacedmonkey to confirm

Confirmed

**Comment by BrittanyIRL** [comment]
Closing as #8591 resolves this issue.
