### ISSUE TITLE
Polyfill lazy loading attribute

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#8609]
## Feature Description

Lazy loading attribute is [not supported](https://caniuse.com/loading-lazy-attr) in Safari, desktop or mobile. The lazy loading attribute, is used in the editor to defer loading of images in the media library. 

Consider adding a polyfill like [mfranzke/loading-attribute-polyfill](https://github.com/mfranzke/loading-attribute-polyfill
).
## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
I'd have to check our analytics to see how relevant this is for our users.

Lazy loading is more of a progressive enhancement and Safari is working on enabling it by default soon, which is good. Plus, that polyfill is quite cumbersome to use for us.

Keeping this in the backlog for now.

**Comment by swissspidy** [comment]
Safari TP now supports this by default, so soon it will be in stable Safari as well. Given that timeline and Safari not being a popular browser among our users, it's not worth adding a polyfill in the interim.
