### ISSUE TITLE
"Publish" and "Switch to Draft" button not updating the DB

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#861]
## Bug Description

"Publish" and "Switch to Draft" button are not making actual changes in the DB, currently, the user needs to click additional "Update" or "Save draft" for these to make a change.
## Expected Behaviour

"Publish" and "Switch to Draft" button should directly Publish or Switch to Draft without the user having to click additional "Save" after clicking the button.

Ideally, we should also display a confirmation for publishing!

## Steps to Reproduce

1. Add a Story
2. Click "Publish"
3. Refresh.
4. See the Story is still a Draft.

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
@obetomuniz Can you move the ticket to QA or done when it complete. Also when you reference a ticket in a PR, can you [use the correct keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
