### ISSUE TITLE
Replace usage of `query-string` package with `addQueryArgs`

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#8614]
## Feature Description

Replace usage of `query-string` package with `addQueryArgs` in the design-system package. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Related reading: https://dev.to/nerdyman/replacing-query-string-with-native-urlsearchparams-4kdg
