### ISSUE TITLE
Packages: Import React dependency from own React package

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8641]
## Feature Description

We created our own dedicated `react` package in #8159.

Now, we want to re-export `react` and `react-dom/server` functions from this package and make any package depend on this one. Similar to `@wordpress/element`.

This makes it easier to maintain the React dependency and update it in the future.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
From https://github.com/google/web-stories-wp/issues/8159#issuecomment-885741070

> Looking at codebase, these functions are used from react

> useCallback, useEffect, useMemo, useRef, useState, forwardRef, memo, useLayoutEffect, useReducer, createRef, Fragment, StrictMode, Suspense, React.

We should add a lint, to force devs to use this package over, react.

**Comment by swissspidy** [comment]
The list above does not include things like `createPortal`, `render`, and `renderToStaticMarkup` from `react-dom` / `react-dom/server`. Those would need to be exported as well.

We can use the `no-restricted-imports` ESLint rule for this (there's precedence in the current config).

**Comment by spacedmonkey** [comment]
> Looking at codebase, these functions are used from react

Those are just the ones from react.
