### ISSUE TITLE
Media Hotlinking

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#8653]
## Feature Description
This is a follow-up issue for https://github.com/google/web-stories-wp/pull/8638 and #471.

#8638 includes just the MVP for the feature, the following items still need addressing:

- Server-side validation for the link validity
- Getting the media type from a `HEAD` request, thus allowing linking image that don't have the file extension in the URL (e.g. Unsplash)
- Poster image creation workflow in case of the user hotlinking the video not having permissions to upload images
- Refactor the code to work more async, [see details from Pascal](https://github.com/google/web-stories-wp/pull/8638#discussion_r686034189)
- UX improvements if needed.
- Confirm copy (including adding helper text about the feature to the dialogue)

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Added this issue for tracking following up on the MVP for #471. More tasks might be added to the description.

@barklund / @swissspidy I've assigned you both currently since this includes both WP and the editor -- we might want to split this more to separate the two pods.

**Comment by swissspidy** [comment]
Definitely need to split this up. I turned this into an epic appropriately.

> * Server-side validation for the link validity
> * Getting the media type from a `HEAD` request, thus allowing linking image that don't have the file extension in the URL (e.g. Unsplash)

These might go together, as the `HEAD` request might not work client-side due to CORS.

Created #8666 for this.

> * Poster image creation workflow in case of the user hotlinking the video not having permissions to upload images

Hotlinking poster images is currently out of scope. Uploading of poster image would need to be done by an admin/editor/author before publishing.

So don't need to worry about this for now.

> * Refactor the code to work more async, [see details from Pascal](https://github.com/google/web-stories-wp/pull/8638#discussion_r686034189)

Thinking about this more, once we have the server-side validation, we'll know more about the media item right away, simplifying this a bit.

Created #8667 for discovery nonetheless.

**Comment by spacedmonkey** [comment]
Should there be some kind of check for file size of embedded image / video. We should have some check to ensure a user do not try and embed, say a 1GB video file?

**Comment by swissspidy** [comment]
cc @o-fernandez on that question.

I'd say that's out of scope for V1 (so not a P0) but an interesting enhancement later on.

**Comment by o-fernandez** [comment]
> I'd say that's out of scope for V1 (so not a P0) but an interesting enhancement later on.

Agree. We can have a separate ticket to review whether we need limits and/or a special flow if the user attempts to hotlink something that's not optimized for good web serving. Let me create a ticket for that.

**Comment by swissspidy** [comment]
Created #8803 for better handling of CORS issues.
