### ISSUE TITLE
Option to turn off or change the Stories background/shadow color

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#8659]
## Feature Description

As a user, I want the ability to turn on/off the story's shadow background color, or the ability to set the color on each page's shadow. 

<img width="1438" alt="Screen Shot 2021-08-11 at 2 04 59 PM" src="https://user-images.githubusercontent.com/66372350/129080860-cb9e785d-3aec-402b-8177-41747053c0d6.png">

## Additional Context

Related topic: https://wordpress.org/support/topic/colored-blurred-background-on-web-browser-version/

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
This color is gathered from the page‘s dominant color, I don‘t think this can be changed. But you can report this in the amphtml repo to ask for this
