### ISSUE TITLE
Dashboard: Move story duplication to the server

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8664]
## Feature Description

Currently in the dashboard we have to pass both `story_data` and `content` for duplicating stories, which means we need to retrieve these fields all the time:

https://github.com/google/web-stories-wp/blob/c6432948c1a91f42ca19b1069255281fff43dd0a/packages/dashboard/src/app/api/useStoryApi.js#L312-L369

Moving this to the server would reduce response sizes and thus performance on the dashboard.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

* No more `story_data` and `content` fields being sent & preloaded
* Duplication still works

**Comment by csossi** [comment]
Verified in QA
