### ISSUE TITLE
Media Hotlinking: Make insertion more async

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8667]
## Feature Description

See https://github.com/google/web-stories-wp/pull/8638#discussion_r686034189 for details.

Hotlinking currently does a lot of things when clicking on the "Insert" button that need to be awaited:

* REST API request for validation
* Fetch remote image/video, check dimensions
* Upload a poster

That can make the whole interaction very slow and not feel very instant.

It should be possible to make this more async, just like we do for media upload, especially when video optimization is involved.

Example:

1. Insert URL & confirm
2. `onInsert` pings REST API for validation & to get media type
3. Try preloading the image/video
4. Insert media right away
5. If loading failed -> display placeholder to say "Preview unavailable"

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Some video URL for testing: https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4

More shared at https://github.com/google/web-stories-wp/pull/8638#issuecomment-901199198

**Comment by spacedmonkey** [comment]
One thing that is a shame is, the as browser can not access the video / image resource, there is not was to get size, poster or if the video has audio it. The placeholder will have to be very generic and will not match the size of the resource. It will make resizing the resource pretty hard, so you will be doing this blind.

**Comment by swissspidy** [comment]
That's true. In #8666 we could try to see how feasible it is to get at least the dimensions on the server side, similar to how WordPress gets the dimensions when uploading files.

**Comment by swissspidy** [comment]
Closing this for now
