### ISSUE TITLE
Video poster image stretched in design panel

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8670]
## Bug Description

In the design panel under "Video Settings", the video poster appears stretched with incorrect aspect ratio.

This should be fixed by using something like `object-fit` in CSS.

## Screenshots

![Screenshot 2021-08-03 at 19 36 43](https://user-images.githubusercontent.com/841956/129210973-049e341e-5ae6-44cd-8c68-89e74b577f51.png)

![Screenshot 2021-08-03 at 19 36 33](https://user-images.githubusercontent.com/841956/129210976-e284d6c2-7676-45ce-922d-92e2fff301f0.png)

## Additional Context

- Plugin Version: 1.10.0
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by hamza-arshad** [comment]
@swissspidy is this available, can I pick?

**Comment by swissspidy** [comment]
Thanks for the ping!

Unfortunately I think this one isn't actionable just yet.

I just looked at this again and apparently we're already using `object-fit: cover` here:

![Screenshot 2021-10-12 at 10 03 45](https://user-images.githubusercontent.com/841956/136916837-ad84f72c-a544-4997-b0c3-d8c3f8d9759c.png)

For comparison, here's what it would look like without it:

![Screenshot 2021-10-12 at 10 04 38](https://user-images.githubusercontent.com/841956/136916869-74158248-6f2b-4847-8ae2-7d0a57180b48.png)

I think we need some design feedback first for this whether the current status is OK or whether we actually need to improve something.

----

@aaskedall @agingoldseco QQ, regarding these two screenshots above:do you see any possible improvements for how we could improve the video poster display there?

The first screenshot is status quo - you can see I have a landscape video but the thumbnail preview doesn't show all of it.

Second one is an alternative that shows the full preview but very small.

This one could be a third option, but that makes the panel a bit taller:

![Screenshot 2021-10-12 at 10 11 25](https://user-images.githubusercontent.com/841956/136917870-5d23ba33-6c11-4030-8d55-70eeb92e516a.png)

**Comment by agingoldseco** [comment]
Honestly, I think it's okay to keep it how it is for now—would be different if the image was actually being warped. While we're updating the design panel in several other ways soon, I'll keep this in mind in case a solution presents itself, but I think as long as we can tell the image in that box and the canvas match we don't need to devote time to this right now. Please let me know if there are any objections to that.
