### ISSUE TITLE
Images are blurry when set as background

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#8671]
## Bug Description

The incorrect image resolution is still being served for images that are set as background on stories, as reported by a [support user.](https://wordpress.org/support/topic/problem-with-resolution-images-in-new-update/#post-14758102)

## Expected Behaviour
Images should display at the correct resolution.

## Steps to Reproduce
1.	Create a new story
2.	Set an image as a background image
3.	View in browser

## Additional Context

Preview this test story on Chrome versus Safari: https://testsite.cmsdevrel.com/web-stories/preview-color/

- Plugin Version: 1.10
- WordPress Version: 5.8
- Operating System: macOS
- Browser: Chrome, Safari

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by dreamofabear** [comment]
I see the blurry image on the second page of your story but I'm having trouble reproducing this locally.

Can you explain your exact repro steps? Or share access to your WP test instance?

**Comment by dreamofabear** [comment]
Ahh ok, I think what happens is this:

1. Insert image onto canvas.
2. Resize image to be very small
3. Click "Set as background" in "Size & Position" panel
4. Update/publish page

Step (3) doesn't seem to update the internal element size, so its `sizes` attribute is rendered with the size in step (2).

**Comment by swissspidy** [comment]
> Step (3) doesn't seem to update the internal element size

I think this is expected, so that you can click "Remove as background" and the image returns to its original size & position.

To solve this, perhaps in `output/page.js` we can pass the correct size (the page size) to `OutputElement` here:

https://github.com/google/web-stories-wp/blob/d48e3d528709c5bd6bf4c4535e09f68082ab230c/packages/story-editor/src/output/page.js#L95-L101

**Comment by csossi** [comment]
Verified in QA
