### ISSUE TITLE
Pause button on story player not functional 

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#8672]
## Bug Description
The pause button on the stories player does not pause the story on click. 
Clicking space to pause the story does not display the play button.
Pause button does not appear until the space bar has been clicked. 

## Expected Behaviour
The play/pause button should display by default and should be functional.

## Steps to Reproduce
1.Preview a story
2.Note top right corner > Missing icon
3. Click space bar > Note pause button displays but story does not pause

https://user-images.githubusercontent.com/66372350/129221140-9917691f-918c-4655-9521-2ec2e797c362.mov

## Additional Context

- Plugin Version: 1.10.0
- WordPress Version: 5.8
- Operating System: macOS
- Browser: Chrome, Safari

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
This should be reported in the amphtml repo

**Comment by swissspidy** [comment]
@LuckynaSan is this still happening? If so, I recommend opening a bug in the amphtml repo.

**Comment by LuckynaSan** [comment]
This is no longer an issue.
