### ISSUE TITLE
Color picker can overflow viewport when switching state

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#8673]
## Bug Description

When switching from custom color picker to basic color picker, the popup window extends and this can cause the popup to move slightly off-screen.

This can also happen if you add a new custom color in the custom view as the picker switches to the basic state, but the list of saved colors now extends by one more row.

## Expected Behaviour

Popup should always be inside the visible viewport area.

## Steps to Reproduce

1. Make sure to have 7+ saved global colors.
2. Open the new basic color picker
3. Switch to custom color picker mode
4. Scroll the design panel so the bottom of the color picker aligns with the bottom of the viewport
5. Switch to basic color picker mode

## Screenshots

![propagation](https://user-images.githubusercontent.com/3294597/129170414-022a360b-d274-4698-a01a-71b8194ac21d.gif)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
