### ISSUE TITLE
Editor: white space displaying on the side of the video

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#8674]
## Bug Description
There is a white space to the side of the video when in the editor on Fit view,

## Expected Behaviour

For the video to display properly on any view. 

## Steps to Reproduce

1. Open Story Editor
2. Set view to Fit 
3. Add a video to the page > Note the display

## Screenshots

<img width="341" alt="Screen Shot 2021-08-12 at 10 59 37 AM" src="https://user-images.githubusercontent.com/66372350/129223294-7473851a-2065-41f3-87f6-d256c6f0f436.png">

## Additional Context

- Plugin Version: 1.10.0
- WordPress Version: 5.8
- Operating System:
- Browser: Chrome, Safari

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Is this only in the editor or also on the frontend?

**Comment by LuckynaSan** [comment]
Editor only.

**Comment by swissspidy** [comment]
Does this happen with all videos or only this particular one?

Works fine for me here:

<img width="486" alt="Screenshot 2021-08-12 at 19 10 44" src="https://user-images.githubusercontent.com/841956/129239197-50ccc91d-5c1d-4e3a-8421-758ae6cf0cdf.png">

**Comment by LuckynaSan** [comment]
Below is a screenshot of multiple videos from stock content. Note white gap on the right. 

<img width="336" alt="Screen Shot 2021-08-13 at 10 14 00 AM" src="https://user-images.githubusercontent.com/66372350/129370544-621d071c-d984-4a69-a3bb-5dc0a038f8cd.png">

**Comment by swissspidy** [comment]
Still don't see this on my end.

@csossi Do you perhaps see this in your testing as well?

**Comment by swissspidy** [comment]
Similar report: #8939

**Comment by swissspidy** [comment]
Unable to repro, closing for now
