### ISSUE TITLE
Add linting to package.json files

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#8675]
## Feature Description

This project now has 38 package.json. We should add some linting to these files to ensure. 

- Packages are sorted alphabetically 
- Correct spaces / tabs are added
- All required fields are included ( including licencing fields are included ). 
- That package.json are valid when used with npm. 

There are packages like [sort-package-json](https://www.npmjs.com/package/sort-package-json?activeTab=readme) or [prettier-package-json](https://www.npmjs.com/package/prettier-package-json) or [npm-sort](https://www.npmjs.com/package/npm-sort)

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
There's also [npm-package-json-lint](https://www.npmjs.com/package/npm-package-json-lint) which Gutenberg uses.
