### ISSUE TITLE
Analyze & Optimize Bundles

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#868]
## Feature Description

The final `edit-story.js` bundle is getting bigger and bigger. It is almost 0.5MB already, which is quite high.

We need to analyze the current bundle (e.g. using `webpack-bundle-analyzer`) to better understand the root cause.

Then, we need to come up with a robust solution. This will involve tweaking some configs, removing some polyfills, splitting up the bundle into multiple chunks, serving less code to modern browsers, etc.

Same goes for the dashboard app.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
Code splitting is fairly easy to do and we could rather smoothly find some components, that could be removed from initial load, as these will never be displayed on from the start:

* all library panes except media
* all inspector panels except those relevant for page background (including document and prepublish).
* more complex form elements such as color picker, font picker, dropdown
* grid mode
* dialogs (grid mode might actually be a dialog?)

It's very common to do code-splitting and natively supported by both webpack and react.

**Comment by merapi** [comment]
Some interesting findings here. 🕵 

![image](https://user-images.githubusercontent.com/21036224/77954849-931a6a00-72cf-11ea-9f68-fa1a9f706f51.png)
![image](https://user-images.githubusercontent.com/21036224/77954967-c0ffae80-72cf-11ea-94e1-5f4322e339a0.png)

**Comment by swissspidy** [comment]
Those two large SVGs are actually encoded PNGs 🤔

**Comment by barklund** [comment]
> Those two large SVGs are actually encoded PNGs 🤔

We could probably get @samitron7 to convert these to proper vectors.

It's these icons here in the figma, which are made with images rather than vector shapes:

<img width="395" alt="Screen Shot 2020-03-31 at 5 20 08 PM" src="https://user-images.githubusercontent.com/637548/78076179-ea721600-7373-11ea-87c6-49b8f1934452.png">

Specifically, it's the three small stars in the corner of both elements, that should be vector shapes rather than a 40kb image.

**Comment by swissspidy** [comment]
Related: #1348

**Comment by swissspidy** [comment]
@barklund any thoughts on how we could best ship slim bundles to modern browsers and polyfilled bundles for older ones?

**Comment by dvoytenko** [comment]
> @barklund any thoughts on how we could best ship slim bundles to modern browsers and polyfilled bundles for older ones?

On AMP side we use module-no-module approach. But figuring out which module browsers support which polyfills is also non-trivial.

**Comment by samitron7** [comment]
@barklund you guys have the svg for those 2 icons already correct?

**Comment by swissspidy** [comment]
@samitron7 yes, that has been addressed

**Comment by o-fernandez** [comment]
@swissspidy @pbakaus would you characterize this as a 1.0 Stable blocker? Considering whether this scope can move out to post the initial release.

**Comment by swissspidy** [comment]
Not really a blocker I think. Existing code can be fixed post-release, and new features can leverage this from the get-go.

**Comment by pbakaus** [comment]
+1, let's not block on this.
