### ISSUE TITLE
Right Click Menu: Add tracking

### ISSUE THREAD

**Issue by samwhale** [GoogleForCreators/web-stories-wp#8681]
## Feature Description

Add tracking to the actions in the menus so we can see how often users click them.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
@BrittanyIRL can/do we have that for quick actions as well?

**Comment by BrittanyIRL** [comment]
> @BrittanyIRL can/do we have that for quick actions as well?

It wasn't part of the feature, can add a ticket to follow up with them.

https://github.com/google/web-stories-wp/issues/8689

**Comment by swissspidy** [comment]
Thanks! Let‘s figure out how we can implement this from the beginning going forward.

cc @choumx
