### ISSUE TITLE
Media: Show accurate upload progress bar

### ISSUE THREAD

**Issue by obetomuniz** [GoogleForCreators/web-stories-wp#869]
## Bug Description

Currently, the upload progress bar UI covers only when an upload batch starts and when it finishes. It is happening because `apiFetch` use Fetch API for requests under the hood, which don't provide **upload** progress status support for real time tracking.

## Expected Behaviour

The upload process for media should display the upload progress bar UI in real time for each file being uploaded. Our initial research recommended to use [apiFetch.setFetchHandler](https://developer.wordpress.org/block-editor/packages/packages-api-fetch/#custom-fetch-handler) and [axios onUploadProgress](https://github.com/axios/axios/blob/master/examples/upload/index.html#L30) as a potential solution to support the expected behavior, but there are potential edge cases to consider in conflict with the natural behavior of WordPress. 

## Steps to Reproduce

- Create a Story
- Drop files in the Story workspace or media library and monitor the upload progress bar UI

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Worth keeping in mind here that want to maintain clear separation in the future from everything WordPress related, so we can also use the editor standalone or with another backend. That might influence how we architect this feature.

**Comment by obetomuniz** [comment]
Well noticed @swissspidy. It should be a requirement in the solution aspect. Thanks for bringing this side note.

**Comment by spacedmonkey** [comment]
Related https://javascript.info/fetch-progress
