### ISSUE TITLE
Can't Create a Story from Honeymooning In Italy Template

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#8691]
## Bug Description

If you go to the dashboard templates and try to 'create a story' from Honeymooning in Italy it won't work. The error I saw coming back was that the json isn't valid. Loading the template directly in the editor with dev tools results in a bunch of broken images. Feels like that might be part of it. 

## Expected Behaviour

Be able to create a story from honeymooning in italy template. 

## Additional Context

Request URL: `http://localhost:8899/wp-json/web-stories/v1/web-story/?_fields=edit_link&_locale=user `
Status code: `200` 

Response: `WordPress database error, got a packet bigger than max_allowed_packet bytes`

Error Received in catch: `{code: "invalid_json", message: "The response is not a valid JSON response."}`

Request Payload: 
![Screen Shot 2021-08-16 at 12 45 07 PM](https://user-images.githubusercontent.com/10720454/129620808-5644247f-18c0-4ce1-ba30-6fc393c6c0a8.png)

I also tried completely reseting my local instance and the issue remains. Every other template is fine, just this one!
Because every other template works just fine, I feel like there's something in this one that locally isn't getting handled accurately? The payload is the same for other templates. 

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
cc @divyarajmasani

**Comment by divyarajmasani** [comment]
I was able to create the story with the Honeymooning in Italy template on following set of environments,

- Local site with latests changes from the `main` branch.
- Local site with latests plugin from the wp.org
- Internal dev sites with latest changes from the `main` 

What I was able to do,
- Create story with `use template` feature.
- Save story, preview and edit

I'm checking the same on `try/template-image-generation` branch. 

Would it be possible to get the error log?

**Comment by BrittanyIRL** [comment]
@divyarajmasani  yup! sorry about that. I filed the ticket planning to come back and add specs and then the weekend happened :) 

So I'm getting this error: 
`{code: "invalid_json", message: "The response is not a valid JSON response."}` 
It's the same locally from `main` for me as well so it's nothing to do with my branch. 

This occurs when i try to 'create a story from template' either on explore templates or the template details page locally. 

It does work on staging so it probably doesn't need to be a priority 1, however it's really weird that this one template won't work locally. I do need it to be create-able so that I can finish up work on #8693 eventually.

**Comment by swissspidy** [comment]
What‘s in the request body when you create a new story from that template?

What are you using for local development?

Does this happen when disabling all other plugins?

**Comment by BrittanyIRL** [comment]
(Added more context to description, also has Max try it out in his environment and is getting the same issue)

**Comment by swissspidy** [comment]
Thanks, very helpful. The `WordPress database error, got a packet bigger than max_allowed_packet bytes` bit here is the crucial part. What happens:

1. You try to create a new story, sending a large blob of HTML and JSON to the server
2. The HTML or JSON content is too big for MySQL to handle (see https://dev.mysql.com/doc/refman/8.0/en/packet-too-large.html) and it errors. Probably because this template contains lots of large SVGs.
3. This database error is returned to the client as-is instead of a nice "success" response, of course causing the `The response is not a valid JSON response` error

What we need to do:

1. Check size of HTML & JSON blob in MB
2. Check current value of `max_allowed_packet` in our docker environment
3. Increase `max_allowed_packet` if necessary
4. Figure out whether this might also happen in other environments

**Comment by swissspidy** [comment]
So `max_allowed_packet` on my [LocalWP](https://localwp.com/) development site is `16777216` (16MB).

On the Docker instance it's merely `4194304` (4MB).

@BrittanyIRL Could you try if the following change to `bin/local-env/docker-compose.yml` works for you?

```diff
  mysql:
    image: mysql:5.7
+   command: --max-allowed-packet=16777216
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress_test
    volumes:
      - ./data/mysql:/var/lib/mysql
```

This should increase `max_allowed_packet` and allow using the template in the docker environment.

Run `npm run env:start` afterwards to apply the changes.

**Comment by BrittanyIRL** [comment]
this worked perfectly, thank you so much!
