### ISSUE TITLE
"Save" Animation - Appearing On Preview Icon

### ISSUE THREAD

**Issue by csossi** [GoogleForCreators/web-stories-wp#8694]
## Bug Description

When I click the "save" icon, the spinning-wheel animation appears on the preview icon

## Expected Behaviour

Expected that this would appear on the save icon

## Steps to Reproduce

edit story (or create new one) and click "save" icon

## Screenshots

https://share.getcloudapp.com/OAunL8DY 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Cc @aaskedall

**Comment by miina** [comment]
This behaviour was a UX decision at some point, to display the spinner on the first icon.

cc @agingoldseco in case you'd like to make changes here.

**Comment by BrittanyIRL** [comment]
Brought this up in design sync today with Amy. We're going to leave it how it is.
