### ISSUE TITLE
Design Panel Alignment Off in Firefox

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#870]
## Bug Description

Various labels, fields and buttons are not aligned according to the designs in Firefox 

72.02, Mac
![image](https://user-images.githubusercontent.com/5874851/77954370-86305300-729c-11ea-9cce-0973d0b2925b.png)

Reported by Claudio on #578 in Firefox 74, WIndows 10
![image](https://user-images.githubusercontent.com/5874851/77954450-9d6f4080-729c-11ea-927e-18bd086c5ae2.png)

## Expected Behaviour

Layout should match designs

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jauyong** [comment]
Merging with #873

**Comment by swissspidy** [comment]
Thanks! Sorry, I didn‘t realize you had created this one.
