### ISSUE TITLE
Improve messaging around save, preview and publish greyed out buttons

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#8701]
## Feature Description

Many users on the support forum have reported the save, preview, or publish buttons greyed out or seemingly disabled. Support informs the users that those buttons can be greyed out when either the story is currently being saved or if there are some media still being uploaded.

Is it possible to add messaging around these buttons actions to let the users know the story is in the progress of saving or media currently being loaded? It would be helpful to know that the story is actually in the progress of saving versus the button just being greyed out and continuously spinning. 

## Additional Context

Related topics:

https://wordpress.org/support/topic/webstories-save-feature-not-working/
https://wordpress.org/support/topic/plug-in-issues-5
https://wordpress.org/support/topic/missing-preview-button-cropping-poster
https://wordpress.org/support/topic/problem-with-many-issues/
https://wordpress.org/support/topic/amp-stories-not-saving

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
To add a little context here. The Save / publish button is can be greyed out, if there is a video transcoding or file uploading. It is not always clear that this is the case.

**Comment by swissspidy** [comment]
I'll look into this to come up with some suggestions.

**Comment by spacedmonkey** [comment]
Adding UX needed here. This ticket is not actionable, so should be remove from the sprint backlog

**Comment by swissspidy** [comment]
I'll tackle this next week

**Comment by csossi** [comment]
Verified in QA
