### ISSUE TITLE
Right Click Menus: Close on Blur

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#8702]
The context menu renders an invisible mask that covers the entire screen (behind the menu). When a user clicks on this mask, the menu will close.

Implement a way to close the menu without needing to render the mask. This may be done with a blur event handler or the `focusin` and `focusout` events.

---

Note: React 17+ uses `focusout` rather than `blur` events for the `onBlur` event handler, so using `onBlur` may be exactly what is necessary. We want to only close the menu when focus leaves it or _anything inside of it_

https://blog.saeloun.com/2021/05/14/react-17-uses-browse-focusin-focusout-for-onfocus-onblur

**Comment by BrittanyIRL** [comment]
@csossi this touches the right click menus that are due on Friday. If you could test the following for it (the rest if blocked by a feature flag that doesn't need testing yet) it would be a massive unblocker for our team. 

This associated PR #8719 updates the context menus used in the dashboard. Can you verify the following: 

- Should be able to open the menu by clicking or with the keyboard in the My Stories view
- Should be able to navigate the menu with keyboard.
- Tabbing away from the menu should close it.
- Arrow keys should not close the menu.
- When navigating with keyboard you should see the focus border.
- All actions in the menu should work as before.

Thank you!

**Comment by csossi** [comment]
Verified in QA (according to scope specified above)
