### ISSUE TITLE
Implement Ads between Web Stories

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#8704]
## Feature Description

Currently, Ads display between Web Stories **pages**. Is it possible to implement ads between Web **Stories**? 

## Additional Context

Related support topic: https://wordpress.org/support/topic/ads-not-appearing-between-web-stories/

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Ad placement is handled by the format, specifically this would probably mean adding this capabilit to amp-story-player. Thus, I‘d open a ticket on the amphtml repo.

**Comment by o-fernandez** [comment]
> Ad placement is handled by the format, specifically this would probably mean adding this capabilit to amp-story-player. Thus, I‘d open a ticket on the amphtml repo.

I see that Lucky has added the request, but let's also keep this ticket here for our tracking. I'm curious to keep an eye on this request.

**Comment by swissspidy** [comment]
Closing this for now to keep our backlog tidy
