### ISSUE TITLE
Renderer: Remove return types from filter callbacks

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8713]
## Bug Description

There can be fatal errors if some other plugin does filter values in unexpected ways.

Reported a few times on the forums:

* https://wordpress.org/support/topic/fatal-php-error-22/
* https://wordpress.org/support/topic/wordpress-critical-error-5/
* https://wordpress.org/support/topic/critical-error-caused-by-webstories-plugin/

Need to remove the return type declarations here (for both methods!):

https://github.com/google/web-stories-wp/blob/cc48e898fb72927854cea135a132524a2a7a4412/includes/Renderer/Single.php#L52-L84

And update the PHPDoc to include `mixed` as the param/return type.

## Expected Behaviour

No fatal errors

## Additional Context

- Plugin Version: 1.10
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Another report: https://wordpress.org/support/topic/after-update-i-cannot-call-to-edit-articles-or-sites/

need to remove the return type for these two filter callbacks and update the docblocks:

https://github.com/google/web-stories-wp/blob/833cc68bd99067cc2288f7026a32f2f0060ff9b8/includes/Admin/Editor.php#L141-L188

There might be more, so let's go through all filter callbacks.

**Comment by spacedmonkey** [comment]
Let's also a lint or something for this, so this doesn't happen again.

**Comment by swissspidy** [comment]
That's what updating the PHPDoc docblocks would help for. Then our existing linters would catch this.

**Comment by spacedmonkey** [comment]
But changing to mixed in all these functions, will that not effect phpstan?

**Comment by swissspidy** [comment]
It does, but that's good.

For example, the `replace_editor()` method mentioned above currently expects `$replace` to be a bool.

But another plugin can filter this to be `null`, an `int`, or something completely different. So we need to reflect that in the docblock.

And then PHPStan will automatically prevent us from adding a return type declaration because of the unknown type.

I can whip up a quick PR to explain this a bit more, if it helps.

**Comment by spacedmonkey** [comment]
> I can whip up a quick PR to explain this a bit more, if it helps.

Hope, I got it. Should we do this for all filters callbacks in the PR, just in case?

**Comment by swissspidy** [comment]
Yeah I think everywhere we use `add_filter()` with some callback we should remove the types & update docblocks accordingly.

For example, `Story_Post_Type::bulk_post_updated_messages( array $bulk_messages, $bulk_counts ): array` should be changed to something more like this:

```php
/**
 * Filters the bulk action updated messages.
 *
 * @since 1.1.0
 *
 * @param string[]|mixed $bulk_messages Arrays of messages, each keyed by the corresponding post type. Messages are
 *                               keyed with 'updated', 'locked', 'deleted', 'trashed', and 'untrashed'.
 * @param int[]          $bulk_counts   Array of item counts for each message, used to build internationalized strings.
 *
 * @return array|mixed Bulk counts.
 */
public function bulk_post_updated_messages( $bulk_messages, $bulk_counts ) {
	if ( ! is_array( $bulk_messages ) ) {
		return $bulk_messages;
	}

	$bulk_messages[ self::POST_TYPE_SLUG ] = [
		/* translators: %s: Number of stories. */
		'updated'   => _n( '%s story updated.', '%s stories updated.', $bulk_counts['updated'], 'web-stories' ),
		'locked'    => ( 1 === $bulk_counts['locked'] ) ? __( 'Story not updated, somebody is editing it.', 'web-stories' ) :
			/* translators: %s: Number of stories. */
			_n( '%s story not updated, somebody is editing it.', '%s stories not updated, somebody is editing them.', $bulk_counts['locked'], 'web-stories' ),
		/* translators: %s: Number of stories. */
		'deleted'   => _n( '%s story permanently deleted.', '%s stories permanently deleted.', $bulk_counts['deleted'], 'web-stories' ),
		/* translators: %s: Number of stories. */
		'trashed'   => _n( '%s story moved to the Trash.', '%s stories moved to the Trash.', $bulk_counts['trashed'], 'web-stories' ),
		/* translators: %s: Number of stories. */
		'untrashed' => _n( '%s story restored from the Trash.', '%s stories restored from the Trash.', $bulk_counts['untrashed'], 'web-stories' ),
	];

	return $bulk_messages;
}
```

This way there will be no error if some other plugin filters this to return something unexpected.

Related reading: https://core.trac.wordpress.org/ticket/51525
