### ISSUE TITLE
Media: Actually crop images when using zoom/masks

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#8715]
## Feature Description

Currently in the stories editor, there is functionality to "crop" images. This doesn't not create new file, but uses masks to zoom in to image. Meaning that, a user could zoom into a section of an image they wish displayed. However, it does mean that the full image is downloaded on the story / in the editor. For a large image, this could be wasteful. 

In WordPress 5.5, functionality to edit inline image was [added](https://make.wordpress.org/core/2020/07/20/editing-images-in-the-block-editor/).  To enable this functionality, a new REST API for editing images was [added](https://github.com/WordPress/wordpress-develop/commit/e51a554f5da556804e05e0bb498f59473de8ce7d). This api includes functionality to crop and rotate images. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Related: #5985

**Comment by spacedmonkey** [comment]
I wonder if we should revisit this, as the WP min version has been increased. This should be simple as they is an existing endpoint for this.

**Comment by swissspidy** [comment]
I want to explore this as part of the video cropping epic, using FFmpeg to do this task client-side so it works for both images and videos.

**Comment by swissspidy** [comment]
Closing in favor of #5985
