### ISSUE TITLE
Render timeout waiting for service amp-story-render to be ready.

### ISSUE THREAD

**Issue by markllego** [GoogleForCreators/web-stories-wp#8718]
## Bug Description

I recently installed Google Web Stories and after using the Inspect Element (Console) the following errors are generated:

Render timeout waiting for service amp-story-render to be ready.​​​

index.js:59 Uncaught Error: Render timeout waiting for service amp-story-render to be ready.​​​
at ha (index.js:59)
at pb.createError (log.js:346)
at timer-impl.js:145
at timer-impl.js:86

## Steps to Reproduce

1. Go to https://www.teacherph.com/
2. Right-click anywhere on the page and select Inspect then click Console
3. Scroll down to the bottom of the page
4. See errors (screenshot attached)

## Screenshots

![Screenshot (444)](https://user-images.githubusercontent.com/9133877/129773583-defc9c94-78a9-4a17-9e77-896687160cb9.png)

## Additional Context

WordPress Version: 5.8
Web server: Apache/2.4.48 (Unix) OpenSSL/1.1.1f
PHP version: 7.4.21 (Supports 64bit values)
DB version: 10.5.12-MariaDB-1:10.5.12+maria~focal

WEBSTORIES_VERSION: 1.10.0
WEBSTORIES_DB_VERSION: 3.0.11
WEBSTORIES_AMP_VERSION: 2.1.3
WEBSTORIES_CDN_URL: https://wp.stories.google/static/11
WEBSTORIES_DEV_MODE: Disabled
Theme supports: Enabled

Experiments
Stickers: Enabled
Eyedropper: Enabled
Video Cache: Enabled
Mute Videos: Enabled

libxml Version: 2.9.10

Browser: Google Chrome
Version: 92.0.4515.159

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Thanks for your thorough report! I've raised this with the AMP project directly as it seems like a bug with `amp-story-player` itself: https://github.com/ampproject/amphtml/issues/35712

**Comment by mauteurs** [comment]
Hi,
Any update about this issue. I've had the same thing on my setup.

**Comment by swissspidy** [comment]
@mauteurs Since I've reported this at https://github.com/ampproject/amphtml/issues/35712, please subscribe to that ticket for any updates. Could you please share your site's URL here? Also try temporarily disabling all your plugins, clearing your browser cache & viewing the site in incognito mode to see if there's a difference.

@markllego I am not currently seeing this error on your page anymore. Can you confirm that?

**Comment by mauteurs** [comment]
> @mauteurs Since I've reported this at [ampproject/amphtml#35712](https://github.com/ampproject/amphtml/issues/35712), please subscribe to that ticket for any updates. Could you please share your site's URL here? Also try temporarily disabling all your plugins, clearing your browser cache & viewing the site in incognito mode to see if there's a difference.
> 
> @markllego I am not currently seeing this error on your page anymore. Can you confirm that?

Hi, my website isn't online
![rect903](https://user-images.githubusercontent.com/89387433/130430388-6fdf7d18-9984-4ed2-bd8e-06694823bdb9.png)

**Comment by markllego** [comment]
@swissspidy Hi Sir, the error still persists.

![Screenshot (8)](https://user-images.githubusercontent.com/9133877/130532263-7bbabac6-4980-42f4-88a5-a97e2ab6a469.jpg)

**Comment by swissspidy** [comment]
This is being handled in https://github.com/ampproject/amphtml/issues/34271. Please follow that ticket for any progress on that.
