### ISSUE TITLE
Quizzes and Polls

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8725]
## Task Description

[`<amp-story-interactive>`](https://amp.dev/documentation/components/amp-story-interactive/) provides rich set of interactive experiences for stories, including quizzes, polls and results.

Example:

![quiz-art](https://user-images.githubusercontent.com/841956/129915215-37337d2c-0aa3-4213-8a3c-53a5d2a1ae73.png)

This epic covers the addition of binary polls, interactive polls and quizzes to the Web Stories editor.

**Comment by swissspidy** [comment]
New interactive components will be available soon: [sliders](https://amp.dev/documentation/components/amp-story-interactive/#amp-story-interactive-slider), [image quizzes](https://amp.dev/documentation/components/amp-story-interactive/#amp-story-interactive-img-quiz) and [image polls](https://amp.dev/documentation/components/amp-story-interactive/#amp-story-interactive-img-poll). 

![unnamed (1)](https://user-images.githubusercontent.com/841956/135873578-4020d489-33d1-42d5-b2c9-2b3868d6e0ed.png)

![image (10)](https://user-images.githubusercontent.com/841956/135873585-d87663bd-ad20-49ae-9b06-d8af5329fc89.png)

Sliders allow users to select a specific value from a range, offering more granular controls over the options. By default, the slider will be configured as a percentage selection (ranging from 0 to 100% inclusive), but it's possible to provide an emoji that will grow or shrink depending on the location where the user slides the thumb. More info to come in the official release.

Image quizzes / polls allow creators to generate more immersive quizzes and polls by offering images to select instead of text. They can be mixed and matched with regular quizzes / polls to contribute towards a percentage or categorical results component (quizzes can interact with percentage results and polls can interact with categorical results, but a quiz and a poll won't interact with the same results component, just like before). The backend integration for these two components are similar to regular quizzes and polls.

**Comment by TCurty** [comment]
Hi @swissspidy the public roadmap says this feature is blocked. Is that still the case or can we expect it soon as you said above? 

Thank you

**Comment by swissspidy** [comment]
@TCurty My above comment was in regards to new interactive components being supported soon by the Web Stories format itself, not by the WordPress story editor. There are still some things we need to figure out before we can bring quizzes and polls to the plugin. So yeah, still blocked at the moment.

**Comment by bawarkamalqader** [comment]
Is there any update on this matter? We are integrating web stories into our custom cms, and any help about adding interactive content like quizzes and polls would be very important for us

At least if you could provide some documentations about adding new elements not supported currently would also be very helpful.

Is there any way this could be implemented in a close future?

**Comment by swissspidy** [comment]
We don't have any plans at this point to support quizzes and polls.

In theory, in the WordPress plugin you could add them yourself on the frontend using PHP. Example to give you an idea:

```php
namespace Demo\UseAtYourOwnRisk\WebStories;

add_action(
	'init',
	static function() {
		if ( ! class_exists( '\Google\Web_Stories_Dependencies\AMP_Base_Sanitizer' ) ) {
			return;
		}

		add_filter(
			'web_stories_amp_sanitizers',
			static function( $sanitizers ) {
				$sanitizers[ \Gorilla\Web_Stories\AMP_Sanitizer::class ] = [];

				return $sanitizers;
			}
		);

		class AMP_Sanitizer extends \Google\Web_Stories_Dependencies\AMP_Base_Sanitizer {
			/**
			 * Sanitize the HTML contained in the DOMDocument received by the constructor.
			 */
			public function sanitize(): void {
				// Insert a quiz on page 2 of every story.

				$page_2 = $this->dom->body->getElementsByTagName( 'amp-story-page' )->item( 1 );

				if ( $page_2 instanceof \DOMElement) {
					$page_2_grid_layer = $this->dom->createElement('amp-story-grid-layer');
					$page_2_grid_layer->setAttribute('template', 'vertical');
					$page_2_grid_layer->setAttribute('aspect-ratio', '412:618');
					$page_2_grid_layer->setAttribute('class', 'grid-layer');
					$page_2_poll = $this->dom->createElement('amp-story-interactive-binary-poll');
					$page_2_poll->setAttribute('endpoint','URL TO YOUR POLLS BACKEND');
					$page_2_poll->setAttribute('id','POLL ID');
					$page_2_poll->setAttribute('option-1-text','Ja');
					$page_2_poll->setAttribute('option-2-text','Nein');
					$page_2_poll->setAttribute('prompt-text','Was meinst du?');
					$page_2_grid_layer->appendChild($page_2_poll);

					$page_2->appendChild($page_2_grid_layer);
				}
			}
		}

	}
);
```

As for the editor, all the packages are open source so feel free to fork them and add your own things on top of it. Take a look at existing elements such as the `product` element for example if you want to
