### ISSUE TITLE
Keyboard Shortcuts Should Use prettifyShortcut

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#8726]
There are some keyboard shortcuts defined in `keyboardShortcutsList` as well as in the new right click context menus that aren't using the `prettifyShortcut` util. They should use this. 

## Acceptance Criteria 
- Use `prettifyShortcut` on shortcuts where possible in right click menus and keyboard shortcuts popup

**Comment by BrittanyIRL** [comment]
@csossi 

QA on this is just regression testing on the keyboard shortcuts popup in the editor - all the keys listed should be the same as staging.

**Comment by csossi** [comment]
Verified in QA
