### ISSUE TITLE
Unable to Edit Text in Windows on Firefox

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#874]
## Bug Description

Unable to edit text in Win10/FFox. Clicked the "+" to add. Then tried to click within the text box to edit and am unable to.

Reported by Claudio in #576 

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Note: The issue seems to happen generally in Firefox, unrelated to the OS.
