### ISSUE TITLE
Dashboard: Clean up or Delete  "Saved Templates"

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#8746]
With grid updates for performance improvements to My Stories and Explore Templates, the saved templates view is increasingly obsolete. It doesn't make sense to take time to keep this up to date if we're not going to use it any time soon.

As it is not coming up soon on the roadmap, I think we should just clear out the code for it in the dashboard. When we are ready to implement, very little of the current code is relevant anymore so we'd really not be missing anything.

If this is wrong and we are wanting to implement this feature soon then instead we should take the time to catch the components up.

**Comment by BrittanyIRL** [comment]
@choumx @o-fernandez  can you weigh in on the priority for saved templates so that we can clean this up accordingly?

**Comment by swissspidy** [comment]
There are also plenty of other half-baked views like templates bookmarking, which we've never implemented and would be nice to remove too.

**Comment by o-fernandez** [comment]
I think it's fine to remove this for now, I don't see a need to implement saved templates in the near future.

**Comment by BrittanyIRL** [comment]
awesome, thanks for the quick reply ❤️
