### ISSUE TITLE
Hotlinked video optimization

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#8756]
Per @spacedmonkey in https://github.com/google/web-stories-wp/issues/8653#issuecomment-903909557

Consider what to do if a user hotlinks a video that's not optimized for web serving. 
1) Allow it anyway? 
2) Disallow the embed?
3) Prompt user to import video into WP media library and optimize the video using the WP editor optimization? 
4) others?

**Comment by gajasinski** [comment]
@aaskedall would love your thoughts on this. Helping the users make the best decision should be key, but protecting the consumer's experience as well. We probably want to warn somehow on the embed and/or have the user import into the WP media library (now sure what this workflow looks like or if even possible).

**Comment by gajasinski** [comment]
@spacedmonkey @aaskedall - from the creator's perspective we probably want to check the size and recommend importing into the media library. I think we'd stay away from completely blocking, but i can be persuaded

**Comment by swissspidy** [comment]
Taking the example from https://github.com/google/web-stories-wp/issues/8653#issuecomment-903909557:

If the external video/image is extremely large, it most likely will still be very large even after importing into the media library. So there's no guarantee that importing into media library will magically solve all their problems.
So I'd tend to recommend completely blocking and displaying a message to manually optimize & import instead.

**Comment by gajasinski** [comment]
So I'm understanding the following:

1. user attempts to link an extremely large video/image
2. WPE checks size and, if too large, blocks link and throws warning to manually optimize and import
3. user can clear error, attempt again with manually optimized link
