### ISSUE TITLE
High memory consumption when using ffmpeg.wasm

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8768]
## Bug Description

User report:

https://wordpress.org/support/topic/aw-snap-when-optimizing-videos/

Related upstream issues:

https://github.com/ffmpegwasm/ffmpeg.wasm/issues/111
https://github.com/ffmpegwasm/ffmpeg.wasm/issues/136
https://github.com/ffmpegwasm/ffmpeg.wasm/issues/200

There is an issue with memory consumption when invoking ffmpeg.wasm, where the worker threads are not properly closed by ffmpeg.wasm itself and accumulating with each use. This massively increases memory usage over time, which can only be "fixed" by reloading the tab (or closing it and opening it again).

Related to that: when uploading multiple files, multiple FFmpeg instances are created instead of re-using an existing one, which also increases memory usage. But instances can't really be shared because ffmpeg.wasm can only run one command at a time. So while not super great, this is negligible if we properly terminate instances after use.

## Expected Behaviour

FFMpeg threads should be properly cleaned up after usage.

`FS.unlink()` doesn't seem to bring the expected effect

Luckily, the new `exit()` method introduced [in the latest release](https://github.com/ffmpegwasm/ffmpeg.wasm/releases/tag/v0.10.0) (which we thought would only be helpful for _cancelling_ in-progress threads) helps with this, as this will properly close the threads.

So ideally we call `exit()` right after processing each file. In my testing that successfully closed all the worker threads.

## Steps to Reproduce

1. Open Chrome's Task Manager and the "Sources" tab in the dev tools.
2. Upload a video to the canvas so it gets transcoded
3. See a bunch of worker threads being created but not closed, even after upload is finished.
4. Upload another video and see how memory usage is steadily increasing

## Screenshots

<img width="814" alt="Screenshot 2021-08-24 at 11 28 13" src="https://user-images.githubusercontent.com/841956/130594998-c7f445be-d251-42c8-9ab4-8de73828f277.png">

## Additional Context

- Plugin Version: 1.10.0
- WordPress Version: 5.8
- Operating System: macOS
- Browser: Chrome

**Comment by spacedmonkey** [comment]
Oh wow, this is a big deal. Looking at service workers, after two video transcoded, it was keeping 400+MB. 

<img width="212" alt="Screenshot 2021-08-24 at 13 12 27" src="https://user-images.githubusercontent.com/237508/130614265-54eac480-63ef-4102-ac4f-dd819edc24a4.png">

**Comment by csossi** [comment]
Verified in QA
