### ISSUE TITLE
Media Hotlinking: use the `hotlink` endpoint for server-side validation

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#8773]
## Feature Description
In #8731, a new endpoint is added for validating a media URL and getting useful data about it (mime type, extension, etc.).

We should now update the client-side logic to actually use this endpoint as well.

Example request: `await wp.apiFetch({path: 'web-stories/v1/hotlink?url=https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-webm-file.webm'})`

**Comment by csossi** [comment]
Verified in QA
