### ISSUE TITLE
Quiz/Poll: Backend Endpoint

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8774]
## Feature Description

For the quizzes and polls feature (#8275) we need to create a backend endpoint [as per the documentation](https://amp.dev/documentation/components/amp-story-interactive/).

```
// Getting the votes for an interactive.
// If no client param, selected will always be false
// (can be used to display the results on a dashboard).

// GET https://backend.com/v1/interactives/<id>?type=0&client=amp-281391283

Response: {
	  "options": [
		    {"index": 0, "selected": false, "count": 0},
		    {"index": 1, "selected": false, "count": 5},
		    {"index": 2, "selected": false, "count": 7},
		    {"index": 3, "selected": false, "count": 2}
	  ]
}

// POST http://localhost:3000/interactives/<id>:vote?
        type=0&
        client=amp-281391283 body:{"option_selected": 2}

```

```
// Posting the vote for an interactive. Client param is required.

POST_URL = "{endpoint}/{interactiveId}:vote?type={interactiveType}&client={ampId}"
POST_BODY = {'option_selected': 1}

Response: No response necessary
```

* `interactiveId` is basically `${base64(CANONICAL_URL)}+${ELEMENT_ID}`, so just a long string
* `endpoint` in the above examples is the full API endpoint, e.g. `https://backend.com/v1/interactives`
* `ampId`: client ID that identifies the session
* `interactiveType` is an [enum](https://github.com/ampproject/amphtml/blob/3a86226fe428ce72adb67cffe2dd2f1fae278a35/extensions/amp-story-interactive/1.0/amp-story-interactive-abstract.js#L48-L52) (0=quiz, 1=poll, 2=results)

## Security and Privacy

AMP gives Client IDs to sessions that identify users. In order to prevent the database to contain these IDs, the client ID will be hashed with the `interactiveID`s to prevent records to be identified across different interactive components in a way that cannot be reversed.

In the database, the users cannot be matched, and the only way to retrieve the data of a user is to provide the client ID _and_ the interactive ID. This means the ID stored in the backend for a client/user will be unique across all the interactive components (eg: the same client can vote on two interactive components on the same story, but the ID used as a key to identify the votes will be different).

No IP addresses or anything will be stored.

### To-do

We need to implement this backend endpoint in the WordPress plugin.

* [ ] Create design brief for implementation

**Comment by spacedmonkey** [comment]
When consider this functionality, this is what I was thinking. 

Create a new post type, called `story_quiz`. This post type would store, the questions / options. Maybe as a json object in post_content_filtered or post meta. 

When a user answers the quiz, the data can be stored in comments against the quiz story id. We could also store a summary of the data, like number of responses to a question, for easier querying. Comments will be stored in a custom comment type. 

I really don't want to add a custom table here, it will add a lot of overhead and not all hosts support adding new tables.

**Comment by swissspidy** [comment]
I don't think we can make a case for any approach before first addressing all the open questions and also the security and privacy concerns in a design brief. Then we get a better sense for what makes most sense.

Some thoughts on the required data structure / example above to help with that:

* Since `interactiveId` contains the element ID, does that mean creating a new quiz in the editor needs to create a new quiz entry in the database?
  * If so, how does that work when duplicating/deleting the element in the editor?
  * Also, how does that work when modifying an existing poll's options in the editor? What happens to the existing replies?
* Since `interactiveId` contains the story's URL, how does that work when the story's URL changes (site migration, permalink change)?
* Are we planning on surfacing quiz / polls data somehow in the admin/editor so they can see all responses?
* Do creators need to be able to modify responses somehow, for example to reset all responses back to 0 after testing?

Some of these are product-related questions, so needs some clearer definition there first.

cc @o-fernandez @choumx
