### ISSUE TITLE
Right Click Menus: Enable Feature Flag

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#8781]
Set Right Click Menu feature flag to default true.

This ticket is to serve as QA for the right click menu feature. 

## Acceptance Criteria 
- right click menus enabled by default 
- QA directions of the feature. @samwhale I know you started this already in a doc.

**Comment by samwhale** [comment]
Follow this doc to see what to test: https://docs.google.com/document/d/1gcVTVMdGaM9Ds8T_EJAGQbiBlSArnJh_onuTBXmSISs.

**Comment by BrittanyIRL** [comment]
@csossi this is a massive feature for pea pod in the next release, if there's any way to QA it today so we can get it bug bashed that would be awesome.

**Comment by csossi** [comment]
How should stickers be handled here? I added a sticker to a page. If I right-click on it, I get the "background" context menu. 

I was able to select Scale And Crop here, and the editor crashed. (should the context menu be disabled for stickers?)

https://share.getcloudapp.com/KouJJArE

**Comment by samwhale** [comment]
good find @csossi. Stickers didn't exist when the context menu feature was designed, so I added a menu for stickers too:
<img src="https://user-images.githubusercontent.com/22185279/131533273-d5886210-b925-452e-a604-07eb18b481ba.gif" height="400px" />

**Comment by csossi** [comment]
Verified in QA
