### ISSUE TITLE
KSES: page attachments are bering removed

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8784]
## Bug Description

In #8578 we replaced `amp-story-page-attachment` with `amp-story-page-outlink`,

Unfortunately, due to a typo, `amp-story-page-outlink` was not correctly added to the allowlist of HTML tags in WordPress KSES. It was not caught due to a missing test.

That means whenever a user without `unfiltered_html` capabilities publishes a story, pages using a page attachments are silently discarded by WordPress.

This affects everyone except super admins on Multisite, and everyone except admins & editors on single site.

Props to Jonathan for finding this bug.

## Expected Behaviour

`amp-story-page-outlink` should be in the KSES allowlist.

## Steps to Reproduce

1. Publish a story with page attachment as an author.
2. Look for page attachment on the frontend.

## Additional Context

- Plugin Version: 1.10.0
- WordPress Version: 5.8
- Operating System: macOS
- Browser: Chrome

**Comment by csossi** [comment]
Verified in QA
