### ISSUE TITLE
Media Hotlinking: Show "Preview unavailable" placeholder if loading fails

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8803]
## Feature Description

Taking this out of #8667.

Sometimes a video or image cannot be displayed in the editor due to CORS, but it will still work fine on the frontend.

For this case, we need some sort of placeholder in the editor that says "Preview unavailable" or something like that.

For example, the image https://pascalbirchler.com/wp-content/uploads/2021/08/juliana-malta-Km_14xo_PIo-unsplash-scaled-e1628006213150-1536x768.jpg would be totally fine to embed, but the editor says it's invalid because of those missing headers.

To give an example, in Gutenberg, embeds which cannot be previewed are displayed like this:

![687474703a2f2f3773747564696f2e66722f6769746875622f677574656e626572672f73637265656e73686f742d312e706e67](https://user-images.githubusercontent.com/841956/131358040-7a94a25e-56cd-4766-8be0-29a5b0200a76.png)

**Comment by swissspidy** [comment]
FYI @aaskedall

**Comment by dreamofabear** [comment]
Re: CORS, can we distinguish between the cases:
1. The placeholder preview fails but will render fine in the FE
2. Both preview and FE will fail to render the image

Wondering if we should prompt the user to verify visibility of the image in the story preview.

**Comment by swissspidy** [comment]
I don‘t think (2) ever happens.
Only (1), and only if video optimization (and thus cross-origin isolation) is enabled.

There are also some ideas to show a preview in the editor using a simple CORS proxy, but that‘s prone to abuse and raises security questions.

Also worth noting that without a preview in the editor we don‘t know an image‘s correct aspect ratio / dimensions.

**Comment by aaskedall** [comment]
![image](https://user-images.githubusercontent.com/4030811/132414319-ce612afd-cfcf-49d3-9987-3e3c3847fb15.png)

@swissspidy Would this be an ok place to start?

**Comment by miina** [comment]
@aaskedall What would the "View in browser" link do, would it open just the media URL in a new tab? Perhaps "View Image" or "View Video" or something similar would be more informative (with an external link icon), then the user would see right away as well if the element is video or image without having to select the element. Thoughts?

**Comment by aaskedall** [comment]
I updated it to say view preview since it should work in the preview window. I think that is the info a user would care the most about. How does this look in my story?

https://www.figma.com/file/1YM3jA9h4QGc4xLdyaXIJS/Stories-Sprint-1.7?node-id=9776%3A384592

**Comment by dreamofabear** [comment]
Aside: I wonder how creators will grapple with authoring a story page with an image/video that can't be previewed and whose aspect ratio is unknown. E.g. I think it'll probably be difficult to layer elements on top, resize accurately, and jumping between the preview mode and the editor is unwieldy.

Some thoughts:
- Should we force the user to manually input the aspect ratio to make sure that it won't be distorted?
- Should the placeholder have a different visual treatment to make a little easier to work with? E.g. low-contrast checkerboard pattern, or some stock photo with a watermark that tells the user to preview the story.
- I wonder if a "View in browser" button directly on the image might feel weird -- currently, there are no such call-to-actions/links on elements in the canvas

**Comment by swissspidy** [comment]
Sounds like we can‘t get around a server-side solution to at least get the aspect ratio and perhaps a blurry placeholder as suggested at some point.

**Comment by aaskedall** [comment]
Updated figma here. https://www.figma.com/file/1YM3jA9h4QGc4xLdyaXIJS/Stories-Sprint-1.7?node-id=9776%3A384592

I think the way images are scaled currently crops the image vs it being proportionally wrong so perhaps this is not a problem. 

In regards to the view in browser preview, A user inserting an image will immediately be confused by this state, if the CTA is right there to show the image in the preview it should then be more understandable that "oh, it only doesn't show up in the editor"

**Comment by dreamofabear** [comment]
Alternative: require thumbnail/poster upload to WP for display in the editor, and add a new optional "hotlink URL" field to image elements. When specified, causes the image element to render the hotlink URL in the output STAMP. Higher friction UX, but still may satisfy the user intent to avoid bandwidth costs on creator origin.

Other notables:
- We discussed COEP workarounds some time ago in #6776.
- Interesting possible long-term solution: https://developer.chrome.com/blog/coep-credentialless-origin-trial/

**Comment by swissspidy** [comment]
The more I think about it, the more I think we should explore using a CORS proxy so that image requests in the editor are proxied through WordPress. Despite concerns around performance/abuse/security.

That would be the option with least UX friction.

**Comment by swissspidy** [comment]
Closing this as the CORS proxy approach seems to be working well.
