### ISSUE TITLE
Karma: improve error output

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8809]
## Task Description

Error output in Karma tests ought to be improved by #6900 / #6545, but it doesn't seem to work as expected or is not good enough yet.

We don't need all this bloated error output on CI, making the logs impossible to use.

**Comment by swissspidy** [comment]
Regarding the `Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27` warning, it sounds like we could do a better job with cleaning up media players after tests, e.g. by setting `mediaElement.src = ''`. See https://bugs.chromium.org/p/chromium/issues/detail?id=1232649#c18

We also might be able to set `--max-web-media-player-count=<some high number>` as a workaround.

**Comment by BrittanyIRL** [comment]
See #6545 for more context
