### ISSUE TITLE
Settings: Allow disabling archive page

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8811]
## Feature Description

See #4862 for history / context on this matter.

We want to allow users to disable the default `/web-stories` archive page.

The idea is to add a new section to the settings page with a dropdown offering two options:

1. Default
2. Disable

Here are some mocks:

**Default**

![Screenshot 2021-08-12 at 15 39 31](https://user-images.githubusercontent.com/841956/129209665-04647846-1b44-41fa-ab1c-86ffa3291407.png)

For convenience, a link to the current archive page can be displayed.

**Note:** We might offer an option to customize the `/web-stories/` slug in the future

**Disable**

![Screenshot 2021-08-12 at 15 56 08](https://user-images.githubusercontent.com/841956/129209617-2e39410d-c053-4fb3-b945-164944c74b72.png)

**Notes**

* In places like the Web Stories block, the TinyMCE button and the customizer, we must hide the UI option for displaying an archive link if the archive has been disabled.
* This can be behind a feature flag initially
* Need to flush rewrite rules when changing this setting

**Comment by csossi** [comment]
Regarding this test step:

1. Test archive is really disabled
2. Diable Stories Archive ( see above ).
3. Go to /web-stories on the front end.
4. Ensure page is a 404.

Seeing this instead of a 404 page:
![image](https://user-images.githubusercontent.com/16945664/133788073-ae9fa089-0ca8-4a26-aaa3-4594c83b54be.png)

**Comment by swissspidy** [comment]
@csossi Looks like there is a general issue with 404s on thee QA site. Opening https://stories-qa-wordpress-amp.pantheonsite.io/sfsfsfsgfsg/ should 404 in theory but for some reason doesn't. On my local site it works as expected.

So let's ignore that for QA here.

Is everything else working?

**Comment by csossi** [comment]
Everything else is fine, @swissspidy 

Verified in QA
