### ISSUE TITLE
Settings: Allow choosing custom archive page

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8812]
## Feature Description

See #4862 for history / context on this matter.

We want to allow users to use a custom static page for the `/web-stories` archive page.

The idea is to add a new `Custom` option to the dropdown added in #8811.

**Custom**

![Screenshot 2021-08-12 at 15 43 36](https://user-images.githubusercontent.com/841956/129209582-24260583-fcc9-4446-9498-62f746e3b2f9.png)

For convenience, a link to the current archive page can be displayed.

There's an autocomplete dropdown to select the page.

The custom page can be annotated as such in the posts list table:

![Screenshot 2021-08-12 at 15 40 06](https://user-images.githubusercontent.com/841956/129210024-ce68c9ce-eb45-4ff1-a2d8-9b229b3c5dbc.png)

"Custom" would mean selecting a custom page for the archives and that users would simply edit that page in the block editor, using the Web Stories block if they want to.

If users create a custom page like this, there would be no pagination etc.

### Dashboard

* Add a third "Custom" option to the "Stories Archive" dropdown.
* Once that option is selected, display a dropdown with autocomplete to select an existing page in WordPress.   
  * There are existing autocomplete/dropdown components for this.
  * The pages can be searched via the REST API
* Once a page is selected, the page ID is stored in `wp_options`
* Ensure rewrite rules are flushed when this has been changed  
  Note: ideally we don't flush rewrite rules twice.

### Page list table

* Filter `display_post_states` to display a "Web Stories Page" label in the page list table in WP admin

### `Story_Post_Type`

* Set `has_archive` depending on whether the archive has been enabled/disabled/customized
  Pseudo code:
  ```php
  $archive_page_option    = get_option(...);
  $custom_archive_page_id = get_option(...);
  $has_archive            = true;
  if ( 'disabled' === $archive_page_option ) {
    $has_archive = false;
  } elseif ( 'custom' === $archive_page_option && get_post( $custom_archive_page_id ) ) {
    $has_archive = urldecode( get_page_uri( $custom_archive_page_id ) );
  }
  ```
  (WordPress supports this out of the box)

### Out of scope

Out of scope for this ticket:

* Changing URL structure for individual stories
* Any custom redirect from `/web-stories/` to custom archive page

**Comment by csossi** [comment]
Verified in QA

![image](https://user-images.githubusercontent.com/16945664/134923169-b8fa4283-bc76-41f9-9569-7912b3fed91d.png)
