### ISSUE TITLE
3P Media: Add category filter for Coverr

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8814]
## Feature Description

Currently blocked by `b/197847990` on the 3P Media API side.

The idea is to offer the same category filters for Coverr as we already do for Unsplash and Tenor.

**Comment by swissspidy** [comment]
This should be unblocked in the next 1-2 weeks.

**Comment by swissspidy** [comment]
@timarney FYI this is now unblocked and available in the API, so we're good to go for implementing it in the editor

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #12045.

Tested in Firefox, Chrome and Safari, as an Admin, an Author, an Editor and a Contributor.

Clicking on a pill filters videos by that subject;
Clicking again on the same pill clears selection and resets results to "All".

https://images.zenhubusercontent.com/235435637/33f9a223-5aac-4d0a-9fb4-abad0d9b2cd6/2022_08_04_10_09_10.mp4
