### ISSUE TITLE
Change tooltip placement if there's not enough space

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8822]
## Feature Description

While working on #8374, it was noted that tooltips can be cut off if they're near the edge of the viewport:

<img width="369" alt="Screenshot 2021-08-24 at 15 25 44" src="https://user-images.githubusercontent.com/237508/130638213-f8b13c9f-b63c-4ed2-bcac-eb6f211e4a62.png">

For cases like this, we should look into automatically changing the tooltip position if there's not enough space at the desired position. Just like we do for popups. In the example above, the tooltip could be added to the left instead.

**Comment by csossi** [comment]
Verified in QA
