### ISSUE TITLE
Add toggle to turn off AdSense for specific stories

### ISSUE THREAD

**Issue by mxbclang** [GoogleForCreators/web-stories-wp#8823]
## Feature Description

<a href="https://wordpress.org/support/topic/suggestion-checkbox-to-remove-adsense-in-specific-stories/">A forum user requested</a> the addition of a toggle to turn off ads via AdSense for specific stories. Right now, if AdSense is connected in the Web Stories plugin settings, ads are added to all stories. This would allow users to turn ads off for specific stories if needed. The user says:

> Perhaps the publisher doesn’t want to show advertisements on the page (for example on some institutional/company page, but appear on other pages of the same site) or fix a policy violation issue without having to set a page exclusion within the Adsense settings.

**Comment by swissspidy** [comment]
This could go well with a similar feature where one could prevent ads from showing before/after certain pages, which the story format supports.
