### ISSUE TITLE
Discovery: Look into using images for page templates and text sets

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#8826]
## Context 

Now that we've got screenshots of every template page, we could try using them in the page templates panel of the editor to cut down on load time. On hover we could still render the full preview so that the user can see the animation - this would prevent us from loading any preview unnecessarily.

Just one idea, I am not sure if we want to mess with this yet or how this would impact the user created layouts. It's an option now though, so I wanted to start a conversation.

## Description 

Let's use the images we have from the work done on the dashboard's explore templates (screenshots of every page on the cdn by template slug and page number) and explore how we might do the same(ish) on page layouts and then text sets. 

Questions to address:  
- how to track page type? 
- how to toggle between page templates that have template images vs the placeholder grid (we'll need to adapt the CLI for. generating template images to have an alternate to generate with grids) 
- should the preview load on hover/focus to allow user to see animations before selecting? 
- What's the perf gain? 
- Do we still need to virtualize the list? 

Using findings here we'll figure out where to take this next.

**Comment by BrookeGraham** [comment]
### How to track page type?
- In `defaultTemplates.js` I added `type: template.pages[index].pageTemplateType,` to `templatePosters` while mapping through `template.postersByPage)`  in the `pageTemplates.reduce` this allows filtering as before. 

### How to toggle between page templates that have template images vs the placeholder grid (we'll need to adapt the CLI for generating template images to have an alternate to generate with grids)
- Grabbing a second set of images for grids vs image so on toggle, we would load the alt set of images. 

### Should the preview load on hover/focus to allow user to see animations before selecting?
- ???

### Do we still need to virtualize the list?
- Navigation (keyboard) is much smoother without virtualization. The jank is still present if virtualized. It does allow for a faster initial load, but some images will be missing while scrolling until they are loaded.

### What's the perf gain?
I took several renders and jotted down the avg time below. 
#### Before:
  no throttle -> 4213ms
  fast 3g ->  4145ms
  slow 3g -> 4539ms

#### Before (while trying to scroll to the very bottom):
  no throttle -> 37169ms
  fast 3g -> 42390ms
  slow 3g -> 45025ms

#### After (with virtualization):
  no throttle -> 3886ms
  fast 3g ->  3763ms
  slow 3g -> 4956ms

#### After (without virtualization):
  no throttle -> 2838ms
  fast 3g -> 3411ms
  slow 3g ->  4201ms

**Comment by swissspidy** [comment]
Nice perf gains! Thanks for doing this research.

> how this would impact the user created layouts

This part needs to be addressed still. Perhaps html-to-image could be used?

**Comment by BrookeGraham** [comment]
Todo list if we / when proceeding 

- Update CLI in templates to also include a version with images swapped for grids
- Implement way to filter template type by meta-data story page type. See example wip pre-work on [branch - try/static-page-layouts -> ](https://github.com/google/web-stories-wp/blob/try/static-page-layouts/packages/story-editor/src/components/library/panes/pageTemplates/defaultTemplates.js#L117-L131) `defaultTemplates.js` lines 117 - 131
- Use images in page layouts for templates (leave existing story rendering for custom layouts saved by users) See example wip pre-work on [branch - try/static-page-layouts -> ](https://github.com/google/web-stories-wp/blob/try/static-page-layouts/packages/story-editor/src/components/library/panes/pageTemplates/pageTemplate.js#L135-L144) `pageTemplate.js`  lines 135-144
- Create a second array similar to `postersByPage` for grid style images. When toggling between "grid" view and "image" view, grab corresponding images. Or store "grid" images in same `postersByPage` array, and only grab corresponding imaging based on toggle. 
- If keeping virtual scroll, fix jank / if removing virtual scroll implement standard grid keyboard nav, See example wip pre-work on [branch - try/static-page-layout](https://github.com/google/web-stories-wp/blob/try/static-page-layouts/packages/story-editor/src/components/library/panes/pageTemplates/templateList.js) `templateList.js`
- Figure out how to implement similar approach for `savedTemplates`

**Comment by BrookeGraham** [comment]
> Re: Implement way to filter template type by meta-data story page type. See example wip pre-work on branch - try/static-page-layouts -> defaultTemplates.js lines 117 - 131

Not 100% sure if this will actually map out correctly. Might be safer to create an actual mapping based on `id` of the two.

**Comment by BrittanyIRL** [comment]
Thanks, @BrookeGraham ! 

I think this gives us a solid launch point for an actual Epic to do this work efficiently and in a manner well communicated. 

As for the custom templates saved by users, I think that can be handled separately. The text-sets have been turned to images, the templates are also static and should follow suite. 

The only thing here that we need a thumbs up from Will, Andrew and George is if it's OK to lose the 'animate on hover/focus'. That's really the only "loss", but it comes at the gain of usability and speed so it feels worth it. 

I'll leave a note in the design channel asking. The speed improvements are substantial though!

**Comment by dreamofabear** [comment]
Ship it! 🚢 

> The only thing here that we need a thumbs up from Will, Andrew and George is if it's OK to lose the 'animate on hover/focus'.

I think that's fine and easily worth the performance gain. It also matches the current UX in the Explore Templates page.

2c: Eventually, it'd be nice to render the page with animations on mouse hover (like video autoplay in YouTube).

**Comment by BrittanyIRL** [comment]
> Ship it! 🚢
> 
> > The only thing here that we need a thumbs up from Will, Andrew and George is if it's OK to lose the 'animate on hover/focus'.
> 
> I think that's fine and easily worth the performance gain. It also matches the current UX in the Explore Templates page.
> 
> 2c: Eventually, it'd be nice to render the page with animations on mouse hover (like video autoplay in YouTube).

@choumx -
cool, i added a new epic and line item for the November release tentatively.

**Comment by BrittanyIRL** [comment]
(Closing since discovery provided enough information to figure out what all would be needed to map out an epic, thanks @BrookeGraham )
