### ISSUE TITLE
Dashboard: Template Details - Related Templates 

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#8827]
We have enough templates with metadata to make this grid show templates that are related to the one getting viewed in some capacity. Currently they're just at random.

I think we should match template metadata and show up to 6 templates that match.

## Acceptance Criteria 
- Display templates that are actually related (via metadata) in the template details view 
- Tests, please!

**Comment by csossi** [comment]
Verified in QA
