### ISSUE TITLE
Template colors added to story saved colors

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#8829]
## Description
- Template colors should be visible as "saved colors" in the editor under the "story" section (not all stories/global, specific to this one instance). 

## Additional information 

I did a bit of debugging here before pointing this and here's my starting point: 

- The colors' hex codes are in the metaData file of each respective template in the template package (packages/templates/src/raw/[template-name]/). They are stored as an array with a label for description and a hex code ({label: 'winter blue', color: '#a4deff'}).
- The saved colors isn't new, users can save their own colors already. Saved colors live in style_presets, accessible through the useStory context. When a story's loaded the saved colors get structured (see story-editor/src/app/story/effects/useLoadStory)
- Right now the colors of a template (template.colors) are not getting passed to getStoryPropsToSave when the 'use template' button is clicked and createStoryFromTemplate request is triggered.
- Pretty sure that the logic is all set up on the editor side to handle this, but that the saved colors of a template aren't quite making it into the story when the editor loads.

## Acceptance criteria
- When you use a template, once the editor loads you should see the same list of colors in the "saved colors" panel as you do in the template detail view of said template.

**Comment by csossi** [comment]
Verified in QA
