### ISSUE TITLE
Taxonomy: New tab in document panel

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#8835]
Prep the document panel to add in taxonomy support. 

## Acceptance criteria 
Should add a new tab to the document panel that is behind the new taxonomy feature flag. When that flag is on should get a new tab for Categories and Tags. 
For now, just add the title `Categories & Tags` and leave the section empty. 
Make sure that this has a demo in storybook.
Add in an initial karma test to toggle the section.

**Comment by swissspidy** [comment]
@BrittanyIRL didn't we agree on creating one panel per taxonomy in our sync yesterday?

**Comment by BrittanyIRL** [comment]
> @BrittanyIRL didn't we agree on creating one panel per taxonomy in our sync yesterday?

I thought we'd agreed on the one for now to let @aaskedall  take a stab at what that would look like with many panels. There's a chance that it gets to be _alot_ of extra panels? If I misunderstood that we can update it. Just seemed like for the time being 1 panel was the outcome. I'll go talk to andrew.
