### ISSUE TITLE
Taxonomy: Add tags

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#8838]
Sets up the initial tag section of the new section of the document panel with the ability to add a tag. 

See  #8830 for API details. 

Note that some users will have custom freeform taxonomies in their site. These will have the same structure as the baked-in tag structure, so try to keep that in mind here so we can support custom taxonomies here: #8849 

## Acceptance criteria 
- Can type a new tag and saves when comma or enter is pressed, updating the text into a tag. 
- Add tests

**Comment by swissspidy** [comment]
How does this relate to #8831?
