### ISSUE TITLE
Taxonomy: Add New Category

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#8841]
Clicking on the `Add New Category` "link" (it's a button) in a post expands the panel with a new input to name a category as well as a dropdown for a parent category. 

This will need to have it's own endpoint to save the category to WordPress (not just the story) and also the ability to grab parent categories specifically. 

This might be a good "nice to have" feature, not necessarily dire for the first implementation depending on how involved it is for infra. 

<img width="292" alt="Screen Shot 2021-08-29 at 2 52 00 PM" src="https://user-images.githubusercontent.com/10720454/131266545-3d46f59c-172c-41b6-80ac-d70d573fb38d.png">

## Acceptance criteria
- Click on 'add new category' get new section (see screenshot) 
- Add New Category button that's newly exposed should be disabled until valid content is in the new category name input. 
- Clicking on the add new category link like button (the toggle) should collapse this new section 
- Category that's added should be saved to WordPress not the story. New category should show up now in the list of available categories. 
- New tests please.

**Comment by swissspidy** [comment]
I left some comments in #8830 about the REST API, showing how easy it is to create a new tag/category via the API. I don't see this as a nice-to-have from that point of view.
