### ISSUE TITLE
Block: Add story selector for embedding single story

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8845]
## Feature Description

Splitting this out from #6894

We want to make the Single Story embed block more similar to the image block, allowing to choose between selecting an existing story or inserting from URL:

Mock:

![Screenshot 2021-08-12 at 16 07 51](https://user-images.githubusercontent.com/841956/129211562-2a454f90-a08f-44d9-92a2-a22855e76b2a.png)

The URL option would show the URL input field in a popup/tooltip like in the Image block.

The "Select Story" button would open the story selector we already have today, but only allow selecting 1 story (and not show a reorder option, obviously).

**Comment by csossi** [comment]
Verified in QA
