### ISSUE TITLE
Media hotlinking error handling

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8847]
## Bug Description

Noticed while testing #8806

When clicking into the input field and then moving out of it, `https://` is inserted in the input field and subsequently flagged as invalid URL.

I am then unable to clear the input field, so it's impossible for me to see the list of allowed file types.

I can not even select the text below the input field due to this.

## Expected Behaviour

If the input field is empty, this should not be happening.

## Steps to Reproduce

See video below

## Screenshots

https://user-images.githubusercontent.com/841956/131357539-8c34bfdd-a1cc-4f7a-94db-ac4018dbfb13.mov

## Additional Context

- Plugin Version: 1.11.0-alpha
- WordPress Version: 5.8
- Operating System: macOS
- Browser: Chrome

**Comment by csossi** [comment]
Verified in QA
