### ISSUE TITLE
Taxonomy: Support custom set ups 

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#8849]
## Feature Description

Some users will have custom taxonomies set up. These follow the same structure and can be handled the same way. We should look at supporting these in our taxonomy panel. 

## Additional Context

As work is done on the initial taxonomy set up for categories and tags I'm sure this will make more sense, the only things I'm initially hesitant about adding this to scope at the moment are UX related - does this expand the panel? Scroll? And associated titling. So let's set up the categories and tags first so we can iterate more informed.

**Comment by aaskedall** [comment]
Figma here: https://www.figma.com/file/1YM3jA9h4QGc4xLdyaXIJS/Stories-Sprint-1.7?node-id=9721%3A383439

**Comment by samwhale** [comment]
Proved that custom taxonomies work: https://github.com/google/web-stories-wp/pull/9201.

Before closing this I think we'll need to change the title of the panel from `Categories & Tags` to something more generic like `Taxonomies` 
<img src="https://images.zenhubusercontent.com/5b1032a1348b7966b43421a4/de414cb3-9aad-4e76-a0d9-8373efa11c81" height="400px" />

**Comment by samwhale** [comment]
This PR by @spacedmonkey adds the new taxonomies as well: https://github.com/google/web-stories-wp/pull/9214

**Comment by spacedmonkey** [comment]
@samwhale As noted here, I am not seeing the taxnomonies in the editor - https://github.com/google/web-stories-wp/pull/9214#issuecomment-931198729

**Comment by swissspidy** [comment]
> @samwhale As noted here, I am not seeing the taxnomonies in the editor - [#9214 (comment)](https://github.com/google/web-stories-wp/pull/9214#issuecomment-931198729)

I think the issue with that is the capability checks I added here:

https://github.com/google/web-stories-wp/blob/35a65a98f5059ad3454b53812473c774fb6d5a21/packages/story-editor/src/components/panels/document/taxonomies/taxonomies.js#L45

https://github.com/google/web-stories-wp/blob/35a65a98f5059ad3454b53812473c774fb6d5a21/packages/story-editor/src/components/panels/document/taxonomies/taxonomies.js#L61

Instead of checking

```js
capabilities[`assign-${taxonomy?.slug}`]
```

We need to check

```js
capabilities[`assign-${taxonomy?.restBase || taxonomy?.slug}`]
```

Then they will show up properly

**Comment by samwhale** [comment]
I can add that real quick 👍

**Comment by samwhale** [comment]
Oh wait - I think the problem is the `rest-base` slug. It should be in the new format: `web_story_${taxonomy}` not `story-${taxonomy}`

If we add the second check that's fine but we could end up with duplicates if we have `web_story_categories` and `story-categories` as possible taxonomies

**Comment by spacedmonkey** [comment]
You need to check rest base then slug. Checkout out [this](https://github.com/WordPress/wordpress-develop/blob/48c68e5dac074b4b5b059180c0715c820efd1e45/src/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php#L2128-L2141) from WordPress core. 

```capabilities[`assign-${taxonomy?.restBase || taxonomy?.slug}`]``` should work.

**Comment by swissspidy** [comment]
What I shared above works. I just tested it before sharing.

**Comment by samwhale** [comment]
Do we want to check each individually or just default to restBase if it exists?

```js
Boolean(capabilities[`create-${taxonomy.slug}`]) || Boolean(capabilities[`create-${taxonomy?.restBase}`])
```

In my mind this is a little sturdier in case the permission matches the slug rather than the rest base but either way works for me 🤔
