### ISSUE TITLE
Allow display of previous and upcoming slides in stories

### ISSUE THREAD

**Issue by mxbclang** [GoogleForCreators/web-stories-wp#8876]
## Feature Description

A <a href="https://wordpress.org/support/topic/web-stories-em-carousel/">user on the support forums</a> would like the ability to display the previous and upcoming slides for a story in the story view. [Here's an example image.](https://jmp.sh/gjbg8ua+/new-story-layout.png)

**Comment by swissspidy** [comment]
Since that player when viewing a single story is handled by the format, this would need to be reported there.

The thing is, this was just revamped recently to _not show the prev/next slides anymore_. Instead we get these nice blurry backgrounds.

**Comment by ogomesux** [comment]
Would it be possible to use a previous version of the plugin to use where previous and future slides were displayed?

**Comment by swissspidy** [comment]
No, because that code is not in the plugin but comes from the AMP format itself and is loaded from the AMP CDN.
