### ISSUE TITLE
Embedded Page Attachments

### ISSUE THREAD

**Issue by Bernietorras** [GoogleForCreators/web-stories-wp#8881]
Expanding the functionalities of amp-story-page-attachment  in order to create a layer with many functionalities: https://amp.dev/documentation/components/amp-story-page-attachment/

Among them, you could embed a google maps location or even add the cookie consent, proof of this on this website:

https://amp.travel/stories/d8603b0a-abe8-4fdc-bedd-078e48ac5773

The Web Stories format is widely displayed on Google in travel-related search results, and for the needs of this sector it would be great to be able to embed a map in this way, using one (or several) layers inserted in amp-story-page-attachment. This functionality would make a lot of sense in this sector.

**Comment by swissspidy** [comment]
Thanks for sharing your feature request!

We're loosely tracking this enhancement on the roadmap as "Embedded Page Attachments" but without any plans to implement this in the near future. We will gladly update this ticket once we decide to pursue this.

Aside: Note that for cookie banners / user consent within stories itself you should be using [`<amp-story-consent>`](https://amp.dev/documentation/examples/user-consent/story_user_consent/), for example via a plugin like [WP GDPR Cookie Notice](https://wordpress.org/plugins/wp-gdpr-cookie-notice/).

**Comment by Bernietorras** [comment]
Thank you for your quick reply and for taking this improvement into consideration.

I think it can be a good push for its use in travel sector, where results appear in the Visual Stories section, being able to add the embedded map would be very useful for the visitor of the web story.
