### ISSUE TITLE
New color picker allows duplicate saved colors

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#8882]
## Bug Description

The new color picker allows duplicate saved colors. This should not happen.

## Expected Behaviour

Duplicate colors added to saved colors **should be ignored**.

## Steps to Reproduce

1. Open the color picker for an element.
2. Select a default color
3. Click _custom_ to go to the custom color picker
4. Click _add_ to add the color as a saved color
5. Click _custom_ again
4. Click _add_ again
6. Observe that in the saved color section at the bottom of the basic color picker, the default color selected now appears twice.

## Screenshots
![image11](https://user-images.githubusercontent.com/637548/131541878-394e032e-a0cb-48c6-b2fb-a5a6b45b066f.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by csossi** [comment]
Verified in QA
