### ISSUE TITLE
Checklist Thumbnails: Caching catch up

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#8883]
Post https://github.com/google/web-stories-wp/issues/7987 we need to catch the checklist thumbnails up to changes, they are rendering as just solid black now. 

![Screen Shot 2021-08-31 at 9.25.13 AM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/db32c037-f8fd-4493-9c83-eaffaf401b7d)

**Comment by BrittanyIRL** [comment]
@csossi there's more details on what to look for her on this bug in the [PR description ](https://github.com/google/web-stories-wp/issues/9087)

**Comment by csossi** [comment]
Created a page with 2 checklist probs. "Add more text to page":
![image](https://user-images.githubusercontent.com/16945664/134981914-f760cad5-87c5-4a07-ba65-3b79d0719ffb.png)

and contrast:
![image](https://user-images.githubusercontent.com/16945664/134982643-9ec45cab-5018-4df3-8691-89163f9452b4.png)

While on the contrast warning, I moved the content to see it move in the thumbnail (which it did - so far so good):
![image](https://user-images.githubusercontent.com/16945664/134982190-7d0ccfdd-ecd9-45d2-825b-92c1be09c14c.png)

Returned to the "Add more text" warning, and the rectangle is now black:
![image](https://user-images.githubusercontent.com/16945664/134982396-a74b755f-76e8-4579-b1b4-81846d4cd38e.png)

**Comment by csossi** [comment]
Also finding the results seem random and unpredictable when using Safari. Here, there are 2 black rectangles (saw 3 here as well at one point):
![image](https://user-images.githubusercontent.com/16945664/134983593-a03193f6-f480-4d94-85df-6a74dd03b68d.png)

**Comment by swissspidy** [comment]
> Also finding the results seem random and unpredictable when using Safari.

#9168 might solve this

**Comment by BrittanyIRL** [comment]
I'll wait for 9168 to be merged and take another look to make sure it's all fixed.

**Comment by swissspidy** [comment]
9168 was merged in the meantime

**Comment by BrittanyIRL** [comment]
great! i was planning on coming back to this today after catching up on everything else. thanks for the update.

**Comment by csossi** [comment]
Verified in QA
