### ISSUE TITLE
Right Click Menus: Clicking behaviors

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#8884]
This ticket is to improve the clicking behaviors of the right click menu stemming from feedback during bug bash. As these all kind of coexist, fixing them together is probably the most efficient way. Acceptance criteria is fixing everything in this task list.

See [bug bash doc ](https://docs.google.com/document/d/1OuZWwAWxPGDEw5Vm285b_z4Hxdoej3DGLtlYq7sqS-4/edit#)for gifs (can't pull those out of the file)

- [ ] When opening the right-click menu and left-clicking another element, the right-click menu for that other element appears while mouse is down, but disappears once mouse is lifted. Looks weird? (thanks @barklund ). Also reported by @choumx : in this video I'm opening the right-click menu and then left-clicking somewhere else, which shows another menu behind the first one.
- [ ] Disabled items should have pointer-events enabled(?) otherwise clicking on them will select the element underneath (@merapi). Clicking on disabled items shouldn't remove focus from the 'selected' element.  
- [ ] Clicking on the divider between selections should also capture and ignore pointer events. (@barklund)

**Comment by BrittanyIRL** [comment]
@samwhale will you point this, please?

**Comment by csossi** [comment]
One comment - when user clicks away, the menu indeed closes, but the click is recognized and as the user moves their mouse it has a drag behaviour. See link - says it better. Let me know if out of scope here for now
https://share.getcloudapp.com/7KuE6Awv

**Comment by samwhale** [comment]
Good catch @csossi! Should be fixed now 🙌

**Comment by csossi** [comment]
Verified in QA
