### ISSUE TITLE
Context Menus: Drop shadow flicker

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#8885]
Reported in bug bash 1.11 by @barklund  - there's a little flicker when the right click menu is opening. 

![flicker](https://user-images.githubusercontent.com/10720454/131551337-9edf328d-a812-4ba8-bfa1-3af610b06202.gif)

There shouldn't be a flicker.

**Comment by csossi** [comment]
Verified in QA
