### ISSUE TITLE
Create trimmable, playable video context

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#8889]
## Feature Description

The purpose of this ticket is to set the foundation for the actual video trimmer component, communication between the components as well as introduce a playable component in the layered frame.

* [x] Create a communication layer (new or existing context?) between the layered frame and the trimmer
* [x] Display the video in the frame with the regular play button as for a video display component (DRY-ly) but loop the video regardless of "loop" setting
* [x] Store _start-offset_, _current-position_, and _end-offset_ in the video as milliseconds in the comm layer
* [x] Update _current-position_ as the video plays in the comm layer
* [x] Make a "dummy" trimmer component with three text fields: _start-offset_ (editable), _current-position_ (non-editable), _end-offset_ (editable), that displays/updates the values from the comm layer
* [x] Make the video start at _start-offset_ and end at _end-offset_ as they are changed (note that the video should be looping based on those offsets)
* [x] If _current-position_ is not within _start-offset_ and _end-offset_, move the play-head so it is within the bounds (but maintain playing or paused state as it was before the ends were moved in)

**Comment by csossi** [comment]
Verified in QA
