### ISSUE TITLE
Implement video trimming logic

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#8891]
## Feature Description

Implement the actual video trimming logic that is missing after #8890 has been created.

- [ ] Create new video asset in WordPress
- [ ] Make sure new video asset is hidden from media library
- [ ] Associate link to original video + offsets as metadata to new video asset

**Comment by swissspidy** [comment]
Sharing [from Slack:](https://xwp.slack.com/archives/C0135V8LYJE/p1630550775020200?thread_ts=1630443888.013400&cid=C0135V8LYJE)

> My idea is that the new media object has something like this as metadata:
> 
> ```
> trimmed: {
>   original: 1234, // media id of original video element
>   start: 12345, // offset in milliseconds in original video element
>   end: 54321, // offset in millisecond in original video element
> }
> ```
> 
> Then if the user later decides to "re-trim" an already trimmed video, we will display the original video in the trim mode and move the trim handles to the displayed offsets, as if the user is still working on the original video.

**Comment by spacedmonkey** [comment]
It sounds like the following is required.

- Add some post meta to attachments, following the example of [Muting](https://github.com/google/web-stories-wp/blob/main/includes/Media/Video/Muting.php). Add a `web_stories_is_trimmed` and  `web_stories_trimmed_id`. The id will be assigned to the original attachment that was trimmed. You can trim a trim of course, but should only be saved on the current video being trimmed. `is_trimmed` a flagged set on the new attachment created. Is there any other data that needs to be stored on the orignal attachment?
- Create a new function in [useProcessMedia](https://github.com/google/web-stories-wp/blob/main/packages/story-editor/src/app/media/utils/useProcessMedia.js), similar to [muteExistingVideo](https://github.com/google/web-stories-wp/blob/6ed8435270cfa5470dbcc2df05241d739df034ea/packages/story-editor/src/app/media/utils/useProcessMedia.js#L171-L255). This would take the following params, resource, startTime, endTime. We will reuse logic that copies over data in the rest api. This will handle adding the new video to the media queue and updating existing elements in the pages. 
- Create a trimVideo function in [useFFmpeg](https://github.com/google/web-stories-wp/blob/main/packages/story-editor/src/app/media/utils/useFFmpeg.js). This will take file, startTime, endTime as params. 

Questions
- do we need state for isTrimmed on the resource?
- Do we need similar state in the media upload queue, for istrimming etc. 
- Do we force trimmed videos to be transcode, if the original video is not transcoded?
- Is all this work going to be done by the infra pod?

**Comment by swissspidy** [comment]
> * do we need state for isTrimmed on the resource?

Yes, on the resource object itself we need to know whether it's trimmed _and_ also the start and end timestamps.

I don't think it needs a separate `isTrimmed` key on the resource. A `trimmed: {}` object like suggested by Morten should work.

> * Do we need similar state in the media upload queue, for isTrimming etc.

I think so. This follows the existing pattern we have with muting.

> * Do we force trimmed videos to be transcode, if the original video is not transcoded?

Let's _not_ do that for now, to ensure trimming is as fast as possible.

> * Is all this work going to be done by the infra pod?

Yes, we're supporting Prometheus pod on this as the de facto owners of media related functionality in the editor.
