### ISSUE TITLE
Re-trimming a video

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#8892]
## Feature Description

Once #8891 has been implemented, make sure that re-trimming a video, that has already been trimmed, will work off of the original video and the offsets relative to that video rather than based on the current (shorter) video. This information will exist in the metadata of the trimmed video element.

However, if this link is somehow broken (e.g. if the original video has been deleted), use the current video as a new blank starting point.

**Comment by csossi** [comment]
Verified in QA
