### ISSUE TITLE
Enable video trimming for all users

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#8893]
## Feature Description

Once the feature is completed and approved, enable video trimming feature flag for all users.

Make sure the feature is properly covered by both unit and integration testing.

**Comment by csossi** [comment]
Verified in QA

**Comment by swissspidy** [comment]
This was closed & shipped with v1.12.0

For tests there should be a new dedicated ticket.

**Comment by miina** [comment]
Added for tests: https://github.com/google/web-stories-wp/issues/9346
