### ISSUE TITLE
Improve the contrast of items in the right click menu

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#8894]
## Feature Description

Originally reported by @barklund 
Although this is as designed, it was flagged that there could be some improvement made to the contrast of items in the right click menu

Here is how it currently looks:

![image17.png](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/aa44701c-f1ab-4f70-a904-eb702d0ccc41)

## Alternatives Considered

An improved design should deliver a better contrast on text menu items, even when they are not selectable in the current context

**Comment by BrittanyIRL** [comment]
@samwhale just updated the tertiary color here which i believe impacts these, so let's revisit and see if we can nail down a contrast that passes accessibility standards. Ticket padded for back and forth with design.

**Comment by csossi** [comment]
Verified in QA
