### ISSUE TITLE
Blocks: support compact display

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8904]
## Feature Description

**Compact displays show multiple Web Stories in one module**

Similar to carousels, compact displays allow you to group Web Stories together, while taking up less space.

**Use compact displays to show Web Stories at the top of any page.**

Compact displays are designed to be placed directly underneath a site’s main header

-> Ensure they look great in WP default themes

**Compact displays are designed to hold between 3 and 5 Web Stories.**

If you have fewer than 3 Web Stories, consider using a singleton. If you have more than 5, try a carousel. 

![Screenshot 2021-09-01 at 17 11 30](https://user-images.githubusercontent.com/841956/131696894-a894530a-14a9-45e4-a07b-82f6e54564d6.png)

![Screenshot 2021-09-01 at 16 21 13](https://user-images.githubusercontent.com/841956/131688264-62f298e9-49b1-45fd-91e0-f4f0e3e9d72e.png)

![Screenshot 2021-09-01 at 17 08 38](https://user-images.githubusercontent.com/841956/131696444-50a53a1f-8dd1-4d9f-9e0d-31d71dc0f77e.png)

![Screenshot 2021-09-01 at 17 12 10](https://user-images.githubusercontent.com/841956/131697035-5a68a045-b9a8-4f29-af04-62b2a0f288e2.png)

**Comment by LuckynaSan** [comment]
Noting here that another user submitted a similar topic: https://wordpress.org/support/topic/can-we-display-category-vise-in-story-page
