### ISSUE TITLE
Blocks: Update singleton styling

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8909]
## Feature Description

There are various possible styling options when embedding a single story:

![Screenshot 2021-09-01 at 17 03 08](https://user-images.githubusercontent.com/841956/131695569-0fa1f1ab-b51f-43cc-8670-cfb3576b9627.png)
![Screenshot 2021-09-01 at 17 03 20](https://user-images.githubusercontent.com/841956/131695602-88837c20-63d8-49c8-a2e1-e24ac889b811.png)

**Comment by panchammsinghh** [comment]
Eagerly waiting for this update, my blog will look amazing with these stylings.
