### ISSUE TITLE
Editors unable to crop poster images or logos

### ISSUE THREAD

**Issue by mxbclang** [GoogleForCreators/web-stories-wp#8912]
## Bug Description

When logged in a user with the role of Editor, the user is unable to crop poster images or publisher logos. Poster images and publisher logos can only be set if the selected image is already the correct size.

## Expected Behaviour

Editors should be able to crop poster images prior to setting.

## Steps to Reproduce

1. Log in as a user with the role of Editor
2. Open the poster image or publisher logo modals
3. Select an image that is not the correct size for a poster image or publisher logo
4. Select a section to crop
5. Error will display

## Screenshots

Video: https://jmp.sh/dIsUe9v

Screenshot of error:

<img width="1887" alt="image-crop" src="https://user-images.githubusercontent.com/12189958/131713113-c4a180ed-6dd0-445b-a5f6-5ef95a0d6324.png">

## Additional Context

- Plugin Version: v1.10.1
- WordPress Version: 5.8

**Comment by csossi** [comment]
Verified in QA
