### ISSUE TITLE
Color Picker: Browser refreshes causes saved colors to be lost

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#8914]
## Bug Description

Originally reported by @aaskedall 

Refreshing the browser caused saved colours to be lost

## Expected Behaviour
Saved colours should be retained.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by miina** [comment]
Not able to reproduce this. If a Saved Color is added and the browser refreshed without saving the Story first, there's a warning about unsaved changes. Otherwise, everything seems to work ok.

@barklund Are you able to repro this? Will close the issue if not.

**Comment by miina** [comment]
Closing since not able to reproduce this. After saving the Story, all colors remain as expected.
