### ISSUE TITLE
Browser refreshes causes saved colours in the colour picker to be lost

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#8915]
## Bug Description

Originally reported by @aaskedall 

Refreshing the browser caused saved colours to be lost

## Expected Behaviour
Saved colours should be retained.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
Duplicate of #8914

**Comment by bmattb** [comment]
I don't even know how this happened here.
