### ISSUE TITLE
Rotate Gradient action on a Radial Gradient shouldn't be presented

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#8916]
## Bug Description
Originally reported by @littlemilkstudio 
A rotate gradient action makes little sense for a radial gradient, as there are no visual changes from it.

<img width="364" alt="image9" src="https://user-images.githubusercontent.com/58738530/131724320-c6afa5db-1fc0-40f7-ae16-4b65ffa25013.png">

## Expected Behaviour

The rotate function might be removed for this specific use case

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by csossi** [comment]
Still seeing option to rotate gradient for radial choice:
![image](https://user-images.githubusercontent.com/16945664/132997174-e202ea6b-bc2d-4d7e-84dd-1c067f7b6940.png)

**Comment by miina** [comment]
@csossi Looks like the plugin build was not properly deployed to QA. Will check what's happening and move it to QA again.

**Comment by csossi** [comment]
Verified in QA:

![image](https://user-images.githubusercontent.com/16945664/133503301-92da489c-be00-4e7a-821e-a5552ea9bd98.png)
