### ISSUE TITLE
Color Picker: Moving slider removes the font weight from preview until selection made

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#8917]
## Bug Description

Originally reported by @samwhale 
Click and drag on the slider removes the font weight from the element in the canvas until value is chosen.

![image19](https://user-images.githubusercontent.com/58738530/131725128-91e23abe-df08-4222-85ec-1ac5731a073f.gif)

## Expected Behaviour

Preview of font weight should remain unaffected by colour picker actions.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by miina** [comment]
Closing in favour of #7966
