### ISSUE TITLE
Text set insertion in Safari is resulting in a noticable latency

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#8920]
## Bug Description

Originally reported by @choumx 

Performance: several hundred ms latency on insertion in Safari (compared to inserting a text set with colors, which skips the feature)

I think we should consider changing this to opt-in (as Marcin suggested) with a quick action and a helpful toast/tooltip

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by miina** [comment]
Closing as the feature was added as opt-in + there have been some performance improvements to it meanwhile.
