### ISSUE TITLE
Hotlinking - Invalid URL warning incorrectly presented.

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#8921]
## Bug Description
Originally reported by @aaskedall 
The ui is telling me the link is invalid but I can press insert and it works

After entering an invalid URL, the error message is not cleared when a new value is entered in that field.

![image16](https://user-images.githubusercontent.com/58738530/131734223-5c0900fe-fb65-498e-9d98-0d81648329a7.gif)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by miina** [comment]
Information from Andrew: the Insert button should be disabled when the link is invalid.

**Comment by csossi** [comment]
Verified in QA
