### ISSUE TITLE
Hotlinking - focus overlaps label on URL insertion modal.

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#8922]
## Bug Description

originally reported by @BrittanyIRL 
The focus overlaps the label. Perhaps should we have input + label pre-grouped components available in the design system? I think we let everything be isolated so we could swap things out more readily, but now that we’re adding new features, this might be a helpful way to unify.

![image16](https://user-images.githubusercontent.com/58738530/131734811-4cc48504-e7ed-4c3f-9a43-97a1292a7446.gif)

![image20](https://user-images.githubusercontent.com/58738530/131735062-51a8893d-71d7-4f24-9ee5-ca5bd29eb21e.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by barklund** [comment]
I don't think this should have been an epic, but I don't know how to un-epicify it?

**Comment by miina** [comment]
Closing as this got fixed within #9036
