### ISSUE TITLE
Some images missing for thumbnails in Safari

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#8923]
## Bug Description

Originally reported by @choumx 
In Safari it appears that some of the image thumbnails are missing:
![image26](https://user-images.githubusercontent.com/58738530/131735422-8af6e8af-ba85-46c2-95f2-25badb9b4009.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by merapi** [comment]
I've obtained a certain level of repeatability of this issue, maybe it will lead us somewhere.
When you insert the image and don't touch it, then change the page, the generated thumbnail will be broken, but if you insert and move (or move the broken image) is it almost certain that the next thumbnail generation will be successful.
Some images work right off the bat (in the same session, without moving them) 🤷🏻‍♂️ .
