### ISSUE TITLE
Fix carousel after aspect ratio change

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#893]
## Bug Description

Looks like #872 broke the responsive layout for the carousel, as numbers in `assets/src/edit-story/components/canvas/layout.js` were not updated.

I suggest moving those constants to `assets/src/edit-story/constants.js` so they don't get missed next time.

## Screenshots

On a 15 inch screen:

<img width="1673" alt="Screenshot 2020-03-31 at 16 44 22" src="https://user-images.githubusercontent.com/841956/78040031-29ea3380-736f-11ea-8c69-efc17d7d82d4.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by dvoytenko** [comment]
The layout.js has been updated. Probably something is off with the math there.

**Comment by dvoytenko** [comment]
@swissspidy also, can you please send your current innerWidth/Height - I'm not seeing this layout. The carousel goes into a compact mode for 15" screen for me.

**Comment by swissspidy** [comment]
`window.innerWidth` x `window.innerHeight` is 1680x916 for me

**Comment by dvoytenko** [comment]
I can repro. Looking.
