### ISSUE TITLE
Layers Panel: Confusing size changes

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8931]
## Bug Description

Let’s say I have three pages:
Page 1: 10 elements
Page 2: 5 elements
Page 3: 10 elements

I go to page 1, manually expand the layers panel to accommodate all elements
I go to page 2, the layers panel shrinks to very small size
I go to page 3, the layers panel stays that small

There’s no way for me to say “Expand the layers panel to max possible height whenever I change pages”

## Additional Context

- Plugin Version: 1.11.0
- WordPress Version:
- Operating System:
- Browser:

_____________

# Issue Update Based on Design Feedback Sept/Oct 2021 

_Kept the above for historical context since this panel's been a bit, well, like the title says, confusing_ 

## Description 
Update the layers panel height and the behaviors of controlling the height to make it (🤞 ) less confusing to users and more of a useful tool. 

- Default layers panel height to 25% of the total screen height 
  - @agingoldseco can you confirm the percentage? ✅ 
- Unless the user adjusts the height manually, the panel will stay this default height regardless of the layer count (any layers that aren’t visible are still known to the user because of the layers number badge at the top of the panel (#9136) )
- If the user changes the height of the palette, it stays their height as they go through their workflow
- If the user toggles the layers panel to expand/collapse using the arrow at the top of the panel this is also respected as the height through their workflow. 
  - this is retooling the current saved height set up.
- If they close the palette using the arrow toggle, the number of layers will visibly change on the badge as they add but it will just stay closed throughout their session unless they open it again

This issue's had quite a lengthy discussion in slack and I suspect there will need to be more here. Whoever picks this up to work on it, please open a dialog in the design slack channel for any questions and to get confirmation on things that feel ambiguous.  

## Acceptance criteria 
- Layers panel height is updated in the ways listed above 
- Tests updated and added accordingly
- Layers panel is still usable for keyboards and SR users, if there isn't a test yet - add an aXe validation test in karma too for this.

**Comment by dreamofabear** [comment]
+1, I actually thought there was a bug where only one layer was showing. TIL users can drag to resize the layers panel.

I think the default behavior (clicking on the panel header) should be maximize/minimize. 

Or at least: if the panel is open but *not* at max height, there should be some clear indication to user (e.g. display a separate maximize button).

/cc @aaskedall

**Comment by swissspidy** [comment]
Yeah it‘s definitely not clear that it can be resized.

I also always thought a double click could be used to maximize the panel and then keep it maximized.

**Comment by dreamofabear** [comment]
This is particularly annoying when using templates -- some templates use large shapes and scrims on top which makes it difficult to select text and images underneath without using the Layers panel.

Tangent: Being able to lock layers (locked layers are not selectable on canvas) would also be nice here, which is a common feature in editing products like Photoshop.

**Comment by BrittanyIRL** [comment]
@samwhale if memory serves, you worked on setting up this panel to retain the height a user sets. Do you have any insight into this or potential roadblocks?

**Comment by samwhale** [comment]
Yeah! 

iirc the layer panel heights are saved in local storage. When you go to a new page, the layer panel height gets saved.

I think the problem we're having here is the 'default height' is too small. We could always change the default to be the maximum height possible. Any time the user changed the page then the layer panel would open back up.

---

Some ideas while thinking through this:
- It would be smart to have a maximum height so that the layer panel can't cover the entire inspector (in case there are many elements).
- Double clicking the header would be a nice way to open and close the panel. There's a provider that deals with the layer panel height, so we could do it there.
- Locked layers is a great idea too. I feel like this should be done separately to the height.
- Adding some buttons to the layer panel to maximize/minimize would be a nice ux improvement too.

**Comment by swissspidy** [comment]
> Locked layers is a great idea too. I feel like this should be done separately to the height.

#7332

**Comment by dreamofabear** [comment]
Chatted with Brittany a bit about this. Recap: IMO it's questionable whether the "implicitly saved display height for layers panel" is a net positive for creators or not.

As Pascal suggests in the OP -- pages generally will have different number of layers, which yield different Layers panel heights. A single stored preference for Layers panel height seems like it could be unergonomic (and certainly confusing for users who are not aware of it).

The cheapest intervention may be: 
- Remove the persistence of custom Layers panel height (keep persistence of collapsed state)
- If the Layers panel is not collapsed, display at max height when switching pages

This is basically removing a feature and assumes that the stored Layers panel height is not useful to most creators.

**Comment by BrittanyIRL** [comment]
@aaskedall  ^^^ for context

**Comment by agingoldseco** [comment]
@BrittanyIRL Checked over the ticket changes—looks good! I think we should default to 25% of the screen height. Seems like a good middle ground for small and large screens.

**Comment by csossi** [comment]
Verified in QA
