### ISSUE TITLE
Quick Actions Menu: Sticker Quick Actions

### ISSUE THREAD

**Issue by samwhale** [GoogleForCreators/web-stories-wp#8933]
## Feature Description

Stickers have no quick actions because the quick action menu was designed and implemented before stickers were implemented. Let's add some quick actions for stickers.

**Comment by BrittanyIRL** [comment]
I'm thinking just `add animation` and `add link` for sticker quick actions. 

@agingoldseco @aaskedall when you get a second can you take a look at this?

**Comment by agingoldseco** [comment]
@BrittanyIRL `add animation` and `add link` sound good to me! Can't think of anything else that would be necessary right now.

**Comment by csossi** [comment]
Verified in QA
