### ISSUE TITLE
Repeatedly right-clicking shows the browser context menu instead of our editor's right-click menu

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#8936]
## Bug Description

Originally reported by @choumx 
Repeatedly right-clicking shows the browser context menu instead of our editor's right-click menu

## Expected Behaviour

Right clicking in the editor should always bring up the right-click menu (?)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by BrittanyIRL** [comment]
| Notion | Google Docs | Google Calendar | 
| --- |  --- | --- | 
| ![notion right click repeats](https://user-images.githubusercontent.com/10720454/132039086-8d087e00-a458-456f-bf7e-34ae467b1d96.gif) | ![google docs repeat right click](https://user-images.githubusercontent.com/10720454/132039097-62e14895-5554-4d46-8287-36e097f2a713.gif) | ![google calendar repeat right click](https://user-images.githubusercontent.com/10720454/132039099-bdd221e6-dc70-4a7b-871c-c0bfe35087f6.gif) | 


Did a little check across some tools, they're all slightly different. Our current implementation agrees more with notion than things in the Google catalog. So let's update that.

**Comment by csossi** [comment]
Verified in QA
