### ISSUE TITLE
Canvas: Background zoom is off by 1px

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#8939]
## Bug Description

Originally reported by @BrittanyIRL 
Page 4 of Summer Adventure (i think?), the bg zoom should be just a touch further out. There’s a fraction of whitespace.
![image2](https://user-images.githubusercontent.com/58738530/131914977-111c0ae6-e716-4909-8f07-e4758eda9936.gif)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by sudeep510** [comment]
The image here is set as background so it is occupying the entire artboard. Also, the background image does not give the option to adjust the coordinates. Maybe the issue presents itself differently on various browsers. For example, in the attached video the white space it noticed on the left side. Whitespace is only visible in the editor, however, once the story is published the whitespace is not seen in the preview.

https://user-images.githubusercontent.com/72914363/132217686-c83e8317-c994-458f-95c4-4a94e4a10fbd.mov

**Comment by swissspidy** [comment]
Thanks for checking @sudeep510!

It sounds like there's some rounding error somewhere in the editor and that it's not specific to this template or this image at all.

A similar issue with such a 1px whitespace was recently reported at #8674.

@barklund @miina @merapi Maybe Prometheus pod has an idea what might be going there?

**Comment by BrittanyIRL** [comment]
this is fixed now, moving to QA for confirmation in staging

**Comment by BrittanyIRL** [comment]
Claudio took a look at this today and it's persisting. I can't see it on my external monitor (pretty low res), moving to the backlog since we have more important things slatted for our sprint and this is related to a rounding issue mentioned about that prometheus is aware of.

**Comment by swissspidy** [comment]
Issue still exists but it's such a small inconvenience, closing for now.
