### ISSUE TITLE
Template : Object animation is incorrect

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#8941]
## Bug Description

Originally reported by @bmattb 
Artist legacy, the animation on the object noted seems off in that it just suddenly appears on the page as a bg element

![image14](https://user-images.githubusercontent.com/58738530/131915296-cacc7ddb-1e83-4b0a-bbe9-3c2926b4501e.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
@bmattb What exactly is the issue here? It's simply some rotated element with a "Fade In" animation.

**Comment by bmattb** [comment]
After revisiting I can see that the animation is fading in as expected. Closing.
