### ISSUE TITLE
Template - One Day City Cover - odd tooltip displayed during preview

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#8943]
## Bug Description

When viewing the template noted in preview, there is an odd tool tip that is displayed that says "Red Section seperator"

![image15](https://user-images.githubusercontent.com/58738530/131916851-ac932d14-bfb6-444e-be83-3f5f653cb258.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
"Red Section Separator" is simply the sticker's `<title>`, which the browser shows when hovering over the SVG.

The `<title>` element provides an accessible, short-text description of any SVG container element or graphics element.

Text in a `<title>` element is not rendered as part of the graphic, but browsers usually display it as a tooltip.

So this is not a bug.
