### ISSUE TITLE
Capability check publish private story

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#8977]
## Bug Description

Users require the `edit_private_posts` capability to publish private story. Currently authors can publish private story in our editor.  

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by spacedmonkey** [comment]
CC @miina

**Comment by swissspidy** [comment]
For context, where is that `edit_private_posts` check for publishing private posts in WordPress?

What's the behavior in Gutenberg / classic editor and how does our editor differ from that?

**Comment by spacedmonkey** [comment]
Closing as invalid
