### ISSUE TITLE
Selecting a media element on a page does not cause (re)focus

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#8981]
## Bug Description

Selecting a non-background media element on a page does not cause a blur on the old focused element and a focus on the newly selected element. It *does* happen if you select a background media element or another type of element (text or shape).

This is particularly a problem if you click on a thumbnail in the carousel, then click on an image on the newly shown page and press <kbd>backspace</kbd> to delete the element. Because focus never left the thumbnail, the thumbnail still has keyboard focus and the entire page is deleted.

## Expected Behaviour

* A selected element should always receive keyboard focus
* In this particular set of events, the thumbnail should lose focus (the selection rectangle should turn gray) and only the element should be deleted, not the whole page.

## Steps to Reproduce

1. Create a story with multiple pages and a non-background image each
2. Click a non-active page in the carousel
3. Observe a blue outline around the newly selected thumbnail page in the carousel indicating it has keyboard focus
4. Click the image element on the new page
5. Observe that the blue outline remains on the selected thumbnail in the carousel
6. Press <kbd>backspace</kbd> in an attempt to delete the selected element
7. Observe that the whole page is deleted rather than the element

## Screenshots

![image-select-no-focus](https://user-images.githubusercontent.com/637548/132551913-5a376649-1c40-41d7-bb02-0d9745e7b9c8.gif)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by csossi** [comment]
Verified in QA
