### ISSUE TITLE
Layers Panel Improvements

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#8983]
Per discussion across team there's a few updates to the layers panel that could be made to improve usability. This epic is meant to gather those for release.

Figma: https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor-Sprint-Feature-Level-Designs_?node-id=9946%3A421527 

The layers panel is going to be updated in batches, because some of the improvements qualify as the epics of their own. 

**Release schedule**
- 1.14: New resize handle & layer count badge
- 1.15: Duplicate/delete buttons & right-click menu

Requests made for future improvements to be given their own epics since they might be controllable from the layers panel however their impact stretches across the app and other pods should be included! 
- Lock and unlock layers (#7332 )
- Layer grouping (#9244 )
- Masks ( #9246 )
- Naming layers (#9248)

**Comment by dreamofabear** [comment]
V1 scope as suggested by @BrittanyIRL:

> Layers Panel Easy(ish) wins
> - Height adjustments (various ideas have been thrown around)
> - add badge to layers title for layer count
> - Duplicate layer from panel
> - Delete layer from panel
> - Adding element type right click menu to layers
> - (optional) Fade text out instead of ellipsis when it’s too long

**Comment by BrittanyIRL** [comment]
Thanks @choumx ! 

For "height adjustments" a few things have been tossed around, let's get this "enhancement" sorted out, for starters we have these tickets for it, some might be wrong, just a starting point: 
- buttons to toggle min max height (+/-): https://github.com/google/web-stories-wp/issues/8985
- double clicking to expand to full height: https://github.com/google/web-stories-wp/issues/8984
- This is more of a 'how do we fix this' question: https://github.com/google/web-stories-wp/issues/8931
- (this is more of a bug, making sure that when layers take up more vertical than the inspector panel has that it doesn't completely cover the inspector) https://github.com/google/web-stories-wp/issues/8986

**Comment by dreamofabear** [comment]
~Re: height adjustments, let's remove the "saved height" feature as [suggested here](https://github.com/google/web-stories-wp/issues/8931#issuecomment-915593026). I checked with Andrew/George and they're cool with it.~

~We can merge the other height issues into #8931 as alternative proposals if we want to revisit this in the future.~

Agreed on chat to address "height adjustments" for now with new dragging indicator to make the panel's resizability very obvious.

**Comment by BrittanyIRL** [comment]
Thanks! Amy gave me this this AM and i haven't had time to come back and update tickets (trying to finish sprint work)
screenshot for now:
![Screen Shot 2021-09-24 at 10 42 21 AM](https://user-images.githubusercontent.com/10720454/134718142-43391882-9233-435a-b47e-8600f4611298.png)
