### ISSUE TITLE
Layers Panel: double click header toggle expand/collapse

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#8984]
## Acceptance Criteria
- When layers panel header is double clicked and panel could be expanded, it will. If panel is expanded when layers header is double clicked shrink to minimum size. 
- Test to verify

**Comment by BrittanyIRL** [comment]
@agingoldseco @aaskedall given #8931 to updated height on the layers panel, do you want this functionality added or no?

**Comment by agingoldseco** [comment]
@BrittanyIRL I think it's a "nice to have" feature—was there a specific reason it was added? Unsure if people will automatically try to double click, but I don't see why this shouldn't be a thing for those that do

**Comment by BrittanyIRL** [comment]
> @BrittanyIRL I think it's a "nice to have" feature—was there a specific reason it was added? Unsure if people will automatically try to double click, but I don't see why this shouldn't be a thing for those that do

It was just an idea that came up before we had designers back in our midst :) no specific reason it was added. Feels redundant to me but it also doesn't hurt, so whatever you want, @agingoldseco

**Comment by BrittanyIRL** [comment]
This feels really redundant since currently you click once to toggle it. i'm closing this since it was just a loose idea to funnel conversation.
