### ISSUE TITLE
Media: Prevent multiple simultaneous FFmpeg operations for the same file

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#8987]
## Feature Description

There are currently three ways to process a video via our `useFFmpeg` hook:

- Optimize an existing video
- Mute a video
- Trim a video

There should be a check to ensure that the user cannot trigger multiple such operations per video and buttons/options are disabled if the video is already being processed in any way.

**Comment by swissspidy** [comment]
Could you perhaps identify all the areas where such checks are needed and what should be done about them?

As for disabling buttons, it's important that buttons are only disabled with `aria-disabled`, so that they can still receive focus. They could then have a tooltip saying why the option is currently disabled.

**Comment by spacedmonkey** [comment]
A transcode can be trigger in a number of places including 

#### Trim and mute buttons
![Screenshot 2021-09-09 at 17 22 16](https://user-images.githubusercontent.com/237508/132725008-77a2375a-501d-42fb-a49e-c4e96e6c66cc.png)

#### Optimize button ( PPCL)
![Screenshot 2021-09-09 at 17 23 49](https://user-images.githubusercontent.com/237508/132725048-6b8feb42-29c1-4444-b51a-096084a08324.png)

#### Trim button, quick bar. 
![Screenshot 2021-09-09 at 17 24 11](https://user-images.githubusercontent.com/237508/132725184-99d1628e-e195-4f42-8461-0a17d3d1df68.png)

#### Drag into canvas
#### Input for WP library. 

We need to ensure in all places, that, file is not currently transcoded, the upload is finished before even starting a transcode. This ticket is also related to https://github.com/google/web-stories-wp/issues/8982, which would also disable these buttons.

**Comment by csossi** [comment]
Verified in QA
