### ISSUE TITLE
Add e2e tests for archive page customization

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8999]
## Feature Description

It would be nice to have some e2e test coverage for #8811 and #8812, since this new feature will affect many areas in the plugin throughout whole WordPress admin and of course also the frontend.

* [ ] Test that disabling the archive completely hides the archive link option for blocks/widgets/classic editor
* [ ] Test that choosing a custom page for the archive will use that page as the archive whenever linked to it

**Comment by spacedmonkey** [comment]
I am going to wait for #9221 is merged before working on this PR.
