### ISSUE TITLE
Richer interactions in Web Stories not exist in web story WordPress

### ISSUE THREAD

**Issue by alzhrani099** [GoogleForCreators/web-stories-wp#9002]
hello there

i have read this article

https://blog.amp.dev/2021/08/26/richer-interactions-in-web-stories/?utm_source=pocket_mylist

Richer interactions in Web Stories not exist in WordPress , is there a way to add it in WordPress plugin ?

if still new , when we will see it in WordPress plugin?

best regards

**Comment by mxbclang** [comment]
Hi @alzhrani099 Thanks for reaching out. All support for the Web Stories plugin is provided via our WordPress.org support forum. If you [create a new topic there](https://wordpress.org/support/plugin/web-stories/#new-topic-0), we'd be happy to help. Thank you!

**Comment by swissspidy** [comment]
This is more of a feature request than a support request, so here is actually fine. Note that this was cross-posted in #9003 too. Let‘s continue discussion there.

**Comment by swissspidy** [comment]
@alzhrani099 Adding quiz & polls support is on our roadmap, but there is no timeline for it just yet. Please follow #8725 for any progress.

There are no immediate plans for adding support for image transitions or 360 video to the editor at this time, but I assume we'll get there eventually.

So for now there's no way to get these in the WordPress story editor, so unfortunately you'll have to simply wait.
