### ISSUE TITLE
Richer interactions in Web Stories not exist in web story WordPress

### ISSUE THREAD

**Issue by newmuis** [GoogleForCreators/web-stories-wp#9003]
Cross-posted from @alzhrani099 in https://github.com/ampproject/amphtml/issues/36029:

> ### Description
> 
> hello there 
> 
> i have read this article 
> 
> https://blog.amp.dev/2021/08/26/richer-interactions-in-web-stories/?utm_source=pocket_mylist
> 
> Richer interactions in Web Stories not exist in WordPress , is there a way to add it in WordPress plugin ?
> 
> if still new , when we will see it in WordPress plugin?
> 
> best regards
> 
> ### Alternatives Considered
> 
> not sure where i should find alternative 
> 
> ### Additional Context
> 
> _No response_

**Comment by swissspidy** [comment]
Thanks for the cross-posting!

Looks like they also opened a new issue here at #9002. Closing this one in favor of the original author's one.
