### ISSUE TITLE
facing problem with featured_media_url

### ISSUE THREAD

**Issue by Basudev1** [GoogleForCreators/web-stories-wp#9005]
## Feature Description

After the removal of featured_media_url from the WordPress REST API, I could not find an alternative way to use the featured image

Actually, I used the fetch method in javascript with a custom template that would display the latest web stories on a non WordPress site

This endpoint https://site/wp-json/web-stories/v1/?per_page=6 is being used to fetch the 6 web stories and filter the required  objects like **title.rendered** , **link** and **featured_media_url**

The latest release of the Web Stories Plugin removed the **featured_media_url** which caused broken images on the dedicated page for web stories

I was wondering if there was any other way to achieve the same, it will be useful if you include the  **featured_media_url** in REST API

**Comment by swissspidy** [comment]
Thanks for your report!

We've removed the non-standard `featured_media_url` field in web-story REST API responses in favor of the standard embed functionality provided by the WP REST API.

To fetch stories including the featured image URL, use `https://site/wp-json/web-stories/v1/?per_page=6&_embed=wp%3Afeaturedmedia` and access it via `_embedded['wp:featuremedia']`

You can learn more about embedding at https://developer.wordpress.org/rest-api/using-the-rest-api/global-parameters/#_embed
