### ISSUE TITLE
Publisher Logos: Handling for non-admins

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#9007]
## Feature Description

Splitting this out from #8989.

**Context:**

1. Not all users can upload media / new publisher logos
2. The list of existing publisher logos can be retrieved from the settings REST API endpoint
3. Not all users have the capability to retrieve settings

**What we need:**

1. When uploading a new publisher logo, it needs to be added to the list of existing publisher logos
1. Even non-admins should be able to choose from the list of existing publisher logos

**Proposal to address this:**

_Amending the list of existing publisher logos:_

Whenever `web_stories_publisher_logo` post meta is updated for a story, add the logo ID to the list of existing publisher logos if not already in there.

_Retrieving the list of existing publisher logos:_

Add a new `web-stories/v1/publisher-logos` REST API endpoint to `GET` the list of existing publisher logos (from the `web_stories_publisher_logos` option).

* Everyone with `edit_web-story` capability should have access
* Only `GET` requests needed for now, don't need anything else

Proposed REST API response format:

```json
[
    {
        "id": 123,
        "_links": {
            "wp:attachment": [
                {
                    "embeddable": true,
                    "href": "https://web-stories.local/wp-json/wp/v2/media/123"
                }
            ]
        }
    },
    {
        "id": 456,
        "_links": {
            "wp:attachment": [
                {
                    "embeddable": true,
                    "href": "https://web-stories.local/wp-json/wp/v2/media/456"
                }
            ]
        }
    }
]
```

Then the list of all publisher logos could be retrieved via `GET web-stories/v1/publisher-logos?_embed=wp:attachment`

**Non-Goals**

* We don't need to update the Dashboard to use this new REST API endpoint for now

**Comment by swissspidy** [comment]
FYI @merapi @spacedmonkey

Curious to hear whether this would resolve the open questions from #8989

**Comment by spacedmonkey** [comment]
I wonder if we could implement this in our settings endpoint https://github.com/WordPress/wordpress-develop/pull/534 and we ahead of core. Worth looking into.

**Comment by merapi** [comment]
Might be an edge case but: if you add a logo (one or more) and then revert to the original one (and other similar scenarios) - nothing will be added to the global publishers logo list - I think it shouldn't be like this (the UI will be confusing because you will see that newly added logo on the list, but then it will disappear).

**Comment by swissspidy** [comment]
@spacedmonkey It‘d be more platform agnostic to have this as a separate endpoint. Especially since we need the embedding.

@merapi can you elaborate?

**Comment by merapi** [comment]
> Whenever web_stories_publisher_logo post meta is updated for a story, add the logo ID to the list of existing publisher logos if not already in there.

Let's say you:
1. Create a story and upload logos A and B
2. Select logo B as the publisher logo for the current story
3. Save the story - web_stories_publisher_logo=B is added to the global list
4. You create new story and want to select logo A  but it's not there (on the global list)

**Comment by swissspidy** [comment]
I see. Thanks.

In such a case, I wouldn't expect A to be on the global list, as I could be just experimenting with different logos and don't expect that to pollute the global list. That said, it might be expected for others, so I would treat this as a P1 item that can be explored in a separate follow-up ticket.

**Comment by spacedmonkey** [comment]
Why can't we just pass an array of existing publish logos ( array ) via the config object. Then you can make a call to the media endpoints with a list of ids. like web-stories/v1/media?include=12,23,34,45.

I would expect every logo you upload to go in the global list. If this a problem, you can go to the dashboard and remove it from that list. Honestly, it seems extremely rare that people would have lots of and lots of publisher logos. The only examples I can think of different logos, might be like a special logos to support a day/chores , like pride or black live matter etc.

**Comment by swissspidy** [comment]
> Why can't we just pass an array of existing publish logos ( array ) via the config object. Then you can make a call to the media endpoints with a list of ids. like web-stories/v1/media?include=12,23,34,45.

It's not really something that belongs to the config. It's not a config at all. This data is really more suitable to be consumed via the REST API.

> I would expect every logo you upload to go in the global list. If this a problem, you can go to the dashboard and remove it from that list.

Another reason why this should be consumed via the REST API instead. So the list of logos can be updated via the REST API.

I'd still treat this as a P1 item though.

P0: Make publisher logos available via REST API
P1: Update list of publisher logos via REST API
