### ISSUE TITLE
Taxonomy: Respect User Role Capabilities

### ISSUE THREAD

**Issue by maxyinger** [GoogleForCreators/web-stories-wp#9011]
Users have permissions on whether they can create or assign a taxonomy depending on their user role.

This ticket is to read these permissions dynamically from the REST API and alter user taxonomy interaction abilities accordingly.

see:
https://github.com/google/web-stories-wp/pull/9004/files#r707369583
https://github.com/google/web-stories-wp/pull/8591

I think the separated out create vs assign permissions are pretty intuitive UX wise for the hierarchical input, but not sure how this would manifest in the freeform input where the create and assign actions are pretty intertwined in the UI.

@spacedmonkey @swissspidy Could we possibly get a couple steps on how we'd see the freeform input on the Gutenberg editor with limited action permissions? that or just a screen capture for UX reference?

**Comment by spacedmonkey** [comment]
> Could we possibly get a couple steps on how we'd see the freeform input on the Gutenberg editor with limited action permissions? that or just a screen capture for UX reference?

Can't you just login as a author / contributor and look at how the gutenberg editor does this?

**Comment by maxyinger** [comment]
> login as a author / contributor and look at how the gutenberg editor does this?

Awesome. yup, was just asking if you knew of any roles off the top of your head that had permission for either creation or assigning, but not the other. Happy to explore tho. Will document in this ticket

**Comment by BrittanyIRL** [comment]
> > login as a author / contributor and look at how the gutenberg editor does this?
> 
> Awesome. yup, was just asking if you knew of any roles off the top of your head that had permission for either creation or assigning, but not the other. Happy to explore tho. Will document in this ticket

@littlemilkstudio I got this, i'll grab role specific details later today for this.

**Comment by BrittanyIRL** [comment]
| Admin | Editor | Author | Contributor | Subscriber |
| --- | --- | --- | --- | --- 
| Full CRUD | Full CRUD |  Categories: can assign, no create, delete, Tags: can create and delete | Categories: can assign, no create, delete, Tags: can create and delete | N/A |
