### ISSUE TITLE
Images Shouldn't Offer Masking

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#906]
## Bug Description

There is no point of masking an image on an image.
![image](https://user-images.githubusercontent.com/5874851/78055710-efbe6900-7351-11ea-82c6-34cf13bd4c8e.png)

## Expected Behaviour

Dragging an and hovering an image over another image shouldn't trigger the masking feature

## Steps to Reproduce

1. Put an image on the page
2. Drag and hover another image over that image as if you are trying to mask it

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by dvoytenko** [comment]
I think @samitron7 explicitly wanted this kind of "image" replacement to exist.

**Comment by jauyong** [comment]
I spoke with Sam and this is not a bug.
