### ISSUE TITLE
Element IDs might not work as HTML IDs

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#909]
## Bug Description

This came to mind while working on #714. `amp-story-page[auto-advance-after]` can reference an element ID, and element IDs can also be used for defining animations.

I remember this being an issue in the old editor where HTML IDs not starting with a letter broke all kinds of things. See ticket in the old editor: https://github.com/ampproject/amp-wp/issues/2631

The solution there was to always prefix HTML IDs with a letter.

**Needs verification**

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
@dvoytenko @wassgha maybe one of you knows if this is true? HTML 5 isn't very strict about the format of IDs, but this definitely was an issue with stories last year.

**Comment by barklund** [comment]
> @dvoytenko @wassgha maybe one of you knows if this is true? HTML 5 isn't very strict about the format of IDs, but this definitely was an issue with stories last year.

In both HTML and JS, ID's starting with a non-letter are perfectly valid. However, in CSS, ID's cannot start with a number, e.g. `#1 { color: hotpink; }` is not valid.

Might that have been the course of the problems - trying to style the elements based on ID's?

**Comment by wassgha** [comment]
Is this preventative or are we seeing issues related to this already?

**Comment by swissspidy** [comment]
Preventative.

But now that I look at it again, `OutputElement` does prefix the IDs with `el-` consistently already.

Sorry for the false alarm everyone!
