### ISSUE TITLE
`useIsKeyPressed` hook

### ISSUE THREAD

**Issue by wassgha** [GoogleForCreators/web-stories-wp#910]
## Feature Description

See https://github.com/google/web-stories-wp/pull/886#discussion_r400606709 . Minor refactor for the keyboard handling allowing for a shortcut hook to determine whether a key is currently being pressed.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by ezxyz** [comment]
@dvoytenko 

An easy fix for this is to do the following:
```
keyboard/index.js >
export function useIsKeyPressed(targetKey, deps = undefined) {
  const [isKeyPressed, setIsKeyPressed] = useState(false);
  useGlobalKeyDownEffect(targetKey, () => setIsKeyPressed(true), deps);
  useGlobalKeyUpEffect(targetKey, () => setIsKeyPressed(false), deps);
  return isKeyPressed;
}
```

```
multiSelectionMovable.js > 
  const canSnap = !useIsKeyPressed('meta');
  const throttleRotation = useIsKeyPressed('shift');
```

However talking to @barklund I realised that @dvoytenko has some ideas on using a single global provider that remembers all states of all relevant keys. 

Pinging @dvoytenko, do you think its worth it for me to fix this issue with the solution provided above, or should we just mark this obselete and then create a new issue for a single global provider?

**Comment by dvoytenko** [comment]
Yeah. Looks good to me. Just a minor nit. Let's make a pair: `useIsKeyPressed(ref, keyNameOrSpec)` and `useGlobalIsKeyPressed(keyNameOrSpec)`.
