### ISSUE TITLE
Unable to remove a link added previously

### ISSUE THREAD

**Issue by obetomuniz** [GoogleForCreators/web-stories-wp#911]
## Bug Description

Clear actions of the `Web address` field in the Link Panel is not removing the link from the Workspace and not persisting the data if you save.

## Expected Behaviour

Pressing the clear button (e.g. X button) or deleting all text content of the `Web address` field should clear the link metadata from the Link panel and Canvas. If the user saves the Story after clear a link of a given element, the user should not see that link again anywhere.

## Steps to Reproduce

1. Create a Story
2. Add an Image to the Story workspace
3. Select the image added in step 2 and go to the Link panel
4. Add a VALID link in the the `Web address` field and Save the Story
5. Clear the `Web address` field in the Link panel pressing the X button or deleting all content of the field.
6. Save the Story and reload the page. The link still will be there. 

## Screenshots

![Kapture-2020-03-31-at-16 30 13](https://user-images.githubusercontent.com/1680157/78067419-14740a00-736d-11ea-81d7-11522dba436f.gif)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Related: #711
