### ISSUE TITLE
Page grid: clicking on the page should select it in the canvas

### ISSUE THREAD

**Issue by dvoytenko** [GoogleForCreators/web-stories-wp#914]
## Bug Description

Open the page grid and click on a non-current page. Nothing happens.

## Expected Behaviour

There should be a way to select the page in the grid view and set it as the current page in the canvas. Especially in the case with compact page carousel view this is important since otherwise the page is not visible to the user.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
I think this one is already solved. @pbakaus, can you confirm?

**Comment by jauyong** [comment]
@barklund this isn't working for me on staging.

**Comment by pbakaus** [comment]
Also isn't working for me.
