### ISSUE TITLE
Elements need minimum element sizes

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#917]
## Feature Description

As an editor I want Elements to have minimum sizes to ensure a good UX

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. Don't let the controls overlap (min size)
2. The controls in design panel can still allow setting width/height without restrictions, see https://github.com/google/web-stories-wp/pull/993#issuecomment-608133563e

## QA Instructions

Video/image/shape elements can be resized down via mouse to min 20x20 and then handles should disappear.
Text element is controlled only by the min font size (this PR doesn't set any min font).
Video element play button should go above the element if the element is too small.
[Rules from Figma.](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=9488%3A26588)

**Comment by swissspidy** [comment]
We don't have Gutenberg blocks in our editor currently 🙂 
Would need to check with UX on guidelines here.

**Comment by csossi** [comment]
Hi @merapi - any details you can add re: "QA Instructions" above?

**Comment by merapi** [comment]
> Hi @merapi - any details you can add re: "QA Instructions" above?

@csossi Added, please also look at the Figma link, all rules are nicely described there.

**Comment by csossi** [comment]
Verified in QA

**Comment by samitron7** [comment]
Issue with setting min size of shape then dragging corner to resize.

1. Add any shape
2. Enter a value of 1 in the width input field then unlock aspect ratio
3. Click drag bottom control of element to resize. You'll see a jump and the height of the element is now 2873
![Screen Shot 2020-06-14 at 11.06.00 PM.png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/e8cbd041-e8ea-4b19-bbae-fe169c63092e)

**Comment by barklund** [comment]
This sounds like a new bug (perhaps not unlike what I found while testing #2255 though, so might also be fixed by that)

**Comment by samitron7** [comment]
@barklund Advice on how you want to treat this ticket? Everything else looks good except this issue so move this to done and create a new bug (which I think should be a blocker, @o-fernandez?)

**Comment by swissspidy** [comment]
Yes, that's the process.

**Comment by swissspidy** [comment]
Created a new issue: #2555
