### ISSUE TITLE
Generate font declarations on the JS side

### ISSUE THREAD

**Issue by dvoytenko** [GoogleForCreators/web-stories-wp#921]
## Feature Description

It appears that font output is calculated on the server side. Ideally we should be able to do this on the client side for better transferability.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
We can't use hooks like `useFont` when generating the story output. Perhaps we can store the font declarations in the JSON blob to work around this?

**Comment by dvoytenko** [comment]
Why can't we use `useFont()`?

**Comment by dvoytenko** [comment]
That being said, definitely good idea to put some form of `font` object into the data model. It should look and function like a (mostly) immutable `Resource` object. But even with this object, we still need to do some font math on the output side. E.g. ideally we'd just say "service: fonts.google.com", "family: Roboto", "variants: [...]", etc. And then have the output computed the actual font declarations based on these font objects and contents. And it will be a reduce over all text elements at the same time, since different text elements may need different features, but we'll probably want fewer stylesheet declarations.

**Comment by swissspidy** [comment]
I thought we couldn‘t use hooks with side effects when using`renderToStaticMarkup`.

**Comment by dvoytenko** [comment]
That's right. And even if we could, those APIs are asynchronous, so it'd be no good for us here. So, yeah, the sufficient `font` object is the way to go then. We can replace `fontFamily` with `font {family, service, variants, etc}`.

**Comment by swissspidy** [comment]
Started with this in #1273. So far the `font` object only includes `family` and `service`.
