### ISSUE TITLE
Clarify edge cases of using bold markup and bold font weights

### ISSUE THREAD

**Issue by dvoytenko** [GoogleForCreators/web-stories-wp#925]
## Feature Description

The following edge cases would be good to clarify:

1. When a 700+ weight is selected, should we auto-toggle "B" button
2. If the "B" button then untoggled, should we set the weight back to 400
3. If a 900 weight is selected, and the bold shortcut is used on the selection, what should happen?  If the bold shortcut is used again on the same selection, should it return to 900? 700?
   3a. Bold shortcut on selection should always go back to 400, and to 700 vice versa. The only way to select other weights are via dropdown in the design panel.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by pbakaus** [comment]
1. Yes.
2. Yes.
3. Bold shortcut on selection should always go back to 400, and to 700 vice versa. The only way to select other weights are via dropdown in the design panel.

Reminder to self to update [relevant product spec](https://docs.google.com/document/d/1EQ12sD4a1plmMeBu7YMWOdUSg0FeegB9qi2_OlV3Tp0/edit#heading=h.pt3g0mq8djol)..

**Comment by pbakaus** [comment]
@o-fernandez could you make sure the spec fixed if needed here?
