### ISSUE TITLE
Drop target prioritizing covered (not top) element

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#943]
## Bug Description

Per comment below, the overarching issue here is that drop targets are prioritizing the covered element when two elements are in the same area. We should prioritize the visible (top) element. 

## Expected Behaviour

We should prioritize the visible (top) element for drop targets.

## Steps to Reproduce

1. Add a new page
1. Add a media element as element (not bg)
1. Click to set the media element as fill
1. Drag a new media element to replace the fill in what looks to be the fill drop target
1. See that nothing changes (unless you unfill the first media element, in which case you'll see the second media element being background now).

## Screenshots

![fill-droptarget](https://user-images.githubusercontent.com/637548/78162696-3cb74380-7415-11ea-8d5a-98711a78ec5e.gif)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## QA Instructions
1. Add two image elements
2. Move these on top of each other
3. Now drag a new image element from the Library to drop target
4. Verify that the top image is being replaced with the new image and not the lower image.

**Comment by jauyong** [comment]
Related to #906 which is awaiting confirmation from Sam

**Comment by o-fernandez** [comment]
AFAIK, images/videos are not valid drop targets, so even if an image is set as "fill" it's still considered an image. That means this would be WAI, but would need Sam's confirmation. @samitron7

**Comment by dvoytenko** [comment]
@o-fernandez I think we consider images/videos as valid drop targets. The frame can be used to drop a new element and we simply replace it.

**Comment by o-fernandez** [comment]
In that case, my bad altogether. I think at some point that wasn't working and I assumed it was on purpose. Feel free to fix this then!

**Comment by miina** [comment]
On fill elements not being a drop target: note that the issue seems to come from prioritizing the bottom drop target (the first element of the page) as opposed to the top visible drop target. This means that the order of the drop targets activation is an issue with non-fill elements as well -- e.g. if there are 2 elements covering each other, the lower one gets priority.

With Fill element being removed #1932 might be good to adjust the description to address the issue generally, not just for Fill.

**Comment by o-fernandez** [comment]
> On fill elements not being a drop target: note that the issue seems to come from prioritizing the bottom drop target (the first element of the page) as opposed to the top visible drop target. This means that the order of the drop targets activation is an issue with non-fill elements as well -- e.g. if there are 2 elements covering each other, the lower one gets priority.
> 
> With Fill element being removed #1932 might be good to adjust the description to address the issue generally, not just for Fill.

Thanks @miina for flagging - updated the issue description. @barklund FYI

**Comment by csossi** [comment]
Verified in QA

**Comment by samitron7** [comment]
Verified in UAT
