### ISSUE TITLE
Text Boxes Getting a Grey Background Fill by Default

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#960]
## Bug Description

Text boxes are being added with a background fill color

![image](https://user-images.githubusercontent.com/5874851/78197847-955a0100-7454-11ea-9063-37ed4388c1e8.png)

## Expected Behaviour

There should be no background fill on text boxes

## Steps to Reproduce

1. Add a textbox
2. Notice the background fill is grey (C4C4C4)

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@jauyong Looks like having a default background is a UX choice.
