### ISSUE TITLE
Show a progress indicator for video poster generation

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#969]
## Feature Description

This video - https://youtu.be/Juk1kSDyEIM

While video poster is being generated, this is no signal to the user that this is happening. A user may decided to upload a poster themselves. Then poster jumps in. Some kind of spinner next to the poster selection might be useful. Or maybe even disable poster selection until the generation is complete. 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
Related: #470 #615 #703

**Comment by samitron7** [comment]
We should use the exact uploading animation that is found in the media panel:

![Screen Shot 2020-06-24 at 9.38.03 PM.png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/a3e6e2cf-d2c6-4507-8b33-df0d3f85627e)

Figma flow [here](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=8484%3A144)
