### ISSUE TITLE
Show an error message if user leaves editor while uploading a file

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#971]
## Feature Description

While uploading a file, the user should not be able to navigate away from the current page until the upload is complete. 

Related to #799

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by obetomuniz** [comment]
Duplicate #865 ?

**Comment by swissspidy** [comment]
Looks like it!
