### ISSUE TITLE
On dropdown, arrow should change direction

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#972]
## Bug Description

When a dropdown is clicked and options displayed, the arrow should change direction. 

[Example](https://material-components.github.io/material-components-web-catalog/#/component/select) of dropdown from material components. 

## Screenshots
![Screenshot from 2020-04-02 12-23-17](https://user-images.githubusercontent.com/237508/78244179-02b17480-74dd-11ea-8176-1ee74ef68363.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
CC @samitron7 @ndev1991

**Comment by swissspidy** [comment]
Seems to work as expected now
