### ISSUE TITLE
Unable to use scrollbar in dropdown

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#973]
## Bug Description
There is some weird styling and I am unable to use scrollbar in dropdown. 

Note: scroll wheel does work. 

## Expected Behaviour

TBC

## Steps to Reproduce

Use any dropdown. 

## Screenshots

https://www.youtube.com/watch?v=bAtAwzVRYE8

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by dvoytenko** [comment]
#788 might be related: the likely action items there is to move a dropdown popup as a fixed element to the body. That'd also likely remove scroll chaining that happens in this case with the design panel itself.
