### ISSUE TITLE
Video - WebM format not updated in Panel

### ISSUE THREAD

**Issue by csossi** [GoogleForCreators/web-stories-wp#980]
## Bug Description

Added a WebM video via "upload" option in panel. Took me to the media library, and uploaded a WebM video there. Selected "insert" option to insert into page. On return to the page in the ed, the video is appearing, but the ALL and VIDEOS sections aren't updated

## Expected Behaviour

ALL and Videos categories in media panel should be updated

## Steps to Reproduce

see above

## Screenshots

![image](https://user-images.githubusercontent.com/16945664/78257752-451c8680-74c8-11ea-958e-7c7b8df43491.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
Webm format is not supported. So it shouldn't work at all. But it should  handle this more gracefully.

**Comment by jauyong** [comment]
@pbakaus please let me know if this is required for Alpha. I have not marked as such. 
CC @kmyram

**Comment by pbakaus** [comment]
If we don't support webm, we should allow upload. So yes, a simple block list would be great to get in.

**Comment by spacedmonkey** [comment]
Should we also support `ogv` / ogg?

**Comment by swissspidy** [comment]
No, as per https://github.com/google/web-stories-wp/issues/441#issuecomment-596029450

> let's do MP4 and WEBM for now.
