### ISSUE TITLE
Broken uploads when using unspported media file type

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#981]
## Bug Description

Trying to upload a 2MB large webm file (which isn't currently supported, see #798), I get a broken snackbar error message that starts with `Object(...) is not a function`. In addition, a REST API POST request to ` /wp-json/wp/v2/media/undefined?_locale=user` is made.

Trying to upload a ZIP file, I don't get any error message at all, but only `TypeError: Object(...) is not a function` in the console.

This error handling could greatly benefit from tests.

## Expected Behaviour

If I upload a media file of unsupported type, I should get a proper error message. No errors in console, and no broken REST API calls.

## Screenshots

<img width="567" alt="Screenshot 2020-04-02 at 15 58 01" src="https://user-images.githubusercontent.com/841956/78257896-c1c85880-74fa-11ea-9fb3-e357f47b882c.png">
<img width="258" alt="Screenshot 2020-04-02 at 15 45 20" src="https://user-images.githubusercontent.com/841956/78257910-c42ab280-74fa-11ea-8c05-97f82f685958.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
CC @ndev1991

**Comment by jauyong** [comment]
Related #232

**Comment by swissspidy** [comment]
Might be fixed now with #998, but needs verification.

**Comment by miina** [comment]
@swissspidy Is this Done and just needs QA? Or what kind of verification is needed?

**Comment by swissspidy** [comment]
Yeah this is fixed
