### ISSUE TITLE
Improve error feedback when a link is invalid

### ISSUE THREAD

**Issue by obetomuniz** [GoogleForCreators/web-stories-wp#983]
## Feature Description

As requested in https://github.com/google/web-stories-wp/issues/806#issuecomment-607738635 by @spacedmonkey, some UX work is needed in the error feedback when a link is invalid

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by samitron7** [comment]
Display an error message below the input field. Can we make sure to to show the metadata fields (ie description and brand icon) if a valid url is not supplied.

[Figma flow](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=9407%3A16711)

Removing UX Needed label

**Comment by swissspidy** [comment]
I'm consolidating this with #1966, as I ended up implementing this error messaging in the associated PR #2254.
