### ISSUE TITLE
Video not playing from media panel when first entered the new story

### ISSUE THREAD

**Issue by ndev1991** [GoogleForCreators/web-stories-wp#985]
## Bug Description

When user first entered new stories editor and move pointer straight to the video element on medial panel, the video not playing. Instead there is console error.

## Expected Behaviour

Video element should be playing when mouse over on video element.

## Steps to Reproduce

- Click new story or refresh from editor.
- Don't click anywhere and move straight to the video element.

## Screenshots

![Screen Shot 2020-04-02 at 11 11 24 AM](https://user-images.githubusercontent.com/40171223/78265979-28d21700-74d3-11ea-9f34-279446473864.png)

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
- Video should be playing when hover on video element on media panel

**Comment by dvoytenko** [comment]
Is this still the case if the video is set to muted? Can we put together a minimal repro case in jsbin or codepen? There might be a way to work it around with `autoplay`.

**Comment by barklund** [comment]
Fixed by #1015
