### ISSUE TITLE
Improve test coverage for text element output

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#989]
## Feature Description

Text elements should get better coverage for their output, especially in regards for AMP validation. Would help prevent things like #988 for text elements with highlight background fill.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
Pea pod will take this on

**Comment by o-fernandez** [comment]
I hate to do this, but we'll have to push this to post stable.
