### ISSUE TITLE
URL exceeds link preview

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#990]
## Bug Description

The link URL overflows the link preview's container

## Expected Behaviour

The URL should probably be truncated

## Steps to Reproduce

Insert text element and add long URL as link

## Screenshots

<img width="286" alt="Screenshot 2020-04-02 at 20 40 59" src="https://user-images.githubusercontent.com/841956/78289351-54c8b900-7522-11ea-9b70-2ac035ea963c.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by ezxyz** [comment]
I wasn't sure how to reproduce this. This is the steps I took:
1) Create a new text element
2) Edit link (using the right side bar) and add a really long link
3) The link appears on the editor truncated.

4) I click save and preview
5) The link also appears in preview truncated.

**Comment by swissspidy** [comment]
Thanks for testing, and sorry for the troubles! Looks like this was fixed by #1152 in the meantime. Closing.
