### ISSUE TITLE
Background Media not shown in Page Preview

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#999]
## Bug Description

Instead of the background media I see a transparent background

## Expected Behaviour

Background media should show in preview.

Video should be static.

## Steps to Reproduce

1. Add background media to page
1. Notice missing media in preview (carousel / grid view)

## Screenshots

Check the previews at the bottom:

<img width="530" alt="Screenshot 2020-04-03 at 10 28 49" src="https://user-images.githubusercontent.com/841956/78340209-f9d0a980-7595-11ea-9e83-387f7d595eef.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Might be related to / caused by #1001.

**Comment by merapi** [comment]
I believe it was fixed in https://github.com/google/web-stories-wp/pull/1037 @swissspidy
